- e2e_tests/tests/fixtures/no_op/single.yaml
- webui/react/src/ioTypes.ts
- i created a noop experiment with https://github.com/determined-ai/determined/pull/1757/commits/87b0edae4c1fd7bc3cb6deca0340ef3c3a698914 config  and that reproduced the reported error. this PR then fixed it.
> fix: add boolean to accepted hparam types [DET-4727]

- docs/release-notes/1758-fix-okta-signin.txt
- webui/react/src/hooks/useAuthCheck.ts
Because the user verification doesn't check for an auth token in a cookie, Okta sign in flow fails.
Update the `useAuthCheck` hook to check for a token within a cookie and using that token if available.
> fix: check for a cookie token and verify auth with it [DET-4732]

- webui/react/package-lock.json
`make live` complains and delays startup everytime
> chore: update caniuse dev package

- agent/internal/fluent.go
Instead of only displaying a generic "Fluent Bit exited" message when
that happens, we now retrieve and display more information on the exit
status of the container.
There's also a `.Get()` added to previous code, without which the `Ask` doesn't actually block as the comment suggests it should.
I added this due to seeing Fluent Bit exiting on a [failed test run](https://app.circleci.com/pipelines/github/determined-ai/determined/8612/workflows/ab5f3941-fb54-4574-ae95-e62e8da66a44/jobs/235605/steps), though I don't think it was the cause of the overall failure (Fluent Bit exiting shouldn't have any effect on trial status).
> chore: show more information if Fluent Bit exits

- webui/react/src/hooks/useAuthCheck.ts
Previously there was a timing issue of when the apikey with the Bearer token was being updated. The token was not set in time for user verification.
> fix: use cookie token from sso if applicable

- common/determined_common/storage/s3.py
I am not sure when this broke (or how it ever worked actually), but this is a workaround for https://github.com/boto/botocore/pull/1328 (I think) that causes our system to fail when using MinIO as an s3 provider.
The workaround is to detect when MinIO is in use (via HTTP headers) and simply avoid uploading empty directories.  The only reason that the S3 StorageManager uploaded empty directories anyway was to imitate the behavior of the S3 console, which is not a very big deal.
Tested manually.  I could be convinced to add a unit test if we were willing to add `minio` as a dependency of our tests.
> fix: workaround boto3+minio bug [DET-4748]

- docs/release-notes/1763-fix-hparam-parsing.txt
- webui/react/src/fixtures/hyperparameter-configs.json
- webui/react/src/fixtures/responses/experiment-details/set-a.json
- webui/react/src/ioTypes.ts
- webui/react/src/services/decoder.test.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
hyperparameter values can be any valid yaml types https://docs.determined.ai/latest/reference/experiment-config.html#hyperparameters
added tests.
revert the fix commit and run the test to see the failure. 
> fix: relax type expectations for hparam values [DET-4742 DET-4744]

- docs/reference/cli.txt
- docs/reference/command-notebook-config.txt
This generalizes the configuration reference so that it also covers shells and commands more explicitly. It also creates a link in the CLI reference to this config reference for easier access.
> docs: update task configurations [DET-4731]

- webui/tests/specs/01-setup.spec
- webui/tests/specs/02-experiments.spec
- webui/tests/specs/02-responsive.spec
- webui/tests/specs/02-tasks.spec
- webui/tests/specs/03-cleanup.spec
- webui/tests/tests/StepImplementation.ts
Fix some flaky issues found in the taiko tests
- fix experiment setup via experiment list table to be less flaky where it attempts to perform an action on an experiment where that action is not available
- closing newly opened tabs for tensorboards and notebooks can sometimes cause the main tab to be closed
- some UI elements are in a collapsed form when in a smaller viewport, requiring additional clicks
> refactor: update tests to be more reliable

- webui/tests/package-lock.json
- webui/tests/package.json
- webui/tests/tests/StepImplementation.ts
resolve the two webui related security alerts
running `npm ci` followed by `npm audit` in both `webui/tests` and `webui/cypress` should not report the `ini` package security issue
> chore: resolve security packages [DET-4733]

- webui/react/src/components/ResponsiveTable.tsx
> fix: webui responsive table showing unneeded horizontal scrollbar [DET-4710]

- agent/go.sum
- agent/internal/fluent_intg_test.go
- master/internal/elastic/elastic_intg_testutils.go
- master/internal/elastic/elastic_trial_logs.go
- master/pkg/fluent/fluent.go
It's debatable whether we should PUT this template when we start the master in normal operation; we should have this debate at the next trial logs sync and for now i renamed the index `determined-triallogs-*` so it's more reasonable for us to be putting indexes matching it.
> chore: put index template in integrations to avoid precision related race

- webui/tests/specs/02-master-logs.spec
- webui/tests/tests/StepImplementation.ts
> test: add master logs test [DET-4684]

- docs/release-notes/1767-improve-webui-style.txt
- webui/react/src/App.module.scss
- webui/react/src/components/Navigation.module.scss
- webui/react/src/components/Page.module.scss
- webui/react/src/components/Page.tsx
- webui/react/src/components/PageHeader.module.scss
- webui/react/src/components/PageHeader.tsx
- webui/react/src/components/Section.module.scss
- webui/react/src/hooks/useResize.ts
- webui/react/src/pages/Dashboard.module.scss
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/ExperimentDetailPage.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.module.scss
- webui/react/src/pages/TaskLogs.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/styles/antd.scss
- webui/react/src/themes.ts
Minor style cleanup
- Remove page back button (adds to confusion of up vs back behavior, can use breadcrumb nav above page title for a more predictable direction)
- Added a slight background tint to bring out the interactive elements more.
- Added secondary and background color to themes for easier theming in the future.
> style: update WebUI style

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
**NOTE:** requires [this PR](https://github.com/determined-ai/determined/pull/1753) to land first!
- verify metric column exists
- check to make sure changing metric of interest will update the column
- verify the column sorting works
> feat: add learning curve metric column [DET-4735]

- webui/tests/tests/StepImplementation.ts
Flakes are occurring when new tabs are opening and closing in quick successions. Add slight delay before and after closing tabs.
> ci: reduce webui e2e-tests flakes [DET-4973]

- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/types.ts
There is confusion around when signing in as an admin to not be able to see every user's experiments and tasks. Update user filter to default to `All` when the signed in user is an admin.
> refactor: update default user filters to All when user is an admin [DET-4726]

- docs/release-notes.txt
- docs/release-notes/1758-fix-okta-signin.txt
- docs/release-notes/1763-fix-hparam-parsing.txt
- docs/release-notes/1772-fix-workload-durations.txt
> docs: release notes for 0.13.12

- master/internal/resourcemanagers/agent_resource_manager.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/resourcepool.proto
- proto/src/determined/resourcepool/v1/resourcepool.proto
PR #1724 isn't passing CI after being merged to master. This is presumably due to new CI steps and a Go version change after that PR was opened. This PR fixes those issues. (1) apply autoformatter to code. (2) correct int -> string conversion bug that is flagged by new Go version.
> fix: CI failing due to PR #1724

- master/internal/resourcemanagers/agent_resource_manager.go
Change API response to return an empty string instead of the 'N/A' placeholder string.
> chore: change ResourcePool API response from N/A to empty string

- docs/release-notes.txt
Per report from mullerrwd (#1804).
> chore: fix typos in release notes

- deploy/determined_deploy/aws/aws.py
- docs/how-to/installation/aws.txt
Add the documentation for `det-deploy aws list`. Fix a bug that might cause `det-deploy aws up` to launch stacks without tags.
Use the e2e test suite.
N/A
> docs: det-deploy aws list

- master/internal/api_trials.go
- master/pkg/model/experiment.go
- proto/src/determined/api/v1/trial.proto
> chore: return more fields from trial log APIs [DET-4825]

- webui/react/src/components/LogViewer.module.scss
- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/pages/TrialLogs/TrialLogFilters.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
> chore: webui support elastic search trial logs [DET-4616]

- README.md
This is a temporary promotion of our lunch and learn that will be removed on 1/27/21
> docs: Add Lunch and Learn promotion to README.md

- webui/react/src/ioTypes.ts
- webui/react/src/types.ts
Trial log levels have a wider list of level types now. Update webui to handle them. Temporarily forking the definition until Master Logs and Task Logs are updated to use the same convention. Then we will re-unify them under just `LogLevel`
> fix: update types to support new log levels [DET-4834]

- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/values.yaml
- master/pkg/fluent/fluent.go
- master/pkg/model/logging_config.go
- tools/master.yaml
The configuration had a typo for `HTTP_User` and `HTTP_Passwd` shown here https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch. The docs used type where backend was the actual key, which was confusing.
> chore: various elastic fixes [DET-4839]

- webui/react/src/components/Link.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
`Download Model` button interaction is not triggering the download interaction when working with a cloud deployment. The click event is breaking and not triggering the appropriate response. Instead, allow for the download button to be a pure raw link (without any React specific interaction) to enable a pure http download with the correct download headers.
> fix: update model def button to be a raw link [DET-4833]

- webui/react/src/components/LearningCurveChart.module.scss
- webui/react/src/components/LearningCurveChart.tsx
Show zoom out tip (double click) when zoomed into learning curve uPlot chart.
- Check to make sure zooming in to the chart shows the zoom out tip "double click to reset zoom"
> fix: show zoom out tip when zoomed into learning curve chart [DET-4836]

- examples/hp_search_benchmarks/darts_penntreebank_pytorch/model_def.py
Fix the dars_penntreebank_pytorch example
Manually tested with the const.yaml and adaptive.yaml
N/A
> fix: dars_penntreebank_pytorch example [DET-4841]

- webui/react/src/services/apiConfig.ts
Upon getting a new auth token, we re-create our apis with the new auth token. We are missing the refresh for the internal streaming api sdk.
> fix: add missing apiKey update to internal streaming sdk [DET-4842]

- master/internal/elastic/elastic_trial_logs.go
- master/test/integration/api/api_trials_test.go
This change fixes duplicates in elastic IDs caused by a loop closure bug. See: https://play.golang.org/p/uT95L_SBEJ0 for a minimal explanation of what the issue was and how it is fixed. 
> chore: fix duplicate elastic ids [DET-4851]

- agent/go.sum
- agent/internal/fluent.go
- docs/topic-guides/cluster-configuration/elasticsearch-logging-backend.txt
- master/pkg/model/experiment.go
This change updates the `model.TrialLog` model a bit to optimize the json tags for what gets indexed in elastic.
This model probably needs to get broken into two, one for postgres and another for elastic but I _kinda_ want to hit release with this, before anyone uses elastic and has logs indexed this way.
Index template to go with this PR.
```
{
"index_patterns": ["determined-triallogs*"],
"mappings": {
"properties": {
// This will make duplicates appear because of the interaction between
// Determined internally using the search_after API and date_nanos. To
// be addressed.
// "timestamp": {
//     "type": "date_nanos"
// },
"agent_id": {
"type": "keyword",
"index": true
},
"container_id": {
"type": "keyword",
"index": true
},
"level": {
"type": "keyword",
"index": true
},
"log": { …
```
> perf: index as few log fields as possible to increase elasticsearch ingest speed

- webui/tests/package-lock.json
- webui/tests/package.json
> chore: bump taiko-video version to fix video generation race condition

- webui/react/src/App.tsx
- webui/react/src/components/Navigation.tsx
- webui/react/src/components/NavigationTabbar.tsx
- webui/react/src/contexts/ClusterOverview.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/HGICluster.tsx
- webui/react/src/types.ts
- update overview calculation
- add CPU slots widget
- make slot utilization widgets conditional
> chore: update cluster utilization overview [DET-4346]

- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/pages/TrialLogs.tsx
> fix: webui trial logs should not use negative offset

- common/determined_common/api/experiment.py
This change stops the CLI from making requests with limit+offset that cause deep pagination in Elasticsearch.
> fix: fix CLI log tailing with elastic and deep pagination [DET-4883]

- common/determined_common/api/experiment.py
> fix: don't set trial logs default limit

- webui/react/src/components/ResourcePoolDetails.tsx
- webui/react/src/types.ts
- avoid showing null fields from resourcepool details response
- show the full top level section
> chore: improve more info modal for resource pools [DET-4884]

- e2e_tests/tests/conftest.py
When debugging, it can be annoying to figure out which cluster logs
corresponded to a given test; printing the start time of each test
should help with that.
The output might look a little abrupt in isolation, but it joins onto the end of the line printed by pytest itself so you get things like `tests/test_users.py::test_link_with_existing_agent_user starting at 2021-01-25 17:51:05`, which I think works out pretty well.
> test: print start time for each E2E test

- docs/release-notes/1827-fix-learning-curve-edge-cases.txt
- webui/react/src/fixtures/responses/experiment-details/set-a.json
- webui/react/src/ioTypes.ts
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/task.ts
Better handle all the different edge cases for HP-viz page.
In progress experiment that does not have any data to plot yet:
Terminal experiment (errored, killed, canceled) experiments that do not have any data to show:
Single trial or PBT experiments alert message (we do not support HP-viz for those two types):
> fix: handle learning curve edge cases [DET-4832]

- webui/api-ts-sdk/Makefile
> build: avoid re-downloading codegen binary [DET-4853]

- deploy/determined_deploy/aws/cli.py
- docs/how-to/installation/aws.txt
Manually tested deployment with and without profile
> chore: expose det-deploy AWS profile support [DET-4891]

- deploy/determined_deploy/gcp/cli.py
- docs/how-to/installation/gcp.txt
- docs/reference/cluster-config.txt
> docs: clarify preemptible instance doc for static and dynamic agents

- cli/determined_cli/agent.py
- cli/determined_cli/cli.py
- cli/determined_cli/command.py
- cli/determined_cli/experiment.py
- cli/determined_cli/notebook.py
- cli/determined_cli/tensorboard.py
- e2e_tests/tests/test_users.py
Add resource pool to CLI output
- Manually tested
- LIST Agents
- LIST commands
- DESCRIBE experiment
- LIST experiment
- LIST notebook
- LIST shell
- LIST slot
- LIST task
- LIST tensorboard
> chore: update CLI commands to display resource pool [DET-4677]

- harness/determined/keras/_tf_keras_trial.py
Running distributed training on TF 1.15 in eager execution mode resulted in an AttributeError as the attribute currently being used is only available in TF 2.0 and higher. This changes the function call such that it is also compatible with version 1.15.
Manually tested
> fix: altered tf.config function call to be compatible with TF 1.15 [DET-4852]

- helm/charts/determined/templates/master-config.yaml
- master/cmd/determined-master/root.go
- master/cmd/determined-master/root_test.go
- master/internal/resourcemanagers/config.go
- master/pkg/check/check_string.go
Fix the Kubernetes configuration resolution.
Use the CI.
N/A
> ci: fix kubernetes configuration resolution [DET-4909]

- .circleci/scripts/upload_cloud_watch_to_s3.py
Increase the retrying times and waiting time for concurrent log uploading.
Use the CI.
N/A
> ci: tolerate longer time for concurrent log uploading [DET-4908]

- master/pkg/model/experiment.go
This change makes request ID in `model.Trial` nullable, since it may not exist for older trials and is only used where it is sure to exist with new trials.
> fix: allow NULL trials.request_id for backwards compat

- agent/internal/docker.go
Very short-lived command containers can exit and be autoremoved by
Docker before the agent starts tracking their logs, causing the logs to
be lost. This changes containers that don't have their logs shipped
to Fluent Bit to be explicitly removed by the agent rather than
autoremoved so that we can be sure to get the logs.
This used to lead to a visible error but has lately been completely
silent due to a typo in error checking (also fixed here).
There's now a risk of a container being left lying around after exiting
if the agent is hard-killed. An alternative would be to add a brief
sleep to every command to mostly ensure that the agent has a chance to
start reading logs; that's maybe cleaner in a sense, but I decided it
was sillier overall.
It would be great if Docker allowed you to start …
> fix: don't lose logs of short-lived commands [DET-4907]

- webui/react/src/pages/Cluster.tsx
> fix: render resource pools in order

- docs/how-to/installation/aws.txt
- docs/topic-guides/system-concepts/resource-pool.txt
- master/packaging/master.yaml
Improve resource pool docs to clarify how to configure and use resource pools.
> docs: improve resource pool docs

- docs/reference/command-notebook-config.txt
- docs/topic-guides/commands-and-shells.txt
- docs/topic-guides/system-concepts/terminology-concepts.txt
- docs/tutorials/quick-start.txt
As requested by a community user.
> docs: add topic guide for commands and shells [DET-4901]

- webui/react/src/pages/Cluster.tsx
> feat: show resource pools without connected agents [DET-4924]

- webui/react/src/pages/Cluster.tsx
> feat: save user preference for cluster view [DET-4926]

- webui/react/src/components/ResourcePoolCard.tsx
- webui/react/src/pages/Cluster.table.tsx
- webui/react/src/pages/Cluster.tsx
- webui/tests/specs/02-cluster.spec
- webui/tests/tests/StepImplementation.ts
> chore: reword resource pool ui presentation [DET-4925]

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/release-notes/1851-framework-upgrades.txt
- e2e_tests/tests/config.py
- e2e_tests/tests/requirements.txt
- examples/gan/dcgan_tf_keras/const.yaml
- examples/gan/dcgan_tf_keras/distributed.yaml
- harness/setup.py
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp_config.go
- master/pkg/model/defaults.go
- tools/scripts/bumpenvs.yaml
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/experiment-details/set-a.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
Duplicate of https://github.com/determined-ai/determined/pull/1904, which I sent to the wrong branch
> chore: Bump images and versions to Tensorflow 2.4.1

- master/internal/api_trials.go
- master/static/srv/proto_get_trial_ids_for_experiment.sql
- proto/src/determined/api/v1/trial.proto
This change corrects the behavior of the best validation and latest validation sort by params in `/api/v1/experiments/$ID/trials` to reflect the intended behavior.
I have less than half a brain.
> fix: fix best and latest metric sort bys for `/api/v1/experiments/$ID/trials`

- proto/src/determined/api/v1/experiment.proto
- webui/react/src/contexts/ActiveExperiments.tsx
- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/types.ts
Update the `getExperiments` call to match the new pagination behavior from the backend. Provide the `limit` param of `0` to explicitly tell the API to return just the pagination info. The `experiments` field will be empty to avoid an expensive scan of the experiments table.
- Ensure that the `# Active Experiments` on the dashboard shows and matches the number of active experiments running.
> refactor: update active experiments [DET-4915]

- webui/react/src/components/ResourcePoolCard.stories.tsx
- webui/react/src/components/ResourcePoolCard.tsx
- webui/react/src/components/SlotAllocationBar.stories.tsx
- webui/react/src/components/SlotAllocationBar.tsx
- webui/react/src/pages/Cluster.tsx
- webui/react/src/utils/cluster.ts
- added stories for failing cases.
> fix: fix a utilization calculation error in hgi resource bar for cpu slots [DET-4913]

- docs/how-to/installation/deploy.txt
> docs: fix incorrect reference in docs

- docs/release-notes/1922-fix-cancel-confirm-button-label.txt
- webui/react/src/pages/ExperimentList.tsx
Before:
After:
Note: The table batch action will remain as `Cancel` but the confirmation button in the modal will be labeled as `Confirm`.
> fix: correct cancel confirm button label to confirm [DET-4966]

- docs/release-notes/1892-fix-experiment-trials-sorting.txt
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentOverview.table.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentOverview.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
- webui/react/src/services/utils.ts
- webui/react/src/types.ts
- Upgrade experiment details page to use pagination for experiment trials endpoint.
- Remove using experiment trials data to figure out whether we allow or disallow viewing in tensorboard. (since we will not have the full list of trials to be able to determine this)
Check to make sure experiment detail page trials load properly, can paginate through and sort the various columns.
> refactor: paginate experiment trials [DET-4900, DET-4921, DET-4922]

- docs/release-notes/1924-fix-numeric-sorter.txt
- webui/react/src/utils/data.test.ts
- webui/react/src/utils/data.ts
number comparison function is failing when the numbers being compared are fractions
> fix: correct the comparison function when numbers are fractions [DET-4969]

- webui/react/src/pages/TrialDetails.tsx
> fix: remove clickable style from trial info table [DET-4967]

- webui/react/src/components/ResourcePoolDetails.module.scss
- webui/react/src/components/ResourcePoolDetails.stories.tsx
- webui/react/src/components/ResourcePoolDetails.tsx
- webui/react/src/fixtures/responses/resource-pools/a.json
- webui/react/src/services/apiConfig.ts
- mock API response. (revert the corresponding commit)
- added a story
> chore: improve resource pool details presentation [DET-4968]

- webui/react/src/components/LogViewer.tsx
- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/components/ResourcePoolCard.stories.tsx
- webui/react/src/components/ResourcePoolDetails.stories.tsx
- webui/react/src/index.tsx
- webui/react/src/pages/MasterLogs.tsx
- webui/react/src/pages/TaskLogs.tsx
- webui/react/src/prototypes.ts
- webui/react/src/react-app-env.d.ts
- webui/react/src/services/decoder.test.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/task.ts
Add support of 3 common array prototypes:
- first() - return the first item in the array
- last() - return the last item in the array
- random() - return a random item in the array
> refactor: array prototype [DET-4976]

- proto/src/determined/api/v1/tensorboard.proto
- proto/src/determined/command/v1/command.proto
- proto/src/determined/container/v1/container.proto
- proto/src/determined/notebook/v1/notebook.proto
- proto/src/determined/shell/v1/shell.proto
- proto/src/determined/tensorboard/v1/tensorboard.proto
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/contexts/Commands.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails/TrialActions.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
- webui/react/src/types.ts
- webui/react/src/utils/types.ts
This has been tested by manually triggering experiments and the 4 kind of tasks and observing the 2 pages which displays tasks (dashboard and tasks).
> chore: migrate webui tasks api endpoint [DET-4018]

- webui/react/src/components/HumanReadableFloat.tsx
- webui/react/src/pages/TrialDetails.tsx
- show zero value metrics (currently treated as empty)
- fix handling of negative numbers (treated as decimals always currently)
- avoid showing integers as decimal or scientific notations
Before:
After:
> fix: show zero value metrics [DET-4686]

- webui/react/src/ioTypes.ts
> chore: remove remaining unused step iotypes

- webui/react/src/components/ResourcePoolCard.stories.tsx
- webui/react/src/services/api.ts
> test: fix resourcepoolcard story not rendering [DET-4964]

- .circleci/config.yml
Maybe we can turn on 3rd party orbs for this - it's the most recent recommended solution to this https://discuss.circleci.com/t/sequentially-running-workflows/23288/2.
> ci: limit concurrent deploys from master

- docs/Makefile
add a make target to allow manual updates of docs
> build: separate out docs pre-publish step [DET-4982]

- webui/react/src/components/ResourcePoolCard.tsx
We've gone back and forth on how to convey this information in a sentence. The idea here is that `x/y connected` implies that we have agents running that are not connected.
> chore: remove max agents count in resource pool card's header

- proto/src/determined/api/v1/notebook.proto
- webui/react/src/ioTypes.ts
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
- webui/react/src/utils/task.ts
I tested this by triggering "launch notebook" and "launch cpu-only notebook".
> chore: migrate webui launch notebook api [DET-4821]

- README.md
- docs/index.txt
> chore: remove lunch-and-learn notice, tweak docs

- master/pkg/schemas/schema_gen.go
- schemas/expconf/v0/test-root.json
- schemas/expconf/v0/test-sub.json
- schemas/expconf/v0/test-union-a.json
- schemas/expconf/v0/test-union-b.json
Minimal effort to avoid causing issues to other devs before #1957 lands.
> chore: commit make -C schemas fmt

- master/internal/grpcutil/errors.go
> fix: add missing comment on exported function

- docs/how-to/installation/deploy.txt
> docs: add DGX instructions for determined-deploy

- common/.gitignore
- common/Makefile
- common/determined_common/schemas/expconf/_gen.py
It was a mistake to think these did not need to be generated.
> chore: commit generated python schemas

- examples/nlp/albert_squad_pytorch/README.md
- examples/nlp/bert_squad_pytorch/README.md
> chore: fix squad example README links

- helm/charts/determined/templates/master-deployment.yaml
> fix: helm chart template dashes

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
Manually tested secure deployment
> fix: fix quoted string bugs for non-simple AWS deployments [DET-5001]

- proto/src/determined/command/v1/command.proto
- proto/src/determined/notebook/v1/notebook.proto
- proto/src/determined/shell/v1/shell.proto
- proto/src/determined/tensorboard/v1/tensorboard.proto
- webui/react/src/services/decoder.ts
- have n gpu slots in the cluster and launch n+1 1 slot notebooks
- kill all notebooks and make sure all show up as terminated
> fix: fix notebook state stuck in pending [DET-4988]

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
There are some major changes coming to parallel coordinates hp-viz. Holding on releasing parcoords to the public until the changes land.
- Check to make sure HP Parallel Coordinates is inaccessible from the Experiment Visualization tab.
> chore: remove parcoords temporarily [DET-5002]

- harness/determined/__init__.py
- harness/determined/_execution.py
- harness/determined/_train_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/exec/harness.py
- harness/determined/exec/worker_process.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/layers/_workload_manager.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/util.py
- master/pkg/searcher/asha.go
Enable the harness to catch `det.InvalidHP` exceptions raised in user code, and propagate that information to the searcher. Note: this is a user-facing API change, thought not a breaking change.
In any `model_def.py` raise a `det.InvalidHP("msg")` in either `__init__`, `train_batch`, or `evaluate_batch` for PyTorch models. For Keras and Estimator models, raise in either `__init__` or in a callback with validation metrics. Ensure the trial stops training, and that an InvalidHP is raised (should be apparent in the trial logs).
> feat: HP constraints harness exception handling [DET-4867]

- webui/react/src/components/LearningCurveChart.tsx
- webui/react/src/components/ParallelCoordinates.module.scss
- webui/react/src/components/ParallelCoordinates.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
- webui/react/src/utils/chart.ts
- webui/react/src/utils/color.test.ts
- webui/react/src/utils/color.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/string.ts
Tasks
- add filtered table to PC plot
- show all trials and then filter based off window
- make column order reset to default order (unable to lock or prevent the columns from being re-ordered)
- fiddle with the labels to make them stand out but without taking even more space (angle them to 45)
- truncate the hp label to 20 characters for long labels
- limit the hp to 10
- add tips on how to filter on parallel coordinates
Thought process on color scale gradients
- avoid red/green due to it being the most common color blindness
- use blue/red color scale for searcher metric, for when we do know if a metric is good or bad within a range. The color gradient is reversed when `smallerIsBetter` is true.
- use blue/orange color scale for non-searcher metric to avoid using red, which generally …
> chore: tune parcoords [DET-4991]

- docs/release-notes/1994-enable-parcoords.txt
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
Previously temporarily disabled navigation to hp-parcoords chart. Re-enable the navigation to make parcoords publically available.
> feat: enable parcoords in webui [DET-5013]

- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/components/LogViewer.store.ts
- webui/react/src/components/LogViewerLevel.tsx
- webui/react/src/components/LogViewerStore.ts
- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/hooks/useGetCharMeasureInContainer.ts
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/routes/utils.ts
- webui/react/src/utils/dom.test.ts
- webui/react/src/utils/dom.ts
This is still a WIP because there's an issue in the follow=true API that I prefer to check before this get's merged.
> chore: refactor trial log viewer to improve rendering performance [DET-4866]

- webui/react/README.md
- webui/react/package-lock.json
- webui/react/package.json
- use the instruction to point `make live` dev server to a remote cluster
> build: add instructions to point webui to cors disabled clusters

- docs/release-notes/1991-keras-validation-end.txt
- harness/determined/keras/_tf_keras_trial.py
Imitate keras more exactly.
Tested with user-provided repro example.
> fix: call Sequence.on_epoch_end after validation [DET-5007]

- docs/how-to/use-trained-models.txt
> docs: fix missing parens in a few checkpoint API code snippets

- .circleci/config.yml
updates the default server address set for the react preview build to a cors proxy served over https
- have no running determined clusters on your machine and visit `build-react-preview` artifact from circle-ci on this pr and preview the UI changes
> chore: update cluster address for react preview [DET-5008]

- master/internal/restore.go
This change fixes the shim to not explode stuff that isn't PBT.
Eh.. I definitely tested with asha, I'm not sure what happened. I'll test it all again.
> fix: fix v0 experiment snapshot shim

- docs/how-to/installation/kubernetes.txt
> docs: add link for enabling Kubernetes GPU support

- docs/release-notes/2003-fix-batch-order.txt
- webui/react/src/components/LabelSelectFilter.tsx
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/TagList.tsx
- webui/react/src/pages/Cluster.table.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx
- webui/react/src/pages/TaskList.table.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails.table.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/prototypes.test.ts
- webui/react/src/prototypes.ts
- webui/react/src/react-app-env.d.ts
- webui/react/src/services/decoder.test.ts
- webui/react/src/setupTests.ts
- webui/react/src/utils/chart.ts
- webui/react/src/utils/data.test.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/sort.test.ts
- webui/react/src/utils/sort.ts
- webui/react/src/utils/trial.ts
Batches column on the trial info table is not sorting purely as numbers but as alpha-numeric order. Correct it to use a numeric sorter.
> fix: correct batches column order on trial detail page [DET-5023]

- docs/examples.txt
- docs/release-notes/4392-hp-search-constraints.txt
- docs/topic-guides/hp-constraints-det.txt
- docs/topic-guides/hp-tuning-defined.txt
- docs/topic-guides/hp-tuning-det/index.txt
- docs/topic-guides/index.txt
- examples/README.md
- examples/features/hp_constraints_mnist_pytorch/README.md
- examples/features/hp_constraints_mnist_pytorch/adaptive.yaml
- examples/features/hp_constraints_mnist_pytorch/data.py
- examples/features/hp_constraints_mnist_pytorch/layers.py
- examples/features/hp_constraints_mnist_pytorch/model_def.py
Add topic guide for HP Search Constraints to Determined docs and create an example. Incorporated quick fix for main examples README page linking `custom_reducers_mnist_pytorch`.
Ensure all links work correctly and are visible.
> feat: HP Search Constraints Documentation [DET-4392, DET-4993]

- examples/hp_search_benchmarks/darts_cifar10_pytorch/README.md
- examples/hp_search_benchmarks/darts_cifar10_pytorch/const.yaml
- examples/hp_search_benchmarks/darts_cifar10_pytorch/constrained_adaptive.yaml
- examples/hp_search_benchmarks/darts_cifar10_pytorch/constrained_random.yaml
- examples/hp_search_benchmarks/darts_cifar10_pytorch/model_def.py
- examples/hp_search_benchmarks/darts_cifar10_pytorch/startup-hook.sh
Add HP constraints to DARTS CIFAR-10 search space to further boost accuracy of the best found architecture.  
> feat: NAS example with HP constraints [DET-5084]

- webui/react/Makefile
- `make clean && make`
- stop get-deps half way and `make`
> fix: remove react extra get-deps dependency

- webui/react/src/components/Navigation.module.scss
- webui/react/src/components/Navigation.tsx
- webui/react/src/components/Toggle.tsx
- webui/react/src/pages/ExperimentList.tsx
> chore: make experiment list page url sharable [DET-4745]

- webui/react/src/App.tsx
- webui/react/src/ErrorHandler.ts
- webui/react/src/components/ActionSheet.stories.tsx
- webui/react/src/components/Breadcrumb.stories.tsx
- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/components/CreateExperimentModal.tsx
- webui/react/src/components/DeterminedAuth.tsx
- webui/react/src/components/Navigation.tsx
- webui/react/src/components/NavigationTabbar.tsx
- webui/react/src/components/NavigationTopbar.tsx
- webui/react/src/components/Router.tsx
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/SignOut.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TaskLogs.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialActions.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/routes/utils.ts
> chore: webui uniform path generation [DET-4734]

- webui/react/src/pages/Wait.tsx
> fix: navigation disappearing when going back from wait page [DET-5020]

- CONTRIBUTING.md
Update the helm version in controbuting.md
> chore: update contributing.md with helm

- docs/reference/cluster-config.txt
- master/internal/config_test.go
- master/internal/provisioner/config.go
- master/internal/provisioner/config_test.go
Add a default value to agent docker image.
N/A
> docs: add default agent docker image

- master/internal/restore.go
- master/pkg/searcher/adaptive.go
- master/pkg/searcher/adaptive_asha.go
- master/pkg/searcher/adaptive_simple.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/grid.go
- master/pkg/searcher/pbt.go
- master/pkg/searcher/random.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/sha.go
- master/pkg/searcher/tournament.go
- master/pkg/searcher/tournament_test.go
> fix: fix shim for stateless searchers (grid, single, etc..)

- webui/react/src/pages/ExperimentDetails/ExperimentOverview.tsx
- webui/react/src/pages/ExperimentList.tsx
With the recent change to using a more generic version of Experiment list endpoint, we need to detect additional changes to the dependencies for the api (sorters, pagination, filters, etc) and make another API call instead of waiting for the polling to kick in to make the UI feel more responsive. The experiment list is updated to reflect this, the experiment trials table requires this fix as well.
> fix: update experiment trials endpoint when changing filters or sorting

- examples/computer_vision/deformabledetr_coco_pytorch/const_fake.yaml
- examples/computer_vision/deformabledetr_coco_pytorch/distributed.yaml
- examples/computer_vision/deformabledetr_coco_pytorch/finetune.yaml
- examples/computer_vision/deformabledetr_coco_pytorch/finetune_adaptive.yaml
Fix e2e tests by adding missing device field to all experiment configs.  
> fix: bug in deformable detr experiment config

- tools/scripts/update-bumpenvs-yaml.py
This includes the once-reverted fix by @mackrorysd and a new fix for aws gov images.
> chore: support new tags and gov images in bumpenvs

- webui/react/src/hooks/usePolling.ts
- webui/react/src/pages/TrialDetails.tsx
- Open any experiment detail page.
- Fork the experiment.
- Confirm that redirection to the newly forked experiment page occurs with the right states and experiment actions.
- Cancel or Kill experiment.
- Confirm that the polling stops on the Network tab for the experiment.
> fix: correct polling issues [DET-5095]

- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
1. The 2 `useEffect` will watch `experiment.archived` and `experiment.state` and reset the related button when either has (really) changed. By default all loading state will already be `false`, but triggering one of the 6 action will set the individual state to `true`. It will get back to `false` when the `experiment.archived` and `experiment.state` get changed.
2. The loading state for Tensorboard has been removed. I'm not sure if Tensorboard has a state and if that can/should be tracked. Btw my guess (maybe wrong) is that this is not needed (Tensorboard is opened in another window).
> fix: webui experiment detail action spinner to persist until state changes [DET-4977]

- webui/react/src/fixtures/hyperparameter-configs.json
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
- webui/react/src/services/decoder.ts
categorical hyperparameters are not coming through in experiment config. fix decoder to properly decode categorical hps.
> fix: decode categorical config hp properly [DET-5098]

- webui/react/src/components/LogViewerTimestamp.tsx
> fix: trial log viewer disappearing when re-clicking direction button [DET-5097]

- harness/determined/exec/worker_process.py
> fix: nas dtrain bug

- webui/react/src/components/LogViewer.module.scss
- webui/react/src/components/LogViewerTimestamp.tsx
> fix: trial log viewer scrolling issues [DET-5096]

- harness/determined/pytorch/README.md
- harness/determined/pytorch/_pytorch_context.py
Write down tribal knowledge for a key element of our system in order to properly review PyTorch-native AMP support (#1914)
> chore: add PyTorchTrial devloper's guide

- docs/release-notes.txt
- docs/release-notes/1817-deformable-detr.txt
- docs/release-notes/1979-k8s-cluster-page.txt
- docs/release-notes/1990-restructure-table-row-links
- docs/release-notes/1991-keras-validation-end.txt
- docs/release-notes/1994-enable-parcoords.txt
- docs/release-notes/2003-fix-batch-order.txt
- docs/release-notes/2007-scatter-plot-heat-map.txt
- docs/release-notes/2022-fix-parcoords-filters.txt
- docs/release-notes/4392-hp-search-constraints.txt
> docs: Release notes for 0.14.3.

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/govcloud.py
- deploy/determined_deploy/aws/templates/govcloud.yaml
- tools/scripts/README.md
> feat: add aws govcloud support for det-deploy

- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
> fix: webui best checkpoint modal not opening in trial details page [DET-5108]

- docs/how-to/install-main.txt
- docs/how-to/installation/deploy.txt
- docs/how-to/installation/upgrades-troubleshoot.txt
- docs/reference/cluster-config.txt
- docs/reference/experiment-config.txt
- docs/topic-guides/checkpoints.txt
- docs/topic-guides/system-concepts/scheduling.txt
> docs: improve docs for scheduling behavior, other fixes

- harness/determined/pytorch/_pytorch_context.py
> fix: fix pytorch optimization aggregation frequency check

- webui/react/src/components/ProgressBar.tsx
> chore: reduce progress bar label precision.

- docs/faq.txt
- docs/how-to/installation/aws.txt
- docs/how-to/installation/deploy.txt
- docs/reference/experiment-config.txt
- docs/topic-guides/model-definitions/index.txt
- docs/topic-guides/model-definitions/trial-api.txt
- docs/topic-guides/system-concepts/scheduling.txt
> docs: minor improvements

- webui/react/src/components/LogViewerTimestamp.tsx
Cause of this were re-creating the `LogViewerRow` on each re-render. Solved by memoizing it (and a couple more items).
> fix: weird text selection behavior in trial logs [DET-5080]

- master/pkg/schemas/gen.sh
Fix build issue on some platforms as /bin/sh is more common than /usr/bin/sh.
> fix: shebang path for schemas generator.

- common/determined_common/check.py
- examples/features/hp_constraints_mnist_pytorch/adaptive.yaml
- harness/determined/_execution.py
- harness/determined/layers/_worker_process.py
Fix a bug with InvalidHP dtrain.
> fix: invalidhp dtrain bug

- common/determined_common/api/authentication.py
- common/determined_common/api/request.py
- docs/release-notes/2082-fix-notebook-auth.txt
Fix the notebook not authorized.
Manually start a notebook and run `det user whoami`
N/A
> fix: notebook not authorized [DET-5129]

- docs/topic-guides/system-concepts/scheduling.txt
- helm/charts/determined/templates/NOTES.txt
- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/templates/priority_classes.yaml
- helm/charts/determined/templates/scheduler-config.yaml
- helm/charts/determined/templates/scheduler-deployment.yaml
- helm/charts/determined/templates/scheduler-permissions.yaml
- helm/charts/determined/values.yaml
- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pod_test.go
- master/internal/kubernetes/pods.go
- master/internal/kubernetes/spec.go
- master/internal/resourcemanagers/resource_manager_config.go
- master/internal/resourcemanagers/setup.go
- master/pkg/tasks/task_spec.go
Implements the coscheduling plugin that enables priority based gang-scheduling in kubernetes
Start a cluster with the `defaultScheduler` value set as "coscheduler". Saturate the cluster with experiments and continue submitting experiments to make sure deadlocking does not occur. Also monitor master logs to make sure GC jobs run properly.
> feat: priority-based gang-scheduling for k8s

- helm/charts/determined/templates/priority_classes.yaml
- helm/charts/determined/templates/scheduler-config.yaml
- helm/charts/determined/templates/scheduler-deployment.yaml
- helm/charts/determined/templates/scheduler-permissions.yaml
> fix: helm chart errors in absence of defaultScheduler value

- harness/determined/exec/gc_checkpoints.py
- harness/determined/load/_load_trial_controller.py
- harness/determined/tensorboard/__init__.py
- harness/determined/tensorboard/base.py
- harness/determined/tensorboard/build.py
- harness/determined/tensorboard/gcs.py
- harness/determined/tensorboard/hdfs.py
- harness/determined/tensorboard/s3.py
- harness/determined/tensorboard/shared.py
- harness/tests/tensorboard/test_base.py
- harness/tests/tensorboard/test_s3.py
- harness/tests/test_workload_manager.py
- master/internal/api_experiment.go
- master/internal/checkpoint_gc.go
- master/pkg/tasks/task_spec.go
This change adds code to GC Tensorboards when DELETE experiment is run. It is piggybacked as a new flag onto the checkpoint GC script.
Looking for a bit of feedback on whether the interface is OK.. I usually don't touch this harness stuff.
> feat: delete Tensorboards with delete API [DET-5143]

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/gcp/gcp.py
- deploy/determined_deploy/local/cluster_utils.py
- deploy/setup.py
- credentials check for aws / cloudformation
- credentials check for gcp / terraform
- have local cluster creation fail on docker-compose failures
> feat: provide user hint on aws, gcp auth in det-deploy [DET-4846]

- docs/release-notes.txt
- docs/release-notes/2057-add-batch-margins.txt
> docs: Release notes for 0.14.5.

- docs/topic-guides/deployment/determined-on-kubernetes.txt
- docs/topic-guides/system-concepts/scheduling.txt
> docs: improve docs on k8s coscheduling plugin.

- examples/computer_vision/mnist_pl/README.md
- examples/gan/gan_mnist_pl/README.md
- examples/gan/gan_mnist_pl/model_def.py
> chore: add readmes to pl examples [DET-5149]

- .circleci/config.yml
- docs/examples.txt
- docs/reference/api/index.txt
- docs/reference/api/lightning_adapter.txt
- docs/requirements.txt
- harness/determined/pytorch/lightning/_adapter.py
- a preview (potentially out of date)
https://299910-253846879-gh.circle-artifacts.com/0/docs/site/html/reference/api/lightning_adapter.html
> docs: add pytorch lightning adapter docs [DET-4800]

- docs/examples.txt
- docs/how-to/installation/kubernetes.txt
- docs/reference/helm-config.txt
> fix: broken doc links [DET-5100]

- docs/how-to/installation/kubernetes.txt
- docs/reference/helm-config.txt
- docs/topic-guides/deployment/determined-on-kubernetes.txt
- docs/topic-guides/system-concepts/scheduling.txt
- helm/charts/determined/Chart.yaml
improve the documentation around the k8s coscheduler and bump the helm chart version.
> docs: further improve k8s coscheduling docs

- helm/Makefile
> fix: release helm chart

- agent/Makefile
- master/Makefile
> fix: master and agent release target

- .circleci/config.yml
- agent/Makefile
- master/Makefile
> fix: go mod tidy for releases

- deploy/determined_deploy/aws/deployment_types/base.py
- deploy/determined_deploy/aws/deployment_types/govcloud.py
- deploy/determined_deploy/aws/deployment_types/secure.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/deployment_types/vpc.py
> feat: colorize output info of det-deploy aws [DET-4749]

- cli/determined_cli/cli.py
- cli/determined_cli/resources.py
- docs/release-notes/2107-resources.txt
Exactly what it says on the tin.
> feat: expose resource allocation endpoints in CLI [DET-5045]

- .circleci/config.yml
- docs/requirements.txt
PTL is now required to build the docs.
> chore: add pytorch-lightning to docs requirements

- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/styles/index.scss
> chore: add server address to cli trial log download cmd [DET-5161]

- .circleci/config.yml
- webui/Makefile
> chore: add webui tests lint step to CI

- docs/release-notes/2086-hp-importance.txt
- proto/src/determined/api/v1/experiment.proto
- webui/react/src/components/HpSelectFilter.module.scss
- webui/react/src/components/HpSelectFilter.tsx
- webui/react/src/components/HumanReadableFloat.tsx
- webui/react/src/components/LabelSelectFilter.tsx
- webui/react/src/components/LogViewer.tsx
- webui/react/src/components/MultiSelect.tsx
- webui/react/src/components/Page.tsx
- webui/react/src/components/ResponsiveTable.tsx
- webui/react/src/components/Section.module.scss
- webui/react/src/components/Section.tsx
- webui/react/src/components/SelectFilter.tsx
- webui/react/src/pages/Cluster.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentOverview.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/ExperimentVisualizationFilters.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/styles/antd.scss
- webui/react/src/types.ts
- webui/react/src/utils/sort.ts
Opportunistically rank the available hparams with hp importance if available.
HP picker without hp importance:
HP picker with hp importance:
run the following experiment:
```
det e create ./e2e_tests/tests/fixtures/mnist_pytorch/random.yaml ./examples/tutorials/mnist_pytorch
```
When the hp importance is available the HP picker shows the hp importance value next to each hparam and orders the hp by the importance value. Otherwise it doesn't show the value and shows the hps alphabetically.
the response for hp importance:
```
{
"result": {
"trainingMetrics": {
"loss": {
"hpImportance": {
"dropout1": 1.1933941110928465e-18,
"dropout2": 2.0018029756745813e-26,
"learning_rate": 7.802653352931384e-30,
"n_filters1": 0.4068482249453416,
"n_filters2": 0.4735429929594936
},
"experimentProgress": 1, …
```
> feat: rank hparams with hp importance [DET-5105]

- docs/release-notes/2126-categorical-scatter-plots.txt
- webui/react/src/components/ScatterPlot.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
Add support for showing categorical hyperparameters for HP scatter plots and HP heatmaps.
categorical hp on x-axis:
categorical hp on y-axis:
categorical hp on both x-axis and y-axis:
string-based categorical hp (previous ones were boolean based)
Some notable experiments with categorical hps:
- /det/experiments/1373/visualization/hp-heat-map
- /det/experiments/1289/visualization/hp-heat-map
- /det/experiments/1255/visualization/hp-heat-map
> fix: update scatter plot to support non-numeric values [DET-5110]

- requirements.txt
> fix: package install order in requirements.txt

- .circleci/config.yml
- e2e_tests/tests/requirements.txt
- examples/tests/requirements.txt
- harness/setup.py
> build: downgrade pytorch

- webui/react/src/components/LogViewer.module.scss
- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/components/Page.tsx
- webui/react/src/components/PageHeader.tsx
- webui/react/src/components/Section.module.scss
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/ExperimentVisualizationFilters.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/ExperimentVisualizationFilters.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialLogs/TrialLogFilters.module.scss
- webui/react/src/pages/TrialLogs/TrialLogFilters.tsx
- webui/react/src/styles/antd.scss
Move trial log filters into Section component filters attribute.
> style: trial log section filters [DET-5176]

- webui/tests/package-lock.json
- webui/tests/package.json
- webui/tests/specs/01-setup.spec
- webui/tests/specs/02-responsive.spec
- webui/tests/tests/StepImplementation.ts
Upgrade taiko to their latest release to reduce test flakiness and resolve `highlight.js` security dependency.
> chore: upgrade taiko [DET-5157]

- examples/computer_vision/mnist_pl/mnist.py
> fix: pytorch lightning example

- e2e_tests/tests/experiment/test_pytorch_lightning.py
- e2e_tests/tests/fixtures/pytorch_lightning_amp/apex_amp.yaml
- e2e_tests/tests/fixtures/pytorch_lightning_amp/auto_amp.yaml
> fix: e2e GPU tests for pytorch lightning examples

- .circleci/config.yml
- README.md
- cli/setup.py
- deploy/setup.py
- docs/how-to/installation/aws.txt
- docs/how-to/installation/deploy.txt
- docs/how-to/installation/gcp.txt
- docs/index.txt
- harness/setup.py
> fix: roll back `det` and `det-deploy` executable move.

- master/Makefile
- tools/Makefile
- fixes regression missed in rollback #2153 
> fix: get cli wheel back into trail runner.

- docs/reference/experiment-config.txt
- master/pkg/model/defaults.go
- master/pkg/model/experiment_config.go
- master/pkg/model/experiment_config_test.go
This change wires up the profiling configurations in the master. The exact configurations added are described by the observability ERD.
> chore: wire up profiling configurations [DET-5064]

- examples/features/checkpoint_hooks_pytorch/README.md
- examples/features/checkpoint_hooks_pytorch/const.yaml
- examples/features/checkpoint_hooks_pytorch/data.py
- examples/features/checkpoint_hooks_pytorch/layers.py
- examples/features/checkpoint_hooks_pytorch/model_def.py
> chore: add an example for checkpoint callbacks [DET-5186]

- harness/tests/experiment/fixtures/lightning_adapter_onevar_model.py
> chore: tweak steplr param

- agent/Makefile
- cli/Makefile
- common/Makefile
- docs/Makefile
- harness/Makefile
- helm/Makefile
- master/Makefile
Rearrange simple Makefiles and set `DEFAULT_GOAL` in complex one so that the default make goal is to build.
> chore: `make` default goal should be `build`.

- master/internal/experiment.go
- master/internal/grpcutil/auth.go
- master/internal/restore.go
- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/pkg/model/length.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/asha_stopping.go
- master/pkg/searcher/grid.go
- master/pkg/searcher/pbt.go
- master/pkg/searcher/random.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/searcher.go
- master/pkg/searcher/sha.go
- master/pkg/searcher/simulate.go
- master/pkg/searcher/tournament.go
This change alters the way in which trials notify the experiments of their progress to be idempotent, which helps to make the experiment's handling of progress stateless (eventually on a crash, progress will recover without being restored), makes the API easier to use if/when it is exposed publicly, and simplifies progress logic a bit.
> chore: idempotent searcher progress API [DET-5211]

- .bumpversion.cfg
- harness/determined/deploy/aws/templates/efs.yaml
- harness/determined/deploy/aws/templates/fsx.yaml
- harness/determined/deploy/aws/templates/govcloud.yaml
- requirements.txt
- start using bumpversion globbing to avoid such issues moving forward.
- Versions are updated after `bumpversion minor --no-commit --no-tag`
> fix: add efs, fsx, and govcloud templates to bumpversion [DET-5200]

- CODEOWNERS
> chore: remove self from codeowners

- webui/react/package.json
- webui/react/src/App.tsx
- webui/react/src/components/GalleryModal.tsx
- webui/react/src/hooks/useKeyTracker.ts
Provide the ability for the WebUI to capture key events at the App level. Implement a publish/subscribe design so any component at any level can listening in on the key events to provide keyboard interactivity.
Implement one example: Listen for left and right arrow key to navigate through the modal gallery.
> feat: add key tracker

- harness/determined/profiler.py
Mostly renames and applying feedback from previous PR. 
> harness metric collection improvements

- harness/determined/profiler.py
> Add code to shut down profiler based on timeout

- webui/react/src/ioTypes.ts
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/Profiles/ProfilesNotEnabled.tsx
- webui/react/src/pages/TrialDetails/Profiles/SystemMetric.tsx
- webui/react/src/pages/TrialDetails/Profiles/SystemMetricChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/SystemMetricFilter.tsx
- webui/react/src/pages/TrialDetails/Profiles/TimingMetricChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/utils.ts
- webui/react/src/pages/TrialDetails/TrialDetailsProfiles.tsx
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/number.test.ts
- webui/react/src/utils/number.ts
> chore: show trial metrics on webui [DET-5060]

- webui/react/src/pages/ExperimentList.tsx
Experiment list re-renders every time we poll even if no data has changed. Do a quick simple dirty check to avoid this behavior.
> chore: avoid unnecessary re-rendering of experiment list

- docs/how-to/installation/custom-pod-specs.txt
Added a short blurb clarifying the behavior of custom pod specs.
> docs: clarify k8s default pod spec behavior

- .circleci/config.yml
- README.md
- cli/setup.py
- deploy/setup.py
- docs/faq.txt
- docs/how-to/install-cli.txt
- docs/how-to/installation/aws.txt
- docs/how-to/installation/deploy.txt
- docs/how-to/installation/gcp.txt
- docs/how-to/installation/upgrades-troubleshoot.txt
- docs/index.txt
- docs/release-notes/2187-executable-move.txt
- harness/setup.py
- helm/charts/determined/templates/NOTES.txt
- master/Makefile
- tools/Makefile
- reapply some work from #2108 that was reverted in #2153 and #2156.
- add more docs.
> feat: move executables to the main package and update docs.

- .circleci/config.yml
This change bumps from 1 to 2 dynamic agents allowed on latest master.
> chore: bump to 2 agents on latest master [DET-5241]

- e2e_tests/tests/experiment/test_tf_keras.py
- e2e_tests/tests/fixtures/keras_tf2_disabled_no_op/const.yaml
- e2e_tests/tests/fixtures/keras_tf2_disabled_no_op/model_def.py
- harness/determined/_tf_rng.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
> fix: TFKerasTrial on tf2 with tf.compat.v1.disable_v2_behavior.

- webui/react/src/pages/Cluster/ClusterOverview.tsx
Fix the issue of cluster page not having a Grid/List view selected (neither are selected).
The core issue is that the enum value has changed from numeric to string, and if the user has a numeric value saved previously, neither will get selected.
> chore: validate grid list enum value from local storage [DET-5187]

- docs/how-to/custom-env.txt
> docs: Update custom environment example

- webui/react/src/components/Navigation.tsx
- webui/react/src/pages/Cluster/ClusterOverview.tsx
Problem: Agent API fetch is happening in the navigation component even when the user is signed out.
Solution: Check to make sure the user is authenticated before making the agent fetch.
> fix: fetch agents only when authenticated [DET-5259]

- docs/how-to/custom-env.txt
- docs/how-to/installation/gcp.txt
- harness/determined/deploy/gcp/cli.py
- harness/determined/deploy/gcp/preflight.py
- fix issue around quota checks with preemptible flag.
- add quota codes for A100.
- add a docs section for A100 on GCP.
> fix: gcp quota checks, A100 and docs.

- .circleci/config.yml
- harness/determined/deploy/aws/constants.py
- harness/determined/deploy/aws/deployment_types/base.py
- harness/determined/deploy/aws/templates/efs.yaml
- harness/determined/deploy/aws/templates/fsx.yaml
- harness/determined/deploy/aws/templates/govcloud.yaml
- harness/determined/deploy/aws/templates/simple.yaml
- harness/determined/deploy/aws/templates/vpc.yaml
- Add an ability to health check clusters with enabled `--master-tls-cert`.
- Remove redundant circleci check for aws clusters.
- Also see #2192, #2164.
> feat: support healthchecks for `det deploy aws` with TLS enabled.

- master/internal/experiment.go
- master/internal/hpimportance/hpimportance.go
Only send `hpimportance.ExperimentCompleted` messages when the experiment is completed.
Could also check the progress on the receiving side is greater than some threshold or 100% but shouldn't rely on that IMO/I'm not sure exactly what that would be.
> chore: fix panics in hp importance actor [DET-5263]

- harness/determined/common/schemas/expconf/_v0.py
- master/pkg/schemas/expconf/environment_config.go
- master/pkg/schemas/expconf/zgen_environment_config_v0.go
- schemas/test_cases/v0/experiment.yaml
Totally forgot to do this in the last PR.
> fix: actually support add/drop capabilities in structs

- master/internal/db/postgres_snapshots.go
This change fixes an incorrect SQL query that caused experiment shims to run on incorrect experiment snapshot versions.
ugh.
> fix: select snapshot version with snapshot [DET-5264]

- master/internal/core.go
- master/internal/experiment.go
This change fixes a bug where restored experiments would attempt to send an `ExperimentCreated` message to the hp importance actor prior to its creation, resulting in a panic from a send on a nil actor.
> chore: fix panic from dependency creation race [DET-5271]

- master/internal/hpimportance/manager.go
This change fixes an actor message that was sent incorrectly to an actor that didn't handle that message.
Probably will take a second pass at this later.
> chore: submit partial hp importance work to pool

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
transpose the hp heatmap matrix of scatter plots to better align the x and y axes.
> style: transpose hp heatmap to better align the plot axes

- harness/determined/keras/_tf_keras_trial.py
- Checking if `tensorflow.compat.v1.disable_tf2_behavior` was called was different in tf 2.2. Use the "current" way by default and fallback to the old one otherwise.
> fix: `TFKerasTrial` check for tf2 behavior on 2.2.0 [DET-5277]

- master/internal/experiment.go
- master/pkg/searcher/searcher.go
Exactly what it says on the tin.
I really don't think this should make a difference, but I don't have a lot of time to look and we can expend no effort to see if it works.
> chore: don't check searcher shutdown to trigger work hp importance work

- e2e_tests/tests/experiment/test_pytorch_lightning.py
https://app.circleci.com/pipelines/github/determined-ai/determined?branch=update-amp-test-cuda-images
prompted following this failures https://app.circleci.com/pipelines/github/determined-ai/determined/11131/workflows/af4d890b-4548-4da9-8331-14071a17eab3/jobs/317746
> chore: update env image for amp e2e test

- .circleci/config.yml
- docs/release-notes.txt
> docs: Release notes for 0.15.1

- docs/topic-guides/deployment/aws-spot.txt
> docs: missing service-linked role [DET-5253]

- master/internal/api_experiment.go
- master/internal/experiment.go
- master/internal/restore.go
- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/internal/trial_workload_sequencer_test.go
- master/pkg/searcher/adaptive_asha_test.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/asha_stopping.go
- master/pkg/searcher/asha_stopping_test.go
- master/pkg/searcher/asha_test.go
- master/pkg/searcher/grid.go
- master/pkg/searcher/grid_test.go
- master/pkg/searcher/operations.go
- master/pkg/searcher/pbt.go
- master/pkg/searcher/pbt_test.go
- master/pkg/searcher/random.go
- master/pkg/searcher/random_test.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/searcher.go
- master/pkg/searcher/simulate.go
- master/pkg/searcher/tournament.go
- master/pkg/searcher/tournament_test.go
- master/pkg/searcher/util_test.go
This change alters the searcher to only emit a single runnable operation, "ValidateAfter". It also cleans up the trial <-> experiment interface to match and use what the coming sprinkle API's searcher API will look like.
There is some more simplification that could fall out of this, but I think this PR is plenty big/complex as is.
> chore: remove validation operations [DET-5213]

- master/internal/api_auth.go
- proto/src/determined/api/v1/auth.proto
- add a param to /api/v1/auth/login to allow passing presalted and hashed password
- if the username is not provided respond with an invalid argument instead of invalid credentials.
> chore: add option to login through the new api w/ pre-hashed pwd [DET-5270]

- webui/react/src/components/DeterminedAuth.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/SignIn.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
- webui/react/src/types.ts
followup to #2253  
- check cookies still get set and websocket connections are authenticated fine.
> chore: migrate to use the new login api [DET-5287]

- docs/release-notes/2261-fix-agents-update.txt
- webui/react/src/contexts/Store.tsx
Fix the issue of agents overview not updating when agents went from positive number to none.
> fix: allow agents to be set to empty [DET-5296]

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
Update to avoid requiring hp-importance to resolve before showing hp-viz page.
> fix: ignore hp-importance as a requirement for displaying hp-viz [DET-5294]

- webui/tests/tests/StepImplementation.ts
Turn on `getElements` log to see why flakes occur around this. Unable to replicate this flake both locally or on CI via PR. Take the next step enabling logging so we'll be able to see what's happening when the flake occurs.
Primarily for DET-5192
> ci: enable taiko get elements logs

- harness/determined/cli/experiment.py
> chore: fix typo in help for "experiment download".

- docs/how-to/installation/docker.txt
> docs: add missing line to docker run

- docs/reference/api/estimator.txt
- docs/reference/api/pytorch.txt
- docs/release-notes/2284-promotions.txt
- e2e_tests/tests/fixtures/estimator_dataset/model.py
- e2e_tests/tests/fixtures/estimator_no_op/model_def.py
- examples/computer_vision/deformabledetr_coco_pytorch/model_def.py
- examples/computer_vision/detr_coco_pytorch/model_def.py
- examples/features/custom_reducers_mnist_pytorch/model_def.py
- harness/determined/estimator/__init__.py
- harness/determined/estimator/_estimator_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/estimator/_reducer.py
- harness/determined/pytorch/__init__.py
- harness/determined/pytorch/_experimental.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/pytorch/_reducer.py
- harness/determined/util.py
- harness/tests/experiment/fixtures/estimator_linear_model.py
- harness/tests/experiment/fixtures/pytorch_onevar_model.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
Promote pytorch custom reducers which have been well-received by users.
Promote estimator custom reducers which have been around for a while with nobody complaining.
I have manually tested backwards compatibility.
> feat: promote custom reducers from experimental [DET-5322] [DET-5321]

- webui/react/src/components/UPlotChart.tsx
- webui/react/src/components/UPlotChart/tooltipsPlugin.ts
While reworking `<LearningCurveChart>` I discovered a couple issues on the <UPlotChart> component.
Preferred to split this in a dedicated MR that can land before the release gets cut.
> fix: wait for uPlot to be ready to setData or setSize [DET-5343]

- webui/react/src/components/UPlotChart.tsx
> fix: correct logic for hasData in uPlotChart

- docs/release-notes/2282-k8s-preemption.txt
Add a release note for the preemptive coscheduler.
> docs: add release notes for preemption in k8s

- agent/Makefile
- master/Makefile
This is not enormously useful, because of how our actor system
works. But it still might have some value when debugging concurrency
issues or interactions with external libraries.
> chore: add support for building with Golang race detector

- harness/determined/common/schemas/extensions.py
- master/pkg/schemas/defaults.go
- master/pkg/schemas/expconf/experiment_config.go
- master/pkg/schemas/expconf/zgen_internal_config_v0.go
- master/pkg/schemas/expconf/zgen_kerberos_config_v0.go
- master/pkg/schemas/expconf/zgen_security_config_v0.go
- master/pkg/schemas/merge.go
- schemas/gen.py
Fix issues found while writing expconf presentation.
> chore: minor expconf issues

- proto/src/determined/experiment/v1/experiment.proto
When an experiment is created it only has start_time, and end_time is not set. The experiment stays in 'Pause' state before it is activated. Swagger generates an exception on the response as the Experiment requires end_time not to be 'None'.
Getting a list of experiments also generates this exception if some experiments are in active/pause state.
> chore: remove end_time as required from json-schema

- docs/reference/command-notebook-config.txt
> docs: remove stray text from task config reference

- master/internal/trial.go
> chore: log incorrect rendezvous addresses

- master/pkg/agent/master_message.go
- master/pkg/container/address.go
… "
This reverts commit 6c686929540ae99e008401c97b42a3a9afcb2be7.
> revert: "fix: gracefully handle Docker binding published ports to ipv4 and ipv6 for host (#2259) [DET-5295]

- webui/README.md
Found a missing word while looking through the README, so I'm suggesting a fix. There isn't a Jira ticket for this change.
This is a single word change in documentation only, so no testing is needed.
> docs: fix missing word in readme

- master/pkg/agent/master_message.go
- master/pkg/container/address.go
… "
This reverts commit 953f528906af9d6de185aa5bb0ce15ab8d547dd6.
> revert: "revert: "fix: gracefully handle Docker binding published ports to ipv4 and ipv6 for host (#2259) [DET-5295]" (#2326)"

- examples/computer_vision/deformabledetr_coco_pytorch/data_utils.py
- examples/computer_vision/deformabledetr_coco_pytorch/model_def.py
- examples/computer_vision/detr_coco_pytorch/data_utils.py
- examples/computer_vision/detr_coco_pytorch/model_def.py
Going to run these on some multi-gpu nodes to make sure they work.
> chore: use filelocks to guard data download

- .circleci/config.yml
- agent/Makefile
- master/Makefile
This change updates the `get-deps` target for Go subprojects to not run `go mod download`. `go mod download` isn't strictly necessary (see https://golang.org/ref/mod#go-mod-download) and seems to be less aware than `go mod tidy`/`go mod why`. For example, when `go mod download` is run, dependencies of the tools listed in the `tools.go` file have lined added in the `go.sum` for files within the modules `.zip` file (see https://golang.org/ref/mod#go-sum-files), but when `go mod tidy` is run, presumably because the main module at the top of the `go.mod` does not depend on these files directly, these lines are removed (I checked, this is the case too for anything in the `go.mod` that isn't actually used). Since `go mod download` isn't strictly necessary and doesn't seem to play nice with our …
> chore: go mod fixes

- master/static/srv/proto_get_trial_ids_for_experiment.sql
This change updates the GET experiment trials API to sort trials with total_batches_processed = 0 correctly.
> chore: sort nulls last in experiment trial API

- webui/react/src/pages/TrialDetails/Profiles/SystemMetricChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/utils.ts
Fixing this chart as per uPlot documentation instructions: https://github.com/leeoniya/uPlot/tree/master/docs#data-format
> fix: system metric chart fix to support milliseconds [DET-5348]

- webui/react/public/index.html
> chore: add viewport meta to improve WebUI mobile experience [DET-5396]

- docs/release-notes.txt
- docs/release-notes/2304-fix-env-images.txt
- docs/release-notes/2319-fix-websockets.txt
> docs: Release notes for 0.15.3

- master/static/srv/get_experiment.sql
- master/static/srv/get_experiments.sql
- proto/src/determined/experiment/v1/experiment.proto
Include the searcher type as part of the experiment LIST and experiment GET APIs.
@hamidzr Should I make `searcher_type` a required field for the API? 
> chore: add searcher type to output of experiment APIs

- webui/react/src/components/UPlotChart.tsx
> fix: improve uPlot chart zooming experience [DET-5395]

- webui/react/src/components/ArchiveSelectFilter.stories.tsx
- webui/react/src/components/ArchiveSelectFilter.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/types.ts
- webui/tests/tests/StepImplementation.ts
Replaced "Show Archived" toggle in the experiments list with a dropdown [DET-3925]
Before:
After:
[DET-3925]: https://determinedai.atlassian.net/browse/DET-3925
> feat: add ArchiveSelectFilter replacing toggle for seeing archived experiments [DET-3925]

- webui/react/src/components/ArchiveSelectFilter.tsx
- webui/tests/specs/02-experiments.spec
disable the broken test to give us time to fix it
> chore: disable webui experiment archive test.

- harness/determined/gpu.py
These statistics are not available when running on a partition of GPU (NVIDIA MIG) unless you're running with more privileges. They do not appear to be critical, so we just apply sensible defaults to avoid divide-by-zero, etc. and log a warning.
Tested on a cluster with MIG devices: was able to provision 7 slots for every actual GPU, and run distributed training successfully.
> feat: tolerate missing GPU stats when running under MIG [DET-5387]

- webui/tests/tests/StepImplementation.ts
When getting a list of elements based on a selector, each element is tracked using the text content of the element (taiko `text()`). The issue arises when the content of the element changes when asynchronously fetching the element text. For example, in task cards, the recent time info can change within each second, which causes taiko to count the card twice because the previous time might be `2s ago` followed by `3s ago`.
Update the `getElements` routine to take in another optional selector that allows the test to pinpoint exactly what it wants to use for the hash id. If nothing is provided, it defaults to the current behavior of using all of the text found within the element.
[DET-1234]: …
> fix: reduce test flakes around task cards [DET-5192]

- webui/react/Makefile
> fix: react build should depend on the public dir

- .gitignore
- docs/Makefile
- docs/examples.txt
- docs/index.txt
- docs/model-hub/index.txt
- docs/model-hub/transformers/api.txt
- docs/model-hub/transformers/examples.txt
- docs/model-hub/transformers/index.txt
- docs/model-hub/transformers/tutorial.txt
- docs/reference/api/pytorch.txt
- docs/requirements.txt
- model_hub/Makefile
- model_hub/model_hub/huggingface/_config_parser.py
- model_hub/model_hub/huggingface/_trial.py
- requirements.txt
> docs: add documentation for model-hub [DET-5031]

- master/internal/api_experiment.go
- master/internal/core_experiment.go
- master/internal/db/postgres.go
- master/pkg/model/experiment.go
- master/static/migrations/20210504130449_add-exp-original-config.down.sql
- master/static/migrations/20210504130449_add-exp-original-config.up.sql
keep a record of the exact user submitted config (prior to applying defaults or any shimming)
create an experiment with det cli and check the database
`select original_config, config, id from experiments;`
> feat: store the original user submitted experiment config in db

- e2e_tests/tests/test_users.py
The tests seem to be fine without this change. But technically you should always call `read` before calling `wait` on a process otherwise it would block forever. `wait()` might be a blocking call if your CLI prints out an empty line, which happens on my MacOS.
> test: always calling read() before calling wait()

- .circleci/config.yml
- e2e_tests/tests/model_hub/test_transformers.py
Split out model-hub nightly tests so the distributed tests won't time out.
> fix: ci/cd e2e tests timeout

- .circleci/config.yml
Fix bug in circle ci config for model-hub nightly tests.
> fix: ci/cd model-hub tests config

- webui/react/src/utils/chart.test.ts
- webui/react/src/utils/task.test.ts
Added tests for functions in the chart.ts and task.ts webui util files.
These new tests passed locally and should continue to pass.
> chore: add unit tests for webui util functions [DET-5323]

- webui/react/src/pages/TrialDetails/Profiles/SystemMetricChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/TimingMetricChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/utils.ts
WebUI was expecting all data points (where with data point I mean the values included in a batch or a timestamp returned by the API) to specify a value for all the metrics.
That's not happening (eg. batch 1 might have 3 metric values, batch 2 might have 1 metric value).
Added a fix to default to `0` when a value is not specified.
Note that we could use `null` too (difference between `0` and `null` is that uPlot will interpret `null` as a missing value and, depending on the chart config, display a gap between points).
> fix: profiles timings graph data conversion filling empty data [DET-5433]

- webui/react/src/pages/TaskList.tsx
> fix: fix task pagination filters not taking effect [DET-5442]

- docs/release-notes.txt
- docs/release-notes/2068-model-hub-transformers.txt
- docs/release-notes/2321-delete-old-command-api.txt
- docs/release-notes/2345-drop-prior-batches-and-num-batches-trials.txt
> docs: Release notes for 0.15.4.

- .bumpversion.cfg
Follow-up for #2366. The line being removed is covered by the line 25 glob.
Running `bumpversion minor --no-commit --no-tag` should bump `model_hub/model_hub/__version__.py`.
> chore: remove redundant model_hub line from bumpversion.

- Makefile
Considering that we have a separate package step for master and agent
- building master wouldn't depend and wait on WebUI or doc builds to pass or finish
- we can spin up the master (for dev) sooner after kicking off rebuilding everything
- donwsides? make build-master would pass even if make build-docs fails
> build: remove webui and docs as direct master dependencies

- docs/release-notes/2364-webui-move-trial-hyperparams.txt
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
This is a simple change needed to be able to remove the overview info box in the next MRs related to the trial detail page.
In the next weeks we will work on a better visualization for those.
BEFORE:
AFTER:
> chore: move trial hyperparameters in a dedicated trial page tab [DET-5412]

- docs/model-hub/index.txt
- docs/model-hub/transformers/index.txt
> docs: fix spelling mistakes in model hub

- master/internal/api_tensorboard.go
- master/internal/command/tensorboard_manager.go
> chore: simplify tensorboard request msg

- docs/release-notes/2390-widen-trial-links.txt
- webui/react/src/pages/ExperimentDetails/ExperimentOverview.tsx
Add `Trial` prefix to the trial links on the experiment detail page.
Before::
After:
> chore: widen the trial link on experiment detail page [DET-5459]

- webui/tests/specs/02-experiments.spec
> ci: temporarily remove flaky tests

- harness/determined/common/schemas/expconf/_gen.py
- master/pkg/schemas/zgen_schemas.go
- schemas/expconf/v0/environment.json
- schemas/test_cases/v0/unions.yaml
Tested manually and added test case.
> fix: wire up support for plain-string image config

- docs/release-notes.txt
- docs/release-notes/deprecate-old-master-config.txt
> docs: Release notes for 0.15.5.

- webui/react/src/pages/ExperimentList.tsx
> fix: correct the url search param setting for archived [DET-5481]

- harness/determined/cli/experiment.py
If the config has a key name "labels" and the value is
None det e describe would fail.
> fix: fix det e describe on parsing old experiment labels [DET-5487]

- harness/determined/common/experimental/determined.py
Update doc strings for create_experiment
> docs: update create_experiment

- docs/how-to/custom-env.txt
Fixes a simple typo in the docs
N/A
> docs: fixed typo in custom custom docker configuration

- docs/topic-guides/system-concepts/resource-pool.txt
Fix a typo. Make 'Tensorboard' consistent with our UI. Replace incorrect use of the term 'zone' with correct term, 'region'.
Replacement PR for #2017 
> docs: resource pool fixes

- docs/release-notes/2320-webui-tqdm-rendering.txt
- webui/react/src/components/LogViewerTimestamp.tsx
In the WebUI, guess if the logs contain a TQDM line and skip rendering that line if so.
> fix: improve tqdm rendering in the web ui

- master/internal/api_trials.go
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/TrialDetails/Profiles/ProfilesNotEnabled.tsx
> chore: terminate /api/v1/trials/:id/avialable_series on trial termination [DET-5499]

- webui/react/src/styles/antd.scss
> chore: thead style update

- harness/determined/cli/shell.py
- master/pkg/tasks/task.go
- switch tasks to use `/bin/bash` as a default shell for non-root users.
we already use `/bin/bash` for root users, and this is required for
VSCode remote access to work properly.
- use `det shell show_ssh_command` or `--show-ssh-command` option for
`start` and `open` to print underlying ssh command.
- based on https://github.com/hoanghphan/determined/tree/ide-integration
- requires #2401 to work on recent local docker.
> feat: `det shell` option to show ssh command for use in IDE [DET-5462]

- docs/release-notes/2428-ide-integration.txt
- docs/topic-guides/commands-and-shells.txt
Add documentation for practical use-cases behind #2407 .
> docs: using `det shell` as a remote shell in IDEs.

- webui/react/src/pages/TrialDetails/Profiles/SystemMetricFilter.tsx
> fix: observability webui widen dropdowns so the entire string is readable [DET-5503]

- webui/react/.eslintrc.js
- webui/react/src/ErrorHandler.ts
- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/ResourcePoolCard.tsx
- webui/react/src/components/ResourcePoolDetails.tsx
- webui/react/src/components/Table.tsx
- webui/react/src/components/TableFilterDropdown.tsx
- webui/react/src/components/TagList.tsx
- webui/react/src/components/TaskCard.tsx
- webui/react/src/contexts/Store.tsx
- webui/react/src/hooks/useRestApi.ts
- webui/react/src/pages/Cluster/ClusterHistoricalUsageCsvModal.tsx
- webui/react/src/pages/Cluster/ClusterHistoricalUsageFilters.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/TrialDetails/Profiles/ProfilesNotEnabled.tsx
- webui/react/src/pages/TrialDetails/Profiles/SystemMetricFilter.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/themes.ts
- webui/react/src/utils/chart.test.ts
- webui/react/src/utils/string.ts
Add more auto-fixable linting rules to produce more consistent code:
- [arrow-spacing](https://eslint.org/docs/rules/arrow-spacing#require-space-beforeafter-arrow-functions-arrow-arrow-spacing)
- [comma-spacing](https://eslint.org/docs/rules/comma-spacing)
- [jsx-quotes](https://eslint.org/docs/rules/jsx-quotes)
- [key-spacing](https://eslint.org/docs/rules/key-spacing)
- [space-in-parens](https://eslint.org/docs/rules/space-in-parens)
> chore: more eslint rules [DET-5513]

- webui/react/src/App.tsx
- webui/react/src/omnibar/tree-extension/index.ts
- webui/react/src/omnibar/tree-extension/trees/dev.ts
> fix: correct lint issues

- webui/react/package-lock.json
- webui/react/src/omnibar/tree-extension/index.ts
> chore: reduce minimum chars to fuzzy match for omnibar

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/TrialDetails/Profiles/ProfilesNotEnabled.tsx
> chore: minor copy fix for alert box spaces

- harness/Makefile
Prevents `harness/determined/_swagger` from being reformatted when running `make fmt`.
Mentioned in: https://github.com/determined-ai/determined/pull/2432#discussion_r638745707
> chore: Prevent harness/determined/_swagger from being reformatted by make fmt

- schemas/lint.py
- schemas/test_cases/v0/misc.yaml
Whitelist `eventually` in the schema linter, and fix `misc.yaml` so that `matches` is replaced by `sane_as`:
> chore: whitelist `eventually` in schema linter

- harness/determined/exec/gc_checkpoints.py
- master/internal/api_experiment.go
- master/internal/checkpoint_gc.go
- master/internal/command/tensorboard_manager.go
- master/internal/core_experiment.go
- master/internal/db/postgres.go
- master/internal/experiment.go
- master/pkg/schemas/expconf/experiment_config.go
- master/pkg/schemas/expconf/legacy.go
- master/pkg/schemas/expconf/legacy_test.go
- master/pkg/tasks/task_spec.go
Based on #2443, but I hit some git error trying to push to the original PR.  Running tests here.
> fix: introduce HistoricConfig for tensorboard and checkpooint gc [DET-5533]

- docs/model-hub/transformers/tutorial.txt
> docs: fix broken links in MH Transformers tutorial

- harness/determined/cli/shell.py
> chore: small rewording in shell help

- webui/tests/specs/02-dashboard.spec.bak
> chore: disable dashboard recent tasks tests temporarily

- webui/react/src/pages/ExperimentList.tsx
Problem: when viewing the Experiment List page via the nav side bar, the route is set to `/experiments` without any search params. For this case, it currently grabs all of the experiments (essentially no filters). Instead, we want to use user preferences if they are available.
> fix: use user preferences when no search params are present [DET-5537]

- helm/charts/determined/templates/master-config.yaml
- tools/scripts/bumpenvs.yaml
When users specify a registry for their images, the helm chart will now propagate this change to environment images.
> fix: allow custom registries with determined env images [DET-5556]

- proto/src/determined/template/v1/template.proto
- webui/react/src/components/NavigationSideBar.tsx
- webui/react/src/components/NavigationTabbar.tsx
- webui/react/src/components/NotebookModal.module.scss
- webui/react/src/components/NotebookModal.stories.tsx
- webui/react/src/components/NotebookModal.tsx
- webui/react/src/contexts/Store.tsx
- webui/react/src/omnibar/tree-extension/trees/index.ts
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
- webui/react/src/types.ts
- webui/react/src/utils/task.ts
- webui/tests/tests/StepImplementation.ts
Created the new modal for launching notebooks in the webui and hooked into APIs.
This addresses tickets [DET-5376] [DET-5377] [DET-5380] [DET-5378] [DET-5379] [DET-5375].
Manual testing. Attached user flow gif.
[DET-5376]: https://determinedai.atlassian.net/browse/DET-5376
[DET-5377]: https://determinedai.atlassian.net/browse/DET-5377
[DET-5380]: https://determinedai.atlassian.net/browse/DET-5380
[DET-5378]: https://determinedai.atlassian.net/browse/DET-5378
[DET-5379]: https://determinedai.atlassian.net/browse/DET-5379
[DET-5375]: https://determinedai.atlassian.net/browse/DET-5375
> feat: add launch notebook modal [DET-5376] [DET-5377] [DET-5380] [DET-5378] [DET-5379] [DET-5375]

- webui/react/src/pages/TrialDetails/Profiles/TimingMetricChart.tsx
In some cases the result computed through the factor is too large.
Fixing this by setting a max value of 70.
So now ticks space will always be between 35 and 70.
> fix: timing metric chart x-axis tick off [DET-5501]

- harness/determined/estimator/_estimator_trial.py
- in 2.5, when setting visible gpu devices, we need to set it using both
the old "session"-y way and the new one. otherwise it uses all
available devices, which breaks nccl-horovod-dtrain.
- get rid of `set_cuda_visible_devices` hack as it's no longer used [DET-3762]
Testing this change with the new tf2.5 image, including nightly: https://app.circleci.com/pipelines/github/determined-ai/determined/12792/workflows/0a7a468f-536b-493f-886e-db30eb9e2c4b
Control with the current images: https://app.circleci.com/pipelines/github/determined-ai/determined/12793/workflows/b74beeb0-8d79-483c-b330-6c1302e39be1
Image PR: https://github.com/determined-ai/environments/pull/94
[DET-3762]: https://determinedai.atlassian.net/browse/DET-3762
> fix: make tf estimator dtrain work with tf 2.5 [DET-5563, DET-3762]

- webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/SystemMetricChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/TimingMetricChart.tsx
Checked all `<UPlotChart>` we have and made sure the x axis label is set.
> fix: show x axis label on all plots [DET-5500]

- harness/determined/profiler.py
Change `ProfilerAgent` to record timings using `time.time()` instead of `datetime.utcnow()`. For timing small segments of code, this will make the measurements more accurate as `utcnow()` does conversion work that was previously included as part of the measurement. 
`time.time()` was chosen over `time.time_ns()` because that was introduced in Python 3.7 and at the time of coding we needed to support 3.6. It was chosen over `time.perf_counter()` and `time.monotonic()` because they are only useful for relative measurements (i.e. calculating durations). We need to record a timestamp to send to the DB so using those clocks would require us to store a timestamp in addition to the starting perf_counter/monotonic value. That seems to complicate the code more than the benefits are worth - we …
> chore: measure profiler timings with time.time()

- master/pkg/model/experiment_config.go
> fix: propagate slots when it is 0

- harness/determined/profiler.py
Fix bug where some datetimes were being serialized in a valid format, while others were not and causing POSTs to fail.
Python's `datetime.datetime` objects can be naive or timezone-aware. When `isoformat()` is called on them, the output is different depending on whether it is timezone-aware. During the initial implementation, all `datetime`s were naive, which meant the serialized form did not include any timezone information. We appended 'Z' to all timestamp strings to indicate that they are in UTC. PR #2475 changed most of the datetimes to be timezone-aware so appending 'Z' to all timestamps led to "2021-06-01T21:41:23.411254+00:00Z" instead of the intended "2021-06-01T21:41:23.411254Z". Now that we are working with timezone aware datetimes, the best way to serialize them is to just call …
> fix: ProfilingAgent serializing timestamps incorrectly

- harness/determined/profiler.py
This change ensures that all batches are sent on shutdown.
This is the PR I'm going to add tests over.
> fix: send all batches from profiler [DET-5566]

- harness/determined/_env_context.py
- harness/determined/_execution.py
- harness/determined/_rendezvous_info.py
- harness/determined/exec/harness.py
- harness/determined/layers/_socket_manager.py
- harness/tests/experiment/utils.py
- harness/tests/tensorboard/test_util.py
- harness/tests/test_horovod.py
- master/internal/trial.go
- master/internal/trial_test.go
- master/pkg/tasks/ports.go
- master/pkg/tasks/task_spec.go
I've always been annoyed that I never understood what all of the fields of RendezvousInfo were for.  I grep'd the code and realized only a couple were ever being used.
I plan on testing the full suite of distributed tests before landing this.
> chore: trim unused parts of rendezvous info

- webui/react/src/components/NotebookModal.tsx
The new notebook modal had a bug where the number of slots wasn't propagated correctly to the api. This fixes that bug.
> fix: notebook modal bugs [DET-5573]

- docs/release-notes.txt
- docs/release-notes/2320-webui-tqdm-rendering.txt
- docs/release-notes/2352-add-word-langauge-model-example.txt
- docs/release-notes/2359-add-preview-parameter.txt
- docs/release-notes/2364-webui-move-trial-hyperparams.txt
- docs/release-notes/2365-webui-trial-logs-moved.txt
- docs/release-notes/2372-webui-move-trial-workloads.txt
- docs/release-notes/2376-fix-gcp-terraform.txt
- docs/release-notes/2378-webui-update-experiment-list-filters.txt
- docs/release-notes/2383-slots-per-agent.txt
- docs/release-notes/2389-webui-update-trial-overview.txt
- docs/release-notes/2390-widen-trial-links.txt
- docs/release-notes/2428-ide-integration.txt
- docs/release-notes/2453-fix-k8s-resource-manager.txt
- docs/release-notes/2459-close-training-iterator.txt
I omitted changes to the `resource-pools` API since it is marked as Internal.
> docs: Release notes for 0.15.6.

- webui/react/.eslintrc.js
- webui/react/src/components/NotebookModal.tsx
- webui/react/src/prototypes.ts
This change will allow unused vars during an object deconstruction. For example, this current causes an issue:
```
const { first, ...rest } = obj;
return rest;
```
This will be an issue if you don't use the `first` variable.
This PR will allow for unused variables in the case of an object deconstruction if you use the spread operator.
> chore: update eslint-no-unused-vars to handle special cases

- harness/determined/profiler.py
This fixes a typo where gpu_util was shipped as both gpu_util and gpu_free_memory.
> fix: ship gpu_free_memory correctly [DET-5508]

- master/internal/trial.go
> chore: remove trial old messages and consolidate others

- harness/determined/profiler.py
Add ThroughputTracker object to reduce code duplication for System Metric Collectors that collect Throughput.
> chore: improve profiler throughput collectors

- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/Profiles/ProfilesEnabled.tsx
- webui/react/src/pages/TrialDetails/Profiles/ProfilesFiltersProvider.tsx
- webui/react/src/pages/TrialDetails/Profiles/SystemMetricChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/SystemMetricFilter.tsx
- webui/react/src/pages/TrialDetails/Profiles/TimingMetricChart.tsx
- webui/react/src/pages/TrialDetails/Profiles/utils.ts
- webui/react/src/pages/TrialDetails/TrialDetailsProfiles.tsx
> fix: observability webui fixes [DET-5567][DET-5246][DET-5506][DET-5531][DET-5530][DET-5571]

- proto/src/determined/api/v1/experiment.proto
> chore: fix TrialsSnapshotResponse comment typo

- webui/tests/package-lock.json
Patch `ws` security vulnerability of `Regular Expression Denial of Service`
https://www.npmjs.com/advisories/1748
> chore: upgrade ws to patch security vulnerability

- e2e_tests/tests/config.py
- e2e_tests/tests/experiment/test_profiling.py
- harness/determined/estimator/_estimator_trial.py
This change adds tests to cover all the observability features.
unfortunately, estimators is failing and it's a genuine failure so i have to fix that first.
> test: add e2e tests for profiling features [DET-5245]

- webui/react/src/App.tsx
UPDATE: decided to disable this notification all together for development environments, as it produces more false positives than actual helpful messaging.
> fix: avoid rc dev release mismatch notifications

- webui/react/src/components/NotebookModal.tsx
- webui/react/src/utils/task.ts
> chore: handle error when loading notebook config [DET-5600]

- webui/react/src/components/NotebookModal.tsx
- webui/react/src/utils/task.ts
Don't launch notebook if there are yaml errors and also have the form remember how many slots you had selected
> fix: notebook modal improvements [DET-5599]

- master/internal/command/command.go
I removed this by mistake in a rebase
> fix: add back bindmounts entry to command default config

- harness/determined/profiler.py
Wrap `pynvml` in a class that checks if `pynvml` is available and if `pynvml` is working. Abstracts away these checks from the user and just exposes a `is_available` boolean. Also wraps the various pynmvl APIs so that they are now typed and have some simple caching.
Also improves the design of the GPU memory/util collectors so that they will not cause errors if used when there are not GPUs (they just return an empty dict of measurements). 
> chore: improved pynvml usage by profiler [DET-5394]

- docs/release-notes/recommend-k8s-upgrade.txt
> docs: recommend users upgrade to 0.16.0 to avoid k8s master crashes

- webui/react/src/pages/TrialDetails/Profiles/utils.ts
Made a fix because the old code here was returning `null` when the value in the object is zero.
BEFORE:
AFTER:
> fix: trial profiling system metric chart ignoring zero [DET-5505]

- e2e_tests/tests/cluster/cluster.py
- e2e_tests/tests/command/command.py
- e2e_tests/tests/experiment/experiment.py
- e2e_tests/tests/experiment/test_metrics.py
- e2e_tests/tests/experiment/test_profiling.py
- harness/determined/cli/cli.py
- harness/determined/deploy/aws/deployment_types/base.py
- harness/determined/deploy/gcp/gcp.py
Fix certificate handling in CI.
Also fix a small bug in the CLI.
Running upstream tests.
> chore: initialize cli_cert in e2e tests

- docs/how-to/index.txt
- docs/how-to/profiling.txt
- docs/reference/experiment-config.txt
- docs/release-notes/2535-add-profiler.txt
This change adds release notes for profiling features, as well as documentation for the configurations in the experiment configuration reference.
> docs: add release notes for profiling features [DET-5351]

- e2e_tests/tests/test_users.py
- harness/determined/cli/sso.py
- harness/determined/cli/user.py
- harness/determined/common/api/authentication.py
- harness/determined/common/api/certs.py
- harness/setup.py
Support multiple individual masters in `auth.json`.
> feat: multimaster Authentication objects [DET-5308]

- docs/release-notes/2539-fix-null-hparam-value-repr.txt
- webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.tsx
> fix: fix hparam string representation failure [DET-5616]

- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
> chore: avoid defaulting to filter list views by current user [DET-5602]

- harness/determined/experimental/client.py
A rebase issue cause post-merge CI to fail.
Also add a note about password hygiene.
> chore: fix client for new password handling

- webui/react/src/pages/TrialDetails/Profiles/ProfilesNotEnabled.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsProfiles.tsx
I don't have a working dev environment but I checked that the link is valid 😬 
There was some redundant code that I _think_ I removed properly but please double-check me.
> fix: Incorrect help link when profiles aren't enabled for a trial. [DET-5621]

- docs/reference/experiment-config.txt
- harness/determined/profiler.py
"s/start_on_batch/begin_on_batch/g"
-
> chore: rename start_on_batch to begin_on_batch everywhere

- master/internal/db/postgres.go
- master/pkg/schemas/expconf/searcher_config.go
> chore: fix typos 

- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/TrialDetails.tsx
> fix: add checks against now nullable experiment description [DET-5622]

- webui/react/src/components/PageHeaderFoldable.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
That's just about adding the button here, since in the next phases we will drop the "Summary" section in the experiment page.
> chore: add download experiment model to new header [DET-5634]

- webui/react/src/components/CreateExperimentModal.tsx
- webui/react/src/components/NotebookModal.tsx
Clears linting!
Don't have a working dev environment, could any reviewer quickly sanity-check this?
> fix: Change wording on modals that edit configs. [DET-5639]

- harness/determined/deploy/aws/templates/efs.yaml
- harness/determined/deploy/aws/templates/fsx.yaml
- harness/determined/deploy/aws/templates/govcloud.yaml
- harness/determined/deploy/aws/templates/simple.yaml
- harness/determined/deploy/aws/templates/vpc.yaml
Make sure that all elastic IPs have the property `domain: vpc` to ensure that we never accidentally try to create an EC2 Classic elastic IP.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html
> fix: set elastic ip domain to vpc in det deploy aws [DET-5631]

- docs/tutorials/model-registry.txt
- e2e_tests/tests/test_system.py
- master/static/srv/get_model_versions.sql
- master/static/srv/insert_model_version.sql
This change fixes up a bad SQL join that resulted in a query that returned a combination of all rows rather than the intended join.
> fix: don't return dupes from det model list-versions [DET-5640, DET-4248]

- docs/release-notes/2526-bump-jupyterlab.txt
> docs: update the JupyterLab bump release note

- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentConfiguration.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentConfiguration.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
BEFORE (opening config yaml in a modal):
AFTER:
> chore: move experiment configuration to a tab [DET-5438]

- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
As per [this slack conversation](https://determined-ai.slack.com/archives/C020TQ54ZJR/p1623320842030300).
BEFORE:
AFTER:
> chore: add start time and duration to new experiment header [DET-5635]

- .circleci/config.yml
The old version has turned into a pumpkin. Probably EOL by GCP. Failure example: https://app.circleci.com/pipelines/github/determined-ai/determined/13387/workflows/4d6caaf1-d970-430b-bea2-d027ee2dfa4c/jobs/394698
> fix: update gke version in circleci since the old one is no longer valid.

- harness/determined/keras/_tf_keras_trial.py
- harness/determined/keras/callbacks.py
- harness/determined/profiler.py
- harness/determined/pytorch/_pytorch_trial.py
- proto/src/determined/trial/v1/trial.proto
This change adds "misc" metrics and collects samples_per_second as the first one, so we can display it in the webui again, but not rely on getting it from a step's metrics (since those will go away shortly). It also heavily refactors the profiler code to have a single "batcher" type and a single "batcher thread" type, instead of one specifically for timings/system/misc metrics.
This code is not yet "always on". I'm going to leave that for a follow up PR / discuss it at ml-ag.
> chore: collect samples per second for pytorch and keras [DET-5515]

- webui/react/src/pages/ExperimentDetails/Header/ExperimentHeaderState.module.scss
- webui/react/src/pages/ExperimentDetails/Header/ExperimentHeaderState.tsx
> fix: make header loading spinner more prominent[DET-5667]

- docs/how-to/installation/upgrades-troubleshoot.txt
Add some documentation around migration failures.
> docs: add db migration troubleshooting section [DET-5493]

- webui/react/src/components/Json.module.scss
- webui/react/src/components/NotebookModal.tsx
- webui/react/src/components/ResourcePoolCard.stories.tsx
- webui/react/src/components/ResourcePoolCard.tsx
- webui/react/src/components/SlotAllocationBar.tsx
- webui/react/src/contexts/Store.tsx
- webui/react/src/pages/Cluster/ClusterHistoricalUsage.tsx
- webui/react/src/pages/Cluster/ClusterOverview.tsx
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/cluster.ts
- webui/tests/specs/02-cluster.spec
- conditional display of aux container count
- separate overall slot allocation bar per resource type
- resource type agnostic resource cards
- promote slotsPerAgent to featured rp properties
- notebook launch ux: remove the resource type picker row
> feat: cpu training ux [DET-5663, DET-5664]

- webui/react/src/pages/TrialDetails/Profiles/ProfilesFiltersProvider.tsx
This works similarly to the other pages where we are already doing something like this (eg: experiment list).
Resulting urls are like those:
- http://localhost:3000/det/experiments/1600/trials/2332/profiler?name=disk_iops&agentId=i-0ede57e50ea09fb97
- http://localhost:3000/det/experiments/1600/trials/2332/profiler?name=gpu_util&agentId=i-0ede57e50ea09fb97&gpuUuid=GPU-b7bea20a-eb78-7eea-9f19-5f73aec28c7b
> chore: webui profiler write/read filters from url [DET-5572]

- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss
- webui/react/src/pages/ExperimentDetails/Header/ExperimentHeaderState.module.scss
- webui/react/src/pages/TrialDetails/Header/TrialHeaderLeft.module.scss
> fix: new header increase font-size for desktop [DET-5680]

- harness/determined/exec/tensorboard.py
- master/static/srv/tensorboard-entrypoint.sh
Supporting various different tensorboard startup args depending on version
> feat: support different tensorboard startup args [DET-5550]

- harness/determined/deploy/aws/aws.py
- In #2588, user has terminated the master instance manually which
caused `det deploy aws down` to fail. We should ignore errors in instance
stopping, because it's going to be deleted anyhow.
> fix: ignore an error with terminated master when deleting AWS stacks.

- docs/how-to/installation/gcp.txt
- docs/reference/cluster-config.txt
- docs/release-notes/2589-filestore.txt
- docs/topic-guides/deployment/gcp.txt
- harness/determined/deploy/gcp/cli.py
- harness/determined/deploy/gcp/gcp.py
- harness/determined/deploy/gcp/preflight.py
- harness/determined/deploy/gcp/terraform/main.tf
- harness/determined/deploy/gcp/terraform/modules/compute/main.tf
- harness/determined/deploy/gcp/terraform/modules/compute/variables.tf
- harness/determined/deploy/gcp/terraform/modules/filestore/main.tf
- harness/determined/deploy/gcp/terraform/modules/filestore/outputs.tf
- harness/determined/deploy/gcp/terraform/modules/filestore/variables.tf
- harness/determined/deploy/gcp/terraform/outputs.tf
- harness/determined/deploy/gcp/terraform/variables.tf
- master/internal/command/notebook_manager.go
- master/static/srv/notebook-entrypoint.sh
1. Spin up Filestore on GCP when running `det deploy gcp up`.
2. Spin down Filestore on GCP when running `det deploy gcp down`.
Manually tested it.
> feat: spin up/down Filestore for det deploy gcp

- .circleci/config.yml
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/tensorboard/util.py
- harness/setup.py
- master/internal/command/tensorboard_manager.go
Add set profiler option to torch trial contexts allowing models to pass in profiler arguments.
> feat: set torch profiler in torch trials [DET-5549]

- helm/Makefile
- helm/charts/determined/Chart.yaml
> fix: helm chart version in Makefile

- webui/react/src/pages/TrialDetails/Profiles/SystemMetricFilter.tsx
- webui/react/src/pages/TrialDetails/Profiles/utils.ts
> fix: avoid showing the gpu dropdown when there is no reported gpu uuid [gh-2604] 

- master/internal/provisioner/agent_setup.go
> fix: print out errors when agent setup script generating fails

- webui/react/src/components/FilterCounter.module.scss
- webui/react/src/components/FilterCounter.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
> feat: display active filter count and option to reset for tasks and experiments [fixes #2584]

- harness/determined/pytorch/_pytorch_context.py
fix unused ignore linting error 
> fix: linting error in circle ci

- docs/how-to/custom-env.txt
- docs/how-to/installation/gcp.txt
> fix: update custom-env docs with new versions

- proto/Makefile
This change prevents master from missing go mod tidy changes.
> build: check Go modules files are up to date in `make -C proto check`

- webui/react/src/pages/TrialDetails/Profiles/ProfilesEnabled.tsx
- webui/react/src/pages/TrialDetails/Profiles/ProfilesFiltersProvider.tsx
fixes #2605 
TODO can we do this? 
> chore: add loading state profile metrics

- harness/determined/deploy/aws/aws.py
> fix: improve det deploy aws messaging for inconsistent stack states [DET-5695]

- docs/how-to/installation/custom-pod-specs.txt
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret
> docs: correct pod spec

- webui/react/scripts/proxy.js
> chore: improve error handling for react preview proxy

- e2e_tests/tests/nightly/test_capability.py
- e2e_tests/tests/nightly/test_distributed.py
- examples/computer_vision/deformabledetr_coco_pytorch/startup-hook.sh
- examples/computer_vision/detr_coco_pytorch/startup-hook.sh
fix following issues:
* gaea tests failed with out of gpu memory so reduced batch size
* detr tests failed due to special handling in upstream code that did not parse torchvision version correctly
> fix: nightly tests broken after environment upgrades

- webui/react/src/pages/TrialDetails.tsx
> fix: make "Continue Trial" button work again [DET-5704]

- webui/react/scripts/README.md
> chore: add a readme for react/scripts

- webui/react/src/pages/ExperimentDetails/Header/ExperimentHeaderProgress.tsx
> fix: header progress bar [DET-5709]

- webui/react/src/pages/TrialDetails/TrialChart.tsx
Tooltips are displayed on what uPlot suggests to be the closest (to the cursor) x index.
In this case the chart might have multiple series which are hidden, and uPlot still account them for computing the closest x index.
If the only visible serie has way less data points than hidden ones, we can see what's reported in the ticket.
Solution:
Only provide uPlot series that are visible, so that x index is computed according to available (and visible) data point.
> fix: improve trial chart tooltip [DET-5712]

- webui/react/src/pages/ExperimentDetails/ExperimentConfiguration.tsx
> fix: Configuration height doesn't go to the full page height [DET-5721]

- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
Simply shows this in all tabs (except config) instead of an empty page with spinners:
> fix: Add page elements to Trial page while data is loading [DET-5718]

- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx
If the range of a log type hp plot includes negative numbers, treat it as a double type instead.
> fix: correct for possibility of negative numbers in log range [DET-5717]

- webui/react/src/omnibar/tree-extension/trees/actions.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
- webui/react/src/pages/SignIn.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/routes/utils.test.ts
- webui/react/src/routes/utils.ts
yes 
there was a bug in `routeAll` and it surfaced since we started using `routeAll` in model download button isntead of using a vanilla anchor tag. 
We've been relying on this semi-bug unintentionally for for routing in different paces hence this commit https://github.com/determined-ai/determined/pull/2661/commits/0007c075cfd9d3cb579f8e3a79f90364d892cc4c  was needed to address this second part.
fixes #2648 
> fix: fix an issue with routing affecting model download [#2648]

- webui/react/src/components/NotebookModal.tsx
- webui/react/src/types.ts
> chore: simplify resourcetype related states following its removal

- webui/react/src/components/TagList.tsx
Requested in the single experiment experience bug bash. This should increase the usability of tags in the experiment list at the expense of some visual inconsistency in terms of row height.
> chore: update experiment tag list limits

- master/static/srv/tensorboard-entrypoint.sh
Tensorboard startup was recently changed to pull container image from experiment configs instead of always using a default tensorboard image. All Determined environment images will have Tensorboard installed, but this leaves the possibility of some users using a custom-built Pytorch image that may not have Tensorboard. We install it (without force upgrade, so if the package already exists this change will be ignored)
> feat: install tensorboard if not already present [DET-5628]

- docs/how-to/installation/deploy.txt
- docs/how-to/notebooks.txt
- docs/release-notes/5432-local-bind-mount.txt
- harness/determined/deploy/local/cli.py
- harness/determined/deploy/local/cluster_utils.py
Add support for automatically bind mounting the specified home directory onto task agents for det deploy local and a flag for disabling it.
Test by running: 
1. `det deploy local cluster-up --auto-bind-mount="put_a_path_here"`, open two files in the base directory and ensure any changes to one happen to the other.
2. `det deploy local cluster-up`, open two files in the base directory and ensure any changes to one happen to the other.
3. `det deploy local cluster-up --no-auto-bind-mount` to ensure normal behavior.
Also look at docs changes in the how-to guide for `det deploy local` and the notebooks how-to guides.
> fix/docs: support det-deploy local cluster-up specified directory to bind mount [DET-5431]

- harness/determined/deploy/gcp/cli.py
> chore: fix a flag in det deploy gcp

- harness/determined/deploy/gcp/cli.py
> chore: lint det deploy

- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx
Fixes a bug found in release party.
> fix: correctly interpret minval and maxval for log hps

- master/internal/command/command.go
Add missing field to the GET tensorboard API.
Looks like this has been broken forever.
> fix: return tensorboard config with GET /api/v1/tensorboards/<id>

- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.module.scss
> fix: visual bug in hp plot [DET-5720]

- .circleci/config.yml
Second half of this: https://github.com/determined-ai/determined/pull/2651
https://app.circleci.com/pipelines/github/determined-ai/determined/13772/workflows/f4ca904b-d5f7-4df0-ae66-2823b9ac60d9/jobs/408266
> ci: add preview cluster creation to Circle CI

- .circleci/config.yml
Allow developers to "request" nightly single gpu and distributed gpu tests.
> feat: allow nightly gpu tests to be requested

- master/internal/command/command.go
> chore: error introduced by rebasing

- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
When viewing a single trial experiment, the detail page shows `No data available` during a trial load. There is a special case where the experiment has not progressed enough to actually have trial data, but is still running. To avoid confusing the user into thinking that the trial will forever not have data, show a spinner instead.
Before:
After:
> fix: no data available [DET-5734]

- netlify.toml
Let netlify handle grabbing node dependencies to take advantage of thecaching that it provides
should shave off about 50 seconds from each build
> build: let netlify handle node dependency management

- master/pkg/tasks/task_command.go
- master/pkg/tasks/task_gc.go
- master/pkg/tasks/task_trial.go
> fix: e2e test

- master/internal/kubernetes/spec.go
This reverts commit 51154955578f5535f2f3194ab018a88d4eaf4119.
> revert: "fix: prevents k8s priority scheduler from blocking cpu only training (#2631)"

- webui/react/src/dev.ts
- webui/react/src/omnibar/tree-extension/trees/dev.ts
- webui/react/src/routes/utils.ts
> chore: add a safeguard for setting server address through the omnibar

- docs/release-notes/2694-boolean-hp-value.txt
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.stories.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx
- manually tested with boolean hp values
> fix: fix an issue with rendering boolean hp values in learning curve table [#2670]

- master/internal/kubernetes/spec.go
> fix: fixes commit 9fec2f9e14d that cherry picked a revert

- docs/how-to/installation/setup-eks-cluster.txt
[DET-5728]
[DET-5728]: https://determinedai.atlassian.net/browse/DET-5728
> docs: EKS Auto-scaling fix [DET-5728]

- docs/how-to/notebooks.txt
- docs/release-notes.txt
- docs/release-notes/2644-pytorch-geometric.txt
- docs/release-notes/2675-det-deploy-aws.txt
- docs/release-notes/2694-boolean-hp-value.txt
- docs/release-notes/2708-reduce-single-trial-exp-page-loading.txt
- docs/release-notes/5432-local-bind-mount.txt
> docs: add release notes for 0.16.2

- e2e_tests/tests/nightly/test_capability.py
- examples/graphs/proteins_pytorch_geometric/README.md
- examples/graphs/proteins_pytorch_geometric/adaptive.yaml
- examples/graphs/proteins_pytorch_geometric/const.yaml
- examples/graphs/proteins_pytorch_geometric/distributed.yaml
- examples/graphs/proteins_pytorch_geometric/model_def.py
Previous example model was flaky and sometimes had "convergence issues", both in our adaptation and in the original code. Since I am no expert on graph convolutional networks, and can't efficiently debug these issues, let's replace the example with a slightly different model which works. Either way, the key point of this example is demoing `get_batch_length` method. 
Also throw in `adaptive.yaml` for good measure.
It is included in nightlies again.
> chore: replace proteins_pytorch_geometric example with a better one.

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
Multi-trial experiments show a spinning loader when Paused. Since the experiment is not progressing, the experiment should go ahead and show "no data" instead of a spinner.
Before:
After:
> refactor: show "no data" instead of spinner [DET-5719]

- webui/react/src/pages/TrialDetails/TrialChart.tsx
Made 2 changes:
1. Display the type of metric on the tooltip
2. If only 1 metric is selected, show it as the Y axis label:
I'm not sure if alternatively we want to display the uPlot default legend and drop the select above the chart.
> fix: Add legend to Trial metrics graph [DET-5723]

- docs/release-notes/2722-trial-sort-by-state.txt
- webui/react/src/pages/ExperimentDetails/ExperimentTrials.table.tsx
> feat: enable sorting trials by state [#2673]

- .circleci/config.yml
> chore: temporarily disable automatic updates to the preview cluster

- e2e_tests/tests/experiment/test_profiling.py
This change bumps the timeout for a _barely_ flaky test.
> test: bump test_streaming_observability_metrics_apis timeout

- docs/release-notes/2723-experiment-trial-actions.txt
- webui/react/src/components/TrialActionDropdown.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentTrials.table.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
> feat: expose trial log links at experiment trials [#2714]

- docs/release-notes/2721-server-availibility-check.txt
- webui/react/src/App.tsx
- webui/react/src/components/PageMessage.module.scss
- webui/react/src/components/PageMessage.tsx
- webui/react/src/routes/utils.ts
- webui/react/src/utils/browser.ts
> feat: check server reachability on first load

- webui/react/scripts/proxy.js
Our netlify cluster is missing PATCH, so the experiment label API endpoint does not work in the netlify preview.
> chore: add patch to webui proxy

- .circleci/config.yml
- netlify.toml
…luster (#2733)"
This reverts commit a77e3b9cd1e5a8da18aceb82cafea5d344a313b6.
> chore: re-enable automatic updates to the preview cluster

- webui/react/src/components/ContinueTrial.tsx
- webui/react/src/components/CreateExperimentModal.module.scss
- webui/react/src/components/CreateExperimentModal.tsx
- webui/react/src/pages/ExperimentDetails.tsx
PROBLEM:
The error message during an experiment `Fork` or `Continue Trial` is vague and hard to fix.
SOLUTION:
Expose the error message returned from the backend service that provides more specific and relevant error message that helps diagnose the issue at hand.
Before:
After:
> refactor: improve fork error message [DET-5795]

- webui/react/src/pages/ExperimentDetails.tsx
> fix: correct single trial experiment routing [DET-5789]

- webui/tests/test-cluster/agent.yaml
make sure webui e2e tests run on the same type of slot whether they're running locally or in ci
> test: consistent slot type for tests between local and ci environemnts

- docs/release-notes/2699-add-nested-hp-support.txt
- webui/react/src/components/ContinueTrial.tsx
- webui/react/src/components/ParallelCoordinates.tsx
- webui/react/src/fixtures/hyperparameter-configs.json
- webui/react/src/ioTypes.ts
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.stories.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.stories.tsx
- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.stories.tsx
- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/data.test.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/experiment.test.ts
- webui/react/src/utils/experiment.ts
- webui/react/src/utils/task.ts
- webui/react/src/utils/types.ts
Add support for nested hyperparameters via experiment config.
The nested hyperparameters config currently come through as an implicit nested dictionary and the way to distinguish a categorical type from a nested hp is the detected of the property `type`. Where `type` is `undefined` for an implicit dictionary, otherwise it is a terminal property where it has hp config info.
The trial hyperparameters are nested as well and require upgrade also.
The overall approach is to flatten the nested dictionary keys based on the nesting. For example:
```
{
a: {
x: true,
y: false,
z: null,
},
b: 1,
c: 2,
}
```
flattens to:
```
{
'a.x': true,
'a.y': false,
'a.z': null,
'b': 1,
'c': 2,
}
```
Areas to address:
- HP visualization pages (learning curve, parallel coordinates, scatter plot, heat map)
- …
> feat: add nested hp support [DET-4786]

- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx
> chore: fix log type hyperparameters 

- webui/react/src/pages/ExperimentDetails/ExperimentMultiTrialTabs.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
What messaging would be good when we’re waiting on the trial to appear? `Waiting for the trial` (since we know it’s a single trial) or `waiting for the trial to appear` something else?
there should be a way that the tscompiler can warn about these 🤔 
https://github.com/microsoft/TypeScript/issues/30239
> fix: fetching trial undefined wait message

- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
> fix: fix stale trial data caused by internal react re-route

- webui/react/src/components/TableBatch.module.scss
- webui/react/src/components/TableBatch.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
This PR adds checkbox selection to the Experiment Trials page, allows for checkbox selection across pagination on the Trials, Experiment List, and Task List pages, and adds URL param tracking of selected rows to the Trials and Experiment List pages.
> feat: persist checkbox selection when changing page if results are paginated [DET-5416]

- docs/release-notes.txt
- docs/release-notes/2524-aks-support.txt
- docs/release-notes/2699-add-nested-hp-support.txt
- docs/release-notes/2721-server-availibility-check.txt
- docs/release-notes/2722-trial-sort-by-state.txt
- docs/release-notes/2723-experiment-trial-actions.txt
- docs/release-notes/2730-fix-too-many-streaming.txt
- docs/release-notes/2732-trial-filter-by-state.txt
- docs/release-notes/2753-model-dup.txt
- docs/release-notes/2761-fix-fork-stale-experiment.txt
> docs: add release notes for 0.16.3

- webui/react/src/pages/ExperimentDetails/ExperimentMultiTrialTabs.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
when we know the experiment is terminated:
- make sure the loading spinner goes away 
- we stop polling for the list of trials
fixes #2764 
> fix: fix indefinite spinner for terminal single-trial experiments

- .circleci/config.yml
> fix: only run circleCI step on master branch

- harness/setup.py
Install extras are stale and see little use. Instead of keeping this extra maintenance burden, let's get rid of them.
The python package can still be installed.
> chore: remove stale install extras from harness python package.

- docs/release-notes/2769-det-e-config.txt
Fix the linting issue for this [release note](https://github.com/determined-ai/determined/pull/2769/commits/43283fffd09fdfb576d107685d3b0e029edd45d5)
> chore: fix release note lint

- docs/release-notes/2789-fix-log-unicode-injection.txt
- webui/react/src/utils/dom.test.ts
- webui/react/src/utils/dom.ts
Escape characters (and their unicode counterpart) that can potentially be an HTML and JS injection.
'<', '>', '&', ''', '"'
> fix: prevent log html injection via unicode [DET-5826]

- .circleci/config.yml
- CONTRIBUTING.md
Add a test that fails if cloud credentials are present. Also update the pattern used to catch GCP credentials. Previous pattern had too many false positives.
> ci: add linter for secrets

- webui/tests/bin/createUserAndExperiments.py
- webui/tests/specs/01-setup.spec
- webui/tests/specs/02-authentication.spec
- webui/tests/specs/02-cluster.spec
- webui/tests/specs/02-dashboard.spec
- webui/tests/specs/02-experiments.spec
- webui/tests/specs/02-master-logs.spec
- webui/tests/specs/02-navigation.spec
- webui/tests/specs/02-responsive.spec
- webui/tests/specs/02-tasks.spec
- webui/tests/specs/03-cleanup.spec
- webui/tests/tests/StepImplementation.ts
I separated this out from push architecture branch
more details in the linked issue
> test: improve web e2e test stability

- docs/how-to/installation/aws.txt
view updated but potentially stale docs [here](https://423937-253846879-gh.circle-artifacts.com/0/docs/site/html/index.html)
closes #2716 
> docs: add manual aws modification steps

- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.module.scss
> fix: remove track for constant hps [DET-5815]

- webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
- webui/react/src/pages/ExperimentDetails/TrialsComparisionModal.tsx
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
- webui/react/src/utils/trial.ts
> feat: add trial comparison modal [DET-5417]

- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx
> feat: move workloads back to trial overview page [DET-5738]

- docs/release-notes/2775-experiment-deletion.txt
- webui/react/scripts/proxy.js
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/components/TaskCard.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/themes.ts
- webui/react/src/types.ts
- webui/react/src/utils/sort.ts
- webui/react/src/utils/types.ts
- tradeoff discussion https://determined-community.slack.com/archives/C025A98H82X/p1627494839214600
closes #2752 
> feat: experiment delete

- .circleci/config.yml
current GKE version 1.18.19-gke.1701 is no longer supported 
https://cloud.google.com/kubernetes-engine/docs/release-notes-nochannel
e2e tests are failing: https://app.circleci.com/pipelines/github/determined-ai/determined/14538/workflows/af34526e-0b74-4cea-9b25-52f567ba7ed3/jobs/434520
> fix: update gke version in CI tests

- master/internal/agent/agent.go
This change updates the agent actor in the master to at least log ws write failures.
This could, in some cases, get kinda noisy.. that is my only concern. But also not writing these made a bug much harder to fine (I found it quickly mostly by luck).
> chore: don't drop agent ws failures

- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
This PR adds a thin border on the bottom of header rows and a small margin after the title column in the trial comparison table.
> fix: minor trial comparison layout adjustments [DET-5852] [DET-5853]

- webui/react/tsconfig.json
Simple change, just updates our emitted JS to use es6 features. Builds correctly and didn't notice any problems.
> chore: upgrade typescript target to es6

- webui/react/src/pages/ExperimentDetails/ExperimentConfiguration.tsx
I don't love my solution for the mobile issue (I just checked whether the width is under the breakpoint and hardcoded the monaco editor height), but it works.
> fix: size and resize the config monico editor [DET-5736]

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
Couldn't reproduce the bug, but this should fix it.
> fix: don't display indefinite spinner if experiment is paused [DET-5849]

- master/static/srv/tensorboard-entrypoint.sh
> fix: issue with order of install and version check of tensorboard

- proto/Makefile
`swaggo/swag` seems to be both a binary build-time dependency installed via `go get` in `/proto`, and a module. 
This change nails down the `go get`'ed package version so they don't drift apart.
CI is green.
> fix: nail down installed swag cmd version.

- master/pkg/model/experiment_config.go
Do the same deduplication that we do for experiments, for commands.
> fix: properly dedup container configs

- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
Removed code that blocks user from seeing tabs. Each individual tab except Config should give a `NoDataAlert` until the trial data loads.
> fix: show tabs independent of trial detail loading [DET-5839]

- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
> feat: add Trial ID to header of single-trial experiment page [DET-5816]

- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
Removes the following rows from trial comparison:
* Start Time
* Validation Time
* Checkpoint Time
* Best Checkpoint
> fix: remove unnecessary rows from trial comparison [DET-5857]

- webui/react/src/components/NavigationSideBar.tsx
- webui/react/src/contexts/Store.tsx
- webui/react/src/hooks/useSettings.test.ts
- webui/react/src/hooks/useSettings.ts
- webui/react/src/pages/TaskList.settings.ts
- webui/react/src/pages/TaskList.tsx
This body of work focus on revamping the user settings on a per page basis. Currently, on a per page-basis, there is a lot of code to perform the following:
- encode and decode settings from the query string
- read/write from storage
- side effects to update state based on storage and query string
Goals of this PR:
- Remove the need for a bunch of boiler plate code for settings
- Convert the settings data flow to be in one direction to avoid the need for complex logic
- Extract a config file per page in order to allow for a simple hook inject + config to support settings seamlessly
- Apply to just the Task List page to see the effects of this PR on a lower impact page
What's happening under the hood:
READ:
detect query string changes => page state (query param > persistent storage > …
> refactor: settings data flow [DET-5625]

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
Adds trial comparison (and ability to open in TensorBoard) to the Learning Curve and HP Parallel Coords charts
> feat: add ability to compare Trials from Learning Curve and HP Parallel Coords charts [DET-5851]

- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
This adds select filters to choose which metrics and hyperparameters are visible in the trial comparison table. It also adds semantic HTML, defining the table as unordered lists.
> feat: allows selection and unselection of hps and metrics in trial comparison table [DET-5854]

- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
- Fix the issue of aligning the arrow within an `antd SelectFilter`
- Add overflow scrolling to table body to avoid having the modal scroll the entire page (also to preserve trial header)
- Minor style tweaks.
BEFORE:
AFTER:
> style: tweak hp comparison styles

- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
Adds links to the trial page when you click on the trial id.
> feat: add links to trial pages in trial comparison modal [DET-5850]

- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/priority_test.go
- master/internal/resourcemanagers/task_list.go
Just a few local tweaks to make the code a bit nicer. No functionality
change.
> chore: clean up priority scheduler code a bit

- docs/tutorials/index.txt
- docs/tutorials/porting-tutorial.txt
> docs: add porting guide

- docs/tutorials/porting-tutorial.txt
> fix: reformat porting tutorial

- docs/how-to/notebooks.txt
> docs: improve Notebook docs [DET-5367]

- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
Boolean values weren't showing up, so this PR just casts everything that isn't a number to a string to display it.
> fix: casts non-number HPs to strings in trial comparison table

- harness/determined/horovod.py
The fallback only works with the gloo controller... which is all we
support anyway.
Tested manually with the `determinedai/environments:cuda-10.0-pytorch-1.4-tf-1.15-gpu-0.8.0` image, where I noticed the problem in the first place.
> fix: support pre-cross_rank versions of horovod

- e2e_tests/tests/experiment/test_profiling.py
- harness/determined/profiler.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
This change just adds "accumulated timings" that get aggregated over a batch (since there may be many calls to ctx.backward() or ctx.step_optimizer()), and adds code to collect new metrics depending on this.
> feat: collect sync_optimizer and backwards pass timings [DET-5724]

- e2e_tests/tests/nightly/test_convergence.py
- examples/tutorials/imagenet_pytorch/const.yaml
- examples/tutorials/imagenet_pytorch/const_cifar.yaml
- examples/tutorials/imagenet_pytorch/distributed.yaml
- examples/tutorials/imagenet_pytorch/distributed_cifar.yaml
> fix: reduce imagenet ci time

- docs/topic-guides/system-concepts/scheduling.txt
Bit short, maybe, but I couldn't think of any more to say.
> docs: describe how to set task priorities

- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/components/Section.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentConfiguration.tsx
- webui/react/src/styles/antd.scss
> style: update exp config and logs to render properly on FF mobile

- e2e_tests/tests/experiment/test_tf_keras.py
- fix `NoCredentialsError` in `test_tf_keras_mnist_data_layer_s3` and `test_tf_keras_mnist_data_layer_parallel`.
Master CI should be green.
> fix: test credentials for test_tf_keras_mnist_data_layer_

- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
This PR fixes a bug that was preventing the selection of rows, and also fixes some other bugs and errors on the experiment visualization page.
> fix: fix row selection and errors on experiement visualization

- webui/react/src/hooks/useSettings.ts
- webui/react/src/pages/Cluster/ClusterHistoricalUsage.settings.ts
- webui/react/src/pages/Cluster/ClusterHistoricalUsage.tsx
- webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx
- webui/react/src/pages/Cluster/ClusterHistoricalUsageCsvModal.tsx
- webui/react/src/pages/Cluster/utils.ts
- webui/react/src/pages/ExperimentDetails/ExperimentTrials.settings.ts
- webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
- webui/react/src/pages/ExperimentList.settings.ts
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.settings.ts
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsOverview.settings.ts
- webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx
apply useSettings in the following areas:
skipping profiler for now due to it being a more complicated setup
> refactor: apply use settings on other sections

- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
> fix: remove visual gap on trial comparison

- master/pkg/tasks/task.go
> fix: remove bad switch default

- docs/release-notes/2863-fix-uplot-0-values.txt
- webui/react/src/components/UPlotChart/tooltipsPlugin.ts
- webui/react/src/pages/TrialDetails/TrialChart.tsx
uPlot was treating values of 0 as the same as not having any data, which was incorrect. This makes it display 0 as a valid value.
Test by making an experiment return a metric with a value of 0, then view it on the Metrics graph on the Trial Details page (or Experiment Overview for single-trial experiments).
> fix: uPlot to show values of 0

- docs/release-notes.txt
- docs/release-notes/2380-fix-fault-tolerance-bug.txt
- docs/release-notes/2769-det-e-config.txt
- docs/release-notes/2775-experiment-deletion.txt
- docs/release-notes/2789-fix-log-unicode-injection.txt
- docs/release-notes/2797-preserve-uplot-zoom-between-remounts.txt
- docs/release-notes/2810-fix-timing-metric-y-axis-label.txt
- docs/release-notes/2834-set-priority.txt
> docs: add release notes for 0.16.4

- e2e_tests/tests/test_users.py
- master/internal/api_experiment.go
- master/internal/grpcutil/auth.go
Exactly the commit description.
> chore: users can delete their own exps [DET-5901]

- .circleci/config.yml
Netlify covers this use-case in all cases but upstream branches that don't have a PR.
> build: sunset circleci based react preview

- e2e_tests/tests/nightly/test_convergence.py
> fix: relax imagenet ci target

- .circleci/config.yml
> chore: bump gke patch version

- harness/determined/cli/checkpoint.py
> chore: augment fields displayed by describe checkpoint

- webui/react/src/components/StopExperimentModal.tsx
- webui/react/src/pages/ExperimentList.tsx
Addresses bug found in release party.
> fix: remove rerender on row selection on Experiment List page

- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
When single trial experiment reaches the moment a where a trial is running, the state controls go away and the state displayed reflects the trial state instead of the experiment state.
BEFORE:
AFTER:
> fix: enable experiment controls in the header for single trial [DET-5914, DET-5915]

- webui/react/src/components/OverviewStats.module.scss
> chore: limit overviewstats widget to one line

- helm/charts/determined/templates/master-permissions.yaml
When we made watchers more resilient, part of that involved getting the internal resource version for events to use watchtools.NewRetryWatcher correctly, but we do not have list on events so it fails perpetually.
I'll add a release note for this one.
> chore: update master ClusterRole permissions to include list on events (helm)

- e2e_tests/tests/conftest.py
`det master config` has started to dump yaml by default in #2766. It turned out we have one place in CI where we parse it as json.
CI is green.
> ci: `using_k8s` should use `det master config -o json`.

- .circleci/config.yml
since we now commit our generated code for WebUI tests don't need to depend on `build-bindings`
anymore
> build: remove unneeded build-bindings dependencies

- agent/Dockerfile
- master/Dockerfile
This change installs `unattended-upgrades` and runs it once in the master and agent Docker images to ensure base OS packages are up to date.
Replaced upgrade of perl-base with this since this upgrades it.
> chore: fix master/agent Docker image vulnerabilities [DET-5926]

- .circleci/config.yml
Quick fix for CI breakage. 
I am still looking for a better solution but this should unblock us for now.
CI works.
> ci: restrict setuptools version.

- webui/react/src/components/StopExperimentModal.tsx
Before:
After:
Rationale:
This removes a click for users to save existing work, while not adding a click for previous default behavior.
> fix: change "stop and save checkpoint" from checkbox to button [DET-5837]

- docs/how-to/installation/aws.txt
- harness/determined/deploy/aws/cli.py
- harness/determined/deploy/aws/constants.py
- harness/determined/deploy/aws/deployment_types/vpc.py
- harness/determined/deploy/aws/templates/efs.yaml
- harness/determined/deploy/aws/templates/fsx.yaml
- harness/determined/deploy/gcp/cli.py
Support passing an existing EFS/FSx to `det deploy aws`.
- This is tested by passing an EFS/FSx and see if it is correctly mounted.
> feat: Support passing an existing EFS to det deploy aws [DET-5737]

- .circleci/config.yml
- e2e_tests/pytest.ini
- e2e_tests/tests/conftest.py
- e2e_tests/tests/model_hub/test_transformers.py
fix ci and pytest config for model-hub tests
note e2e_tests for model-hub all passed
> fix: e2e nightly model-hub tests

- master/internal/kubernetes/spec.go
Attempting to run as a non-root user has previously caused kubernetes to fail, erroring out during the mounting volumes step. This fix addresses the issue by allowing the fluent bit sidecar to run as a root user. The main determined container will still run as non-root. 
launch a kubernetes cluster and use `det user link-with-agent-user ...` to assign a uid and gid to the determined user. Submit an experiment and monitor. The experiment should complete without issue. 
> fix: kubernetes link with agent user [DET-5907]

- webui/react/src/components/TrialLogPreview.tsx
the logic for hiding log preview for completed trials is slightly wrong and needs updating
> fix: correct the logic for hiding log preview for completed trials

- agent/internal/fluent_intg_test.go
- agent/tools.go
- master/internal/command/command.go
- master/internal/elastic/elastic_intg_testutils.go
- master/test/integration/api/api_trials_test.go
- master/test/integration/api/main_test.go
- master/test/testutils/fixtures.go
- master/test/testutils/mocks.go
- master/tools.go
> //go:build lines
> The go command now understands //go:build lines and prefers them over // +build lines. The new syntax uses boolean expressions, just like Go, and should be less error-prone. As of this release, the new syntax is fully supported, and all Go files should be updated to have both forms with the same meaning. To aid in migration, gofmt now automatically synchronizes the two forms. For more details on the syntax and migration plan, see https://golang.org/design/draft-gobuild.
I haven't dug through go1.17 changelog but with it I get this set of changes every time I build. Would it be safe to commit these?
https://golang.org/doc/go1.17
> chore: add 1.17 golang build syntax

- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/components/UPlotChart.tsx
> fix: make uPlot axis expand to show new data when not zoomed in [DET-5941]

- agent/go.sum
- master/Makefile
- master/go.mod
- master/go.sum
> chore: pin mockery version

- docs/release-notes/2943-nan-infinity-metrics.txt
- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/components/ColorLegend.tsx
- webui/react/src/components/HpSelectFilter.tsx
- webui/react/src/components/HumanReadableFloat.tsx
- webui/react/src/components/HumanReadableNumber.stories.tsx
- webui/react/src/components/HumanReadableNumber.tsx
- webui/react/src/components/Table.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx
- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx
- webui/react/src/utils/trial.ts
We currently don't support displaying NaN` and +/- `Infinity` metric numbers. They show up as an empty string. Update to distinguish each case.
Not-A-Number
Positive Infinity
Negative Infinity
Typical Number
> feat: add support for nan and infinity metrics [DET-5944]

- webui/react/src/components/NotebookModal.tsx
> chore: update docs link in notebook webui modal

- webui/react/src/components/SelectFilter.tsx
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
Fixes header so that the trial ids scroll with values, while remaining sticky to the top of the table. Also makes the row labels sticky.
> fix: scroll trial ids with values in trial comparison [DET-5918]

- tools/scripts/refresh-ubuntu-amis.py
rookie error, mibad.  I'm actually a little unsure sure how this never manifested.
> chore: fix rstrip bug in refresh-ubuntu-amis

- docs/release-notes/2953-support-continue-trial-for-nested-hp-trials.txt
- webui/react/src/hooks/useCreateExperimentModal.tsx
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/utils/data.test.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/experiment.test.ts
- webui/react/src/utils/experiment.ts
- webui/react/src/utils/types.ts
Add support for reverting flattened nested trial hyperparameters to experiment config hyperparameters.
> fix: fork nested hp [DET-5945]

- master/internal/core.go
- master/internal/root.go
This change adds scary and obvious messages when the Determined resource manager crashes. Previously the master used the default "rootActor" which ignored all messages. This adds a root actor just for the master that warns on failures of critical sub-components of Determined and, if it returns an error, it has the potential to crash the root actor (though it doesn't do that quite yet). Previously, there were incidents where the `pods` actor crash didn't result in a system crash and we never recovered. The pods actor crashes were addressed in #2880, this is just the next in a line of improvements.
Nice to have future work after this PR would be to handle cleaning up stray agents/pods on startup (easy) or recovering them properly (hard) and causing RM crashes to crash the master (returning …
> chore: log warnings on critical failures

- docs/examples.txt
- e2e_tests/tests/nightly/test_capability.py
- examples/computer_vision/detectron2_coco_pytorch/Base-RCNN-FPN.yaml
- examples/computer_vision/detectron2_coco_pytorch/README.md
- examples/computer_vision/detectron2_coco_pytorch/const.yaml
- examples/computer_vision/detectron2_coco_pytorch/const_fake.yaml
- examples/computer_vision/detectron2_coco_pytorch/detectron2_files/coco_evaluation.py
- examples/computer_vision/detectron2_coco_pytorch/detectron2_files/common.py
- examples/computer_vision/detectron2_coco_pytorch/detectron2_files/data.py
- examples/computer_vision/detectron2_coco_pytorch/detectron2_files/evaluator.py
- examples/computer_vision/detectron2_coco_pytorch/detectron2_files/panoptic_evaluation.py
- examples/computer_vision/detectron2_coco_pytorch/detectron2_files/samps.py
- examples/computer_vision/detectron2_coco_pytorch/detectron2_files/sem_seg_evaluation.py
- examples/computer_vision/detectron2_coco_pytorch/detectron2_files/utils.py
- examples/computer_vision/detectron2_coco_pytorch/distributed.yaml
- examples/computer_vision/detectron2_coco_pytorch/mask_rcnn_R_50_FPN_noaug_1x.yaml
- examples/computer_vision/detectron2_coco_pytorch/model_def.py
- examples/computer_vision/detectron2_coco_pytorch/startup-hook.sh
> feat: add detectron2 example

- master/internal/api_job.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
- proto/src/determined/api/v1/job.proto
- proto/src/determined/api/v1/pagination.proto
- proto/src/determined/api/v1/trial.proto
- proto/src/determined/command/v1/command.proto
- proto/src/determined/job/v1/job.proto
- proto/src/determined/notebook/v1/notebook.proto
- proto/src/determined/resourcepool/v1/resourcepool.proto
- proto/src/determined/shell/v1/shell.proto
- proto/src/determined/tensorboard/v1/tensorboard.proto
- webui/react/src/services/api-ts-sdk/api.ts
- webui/react/src/services/decoder.ts
- add external APIs and types use for the project
There are some comments I marked with TODO that are specifically open to discussion
> chore: job queue api placeholder

- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
Rename "Download Model" to "Download Experiment Code"
> chore: rename download model button [DET-5920]

- docs/release-notes/2942-drop-start-time-stats-boxes.txt
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
- webui/react/src/utils/trial.ts
> chore: remove trial details start time related stats boxes [DET-5956]

- docs/release-notes/2958-batch-experiment-delete.txt
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/utils/types.ts
> chore: add support for batch delete of experiments [DET-5224]

- webui/react/src/ee/SamlAuth.ts
> chore: restore saml auth file to match ee version

- master/internal/core.go
- master/static/srv/get_raw_allocation.sql
- proto/src/determined/api/v1/api.proto
This change updates GET raw allocation to account for the fact that "workloads" are no longer really stored, and we don't know the start times at which we began to produce some set of metrics.
Follow up to make this all worthwhile is to remove the weird metric start time derivation from push.
> chore: update GET raw allocation to account for loss of workload information [DET-5973]

- harness/determined/pytorch/_lr_scheduler.py
- harness/determined/pytorch/_pytorch_trial.py
> chore: add STEP_WITH_OPTIMIZER setting for lr scheduler

- master/static/srv/get_checkpoints_for_trial.sql
> chore: remove start_time from get_checkpoints_for_trial

- helm/Makefile
> chore: remove -r option since default macos ln doesn't support it

- docs/conf.py
- docs/requirements.txt
> chore: fix doc build dependencies

- docs/release-notes/2977-owner-delete-experiments.txt
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
- webui/react/src/pages/ExperimentList.tsx
> feat: allow experiment owner to delete their own experiments [DET-5989]

- docs/release-notes/2979-new-notebook-tabs.txt
- webui/react/src/components/Table.tsx
> chore: popout new tab when clicking on task list links [DET-5998]

- harness/determined/ipc.py
In other words, try even harder to avoid hangs.
I had a bug in some other half-written feature that was causing the `ZMQBroadcastServer` to hang in ways that it normally wouldn't, which resulted in hangs.  This fixed the hangs that resulted.
> fix: make PIDServer send SIGKILL after waiting on SIGTERM

- docs/reference/api/command-notebook-config.txt
- docs/release-notes/2773-work-dir.txt
- docs/topic-guides/commands-and-shells.txt
- master/internal/api_command.go
- master/internal/experiment.go
- master/internal/kubernetes/spec.go
- master/internal/restore.go
- master/internal/trial.go
- master/internal/trial_test.go
- master/pkg/model/command_config.go
- master/pkg/model/task_container_defaults.go
- master/pkg/tasks/mounts.go
- master/pkg/tasks/task.go
- master/pkg/tasks/task_command.go
- master/pkg/tasks/task_gc.go
- master/pkg/tasks/task_trial.go
- schemas/README.md
This PR supports configuring working directory for tasks. Users can also specify default working directory in task container defaults.
- Manually test overriding working directory on different tasks.
> feat: support configuring working directory for tasks [DET-5009]

- .circleci/config.yml
- harness/determined/deploy/aws/cli.py
> chore: confirm with users when running det deploy aws down [DET-6000]

- master/internal/api_notebook.go
- master/static/srv/notebook-template.ipynb
> chore: update notebook README [DET-6001]

- agent/Dockerfile
- master/Dockerfile
- switch from debian:10.3-slim to ubuntu:20.04 and unattended-upgrades
to get better security upgrades.
> fix: address CVEs in agent & master docker images.

- proto/src/determined/api/v1/api.proto
- webui/react/src/services/api-ts-sdk/api.ts
> chore: update job queue route paths

- master/internal/task/idle_timeout.go
> chore: fix nil deref in idle timeout

- master/pkg/model/task.go
> chore: rename trial job type to experiment

- master/internal/sproto/task.go
- master/internal/task/allocation.go
- webui/react/src/pages/Wait.tsx
Fix the notebook wait page by adding back in some old API fields.
I'm having a bad day.
> fix: notebook wait page updates for API changes

- harness/determined/cli/experiment.py
- master/internal/db/postgres.go
Remove start_time from `det e describe` in a few places.
> fix: det e describe

- master/internal/api_notebook.go
- master/static/srv/notebook-template.ipynb
> fix: bug in notebook README

- master/internal/api_trials.go
Fix `det t kill` to send a kill signal.
> fix: kill trial should send kill [DET-6026]

- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
> fix: Inline editor for experiment description truncates placeholder text [DET-6024]

- harness/determined/profiler.py
- harness/determined/pytorch/_pytorch_trial.py
I went a little too far with the removals. Also, mostly, this makes the webui look better.
> chore: add back some timings that are still valid without a sync

- master/internal/task/allocation.go
- master/internal/trial.go
After eating my own dog food, this message looks out of place and is confusing. It used to just be an empty string, this was more clear when debugging but totally unnecessary.
noop
> chore: nit command exit message placeholder

- master/internal/db/postgres.go
This fixes a bug where `TrialByID` and `TrialByExperimentAndRequestID` did not properly query `trials.task_id`, so downstream queries did not have it to update the table.
This has no real impact since it is unused, I just noticed it while looking at the DB.
> fix: save task end times [DET-6028]

- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
> chore: minor copy fix

- webui/react/src/components/NavigationSideBar.tsx
- webui/react/src/components/NavigationTopbar.tsx
Without the keys, newer `antd` will throw errors.
> chore: menu items require keys for newer antd versions (4.x+)

- master/static/srv/check_idle.py
Fix Notebook Idle timeout check to use master port/cert.
> fix: notebook idle check use master port, cert [DET-6013]

- master/static/srv/notebook-template.ipynb
> chore: clean notebook readme

- .circleci/config.yml
> chore: lower e2e-webui resource class

- master/internal/task/idle_timeout_test.go
> test: fix flake from race idle watcher tests

- master/pkg/searcher/grid.go
- master/pkg/searcher/grid_test.go
Nested hparams weren't working properly with grid search.
Added a test which failed without this fix.
> fix: fix nested hparams with grid [DET-6045]

- docs/release-notes/README.md
> chore: update release note guidelines

- webui/react/src/components/TaskActionDropdown.tsx
- webui/tests/tests/StepImplementation.ts
> chore: added confirmation modal to task kill [DET-6049]

- harness/determined/deploy/local/cli.py
[DET-5943]
Tested by deploying two servers in AWS, one was running the master and an agent, the other was running just an agent.
[DET-5943]: https://determinedai.atlassian.net/browse/DET-5943
> fix: Make agent names unique for det deploy local agent-up

- docs/sysadmin-basics/cluster-config.txt
- master/internal/api_command.go
- master/internal/api_shell.go
- master/internal/config.go
- master/internal/core_experiment.go
- master/internal/trial.go
- master/internal/trial_test.go
- master/pkg/ssh/ssh.go
- master/pkg/tasks/task.go
> feat: Make SSH RSA key size configurable [DET-5983]

- master/internal/api_job.go
Fixes the `actor not found` message returned by the system when the job queue request is submitted.
> fix: Job-queue fix update response

- harness/determined/exec/launch_autohorovod.py
> fix: hide secrets when printing config in trial log  [DET-6046]

- proto/scripts/swagger.py
- webui/react/src/components/TrialLogPreview.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
- webui/react/src/pages/TrialDetails/Profiles/useFetchAvailableSeries.ts
- webui/react/src/pages/TrialDetails/Profiles/useFetchMetrics.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
- webui/react/src/routes/utils.ts
- webui/react/src/services/api-ts-sdk/api.ts
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/utils.ts
- webui/react/src/utils/browser.ts
shorter operationIds for the main service (determiend) would result in friendlier names for generated code
while not adding collision risk.
> chore: advertise shorter openapi operation ids

- webui/react/public/determined/manifest.json
- webui/react/public/hpe/manifest.json
Update the incorrect relative paths in both of the `manifest.json` files
> chore: update manifest to use relative paths

- webui/react/src/components/NavigationSideBar.tsx
Master Logs really belongs with the Dashboard, Experiment List and other local nav items. The bottom sidebar nav items are external items or sidebar-related controls.
> style: move master logs nav item to other internal nav items

- harness/determined/cli/trial.py
- master/internal/core.go
- master/internal/core_trial.go
Old API missed getting updated at some point and was wrong, so this change removes it and updates the CLI to just use the new API.
> fix: remove old api kill trial

- master/packaging/fetch-cloud-forest.sh
Or I could just update bash (though I suspect this affects more MacOS users than me).
> fix: update fetch-cloud-forest.sh to be compatible with old versions of bash

- docs/sysadmin-basics/cluster-config.txt
- docs/sysadmin-deploy-on-k8s/helm-config.txt
- docs/training-apis/experiment-config.txt
- e2e_tests/tests/command/test_tensorboard.py
- e2e_tests/tests/experiment/experiment.py
- harness/determined/common/schemas/expconf/_gen.py
- harness/determined/common/schemas/expconf/_v0.py
- harness/determined/common/storage/s3.py
- harness/determined/tensorboard/build.py
- harness/determined/tensorboard/s3.py
- harness/tests/storage/test_s3.py
- harness/tests/tensorboard/test_s3.py
- harness/tests/test_imports.py
- master/internal/api_tensorboard.go
- master/pkg/model/storage_config.go
- master/pkg/schemas/expconf/storage_config.go
- master/pkg/schemas/expconf/zgen_s3_config_v0.go
- master/pkg/schemas/zgen_schemas.go
- schemas/expconf/v0/checkpoint-storage.json
- schemas/expconf/v0/s3.json
- schemas/test_cases/v0/misc.yaml
- schemas/test_cases/v0/unions.yaml
DET-5968
Test cases updated.
Manually tested invalid prefix, i.e., starting and/or ending with /
- [?] Release notes should be added as a separate file under `docs/release-notes/`.
> feat: Add Checkpoint Storage prefix for S3  [DET-5968]

- master/internal/restore.go
> fix: clarify/correct experiment snapshot shim error messages

- master/internal/api_trials.go
Correct API routing to trial actor, which caused kill to not work.
This endpoint somehow contains every bug. Looks like this has existed since inception.
> fix: bad routing to trial actor

- webui/react/src/pages/SignIn.tsx
This only impacts the logo not the functionality.
> chore: handle different provider name cases

- harness/determined/keras/_tf_keras_trial.py
Minor fix for outdated TFKerasTrial docstring.
N/A
> docs: `TFKerasTrial` docstring should say we default to TF 2.x.

- docs/release-notes.txt
- docs/release-notes/3113-patch-model-api.txt
- docs/release-notes/3117-confirm-cloudformation-updates.txt
- docs/release-notes/3138-delete-model-api.txt
- docs/release-notes/3160-nonroot-fluentbit.txt
> docs: add release notes for 0.17.3

- master/internal/core_experiment.go
- master/internal/db/postgres_experiments.go
- master/internal/experiment.go
- master/pkg/model/experiment.go
- proto/src/determined/experiment/v1/experiment.proto
- proto/src/determined/job/v1/job.proto
- webui/react/src/services/api-ts-sdk/api.ts
- report experiment progress for jobs
- get experiment owner's username from db and keep in memory. 
we're going toward relying on username instead of id as the unique key for users
> feat: jq api report experiment username and progress

- master/internal/api_job.go
- master/internal/resourcemanagers/fair_share.go
- master/internal/resourcemanagers/priority.go
> feat: get jobs for fairshare scheduler

- webui/react/src/components/MultiSelect.tsx
- webui/react/src/pages/TrialDetails/Logs/TrialLogFilters.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsLogs.settings.ts
- webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
Create settings config for trial log filters and use `useSettings` hooks to preserve trial log filter selection in the url query param.
> chore: trial log settings query param [DET-6206]

- docs/interact/cli.txt
[DET-6196](https://determinedai.atlassian.net/browse/DET-6196) - det exp does not work
The [CLI docs](https://docs.determined.ai/latest/interact/cli.html#usage) suggest that `det exp` can be used as a shorthand for `det experiment`, but this is not implemented. Since there are no other occurrences of this shorthand elsewhere in the docs, I simply trimmed this line. 
N/A
> docs: remove det exp from docs

- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
Problem:
The type imports in `api.ts` and `apiConfig.ts` are getting massive due to each individual type being brought in explicitly.
Solution:
Import types and service types using wildcard to implicitly bring new types in.
> refactor: simplify api and api config imports [DET-6201]

- webui/react/src/utils/string.test.ts
> chore: update string tests organization

- webui/react/src/styles/antd.scss
Ant Design has `text-shadow` applied on the selected tab option for Firefox.
Before:
After:
> style: remove text-shadow from selected antd tabs

- webui/react/src/components/NavigationSideBar.tsx
Older version used to report in a format of `x.xx.xx.yyy` but recently the versions are reported as `x.xx.xx-yyy`. Update code to be more flexible and better detect "core version" of `x.xx.xx`
Before:
After:
> fix: display short version in sidebar properly

- .circleci/config.yml
version "1.21.3-gke.2001" is no longer supported.
> ci: update gke version.

- webui/react/.eslintrc.js
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/ProgressBar.tsx
- webui/react/src/components/SlotAllocationBar.tsx
- webui/react/src/components/TableBatch.tsx
- webui/react/src/components/UPlotChart/tooltipsPlugin.ts
- webui/react/src/omnibar/tree-extension/index.ts
- webui/react/src/omnibar/tree-extension/utils.ts
- webui/react/src/pages/Cluster/ClusterOverview.tsx
- webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
- webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx
- webui/react/src/services/utils.ts
- webui/react/src/utils/browser.ts
- webui/react/src/utils/chart.test.ts
- webui/react/src/utils/number.ts
- webui/react/src/utils/string.ts
- webui/react/src/utils/task.ts
> chore: consistent spacing around operators

- master/internal/api_job.go
- master/internal/experiment.go
- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pods.go
- master/internal/kubernetes/preemptions.go
- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/sproto/kubernetes_resource_manager.go
Blocked on #3039
This PR enables scheduler compatibility with the new job queue mechanics and brings the k8s implementation up to speed with the resource pool implementation. Changes include:
- adding internal messages and plumbing for kubernetes specific handling
- enable the priority scheduler to set initial queue positions for jobs
- allow resource pools to insert jobs in arbitrary queue positions
- allow k8s RM to change priority and queue position
- allow reading of job queue in k8s
Note: there is a known bug where changing queue position in k8s is unsuccessful.
> feat: job queue scheduler internals

- master/internal/command/api.go
- master/internal/command/command.go
- master/internal/command/command_manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/config/config.go
- master/internal/core.go
- master/internal/experiment.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/scheduler_config.go
- proto/src/determined/api/v1/job.proto
- webui/react/src/services/api-ts-sdk/api.ts
> chore: jq read weight, priority, and preemption from config

- tools/scripts/scan-docker-images.sh
Allow using `scan-docker-images.sh` to scan a set of images manually specified in the command line. Useful for testing when you build new env images.
N/A
> ci: manual image scanning with anchore script.

- docs/sysadmin-deploy-on-k8s/install-on-kubernetes.txt
- harness/determined/deploy/__init__.py
- harness/determined/deploy/cli.py
- harness/determined/deploy/gcp/cli.py
- harness/determined/deploy/gke/cli.py
- harness/determined/deploy/gke/constants.py
I've inherited #2842 and did a minimal amount of changed and testing to make it mergeable. Compared to the original PR,
- rename to `gke-experimental` to better highlight the nature of the tool.
- fixed a number of lint issues.
- added auto-naming for node pools and buckets (because providing these by hand is unnecessary and confusing).
- some extra flag validation to avoid basic failures.
- make `down` operation actually work.
- destroy GCS bucket on `down`.
Basic:
1. `det deploy gke-experimental up --cluster-id <test-cluster-name>` (while in repo root, or pass `--helm-dir`)
2. kubectl get service determined-master-service-determined-gke -n default
3. export DET_MASTER=<ip address>:8080
4. Use it.
5. `det deploy gke-experimental down --cluster-id <test-cluster-name>`
There's a number of …
> feat: add `det deploy gke-experimental` [DET-5752]

- master/internal/config/config.go
when querying for jobs in k8s, the experiment actor crashes because it attempts to read the agent RM config, which is nil.
> fix: jq k8s nil pointer exception

- master/pkg/model/experiment.go
N/A
This fixes #3205 (or at least part of it). This was also fixed in #3037 but it hasn't landed yet.
> fix: typo in experiment state go to postgres enum mapping

- webui/react/src/components/TableFilterDropdown.module.scss
- webui/react/src/components/TableFilterDropdown.tsx
- webui/react/src/pages/ExperimentList.tsx
PROBLEM:
The states `DELETED`, `DELETING` and `DELETE_FAILED` are not supported on the experiment list API.
SOLUTION:
After discussing with UX, decided to clean up the state filters:
- remove all the transitive state filters that end in `ING`
- remove all the `DELETE` related state filters
BEFORE:
AFTER:
> fix: update experiment state filter [DET-6217]

- docs/release-notes/3199-historical-allocation-over-users.txt
- master/internal/command/command.go
- master/internal/db/postgres_experiments.go
- master/internal/db/postgres_jobs.go
- master/internal/db/postgres_tasks.go
- master/internal/db/postgres_trial.go
- master/internal/trial.go
- master/pkg/model/experiment.go
- master/pkg/model/job.go
- master/static/migrations/20211116131035_add-job-users.down.sql
- master/static/migrations/20211116131035_add-job-users.up.sql
- master/static/srv/update_aggregated_allocation.sql
- master/test/integration/api/api_trials_test.go
- master/test/testutils/mocks.go
Update persistence code and aggregations over persisted data so that aggregates over users are accurate for all tasks.
fairly straightforward
> feat: track historical allocation over users for all tasks

- agent/internal/docker.go
- docs/release-notes/3219-force-pull-image.txt
> feat: don't delete image before force_pull_image [DET-6145]

- webui/react/src/components/NavigationSideBar.tsx
- webui/react/src/components/NavigationTabbar.tsx
> chore: reorder where Model Registry appears in navbar

- webui/react/src/components/Icon.module.scss
- webui/react/src/components/Icon.tsx
- webui/react/src/pages/ModelRegistry.module.scss
- webui/react/src/pages/ModelRegistry.tsx
- webui/react/src/themes.ts
Since most people will discover Model Registry without any models created, add a link to the docs page to let them know how to use it.
> feat: add link to docs in Model Registry empty state

- webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.module.scss
- webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
Move model version details header buttons into overflow menu as screen shrinks.
> fix: overflow buttons on small screens

- webui/react/package-lock.json
for true public access from GitHub, we need to use the HTTPS protocol
instead of git+ssh from GitHub.
this was originally fixed in 9012a7855087b389b788fd84f227f06c24e3c98a 
and then put back in a later commit. 
> chore: prefer https over git for dependency

- harness/determined/deploy/gke/cli.py
> fix: clarify det deploy gke-experimental help text

- harness/tests/experiment/fixtures/tf_keras_one_var_model.py
- harness/tests/experiment/fixtures/tf_keras_xor_model.py
`flake8-bugbear==21.11.28` has got a new feature to find useless declarations. it doesn't quite like a couple of our classes where a class field was *before* a docstring.
`lint-python` should start passing again.
> ci: lint-python: readjust to fresh flake8-bugbear==21.11.28 release.

- webui/react/src/pages/ModelRegistry.tsx
> fix: stop Model Registry from showing empty message while loading

- .circleci/config.yml
- tools/scripts/scan-docker-images.sh
- Add a batch of fresh tf2 vulnerabilities to the list of tf1 ignores.
- Sort vulnerability codes in the output to make it more readable.
- Fix typo in CIrcleCI error message.
I didn't actually test this, but it's trivial enough.
> ci: docker image scan: update known tf1 vulns.

- docs/features/job-queue.txt
- docs/features/scheduling.txt
Adds new job queue docs and connects them to the existing scheduler docs.
> docs: adding job-queue docs

- master/internal/resourcemanagers/kubernetes/pods.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/sproto/task_actor.go
k8s previously did not update job status because we just throw pods at k8s and let it handle the entire lifecycle. This is a quality of life improvement for job queue that allows us to track whether the job is active or pending.
> feat: k8s exp status

- master/internal/api_job.go
- master/internal/job/job.go
- master/internal/resourcemanagers/agent_resource_manager.go
> fix: jq fix rp name check

- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/priority.go
Fixes two bugs:
- bug where the reported priority was always the default
- bug where master panics when calling `det job list`
> fix: det job get returns inaccurate info

- .bumpversion.cfg
> fix: update bumpversion config to account for new React config file

- master/internal/resourcemanagers/kubernetes_resource_manager.go
> fix: k8s webui error

- master/internal/api/stream.go
- master/internal/api_master.go
- master/internal/api_trials.go
- master/internal/db/postgres_filters.go
- master/internal/db/postgres_trial_logs.go
- master/pkg/model/experiment.go
This PR comprises two changes. First, it removes artificial waits added for backpressure, since [gRPC should handle this](https://github.com/grpc/grpc-go/blob/master/stream.go#L104-L122) at the http2 level by blocking whenever the receiver hasn't indicated they can receive (via window_update frames). Second, it touches up the SQL used to stream trial logs to rely on `WHERE id > $last_id AND LIMIT 1000` instead of `OFFSET N LIMIT 1000` since they should have equivalent results and the former can be filter in the index scan and the latter can't. This is still sub-optimal; the rewrite of task logs should follow with more concrete improvements since by design it is flexible to make breaking changes to the data model easily.
Any actual need for backpressure that arises after this should have a …
> perf: optimizations to trial logs streaming [DET-6262]

- master/internal/command/command.go
- master/internal/experiment.go
- master/internal/job/job.go
- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/resource_managers.go
- prepqueue.sh
- unset RP excluded job definitions
- unstable priority scheduler sorting
> fix: jq fix an issue with computing job order in priority scheduler

- Makefile
- cli/Makefile
- common/Makefile
`make test` was failing. 
#2108 moved the tests in ./common and ./cli into ./harness, but didn't remove their build targets. When `make test` was invoked it attempted to run pytest against missing directories. This removes `test-common` and `test-cli`, as they are now run as part of `make test-harness`. 
`make test`
> fix: remove old build targets

- webui/react/src/components/BadgeTag.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
- webui/react/src/pages/JobQueue/JobQueue.module.scss
- webui/react/src/pages/JobQueue/JobQueue.settings.ts
- webui/react/src/pages/JobQueue/JobQueue.table.tsx
- webui/react/src/pages/JobQueue/JobQueue.tsx
Remember selected RP 
Exp details to link to the job queue 
Update default job order
Show exp ids in the table 
> feat: jq webui persist selected resource pool

- webui/react/src/components/Spinner.stories.tsx
The full screen spinner story uses the `Page` component, which requires the `HelmetProvider` and the `StoreProvider` to function properly.
> chore: fix the spinner story

- harness/determined/common/api/b.py
- prepqueue.sh
- proto/src/determined/api/v1/api.proto
- webui/react/src/pages/JobQueue/JobQueue.tsx
- webui/react/src/services/api-ts-sdk/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
https://determined-community.slack.com/archives/C0269E3SMJP/p1631647360032000
> chore: jq update api paths

- master/internal/job/job.go
> fix: Jq read nil ptr

- webui/react/src/components/DownloadModelModal.tsx
- webui/react/src/components/InfoBox.module.scss
- webui/react/src/components/Table.tsx
- webui/react/src/pages/ModelDetails.module.scss
- webui/react/src/pages/ModelDetails.tsx
- webui/react/src/pages/ModelDetails/ModelHeader.module.scss
- webui/react/src/pages/ModelVersionDetails.module.scss
- webui/react/src/pages/ModelVersionDetails.tsx
- webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.module.scss
- webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
Mostly adjusting padding and margins after feedback from Alex.
> fix: various model registry tweaks

- master/internal/resourcemanagers/fair_share.go
- master/internal/resourcemanagers/job.go
- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/round_robin.go
- master/internal/resourcemanagers/scheduler_test.go
- proto/src/determined/job/v1/job.proto
- webui/react/src/pages/JobQueue/ManageJob.tsx
- webui/react/src/services/api-ts-sdk/api.ts
> test: jq add unit tests for job stats and order

- master/cmd/determined-master/migrate.go
- master/cmd/determined-master/root.go
- master/internal/command/api.go
- master/internal/command/command.go
- master/internal/command/command_manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/config/config.go
- master/internal/core.go
- master/internal/experiment.go
> chore: singleton config (jq)

- harness/determined/cli/job.py
Changes the output of `det job list` to match what the webui displays.
> fix: job cli returns different info from webui

- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/components/Table.tsx
- webui/react/src/components/TaskCard.tsx
- webui/react/src/components/TimeAgo.test.tsx
- webui/react/src/components/TimeAgo.tsx
- webui/react/src/components/TimeDuration.test.tsx
- webui/react/src/components/TimeDuration.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
- webui/react/src/utils/data.test.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/datetime.ts
Build `TimeAgo` and `TimeDuration` components to bring time ago display in-house (as opposed to relying on `timeago-react`) to be able to have more fine-grain control over the display format.
Build interaction tests for each component.
> refactor: customized timeago [DET-6244]

- webui/react/src/components/InlineEditor.module.scss
- webui/react/src/components/InlineEditor.tsx
- webui/react/src/components/Metadata/MetadataCard.tsx
- webui/react/src/components/NotesCard.tsx
- webui/react/src/components/TagList.tsx
- webui/react/src/pages/ModelDetails.tsx
- webui/react/src/pages/ModelDetails/ModelHeader.tsx
- webui/react/src/pages/ModelRegistry.tsx
- webui/react/src/pages/ModelVersionDetails.tsx
- webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
See title. Also adds ability to clear the InlineEditor.
> fix: add visual indicators that you can't edit an archived model [DET-6280]

- harness/determined/cli/job.py
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- webui/react/src/pages/JobQueue/JobQueue.table.tsx
> fix: k8s cli and webui

- webui/react/src/components/TaskCard.tsx
hide progress bar and numerical progress when there is no progress to report
> chore: avoid progress rendering for tasks card in some cases

- harness/determined/cli/model.py
Fix a failure in `det model list-versions --json <model name>` caused by wrong URL and 404 Not Found.
Run `det model list-versions --json <model name>`.
> fix: `det model list-versions --json`

- webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
> fix: update use in notebook code snippet [DET-6305]

- webui/react/src/pages/JobQueue/JobQueue.table.tsx
> fix: open task links in job queue in a new tab

- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/constants/states.ts
- webui/react/src/pages/ExperimentDetails/Header/ExperimentHeaderProgress.tsx
- webui/react/src/pages/ExperimentDetails/Header/ExperimentHeaderState.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/JobQueue/JobQueue.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
- add missing pause button in experiment detail page
> fix: fix experiment active state check in webui

- webui/react/craco.config.js
Applies browserify transformations for `plotly` libraries during our WebUI production build.
To test that this is working, run a `npm run build` and check to make sure HP Parallel Coordinates chart loads. If it's not built properly, this error will popup:
```
react_devtools_backend.js:2540 Error: (regl) Error compiling fragment shader, unknown
at Function.a [as raise] (6.8bea5242.chunk.js:2)
at Function.T [as shaderError] (6.8bea5242.chunk.js:2)
at Object.c [as shader] (6.8bea5242.chunk.js:2)
at 6.8bea5242.chunk.js:2
at Function.z [as optional] (6.8bea5242.chunk.js:2)
at o (6.8bea5242.chunk.js:2)
at j (6.8bea5242.chunk.js:2)
at U (6.8bea5242.chunk.js:2)
at Object.ce [as compile] (6.8bea5242.chunk.js:2)
at H (6.8bea5242.chunk.js:2)
```
See [Release Note](../docs/release-notes/README.md) …
> fix: add `ify-loader` to webpack config for proper `plotly` builds [DET-6330]

- webui/react/src/constants/states.ts
- webui/react/src/pages/JobQueue/JobQueue.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
addressing non-blocking comments from https://github.com/determined-ai/determined/pull/3295
> chore: reorganize webui fetchAll code

- webui/react/src/components/NavigationSideBar.tsx
- webui/react/src/pages/JobQueue/JobQueue.tsx
> chore: update job queue title and navigation entry

- CODEOWNERS
> chore: clean up code owners

- e2e_tests/tests/fixtures/metric_maker/metric_maker.py
- e2e_tests/tests/fixtures/no_op/model_def.py
- harness/determined/__init__.py
- harness/determined/_data_layer/_context.py
- harness/determined/_data_layer/_data_layer.py
- harness/determined/_execution.py
- harness/determined/_experiment_config.py
- harness/determined/_trial_context.py
- harness/determined/_trial_controller.py
- harness/determined/estimator/_estimator_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/exec/harness.py
- harness/determined/exec/launch_autohorovod.py
- harness/determined/experimental/_native.py
- harness/determined/horovod.py
- harness/determined/keras/_tf_keras_context.py
- harness/determined/keras/_tf_keras_multi_gpu.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/layers/_worker_process.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
- harness/tests/experiment/utils.py
Separating this change from native pytorch dtrain support.
> chore: remove hvd_config usage [DET-6220]

- harness/determined/_trial_controller.py
This change corrects usage of rank/cross_rank so that the profiler correctly knows it should collect metrics when local rank is 0.
> fix: collect metrics from all agents [DET-6332]

- master/internal/resourcemanagers/fair_share.go
- master/internal/resourcemanagers/job.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/round_robin.go
- master/internal/resourcemanagers/task_list.go
depends on https://github.com/determined-ai/determined/pull/3301
> chore: simplify job queue state tracking

- harness/determined/common/storage/gcs.py
- harness/setup.py
- Unpin google-cloud dependencies as we have no reason pinning them anymore.
- Pull in `pytz` which used to be a transient dependency but now is something we use directly.
- `mypy` doesn't quite like the new packages, so we disable it for a single method.
> chore: unpin google-cloud dependencies.

- e2e_tests/tests/experiment/experiment.py
Previously, if an experiment failed to complete within a timeframe, then
it failed to cancel within a timeframe, the trial logs were never
printed.
There was logic in place to try to avoid printing too many trial logs
when there was a mix of successful and failure trials in the same
experiment.  In practice, the number of e2e tests with multiple trials
is extremely low, but the edge cases where tests failed to show useful
logs was non-zero.  It's much better for developers to just always print
all trial logs when the wait_for_state fails.
[Example](https://app.circleci.com/pipelines/github/determined-ai/determined/17644/workflows/c63cd9c5-b76a-4935-845c-d3a642545066/jobs/540501/steps):
```
tests/experiment/test_tf_estimator.py::test_mnist_estimator_const_parallel[True] starting at …
```
> ci: print trial logs in more failure cases

- .circleci/config.yml
These tests got missed in go version bumps. Since they run `make -C master get-deps` and some upgraded deps may use go1.17 packages (io/fs) this is necessary.
> chore: bump test-e2e go version

- .circleci/config.yml
> ci: only install yq with snap.

- master/internal/core.go
This change just moves some initialization code around to clean up a data race found by `go run --race`. The race itself was that `grpcutil.RegisterHTTPProxy` tries to use the gRPC logger in a goroutine it spawns but that isn't initialized until `grpcutil.NewGRPCServer` runs, so there is a race writing/reading the global logger set by `grpclogrus.ReplaceGrpcLogger`.
> chore: fix small data race found by --race

- e2e_tests/tests/experiment/experiment.py
- master/internal/api_trials.go
This change updates `check_if_string_present_in_trial_logs` to follow trial logs, which makes it adhere to the master's loose attempt to delay until we think all logs should be here (this is hard to do accurately, but this at least should be better). Also loosen that delay up some more. It used to be 10s but I shortened it because it makes the CLI take too long to exit; 5s should be an OK compromise.
> chore: try to sidestep race in use of check_if_string_present_in_trial_logs test utility

- webui/react/src/components/JupyterLabModal.tsx
- webui/react/src/components/ResourcePoolCard.module.scss
- webui/react/src/components/ResourcePoolCard.tsx
- webui/react/src/components/ResourcePoolDetails.tsx
Static resource pool agents report a `-1` for `slotsPerAgent`.
1. Update resource pool to display `Unknown` instead of `-1`.
2. Update Launch JupyterLab to support slots # for when `slotsPerAgent` is -1.
> fix: negative slots per agent [DET-6357]

- master/internal/api_job.go
- master/internal/command/command.go
- master/internal/core_experiment.go
- master/internal/experiment.go
- master/internal/job/job.go
- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/resource_managers.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/resourcemanagers/resource_pool_test.go
- master/internal/sproto/task_actor.go
- proto/src/determined/job/v1/job.proto
- webui/react/src/pages/JobQueue/ManageJob.tsx
- webui/react/src/services/api-ts-sdk/api.ts
- reorganize msgs used for adjusting priority, weight, and q position
- add ahead_of and behind_of actions for updating job order replacing the exposed q_position
> chore: update relative job positioning api

- .github/pull_request_template.md
> chore: update GitHub pr template

- docs/release-notes/3372-fix-jupyterlab-fullconfig-edit.txt
- webui/react/src/components/JupyterLabModal.tsx
closes #3372 
I was thinking if there is a better/safer way of defining the types for launchJupyter.. that would have caught this but I didn't see a simple clean way of doing it short of changing the function or how it's used.
> fix: fix webui full config edit in notebook modal

- agent/go.mod
- agent/go.sum
- master/go.mod
- master/go.sum
This change bumps echo to drop the last indirect dependency on `github.com/dgrijalva/jwt-go` (even though it was unused by of code, this is useful otherwise, too).
blocked on #3352 
> chore: bump github.com/labstack/echo/v4 dependencies to address dependabot

- webui/react/src/hooks/useModal/useModal.tsx
- webui/react/src/hooks/useModal/useModalExperimentCreate.tsx
There are couple of issues identified related to this issue.
1) The modal component function props has a dependency on the modal state. However, the way it is written the modal props constantly changes, causing the `openOrUpdate` to constantly be called, which causes a rendering loop.
2) The experiment create submission was not throwing the errors properly to trigger a failure when there is a form error or when the submission endpoint call returns with a failure.
> fix: stop re-rendering loops and throw the appropriate errors for continue trial modal [DET-6368]

- bindings/generate_bindings.py
- harness/determined/cli/job.py
- harness/determined/cli/master.py
- harness/determined/common/api/bindings.py
- default to the most human-readable format out of the supported output formats.
I just broke these in https://github.com/determined-ai/determined/pull/3361
> chore: fix default format selection and Enum loading in cli

- e2e_tests/tests/cluster/test_checkpoints.py
When the checkpoint gc tests were written, checkpoint gc ran directly on
the same compute node as the experiment ran, so waiting for 35 seconds
for checkpoint gc to finish was a reasonable design.
Now that we run checkpoint gc in a separate resource pool which might be
empty, we need to actually wait for the checkpoint gc to run.  There's
still a hard-coded 5-minute timeout, but cpu instances usually don't
take too long to spin up, so that should be reasonable.
> ci: make checkpoint gc tests actually wait for gc

- harness/determined/cli/job.py
- webui/react/src/pages/JobQueue/JobQueue.tsx
setting a user selection of resource pool and a subsequent page load could get the job queue page into a render loop.
> fix: fix a conditional render loop

- master/internal/db/postgres_jobs.go
- master/internal/db/postgres_tasks.go
- master/internal/db/postgres_tasks_intg_test.go
- master/internal/db/postgres_users.go
This change fixes a bug in the mapping to and from the DB for `model.Allocation`s, which caused agent labels and slots to not get persisted.
eh.. 🤦 
> fix: add missing fields to allocation query and tests to prevent future bugs

- harness/tests/test_ipc.py
On MacOS, with python 3.9 (which is required to install tensorflow on Mac with Apple Silicon),
I see TestPIDServer tests fail, with similar stack traces:
```
for p in procs:
>               p.start()
tests/test_ipc.py:332:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../miniforge3/lib/python3.9/multiprocessing/process.py:121: in start
self._popen = self._Popen(self)
../../../miniforge3/lib/python3.9/multiprocessing/context.py:224: in _Popen
return _default_context.get_context().Process._Popen(process_obj)
../../../miniforge3/lib/python3.9/multiprocessing/context.py:284: in _Popen
return Popen(process_obj) …
```
> fix: avoid Can't pickle local object in TestPIDServer

- .circleci/config.yml
- e2e_tests/tests/config.py
- examples/computer_vision/unets_tf_keras/const.yaml
- examples/computer_vision/unets_tf_keras/distributed.yaml
- harness/determined/common/schemas/expconf/_v0.py
- harness/determined/deploy/aws/templates/efs.yaml
- harness/determined/deploy/aws/templates/fsx.yaml
- harness/determined/deploy/aws/templates/secure.yaml
- harness/determined/deploy/aws/templates/simple.yaml
- harness/determined/deploy/aws/templates/vpc.yaml
- harness/determined/deploy/gcp/constants.py
- helm/charts/determined/templates/master-config.yaml
- master/internal/resourcemanagers/provisioner/aws_config.go
- master/internal/resourcemanagers/provisioner/gcp_config.go
- master/pkg/schemas/expconf/const.go
- master/pkg/schemas/expconf/legacy_test.go
- model_hub/Makefile
- schemas/test_cases/v0/experiment.yaml
- tools/scripts/bumpenvs.yaml
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/experiment-details/set-a.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
Bump for https://github.com/determined-ai/environments/pull/129
[x] Test run: https://app.circleci.com/pipelines/github/determined-ai/determined/18084/workflows/504341b4-4d9d-4be0-a829-94bb786332c6
NGC confirmation - waited for over a day but it's still not ready.
> chore: bump env images for security.

- webui/react/src/components/Navigation.tsx
- webui/react/src/components/NavigationSideBar.tsx
- webui/react/src/components/NavigationTabbar.tsx
- webui/react/src/components/ResourcePoolCard.tsx
- webui/react/src/pages/Cluster/ClusterOverview.tsx
> fix: show correct total gpu capacity [DET-3733]

- harness/determined/common/schemas/expconf/_gen.py
- master/internal/resourcemanagers/kubernetes/spec.go
- master/pkg/model/environment_config.go
- master/pkg/schemas/zgen_schemas.go
- schemas/expconf/v0/environment.json
Allows the determined task pod to accept environment variables from the podspec.
Previously approved here: https://github.com/determined-ai/determined/pull/3368
> feat: allow podSpec env variables

- master/internal/job/job.go
> chore: validate priority and weight ranges

- .circleci/config.yml
- e2e_tests/tests/cluster/test_agent_restart.py
Inject test boundary markers from pytest into managed devcluster logs and store these as circleci artifacts to allow troubleshooting the flakes in this category of tests.
> ci: log test boundary markers to managed devcluster logs.

- webui/react/src/components/Avatar.test.tsx
> test: Create Avatar component test [DET-6404]

- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/task_list.go
- master/internal/resourcemanagers/task_list_test.go
> chore: update tasklist comparator

- .circleci/config.yml
- webui/tests/bin/e2e-tests.py
- webui/tests/bin/try-for-flakes.sh
- webui/tests/tests/StepImplementation.ts
- adds a missing await for taiko.focus which introduced an unexpected behavior
the sign in test passes without focusing as the username element should be in focus on page load to begin with
fixes #3447 
> test: await focusing username element

- webui/tests/tests/StepImplementation.ts
> fix: check that login input is visible before logging in

- webui/react/src/components/NavigationSideBar.tsx
- webui/react/src/components/NavigationTabbar.tsx
> fix: revert to prior slot utilization logic for static agents

- master/internal/db/postgres_tasks_intg_test.go
- master/internal/resourcemanagers/priority.go
Small refactor that gets rid of the sortTasks function
> chore: jq write remove sort

- webui/react/src/components/NavigationSideBar.module.scss
- webui/react/src/components/NavigationSideBar.tsx
Update nav sidebar to display full version when not collapsed
Manual tested with long and short version
> fix: update to show full version when nav sidebar is not collapsed [DET-6264]

- model_hub/examples/huggingface/token-classification/ner_config.yaml
NER example broke due to missing dataset at previous URL for conll2003.  This PR switches to conllpp which is a correct version of conll2003.
https://huggingface.co/datasets/conllpp
Tested experiment on a determined cluster.
We can consider switching back to conll2003 once a new URL is available.  
> fix: model-hub transformers ner example

- netlify.toml
> chore: update netlify address

- harness/determined/cli/job.py
> chore: cli to report job entity id

- master/internal/core.go
Since the gRPC HTTP proxy functionality currently requires the master to
know what port it's listening on, working with systemd socket activation
requires us to do more than simply using the passed listener: we also
need to figure out what port it's actually listening on. This change
allows the master to do that by inspecting various parts of
`/proc/self` (Linux-specific, but of course this only comes up under
systemd anyway). Figuring out this by reading a bunch of text files is
not the most reassuring process, but it's an interface exposed directly
by the Linux kernel, so it should be robust enough.
Alternatives would include getting the same information via the Netlink
interface (but the space of libraries here doesn't look that good) or
doing some magic with the listeners to make …
> fix: make systemd socket activation actually work
