- common/determined_common/experimental/checkpoint/_tf.py
- docs/topic-guides/checkpoints.txt
- harness/determined/keras/_tf_keras_trial.py
- tests/integrations/experiment/test_tf_keras.py
> [DET-2889] feat: checkpoint export tf.keras support

- cli/determined_cli/user.py
- master/internal/db/postgres_users.go
- master/static/srv/list_users.sql
> refactor: migrate users away from graphql

- docs/deploy/s3.tf
> fix: invalidate uploaded files to docs cloudfront distribution

- cli/determined_cli/experiment.py
- docs/tutorials/pytorch-mnist-tutorial.txt
- docs/tutorials/tf-cifar-tutorial.txt
- docs/tutorials/tf-mnist-tutorial.txt
> docs: Tweak example CLI output in tutorials

- docs/release-notes.txt
> docs: add 0.12.3 release notes

- combined-reqs.txt
- release-requirements.txt
> Remove ansible dependency to fix security vulnerability

- docs/how-to/install-main.txt
> docs: tweaks for installation instructions

- cli/determined_cli/cli.py
> feat: print full traceback when cli encounters an unexpected error

- docs/how-to/data-layer.txt
- docs/how-to/index.txt
- docs/reference/experiment-config.txt
- harness/determined/_data_layer/_context.py
> [DET-2250] docs: add docs how-to and experiment configurations for data-layer 

- docs/how-to/index.txt
- docs/how-to/use-trained-models.txt
- docs/reference/api/experimental.txt
I re-forked the repository. This is a continuation of https://github.com/determined-ai/determined/pull/197
> [DET-2271] feat: how-to use trained model checkpoints guide

- .circleci/config.yml
> Fix nightly tests

- examples/experimental/mnist_pytorch_multi_output/model_def.py
- examples/official/mnist_pytorch/model_def.py
> docs: update doc string for pytorch mnist examples

- cli/determined_cli/cli.py
- common/determined_common/util.py
- harness/determined/experimental/_native.py
Move some verbose log statements to only be printed when `$DET_DEBUG` is
active. Tweak hyperparameter logging message.
N/A
> feat: clean-up logging for LOCAL mode

- docs/deploy/s3.tf
> fix: update docs terraform config to create invalidation upon s3 upload

- master/pkg/agent/master_message.go
> chore: move timestamp to lead trial logs

- .circleci/config.yml
> test: notify ml-ag on nightly failures

- docs/how-to/use-trained-models.txt
> feat: add documentation for experiment level checkpoint export CLI

- .circleci/config.yml
- CI/integrations/Makefile
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/how-to/custom-env.txt
- docs/tutorials/quick-start.txt
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- master/pkg/model/defaults.go
- tests/integrations/config.py
> chore: update environment for notebook fix

- harness/determined/__init__.py
- harness/determined/_logging.py
- harness/determined/exec/harness.py
- harness/determined/experimental/_native.py
- harness/determined/keras/_tf_keras_trial.py
No need to test because it doesn't actually change any logic.
> [DET-2728] use a better message in WaitForInstructionsCallback

- tests/integrations/command/command.py
- tests/integrations/experiment/experiment.py
> chore: add stdout and stderr to integration logs

- cli/determined_cli/trial.py
- master/internal/core.go
- master/internal/core_trial.go
- master/static/srv/get_logs.sql
- master/static/srv/get_logs_limit.sql
- UI change:
Manually tested with running and stopped experiments.
> refactor: migrate trial logs away from graphql

- .circleci/config.yml
- tests/integrations/fixtures/estimator_dataset/const.yaml
- tests/integrations/fixtures/metric_maker/const.yaml
- tests/integrations/fixtures/mnist_estimator/adaptive.yaml
- tests/integrations/fixtures/mnist_estimator/single-multi-slot.yaml
- tests/integrations/fixtures/mnist_pytorch/adaptive_short.yaml
- tests/integrations/fixtures/mnist_pytorch/const-pytorch11.yaml
> Improve stability of e2e GPU tests

- docs/how-to/installation/requirements.txt
- docs/reference/cluster-config.txt
- docs/topic-guides/yaml.txt
> docs: minor fixes for master config file docs

- master/internal/core.go
- master/internal/core_experiment.go
- master/internal/db/postgres.go
> chore: reintroduce old experiment queries

- cli/determined_cli/checkpoint.py
- common/determined_common/experimental/__init__.py
- common/determined_common/experimental/checkpoint/__init__.py
- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/determined.py
> [DET-2890] Chexport checkpoint by UUID

- CI/integrations/Makefile
- CONTRIBUTING.md
- Makefile
- master/Makefile
> chore: remove unused master integration test targets

- combined-reqs.txt
- docs-requirements.txt
- docs/conf.py
> docs: add copy button to code snippets

- .circleci/config.yml
> ci: only download aws logs on failure

- cli/determined_cli/checkpoint.py
- cli/determined_cli/trial.py
- master/static/srv/get_trial.sql
> refactor: remove graphql dependency from trials

- docs/reference/api/estimator.txt
- docs/reference/api/keras.txt
- docs/reference/api/pytorch.txt
- harness/determined/_trial.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/pytorch/_pytorch_trial.py
rendered and tested docs locally
> docs: document trial __init__ functions

- master/internal/user/service.go
- lower the session expiry time to 7 days
- share the same constant with cookie expiry.
> feat: set session duration to 7 days

- Makefile
> chore: remove bump version target

- Makefile
- agent/Makefile
> chore: remove unused agent build target

- .circleci/config.yml
improve Circleci log output and timing.
> ci: pull cypress docker image in dependency set up step

- Makefile
> chore: remove unused PHONY target

- .circleci/config.yml
- Makefile
> chore: move commit message linter to new step

- deploy/determined_deploy/local/cluster_utils.py
- docs/how-to/installation/requirements.txt
- webui/tests/bin/createUserAndExperiments.py
See, e.g., https://www.apple.com/macos/.
> chore: fix references to Apple's OS, which is currently called macOS

- Makefile
> Clean root makefile

- .circleci/config.yml
This adds about 15 seconds to each PR, but I believe the benefits outweigh the cost of those 15 seconds.
- https://15335-253846879-gh.circle-artifacts.com/0/build/share/determined/master/webui/docs/index.html
> ci: store docs artifacts

- Makefile
> chore: move commit linter to check target

- Makefile
> chore: remove unused root build target

- Makefile
> chore: move phony targets to respective targets

- .bumpversion.cfg
- CONTRIBUTING.md
> Root doc cleanup

- .circleci/config.yml
- Makefile
- combined-reqs.txt
- requirements.txt
>  chore: combine root requirements files

- .mailmap
> chore: remove old mailmap file

- webui/tests/cypress/integration/02-loginout.spec.ts
- webui/tests/cypress/support/commands.js
- webui/tests/cypress/support/index.d.ts
> [DET-3026] login flake

- Makefile
> fix: add missing dep in build-docker target

- harness/determined/keras/_tf_keras_context.py
- harness/tests/experiment/fixtures/tf_keras_xor_model.py
- harness/tests/experiment/fixtures/tf_keras_xor_model_native.py
- harness/tests/experiment/keras/test_tf_keras_trial.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
- harness/tests/experiment/utils.py
> [DET-2436] test: add a test for tf.dataset with tf.keras native api

- .circleci/config.yml
> ci: use remote docker save/load for local tests

- scripts/lint-assert.sh
> chore: remove unused script

- cli/.gitignore
- cli/Makefile
- master/Makefile
> chore: simplify cli Makefile

- .bumpversion.cfg
- cli/determined_cli/__version__.py
- cli/setup.py
- common/determined_common/__version__.py
- common/setup.py
- deploy/determined_deploy/__version__.py
- deploy/setup.py
- harness/determined/__version__.py
- harness/setup.py
> chore: remove version dep from python packages

- harness/.gitignore
- harness/Makefile
- master/Makefile
> chore: simplify harness Makefile

- deploy/.gitignore
- deploy/Makefile
> chore: simplify det-deploy Makefile

- common/.gitignore
- common/Makefile
- master/Makefile
> chore: simplify commons Makefile

- docs/how-to/installation/aws.txt
- docs/how-to/installation/gcp.txt
Clarify AWS Keypair requirements and Cluster ID; other minor fixes.
- UI change:
> docs: improvements to AWS, GCP install docs

- .circleci/scripts/wait_for_master.py
> ci: bump wait_for_master time to five minutes

- .circleci/config.yml
> ci: fix e2e_tests splitting paths

- .circleci/config.yml
- master/Makefile
- webui/react/Makefile
- webui/tests/Makefile
> Webui make targets

- .circleci/config.yml
> ci: clean up Python venv creation

- .circleci/config.yml
- master/Makefile
- webui/elm/.gitignore
- webui/elm/Makefile
> build: clean up elm make file

- master/internal/core.go
> [DET-2974] perf: clean up master routes for webui

- docs/deploy/Makefile
> build: clean up docs deploy Makefile

- cli/determined_cli/master.py
- docs/reference/cluster-config.txt
- master/internal/core.go
> cli: Support dumping master config

- .circleci/config.yml
- e2e_tests/pytest.ini
- e2e_tests/tests/conftest.py
- e2e_tests/tests/experiment/test_tf_estimator.py
- e2e_tests/tests/experiment/test_tf_keras.py
> ci: separate tf1 and tf2 tests

- .circleci/config.yml
- Makefile
- master/.goreleaser.yml
- master/Dockerfile
- master/Makefile
> build: clean up master goreleaser file

- Makefile
- agent/Makefile
- master/Makefile
- tools/Makefile
- tools/agent.yaml
- tools/docker-compose.yaml
- tools/master.yaml
- tools/run-server.sh
> Cluster tool

- docs/how-to/distributed-training.txt
- docs/topic-guides/effective-distributed-training.txt
- docs/tutorials/data-access.txt
> docs: minor fixes for dtrain documentation

- .circleci/config.yml
- Makefile
- master/.goreleaser.yml
- master/Dockerfile
- master/Makefile
> build: clean up master build dir

- .circleci/config.yml
- Makefile
> Clean up root get-deps

- master/Makefile
> build: remove master install target

- deploy/Makefile
> build: reduce deploy build target output

- agent/Makefile
> chore: remove agent install target

- Makefile
> build: support parallel builds

- Makefile
> build: remove unused VERSION variable in root Makefile

- Makefile
> build: set root all target to build

- Makefile
> Parallel make targets

- Makefile
> fix: enable go modules for root get deps

- agent/tools.go
> fix: format agent tools file

- Makefile
- tools/Makefile
> build: clean tools dir on root level clean

- e2e_tests/tests/experiment/experiment.py
- e2e_tests/tests/experiment/test_native.py
- e2e_tests/tests/experiment/test_pytorch.py
- e2e_tests/tests/experiment/test_tf_estimator.py
- e2e_tests/tests/test_convergence.py
- e2e_tests/tests/test_system.py
> chore: remove hasura from integration tests

- master/internal/scheduler/filterable_view.go
- master/internal/scheduler/filterable_view_test.go
- master/internal/scheduler/summaries.go
> Cleanup for filterable view

- .circleci/config.yml
- tools/run-server.py
> feat: add temp db support to run-server

- cli/determined_cli/checkpoint.py
- cli/determined_cli/experiment.py
- common/determined_common/api/metric.py
> chore: remove hasura from cli

- docs/how-to/use-trained-models.txt
- More precisely describe the semantics of `top_n_checkpoints`.
- Add more links to the reference docs.
- Edit text generally.
> docs: edit guide on using trained checkpoints

- Makefile
> build: remove parallel support for make all

- tools/Makefile
> build: separate symlinks from tools run server step

- harness/determined/pytorch/_pytorch_trial.py
> fix: add missing "f" for format string

- common/determined_common/experimental/trial.py
> chore: rename best checkpoint to imply its a function

- webui/react/src/services/apiBuilder.ts
> [DET-3050] fix: set the ApiBuilder errorType based on the response code

- docs/how-to/installation/docker.txt
- docs/reference/cluster-config.txt
* Add Postgres container run command
* Add example for agent.yaml generation
* Provide config file and environment variable examples for master
and agent
> docs: add additional Docker install instructions

- harness/determined/_data_layer/_data_layer.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
Commit 8e74b749 changed some strs to ints, but TensorFlow isn't happy about that.
> fix: pass a string for visible devices, as TF expects

- master/internal/provisioner/agent_setup.go
- master/internal/provisioner/api.go
- master/internal/provisioner/aws.go
- master/internal/provisioner/gcp.go
- master/internal/provisioner/instance.go
- master/internal/provisioner/provisioner.go
- master/internal/provisioner/scale_decider.go
- master/internal/scheduler/filterable_view.go
> chore: provisioner cleanup, fix a minor bug

- CONTRIBUTING.md
- docs/how-to/install-main.txt
> docs: update contributing, install docs for recent changes

- cli/determined_cli/experiment.py
- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/checkpoint/_tf.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/experimental/_native.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/util.py
> [DET-3044] fix tf.keras checkpoint export

- Makefile
> build: remove commit message check

- agent/packaging/agent.yaml
- docs/reference/cluster-config.txt
> fix: use master_host in default agent config

- .circleci/config.yml
This removes one more manual step for release parties.
> ci: don't require approval for deploying release-.* branches

- .bumpversion.cfg
> build: tag git commit when using bumpversion

- cli/determined_cli/experiment.py
- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/checkpoint/_tf.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/experimental/_native.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/util.py
Revert of #459 due to failing `tests/experiment/test_tf_keras.py::test_iris`
> revert: keras checkpoint export

- .circleci/config.yml
> ci: use bigger clusters for release parties

- webui/react/package-lock.json
- webui/react/package.json
> chore: resolve a security vulnerability with node-sass

- webui/react/src/components/DeterminedAuth.tsx
update login docs link to match the recent changes around topic-guides
> fix: update login docs link

- CONTRIBUTING.md
> chore: update CONTRIBUTING.md to reflect how to run integration tests

- docs/release-notes.txt
`make`'d the docs locally, looks good!
Would like a quick sanity check against the release spreadsheet to ensure I'm not missing any commits we should add.
> docs: release notes for v0.12.4

- .circleci/config.yml
> ci: add author email to slack notifications

- docs/how-to/data-layer.txt
- docs/how-to/hyperparameter-tuning.txt
- docs/how-to/installation/aws.txt
- docs/how-to/installation/gcp.txt
- docs/how-to/notebook-configuration.txt
- docs/how-to/run-notebooks.txt
- docs/reference/cluster-config.txt
- docs/reference/index.txt
- docs/release-notes.txt
- docs/topic-guides/best-practices-model-definitions.txt
- docs/topic-guides/elastic-infra/dynamic-agents-aws.txt
- docs/topic-guides/elastic-infra/dynamic-agents-gcp.txt
- docs/topic-guides/elastic-infra/index.txt
- docs/topic-guides/optimizing-distributed-training.txt
* copy editing for elastic infra topic guide
* remove no-longer-supported stuff from notebook config doc
* tweaks for release notes
* other various copy editing
> docs: various fixes

- webui/react/package-lock.json
> fix: re-sync package-lock.json to package.json for react

- .circleci/config.yml
> ci: use determinedai/cimg-base:stable for try now publish

- .circleci/config.yml
> ci: install AWS CLI correctly for releasing docs

- .bumpversion.cfg
> build: change version tag syntax

- agent/.goreleaser.yml
- master/.goreleaser.yml
> build: don't skip_push since --snapshot handles this

- docs/topic-guides/users.txt
Compiled and checked the docs locally.
A bit of overlap with the rest of the documentation, but this is intended to give as much necessary information to get started as possible.
> docs: update Users docs for auto-login removal [DET-2992]

- .circleci/config.yml
> ci: remove 'v' from tag filters

- e2e_tests/tests/nightly/test_convergence.py
This regression was introduced by
https://github.com/determined-ai/determined/commit/c86899b548d62955bf7b0e476b37ab1ac035657e.
Example failure: https://app.circleci.com/pipelines/github/determined-ai/determined/1601/workflows/8b888735-0f4f-4229-9e37-b593d9d336a9/jobs/29543
Manually ran this test and observed that it did not fail due to `AttributeError`
> chore: fix nightly tests regression

- CONTRIBUTING.md
Add CONTRIBUTING guidelines.
Proofread.
> docs: Add CONTRIBUTING guidelines.

- master/internal/config.go
As reported by @vishnu2kmohan, we're printing checkpoint storage credentials in the "printable" master config. This change removes S3 storage credentials from printable.
> chore: remove creds in printable checkpoint storage [DET-3076]

- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
This callback will be called on the chief process that performs the checkpoint.
Added unit test.
> feat: add on_checkpoint_end PyTorch callback

- webui/react/src/hooks/useRestApi.ts
Fixes an issue where the method name could get logged as "undefined"
https://determinedai.atlassian.net/browse/DET-3087
> fix: set default http method name to GET

- tools/Makefile
Adds `make -C tools psql` for connecting to the local Postgres database
> build: add psql make target

- e2e_tests/tests/nightly/test_convergence.py
- examples/official/mnist_estimator/adaptive-advanced.yaml
- examples/official/mnist_estimator/const.yaml
- examples/official/mnist_estimator/distributed.yaml
- examples/official/mnist_tp/adaptive.yaml
- examples/official/mnist_tp/const.yaml
- examples/official/mnist_tp/distributed.yaml
Add convergence tests for the MNIST tensorpack example and the MNIST tf.estimator example in official.  https://determinedai.atlassian.net/browse/DET-3023
Tests require validation accuracy to be >95% after 20 steps.
> test: add convergence test for mnist_tp and mnist_estimator

- examples/official/multiple_lr_schedulers_pytorch/const.yaml
- examples/official/multiple_lr_schedulers_pytorch/data.py
- examples/official/multiple_lr_schedulers_pytorch/layers.py
- examples/official/multiple_lr_schedulers_pytorch/multiple_lr_schedulers_pytorch.py
> feat: add multiple lr schedulers example

- harness/setup.py
The new version handles random seeds of 0 correctly.
Tested as part of https://github.com/determined-ai/yogadl/pull/19
> feat: bump YogaDL version to 0.1.1

- webui/react/src/contexts/Auth.tsx
- webui/react/src/routes/index.ts
We will reset the (stale) authentication state only when the encountered error indicates that the user is unauthorized.
> chore: check error type before resetting authentication state

- harness/determined/pytorch/_callback.py
This callback was intended to be exposed as user-facing, but it doesn't fit in cleanly into a trial initialization cycle given that one of the arguments is the optimizer. Instead, users should implement the Reduce LR callback themselves like so: 
```
class ReduceLROnPlateauEveryValidationStep(PyTorchCallback):
def __init__(self, context):
self.reduce_lr = torch.optim.lr_scheduler.ReduceLROnPlateau(
context.get_optimizer(), "min", verbose=True
)
def on_validation_step_end(self, metrics: Dict[str, Any]) -> None:
self.reduce_lr.step(metrics["validation_error"])
def state_dict(self) -> Dict[str, Any]:
return self.reduce_lr.state_dict()
def load_state_dict(self, state_dict: Dict[str, Any]) -> None:
self.reduce_lr.load_state_dict(state_dict)
```
N/A
[DET-1234]: …
> chore: remove unused ReduceLROnPlateau callback

- e2e_tests/tests/experiment/experiment.py
Motivation is to avoid network flakes such as these: https://app.circleci.com/jobs/github/determined-ai/determined/34000
Will see over the next few nightly tests whether these sorts of flakes continue popping up. 
> test: ignore network errors when polling for experiment state

- docs/reference/api/pytorch.txt
> docs: add documentation for pytorch callbacks

- e2e_tests/tests/nightly/test_convergence.py
> test: add mnist_pytorch and object detection convergence test

- docs/Makefile
rebuild docs on each change to text files in `/docs` directory.
> build: add live target for docs to rebuild on changes

- e2e_tests/tests/nightly/test_convergence.py
Add tests to guarantee convergence to target metrics for `tf.keras` examples
[DET-3022](https://determinedai.atlassian.net/browse/DET-3022)
Tested manually on a 2-GPU GCP cluster with: 
```
pytest -vv -k tf_keras --master-host=... tests/nightly/test_convergence.py
```
[DET-3022]: https://determinedai.atlassian.net/browse/DET-3022
> test: add convergence tests for tf.keras examples

- harness/tests/experiment/pytorch/test_pytorch_trial.py
> test: add unit test for Multi LR Schedulers

- webui/react/src/components/DeterminedAuth.tsx
> feat: auto focus the username field on page load

- cli/determined_cli/agent.py
We previously used "id" or "agent_id" in the JSON output but "Agent
Name" in CSV and plaintext output. Use "Agent ID" in all cases now, for
consistency with what this value is called elsewhere.
> fix: use "Agent ID" instead of "Agent Name" in CLI.

- cli/determined_cli/experiment.py
- common/determined_common/__init__.py
- common/determined_common/_logging.py
- harness/determined/__init__.py
- harness/determined/exec/harness.py
- harness/determined/experimental/_native.py
Logging was not being enabled whatsoever in the code path of `det e create --local --test`.
> fix: enable logging with --local --test mode

- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_lr_scheduler.py
- harness/determined/pytorch/_pytorch_trial.py
> docs: fixes for PyTorch API docs.

- docs/release-notes.txt
> docs: release notes for 0.12.5

- examples/experimental/bert_squad_pytorch/const.yaml
- examples/experimental/bert_squad_pytorch/constants.py
- examples/experimental/bert_squad_pytorch/data.py
- examples/experimental/bert_squad_pytorch/distributed.yaml
- examples/experimental/bert_squad_pytorch/model_def.py
- examples/experimental/bert_squad_pytorch/startup-hook.sh
Example of fine-tuning BERT on SQuAD Dataset (compatible with both SQuAD1.1 and SQuAD2.0)  from https://github.com/huggingface/transformers/tree/master/examples/question-answering.
Tested in both single GPU and distributed training contexts on AWS p2.8xlarge instance, which consists of 8 K80 GPUs and 488 GiB of RAM. Expected F1 score of 88.52 on bert-base model upon completion.
> feat: BERT on SQuAD Dataset

- docs/requirements.txt
Incorporate https://github.com/determined-ai/determined_sphinx_theme/commit/accf3fbb639c88deb2e60293bdd15b3cae3afc01 in the docs build. 
Built on my local machine observed the dead links have been removed. 
> docs: update sphinx theme version

- webui/react/src/ErrorHandler.ts
- webui/react/src/utils/string.ts
The webui error handler accepts a public message to show for errors but when logging the message can sometimes show `undefiend` as part of the log statement.
> fix: properly stringify optional public message

- docs/topic-guides/model-definitions/native-api.txt
- examples/tutorials/native-tf-keras/README.txt
- examples/tutorials/native-tf-keras/tf_keras_native.py
- examples/tutorials/native-tf-keras/tf_keras_native_dtrain.py
- examples/tutorials/native-tf-keras/tf_keras_native_hparam_search.py
> docs: various fixes for Native API docs

- master/Makefile
> ci: fix changelog generation

- .circleci/config.yml
the target is now named `upload-try-now-template`
> ci: fix upload-try-now-template

- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/Determined.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
done as a part of [DET-2934]
[DET-2934]: https://determinedai.atlassian.net/browse/DET-2934
> refactor: separate API configs

- webui/react/src/App.tsx
- webui/react/src/components/NavMenu.stories.tsx
- webui/react/src/components/SideBar.tsx
- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/routes/index.ts
> refactor: remove additional determined routing [DET-3216]

- master/internal/agent/agent.go
- master/internal/agent/slot.go
- master/internal/agent/slots.go
- master/internal/api_agents.go
- master/proto/api/v1/agent.proto
- master/proto/api/v1/api.proto
> feat: add agent endpoints for new api

- proto/.gitignore
> chore: ignore pkg dir in proto sub project

- master/go.mod
- master/go.sum
- master/internal/api_master.go
- proto/src/api/v1/api.proto
- proto/src/api/v1/master.proto
- proto/src/google/protobuf/struct.proto
Sample Output to /api/v1/master:
```
{
"version": "0.12.5.dev0",
"masterId": "b023a809-a6da-4139-9f8b-99f54c40d348",
"clusterId": "0fbbf34d-20c4-43eb-baf3-8c179c352ad3",
"config": {
"checkpoint_storage": {
"host_path": "/tmp",
"save_experiment_best": 0,
"save_trial_best": 1,
"save_trial_latest": 1,
"storage_path": "determined-checkpoint",
"type": "shared_fs"
},
"config_file": "master.yaml",
"db": {
"host": "localhost",
"migrations": "file:///Users/yoni/Development/src/github.com/determined-ai/determined/tools/build/static/migrations",
"name": "determined",
"password": "********",
"port": "5432",
"ssl_mode": "disable",
"ssl_root_cert": "",
"user": "postgres"
},
"grpc_port": 8090,
"harness_path": "/opt/determined",
"http_port": 8080,
"https_port": 8443,
"log": {
"color": true,
"level": …
```
> feat: add master endpoint to new api

- agent/internal/agent.go
- agent/internal/container.go
- agent/internal/containers.go
- agent/internal/docker.go
- master/internal/agent/agent.go
- master/internal/agent/proto.go
- master/internal/agent/slots.go
- master/internal/command/command.go
- master/internal/scheduler/assignment.go
- master/pkg/agent/master_message.go
- master/pkg/container/container.go
- master/pkg/tasks/task_spec.go
- proto/src/agent/v1/agent.proto
> chore: remove container recovery

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/secure.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/deployment_types/vpc.py
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/constants.py
- deploy/determined_deploy/gcp/terraform/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/variables.tf
- deploy/determined_deploy/gcp/terraform/variables.tf
- docs/reference/cluster-config.txt
- docs/topic-guides/elastic-infra/dynamic-agents-aws.txt
- docs/topic-guides/elastic-infra/dynamic-agents-gcp.txt
- master/internal/config_test.go
- master/internal/provisioner/config.go
- master/internal/provisioner/config_test.go
- master/internal/provisioner/provisioner.go
- master/internal/provisioner/provisioner_test.go
- master/internal/provisioner/scale_decider.go
- master/internal/provisioner/scale_decider_test.go
- master/packaging/master.yaml
* feat: make agent starting period configurable
The provisioner would retry launching an agent after reaching
a duration, which is set by max agent starting period. Previously,
this configuration is hardcoded to 300 seconds. Now, change it to
be in the configuration of the provisioner.
DET-3219 #Done.
* test: update tests for max agent starting period
* chore: clean up provisioner code for better readability
* chore: clean up provisioner tests for better readability
* docs: update docs for agent starting period
* chore: update gcp deployment tool for agent starting period
* chore: update packaged master.yaml with agent starting period
* chore: update aws deployment tool with agent starting perioo
> feat: make agent starting period configurable [DET-3219]

- harness/determined/estimator/_callback.py
- harness/determined/estimator/_estimator_trial.py
- harness/tests/experiment/fixtures/estimator_xor_model.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
This will allow users to do any post-experiment cleanup they may need to do.
Added a test for this.
> feat: add end of training callback to EstimatorTrial [DET-3245]

- webui/react/src/components/Page.module.scss
- webui/react/src/components/Page.tsx
- webui/react/src/pages/Dashboard.module.scss
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/types.ts
I think a page is a common enough concept that merits its own component. page description, title, meta keywords, padding,  tab title etc
> feat: add page component [DET-3232]

- webui/react/src/components/DeterminedAuth.tsx
- webui/react/src/components/Link.module.scss
- webui/react/src/components/Link.tsx
- webui/react/src/components/NavItem.tsx
- webui/react/src/components/TaskCard.tsx
Update `Link` component to prevent unsafe cross-origin links.
> refactor: update link component to prevent unsafe cross-origin links

- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/pkg/searcher/message.go
This is the master side changes necessary to support returning these messages from the harness. The actual harness side changes will happen as separate work.
> feat: support USER_CANCELLED exited reason

- master/internal/api_templates.go
- master/internal/db/postgres.go
- master/internal/db/postgres_templates.go
- proto/src/api/v1/api.proto
- proto/src/api/v1/template.proto
- proto/src/template/v1/template.proto
Using postman:
- List empty templates
- Put 2 new templates
- List templates in asc and desc order
- Deleted a Template
- Put a template with a different body id than path id
- Deleted a non-existent template
- Upserted an existing template
- Fetched a non-existent template
> feat: add template endpoints to new api

- proto/Makefile
- proto/src/determined/agent/v1/agent.proto
- proto/src/determined/api/v1/agent.proto
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/master.proto
- proto/src/determined/api/v1/template.proto
- proto/src/determined/template/v1/template.proto
> chore: move proto files to determined namespace

- webui/elm/Makefile
Due to a mismatch between different instances of what should've been the
same name, the CSS file was getting built unnecessarily every time,
considerably increasing the Elm build time.
> fix: correct filename in Elm Makefile

- webui/tests/Makefile
> chore: remove yarn mentions from tests

- docs/release-notes.txt
(cherry picked from commit 071b3eb4129157640e46cd0e857fa510105f4541)
Pull in 0.12.5 release notes from the release branch.
> docs: release notes for 0.12.5 (#595)

- .circleci/config.yml
> ci: download protoc install to /tmp

- e2e_tests/tests/fixtures/metric_maker/metric_maker.py
- e2e_tests/tests/fixtures/no_op/grid-graceful-trial-termination.yaml
- e2e_tests/tests/fixtures/no_op/model_def.py
- e2e_tests/tests/test_system.py
- harness/determined/_train_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/experimental/_native.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/layers/_workload_manager.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/tensorpack/_tensorpack_trial.py
- harness/tests/experiment/keras/test_tf_keras_trial.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
- harness/tests/experiment/utils.py
> feat: support stopping training in trial code [DET-3238]

- webui/react/src/App.tsx
- webui/react/src/components/Link.tsx
- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
Problem: Clients sometimes load the WebUI and leave the session open. When they upgrade to a new version and restart the cluster, the open WebUI session is out of date and may not be able to communicate with the upgraded platform.
1. get master cluster up and running
2. open the WebUI in the web browser
3. change the version in the `master.yaml` file and restart the cluster.
4. check to make sure the WebUI opens an in-app notification regarding the version being out of sync.
> feat: ensure WebUI version is up to date with platform version

- e2e_tests/tests/fixtures/metric_maker/metric_maker.py
- e2e_tests/tests/fixtures/no_op/grid-graceful-trial-termination.yaml
- e2e_tests/tests/fixtures/no_op/model_def.py
- e2e_tests/tests/test_system.py
- harness/determined/_train_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/experimental/_native.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/layers/_workload_manager.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/tensorpack/_tensorpack_trial.py
- harness/determined/util.py
- harness/tests/experiment/keras/test_tf_keras_trial.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
- harness/tests/experiment/utils.py
This is the same PR as #648 but with fixes for dtrain.
> revert: "revert: "feat: support stopping training in trial code [DET-3238] (#648)" (#654)"

- master/internal/agent/agent.go
- master/internal/agent/slot.go
- master/internal/agent/slots.go
- master/internal/checkpoint_gc.go
- master/internal/command/command.go
- master/internal/scheduler/cluster.go
- master/internal/scheduler/cluster_test.go
- master/internal/scheduler/resource_provider.go
- master/internal/trial.go
This turned out a smaller changed than I had originally planned. Ended up just rewrapping agent messages in RP message. 
Existing test have us covered.
> feat: decouple agents from transmitting container status changes [DET-3174]

- webui/react/src/components/DeterminedAuth.tsx
> fix: set authentication failure reason synchronously.

- master/internal/trial_workload_sequencer.go
uses same strategy as run step
> feat: support early stopping callbacks on a validation step

- master/internal/grpc/api.go
- master/internal/grpc/auth.go
> feat: read cookies in the new API auth module

- master/internal/grpc/auth.go
> fix: set auth cookie path to apply site wide

- harness/determined/layers/_workload_manager.py
The expected behavior when we hit a NaN is to error the trial. This will restart the trial if we have not restarted `max_restarts` times.
> feat: treat NaN metrics as an error [DET-3237]

- e2e_tests/tests/experiment/test_pytorch.py
> test: temporarily disable AMP since it causes NaNs

- harness/determined/estimator/_estimator_trial.py
- harness/tests/experiment/fixtures/estimator_xor_model.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
- harness/tests/experiment/utils.py
> feat: support Estimator early stopping hooks [DET-3239]

- docs/faq.txt
Update FAQ based on question from [customer slack](https://determined-community.slack.com/archives/CV37XVAGL/p1591275220060000).
Tested by 👀
> docs: add to faq how to port a TF core model

- harness/determined/keras/_tf_keras_trial.py
- harness/tests/experiment/fixtures/tf_keras_xor_model.py
- harness/tests/experiment/keras/test_tf_keras_trial.py
- harness/tests/experiment/utils.py
> feat: support TF Keras EarlyStopping callbacks [DET-3240]

- webui/react/src/App.tsx
- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/contexts/Experiments.tsx
- webui/react/src/hooks/useRestApi.ts
- webui/react/src/pages/Dashboard.tsx
> refactor: set up experiments context [DET-3255]

- webui/react/src/components/DeterminedAuth.tsx
the last username used to log in with a Determined (non SSO) account would prefill the username field for subsequent visits to the login form.
Clearing the browser/site data would remove the "last username used"
This means that if a user logs once with a determined username "x" and logs in using SSO every subsequent time, they will still see the "X" show up in the username field every time.
> feat: remember last logged in username [DET-3274]

- webui/react/src/pages/TaskList.tsx
- webui/react/src/routes/index.ts
> feat: add task list page route and placeholder [DET-3220]

- webui/react/package-lock.json
- webui/react/src/components/DeterminedAuth.tsx
- webui/react/src/contexts/Experiments.tsx
> chore: remove unused variables

- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/experiment.py
- common/determined_common/experimental/trial.py
- common/determined_common/storage/base.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/layers/_workload_manager.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/util.py
- master/internal/core_checkpoints.go
- master/internal/db/postgres.go
- master/internal/experiment_utils.go
- master/pkg/model/experiment.go
- master/pkg/searcher/message.go
- master/static/migrations/20200605133712_add-checkpoint-format-fields.down.sql
- master/static/migrations/20200605133712_add-checkpoint-format-fields.up.sql
- master/static/srv/get_checkpoint.sql
- master/static/srv/get_checkpoints_for_experiment.sql
- master/static/srv/get_checkpoints_for_trial.sql
[DET-3272]
Checkpoint export writes out a `metadata.json` file to the checkpoint directory during training storing the experiment configuration, hyperparameters, and other relevant information (later used to load the checkpoint). This file doesn't currently contain the checkpoint metadata added as part of the model registry project. Additionally, the hparams and experiment configuration are queryable at download time and do not have to be written out to every checkpoint.
This PR will change the `Checkpoint.download` method to query the database in order to construct the `metadata.json` file. 
Current integration tests cover all code changed here.
I am manually testing creating checkpoints with the tip of master and loading them with the changes proposed here. This will sanity check the …
> feat: checkpoint export from database fields

- webui/react/package-lock.json
- webui/react/src/App.tsx
- webui/react/src/contexts/AppContexts.tsx
This issue was discovered during rebasing EE onto OSS.The `ssoProviders` field under `/info` is required for sign in, so it can not sit behind a component that only functions when authenticated, like the `AppContext`.
Check to make sure Sign In and version info work the same as before.
> fix: update /info to not require auth

- webui/react/src/components/DeterminedAuth.tsx
> feat: enable sign in button when last username is recalled

- .circleci/config.yml
- webui/Makefile
- webui/react/.gitignore
- webui/react/Makefile
- webui/react/package.json
sample build artifact: https://39839-253846879-gh.circle-artifacts.com/0/webui/react/build-storybook/index.html?path=/story/avatar--default
> build: build storybooks as part of CI [DET-3248]

- e2e_tests/tests/experiment/test_tensorpack.py
- e2e_tests/tests/experiment/test_tf_estimator.py
> fix: fix broken examples tests [DET-3321]

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/tutorials/quick-start.txt
- e2e_tests/tests/config.py
- harness/determined/keras/_tf_keras_trial.py
- master/pkg/model/defaults.go
New task environments fix gradient aggregation for TF2.
Will run full suite of tests.
> chore: bump task environments version

- examples/experimental/trial/bert_squad_pytorch/const.yaml
- examples/experimental/trial/bert_squad_pytorch/data.py
- examples/experimental/trial/bert_squad_pytorch/distributed.yaml
- examples/experimental/trial/bert_squad_pytorch/model_def.py
Fixing distributed training for BERT on SQUAD.
Tested on AWS EC2 p2.8xlarge Instance. Adding integration test for this soon.
> fix: data caching by rank for distributed setting [DET-2897]

- cli/determined_cli/user.py
- master/internal/db/postgres_users.go
- master/internal/user/api.go
- master/internal/user/service.go
Tested CLI manually.
List users:
```
(determined) ➜  cli git:(add-rename-user-to-cli) ✗ det user    
Username   | Admin   | Active   | Agent Uid   | Agent Gid   | Agent User   | Agent Group
------------+---------+----------+-------------+-------------+--------------+---------------
admin      | True    | True     | N/A         | N/A         | N/A          | N/A
determined | False   | True     | N/A         | N/A         | N/A          | N/A
```
Change `determined` -> `determined1`:
```
(determined) ➜  cli git:(add-rename-user-to-cli) ✗ det user change-username determined determined1
Failed to change username for user: Unauthenticated: Please use 'det user login <username>' to log in
```
Unauth 👍 
Login as admin and try again:
```
(determined) ➜  cli git:(add-rename-user-to-cli) ✗ det user …
```
> feat: add `det user change-username` to CLI [DET-3322]

- common/determined_common/experimental/checkpoint/_checkpoint.py
- docs/how-to/use-trained-models.txt
Documentation for the metadata feature of the model registry project.
[DET-3211]
Rendered the docs
[DET-3211]: https://determinedai.atlassian.net/browse/DET-3211
> docs: checkpoint metadata [DET-3211]

- e2e_tests/tests/nightly/test_capability.py
- e2e_tests/tests/nightly/test_convergence.py
> fix: fix nightly tests file locations

- docs/release-notes.txt
> docs: release notes for 0.12.7

- docs/faq.txt
- docs/how-to/tensorboard.txt
- docs/reference/api/keras.txt
- docs/topic-guides/experiment-lifecycle.txt
- harness/determined/keras/_tensorboard_callback.py
- harness/determined/keras/_tf_keras_trial.py
Also make a few tweaks elsewhere.
Proofread the new docs.
> docs: minor fixes for TensorBoard docs

- webui/react/src/components/TaskCard.stories.tsx
- webui/react/src/storybook/ConetextDecorators.ts
> feat: add context decorators and fix task cards story [DET-2982]

- .circleci/config.yml
- webui/tests/package-lock.json
- webui/tests/package.json
Cypress 4.3.0 to 4.8.0 [changelog](https://docs.cypress.io/guides/references/changelog.html#4-8-0)
> chore: update webui test dependencies

- master/internal/trial.go
When a trial terminates, if the process does not exit, the trial
container just sits there indefinitely; this can happen, for instance,
when model code spawns threads that don't terminate properly.
This change adds a timeout to trial termination: a fixed time after a
trial actor sends out a terminate message (whether the trial is
completely finished or just being paused), it sends a kill request to
the cluster.
Once a request for termination has been sent out, any task termination
errors are ignored, since the master has all it needs from the task;
whatever happens afterward is not really our concern.
Perhaps having a trial time out should count as an error, but it sounded
like hangs may be coming up in situations where it could be hard to fix
the hang (e.g., a third-party library …
> feat: add a timeout to trial termination [DET-3246]

- master/internal/api_auth.go
- master/internal/api_user.go
- master/internal/db/database.go
- master/internal/db/postgres_users.go
- master/internal/grpc/api.go
- master/internal/grpc/validate.go
- master/internal/user/service.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/auth.proto
- proto/src/determined/api/v1/user.proto
- proto/src/determined/user/v1/user.proto
- proto/src/google/protobuf/field_mask.proto
> feat: add user endpoints to new api

- docs/topic-guides/hp-tuning-det/index.txt
> docs: add info to topic guide for graceful trial termination [DET-3361]

- webui/elm/public/js/determined-shims.js
- webui/elm/src/Main.elm
- webui/elm/src/Msg.elm
- webui/elm/src/Ports.elm
- webui/elm/src/View.elm
Where there is a version mismatch between the WebUI and the cluster, on the React side a notification is shown to the user to refresh the app. Building the elm equivalent since they are separate single page apps that can individually be out of sync in terms of version.
> feat: Elm cache busting [DET-3287]

- harness/determined/_trial_controller.py
Remove is_chief calculation for non-horovod distributed training.
Use CI to run our test suite.
Nothing here.
> chore: remove is_chief calculation for non-horovod distributed training [DET-3338]

- common/determined_common/storage/gcs.py
I was unable to repro the behavior the failures so 🤷‍♂️-- but inspection of the log indicates this should work.
> feat: retry ConnectionError and ProtocolError types for GCS upload [DET-3331]

- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/determined.py
- common/determined_common/experimental/experiment.py
- common/determined_common/experimental/trial.py
- docs/how-to/use-trained-models.txt
- docs/topic-guides/checkpoints.txt
> docs: various improvements for checkpoint documentation

- master/internal/user/service.go
> chore: simplify logic in patchUsername [DET-3322]

- webui/elm/src/View.elm
- webui/react/src/components/NavBar.tsx
- webui/react/src/components/NavItem.tsx
> feat: link to swagger-ui from WebUI [DET-3350]

- deploy/determined_deploy/config.py
- deploy/determined_deploy/local/cluster_utils.py
- deploy/setup.py
> fix: "det-deploy local agent-up" works for remote master [DET-3386]

- master/pkg/model/defaults.go
- master/pkg/model/searcher_config.go
- master/pkg/searcher/adaptive.go
- master/pkg/searcher/adaptive_simple.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/sha.go
- master/pkg/searcher/sha_test.go
Rename AsyncHalvingSearch to SyncHalvingSearch since that is what we are actually doing.  This PR will be followed up with PRs to add AsyncHalvingSearch as a beta feature alongside our current adaptive.  
> refactor: rename asha to sha

- webui/react/.eslintrc.js
Running into the issue of multiple spaces in our code enough times, adding a rule to auto fix it when encountered.
> style: add linting to prevent multi-spaces

- webui/react/src/components/SideBar.tsx
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/components/TaskCard.stories.tsx
- webui/react/src/components/TaskCard.tsx
- webui/react/src/components/TaskFilter.tsx
- webui/react/src/components/TaskTable.stories.tsx
- webui/react/src/components/TaskTable.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/task.ts
- webui/react/src/utils/types.ts
required by the experiment list page.
> refactor: separate task types [DET-3395]

- webui/react/.eslintrc.js
- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/components/IconFilterButtons.module.scss
- webui/react/src/components/IconFilterButtons.stories.tsx
- webui/react/src/components/IconFilterButtons.tsx
- webui/react/src/components/TaskFilter.module.scss
- webui/react/src/components/TaskFilter.tsx
- webui/react/src/components/TaskTable.tsx
- webui/react/src/themes.ts
The icon filter buttons will be reused in the task list page, extracting the component to be reusable in advance.
Add storybook stories for extracted component.
> refactor: extract icon filter buttons from dashboard to be a reusable component

- webui/react/src/components/AuthToken.tsx
- webui/react/src/components/LogViewer.tsx
- webui/react/src/styles/index.scss
- webui/react/src/utils/dom.test.ts
- webui/react/src/utils/dom.ts
The clipboard API is only available for https and local development. Abstract the copy to clipboard capability since we have multiple places using this functionality and gives us the opportunity to handle the case of when clipboard is not available. 
example of when clipboard is available:
example of when clipboard is NOT available:
Two areas of copy to clipboard function in our webUI. One is master logs as `/det/logs` and the other is for EE CLI signin. When signing in at `/det/login?cli=1` on EE, a notification will appear to allow the user to copy the auth token to clipboard.
`latest-master` is a good location to check for the case when the clipboard is NOT available since it is currently on `http`.
> refactor: abstract reading and writing to clipboard [DET-3396]

- e2e_tests/tests/nightly/test_capability.py
- examples/experimental/trial/gbt_estimator/adaptive.yaml
- examples/experimental/trial/gbt_estimator/const.yaml
- examples/experimental/trial/gbt_estimator/model_def.py
- examples/experimental/trial/gbt_estimator/startup-hook.sh
Quick GBT example based on https://www.tensorflow.org/tutorials/estimator/boosted_trees. This is mainly for single and hyperparameter search as parallel/distributed training will not work due to the way the Estimator is constructed.
> feat: add GBT TF Estimator example

- webui/react/src/components/Link.module.scss
- webui/react/src/components/Link.tsx
- webui/react/src/components/TaskActionDropdown.module.scss
- webui/react/src/components/TaskActionDropdown.stories.tsx
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/components/TaskCard.module.scss
- webui/react/src/components/TaskCard.tsx
> feat: add no action state to task action dropdown [DET-3381] [DET-3393]

- webui/react/src/routes/index.ts
> feat: expose in development pages in dev

- webui/react/.eslintrc.js
- webui/react/src/components/LogViewer.tsx
- webui/react/src/components/TaskCard.stories.tsx
- webui/react/src/utils/dom.test.ts
- webui/react/src/utils/task.ts
> chore: raise Eslint check level for sort and unused variable rules.

- webui/react/src/pages/Cluster.tsx
removed agents to test no agent behavior.
> fix: set a fallback array for computing available resources [DET-3411]

- webui/react/src/components/TaskActionDropdown.stories.tsx
~this somehow slipped through CI. build cache?~ https://github.com/determined-ai/determined/pull/725
result of #753 and #750 happening around the same time
the function name was changed in pr 1 used in pr2 . pr1 landed before pr2 . pr 2 had alread passed tests against old master.
> fix: fix an import typo

- webui/react/src/components/TaskTable.tsx
- webui/react/src/table/columns.tsx
- webui/react/src/types.ts
- webui/react/src/utils/task.ts
- webui/react/src/utils/types.ts
> refactor: separate reusable task table columns

- master/internal/agent/agents.go
- master/internal/api_agents.go
- proto/src/determined/api/v1/agent.proto
> chore: clean up GET agents endpoint

- webui/react/src/components/SideBar.tsx
- webui/react/src/routes/index.ts
fix minor `key` conflict issue for `/ui/cluster` and `/dev/cluster` having the same id.
> fix: dev sidebar

- master/internal/api_model.go
- master/static/srv/update_model.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/model.proto
Patch endpoint to update model fields
Currently, testing is manual. The integration tests will cover these endpoints once we have a python client.
> feat: registry patch

- master/internal/api_trials.go
- master/internal/db/postgres.go
- master/static/srv/stream_logs.sql
- master/static/srv/trial_status.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/trial.proto
> feat: add trial logs to the new API [DET-3308]

- webui/elm/src/View.elm
The master logs was unwittingly exposed on the elm side. Disabling it temporarily until it is ready for public release.
> fix: hide master logs on elm

- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/components/ExperimentTable.module.scss
- webui/react/src/components/ExperimentTable.stories.tsx
- webui/react/src/components/ExperimentTable.tsx
- webui/react/src/components/ProgressBar.tsx
- webui/react/src/components/TaskTable.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/routes/index.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/string.ts
- webui/react/src/utils/time.ts
blocked by #741 
to keep this smaller created some subtasks to follow up.
https://determinedai.atlassian.net/browse/DET-3399
https://determinedai.atlassian.net/browse/DET-3398
> feat: add experiments table [DET-2998 DET-3015]

- common/determined_common/experimental/__init__.py
- common/determined_common/experimental/determined.py
- common/determined_common/experimental/model.py
- e2e_tests/tests/test_system.py
- harness/determined/experimental/__init__.py
> feat: model python class

- master/internal/trial.go
Timeout messages come after a minute, even if the container has closed and restarted and doesn't need to be killed.
Remember the number of resets from when the timeout message is sent and ignore it if another reset has occurred since it was sent.
> fix: ignore timeout messages after trial reset [DET-3434]

- webui/react/src/components/ResourceChart.tsx
- webui/react/src/pages/Cluster.tsx
> fix: avoid unnecessary re-rendering on each agent poll [DET-3427]

- master/internal/core.go
- load the swagger UI from both /swagger-ui and /swagger-ui/
> fix: fix relative asset paths for swagger-ui [DET-3437]

- cli/determined_cli/trial.py
- e2e_tests/tests/test_system.py
- master/internal/core_trial.go
- master/static/srv/get_logs_limit.sql
- master/static/srv/get_logs_offset_limit.sql
paginating fetching of trial logs through CLI. with the new API we will use the generated python SDK with streaming support and this would become a nonissue. 
tested with running a single trial long noop experiments and running
- `det trial logs 3`
- `det trial logs 3 -f `
- `det trial logs 3 -f --tail 10 `
- `det trial logs 3 --tail 10`
note that this does paginate when the tail option is used
> feat: paginated CLI trial logs [DET-3442]

- Makefile
- webui/Makefile
> fix: add a missing dependency step

- CONTRIBUTING.md
- webui/api-ts-sdk/Makefile
curl seems to be more widely available than wget. plus we need to declare the dependency.
https://curl.haxx.se/mail/lib-2012-11/0013.html#:~:text=All%20versions%20of%20OS%20X,come%20with%20curl%2Flibcurl%20installed.
> build: swap wget for curl and add it as a dependency

- webui/tests/.eslintrc.js
- webui/tests/package-lock.json
- webui/tests/package.json
`make clean get-deps check` fails in `webui/tests`
> fix: add missing sort-fix eslint plugin

- docs/examples.txt
- docs/reference/api/estimator.txt
- docs/reference/api/keras.txt
- docs/reference/api/pytorch.txt
- docs/reference/api/tensorpack.txt
> fix: fix broken docs examples link [DET-3462]

- webui/elm/src/Main.elm
- webui/elm/src/Route.elm
- webui/elm/src/View.elm
- webui/react/src/components/SideBar.tsx
- webui/react/src/routes/index.ts
- webui/tests/cypress/integration/02-navigation.spec.ts
- webui/tests/cypress/plugins/index.js
- webui/tests/package-lock.json
- webui/tests/package.json
The master logs and cluster page have been enabled ported over to React. We just need to update the navigation components on React and Elm to point to the migrated routes.
> chore: point cluster and master logs routes to react

- .circleci/config.yml
- webui/tests/bin/e2e-tests.py
- webui/tests/cypress/plugins/index.js
- webui/tests/cypress/support/index.js
- webui/tests/package-lock.json
- webui/tests/package.json
Remove the automatically logging all console logs during `webui-e2e-tests`, both locally and via CI.
> ci: remove cypress logs

- docs/release-notes.txt
> docs: release notes for 0.12.10

- webui/react/src/components/TableBatch.module.scss
- webui/react/src/components/TableBatch.stories.tsx
- webui/react/src/components/TableBatch.tsx
- webui/react/src/components/TaskTable.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/styles/antd.scss
- webui/react/src/utils/task.ts
> feat: task list batch [DET-3224]

- cli/determined_cli/model.py
Adds the CLI command for creating a model in the registry
Backing code already covered via an integration test.
> feat: model registry create CLI [DET-3280]

- common/determined_common/experimental/checkpoint/_checkpoint.py
- docs/reference/experiment-config.txt
- docs/topic-guides/checkpoints.txt
Clarify the assumption of shared fs checkpoint exporting in the documentation and error.
Test manually by downloading a shared fs checkpoint.
N/A
> docs: improve shared fs checkpoint exporting documentation. [DET-3392]

- .circleci/config.yml
> ci: ensure all release jobs have the proper filters [DET-3459]

- master/internal/api_trials.go
- proto/src/determined/api/v1/trial.proto
1) Got logs of an active trial with a limit and no follow
2) Got logs of an inactive trial with a limit and no follow
3) Got logs of an active trial without a limit and no follow
4) Got logs of an inactive trial without a limit and no follow
5) Got logs of an active trial with a limit and follow
6) Got logs of an inactive trial with a limit and follow
7) Got logs of an active trial without a limit and follow
8) Got logs of an inactive trial without a limit and follow
> feat: support follow flag in trial logs

- master/internal/api_experiment.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
- proto/src/determined/experiment/v1/searcher.proto
> feat: add preview search to new API

- proto/src/determined/api/v1/user.proto
> docs: update a misplaced comment reference

- webui/react/src/ioTypes.ts
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/routes/index.ts
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
- webui/react/src/types.ts
> feat: add experiments details page and endpoint [DET-3003]

- docs/reference/experiment-config.txt
> docs: add warning for `max_slots` [DET-3145]

- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/utils/types.ts
Looks like there were two methods of calculating active tallies in the codebase and they were incorrectly resolved (probably during refactor). This fixes it.
> fix: correct the active task counter on dashboard [DET-3510]

- docs/reference/experiment-config.txt
- docs/release-notes.txt
- docs/topic-guides/hp-tuning-det/index.txt
- harness/determined/pytorch/_callback.py
Also make some fixes to the release notes.
> docs: improve docs for graceful trial termination

- cli/determined_cli/agent.py
- cli/determined_cli/checkpoint.py
- cli/determined_cli/cli.py
- cli/determined_cli/experiment.py
- cli/determined_cli/master.py
- cli/determined_cli/notebook.py
- cli/determined_cli/remote.py
- cli/determined_cli/shell.py
- cli/determined_cli/template.py
- cli/determined_cli/tensorboard.py
- cli/determined_cli/trial.py
- cli/determined_cli/user.py
- common/determined_common/api/__init__.py
- common/determined_common/api/authentication.py
- common/determined_common/api/experiment.py
- harness/determined/experimental/_native.py
Added cli logging to native experiments.
Run python trial_impl.py --test in examples/official/native/native_mnist_pytorch
> feat: added cli logging to native [DET-3316]

- common/determined_common/experimental/model.py
- master/internal/api_model.go
- proto/Makefile
- proto/scripts/swagger.py
- proto/src/determined/api/v1/agent.proto
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/model.proto
- proto/src/determined/api/v1/trial.proto
- proto/src/determined/model/v1/model.proto
- webui/react/src/services/api.ts
> feat: clean up swagger spec

- examples/experimental/trial/unets_tf_keras/README.md
- examples/experimental/trial/unets_tf_keras/const.yaml
- examples/experimental/trial/unets_tf_keras/distributed.yaml
- examples/experimental/trial/unets_tf_keras/model_def.py
- examples/experimental/trial/unets_tf_keras/startup-hook.sh
> feat: add unets tf.keras example [DET-3397]

- cli/determined_cli/agent.py
- cli/determined_cli/checkpoint.py
- cli/determined_cli/cli.py
- cli/determined_cli/experiment.py
- cli/determined_cli/master.py
- cli/determined_cli/notebook.py
- cli/determined_cli/remote.py
- cli/determined_cli/shell.py
- cli/determined_cli/template.py
- cli/determined_cli/tensorboard.py
- cli/determined_cli/trial.py
- cli/determined_cli/user.py
- common/determined_common/api/__init__.py
- common/determined_common/api/authentication.py
- common/determined_common/api/experiment.py
- common/setup.py
- harness/determined/experimental/_native.py
> feat: added cli logging to native

- webui/elm/src/Main.elm
- webui/react/src/pages/Cluster.tsx
repeat after me: "in JS Array.push does NOT return the resulting array"
- re enables the old cluster page on `/ui/cluster` route
- fixes the mentioned issue
> fix: fix an issue with cluster resource computation [DET-3509]

- master/internal/api_model.go
- master/internal/core_checkpoints.go
- master/static/migrations/20200630141158_update-model-version-foreign-keys.down.sql
- master/static/migrations/20200630141158_update-model-version-foreign-keys.up.sql
- master/static/srv/get_checkpoint.sql
- master/static/srv/get_model_version.sql
- master/static/srv/get_model_versions.sql
- master/static/srv/insert_model_version.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/model.proto
- proto/src/determined/checkpoint/v1/checkpoint.proto
- proto/src/determined/experiment/v1/checkpoint.proto
- proto/src/determined/model/v1/model.proto
Endpoints for managing model versions.
Integration tests will cover this code when we land the python SDK
> feat: model versions endpoints [DET-3478]

- webui/react/src/components/LogViewer.module.scss
- webui/react/src/components/LogViewer.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/routes/index.ts
- webui/react/src/services/decoder.ts
This page will be accessible from the WebUI once this [ticket](https://determinedai.atlassian.net/browse/DET-3530) is done. For now it is accessible directly `/det/trials/<trial_id>/logs`.
> feat: react trial logs [DET-3128]

- webui/react/src/services/apiBuilder.ts
or we could override the silent option in the error handler for everything :thinking: 
> chore: don't silence api errors in dev

- docs/examples.txt
> fix: update examples link

- master/internal/core.go
The reloading of the WebUI apps do not work because `index.html` file is still cached until a manual hard refresh is invoked. Update the Go webserver to send response headers to tell the browsers to avoid caching the `index.html` files.
> chore: add response headers to bust cache for elm and react index.html [DET-3560]

- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/util.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
- harness/tests/experiment/keras/test_tf_keras_trial.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
- harness/tests/experiment/utils.py
1. Update all the Pytorch unit tests with the new interface.
2. Merge all unit tests for checkpoint and restoring.
3. Merge the unit tests for LR schedulers.
N/A
N/A
> test: update unit tests for Pytorch flexible primitives [DET-3200]

- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/Dev.ts
- webui/react/src/services/api.ts
- webui/react/src/services/apiBuilder.ts
based on https://github.com/determined-ai/determined/pull/819
commits starting with `temp:` are just here to demonstrate the usage and I'll remove them before landing the PR
> chore: set up browser NDJSON stream consumption [DET-3451]

- proto/src/determined/api/v1/api.proto
> docs: fix getModels endpoint documentation

- .circleci/config.yml
> ci: fix docs publish

- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/utils/types.ts
> feat: add simple Tensorboard launch action to UI [DET-3231]

- webui/react/src/ErrorHandler.ts
- webui/react/src/components/ExperimentInfoBox.module.scss
- webui/react/src/components/ExperimentInfoBox.stories.tsx
- webui/react/src/components/ExperimentInfoBox.tsx
- webui/react/src/components/Section.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/services/apiBuilder.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/string.ts
- webui/react/src/utils/task.ts
> feat: add experiment info box  [DET-3554 DET-3012]

- webui/react/src/App.tsx
Check for analytics library and the validity of the segment key:
32 characters composed of upper case letters, lower case letters and numbers 0-9.
> chore: validate segment key [DET-3505]

- master/internal/api_trials.go
- master/static/srv/stream_logs.sql
> fix: use local log line ids for trial logs

- e2e_tests/tests/nightly/test_distributed.py
Work around that pytest returns a non-zero exit code if there exist
no distributed tests.
No need to test.
N/A
> ci: work around there existing no distributed tests

- webui/tests/cypress/integration/02-navigation.spec.ts
Unable to diagnose the flake of `/det/logs` producing a `undefined` error. Cypress is no help in providing anything useful to determine the root of the cause. Under chrome browser (including `localhost:8081` for `make dev-tests`) the error does not occur, but if you rerun the `02-navigation.specs.ts` enough times you can reproduce the following error about 1 out every 10 times.
```
CypressError: The following error originated from your application code, not from Cypress.
> undefined
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
```
Skip the test for now until additional time can be allotted to figure out what the root cause is. I don't believe Cypress that this is an app code issue :)
- Tried both chrome headless and …
> test: e2e nav test flake [DET-3579]

- cli/determined_cli/experiment.py
- common/determined_common/api/__init__.py
- common/determined_common/api/experiment.py
- common/determined_common/experimental/checkpoint/_tf.py
- common/determined_common/experimental/checkpoint/_torch.py
- e2e_tests/tests/experiment/test_pytorch.py
- harness/determined/__init__.py
- harness/determined/_local_execution.py
- harness/determined/experimental/__init__.py
- harness/determined/experimental/_native.py
- harness/tests/experiment/test_local.py
Update Pytorch checkpoint exporting API to return a trial if it uses the new Pytorch trial interface otherwise returns the only model.
Test manually.
N/A
> feat: update Pytorch checkpoint exporting API [DET-3465]

- e2e_tests/tests/experiment/test_pytorch.py
fix PyTorch parallel test
Use a separate branch to run all the tests with CI.
N/A
> test: fix pytorch parallel test

- webui/react/src/ioTypes.ts
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
- webui/react/src/types.ts
needed for https://github.com/determined-ai/determined/pull/867
> feat: add basic trial details endpoint consumption [DET-3640]

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/how-to/custom-env.txt
- docs/reference/command-config.txt
- docs/reference/experiment-config.txt
- docs/tutorials/quick-start.txt
- e2e_tests/tests/config.py
- examples/experimental/trial/gbt_estimator/adaptive.yaml
- examples/experimental/trial/gbt_estimator/const.yaml
- examples/experimental/trial/unets_tf_keras/const.yaml
- examples/experimental/trial/unets_tf_keras/distributed.yaml
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- master/pkg/model/defaults.go
Update to task container version. This new version includes an updated Horovod version which fixes d-train for TF2 and
changes the default TF1 version from 1.14 to 1.15.
Tested manually as well as ran full suite of tests: https://app.circleci.com/pipelines/github/determined-ai/determined/3520/workflows/cf39b490-cf38-4067-b8c0-2492d57dffd2
> feat: switch to TF 1.15 and fix dtrain for TF2 eager execution [DET-3576, DET-3556]

- webui/react/src/pages/ExperimentList.tsx
fix an issue where the target branch changed but the tests had succeeded against an older target
> fix: fix a react build problem

- webui/react/src/components/Table.tsx
- webui/react/src/pages/ExperimentList.table.tsx
- webui/react/src/pages/TaskList.table.tsx
- fix a bug with task time parsing (only affect the time title)
- render start time on hover as local browser time
> fix: fix a parsing problem with tasks start time [DET-3657]

- webui/elm/package-lock.json
- webui/elm/package.json
- webui/react/package-lock.json
- webui/tests/package-lock.json
- webui/tests/package.json
> fix: upgrade lodash to fix vulnerability

- master/pkg/searcher/adaptive_asha_test.go
- master/pkg/searcher/asha_test.go
Added tests for the following:
* Allocation of max_trials across brackets for adaptive_asha
* Setting of max_concurrent_trials across brackets for adaptive_asha
* Asynchronous promotions for ASHA
N/A
> test: add additional tests for asynchronous adaptive

- harness/setup.py
> chore: loosen pyzqm requirements

- webui/react/.eslintrc.js
declare the project's Eslint config file as the root.
https://eslint.org/docs/user-guide/configuring#using-configuration-files-1
```
(node:887526) [ESLINT_PERSONAL_CONFIG_SUPPRESS] DeprecationWarning: '~/.eslintrc.*' config files have been deprecated. Please remove it or add 'root:true' to the config files in your projects in order to avoid loading '~/.eslintrc.*' accidentally. (found in "../../../../../.eslintrc")
```
> chore: suppress parent configs for eslint

- webui/react/src/ErrorHandler.ts
- webui/react/src/ioTypes.ts
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/routes/index.ts
- webui/react/src/services/apiBuilder.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- add trial details page
- more verbose logging on non-silent errors.
> feat: trial details page [DET-3011]

- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/Analytics.ts
- webui/react/src/App.tsx
- webui/react/src/ErrorHandler.ts
- webui/react/src/hooks/useRouteTracker.ts
Discovered that it's possible that `window.analytics` (segment analytics library) can be defined but not actually have the sub functions such as `page` and `identify` to be defined. Seems like they are incrementally initiated. This updates the logic around segment usage to correctly handle this behavior.
> fix: check for sub analytics functions before making calls [DET-3636]

- master/cmd/determined-master/init.go
- master/internal/config.go
- master/internal/core.go
- master/internal/grpc/api.go
- tools/master.yaml
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/services/apiBuilder.ts
- webui/react/src/utils/routes.ts
- add an option to set master to dev mode on startup 
- enable CORS on new APIs in dev mode
consume streaming trial logs endpoint through react dev server.
any name suggestion for this mode? We could also make the CLI option more specific to cors
--cors <bool> . thoughts?
or maybe --dev-mode <bool>
> feat: add development mode to master and enable CORS in dev [DET-3638]

- docs/release-notes.txt
> docs: release notes for 0.12.12

- webui/react/src/components/TaskCard.tsx
> chore: open command tasks in a new tab by default [DET-2623] [DET-3470]

- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/routes/index.ts
https://github.com/determined-ai/determined/pull/910 could have caught this :(
> fix: reorder react routes to match more specific routes first

- agent/internal/docker.go
Downgrade a message from a warning to an info and change the message to indicate it is not a failure, but just information.
Ever since I wrote this it's been killing me when I see it. Seems misleading.
> chore: downgrade warning to info and improve message

- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/components/LogViewer.module.scss
- webui/react/src/components/LogViewer.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiBuilder.ts
- webui/react/src/services/decoder.ts
Update trial logs to use trial log streaming endpoint.
> feat: streaming trial logs [DET-3536]

- docs/reference/api/pytorch.txt
- docs/topic-guides/model-definitions/best-practices.txt
- docs/tutorials/pytorch-mnist-tutorial.txt
- docs/tutorials/tf-mnist-tutorial.txt
- examples/experimental/trial/flexible_primitives_mnist_pytorch/model_def.py
- harness/determined/_trial.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/pytorch/_reducer.py
* Remove prohibition against early stopping
* get_hyperparameters -> get_hparams
* Better hyperlinks
> docs: various fixes for model definition and API docs

- webui/react/src/components/ResourceChart.tsx
> feat: show total resource count on cluster charts [DET-3558]

- webui/react/src/components/ExperimentActions.tsx
- webui/react/src/components/TrialActions.module.scss
- webui/react/src/components/TrialActions.tsx
- webui/react/src/components/types.ts
- webui/react/src/pages/TrialDetails.tsx
this adds 2 out of the 3 actions on trial details page and leaves out continue trial for another PR
> feat: add trial details actions logs and tensorboard

- webui/react/src/components/LogViewer.tsx
> feat: add pending state log viewer's download action [DET-3682]

- webui/react/.eslintrc.js
- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/components/ExperimentActions.tsx
- webui/react/src/components/Link.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/utils/task.ts
Add linting rule to auto detect and fix function parameters to either be on a single line or be on multiple lines individually.
> chore: add function parameter linting rule

- master/internal/trial.go
This change modifies the trial actor to track when it has been killed, so that it can use this information to avoid resetting itself when it receives the `scheduler.TaskTerminated` message from the scheduler. In the event a trial is killed, it makes more sense to _not_ reset the trial, since it cannot be restarted and it may be useful for users to see training and validation workloads that would be rollback in the event of a reset.
> fix: when trials are killed, do not rollback steps [DET-3691]

- webui/react/src/ioTypes.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
> fix: fix decoder for generic commands

- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/components/ExperimentInfoBox.tsx
- webui/react/src/pages/ExperimentDetails.tsx
> feat: add config modal to experiment detail [DET-3005]

- webui/react/.stylelintrc.js
- webui/react/src/components/Table.module.scss
- webui/react/src/components/TagList.module.scss
- webui/react/src/components/TagList.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentList.module.scss
- webui/react/src/pages/ExperimentList.table.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.table.tsx
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
> feat: add tag list component and add read/write for experiment labels [DET-3544]

- webui/react/src/App.tsx
- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/hooks/useRestApi.ts
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/MasterLogs.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
There is no feedback upon a batch kill on task list, so users are not able to discern if the batch kill is in progress, completed or any other state.
Fetch the updated task list to before unblocking the batch kill modal.
Shows a spinner next to the `Kill` button on the modal while the batch kill is running.
> chore: fetch upon task batch kill [DET-3665]

- webui/Makefile
- webui/api-ts-sdk/Makefile
- add missing get-deps and clean targets for api-ts-sdk
- remove a checked in dependency
- update the makefile format to use substitutes
> chore: add missing get-deps and clean targets for api-ts-sdk

- webui/react/src/Plotly.tsx
- webui/react/src/components/ResourceChart.tsx
- webui/react/typings/plotly.d.ts
Update the library path to use the correct pie library that `react-plotly` depends on.
> fix: update resource chart to use the correct library [DET-3721]

- webui/react/src/components/NavBar.tsx
Update the navbar agents button to point to new cluster page.
> fix: navbar cluster link

- harness/determined/estimator/__init__.py
- harness/determined/estimator/_estimator_context.py
- harness/determined/estimator/_reducer.py
- harness/tests/experiment/fixtures/estimator_linear_model.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
Address PR comments from last week (which were ignored since we were blocking a release), and also fix the custom reducer type bug that was exposed during release-party testing by @liamcli (but which was decided not to be a blocker).
Added unit tests to cover the breakage that was detected during the last release party.
> fix: support lists and dictionaries in make_metric [DET-3710]

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- e2e_tests/tests/config.py
- master/pkg/model/defaults.go
This pulls in the recent update to the Nvidia drivers in the AMIs.
> chore: update cloud AMIs.

- webui/react/.storybook/main.js
> fix: fix missing override from CRA [DET-3725]

- webui/react/src/ioTypes.ts
Fix the decoder issue of not handling `/agents` returning `null` for `container.agents`.
https://determined-ai.slack.com/archives/CKQ3EV0G6/p1596470224233300
> fix: correct the decoder for `/agents` endpoint

- master/pkg/agent/exit.go
> fix: handle case where exit code is not set

- .circleci/config.yml
- .circleci/scripts/gpu-daemonset.yaml
- e2e_tests/tests/experiment/test_tf_estimator.py
- e2e_tests/tests/experiment/test_tf_keras.py
- e2e_tests/tests/requirements.txt
Adding support for running full suite of e2e GPU tests and parallel tests on GKE as part of our CI. Added support for running automatically on merge for master branch, and on approval for all other branches. 
Ran the full suite of tests here: https://app.circleci.com/pipelines/github/determined-ai/determined/4009/workflows/f3e25e8f-b28d-447c-8c69-248d5ae9bc07
> test: add CI for k8s [DET-3652, DET-3653, DET-3654, DET-3655]

- cli/determined_cli/checkpoint.py
- cli/determined_cli/experiment.py
- cli/determined_cli/trial.py
- master/internal/db/postgres.go
- master/pkg/model/experiment.go
- master/static/migrations/20200729211811_extend-steps-table.down.sql
- master/static/migrations/20200729211811_extend-steps-table.up.sql
- master/static/srv/get_trial.sql
- master/static/srv/get_trial_metrics.sql
In the workloads sent to the harness, `total_batches_processed` represents the total batches processed prior to receiving that workload. This makes _some_ sense in the harness but almost none in a step. This change renames `total_batches_processed` to `prior_batches_processed` in the database and `model.Step` model.
> chore: rename total_batches_processed [DET-3723]

- common/setup.py
- master/internal/api_experiment.go
- master/internal/db/postgres.go
- master/internal/experiment.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
split from https://github.com/determined-ai/determined/pull/719
created experiments and tried pausing and activating them in different states
> feat: create activate and pause experiment [DET-3580]

- docs/reference/experiment-config.txt
- docs/topic-guides/hp-tuning-det/hp-adaptive-advanced.txt
- docs/topic-guides/hp-tuning-det/hp-adaptive-asha.txt
- docs/topic-guides/hp-tuning-det/index.txt
Add documentation for the adaptive_asha searcher.  
[DET-3449]
I have rendered the doc in rst format to make sure the syntax is correct. 
[DET-3449]: https://determinedai.atlassian.net/browse/DET-3449
> docs: add documentation for asynchronous adaptive searcher

- master/static/srv/entrypoint.sh
- master/static/srv/notebook-entrypoint.sh
Use the same logic in notebooks as in trials.
> fix: fix HOME in nonroot notebooks [DET-3751]

- helm/charts/determined/templates/master-deployment.yaml
- helm/charts/determined/values.yaml
This will support deploying EE on k8.
Tested this manually by deploying and old EE image on k8.
> feat: support private master images in helm

- webui/react/src/components/LogViewer.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/styles/index.scss
> feat: add modal confirmation for trial logs download [DET-3740]

- master/internal/api_templates.go
- master/static/srv/get_templates.sql
- master/static/srv/put_template.sql
- proto/src/determined/api/v1/template.proto
continuation of https://github.com/determined-ai/determined/pull/755
> feat: clean and add pagination to templates API [DET-3754]

- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
Minor fixes in warning messages.
> fix: fix PyTorchTrial warning messages

- common/determined_common/experimental/model.py
- common/determined_common/experimental/trial.py
- docs/how-to/use-trained-models.txt
- docs/reference/api/experimental.txt
- docs/reference/experiment-config.txt
- docs/topic-guides/checkpoints.txt
- docs/tutorials/index.txt
- docs/tutorials/model-registry.txt
Also make a bunch of improvements to other documentation for checkpoints.
> docs: revisions for model registry tutorial

- common/determined_common/storage/gcs.py
- e2e_tests/tests/experiment/test_noop.py
Tests for random state restoration were failing because gcs checkpoint upload caused the random number generator states to drift apart. This fix ensures that gcs checkpointing does not affect the random state. 
> fix: random number divergence on gcs checkpoint upload

- examples/official/trial/object_detection_pytorch/model_def.py
Tested by running on the release cluster.
> docs: fix object detetion example

- docs/reference/api/pytorch.txt
- examples/experimental/trial/bert_glue_pytorch/model_def.py
- examples/experimental/trial/bert_squad_pytorch/model_def.py
- examples/experimental/trial/imagenet_nas_arch_pytorch/model_def.py
- examples/experimental/trial/nas_search/model_def.py
- examples/experimental/trial/omniglot_protonet_pytorch/model_def.py
- examples/official/native/native_object_detection_pytorch/model_def.py
- examples/official/trial/mnist_gan_pytorch/model_def.py
- examples/official/trial/object_detection_pytorch/model_def.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
See https://determined-ai.slack.com/archives/C0147BBR61E/p1596632332013700
> chore: rename wrap_lrscheduler and return original scheduler

- docs/reference/api/pytorch.txt
Make migration guide easier to find and easier to link to.
generate docs, open page
> docs: promote PyTorch flexible primitives migration guide [DET-3771]

- e2e_tests/tests/nightly/test_capability.py
Bad rebase or something. See DET-3769 for fix.
Gonna run the tests
> test: disable imagenet_nas_arch_pytorch for release [DET-3770]

- e2e_tests/tests/nightly/test_capability.py
- examples/experimental/trial/imagenet_nas_arch_pytorch/model_def.py
Fix missing imports and merge and rebase conflicts from pytorch flexible primitives update.  
Tested locally and runs as expected.
> fix: imagenet_gaea merge and rebase conflicts [DET-3769]

- docs/tutorials/model-registry.txt
I think it's cleaner to talk about use-cases first before we get into the data
model.
> docs: tweak intro to model registry tutorial

- webui/react/src/components/Avatar.tsx
- webui/react/src/components/Link.tsx
- webui/react/src/components/ProgressBar.module.scss
- webui/react/src/components/ProgressBar.tsx
- webui/react/src/components/Table.tsx
- webui/react/src/components/TagList.module.scss
- webui/react/src/components/TagList.tsx
- webui/react/src/components/TaskActionDropdown.module.scss
- webui/react/src/components/TaskCard.module.scss
- webui/react/src/components/TaskCard.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
- webui/react/src/pages/ExperimentList.module.scss
- webui/react/src/pages/ExperimentList.table.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/styles/antd.scss
Fine tune styles relating to list tables.
> style: refine tables

- docs/reference/api/pytorch.txt
- docs/reference/experiment-config.txt
- docs/release-notes.txt
- docs/tutorials/pytorch-mnist-tutorial.txt
- harness/determined/pytorch/_callback.py
Small updates to docs as well to reflect PyTorch changes.
make docs and click around
(Sorry for the typo on the branch name)
> docs: release notes for 0.12.13

- proto/src/determined/api/v1/model.proto
- proto/src/determined/api/v1/tensorboard.proto
protoc complains (quietly) about unused imports.
> chore: silence protobuf warnings

- webui/react/src/components/TaskActionDropdown.tsx
Archive option
Unarchive option
> fix: show archive / unarchive options under task actions properly [DET-3635]

- webui/react/src/contexts/ClusterOverview.tsx
- webui/react/src/pages/Cluster.tsx
Handle disabled slots on both the dashboard and the cluster page.
> fix: filter out disabled slots for reporting

- webui/react/src/ioTypes.ts
- webui/react/src/services/decoder.ts
App breaks when the io-ts decoder encounters an unexpected `null` or `undefined` json property value. Apply the io union type of `null` or `undefined` to all properties that is defined as `null` or `undefined` so we don't have to guess which might come through.
> refactor: convert io.null and io.undefined to ioNullOrUndefined [DET-3747]

- docs/examples.txt
- docs/reference/api/pytorch.txt
- docs/reference/experiment-config.txt
- docs/release-notes.txt
- harness/determined/pytorch/_pytorch_context.py
* Document `records_per_epoch`
* Add some additional release notes for 0.12.13
* Various other fixes
> docs: various fixes.

- webui/react/src/components/Table.tsx
- webui/react/src/pages/TaskList.module.scss
- webui/react/src/pages/TaskList.table.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/utils/data.ts
> feat: add tensorboard sources to task list [DET-3760]

- master/pkg/searcher/sha.go
Previously, any operations that came about due to the promotion of a
trial that had already exited early were dropped, which could lead the
searcher to get to a state where it stopped emitting workloads while
trials were still active.
```yaml
searcher:
name: adaptive
metric: validation_error
target_trial_steps: 16
step_budget: 500
mode: standard
max_rungs: 3
divisor: 2
```
Without the fix, 12 of 30 experiments I ran got stuck; with it, I didn't see any out of 30 do so.
This will conflict with #968 and should probably wait for that, since it'll be easier to fix up this smaller PR.
> fix: don't ignore SHA operations from promotion of exited trials [DET-3546]

- e2e_tests/tests/fixtures/metric_maker/metric_maker.py
Only print messages on failures, rather than multiple times for every single metric.
Tests should still pass.
> chore: make metric_maker test quieter

- .circleci/scripts/upload_cloud_watch_to_s3.py
Cloudwatch limits one concurrent upload from from cloud formation. 
Tested locally by starting concurrent uploads and verified that we successfully complete all of them.
> test: handle concurrent cloudwatch CI uploads [DET-3713]

- examples/official/trial/mnist_gan_pytorch/model_def.py
> chore: minor fixes for PyTorch GAN example.

- webui/react/src/services/api.ts
- webui/react/src/services/apiBuilder.ts
> chore: change processApiError to return the error.

- README.md
- docs/index.txt
> docs: tweak index page text

- webui/react/src/services/decoder.ts
> fix: update regex to handle newlines in the log messages [DET-3804]

- deploy/determined_deploy/aws/aws.py
Rearranged the deletion order of resources. Added waiters to block for resources to stop or terminate before proceeding to next resource.
(I'm taking over for @seanr15 from #1039)
Manually tested with Determined clusters on AWS
> build: adjust resource deletion order [DET-3793]

- webui/elm/src/Page/ExperimentDetail.elm
- webui/elm/src/Page/TrialDetail.elm
> chore: route Elm experiment list links to react [DET-3827]

- webui/react/src/components/InfoBox.module.scss
- webui/react/src/components/InfoBox.tsx
- webui/react/src/components/Section.module.scss
- webui/react/src/components/Section.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentChart.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentChart.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.module.scss
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
> chore: infobox style update and refactor [DET-3796]

- webui/elm/src/Main.elm
- webui/elm/src/Page/TrialDetail.elm
- webui/elm/src/Route.elm
- webui/react/src/components/Breadcrumb.stories.tsx
- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/components/Page.module.scss
- webui/react/src/components/Page.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/utils/task.ts
- webui/react/src/utils/types.ts
- webui/tests/cypress/integration/01-setup.spec.ts
- webui/tests/cypress/integration/02-tasks.spec.ts
> feat: enable experiment detail [DET-3788]

- examples/experimental/trial/gaea_nas/const.yaml
- examples/experimental/trial/gaea_nas/data.py
- examples/experimental/trial/gaea_nas/genotypes.py
- examples/experimental/trial/gaea_nas/model_def.py
- examples/experimental/trial/gaea_nas/model_search.py
- examples/experimental/trial/gaea_nas/operations.py
- examples/experimental/trial/gaea_nas/optimizer.py
- examples/experimental/trial/gaea_nas/utils.py
Implement recent NAS method proposed in:
https://arxiv.org/abs/2004.07802
[DET-3553]
[DET-3553]: https://determinedai.atlassian.net/browse/DET-3553
> feat: add gaea nas [DET-3553]

- docs/faq.txt
> docs: add two new FAQs.

- docs/reference/experiment-config.txt
- e2e_tests/tests/config.py
- e2e_tests/tests/experiment/__init__.py
- e2e_tests/tests/experiment/experiment.py
- e2e_tests/tests/experiment/test_tf_estimator.py
- e2e_tests/tests/test_system.py
- master/internal/db/postgres.go
- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/pkg/model/experiment.go
- master/pkg/model/experiment_config.go
This change adds the ability to perform initial validations for trials. It also adds the concept of a zeroth step; it is special because it can be assumed to have a checkpoint, since we never train in a zeroth step. This simplifies rollback logic a lot - if anything is completed in a zeroth step (for now only validations), let it be (generally, we rollback to the last checkpoint).
I also found a master restart bug (not harmful but would print errors) that I missed in remove steps, to-do with how I was rolling back ACTIVE validations in `RollbackTrial`. This bug existed in master _before_ remove steps, but my fix I added in then was wrong.
> feat: add ability to perform initial validation [DET-3584]

- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
> feat: hide experiment max slots if it's unset

- webui/react/src/ioTypes.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/trial.ts
Set up types for training and validation metric names. Create utility function that extracts metric names from trial steps.
> chore: extract training validation metrics

- docs/tutorials/data-access.txt
> docs: minor fixes for data access tutorial

- webui/react/src/components/MetricChart.module.scss
- webui/react/src/components/MetricChart.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/ExperimentDetails/ExperimentChart.tsx
- webui/react/src/pages/TrialDetails.module.scss
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.module.scss
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
Needs [PR 1073](https://github.com/determined-ai/determined/pull/1073) to land first.
> feat: add trial detail chart [DET-3013]

- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/experiment.py
- common/determined_common/experimental/model.py
- common/determined_common/experimental/trial.py
Adds `__repr__` methods to python SDK classes for easier debugging.
> feat: repr methods for python classes [DET-3750]

- master/internal/db/postgres.go
This change adds total_batches_processed to `/trials/{id}/details` endpoint.
```
{
"end_time": "2020-08-14T15:27:01.217091+00:00",
"experiment_id": 1,
"hparams": {
"metrics_base": 0.9,
...
"total_batches_processed": 3000,
"steps": [
{
...
```
> feat: add total_batches_processed to trials details endpoint [DET-3872]

- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
The motivation of fixing the problem of [DET-3867](https://determinedai.atlassian.net/browse/DET-3867).
> chore: update archive/unarchive endpoint to the new api [DET-3867, DET-3871]

- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
Take the same approach as TensorBoard and Notebooks.
> fix: support shell with host networking mode

- webui/react/src/pages/TrialDetails.tsx
> fix: handle when config is undefined for trial length

- agent/internal/container.go
We experienced an experiment failure due to a container panic caused by an illegal state change. This patches the issue by making termination state transitions idempotent and adds a log statement for when the container attempts this state change.
> fix: Idempotent termination state transition [DET-3802]

- master/internal/api_trials.go
- master/internal/db/postgres.go
- master/internal/trial.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/trial.proto
the final logic for killing trials remains the same as the current endpoint and thus comes with the same behavior (eg DET-3828)
this makes the kill request idempotent from an external POV
- tried out the endpoint and the swagger ui
> chore: add kill trial endpoint [DET-3739]

- webui/react/src/components/Badge.tsx
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/SelectFilter.tsx
- webui/react/src/pages/TrialDetails.table.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
- webui/react/src/styles/antd.scss
- webui/react/src/types.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/trial.ts
> feat: trial table [DET-3019]

- webui/react/src/components/Badge.tsx
- webui/react/src/components/ProgressBar.tsx
- webui/react/src/components/ResourceChart.stories.tsx
- webui/react/src/components/ResourceChart.tsx
- webui/react/src/themes.ts
> fix: fix cluster resource pie chart color mapping [DET-3861] (#1094)

- master/internal/trial.go
We should always close a trial after setting t.killed, which should never get cleared.
> fix: actually kill trials [DET-3828]

- webui/react/src/styles/antd.scss
> style: fix table cell styles when there is only one cell

- webui/elm/src/Main.elm
- webui/elm/src/Page/ExperimentDetail.elm
- webui/elm/src/Page/TensorBoardList.elm
- webui/elm/src/Route.elm
- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.stories.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/services/decoder.ts
- webui/tests/cypress/integration/02-navigation.spec.ts
direct users to the new trial details page
should not land before https://determinedai.atlassian.net/browse/DET-3683
> chore: publish trial details page [DET-3843]

- docs/reference/api/keras.txt
- harness/determined/keras/_tf_keras_trial.py
This change adds a bit of clarifying documentation for the behavior of the `tf.keras.callbacks.Callback` when used with Determined.
> docs: add docs for behavior of keras's on_epoch_end callback

- webui/react/src/ioTypes.ts
- webui/react/src/services/decoder.ts
> fix: drop null metric values [DET-3910]

- master/internal/proxy/proxy.go
Previously, `getTargetURL` would attempt to assign through a nil
pointer in the case of an unknown service.
> fix: don't panic when an unknown service is encountered

- webui/react/src/components/InfoBox.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
> fix: show progress bar in experiment info box [DET-3922]

- docs/reference/experiment-config.txt
> docs: add remove steps migration guide

- docs/how-to/tensorboard.txt
- docs/reference/cluster-config.txt
- master/internal/command/tensorboard_manager.go
Document default value, update TensorBoard how-to.
> docs: improve docs for tensorboard_timeout.

- docs/faq.txt
- docs/how-to/tensorboard.txt
- docs/reference/api/pytorch.txt
- harness/determined/tensorboard/metric_writers/pytorch.py
> docs: fixes for PyTorch + TensorBoard docs.

- docs/reference/experiment-config.txt
> docs: minor tweaks to remove steps migration guide

- webui/react/src/pages/TrialDetails.table.tsx
> fix: remove id column from trial info table on trial detail page [DET-3940]

- docs/reference/experiment-config.txt
- docs/release-notes.txt
> docs: Release notes for 0.13.0.

- harness/determined/layers/_workload_manager.py
- harness/tests/test_workload_manager.py
The validation metric that is specified as the searcher metric is
supposed to take on only scalar numerical values, since we may need to
compare values of that metric for a hyperparameter search. Other parts
of the system (the raw trial details SQL query, at least) also assume
scalar values. However, the property wasn't actually explicitly checked
on input, so it was possible to successfully run an experiment
outputting non-scalar searcher metric values and not have anything go
wrong until a later database query exploded, as long as the searcher
never needed to make any comparisons.
This adds a check in the harness that the searcher metric only takes on
scalar values so that the issue is caught as soon as possible.
> fix: check that searcher validation metric values are scalars [DET-2134]

- webui/react/src/pages/TaskList.table.tsx
> style: enlarge task list table overflow trigger target [DET-3928]

- docs/release-notes/1161-custom-mult-select.txt
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/SelectFilter.tsx
- webui/react/src/styles/antd.scss
Ant Design's multiple select picker always defaults to showing tags in the selected values area. It's not great when the user has a lot of options selected because the area keeps growing to show every selected option as a removable tag. Instead, create a property that allows the old Elm behavior of showing `X selected` to just indicate how many options have been selected.
> feat: custom multi select [DET-3957]

- agent/cmd/determined-agent/run.go
- docs/faq.txt
- docs/reference/cluster-config.txt
- docs/reference/command-notebook-config.txt
- docs/reference/experiment-config.txt
* Document `resources.agent_label` in experiment/command config
* Document TLS options in agent config
* Add support for proxy-related settings to agent CLI
* Clarify docs for setting master and agent settings via env variables
* Add FAQ on using agent labels to influence task placement
> docs: fixes for agent config and agent labels [DET-3958][DET-2372]

- webui/react/Makefile
to allow running make without specifying a target.
running make with no target runs the first one.
> build: add default react make target for React module

- docs/reference/experiment-config.txt
> docs: add scheduling unit to migration table

- docs/reference/attributions.txt
Update WebUI attributions list with recently added packages.
> chore: update webui attributions list [DET-3979]

- docs/reference/experiment-config.txt
Add full experiment config example to remove_steps migration guide
docs: add full experiment config example to remove_steps migration guide
> docs: add full experiment config example to remove_steps migration guide [DET-3993]

- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/determined.py
- common/determined_common/experimental/experiment.py
- common/determined_common/experimental/model.py
- docs/reference/api/experimental.txt
> docs: Improve docs for Checkpoint-related APIs

- webui/react/src/components/AuthToken.tsx
- webui/react/src/components/Router.tsx
- webui/react/src/contexts/Auth.tsx
- webui/react/src/hooks/useAuthCheck.ts
~If we want to forgo having pages that do not require auth (other than login) one option is to move the auth check up a level and into app.tsx. there we can go with a different code path before engaging the router. without doing so the router has to send the user somewhere while it is waiting to check the auth status with server and that somewhere with this PR is the target component. going anywhere else would have the effect of seeing a route change~
> chore: perform authentication check in react router [DET-3929]

- webui/react/src/components/StateSelectFilter.tsx
- webui/react/src/types.ts
dashboard filter - experiment states and task states
experiment list filter - experiment states
task list filter - task states
> style: remove state filter groups [DET-3911]

- docs/release-notes/1147-dynamic-chart-range.txt
- webui/react/src/components/MetricChart.tsx
- Dynamically figure out the max range of chart based on the data points. Add 10% padding to each axis for the max range.
- Handle the case of when new data points come into A) preserve the zoom if previously zoomed in or B) resize the chart to show all the data points including the new data points.
> feat: dynamicaly update range based on provided data [DET-3923]

- master/internal/api_experiment.go
- master/static/srv/get_experiment.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
```
{
"experiment": {
"id": 1,
"description": "noop_single",
"labels": [],
"startTime": "2020-08-27T19:55:43.354294Z",
"endTime": "2020-08-27T19:55:47.205454Z",
"state": "STATE_ERROR",
"archived": false,
"numTrials": 1,
"progress": 0,
"username": "determined"
},
"config": {
"checkpoint_policy": "best",
"checkpoint_storage": {
"host_path": "/tmp",
"save_experiment_best": 0,
"save_trial_best": 30,
...
"smaller_is_better": true,
"source_checkpoint_uuid": null,
"source_trial_id": null
}
}
}
```
> feat: add GET /api/v1/experiment/id to the new api [DET-3753]

- deploy/determined_deploy/local/cluster_utils.py
Motivation for this change is to have a record of why CI sometimes fails waiting for master to come up.
> chore: dump docker logs before cluster-up times out [DET-3880]

- docs/release-notes/1200-fix-prior-batches-processed-backfilling.txt
- master/static/migrations/20200729211811_extend-steps-table.up.sql
- master/static/migrations/20200828140013_fixup-steps-prior-batches-processed.up.sql
This fixes an error in the migration to backfill `steps.prior_batches_processed` that results in incorrect numbers and takes extremely long to run.
I'm going to try to figure out how to make this query faster too, but I'm unsure right now.
> fix: fix prior_batches_processed backfill migration [DET-4006]

- examples/tutorials/native-tf-keras/README.txt
- examples/tutorials/native-tf-keras/tf_keras_native.py
* Quote the package / extra 'determined[tensorflow]' so that users using
shells like zsh that treat square brackets as a globbing characters don't
hit a "no matches found" error during prereqs.
* Add missing tensorflow import.
docs: minor tweaks to native API tutorial for copy/paste friendliness
> docs: minor tweaks to native API tutorial for copy/paste friendliness

- .circleci/config.yml
Still seeing issues, Returning to the original value of 4.
> ci: reduce e2e-cpu parallelism

- master/internal/scheduler/kubernetes_resource_provider.go
Updating this to keep parity with the default RP.
Tested manually on a k8 cluster.
> feat: support multi-GPU training < slotsPerNode for k8 RP

- webui/react/src/pages/TrialDetails/TrialChart.tsx
Default chart metric to be based on config searcher. If not available, fallback to first available metric from the list of metric names extracted from the data points.
> fix: default chart metric based on config searcher [DET-3934]

- docs/release-notes.txt
> docs: release notes for 0.13.1

- master/internal/scheduler/filterable_view.go
- master/internal/scheduler/fitting.go
> fix: update filterable_view to unfilter shared agent jobs

- docs/tutorials/data-access.txt
- harness/determined/keras/_tf_keras_trial.py
> docs: fix broken external links

- docs/release-notes/1170-add-user-preferences.txt
- webui/react/src/components/Table.tsx
- webui/react/src/pages/ExperimentDetails.table.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentList.table.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.table.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails.table.tsx
- webui/react/src/pages/TrialDetails.tsx
Save the following user preferences:
- Experiment list filters: Show Archive, State Picker, User Picker, Sort Column and Sort Order
- Task list filters: Task Types, State Picker, User Picker, Sort Column and Sort Order
- Experiment Detail Trial list filters: Sort Column and Sort Order
- Trial Detail page - table filters (has checkpoints) Will be leaving this task to be done by another [Ticket 3962](https://determinedai.atlassian.net/browse/DET-3962).
UPDATE
Experiment List table filters were already being saved.
Task List table filters were already being saved as well.
> feat: user preferences [DET-3719]

- docs/how-to/tensorboard.txt
> docs: fix download link

- docs/how-to/distributed-training.txt
- docs/reference/cluster-config.txt
- docs/topic-guides/determined-on-kubernetes.txt
> docs: fixes for k8s docs

- webui/react/src/components/Link.tsx
- webui/react/src/components/Navigation.tsx
- webui/react/src/utils/types.ts
Use `localhost:8080` instead of dev proxy of `localhost:3000` during development for
- task urls: Notebooks and TensorBoards
- API
- Docs
> chore: update notebooks, tensorboards, api and docs to dev proxy address [DET-3995]

- docs/how-to/installation/kubernetes.txt
- docs/reference/cluster-config.txt
- docs/reference/helm-config.txt
- docs/reference/index.txt
> docs: minor tweaks for cluster config / k8s docs

- docs/topic-guides/determined-on-kubernetes.txt
> docs: fix typo in k8s topic guide

- docs/how-to/installation/kubernetes.txt
- docs/index.txt
- docs/reference/command-notebook-config.txt
- docs/reference/experiment-config.txt
- docs/topic-guides/custom-pod-specs.txt
- docs/topic-guides/determined-on-kubernetes.txt
> docs: edits for k8s docs

- master/internal/command/command.go
- master/internal/core.go
- master/internal/scheduler/default_resource_provider.go
- master/internal/scheduler/kubernetes_resource_provider.go
- master/internal/scheduler/resource_providers_test.go
- master/internal/scheduler/scheduler_test.go
- master/internal/trial_test.go
Move registering and unregistering proxy out of the scheduler.
Use the CI test suite.
N/A
> chore: move proxy out of the scheduler

- webui/react/Makefile
ensure cp can copy over the latest API bindings
> build: ensure cp overwrites on all platforms

- examples/hp_search_benchmarks/darts/cnn/README.md
- examples/hp_search_benchmarks/darts/cnn/adaptive.yaml
- examples/hp_search_benchmarks/darts/cnn/const.yaml
- examples/hp_search_benchmarks/darts/cnn/genotypes.py
- examples/hp_search_benchmarks/darts/cnn/model.py
- examples/hp_search_benchmarks/darts/cnn/model_def.py
- examples/hp_search_benchmarks/darts/cnn/operations.py
- examples/hp_search_benchmarks/darts/cnn/utils.py
- examples/hp_search_benchmarks/darts/rnn/README.md
- examples/hp_search_benchmarks/darts/rnn/adaptive.yaml
- examples/hp_search_benchmarks/darts/rnn/const.yaml
- examples/hp_search_benchmarks/darts/rnn/data.py
- examples/hp_search_benchmarks/darts/rnn/model_def.py
- examples/hp_search_benchmarks/darts/rnn/optimizer.py
- examples/hp_search_benchmarks/darts/rnn/randomNAS_files/data_util.py
- examples/hp_search_benchmarks/darts/rnn/randomNAS_files/genotypes.py
- examples/hp_search_benchmarks/darts/rnn/randomNAS_files/model.py
- examples/hp_search_benchmarks/darts/rnn/randomNAS_files/utils.py
- examples/hp_search_benchmarks/darts/rnn/startup-hook.sh
Add hp search benchmarks from ASHA paper to examples.  
[DET-4048]
We have confirmed convergence to expected results.
[DET-4048]: https://determinedai.atlassian.net/browse/DET-4048
> feat: add hp search benchmarks to examples [DET-4048]

- master/internal/checkpoint_gc.go
- master/internal/command/command.go
- master/internal/scheduler/assignment.go
- master/internal/scheduler/default_resource_provider.go
- master/internal/scheduler/default_resource_provider_test.go
- master/internal/scheduler/group.go
- master/internal/scheduler/kubernetes_resource_provider.go
- master/internal/scheduler/resource_providers.go
- master/internal/scheduler/scheduler_test.go
- master/internal/scheduler/task.go
- master/internal/trial.go
Move starting tasks on containers out of resource providers.
N/A
Each commit serves a single purpose. It would be better to review it by commit.
> chore: move starting tasks on containers out of resource providers

- docs/release-notes/3866-warm-start-from-large-checkpoint.txt
- harness/determined/exec/harness.py
- master/internal/kubernetes/spec.go
- master/internal/trial.go
- master/pkg/tasks/task.go
There's a limit to how much data you can pass directly to an environment variable. This change modifies the harness to load checkpoint data as a file to prevent issues with warm starting from a large amount of checkpoint data.
> fix: pass latest checkpoint data as a file [DET-3866]

- docs/release-notes/1246-deprecate-dataflow.txt
- examples/experimental/trial/mnist_tp_to_estimator/const.yaml
- examples/experimental/trial/mnist_tp_to_estimator/const_visualize_synthetic.yaml
- harness/determined/_experiment_config.py
- harness/determined/estimator/_estimator_context.py
- harness/determined/estimator/_estimator_trial.py
deprecate dataflow_to_tf_datase
N/A
> chore: deprecate dataflow_to_tf_dataset [DET-3798]

- deploy/determined_deploy/local/cluster_utils.py
> fix: add missing cluster_name for det-deploy local

- CONTRIBUTING.md
> docs: Tweaks for CONTRIBUTING guidelines.

- webui/react/src/pages/ExperimentList.tsx
> fix: match key for experiment list name column for taglist renderer

- docs/release-notes.txt
> docs: Release notes for 0.13.3.

- CODEOWNERS
I did a first pass at ownership files/folders, but I'm likely off on some. Could folks please take a look and modify the file when necessary? Also, there are some features (like model registry) that are spread out over many files; I've tagged people who I might need input from on the review.
> chore: Add CODEOWNERS.

- webui/react/src/ioTypes.ts
code clean up to use the shorter more descriptive `optional(type)` vs `io.union([ioNullOrUndefined, type])`
> chore: switch ioNullOrUndefined decoder usage with optional

- proto/src/determined/api/v1/api.proto
- webui/react/src/components/Navigation.tsx
- add beta tag
- lower the version to below 1
> chore: communicate that the API is not fully stable yet [DET-4044]

- docs/release-notes/1276-tensorboard-sources.txt
- webui/react/src/components/Table.tsx
- webui/react/src/pages/TaskList.module.scss
- webui/react/src/pages/TaskList.table.tsx
- webui/react/src/pages/TaskList.tsx
**Motivation:** A dedicated sources column in the task list is mostly wasted space except for the tensorboard tasks.
Move the tensorboard sources out of the dedicated sources column and show a button that displays how many tensorboard sources there are. Add a modal that triggers when the button is clicked to show the full list of tensorboard sources with corresponding links.
**Future Work:** The next round of improvements can be applied when we have the experiment list endpoint that can take in specific list of experiment ids. We can then show a table of experiments and the corresponding info within the modal (such as number of trials, experiment name, etc).
> feat: tensorboard sources [DET-3797]

- e2e_tests/tests/fixtures/estimator_gpu_detection/model_def.py
Spun up a cluster with latest master and ran against it.
> test: fix estimator detect gpu test

- master/internal/core.go
This should fix a concurrent-write-to-map error seen in some test run
logs.
Unsure how to reproduce the bug in testing, but I think the bug should be clearly visible from the attached master panic output (see goroutines 99 (at the top) and 100 (at the bottom)).
[master_concurrent_writes.txt](https://github.com/determined-ai/determined/files/5202698/master_concurrent_writes.txt)
> fix: register gRPC proxy synchronously [DET-4140]

- docs/index.txt
`make build docs`
Somewhat annoyingly, it seems that Slack invites expire. This is probably okay for now though.
> docs: Add community links to documentation. [DET-4038]

- docs/index.txt
- docs/release-notes/1264-connection-checks-for-dynamic-agents.txt
Due to some other PRs that managed to cross paths with the last
formatting PR during the brief window it was open, the merged version
ended up not being correctly formatted. This fixes that by formatting
the docs again.
Oops. I considered previously that this might come up, but the other PR ended up going through quickly enough that I forgot to check (and I was expecting there to be conflicts if anything like this happened).
> style: update docs formatting

- master/internal/core.go
The echo server is sometimes getting endpoints registered concurrently
in CI.  I think this is the culprit, but I'm unable to reproduce
locally.
> fix: register ResourceProvider endpoints synchronously

- docs/release-notes/1273-table-row-middle-click.txt
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/utils/routes.ts
Create isolated example of `useAuxClick` in codesandbox to confirm linux users see the correct behavior.
> feat: middle mouse support for table rows [DET-3840]

- master/internal/api_experiment.go
- proto/src/determined/api/v1/experiment.proto
- webui/react/src/services/api.ts
- webui/react/src/types.ts
add labels  query parameter to experiments endpoint
> feat: add labels query parameter to experiments endpoint [DET-4098]

- docs/release-notes/1266-update-trial-detail-table-filters.txt
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/SelectFilter.module.scss
- webui/react/src/components/SelectFilter.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/styles/antd.scss
- Update trial table to only select default config searcher metric by default
- Add searching capability to metric select filter for large metric lists
Search example:
> fix: default trial table metrics [DET-4096]

- proto/src/determined/api/v1/auth.proto
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/tests/cypress.env.json
- webui/tests/cypress/constants.ts
- webui/tests/cypress/integration/01-setup.spec.ts
- webui/tests/cypress/integration/02-loginout.spec.ts
- webui/tests/cypress/support/commands.js
- webui/tests/cypress/support/index.d.ts
- webui/tests/cypress/support/index.js
- webui/tests/cypress/tsconfig.json
Migrate over to new login api.
> refactor: new api login [DET-4014]

- webui/react/src/services/apiBuilder.ts
> test: simple support for stubbing API responses.

- docs/release-notes/1272-save-table-page-size.txt
- webui/react/src/components/Table.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails.tsx
Save table page size for all tables to user preferences on WebUI.
> fix: save table page size in user preferences [DET-4012]

- master/internal/api_tensorboard.go
tensorboards actor address, unlike other command actors, is not plural.
> fix: fix tensorboards base address [DET-3833]

- docs/release-notes/1291-improve-wait-page-loading
- master/internal/core.go
- webui/react/public/wait/wait.js
command `is_ready` used to be unreliable but that's fixed now https://determinedai.atlassian.net/browse/DET-2467 and we can remove an stopgap we had put in place. opening notebooks and tensorboards through the UI should much faster now especially if it's not the first launch.
https://determined-ai.slack.com/archives/C6D7MDSQ5/p1600112931018100
> chore: improve wait page loading [DET-3225]

- docs/release-notes/1269-multiple-metrics-on-one-chart.txt
- webui/react/src/components/MetricChart.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
Add support for displaying multiple metric charts on trial detail.
> feat: multiple metric chart [DET-3927]

- webui/react/src/components/TableBatch.stories.tsx
- webui/react/src/components/TableBatch.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
Update table batch component to show # of selected items.
Checked working app and working storybook.
Screenshots:
[DET-4047]: https://determinedai.atlassian.net/browse/DET-4047
> chore: webui update TableBatch component to show # of selected items [DET-4047]

- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialActions.tsx
This PR addresses the request of the JIRA issues. 
App working fine.
> chore: webui disable "continue trial" when there are no checkpoints [DET-3850]

- docs/release-notes/1293-lazily-open-tensorboard
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TrialDetails/TrialActions.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/types.ts
- webui/react/src/types.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/types.ts
avoid launching new tensorboards if there is already one running that exactly matches the requested tensorboard.
> feat: lazily launch TensorBoards [DET-4156]

- webui/react/src/ioTypes.ts
We had a change to the event response shape in
04bd4fe469eced74c56d71bf4ceb72bc4b74ca23 to command log endpoint responses. This updates the WebUI
expectation to match the changes.
> fix: update command logs response expectation [DET-4167]

- docs/release-notes/1306-remove-tensorboard-source-column.txt
- webui/react/src/pages/TaskList.table.tsx
- webui/react/src/utils/data.ts
Check to make sure the `Sources` column doesn't exist on task list page and check the sources button still appear below the experiment name.
> fix: remove tensorboard source column from task list [DET-4173]

- webui/react/src/components/StateSelectFilter.stories.tsx
- webui/react/src/components/StateSelectFilter.tsx
This PR addresses the request of DET-4039 JIRA issue.
Note that storybooks are still not working on master due to serverAddress issue (addressed in this PR: https://github.com/determined-ai/determined/pull/1240/commits).
Storybook working fine.
Screenshots:
> chore: webui react storybook for StateSelectFilter component [DET-4039]

- webui/react/src/components/Navigation.stories.tsx
- webui/react/src/components/UserSelectFilter.stories.tsx
- webui/react/src/components/UserSelectFilter.tsx
- webui/react/src/storybook/ContextDecorators.ts
This PR addresses the request of the JIRA issues and adds some fixes to make a function (serverAddress) reachable by storybooks. Attached 
Storybook working fine. App loading.
Attached screenshot of the error message that got fixed and of the resulting storybook.
> chore: create storybook stories for Navigation and UserSelectFilter components [DET-4013] [DET-4041]

- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/templates/master-deployment.yaml
- helm/charts/determined/templates/master-permissions.yaml
> fix: fix typo in Helm chart [DET-3781]

- webui/react/src/hooks/usePolling.ts
The polling function creates multiple threads of polling if the polling function changes rapidly. One use case encountered that causes this is when we are change query parameters or filters for a list based endpoint. For example when we type in a search string in the search box for experiment list page.
I don't know of a way to test for this without console logging inside the polling function. The easiest for a dev to test this is to put a `console.log('fetchExperiments', sorter, pagination, filters, search);` inside the `fetchExperimentList` function around line 129 and then type in the search box about 4 characters quickly and see the console logs popup in sets of 4 every 5 seconds. If this is fixed, this console log should be limited to 1 every 5 seconds.
See [Release …
> refactor: prevent rapid polling calls from making multiple polling timers [DET-4183]

- docs/release-notes/1317-webui-use-async-polling.txt
- webui/react/src/hooks/useRestApi.ts
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/services/types.ts
**NOTE:** This PR has changes from [PR 1316](https://github.com/determined-ai/determined/pull/1316).
Update the experiment and trial detail pages to use cancelable async functions for polling functions, in order to be able to block the subsequent polling from running if the previous polling has not been resolved yet. Avoid using the `useRestApi` hook and directly use the generated async old API function. The issue with `useRestApi` is that during the hook setup, the resulting promise of the rest call is not exposed, instead a trigger function is returned. If provided the `promise` in the state from the `useRestApi` hook, not sure if that would make it any easier to block the polling function, but it is a possibility.
The way to test this is to find a very long experiment that has a lot of …
> refactor: use async polling [DET-4182]

- master/pkg/actor/actor.go
- master/pkg/actor/response_test.go
This change is fairly useful for creating dummy actors (for instance, a trial logger) while avoiding a lot of boiler plate.
Zero impact change, but it will be tested by being used in tests.
Opening this separately because I don't want to just open some mega pr for all the tests I'm trying to write.
> chore: add helper to register functions as actors

- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/gcp.py
- deploy/determined_deploy/gcp/terraform/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
- deploy/determined_deploy/gcp/terraform/variables.tf
- deploy/setup.py
- docs/how-to/installation/gcp.txt
> feat: "det-deploy gcp down" deprovisions dynamic agents [DET-4155]

- docs/topic-guides/terminology-concepts.txt
> docs: fix phrasing from Tensorpack removal

- e2e_tests/tests/nightly/test_capability.py
Missed these when removing TensorpackTrial yesterday.
> test: remove nightly tensorpack tests

- README.md
- docs/index.txt
We probably want to add some more content to both places (the new content is
fairly short), but for now it's important to keep the GitHub/docs messaging
aligned with what's on the website.
> docs: Revise README and docs landing page

- docs/conf.py
This is important for SEO; because we publish many versions of the docs, we need
to clarify which version is the "canonical" one to avoid being penalized by
search engines.
Looked at the generated HTML, ensured that the expected `<link rel="canonical" ...>` tags show up for several different pages.
> docs: ensure canonical URLs are set for generated doc pages

- helm/charts/determined/values.yaml
> chore: remove maxSlotsPerPod hardcoding from values.yaml

- docs/how-to/custom-env.txt
- docs/how-to/installation/aws.txt
- docs/how-to/installation/kubernetes.txt
- docs/how-to/rest-apis.txt
- docs/index.txt
- docs/reference/cluster-config.txt
- docs/reference/command-notebook-config.txt
- docs/reference/helm-config.txt
- docs/release-notes.txt
- docs/release-notes/1299-fix-deselect-rows-after-table-batch-actions.txt
- docs/release-notes/1306-remove-tensorboard-source-column.txt
- docs/release-notes/1310-support-tls-configuring-in-helm.txt
- docs/release-notes/1317-webui-use-async-polling.txt
- docs/release-notes/1318-no-health-checks-during-termination.txt
- docs/release-notes/1319-remove-TensorpackTrial.txt
we are missing a check target on docs (rstfmt doesn't have one) thus we don't catch format violations on opening PRs
as a basic `check` maybe we could run fmt and check git diff 
> chore: format docs.

- master/internal/grpc/logging.go
Fun fact: this jira ticket number is a palindrome.
> chore: quiet grpc log levels down [DET-4224]

- master/internal/api_experiment.go
- master/internal/db/postgres_experiments.go
- master/static/srv/get_experiment_labels.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
> chore: add API call to list all defined labels for experiments [DET-4099]

- .circleci/config.yml
- e2e_tests/pytest.ini
- e2e_tests/tests/config.py
- e2e_tests/tests/conftest.py
- e2e_tests/tests/deploy/etc/master.yaml
- e2e_tests/tests/deploy/test_local.py
- e2e_tests/tests/fixtures/no_op/single-default-ckpt.yaml
Added integration tests that test `det-deploy local`, and add them to the `test-e2e` workflow in CircleCI
See CircleCI execute the new tests.
> feat: add integration tests for det-deploy local

- docs/release-notes/1323-fix-trial-failures-on-preclose-checkpoint-failures
- e2e_tests/tests/test_system.py
- master/internal/db/postgres.go
- master/internal/trial.go
This addresses a bug in the handling of trial terminations when the trial fails during it's preclose checkpoint workload, that caused the trial to panic. This appeared in `det create -test` because because it's first and only checkpoint is a preclose checkpoint, so any failures make this appear.
> fix: fail correctly on preclose checkpoint failures [DET-4189, DET-4194]

- examples/computer_vision/cifar10_pytorch/README.md
- examples/computer_vision/cifar10_pytorch/adaptive.yaml
- examples/computer_vision/cifar10_pytorch/const.yaml
- examples/computer_vision/cifar10_pytorch/distributed.yaml
- examples/computer_vision/cifar10_tf_keras/adaptive.yaml
- examples/computer_vision/cifar10_tf_keras/const.yaml
- examples/computer_vision/cifar10_tf_keras/distributed.yaml
- examples/computer_vision/fasterrcnn_coco_pytorch/adaptive.yaml
- examples/computer_vision/fasterrcnn_coco_pytorch/const.yaml
- examples/computer_vision/iris_tf_keras/const.yaml
- examples/computer_vision/iris_tf_keras/distributed.yaml
- examples/computer_vision/mnist_estimator/adaptive.yaml
- examples/computer_vision/mnist_estimator/const.yaml
- examples/computer_vision/mnist_estimator/distributed.yaml
- examples/data_layer/data_layer_mnist_estimator/const.yaml
- examples/decision_trees/gbt_titanic_estimator/adaptive.yaml
- examples/hp_search_benchmarks/darts_cifar10_pytorch/adaptive.yaml
- examples/hp_search_benchmarks/darts_cifar10_pytorch/const.yaml
- examples/nas/gaea_pytorch/eval/const.yaml
- examples/nas/gaea_pytorch/eval/distributed.yaml
- examples/nas/gaea_pytorch/search/const.yaml
- examples/tutorials/fashion_mnist_tf_keras/const.yaml
- examples/tutorials/fashion_mnist_tf_keras/distributed.yaml
> chore: fixes for example configuration files

- master/internal/api.go
- master/internal/api/actor.go
- master/internal/api_tensorboard.go
- master/internal/command/manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/grpc/auth.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/tensorboard.proto
add create tensorboard endpoint supporting: experiment ids & trial_ids parameters
- tried out the old endpoint through the webui to make sure it still works.
> chore: add basic create tensorboard endpoint [DET-4095]

- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
I tested using `det-deploy` and confirmed it set the minimum to 2 and maximum to 8. The idle timeout works, and when the DB is scaled to 0, it takes ~30s-1m for the first master request to return as the DB spins backup.
Many of our development instances don't need a large-sized RDS minimum, and I've added an auto-pause timeout of one hour.
> chore: Reduce default RDS capacity and enable auto pause. [DET-4220] [DET-4219]

- webui/tests/test-cluster/master.yaml
http_port had been renamed to port
> test: update http_port for webui e2e-tests

- docs/release-notes/1335-support-initContainers-and-sidecars.txt
- docs/topic-guides/custom-pod-specs.txt
- e2e_tests/tests/command/test_run.py
- master/internal/kubernetes/log.go
- master/internal/kubernetes/pod.go
- master/internal/kubernetes/spec.go
- master/pkg/model/environment_config.go
This PR allows users to specify initContainers and sidecars as part of
the custom pod spec.
Tested manually and added e2e tests.
> feat: support initContainers and sidecar containers for k8s [DET-4026]

- master/internal/kubernetes/pod.go
> fix: check k8 message length before parsing [DET-4241]

- webui/react/src/services/api.ts
- webui/react/src/services/utils.ts
- webui/tests/cypress/support/commands.js
- webui/tests/test-cluster/master.yaml
Current new api login does not align with best practices. Until then, revert login to original API endpoint.
**NOTE:** changes to `test-cluster/master.yaml` will land with [this PR](https://github.com/determined-ai/determined/pull/1366).
> chore: revert old login [DET-4242]

- webui/tests/bin/createUserAndExperiments.py
- webui/tests/test-cluster/Makefile
- webui/tests/test-cluster/run-server.py
- Update the webui test-cluster to match current tools
- Add better logging to `createUserAndExperiment.py` script
> chore: update webui test tools

- master/internal/api_auth.go
This change replicates the client side hash done by the frontend and cli in the backend for the new api.
> chore: replicate client side hash server side

- .circleci/config.yml
- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- e2e_tests/tests/config.py
- master/pkg/model/defaults.go
- tools/scripts/README.md
- tools/scripts/bumpenvs.yaml
- tools/scripts/refresh-ubuntu-amis.py
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
This is the proposed change to follow-up https://github.com/determined-ai/environments/pull/49.
It includes an application of `bumpenvs.py` that I apparently lost during a rebase in the PR where I added `bumpenvs.py`.
> feat: support new AWS regions [DET-3837]

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/how-to/custom-env.txt
- docs/reference/cluster-config.txt
- docs/reference/command-notebook-config.txt
- docs/reference/experiment-config.txt
- docs/reference/helm-config.txt
- docs/tutorials/quick-start.txt
- e2e_tests/tests/config.py
- examples/decision_trees/gbt_titanic_estimator/adaptive.yaml
- examples/decision_trees/gbt_titanic_estimator/const.yaml
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- master/pkg/model/defaults.go
- tools/scripts/bumpenvs.yaml
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
For environments commit 699677b01d555e70ae60cdcbdcd531c600cd9a07.
> chore: bumpenvs

- webui/react/src/utils/number.ts
> fix: update percent utility to handle out of range numbers

- docs/how-to/data-layer.txt
- docs/reference/cluster-config.txt
- harness/determined/keras/_tf_keras_trial.py
> docs: fix broken links

- docs/release-notes/1386-increase-timeout.txt
- master/internal/provisioner/config.go
- master/internal/provisioner/config_test.go
- master/internal/provisioner/scale_decider.go
increase max disconnected and idle periods.
N/A
N/A
> feat: increase max disconnected and idle period [DET-4267]

- webui/react/src/contexts/AppContexts.tsx
Block `/agents` polling from polling again until the previous polling resolves.
Load any webui page, change chrome to `Slow 3G` under console > Network and check to see if `/agents` request intervals are greater than the default 5s.
> fix: update agents context polling to block before next poll [DET-4264]

- docs/release-notes.txt
> docs: Release notes for 0.13.5.

- e2e_tests/tests/requirements.txt
- examples/tests/requirements.txt
Remove security vulnerability warnings.
> chore: bump tf test versions

- proto/src/determined/api/v1/api.proto
- webui/react/src/services/api.ts
this lets generated code through swagger-code-gen know how to apply authentication
- tested using the example here https://github.com/determined-ai/api-bindings
> chore: add swagger authentication spec [DET-4272]

- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
> fix: webui trial info checkpoint size label update [DET-4250]

- docs/reference/helm-config.txt
- docs/release-notes/1412-db-helm-configs.txt
- helm/charts/determined/templates/db-deployment.yaml
- helm/charts/determined/values.yaml
Tested by manually spinning up a cluster.
> feat: support configuring CPU and Mem reqs for DB in helm chart [DET-4032]

- docs/reference/cluster-config.txt
> docs: fix doc for agent starting period and idle timeout

- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/gcp.py
- deployed up and down with and without --local-state-path
- validated --dry-run with and without --local-state-path
> fix: support for --local-state-path with det-deploy gcp [DET-4277]

- webui/react/src/components/InfoBox.module.scss
- webui/react/src/components/TagList.module.scss
- webui/react/src/hooks/useExperimentTags.ts
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
- webui/react/src/pages/ExperimentList.tsx
Moved some code to avoid code duplication and made some CSS tweaks to make sure that all items in the Summary box in the experiment page are properly aligned.
> chore: webui add experiment label editing on experiment detail page [DET-3972]

- docs/requirements.txt
This increases the font size, fixes some CSS layout issues, and tweaks the
navigation layout.
> docs: update to new version of custom Sphinx theme

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- e2e_tests/tests/config.py
- e2e_tests/tests/fixtures/tf_keras_grad_aggregation/grad_aggregation_test.py
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp_config.go
- master/pkg/model/defaults.go
- tools/scripts/bumpenvs.yaml
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
This new version of horovod correctly increments `iterations` in tf.keras optimizers
and support gradient aggregation for Tensorflow 2.4.
Improved gradient aggregation tests, also going to run full suite of e2e GPU 
before merging.
> chore: update horovod version 

- master/internal/core.go
- master/internal/resourcemanagers/resource_managers.go
- master/internal/telemetry/telemetry.go
Help distinguish between agent and k8 deployments in telemetry data.
> chore: add telemetry for k8s vs. agents [DET-4234]

- webui/react/src/components/MetricChart.tsx
Example video attached in JIRA.
There are 2 fixes there.
1) calling `setIsRendered(true);` before initializing the chart, because otherwise that block of code (lines 110-114) will get called a 2nd time on the 2nd run after changing the component state (with setIsRendered) resulting in initializing the chart and the listeners twice.
2) fix the `handleRelayout` function, the previous if condition was failing to `setRange` when only 1 axis was moved (for example by scrolling the chart). That was an issue visible mainly in the LOg view, because data point are ~always in the low part of the chart (and the user needs to scroll).
> fix: webui metric chart not displaying log scale properly [DET-4246]

- agent/go.sum
- master/go.mod
- master/go.sum
- master/pkg/actor/context.go
- master/pkg/actor/inbox.go
- master/pkg/actor/ref.go
- master/pkg/actor/system.go
- master/pkg/actor/trace.go
- master/pkg/actor/util.go
This change adds distributed tracing support to the actor system, to better visualize and understand the actor system and how parts of the system interact. This is _preliminary_ support. It does not implement a websocket carrier to carrier span contexts over websockets, to and from the agents and harness. However, the trace is complex as is and that's probably not necessary.
This is a small, out of the way change, and it gets us a wee bit closer to having a much more understandable system, so in that way I think it's a net positive.
Example completed message in all the way to workload out trace:
Example system architecture diagram (highlighting experiment interactions):
> feat: add opentracing to actor system [DET-4212]

- docs/release-notes/1431-fix-experiment-details.txt
- webui/react/src/pages/ExperimentDetails.tsx
The latest validation metric on the experiment detail page may not be defined at the time it is run through `humanReadableFloat` function which requires a number. Perform an extra check to make sure the value exists before running the `humanReadableFloat` function.
> fix: correct `humanReadableFloat` error on Experiment Detail page [DET-4354]

- docs/release-notes.txt
> docs: release notes for 0.13.6.

- docs/tutorials/model-registry.txt
> fix: update model registry link to REST APIs

- proto/Makefile
swagger spec advertised object attributes using snake_case where our go server responded with camelCase objects as it is standard for JSON. this instructs protoc to advertise camelCase names
> fix: instruct protoc to generate camelCase var names [DET-4380]

- docs/release-notes/1446-style-and-copy-fix.txt
- webui/react/src/components/CheckpointModal.module.scss
- webui/react/src/pages/TaskList.tsx
> fix: style fix for long checkpoint names and minor copy change for task batch modal confirmation [DET-4376]

- docs/release-notes/1441-tensorboard-sources.txt
- webui/react/src/pages/TaskList.table.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
When starting a tensorboard with a single trial the tensorboard sources for experiments show up as an empty array instead of a `null` when it is created from the CLI (instead of through the API/WebUI). Handle the empty array cases too.
UPDATE: added the ability to show both experiment and trial type sources:
> fix: show tensorboard sources for CLI deployed tensorboards [DET-4372]

- docs/how-to/install-main.txt
- docs/how-to/installation/kubernetes.txt
- docs/how-to/installation/setup-eks-cluster.txt
- docs/release-notes/4028-add-eks-docs.txt
- docs/topic-guides/custom-pod-specs.txt
Add instructions specifying the configs and steps needed to setup a cluster for Determined on EKS. 
> chore: add EKS cluster setup documentation [DET-4028]

- master/internal/api_tensorboard.go
- master/internal/command/command_manager.go
- master/internal/command/manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- proto/patches/api.json
- proto/src/determined/api/v1/tensorboard.proto
- proto/src/determined/util/v1/util.proto
add `config`, `files`, and `template_name` parameters.
https://determinedai.atlassian.net/browse/DET-4094 depends on this.
- tested by using the generated SDK to launch a tensorboard and checking that the added parameters carry over to commandParams (available in api-bindings repo)
> chore: add common launch params to tensorboard API [DET-4214]

- docs/how-to/installation/kubernetes.txt
- docs/how-to/installation/setup-eks-cluster.txt
- docs/release-notes/4028-add-eks-docs.txt
Previous version of eks setup docs failed to pass format check.
> fix: change eks cluster setup docs to pass fmt check

- .circleci/config.yml
- docs/Makefile
- remove last line of the publish target
- make -C docs clean build publish
- [http-server](https://www.npmjs.com/package/http-server) docs/site/html
- visit SERVER/rest-api
a previous deploy step for docs https://app.circleci.com/pipelines/github/determined-ai/determined/6478/workflows/4a88ce00-80cd-4ad5-a884-5e727678ccf1/jobs/170582
> fix: set up swagger static deploy

- .circleci/config.yml
- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/secure.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/deployment_types/vpc.py
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
> chore: set enable_cors for test aws cluster [DET-4326]

- docs/release-notes/1432-webui-improve-float-values-visualization.txt
- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/components/HumanReadableFloat.tsx
- webui/react/src/components/Table.tsx
- webui/react/src/pages/ExperimentDetails.table.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
- webui/react/src/utils/string.ts
> chore: webui improve float values vizualization [DET-4127]

- docs/release-notes/1465-webui-experiment-labels-filter.txt
- webui/react/src/components/LabelSelectFilter.module.scss
- webui/react/src/components/LabelSelectFilter.tsx
- webui/react/src/components/SelectFilter.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/services/api.ts
Adds a labels filter to the experiments page.
Default <SelectFilter> placeholder logic behaves a bit tricky in this case because the default case is that no labels are selected, and that causes the Ant Select `maxTagPlaceholder` to don't be rendered (in the other multiple cases, <MetricSelectFilter>, have a min 1 value always selected). For that reason I used the placeholder with an hardcoded "all" value and changed the color to mimic the other placeholder.
Waiting for feedbacks to eventually improve that.
Another improvable point (not sure about the current preferred method) is the TS interface of the experiments labels API, I resolved it to a simple string[].
> feat: webui add labels filter for experiments [DET-4117]

- .circleci/config.yml
> fix: fix a ci parameter typo

- master/internal/api/actor.go
- master/internal/api_command.go
- master/internal/api_notebook.go
- master/internal/api_shell.go
- master/internal/api_tensorboard.go
- master/internal/command/command_manager.go
- master/internal/command/manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/command.proto
- proto/src/determined/api/v1/notebook.proto
- proto/src/determined/api/v1/shell.proto
- proto/src/determined/api/v1/tensorboard.proto
- proto/src/determined/util/v1/util.proto
- add new apis command, shell, and notebook launch apis
- update config type from byte array to struct (map[string]Value)
- created example code usage through python API bindings (available at the repo) 
- `curl-da.sh http://localhost:8080/api/v1/notebooks -d '{"config": {"resources":{"slots":0}}}'
> feat: add shells, command, and notebooks launch APIs [DET-4094]

- docs/release-notes/1480-fix-hyper-parameter-bool-view.txt
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.stories.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.stories.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
- webui/react/src/types.ts
- webui/react/src/utils/task.ts
> fix: fix handling of boolean hyperparameters in trial view [DET-4412]

- e2e_tests/tests/nightly/test_convergence.py
> chore: update time for convergence tests

- .circleci/config.yml
- e2e_tests/tests/nightly/test_convergence.py
> chore: make nightly tests parallel

- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/utils/step.ts
> fix: webui remove checkpoint button for deleted checkpoint [DET-4286]

- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/TrialDetails.tsx
> chore: webui stop polling on experiment terminal state [DET-4305]

- e2e_tests/tests/nightly/test_convergence.py
- examples/nlp/bert_glue_pytorch/startup-hook.sh
- examples/nlp/bert_squad_pytorch/startup-hook.sh
> chore: fixing Huggingface example and nightly tests

- docs/reference/experiment-config.txt
- docs/topic-guides/index.txt
- docs/topic-guides/training-units.txt
This change adds a stop guide for the changes introduced by remove steps.
Sorry this took a bit. I had a lot of back and forth about whether this should be necessary or the API should be improved further to target the deficiencies we wanted to doc to explain. In the end, there isn't time or consensus on how to fix the API, so the doc is here.
> docs: add remove steps topic guide [DET-3876]

- docs/reference/experiment-config.txt
- docs/release-notes/4336-deprecate-sha.txt
- docs/topic-guides/hp-tuning-det/hp-adaptive-advanced.txt
- docs/topic-guides/hp-tuning-det/hp-adaptive-simple.txt
- docs/topic-guides/hp-tuning-det/index.txt
Deprecation notice for `Adaptive (Simple)` and `Adaptive (Advanced)` searchers.
> docs: deprecate SHA notice [DET-4336]

- e2e_tests/tests/nightly/test_convergence.py
protonet_omniglot_pytorch takes too long to converge, so removing from nightly tests.
> chore: remove protonet_omniglot_pytorch from nightly

- master/internal/resourcemanagers/agent_resource_manager_test.go
- master/internal/resourcemanagers/fair_share_test.go
- master/internal/resourcemanagers/priority_test.go
- master/internal/resourcemanagers/resource_pool_test.go
- master/internal/resourcemanagers/scaling_test.go
- master/internal/resourcemanagers/scheduler_test.go
Add unit tests for agent resource manager.
N/A
N/A
> test: add unit tests for agent resource manager [DET-4134]

- docs/how-to/installation/kubernetes.txt
- docs/topic-guides/custom-pod-specs.txt
- helm/charts/determined/templates/NOTES.txt
> docs: minor updates to k8s docs

- docs/reference/cluster-config.txt
- docs/release-notes/1474-cluster-name.txt
- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/values.yaml
- master/internal/api_master.go
- master/internal/config.go
- master/internal/core.go
- master/packaging/master.yaml
- master/pkg/agent/master_message.go
- proto/src/determined/api/v1/master.proto
- tools/master.yaml
should we have a release note if we still don't show the cluster name anywhere?
- set cluster name and check it shows up in the corresponding API response.
- run gke cluster tests https://app.circleci.com/pipelines/github/determined-ai/determined/6867/workflows/959efbfe-53cf-4896-b63b-4ca659b9f786
> feat: add cluster name to master config [DET-3953]

- webui/tests/.eslintrc.js
> test: cypress eslint wait [DET-4423]

- deploy/determined_deploy/gcp/gcp.py
Tested 0.13.5 --> 0.13.6 upgrade
> fix: fix to allow det-deploy to upgrade existing clusters [DET-4427]

- agent/Dockerfile
- deploy/determined_deploy/local/docker-compose.yaml
- helm/charts/determined/templates/db-deployment.yaml
- master/Dockerfile
- tools/docker-compose.yaml
- webui/tests/test-cluster/docker-compose.yaml
Bump postgres to 10.14 and update the in-container perl version to address security vulnerabilities.
> fix: update postgres and perl version [DET-4395]

- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/utils/step.ts
1. Changing any filter will result on restoring the 1st page on pagination (or offset=0). That will avoid calling experiment list API with an offset > 0 && offset > experiment.length for that filter.
2. There's a minor and unrelated ES fix in the PR.
> fix: webui experiment list goes to first page when changing filters [DET-4377]

- e2e_tests/tests/nightly/test_capability.py
- e2e_tests/tests/nightly/test_distributed.py
> fix: incorrect directory path for mmdetection tests

- docs/release-notes/1461-fix-nav-tooltip.txt
- webui/react/src/components/Navigation.module.scss
When the nav bar is collapsed, the label for the nav item is hidden via opacity of 0, but still picking up mouse events. Update the CSS of the nav item that preserves the animation appropriately but sets the `display: none;`.
> fix: avoid showing tooltip when hovering outside of the nav bar [DET-4284

- agent/go.sum
> chore: sync agent go checksum file

- master/internal/api.go
- master/internal/api/api_test.go
- master/internal/api/params.go
> test: add api pagination refactor and test [DET-4425]

- master/internal/api_experiment.go
actor startup for the new create experiment endpoint is missing. probably was removed in a rebase here https://github.com/determined-ai/determined/pull/1455/commits/b7304388ad7c31c9303e049395f1923e2ff9063b
- create an experiment through the new API
- activate
> fix: add missing actor startup for create experiment [DET-4473]

- docs/reference/cluster-config.txt
> docs: add tls note

- e2e_tests/tests/nightly/test_capability.py
- e2e_tests/tests/nightly/test_convergence.py
- e2e_tests/tests/nightly/test_distributed.py
> chore: fix e2e convergence tests

- master/pkg/model/experiment.go
- master/static/migrations/20200929105146_add-trial-log-fields-for-filtering.down.sql
- master/static/migrations/20200929105146_add-trial-log-fields-for-filtering.up.sql
- master/static/migrations/README.md
This change just adds the new fields that will be used for filtering logs to the database and migrations to create them. Additionally, a new field is added for new log messages written by Fluentd so they can be reconstructed to match the previous trial logs.
Not really much going on here, @dzhu if you wanted to last this with "write logs to the master through fluentd" instead, I'd be fine with that. But for now, I will use this to work on filtering with the new api.
> chore: add new fields to trial logs [DET-4176]

- cli/determined_cli/tensorboard.py
This change allows tensorboard, when started from command line, to pass a context directory as arguments. This is especially useful for running a startup-hook before executing the actual tensorboard operation. The option`-c` allows the user to specify a context directory containing a startup-hook.
> feat: allow tensorboard to take context directories [DET-4187]

- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
> chore: webui migrate killExperiment to new API [DET-4016]

- agent/Makefile
- master/Makefile
> chore: fix master and agent release targets

- docs/release-notes/1486-webui-page-title.txt
- tools/scripts/licenses/react-helmet
- webui/react/package-lock.json
- webui/react/package.json
- webui/react/public/index.html
- webui/react/src/Dev.ts
- webui/react/src/components/Page.tsx
- webui/react/src/contexts/Info.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/SignIn.tsx
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
This will need to be reviewed as soon as getInfo API will expose the cluster_name.
Currently showing the cluster_id as a placeholder.
But most of the MR will stay the same so I'm already asking for a review. 
> chore: webui make page/tab title more descriptive [DET-2151]

- e2e_tests/tests/nightly/test_capability.py
- e2e_tests/tests/nightly/test_convergence.py
- e2e_tests/tests/nightly/test_distributed.py
These tests failed in each of 2 nightly runs last night: in all cases by <1%.
> chore: lower threshold for some convergence tests

- e2e_tests/tests/nightly/test_distributed.py
> chore: remove protonet_omniglot_pytorch nightly test

- docs/reference/api/keras.txt
- docs/release-notes/1458-fix-keras-callbacks.rst
- harness/determined/_experiment_config.py
- harness/determined/keras/__init__.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/keras/callbacks.py
- harness/tests/experiment/fixtures/keras_cb_checker.py
- harness/tests/experiment/fixtures/tf_keras_one_var_model.py
- harness/tests/experiment/fixtures/tf_keras_xor_model.py
- harness/tests/experiment/keras/test_tf_keras_trial.py
Support stateful callbacks with Keras, and implement Determined versions of EarlyStopping and ReduceLROnPlateau.
Unit tests ensure that calls are properly ordered relative to each other, and that they are called the right number of times.
> fix: keras callbacks [DET-4299] [DET-4202]

- docs/release-notes/1547-fix-disabling-slots.txt
- master/internal/agent/agents.go
- master/pkg/actor/api/api.go
> fix: fix disabling slots [DET-4492]

- master/internal/trial.go
Under Kubernetes, trial actors still need to receive and handle
`ContainerLog` messages, which functionality was removed in the course
of switching over to Fluent Bit, causing trial actors to crash and
experiments to fail to complete. This simply reinserts the original code
path for that case.
> fix: make trial actor still handle `ContainerLog` messages

- webui/react/src/components/LabelSelectFilter.module.scss
- webui/react/src/components/LabelSelectFilter.tsx
- webui/react/src/styles/antd.scss
> fix: webui label select misalignment [DET-4416]

- e2e_tests/tests/test_system.py
add a test to disable and enable slots.
Run the e2e test using the CI.
N/A
> test: add a test to disable and enable slots.

- docs/release-notes/1549-update-trial-route.txt
- webui/react/src/components/Breadcrumb.stories.tsx
- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.stories.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialActions.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.stories.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/routes/routes.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
Update the trial details and trial logs route to include experiment id in the route. From...
```
/trials/<trial-id>
/trials/<trial-id>/logs
```
to...
```
/experiments/<experiment-id>/trials/<trial-id>
/experiments/<experiment-id>/trials/<trial-id>/logs
```
**NOTE:** The original trial paths will still work, but will auto replace the route with the proper one with an experiment id in the route.
Click on trial links from...
- Task list page (TensorBoard sources)
- Experiment detail page
- Checkpoint modals
> feat: update trial route [DET-4402]

- harness/determined/keras/callbacks.py
Tracking of the percentage reported was not being reset after each workload.
> chore: fix reporting for verbose=1

- agent/internal/fluent.go
Since Docker host mode networking doesn't really work properly on macOS,
`make -C tools run` uses the agent's special `--container-master-host`
setting so that containers can connect to the master. That setting and
the related `--container-master-port` were not being applied to the
Fluent Bit container, which they should be.
> fix: use agent's master location overrides for Fluent Bit

- docs/release-notes/1545-webui-log-views-navigation-update.txt
- webui/react/src/components/LogViewer.stories.tsx
- webui/react/src/components/LogViewer.tsx
- webui/react/src/components/Navigation.tsx
- webui/react/src/components/Page.tsx
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/pages/MasterLogs.tsx
- webui/react/src/pages/TaskLogs.tsx
- webui/react/src/pages/TrialDetails/TrialActions.tsx
- webui/react/src/pages/TrialLogs.tsx
> feat: add navigation sidebar and breadcrumbs to log views [DET-4394]

- proto/src/determined/api/v1/agent.proto
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/auth.proto
- proto/src/determined/api/v1/command.proto
- proto/src/determined/api/v1/experiment.proto
- proto/src/determined/api/v1/notebook.proto
- proto/src/determined/api/v1/shell.proto
- proto/src/determined/api/v1/template.proto
- proto/src/determined/api/v1/tensorboard.proto
> docs: clean up API docs [DET-4399]

- webui/react/src/components/Link.tsx
- webui/react/src/routes/utils.ts
- ctrl click experiment rows.
this will have some conflicts with #1551 
> fix: fix ctr/cmd click failing to open experiment/trial from table views [DET-4531]

- webui/react/src/App.tsx
depends on #1551 for the link to work through react dev server
> chore: link to release notes [DET-4097]

- docs/release-notes/1575-experiment-actions-sync.txt
- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
- webui/react/src/services/api.ts
- Fix experiment archive action button going out of sync.
- Fix experiment actions not displaying loading spinner.
if you use any of the action buttons in experiment details a new request is initiated to update the state of the experiment and that doesn't always reflect the correct state. running curl can verify the API blocks properly 
curl-da.sh http://SERVER:8080/api/v1/experiments/716/archive -X POST -d '{}' && curl-da.sh http://SERVERi:8080/experiments/716/summary | jq '.archived'
> fix: fix experiment archive action going out of sync [DET-4535]

- docs/release-notes/4534-salthash-password-change.txt
- master/internal/api_user.go
we had decided to not require salting and hashing for new API authentication (https://github.com/determined-ai/determined/pull/1372)  we should probably do the same for password changes under our new API
> chore: replicate client side salt and hash [DET-4534]

- webui/react/src/pages/TrialLogs.tsx
> chore: add a leaf node to trial log's breadcrumb [DET-4530]

- examples/computer_vision/unets_tf_keras/README.md
> chore: unets_tf_keras README note

- webui/react/src/components/DeterminedAuth.tsx
no release notes needed this shouldn't be present in the previous release.
> fix: fix sign in docs link

- docs/reference/api/index.txt
- docs/reference/index.txt
We use a hacky way to include an external link in Sphinx toctree described
https://stackoverflow.com/questions/27979803/external-relative-link-in-sphinx-toctree-directive
> docs: add rest API to list of references [DET-4381]

- webui/react/src/components/TagList.tsx
- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/hooks/useExperimentTags.ts
- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
> chore: webui migrate patchExperiment to new API [DET-4017]

- webui/react/src/components/ResourceChart.tsx
- webui/react/src/pages/Cluster.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/themes.ts
- webui/react/src/types.ts
> chore: webui migrate getAgents to new API [DET-3844]

- common/determined_common/storage/shared.py
- master/internal/command/tensorboard_manager.go
- master/pkg/model/storage_config.go
- master/pkg/model/storage_config_test.go
> fix: tensorboard with absolute storage_path [DET-4543]

- harness/determined/pytorch/_data.py
- harness/determined/pytorch/_pytorch_context.py
- harness/tests/experiment/pytorch/test_pytorch_data.py
> fix: issue data type warnings in to_device [DET-4544]

- master/internal/experiment.go
- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/grid.go
- master/pkg/searcher/pbt.go
- master/pkg/searcher/random.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/searcher.go
- master/pkg/searcher/sha.go
- master/pkg/searcher/tournament.go
- master/pkg/searcher/util_test.go
- master/pkg/workload/completed_message.go
Add logic to searcher for InvalidHP messaging.
> feat: InvalidHP Searcher Ability [DET-4333]

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- e2e_tests/tests/config.py
- examples/gan/dcgan_tf_keras/const.yaml
- examples/gan/dcgan_tf_keras/distributed.yaml
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp_config.go
- master/pkg/model/defaults.go
- tools/scripts/bumpenvs.yaml
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
Based on environments commit 0e2ce4d98e0c0670be4329423a136f1260e9ba08.
> chore: bumpenvs for NCCL update

- master/internal/api/logs.go
- master/internal/api_trials.go
- master/internal/db/postgres_proto.go
- master/static/srv/get_trial_log_fields.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/trial.proto
This change adds a new endpoint `/trial/:trial_id/logs/fields` to stream all available fields for filters for the filtering available in the trial logs API.
```
(determined) ➜  determined git:(trial-logs-fields) curl -H "Authorization: Bearer v2.public.eyJpZCI6OCwidXNlcl9pZCI6MiwiZXhwaXJ5IjoiMjAyMC0xMS0wNlQxNjoxNDo0OS4xMTU3MjgtMDU6MDAifTlogDO6RnmFIHJxnxg3Ydc-2HDWsTgl3nMfeDSXJUSV6q3cO_sV8PLGm4szq8qQLpV8a2RyitF25KXFX0YECAQ.bnVsbA" localhost:8080/api/v1/trials/1/logs/fields
{"result":{"agentIds":["elated-backward-cat","sad-testfailed-cat"],"containerIds":[],"rankIds":[],"stdtypes":[],"sources":[]}}
```
Reused some infrastructure from the trial logs PRs. Plan on moving it somewhere else in a follow up and not calling it `Log..`.
> chore: add endpoint to stream trial log fields [DET-4479]

- CODEOWNERS
I didn't remove Hamid because he's on vacation :)
> chore: update CODEOWNERS to be opt-in

- cli/determined_cli/shell.py
- cli/determined_cli/tunnel.py
- common/determined_common/api/request.py
> fix: honor DET_MASTER_CERT_NAME with shells

- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
> chore: webui migrate killTask to new API [DET-4019]

- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
> fix: webui unarchive button loading state [DET-4017]

- webui/tests/cypress/integration/02-loginout.spec.ts
- webui/tests/cypress/integration/02-tasks.spec.ts
Fix the following three WebUI integrations test
- Task List Notebooks should launch notebooks - should launch notebooks
- Task List Tensorboards should terminate tensorboard - should terminate tensorboard
- Sign in/out - should be able to log out from React
Check that the test passes on CI and locally, particular the two mentioned above.
> ci: fix webui test failures

- docs/release-notes/1617-fix-experiment-list-tensorboard.txt
- webui/react/src/pages/ExperimentList.tsx
Fix the issue of Tensorboard not launching properly via Table batch operation.
- open webui and go to Experiment list page
- click on the checkbox to the left for multi-select
- click on View in TensorBoard button above the table
- verify the tensorboard launches and runs ok
> fix: tensorboard to load from experiment list via table batch

- harness/determined/keras/_tf_keras_trial.py
> chore: fix keras validation for dtrain

- examples/computer_vision/unets_tf_keras/const.yaml
- examples/computer_vision/unets_tf_keras/distributed.yaml
- examples/computer_vision/unets_tf_keras/model_def.py
- examples/computer_vision/unets_tf_keras/startup-hook.sh
> fix: unets_tf_keras data download

- docs/reference/cluster-config.txt
- docs/release-notes/1621-custom-tags.txt
This PR adds documentation for AWS dynamic agent custom tags. (Continued on [#1561](https://github.com/determined-ai/determined/pull/1561))
N/A
> feat: add documentation for AWS custom tags

- webui/react/src/utils/task.ts
Notebook launch path changed in commit #e3c24 this fixes
that.
> fix: fix wait page url for notebook launch request [DET-4586]

- docs/how-to/installation/setup-eks-cluster.txt
- docs/how-to/installation/setup-gke-cluster.txt
- docs/topic-guides/custom-pod-specs.txt
Fix broken link, improve some internal linkage, and make other minor fixes.
> docs: fixes for EKS docs.

- docs/how-to/rest-apis.txt
- docs/reference/index.txt
- docs/reference/rest-api.txt
add a Sphinx powered reference page to our references TOC replacing the 
unsupported external link that was added in a previous PR. 
the sidemenu doesn't behave properly on my builds. (reported in 4611) but it works fine here
https://212702-253846879-gh.circle-artifacts.com/0/docs/site/html/reference/api/experimental.html 
> docs: fix rest-api side menu links [DET-4598]

- webui/react/.eslintrc.js
- webui/react/src/components/LabelSelectFilter.tsx
- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/hooks/useAuthCheck.ts
- webui/react/src/pages/SignOut.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
- webui/react/src/services/utils.ts
Early api termination was previously supported through `axios.cancelToken`. With the new swagger API, it uses the native `fetch` underneath. Enable the capability again through the native `AbortController.signal.abort()`.
> refactor: add abort api calls [DET-4585]

- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
- webui/react/src/utils/types.ts
> chore: webui migrate ActiveExperiment context polling to new API [DET-4068]

- webui/react/src/components/TaskActionDropdown.tsx
report actions being taken to parents
> chore: define and report actions onComplete [DET-3847]

- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/resourcemanagers/resource_pool_test.go
- master/internal/resourcemanagers/scheduler_config.go
- master/internal/resourcemanagers/scheduler_test.go
- master/internal/telemetry/reports.go
> feat: add telemetry for schedulers [DET-4517]

- docs/how-to/installation/kubernetes.txt
- docs/reference/helm-config.txt
- docs/release-notes/4435-fix-default-user.txt
- helm/charts/determined/Chart.yaml
- helm/charts/determined/templates/change-password.yaml
- helm/charts/determined/templates/master-permissions.yaml
- helm/charts/determined/values.yaml
Default user password cannot be blank for AWS marketplace. This change allows a default password, specified in the cluster configuration, to be applied to the admin and determined users.
> feat: allow default password in kubernetes [DET-4435]

- .circleci/config.yml
Until we have an https and cors enabled server available that we can point the react builds to
we point it to the user's local server.
> build: set server address for react preview build.

- webui/cypress/cypress/constants.js
- webui/cypress/cypress/integration/00-cypress.spec.ts
- webui/cypress/cypress/integration/01-setup.spec.ts
- webui/cypress/cypress/integration/02-dashboard.spec.ts
- webui/cypress/cypress/integration/02-experiments.spec.ts
- webui/cypress/cypress/integration/02-loginout.spec.ts
- webui/cypress/cypress/integration/02-navigation.spec.ts
- webui/cypress/cypress/integration/02-tasks.spec.ts
- webui/cypress/cypress/support/commands.js
- webui/cypress/cypress/support/index.d.ts
- webui/cypress/cypress/support/index.js
- webui/react/config-overrides.js
- webui/react/src/ErrorHandler.ts
- webui/react/src/components/AuthToken.tsx
- webui/react/src/globalStorage.ts
- webui/react/src/hooks/useAuthCheck.ts
- webui/react/src/routes/utils.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/utils.ts
We reduce state sharing between tests by not preventing Cypress from clearing
local storage before each tests. Since the headless login mechanism is flaky at the moment
this updates the `cy.login` command to drive the UI to login.
> test: reduce state sharing between e2e tests [DET-4487]

- webui/tests/tests/StepImplementation.ts
> test: avoid swallowing errors in taiko

- webui/tests/TODO.md
- webui/tests/specs/02-responsive.spec
- webui/tests/tests/StepImplementation.ts
> test: add responsive navbar test [DET-4603]

- proto/src/determined/api/v1/experiment.proto
- webui/react/Makefile
- webui/react/src/components/CreateExperimentModal.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
- webui/react/src/types.ts
- webui/react/src/utils/task.ts
> chore: migrate fork/continue experiment endpoint [DET-4023]

- docs/topic-guides/deployment/determined-on-kubernetes.txt
Updates the k8s limitations to more accurately reflect our current state. 
> docs: update k8s limitations [DET-4582]

- docs/reference/cluster-config.txt
- docs/release-notes/1667-priority-scheduler.txt
- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/scheduler.go
- master/internal/resourcemanagers/scheduler_test.go
This PR should not be landed until after #1639 lands and dogfooding is completed.
> feat: make priority scheduler configurable and add docs [DET-4641]

- agent/internal/docker.go
- agent/internal/fluent.go
If the agent's subordinate Fluent Bit container has an issue, it can be
awkward to debug, since its logs are not exposed in our product and can
even vanish entirely if the container exits. Here, we make the agent (1)
print out any error or warning lines it finds in Fluent Bit's output and
(2) dump all recent logs if the container exits.
Perhaps we should revisit using the existing `dockerActor` to manage the Fluent Bit container. I avoided that initially because I decided there was enough difference in what this was doing to not make it worth it, but this one is doing more stuff now.
> feat: expose some Fluent Bit logs in the agent

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/constants.py
- deploy/determined_deploy/gcp/terraform/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/variables.tf
- deploy/determined_deploy/gcp/terraform/variables.tf
> feat: support configuring priority scheduler in det-deploy [DET-4508]

- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/pages/TrialLogs/TrialLogFilters.tsx
- webui/react/src/services/utils.ts
When changing filters quickly, each action triggers a new streaming endpoint call. The older unresolved calls need to be aborted early so they don't tie up resources.
> fix: add abort controller to trial log endpoints [DET-4657]

- webui/react/src/pages/TrialLogs/TrialLogFilters.tsx
> chore: order trial logs filter options [DET-4653]

- docs/release-notes/1688-fix-mobile-master-logs-link.txt
- webui/react/src/components/NavigationTabbar.tsx
In mobile view, check that Master Logs (under the overflow button) doesn't open a new tab
> fix: prevent mobile tabbar from opening new window for Master Logs [DET-4654]

- master/internal/core.go
chore: fix a shadowvar declaration
> chore: fix a shadow var declaration

- webui/react/src/pages/TrialLogs/TrialLogFilters.tsx
Avoid showing trial log filters if there are no filter options available.
- Open an old experiment trial log (> 5 months) and check to make sure the filters don't show up.
- Open a new experiment trial log and check for the filters to show up.
> chore: hide the trial logs filters when there are no filter options [DET-4652]

- webui/react/src/pages/TrialLogs/TrialLogFilters.tsx
> chore: minor copy update to trial log datetime filters

- webui/react/src/pages/Cluster.tsx
- webui/react/src/pages/HGICluster.tsx
- webui/react/src/routes/index.ts
- webui/react/src/routes/routes.ts
add a new temporary page to house the new cluster page with resource pools starting with the top stats.
> chore: add dev hgi cluster page and stat overview [DET-4633]

- master/Makefile
- master/internal/api_trials.go
- master/internal/core.go
- master/internal/db/postgres.go
- master/internal/elastic/elastic.go
- master/internal/elastic/elastic_intg_testutils.go
- master/internal/elastic/elastic_trial_logs.go
- master/pkg/model/experiment.go
- master/test/integration/api/api_trials_test.go
- master/test/integration/api/main_test.go
- master/test/testutils/fixtures.go
- tools/docker-compose.yaml
This PR adds tests to ensure elastic reading functionality matches postgres.
The only kinda funky thing here is the `WaitForIngest` stuff.. it's either that or a `time.Sleep(2)` really and this felt like it would flake less.
Also, these helped me find 2 or 3 bugs!
> test: integration test elastic-backend trial logs APIs

- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/Page.module.scss
- webui/react/src/components/SelectFilter.module.scss
- webui/react/src/components/SelectFilter.tsx
- webui/react/src/pages/ExperimentDetailPage.tsx
- webui/react/src/pages/ExperimentDetails.module.scss
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentOverview.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentOverview.table.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentOverview.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/routes/index.ts
- webui/react/src/routes/routes.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/styles/antd.scss
Add an unexposed experiment detail page with navigation setup for HP Viz. The current path is set as `/experiments/<id>/hp`, which will replace `/experiments/<id>` when complete.
> feat: hp viz skeleton [DET-4494, DET-4495, DET-4545]

- deploy/determined_deploy/aws/templates/secure.yaml
> chore: set MinCapacity for RDS for secure det-deploy to 2

- proto/src/determined/api/v1/trial.proto
- proto/src/determined/trial/v1/trial.proto
- webui/react/src/components/Badge.tsx
- webui/react/src/components/Table.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.stories.tsx
- webui/react/src/pages/TrialDetails.table.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialActions.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.stories.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/themes.ts
- webui/react/src/types.ts
- webui/react/src/utils/step.ts
- webui/react/src/utils/trial.ts
- webui/react/src/utils/types.ts
> chore: migrate trial details [DET-4021]

- master/internal/resourcemanagers/agent.go
- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/priority_test.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/resourcemanagers/task_list.go
Adds a more extensive set of unit tests for the priority scheduler.
Run it :)
Depends on the priority scheduler [DET-4512](https://github.com/determined-ai/determined/pull/1634)
> chore: priority scheduler unit tests [DET-4513]

- master/internal/api_master.go
- master/internal/grpc/auth.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/master.proto
we have telemetry information available for webui as part of an unauthenticated endpoint /info. /master is the equivalent of that and was missing this information.
Would telemetry info be a good fit here? this goes to enable https://determinedai.atlassian.net/browse/DET-4406 
> chore: provide telemetry information in new api [DET-4642]

- docs/release-notes/1701-fix-mobile-steps-table.txt
- webui/react/src/pages/TrialDetails.table.tsx
Before:
batches, state and overflow columns were fixed
After:
Check the trial info table in smaller viewports (mobile and tablet) to make sure it's usable.
> style: fix mobile steps table [DET-4669]

- master/internal/command/command.go
- proto/src/determined/command/v1/command.proto
- proto/src/determined/notebook/v1/notebook.proto
- proto/src/determined/shell/v1/shell.proto
- proto/src/determined/tensorboard/v1/tensorboard.proto
Update shell, tensorboard, notebook, and command LIST/GET APIs to return the resource pool information
> chore: update command APIs to return resource pool info [DET-4568 DET-4569 DET-4570 DET-4571]

- master/internal/api_trials.go
- master/internal/db/postgres_filters.go
- master/internal/db/postgres_trial_logs.go
- master/internal/elastic/elastic_trial_logs.go
- master/test/integration/api/api_trials_test.go
- proto/src/determined/api/v1/trial.proto
- webui/react/src/pages/TrialLogs.tsx
This change adds support for ORDER BY to the trial logs API.
> feat: support order by in trial logs api [DET-4647]

- examples/nlp/bert_squad_pytorch/model_def.py
- examples/nlp/bert_squad_pytorch/startup-hook.sh
Ran BERT SQuAD example and confirmed a successful validation pass
> fix: BERT SQuAD example works with latest stable transformers [DET-4680]

- docs/how-to/installation/kubernetes.txt
- docs/reference/cluster-config.txt
- docs/reference/helm-config.txt
- helm/charts/determined/values.yaml
The lowest common denominator/multiple of 4 and 8 is 8; it's the
greatest common divisor that is 4.
Also couldn't resist throwing in some other edits while I was looking at `values.yaml` (consistent paragraph widths and some copy edits).
> docs: clarify some Kubernetes-related docs

- webui/react/src/components/MultiSelect.stories.tsx
> chore: webui MultiSelect storybook [DET-4040]

- .circleci/config.yml
- agent/Makefile
- agent/go.mod
- agent/go.sum
- agent/internal/agent.go
- agent/internal/agent_test.go
- agent/internal/containers.go
- agent/internal/fluent.go
- agent/internal/fluent_intg_test.go
- master/Makefile
- master/internal/api_trials.go
- master/internal/elastic/elastic.go
- master/internal/elastic/elastic_intg_testutils.go
- master/test/integration/api/api_trials_test.go
- master/test/testutils/fixtures.go
This change adds integration tests in the agent to test elastic and postgres backends.
I'm going to rename the tests in the master to `test-e2e-master`. I think integrations tests go in tree beside unit but postfixed with `_intg_test.go`, e2e outside in `test/`. Seems like a fine pattern to me, I think im setting with that.
> test: integration test fluent with postgres and elasticsearch backends

- agent/go.mod
- agent/internal/fluent_intg_test.go
> fix: fix missing field in function call from bad merge

- webui/react/Makefile
> build: allow parallel run of js and css checks.

- webui/react/src/components/ResponsiveTable.tsx
> fix: webui table horizontal scroll [DET-4660]

- webui/react/src/Analytics.ts
- webui/react/src/contexts/Info.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
> chore: migrate getInfo endpoint [DET-4406]

- e2e_tests/tests/nightly/test_convergence.py
> chore: fix mnist_data_layer convergence test

- deploy/determined_deploy/local/cli.py
- deploy/determined_deploy/local/cluster_utils.py
Deployed agent locally with and without labels, and, for each, ran an experiment with and without `resources.agent_label` set and verified expected behavior.
> feat: support agent label for "det-deploy local agent-up" [DET-4713]

- master/internal/experiment.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/event_log.go
- master/pkg/searcher/random.go
- master/pkg/searcher/searcher.go
- master/pkg/searcher/util_test.go
Add searcher logic to handle InvalidHP exceptions, and implement searcher-specific handling for ASHA and other searchers.
Run an ASHA experiment and randomly pause/restart/terminate trials and ensure that progress does not break (i.e. go over 100%) and the experiment behaves as normal.
> feat: add searcher-specific InvalidHP logic [DET-4334, DET-4335]
