determined-ai/determined

.circleci/config.yml
To help with tracking cloud spend from different sources, this adds a
label to mark GCE instances spun up as part of GKE clusters in CI.
=> ci: add label for GKE clusters in CI

docs/release-notes/2797-preserve-uplot-zoom-between-remounts.txt, webui/react/src/components/LearningCurveChart.tsx, webui/react/src/components/UPlotChart.tsx
PROBLEM:
Zoom on the chart does not get preserved on the Learning Curve chart. The Learning Curve chart differs slightly in that new series (new trials) can get added to the chart, which cause the chart options to change, which requires the chart to be remounted (teared down and rebuilt). The zoom gets lost during this remount process.
SOLUTION:
Preserve the zoom (scales) if a zoom is detected, and upon remounting, apply the scales appropriately.
ADDITIONS:
- refactor to save chart as a reference instead of a state.
- refactor to remove the need for a forward reference (generally an anti-pattern)
- fix issue of learning curve not resizing properly.
=> fix: preserve zoom levels between uPlot remounts [DET-5636, DET-5751]

master/static/srv/notebook-entrypoint.sh
JupyterLab defaults to `/bin/sh` in terminals which is annoying for users. Let's grab the shell from passwd and set `SHELL` to make JupyterLab use the user's preferred shell (in practice, `/bin/bash`).
Launch a terminal inside JupyterLab.
=> feat: switch to bash in jupyterlab shells. [DET-5791]

master/internal/grpcutil/api.go
This isn't a perfect solution but is great as far as eng cost/user benefit goes. This isn't too much of a stretch anyway, echo already did this and I'd consider it new api breakage.
=> chore: increase gRPC recv cap to accomodate equal size shell and experiment context dirs

docs/release-notes/2810-fix-timing-metric-y-axis-label.txt, webui/react/src/pages/TrialDetails/Profiles/TimingMetricChart.tsx
Update y-axis label of `Milliseconds` to `Seconds` for Profiler Timing metrics chart.
=> fix: correct timing metric chart y-axis label to Seconds

.circleci/config.yml, harness/setup.py
- We currently have a restrictive `h5py` requirement in `setup.py` which is not compatible with python 3.9. It's due to TF 2.2 issue long time ago. We aren't dealing with 2.2 anymore so it can be relaxed. But also our use of `h5py` is strictly limited to `_tf_keras_trial.py`, and we end up doing most of the work using tensorflow h5 utilities. Let's treat it as a transient dependency and not explicitly require it in `setup.py` similarly to tensorflow itself; tensorflow install can pull in whatever version it needs, therefore avoiding any potential conflicts and extra version management burden.
- Add python3.9 to `test-cli`.
- Partially addresses #2626 
- Remove neighboring `dill` dependency because it seems it hasn't been used since PEDL.
- determined CLI now works with python 3.9 (unit …
=> chore: basic python 3.9 support.

docs/release-notes/2380-fix-fault-tolerance-bug.txt, examples/tutorials/mnist_pytorch/const.yaml, master/internal/experiment.go, master/internal/trial.go
This fixes a bug where we only took trial snapshots on searcher related events. This sounds right from the searcher point of view.. but the snapshots are also how we restore the workload sequencer state, so this caused us to lose all kinds of state on failures.
Oops. I removed a message but I forgot it had a snapshot attached..
=> fix: add in 'just a snapshot' msg to not lose progress on restart

docs/release-notes/2834-set-priority.txt, harness/determined/cli/command.py, harness/determined/cli/experiment.py, harness/determined/cli/notebook.py, harness/determined/cli/remote.py, harness/determined/cli/shell.py, harness/determined/cli/tensorboard.py, master/internal/api_command.go, master/internal/api_notebook.go, master/internal/api_shell.go, master/internal/api_tensorboard.go, master/internal/command/command.go, master/internal/core_experiment.go, master/internal/experiment.go, master/internal/resourcemanagers/priority.go, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/command.proto, proto/src/determined/api/v1/notebook.proto, proto/src/determined/api/v1/shell.proto, proto/src/determined/api/v1/tensorboard.proto, webui/react/src/services/api-ts-sdk/api.ts
Add `det ... set priority` CLI commands and API support for changing
priorities.
The scheduling algorithm itself already adapted perfectly fine to
changing priorities; all we have to do here is wire up the CLI and API
to let changes be requested from outside.
I feel like it's a problem how much repetition it takes to handle all the non-experiment task types...
=> feat: add the ability to set job priorities on the fly [DET-5863]

master/cmd/determined-master/init.go, master/internal/api.go, master/internal/api/actor.go, master/internal/api_agents.go, master/internal/api_command.go, master/internal/api_experiment.go, master/internal/api_notebook.go, master/internal/api_resourcepool.go, master/internal/api_shell.go, master/internal/api_tensorboard.go, master/internal/api_trials.go, master/internal/command/command.go
- Remove the unused error return from an internal `toNotebook` function,
bringing it in line with other similar functions nearby.
- Change an internal `actorRequest` function to take an `actor.Addr`
instead of a string, since it was almost always passed a stringified
address anyway.
- Expand usage of some predefined address constants.
=> chore: remove some unnecessary conversions and error paths

master/pkg/tasks/task.go
Previous we set the default container runtime to `nvidia` regardless of slot type for the agent. This change moves us to selecting `runc` or `nvidia` based on the slot type, since nvidia-based GPU images won't launch on CPU agents with the `nvidia` runtime when drivers/etc are already baked in (it tries to run an container start hook and fails).
Seems like just an oversight we weren't doing this before.
=> fix: switch container runtime on slot type

master/pkg/tasks/task.go
This fixes a bug for users who wouldn't have the nvidia runtime installed and instead use Docker's native GPU support.
=> fix: dont force nvidia runtime for users using Docker native GPU support

harness/determined/profiler.py
chore: make MetricsBatcherThread safer:
- Avoid hanging when exceptions are raised
- Avoid accidentally calling queue.get() with timeout <= 0
- Avoid crashing on empty metrics
- Avoid publishing empty metrics altogether
=> chore: make MetricsBatcherThread safer

e2e_tests/tests/experiment/test_profiling.py, harness/determined/profiler.py, harness/determined/pytorch/_pytorch_trial.py, master/internal/api_trials.go
Calls to the profiler metrics API without follow should return some metrics. Additionally, this fixes some bad code in tests that did not catch this issue.
For simplicity, i omitted a limit from the API but also omitted this critical detail.
=> fix: profiler metrics without follow should return metrics [DET-5911]

agent/.goreleaser.yml, master/.goreleaser.yml
Closes #2630.
Eh, wait and see what happens during the release? Seems unlikely to go wrong.
=> ci: push `latest` tag for master and agent Docker images

agent/go.sum, master/go.sum, master/internal/kubernetes/events.go, master/internal/kubernetes/informer.go, master/internal/kubernetes/pod.go, master/internal/kubernetes/pods.go, master/internal/kubernetes/preemptions.go, master/internal/resourcemanagers/setup.go
This change updates the k8s code to use the `watchtools.RetryWatcher` helper to recover from bad watches. Additionally it makes the watcher restart correctly from errors before it is instantiated.
I'll have a follow up to restructure the k8s actors so that the RM can actually handle pods actor failures (or at least notice them and print a really scary message).
=> fix: make k8s watchers more resilient [DET-5910]

docs/reference/api/api-pytorch-samplers.txt, docs/reference/api/api-pytorch.txt, docs/release-notes/1937-iterable-datasets.txt, harness/determined/_train_context.py, harness/determined/pytorch/__init__.py, harness/determined/pytorch/_data.py, harness/determined/pytorch/_experimental.py, harness/determined/pytorch/_pytorch_trial.py, harness/determined/pytorch/samplers.py, harness/tests/experiment/fixtures/pytorch_onevar_model.py, harness/tests/experiment/pytorch/test_pytorch_data.py, harness/tests/experiment/pytorch/test_pytorch_trial.py, harness/tests/experiment/test_local.py
My first idea for handling iterable datasets was  #1928, but I think that PR offered tooling to the user at the wrong layer; lower-layer than what the happy-path users wanted, and higher-layer than what the advanced users needed.
This PR is another idea, which offers high-level tooling for the happy-path users, and clearly documented primitives for building data loaders that are "determined-compliant" in other cases.
Here are some meeting notes from the #ml-ag meeting on 2 Nov 2020 (abriged):
> Aaron: Accept arbitrary Pytorch DataLoaders to reduce initial porting overhead. Could also upstream some of this.
> - AH: We wanted to do it for at least IterableDatasets, but we should do this for all data loaders (while explaining caveats). Doesn’t require YogaDL necessarily (but may have caveats …
=> feat: expose primitives for pytorch dataloaders

docs/release-notes/2884-int-maxval.txt, master/pkg/searcher/hyperparameters.go
Do what the docs have always said we do.
This has been broken since the python master was replaced with the go master.
Changing it includes breaking reproducibility of hparam sampling across determined versions, so we will land this in 0.17.0.
=> fix: include maxval in int hparam range

harness/determined/deploy/aws/templates/simple.yaml
A two line "refactoring"/unification in #2766 broke `--retain-log-group` in `--deployment-type simple`. Rolling that back.
CI is green again.
=> fix: `det deploy aws --retain-log-group`.

docs/reference/api/experiment-config.txt, harness/determined/_experiment_config.py, harness/determined/common/schemas/expconf/_gen.py, harness/determined/common/schemas/expconf/_v0.py, harness/determined/profiler.py, harness/determined/pytorch/_pytorch_trial.py, master/pkg/schemas/expconf/profiling.go, master/pkg/schemas/expconf/zgen_profiling_config_v0.go, master/pkg/schemas/zgen_schemas.go, schemas/expconf/v0/profiling.json, schemas/test_cases/v0/experiment.yaml
This change adds the toggle `profiling.sync_timings` which defaults to `true` and forces Determined to call `torch.cuda.synchronize` appropriately so that timing metrics are more accurate. Since this comes as a trade off, the toggle is available, which disables synchronize and instead of collecting many granular metrics, the profiler instead collects a single "overview" metric.
Currently this collects no timings when sync is disabled, since `samples_per_second` will likely be the best "overview" we can still get and any subset of timings that can be trusted are piecemeal and not as useful together, I think.
=> feat: add sync timing toggle for profiling [DET-5891]

.circleci/config.yml, e2e_tests/tests/fixtures/mmdetection/fake_data.yaml, e2e_tests/tests/fixtures/mmdetection/startup-hook.sh, harness/determined/pytorch/_experimental.py, model_hub/Makefile, model_hub/docker/Dockerfile.mmdetection, model_hub/examples/mmdetection/hydra/README.md, model_hub/examples/mmdetection/hydra/configs/config.yaml, model_hub/examples/mmdetection/maskrcnn.yaml
There needs to be a blank line after a `.. code-block::` directive.
=> chore: fix docstring syntax and remove extra whitespace

docs/requirements.txt
The just-released 0.5.1 appears to raise an error on import, at least in
the context of docs builds, so pin it for now.
- observe [broken docs build first](https://app.circleci.com/pipelines/github/determined-ai/determined/15122/workflows/6230fcb2-484f-4b1b-b26e-b1e5cf25a026/jobs/455506), observe [successful docs build](https://app.circleci.com/pipelines/github/determined-ai/determined/15128/workflows/64cd79dd-5927-47c4-93b7-5e7eaf29db8d/jobs/455711) with the change
=> fix: pin version of `torchmetrics`

docs/how-to/notebooks.txt, docs/reference/api/command-notebook-config.txt
=> docs: update idle timeout [DET-5906]

.circleci/config.yml
- Continuing #2920, I've found that the problem wasn't caused by setuptools 58 itself, but a conflict between it and the old circleci cache.
- To fix that, we bump the "major version" of the cache and add `pip freeze --all` to it, because it includes the versions of pip, wheel, and setuptools themselves (in contrast with the plain `pip freeze`).
- `pip<20` restriction comes from a while ago, and it seems we can modernize it.
- `setuptools<58` is no longer necessary.
CI is green, and also runs fresh pip & setuptools.
=> ci: unpin pip version, improve py venv cache key.

e2e_tests/tests/test_users.py, harness/determined/common/api/authentication.py, harness/determined/common/api/errors.py, harness/determined/common/api/request.py, master/internal/user/service.go
DET-5869
[DET-5869]
e2e tests added. Manual testing was also done.
In, harness/determined/common/api/authentication.py, the `catch Unauthorized -> throw Unauthenticated` is needed because of our automatic fallback to the default determined user. It doesn't make sense to say, "Unauthorized" unless the user actually attempted to login as a specific user.
[DET-5869]: https://determinedai.atlassian.net/browse/DET-5869
=> fix: make clear unauthorized vs. unauthenticated [DET-5869]

proto/src/determined/api/v1/master.proto, webui/react/src/ee/SamlAuth.ts, webui/react/src/ioTypes.ts, webui/react/src/pages/SignIn.tsx, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/decoder.ts, webui/react/src/types.ts
NOTE: pointing to [original approved PR](https://github.com/determined-ai/determined/pull/2924) (was just set to the wrong repo)
Update OSS to detect if `ssoProviders` property is set on `/api/v1/master` and enable SAML sign in (via Okta).
Previously this code sat in our enterprise only version but we decided to bring all these features and delineations into the OSS repo. The goal is to have the cluster the WebUI is connected to, to determine what capabilities the cluster can support and turning these features on and off based on availability via the API. The basic idea is the following:
1. WebUI loads a generic form
2. WebUI fetches GET `/api/v1/master` to see what type of cluster setup it is talking to
3. Based on the previous API call, the WebUI turns on/off features the cluster is …
=> refactor: move ee to oss [DET-5937]

model_hub/examples/mmdetection/yolov3.yaml, model_hub/model_hub/mmdetection/_trial.py
mmdetection was overriding our logging settings so we need to reset them after the mmdetection model has been initialized.
Also fixed an incorrect setting in the experiment config for fasterrcnn and added a config for yolo3
Tested in a determined cluster.
=> fix: model-hub mmdetection logging

harness/determined/exec/tensorboard.py, master/internal/api_tensorboard.go, master/pkg/tasks/task_gc.go
Make the tensorboard and checkpoint gc applications to not rely on
the working directory whatsoever.
Let tensorboard use /run/determined/tensorboard, and let checkpoint gc
use /run/determined/checkpoint_gc, the way trials use
/run/determined/trial.
=> chore: rework tensorboard and checkpoint gc paths

harness/determined/util.py
Adds support for float16 metrics serialization
When running an experiment using keras while having enable mixed precision using `tf.keras.mixed_precision.set_global_policy("mixed_float16")` (TF 2.6), the metrics are serialized before being sent by socket (to the master I guess?).
However, while float64 and float32 are supported, **float16** is not one of them: this patch hopefully fixes it.
=> fix: add support for float16 metrics serialization

docs/release-notes/2932-auto-bind-mount.txt, harness/determined/deploy/local/cli.py, harness/determined/deploy/local/cluster_utils.py, harness/determined/deploy/local/docker-compose.yaml, harness/determined/deploy/local/mount.yaml, harness/determined/deploy/local/storage.yaml, master/cmd/determined-master/init.go, master/cmd/determined-master/root.go
Support for work_dir will provide a strictly better experience that
--auto-bind-mount could provide, but both features combined would result
in strange directory layouts.  We'd rather just have work_dir.
Users who depended on --auto-bind-mount should instead use the
--master-config-path option to create a relative bind mount directly in
the master.yaml.
=> feat: det deploy local: remove support for --auto-bind-mount [DET-5948]

helm/Makefile
The version needed to be kept in sync with the chart before, which was
annoying. It turns out `helm push` works fine with the `latest` symlink.
=> fix: always `helm push` latest version

harness/determined/cli/checkpoint.py, master/static/srv/get_trial_metrics.sql
This fixes a mistaken removal in the API backing `det t describe --metrics` and a long-standing rendering bug with `det t describe`, where `format_checkpoint` didn't return enough rows if there was no checkpoint.
I was unaware `det t describe --metrics` called an entirely separate API with an entirely separate SQL query, so I missed this yesterday when I checked `det t describe`.
=> fix: `det t describe --metrics` API and rendering [DET-6025]

agent/go.mod, agent/internal/agent.go, master/internal/agent/agent.go, master/internal/agent/agents.go, master/pkg/actor/api/ws.go, master/pkg/agent/agent_message.go
This change adds functionality to recover agent websocket flakes.
Writing tests right now, going to add a "chaos test" target I think. For manual testing
* add `actors.NotifyAfter(ctx, 10*time.Second, errors.New("connection reset"))` to the websocket prestart
* modify `isClosingError` to treat abnormal closures as socket errors
* submit an experiment and watch it complete, with the agent websocket crashing on both sides every 10 seconds
* or just use socat/nc 🤷 (i also tested this way with `socat TCP-LISTEN:8081,fork,reuseaddr TCP4:localhost:8080` between the master and agent, blipping the tunnel)
For now, I didn't set the agent to draining. There are some edge cases that are tempting to not handle when we're draining because they're _almost_ not possible (E.G. getting a task scheduled, …
=> chore: recover agent websocket flakes [DET-5935]

docs/topic-guides/system-concepts/scheduling.txt, helm/charts/determined/Chart.yaml, helm/charts/determined/templates/master-permissions.yaml, helm/charts/determined/templates/priority-classes.yaml, master/internal/kubernetes/pods.go, master/internal/kubernetes/spec.go
Previously we relied on static priority classes that we create with helm install. With this change, determined can now dynamically create and destroy priority classes, allowing the user to specify a priority number in the experiment config. Now only two priority classes will be created during installation: a determined system priority for high priority tasks like master and gc, and a medium priority to serve as a default priority level.
NOTE: so far, this has only been tested with 0.16.5 becuase I've had troubles getting 0.17 to build. The mechanisms for priorityclass creation and deletion shouldn't change though.
spin up a kubernetes cluster, launch an experiment with the priority field populated. (`resources: priority: x`) Check the list of priorityclasses and make sure that the …
=> feat: allow kubernetes to use priority from exp config

harness/determined/exec/tensorboard.py
tensorboard updated to 2.6 which causes the same issues when using default load_fast=true, has trouble loading certain plugins.
=> fix: disable load_fast flag in tensorboard 2.6

agent/.goreleaser.yml, master/.goreleaser.yml, master/packaging/fetch-cloud-forest.sh
For fetch-cloud-forest.sh, assume that GOOS and GOHOST have been set already, and only detect the special case where `growforest` is put directly in the GOPATH/bin.
First, the user will confirm if it runs at all.  Then we can talk about potentially some sort of powerpc automated testing.
An OSS user has been trying to get the `determined-master` and `determined-agent` to build for powerpc64 but has not been successful.  I think that actually supporting powerpc64 is basically free for us.
=> feat: cross-compile for powerpc64

master/internal/agent/agent.go
Fix a bug that could crash the resource manager when an agent disconnects before it sent the master it's `AgentStarted` message. In this case, the failure caused the master to move the agent to the draining state but, since it wasn't registered with the resource manager, this made the RM panic.
oops
=> fix: gracefully handle prestart agent failures

harness/determined/_generic/_searcher.py, harness/determined/_generic/_training.py, harness/determined/common/util.py, harness/determined/util.py
As a quick release-party fix, add a post-processing step to catch NaN's in arrays.
This means we do a pre-processing step and a post-processing step.  This is less code (better for a release party fix) but the long-term fix will involve replacing simplejson.dumps, which doesn't allow us to customize handling of python-native types.
=> fix: non-scalar nan handling

.circleci/config.yml, e2e_tests/pytest.ini, e2e_tests/tests/cluster/test_agent_disable.py, e2e_tests/tests/cluster/test_agent_restart.py, e2e_tests/tests/cluster/utils.py, e2e_tests/tests/config.py, e2e_tests/tests/conftest.py, master/internal/task/allocation.go, master/internal/trial.go, master/pkg/agent/exit.go
Currently, when an allocation is terminated for agent-related reasons (e.g. agent failing), it's not counted as failure, and as a result the master treats the non-trial tasks (e.g. commands) as if they exited successfully. 
- We should count these as failures.
- _Not counting_ these against trial `max_restarts` is moved to trial.
- Update devcluster to latest version, and add a new test option for a "managed devcluster", where we use devcluster API to spawn and programmatically control it to kill/restart agents as needed for the test purposes.
Added managed-devcluster tests for
- making sure commands die without reporting success on agent kill.
- checking that max_restarts=0 experiments still restart in that setup.
This managed setup will get used more extensively in the work related to …
=> fix: fail non-restartable tasks on allocation termination [DET-6158]

e2e_tests/tests/cluster/test_model_registry.py, harness/determined/common/experimental/determined.py, harness/determined/experimental/client.py, master/internal/api_model.go, master/static/srv/get_model_labels.sql, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/model.proto, webui/react/src/services/api-ts-sdk/api.ts
Adds a new endpoint `/model/labels` to the Model Registry, listing all labels used in any model, in order of popularity.
We SELECT the model id and order by COUNT(DISTINCT(id)) to prevent duplicate labels on a model counting more than once. Labels with the same number of model occurrences are secondarily ordered alphabetically. 
Adds a call to the model registry's e2e test
=> feat: Add /labels to Model Registry API [DET-6178]

docs/release-notes/3117-confirm-cloudformation-updates.txt, harness/determined/deploy/aws/aws.py, harness/determined/deploy/aws/cli.py, harness/determined/deploy/aws/constants.py, harness/determined/deploy/aws/deployment_types/base.py, harness/determined/deploy/aws/deployment_types/govcloud.py, harness/determined/deploy/aws/deployment_types/secure.py, harness/determined/deploy/aws/deployment_types/simple.py, harness/determined/deploy/aws/deployment_types/vpc.py
Changing from a simple deployment an EFS deployment for example, will cause the database to be recreated because of the change to put everything inside a VPC. CloudFormation doesn't provide a good mechanism to check for this dynamically, so on any update we'll just confirm before proceeding.
I tested new deployments, updated deployments, both approved and un-approved, and the use of the --no-prompt flag, etc.
=> feat: confirm before modifying an existing AWS stack in `det deploy` [DET-6128]

.circleci/config.yml
Automation is tripping up on this, but in this case it's safe: https://github.com/determined-ai/determined/pull/3117
Will rely on the normal CI pipeline to verify
=> ci: add no-prompt to ignore safety checks in automation

agent/cmd/determined-agent/main.go
One can run master as `determined-master`, but `determined-agent` just prints help, and you need `determined-agent run`. This is odd. 
This PR makes it work either way for the sake of backwards compatibility and convenience.
Cobra doesn't really support that, and they simply recommend users to inject `os.Args[1]`: https://github.com/spf13/cobra/issues/725
- `determined-agent [RUN SUBCOMMAND ARGS]` should work the same as `determined-agent run [RUN SUBCOMMAND ARGS]`.
- other subcommands should still work fine.
=> feat: make `determined-agent [ARGS]` behave as `determined-agent run [ARGS]`.

harness/determined/_trial_controller.py, harness/determined/estimator/_estimator_trial.py, harness/determined/keras/_tf_keras_trial.py, harness/determined/pytorch/_pytorch_trial.py
Use classmethods for some trial controller internals to allow users inherit from our TrialControllers and override these w/o issues with inheritance.
Motivated by a question https://determined-community.slack.com/archives/CV3MTNZ6U/p1636077811035500 , where they wanted to setup tf logical devices in order to debug some OOM issue. That requires overriding `TFKerasTrialController#_configure_session`, but staticmethod style forces you to also override `from_trial`. 
Existing overrides using `staticmethod` shouldn't be affected and should continue working.
Everything works as before.
=> refactor: classmethods instead of staticmethods in trial controllers.

e2e_tests/tests/experiment/record_profiling.py, e2e_tests/tests/experiment/test_core.py, e2e_tests/tests/experiment/test_profiling.py, e2e_tests/tests/fixtures/metric_maker/metric_maker.py, harness/determined/_generic/_searcher.py, harness/determined/_generic/_training.py, harness/determined/common/api/experiment.py, harness/determined/common/api/request.py, harness/determined/exec/launch_autohorovod.py, harness/determined/util.py, harness/setup.py
simplejson is just externally-maintained json.  We don't have any
particular need to bring in an external dependency over what's packaged
in python's standard library, so just use the built-in json module.
Additionally, stop using json's "default" argument for encoding custom
types.  The function passed to "default" argument is not consulted when
encoding default types (especially "float") so it is impossible to catch
NaNs.  As a result, when using "default", we had to pre-and-post-process
the object during encoding.  Now, we do our own pre-processing step,
where we explicitly visit every object so we can eliminate the
post-processing step.
=> chore: remove simplejson

agent/internal/fluent.go, docs/release-notes/3160-nonroot-fluentbit.txt, master/internal/kubernetes/spec.go, master/pkg/fluent/fluent.go, master/static/srv/entrypoint.sh, master/static/srv/k8_init_container_entrypoint.sh
This change updates the kubernetes resource manager so that experiments launched from non-root users will also launch fluentbit as the `nonroot` user included in the fluentbit container.
Note: the init container still runs as root because `tar --same-owner` requires root. Changing that will require more work.
=> fix: fluentbit should be able to run as nonroot [DET-5949]

docs/release-notes/3152-model-registry-cli.txt, harness/determined/cli/model.py, master/static/migrations/20211102110152_make_model_registry_names_unique.down.sql, master/static/migrations/20211102110152_make_model_registry_names_unique.up.sql
Restores references to model names from the command line to be compatible with our shift to models.id on the backend. This un-does our quick fix of #3134 . Restores a unique constraint so an instance will not have models with duplicate names.
DET-6152 ticket should stay active, as I understand it to mean we would add more model registry actions to the CLI.
=> fix: Continue using model names on the CLI [DET-6152]

harness/determined/keras/_tf_keras_trial.py
Nobody is 100% confident if the old restriction still applies, but I was
able to run the old model that was provided as a reproducing example to
DET-2728, which was the ticket that caused us to add this documentation.
So it's pretty darn likely that the restriction was secretly lifted
during one of a couple of TFKerasTrial rewrites that occurred.
=> docs: remove note about model.predict

agent/internal/detect.go, docs/release-notes/3204-experimental-mig-support.txt
This is a step toward supporting MIG instances, a feature of CUDA 11 and A100's that allows a GPU to be split into smaller virtual devices that have their own compute / memory resources. For instance, a 40GB A100 can be split into 7 5GB MIG instances. This could be useful for more granular scheduling of smaller, distinct jobs on bigger GPUs. For instance, a single A100 could be shared by 7 distinct JupyterLab instances, or 7 concurrent (smaller) trials.
This support is considered experimental only and applies only to Kubernetes clusters and static agent clusters. Distributed training is not supported.
See https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html for how to do the MIG portion of this. The GPU cards need to have their MIG mode enabled and the MIG instances created …
=> feat: detect MIG instances in agents

e2e_tests/tests/cluster/test_model_registry.py, master/internal/api_model.go, master/static/migrations/20211118104412_model_add_notes.down.sql, master/static/migrations/20211118104412_model_add_notes.up.sql, master/static/srv/get_model.sql, master/static/srv/get_model_version.sql, master/static/srv/get_model_versions.sql, master/static/srv/get_models.sql, master/static/srv/insert_model.sql, master/static/srv/insert_model_version.sql, master/static/srv/update_model.sql, master/static/srv/update_model_version.sql, proto/src/determined/api/v1/model.proto, proto/src/determined/model/v1/model.proto, webui/react/src/services/api-ts-sdk/api.ts
In this updated PR, we make it possible to edit the Name field in PATCH /models/:id.  Re-add the Notes column to Models.
=> feat: model registry API can update name, has Notes field

docs/release-notes/3212-fix-delete.txt, master/internal/db/postgres_experiments.go
Fix a bug where the experiment delete code referred to `steps` rather than `raw_steps` causing it to miss steps and cause constraint failures downstream. Also, properly delete validations and checkpoints now that they are unlinked.
Fixes #3205 entirely. Stacked on #3211 . I'll follow up with a test over this.
=> fix: experiment delete should work when trials have restarts

helm/charts/determined/templates/master-route.yaml, helm/charts/determined/values.yaml
We need to account for the case where the `openshift` key is not present
at all; Helm fails to run in that case without this change.
=> fix: make Helm deployment work with no OpenShift config present

.circleci/config.yml, .circleci/devcluster/double-reattach.devcluster.yaml, CONTRIBUTING.md, agent/internal/agent.go, agent/internal/container.go, agent/internal/containers.go, agent/internal/docker.go, docs/release-notes/3155-rolling.txt, e2e_tests/tests/cluster/test_agent_restart.py, master/cmd/determined-master/root_test.go, master/internal/config/config_test.go, master/internal/resourcemanagers/agent/agent.go, master/internal/resourcemanagers/agent/agents.go, master/internal/resourcemanagers/resource_pool.go, master/internal/resourcemanagers/resource_pool_config.go, master/internal/sproto/task_actor.go, master/internal/task/allocation.go, master/pkg/actor/actors/timer.go, master/pkg/actor/address.go, master/pkg/actor/api/ws.go, master/pkg/aproto/agent_message.go, master/pkg/aproto/master_message.go, master/pkg/aproto/net.go, master/pkg/cproto/state.go
Basic support for "reattaching" running containers on agent restart (or crash). 
- The full feature is somewhat dependent on #3070 (task logs); otherwise the task logs are lost. So, this PR hides the reattachment behind a feature flag: `resource_pool` configuration ffield `agent_reattach_enabled`.
- Since #2991 when an agent tried to cleanly reconnect under the disconnect timeout, it'd be rejected. With this change, they'll be "accepted" once again; same agent actor is reused. When reattachment if off, old container state is cleaned up as if they exited to an error.
- When reattachment is on, the master will send the agent a list of container it expects it to have; the agent will try to reattach these. It'll send a list of successfully reattached ones back to the master. Master will treat …
=> feat: basic support for container recovery on agent restarts [DET-6061]

docs/release-notes/3223-gcp-no-filestore.txt, harness/determined/deploy/gcp/cli.py, harness/determined/deploy/gcp/terraform/main.tf, harness/determined/deploy/gcp/terraform/variables.tf
This change fixes a logic within terraform such that when creating a GCP cluster with `det deploy` and `--no-filestore` a filestore is not created.
=> fix: don't create filestore with no_filestore flag

master/internal/api_model.go, master/static/srv/insert_model_version.sql
Adds name and comment to insert_model_version - these attributes are already received by the API but unused. This also prevents archived models from getting updated attributes or registering new model versions.
=> fix: Add fields to new model versions, and protect archived models

master/pkg/searcher/random.go
If we catch an InvalidHP exception for a single trial experiment, we will continue creating new trials with the same constant experiment config.  This PR fixes that.
=> fix: invalidhp handling for single trial experiments [DET-6259]

docs/training-apis/experiment-config.txt
An OSS user had a confusion about proper use of `bind_mounts`. It is indeed hard to find an example of `bind_mounts` use in our docs. They tend to link to this section in `experiment-config.html`, so I've just added a couple examples here.
https://determined-community.slack.com/archives/CV3MTNZ6U/p1638369591151400
N/A
=> docs: add an example for `bind_mounts` usage.

master/pkg/searcher/asha.go, master/pkg/searcher/asha_stopping.go, master/pkg/searcher/grid.go, master/pkg/searcher/pbt.go, master/pkg/searcher/random.go, master/pkg/searcher/search_method.go, master/pkg/searcher/searcher.go, master/pkg/searcher/tournament.go
We are not counting progress for early exit trials correctly for random and grid search.  The desired behavior is as follows:
- Random: trials with exit reason InvalidHPs should not count towards trial progress at all. All other early exit trials should count as completing the max_length when accounted for progress.
- Grid: all early exit trials including InvalidHP trials should count as completing the max_length when accounted for progress.
This PR changes progress calculations to reflect the above.
=> fix: hp search progress to account for early-stopped trials [DET-6231]

master/internal/api_command.go, master/internal/core.go, master/internal/core_experiment.go
Previously, the SSH RSA key size for trials was set on a code path that
was only run for newly created experiments. A trial restored after a
master restart would therefore attempt to generate keys with a size of 0
and crash. Instead, we now set the key size in the master's base task
spec so that it applies to all tasks automatically.
The error in key generation and, more generally, the reason an allocation was killed don't seem to be surfaced anywhere at all, as far as I can tell.
=> fix: generate SSH keys for restored trials

docs/release-notes/3270-list-experiment-trials.txt, harness/determined/common/experimental/__init__.py, harness/determined/common/experimental/experiment.py, harness/determined/common/experimental/trial.py, harness/determined/experimental/__init__.py, harness/determined/experimental/client.py
Add method to ExperimentReference to list trials within an experiment [DET-5088].
Tested manually, locally.
There is an endpoint in the REST API to get trials within an experiment. It has a rich set of parameters: sorting, pagination, filtering by state. I decided to only expose the sorting parameters. The only similar method, `determined.experimental.client.get_models`, also does not offer pagination, which makes sense if you view serving UIs as one of responsibility of a RESTful API of which the python API is free.
I don't have as strong an argument for not offering filtering by state; it just does not feel very important.
[DET-5088]: https://determinedai.atlassian.net/browse/DET-5088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
=> feat: Add python method for listing trials in an experiment [DET-5088]

master/static/srv/get_model_version.sql, master/static/srv/get_model_versions.sql
This fixes a bug where the Model Version API always returns `null` for `last_updated_time`.
Reproducing the bug: if you update the description or other attribute of a model version, you'll see the updated time does not change - it is falling back to the creation time.
=> fix: Return last_updated_time on model versions

harness/determined/common/api/experiment.py
#3236 changed how the CLI initializes experiments. This caused the new CLI to create only paused/inactive experiments in an old master server. This restores the previous CLI code which creates the experiment and activates it as two separate requests.
=> fix: CLI keeps activate_experiment for backward compatibility [DET-6315]

webui/react/src/services/apiConfig.ts
Quick fix to make sure the CreateExperimentParams includes the activate param
=> fix: Send activate param from WebUI to API

harness/determined/common/experimental/experiment.py
get_trials sort parameters were not passed to the underlying REST api.
https://determinedai.atlassian.net/browse/DET-5088
=> fix: pass get_trials sort parameters to REST

.circleci/config.yml
Already applied on release branches. Craco keeps causing the React build to fail.
=> fix: increase CircleCI resource class for React builds

master/internal/resourcemanagers/priority.go, master/internal/resourcemanagers/priority_test.go, master/internal/resourcemanagers/resource_managers.go, master/internal/resourcemanagers/scheduler_test.go
fix a job order inconsistency between k8 and priority scheduler. 
improve code reuse.
=> chore: reuse ordering logic between k8 and priority schedulers

docs/sysadmin-basics/cluster-config.txt, master/internal/resourcemanagers/provisioner/aws_config.go
To test:
See the following three master config entries which should test all new code paths. Try and start master with these.
1. Working Config:
...
resource_pools:
...
- pool_name: compute-pool
...
provider:
type: aws
...
instance_type: g3.16xlarge 
instance_slots: 4
...
2. Error Config (unknown instance type without instance_slots specified):
...
resource_pools:
...
- pool_name: compute-pool
...
provider:
type: aws
...
instance_type: g3.16xlarge
3. Error Config (cannot have instance slots < 0):
...
resource_pools:
...
- pool_name: compute-pool
...
provider:
type: aws
...
instance_type: g3.16xlarge 
instance_slots: -123
...
=> feat: Allow new AWS instances to be specified [DET-6327]

docs/release-notes.txt
Looks like the spacing matters and was wrong - I didn't check the eventual formatting prior to release.
Built and viewed locally: fixed.
=> docs: fix image formatting in 0.17.5 release notes

agent/internal/detect.go, docs/release-notes/3304-fix-cpu-core-count.txt
Agent CPU slot detection was incorrectly parsing `cpuinfo` on linux. As a result, `det slot list` will display CPU-based slot device brand as if it only uses a single core, e.g. `Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz x 1 physical cores`, even though in reality it uses all 32 cores.
This PR fixes that, and also tries to handle multi-socket systems with different CPU models, if that ever happens.
Run a CPU-slotted agent on linux and confirm it reports a correct number of cores.
=> fix: improve CPU core count parsing on agents with CPU slots.

harness/determined/tensorboard/metric_writers/pytorch.py
setuptools 59.6.0 exposed a bug in pytorch, where pytorch is improperly
importing a particular submodule of distutils.  In old setuptools,
distutils.version was automatically imported, but in new setuptools, it
is not.  For details, see:
https://github.com/pytorch/pytorch/issues/69894
Since forcing users to upgrade pytorch is not feasible, we intervene by
enforcing that distutils.version is imported before we try to import the
problematic torch.utils.tensorboard submodule.  This workaround will not
help users who import torch.utils.tensorboard directly, but it will
protect users who only import torch.utils.tensorboard because of us.
I imported `determined.tensorboard.metric_writers.torch` with and without the fix.
Example test failure …
=> chore: workaround upstream torch bug

agent/internal/agent_test.go, agent/internal/detect.go
Agent exits on Apple with M1 chip because of an error when obtaining the CPU info using gopsutil ( https://github.com/shirou/gopsutil/issues/1000 ). This PR works around the error by providing placeholder values for brand and UUID.
Start Agent successfully on M1 Mac.
We may choose to wait for the fix to gopsutil or we can merge this fix now and replace it with an upgrade of gopsutil when a fix becomes available there.
=> feat: support agent on Apple Silicon without Rosetta

master/internal/sproto/agent_resource_manager.go
Prefer something which is obviously correct in this case, since it
doesn't run frequently enough to bother with optimizing memory patterns.
=> fix: small bug in log message

master/internal/task/errors.go, master/internal/trial.go, master/internal/trial_test.go
A bug occurred where, in quick succession, a RM granted an allocation resources and it reached out to build its task spec/save the trial to the DB, and the trial was canceled. This caused a trial to get saved in the `ACTIVE` state (as it always defaults to) instead of its actual state `STOPPING_CANCELED`. Rather than just save the state correctly by saving it as `STOPPING_CANCELED`, we introduce a new error type and return it to the allocation when it takes an action with an unreceived cancellation in its inbox. This stops the task from pointlessly allocating then killing itself and prevents the bug since we only add an active trial when the trial is active. 
[DET-1234]: …
=> fix: prevent trial being saved before allocation cancellation is acknowledged

master/internal/command/command.go, master/internal/config/config.go, master/internal/config/config_test.go, master/internal/experiment.go, master/internal/resourcemanagers/kubernetes/spec.go, master/internal/resourcemanagers/kubernetes_resource_manager.go, master/internal/resourcemanagers/resource_manager_config.go, master/internal/resourcemanagers/resource_pool.go, master/internal/resourcemanagers/scheduler_config.go
- dummy k8 resource pool reported inaccurate preemption status when using the `preemption` scheduler plugin
- set up scheduler and Kubernetes config structs to report their own preemption status
=> fix: fix incorrect preemption status report from Kubernetes RP

webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
Raw values I believe came from JobState (STATE_QUEUED, STATE_SCHEDULED, and STOPPING_CANCELED) were displayed on the experiment details header, instead of human format (Queued, Scheduled, Canceling). This patch uses the unified `stateToLabel` to guarantee whatever relevant state object is coming through, it's decoded for human user.
=> fix: Convert all experiment and job states to labels

master/internal/command/api.go, master/internal/command/command.go, master/internal/command/command_manager.go, master/internal/command/notebook_manager.go, master/internal/command/shell_manager.go, master/internal/command/tensorboard_manager.go
This change updates the command manager code to not crash permanently when receiving API calls from echo routed through the actor system. The actor's handling of these calls was removed but the system still could route calls to it, so, for example, an old CLI could crash commands until a restart occurred. We still need to route to the actors below `/commands/...`, `/shells/...`, etc, for the event endpoints et al, so the routing cannot just be purged.
=> fix: handle calls to old command endpoints, make it harder to crash cmd managers [DET-6336]

harness/determined/_core/__init__.py, harness/determined/_core/_context.py, harness/determined/_core/_searcher.py
Turns out that the master doesn't even need units when configuring the
searcher.  That means that the basic searcher doesn't make much since,
since it only really worked with a large unit (epochs) rather than a
small unit (batches/records), so for now the Core API will only support
SearcherOp-based training loops.
This is a bit unforunate, since a SearcherOp-based training loop
requires an extra layer of for loop that is not totally intuitive.  We
can revisit this at a later time when it is clearer how we can reduce
user friction.  In the mean time, keeping the Core API barebones is a
good idea.
=> chore: AdvancedSearcher->Searcher

master/internal/task/idle_timeout_test.go
`IdleTimeoutWatcher` test has been a bit flaky recently. It boils down to Go being late to schedule and execute the `NotifyAfter` message. In my anecdotal tests on a test machine, it was up to 0.4ms late. I suspect on a busy shared circleci environment it ends up being worse (>1ms), which causes the test to fail. 
Let's try to wait a bit longer, opportunistically breaking early if all is well.
N/A but CI should get greener.
=> ci: unflake master `IdleTimeoutWatcher` test.

master/internal/api_command.go
Fixing a regression in #3362 
Removal of this line: https://github.com/determined-ai/determined/pull/3362/files#diff-abb761c42fd4f61b025150aed52216a0a00a28c27958b5abd28f9278bc7e0e79L12
caused the shells & cmds to default to running on *compute pool* with 0 slots.
- that was not intended change
- it cannot be scheduled in some setups, causing a CI failure in `test_start_and_write_to_shell`.
Run a shell or cmd and ensure that:
- by default, it runs on 1 slot in compute pool
- `--config resources.slots=0` will cause it to run in 0 slots in aux pool
This should also fix `test_start_and_write_to_shell`
=> fix: default shell/cmd slots should be 1.

.circleci/config.yml, docs/release-notes/3377-rm36.txt
Python 3.6 became EOL on 23 Dec 2021:
www.python.org/dev/peps/pep-0494/#lifespan
The Python 3.6 CLI test started failing because psutil no longer ships
wheels for Python 3.6 for the latest post-3.6-eof version, which means
our CI would need gcc to build that package.  Instead, just delete the
test.
=> ci: stop testing EOL python

agent/go.mod, agent/go.sum, docs/release-notes/socket-activation.txt, docs/sysadmin-deploy-on-prem/linux-packages.txt, master/.goreleaser.yml, master/go.mod, master/go.sum, master/internal/core.go, master/packaging/determined-master.socket
This change allows the master to be run using systemd's socket
activation feature. It simply changes the creation of the base socket
listener to check for one provided by systemd or fall back to a manually
created listener; everything else built on that stays the same.
We also ship a new socket unit file so that users can switch to socket
activation easily with a few `systemctl` invocations.
=> feat: add systemd socket activation support to the master

harness/determined/cli/experiment.py
To test fix:
1. Run an experiment which creates a checkpoint.
2. Run the following command:
det experiment set gc-policy \
--save-experiment-best 0 \
--save-trial-best 0 \
--save-trial-latest 0 <exp_id>
^ this should not error and remove all the checkpoints.
=> fix: set gc-policy broken [DET-6373]

tools/scripts/README.md, tools/scripts/refresh-ubuntu-amis.py
Unfortunately, this uses a non-public endpoint (the endpoint backing
the webui at https://cloud-images.ubuntu.com/locator/ec2), but that
seems to be the only automated way to get the gov-region amis.
=> chore: get gov images in refresh-ubuntu-amis.py

.circleci/config.yml, e2e_tests/tests/config.py, examples/computer_vision/unets_tf_keras/const.yaml, examples/computer_vision/unets_tf_keras/distributed.yaml, harness/determined/common/schemas/expconf/_v0.py, harness/determined/deploy/aws/templates/efs.yaml, harness/determined/deploy/aws/templates/fsx.yaml, harness/determined/deploy/aws/templates/govcloud.yaml, harness/determined/deploy/aws/templates/secure.yaml, harness/determined/deploy/aws/templates/simple.yaml, harness/determined/deploy/aws/templates/vpc.yaml, harness/determined/deploy/gcp/constants.py, helm/charts/determined/templates/master-config.yaml, master/internal/resourcemanagers/provisioner/aws_config.go, master/internal/resourcemanagers/provisioner/gcp_config.go, master/pkg/schemas/expconf/const.go, master/pkg/schemas/expconf/legacy_test.go, model_hub/Makefile, schemas/test_cases/v0/experiment.yaml, tools/scripts/bumpenvs.yaml, webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json, webui/react/src/fixtures/responses/experiment-details/set-a.json, webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
Updating the base AMIs will cause automatic updates to not be so
aggressive in our CI instances.
Hopefully this will help stabilize CI a bit, but if not it will still
improve our overall security.
=> chore: bumpenvs for updated base AMIs

harness/determined/common/requests.py
The latest types-request==2.27.1 combined with our requests wrapper
module is confusing mypy, which we fix with a type cast.
=> chore: make mypy happy with requests wrapper

docs/release-notes/3414-fix-jobname-not-updating.txt, master/internal/api_experiment.go, master/internal/config/config.go, master/internal/experiment.go
a more comprehensive solution could start from https://github.com/determined-ai/determined/pull/3396 but 
1. it'd take longer to flush out 
2. we're working to remove the patchExperiment from core_experiment module soon
fixes #3390 
=> fix: address experiment name going out of sync with db

harness/determined/_core/_distributed.py, harness/determined/pytorch/_reducer.py, harness/tests/experiment/pytorch/test_reducer.py
Pass metrics to simple reducer in original order
[DET-5726]
The way that we shard changes the order of the observations (metric values captured by calls to `update`) when we later gather observations for custom reducers.
At a small extra cost we put the observations back in the original order before passing them to the reducer.
Note: 
1. This is only implemented for Pytorch and only for the "simple" metric reducer, i.e. one that is a function as opposed to a `MetricReducer`.
2. If the user calls `update` a variable number of times per batch (whether in training or validation) we cannot guarantee the order.
A new unit test creates a bare-bones Trial-like object and distributes calls to `update` in a way consistent with how `DistributedBatchSampler` does it.
It then confirms that the …
=> feat: pass metrics to simple reducer in original order

harness/determined/common/api/bindings.py, master/internal/api_task.go, master/internal/db/database.go, master/internal/db/postgres_tasks.go, master/internal/mocks/db.go, master/internal/task/allocation.go, master/internal/task/allocation_test.go, master/pkg/model/task.go, master/static/migrations/20211221113503_add-allocation-state.down.sql, master/static/migrations/20211221113503_add-allocation-state.up.sql, master/static/srv/get_task.sql, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/task.proto, proto/src/determined/task/v1/task.proto, webui/react/src/pages/Wait.tsx, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/decoder.ts, webui/react/src/services/types.ts, webui/react/src/types.ts
Adds an endpoint to GET status / readiness of a specific task. This approach adds columns to the allocations table, and an UPDATE query when container state changes.
An alternative would be to combine `/api/v1/tensorboards` and `/notebooks` calls, or a similar call to `a.ask(tensorboardsAddr.Child(req.TensorboardId)` format.
=> feat: Add /tasks/:task_id endpoint to GRPC API [DET-6354] [DET-6355]

harness/determined/common/api/bindings.py, master/internal/db/postgres_experiments.go, master/static/srv/get_experiment.sql, master/static/srv/get_experiments.sql, proto/src/determined/experiment/v1/experiment.proto, webui/react/src/services/api-ts-sdk/api.ts
- Fixes an issue where experiments forked and continued from the Web UI were stored with parent_id = NULL
- Returns parent_id in the experiments API
=> feat: Record parent_id from WebUI, return forkedFrom from API

.circleci/config.yml
As it says on the tin.
This already got used during the last release, but I only put the change on the release branch and never brought it back to master.
=> ci: run releases for tags with new proper SemVer format

webui/react/src/components/Icon.stories.tsx, webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss, webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx, webui/react/src/pages/TrialDetails/TrialDetailsHeader.tsx
Display experiment status icon for mobile view.
Place experiment status in the center of tag.
Display tensor board icon where needed.
Manual tested
=> fix: mobile view icons for experiment header [DET-6011]

docs/release-notes/3453-fix-profiler-filtering.txt, webui/react/src/pages/TrialDetails/Profiles/useFetchMetrics.tsx
[Relevant PR that introduced the error](https://github.com/determined-ai/determined/pull/3325)
The abort controller was created as a state and once canceled the all future profiler calls don't happen. This included changes to the filters which needs to trigger a new call with different filtering parameters.
Instead, when a trial reaches a terminal state, change the `follow` (indicator of whether to stream or just GET once) to `false`.
=> fix: avoid terminating profiler streaming [DET-6459]

harness/determined/common/experimental/determined.py, harness/determined/experimental/client.py, webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
- Adds `client.get_model_by_name("ABCDE")` to Determined client
- Fix non-working code sample on `/det/models/{model_id}/versions/{version_id}/overview`
=> fix: Update sample models code for Determined client

master/static/srv/get_task.sql, webui/react/src/pages/Wait.tsx
Fixes an issue in the new GRPC Tasks API, so that before a task gets an allocation, the Task can return an empty array  of Allocations instead of a null (causes a SQL/proto error)
=> fix: Allow allocations array to be empty without null value

master/Makefile, master/internal/resourcemanagers/task_list_test.go
Also fix a file that wasn't formatted as a result of the accidental make
fmt.
=> build: make -C master doesn't call make fmt

.circleci/config.yml
- Bump GKE cluster creation timeout to 30 minutes.
- Move current #ml-ag notifications to #ci-bots. Since it's not valuable to notify neither the entire channel or the last committer for these nightly tests, remove the mentions.
N/A
=> ci: increase timeouts for GKE cluster creation, move notifications from #ml-ag to #ci-bots.

e2e_tests/tests/requirements.txt, examples/tests/requirements.txt
Running `make all` on Mac results in
```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.3 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.4.3
make[1]: *** [get-deps-pip] Error 1
make: *** [all] Error 2
```
The problem is tensorflow-macos does not exist for 2.4.3; it only begins with 2.5.0.
Have new users ( @johnkim-det ) try it :)
=> fix: use different tf on macos

webui/react/src/pages/ExperimentDetails/ExperimentVisualization/ExperimentVisualizationFilters.tsx
Under "visualization" tab,  the button for "Apply" is not properly styled.
Before:
After:
=> fix: HP viz 'Apply' button style [DET-6442]

webui/react/src/pages/TaskList.tsx
Update task list "Resource Pool" column sorting to sort by alphabetical order.
Before:
https://user-images.githubusercontent.com/40620519/150424829-4b798328-d27e-4df6-80e3-05f089f1ba9b.mov
After:
https://user-images.githubusercontent.com/40620519/150424869-6f5ae74b-7284-4be9-88cd-b5f557c9b94f.mov
=> fix: update task list Resource Pool sorter to alphaNumericSorter [DET-6434]

agent/internal/fluent.go
When running multiple agents on the same host with fluent container names such as `determined-fluent` and `determined-fluent-2`, the first agent will try to erroneously remove both fluent containers. This may cause issues but itself, but if you run the second at the same time, it'll try to kill its own `determined-fluent-2` as well and hit an error because this container is already being removed.
This is caused by docker's `ContainerList` filtering by prefix (with a possible extra slash) and not exact match. With this fix, we do the exact match on our end.
While this may theoretically happen to a real customer running multiple agents, we don't officially support this configuration, and this change is primarily aimed at local development.
Run devcluster when multiple agents starting …
=> chore: support concurrent agents with matching fluent names.

webui/react/src/components/LogViewerCore.tsx
For running experiment, there is a chance that when first navigate to logs tab, (especially when logs are long and appearing quickly), logs are not automatically tailing. 
Navigate to a running experiments with continuous long log 10+ times (or just refresh the logs page), verify that logs are tailing. 
Also verify that scrolling up/down, scroll to oldest, tailing enable are all functional. 
Upon observation of `addLogs` and `handleItemsRendered`, I noticed that when the page loaded, `addLogs` is triggered several times with different length of `newLogs` argument, and I noticed that logs only misbehave when `handleItemsRendered` is triggered (with `isScrollReady` being true) before `addLogs` triggered with `newLogs.length` equal to 1 (after initialization), so I add an indicator for this …
=> fix: running experiment log misbehave [DET-6339]

webui/react/src/components/Navigation.tsx, webui/react/src/hooks/usePolling.ts
There seems to be multiple problems within the reported issue with over polling `/agents`. The known and addressable issue is to ensure that the WebUI doesn't poll the agents endpoint while an existing one is still in progress. Update the polling policy for `agents` to only continue polling if an existing agents poll is not currently in progress.
A couple of ways to test this...
Way to test without editing code:
Ways to test via editing code:
=> fix: resolve previous `/agents` fetch before polling for a new one [DET-6490]

docs/release-notes/3483-remove-deprecated-from-experiment-api.txt, harness/determined/cli/experiment.py, master/internal/core.go, master/internal/core_experiment.go
Removes deprecated code from core_experiment.go (old API)
Specifically: experiment-list, experiment-summaries, and kill
Work in progress
=> chore: Remove deprecated routes from old API

master/internal/trial.go
Previously, the runID of the trial was incremented in the `buildTaskSpec` function. This does not cover the case where we switch resource pools and need to restart the task on a different pool. In this case, we don't enter the function or increment the ID, leading to an error. Moving the increment to the task allocation function ensures that we increment the ID every time we allocate a task, which is the more correct behavior.
=> fix: increment runID during allocation

.circleci/config.yml
The scan is timing out. I suspect (and am confirming) that a larger resource class would address this.
=> ci: increase resource_class for Docker image scan

e2e_tests/tests/experiment/experiment.py
In e2e distributed tests, print trial logs when a trial is completed but has 0 steps.
While trying to detect the cause of flakiness of test_unets_tf_keras_distributed ( https://determinedai.atlassian.net/browse/DET-6598 ) I realized we were not retaining (printing) the trial logs when the trial ends in a COMPLETED state but something goes wrong and it has 0 steps. This was the case in the 3 failures of this test: the assertion that then number of steps is positive failed but pytest logs did not have sufficient information to understand what went wrong.
A more general solution would be to modify our CI code to retain trial logs as build artifacts.
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjo …
=> chore: print trial logs if trial ends with 0 steps

docs/release-notes/3500-page-visibility-polling.txt, webui/react/src/App.tsx, webui/react/src/contexts/Store.tsx, webui/react/src/hooks/usePageVisibility.ts, webui/react/src/hooks/usePolling.ts
PROBLEM
Polling can potentially be an expensive operation, using up power and bandwidth.
SOLUTION
Use the Page Visibility API that is supported by most modern browsers to store the state of whether the current page/tab is visible (aka user is focused on the tab/page or not). Using that state, to stop polling when the page is hidden and start polling if the page is visible and previously polling (meaning if it was stopped prior to the page becoming hidden, then when the page becomes visible, don't attempt to reactivate the polling).
=> feat: stopping and starting polling based on page visibility [DET-6604]

docs/release-notes/3479-new-pytorch-callback-method.txt, harness/determined/pytorch/_callback.py, harness/determined/pytorch/_pytorch_trial.py, harness/determined/pytorch/lightning/_adapter.py, harness/tests/experiment/fixtures/pytorch_xor_model.py, harness/tests/experiment/pytorch/test_pytorch_trial.py, model_hub/model_hub/mmdetection/_callbacks.py
DET-5180 additional pytorch callbacks
https://determinedai.atlassian.net/browse/DET-5180
Added
- `on_training_epoch_end(self, epoch_idx: int)`
Modified
- `on_training_epoch_start(self, epoch_idx: int)`  (legacy callbacks will log a warning `[2022-01-25 00:09:56] 9ef58fcb [rank=1] || 2022-01-25 00:09:56,151:WARNING [81]: on_training_epoch_start() without parameters is deprecated in 0.17.7. Please add epoch_idx parameter
`)
Enhanced unit test for pytorch callbacks
1. The way I read other implementations of callbacks, `on_training_epoch_end` should be called _after_ processing the last batch in an epoch.
2. As I mentioned earlier, it is possible that `on_training_epoch_end` will not get invoked after the latest batch in an epoch if `is_epoch_end()` returns `False`.
3. Upon discussion with …
=> feat: additional pytorch callbacks [DET-5180]

harness/determined/exec/launch.py
This change moves the launch script code around a tad so that logging setup happens before the first log is print, since the first log is fairly important.
=> fix: move python launch logger setup to not miss important log

master/internal/task/allocation.go, master/internal/task/errors.go, master/pkg/actor/response.go
This change aims to prevent a bug where an allocation may receive resources when it no longer needs them. From static analysis of the code, it should be semi-apparent to the reader that the scheduler may send the allocation actor resources as it pleases so long as it has not received notice that the resources have been released, and also that the allocation actor checks no preconditions upon receipt but moves straight along with launching on the resources. This change has 3 parts: ensure we _always_ log allocation errors, since it was very annoying in debugging, make the allocation actor check the precondition "am i still pending" in the event it decided to exit already _and_ the trial already received the allocationExited message, and as a last line of defense, don't make a bidirectional …
=> fix: add abort mechanism to stop actor deadlocks, check resource staleness on receipt

docs/sysadmin-basics/cluster-config.txt, master/internal/resourcemanagers/kubernetes/pod.go, master/internal/resourcemanagers/kubernetes/pod_test.go, master/internal/resourcemanagers/kubernetes/pods.go, master/internal/resourcemanagers/kubernetes/spec.go, master/internal/resourcemanagers/kubernetes_resource_manager.go, master/internal/resourcemanagers/resource_manager_config.go
This change adds a config section to the Kubernetes resource manager config to make the image for the fluentbit sidecar configurable.
This is a bit unfortunate, that there are agent fluent configs in the agents, fluent configs in dynamic agents configs and now another section in k8s. We should consider a master config refactor probably, one day.
=> feat: make k8s fluent bit sidecar image configurable

webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
Replaces double quotes and backslash in the model name, so that the Python code on the Model Version / Use in Notebook modal can be copied into a code editor.
If you rename a model `mni<">st`, then the output line of code should be `client.get_model("mni<\">st")`. This is already inside of standard HTML escaping.
=> fix: Escape model name in Python sample code [DET-6603]

webui/react/src/hooks/useRegisterCheckpointModal.tsx
One-line patch, when I have an experiment checkpoint and register it to a model > model version, it should use the updated models/:name/versions endpoint, instead of sending the ID.
=> fix: Patch issue with registering a checkpoint to a model version [DET-6622]

webui/react/Makefile, webui/react/package.json
local coverage report didn't generate properly after `npm run test:coverage`, thought Circle CI coverage report looked great.
BEFORE:
AFTER:
=> fix: update test:coverage and makefile to enable coverage report locally

harness/determined/exec/launch.py
We should make it clear that the action we are taking at the beginning
of a trial is to validate the checkpoint storage. In the event that
storage hangs, it isn't clear what the system is doing. This will
hopefully hint to folks that they need to look at their storage.
To test:
Start a trial, make sure there is a log line in the trial logs after "New trial runner"
=> chore: Add logging - checkpoint storage validation [DET-6623]

bindings/Makefile, harness/Makefile
This also fixes make devcluster, which invokes:
make -C harness clean build
as one of its startup steps.
=> build: fix make -C harness clean

docs/features/command-notebook-config.txt, docs/features/notebooks.txt, docs/release-notes/notebook-idle.txt, master/internal/api_notebook.go, master/pkg/model/command_config.go, master/pkg/model/command_config_test.go, master/static/srv/check_idle.py
Previously, we could only set the idle timeout for notebooks to start
counting if there were no kernels; that requires users to manually shut
down kernels to take advantage of the feature. This change allows the
notebook idle timeout to be based on either the presence of connections
to kernels or the last activity on any kernel or terminal (as well as
the method from before).
- primarily, start a long-running notebook command and then close the tab
- also manually stop all kernels and terminals and make sure that still works
I realized after writing this that the kernel connections option is redundant with the existing HTTP proxy traffic check. I've left it in in case there's some way I've missed in which it's not _completely_ redundant, but obviously I will quickly remove it upon hearing …
=> feat: make notebook timeout more configurable [DET-6268]

webui/react/src/components/MetricBadgeTag.test.tsx
Based on the test for Avatar, verify that this component on the Experiment Detail page displays the accuracy validation metric as "[ V ] accuracy" and has a "validation" tooltip.
`make test` inside of `webui/react`
=> chore: WebUI interaction test on MetricBadgeTag [DET-6424]

e2e_tests/tests/nightly/test_distributed.py, examples/computer_vision/unets_tf_keras/model_def.py
https://determinedai.atlassian.net/browse/DET-6598
The test is flaky because occasionally the dataset download times out. We run 8 workers, and sometimes one or two of them time out in the download; the end result is a COMPLETED experiment with a single trial that has 0 steps.
*Note*: A preprocessed version of the dataset has been uploaded to S3 and is available at https://s3-us-west-2.amazonaws.com/determined-ai-datasets/oxford_iiit_pet/oxford_iiit_pet.tar.gz
Run the e2e test against a cluster.
There are 2 things we consider doing:
1. Download dataset to the same nominal location `/tmp/data` instead of distinct locations by rank.
2. For CI purposes only:
- download and preprocess the dataset into S3
- amend the test code (the example itself as stored on github is unchanged for this …
=> fix: deflake unets-tf-keras test by avoiding redundant downloads

master/internal/experiment.go
=> chore: restore RP on set failure

webui/react/src/components/InlineEditor.tsx, webui/react/src/pages/ModelDetails.tsx
When a model successfully changes name, the browser should be redirected to the new URL (/det/models/:new_name)
When a model fails to change name, we were already resetting InlineEditor to the previous name, but this should handle it with a returned error instead of my previous `throw Error()` idea
1. Change the name of a model "test" -> "test2"
2. Change the name of a model to something not allowed "hello" -> "hello/world"
=> fix: Handle model name changes [DET-6648]

webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx, webui/react/src/pages/TrialDetails/Profiles/useFetchAvailableSeries.ts, webui/react/src/pages/TrialDetails/Profiles/useFetchMetrics.tsx, webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
PROBLEM
gRPC streaming are HTTP2 based connections so a typical browser limits them to about 6 per host. Which means when the user is opening multiple tabs, it can quickly saturate the browser's ability to make new connections. New connections are made but end up in a `pending` state until the previous ones resolves, but with streaming endpoints they generally do not resolve unless the backend closes the connection or if it errors out.
SOLUTION
We previously [applied the logic](https://github.com/determined-ai/determined/pull/3500) of canceling any ongoing polling endpoint calls when the user switches to another window or tab, and reactivating them when they come back to the page/window/tab. Apply the same logic for streaming endpoints.
See [Release Note](../docs/release-notes/README.md) …
=> chore: stop streaming when page loses focus and restart them when they are [DET-6629]

master/internal/command/command.go, master/internal/sproto/task.go, master/internal/task/idle_timeout.go, master/pkg/model/command_config.go
Test by launching a Tensorboard with these options:
`det tensorboard start -t <trial_id> --config=debug=true` and note that we get INFO level logging about the IdleTimeoutTicker state.
=> chore: add tensborboard timeout logging [DET-6317] 

master/static/srv/entrypoint.sh, master/static/srv/gc-checkpoints-entrypoint.sh, master/static/srv/notebook-entrypoint.sh, master/static/srv/shell-entrypoint.sh, master/static/srv/tensorboard-entrypoint.sh
A user requested an option to disable determined wheel installation at runtime because they want to prepackage all python libraries at container build time - see ticket for context. 
We don't have env images with preinstalled determined at the moment, so rigging up an automated test for this would be a chore.
Manual test plan: 
1. Build an env container which has determined installed, and `DET_SKIP_PIP_INSTALL=1` env var set.
2. Check it doesn't reinstall the wheel and uses the preinstalled one when you run trials, tensorboards, etc.
Technically it's a new feature, but it is very marginal and so I don't think we want to advertise it in release notes or docs.
=> feat: option to skip determined wheel installation [DET-6650]

harness/determined/_env_context.py, harness/determined/_execution.py, harness/determined/_info.py, harness/determined/exec/harness.py, harness/determined/exec/launch.py, harness/determined/exec/prep_container.py, harness/determined/launch/autohorovod.py, harness/tests/experiment/utils.py, harness/tests/tensorboard/test_util.py
Even though agents and k8s let us see the container ids before we
actually start the container, for other runtimes we plan to support
(like slurm) are likely not to support such a workflow.  A simpler, more
universal workflow is to ask some external resource manager, "please
give us N containers with this environment" and we get N containers with
identical environments.
This means that we should not be relying on container_id anywhere in the
harness (except perhaps Rendezvous API which can just use a different
implementation at some point when we have to support non-agent, non-k8s
rendezvous).  But the ClusterInfo API, which will become a public API
soon, should certainly not expose a container_id.
I noticed that there are a few API routes that require a container_id, which need to be …
=> chore: remove container_id from ClusterInfo

harness/determined/common/storage/azure.py, harness/determined/common/storage/azure_client.py, harness/determined/exec/tensorboard.py, harness/determined/tensorboard/fetchers/__init__.py, harness/determined/tensorboard/fetchers/azure.py, harness/determined/tensorboard/fetchers/base.py, harness/determined/tensorboard/fetchers/gcs.py, harness/determined/tensorboard/fetchers/s3.py, harness/determined/tensorboard/fetchers/shared.py, harness/tests/storage/test_azure.py, harness/tests/storage/test_gcs.py, harness/tests/storage/test_s3.py, harness/tests/storage/test_shared_fs.py, harness/tests/storage/util.py, master/internal/api_tensorboard.go
Features:
- Tensorboard rewrite to sync to local storage.
- Start of named logger use
- Added debug flag for task specs. Only used by Tensorboard.
- Tensorboard now starts for any new files found, i.e., profiler fix
Tensorboard Fetchers:
- GCS Fetcher
- S3 Fetcher
- Azure Fetcher
- SharedFS
Bug Fixes:
- Empty directories in checkpoints did not work for Azure
- Upload for azure_client should overwrite to match S3 behavior.
Unit Tests added:
- Azure live storage manager test.
- S3 Tensorboard Fetcher
- GCS Tensorboard Fetcher
- Azure Tensorboard Fetcher
- SharedFS Tensorboard Fetcher
=> feat: Tensorboard use local storage [DET-6029]

harness/determined/cli/notebook.py
When the CLI started switching over to the new binding code, handling of
the context argument got left out of the notebook launch function, so
here we put that back in. Just need to do a bit of translation to the
new type for a context file.
Should be pretty straightforward, but I haven't investigated to see if there are any subtle mismatches in semantics between the corresponding fields of `ContextItem` and `v1File`. One visible difference is that `content` is `bytes` in one and `str` in the other, hence the `.decode()`, but the value is always a Base64-encoded string, so that shouldn't be a problem.
=> fix: actually send the context directory for notebooks [DET-6634]

examples/computer_vision/unets_tf_keras/model_def.py
The previous fix to test_unets_tf_keras_distributed protected model data file loading with filelock but did not forego loading file if it was already present. As a result, other workers started downloading the file as soon as they got the lock and the file appeared as truncated to some workers. The solution is to check if file exists inside the lock and not download it again if it does.
=> fix: check if data file exists before downloading

harness/determined/cli/master.py
`det master` and `det model` both showed as allowing `det m`.
In practice `det m` only referred to `det model`.
=> chore: resolve conflicting cli abbreviation

webui/react/src/components/LogViewerEntry.tsx
Remove icon for log with level `LOG_LEVEL_UNSPECIFIED`
Navigate to log tab and verify log with level `LOG_LEVEL_UNSPECIFIED` not have an icon in front of the row.
Before:
After:
=> fix: remove icon for LOG_LEVEL_UNSPECIFIED log [DET-6436]

agent/internal/container.go, master/internal/checkpoint_gc.go, master/internal/resourcemanagers/agent/agent.go, master/internal/resourcemanagers/agent/slot.go, master/internal/task/allocation.go, master/pkg/aproto/exit.go
Previously if a container was killed through the agent/slot disable code path, it would kill containers directly rather than telling the allocation actor to kill itself. In all cases, a spurious container death will cause the allocation to die anyway and `det a --drain` is available when killing the allocation is not optimal (despite its issues, this will be true eventually). Moreover, a spurious container exit while the container is pulling causes the allocation actor to just receive an empty `containerStopped{}` which is indistinguishable from an exit 0. The allocation actor would interpret that exit incorrectly as a container deciding to exit early. 
This change makes kills always go through the allocation actor, so logic like counting towards max restarts is taken into account, and …
=> chore: containers should always be killed by their parent, remove incorrect exits with 0

master/internal/trial.go
Fixes a nil pointer exception that might cause trials to error out when switching resource pools.
=> fix: nil pointer error during switch RP

agent/internal/docker.go
How to test:
Launch an experiment and use a container on a repo which doesn't allow anonymous credential without the domain specified in your `~/.docker/config.json`
Exp config:
environment:
image: us-east1-docker.pkg.dev/determined-ai/msuarez-test-f/cuda-11.1-pytorch-1.9-lightning-1.3-tf-2.4-gpu-9f0cb26
Make sure you don't have, `us-east1-docker.pkg.dev` in your `~/.docker/config.json` `credHelpers`.
Note that it fails with a message saying that we couldn't find the domain.
----
Update your `~/.docker/config.json` to have this:
```
{
"auths": {...}
},
"credHelpers": {
...
"us-east1-docker.pkg.dev": "gcloud"
}
}
```
Run the same experiment and verify that there is a log line indicating we are using the credential helper for the domain.
=> chore: add additional logging for creds helper [DET-6710]

e2e_tests/tests/experiment/test_pytorch.py, e2e_tests/tests/fixtures/pytorch_no_op/model_def.py, harness/determined/exec/harness.py, harness/determined/exec/launch.py, harness/tests/test_launch.py
Previously, Native API-launched experiments always took the non-dtrain
codepath.
=> fix: dtrain + native api

webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx, webui/react/src/pages/ExperimentList.tsx, webui/react/src/pages/ModelDetails.tsx, webui/react/src/pages/ModelRegistry.tsx, webui/react/src/pages/ModelVersionDetails.tsx
On pages where we use the InlineEditor component (listed in Test Plan) we should return a server-side error to the component so it reverts the user's change and shows the original/stored value. This also uses `handleError({ silent: false })` to make sure the user knows what's happened.
Note: I changed silent from true to false in a few other places (I think model and model version metadata / notes). If this is excessive then I can change those back.
To test DB failures, in `master/static/srv/update_model.sql` and `patch_experiment.sql` write a SQL bug like `name = $2::int` to fail every update.
Uses of InlineEditor:
- description on Experiments (list)
- name and description on ExperimentDetails
- description on Model Registry (model list)
- name, description, and descriptions of model …
=> feat: Undo changes and warn user when InlineEditor fails to update db [DET-6659]

webui/react/src/components/MetricSelectFilter.tsx, webui/react/src/components/SelectFilter.module.scss
On the Experiment Detail page / TrialDetails chart, in the dropdown where you select Metrics for the chart, this fixes an issue where you couldn't see what you were typing ( https://determinedai.atlassian.net/browse/DET-6642 )
The only Ant Select component / prop-level issue I could see is this happens when we set  mode='multiple', which we need.
Select a metric (such as loss) by typing a metric such as 'loss' in the MetricSelectFilter dropdown of the TrialDetails chart.
=> fix: make SelectFilter input wide enough to see what I type in MetricSelectFilter [DPS-30] [DET-6642]

webui/react/src/components/LogViewerCore.tsx
Fix for bug where log viewer was flickering (scrolling to top) and some log entries would disappear. Flickering/scrolling issue was more noticeable in Safari but both issues appeared in both Safari and Chrome.
https://user-images.githubusercontent.com/97752292/153456995-9b812e8d-114c-4624-a507-838d12137815.mov
Seemed to be an issue where the update to `logs.length` made the `handleItemsRendered` callback run before `visibleStopIndex` updated. There may be another way to make sure these values match, but checking that `visibleStopIndex` matches `logs.length - 2` instead of `logs.length - 1` seems to fix the problem.
=> fix: log viewer bug

master/static/migrations/README.md, master/static/migrations/migration-create.sh, master/static/migrations/migration-move-to-top.sh
Previously, the `[ -z migration ]` test was broken.
Additionally, use quotes around all variable expansions, make the API
for the two scripts consistent, and document the scripts in the README.
=> chore: fix migration helper scripts

master/internal/db/postgres_tasks.go
Without this fix, the following line in a model definition:
print('\\"')
would result in an SQL syntax error.
We have a `model.RawString` in `pkg/model/types.go` that has a Valuer and Scanner implementation to make this automatic.
Is there an advantage to using that somehow?  I wasn't sure.
=> fix: use model.RawString for logs

docs/release-notes/3624-support-k8s-ssl.txt, helm/charts/determined/templates/master-config.yaml, helm/charts/determined/templates/master-deployment.yaml, helm/charts/determined/values.yaml
Lets users specify a secret name and ssl certificate name for postgres. Ssl mode is configurable, but only `verify-ca` is supported at this moment.
Uncomment the relevant fields in `db` of `values.yaml` and deploy using helm. You might have to generate keys/certificates and create a secret in kubernetes first. Then, ssh into the master container and check to see that the secret you specified is present under `/mount/determined/secrets/` and that the `ssl_root_cert` is populated in the master config.
Additionally, you may deploy a db instance with ssl enabled. Add your certificate to the `db` fields and check that your master instance is able to launch and connect to the db. Steps here:
Start by generating keys and create a kubernetes secret.
```
openssl req -new -x509 -days 365 -nodes …
```
=> feat: support k8s db ssl [DET-6364]

webui/react/src/components/InlineEditor.test.tsx, webui/react/src/components/InlineEditor.tsx
Added interaction tests to InlineEditor
specifically targeted the observed behavior below: value being reset onBlur 
implemented simple fix, but there are other considerations, see [3559](https://github.com/determined-ai/determined/pull/3559) and [3612](https://github.com/determined-ai/determined/pull/3612). In particular, if the save fails, we want to display a message to the user
=> test: add interaction test for inline editor [DET-6667]

e2e_tests/tests/command/test_shell.py
`test_start_and_write_to_shell` was flaking recently after bumping the version of Determined. `argparse` calls `shutil.get_terminal_size().columns` to figure out how to do indenting and line breaking. `argparse` also calls `textwrap.fill` with `break_on_hyphens` defaulted to `True`. Because of this, only in e2e tests where the size of the 'terminal' can't be properly discerned by `shutils`, tests fail because we grep for `0.17.10-dev0` and find `0.17.10\n-dev0`. This only happened now because the default width is `max()`'d with `11` in `argparse` and `"det 0.17.10-dev0"[:11] == 'det 0.17.10'` so the hyphen is where `textwrap` will wrap it.
~~I will explain why this works later, after sleep.~~
[DET-1234]: …
=> test: fix test_start_and_write_to_shell

harness/determined/cli/experiment.py
Fixes the CLI's `det experiment list` and `det experiment list-trials` to use API pagination to return all items (when >100 results). This expects 200 items / request until there are no more pages.
An alternative would be one request with a huge limit parameter (such as limit=100000); first commit shows this approach
Run `det experiment list` on a server with more than 200 experiments.
- All experiments should be returned.
- Order should be first to last.
- There should be no seams between pages.
=> fix: Use pagination in CLI to return all experiments, not the default limit

webui/react/src/pages/TrialDetails/Profiles/SystemMetricFilter.tsx
fix: refreshing profiler with blank screen results blank screen [DET-6673]
Set http://34.105.48.209:8080 as the backend and go to /det/experiments/41/profiler
Wait for page to load. This can take a while, see [6672](https://determinedai.atlassian.net/browse/DET-6672). Once it is loaded, the address will have additional query parameters, e.g. http://34.105.48.209:8080/det/experiments/41/profiler?agentId=det-dynamic-agent-corey-preemptible-0-17-7-apt-tiger&name=gpu_util.  
Refreshing the page then, or navigating to that url should load the page, whereas before user got  "unknown error" popups and a blank screen.
This PR is just one line of defensive coding, the underlying reason is that `ProfilesFiltersProvider.tsx` is providing `systemMetrics` metadata that say `systemSeries` is not …
=> fix: refreshing profiler results in blank screen [DET-6673]

harness/determined/common/api/bindings.py, master/internal/resourcemanagers/agent_resource_manager.go, master/internal/resourcemanagers/provisioner/aws_config.go, master/internal/resourcemanagers/provisioner/gcp_config.go, proto/src/determined/resourcepool/v1/resourcepool.proto, webui/react/src/services/api-ts-sdk/api.ts
Add GPU accelerator field for resource pool.
For AWS instance, accelerator is implied from this article: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/accelerated-computing-instances.html 
Ping `/resource-pools` endpoint to verify new field `accelerator` is added
=> feat: add `accelerator` field for resource pool [DET-6755]

harness/determined/common/api/experiment.py
Allow list hparams in --local mode.
Run an experiment that uses a list in hparams and ensure it does not error out during loading.  A good example is `cd examples/computer_vision/byol_pytorch && det experiment create --local --test const-cifar10.yaml .`
List hparams work just fine normally, but the function `generate_random_hparam_values` (accidentally?) excluded them.
- [] Release notes should be added as a separate file under `docs/release-notes/`.
=> fix: allow list hparams in local mode

master/internal/api_model.go
This is a WIP of returning 400 error codes when the server or DB reports an input-related error, instead of a 500.  Right now it is returning a 400 when we discussed using a 409.  If this code makes sense then I can generalize the error-capture code to other PG functions and Model/Experiment API endpoints.
- When creating an invalid model name (such as "a/b") or changing the name (to an invalid or duplicate name), the server should return the error with an InvalidArgument code and not a 500
- When the Postgres Database returns an error code which we recognize (such as uniqueness or bad param), that code should be turned to a message and passed up with an InvalidArgument code. I'm not sure an example how to test this (int/string API error?) it needs to be a constraint where we don't …
=> fix: Model/Experiment API and error codes [DET-6711]

e2e_tests/tests/test_logging.py, master/internal/api_tasks.go, master/internal/api_trials.go
Task logs now get written to a new table, and the old trial logs endpoint merges the results of reading both tables, but this merging was missed for `GET /api/v1/trial/logs/fields`. This change adds this functionality.
=> fix: GET /api/v1/trial/:id/logs/fields should return all filters

.circleci/config.yml
This is broken / bit-rotted and it isn't even used in our release process anymore. YANK!
As long as CircleCI doesn't complain about syntax errors on this config...
=> ci: deploy-release-party is no longer used in releases

docs/prepare-environment/custom-pod-specs.txt
Fix broken link to k8s API reference pod specs.
=> docs: fix broken link to k8s pod specs

docs/release-notes/3643-callbacks.txt, harness/determined/pytorch/_callback.py, harness/determined/pytorch/_pytorch_trial.py, harness/tests/experiment/fixtures/pytorch_xor_model.py, harness/tests/experiment/pytorch/test_pytorch_trial.py
I have argued against this feature for a _long_ time because of how users frequently ask for it looking for an end-of-trial hook, rather than an end-of-allocation hook.  We can't deliver the first one.  But I've finally assented. I think this is a pretty basic feature that we should just support.
=> feat: add on_trial_{startup,shutdown} hooks to PyTorchCallback

master/internal/db/postgres_cluster_intg_test.go, master/internal/db/postgres_tasks.go
An edge case arose with our cluster heartbeat scheme where we save the heartbeat, an allocation is started and the cluster dies. In this case, the end time will be set to the most recent cluster heartbeat but that is before end time so the logs show `failed to aggregate resource allocation: failed to add aggregate: ERROR: range lower bound must be less than or equal to range upper bound (SQLSTATE 22000)  id="allocation-aggregator" system="master" type="allocationAggregator"`.
=> fix: ensure allocation end time is always valid

master/internal/task/allocation.go, master/internal/task/rendezvous.go
In 0.17.0 (push arch) we had a regression such that failing to rendezvous after 10m would cause a failure rather than just a warning. This PR comprises 2 small changes. First, the behavior is reverted back to the old. Second, the deadline does not start until the first connection to avoid spurious warnings for things such as long start up scripts. Both are done rather than just the second since for k8s the kill resulting from not suppressing the error could still be incorrect.
=> fix: trial rendezvous timeout should just warn

master/static/srv/get_experiments.sql
Previously, the query for `get_experiments.sql` was something like: CTE with filtered experiments, CTE to make page info from filtered experiments, CTE to apply page info to filtered experiments (so, filtered paginated experiments), then form the result from these CTEs. The first CTE is very expensive because it does a lot of work that gets thrown away by pagination; this change refactors the query to minimize this wasted work. This results in a bit of unfortunate code duplication but I think this is fine.
previous plan (on a db with 3k experiments)
```
Result  (cost=30629.29..30629.30 rows=1 width=64) (actual time=84.627..84.633 rows=1 loops=1)
CTE filtered_exps
->  Hash Join  (cost=23.95..30263.61 rows=3540 width=334) (actual time=0.070..81.317 rows=3540 loops=1)
Hash Cond: (e.owner_id …
```
=> perf: refactor get_experiments.sql for a better query plan

master/internal/resourcemanagers/agent_resource_manager.go, master/internal/resourcemanagers/provisioner/aws_config.go, master/internal/resourcemanagers/provisioner/gcp_config.go, webui/react/src/components/ResourcePoolCardLight.tsx, webui/react/src/components/SlotAllocationBar.tsx
For GCP instances, move accelerator information from `InstanceType` to `Accelerator`
For AWS instances, add number of GPU for `Accelerator`
Minor fix for allocation bar to accommodate aux containers 
Navigate to `/clusters` page with AWS/GCP clusters and verify `Accelerator` field displayed as expected
=> fix: `accelerator` field for GCP instance

webui/react/src/components/RadioGroup.test.tsx
Following our WebUI plan, adding interaction tests to RadioGroups with labels, and RadioGroups with icons only.
`make test` in webui/react
For the icons I needed to do document.querySelector. I tried adding `role="button"` or `role="radio"` to the radio button options for accessibility and to use screen.getAllByRole. This got the typescript error `Property 'role' does not exist on type 'IntrinsicAttributes & RadioButtonProps & RefAttributes<any>'` during build.
=> chore: Add interaction tests for RadioGroup [DET-6662]

examples/computer_vision/cifar10_pytorch/model_def.py
Download cifar10 only once per node in cifar10_pytorch example. [DET-6801]
Run the example at `computer_vision/cifar10_pytorch/distributed.yaml`, i.e. from root directory run:
```
cd computer_vision/cifar10_pytorch/distributed.yaml && det experiment create distributed.yaml .
```
The trial logs should contain the string `Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to data/cifar-10-python.tar.gz` exactly once per node.  It's a 16 GPU experiment, so if nodes have 8 GPUs it should appear twice.
Previously, a different temp directory was made for each rank to hold independent copies of the dataset.  Instead, this changes the model to use a single fixed directory `data`, and FileLocks to ensure only one rank attempts to download at once.  All other ranks after the first …
=> fix: download cifar10 only once per node in cifar10_pytorch example

tools/scripts/update-bumpenvs-yaml.py
Add `update-bumpenvs-yaml.py` support for dev builds generated by https://github.com/determined-ai/environments/pull/135
- `--dev` option to use "dev" builds because they have suffixed names. 
- `--no-cloud-images` option to skip cloud images if you didn't elect to build these
This is a development & testing tooling only.
1. Push an upstream branch to environments and request a docker image build and (optional) cloud image build. Wait for it to complete.
2. Run `./update-bumpenvs-yaml.py --dev --no-cloud-images ./bumpenvs.yaml COMMIT_ID` or `./update-bumpenvs-yaml.py --dev ./bumpenvs.yaml COMMIT_ID` depending on whether the cloud images were built.
3. Use bumpenvs normally.
=> chore: dev mode for `update-bumpenvs-yaml`.

master/internal/core.go, master/internal/core_searcher.go
Returns an API endpoint which is used by the CLI's `det preview-search`. Re-implementing the code in the new API would take an additional time commitment.
`det preview-search path/to/configfile.yaml`
=> fix: Restore det preview-search in CLI [DET-6850]

docs/release-notes/invalid-hp-dtrain.txt, master/internal/api_trials.go, master/internal/experiment.go, master/internal/trial.go, master/pkg/searcher/searcher.go
This change modifies the searcher logic to allow multiple invalid HP exits per trial. Exits after the first are ignored. This is useful for multi-rank trials to invalid HP without coordination. The change in behavior in this change is that now, rather than the experiment failing violently on the receipt of the 2nd invalid HP, nothing will happen. Nothing includes no kill, cancel, etc. The master will just wait for the trial to exit on its own, so it is a bit susceptible to hangs.
=> fix: allow ranks to report independent early exits [DET-6792, DET-6835]

master/internal/api_user.go, master/internal/db/postgres_users.go
Create a user with a password via the REST API.
```
export DET_MASTER=http://localhost:8080
export TOKEN=$(curl -X POST -d '{"username": "admin", "password": ""}' ${DET_MASTER}/api/v1/auth/login | jq '.token' | sed 's/"//g')
curl -H "Authorization: Bearer ${TOKEN}" -H  "accept: application/json" -X POST "${DET_MASTER}/api/v1/users" -d '{"user": {"username": "mytestuser", "admin": false, "active": true}, "password": "asdf"}'
det user login mytestuser
```
=> fix: create user with password broken [DET-6852]

.circleci/config.yml, .circleci/devcluster/custom-agent-version.devcluster.yaml, .circleci/devcluster/postgres-with-ssl.devcluster.yaml, e2e_tests/pytest.ini, e2e_tests/tests/cluster/test_users.py, e2e_tests/tests/template/test_template.py, e2e_tests/tests/test_logging.py
For rolling upgrades to work properly, we need the master to be able to
communicate with agents from previous versions of Determined. (At least
for now, we're focusing on an upgrade strategy where the master is
upgraded first and the agents second.) And a first step toward ensuring
that is running tests on a cluster with mismatched versions, which this
adds using a custom devcluster config.
Strategy for determining which previous version(s) to use in general
TBD; perhaps 0.x.0 for each minor version, and maybe an occasional later
0.x.y, though that won't work right now because of a recent change to
logging.
=> test: add test for cross-version master/agent clusters

examples/graphs/proteins_pytorch_geometric/adaptive.yaml, examples/graphs/proteins_pytorch_geometric/const.yaml, examples/graphs/proteins_pytorch_geometric/distributed.yaml, examples/graphs/proteins_pytorch_geometric/startup-hook.sh
Prevent pytorch geometric nightly test timeout
`test_protein_pytorch_geometric` in nightly E2E GPU job should run successfully.
No testing needed for release / outside of CI.
Needed to update image/wheel for install to be quick enough, due to order of installs and incompatibility with the current `torch-geometric` version.
Also removed `cpu` images since it appears CUDA is required to run the model.
=> fix: prevent pytorch geometric nightly test timeout

harness/determined/pytorch/_reducer.py, model_hub/model_hub/mmdetection/_trial.py
Use @typing.overload and typing.TypeVar to make sure that the following
code snippets avoid static analysis issues:
reducer = wrap_reducer(my_reducer_fn, ...)
reducer.update()  # avoid "MetricReducer has no .update"
class MyReducer():
def my_update(...):
...
reducer = wrap_reducer(MyReducer(), ...)
reducer.my_update()  # avoid "MetricReducer has no .my_update"
`mypy` is capable enough to handle this, but IMO this means that the `wrap_reducer` API should really be two separate calls:
- `wrap_simple_reducer(fn: Callable) -> SimpleReducer`
- `register_reducer(metric_reducer: MetricReducer) -> None`
I verified that running `mypy model_def.py` on the following model definition reproduced the errors without this fix, and I made sure that the errors were gone with this fix.
```python
from typing …
```
=> fix: update types for pytorch custom reducers

master/internal/restore.go
When restoring experiments, we encounter a nil pointer exception due to the lack of `Owner.Username`. This makes sure we populate the field during restoration.
=> fix: nil pointer exception when restoring experiments

master/pkg/protoutils/converter.go
"just write the struct as json and unmarshal it into protobuf" is not a
computationally free operation or an acceptable strategy overall.
Without some syntactic sugar though, coverting e.g. a
map[string]interface{} in go to a to a protobuf struct.Struct is
actually a pain because the conversion function can return an error.
ProtoConverter just captures and holds those errors until you've called
all of your conversion functions.
I pulled this out of the checkpoints feature branch as its own PR in case we wanted to land it independently, but I don't plan on overhauling existing code to use this, so I can land it with the rest of the checkpoints feature branch if reviewers prefer that.
=> chore: add ProtoConverter

harness/determined/cli/experiment.py
Change where we define `wl_output` so that `det e describe` works on zero-trial experiments.
=> fix: CLI describes experiment with zero trials

master/internal/core.go, master/internal/core_experiment.go
The "Download Experiment Code" button uses this legacy API route, which we now return. The Web UI would not be able to convert the encoded ZIP / JSON from the new `/api/v1/experiments/:id/model_def` endpoint without some additional work.
On latest-master, go to an experiment detail page and click "Download Experiment Code". If the button is not visible, click the three dots in the top right to select it from the dropdown.
=> fix: Restore /model_def / getExperimentModelDefinition

agent/go.mod, agent/go.sum, master/go.mod, master/go.sum, master/internal/db/postgres.go, master/internal/db/postgres_cluster_intg_test.go, master/internal/db/postgres_experiments_intg_test.go, master/internal/db/postgres_model_intg_test.go, master/internal/db/postgres_tasks_intg_test.go, master/internal/db/postgres_test_utils.go, master/internal/db/postgres_trial_intg_test.go, master/test/integration/api/main_test.go, master/test/testutils/fixtures.go
The bun.DB singleton will be the basis of future database code.
It was agreed that making the database connection a singleton is fine
because at runtime, because we only support one database anyway.  This
will allow for very concise and easy interfaces, like trials.List(...)
to list trials from the database.
When we want to unit test something like the trial actor (which makes a
few calls to the database), we can pass it a small interface to use, and
mock just that interface in the unit test.
=> chore: add bun.DB singleton in master

e2e_tests/tests/cluster/test_logging.py
We need a GPU acquisition/warmup step else using timeouts is doomed to fail if the test is the first test in a split. Ticketed as DET-5803.
=> test: turn off timeout for now on logs tests

.circleci/config.yml, harness/tests/requirements/requirements-cli.txt, harness/tests/requirements/requirements-harness.txt, requirements.txt
windows CLI tests broken due to uninstallable deepspeed dependency.  fix by separating out dependencies for cli tests and other harness tests.  
CLI and harness-unit tests should pass.
=> fix: cli win tests

.circleci/config.yml, Makefile, harness/tests/requirements/requirements-harness.txt
Make sure pytorch is always installed before deepspeed when installing from requirements files.  
`pip install -r requirements.txt` does not guarantee items are installed in order so there may be flaky tests if deepspeed is installed before pytorch.  This PR makes sure to install torch before we install deepspeed when developing locally and for ci.  
=> fix: add pytorch as requirement before deepspeed is installed

docs/release-notes/3723-model-registry-api.txt, e2e_tests/tests/cluster/test_model_registry.py, harness/determined/common/experimental/determined.py, harness/determined/experimental/client.py, master/internal/api_model.go, master/static/srv/get_model_by_id.sql, webui/react/src/components/Table.tsx, webui/react/src/pages/ModelDetails/ModelHeader.tsx, webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx, webui/react/src/routes/utils.ts
This change would accept  `/det/models/:model_id` and `/api/v1/models/:model_id` as valid routes. A model name can't be all digits, so there should be no collision between model names and IDs.  The `GetModel` Go code is also used in PatchModel, GetModelVersion, PostModelVersion, and GetModelVersions, but we don't need to support IDs there explicitly.
The second part of the request is **displaying** the ID and **making the permalink visible**. I've added the number to breadcrumbs in the PR as a start. We could change to use the model ID in WebUI's links, so you are always on the permalink URL. Or we can make a permalink button.
Current proposal for updated breadcrumbs:
Go to `/api/v1/models` to see your list of models
- Given any model, `/api/v1/models/:model_name` and …
=> feat: Accept model.id for lookups, show model.id in UI [DPS-49]

docs/training-apis/api-pytorch-advanced.txt
Example code and explanation of how to use PyTorch's native Automatic Mixed Precision API.
I've checked the formatting on a local service.
These details are already well-covered by tests (which can also serve as complete examples of the various approaches here) in e2e_tests/tests/fixtures/pytorch_amp.
=> docs: Add examples and documentation for AMP [DET-5170]

webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.tsx
fix: keep page from crashing when trial/hyperparameters are not loaded yet [DET-6951]
- `cd examples/computer_vision/cifar10_pytorch`
- `det e create distributed.yaml .`
navigate to /experiments/<new_experimentid> and click on hyperparameters before experiment is able to start.
page should not crash
It looks like it first crops up in [3743](https://github.com/determined-ai/determined/pull/3743), which prevented the loading limbo state.
seems like if there is only one trial for an experiment we shouldn't have to wait for it to start in order to be able to display the hyperparameters, but [this](https://github.com/determined-ai/determined/blob/e35972d83ca67b5fe3b4672248e0db6d940e97b5/webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx#L64) is unable to fetch. 
more …
=> fix: keep page from crashing when trial/hyperparameters are not loaded yet [DET-6951]

e2e_tests/tests/cluster/test_workspace_org.py, harness/determined/common/api/bindings.py, master/internal/api_project.go, master/internal/api_workspace.go, master/static/srv/delete_project.sql, master/static/srv/delete_workspace.sql, master/static/srv/get_project.sql, master/static/srv/get_workspace.sql, master/static/srv/get_workspace_projects.sql, master/static/srv/get_workspaces.sql, master/static/srv/insert_project.sql, master/static/srv/insert_workspace.sql, master/static/srv/update_project.sql, master/static/srv/update_workspace.sql, proto/src/determined/project/v1/project.proto, proto/src/determined/workspace/v1/workspace.proto, webui/react/src/services/api-ts-sdk/api.ts
Handles the special case of immutable workspaces and projects (the default ones created to hold existing experiments). This should prevent PATCH to change their name or DELETE to remove them.  The column already existed but here we're adding it to the proto / API.
I added some lines to the `e2e_test`
=> feat: Prevent PATCH/DELETE on default workspace/project [DET-6952]

master/static/migrations/20220329122139_set_default_exp_project.down.sql, master/static/migrations/20220329122139_set_default_exp_project.up.sql
This updates the experiments table project_id column to have a default value (the ID of the Uncategorized project).
The Uncategorized / default project was created in the same migration as the table was created, so project_id is probably 1, but I wanted to avoid assumptions and errors about the IDs, so I needed to do this `EXECUTE format` query.
It's not possible to do a `WITH (SELECT min(id) from projects)` before `ALTER TABLE ALTER COLUMN...` or use a more conventional `\set variable`, as best I can tell.
New experiments should have project_id = 1 (or whatever the default project is) instead of NULL.
This should also update recent experiments.
=> fix: Set default project for experiments.project_id [DET-6958]

e2e_tests/tests/cluster/test_workspace_org.py, harness/determined/common/api/bindings.py, master/internal/api_experiment.go, master/internal/api_project.go, master/static/srv/get_experiment.sql, master/static/srv/get_experiments.sql, master/static/srv/move_experiment.sql, master/static/srv/move_project.sql, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/experiment.proto, proto/src/determined/api/v1/project.proto, proto/src/determined/experiment/v1/experiment.proto, webui/react/src/services/api-ts-sdk/api.ts
Add endpoints to move a project between workspaces, or move an experiment between projects.
**This merges into the workspaces_projects feature branch.**
The automated tests move a project, but do not properly test moving an experiment, there is an issue with how deleting the experiment would work.
=> feat: Add endpoints to move projects and experiments [DET-6817]

harness/determined/cli/experiment.py
This removes a [python 3.10-specific syntax](https://peps.python.org/pep-0604/) from the codebase.
I can't figure out how the code in question runs at all.  It must be some sort of runtime optimization that isn't considering types at all, because a simple command like:
```
python -c 'a: int | str = 1'
```
throws an error:
```
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
I was occasionally (but not consistently) seeing mypy errors in make check.
=> fix: remove python 3.10 union-type syntax

docs/conf.py
Docs failing due to import error of `determined.pytorch.deepspeed` module when building reference for DeepSpeedTrial.
=> fix: docs build failure for deepspeed reference

harness/determined/cli/__init__.py, harness/determined/cli/cli.py, harness/determined/cli/workspace.py, harness/determined/common/api/bindings.py, master/internal/api_workspace.go, proto/src/determined/api/v1/workspace.proto, webui/react/src/services/api-ts-sdk/api.ts
Adds CLI commands which call the Python API bindings for Workspaces.
I decided to add a sort-by-id option to GetWorkspaces and GetWorkspaceProjects instead of sending "Unspecified"
**This merges into the workspace/projects feature branch**
`det workspace help` == `det w help`
`det w list` - the default workspace ("Uncategorized") should already be here
`det w list-projects Uncategorized` - the default project ("Uncategorized") should already be here
`det w describe Uncategorized` - prints this workspace row and then a table of projects
`det w create NewName` - creates a new workspace verifiable with `det w list`
`det w list` - order should be Uncategorized, NewName
`det w list --sort-by name` - order should be NewName, Uncategorized
`det w edit NewName UpdatedName`
`det w delete …
=> feat: CLI supports Workspaces [DET-6819]

webui/react/src/components/Spinner.tsx
Add a prop to the `<Spinner>` component that provides the option to not render content while loading/spinning [DET-6275]
[DET-6275]: https://determinedai.atlassian.net/browse/DET-6275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add conditionalRender prop to Spinner

webui/react/src/hooks/useModal/useModalExperimentCreate.tsx
The "full config" version of the "Fork" and "Continue Trial" modals need to be wider than the current default of 416px.
=> fix: make "Show full config" modal larger

docs/release-notes/cli-uuid-prefixes.txt, harness/determined/cli/command.py, harness/determined/cli/notebook.py, harness/determined/cli/remote.py, harness/determined/cli/shell.py, harness/determined/cli/task.py, harness/determined/cli/tensorboard.py, harness/tests/cli/test_cli.py
For user convenience, this allows the CLI to accept an incomplete prefix
of a task UUID as long as there is a unique UUID that it corresponds to.
=> feat: allow the CLI to accept incomplete task UUIDs [DET-6706]

e2e_tests/tests/nightly/compute_stats.py, master/static/srv/get_raw_allocation.sql
Fix compare stats for e2e test when agent and instance is not applicable
Verify that e2e tests on GKE machine pass
=> fix: e2e test stats for gke machine

harness/determined/launch/horovod.py
This flag was left in the --help text on accident.
=> chore: remove internal flag from det.launch.horovod --help

harness/determined/common/_logging.py, harness/determined/exec/harness.py
We attach timestamps to all logs after-the-fact, so the python logging
library needs to be configured to not also emit timestamps.
Apparently, this was broken in distributed training since 0.17.0, and
recently it became broken in non-distributed training as well.
The source of the bug was that there used to be two common paths by
which we configured logs, which I did not realize, and so in the push
architecture refactor I unwittingly took the worse one and used it on a
new code path.
This fix deletes that way to configure logs and uses the remaining way
everywhere.
=> fix: avoid double-timestamps in logs

agent/internal/agent.go, e2e_tests/tests/cluster/test_agent.py, harness/determined/cli/agent.py, harness/determined/common/api/bindings.py, master/internal/resourcemanagers/agent/agent.go, master/internal/resourcemanagers/agent/agents.go, master/pkg/model/agent.go, proto/src/determined/agent/v1/agent.proto, webui/react/src/services/api-ts-sdk/api.ts
Simply make the agent report its Determined version as a query parameter
when it connects to the master, and then thread that information through
to the API endpoint and CLI.
The test should ideally be a cross-version test so that we can confirm that the endpoint returns the actual agent version and not always the current master version, but we can't do that right now because older agents don't report their versions at all. (At least using older agents just leads to the master treating the version as an empty string, not erroring out.)
=> feat: show agent version in `/agents` and `det agent list` [DET-6847]

harness/determined/_core/_context.py, harness/determined/_core/_searcher.py, harness/determined/layers/_workload_sequencer.py, harness/tests/core/test_searcher.py, harness/tests/parallel.py, harness/tests/test_ipc.py
core_context.searcher.ops() needs to be coordinated across workers
the same way that core_context.preemption.should_preempt() is
coordinated across workers.
This change also includes tests for the new functionality.
I labeled this as a "user-facing change" because it's a deviation from previously-advertised Core API specs, even though technically it's still not a released API so it isn't any sort of breaking change.
=> feat: make core.Searcher multiworker-safe

e2e_tests/tests/cluster/test_agent_disable.py, e2e_tests/tests/cluster/test_agent_restart.py, e2e_tests/tests/cluster/test_checkpoints.py, e2e_tests/tests/experiment/__init__.py, e2e_tests/tests/experiment/experiment.py, e2e_tests/tests/experiment/test_core.py, e2e_tests/tests/experiment/test_noop.py, e2e_tests/tests/experiment/test_pytorch.py, e2e_tests/tests/experiment/test_tf_estimator.py, e2e_tests/tests/experiment/test_tf_keras.py, harness/determined/cli/checkpoint.py, harness/determined/cli/experiment.py, harness/determined/common/api/bindings.py, proto/src/determined/api/v1/experiment.proto, proto/src/determined/api/v1/trial.proto, proto/src/determined/trial/v1/trial.proto, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/decoder.ts
During earlier changes to e2e_tests (#3539) I avoided issues with `Optional[]` types with some additional code -- `assert training_workloads is not None` or `for w in (workloads or []):`. Even if a trial has 0 workloads, the API will return an empty array, so we can mark this field as required and avoid `Optional[]` typing.  Similar reasoning to require metrics on a `MetricsWorkload`.
Marking these as required allows us to remove or simplify some code in e2e_tests.
I also replace `workloads_for_mode(wl, "training")` with `workloads_with_training(wl)` and other specific functions to avoid type differences between MetricWorkload and CheckpointWorkload.
=> chore: Clean up tests with fewer Optional types and asserts

e2e_tests/tests/fixtures/metric_maker/metric_maker.py, e2e_tests/tests/fixtures/no_op/model_def.py, examples/deepspeed/gpt_neox/gpt2_trial.py, harness/determined/_core/__init__.py, harness/determined/_core/_checkpoint.py, harness/determined/_core/_context.py, harness/determined/_core/_distributed.py, harness/determined/_core/_preempt.py, harness/determined/_core/_searcher.py, harness/determined/_core/_train.py, harness/determined/estimator/_estimator_context.py, harness/determined/estimator/_estimator_trial.py, harness/determined/keras/_tf_keras_trial.py, harness/determined/layers/_workload_sequencer.py, harness/determined/pytorch/_metric_utils.py, harness/determined/pytorch/_pytorch_context.py, harness/determined/pytorch/_pytorch_trial.py, harness/determined/pytorch/deepspeed/_deepspeed_context.py, harness/determined/pytorch/deepspeed/_deepspeed_trial.py, harness/tests/core/test_preempt.py, harness/tests/core/test_searcher.py, harness/tests/experiment/pytorch/test_reducer.py, harness/tests/test_ipc.py
Part 1: shorten names and use a consistent part of speech:
core_context.training -> core_context.train
core_context.checkpointing -> core_context.checkpoint
core_context.preemption -> core_context.preempt
Part 2: Change the class name of each component of the Core API to
include "Context".  This won't really affect users but it's a bit clearer.
core.Searcher -> core.SearcherContext
core.Training -> core.TrainContext
core.Preemption -> core.PreemptContext
core.Checkpointing -> core.CheckpointContext
Part 3: avoid abbreviations
core_context.search.ops -> core_context.search.operations
core.SearcherOp -> core.SearcherOperation
Part 4: anything that must only be called by the chief is named report_*
SearcherOperation.complete() -> SearcherOperation.report_completed()
Part 5: expose …
=> chore: sweeping rename of Core API components

docs/training-apis/experiment-config.txt
=> docs: fix description of scheduling_unit behavior

e2e_tests/tests/fixtures/metric_maker/metric_maker.py, e2e_tests/tests/fixtures/no_op/model_def.py, harness/determined/_core/_checkpoint.py, harness/determined/common/storage/__init__.py, harness/determined/common/storage/azure.py, harness/determined/common/storage/base.py, harness/determined/common/storage/cloud.py, harness/determined/common/storage/gcs.py, harness/determined/common/storage/hdfs.py, harness/determined/common/storage/s3.py, harness/determined/common/storage/shared.py, harness/determined/estimator/_estimator_trial.py, harness/determined/keras/_tf_keras_trial.py, harness/determined/pytorch/_pytorch_trial.py, harness/determined/pytorch/deepspeed/_deepspeed_trial.py, harness/tests/storage/test_shared_fs.py, harness/tests/storage/util.py, harness/tests/test_gc_harness.py
- Take checkpointing business logic out of StorageManager; functions now
operate in terms of src and dst, not storage_id (checkpoint uuid).
This is not clearly necessary yet, but when we support sharded
checkpointing we will certainly need to separate the storage layer
from the checkpointing layer (so as to support multiple storage layer
calls for a single checkpointing operation).
- Add upload(src,dst) and download(src,dst) to the StorageManager
interface. Also add unit tests for upload/download.
- Redesign StorageManager to use pathlib.Path everywhere, which makes
the src/dst distinction a bit clearer.
- Introduce CloudStorageManager, which defines restore_path() and
post_store_path() for all cloud-based storage managers in terms of
upload. This saves a good chunk of duplicate code.
- …
=> chore: update StorageManager and extend CheckpointContext

e2e_tests/tests/nightly/test_distributed.py, examples/deepspeed/deepspeed_dcgan/cifar10_zero2.yaml, examples/deepspeed/deepspeed_dcgan/mnist.yaml, examples/deepspeed/deepspeed_dcgan/mnist_grad_accum.yaml
Typo made it into `test_distributed` for DeepSpeed DCGAN example because I ran the wrong nightlies on the PR.
Also fixes entrypoint formatting.
Check that DeepSpeed distributed nightly passes
=> chore: fix deepspeed nightly tests

harness/determined/_core/__init__.py, harness/determined/_core/_checkpoint.py, harness/determined/_core/_distributed.py, harness/tests/core/test_checkpoint.py
In multi-worker settings, it is important that workers on the same node
share a single copy of a downloaded checkpoint.  On an 8-GPU compute
node, that amounts to an 8x bandwidth savings, and also it prevents
workers from stepping on each other's files.
This PR introduces DownloadMode.LocalWorkersShareDownload and
DownloadMode.NoSharedDownload settings, which apply to both
CheckpointContext.download() and CheckpointContext.restore_path().
This allows users to use .download() with or without this coordination,
in case they have special use cases that don't need coordination.
This PR also introduces unit tests for the CheckpointContext.
=> feat: add core.DownloadMode

harness/determined/_core/_train.py, harness/determined/layers/_workload_sequencer.py
get_last_validation() had a bug where it might return a different value
before vs after you report any metrics.
Fixing it would require reconsidering how metrics are archived in the
master, which is a lot of work for an API that seems unlikely to be
useful to users, so we'll just make it internal.
=> chore: demote _get_last_validation to internal

harness/determined/cli/experiment.py
As we were working on the Determined Project CLI, I noticed that the experiments CLI claims that the `--all` flag is needed to show archived experiments in `det experiment list`. Yet currently archived experiments are included by default.
Bug originated in #3418 because we started using the new API instead of sending filter=all to the legacy API.
This does not affect the Experiments API -- it is just changing what the CLI calls.
Run `det experiment list` to see which experiments are visible and completed running.
Pick one and archive it: `det experiment archive [id]`
Try `det experiment list` (archived experiment is now hidden)
Try `det experiment list --all` (archived experiment is included)
If you have access to an instance with other users' experiments, `det -m URL experiment list …
=> fix: Hide archived experiments unless using --all [DET-7042]

harness/determined/cli/__init__.py, harness/determined/cli/cli.py, harness/determined/cli/project.py, harness/determined/cli/workspace.py, master/internal/api_model.go, master/internal/api_project.go, master/internal/api_workspace.go
Adds CLI commands which call the Python API bindings for Projects.
**This merges into the workspace/projects feature branch**
can use `det project help` or `det p help`
`det p list Uncategorized` - the default workspace ("Uncategorized") will already be set up on your db and have a default project (also named "Uncategorized")
`det p list-experiments Uncategorized Uncategorized` - should list all experiments in your db
`det p create Uncategorized Added` - creates a new project inside Uncategorized workspace
`det p describe Uncategorized Added` - prints the new project row and an (empty) table of experiments
`det p list Uncategorized --sort-by name` - order should be Added, Uncategorized
`det p edit Uncategorized Added --new_name UpdatedName --description Example` - updates project
`det p …
=> feat: CLI supports Projects [DET-6820]

webui/react/src/components/CheckpointModal.tsx, webui/react/src/pages/ModelVersionDetails.tsx, webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx, webui/react/src/pages/TrialDetails/TrialInfoBox.tsx, webui/react/src/services/decoder.ts, webui/react/src/types.ts, webui/react/src/utils/workload.test.ts, webui/react/src/utils/workload.ts
chore: bring webui checkpoint types into alignment with CoreAPI [DET-6676]
Many fields previously required in checkpoints are now optional. This PR brings the WebUI types into alignment and provides a fallback UX on the ModelVersionDetails page for when experiment_id, trial_id, etc. are not available.
Check out the branch and build devcluster from scratch. May have to `rm -rf ~/.postgres` (proceed with care) in order to get the migrations to run properly.
Create a simple mnist pytorch with a checkpoint, register the checkpoint to a model, and go to model version page. things should be ok.
The real test is that with the new schema, many fields are optional that were previously required. model checkpoints automatically have most of those fields, but one way to simulate their absence is to …
=> chore: bring webui checkpoint types into alignment with CoreAPI [DET-6676]

master/internal/api_experiment.go, master/test/integration/api/api_checkpoints_test.go
Checkpoints without searcher metric were placed at the bottom of the results even when the requested sort attribute was not search metric.
Enhance api_checkpoints_test.go
=> fix: null searcher metric at bottom only if sorting by searcher metric

harness/determined/cli/workspace.py, harness/determined/common/api/bindings.py, master/static/srv/get_workspace.sql, master/static/srv/get_workspaces.sql, master/static/srv/update_workspace.sql, proto/src/determined/workspace/v1/workspace.proto, webui/react/src/services/api-ts-sdk/api.ts
Adds numProjects / num_projects count associated with each workspace. Affects API and CLI.
- The /api/v1/workspaces response should include numProjects in each record (with workspace 1 having numProjects: 1)
- The /api/v1/workspaces/1 (default workspace) should include numProjects: 1
- In the CLI, `det w list` should list workspaces table with "# Projects" column, default workspace has "1"
- `det w describe Uncategorized` should print table with numProjects = 1
- `det w create test` should create a workspace and print out table numProjects = 0
- `det w describe test`, `det w edit test test`, etc. should return table with numProjects = 0
=> feat: Add numProjects field to workspaces API, CLI [DET-7064]

e2e_tests/tests/nightly/compute_stats.py, e2e_tests/tests/requirements.txt
Parse different time format in stats script
Run `e2e_test` based on local/cloud instance should all work
=> fix: parse different time format in compare stats script [DET-7039]

master/static/srv/update_model_version.sql
Micro-fix for this [error](https://app.circleci.com/pipelines/github/determined-ai/determined/21155/workflows/83aad580-1cad-4ecb-ab22-980cf33e7933/jobs/665352):
```
determined.common.api.errors.APIException: {"error":{"code":13,"reason":"Internal","error":"error updating model version 1 in database: error running query: update_model_version: ERROR: operator does not exist: text = uuid (SQLSTATE 42883)"}}
```
=> fix: avoid type mismatch in update_model_version.sql

.circleci/config.yml, tools/scripts/scan-docker-images.sh
These are vulnerabilities that for various reasons we can't address further than we already have. Also, bumping the machine image used for the scans to eliminate a Linux kernel vulnerability that comes up in scans.
We'll see what the scan says next week!
=> chore: Update list of false alarms in Docker image scanning

e2e_tests/tests/experiment/test_core.py, harness/determined/cli/checkpoint.py, harness/determined/cli/experiment.py, harness/determined/cli/model.py, harness/determined/common/experimental/checkpoint/_checkpoint.py, harness/determined/core/_checkpoint.py
Handle multiple issues:
1. Align the shape of `experimental.Checkpoint` with the Checkpoint protobuf representation.
2. Handle downstream issues detected by integration and e2e tests:
a. As the generic json encoder does not handle some corner cases we could not rely on bindings to invoke Report Checkpoint endpoint. So we have to switch back to raw requests posting.
b. Adjust an e2e test to reflect the fact that we now have `format`, `framework`, and `latest_batch` automatically added into the "free form" metadata dict.
Note: `XXX` prefix in comments is @rb-determined-ai 's way to designate unfinished CoreAPI items in `generic-checkpoints`.
| Old Checkpoint Attribute | Disposition |
| ------------------------|--------------|
| Checkpoint.uuid                |   |
| …
=> fix: _report_checkpoint correct POST payload

e2e_tests/tests/cluster/test_logging.py, e2e_tests/tests/conftest.py, e2e_tests/tests/experiment/test_profiling.py
fix: add test warmup command e2e [DET=5803] 
Made sure the e2e_tests run fine (even with the timeouts specified for tests in test_logging.py and and test_profiling.py)
=> fix: add test warmup command e2e [DET-5803] 

webui/react/src/components/ResourcePoolCardLight.module.scss, webui/react/src/components/ResourcePoolCardLight.tsx, webui/react/src/pages/Cluster/ClusterHistoricalUsage.module.scss, webui/react/src/pages/Cluster/ClusterOverallBar.tsx, webui/react/src/pages/Cluster/ClusterOverview.tsx, webui/react/src/pages/Clusters.module.scss, webui/react/src/pages/Clusters.tsx, webui/react/src/pages/Clusters/ClustersOverview.tsx
Add overall allocation bar and historical usage page to new cluster page, allocation bar and historical page should behave exactly like the old one.
Navigate to `/clusters` page to verify the allocation bar and `Historical Usage` tab exists.
=> feat: Add overall allocation bar to new cluster page [DET-7074]

master/internal/core.go
chore: document usage of `/ws/data-layer` [DET-6685]
does this look right?
[DET-6685]: https://determinedai.atlassian.net/browse/DET-6685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: document usage of /ws/data-layer [DET-6685]

master/internal/db/postgres_proto.go, master/pkg/model/types.go, master/pkg/searcher/asha.go, master/pkg/searcher/asha_stopping.go
This is simply applying the recently added "float extended with JSON
handling for infinite values" type to another place (and moving it to a
public place, and adding unmarshalling support, where it only had
marshalling before). See f915a695 for its introduction and other
context.
Possibly we should look into redoing marshalling entirely so we can add
support for infinities (and anything else that might require special
handling in the future) in just the one place rather than peppering this
type and type conversions everywhere. But that's going to be a whole
other thing.
=> fix: handle infinite metrics in searcher snapshots [DET-7122]

e2e_tests/tests/cluster/test_workspace_org.py, harness/determined/common/api/bindings.py, harness/determined/common/experimental/session.py, master/internal/api_project.go, master/internal/api_workspace.go, master/static/migrations/20220422101847_pin-workspaces.down.sql, master/static/migrations/20220422101847_pin-workspaces.up.sql, master/static/srv/delete_workspace.sql, master/static/srv/get_workspace.sql, master/static/srv/get_workspaces.sql, master/static/srv/pin_workspace.sql, master/static/srv/unpin_workspace.sql, master/static/srv/update_workspace.sql, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/workspace.proto, proto/src/determined/workspace/v1/workspace.proto, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/types.ts
- A user can pin a workspace to signify that it is important / current to their work.
- API supports pinning, unpinning, GetWorkspaces optional filtering by pinned/unpinned
- Returned Workspace object (GetWorkspace, GetWorkspaces, PatchWorkspace) include `"pinned": bool` field
- Pins contain a `created_at` column which could be used for sorting, but TODO
- Includes e2e_tests for pinning, checking len(pinned) = 1, unpinning, then checking len(pinned) = 0.
- Should test GetWorkspace and GetWorkspaces
=> feat: Users-specific pinned workspaces

docs/release-notes/fix-noverify.txt, harness/determined/cli/session.py
OSS user has reported we were defaulting no `noverify` in `setup_session` helper: https://determined-community.slack.com/archives/CV3MTNZ6U/p1650642072594889
We don't do it in cli cert setups elsewhere, and all of `noverify`, `cert_path`, and `cert_name` options on `args` seem to be dead. 
CLI shouldn't print urllib's noverify warnings when used with HTTPS cluster.
=> fix: do not default to `noverify` for `bindings` sessions in CLI.

webui/react/src/components/ModalItemDelete.tsx, webui/react/src/pages/ModelDetails.tsx, webui/react/src/pages/ModelDetails/ModelHeader.tsx, webui/react/src/pages/ModelRegistry.tsx, webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
feat: add modal to explain why users cannot delete items [DET-6998]
The "Delete" button is no longer disabled when deleting a model or deregistering a model version. Instead a modal is shown explaining that only an admin or the user who created the item is able to delete it. 
1. Using an admin account or the account of a user that has created the model or version, attempt to delete a model or deregister version. Everything should work as expected.
2. Using a non admin account or account of a user that did not create a model or version. Attempt to deregister a model or version. The "Delete" or "Deregister" button should be enabled. After clicking the button, a modal should show explaining that "Only the item creator or an admin can delete items from the model registry".
The …
=> feat: add modal to explain why users cannot delete items [DET-6998]

CODEOWNERS
Removing Gene as the owner of release notes, per his request.
=> chore: Removing CODEOWNERS entry for release notes

e2e_tests/tests/conftest.py
- when running [failing] tests locally, extra stack traces from `compare_stats` add unnecessary logs. add an option to disable them.
`pytest --no-compare-stats` skips stats comparison.
=> test: add option to disable `compare_stats`.

docs/tutorials/pytorch-porting-tutorial.txt
Rebuild docs and review affected page.
An indent was missing from a Python codeblock. The intention was clear.
=> docs: fix indent in pytorch-porting-tutorial

e2e_tests/tests/cluster/test_workspace_org.py, master/internal/db/postgres_cluster.go, master/static/srv/get_experiments.sql
Include our planned telemetry on workspace and project features:
- total count of workspaces and projects
- average projects-per-workspace and average experiments-per-project (excepting those in the default workspace + project)
Uses `::float` for averages, and `greatest(count(*), 1)` to avoid dividing by 0. You cannot make new projects in the default workspace, so there are no user-created projects in this situation.
=> feat: Telemetry of use of workspaces and projects

webui/react/src/pages/ExperimentList.tsx
fix: Ensure table offset does not exceed pagination total [DET-6829]
Currently, filtering can cause the ExperimentList table to show "no data" because the table pagination offset may exceed the total number of data points. For example if there are only 20 data points, but the pagination offset is 100, the table will show "no data". 
The following fix addresses the issue by subscribing to pagination changes, most importantly the value of "total". If the offset is determined to be great than the total, then the table is updated to show the correct last page of the current data set. An example can be seen below. 
https://user-images.githubusercontent.com/103522725/165338395-172bef94-d72b-44f4-a624-296c154833eb.mov
1. Reset any applied filters on the Experiments List table or apply a filter …
=> fix: Ensure table offset does not exceed pagination total [DET-6829]

e2e_tests/tests/cluster/test_workspace_org.py, harness/determined/common/api/bindings.py, master/internal/api_project.go, master/internal/db/postgres_cluster.go, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/project.proto, webui/react/src/services/api-ts-sdk/api.ts
- PutProjectNotes replaces any existing notes with the given array
- Includes telemetry for notes
- Includes e2e_test for PutProjectNotes
=> feat: PutProjectNotes to set notes on workspaces/projects

webui/react/src/hooks/useRegisterCheckpointModal.tsx
After a model is archived, it cannot add new Model Versions, so it should not be in the list of selectable models in the Register Checkpoint / new Model Version modal window.
In the current version the model appears, and trying to register a new model version throws an error. 
- Archive a model
- Go to an experiment with checkpoints
- Check list of models available when you register a checkpoint
=> fix: Prevent archived models from appearing in the Register Checkpoint modal [DET-7132]

examples/tutorials/core_api/4_distributed.py, harness/determined/common/experimental/checkpoint/_checkpoint.py, harness/determined/core/_checkpoint.py, harness/tests/core/test_checkpoint.py
A less ambitious change: save metadata to `metadata.json` as part of upload.
Initially (https://github.com/determined-ai/determined/pull/4010) I tried to push `metadata.json` into the checkpoint storage as part of `Checkpoint.add_metadata` and `Checkpoint.remove_metadata`. That did not work as the client typically does not have write access to the checkpoint storage directory in the case of shared_fs.
Instead we still save metadata into the local directory just before uploading it but only in `CheckpointContext`.
The good news: metadata is saved to checkpoint storage as part of `CheckpointContext.upload` and `CheckpointContext.store_path` (in addition to being saved to DB).
The sad news: if the user mutates metadata locally with python SDK (outside of Contexts/experiment execution) those …
=> feat: save metadata pre-upload

webui/react/src/components/LogViewer/LogViewerFilters.tsx
On the task logs page, the filter UI includes options for allocation, agent, container, rank, and levels.  Levels is constant, but the others are filled in by the database from all options available in the task logs.
When there is 0-1 option in a dropdown, `moreThanOne` already hides this dropdown (only Levels and Container dropdowns visible below).
When there is an empty string value, the containers dropdown already lists this option as "No Container". This PR adds "No Agent", "No Rank", and "No Allocation" to the other dynamic dropdowns in place of any empty string value.
=> fix: Human-readable option for empty filters in logs [DET-6781, DET-6999]

harness/determined/common/api/bindings.py, master/internal/api_user.go, master/internal/db/postgres_users.go, master/internal/user/api.go, master/internal/user/service.go, master/pkg/model/user.go, master/static/srv/20220228132402_store-profile-pics.down.sql, master/static/srv/20220228132402_store-profile-pics.up.sql, master/static/srv/get_user_image.sql, master/static/srv/list_users.sql, proto/src/determined/user/v1/user.proto, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/decoder.ts, webui/react/src/types.ts
Adds a database table to store a profile picture / user image. Adds an API endpoint for the client to fetch the user's profile image, showing it as the CSS background-image for the Avatar component (circle representing user).
**[edit: these were the issues with implementing in GRPC - we now use images directly]**:
- Type for images is `bytea` in Postgres, and `bytes` in GRPC. There is a size limit for `bytes` which is preventing larger images from being returned by the API. It's unclear whether we will continue using base64 to download images. It would be more efficient to have a URL which returns the image file not in a JSON wrapper.
- When we have multiple Avatar components (as in the Experiments table) these each make a request to the image API endpoint. Ideally the image would be …
=> feat: Create a table of user profile pictures [DET-6739]

harness/determined/common/api/bindings.py, master/pkg/model/experiment.go, master/static/migrations/20220423162505_generic-checkpoints.tx.up.sql, proto/src/determined/checkpoint/v1/checkpoint.proto, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/types.ts
Testing upgrade (creating a bunch of experiments with 0.17.6, upgrading to the current version, then accessing existing experiments, trials, checkpoints).
Error:
```
time="2022-04-28T03:27:32Z" level=error msg="finished unary call with code Internal" error="rpc error: code = Internal desc = failed to create experiment: failed to get checkpoint for source trial 162: error querying for latest trial checkpoint (162): sql: Scan error on column index 3, name \"allocation_id\": converting NULL to string is unsupported" grpc.code=Internal grpc.method=CreateExperiment grpc.service=determined.api.v1.Determined grpc.start_time="2022-04-28T03:27:32Z" grpc.time_ms=59.749 span.kind=server system=grpc
```
when trying to continue trial created with 0.17.6 after upgrading to the current version.
See …
=> fix: avoid null allocation id in checkpoint view

harness/determined/common/declarative_argparse.py
Adjust the default value when adding Boolean args for improved help output clarity.
Closes #4037
The `make test` is misbehaving on this old machine, but here's sketchy PoC output in the interim:
```python
Python 3.6.12 (default, Dec 02 2020, 09:44:23) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import argparse
>>> p = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
>>> k = False
>>> out = None
>>> p.add_argument("--k", dest="out", action="store_true", help="enable k", default=k)
_StoreTrueAction(option_strings=['--k'], dest='out', nargs=0, const=True, default=False, type=None, choices=None, help='enable k', metavar=None)
>>> p.add_argument("--no-k", dest="out", action="store_false", help="disable k", …
```
=> fix: Alter Boolean arg default handling

webui/react/package-lock.json, webui/react/package.json, webui/react/src/components/LogViewer/LogViewer.test.tsx, webui/react/src/components/LogViewer/LogViewer.tsx, webui/react/src/components/TrialLogPreview.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx, webui/react/src/pages/TaskLogs.tsx, webui/react/src/pages/TrialDetails/Profiles/useFetchAvailableSeries.ts, webui/react/src/pages/TrialDetails/Profiles/useFetchMetrics.tsx, webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx, webui/react/src/services/utils.ts, webui/react/src/utils/browser.ts
Rewrite the our stream reader by bringing in the same concepts from `can-ndjson-stream` for data parsing. The `can-ndjson-stream` has plagued us with numerous uncaught exceptions. More noticeable on FireFox than other browsers (other browsers tend to just show it as console.errors, where as FireFox breaks the page with something like the screenshot below).
Improvements:
* Reduce the `consumeStream` and `ndjsonStream` into a single `readStream`.
* Update `readStream` to process data as `ndjson` streams, but also handle url fetching.
* Gracefully terminate stream reader when `AbortController` cancel signal is received.
Pages that uses streaming:
- log pages (Master, Trial, Task)
- active experiment detail pages, particularly multi-trial experiments
Tests
See [Release …
=> refactor: rewrite ndjson streamer [DET-7121]

CONTRIBUTING.md, README.md
Update our docs where we `git clone` to include the new submodules with `git clone --recursive`
=> chore: Recommend git clone --recursive for submodules

e2e_tests/tests/cluster/test_users.py, harness/determined/cli/shell.py
To test, see description in DET-7131
=> fix: remove dead shell start code [DET-7131]

harness/determined/common/schemas/expconf/_gen.py, harness/determined/common/schemas/expconf/_v0.py, master/internal/core_experiment.go, master/internal/db/postgres_experiments.go, master/pkg/model/experiment.go, master/pkg/schemas/expconf/experiment_config.go, master/pkg/schemas/expconf/zgen_experiment_config_v0.go, master/pkg/schemas/zgen_schemas.go, master/static/srv/get_project_from_name.sql, master/static/srv/get_workspace_from_name.sql, schemas/expconf/v0/experiment.json, schemas/test_cases/v0/experiment.yaml
The YAML for an experiment loaded from the command line, forked from another experiment, etc. can include optional Workspace and Project parameters.  These should be the names of a current Workspace and nested Project.  If provided, the experiment should become associated with the Project.   If the named workspace/project is not found, or only one of the two parameters is provided, it should raise an error and prevent the experiment from being created or run.
=> fix: Add Workspace and Project name params to experiment yaml

docs/release-notes/4060-custom-reducers.txt, harness/determined/estimator/_estimator_context.py, harness/determined/pytorch/_experimental.py, harness/determined/util.py
When custom reducers were promoted from experimental to GA in 0.15.2, we
left forward references in the old experimental namespace.  This PR
cleans those up.
=> chore: remove deprecated experimental custom reducer methods

docs/release-notes/4066-reset-params.txt, harness/determined/pytorch/__init__.py, harness/determined/pytorch/_pytorch_trial.py
reset_parameters was deprecated in 0.12.13 (Aug 2020).
=> chore: remove det.pytorch.reset_parameters()

.gitmodules, webui/react/src/components/TaskActionDropdown.tsx, webui/react/src/hooks/useModal/useModalExperimentDelete.tsx
When deleting experiment from experiment list and the action fails from server side error, fix notification to pop. 
- Verify delete experiment function works as expected at experiment list page and experiment detail page. 
- Create server side error for `func (a *apiServer) DeleteExperiment` and verify delete experiment pops notification as expected. 
- As suggested by Trent, another way to create server side error during testing is to disconnect WIFI.
=> fix: show notification when delete experiment fail [DET-6811]

webui/react/src/pages/Cluster/ClusterHistoricalUsage.tsx, webui/react/src/pages/Cluster/utils.ts
"Compute Hours by User" chart is not displaying `displayName` for users, still uses `username` only.
=> fix: use displayNames in ClusterHistoricalUsage

webui/react/src/components/LogViewer/LogViewerFilters.test.tsx, webui/react/src/components/LogViewer/LogViewerFilters.tsx
Supports '0' as a Rank and not as a falsey value rendered as 'No Rank'.
Includes a test that 0 and undefined appear as options (as '0' and 'No Rank').
'0' appears somewhere else in the DOM, so we check that '0' appears twice.
=> fix: Support rendering rank of 0 [DET-7186]

docs/training-apis/api-core/distributed.txt, docs/training-apis/api-core/getting-started.txt, docs/training-apis/api-core/metrics.txt, examples/tutorials/core_api/0_start.py, examples/tutorials/core_api/1_metrics.py, examples/tutorials/core_api/2_checkpoints.py, examples/tutorials/core_api/3_hpsearch.py, examples/tutorials/core_api/4_distributed.py, harness/determined/__init__.py, harness/determined/common/_logging.py
Expose our log format to Core API users, who are responsible for
configuring logging on their own.  However, they need to user our format
for the log-level filtering to work in the WebUI.
Since we concluded that we _had_ to make users use a [per-rank wrapper script](https://github.com/determined-ai/determined/pull/4086), I didn't see a reason to have a `det.configure_logging(level=...)` call when there's a perfectly good `logging.basicConfig()` in the standard library that only needs a `format=det.LOG_FORMAT` parameter to work for us.
Telling users they need to use this format, however they decide to set up their logging, is much more flexible to the end user, which is in line with the philosophy of the core api.
=> feat: add det.LOG_FORMAT constant

harness/determined/launch/horovod.py
Change the pidserver settings for sshd launches to SIGTERM during
pidserver exit.  Previously the setting was to wait for the sshd
processes, but they never exit so it can cause a hang.  With
this change when when the horovodrun command completes, and the
pidserver is about to exit, it instead sends SIGTERM to the
sshd processes and all containers can exit cleanly.
Verified with successful run and test completion and shutdown using. SLURM  on casablanca & horizon with cifar10_pytorch distributed (8 slots).
=> chore: HAL-2879 Cleanly shutdown all sshd servers on exit (#176)

master/static/migrations/20220504154053_add-checkpoints-v2-steps-completed-index.tx.down.sql, master/static/migrations/20220504154053_add-checkpoints-v2-steps-completed-index.tx.up.sql, master/static/srv/proto_get_trials_plus.sql
Ran into some fairly serious perf issues without this index due to joins, wheres and sorts using this fields.
Before
```
QUERY PLAN                                                                                                                                                                                                                                                         
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> perf: improve plan for proto_get_trial_plus.sql

harness/determined/common/api/bindings.py, master/internal/api_experiment.go, master/internal/core_experiment.go, master/internal/db/database.go, master/internal/db/postgres_experiments.go, master/internal/mocks/db.go, master/static/migrations/20220505122814_workspace-name-restrictions.tx.down.sql, master/static/migrations/20220505122814_workspace-name-restrictions.tx.up.sql, master/static/srv/delete_project.sql, master/static/srv/delete_workspace.sql, master/static/srv/get_project.sql, master/static/srv/get_project_from_name.sql, master/static/srv/get_workspace.sql, master/static/srv/get_workspace_projects.sql, master/static/srv/get_workspaces.sql, master/static/srv/insert_project.sql, master/static/srv/insert_workspace.sql, master/static/srv/update_project.sql, master/static/srv/update_workspace.sql, proto/src/determined/api/v1/experiment.proto, proto/src/determined/project/v1/project.proto, proto/src/determined/workspace/v1/workspace.proto, webui/react/src/hooks/useModal/useModalExperimentCreate.tsx, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/types.ts
- Workspaces and projects have a name between 1 and 80 chars.
- Forking an experiment in the WebUI keeps it in the same project.
- Allow user to delete workspaces with a project, projects with an experiment, or combined (deleting workspaces with a project with an experiment).  The experiments are not deleted and go to the Uncategorized project (project_id = 1).
=> fix: Assorted fixes for Workspaces/Projects

.circleci/config.yml
Needed, particularly in EE, to publish these artifacts to the correct places.
=> ci: persist debs, rpms

master/internal/api_experiment.go, master/static/srv/move_experiment.sql, webui/react/src/components/PageHeaderFoldable.tsx, webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx, webui/react/src/services/decoder.ts, webui/react/src/types.ts, webui/react/src/utils/task.ts
One-line fix to prevent an archived experiment from being selected and moved between projects from CLI/API
=> fix: Prevent archived experiments from being moved or forked

bindings/generate_bindings.py, harness/determined/cli/experiment.py, harness/determined/common/api/bindings.py
The generated python bindings would emit boolean url parameters as
`val=True` but apparently grpc wants `val=true` instead.
`det e list` now uses real booleans instead of string booleans, so test with and without `-a`.
It bugs me that we use generated bindings for "type safety" but that we also have this `limit_offset_paginator` which destroys type safety.  I spent quite a while learning about python's 3.10 [typing.ParamSpec feature](https://sobolevn.me/2021/12/paramspec-guide) but even with that I couldn't get things to work.  And I like what the function does so for now I have no response to it.
It might be worth making the generated bindings do the repeated paging at some point, which would be a lot more ergonomic for these paginated endpoints.
=> chore: fix boolean urlparams for grpc

webui/react/src/pages/ModelDetails.tsx
For complicated reasons, we have linked to models by name (`/det/models/:name`) in the past. When the model name changed, we used #3559 to redirect to the new model URL.
We now prefer a permanent link with the numeric id  (`/det/models/:id`) so this redirect can be removed.
I don't think there's anywhere else in Web UI where the model name can be changed.
- Create a model
- Visit that model's detail page
- Change the name of the model (we should not be redirected)
- Refresh the page to confirm that the name was successfully changed
=> fix: No redirecting url when model name is changed

e2e_tests/tests/conftest.py
Upstream tests relied on getting master configuration without being logged in as admin. This makes sure when the tests call config they are logged in as admin.
=> fix: upstream test failures due to config being admin protected

bindings/generate_bindings.py, harness/determined/cli/experiment.py, harness/determined/common/api/bindings.py, harness/determined/common/experimental/session.py
- Cherry-picks a commit on master branch to support True/False in GET params (previously "True" and "False" were rejected and we needed to send a string such as "false")
- Removes my related patch on workspaces
This branch merges into the workspaces feature branch.  We should probably wait to merge after other PRs are merged, because it will rewrite a lot of the Python bindings.py
Existing e2e_tests already include boolean values
=> chore: Use new boolean patch in workspaces bindings

e2e_tests/tests/experiment/test_noop.py, e2e_tests/tests/fixtures/no_op/model_def.py, e2e_tests/tests/fixtures/no_op/single-nan-validations.yaml, harness/determined/core/_searcher.py, harness/determined/core/_train.py, harness/determined/layers/_workload_sequencer.py
In several places, the harness had checks to filter out NaN validation
metric values, which previously could not be handled. This change
removes the checks, and testing has seemed to indicate that NaN values
are serialized and otherwise handled just fine without causing any
errors.
As a historical note, I found while tracing the history of this code
that NaN values were originally considered an error, then changed to not
being an error, then changed back again. The comment I changed was
actually incorrect until just now, as it applied to an older version of
the code.
I noticed while
=> feat: allow NaN validation metrics [DET-7177]

webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss
fix: prevent experiment name in header from overflowing entire vertical [DET-7342]
https://user-images.githubusercontent.com/28383080/168981826-c66c486c-82a0-4db0-87f2-220921ce982b.mov
https://user-images.githubusercontent.com/28383080/168981886-4d8bfb3d-fec9-425d-8e4b-04759263a3ac.mov
[DET-7342]: https://determinedai.atlassian.net/browse/DET-7342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: prevent experiment name in header from overflowing entire vertical

harness/determined/constants.py
… port
Allow the user to change the ports used by Determined do deal with the situation where those ports may already be in use by another process on the compute node.
Tested using the "cifar10_pytorch" experiment with the "distributed.yaml" file and these environment variables.  The experiment completed successfully.
```
environment:
- DTRAIN_SSH_PORT=13000
- HOROVOD_GLOO_RENDEZVOUS_PORT=13010
- INTER_TRAIN_PROCESS_COMM_PORT_1=13020
```
Bradley said that users will typically be instructed to set these environment variables in "startup-hook.sh", rather than in the experiment's YAML file.  I set them in the experiment's YAML file for testing.
```
you dont even need to make configurations for all of this, for now
it can be 'secret'
we source startup-hook.sh where the …
```
=> chore: multiple distributed jobs collide on horovod run sshd port [HAL-2894]

master/internal/task/allocation.go
AllocationReady comes from the container for shells, notebooks,
and tensorboards, but the clients also depend upon the state
being running immediately after AllocationReady, so to avoid
a race condition where the dispatcher RM discovers the running
state by polling for dispatcher RM, force the state to running upon reception
of the AllocationReady event.
Manually verified that `det shell start` now works with slurm dispatcher RM.
=> fix: avoid potential race between AllocationReady and Running state

proto/Makefile, tools/scripts/lock-api-state.sh
=> chore: check git state in lock-api-state.sh

master/internal/task/allocation.go
Change plucked from EE's slurm branch.
=> chore: just warn on non-sense daemon calls when using slurm

master/static/srv/task-logging-setup.sh, master/static/srv/task-logging-teardown.sh
A task may output carriage return characters (\r) do something mildly
fancy with the terminal like update a progress bar in place on one
line. Python's tqdm library is a common way to do this. That works
poorly with our logging, since Fluent Bit interprets everything as one
line, causing it to mash everything together and buffer the output for
way too long. Since we're not going to do anything like interpreting the
carriage returns in our log displays, here we simply replace them all
with newlines to get a reasonable effect in those cases.
An alternative might be trying to manipulate tqdm itself, as the
original ticket proposes. But that comes with the issue that dealing
with `det cmd run ...` case would require us to ship a patched copy of
tqdm, since we don't have direct control over …
=> fix: replace carriage returns with newlines in task output [DET-5302]

master/static/srv/proto_get_trials_plus.sql
Due to recent reshuffling of the checkpoints tables, part of this query
ended up including only the old checkpoints table and ignoring the new
one, where instead it should consider both the old and new views, like
the rest of the query.
I'm kind of cargo-culting the exact form of the query; improvement suggestions welcome.
=> fix: include both old and new checkpoints in total checkpoint size

agent/internal/agent.go, docs/release-notes/fix-cant-cancel-agent-master-con.txt
Previously the agent was unable to be canceled while connecting to master. This makes it so it can be.
Run
```
./determined-agent --master-host 34.215.4.95 --master-port 8080
```
and verify control-C closes the agent
This fix won't cause the ```ctx.Self().Stop()``` to be called or the agent message to be printed. Not sure how important that is because the agent connection to master happens before the agent is initialized completely.  
=> fix: agent can now be control-C while connecting to master [DET-6287]

docs/release-notes/checkpoint-prefix.txt, helm/charts/determined/templates/master-config.yaml, helm/charts/determined/values.yaml
Previously, checkpointStorage could not be set through helm. This change allows it.
Create a publicly accessible s3 bucket 
Login
```
gcloud auth login
```
Switch project
```
gcloud config set project determined-ai
```
Create cluster (this takes awhile)
```
gcloud container clusters create nblaskey-test \
--region us-west1 \
--node-locations us-west1-b\
--num-nodes=1 \
--image-type=UBUNTU \
--cluster- --cluster-version=1.22.8-gke.200 \
--machine-type=n1-standard-8
```
Creates a node pool for GPUs
```
gcloud container node-pools create node-pool-name \
--cluster nblaskey-test \
--accelerator type=nvidia-tesla-k80,count=1 \
--zone us-west1 \
--num-nodes=1 \
--image-type=UBUNTU \
--machine-type=n1-standard-8 \
--scopes=storage-full
```
Apply DaemonSet to enable nodes to detect GPUs
``` …
```
=> feat: allow setting of checkpointStorage.prefix through helm [DET-7152]

harness/determined/cli/project.py, harness/determined/cli/workspace.py, master/static/srv/delete_project.sql, master/static/srv/delete_workspace.sql, webui/react/src/hooks/useModal/Project/useModalProjectDelete.tsx, webui/react/src/hooks/useModal/Workspace/useModalWorkspaceDelete.tsx
After our discussion about when experiments can/can't be safely deleted and how that process is async / not easy to do en masse, when a project is deleted we're going to move its experiments back to the Uncategorized workspace.
This updates the language in the CLI and WebUI to inform users. Notes on a project get deleted, so I added that in.
=> feat: Deleting workspace/project moves its experiments [DET-7368]

docs/integrations/prometheus.txt, docs/release-notes/helm-enable-prom.txt, docs/sysadmin-basics/cluster-config.txt, docs/sysadmin-deploy-on-k8s/helm-config.txt, helm/charts/determined/templates/master-config.yaml, helm/charts/determined/values.yaml
Previously helm was unable to enable Prometheus monitoring. This change enables Prometheus to be set through helm.
Run
```
helm install determined helm/charts/determined/ \
--values helm/charts/determined/values.yaml \
--set maxSlotsPerPod=1 \
--set detVersion=0.18.0 \
--set observability.enable_prometheus=true
```
Port forward
```
kubectl port-forward service/determined-master-service-determined 8080:8080 --address=0.0.0.0
```
Test endpoints (should return 200 status code)
```
curl 127.0.0.1:8080/prom/det-state-metrics
curl 127.0.0.1:8080/prom/det-http-sd-config
```
Clone https://github.com/determined-ai/works-with-determined#observability-tools and change the following lines to your computers IP somehow
https://github.com/determined-ai/works-with-determined/blob/master/observability/prom …
=> feat: allow enabling Prometheus monitoring through helm [DET-6993]

docs/sysadmin-deploy-on-k8s/install-on-kubernetes.txt, docs/sysadmin-deploy-on-k8s/setup-eks-cluster.txt
Using AWS Load Balancer on EKS causes a failed health check due to it expecting ```/``` while we provide ```/det/```. This documents how to provide the fix.
To reproduce the issue first create an EKS cluster.
Then install the AWS Load Balancer with these docs https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html
Then start determined through helm
```
helm install determined helm/charts/determined/ \
--values helm/charts/determined/values.yaml \
--set maxSlotsPerPod=1 \
--set detVersion=0.18.0 \
--set useNodePortForMaster=true
```
Then start an ingress for master (intentionally without the health check path)
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
annotations:
alb.ingress.kubernetes.io/inbound-cidrs: 0.0.0.0/0 …
```
=> docs: document using AWS Load Balancer on EKS [DET-6669]

harness/determined/common/schemas/expconf/_gen.py, master/pkg/schemas/zgen_schemas.go, schemas/expconf/v0/experiment.json, schemas/test_cases/v0/experiment.yaml
The internal field was removed with 0.18.0, along with the Native API.
But before 0.15.6, the `internal` field did not have an `omitempty` tag,
so it was still being stored in the database as `null`.  This causes
forking and certain REST API endpoints to fail on older experiments.
Find a pre-0.15.6 experiment on a test cluster and see if the webui is broken for it or not.
=> fix: allow `internal: null` for pre-0.15.6 experiments

master/static/srv/proto_get_trials_plus.sql
Checkpoint size calculation was using `int` causing it to fail for checkpoints over 2 gigabytes. Transformers test `huggingface_squad_v2_with_beam_search` had 4 gig checkpoints.
[Example](https://gcloud2.determined.ai/det/experiments/1726/overview)
Run `model_hub/examples/huggingface/question-answering/squad_v2_beam_search.yaml` with 200 batches and `--config resources.slots_per_trial=8 --config hyperparameters.global_batch_size=16`.
=> fix: use bigint for checkpoint size in `proto_get_trials_plus`

e2e_tests/tests/command/command.py, e2e_tests/tests/command/test_tensorboard.py, master/internal/api_tensorboard.go, master/pkg/model/environment_config.go
When start a tensor board, disable override environment image when custom image is presented.
=> fix: use custom image for tensor board [DET-7242]

harness/determined/cli/cli.py, harness/determined/cli/shell.py
tempfile.NamedTemporaryFile does not do what you think it does, at least
not in Windows.  Use mkstemp directly instead.
Also, fix the color-related ANSI escape codes so there's not a bunch of
raw escape codes when using det in cmd.exe.
Run `det shell start` in windows, see if it works and if the colors look right.
=> fix: det shell start/open, in windows

harness/determined/cli/project.py, harness/determined/cli/workspace.py, harness/determined/common/api/bindings.py, master/static/migrations/20220422101847_pin-workspaces.up.sql, master/static/srv/delete_project.sql, master/static/srv/delete_workspace.sql, master/static/srv/get_workspace.sql, master/static/srv/get_workspaces.sql, master/static/srv/update_workspace.sql, proto/src/determined/workspace/v1/workspace.proto, webui/react/src/hooks/useModal/Project/useModalProjectDelete.tsx, webui/react/src/hooks/useModal/Workspace/useModalWorkspaceDelete.tsx, webui/react/src/pages/WorkspaceDetails/ProjectActionDropdown.tsx, webui/react/src/pages/WorkspaceList/WorkspaceActionDropdown.tsx, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/decoder.ts, webui/react/src/types.ts
Hoping to discuss this later today - this PR adds to workspaces branch a new plan for deleting workspaces and projects.
- Remove previous deletion / movement commit
- Block deletion (server-side, in SQL) of workspaces and projects with associated experiments
- Add a numExperiments item to Workspace API endpoints (similar to Project.numExperiments)
- Only show "Delete" in WebUI when Workspace/Project have no Experiments
- The CLI deletes Workspaces/Projects by looping through associated experiments and attempting to delete for 2 minutes per project.
CLI testing:
det w create apple
det p create apple orange
(empty workspace and project show deletion option in WebUI)
det e list
(pick an experiment id in COMPLETED state for success, trapped in DELETING stage to see errors)
det e move 220 …
=> feat: Change workspace deletion - workspace must be empty to delete

harness/tests/test_ipc.py
Default macbook ulimits cause the 4x4 test to fail.
=> ci: check ulimit before 4x4 distributed test on macs

docs/sysadmin-basics/cluster-config.txt, docs/sysadmin-basics/network-requirements.txt, docs/sysadmin-deploy-on-k8s/helm-config.txt, helm/charts/determined/templates/master-config.yaml, helm/charts/determined/values.yaml, master/packaging/master.yaml, master/pkg/model/task_container_defaults.go, master/pkg/tasks/task.go
The port ranges used by NCCL and Gloo were previously configurable, but support
for this feature was removed quite a while ago. This commit removes the vestiges
of the previous feature, including docs and config parsing code. (We continue to
allow `nccl_port_range` and `gloo_port_range` to be specified in `master.yaml`
but those values are now ignored.)
=> chore: remove legacy code/docs for NCCL/Gloo port range config

webui/react/Makefile, webui/react/package-lock.json
Something keeps setting up hamidzr/omnibar as an ssh url instead of an
https url.  Fix it, add a lint checker, and a fmt fixer.
=> ci: add check to prevent ssh git url

webui/react/Makefile, webui/react/craco.config.js
causes the webpack dev server "`make live`" to proxy requests from `localhost:3000/api` to `localhost:8080/proxy` and from `localhost:3000/proxy` to `localhost:8080/proxy`. this allows the jupyter view to be embedded since it is considered to have the same source, getting around:
```Refused to frame 'http://localhost:8080/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".```
we no longer need `SERVER_ADDRESS=http://localhost:8080` in the Makefile, because we are proxying there by default.
in order for it to work you need to `dev.resetServerAddress`. proxy is not compatible, so it only works against local `devcluster`.
dogfood
If you want to do against external cluster, change `localhost:8080` to desired `cluster:port` AND do …
=> chore: add dev server support for embedded tasks view

.circleci/config.yml, docs/release-notes/det-deploy-no-prompt-yes.txt, harness/determined/deploy/aws/cli.py, harness/determined/deploy/gcp/cli.py, harness/determined/deploy/gcp/gcp.py
```det deploy``` commands now can take ```--yes``` to skip prompts. 
Deploy a aws cluster using det deploy. Redeploy with changes with ```--no-prompt``` then again with ``--yes`` to ensure prompts are skipped. 
Then run
```
det deploy aws down --cluster-id nblaskey-test --yes
det deploy aws down --cluster-id nblaskey-test --no-prompt
det deploy aws down --cluster-id nblaskey-test # Should ask for prompt
```
Deploy a gcs cluster.
Run
```
det deploy gcp down --yes
det deploy gcp down --no-prompt
det deploy gcp down # Should ask for prompt
```
=> feat: det deploy now can use --yes to skip prompts [DET-7408]

docs/release-notes/fix-task-logs.txt, harness/determined/cli/command.py, harness/tests/cli/test_cli.py
```det task logs``` now works for trial task IDs and checkpoint GC task IDs.
CLI unit test and running ```det task logs <CHECKPOINT_GC_TASK_ID>```
=> fix: det task logs unable to use trial task IDs and checkpoint GC task IDs [DET-7424]

docs/release-notes/4257-which.txt, master/static/srv/entrypoint.sh, master/static/srv/gc-checkpoints-entrypoint.sh, master/static/srv/notebook-entrypoint.sh, master/static/srv/shell-entrypoint.sh, master/static/srv/tensorboard-entrypoint.sh
This was my bug, introduced in #1967.
I have no idea why I wrote it that way.
Run a notebook in an image that doesn't have /bin/which, like:
```python
det notebook start --config=environment.image=python:3.9.11-slim
```
Check the logs, ensuring the following log does NOT appear:
```
error: unable to find python3 as "python3"
```
=> fix: don't hardcode /bin/which in entrypoints

agent/internal/options.go, docs/sysadmin-basics/cluster-config.txt, master/internal/config/resource_manager_config.go, master/internal/core.go, master/internal/resourcemanagers/agent/agents.go
<will add something here later, but don't feel like it at the moment>
=> feat: add master-side verification for agent mTLS

harness/determined/cli/shell.py
Avoid showing backslashes in show_ssh_command, because when passed to
VSCode, they break the resulting .ssh/config.
On windows and *nix:
After discussion with @ioga, the best "solution" to the vscode/virtualenv problem is to say that "show_ssh_command must be run from the same virtualenv as vscode, which is usually no virtualenv at all".
=> fix: backslashes in show_ssh_command for windows

master/static/migrations/20220528215116_reindex-raw-steps.tx.down.sql, master/static/migrations/20220528215116_reindex-raw-steps.tx.up.sql
There have been many issues in latest-master recently for queries that involve `raw_steps` taking 30+ seconds due to Seq Scans. Might or might not have to do with a certain someone launching a bunch experiments to generate a tons of data to test their graphs. In any case it is a good thing to address. [DET-7473]
Among the offenders:
- [proto_get_trials_plus](https://determinedai.atlassian.net/browse/DET-7352): this one was resolved by [4206](https://github.com/determined-ai/determined/pull/4206), but included here for context
- [metric_names](https://determined-ai.slack.com/archives/CT01QS70Q/p1652736744444729)
- [get_model_versions](https://determined-ai.slack.com/archives/CKQ3EV0G6/p1653595557956529)
common theme is query planner not using index on `raw_steps`
`raw_steps` has index …
=> perf: avoid Seq Scanning raw steps

docs/release-notes/4286-passthru.txt, harness/determined/exec/launch.py, harness/determined/exec/tensorboard.py, harness/determined/ipc.py, harness/determined/launch/deepspeed.py, harness/determined/launch/horovod.py, harness/determined/launch/torch_distributed.py, harness/determined/launch/wrap_rank.py, harness/determined/util.py
I thought we were cleaning things up nicely, but when logging started
keeping containers open until all copies of the stdout file descriptor
closed, it became obvious that the pid_client was being killed by
horovodrun without shutting down its child wrap_rank script, causing the
logging to stay active and the container to hang.
This first fix is to pass signals through wrapper processes, so that
normal graceful shutdowns complete as-expected.
With a 0.18.1 master:
- start a trial with a context.distributed.allgather in one rank, with an exit(1) in another rank
- observe horovod try to shut down training
- observe training does not stop
- observe pid_server gets impatient and SIGKILLs horovodrun
- observe the container is hung
- docker exec into the container, and see that the pid_client …
=> fix: pass signals through wrapper processes

docs/release-notes/4288-version.txt, e2e_tests/tests/experiment/test_core.py, harness/determined/estimator/_estimator_trial.py, harness/determined/keras/_tf_keras_trial.py, harness/determined/pytorch/_pytorch_trial.py
This was accidentally dropped from the automatically-stored metadata as
part of the generic checkpoint feature branch (4fb1886b).
This was probably my mistake.
=> chore: restore determined_version in Trial checkpoint metadata

webui/react/src/hooks/useModal/useJupyterLabModal.test.tsx, webui/react/src/hooks/useModal/useJupyterLabModal.tsx, webui/react/src/omnibar/tree-extension/trees/index.ts, webui/react/src/types.ts, webui/react/src/utils/jupyter.ts
[DET-7478] [DET-7389]
fixes some staleness with jupyterlab modal in both the ui and values that get sent to API 
also does some refactoring/cleanup of the adjacent code (mainly the older parts of the code, from before the recent refactor)
jupyterlab modal has stale values for compute pool (clicking in dropdown doesnt update value):
https://user-images.githubusercontent.com/28383080/172557596-60342111-e605-4063-ad30-f9ee647d37e7.mov
and slots (pressing enter or clicking away causes the current input value to be clobbered by previous):
https://user-images.githubusercontent.com/28383080/172557934-b56badca-dbfa-47b8-b2c4-efa1d496e4b8.mov
and sends empty/stale values to api:
https://user-images.githubusercontent.com/28383080/172558702-7bd90a52-d4b2-4974-bdad-54a54090b8a1.mov
there is a warning …
=> fix: jupyterlab modal stale values, not sending values to api

e2e_tests/tests/command/test_run.py, master/static/srv/task-logging-setup.sh, master/static/srv/task-logging-teardown.sh
If the main process exits and the logger is still going after 30
seconds, assumes something is wrong and give up.
The 30 second window is configurabe by setting DET_LOG_WAIT_TIME in the
environment, in case of emergency.
An automated test is included to make sure that we log things after the
main process exits, but not after the DET_LOG_WAIT_TIME is exceeded.
=> fix: limit waiting for logger to 30 seconds

master/internal/resourcemanagers/priority.go
Band aid fix for resource pool crashing when our local agent state doesn't include an agent that an allocation references.
Run priority scheduler with preemption enabled 
add this below line 358 in ```master/internal/resourcemanagers/priority.go```
```
delete(agents, allocation.agent.Handler)
```
then have the scheduler preempt a task and you should see a log along with the resource manager not crashing
```
det e create --config="resources.priority=80" examples/tutorials/mnist_pytorch/const.yaml examples/tutorials/mnist_pytorch/ && sleep 5 && det e create --config="resources.priority=1" examples/tutorials/mnist_pytorch/const.yaml examples/tutorials/mnist_pytorch/
```
=> fix: stale agent state crashes resource pool [DET-7493]

docs/sysadmin-basics/cluster-config.txt
Accidentally put the new stuff into a different TLS-related section before.
=> docs: move description of agent client cert fields to the right place

e2e_tests/tests/cluster/test_resource_manager.py
Disable assert that races with a no op trial completing.
=> ci: remove overzealous assert that can finish after noop trial

docs/concepts/index.txt, docs/index.txt
To aid automated rebranding, strengthen the pattern of using
"Determined" to refer to the product and "Determined AI" to refer to the
related business entity.
=> docs: more consistently use Determined AI vs. Determined

master/internal/resourcemanagers/resource_pool.go, master/pkg/tasks/ports.go, master/pkg/tasks/task_trial.go
The DET_UNIQUE_PORT_OFFSET was always coming out to zero, which
prevented host-mode networking in multi-tenant dtrain scenarios.
The source of the bug was that the unique port offset was being
calculated before the TaskSpec.Devices was populated.
- Configure `task_container_defaults.network_mode: host` in master
- Start an `artificial_slots:4` agent
- Start two simultaneous `slots_per_trial: 2` trials
- Make sure both trials succeed.
This bug was difficult to track down because the TaskSpec means multiple different things at different points in time (something I did not previously realize).  Initially, a trial actor is started with a "base" TaskSpec.  I think this has some defaults from the master.  Then the TrialSpec (which has a base TaskSpec as its member) creates a new TaskSpec in …
=> fix: provide unique port offsets to trials

.github/CODEOWNERS, CODEOWNERS
Merge top-level codeowners into .github location
Make more PRs!
In general, I'm partial to having GitHub-control stuff located in the .github directory, so my opinion is that this is the "right" place for this file. I'm open to dissent, though.
The individual users in here should be converted to GH Teams later, but that's a problem for the future.
=> ci: merge separate codeowners

.circleci/config.yml
I mistakenly configured it so it only ran on upstream feature branches
originally.
=> ci: make test-unit-storage run on any upstream branch

.github/dependabot.yml
Enable Dependabot version updates for the various sub-projects within the repo.
Watch dozens of PRs start opening up.
(Effect was pre-tested on my personal fork - https://github.com/dannysauer/determined.ai_determined/pulls)
This is going to open a lot of PRs, many of which are version bumps that do not have immediate security implications.  By default, it will open no more than five at a time for each package manager type and sub-project (there's an additional limit of ten at a time for security-specific dependencies).  They will all have the dependabot label, making them relatively easy to sort, and will include the path to the sub-project to which they apply.  The web environment PRs will get an additional label assigned to distinguish those which are version bumps in the web dev …
=> ci: add dependabot for all the things

docs/release-notes/agent-config-path.txt, e2e_tests/tests/deploy/etc/agent.yaml, e2e_tests/tests/deploy/test_local.py, harness/determined/deploy/local/cli.py, harness/determined/deploy/local/cluster_utils.py
Adds a new CLI option ```--agent-config-path``` to allow users to specify a custom agent yaml.
e2e tests along with manual regression testing of 
```
det deploy local agent-up
```
CLI flags
```
--master-port
--agent-name
--agent-label
--agent-resource-pool
```
=> feat: add --agent-config-path to det deploy local agent-up [DET-6278]

webui/react/src/components/TagList.module.scss, webui/react/src/components/TagList.tsx, webui/react/src/pages/ProjectDetails.tsx
Per customer request, we increate the tag max length to 50, and remove tags overflow in experiment list table.
Before
After
At experiment list table, create tags with various length, verify the content can be displayed up to 50 characters. 
Create multiple tags (>5), verify all can be displayed. 
=> fix: update experiment list tag truncate rule [DET-7530]

e2e_tests/tests/deploy/test_local.py
Test flake occurring whenever test_agent_config_path runs and needs to pull the fluent docker image. We did not wait properly for the agent to create the fluent container.
=> fix: test agent config flake

master/internal/resourcemanagers/job.go
jobStatsByPool is only used in determined-ee and thus has a nolint:deadcode directive, however, since it is used in
determined-ee it additionally needs ,nolintlint to avoid a linter error that it is not needed.
=> chore: Add nolintlint to deadcode for unused oss method

master/internal/db/database.go, master/internal/db/postgres_agent.go, master/internal/mocks/db.go, master/internal/resourcemanagers/resource_pool.go, master/internal/resourcemanagers/resource_pool_test.go
Suppress unnecessary log to debug level. 
Simulate a situation where agent is up but stats is not recorded, then kill the agent, there should be a debug level log `End agent stats call affects 0 row(s), this number is suppose to be 1.` instead of any error.
=> fix: End agent stats log to debug level

harness/determined/exec/tensorboard.py
Tensorboards weren't opening reliably because the 'isReady' bit wasn't being set. upon some investigation, the proxy is up because the container is running, and the fetcher has indeed moved the tfevents files over from shared_fs to /tmp/whatever, which should imply it has printed this line. I noticed running on `debug: True` made this never happen and assume it was some weird stream buffering thing. This patch entire removes the issue.
If a python world person has a better way, pls save me.
=> fix: always flush tensorboard ready log

docs/release-notes/4412-registry-auth.txt, master/internal/config/config.go, master/internal/config/config_test.go
Since 0.17.15, there was a bug where registry auth configured in
master.yaml was not correctly passed to tasks.
This change fixes it and adds it to the config unit test.
=> fix: registry auth in master.yaml [DET-7629]

webui/react/src/components/LogViewer/LogViewerFilters.tsx, webui/react/src/components/MultiSelect.tsx, webui/react/src/setupTests.ts
Address the following:
- silence async-validator warnings show around `antd` forms (not test failures but adds a lot of noise)
- fix missing `key` error in `LogViewerFilter` tests
Sample `async-validator` warning:
```
PASS  src/hooks/useModal/UserSettings/useModalChangeName.test.tsx (42.857 s)
● Console
console.warn
async-validator: [ "'displayName' cannot be longer than 80 characters" ]
at Function.warning (node_modules/src/util.js:18:17)
at callback (node_modules/src/index.js:162:20)
at Object.validator (node_modules/src/validator/string.js:32:3)
at func (node_modules/src/index.js:237:22)
at forEach (node_modules/src/util.js:113:5)
at Array.forEach (<anonymous>)
at asyncParallelArray (node_modules/src/util.js:112:7)
at node_modules/src/util.js:199:9
```
Sample `LogViewerFilter` missing …
=> test: tune web tests

harness/determined/launch/deepspeed.py, harness/tests/launch/test_deepspeed.py
There have been changes to the deepspeed launcher in newer versions that break compatibility with our launcher.  This PR addresses those compatibility issues introduced in 
- https://github.com/microsoft/DeepSpeed/pull/1832
- https://github.com/microsoft/DeepSpeed/pull/1907
Using deepspeed versions > 0.6.4 will depend on this upstream PR https://github.com/microsoft/DeepSpeed/pull/1957
Tested single and multinode for 0.5.10 and 0.6.5.dev with the PR above
=> chore: update deepspeed launcher to work with newer versions

harness/determined/cli/command.py, harness/determined/common/util.py, harness/determined/ipc.py, harness/determined/load.py, harness/determined/pytorch/_pytorch_trial.py, harness/determined/pytorch/_reducer.py, harness/determined/util.py, harness/tests/common/test_schemas.py, harness/tests/experiment/keras/test_tf_keras_trial.py, harness/tests/experiment/pytorch/test_metric_utils.py, harness/tests/experiment/utils.py
Fix some warnings from `yaml` and `numpy`.
Fix a few fstrings missing the prefix `f`.
Fix some typing mismatches, solving several `mypy` errors.
Fix a little bit of code formatting and typos.
To see the reduction in `numpy` warnings, in the directory `determined/harness`, running the command
`pytest tests/experiment/pytorch/test_reducer.py tests/experiment/tensorflow/test_estimator_trial.py`
would result in 4140 warnings. After the proposed changes, this reduces to 29 warnings. There are certainly repeated warnings.
The output of `mypy` as used in, say, `make -C harness check` is now as follows:
```
determined/pytorch/_reducer.py:36: error: Returning Any from function declared to return "floating[_64Bit]"
determined/pytorch/_reducer.py:38: error: Returning Any from function declared to …
```
=> chore: resolve warnings from yaml and numpy, fix supposed fstrings, black formatting

webui/react/src/components/TagList.module.scss
Fix long tag display in experiment table
Before: 
After: 
=> fix: long tag display

harness/determined/pytorch/_callback.py
It is called on every rank, but the docs said it wasn't.
It should be called on every rank, so fix the docs.
=> docs: PyTorchTrialCallback.on_validation_end

webui/react/src/components/LogViewer/LogViewer.tsx, webui/react/src/components/ResponsiveTable.tsx, webui/react/src/pages/TrialDetails/TrialChart.module.scss, webui/react/src/pages/TrialDetails/TrialChart.tsx, webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.tsx, webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx, webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx, webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx
Original ticket: [DET-7180]
Some of the tabs from the `ExperimentSingleTrialTabs` component were showing a "No data" message and icon while the component fetches the experiment/trial details in the background.
So, to better visualize the initial data fetching, I've bound the `trial` prop (which is `undefined` while it fetches) to a spinner conditional rendering on the affected component tabs (Overview, Hyperparameters and Logs).
To test this implementation, go to any experiment overview page `/experiments/<experiment_id>/overview`, upon reaching the page, the spinner should appear to highlight data fetching, instead of the "No Data" background.
The same behavior is expected for each experiment tab on this page.
For more context, check the gifs linked below.
Here's some gifs to better …
=> feat: add spinner to show data fetching

webui/react/src/pages/ProjectDetails.tsx, webui/react/src/pages/TrialDetails/TrialChart.module.scss, webui/react/src/pages/WorkspaceList.tsx
setting `isLoading=true` for every poll results in the following flashing behavior
https://user-images.githubusercontent.com/28383080/176763109-6381cc34-5fe1-4038-bd32-bc08eb629ed3.mov
use network throttling:
- both table and grid don't flash as long as you don't do anything
- when you update dropdowns/filters the loading state should be reflected
left some comments in the code.
=> fix: loadingState cleanup for WorkspaceList

master/internal/resourcemanagers/agent/agent.go, master/internal/resourcemanagers/agent/agents.go
Wait until agents actor initializes agent actors and they add themselves to a resource pool to avoid a race condition in restoring tasks on master restart. 
This is a race condition which happens 100% of the time when manually cycling `det deploy aws` clusters, but not in CircleCI or local tests.
1. Make a `det deploy aws` cluster
2. ssh into the cluster and set `agent_reattach_enabled: true` for both resource pools in the master config in `/usr/local/determined/etc/master.yaml`.
3. Start a jupyter notebook
4. `sudo docker restart determined-master`
5. The notebook should still be running and accessible (jupyterlab will show a disconnection message).
=> fix: sync agent actor init on master restart [DET-7746]

docs/release-notes/non-root-init-k8s.txt, master/internal/resourcemanagers/kubernetes/spec.go, master/internal/resourcemanagers/kubernetes/volumes.go, master/pkg/archive/archive.go, master/pkg/model/agent_user_group.go, master/pkg/tasks/task.go, master/static/srv/k8_init_container_entrypoint.sh
Support non root init container k8s.
Run a dtrain job as admin and non admin on k8s and verify it works correctly and that the root container is running as non root. 
To run as a nonroot user you can link determined agent to linux user / group on the nodes of the k8 cluster.
SSH into all the nodes of the cluster with
```
gcloud compute ssh <node name from kubectl get nodes>
```
then run the following commands to create a user
```
sudo useradd normal
id -u  normal  # user id
id -g  normal  # group id
sudo mkdir /checkpoints && sudo chown normal: /checkpoints  
sudo chmod u+w /checkpoints
```
Then link the determined user with this linux user / group and all following experiments should run as that user
```
det -u admin user link-with-agent-user determined --agent-uid 1038 --agent-user …
```
=> feat: support non-root init container k8s [DET-7109]

harness/determined/_trial_controller.py, harness/determined/tensorboard/util.py
**Note: this is a release blocker**
**Note 2: the issue being fixed is introduced in this release**.
https://determinedai.atlassian.net/browse/DET-7770
The symptom is a deepspeed trial getting a 429 rate limit exceeded response from GCS.
An incorrect expression was given as a selector for files to be uploaded. The intent was to upload all files from chief and all but `tfevents` files from the (other) workers. But `lambda _: True if self.is_chief else lambda p: not p.match("*tfevents*")` is actually a single lambda that would map any path to `True` on chief and to another lambda on a non-chief, and lambda is apparently is a truthy value. The correct expression would put parentheses around lambdas.
I don't find it practical to write a brand new test for TrialController just to test the …
=> fix: correct path selector for tensorboard upload

master/internal/task/allocation.go, master/internal/trial.go
Sometimes a trial will report errored even though it has exited with code 0. This is because even if it has exited successfully, the daemon process might still need to be killed. This change make sure that we don't report an error after slaying the daemon. 
Run some tensorflow or deepspeed hp search jobs with a `slots_per_trial` value greater than the slots in one node. Make sure that no trials error with exit code 0.
=> fix: allocation errors on finished hp search [DET-7724]

master/pkg/actor/response.go, master/pkg/actor/response_test.go
- `GetOrElseTimeout` was de-facto only returning once it's got the
response, regardless of the timeout value. The unit test for it was
testing it wrong.
=> fix: make actor system `GetOrElseTimeout` actually timeout.

examples/deepspeed/cifar10_moe/moe.yaml, examples/deepspeed/cifar10_moe/zero_stages.yaml, examples/deepspeed/deepspeed_dcgan/cifar10_zero2.yaml, examples/deepspeed/deepspeed_dcgan/mnist.yaml, examples/deepspeed/deepspeed_dcgan/mnist_grad_accum.yaml, examples/deepspeed/pipeline_parallelism/distributed.yaml
Deepspeed examples in `cifar10_moe`, `deepspeed_dcgan` and `pipeline_parallelism` are failing on GCP/AWS. Solution was to add the following NCCL config (as in `gpt_neox`):
```
environment_variables:                                                                          
- NCCL_DEBUG=INFO                                                                           
- NCCL_SOCKET_IFNAME=ens,eth,ib
```
Tested on old .yaml files - Errors
Tested on new .yaml files - Experiments are starting and running.
=> fix: deepspeed examples config

agent/go.mod, agent/go.sum, agent/internal/docker.go, agent/internal/docker_credential_store.go, agent/internal/docker_test.go, docs/release-notes/dont-send-docker-creds-to-any-server.txt, docs/sysadmin-basics/cluster-config.txt, docs/training-apis/experiment-config.txt, e2e_tests/tests/deploy/test_local.py
Docker auth is improved in two ways. First if a serveraddress is specified in experiment config we will not send credentials to another server. The second is we now read the ```auths``` section of a users ```~/.docker/config.json``` file meaning users can now use ```docker login``` on their agent nodes.
Go unit tests.
Note it is expected commands fail with a message like
```
[2022-07-11T17:36:29.317436Z] 3ecfd61a || env: can't execute 'bash': No such file or directory
```
Host a local dockerhub registry
```
docker run -e "REGISTRY_AUTH_HTPASSWD_REALM=default" -e "REGISTRY_AUTH_HTPASSWD_PATH=registry" -p 5000:5000 registry:2
```
Get password and username from this line printed from above command
```
time="2022-07-11T18:40:28.564679738Z" level=warning msg="htpasswd is missing, provisioning …
```
=> feat: docker auth improvements [DET-7633, DET-7636]

.github/dependabot.yml
Disable version-bump dependabot PRs (temporarily).
Leave github actions and docker base image PRs, since those aren't
universally broken in CI (and are less frequent)
Security updates will still happen with this change.
Dependabot change only; formal testing is N/A
=> chore: temporary-disable-dependabumps

agent/internal/container.go, agent/internal/docker.go, master/internal/resourcemanagers/agent/agent.go, master/pkg/aproto/master_message.go
This change actually sends the log level for agent added container logs.
The following command 
```
det command run --config="environment.registry_auth.password=docker" --config="environment.force_pull_image=true"  "echo hello" 
```
should print
```
[2022-07-13T14:09:22.225898Z] f9d23f8f || WARNING: setting registry_auth without registry_auth.serveraddress is deprecated and will soon be required
```
=> chore: agent sends log level with agent added container logs

master/internal/resourcemanagers/kubernetes_resource_manager.go
Kubernetes does not support resource pools yet and currently returns an empty string as its resource pool. This causes an issue when launching tensorboard.
=> fix: tensorboard redirecting due to missing rp [DET-7813]

harness/determined/cli/experiment.py, master/static/srv/get_experiments.sql
Responding to DET-7720, this makes two changes to the Experiment CLI, which includes a change to how we respond to CreateExperiment and GetExperiments.
- CreateExperiment CLI will accept a numeric `--project_id`. We get that workspace / project, and overwrite any workspace / project in the config yaml file.
- GetExperiments will use JOINs to put the workspace name and project name in the response (previously left these fields blank except in singular GetExperiment)
- GetExperiments CLI with `--show_project` will prepend two columns: Workspace and Project
(create a project and get its numeric ID)
`det e create decision_trees/gbt_titanic_estimator/const.yaml decision_trees/gbt_titanic_estimator/ --project_id 200`
`det e list` and `det e list --show_project`
=> feat: Place experiment in a project using CLI [DET-7720]

master/internal/core_experiment.go, master/internal/experiment.go
#4533 caused a test failure due to it timing out, not sure if the timeout was just experiment config copying taking longer than the timeout (2 seconds) or if the experiment actor was busy with another message. Either way this change is a lot safer moving the copy before we create the actor since it doesn't add anything interesting to the config.
upstream tests
=> fix: expconf copy timeout triggering when it shouldn't

webui/react/src/hooks/useModal/JupyterLab/useModalJupyterLab.tsx
we were restoring the default when slots input was 0. this fixes that.
do `devcluster`, go to JupyterLab modal, click down arrow on slots, should allow a selection of zero. 
=> fix: allow zero slots for JupyterLab in modal

docs/release-notes/zero-slot-k8s.txt, master/internal/resourcemanagers/kubernetes/spec.go
Zero slot tasks would use the GPU image before this fix. 
In addition zero slot tasks would end up getting exposed all GPUs (not sure if all in the cluster or on the node but still a problem either way).
Create a EKS cluster with a GPU
then run and verify that we can see the GPUs (and the image used has ```-gpu-``` in the name)
```
det cmd run --config="resources.slots=1" nvidia-smi
```
now run a zero slot command and verify we do not see any GPUs (should get command not found with image with ```-cpu-``` in the name)
```
det cmd run --config="resources.slots=0" nvidia-smi
```
Then start a notebook verify the image has ```-cpu-``` in the name
```
det notebook start --config="resources.slots=0"
```
Then run the following snippet in a notebook and verify that the output is ```0``` 
```python …
```
=> fix: zero slot tasks k8s using wrong image and exposing all GPUs [DET-7808]

docs/release-notes/fix-notebook-ignore-template.txt, e2e_tests/tests/fixtures/templates/template.yaml, e2e_tests/tests/template/test_template.py, harness/determined/cli/notebook.py
Notebook now correctly uses the ```--template``` CLI parameter. In addition notebooks now won't launch if ```--preview``` is passed in.
Create the following template with the file below
```
environment:
- "TEST=true"
```
Using the command
```
det tpl set test <path to above.yaml>
```
Then start a notebook with the option
```
det notebook start --template test
```
Then in the notebook run this in a cell and verify that the environment variable set above is actually set
```
import os
os.environ["TEST"]
```
=> fix: notebook ignores --template CLI param and notebooks still launch if --preview param is set [DET-7632]

webui/react/src/shared/utils/data.test.ts, webui/react/src/shared/utils/data.ts
[DET-7822]
`Sets` are the same if they have the same size and their elements are equal.
Note: with the logic in this PR, 
```
isEqual(new Set([[1]]), new Set([[1]])) === false
``` 
This is in keeping with how `Sets` see things though: `Sets` see different arrays containing the same elements as distinct, e.g.
```
> new Set([[1], [1]]).size 
2
```
so that seemed the appropriate way to handle it. 
It would not be possible to implement custom `isEquals` for individual set elements while maintaining performance characteristics one would expect for an `isEqual(a: Set, b: Set)` function (caveat: runtime for `Set` is not part of the JS spec).
[DET-7822]: https://determinedai.atlassian.net/browse/DET-7822?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> fix: ignore order for Set isEqual [DET-7822]

master/internal/api/filters.go, master/internal/api_tasks.go, master/internal/api_trials.go, master/internal/db/postgres_filters.go, master/internal/db/postgres_tasks.go, master/internal/elastic/elastic_task_logs.go, proto/src/determined/api/v1/task.proto, proto/src/determined/api/v1/trial.proto, webui/react/src/components/LogViewer/LogViewerFilters.settings.ts, webui/react/src/components/LogViewer/LogViewerFilters.test.tsx, webui/react/src/components/LogViewer/LogViewerFilters.tsx, webui/react/src/components/TrialLogPreview.tsx, webui/react/src/pages/TaskLogs.tsx, webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx, webui/react/src/services/api-ts-sdk/api.ts
add text search to trial logs. [DET-7446]
added support to text search for trial/task logs stored in postgres.
made an attempt to do the same for elastic, but dont know how to test. I tried uncommenting the `elastic` stage in `devcluster.yaml` then starting a task, but the new tasks still ended up using the postgres backend. in any case not all filtering functionalities are implemented for elasticsearch anyways.
https://user-images.githubusercontent.com/28383080/179709684-3d302f9d-b38e-4ac5-9ebf-8e061978990b.mov
streaming causes the api to get hit pretty frequently. if we think queries might get expensive, we may want to increase the interval.
[DET-7446]: https://determinedai.atlassian.net/browse/DET-7446?atlOrigin=eyJpIjoiNW …
=> feat: text search for task/trial logs [DET-7446]

docs/release-notes/default-password-k8-fix.txt, helm/charts/determined/scripts/k8s-password-change.py, helm/charts/determined/templates/change-password.yaml
API changes had caused this option to cause any deployment with a non empty ```defaultPassword``` to hang.
On a GKE cluster run a deployment with (any recent determined version should be fine) 
```
helm install determined helm/charts/determined/ --set maxSlotsPerPod=2 --set defaultPassword=secret --set detVersion=0.18.4
``` 
Above command can take a minute but it should not hang
Then running
```
det user login admin
det user login determined
```
should both work when ```secret``` is used as the password.
Moves the python code out of this repo https://github.com/determined-ai/k8s-utility and we should ideally replace the image to something we maintain actively (possible dev image we are making with all determined dependencies?) 
See [Release Note](../docs/release-notes/README.md) for …
=> fix: helm option "defaultPassword" caused the deployment to hang [DET-7814]

harness/determined/exec/prep_container.py
On Slurm we attempt prioritize an eth* interface for rendezvous to make sure we have a reachable address for the master.  It appears common for systems to not have an eth* interface, so drop the warning to avoid the noise.
If the eth* interface did not have a valid address, the fallback to hostname would not have been applied, so fixed
that as well.
No behavior change, just changed warning logs.
=> fix: Drop rendezvous interface warning (FOUNDENG-139)

agent/internal/rocm.go, harness/determined/gpu.py
an rocm-smi bug throws up when GPU vendor information isn't present/corrupted on a machine. since this information isn't strictly required by the backend (only web UI), a workaround is to try again to retrieve the needed GPU ID info without the "--showproductinfo" flag.
=> fix: rocm-smi workaround without product info

.circleci/devcluster/double-reattach.devcluster.yaml, agent/internal/agent.go, agent/internal/detect.go, e2e_tests/tests/cluster/managed_cluster.py, e2e_tests/tests/cluster/test_master_restart.py, master/internal/resourcemanagers/agent/agent.go, master/internal/resourcemanagers/agent/agent_state.go, master/pkg/aproto/agent_message.go
When master/agent task restoration is enabled (i.e. `agent_reattach_enabled: true`), and devices change on reconnect, discard the corresponding agent state and tell the agent to shutdown (and restart) as a way to not overly complicate the restore process and keep sanity. 
We use device count and their UUIDs to match the devices. UUIDs for CPUs, CUDA, and ROCM should be stable. In this change, we also introduce stability for artificial slot UUIDs, using agent id as a seed.
- Automated test added. 
- Normal task restoration should continue working the same for existing setups.
For manually testing the device change handling:
1. ensure `agent_reattach_enabled: true` in master config
2.a for CUDA agent, change `NVIDIA_VISIBLE_DEVICES` on the agent container on restart so it sees different …
=> fix: reject reconnecting agents with different device configuration  [DET-7568]

master/.golangci.yml, master/internal/api_user.go, master/internal/authz/authz_provider_type.go, master/internal/config/authz_config.go, master/internal/config/config.go, master/internal/db/postgres.go, master/internal/user/authz_basic_impl.go, master/internal/user/authz_iface.go, master/internal/user/authz_unrestricted_impl.go, master/internal/user/service.go, master/internal/usergroup/postgres_groups.go
We'd like to enable pluggable authorization so:
1. it can be added and enabled in EE in an easier, additive-only fashion to
minimize EE issues.
2. it's modular: no single interface, authorization can instead be implemented
for modules (i.e. `internal/*` subdirectories).
See `AuthZProviderType` in `internal/authz/authz_provider_type.go` for the core implementation.
As an example, the "can user change someone's password" APIs were modified to use it:
- `internal/user/authz_iface.go` contains an interface that all AuthZ types will need to implement and "the registry" (`AuthZProvider`) 
- `internal/user/authz_basic_impl.go` implements this interface for our existing authorization (users can change their own password, admins can change anyones)
- `internal/user/authz_unrestricted_impl.go` is a …
=> feat: pluggable authorization for RBAC.

docs/attributions.txt, harness/determined/common/api/bindings.py, master/internal/api_tasks.go, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/task.proto, webui/react/src/contexts/Store.tsx, webui/react/src/hooks/useFetch.ts, webui/react/src/pages/Cluster/ClusterOverallStats.tsx, webui/react/src/pages/Clusters/ClustersOverview.tsx, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/types.ts
Adds a row of numbers for Active Experiments, TensorBoards, JupyterLabs, etc. to the Clusters page. This was previously on the Experiments page but was removed when that became a Project page.
For consistency with other stats on this page, I've put them into the shared Store.
I'm waiting for UI approval, but in the meantime it can go through a technical review.
When running experiments and notebooks, this row of mini-cards should appear on the Clusters page. 
When nothing is running, none of these mini-cards should be visible.
=> feat: Show active experiment and task count on resources page [DET-7680]

agent/packaging/entrypoint.sh
Agent entrypoint shell script should use `exec`. This allows `SIGTERM` to be forwarded on container stop, which in order makes agent stop its fluentd.
Fixes #4565 
1. `det deploy local cluster-up`
2. `det deploy cluster cluster-down` 
3. `docker ps`: there should be NO orphaned `determined-fluent` container.
=> fix: agent entrypoint should use `exec`. [DET-7834]

.circleci/config.yml, e2e_tests/pytest.ini, e2e_tests/tests/conftest.py, e2e_tests/tests/deploy/test_local.py
This is the longest running e2e test so moving it to upstream improves CI build time. The test is also a stress test so not really needed to run on every PR.
See this PR doesn't run the test and that this upstream commit ran ```test-stress``` https://github.com/determined-ai/determined/runs/7524411987
=> ci: long running det_deploy_local stress test to upstream

master/internal/core_experiment.go, webui/react/src/services/api-ts-sdk/api.ts
Before:
After:
Go to swagger page (click `API (Beta)` on the side navigation) and verify `/{experiment_id}/file/download` works as expected. 
=> fix: comment to gen swagger [DET-7926]

webui/react/src/pages/InteractiveTask.tsx, webui/react/src/pages/Wait.tsx
fix: persist task state update in interactive task view [DET-7929]
The previous implementation of tracking the `Command` state for the `InteractiveTask` did not fully solve the problem since the `Wait` page ultimately gets redirected and the `Command` state polling is stopped. Since the polling would stop users would not be notified of any `Command` state changes. 
The initial implementation was chosen as a way to avoid additional polling for the command state but this PR does add additional polling within the `InteractiveTask` component. The decision comes with two advantages: 
1. Now the `InteractiveTask` page will always receive the most up to date information about the appropriate task, and no longer depend on the `Wait` component,  which will be beneficial as more features are added …
=> fix: persist task state update in interactive task view [DET-7929]

webui/react/src/components/InlineEditor.module.scss
I found that sentences in description are sometimes invisible when width is narrow and sentences are long.
Sentences should be always visible 
https://user-images.githubusercontent.com/109113616/182296754-9b0c0136-1909-4903-860d-3d43cc76d876.mov
https://user-images.githubusercontent.com/109113616/182296648-db2b52db-377c-4efa-895b-829aceb29481.mov
- Check if sentences are visible in any length and type of sentences and description width
Description in experiment detail has 500 letters limit but the one in experiment list doesnt. Should we add one?
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> fix: word break in description

master/pkg/searcher/random_test.go, master/pkg/searcher/searcher.go
The `s.Record` call was previously moved after the `if` block so that
the `Shutdown` operation was correctly recorded. However, this meant
that, running, e.g., random search with `max_concurrent_trials = 1`
would shut down after one trial, since the request to create the next
trial would not be counted in the check. So we simply have to record the
other operations first and then the `Shutdown` separately.
=> fix: record operations at the right places around shutting down

proto/src/determined/api/v1/experiment.proto, proto/src/determined/api/v1/notebook.proto, proto/src/determined/api/v1/task.proto, proto/src/determined/experiment/v1/searcher.proto, proto/src/determined/user/v1/user.proto
Trent pointed out that a removed field is still marked as "required" in the proto, which this fixes. I used this opportunity to clean up unused imports which have show up as warnings on `make -C proto build`
=> chore: Remove unnecessary imports and fields in proto

harness/determined/pytorch/deepspeed/_deepspeed_trial.py
We were computing the batch size for a sample from the validation loader incorrectly; the previous way did not account for batch structure (e.g. list, dictionary, etc).  This resulted in incorrect tracking of records when we logged validation timing info.  
Tested locally.
=> fix: deepspeedtrial validation batch size computation

docs/release-notes/4745-fix-sdk.txt, e2e_tests/tests/test_sdk.py, harness/determined/common/experimental/determined.py, harness/determined/common/experimental/experiment.py, harness/determined/common/experimental/model.py, harness/determined/experimental/client.py
The GET experiments endpoint changed, but the python sdk did not.
Follow-up work includes migrating all of the python sdk over to
use the generated bindings, but that was no way going to happen
in time for the 0.19.1 release.
=> fix: python sdk can parse master output again [DET-8021]

harness/determined/tensorboard/metric_writers/callback.py
Metrics writer was computing step count incorrectly resulting in bad tensorboard charts (see ticket for screenshots).
- run `mnist_pytorch/const.yaml` or `mnist_pytorch/distributed.yaml` experiment
- open tensorboard, zoom in on `loss` chart, ensure there're no artifacts.
=> fix: tensorboard metrics step count [DET-8028]

e2e_tests/tests/experiment/test_custom_searcher.py, harness/determined/common/schemas/expconf/_gen.py, harness/determined/common/schemas/expconf/_v0.py, harness/determined/core/_searcher.py, master/pkg/schemas/expconf/length.go, master/pkg/schemas/expconf/searcher_config.go, master/pkg/schemas/expconf/zgen_custom_config_v0.go, master/pkg/schemas/zgen_schemas.go, schemas/expconf/v0/searcher-custom.json, schemas/expconf/v0/searcher.json
Trials require the unit to be specified. All searchers have it included in MaxLength but custom searcher does not.
We noticed that after I removed max_length from the custom searcher configuration (because it is not supposed to be required), the custom searcher test started only running a single batch in each trial. Furthermore, the following message appeared in the trial logs:
```
root: The searcher configuration provided was configured without units, but the training loop you are using (one of the Trial APIs) requires a searcher configured with units.  Proceeding anyway, and assuming that the lengths configured in the searcher are in terms of epochs.
```
Trials quietly default to epochs as a unit.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-not …
=> fix: add unit to custom searcher config

.github/workflows/publish-helm.yml
Add an action to update the GH pages-hosted helm chart repo with the new chart when a new release is cut.  Backwards compatibility workflow-dispatch trigger also included to retrofit previous releases.
Run it manually and hope the world doesn't burn.
This is gross because I'm a sysadmin and sysadmins can only write gross, mostly-functional scripts. :bomb:  Commit messages are also gross because I figured it'd be easier to wait until merge time to squash them into something better instead of bothering with rebase. :D 
=> ci: add helm repo [infeng 1]

master/static/srv/get_models.sql
There's some logic error in how I set up tag-level filtering in `get_models.sql`. In this fixed version, you can choose tags and return any models with 1 or more of those tags. 
- On the model registry page, create empty new models with no tags, common tags, and unique tags
- Verify that all model tags appear in the table's Tags column filter
- In the Tags column, use filters to limit table rows to models with the common tag, or with any of a few unique tags
=> fix: Model table - tags filter [DET-8027]

examples/deepspeed/gpt_neox/det_utils.py, examples/deepspeed/gpt_neox/gpt2_trial.py
fix a minor issue with the example:
- parsing args failed if `overwrite_values` is not provided in the determined experiment config -> now we will return an empty dict
Note that we do not have a dataloader resume issue since we are relying on determined's dataloader to skip the correct number of datapoints when resuming.  If we were using gpt-neox's dataloader directly, we'd need to make sure to set start_iter after loading a checkpoint.  
Tested manually
=> fix: gpt_neox deepspeed example

bindings/generate_bindings.py, harness/determined/cli/job.py, harness/determined/cli/notebook.py, harness/determined/cli/workspace.py, harness/determined/common/api/bindings.py
generate_bindings.py generates deterministic code.  One way in which it
accomplishes that is by sorting parameters by name when it writes the
parameters to functions and methods.
That is safe to do as long as all args are keyword-only.  I made
keyword-only a requirement that for all the functions, but forgot to do
that for all the class __init__ methods.
=> chore: disable positional args in bindings.py classes

e2e_tests/tests/cluster/test_users_experiment_api.py, harness/determined/cli/command.py, harness/determined/cli/experiment.py, harness/determined/cli/notebook.py, harness/determined/cli/tensorboard.py, harness/determined/common/api/experiment.py, harness/determined/common/context.py, harness/determined/common/experimental/determined.py, harness/determined/common/util.py, harness/tests/cli/test_cli.py, master/internal/core_experiment.go
This is an early part of a larger refactor.  Overall, the goal is to
move away from handcrafted API requests towards using the generated
bindings.
One blocker to that effort is that the creation of context directories
is definitely based on the handcrafted APIs.
Additionally, the context loading code has grown "crusty" over time; it
involved a lot of bandaid-style coversions between old and new formats,
in addition to the fact that a Context class existed, but it didn't
really do anything.  This PR focuses on migrating to a bindings-native
storage structure and reducing overall "crustiness".
=> chore: Use bindings.v1File instead of ContextItem

e2e_tests/tests/cluster/utils.py
Fix the cluster utils cluster_slots()  agents url, and properly
reference the agents dict within the response.
This code was apparently not exercised without custom
resource pools defined during the test?
=> test: Fix cluster utils cluster_slots() API

webui/react/src/App.tsx, webui/react/src/components/UserAvatar.test.tsx, webui/react/src/components/UserAvatar.tsx
[DET-7962]
- Check if user api call is reduced (user api call less than 5 times before polling starts in network tab)
- user api used to be called more than 5 times before polling starts
- Check if user data is fetched appropriately instead of no user data
[DET-7962]: https://determinedai.atlassian.net/browse/DET-7962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> perf: improve too many user api call

master/internal/db/postgres_proto.go
We have a specific message and `codes.NotFound` response when an experiment/model/project/workspace does not exist:
```go
switch err := a.m.db.QueryProto("get_experiment", exp, experimentID); {
case err == db.ErrNotFound:
return nil, status.Errorf(codes.NotFound, "experiment not found: %d", experimentID)
```
but `QueryProto` always wraps the error inside of a new internal error, so err never matches db.ErrNotFound
this moves code around in `QueryProto` to let the ErrNotFound message pass through unwrapped
Go to /api/v1/workspaces/1000 to trigger a not-found response
=> fix: directly return object-not-found errors instead of rewrapping them

webui/react/package-lock.json, webui/react/package.json, webui/react/src/components/Router.tsx, webui/react/src/index.tsx, webui/react/src/routes/routes.ts
Successor of #4619
Followed [the instruction](https://github.com/remix-run/react-router/discussions/8753)
I'm done with `props.match -> v6 useParams` in `2) Change component code use v6 instead of v5 APIs`
- Check if all routes work
=> chore: `react-router-dom` partial update part1

master/internal/api_experiment.go
Learning Curve in Experiment visualization was empty due to 
```
case expconf.CustomConfig:
return nil, errors.New("experiments with custom searcher are not supported for trial sampling")
```
Now we are returning top trials by `ByMetricOfInterest`
```
cd e2e
pytest tests/experiment/test_custom_searcher.py --log-cli-level=info
```
check if learning curve shows plot
=> fix: show learning curve

master/internal/api_trials.go, webui/react/src/pages/TrialDetails/TrialChart.tsx, webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
Use the trial-comparison / trial-summarization endpoint to get downsampled metrics from an experimental run. As intended back in #4300 and missed in #4703 .
Single-trial experiments should have an experiment graph with metrics added/removed
=> fix: get trial datapoints from trial comparison/summarization endpoint

e2e_tests/tests/cluster/test_logging.py, e2e_tests/tests/cluster/test_users.py, e2e_tests/tests/cluster/test_workspace_org.py, e2e_tests/tests/experiment/experiment.py, e2e_tests/tests/nightly/compute_stats.py, harness/determined/cli/job.py, harness/determined/cli/project.py, harness/determined/cli/session.py, harness/determined/cli/util.py, harness/determined/cli/workspace.py, harness/determined/common/__init__.py, harness/determined/common/api/__init__.py, harness/determined/common/api/_session.py, harness/determined/common/api/authentication.py, harness/determined/common/api/experiment.py, harness/determined/common/experimental/__init__.py, harness/determined/common/experimental/_session.py, harness/determined/common/experimental/checkpoint/_checkpoint.py, harness/determined/common/experimental/determined.py, harness/determined/common/experimental/experiment.py, harness/determined/common/experimental/model.py, harness/determined/common/experimental/trial.py, harness/determined/common/util.py, harness/determined/core/_checkpoint.py, harness/determined/core/_context.py, harness/determined/core/_preempt.py, harness/determined/core/_searcher.py, harness/determined/core/_train.py, harness/determined/exec/prep_container.py, harness/determined/experimental/client.py
Originally, Session was part of the python sdk, and not used anywhere
else.  Slowly it has come to be preferred for REST API interactions,
especially now that it is used with the new generated bindings.
Most things need bindings to work, and this requirement will grow
stronger as we port more and more code to use the generated bindings.
Bindings needs Session to work.  Session needs api.requests and
api.authentication to work.  This is all a big mess unless the importing
of Session is carefully controlled.
This PR promotes Session to be part of determined.common.api, with a
controlled import order to prevent failed circular imports.  Python
SDK-related import paths just point at the real definition now.
Additionally, this renames the old api.authentication.Session class to
UserTokenPair, …
=> chore: promote Session to a first-class citizen

webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.module.scss, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx, webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.module.scss, webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx, webui/react/src/routes/routes.ts
From ticket:
> To repro, run a hp search experiment where one of parameters is categorical, e.g. as suggested in the thread:
> ```
> scheduler:
>       type: categorical
>       vals:
>         - _type: "WarmupDecayLR"
>           params:
>             warmup_min_lr: 0
>             warmup_num_steps: 100
>             total_num_steps: 1841
>             warmup_type: "linear"
>         - _type: "WarmupLR"
>           params:
>             warmup_min_lr: 0
>             warmup_num_steps: 100
>             warmup_type: "linear"
> ```
> Issue:
- >  In visualization → learning curve UI the parameter value is displayed as “undefined”.
- >  In visualization → hp parallel coordinates it is displayed as “[object Object]”
Try to repro, parameter values should show up as stringified JSON instead of …
=> fix: correctly display nested categorical hyperparameters [DET-8074]

webui/react/src/services/decoder.ts
When viewing an individual trial on a multi-trial experiment, the endpoint returns `metrics: { avgMetrics: {...}, batchMetrics: [ ... ] }` instead of a single `metrics` object. On [latest-master](http://latest-master.determined.ai:8080/det/experiments/1292/trials/3709?filter=All&metric=validation%7Cvalidation_loss&metric=training%7Closs) the result is a workloads table with no numbers.
This modifies `filterNonScalarMetrics` to get metrics out of `metrics.avgMetrics` if it exists.
Edit: this also fixes `bestValidationMetric` and `latestValidationMetric` in the trial comparison table.
- Single-trial experiment has numbers in workloads table.
- While running a multi-trial experiment, numbers appear in `bestValidationMetric` and `latestValidationMetric` columns.
- After running a multi-trial …
=> fix: handle avgMetrics response on trials of multi-trial experiment

docs/release-notes/torch-distributed-single-slot.txt, harness/determined/launch/torch_distributed.py, harness/tests/launch/test_torch_distributed.py
we bypass torch.distributed.launch behavior by automatically detecting single-slot trials and just calling the training script. 
=> fix: do not bypass torch.distributed.launch for single-slot trials

docs/release-notes/max-cc-searcher-bugs.rst, e2e_tests/tests/experiment/__init__.py, e2e_tests/tests/experiment/experiment.py, e2e_tests/tests/experiment/test_core.py, master/pkg/searcher/grid.go, master/pkg/searcher/random.go
This change fixes a bug where, if trials exited early under the grid or random searchers when using `max_concurrent_trials`, it would cause double the amount of trials to be spawned in its place, exceeding max concurrent trials. This was caused by the searcher hooking into both 'trial exited early' and 'trial closed' events as notification a trial had closed when 'trial closed' is already emitted for every trial ('trial exited early' is just an additive event for failed and invalid HP trials).
=> chore: fix random/grid searcher bug with max_concurrent_trials

webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.module.scss, webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.tsx, webui/react/src/pages/ExperimentDetails/CodeViewer/index.scss
tickets: 
- [DET-7872]
- [DET-7873]
- [DET-8058]
- [DET-8059]
- [DET-8060]
- [DET-8061]
This PR implements some of the points taken in a dogfooding session. 
Here's the summary of the current changes:
- handle when the file returns an error (can't render the file)
- handle unsupported file types
- display appropriate syntax for the selected file (especially python)
- display error message for empty files
- improve rendering for the tree
- improve CSS for the tree overall
- improve the rendering logic to avoid rendering invalid items (as in "Original config" when it's not there)
- improve the tree behavior, right now it expands horizontally when the tree gets expanded, up to a limit
Go to any experiment `/det/experiments/<experiment_id>`, then click the `Code` tab.
The initial render …
=> feat: view code improvements

docs/release-notes/experiment-restore.txt, master/internal/experiment.go, master/internal/rm/job.go, master/internal/rm/kubernetes_resource_manager.go
the k8 resource manager's actor was missing a handler for RecoverJobPosition msg
reproduced the issue through minikube and manually setting q_position to -1
- the job positions does get defaulted to 0 somewhere I'm not sure where. in the customer's case they might have ran an older migration where it had translated into -1
- `for i in $(seq 1 4); do det e create ./examples/gan/gan_mnist_pytorch/const.yaml ./examples/gan/gan_mnist_pytorch/&; done`
- `update jobs set q_position=-1;`
repeated the steps in this branch and the resource manager did not crash
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> fix: job queue experiment restore

e2e_tests/tests/cluster/test_workspace_org.py, harness/determined/common/api/bindings.py, master/internal/api_experiment.go, master/internal/api_project_intg_test.go, master/internal/mocks/project_authz_iface.go, master/internal/project/authz_basic_impl.go, master/internal/project/authz_iface.go, master/static/srv/get_experiment.sql, master/static/srv/get_experiments.sql, master/static/srv/move_experiment.sql, proto/src/determined/experiment/v1/experiment.proto, webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx, webui/react/src/pages/ProjectDetails.tsx, webui/react/src/pages/TrialDetails/TrialInfoBox.stories.tsx, webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.stories.tsx, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/decoder.ts, webui/react/src/storybook/shared/generateTestExperiments.ts, webui/react/src/types.ts, webui/react/src/utils/experiment.ts
My goal is to add permissions on moving experiments and incorporate it into the authz interface
- [Already required] Destination project must be visible to the user (through `GetProjectByID`)
- [Already required] Destination project cannot be archived
- Moved experiment must be visible to the user (runs through `getExperiment`, which doesn't use authz yet, but will)
- Experiment's source project must be visible to the user (through `GetProjectByID`)
- Call new `CanMoveProjectExperiments` authz
Conditions to allow `CanMoveProjectExperiments`:
- admin user
- immutable source project [not quite right, but tl;dr I don't want to block users from withdrawing experiments from their default Uncategorized project]
- user with ownership of both source and destination projects [this doesn't seem …
=> chore: add authz on moving experiments between projects [DET-7750]

webui/react/src/pages/TrialsComparison/Table/TrialTable.tsx, webui/react/src/pages/TrialsComparison/Trials/data.ts, webui/react/src/pages/TrialsComparison/TrialsComparison.tsx
we do not do a total count for performance reasons.
`fakeTotal` is a hack to get infinite pagination
antd complains with 
```
Warning: [antd: Table] `dataSource` length is less than `pagination.total` but large than `pagination.pageSize`. Please make sure your config correct data with async mode. 
```
but it doesn't seem to matter?
=> remove leftover pagination total fields

e2e_tests/tests/experiment/__init__.py, e2e_tests/tests/experiment/experiment.py, e2e_tests/tests/experiment/test_core.py
There was a race condition where two trials might not get created at the
exact same time, creating the possibility for false negatives
=> ci: fix flakes in test_max_concurrent_trials

master/internal/api_experiment.go
If OrderBy is unspecified for sortBy SearcherMetrics sort by best, otherwise follow ASC or DESC. 
Call ```GetExperimentsCheckpoints``` with ```SearcherMetrics``` 
With ```OrderBy``` unspecified and make sure ```searcherMetrics``` in the response has "best" according to metric at the top
With ```OrderBy``` DESC and make sure ```searcherMetrics``` is in DESC order
With ```OrderBy``` ASC and make sure ```searcherMetrics``` is in ASC order
=> chore: allow OrderBy in GetExperimentCheckpoints for SortBy SearcherMetrics

examples/graphs/proteins_pytorch_geometric/startup-hook.sh
Set `torch_geometric==2.0.4` in example to avoid behavior change in `2.1.0` that breaks nightly e2e gpu test.
Verify the `test-e2e-gpu-nightly` CI test `test_protein_pytorch_geometric` runs successfully.
- [N/A] User-facing API changes need the "User-facing API Change" label.
- [N/A] Release notes should be added as a separate file under `docs/release-notes/`.
- [N/A] Licenses should be included for new code which was copied and/or modified from any external code.
- [N/A] If modifying `/webui/react/src/shared/` verify `make -C webui/react test-shared` passes.
=> chore: set torch_geometric version in example to fix e2e test.

master/Dockerfile
On OpenShift/OKD, the master pod runs as an ephemeral user with GID 0.
This patch changes the permissions so it can write to /var/cache.
Signed-off-by: Burt Holzman <burt@fnal.gov>
=> fix: change /var/cache permissions to mode 775

bindings/generate_bindings.py, harness/determined/common/api/_session.py, harness/determined/common/api/bindings.py
This is a step towards slowly migrating old cli code to the new
generated bindings.
In the short term, this will allow a migration of
determined/common/api/experiment.py to newer patterns (mostly generated
bindings, but a few manual Session.get(stream=True) calls).
In the long term, the generated bindings should also automatically
support streaming endpoints.
No differences in code execution as of this PR.
=> chore: add stream argument to Session._do_request

helm/charts/determined/templates/master-config.yaml, helm/charts/determined/templates/master-deployment.yaml, helm/charts/determined/values.yaml
add OIDC and SCIM (EE-only) configuration options to helm chart [DPS-204]
1. Fill in the new options in `helm/charts/determined/values.yaml`:
```yaml
enterpriseEdition: true
oidc:
enabled: true
provider: Okta
idpRecipientUrl: http://localhost:8080
idpSsoUrl: https://dev-########.okta.com
clientId: <client_id>
clientSecretKey: client-secret
clientSecretName: oidc
scim:
enabled: true
auth:
type: basic
username: determined
password: password
```
2. Add `command` and `args` keys under the hierarchy below in `helm/charts/determined/templates/master-deployment.yaml`:
```yaml
spec:
template:
spec:
containers:
- name: determined-master-{{ .Release.Name }}
command: ["sleep"]
args: ["999d"]
```
3. Store the OIDC client secret in a k8s secret:
```Shell
$ kubectl create secret generic oidc …
```
=> feat: helm chart: add OIDC and SCIM options [DPS-204]

docs/interfaces/commands-and-shells.rst, docs/training/setup-guide/custom-env.rst, harness/setup.py, master/static/srv/notebook-template.ipynb
We stopped supporting Python 3.6 when it went EOL.
I reported it in the release notes in #3377, but forgot to fix the rest
of the docs.
Note that setup.py has not been modified; there's no need to break
existing users who are succesfully using an usupported old version.
=> docs: update required python to 3.7

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.rst, docs/reference/reference-deploy/config/master-config-reference.rst
Relax the minimal requirement that Slurm must be configured for GresTypes=gpu. Add gres_supported option to resource_manager section of Determined-AI master.yaml.
=> docs: Determined AI Slurm jobs do not require gres.

harness/determined/common/api/request.py, master/internal/api_auth.go, master/internal/db/database.go, master/internal/db/postgres_tasks.go, master/internal/grpcutil/auth.go, master/internal/mocks/db.go, master/internal/task/allocation.go, master/pkg/model/task_session.go, master/static/migrations/20220902141323_add-user-to-allocation-session.tx.down.sql, master/static/migrations/20220902141323_add-user-to-allocation-session.tx.up.sql
#4905 assumed that using user session would be ok. I wasn't considering user sessions expiring to be an issue so switched back to using allocation sessions. This change associates allocation sessions with users so that they can use ```grpcutil.GetUser``` which is needed for RBAC to determined access for users.
Run an experiment and see no errors.
=> fix: associate allocation sessions with users

webui/react/src/components/PageHeaderFoldable.module.scss, webui/react/src/components/PageHeaderFoldable.tsx
`.optionsMainButton:nth-of-type(1)` doesn't select the first element with the class `.optionsMainButton`. Apparently it actually selects the element with the class `.optionsMainButton` that is the first of its type (button). Since the first sibling button didn't have the class `.optionsMainButton`, it didn't select anything. It's very confusing, here are some more details: https://stackoverflow.com/questions/30603786/nth-of-type2-is-targeting-the-first-of-type
Go to an experiment details page and change the width of the window. The actions buttons should swap between the button row and the overflow menu smoothly.
[DET-1234]: …
=> fix: correct overflow action buttons [DET-8322]

webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx, webui/react/src/hooks/usePermissions.ts, webui/react/src/services/api.ts, webui/react/src/services/apiConfig.ts
When viewing a user profile in RBAC, their permissions are listed in an `antd.Table` component. 
For testing purposes, this is available to OSS admin users, and the mock response is a global `oss_user` permission.
[to test in OSS]
- While logged in as admin, go to `/det/settings/user-management/rbac-enabled`. Click "Edit User" (or view, if it's available). You should see the table and oss_user permission.
- Log in as determined / other user, and go to the same page. There is no table.
=> feat: can see users' permissions if view_permissions enabled [DET-8222]

master/internal/api.go, master/internal/usergroup/api_groups.go
Should avoid name clash when embedding multiple APIServers within the main one.
N/A
I've hit that in my current work in progress, and it'd also be an improvement for https://github.com/determined-ai/determined-ee/pull/409/files#diff-3917b52e2d2657bb4bd3d17fa4f229e3fd52b6ed36cf831921870b7fc7f853f9R27
=> refactor: rename `usergroup.APIServer` -> `usergroup.UserGroupAPIServer`

master/internal/db/postgres_checkpoints_intg_test.go
`db.CheckpointByUUIDs` query doesn't sort it's results, so they're up to postgres to decide. On my local dev setup, they always come out in an "unexpected" order. To make the equality check stable, let's sort both expected & actual uuid slices.
N/A - this is a fix for a test.
=> test: master test-intg `TestDeleteCheckpoints` stability.

e2e_tests/tests/experiment/test_custom_searcher.py, master/internal/api_experiment.go, master/internal/mocks/authz_experiment_iface.go
When I run custom searcher tests multiple times _locally_ they fail after the first run because experiments with expected names already exist (they have been created by previous runs). This does not affect circleci but is still quite annoying:
```
FAILED tests/experiment/test_custom_searcher.py::test_run_random_searcher_exp_core_api[core_api_model.yaml-custom-searcher-random-test-exception_points0] - assert 6 == 1
FAILED tests/experiment/test_custom_searcher.py::test_run_random_searcher_exp_core_api[core_api_model.yaml-custom-searcher-random-test-fail1-exception_points1] - assert 2 == 1
FAILED tests/experiment/test_custom_searcher.py::test_run_random_searcher_exp_core_api[core_api_model.yaml-custom-searcher-random-test-fail2-exception_points2] - assert 2 == 1
FAILED …
```
=> fix: make experiment names unique across test runs

master/internal/core.go
feat: add cache control headers to static web assets [DET-7450]
Currently we are not sending any cache-control headers with server responses for static assets for the WebUI. This change 
will add cache control headers to static assets. 
Assets that are given a unique filename per deployment we can cache "forever", one year according to [RFC 2616 14.21](https://www.ietf.org/rfc/rfc2616.txt). Assets that we may expect to change regularly such as image files we will only cache for a short period of 5 minutes.
1. Navigate to the  Determined website. Open up the network tab. The next few steps can be verified by looking at the `Headers` tab as shown above.
2. Ensure that all of our bundled and hashed files which are the `chunk.js or chunk.css`, `woff`, `woff2`, contain a `Cache-Control` header …
=> feat: add cache control headers to static web assets [DET-7450]

harness/determined/common/context.py, harness/tests/cli/test_cli.py
There is a bug in how Determined deals with wildcard patterns in `.detignore`.
The new `test_cli.test_read_context_with_detignore_wildcard` should be run by CircleCI and should pass.
=> fix: .detignore interprets wildcards like .gitignore [DET-7094]

harness/determined/common/api/bindings.py, master/internal/api.go, master/internal/api/apiutils/utils.go, master/internal/db/postgres.go, master/internal/db/utils.go, master/internal/rbac/api_rbac.go, master/internal/rbac/api_rbac_stub.go, master/internal/rbac/api_rbac_wrapper.go, master/internal/usergroup/api_groups.go, master/internal/usergroup/postgres_groups.go, master/static/migrations/20220907145440_groups-constraint.tx.down.sql, master/static/migrations/20220907145440_groups-constraint.tx.up.sql, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/rbac.proto, proto/src/determined/rbac/v1/rbac.proto, webui/react/src/services/api-ts-sdk/api.ts
Addresses the OSS portion of [DET-7867] and [DET-8000] by adding a stub version of the RBAC API and its types.
Outside of EE, the RBAC API should be available, but making requests to its endpoints should result in the error message "Determined Enterprise Edition is required for this functionality." Additionally, creating a new group with an owner should add the owning user to the group regardless of if the user is passed in as one of the users to add to the group.
[DET-7867]: https://determinedai.atlassian.net/browse/DET-7867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-8000]: https://determinedai.atlassian.net/browse/DET-8000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add stub RBAC API

webui/react/src/contexts/Store.tsx, webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx, webui/react/src/hooks/usePermissions.ts, webui/react/src/services/apiConfig.ts, webui/react/src/types.ts
To match the draft spec, we included `globalOnly` and `workspaceOnly` fields. The API implementation has only one `isGlobal` field. For consistency we can change this now.
If this merges first, I need to update #5022 
`globalOnly` should not exist in the code. `workspaceOnly` is kept in one place for the user modal permissions table for admins.
=> chore: replacing globalOnly/workspaceOnly with isGlobal [DET-8370]

e2e_tests/tests/experiment/__init__.py, e2e_tests/tests/experiment/experiment.py, e2e_tests/tests/experiment/test_custom_searcher.py, e2e_tests/tests/fixtures/custom_searcher/core_api_custom_searcher.py, harness/determined/searcher/core_search_runner.py, harness/determined/searcher/search_runner.py
LocalSearchRunner: 
* when an experiment is stopped in the WebUI, print warning to the user and allow them to manually CTRL+C the process
CoreSearchRunner:
* when a searcher experiment is paused → preempt the experiment
* when the experiment is paused → preempt the searcher experiment
Added tests for Core Search Runner pausing searcher first or multi-trial experiment first.
LocalSearchRunner tested manually.
=> fix: handle pausing experiment [MLG-55]

harness/determined/common/api/bindings.py, proto/src/determined/api/v1/rbac.proto, proto/src/determined/rbac/v1/rbac.proto, webui/react/src/components/Navigation.tsx, webui/react/src/contexts/Store.tsx, webui/react/src/hooks/useFetch.ts, webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx, webui/react/src/hooks/useModal/UserSettings/useModalGroupRoles.test.tsx, webui/react/src/hooks/useModal/UserSettings/useModalGroupRoles.tsx, webui/react/src/hooks/usePermissions.ts, webui/react/src/pages/Settings/GroupManagement.tsx, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/decoder.ts, webui/react/src/services/types.ts
- New modal, based on the Create/Edit Group modal and its tests.
- Calls `listRoles` for all global roles, `getRolesAssignedToGroup` to filter out current roles, `assignRoles` to add role to a group.
- Require role.id and permission.id fields for convenience. Don't require other fields (such as role.permissions) as these would be annoying to send back to the API.
In the future we might want to list existing roles (and users) and make them removable with checkboxes or other UI.
In contexts/Store.tsx , replace the `knownRoles: [],` line with a initial demo role (since listRoles will not return content).
```typescript
knownRoles: [{
id: -1,
name: 'Test OSS',
permissions: [{
id: -2,
isGlobal: true,
name: 'oss_user',
}],
}],  // comma before pinnedWorkspaces
```
See [Release …
=> feat: Modal to add role to group [DET-8220]

webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.test.tsx
Add mock for `routes/utils` so import from other places do not error
On way to reproduce error without changes in this PR is to edit `webui/react/src/contexts/Store.tsx` as
`+import { getCookie } from 'utils/browser'; getCookie('hola');`
=> fix: WebUI codeview test mock [DET-8351]

webui/react/src/hooks/usePermissions.ts
- The cluster_admin has all possible permissions, so I modified `relevantPermissions` to return `{ has: () => true }` in this case instead of a Set<string>.
- Without OSS admin or permission CAN_ADMINISTRATE_USERS, the RBAC table dropdown menu has only a View Profile option.
- Without OSS admin or permission CAN_UPDATE_GROUP, the RBAC table has no dropdown menu
- I liked how canViewWorkspaces is static, so I had other globally applicable permissions (view-permissions, and the new user-admin and group-admin) also be static.
- On OSS, non-admin users have fewer options on /settings/user-management and no options /settings/group-management
- relevantPermissions workflow makes sense for OSS admin/non-admin and RBAC cluster_admin / other permissions
See [Release …
=> feat: cluster_admin permission and related user/group admin permissions [DET-8229]

webui/react/src/components/NavigationSideBar.tsx, webui/react/src/hooks/usePermissions.ts, webui/react/src/pages/ProjectDetails.tsx, webui/react/src/pages/WorkspaceDetails.tsx, webui/react/src/pages/WorkspaceList.tsx
Completes the current spec of workspace permissions with `create_workspace` (global) and `view_workspace` (a specific workspace).
- Creating a workspace is possible from the + icon in sidebar, or from the New Workspace button on `/det/workspaces`. No permission = we hide these buttons.
- You might view workspace content by loading Determined (`/` -> `/det/projects/1`) or a link. In RBAC, the API will return a 404 if these are not accessible. I implemented `canViewWorkspace({ id: workspaceId })` to show the 404 page.
- You might go to WorkspaceDetails from those listed in pinned workspaces or WorkspaceList. When RBAC is on, the API will not return un-viewable workspaces to these lists. No need to implement client-side filtering.
Creating and viewing workspaces continues to be allowed on …
=> feat: Permissions to create and view workspaces [DET-8373]

master/static/srv/proto_get_trials_plus.sql
Fix issue where Total Checkpoint Size was showing the size of all checkpoints, even deleted ones.
1. Create an single trial experiment which creates multiple trials (set min_checkpoint_period to something small).
2. Wait for trial to complete and GC task to run,.
3. Go to `http://host:8080/det/experiments/<exp_id>/overview`
4. Observe that the "Total Checkpoint Size" matches the total for non-deleted checkpoints in: `http://host:8080/det/experiments/<exp_id>/checkpoints`
=> fix: Trial.TotalCheckpointSize considers deleted checkpoints [DET-8399]

e2e_tests/tests/cluster/test_users.py, e2e_tests/tests/experiment/experiment.py, harness/determined/common/api/bindings.py, master/internal/api_user.go, master/internal/api_user_intg_test.go, proto/src/determined/user/v1/user.proto, webui/react/src/services/api-ts-sdk/api.ts
grpc-style user APIs were missing support for username / groupname fields in `AgentUserGroups`, i.e. `link-with-agent-user` feature. This is not an externally facing fix: `AgentUserGroups` isn't currently in use by WebUI, CLI still uses the old style.
Under the hood, user name and group name are NOT NULL fields in the table. Prior to this fix, they'd be reset to empty strings due to protobuf / golang empty struct initializations.
Technically, uid and gid are critical for the system, while user name and group name are cosmetic, however if we enforce them in one place (db and `link-with-agent-user`) it probably makes sense to enforce them everywhere.
Expanded automated testing. …
=> fix: support setting agent username and group in user APIs.

webui/react/src/services/apiConfig.ts, webui/react/src/utils/error.ts
Returns an empty list of possible roles to `listRoles`. This is separate from the what-role-am-I request.
First commit was an attempt to silence the 501 error, but TypeScript does not like it.
No error appears in browser console, no request outbound to `roles/search`
=> chore: Avoid error from RBAC listRole endpoint [DET-8395]

.circleci/config.yml
Uploading the directory containing the docs output takes a considerable amount of time, due to the large number of files involved.
=> ci: store docs output as a single file

webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
[DET-8443]
do `dev.setServerAddress` against http://gke.determined.ai/det/experiments/201 to verify fix and against http://52.89.73.17:8080/api/v1/experiments/126 to verify preservation of behavior for nested hps.
[DET-8443]: https://determinedai.atlassian.net/browse/DET-8443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: display primitive hps correctly in parallel coordinates plot

webui/react/src/constants/states.ts
Addressing an issue in the release - when 1+ experiments are selected, the new run states should allow the same actions which were allowed for Active state.  This is pause/cancel/kill.
On Project details page or Experiment details page, try to cancel or kill a running experiment.
=> fix: new states can be paused, canceled, killed [DET-8449]

webui/react/src/pages/ProjectDetails.tsx
When I added a 404 page in #5045 , I accidentally blocked the NoPermissions page from showing up in that case. This moves the NoPermissions check to happen first.  Should not block release.
Remove initial permissions ( oss_user ) from contexts/Store.tsx
=> fix: No Permissions page vs. 404 page

e2e_tests/tests/cluster/test_rbac.py, harness/determined/cli/cli.py, harness/determined/cli/rbac.py
RBAC CLI implementation with e2e tests. Requires EE to use and run the tests.  
E2e tests. They are skipped in OSS so to test you can run a ee devcluster with config the following config
```
security:
authz:
rbac_ui_enabled: true
```
=> feat: rbac CLI [DET-7868] 

master/internal/api_user_intg_test.go, master/internal/api_workspace.go, master/internal/api_workspace_intg_test.go, master/internal/rbac/api_rbac.go, master/internal/rbac/api_rbac_stub.go, master/internal/rbac/api_rbac_wrapper.go, master/pkg/model/workspace.go, master/static/srv/insert_workspace.sql
Converts ```PostWorkspace``` to bun so we can share a transaction with EE adding the user role and adds ```AssignWorkspaceAdminToUserTx``` as a plugin metod to APIServer which is a no-op in oss.
Integration test to make sure we didn't break existing behavior.
=> chore: oss refactor for auto assign WorkspaceCreator role plugin

docs/release-notes/5123-tb-secrets.txt, e2e_tests/tests/command/test_tensorboard.py, master/internal/api_tensorboard.go
The secrets are inherited only when the image from that experiment is also inherited.
=> fix: tensorboard inherits imagePullSecrets from experiment [DET-8458]

webui/react/src/components/Badge.module.scss, webui/react/src/components/ExperimentActionDropdown.tsx, webui/react/src/hooks/usePermissions.ts, webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss, webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx, webui/react/src/pages/ExperimentDetails/ExperimentMultiTrialTabs.tsx, webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx, webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx, webui/react/src/pages/ProjectDetails.tsx, webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx, webui/react/src/types.ts, webui/react/src/utils/experiment.ts
Permissions:
- creating an experiment (forking, continuing a trial, or starting a new hyperparameter search [ includes button in hparam tab, dropdown in multi-trial experiment trials tab ])
- editing metadata (unable to change name, description, tags, notes - exp. details and project details pages)
- modifying an experiment (archive/unarchive, pause/cancel/stop)
- viewing experiment metadata (will be handled server-side by not returning experiments to ProjectDetails)
- viewing experiment artifacts (hides Checkpoints, Code, and Logs tabs on experiment details; prevents forking or continuing a trial, downloading code or opening tensorboard, hides metrics / workloads on trial details page; arguably this may as well hide an experiment as in metadata permission)
Create your own workspace and …
=> feat: RBAC for experiment actions [DET-8372]

webui/react/src/components/Navigation.tsx, webui/react/src/services/apiConfig.ts
Removes the mock added in #5079 - instead `listRoles` only happens with RBAC on.
For OSS user - load `/det/projects/1?f_rbac=on` and see request to `roles/search` (will error out). 
Request the page *without* `f_rbac=on` and there should be no request / error from `roles/search`
=> chore: only request listRoles with rbac on [DET-8419]

.circleci/config.yml, agent/Makefile, agent/get-deps.sh, master/Makefile, master/get-deps.sh, proto/Makefile, proto/get-deps.sh
Despite the caching that was in place previously, the `go-get-deps` stage still took quite a while because the caching did not cover everything that `go install` touches. This change expands the caching to cover the relevant directories. It also moves the `go install` commands into separate files so that they can be accounted for in the cache key.
In my testing, this saves 60-90 seconds each time `go-get-deps` is run, which speeds up several different jobs. Meanwhile, it increases the cache size from 465 MiB to 676 MiB.
Is there some functional reason not to do this? I've thought about doing it before, but I vaguely feel like there was something that stopped me (besides, you know, time and attention).
=> ci: cache more Go files

webui/react/src/components/Markdown.stories.tsx, webui/react/src/components/Markdown.tsx, webui/react/src/components/NotesCard.tsx
As we're adding RBAC permissions, we sometimes disable NotesCard. The underlying Markdown placeholder says "Add notes..." even if no changes can be made.
This is a minor change to the NotesCard component to pass disabled attribute to Markdown, and changing the placeholder for that case.
Most Notes should stay the same. You can use the storybook or set the NotesCard component on a page to be `disabled={true}`
=> chore: Placeholder when notes/markdown is disabled [DET-8409]

master/static/srv/shell-entrypoint.sh
If a variable contains an explcit newline, det shell start fails because the sed pattern replacement to inject the environment into the ssh authorized_keys file fails with the sed error:
sed: -e expression #1, char 100: unterminated `s' command
Translate any env var value that contains a newline to \n.
Manually verified that this change enables `det shell start` succeeds with the variable `IFS="  \n"` set (that is an explicit newline) on casablanca-login2.   The value is properly maintained in the started shell.
Oddly, IFS is somehow set to `IFS="  \n"`  -- presumably by PBS.   Using Slurm on the same system does not  have this problem.
=> fix: shells fail if vars contain a newline [FOUNDENG-251]

harness/determined/launch/horovod.py, harness/determined/util.py
Apparently batch size calculation is the only reason left why zero-slot
experiments didn't work.
=> feat: support slots_per_trial=0 in Trial classes

harness/determined/launch/wrap_rank.py
Ran the "computer_vision/cifar10_pytorch" experiment on "casablanca-login2" with PBS using the dev launcher, using the experiment file shown below.
```
(base) rcorujo@C02FJ0T8MD6Q cifar10_pytorch % cat rig_distributed.yaml 
name: cifar10_pytorch_distributed
hyperparameters:
learning_rate: 1.0e-4
learning_rate_decay: 1.0e-6
layer1_dropout: 0.25
layer2_dropout: 0.25
layer3_dropout: 0.5
global_batch_size: 512 # Per-GPU batch size of 32
resources:
slots_per_trial: 12
records_per_epoch: 50000
searcher:
name: single
metric: validation_error
max_length:
epochs: 32
entrypoint: model_def:CIFARTrial
min_validation_period:
epochs: 1
environment:
- NCCL_DEBUG=DEBUG
#- NCCL_SOCKET_IFNAME=ens5np0
- NCCL_IB_DISABLE=1
- CUDA_VISIBLE_DEVICES=0,1,2,3
image:
cuda: …
```
=> fix: FOUNDENG-246 Task reports "RuntimeError: Dataset not found or corrupted"

harness/determined/cli/cli.py
While doing some testing, I realized that `PEM_cert_to_DER_cert` is only supposed to operate on one certificate, though it sometimes can work on more than one (if, say, the first ends with Base64 padding characters, or possibly if the certs up to the first one ending in padding happen to together contain a valid number of Base64 characters), which is how this didn't get caught before.
=> fix: more correctly compute TLS cert hash in CLI

e2e_tests/tests/command/test_run.py
`test-k8-mount` has been inexplicably failing recently with `context deadline exceeded`. 
The image it uses isn't supposed to matter, but after I've changed TF1 image to TF2 I can't get it to fail any more.
N/A: this is a test.
=> test: fix `test-k8-mount`.

harness/determined/cli/rbac.py
I've typed full parameters twice and my fingers got tired, so I made this.
1. login as `admin`.
2. `det rbac assign-role --username-to-assign admin ClusterAdmin`
3. `det user create creator`
4.  login as `determined`.
5. `det rbac assign-role -u creator WorkspaceCreator` -- should fail because you are logged in as a simple user.
6. `det -u admin rbac assign-role -u creator WorkspaceCreator`  -- should work, because duplicate `-u` options make sense and don't conflict.
=> feat: short options for RBAC CLI.

Makefile, webui/Makefile, webui/react/craco.config.js
allow personages to run `make local` from repo root to install and run frontend dev server against current `DET_MASTER`
to make easier for non-webs to test/try/debug things
from repo root
`make clean`
`export DET_MASTER=$YOUR_SECRET_CLUSTER`
`export HOST=hey-yall-its-conda` # this is for testing something tim encountered
`make local`
should work
support team sometimes experiences issues with the node version dependency changing.
is there a sane way to install a specific node version to be used just in the context of the determined repo without messing anything else up for the user as a part of `make get-deps`.
=> chore: ez live server

webui/react/src/hooks/useMetricNames.ts, webui/react/src/hooks/useTelemetry.ts, webui/react/src/pages/ExperimentComparison/CompareVisualization.tsx, webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx, webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx, webui/react/src/pages/InteractiveTask.tsx, webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx, webui/react/src/pages/Wait.tsx, webui/react/src/services/utils.ts, webui/react/src/shared/utils/error.ts
[WEB-502](https://determinedai.atlassian.net/browse/WEB-502)
[WEB-492](https://determinedai.atlassian.net/browse/WEB-492)
[WEB-505](https://determinedai.atlassian.net/browse/WEB-505)
[WEB-503](https://determinedai.atlassian.net/browse/WEB-503)
This PR addresses a few related issues:
- errors in streaming APIs are not caught
- object literals sent to `handleError` are ignored
- infinite loading spinners for canceled/errored experiments with no trials
to test streaming APIs errors are caught:
- `make live` against devcluster on this branch (there is debugging code to generate errors)
- filter network tab to requests that include "metric-names"
- go to experiment visualization page. 
-  refresh until you see a 500
- that means API failed when it was first called
- you should see a message on …
=> fix: streaming errors not being handled

.circleci/config.yml, .circleci/devcluster/agent-no-connection.devcluster.yaml, .circleci/devcluster/double-reattach.devcluster.yaml, .circleci/devcluster/double.devcluster.yaml, agent/internal/agent.go, agent/internal/options.go, docs/reference/reference-deploy/config/agent-config-reference.rst, e2e_tests/pytest.ini, e2e_tests/tests/cluster/managed_cluster.py, e2e_tests/tests/cluster/test_agent.py, e2e_tests/tests/conftest.py
In the latest commit, the command is configured through a new  "hooks" section in the agent config; in the intermediate one, the config is more specifically tailored to this scenario of shutting down on connection failure. The former both is more extensible and allows for nicer names in the code; I don't think I see any downside except that it may cause users to expect us to have more hooks available in the near future.
Of course, we may not want to allow the agent to run arbitrary commands on the host at all. But I feel like we need some amount of flexibility, and I couldn't think of a way I liked to have some without doing this. (Maybe just specifying arguments to be passed to `shutdown`? But maybe there's a reason to run a command other than `shutdown`. I don't really know.)
=> feat: enable configuring the agent to shut down on connection failure [DET-7022]

.circleci/config.yml
For some reason, it looks like c82be870, the change introduced by #5140, hasn't had the time-saving effect it was supposed to. The only explanation that comes to mind is that I accidentally created an incomplete cache item while testing that is now being used. Feels unlikely, but in any case here's a version bump to be sure to get away from anything like that.
=> ci: bump cache buster version

webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.tsx
[WEB-286]
- Check if files are sorted as expected 
- Check if `Code` tab (`det/experiments/<expId>/code`) is visible on Safari
https://caniuse.com/js-regexp-lookbehind
[WEB-286]: https://determinedai.atlassian.net/browse/WEB-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: avoid using lookbehind regex for Safari

webui/react/src/components/Navigation.tsx
Now that `fetchMyRoles` is called when we load Determined WebUI (#5185) , I am following the ticket to periodically request an update from the API for the relevant RBAC roles.  In this code it is every 120 seconds, but it could be adjusted. We previously implemented polling on `fetchUserSettings` every 60 seconds.
When loading the WebUI with `?f_rbac=on`, you should see an immediate request to `permissions/summary`, and a following request 120 seconds later.
=> chore: usePolling on fetchMyRoles [WEB-3]

webui/react/src/pages/Settings/GroupManagement.tsx, webui/react/src/pages/Settings/UserManagement.tsx
Tests of UserSettings and GroupSettings were calling fetchKnownRoles without RBAC responses. The error is supposed to be processed by handleError , but that's not possible during these tests.
Situation is resolved by only calling fetchKnownRoles when rbacEnabled 
Passing CI
=> fix: only call fetchKnownRoles in RBAC, closing testing issue

master/internal/authz/permission_denied_error.go
The custom `PermissionDeniedError` previously took in a `Permission` object that required overhead to build - this change makes the error take in `PermissionType` (int32) which is much more efficient and cuts unnecessary struct building.
=> fix: custom error requires permission object

master/internal/command/command.go, master/internal/rm/fair_share.go, master/internal/rm/fitting_methods.go, master/internal/rm/fitting_test.go, master/internal/rm/priority.go, master/internal/rm/scheduler_test.go, master/internal/sproto/task.go, master/internal/task/allocation.go, master/internal/trial.go
Resource aggregation has been incorrectly using the task name instead of agent label.
Also rename `Label` field to `AgentLabel` because we have so many different labels.
=> fix: correctly aggregate allocation resources by agent label.

webui/react/src/components/NavigationSideBar.tsx
If an RBAC user has no permission to view the Uncategorized workspace (aka the default workspace/project) then that option should be hidden from navigation.  Other sections should be visible.
- Visit `/det/models` and see Uncategorized in the left nav menu. With RBAC off there is no change
- Visit `/det/models?f_rbac=on` and see Uncategorized is hidden. In this setting with no permissions, it's hidden
- Visit `/det/models?f_rbac=on&f_mock_permissions_read=on` and Uncategorized reappears
=> fix: hide uncategorized from nav, when it is not available to RBAC user [WEB-509]

docs/release-notes/5087-single-file-context.txt, e2e_tests/tests/test_sdk.py, harness/determined/cli/command.py, harness/determined/cli/experiment.py, harness/determined/cli/notebook.py, harness/determined/cli/remote.py, harness/determined/cli/shell.py, harness/determined/cli/tensorboard.py, harness/determined/common/context.py, harness/determined/common/experimental/determined.py, harness/determined/experimental/client.py, harness/tests/cli/test_cli.py
This is especially useful for including just one or two files in
interactive workflows without having to create an empty context
directory and copy files into it.
This PR began life as #5087.
=> feat: support -i/--include [MLG-194]

e2e_tests/tests/experiment/experiment.py
The retry logic in experiment.py (when master is not _yet_ available) is probably obsolete since we started using `bindings` for the API call. I am removing it and looking at CI to test this hypothesis.
=> chore: No retries

webui/react/src/pages/WorkspaceDetails.tsx, webui/react/src/services/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/types.ts, webui/react/src/types.ts
PR fills in the Workspace Members tab using a request to the `GetGroupsAndUsersAssignedToWorkspace` API endpoint, represented in the code as `getWorkspaceMembers`.
Requests are not made when RBAC is not enabled.
- When viewing a workspace in OSS [not RBAC], there are no requests to `/roles/workspace/{workspace_id}`
- When viewing a workspace with RBAC flag on - `?f_rbac=on&f_mock_permissions_read=on` - you should see repeated requests to `/roles/workspace/{workspace_id}`, though in OSS these will return an error
=> fix: Load workspace members from RBAC API

master/internal/api_user.go
- address issue of display names including but not actually == "Admin"
- code changes from checking `curUser.isAdmin` to `targetUser` for the renaming
Rename user
=> fix: check target user, allow \wadmin\w names but not admin itself [WEB-529]

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceAddMember.tsx, webui/react/src/pages/WorkspaceDetails.tsx, webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.tsx, webui/react/src/services/apiConfig.ts, webui/react/src/services/types.ts
Handles two reported issues with the workspace Add Members modal form:
- Groups should be included in the list of members to add
- addRoles should assign to this specific workspace instead of globally
Breakdown of changes:
- in WorkspaceDetails.tsx, groups were all filtered out due to syntax hiding returned value (`filter((group) => { expression })` rather than `filter((group) => expression)`)
- added a group icon to the dropdown to make users and groups more distinct
- set dropdown value to g_{GroupID} or u_{UserID} so  `handleSelect` can handle user or group from ID, not name
- passed `workspaceId` to the modal to pass it on to the addUserRole / addGroupRole calls
Your database should have a group in it, otherwise:
```sql
insert into groups (group_name, roles) values ('cool group', …
```
=> fix: Workspace member modal handling of groups and roles

webui/react/src/pages/WorkspaceDetails.tsx, webui/react/src/routes/utils.ts
Bug report:
Workspace -> Members tab; hitting Ctrl-R to refresh the page sends you back to Projects tab (although the url in the browser URL bar still ends with `members`).
Navigate to workspace page with rbac enabled, click on tabs and refresh page, page should stay at where it was.
=> fix: workspace page tab route [WEB-531]

proto/Makefile
This just checks the version of protoc folks are using and outputs a message indicating that they need to upgrade.
Almost everyone hits this and is confused.
=> fix: add version check for protoc to prevent confusion

.circleci/config.yml, .circleci/devcluster/strict-ntsc.devcluster.yaml, e2e_tests/pytest.ini, e2e_tests/tests/command/test_strict_ntsc.py, e2e_tests/tests/conftest.py, harness/determined/cli/shell.py, master/internal/api.go, master/internal/api_command.go, master/internal/api_experiment_intg_test.go, master/internal/api_notebook.go, master/internal/api_shell.go, master/internal/api_tasks.go, master/internal/api_tasks_intg_test.go, master/internal/api_tensorboard.go, master/internal/api_trials_intg_test.go, master/internal/command/events.go, master/internal/config/authz_config.go, master/internal/core_task.go, master/internal/db/postgres_command.go, master/internal/experiment/authz_basic_impl.go, master/internal/experiment/authz_iface.go, master/internal/mocks/authz_experiment_iface.go, master/internal/user/service.go
- Adds a authz function ```CanAccessNTSC``` which is called to allow for enabling allowing non-admin users to view their own tasks.
- Adds a dev master config option ```_strict_ntsc_enabled``` allowing for testing of a strict task world
- Checks authz for getting experiments in tensorboard creation
- Adds an authz function for ```GetActiveTasksCount```
- E2e test covering strict NTSC
- Go integration test for authz for tensorboard creation
- Go integration test for ```GetActiveTasksCount``` authz
The second ticket is for tests around ```/proxy``` and I think this covers ensuring the proxy is authenticated. 
=> refactor: Add ability to lockdown NTSC [DET-8276, DET-7377]

webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.test.tsx, webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx, webui/react/src/hooks/useModal/Workspace/useModalWorkspaceRemoveMember.tsx, webui/react/src/pages/Settings/UserManagement.test.tsx, webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx, webui/react/src/services/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/types.ts
This PR wires up the user edit modal to the rbac API. 
1. Open the user management page on local dev
2. Click into "determined" user edit modal.
3. Add three roles to the user and click submit, confirm API calls in the web console.
4. Click into the modal and confirm the updates are reflected
5. Refresh the page.
6. Click into the user edit modal again and confirm the three roles are present
7. Remove one role and add another, submit the modal
8. Refresh, reopen the modal, and confirm the permissions are correct.
9. Open the new user modal
10. Add roles and create the new user
11. Click into the modal and confirm the form is empty again
12. Confirm the new user shows up and has the correct roles
13. Refresh and confirm the user has the roles
See [Release …
=> fix: Wire up user edit modal to rbac endpoints

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-aws/install-on-aws.rst, docs/release-notes/det-deploy-clean-orphaned.rst, harness/determined/deploy/aws/cli.py, harness/determined/deploy/aws/constants.py, harness/determined/deploy/aws/deployment_types/govcloud.py, harness/determined/deploy/aws/deployment_types/secure.py, harness/determined/deploy/aws/deployment_types/simple.py, harness/determined/deploy/aws/deployment_types/vpc.py, harness/determined/deploy/aws/templates/efs.yaml, harness/determined/deploy/aws/templates/fsx.yaml, harness/determined/deploy/aws/templates/govcloud.yaml, harness/determined/deploy/aws/templates/secure.yaml, harness/determined/deploy/aws/templates/simple.yaml, harness/determined/deploy/gcp/terraform/modules/compute/main.tf, master/internal/config/provconfig/config.go, master/internal/rm/provisioner/agent_setup.go, master/internal/rm/provisioner/agent_setup_test.go, master/internal/rm/provisioner/aws.go, master/static/srv/agent_setup_script.sh.template
This just threads through a command-line option to `det deploy aws` all the way down to adding the appropriate config entry to the agent. Since the hook is configured in a nested object in the config and has a list value, I didn't want to use another environment variable to configure it, so the provisioner config now includes a free-form JSON field that gets inserted into the agent config file.
The new arguments to `docker run` in the agent setup script are necessary to access and run `shutdown` from within the container.
Might be a bit weird to have `loss` here and `lost` in the agent config. For some reason each of those sounds the most natural to me in its own context, but I'd be willing to change either one to match the other.
=> feat: support configuring agent self-shutdown for `det deploy aws`

webui/react/src/components/InteractiveTable.tsx
when clicking between columns to begin resize, the resize shadow was positioned at the beginning of the column, instead of under the cursor
the resize shadow is positioned under the cursor
verify the above, and verify that the rest of the existing resize behavior is preserved.
=> fix: position resize shadow under cursor at start

webui/react/src/components/DeterminedAuth.tsx
Prevents an issue on OSS / latest-master, where after logging in / with incognito on, `fetchMyRoles` is called just after logging in.
=> fix: fetchMyRoles on login, only if rbac is on

master/static/migrations/20221019080320_fixup-incompatible-expconf.tx.down.sql, master/static/migrations/20221019080320_fixup-incompatible-expconf.tx.up.sql
When we changed the experiment config, because we did not have `omitempty` on the original slurm config, its presence in every full defaulted config in the database caused load failures. This migration fixes it for now. Long term we should generally load less of the expconf and come up with a general "expconf break guide".
Tested manually on a local cluster. Will be tested by old experiments loading properly on the release cluster.
We should follow up to only load the config necessary in general. Loading launch configs outside of launch is pointless.
=> fix: account for incompatible expconf change

webui/react/src/shared/components/Avatar/Avatar.module.scss, webui/react/src/shared/components/Avatar/Avatar.tsx
using dark/light text color for avatars in `noColor` mode. no changes to text color when `noColor` prop is false (remains `white`).
https://determinedai.atlassian.net/browse/DET-8237
nothing to test in core since `noColor` prop is only used in SaaS.
can test in storybook and SaaS to see that in light mode with `noColor` mode, text is dark instead of white:
=> fix: Avatar text color change (DET-8237)

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceRemoveMember.tsx, webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx, webui/react/src/services/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/types.ts
On the Workspace Members page,
- When changing the role with the dropdown, passes a `scopeWorkspaceId` param when adding/removing the role
- When removing a role with the three dots / action menu, passes a `scopeWorkspaceId` param instead of modifying a global role.
- Instead of `roleId: 0`, added a function `getAssignedRole` which gets the first relevant `role.roleId` for this member, and is compatible with the mock workspace
For consistency, changes `removeRoleFromGroup` to accept an array of roles like the users feature, so it is renamed `removeRolesFromGroup`
Go to the workspace detail page and add `?f_rbac=on&f_mock_permissions_all=on&f_mock_workspace_members=on`
- Changing a role passes `scopeWorkspaceId` to the API when removing, and then adding the new role
- Removing a role with …
=> feat: Changing and removing roles from workspace members list

master/internal/sproto/task.go
Job exited with failure will log a message at ERROR level, but the same message is also appended to ExitedEvent message that is showing at INFO level. Every job exit message is duplicated. 
On success
[2022-10-06T21:11:14.596823Z]          || INFO: Scheduling Command (truly-keen-cicada) (id: a2f367af-d75f-4675-9086-822331336ebf)
[2022-10-06T21:11:14.672017Z]          || INFO: Command (truly-keen-cicada) was assigned to an agent
[2022-10-06T21:11:32.113061Z]          || INFO: **resources exited successfully with a zero exit code**
[2022-10-06T21:11:32.129114Z]          || INFO: Command (truly-keen-cicada) was terminated: allocation stopped early after **resources exited successfully with a zero exit code**
On failure
% det command run exit 1
[2022-10-06T16:18:05.741031Z]          || INFO: …
=> fix: remove duplicate event message.

webui/react/src/pages/ExperimentList.tsx, webui/react/src/pages/OldProjectDetails.tsx
WEB-548
`useSettings` does not provide a stable reference to arrays when they are unchanged. this causes the list of tags and the list of users in the filters to be "changed" any time any of the settings are changed (e.g. row selection). 
because we call the `fetchExperiments` when tag and user filters change, this triggers a loading state in the table on row selection.
solution in this case is to stringify those lists and put them in the dependency array instead-- since react compares primitives to their previous values by value instead of reference.
Main test criteria are that:
- loading state is not triggered on row selection when any filters are applied but especially user and/or tags
- that the filters are applied correctly
See [Release …
=> fix: dont trigger loading state on experiment selection

harness/determined/common/schemas/expconf/_gen.py, harness/determined/common/schemas/expconf/_v0.py, master/pkg/model/experiment_config.go, master/pkg/model/experiment_config_test.go, master/pkg/schemas/expconf/experiment_config.go, master/pkg/schemas/expconf/schema_test.go, master/pkg/schemas/zgen_schemas.go, schemas/expconf/v0/devices.json, schemas/test_cases/v0/defaults.yaml, schemas/test_cases/v0/experiment.yaml, schemas/test_cases/v0/merging.yaml
Our docs claim that resources.devices may be the equivalent strings as
one would pass to docker run --device, but that has never been true.
We like what the docs promise, so this PR adds support for exactly that.
We continue to support the map form as well, because devcies with colons
in their name (such as some pci devices) can't be passed in the --device
strings.
=> feat: actually support --device strings

master/go.mod, master/internal/api/apiutils/mask.go, master/internal/api/apiutils/mask_test.go
While reviewing #5177, I noticed some ergonomic issues working with FieldMasks and wanted to help make that easier. In particular:
- Doing repeated O(n) scans through a slice of fields to check whether fields were specified in the FieldMask is slow and verbose.
- An unspecified FieldMask, by convention, should be interpreted by the server as though all fields were specified, so a check was necessary that was easy to miss.
- FieldMask allows a request to specify an ancestor field such as `a.b` and should carry the semantics that a descendent field like `a.b.c` should be considered in the field set.
So I made a new type (with tests) that uses a map for containment checks and respects the listed FieldMask conventions.
No behavior should change as a result of this PR.
=> chore: add FieldMask type to apiutils

docs/reference/reference-interface/job-config-reference.rst, docs/reference/reference-training/experiment-config-reference.rst
Describe usage of slots_per_node for PBS & Slurm.
Builds & reads locally OK.
=> docs: slots_per_nodes for PBS & Slurm

harness/determined/common/api/bindings.py, master/internal/api_master.go, master/internal/config/config.go, proto/src/determined/api/v1/master.proto, webui/react/src/contexts/Store.tsx, webui/react/src/hooks/useFeature.test.tsx, webui/react/src/hooks/useFeature.ts, webui/react/src/services/api-ts-sdk/api.ts, webui/react/src/services/decoder.ts, webui/react/src/types.ts
Add `feature_switch` to master config, and every valid switch in the list is considered “on” for feature switching at front end.
Add `feature_switch` to master config
Verify that `/master` return with `featureSwitch`
=> feat: implement feature switch [WEB-535]

harness/determined/_trial_controller.py
flake8 started failing, saying:
initialize_wrapper is an empty method in an abstract base
class, but has no abstract decorator
=> chore: delete dead code to fix flake8

e2e_tests/tests/test_sdk.py, harness/determined/common/experimental/experiment.py, harness/determined/common/experimental/trial.py
The CLI command:
det e create const.yaml -f
can now be expressed via the Python SDK:
e = client.create_experiment()
t = e.await_first_trial()
for log in t.logs(follow=True):
print(log, end="")
I'd like to agree on the API before writing tests and landing it.
=> feat: support streaming logs in Python SDK [MLG-46]

docs/release-notes/fix-aggregation.rst, master/static/srv/update_aggregated_allocation.sql
The allocation aggregation query was designed under the assumption that everything has a start time, since that was true for trials. At some point after the query switched to using the allocations table, we added the PENDING state, within which an allocation has NULL start time.
In PostgreSQL, a NULL start or end for a range indicates that the range is unbounded in that direction, so an allocation that is in PENDING when an aggregation runs registers as having been running for the whole day of the aggregation. We should just ignore those instead.
The case of NULL end time should already be handled, since that has always been a possibility.
=> fix: exclude allocations without start times from aggregation

master/pkg/ptrs/ptrs.go
Inside the function, the value is already addressable now that it has a name, so declaring a new variable to take the address of isn't necessary.
=> chore: simplify `ptrs.Ptr`

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceAddMember.tsx, webui/react/src/pages/WorkspaceDetails.tsx, webui/react/src/pages/WorkspaceDetails/RoleRenderer.module.scss, webui/react/src/pages/WorkspaceDetails/RoleRenderer.tsx, webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.tsx, webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.module.scss, webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx, webui/react/src/services/api.ts, webui/react/src/services/apiConfig.ts, webui/react/src/services/types.ts, webui/react/src/utils/user.ts
fix: add and edit workspace member UI [WEB-552]
The ability to add and edit roles was fixed in https://github.com/determined-ai/determined/pull/5322. This PR implements two UI bug fixes. The fixes in this PR:
1. When editing roles the dropdown value would not change until the new assignments were polled. 
2. The "Add Workspace Member" modal would be slow and buggy as well as prematurely show form validation before attempting to submit the form. 
Premature form validation: 
https://user-images.githubusercontent.com/103522725/197856615-ef340736-464e-473c-87d2-50e0a90817c9.mov
Role select not updating:
https://user-images.githubusercontent.com/103522725/197856855-1d79450b-fc98-4539-b90b-1df0f0f5073e.mov
- Setup a determined-ee environment. 
- Log in and create a workspace. 
- Click the "Add …
=> fix: add and edit workspace member UI [WEB-552]

master/internal/sproto/task.go, master/internal/task/allocation.go
This change will fix logging the same exit error message at the INFO level as well as at the ERROR level. In addition, this fix cherry-picked a change made for FOUNDENG-260 from https://github.com/determined-ai/determined-ee/pull/463.
With this change:
% det command run exit 0
[2022-10-24T16:12:58.439433Z]          || INFO: Scheduling Command (needlessly-included-thrush) (id: 9765c6e7-d221-464f-81da-f8b6e3c17302)
[2022-10-24T16:12:58.580698Z]          || INFO: Command (needlessly-included-thrush) was assigned to an agent
[2022-10-24T16:13:19.466281Z]          || INFO: resources exited successfully with a zero exit code
[2022-10-24T16:13:19.508887Z]          || INFO: Command (needlessly-included-thrush) was terminated: allocation stopped early after resources exited successfully with a …
=> fix: duplicated messages logged at INFO and ERROR levels.

webui/react/src/pages/WorkspaceList.module.scss, webui/react/src/pages/WorkspaceList.tsx
There are two places where a user can create a workspace:
- a small + button in the left nav
- a 'New Workspace' button in the top right of `/det/workspaces`
I'm interpreting WEB-553 as: the button on `/det/workspaces` should be visible, disabled, and have a title text. (we cannot use an `antd.Tooltip` on a disabled component per https://github.com/ant-design/ant-design/issues/27118 ).
I still hide the + button because when disabled, it's very visible and more confusing (screenshot)
On `/det/workspaces`,
- click the + button on the left nav to open a New Workspace modal
- click the 'New Workspace' button on the top right to open the New Workspace modal
With `/det/workspaces?f_rbac=on`, or with a user missing create workspace permission
- the + button on nav is hidden
- 'New Workspace' …
=> feat: when user can't create workspaces, show a disabled button [WEB-553]

agent/.goreleaser.yml, helm/.goreleaser.yml, master/.goreleaser.yml
Add a header with a link to the release notes in the released tag.  This seems the simplest way to get the relase notes linked in without having to make sure they're generated at the time the release is created.
The intended result is manually created at https://github.com/determined-ai/determined/releases/tag/0.19.5
Make a release and see if it works.  Fix it if not. :shrug:
I'm not sure if the `##Changelog` is auto-inserted or not; that may need added in a second revision.
=> ci: add release notes header with link [INFENG-115]

agent/Makefile, helm/Makefile, master/Makefile
The agent and helm releases were failing to get the previous tag completely (we don't use a `v` prefix any longer) Also adjust the grep to include only what we want instead of excluding known unwanted tags.  The previous tag functionality doesn't make much of a difference, but the exclusion was brittle; any new tag which happened to get added would break the exclusion logic.
~Marking as draft since there's a conflicting helm Makefile update in-flight; this will need updated to reflect that change.~
Run shell commands in a shell and confirm expected behavior.  Pay attention on next release to make sure things actually work as planned. :)
It's tough to suppress my urge to also convert the `grep "$VERSION" -A1 | sed -n '2 p'` into just `sed -n "/$VERSION/{n;p;}"`, and it's a real bummer that …
=> ci: fix "previous tag" logic

webui/react/src/components/DeterminedAuth.tsx, webui/react/src/declarations.d.ts, webui/react/src/globalStorage.ts, webui/react/src/hooks/useSettings.test.tsx, webui/react/src/hooks/useSettings.ts, webui/react/src/hooks/useStorage.ts, webui/react/src/react-app-env.d.ts, webui/react/src/shared/configs/tsconfig.json, webui/react/src/shared/utils/storage.test.ts, webui/react/src/shared/utils/storage.ts
Turns off `skipLibCheck` in tsconfig.json, then updates our other configs to newest standards.
The biggest non-config changes are around localStorage. We've been creating our own 'Store' type and 'Storage' class instead of the native localStorage's 'Storage' type. To avoid confusion, I'm removing the 'Store' type and renaming our class to 'StorageManager'.
We need two new attributes on MemoryStore for compatibility with localStorage's Storage type. This class is used only by tests, and never these functions (as they were not previously available).
**Note: does this take an excessive amount of time to build?**
Builds successfully, passes tests
=> chore: Enable library checks for TypeScript; update types [WEB-191]

e2e_tests/tests/cluster/test_users.py, master/.golangci.yml, master/internal/api_user.go
Username / display name regex wasn't approving perfectly ascii dashes in usernames on patches. In this change,
- Change regex to allow all printable ascii characters.
- Start validating these fields on user creation as well.
- Change golang linter settings to stop enforcing variable shadowing for `err` and `ctx` because that's how idiomatic go works.
=> fix: validate username and display name in `PostUser`.

agent/Makefile, helm/Makefile, master/Makefile
The `$` was being interpreted as an escape character, causing the following quote to not get sent to the shell.
Also, `egrep` has been deprecated since 2007 and now emits a warning when used [1], so switch to `grep -E`.
[1] https://git.savannah.gnu.org/cgit/grep.git/commit/?id=a9515624709865d480e3142fd959bccd1c9372d1
Has the old version been known to work, or was it changed after the last time it was actually used?
=> fix: improve previous tag logic

master/internal/config/resource_manager_config.go, master/internal/rm/kubernetes/pods.go, master/internal/rm/kubernetes_resource_manager.go, tools/k8s/README.md, tools/k8s/devcluster.yaml, tools/k8s/fetch-creds.sh, tools/k8s/my-service-account.yaml
See the [README in the PR](https://github.com/rb-determined-ai/determined/blob/local-k8s/tools/k8s/README.md) for more info.
* Adding dev flags to the master isn't strictly necessary, but it does make rebuilding and rerunning fast and easy.
* There are authentication plugins that you can use, which would make `fetch-creds.sh` unnecessary.  Basically, if `kubectl` can be configured to authenticate, so can any piece of go code.  I didn't pick that strategy for two reasons:
* It is less flexible.  `fetch-creds.sh` works on unmodified k8s apps as well (as demonstrated with the coscheduler in this pr)
* The auth plugins get compiled into the application, and are not guaranteed to work across versions.  `fetch-creds.sh` lets `kubectl` figure out the auth plugins and just uses the end-state …
=> chore: support out-of-k8s dev workflow [DET-8107]

harness/determined/tensorboard/metric_writers/pytorch.py, harness/tests/tensorboard/test_torch_writer.py
https://determinedai.atlassian.net/browse/MLG-191
https://determinedai.atlassian.net/browse/MLG-196
We have waited a long time to make TorchWriter behave the same way TFWriter does: `reset()` closes the underlying file writers. Next attempt to write will reopen them automatically (which is why `torch.SummaryWriter` does not have a `reopen` method.)
=> fix: TorchWriter.reset closes a file

webui/react/src/shared/utils/storage.ts
saas can't build unless we specify these params as strings, not any
I believe this is more related to type checking, and not the changes to Storage. These lines were written 4 months ago: https://github.com/determined-ai/determined/blame/master/webui/react/src/shared/utils/storage.ts#L89
I tried `make push-shared` but there is a saas check which fails because saas is still on the old version of shared:
```
./src/experimental/notifications/storage.ts
Attempted import error: 'Storage' is not exported from 'shared/utils/storage'.
```
I could disable checks on `make push-shared` but I don't know if that's what we want to do.
Successfully builds
=> fix: typescript inside keys function

e2e_tests/tests/cluster/test_workspace_org.py, harness/determined/cli/workspace.py
Allows ```--checkpoint-storage-config-file``` to also support yaml in addition to json.
Create file ```test.yaml``` with 
```
type: shared_fs
host_path: /tmp/test
```
And you should see the checkpoint storage set in output of following two commands
```
det w create test --checkpoint-storage-config-file=test.yaml
det w edit test --checkpoint-storage-config-file=test.yaml
```
=> chore: cli allow workspace --checkpoint-storage-config-file to use yaml

webui/react/src/App.tsx, webui/react/src/components/Navigation.tsx, webui/react/src/components/NavigationSideBar.tsx, webui/react/src/components/NavigationTabbar.tsx, webui/react/src/components/ResourcePoolCard.test.tsx, webui/react/src/components/ResourcePoolCard.tsx, webui/react/src/contexts/Store.tsx, webui/react/src/hooks/useFetch.ts, webui/react/src/pages/Cluster/ClusterOverallBar.tsx, webui/react/src/pages/Cluster/ClusterOverallStats.tsx, webui/react/src/pages/Clusters.tsx, webui/react/src/pages/Clusters/ClustersOverview.tsx, webui/react/src/pages/ResourcepoolDetail.tsx, webui/react/src/stores/agents.tsx, webui/react/src/utils/loadable.ts
This is a PR @trentwatt and I put together. It does two things:
1. Split out Agents from the `Store` context. This is how we want to go about breaking up the Store context so that we can eventually switch to a more flexible way of managing global data.
2. Introduces a Loadable data type to manage loading states. Currently we're pretty bad at handling loading states and often just temporarily display incorrect data while loading. This will make it easier to implement loading states going forward and see where they're missing now.
1. Visit the cluster overview page, confirm it matches latest-master (there are some features here I don't see in latest master if people have ideas on how to test them).
2. Confirm the navbar matches latest-master
4. Confirm the resource pool detail page matches …
=> chore: Move Agents into their own context, introduce Loadable abstraction

master/internal/core.go, master/internal/user/service.go
On tip of master redirect seems to not work after #4996
we should fix that before release since we tell people to go to their cluster address in the quick start guide. 
To reproduce open a private browser and clear cache and go to ```127.0.0.1:8080``` in a browser and ```Unauthorized``` should be the response on latest master and you should be at the login page with this fix
=> fix: redirect url to login page

master/static/srv/ssh_config
On HPTC clusters with Singularity the default is to mount the users home directory into the container and add clone the host passwd entry for the user. This means that by default ssh will write keys to the users ~/.ssh/known_hosts file. As these keys are Determined-generated per trial, they change which leads to warnings about potentially hijacked nodes.
This change to the ssh_config will prevent writing these private Determined keys to the existing known_hosts file which will avoid these warning messages in the experiment log after multiple runs.
Validated ~/.ssh/known_hosts is no longer updated when running a determined trail with singularity.
=> fix: Avoid writing to users known_hosts [FOUNDENG-314]

webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.module.scss
When RBAC is enabled, the workspace header has an additional button (Add Members) which crowds the header, especially on mobile view (ticket discusses Pixel 5 in particular).
I add a media query css here to shift the Add Members and New Project buttons below the name / pinning UI
The minimum breakpoint is about 600-650px, which I then compared to our existing media queries and used the nearby tablet breakpoint (768px).
- Start an instance with RBAC / EE enabled
- Visit a workspace details page
- Use the browser tools to view in mobile view
=> fix: Workspace header in mobile view [WEB-633]

webui/react/src/pages/Settings/Settings.tsx
A bug was reported that InteractiveTableSettings are kept when switching between User Settings and Group Settings tabs. You could move from User Settings with `tableOffset=20` to a blank Group Settings page because there aren't enough groups for a 3rd page.
This might be fixable with storagePath in useSettings, but because changes there could cause other problems, it may be cleaner to clear InteractiveTableSettings when switching tabs.
- Visit `/det/settings/account` on an admin/EE system or with `?f_rbac=on&f_mock_permissions_all=on`
- Click to User Settings tab, and see a table of users. If there is less than one page of users, add users or lower page limit
- Click to additional pages of users and observe the URL includes `tableOffset=10`
- Click to Group Settings tab and observe the …
=> fix: Clear table settings between users and groups pages [WEB-636]

master/internal/core_task.go
Fixes [DET-8650].
- Turn on RBAC
- Create at least one experiment
- Create a Tensorboard
- Run `det -u admin task list` and make sure there's no panic
- Make some unprivileged user like `det -u admin user create foo` then `det -u foo task list` and make sure there's still no panic
[DET-8650]: https://determinedai.atlassian.net/browse/DET-8650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: avoid panic in getTasks

webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
In the Multi-Trial Experiment's Parallel Coordinates visualization, double-clicking the chart should reset all filters. Listen for the distinct onReset event.
Also improves a variable name here
- Create or fork a multi-trial experiment.
- While the experiment is running (new data streaming into the chart), drag the mouse along axes to create filters. As the chart updates with more data, the filters should remain ( #5243 )
- Double-clicking the chart somewhere other than the pink highlight (on the axis, background, etc.) should remove all filters at once.
- Filters should be totally removed and not return when chart updates with new data
=> fix: listen for onReset for ParallelCoordinates filters

master/internal/core.go, webui/react/package-lock.json, webui/react/package.json, webui/react/public/index.html, webui/react/src/shared/configs/craco.config.js
A Content Security Policy (CSP, https://content-security-policy.com/ ) limits what scripts, styles, images, etc. are loaded by the browser. Even if a malicious user manages to add a script or iframe, they won't be run. The CSP can be set in the server's response headers, or an HTML meta tag. 
Notes:
- I initially put the CSP on the server (master/internal/core.go) - but we use two inline `<script>` tags which are sent by a hash or a one-time nonce. Webpack dynamically adds a script, so we need their plugin for this (Slack's csp-html-webpack-plugin)
- script-src is used, includes the two webpack scripts and an analytics domain (segment)
- style-src allows unsafe-inline (like `style="color: red"`) because we use it, and monaco markdown editor and other component dependencies use it
- …
=> chore: Add content-security-policy via meta tag, webpack plugin [WEB-310]

docs/release-notes/exp-notes-fix.rst, master/static/migrations/20221115135515_notes-not-null.tx.down.sql, master/static/migrations/20221115135515_notes-not-null.tx.up.sql
Experiment with null notes can't load. This change makes notes always not null and treats "" as no notes. 
On a release cluster just find an old experiment (like experiment ID 146 on gcloud) and try to create a tensorboard and verify you don't get a 500 error. 
Locally create an experiment pre this change, then set experiment notes to NULL with ```UPDATE experiments SET notes = NULL``` then verify after this commit you can open a tensorboard of the experiment. 
=> fix: experiment with null notes can't load [DET-8572]

harness/determined/common/api/bindings.py, harness/determined/exec/prep_container.py, master/internal/api_trials.go, master/internal/rm/actor_resource_manager.go, master/internal/rm/agent_resource_manager.go, master/internal/rm/kubernetes_resource_manager.go, master/internal/rm/resource_manager_iface.go, master/internal/sproto/task.go, master/static/srv/task-logging-setup.sh, proto/src/determined/api/v1/api.proto, proto/src/determined/api/v1/trial.proto, webui/react/src/services/api-ts-sdk/api.ts
Note: These are the changes for the OSS side.  The changes for the EE side (i.e., "dispatcher_*.go") needed for the "launcher" will be made on the EE branch.
The launcher reports as state of "Running" when Slurm/PBS start the job.  However, from the Determined Master's perspective, the experiment is not really running until the Determined startup scripts are running in the container.  In the case where Slurm/PBS start the job, but Singularity/Podman need to pull the image from the Internet, Determined needs to report a state of "PULLING", even if the launcher is reporting a state of "RUNNING".  Not until all containers are running should Determined report RUNNING.
With these changes, Determined will report a state of "PULLING" until all containers notify the master that they are running. …
=> chore: FOUNDENG-296 Determined shows PULLING state while container is spinning up

harness/determined/_info.py, harness/determined/core/_context.py
* UseDummyPreemptContext in non-trial tasks.
* Fabricate RendezvousInfo in non-trial tasks.
=> feat: enable limited core api usage in NTSC

webui/react/src/shared/configs/craco.config.js
Continuing to resolve issues with Content-Security-Policy - this allows Jupyter notebooks to appear again by changing the frame-src security policy to 'self' (iframes allowed on same web domain and port)
We need to test some more interactive Jupyter notebooks before merging; we may need to allow more third-party scripts on notebook pages? But the CSP may be applied only on pages from Determined, and not on Jupyter.
Launch a Jupyter notebook and wait for it to open correctly. Run a script.
Kudos to @trentwatt for noticing that this issue would come up
=> fix: Jupyter notebook iframes

agent/pkg/docker/docker.go, agent/pkg/docker/docker_api_test.go, agent/pkg/docker/docker_credential_store.go, agent/pkg/docker/docker_test.go, agent/pkg/docker/events.go, agent/pkg/docker/pull_log_formatter.go, agent/pkg/events/types.go
I've taken a lot of care to pull stuff like `aproto.MasterMessage` and `cproto.ID`'s out of this interface. I figured the better, more encapsulated our interfaces, the easier stuff would get to test, and to extend and reuse. So far I feel validated.
I also took a lot of care to design the concurrent parts of the API in a way that is the most user friendly; APIs mostly take channels instead of returning them, to let users control back pressure and reuse channels in their code without much fuss, some APIs return channels, but only if they are returning a bounded result, and I used directional channels everywhere, etc. Probably the most important is it is as un-concurrent as possible so it feels as much like "normal code" as possible.
Order to review this set of PRs:
* [refactor: rewrite …
=> refactor: rewrite docker lib without actors [DET-8300]

webui/react/src/components/Table/InteractiveTable.tsx, webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx, webui/react/src/pages/ExperimentList.tsx, webui/react/src/pages/ModelDetails.tsx, webui/react/src/pages/ModelRegistry.tsx, webui/react/src/pages/OldProjectDetails.tsx, webui/react/src/pages/TaskList.tsx, webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx, webui/react/src/pages/WebhookList.tsx
This fixes an issue with the experiment listing page where it would constantly swap between two states when on the last page of the listing if you switched the amount displayed per page.
1. Go to http://localhost:3000/projects/1/experiments
2. Change the page size to 100
3. Confirm there is now only one page
4. Change the page size to 50
5. Confirm there are now two pages and the app is not caught in a state update loop
6. Click on the 3rd page button, confirm it goes to the third page
7. Click on the first page button, confirm it goes to the first page
WEB-669
=> fix: Experiment listing should not have spurious state triggers

master/test/integration/api/api_trials_test.go
There was a chance this code could `math.Round` up to invalid nanos for a `timestamppb.Timestamps`. By my rough math, this should've been a 1 in 100 chance or something, it is one of two flakes that I saw recently.
🤷 
=> ci: fix rounding that created invalid timestamppb.Timestamps

master/static/srv/shell-entrypoint.sh
When a shell is launched for an HPC job the permissions sometimes enable other read which will cause sshd to not use the file for authorization which results in a ssh login permission.
Manually verified on PBS/Slum launches.
=> fix: Ensure authorized_keys permisison [FOUNDENG-342]

webui/react/src/App.tsx, webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx, webui/react/src/pages/ExperimentDetails/ExperimentDetails.test.tsx, webui/react/src/stores/agents.tsx, webui/react/src/stores/index.tsx, webui/react/src/stores/workspaces.tsx
This adds a new store for workspaces. Currently we make a request for workspaces for every row on the experiments page leading to significant lag. This reduces it to only on total (and only if they're not already loaded).
1. Load the uncategorized page
2. Confirm only one request for workspaces is made
3. Change the table sort order
4. Confirm that no calls are made for workspaces
WEB-674
=> chore: Move workspaces to their own store [WEB-674]

master/internal/config/provconfig/config.go, master/internal/config/provconfig/config_test.go
See design note: [here](https://connect.us.cray.com/confluence/display/AT/Design+Note%3A+Allow+Specification+of+Slurm+Gres)
Allow for configuration of HPS resource pool providers in the master .yaml, for example:
```
resource_manager:
…
resource_pools:
- pool_name: pool1
description: the description
- pool_name: tesla_gpu_q
description: Where the GPUs are
provider:             
type: hpc
partition: gpu_q
```
More testing will be done in the EE repo.
=> chore: configure HPC resource pool providers

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst, docs/reference/reference-deploy/config/master-config-reference.rst
Add user doc for default_aux_resource_pool and default_compute_resource_pool.
and
Using the same phrasing from the Agent version of this setting:
=> docs: Slurm/PBS override of default resource pools

master/internal/rm/agentrm/provisioner/aws.go
Problem:
1. scale decider assumes agent id is instance id for the purpose of detecting "disconnected" instances.
2. with imdsv2, `ec2metadata --instance-id` helper does not work, so agent id has defaulted to random container id.
3. this has caused the scale decider to erroneously terminate the instances.
4. this wreaked havoc on nightlies (or any other tasks which need the instances to live more than 15 minutes.
Solution: fetch instance id using the imdsv2-recommended incantation.
Run a ~30 minute experiment on aws cluster; the agents shouldn't spontaneously terminate mid-way.
Nightlies should work.
=> fix: aws instance id under IMDSv2.

harness/determined/cli/user.py, harness/determined/common/api/authentication.py, harness/determined/common/experimental/determined.py, harness/determined/experimental/client.py
fix: cli and sdk logout works without login
The logout logic just can't be squeezed into looking like the login
logic, just like the login logic can't be squeezed into looking like a
normal authorized request.
So just as there is a special authentication function for do_login(),
add a speciation authentication function for logout().
Co-authored-by: nrajanee <nikita.rajaneesh@hpe.com>
=> fix: cli and sdk logout works without login

e2e_tests/tests/cluster/test_workspace_org.py
Adding this fix to ensure that determined credentials are set correctly. Ideally, wherever they were changed it would be set back to default but it's tough to figure out where so just doing this for now. 
=> ci: fix test_workspace_org

harness/determined/common/api/experiment.py, harness/determined/experimental/client.py
One issue here was accidentally adding a private module into a public namespace.
Of course, since it's a file-level module, we don't have the world's best namespace hygiene anyway, but at least the other symbols in the `client` namespace are all stdlib symbols.
The other thing here is a mypy fix.  Not sure why our ci didn't catch it, but I see it locally.
=> chore: minor fixups

docs/release-notes/k8s-dont-set-exit-code-to-ones-people-think-oom.rst, master/internal/rm/kubernetesrm/pod.go
Previously when we can't find an exit status for a pod we would give 137. While technically semantically correct googling exit status 137 k8s could be confusing causing people to think the pod was OOM killed. This change uses 1025 and includes a message explaining we can't find the pod exit code.
On a k8s cluster
Run a command with an image not pulled yet
```
det cmd run --config="environment.image=determinedai/environments:cuda-10.2-pytorch-1.7-tf-1.15-gpu-mpi-0.19.4" sleep 100
```
Kill pod
```
kubectl get pods
kubectl delete pod $pod
```
Verify ```det cmd``` output shows this message
```
2bf0948d-149a-446e-8654-612eaf724802 | determined | Command (formally-united-gorilla) | TERMINATED | resources failed with non-zero exit code: unable to get exit code or exit message from pod (exit code …
```
=> chore: changes k8s unable to find exit status from 137 -> 1025 [DET-8717]

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst
Add more details based upon review feedback.
=> docs: Document PBS CUDA_VISIBLE_DEVICES requirement [FOUNDENG-359]

e2e_tests/tests/experiment/test_custom_searcher.py
Nightly tests typically start experiments through `det -m master_url e create ...` where master url is created based on values on MASTER_HOST and MASTER_PORT. Custom Searcher is using DET_MASTER env variable, and since it is not set, it defaults to localhost:8080 and fails since master is not there. 
Solution: in nightly custom searcher test, use client.login(master_url) to create a singleton object connecting to the master that will be re-used later. At the end of the test,  set the singleton to None to make sure other tests will not use the same objects again.
=> fix: nightly test for custom searcher

examples/graphs/proteins_pytorch_geometric/startup-hook.sh
pytorch geometric repo was missing wheels for latest `torch_scatter` and `torch_sparse` for our older pytorch and cuda. this caused `pip install` to build these from source which takes a ton of time, and sometimes makes the test timeout.
pin these packages to the last prebuilt wheel version.
- Nightlies are less flaky.
=> test: speed up nightly `test_protein_pytorch_geometric`.

e2e_tests/tests/api_utils.py, e2e_tests/tests/cluster/test_checkpoints.py, e2e_tests/tests/cluster/test_logging.py, e2e_tests/tests/cluster/test_trial_collections.py, e2e_tests/tests/cluster/test_users.py, e2e_tests/tests/cluster/test_users_experiment_api.py, e2e_tests/tests/cluster/test_workspace_org.py, e2e_tests/tests/cluster/utils.py, e2e_tests/tests/command/command.py, e2e_tests/tests/command/test_strict_ntsc.py, e2e_tests/tests/experiment/experiment.py, e2e_tests/tests/experiment/test_metrics.py, e2e_tests/tests/experiment/test_profiling.py, e2e_tests/tests/nightly/compute_stats.py, harness/determined/common/api/authentication.py, harness/determined/common/experimental/determined.py, harness/tests/cli/test_auth.py, harness/tests/cli/test_experiment.py
try_reauth was literally always true, except:
- in a unit test to make sure it worked when it was False
- in logout code, which recently was refactored to not use Authentication at all
Furthermore, try_reauth does not make sense to expose to end users.  At first glance, it sounds like the equivalent of a --noninteractive commandline flag for batch scripts, but that's only part of what it does.  try_auth=False has the additional effect that we would not attempt to log in with the default credentials.  So if we want to give users a noninteractive setting, that's fine, but it also isn't what try_reauth does currently.
There's no new codepaths, so nothing to test.
=> chore: delete try_reauth from authentication logic

webui/react/src/contexts/Store.tsx, webui/react/src/hooks/useFetch.ts, webui/react/src/pages/Cluster/ClusterOverallStats.test.tsx, webui/react/src/pages/Cluster/ClusterOverallStats.tsx, webui/react/src/pages/Clusters/ClustersOverview.tsx, webui/react/src/stores/experiments.tsx, webui/react/src/stores/index.tsx, webui/react/src/stores/tasks.tsx
As part of breaking parts out of the central Store, this covers the active experiment and active tasks counts. These are used only on the Clusters page, but the experiment store should be OK for future queries.
Results of experiment queries are stored in the Immutable Map with the key generated by `encodeArgs`. This function uses an `any` type so we could put it in utils or shared or something for other stores.
Notes:
- Moves the code which polls the API from `pages/Clusters/ClustersOverview.tsx` to the same file which uses the data from the store `pages/Cluster/ClusterOverallStats.tsx`
- Why limit=-2 ? In `proto/src/determined/api/v1/experiment.proto` GetExperimentsRequest clarifies that limit=0 is the default page, limit=-1 is all results, so -2 is the first option which returns …
=> chore: Moving active experiment and task queries to separate stores [WEB-581] [WEB-582]

master/internal/api_command.go
for launcher-provided resource pools
Running a command:
det command run --config=resources.resource_pool='defq_GPU_tesla' hostname
In api_command.go, the resource pool gets set up at line 116, but is overwritten by deserializing from the configBytes at line 134. This causes the result of ResolveResourcePool from line 88 to be lost.
To deal with this I propose to move lines 115 & 116 to after line 134. Does that sound plausible?
=> chore: Update resource pool resolution & validation

harness/determined/common/util.py
We have some code that handles multiple versions of urllib3, but mypy always complains about one version or the other.
CI has been passing, but I've been seeing false positives on my machine.
This approach should work in both cases.
=> chore: fix mypy false positive

master/internal/sproto/task_actor.go
When manually sending an ContainerLog event to the Allocation, the Level field is ignored and resets to nil.   Propagate the Level field to the task.Event so that the caller has control over the Level.
=> fix: ContainerLog.ToEvent honors Level [FOUNDENG-370]

agent/internal/fluent/fluent.go, agent/internal/fluent/fluent_api_test.go, agent/internal/options/options.go, agent/test/testutils/fixtures.go, agent/test/testutils/log_hook.go
The primary goal of the PR is refactoring the actor-based Fluent daemon manager away from the actor system. Secondary goals, similar to other PRs in this set, are to decouple the interface from other packages (less leaky abstractions) and increase test coverage. There is still one offender w.r.t that: `Options`/`MasterSetAgentOptions` passed everywhere, but I decided this wasn't worth refactoring.
Blocked on #5384 
Order to review this set of PRs:
* [refactor: rewrite websocket lib without actors DET-8299](https://github.com/determined-ai/determined/pull/5382)
* [refactor: rewrite our docker lib without actors DET-8300](https://github.com/determined-ai/determined/pull/4943)
* [refactor: rewrite container lib without actors](https://github.com/determined-ai/determined/pull/5384)
* …
=> refactor: rewrite fluent lib without actors [DET-8303]

harness/determined/common/api/bindings.py, master/internal/api_trials.go, master/pkg/model/experiment.go, master/pkg/model/task.go, proto/src/determined/api/v1/task.proto, proto/src/determined/api/v1/trial.proto, webui/react/src/services/api-ts-sdk/api.ts
Should finally resolve [DET-7103] by adding more fields to the task and trial log endpoints. For now, this leaves (but deprecates) the `message` field to give applications time to migrate from it to composing their own message.
`/api/v1/tasks/{id}/logs` and `/api/v1/trials/{id}/logs` should now have new fields. I used the Swagger page to verify this.
[DET-7103]: https://determinedai.atlassian.net/browse/DET-7103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add structured task and trial logs

harness/determined/exec/prep_container.py
When unable to communicate with the master, trial_prep issues a helpful message, but
it reported to stdout instead of stderr.   Move it to stderr such that it will be highlighted
as an ERROR on HPC clusters where it is particularly a useful message.   It also allows
the Dispatcher RM to drop the display of stdout on job initialization errors.
=> fix: Report incorrect configuration message to stderr [FOUNDENG-370]

tools/k8s/fetch-creds.sh
While kind directly returns an encoded certificate with the key "client-certificate-data", minikube (at least in my testing) returns a path to a file with the key "client-certificate". Now the script handles both.
=> chore: update Kubernetes fetch-creds.sh to handle cert file path

.circleci/config.yml
Kubectl update has deprecated the previous gcloud auth plugin. The new plugin requires direct installation on the system for kubectl to auth against gke clusters. This commit adds a step to install the new plugin during gke cluster provisioning.
Run CI for the PR and see if gke e2e tests work fine.
=> ci(circle-ci): install gke auth plugin

webui/react/src/App.tsx, webui/react/src/stores/users.tsx
This is a bug with the UserSettings page which I think was mis-identified as an issue with admin/determined users (which do have restricted usernames).
- When logging into the app, we call `updateCurrentUser` with the login user, and you can visit `/det/settings/account`
- When refreshing the app or loading a new tab while signed in, `updateCurrentUser` is never called, so `/det/settings/account` shows U for Undefined / Unloaded.
This PR adds `useEnsureCurrentUserFetched` to the user store and calls it on the App.tsx level.
Other changes:
- fixed an array fn which was always true: `findIndex((user) => user.id === user.id)`
- `updateCurrentUser` was renamed to `updateContextUser` inside of a function to create a new callback named `updateCurrentUser` and I would rather avoid this
- Open …
=> fix: Ensure current user available for new username / display name [WEB-724]

master/internal/user/service.go
Open a docs link while unauthenticated (e.g. from incognito mode).
=> fix: docs should not require user auth. [DET-8744]

harness/determined/exec/gc_checkpoints.py
If a checkpoint/tensorboard does not exist (due to manual delete, change in configuration, etc), do not fail the GC if the checkpoint or tensorboard is already gone.
On HPC development systems we commonly see the case where a checkpoint may not exist, this prevent the experiment from ever being deleted because the GC task will fail if it cannot successfully delete all checkpoints.
Handle the errors.CheckpointNotFound exception, and just log as a warn and treat as a success.
Validated manually that test_noop_hpc can now run successfully and cleanup checkpoints without any errors in the task.
Validated  deletion of experiments that previously would go to DELETE_FAILED state.
This is a general improvement that alleviates the symptom of duplicated checkpoint id in the DB that sometimes occurs …
=> fix: Do not fail gc of already deleted checkpoints [FOUNDENG-387]

webui/react/src/pages/Cluster/ClusterOverallStats.test.tsx, webui/react/src/pages/Cluster/ClusterOverallStats.tsx, webui/react/src/stores/userRoles.tsx
Given that the Active Tasks API does not return results unless you have the administrateUser permission, we want to remove the Active Experiments, Commands / Shells / Notebooks / Tensorboards badges unless you are able to see results.
With `?f_rbac=on` ,
Log in as 'admin' and see numbers for Active Experiments and Commands load on `/det/clusters` (can be 0s, just no spinners or missing badge)
Log in as 'determined' and these numbers should be hidden (no label or spinner for Active Experiments)
=> fix: hide Active Command UI unless it can be populated from API

webui/react/src/pages/OldProjectDetails.tsx
When selecting multiple experiments and commanding TensorBoard to open, this should continue to work on the OldProjectDetails page.  An issue with the exact object was camouflaged by `as CommandTask`; we instead receive a CommandResponse object which should be passed to a different function (`openCommandResponse`)
Checked that all other TensorBoard calls receive the CommandResponse object and pass it to openCommandResponse
- On a project view, use the checkbox to select multiple experiments
- Use the batch dropdown at left to Open TensorBoard - confirm this opens tensorboard in a new tab
- On a project view, look at an experiment row. On the right end of the row, the three-dots menu should include Open Tensorboard. Confirm this opens TensorBoard in a new tab
Fix is successful if both …
=> fix: Tensorboard launch from experiment multi-select [WEB-742]

e2e_tests/tests/cluster/test_logging.py, master/internal/api/filters.go, master/internal/api_tasks.go, master/internal/db/postgres_filters.go, master/internal/elastic/elastic_task_logs.go, webui/react/src/components/LogViewer/LogViewerFilters.test.tsx, webui/react/src/components/LogViewer/LogViewerFilters.tsx
In the log viewer filters, "No Rank" isn't available as an option because Rank is our only numeric filter. This PR represents No Rank / NULL as an option represented by -1. This won't be made available by the server, so we need to add -1 to the list of rank options on the client. 
Number or NULL needs to be searched differently on the server, so I added `FilterOperationInOrNull` to the Postgres operations
A test is included for -1 to be represented as 'No Rank'.
- Open an experiment and navigate to the Logs tab
- Confirm that a Rank filter is available and the dropdown includes 'No Rank' option
- Select the 'No Rank' option and confirm -1 is passed to API
=> feat: Include No Rank in rankIds dropdown [WEB-239] [WEB-240]

webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx
Dropdown on the WorkspaceProjects page (All/My/Others’) causes a ‘Maximum update depth exceeded’ error
Should be able to update this dropdown and see listed projects change accordingly, without the app freezing.
also updated `username` to `id` where appropriate, which was missed in https://github.com/determined-ai/determined/pull/5529.
also made `setIsLoading` calls match `WorkspaceList`. identified an outstanding bug with the loading spinners on both pages, which has been ticketed: https://determinedai.atlassian.net/browse/WEB-749
=> fix: WorkspaceProjects dropdown

.circleci/config.yml
`master/dist` contains the many individual files from the output of the docs build, which make the upload take a long time but are unnecessary to upload at all here (the docs output is uploaded from the docs build step). We really only want the packages from this step (see #4124).
=> ci: save time by only storing necessary artifacts

webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
At some point - perhaps still active - there was a scoping issue with Settings of which columns we make visible in a table. As a result, some users see a mostly blank table for a Multi-Trial Experiment's Trials.  For example you cannot see the IDs of Trials and click through to view the Trial.
After some sleuthing - we're seeing only columns which overlap with the experiments table.
We don't have a way to add or remove columns from this table, so the best fix is to show DEFAULT_COLUMNS regardless of the settings. 
On a multi-trial experiment, go to the Trials tab and confirm you can see a table listing Trial IDs, best validation metric, etc.
In one of the Trial rows, click the link to successfully view an individual trial
See [Release …
=> fix: Restore columns in experiment multi-trial view

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceAddMember.tsx, webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx
Fixes two bugs related to the Workspace Add Member modal:
- Autocomplete was not matching any users or groups now that they're more complex UI objects. In this fix, replaces `handleFilter`'s `any`-type prop with values which we expect for a User or Group item. This makes it easier to follow the function for search term -> items match
- ~Remove Member dropdown was lowercase "remove"~ fixed by #5640
- Third issue which I don't know how to solve? The members search rotates between an up and down arrow, but also changes to a search icon, so we get an upside-down search icon. On the [antd reference page](https://ant.design/components/select), this would only change to a search icon. So is this a bug with our version of antd, could CSS block the rotation..?
- Run determined-ee, with RBAC …
=> fix: Workspace members search fixes for users and groups [WEB-753]

master/internal/core.go
swagger spec at `/api/v1/api.swagger.json` has started throwing 404 after upgrade to echo v4.9.3 #5249 
Apparently we've been misusing `.Static` method to serve a single file, while `.File` is intended: https://echo.labstack.com/guide/static-files/
It used to work before by accident, and now it does not. 
Check if REST API docs work ok.
=> fix: swagger json spec 404 error.

docs/release-notes/job-submission-time.rst, e2e_tests/tests/cluster/test_master_restart.py, master/internal/command/command.go
Command start time was not getting loaded on restore. 
Experiments should already handle this correctly as far as I can tell. 
e2e test + manual 
On a cluster with a resource pool with ```agent_reattach_enabled: true``` 
run a command ```det command run sleep 100```
See the job submission time ```det job```
Restart devcluster / master
Check submission time to ensure it hasn't changed ```det job```
=> fix: correctly report command submission time on restore [DET-8750]

webui/react/src/components/LogViewer/LogViewerFilters.settings.ts, webui/react/src/pages/TaskLogs.tsx, webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
Prevents log filters (such as Level: Critical) from carrying over when viewing a new trial or task.
As recommended by Trent / #5531 , scoping the settings to the relevant object. Both trials and tasks use this component and its settings, so we need to pass their IDs. It wouldn't make sense to use Experiment ID because it could cover many trials, and we would also need to cover tasks.
Trial filters
- Open the Uncategorized Project or another project
- Open an experiment's Logs tab and select a noticeable filter (Level > Critical)
- Confirm that `level=LOG_LEVEL_CRITICAL` is added to the browser URL
- Open that browser URL in a new window and confirm Level > Critical is still applied. Close this window
Trial scoping
- Go back to the Project and select a 2nd experiment
- In the 2nd …
=> fix: Log filters scoped to trial/task [WEB-735]

docs/release-notes/allow-killing-of-cancel-trial.rst, e2e_tests/tests/experiment/test_core.py, e2e_tests/tests/fixtures/core_api/sleep.py, e2e_tests/tests/fixtures/core_api/sleep.yaml, master/internal/experiment.go
If an experiment doesn't implement preemption then it will get stuck in a stopping canceled state for an hour while being unkillable. This change allows experiments that are being canceled to be killed. 
E2e test. 
Manual 
Run an experiment without preemption implemented and wait for it to start
```
det e create e2e_tests/tests/fixtures/core_api/sleep.yaml e2e_tests/tests/fixtures/core_api -f
```
Cancel experiment running
```
det e cancel $exp_id
```
See that it is stuck in the state of ```STOPPING_CANCELED```
```
det e
```
Kill experiment
```
det e kill $exp_id
```
Verify it is now in ```CANCELED``` state
```
det e
```
=> fix: allow killing of STOPPING_CANCELED experiments [DET-8283]

webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
Revert changes to flex menu made in #5653
On the ModelVersion / details page, shrinking the window size should move any hidden buttons into a dropdown menu at the extreme top right.
=> fix: Revert change to flex menu

harness/determined/pytorch/_pytorch_trial.py
The docstring had one too many spaces of indent, causing paragraphs
within a bullet to render as block quotations.
=> chore: fix PyTorchTrial docstring

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go, master/pkg/actor/context.go
This was accidentally using `System.MustActorOf`, putting the new actor
at the root, rather than as a child of the current actor.
=> fix: put Kubernetes resource pool at right address

webui/react/src/components/NavigationSideBar.module.scss, webui/react/src/components/NavigationSideBar.tsx, webui/react/src/components/NavigationTabbar.tsx
As requested in the ticket, remove the small '+' button from Workspaces nav header, and add a more visible '+ New Workspace' button.
An unmodified + icon is too big (screenshot below) so I needed to add `iconSize` prop and some CSS.  Here's what it looks like with the + the same size as the regular nav items:
Would be open to some cleaner flexbox css or something instead of these specific css changes
- While logged into Determined, confirm a new "+ New Workspace" is added below the list of pinned workspaces.
- Click the "New Workspace" button to create a workspace.
- Check code that visibility of this button depends on `canCreateWorkspace`
=> chore: Move '+ New Workspace' button to nav item [WEB-698]

harness/determined/common/storage/azure.py, harness/determined/common/storage/gcs.py, harness/determined/common/storage/s3.py, harness/determined/common/storage/shared.py, harness/tests/storage/util.py
`os.path.relpath` removes trailing slashes for dirs. This is a problem for uploading/downloading an empty dir with selector.
For instance, if a user has a selector `lambda x: x=='empty_dir/'`  then `empty_dir/` won't be found since `os.path.relpath` removes slashes. I decided to re-append slashes to dirs in such cases.
=> fix: respect traling / for dirs

webui/react/src/pages/SignIn.tsx
Prevent an issue which was capitalizing Google and Okta, but causing issues with all-caps SSO service names
- `ssoProvider.name` is converted to a lowercase `key` to get logos, etc
- if `ssoProvider.name` === `key` (name was always all-lowercase) then continue to call `capitalize(key)`
- else (name is mixed-case or upper-case) then return unedited `ssoProvider.name`
Test on SSO with lowercase and mixed-case names
=> fix: SSO Provider name capitalization [WEB-768]

.circleci/config.yml, e2e_tests/pytest.ini, e2e_tests/tests/cluster/conftest.py, e2e_tests/tests/cluster/managed_cluster.py, e2e_tests/tests/cluster/managed_cluster_k8s.py, e2e_tests/tests/cluster/test_master_restart.py, e2e_tests/tests/conftest.py, e2e_tests/tests/requirements.txt, helm/charts/determined/templates/master-config.yaml, helm/charts/determined/values.yaml, master/internal/api_tasks.go, master/internal/api_trials.go, master/internal/command/command.go, master/internal/config/resource_manager_config.go, master/internal/rm/kubernetesrm/kubernetes_resource_manager.go, master/internal/rm/kubernetesrm/pod.go, master/internal/rm/kubernetesrm/pods.go, master/internal/rm/kubernetesrm/resource_pool.go, master/internal/rm/kubernetesrm/spec.go, master/internal/rm/resource_manager_iface.go, master/internal/sproto/task.go, master/internal/task/allocation.go, master/internal/task/errors.go, master/internal/trial.go
Fault tolerance for kubernetes master by restoring jobs upon master restart.
e2e tests
Manual test
Deploy a k8s cluster with helm chart option ```_reattachResources```
Then run jobs and delete the master pod and the deployment should create a new pod eventually and things should behave reasonably. Jobs shouldn't error or get deleted on master restart. 
=> feat: k8s restore jobs on master restart [DET-8718]

helm/charts/determined/templates/master-config.yaml, helm/charts/determined/values.yaml, master/internal/config/resource_config.go, master/internal/config/resource_manager_config.go, master/internal/rm/kubernetesrm/kubernetes_resource_manager.go, master/internal/rm/kubernetesrm/resource_pool.go
The RPs do not correspond to namespaces for the moment; this just sets up the ability to have multiple logical resource pools at all.
Some of the APIs return slightly incorrect values, since this is still pushing everything through a single pods actor, which is doing some summarization without being aware of the multiple RPs. I'm going to call that okay for this PR, since cluster behavior won't change without config changes, this is undocumented, and the plan is to do more work before the next release anyway.
Much of the new code in the RM is copied directly from the agent RM. I think it may be possible to fully unify them and move all agent/Kubernetes-specific code into the pools, seeing how both RMs are pretty much just managing the fleet of RP actors and doing some of mostly …
=> feat: allow configuring multiple RPs for Kubernetes [DET-8711]

webui/react/package-lock.json, webui/react/package.json
When building WebUI, we get warnings about the browser support dependencies. There was a recommendation to run `npx update-browserslist-db@latest`; but this command did not run successfully.
Fixes:
- installed `browserslist` as a dev dependency
- run `npx update-browserslist-db@latest` to update `caniuse-lite`. Old version from 6 months ago; new from 6 days ago.
`make live` does not show warnings about caniuse / browser list updates
=> chore: update browserslist as recommended

webui/react/src/components/Page.tsx, webui/react/src/hooks/usePermissions.ts, webui/react/src/pages/SignIn.tsx
https://determinedai.atlassian.net/browse/WEB-558
Add `loading` to `usePermissions` hook and check that value in `<Page>` component. Ignore in `<Signin>` page (won't have an authenticated user to fetch permissions).
In EE/RBAC:
=> fix: check permissions loading in Page component

docs/release-notes/cli-job-ls-resource-pool-fix.rst, harness/determined/cli/job.py
Tiny regression from #4833 not passing ```--resource-pool``` to the ```get_GetJobs```.
In a cluster with two resource pools run a command in the non default resource pool. 
```
det command run --config="resources.resource_pool=$NON_DEFAULT_POOL_NAME" sleep 1000
```
Check the job list and verify you see the command in the output.
```
det job list --resource-pool=$NON_DEFAULT_POOL_NAME
```
Could not find any easy way to add an e2e test with multiple resource pools, didn't feel worth effort to value trade off for this feature
=> fix: 'det job list' ignores the '--resource-pool' argument

webui/react/src/pages/TrialDetails/TrialDetailsOverview.settings.ts, webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
Settings to the metrics view should be remembered within an Experiment, but not carried over to other Experiments. This uses an experiment-level scope.
Clarification: Do we want metrics to be carried over between Trials of one Multi-Trial Experiment?  That's currently active with this experiment-level scope.
Single-Trial Experiment Storage
- Find a single-trial experiment (such as mnist_pytorch_const) which has successfully run twice; or run an experiment twice now for testing purposes.  We want it to be the same experiment so it has the same metric names.
- On Experiment A, above-left of the chart, select a new metric (training:loss). Confirm that the URL updates to include the selected metrics (i.e. `/det/experiments/1623/overview?metric=validation%7Cvalidation_loss&metric=training%7Clos …
=> fix: Experiment metric selection scoped to experiment [WEB-743]

webui/react/package-lock.json, webui/react/package.json, webui/react/src/pages/Settings/UserManagement.tsx
On `/det/admin/user-management`, use `DEFAULT_COLUMNS` to overwrite any previously-saved column removal/re-ordering on the User-Admin table.
Notes:
- On EE the "isAdmin" column will be missing; admin role is more complex, so it is removed before sending to the table
- The `columns` setting cannot be deleted because it is part of `InteractiveTableSettings`
- `columns` cannot be an empty array or null
- On OSS version, log in as admin
- On `/det/admin/user-management` , I should see a table of users with columns in this order: Name, Active, Admin, Modified Time, and [nameless] which contains a three-dot menu
=> fix: Pass default to overwrite Users table column preferences [WEB-760]

e2e_tests/tests/requirements.txt
The slurm gate invocations of pytest are failing with
AttributeError: module 'numpy' has no attribute 'typeDict'
due to numby>1.20 and h5py==2.10. Add dependency to force h5py>=3 in the e2e-tests requirements.txt to eliminate the error.
=> chore: Fix slurm gate tests with h5py>=3  dependency

harness/tests/experiment/pytorch/test_reducer.py
Fix to the tests so that local tests on mac will correctly skip tests that it cannot run
Default mac ulimits cause the custom_reducer (3x3) test to fail
On a Mac:
```bash
(det) ulimit -n 256
(det) make test
```
Tests should fail
```bash
(det) ulimit -n 1024
(det) make test
```
Tests should pass again
=> chore: Fix to the tests so that local tests on mac will correctly skip tests that it cannot run

docs/release-notes/stuck-on-reattach.rst, e2e_tests/tests/cluster/test_master_restart.py, master/internal/rm/agentrm/agent.go, master/internal/sproto/resources.go, master/internal/task/allocation.go
Fixing two cases where the container will get stuck.
1. Is when a container is gone on restart a task wouldn't get sent terminated due to the agent not notifying it was because ```sproto.GetResourcesContainerState``` could return an error while still knowing about the container.
2. Is when an agent is gone past its reconnect period we would never call ```agentState.restoreContainersField```  causing us to not have a containerID -> task actor to send the terminated messages.
This change also makes ```restoreError``` a transient system error.
e2e tests cover both cases
manual 
In devcluster with this config
```
resource_pools:
- pool_name: default
agent_reattach_enabled: true
```
Have an experiment that just sleeps ready, can just edit ```./examples/tutorials/core_api/0_start.py``` to be …
=> fix: tasks get stuck if container gone in reattach [DET-8828]

e2e_tests/tests/cluster/test_master_restart.py
Flaky test for ```test_master_restart_with_queued``` caused by submitting two commands at the same time and assuming the first submitted would run first.
See CI passes.
=> test: fix test flake for test_master_restart_with_queued

webui/react/src/pages/DesignKit.module.scss
https://determinedai.atlassian.net/browse/WEB-812
Make design kit page use a lower minimum width. Using the `$breakpoint-mobile` value of 480px.
On design kit page (`/det/design`), should be possible to reduce window width until the `<main>` element wrapping the `<section>` elements has a width of 480px.
=> chore: design kit page content width

master/internal/rm/agentrm/resource_pool.go
Fix issue where slot capacity check always fails for agent resource manager.
Create an experiment for which your cluster has enough slots to run and ensure that you don't see the warning message about not having enough slots.
=> fix: Slot Capacity Check Always Fails

master/internal/api_experiment.go
I updated the migration to just materialize the searcher metric value itself as opposed to all of the metrics, but I forgot to update the code that depended on it.
=> fix: get searcher metric val from column that actually exists

harness/determined/cli/command.py
listing commands used to fail if the associated workspace was deleted
`git apply <(gd $(g merge-base ee/master ee/rbac-ntsc-ee)..ee/rbac-ntsc-ee harness/)`
=> fix: account for listing ntsc in deleted workspaces

docs/release-notes/equal-in-env-value-k8s.rst, master/internal/rm/kubernetesrm/spec.go, master/internal/rm/kubernetesrm/spec_test.go
K8s environment variables were parsed incorrectly for empty environment variables like ```TEST``` and ones with equal signs in the value like ```f=f(x)=test```.
On a k8s cluster this command outputs
```
det cmd run --config="environment.environment_variables='test=abc=d','testempty'" printenv | grep test
```
```
[2023-01-20T21:32:40.592512Z] b0e43a15 || test=abc=d
[2023-01-20T21:32:40.592517Z] b0e43a15 || testempty=
```
=> fix: k8s environment variable with equal sign or empty env errors [DET-8837]

webui/react/src/components/UPlot/UPlotChart.tsx, webui/react/src/components/UPlot/UPlotChart/closestPointPlugin.module.scss, webui/react/src/components/UPlot/UPlotChart/closestPointPlugin.ts, webui/react/src/components/UPlot/UPlotChart/tooltipsPlugin2.ts, webui/react/src/components/kit/LineChart.module.scss, webui/react/src/components/kit/LineChart.tsx, webui/react/src/pages/DesignKit.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx, webui/react/src/shared/styles/index.scss
The ticket says to replace charts on the multi-trial view; from looking around I take this to mean the Learning Curve visualization.
This also fixes an issue with the colors in the trials table not matching the colors used in the chart and tooltip.
Go to a multi-trial page which completed and has >10 trials. I've recently found you can add Trials  to the columns on the experiment page, then sort descending.
- On the initial / learning curve tab, the page has a chart with multiple lines, and a table with multiple rows, corresponding to these trials
- Possible to select another metric in a dropdown
- Possible to change linear/log scale of the chart
- Possible to limit number of trials to 1 or 10
- Checking 1-5 trials in the lower table -> limits the chart to showing only those trials
Then: …
=> feat: Learning Curve using LineChart component [WEB-661]

webui/react/src/components/InfoBox.module.scss, webui/react/src/components/InfoBox.tsx, webui/react/src/components/Metadata/EditableMetadata.tsx
As described in WEB-432, false-y values from the metadata editor did not show up in the viewer / get saved.
This PR displays all metadata rows, including empty strings.  It enables a metadata row to store an empty string. If an empty string or null value is used, it will appear as a grey oval (to show some content exists).
Preparing
- Open a model's detail page, and edit metadata
- Add a key "A" and assign value 0
- Add a key "B" and do not assign a value
- Click to add another key, but do not name a key. Add a value if you like.
- Save metadata
Assessment
- The viewer should display a 0 for A, a grey oval for B (empty string), and not have a third item (no key was given). 
- If you refresh the page, A and B should still be there.
See [Release …
=> fix: Empty string can be stored in metadata values [WEB-432]

docs/release-notes/dont-checkpoint-gc-no-checkpoints.rst, e2e_tests/tests/cluster/test_checkpoints.py, master/internal/api_experiment.go, master/internal/api_experiment_intg_test.go, master/internal/api_user_intg_test.go
Don't create checkpoint GC task if we don't have any checkpoints.
intg + e2e tests
Create an experiment that will fail and cause checkpoint GC to fail.
```
det e create --config="checkpoint_storage.type=s3" --config="checkpoint_storage.bucket=notarealbucket" examples/tutorials/mnist_pytorch/const.yaml examples/tutorials/mnist_pytorch/ -f
```
Delete experiment after it errors
```
det e delete $exp_id
```
Verify the exp is gone from ```det e```
Created DET-8836 to follow up about how we can handle failed checkpoint GC better.
=> fix: don't checkpoint gc in exp delete with no checkpoints [DET-8834]

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst
The scriptlet example of how to import/create an enroot container for Determined was missing the .sqsh suffix add it.
=> docs: Add misssing suffix in enroot create example

agent/.goreleaser.yml, agent/packaging/determined-agent.service, docs/release-notes/usr-bin.rst, master/.goreleaser.yml, master/packaging/determined-master.service
We've always been installing binaries into `/usr/local/bin`, but that's wrong. Recent goreleaser update made it obvious #5816.
Linux package installs and upgrades from older versions still work okay.
=> fix: deb and rpm should install master and agent bins into `/usr/bin`

.circleci/config.yml, e2e_tests/tests/cluster/test_master_restart.py, helm/charts/determined/templates/master-config.yaml, helm/charts/determined/values.yaml, master/internal/command/command.go, master/internal/config/resource_manager_config.go, master/internal/config/resource_pool_config.go, master/internal/rm/kubernetesrm/events.go, master/internal/rm/kubernetesrm/informer.go, master/internal/rm/kubernetesrm/kubernetes_resource_manager.go, master/internal/rm/kubernetesrm/message.go, master/internal/rm/kubernetesrm/pod.go, master/internal/rm/kubernetesrm/pod_test.go, master/internal/rm/kubernetesrm/pods.go, master/internal/rm/kubernetesrm/preemptions.go, master/internal/rm/kubernetesrm/request_queue.go, master/internal/rm/kubernetesrm/request_queue_test.go, master/internal/rm/kubernetesrm/request_workers.go, master/internal/rm/kubernetesrm/resource_pool.go, master/internal/task/allocation.go, master/pkg/set/set.go
This allows each resource pool in a Kubernetes cluster to map to a specific namespace in the cluster. The pods actor now maintains pod and config map clients for each namespace that might be necessary and passes the appropriate one along to each of its child actors. (Since the clients have namespaces built into them that can't be changed, we can't just have one of each kind of client.)
An alternative would be to have a separate pods actor for each namespace, along with the attending actors for informers, listeners, and the request queue. That has a certain elegance and might be a smaller code change, but I didn't go that way because it seemed kind of heavyweight in execution.
The API for available resources still needs updating, since it's based on enumerating nodes in the cluster, and …
=> feat: correspond Kubernetes resource pools to namespaces

master/internal/core.go
Currently assets for the UI are not being compressed due to a single small error on the backend. This fix enables `gzip` compression.
1. Navigate to the login page. 
2. Open up the network tab in the browser console.
3. Select "disable cache" so that assets are not being served from the browser cache.
4. Refresh the page.
5. Ensure that media files and assets `.js`, `.css`,`.woff2`, `.png` are being `gzip` encoded. The files should include `Content-Encoding: gzip`
6. Start a Tensorboard session and ensure that Tensorboard loads successfully. 
Part of the reason that this bug may not have been caught is because file compression is working differently locally when the UI is being served on the dev server vs devcluster. For example:
**Without the fix being implemented**
You will see that the …
=> fix: enable asset compression [WEB-654]

webui/react/src/components/UPlot/UPlotChart.tsx, webui/react/src/pages/TrialDetails/Profiles/Charts/SystemMetricChart.tsx, webui/react/src/pages/TrialDetails/Profiles/Charts/SystemMetricChartFilters.tsx
The experiment's profiler tab had a global storagePath, so the 'Agent Name' / ID from one experiment was carried over to another (where that Agent ID is not valid).  This blanks the System Metrics chart when requesting an unusable trial-agent combination.
(sample bad API request: http://latest-master.determined.ai:8080/api/v1/trials/6703/profiler/metrics?labels.name=cpu_util_simple&labels.agentId=i-072f3882870741314&labels.metricType=PROFILER_METRIC_TYPE_SYSTEM&follow=false )
The fix makes `storagePath` specific to the trial.
Alternatives:
- should we use `trial.experimentId` ?  I don't think an experiment is certain to have the same agent IDs
- should we remove `agentId` from Settings, or remove Settings from this page?  I am open to this solution, but the `SystemMetricFilter` component …
=> fix: Profiler useSettings bug, dependency warning in chart [WEB-847]

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
In the recent refactors, the line that reported the slot type from the config got removed accidentally, causing all slots to reported as unspecified type.
Ideally, the values should actually be read on a per-RP basis using quotas or something, but that is still being figured out, so let's at least get this value in here first.
=> fix: report configured slot type in Kubernetes

webui/react/src/components/kit/LineChart.tsx, webui/react/src/hooks/useFeature.ts, webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx, webui/react/src/shared/styles/index.scss
Requires feature flag to show the new chart component - add `f_chart=on` to URLs.  The one chart which needs to be un-done in this PR is the Learning Curve chart.
This keeps the fix which we discussed in #5807 re: colors matching on LearningCurve chart and table
Cursor CSS
- In the design kit (`/det/design`), charts continue to have the new component (hovering shows diamond cursor)
- Find a single-trial experiment and confirm old format chart (hover cursor is a solid circle, not diamond)
Learning Curve
- Find a multi-trial experiment which completed successfully (example : `/det/experiments/1754/visualization/learning-curve` )
- In the experiment's Learning Curve tab, you should see an old format chart (note hollow circles at each data point)
- Add `?f_chart=on` or `&f_chart=on` to the …
=> feat: Chart feature flag

examples/gan/pix2pix_tf_keras/adaptive.yaml, examples/gan/pix2pix_tf_keras/const.yaml, examples/gan/pix2pix_tf_keras/distributed.yaml
Sometimes, the test `examples/tests/test_official.py::test_official` would fail. Reducing the `global_batch_size` seems to help prevent the problem.
`test-examples` should pass.
=> fix: reduce global_batch_size in pix2pix example

harness/determined/tensorboard/util.py, harness/tests/tensorboard/test_util.py
Determined uploads log files to a directory accessible by Tensorboard for visualization. Determined would append the rank information to the log files to keep track of which worker the log is from.
https://determinedai.atlassian.net/browse/MLG-274
We found out that in some cases, portions of the log files will be dropped by the `with_suffix` function of pathlib library of Python after we append the rank information. These paths are actually valid on both S3 and Determined's Docker containers. 
Example:
Original path: "/tmp/tensorboard-39.ff54aea9-0a94-4ce7-bf38-e8b3e69cc944.1-0/aa1f87508336_37.1674696139174.pt.trace.json"
Expected path (assuming rank is 3): /tmp/tensorboard-39.ff54aea9-0a94-4ce7-bf38-e8b3e69cc944.1-0/aa1f87508336_37.1674696139174#3.pt.trace.json
Actual modified path: …
=> fix: TensorBoard file pathnames incomplete and lacking rank information  [MLG-274] 

docs/reference/rest-api.rst
the protocols buffer page we were referencing is being deprecated this month, this PR replaces the URL to the deprecated site with the new URL, plus some minor edits for readability
=> docs: Update REST API page

webui/react/src/components/UPlot/UPlotChart.module.scss, webui/react/src/components/UPlot/UPlotChart.tsx, webui/react/src/components/UPlot/UPlotChart/tooltipsPlugin2.ts, webui/react/src/components/kit/LineChart.module.scss, webui/react/src/components/kit/LineChart.tsx, webui/react/src/shared/styles/index.scss
Covers three overflow-related bugs on the LineChart component.
I'm OK if this PR includes other UI and interaction bugs / quirks. 
I'm OK if this PR includes adding more points / more series in the UI Kit for more intense testing.
See images in WEB-842 for reference.
1. In Firefox, and changed page zoom in Chrome, the chart tooltip could be cut off on the right edge. In #5807 I changed tooltip to appear left of cursor earlier (90%), and added overflow-x hidden. I now prefer overflow-x visible.
2. The chart plot div was appearing below the "No Data" card. Chart div now is destroyed when a chart has no data or switches to have no data. Removed previous CSS fix (overflow-y)
3. Cursor crosshair / target responded mouseenter before the tooltip. Now when the cursor re-enters the chart, calling …
=> fix: Overflow bugs on charts [WEB-842]

webui/react/src/components/DeterminedAuth.tsx, webui/react/src/components/Navigation.tsx, webui/react/src/hooks/usePermissions.ts, webui/react/src/pages/SignOut.tsx, webui/react/src/stores/permissions.tsx, webui/react/src/stores/users.tsx
As we discussed recently:
- on signout, reset current user to NotLoaded, by sending `null` instead of a negative number
- rename UserRolesService to PermissionsStore (I also changed names of some functions from User to My, i.e. `fetchMyAssignmentsAndRoles`, which matches how we name the returned callbacks in files `fetchMyRoles = PermissionsStore.fetchMyAssignmentsAndRoles`)
Passing build / tests
=> chore: Rename user roles to PermissionsStore, set current user accepts null

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst
Even more specific based upon additional review.
Passed through grammerly.com
=> docs: More specific HPC launcher linux requirements

docs/reference/reference-deploy/config/master-config-reference.rst
Update the Slurm/PBS master configuration docs to better describe the current behavior WRT slot_type.
Perhaps also finally deconflict with content in the 'EE' repo.
Docs build and tested locally.
=> docs: clarify usage of slot_type with HPC

harness/determined/tensorboard/base.py, harness/tests/tensorboard/test_base.py
[MLG-287]: https://determinedai.atlassian.net/browse/MLG-287
This is the first of a group of PRs to enable asynchronous upload of TensorBoard files as described in  MLG-287.
For details, please refer to the design doc linked in the ticket.
This PR creates a new thread subclass responsible for running upload of Tensorboard files and add relevant unit tests. See commentary section below for more details on how this class will be used and design choices.
We added unit tests for this test class in test_base.py
`% pytest test_base.py `
` 9 passed, 1 warning in 0.27s`
(1)
This class will be a member variable to the [TensorboardManager class](https://github.com/determined-ai/determined/blob/master/harness/determined/tensorboard/base.py#L10)
It will be initialized if the async upload mode is …
=> perf: [1/n] Add new thread sub-class to handle Tensorboard files sync

webui/react/src/pages/Cluster/ClusterOverallStats.test.tsx, webui/react/src/pages/Cluster/ClusterOverallStats.tsx, webui/react/src/services/apiConfig.ts, webui/react/src/stores/index.tsx, webui/react/src/stores/tasks.tsx
Creates an observable-based `TaskStore` to replace previous store.
This is currently only used to display active notebooks, tensorboards, shells, and commands on the cluster page.
The counts are updated simultaneously from regular polling on this page, so it makes sense to set them up as a single Observable Loadable TasksCount object
- Sign in as admin
- Visit the Cluster page and view counts of active commands / shells / tensorboards
- In a terminal enter `det -m SERVER_ADDRESS shell start`
- Watch for Active Shells to go up by 1
- Go to Tasks section and kill the shell
=> feat: Tasks store to observables [WEB-797]

harness/determined/cli/command.py, harness/determined/cli/render.py
OrderedDict was added to typing in 3.7.1, but we support 3.7.0 still.
=> fix: avoid typing.OrderedDict

master/internal/api_auth.go
The current message is not actionable for end-users. Virtually every time they see this, it just means they didn't run `det auth login` and authenticate via their browser. Possibly we could improve this further by automatically trying to start authentication when we hit authentication errors, but for now this is a low-hanging fruit usability fix by making the required action clear to end-users.
Will test a build of HPE MLDE that has authentication configured this way just for completeness' sake. Do not expect any issues since it's just changing a string in a user-facing error message.
=> chore: improve error message for unauthenticated API clients

webui/react/src/components/ThemeProvider.tsx
This fixes the tree element in the workspace/project searcher appearing with an inappropriate background color.
OLD:
NEW: 
The tree element that shows up when searching workspaces should appear with a transparent background
[WEB-864]
[WEB-864]: https://determinedai.atlassian.net/browse/WEB-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: fix tree transparency color

master/static/srv/get_workspaces.sql
~~Motivation is that support workspace (ws) id filter in [GetWorkspaces](http://latest-master.determined.ai:8080/docs/rest-api/#/Workspaces/GetWorkspaces) with [Int32FieldFilter](https://github.com/determined-ai/determined/blob/master/proto/src/determined/common/v1/common.proto#L34) like [experimentIdFilter  in GetExperiments](http://latest-master.determined.ai:8080/docs/rest-api/#/Experiments/GetExperiments) to optimize API call. 
In order to archive this, we need to switch sql code to Bun code.~~ <- so far web team end up not needing it, 
The current SQL is a bit complicated, so I removed subquery to simplify and speed up as by-product (subquery is usually slow).
---
M1 Max Mac with 32GB memory, 10 cores:
On my local db, i have 464 experiments, 133 projects, 255 workspaces, 257 pinned …
=> refactor: `getWorkspaces` sql refactor and speed up

webui/react/src/pages/SignOut.tsx
Prevent getting stuck in an unusable state when you are logged out.  My understanding from testing other branches is that our spinner issues stem from SignOut making some unusual calls, error handling, etc.  From console.log-ing, there is a try-catch section, and signOut completes, but still we don't redirect to a clean login page. This is my recommendation to make the redirect to new login + state effective.
(this may already have been addressed for logged-in users?)
`make build` the webui
Start devcluster. In incognito mode, or a browser where you are not typically signed in, visit `http://localhost:8080`. You should arrive on the login screen and not be stuck on a spinner.
Restart devcluster between tests
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/re …
=> fix: Patch an issue where login (?) seems to load forever

webui/react/src/pages/WorkspaceDetails.tsx
Prevent an issue where a user does not have access to the Uncategorized project (and other workspaces/projects) yet we continued to poll for data and workspace roles from the Not Found page.
The change is on `src/pages/WorkspaceDetails.tsx` - `fetchAll` will stop if we know that the user does not have access to this project. Also integrates NotFound page into the display/error conditions.
I explored changes on WorkspaceProjects and ProjectDetails but this appears to be the core issue.
As described in bug, as EE admin create a user with no permissions, then log in as that user
Open the console to check for auth / failed requests
Visit / (for devcluster, localhost:8080) -> redirect to /det/workspaces with empty workspaces list
Visit /det/workspaces -> see empty workspaces list
Visit …
=> fix: Prevent extra calls to fetch inaccessible workspaces, projects [WEB-880]

webui/react/src/pages/SignOut.tsx, webui/react/src/stores/workspaces.tsx
- Add callback to workspaces store to clear workspaces store/cache (this is the source of pinned workspaces)
- On signout, call useResetWorkspaces
- Sign in as admin and have at least one pinned workspace
- Create a user with no roles / permissions
- Sign out and sign in under this new user / no password: no pinned workspace is shown at any time
- Sign out and sign in again as admin: after a short delay to fetch workspaces, the pinned workspace is visible again
=> fix: Clear pinned / all workspaces on signout [WEB-899]

master/static/srv/entrypoint.sh, master/static/srv/notebook-entrypoint.sh, master/static/srv/shell-entrypoint.sh, master/static/srv/tensorboard-entrypoint.sh
Description:
It is very useful to have a print out of what was executed in the startup-hook.sh when troubleshooting issues. Just as we show the experiment config, we should show what the user did in their startup-hook.sh to modify the environment.
=> feat: add command echo around startup hook

webui/react/src/components/Page.tsx, webui/react/src/pages/ExperimentDetails/ExperimentDetails.tsx, webui/react/src/pages/ModelDetails.tsx, webui/react/src/pages/ModelRegistry.tsx, webui/react/src/pages/ModelVersionDetails.tsx, webui/react/src/pages/ProjectDetails.tsx, webui/react/src/pages/TrialDetails.tsx, webui/react/src/pages/WorkspaceDetails.tsx
https://determinedai.atlassian.net/browse/WEB-831
Should not see 404 flash while loading a page.
Also looked at adding more props to `Page` to handle repeated code (rendering `<Spinner>` or `<Message>`), but seemed like that added complexity to the `Page` component without much benefit. Sticking to only using an additional prop for `<PageNotFound>` or anything that relies on permissions being loaded first.
=> fix: hide 404 until permissions are loaded

CONTRIBUTING.md
Removes link to the outdated Project Roadmap on the GitHub Wiki which itself has been deprecated.
No test plan required.
Discussed internally and approved by leadership.
- [**NA**] Changes have been manually QA'd
- [**NA**] User-facing API changes need the "User-facing API Change" label.
- [**NA**] Release notes should be added as a separate file under `docs/release-notes/`.
- [**NA**] Licenses should be included for new code which was copied and/or modified from any external code.
No Ticket
=> docs: remove link to outdated project roadmap wiki page

cli/determined_cli/__init__.py, common/determined_common/__init__.py, deploy/determined_deploy/__init__.py, harness/determined/common/experimental/checkpoint/_checkpoint.py, harness/determined/common/experimental/determined.py, harness/determined/common/experimental/model.py, harness/determined/deploy/cli.py, harness/determined/experimental/client.py, harness/determined/pytorch/_pytorch_trial.py, harness/determined/pytorch/deepspeed/_deepspeed_trial.py
According to the latest version of `flake8-bugbear`, a `stacklevel` argument should be provided to `warnings.warn`, and it should be at least 2 (otherwise the warning just shows the line of the warning call itself, which is not that helpful).
=> fix: satisfy lint for `stacklevel` to `warnings.warn`

webui/react/src/App.tsx, webui/react/src/components/Navigation.tsx
This fixes an issue where the user's theme preference wasn't respected on refreshing the page. This was because the theme context was moved above the settings context as part of the antd5 upgrade. That's now fixed, but there is a minor chance that some dialogues that appear at the same time as the initial render will not be aware of the theme.
1. On any page, change the theme from the system theme to either the light theme or dark theme
2. On reload, the theme should persist
WEB-866
=> fix: Persist theme settings

.circleci/config.yml, .circleci/devcluster/double-priority.devcluster.yaml
One of the tests in the changed run flakes occasionally due to a bug in the fair share scheduler that we're not planning to address soon (DET-8883), so let's try changing over to priority.
We could also change that test to a managed devcluster test, but that would be more work, and also this way I think we get a better overall split of testing between the two schedulers.
=> test: switch test-e2e-cpu-double to use priority scheduler

webui/react/src/hooks/usePermissions.ts, webui/react/src/pages/ModelRegistry.tsx, webui/react/src/pages/WorkspaceDetails.tsx
- Show models from any workspaces in global model registry (previously required a cluster-wide permission).
- If the user has no workspace permissions, global model registry will be empty rather than 404.
- Puts model registry RBAC checks behind a feature flag which we've been using (`f_model_rbac=on`)
- Workspaces check a workspace-specific view registry permission (previously used cluster-wide permission in all cases)
OSS behavior should be unchanged.
On EE
- As admin, create a new user. Grant them Viewer access on one workspace
- The created user can log in and visit an empty Model Registry at `/det/models?f_model_rbac=on`
- The created user can view their one Workspace and see the Model Registry tab even with `?f_model_rbac=on`
See [Release …
=> fix: Avoid model registry 404, workspace-specific permissions [DET-8917]

.circleci/config.yml
We had one CI failure [1] caused by the Go package download somehow fetching some incorrect file (seems like probably a 5xx status page or something, though there's no way to know now). This attempts to work around that by checking the hash of the downloaded file to at least cover for totally transient errors.
Also upgrade from 1.18 to 1.18.10 while we're here.
[1] https://app.circleci.com/pipelines/github/determined-ai/determined/33339/workflows/dd7d6e62-e6c8-4152-bb41-3d313ae9adab/jobs/1170863
=> ci: check and retry Go package download

webui/react/src/components/JupyterLabButton.tsx, webui/react/src/components/NavigationSideBar.tsx, webui/react/src/components/NavigationTabbar.tsx, webui/react/src/components/TaskList.tsx, webui/react/src/hooks/useFeature.ts, webui/react/src/pages/Dashboard.tsx, webui/react/src/pages/DefaultRoute.tsx, webui/react/src/routes/index.tsx
https://determinedai.atlassian.net/browse/WEB-860
Dashboard should appear as an option in the navigation bar, and should be the default route (unless rbac is on, in which case the default route is the workspaces list page).
Haven't received design approval on the changes from WEB-814, not sure if we should wait on that to merge this PR to release the dashboard.
=> chore: remove dashboard feature switch

agent/packaging/entrypoint.sh, master/internal/rm/agentrm/provisioner/agent_setup_test.go, master/static/srv/agent_setup_script.sh.template
DET-8747
found a sort of related issue that only wwas exposed when we start failing agents: DET-8929
I have not tested on GCP but the changes here are provider agnostic. let me know if you think it should be tested on GCP
- run agents with failing startup and container_startup_scripts with failing scripts on one RP and no scripts on another RP prior to this pr eg 
```
startup_script: |
echo "this is startup script"
touch /tmp/sssc-$(date)
echo "failign now"
exit 3
container_startup_script: |
echo "this is startup script"
touch /tmp/sssc-$(date)
echo "failign now"
exit 3
```
see that the agents continue to come up and function despite the script being executed
- apply the changes and deploy another aws cluster with the same scripts and see the agent doesn't come up
See [Release …
=> fix: prevent agent startup on startup script non-zero exit

docs/quickstart-mdldev.rst
Docs-only change. Removes a redundant item that's covered in the next element.
N/A
=> docs: remove an extraneous item about accessing WebUI

docs/reference/reference-deploy/config/master-config-reference.rst, docs/release-notes.rst
=> docs: document `kubernetes_namespace` resource pool config option

master/internal/api_trials.go, webui/react/src/components/UPlot/UPlotChart/drawPointsPlugin.ts, webui/react/src/pages/TrialDetails/F_TrialDetailsOverview.tsx
On the Trial Details page, LineChart was always displaying "Batches" in the X-Axis and tooltip. Adjusted to show `String(xAxis)` which covers Batches and Time.
Three other issues:
- Single point series (ex: a validation series with one record) were invisible unless also a checkpoint or hovered. Changed the drawPoints plugin to return `true` in this case, which shows an unfilled circle.
- checkpoint.endTime occurs after the metric is recorded, so the best checkpoint may match to a point on x = checkpoint.totalBatches but not on x = checkpoint.endTime (see experiment used in test).  If we're going to have separate series for batches and time then probably checkpoint(s) need to be sent to the chart as their own series?  But for now in this chart we can expect a batch # to be associated with …
=> fix: Various chart axis + checkpoint bugs [WEB-911]

webui/react/src/hooks/useSettingsProvider.tsx
Debug conversation occurred on Slack; essentially we want both the user and checked auth, before making requests and risking failing out to login again.
=> fix: Don't call getUserSetting until auth is fully checked

webui/react/src/components/CheckpointModalTrigger.test.tsx, webui/react/src/hooks/useFeature.ts, webui/react/src/hooks/useModal/Checkpoint/useModalCheckpointRegister.tsx, webui/react/src/hooks/usePermissions.ts
When registering a checkpoint as a "Model Version", filter the list of destination models through a new client-side check `canModifyModel({ model })`
`canModifyModel` matches the existing `canModifyModelVersion` but avoids the complexity of accepting both types or a partial type through a single function, or some future issues.
While working on this ticket, I realized that `canDeleteModel` had not been updated either. This now follows the logic of `canDeleteModelVersion`.
Client-side alternative to https://github.com/determined-ai/determined/pull/5924
On OSS version:
- Navigate to a successfully completed experiment.
- Click the flag icon to open a checkpoint modal. On the bottom of the modal, click "Register Checkpoint"
- On this Model Version modal, open the dropdown. You should see an …
=> feat: Permissions for registering a model version, deleting a model [WEB-808]

webui/react/src/components/Navigation.tsx, webui/react/src/stores/cluster.tsx
This fixes an issue where a login loop could occur when using Okta. Okta login requires auth to read the token after mounting the app. The initial call to check the auth happens in the App component. When we moved the agent and resource pool calls to an observable store, we moved the calls to init the information into a polling funciton called above the App component, causing a race condition where the auth would complete but the user would be kicked back to the login screen because the initial polling calls made before the user could be authenticated failed. To be safe, we fix a similar pattern happening in the navigation component which causes a failed request on the login page.
logging in with okta should work
See [Release Note](https://github.com/determined-ai/determined/blob/master/do …
=> fix: guard against store polling when not logged in

Makefile
Determined cannot be currently built with go1.20. This adds a target in the Makefile that checks the system go version against the supported go version and errors if the system go is not supported.
This was tested by hand against go1.18.10, go1.19.5, and go1.20.
This is just a simple fix for an existing problem. It temporizes any decisions about more generally checking requirements, and also leaves for a future commit updates to the library to make determined buildable with more recent go.
MLG-305
=> build: [MLG-305] Check for supported go version at make.

webui/react/src/components/Metadata/MetadataCard.tsx, webui/react/src/pages/ModelDetails.tsx, webui/react/src/pages/ModelDetails/ModelHeader.tsx, webui/react/src/pages/ModelRegistry.tsx
This should follow #6001
If user does not have `EDITMODELREGISTRY` permission in their cluster or workspace, UI should not appear editable. Server-side permission is already there.
Features on the model registry / list:
- Changing model name, description, or tags
- Using the three-dots menu at right to Archive the model (delete is handled separately)
- Using the right-click context menu to Archive the model
Features on the model details page:
- Changing the model name, description, or tags
- Using the three-dots menu at upper-right to Archive the model
- Adding a Note
- Editing Metadata
OSS behavior should be unchanged.
This is difficult to test on EE before we can create models in different workspaces.
For now you can set `canModifyModel` to always `return false` and see what UI is …
=> feat: Model editing tools disabled if you lack permission [WEB-912]

webui/react/src/components/Navigation.tsx
Fix a bug where EE / RBAC was not showing workspaces, models, or other right panel content unless you had just signed in.
Because the issue is not in OSS, hides the UI, and was connected to login; we know this relates to RBAC roles and storage.
The usePolling for `fetchMyRoles` is called on load and every 2 minutes after. If currentUser is NotLoaded on initial call, we skip that call and are left role-less.  Under this new setup, a `useEffect` fetches roles after `currentUser` changes. 
Notes:
`useEnsureCurrentUserFetched` is already successfully fetching the current user info from App.tsx; timing just was not good.
I'm open to `syncRoles` being a regular function instead of `useCallback` if it would work.
- Run in EE
- Visit `/det/workspaces` and see workspaces
- Refresh the page and …
=> fix: Load roles after current user is loaded [WEB-924]

webui/react/src/pages/JobQueue/JobQueue.tsx
The crash on the cluster jobs queued page is caused by infinite component re-renders due to `updateSettings` being an included dependency in a [useEffect](https://github.com/determined-ai/determined/blob/3ed96ccf44ce89cb00e54c25c540b95aab995cb2/webui/react/src/pages/JobQueue/JobQueue.tsx#L218). 
1. Log into the WebUI with a user that currently does not have any saved `job-queue` settings. You can also clear the settings in the database by running `DELETE FROM user_web_settings WHERE user_id = <user_id> AND storage_path LIKE '%job-queue%';`.
2. Visit the cluster overview page in the UI. `/det/clusters`.
3. Click on a `Resource Pool` card. For example the `default` resource pool.
4. Click on the `Queued` tab. The page should not crash and the UI should still be functional.
5. Resize and …
=> fix: cluster queued jobs page crash

webui/react/src/pages/ModelDetails.tsx, webui/react/src/pages/ModelDetails/ModelHeader.tsx, webui/react/src/pages/ModelRegistry.tsx
If a user has Model Registry Viewer permission but not Workspace Viewer permission, we should display the Model Registry and Model Details pages successfully.
Related to WEB-919 and our previous work on Models,
- Global Model Registry (`/det/models`) will display a `[-]` block in the workspaces column if we can't display a useful link + name of an inaccessible workspace
- Model Viewer will stop spinner once workspaces are loaded (regardless of whether one with `model.workspace_id` is returned)
- Model Viewer's Header will link to Global Model Registry in the breadcrumbs if no workspace was accessible
No effect on OSS.
You can test with a new user with only ModelRegistryViewer permission, or test having `canViewWorkspace` always return false.
See [Release …
=> fix: Display model breadcrumbs even if no access to workspace [WEB-919]

harness/determined/core/_distributed.py
There was a guard to skip local zmq setup when local_size < 2, but that became no longer valid when local_size varied from worker to worker.
The result is one extra global allgather in some cases, no big deal.
=> fix: lopsided training with 2,1 gpus

.circleci/config.yml
We got a failure due to a timeout on this, so let it retry a few times.
May or may not help, probably won't hurt.
=> ci: retry downloading GKE auth plugin [DET-8956]

harness/determined/tensorboard/util.py, harness/tests/tensorboard/test_util.py
As I investigate MLG-326, I notice that the current way to append rank to PT profiler files would append the rank behind the timestamp as opposed to the worker.
This clashes with the torch-tb-profiler library's regex to parse worker and time stamp (see [link](https://github.com/pytorch/kineto/blob/cdfa44f8d8f2f2b5c6f2efa83322977551e05d92/tb_plugin/torch_tb_profiler/profiler/loader.py#L28))
As a result, each {worker}{timestamp#rank} file was treated as one worker in the visualization. For example, if a worker has 10 PT profiler files of different time stamp, they were treated as 10 different workers.
After this change, each {worker#rank} is treated as one worker and each timestamp file for it would be treated as a span (see screenshot in test plan for details)
Make sure unit test jobs …
=> fix: Add #rank to worker segment instead of timestamp segment of Pytorch Profiler files [MLG-326]
