- harness/determined/tensorpack/_tensorpack_trial.py
Previously when backbone weights are set, we would load checkpoints
from the wrong path.
> fix: fix loading logic for tensorpacktrial when backbone is set

- agent/go.mod
- agent/go.sum
- agent/internal/docker.go
- agent/internal/docker_credential_store.go
When we added in the container_startup_script to run in the
agent's runtime environment (docker), an assumption was made
that the golang client would handle invoking credentials
helpers. Unfortunately, they are invoked by the cli itself.
Because of this, this commit was made to invoke the credential
helper if auth wasn't provided on the experiment config.
> fix: add logic in agent to invoke docker credentials helpers

- docs/Makefile
We previously created tarballs for the examples without a directory
prefix. As a result, when extracted via `tar` or similar tools, files
would be placed in the shell's present working directory. That is
generally not considered good form.
Instead, we now prefix the files in the example tarballs with the name
of the example. For example, the contents of `mnist_pytorch.tgz` are now
nested under a top-level directory `mnist_pytorch`.
- UI change:
> fix: include example name as prefix in example tarballs

- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/checkpoint/_torch.py
- tests/integrations/experiment/test_pytorch.py
- tests/integrations/experiment/test_tf_estimator.py
- tests/integrations/experiment/test_tf_keras.py
- tests/integrations/test_system.py
If models are trained on a GPU but loaded on a CPU pytorch throws an
error telling the user to explicitly target the CPU. This commit adds
the ability to pass the `map_location` parameter to `torch.load` in
order to target the CPU.
- UI change:
> fix: target cpu for torch.load in integration tests

- cli/determined_cli/checkpoint.py
- cli/determined_cli/experiment.py
- cli/determined_cli/trial.py
- common/determined_common/experimental/experiment.py
Adds `det experiment download` command for downloading n checkpoints in
sorted order by metric to a local directory.
- UI change:
> [DET-2888] feat: experiment download cli command

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/secure.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/deployment_types/vpc.py
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/constants.py
- deploy/determined_deploy/gcp/terraform/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/outputs.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/variables.tf
- deploy/determined_deploy/gcp/terraform/outputs.tf
- deploy/determined_deploy/gcp/terraform/variables.tf
- docs/how-to/installation/aws.txt
- docs/how-to/installation/gcp.txt
1. new --static-agents argument to det-deploy gcp specifying the static
agent count
2. rename --max-instances to --max-dynamic-agents for AWS and GCP to
distinguish it as the dynamic agent pool size
DET-2912 #Done.
- UI change:
> feat: support GCP static agent instances in det-deploy

- docs/how-to/hyperparameter-tuning.txt
- docs/how-to/install-cli.txt
- docs/how-to/install-main.txt
- docs/how-to/installation/deploy.txt
- docs/how-to/installation/docker.txt
- docs/how-to/installation/packages.txt
- docs/how-to/installation/requirements.txt
- docs/how-to/installation/upgrades-troubleshoot.txt
- docs/reference/index.txt
- docs/topic-guides/terminology-concepts.txt
- docs/tutorials/quick-start.txt
- docs/tutorials/tf-mnist-tutorial.txt
* Mention that Docker must be started after installing it via Homebrew
on MacOS
* Call it "Nvidia Container Toolkit", not "nvidia-docker2"
* Streamline main installation page
* Minor fixes and cleanups elsewhere
- UI change:
> docs: various improvements

- webui/elm/package-lock.json
- webui/elm/package.json
- webui/react/package-lock.json
- webui/react/package.json
- webui/tests/package-lock.json
- webui/tests/package.json
Some packages may still be using old and vulnerable dependencies.
To override these vulnerabilities, using npm-force-resolutions to
force overriding nested dependencies with specific version via the
"resolutions" field under package.json, which npm-force-resolutions
will use. npm-force-resolutions will get installed during preinstall
if it does not exist already.
Recreation of [this PR](https://github.com/determined-ai/determined/pull/285) due to possible repo migration corruption.
> [DET-2950] feat: enable overriding nested package dependencies

- agent/internal/detect.go
- agent/internal/nvidia.go
When an agent Docker image is built with the Nvidia runtime and run without it, the container winds up with an empty `/usr/bin/nvidia-smi` file, which would cause the agent to get an unexpected error and fall over. This changes the agent to log any such errors and continue running instead. It is perhaps a bit broad to handle _all_ errors like so, but it doesn't seem that helpful to add a bunch of code for ferreting out very specific errors, and I think it does make sense to allow the agent to be robust here.
> feat: be more lenient about errors in running `nvidia-smi`

- examples/official/object_detection_pytorch/model_def.py
Apparently `fasterrcnn_resnet50_fpn` actually modifies the labels that are passed to it.  To actually get correct metrics, updated to pass a deep copy of the labels to the model, so we can still calculate metrics with the original (correct) labels.
> fix: fix bbox bug in object detection example

- master/internal/user/service.go
without an expiration date, the cookie expires and the user is logged out when the session ends.
> [DET-2971] feat: set an expiration date for auth cookie

- harness/determined/exec/worker_process.py
- harness/determined/ipc.py
- harness/determined/layers/_worker_process.py
- tests/unit/test_ipc.py
Previously during multi-GPU training if a worker process died, if there was no hvd.allreduce() call prior to the next barrier (e.g., if the error occurred while reducing metrics) the worker would die but the trial would hang. This would happen because the  SubProcessLauncher monitors the liveliness of the horovodrun process on the chief machine and the liveliness of the sshd process on the non-chief machines. These processes fail when a worker process fails during or before a hvd.allreduce() call.
Performed a number of manual tests to verify the fix including crashing the chief process and/or a non-chief process during training and validation.
> [DET-2879 DET-2882] Prevent hangs in multi-GPU trials

- tests/integrations/experiment/experiment.py
This should help alleviate the issue where circle CI times out after not receiving output from pytest for >10m
Manually tested with `pytest -vv -s`
> test: output logs during wait_for_experiment_state

- master/internal/checkpoint_gc.go
- master/internal/command/command.go
- master/internal/scheduler/cluster.go
- master/internal/scheduler/fair_share_test.go
- master/internal/scheduler/fitting.go
- master/internal/scheduler/fitting_test.go
- master/internal/scheduler/task.go
- master/internal/trial.go
This will allow us to differentiate in how we schedule different type of tasks. Including allowing us to schedule multi-slot-notebooks that do not take up the entire agent, which was the original ask in this ticket.
In addition adding unit tests. I spun a cluster and launched several different experiments and notebook configurations that use the modified codepath.
> [DET-2856] Allow tasks to specify fitting requirements

- tests/integrations/nightly/test_capability.py
After adding this test, all `experimental` examples should now have capability coverage.
> [DET-2963] Add a capability test to `mnist_pytorch_multi_output`

- examples/official/cifar10_cnn_pytorch/adaptive-advanced.yaml
- examples/official/cifar10_cnn_pytorch/adaptive.yaml
- examples/official/cifar10_cnn_pytorch/const.yaml
- examples/official/cifar10_cnn_pytorch/distributed.yaml
- examples/official/cifar10_cnn_pytorch/model_def.py
- examples/official/cifar10_cnn_pytorch/parallel.yaml
- tests/integrations/test_convergence.py
The convergence test will run `cifar10_cnn_pytorch` for 500 steps nightly and verify the validation accuracy is above 74.5%. 
The test experiment I ran takes about ~10 minutes to finish 500 steps and reaches a best validation accuracy of ~74.9%. I set the target threshold accuracy at slightly below that to give some slack for non-deterministic factors. We might need to revisit this based on how flaky this threshold ends up being.
> [DET-2972] Fix cifar10_cnn_pytorch bugs and add a convergence test

- Makefile
> chore: clean webui root make targets

- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/tensorpack/_tensorpack_trial.py
To exit out of a trial, the harness processes a Terminate message. When using a subprocess
to train (multi-GPU), the subrprocess launcher waits to receive a reply from all the subprocesses
or until a health check fails while a Terminate message is being process to reply to the socket and
workload manager that the Terminate has completed. Previously, the trial controllers would not respond to the Terminate message. On the chief agent that started  horvodrun, the health check would fail because the horovodrun process would exit out once all the subprocesses completed, and the containers would terminate with error code of 0. On the other agents, the sshd process would remain alive, thus the health checks would never fail, and the container would not exit until forcibly being killed, …
> [DET-2945] fix: exit out of non-chief containers gracefully

- .circleci/config.yml
The manual approval request steps (for GPU tests and deploying) in CircleCI had dependencies on the Docker build steps, which meant we had to wait a few minutes after pushing to provide the approvals. Removing the dependencies will mean we can immediately approve after pushing and then let the build and tests/deployment run from there.
> ci: allow manual approvals to be provided immediately

- agent/internal/agent.go
- agent/internal/containers.go
- agent/internal/nvidia.go
- deploy/determined_deploy/local/cluster_utils.py
- docs/how-to/installation/deploy.txt
- docs/how-to/installation/docker.txt
- docs/how-to/installation/requirements.txt
- docs/how-to/installation/upgrades-troubleshoot.txt
- docs/reference/cluster-config.txt
- master/internal/config_test.go
- master/internal/provisioner/agent_setup_test.go
- master/internal/provisioner/config.go
- master/internal/provisioner/config_test.go
- master/pkg/container/container.go
- master/static/srv/agent_setup_script.sh.template
- packaging/master.yaml
Things are a bit confusing due to unclear messaging by Nvidia, but here's what's going on:
- There is a repo called [`nvidia-docker`](https://github.com/NVIDIA/nvidia-docker). `nvidia-docker` is not the name of any package currently described there.
- That repo currently recommends a package called `nvidia-container-toolkit` (or "the NVIDIA Container Toolkit") that works on Docker >= 19.03.
- That repo used to describe (and still references in a few places) a now-deprecated package called `nvidia-docker2` that was for Docker < 19.03 (though it still works for newer versions).
- They make a big deal about the newer version of Docker having "native" support for GPUs, but the only user-facing change is the name of the package and the flag used to select GPUs.
(The above points led to some …
> [DET-2973] feat: make agent work with `nvidia-container-toolkit`

- harness/determined/pytorch/_pytorch_trial.py
The `logging.debug` that was present before would interpret the metric name as a format string and attempt to interpolate the metric value into it.
> fix: avoid crash in PyTorch trial when debug mode is on

- docs/conf.py
- docs/faq.txt
- docs/how-to/tensorboard.txt
- docs/reference/attributions.txt
- docs/tutorials/pytorch-mnist-tutorial.txt
- docs/tutorials/quick-start.txt
- docs/tutorials/tf-mnist-tutorial.txt
Sphinx defaults to applying Python highlighting if possible [1], since reST is so closely associated with Python. In our docs, though, we actually have a pretty broad mix, so we don't want to end up with Python highlighting where it doesn't apply.
This changes the default to no highlighting and removes all explicit instances of "text" highlighting, which also means no highlighting.
[1] https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#code-examples
> docs: make Sphinx default to not syntax highlighting code

- docs/tutorials/data-access.txt
- docs/tutorials/pytorch-mnist-tutorial.txt
- docs/tutorials/tf-mnist-tutorial.txt
- examples/official/iris_tf_keras/model_def.py
* Object stores can be used on-prem and distributed file systems can be
used in the cloud, so I thought it was a bit confusing to have "cloud"
vs. "on-prem" as the top-level distinction. This also resulted in the
"cloud NAS" and "on-prem NAS" sections being mostly identical.
* Use the term "distributed file system" instead of "network-attached
storage" -- the latter is more closely associated with a hardware
appliance.
* Move docs on security credentials from "object storage download" to
the parent section, "object storage".
* Fix a bunch of typos and do various copy-editing.
* Simplify front-matter.
* Add links to this tutorial to the TF Keras and PyTorch tutorials.
- UI change:
> docs: revise data access tutorial

- CONTRIBUTING.md
Update references to how to use GPUs with Determined and remove an outdated section on dependency management.
(There's still more that needs updating to account for recent build system changes, but I'm not very familiar with that at the moment.)
> docs: update `CONTRIBUTING.md` for recent changes

- webui/elm/src/Modals/CreateExperiment.elm
> [DET-2979] fix: resize the Ace editor when an error pops up

- e2e_tests/tests/test_convergence.py
0.745 seems to have resulted in a pretty quick flake: https://app.circleci.com/pipelines/github/determined-ai/determined/1253/workflows/6e5ab66b-d030-45fc-a032-be8935b945fc/jobs/21072/steps. tweak it lower.
> test: adjust confidence threshold for a successful convergence

- harness/determined/_env_context.py
- harness/determined/exec/harness.py
- harness/determined/experimental/_native.py
- harness/determined/gpu.py
- harness/determined/layers/_harness_profiler.py
- harness/setup.py
Given the complexity of GPUtil and how little we need from it, it makes sense to remove that dependency and get what we need from `nvidia-smi` directly.
This code also provides better error handling in the face of strange output from `nvidia-smi`.
Also fix up some type annotations; GPUtil returns IDs as integers, and this code does the same, but the annotations thought they were strings.
> [DET-2955] refactor: remove dependency on GPUtil

- cli/determined_cli/shell.py
- master/internal/agent/agent.go
1. The ip address of agents might be parsed wrong if the agent is in the same machine as the master. This PR fixs the parsing.
2. When opening a shell, the address of an agent is hardcoded into localhost. This PR changes to use the host of the agent.
> [DET-2976] Fix openning a shell

- docs/how-to/custom-env.txt
The environment.image configuration field used to contain a list of
images for CPU and GPU containers. This is now a dictionary and
therefore the snippet was not a valid experiment configuration.
See: https://github.com/determined-ai/determined/blob/8bdda0087a17a7b107e626b6bda879a637bb4418/master/pkg/model/environment_config.go#L14-L27
> docs: fix custom env tf.2 snippet

- deploy/determined_deploy/local/cli.py
- deploy/determined_deploy/local/cluster_utils.py
- docs/how-to/installation/deploy.txt
- webui/tests/bin/e2e-tests.py
We've heard feedback that `fixture` is not the clearest term when starting a local Determined cluster.  This PR renames `fixture` to `cluster`:
```
det-deploy local cluster-up
det-deploy local cluster-down
```
> chore: rename fixture-up to cluster-up

- e2e_tests/tests/requirements.txt
We don't run startup-hook.sh as part of checkpoint export, so pandas which is installed in the startup-hook for iris is not present in our environment. 
Tested locally to confirm issue is solved.
> test: install pandas to fix iris test

- docs/reference/api/pytorch.txt
- docs/reference/api/trial_context.txt
- harness/determined/errors.py
- harness/determined/pytorch/__init__.py
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
First phase of https://determinedai.atlassian.net/browse/DET-3033 to add support for a generic callback interface in PyTorchTrial. Second phase will involve fixing the `on_validation_step_end()` case in the distributed / parallel context.
Test Plan:
Added unit tests.
> feat: create generic callback support for PyTorch

- docs/reference/api/pytorch.txt
- docs/reference/api/trial_context.txt
- harness/determined/errors.py
- harness/determined/pytorch/__init__.py
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
This is a follow-up to https://github.com/determined-ai/determined/pull/405 to fix the failure introduced into pytorch parallel callbacks.
The failure that led to a revert was due to switching the ordering of the sequence "build model" -> "build optimizer" -> `model.to(device)` to "build model" -> `model.to(device)` -> "build optimizer". It turns out that this leads to a failure in the parallel training. I've adjusted the ordering back to the original.
See https://github.com/determined-ai/determined/pull/405
1) Tested running a parallel pytorch trial on a 2-GPU development instance on GCP. 
2) Manually ran the full GPU tests on Circle CI: https://app.circleci.com/pipelines/github/determined-ai/determined/1533/workflows/6ec88165-a5dc-4b85-ab30-489b22d808bf
> feat: re-introduce generic callback support for PyTorch

- webui/react/src/components/Link.module.scss
- webui/react/src/components/Link.tsx
The anchor tag was not initially used due to the nesting limitation with
anchor tags. Going forward we will need to avoid this situation.
before (anchor tags in the page):
after (anchor tags in the page):
> [DET-2933] feat: make Link component to be based on HTML anchor tag

- cli/determined_cli/agent.py
- master/internal/agent/agent.go
When working with dynamic agents on a cluster running a variety of
workload types (e.g., experiments, notebooks, tensorboards, etc.), it
can be difficult to tell whether an agent is idle or not. This commit
adds a simple way to do that via "det agent list".
Note: this breaks CLI backward compatibility, as "det agent list" with
CLI >= 0.12.5 won't work with masters < 0.12.5.
> feat: add container count to "det agent list"

- e2e_tests/tests/experiment/test_pytorch.py
- harness/determined/pytorch/_pytorch_trial.py
Currently, AMP w/ Horovod w/ aggregation_frequency > 1 leads to convergence errors.
DET-3028  #Done.
Updated tests.
There are at least two current issues. First, when overflows happen, they only happen on some of the workers, those workers end up skipping `step()`, which leads to different model parameters on different GPUs. The second issue, is that `parameters.grad.data` from prior steps (that haven't been zeroed out) are being used as part of subsequent loss scaling. Even after addressing these two issues (with debugging hacks) there are still other unknown issues that lead to convergence issues. 
One possible workaround is to limit `max_loss_scaling` to a lower number, which would prevent overflows and prevent the convergence issues. However, this may cause issues with gradients …
> fix: don't support AMP w/ aggregation_frequency > 1

- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/terraform/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/variables.tf
- deploy/determined_deploy/gcp/terraform/modules/database/outputs.tf
- deploy/determined_deploy/gcp/terraform/variables.tf
- master/cmd/determined-master/init.go
- master/internal/db/config.go
- master/internal/db/setup.go
We should, in cloud setups, setup TLS for communication with
the postgres database, since credentials and models are
sent between it.
> chore: add TLS by default for cloud deployments

- Makefile
`$*` expands to the stem with which an implicit rule matches (that is, whatever the `%` corresponds to).
For more information, see the manual (https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html).
> build: use `$*` in Makefile pattern rules

- cli/determined_cli/experiment.py
- harness/determined/experimental/__init__.py
- harness/determined/experimental/_native.py
- harness/determined/experimental/estimator/_estimator_native.py
- harness/determined/experimental/keras/_tf_keras_native.py
- harness/tests/experiment/test_local.py
Previously, there are different code paths to run local and cluster modes. The code path to run local mode when using Tensorflow Keras and Estimator Native API has behaviors inconsistent with other code paths in:
1. training one step rather than one batch.
2. not setting the context directory to be the working directory
Now, unify these code paths to improve the ease of maintenance.
> refactor: unify the code paths for local and cluster modes

- cli/determined_cli/agent.py
- cli/determined_cli/render.py
This is useful as a stop-gap for folks that want to probe the state of
the cluster, e.g., to determine if there are free GPUs to run
low-priority batch inference jobs using the command infrastructure.
To make JSON output consistent with non-JSON output, we now construct an
intermediate list of dicts with the formatted version of the JSON we get
from the master.
Note that there are other `list` subcommands that might benefit from
being treated consistently, but this commit does not attempt to add
support for all of them.
> feat: support `--csv`, `--json` in `slot list` and `agent list` in CLI

- scripts/setup-env-arch.sh
- scripts/setup-env-centos.sh
- scripts/setup-env-macos.sh
- scripts/setup-env-ubuntu.sh
- Update the scripts to use the newer `nvidia-toolkit-container` package rather than the deprecated `nvidia-docker2` one, since the rest of the system has just switched over.
- Remove the use of `virtualenvwrapper` in favor of the Python-recommended `python -m venv` (except on CentOS, since it seems to be awkward to get the latter to work there).
- Reorder each script into "install things from the network" followed by "do local setup things".
- Make the scripts consistently handle the Docker service (they all enable it, to avoid somebody coming back after a reboot and being surprised that it's not running, and restart it, which is necessary to pick up GPU support after installing the toolkit).
- Apply `shfmt`.
> chore: update OS setup scripts

- master/internal/user/service.go
Currently, when the database is down and someone
tries to login, we just give them a 403. From a
UX perspective, this is misleading. We should respond
with something other than invalid credentials.
> chore: show better messaging when db is down

- webui/react/src/ErrorHandler.ts
- webui/react/src/services/apiBuilder.ts
the requests are always cancelled at the explicit request of the caller (which most commonly happen when dismounting the component) we generally do not consider those as errors and as such don't pass them through ErrorHandler.
errorHandler is mainly for unifying logging, notification, and other forms of error response.
> chore: stop handling request cancellation errors

- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/checkpoint/_tf.py
- common/determined_common/experimental/checkpoint/_torch.py
- e2e_tests/tests/experiment/test_pytorch.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/experimental/_native.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/load/_load_implementation.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/util.py
Re-apply https://github.com/determined-ai/determined/pull/459.
Fixes `tf.keras` trial checkpoint export by loading the users trial class, calling build_model, and loading the weights. This is necessary because custom object in keras are not serialized via `h5`. Loss functions and custom layers were therefore not recoverable in the previous iteration.
Custom layers in for torch trials were also not pickled correctly. Therefore, we are applying the same instantiate and load weights strategy to pytorch going forward.
[DET-3044]
The current test suite covers these changes.
[DET-3044]: https://determinedai.atlassian.net/browse/DET-3044
> fix: checkpoint export with custom python objects

- webui/react/src/pages/Authentication.tsx
- webui/react/src/routes/index.ts
- webui/react/src/utils/routes.ts
[DET-3068]
[DET-3068]: https://determinedai.atlassian.net/browse/DET-3068
> feat: support arbitrary login redirect routes

- .circleci/config.yml
- requirements.txt
- webui/tests/bin/createUserAndExperiments.py
- webui/tests/cypress/support/commands.js
- webui/tests/package-lock.json
- webui/tests/package.json
- webui/tests/requirements.txt
terminal output on OSX
```
Waiting for master to be available...
Waiting for master to be available...
Waiting for master to be available...
Starting determined_integrations_5300-agent-0
+ python /Users/ck/Projects/determined/webui/tests/bin/createUserAndExperiments.py
Preparing files (/Users/ck/Projects/determined/tests/integrations/fixtures/no_op) to send to master... 17.0KB and 16 files
Created experiment 1
Preparing files (/Users/ck/Projects/determined/tests/integrations/fixtures/no_op) to send to master... 17.0KB and 16 files
Created experiment 2
Preparing files (/Users/ck/Projects/determined/tests/integrations/fixtures/no_op) to send to master... 17.0KB and 16 files
Created experiment 3
Preparing files (/Users/ck/Projects/determined/tests/integrations/fixtures/no_op) to send to …
```
> fix: allow OSX interactive session during det user create

- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/how-to/custom-env.txt
- docs/tutorials/quick-start.txt
- e2e_tests/tests/config.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- master/pkg/model/defaults.go
The new task envs include our Horovod repository rebased on top of v0.19.2.
[DET-3069](https://determinedai.atlassian.net/browse/DET-3069)
These changes have been manually tests for TF 1 & 2 for keras and estimators. Also going to run the full suite of tests before merging.
> chore: bump environments version

- webui/react/src/App.module.scss
On the dashboard the content panel is short about 50 pixels on the bottom.
visually inspect to check the fix was applied properly on all the pages
> style: fix the height of the content panel of the dashboard

- harness/determined/exec/tensorboard.py
- master/internal/command/tensorboard_manager.go
TensorBoard did not previously accept the `endpoint_url` parameter for s3 checkpoint configurations. Therefore, S3 compliant APIs could not be used with TensorBoard ie. MinIO. This Change adds support for the `endpoint_url`
[DET-3078]
Spin up a test cluster backed by MinIO persistent storage.
[DET-3078]: https://determinedai.atlassian.net/browse/DET-3078
> fix: pass s3 endpoint url to tensorboard process

- webui/react/src/hooks/useRestApi.ts
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/Determined.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/decoder.ts
- reuse the `apiBuilder` in rest API hooks
- allow the same api use pattern that is used elsewhere in our app to be used in `hooks/useRestApi` as well
- limit all the decoding in the `decoder` module
once this looks good to everyone and is refined and is approved we can port the rest of the rest API hooks and future ones to use this pattern
https://determinedai.atlassian.net/browse/DET-3086
> refactor: introduce a more modular approach  to useRestApi

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/how-to/custom-env.txt
- docs/tutorials/quick-start.txt
- e2e_tests/tests/config.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- harness/tests/experiment/keras/test_tf_keras_trial.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
- master/pkg/model/defaults.go
We now support TF 2.2 and have made it the default TF2 version. 
[DET-3088](https://determinedai.atlassian.net/browse/DET-3088)
Tested manually and ran a full suite of tests: https://app.circleci.com/pipelines/github/determined-ai/determined/1735/workflows/041781c3-3e21-4758-82ef-4b52861e928b
> feat: support TF 2.2

- webui/react/src/pages/Authentication.tsx
> chore: import defaultAppRoute constant instead of redefining it

- docs/how-to/installation/packages.txt
* Add more guidance and sample commands on installing PostgreSQL,
including steps for package-based install
* Use apt rather than apt-get
* Add validation steps to installation to help users checkpoint
that each install step succeeded
> docs: package-based install documentation improvements

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/tutorials/quick-start.txt
- e2e_tests/tests/config.py
- master/pkg/model/defaults.go
Previously following the recent Horovod upgrade  (#556), multi-machine distributed
training did not work unless the network interface was explicitly specified.
[DET-3096 ](https://determinedai.atlassian.net/browse/DET-3067)
[DET-3067](https://determinedai.atlassian.net/browse/DET-3096)
Tested these changes manually, and going to run full suite of tests before merging.
> feat: update to nccl 2.6.4 and fix multi-machine dtrain

- harness/determined/ipc.py
- harness/determined/pytorch/_pytorch_trial.py
Previously, on_validation_end callbacks only executed on the chief if
the trial was training in a multi-GPU context. Now, the callback is
executed on all workers, allowing for callbacks that modify the state of
the optimizer such as lr schedulers.
[DET-3033]: https://determinedai.atlassian.net/browse/DET-3033
* e2e gpu tests: https://app.circleci.com/pipelines/github/determined-ai/determined/1769/workflows/7f01fad6-23f8-437c-aa5e-3c9c405d3a2a
* TODO(yoavz): Test an implementation of ReduceLROnPlateau with distributed training and observe that the LR is appropriately reduced.
> feat: support passing reduced validation metrics to all workers

- e2e_tests/tests/command/test_tensorboard.py
- harness/determined/exec/tensorboard.py
- master/static/srv/tensorboard-entrypoint.sh
Run TensorBoard as a subprocess rather than a peer process, making it easy to control with a timeout check.
Will additionally check manually that an s3-based experiment continues to work.
> feat: add timeout to tensorboard startup

- cli/determined_cli/experiment.py
- docs/reference/api/experimental.txt
- docs/topic-guides/model-definitions/native-api.txt
- docs/topic-guides/model-definitions/trial-api.txt
- examples/experimental/native_fashion_mnist_tf_keras/native_impl.py
- examples/experimental/native_fashion_mnist_tf_keras/trial_impl.py
- examples/experimental/native_mnist_estimator/native_impl.py
- examples/experimental/native_mnist_estimator/trial_impl.py
- examples/experimental/native_mnist_pytorch/trial_impl.py
- examples/experimental/native_object_detection_pytorch/trial_impl.py
- examples/tutorials/native-tf-keras/tf_keras_native.py
- examples/tutorials/native-tf-keras/tf_keras_native_dtrain.py
- examples/tutorials/native-tf-keras/tf_keras_native_hparam_search.py
- harness/determined/experimental/__init__.py
- harness/determined/experimental/_native.py
- harness/determined/experimental/estimator/_estimator_native.py
- harness/determined/experimental/keras/_tf_keras_native.py
- harness/tests/experiment/fixtures/estimator_xor_model_native.py
- harness/tests/experiment/fixtures/tf_keras_runtime_error.py
- harness/tests/experiment/fixtures/tf_keras_xor_model_native.py
- harness/tests/experiment/keras/test_tf_keras_trial.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
- harness/tests/experiment/utils.py
This is sort of a bare-minimum PR to have a concrete discussion around the API change.
Mostly I think this API matches what we have already agreed on for the cli, which will look something like this:
```
det e create ...
det e create --local ...
det e create --test ...
det e create --local --test ...
```
IMO, this is best reflected by a `det.create()` function like:
```
def create(..., local: bool = False, test: bool = False, ...):
...
```
I thought about making two enums but I had a bit of a crisis of naming.  Which one got to be called "mode"?  What would the other one be called?  And combining them into a single enum like `LOCAL_TRAIN`, `LOCAL_TEST`, `SUBMIT_TRAIN`, `SUBMIT_TEST` felt wrong.
Ultimately, I like the boolean thing because it is utterly simple to understand from just …
> feat: support local and test modes separately

- harness/determined/estimator/_estimator_trial.py
- harness/tests/experiment/fixtures/estimator_xor_model.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
We previously ignored hooks that were passed into `tf.estimator.EvalSpec`.
[DET-3097](https://determinedai.atlassian.net/browse/DET-3097)
Tested manually, and also added a unit test for both training and eval hooks.
> feat: add support for estimator eval hooks

- e2e_tests/tests/config.py
- e2e_tests/tests/nightly/test_convergence.py
Nightly test for PyTorch obj detection has been missing the target accuracy. Set random seed to reduce randomness.
Ran twice locally, both times reached accuracy of 0.56, which exceeds the target accuracy of 0.42.
> test: fix nightly objection detection convergence test

- master/internal/trial.go
Before fix, after a `max_restarts: 0` experiment fails:
```
unexpected failure of trial (1/0): ...
```
After fix:
```
unexpected failure of trial after restart 0/0: ...
```
> fix: fix off-by-one error in master logs

- docs/reference/api/estimator.txt
- harness/determined/estimator/__init__.py
- harness/determined/estimator/_callback.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/estimator/_util.py
- harness/determined/util.py
- harness/tests/experiment/fixtures/estimator_xor_model.py
- harness/tests/experiment/fixtures/estimator_xor_model_native.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
Most callback functionality can be handled via native support in tf.estimator using `tf.estimator.SessionRunHook`. However our checkpoint mechanism does use `CheckpointSaverHook`, thus checkpoint callbacks can not be performed via `tf.estimator.SessionRunHook`. To support such use cases (e.g., adding custom meta-data file to a checkpoint) we are adding support for deteremined callbacks in EstimatorTrial. Currently we are adding support for `on_checkpoint_load` and `on_checkpoint_end`.
Additionally as part of this PR, removed copies of checkpoint files that are no longer necessary. 
[DET-3100](https://determinedai.atlassian.net/browse/DET-3100)
Added a unit test to test callback support. Also performed manual test confirming that changes do not break checkpoint/restart for multi-gpu.
> feat: add callback support to EstimatorTrial

- docs/reference/api/estimator.txt
- harness/determined/estimator/_callback.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/fixtures/estimator_xor_model.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
Updated docs and code to use `str` instead of `pathlib.Path`.
Updated tests.
> feat: use str instead of pathlib.Path in checkpoint callbacks

- harness/determined/pytorch/_pytorch_trial.py
In a previous iteration of checkpoint export, we used `torch.save()` to save the entire model architecture.  We had to switch to only loading weights to make checkpoint export more robust.
This change removes the now unnecessary `torch.save()` which was failing with the Native API and custom PyTorch layers.
TBH, I'm not 100% certain that the `torch.save()` is actually unnecessary.
> fix: avoid saving pytorch model architecture

- harness/determined/pytorch/_pytorch_trial.py
Previously when not using mixed precision, we were potentially performing gradient clipping prior to gradient communication being completed.
Going to run the full suite tests before merging.
> fix: synchronize before gradient clipping in PyTorch

- .circleci/config.yml
- Makefile
- e2e_tests/tests/experiment/test_pytorch.py
- e2e_tests/tests/experiment/test_tf_estimator.py
- e2e_tests/tests/experiment/test_tf_keras.py
- examples/Makefile
- examples/tests/.flake8
- examples/tests/.isort.cfg
- examples/tests/Makefile
- examples/tests/requirements.txt
- examples/tests/test_official.py
- harness/determined/experimental/_native.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
This PR creates a test suite associated with `examples`. It runs a minimal test on each example using `--local --test` mode. It is slightly more heavyweight than our unit tests since every example runs in a separate Python process, but more portable than full integration tests since no Determined cluster is required.
Run-time on my local macbook pro is 1 minute 42 seconds:
```
41.38s call     test_examples.py::test_official[official/cifar10_cnn_tf_keras-official/cifar10_cnn_tf_keras/const.yaml]
22.36s call     test_examples.py::test_official[official/cifar10_cnn_pytorch-official/cifar10_cnn_pytorch/const.yaml]
9.46s call     test_examples.py::test_official[official/multiple_lr_schedulers_pytorch-official/multiple_lr_schedulers_pytorch/const.yaml]
9.39s call …
```
> test: create a test suite for examples

- master/internal/experiment.go
- master/internal/trial.go
- master/pkg/searcher/adaptive_simple.go
- master/pkg/searcher/adaptive_simple_test.go
- master/pkg/searcher/adaptive_test.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/asha_test.go
- master/pkg/searcher/event_log.go
- master/pkg/searcher/grid.go
- master/pkg/searcher/grid_test.go
- master/pkg/searcher/message.go
- master/pkg/searcher/operations.go
- master/pkg/searcher/pbt.go
- master/pkg/searcher/pbt_test.go
- master/pkg/searcher/random.go
- master/pkg/searcher/random_test.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/searcher.go
- master/pkg/searcher/tournament.go
- master/pkg/searcher/util_test.go
We now support trials erroring without closing the experiment. The
behavior for how this is left up to each search method, and is handled
strictly internal to the search method. This means that any mocked
metrics are not saved in the db or exposed to the user.
- Random: No further action is needed.
- Grid: No further action is needed.
- ASHA-based: Treat the trials as having a MaxFloat64 validation
metric. Mock promotions and ensure that no further workloads are sent
to the experiment.
- PBT: treat the trials as having a MaxFloat64 validation metric.
Ensure that no further workloads are sent to the experiment, and we
do not create new trials based on the completed workload.
As part of this work, we have introduced a flag to the shutdown message
that indicates to the experiment whether the …
> feat: support early trial termination

- master/internal/agent/agent.go
- master/internal/checkpoint_gc.go
- master/internal/command/command.go
- master/internal/command/events.go
- master/internal/command/notebook_manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/scheduler/resource_provider.go
- master/internal/trial.go
- master/pkg/agent/master_message.go
Start of decoupling agents and workflows. Have container log messages come from resource providers.
[DET-3175](https://determinedai.atlassian.net/browse/DET-3175)
Tested manually by spinning up a cluster and trying trials and notebooks.
> feat: decouple container logs from agents [DET-3175]

- e2e_tests/tests/test_system.py
- harness/determined/exec/gc_checkpoints.py
- master/pkg/tasks/task.go
There's a limit to how much you can pass in environment variables, which I hit while playing with Estimators, which generate a large number of verbose filenames in checkpoints.
This change passes information into the checkpoint gc script as files instead of as environment variables.
Regular tests are fine, IMO.
> fix: pass checkpoint gc metadata as a file

- e2e_tests/tests/nightly/test_convergence.py
Without the random seed, the convergence sometimes falls just short of the target accuracy of `0.85`.
Tested locally.
> test: set seed for fashion mnist nightly convergence test [DET-3234]

- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/constants.py
- deploy/determined_deploy/gcp/terraform/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/variables.tf
- deploy/determined_deploy/gcp/terraform/variables.tf
- docs/reference/cluster-config.txt
- docs/topic-guides/elastic-infra/dynamic-agents-gcp.txt
- master/internal/provisioner/gcp_config.go
- master/internal/provisioner/gcp_config_test.go
- master/internal/provisioner/gcp_operation_tracker.go
- master/packaging/master.yaml
When creating or terminating an instance, the GCP provider sends a request to the GCP API and the response will be a GCP operation. By tracking the GCP operation, we are able to know if the instance is successfully created/terminated. There is a timeout before we consider a GCP operation no longer effective and we might retry after hitting the timeout. This PR intends to make that timeout period configurable. This PR changes the code and the doc relates to it.
[DET-3182](https://determinedai.atlassian.net/browse/DET-3182)
Manually test it with the following provisioner config and see if the timeout is configurable:
```
provisioner:
agent_docker_network: host
agent_docker_image: determinedai/determined-dev:determined-agent-d90294d941964f104b50204232002fa551daa648
max_idle_agent_period: 1m …
```
> feat: make GCP operation tracker timeout configuration [DET-3182]

- agent/internal/docker_credential_store.go
The path to the docker config file varies depending on location of HOME directory. When an agent was run somewhere where /root is not the HOME directory, this prevented using docker credential stores. 
Manually tested that we are able to pull from GCR when running the agent outside of a container on Ubuntu.
> fix: read docker config file from HOME directory

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/secure.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/deployment_types/vpc.py
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/constants.py
- deploy/determined_deploy/gcp/terraform/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/variables.tf
- deploy/determined_deploy/gcp/terraform/variables.tf
- docs/reference/cluster-config.txt
- docs/topic-guides/elastic-infra/dynamic-agents-aws.txt
- docs/topic-guides/elastic-infra/dynamic-agents-gcp.txt
- master/internal/config_test.go
- master/internal/provisioner/config.go
- master/internal/provisioner/config_test.go
- master/internal/provisioner/provisioner.go
- master/internal/provisioner/provisioner_test.go
- master/internal/provisioner/scale_decider.go
- master/internal/provisioner/scale_decider_test.go
- master/packaging/master.yaml
The provisioner would retry launching an agent after reaching
a duration, which is set by max agent starting period. Previously,
this configuration is hardcoded to 300 seconds. Now, change it to
be in the configuration of the provisioner.
1. Manually test.
The goal of the test is to test if the functionality has been changed and the agent starting period is configurable as planned.
Use the following provisioner config:
```
provisioner:
agent_docker_network: host
agent_docker_image: determinedai/determined-dev:determined-agent-d90294d941964f104b50204232002fa551daa648
max_idle_agent_period: 1m
max_agent_starting_period: 10s
operation_timeout_period: 1m
provider: gcp
boot_disk_size: 200
boot_disk_source_image: projects/determined-ai/global/images/pedl-environments-4e98289
network_interface: …
```
> feat: make agent starting period configurable [DET-3219]

- master/internal/experiment.go
- master/internal/experiment_test.go
Previously, every validation would be marked as the best one seen when `smallerIsBetter` was true. The new version avoids that and also separates the code a bit more cleanly into "decide whether the validation is best" followed by "do things accordingly".
> fix: correct logic for checking if a validation is the best one seen

- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/types.ts
- webui/react/src/types.ts
- webui/react/src/utils/types.ts
[DET-2934]
depends on https://github.com/determined-ai/determined/pull/584
[DET-2934]: https://determinedai.atlassian.net/browse/DET-2934
> feat: add pause/activate and cancel actions to task cards 

- docs/reference/api/pytorch.txt
- harness/determined/pytorch/__init__.py
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
Previously we supported gradient clipping in PyTorch only via special hyperparameters. Moving to supporting it via callbacks will make it more transparent for users as well as allow users to apply more specialized clipping techniques.
As part of this PR also providing pre-made callbacks for the two types of gradient clipping we had previously supported. 
[DET-3233](https://determinedai.atlassian.net/browse/DET-3233)
Updated existing tests.
> feat: support gradient clipping in PyTorchTrial via callbacks [DET-3233]

- e2e_tests/tests/nightly/test_convergence.py
- examples/experimental/nas_search/arch_search.yaml
- examples/experimental/nas_search/model_def.py
- examples/experimental/nas_search/train_one_arch.yaml
NAS was using the old form of gradient clipping. Iris test needed to have a random seed set to reduce flakiness.
Tested locally.
> test: fix nightly nas and iris tf keras tests [DET-3264]

- webui/elm/src/Plot.elm
The ticks could get bunched up too much with long-running experiments
before; this just makes sure the spacing is a bit wider by enough to
work well in reasonable cases. The ticks may now occasionally look a
tiny bit wider than ideal with very short experiments, but it still
works fine in practice. Similarly, a long last tick could get cut off at
the end, so this also bumps the right side spacing correspondingly.
Before:
After:
> fix: space out WebUI plot x-axis ticks a bit more

- master/internal/agent/agent.go
- master/internal/checkpoint_gc.go
- master/internal/command/command.go
- master/internal/command/events.go
- master/internal/scheduler/agent.go
- master/internal/scheduler/assignment.go
- master/internal/scheduler/cluster.go
- master/internal/scheduler/cluster_test.go
- master/internal/scheduler/resource_provider.go
- master/internal/scheduler/scheduler_test.go
- master/internal/scheduler/task.go
- master/internal/trial.go
As part of this change, Tasks now receive a single `TaskAssigned` message
when they are assigned rather than one `Assigned` message per container.
They also start containers by sending specs back to the cluster rather than directly to agents.
Updated existing tests which should provide coverage. Additionally going to perform manual testing to test multi-container changes, and sanity check commands.
> feat: decouple agent information from workloads starting tasks [DET-3178]

- cli/setup.py
- common/setup.py
- deploy/setup.py
- harness/setup.py
Without this change, `pip show determined-cli | grep License` returns:
License: UNKNOWN
> chore: add license to pip metadata

- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/contexts/Experiments.tsx
- webui/react/src/hooks/useRestApi.ts
we locally update the experiment states on successful write actions to avoid waiting for the next poll period.
depends on #640 
> fix: eagerly update experiments on successful write actions [DET-3263]

- webui/react/src/utils/types.ts
We have three states that are hard to understand.
`StoppingCanceled`, `StoppingCompleted` and `StoppingError`
Updated them to something easier to understand.
`Canceling`, `Completing` and `Erroring`
> fix: update state labels to be more user-friendly

- webui/tests/.gitignore
- webui/tests/README.md
- webui/tests/bin/e2e-tests.py
- webui/tests/bin/try-for-flake.sh
> feat: store test cluster logs and improve test readme [DET-3269]

- webui/elm/package.json
- webui/react/package.json
There are security vulnerabilities that are sometimes discovered in npm packages that are dependencies of dependencies which we do not directly control. To overcome this limitation, we us `npm-force-resolutions` and the `resolutions` field under `package.json` to forcibly resolve the packages to use the proper dependencies that resolved the security vulnerabilities. The problem is that the resolution process should only occur during the package installation step (`npm install`) but NOT during CI gathering of dependencies (`npm ci`). Currently it occurs in both. This PR uses a `postshrinkwrap` script to run `npm-force-resolutions`, which only occurs for `npm install` and not `npm ci`.
@hamidzr discovered this post that provides basis of this solution: …
> ci: ensure npm ci does not dirty package-lock via npm-force-resolutions

- e2e_tests/tests/experiment/test_pytorch.py
- harness/determined/pytorch/_pytorch_trial.py
When performing mixed precision multi-GPU training, we need to finalize gradient update communication prior to un-scaling.
Re-enabled test and tested manually,
> fix: correctly use mixed precision with multi-GPU in PyTorchTrial [DET-3285]

- common/determined_common/api/request.py
When we use websockets to connect to the master, historically we
have not changed the protocol to ws/wss. This works fine for ws
but in the case of wss, it causes lomond (the python library we
use) to perform the ws upgrade before a tls handshake is
completed---causing the connection to be rejected.
The offending line of code is https://github.com/wildfoundry/dataplicity-lomond/blob/f7d0476c85777a4ce874323428a62ef085e76dd4/lomond/websocket.py#L102 which causes Lomond to not think our url with https is not secure so it tries to upgrade the connection before performing a tls handshake. My guess is a PR into Lomond to check for `https` also would be declined since `lomond.WebSocket` states a protocol of ws/wss is required https://github.com/wildfoundry/dataplicity-lomond/blob/f7d0476c85777a4c …
> fix: upgrade scheme when using websockets [DET-3230]

- common/determined_common/api/request.py
The websocket library we use provides nice representations for events, example https://github.com/wildfoundry/dataplicity-lomond/blob/f7d0476c85777a4ce874323428a62ef085e76dd4/lomond/events.py#L130-L135 but we scrap that and just print the event name. To help trouble shooting issues, we should just print the entire event.
Before:
```
Failed to fetch command logs: WebSocket failure: rejected
```
After:
```
Failed to create command: WebSocket failure: Rejected(response=<response HTTP/1.0 400 Bad Request>, reason='Websocket upgrade failed (code=400)')
```
> chore: better logging for websocket failures [DET-3230]

- webui/react/src/hooks/useAuthCheck.ts
During `webui-e2e-tests`, there is sometimes a race condition during login check that cancels user authentication check. The cancelation of the auth check causes the webui to clear out the cookie and log you out because it is considered an auth failure. Instead, we need to handle cancelation to skip the clearing of the cookies.
Pay special attention to CI `webui-e2e-tests` to see if failure occurs on the 5th test of the `02-loginout.spec.ts` test suite (`should redirect away from login when visiting login while logged in`). This test should not fail due to aborted `/users/me` calls.
> fix: handle auth check cancelation

- examples/experimental/trial/bert_squad_pytorch/const.yaml
- examples/experimental/trial/bert_squad_pytorch/distributed.yaml
- examples/experimental/trial/bert_squad_pytorch/model_def.py
>  fix: learning rate scheduler fix for bert squad example [DET-2897]

- harness/determined/keras/_tf_keras_trial.py
> docs: add support for model.stop_training to Keras docstring

- webui/react/src/App.tsx
The cache busting method currently used is not reliable across various browsers. The most reliable method discovered is using the query string to modify the URL, which modern browsers treat them as different file access, defeating cache. The basic idea is to attach a `ts` parameter with a timestamp attached to the URL the user is currently on and using `window.location.href` to load that page (essentially a reload with a `ts` query parameter.
> fix: change cache busting mechanism on react to query string

- cli/determined_cli/cli.py
- common/determined_common/api/request.py
Previously, if the CLI found a custom trusted master certificate, it
would be used for all requests made using Requests; that was the
simplest thing to write, but it meant that other HTTPS requests would
fail (e.g., checkpoint downloads from GCS, which go through Requests
internally). This change restricts the cert to only be applied to
requests made to the master.
The global variable is unfortunate, as always, but it's still better-scoped than the environment variable and anything else I can think of would be way overkill (doing some sort of singleton thing or having contexts everywhere).
> fix: use custom TLS cert only for Determined API requests [DET-3360]

- webui/elm/src/Page/ExperimentList.elm
- webui/tests/cypress/integration/01-setup.spec.ts
- webui/tests/cypress/integration/02-experiments.spec.ts
show experiments in increments instead of rendering all at the same time by default. we still keep the full list in memory to enable search over description.
batch operations work as before.
an alternative to full pagination
noop single experiments
1200 exps
- 2MB payload
- 0.19s master latency
4500
- 0.6s master latency (curl)
- 8.5MB payload
9500
- 0.98s master latency
- 18MB payload
~10k experiments 
before: load+3seconds
before load+16seconds
after: load+3seconds (50 rows shown by default)
after: load+3seconds
> feat: show experiments in increments [DET-3320]

- examples/official/trial/mnist_estimator/model_def.py
- harness/determined/estimator/_estimator_trial.py
Previously we were dividing by the number of workers, but the number of steps is set based on global batch size, thus the division is not necessary.
Tested this manually.
> fix: correctly set steps for eval in EstimatorTrial

- harness/determined/constants.py
- harness/determined/horovod.py
- harness/tests/test_horovod.py
When running on a large number of nodes (40+), the default timeout of 30 seconds is not enough for all nodes to connect with the chief process.
Tested by spinning up a 48 node cluster and successfully running a training job.
> feat: increase GLOO timeout [DET-3309]

- webui/react/src/components/TaskActionDropdown.tsx
- webui/react/src/components/TaskCard.module.scss
- webui/react/src/styles/antd.scss
- webui/react/src/themes.ts
The progress bar is sticking out of the task card boundary, this corrects the style.
Before:
After:
Additional work was done to unify floating UI element styles (task menus and dropdown menus)
> style: fix task card, menu and dropdown styles to be uniform [DET-3286]

- harness/determined/pytorch/__init__.py
- harness/determined/pytorch/_lr_scheduler.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
Clean up LR helper in our Pytorch support. Previously, `LRScheduler` is an user-facing object that lets users set how often an LR scheduler is stepped and `_LRHelper` is an internal object that lets the Determined step an LR scheduler. Keeping two objects is unnecessarily complicate especially in that part of the `_LRHelper` handles accepting an input of a None `LRScheduler`.
There are two different ways of calling the step() of a LR scheduler.
Method 1:
```
class MyTrial:
def __init__(context):
self.context = context
self.lr_scheduler = self.context.LRScheduler(optimizer=optimizer, step_mode=MANUAL_STEP)
def train_for_step(self, ...):
...
self.lr_scheduler.step()
```
Method 2:
```
class MyTrial:
def __init__(context):
self.context = context
self.lr_scheduler = …
```
> chore: clean up _LRHelper [DET-3270]

- webui/react/.eslintrc.js
- webui/react/src/services/api.ts
Add lint rule to capture errors around async functions missing await functions. To avoid unnecessary async applications.
> style: add linting rule to require await for async functions

- webui/react/.eslintrc.js
- webui/react/src/components/Logo.stories.tsx
- webui/react/src/components/ResourceChart.tsx
- webui/react/src/services/apiConfig.ts
- webui/react/src/types.ts
- webui/react/src/utils/Logger.ts
- webui/react/src/utils/data.ts
- webui/react/src/utils/task.ts
> style: fix lint issues

- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/storage/__init__.py
- e2e_tests/tests/fixtures/no_op/model_def.py
- e2e_tests/tests/requirements.txt
- e2e_tests/tests/test_users.py
- harness/determined/exec/harness.py
- harness/tests/storage/test_s3.py
- harness/tests/storage/test_storage_base.py
fix: support storage validation in container
test: regression test for host_path in container
chore: require container_path in storage.build()
It was never really optional, it was only very easy to forget that it
not passing container_path was only allowed in the host environment.
This was blatantly wrong, but it went unnoticed for weeks because it only arose when running experiments as non-root AND when using a non-`/tmp` `host_path` for a shared_fs storage.
This change also includes an improvement to an internal API to make it more difficult to make the same mistake.
PR includes a regression test, which fails when applied without the `fix` commit.
@sidneyw please confirm that the new test runs properly on a mac, and that it cleans up the checkpoint directories that it creates.
> fix: shared_fs checkpoint validation

- harness/determined/tensorboard/metric_writers/callback.py
Tested by running some keras/pytorch/estimator experiments. After removing the filter, the estimator metrics show up and the keras/pytorch looks unchanged. Any more thoughts @sidneyw? (I'm git blame'ing to see where this got introduced).
> chore: don't filter metrics with "/"

- webui/react/src/components/Badge.module.scss
- webui/react/src/components/Page.tsx
- webui/react/src/styles/antd.scss
> style: antd style adjustments

- harness/determined/layers/_workload_manager.py
- harness/tests/experiment/utils.py
- harness/tests/test_workload_manager.py
Fix a bug that @liamcli found.  Asking for a review from @stoksc since it conflicts with a change he has in flight.
Previously, the ordering of the context manager for storage_manager.save_path() was such that workload completed messages were sent before the upload finished.  As a result, the database would sometimes contain checkpoint uuid's that never got uploaded to cloud storage.
I added a unit test for the workload manager, which fails without the fix.
> fix: checkpoint workload fails if upload fails

- master/internal/api_model.go
- master/static/srv/get_models.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/model.proto
Endpoint for returning a paginated list of all models in the database.
Integration tests will cover the endpoint once we have the python client.
> feat: list models endpoint [DET-3278]

- CONTRIBUTING.md
MNIST example configs were moved from `examples/official/` to `examples/official/trial/`. This updates `CONTRIBUTING.md` to reflect the new location.
> docs: update the path to example configs

- master/internal/trial.go
Previously, for every container termination, we inserted a failure
status, which would result in us terminating the whole gang prematurely.
Tested this manually.
> fix: read correct failure status for terminated containers [DET-3435]

- harness/determined/estimator/_estimator_trial.py
If the response is sent before the callback, the socket to the master
may close and the container may get SigKilled before the callback
completes.
Tested this manually. Further testing should be done once [DET-3435](https://determinedai.atlassian.net/browse/DET-3435) is fixed and we should hold off merging this until then.
> fix: send Terminate response after on_trial_close callback [DET-3433]

- webui/react/src/App.tsx
During an `/info` poll, it's possible for `window.analytics` to be undefined, causing the `App` component to throw an error, resulting in a blank white screen.
> fix: check for analytics library

- e2e_tests/tests/experiment/experiment.py
Trials can now fail while the experiment succeeds. In the event this occurs, e2e tests still check that every trial succeeded causing the tests to fail. This check _could_ be done away with but that seems dangerous---test cases that want to test that graceful trial termination works should be separate and explicit, not baked into every test case. This PR just adds a bit of code to log the trial failures before we bail out and fail the tests.
This is useful because `test_end_to_end_adaptive` is failing in the exact manner and finding the trial logs is a pain.
> chore: log failed trial's trial logs when experiment succeeds [DET-3501]

- common/determined_common/storage/gcs.py
Uploading checkpoints to GCS fails intermittently, throwing a requests.exceptions.ConnectionError exception. The retry function retries the upload on a ConnectionError, which is different from requests.exceptions.ConnectionError. After adding this different exception type to the retry function, we see the checkpoints being uploaded successfully.
> fix: retry uploads on ConnectionError [DET-3358]

- common/determined_common/experimental/checkpoint/_torch.py
- harness/determined/_experiment_config.py
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_lr_scheduler.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/utils.py
This PR supports flexible primitives in Pytorch, i.e. supporting multiple optimizers and LR schedulers. It also modifies the current interface to be more Pytorch-y, making porting Pytorch models easier than before.
1. Users need to initialize the model, optimizers, and LR schedulers in the constructor of the trial class themselves as opposed to providing a callback for Determined to call in the old interface. Note that all the functions provided in the trial interface start with an underscore. These underscores will be removed when officially releasing this feature. They need to call the wrapping functions of the context object to wrap the model, optimizers, and LR schedulers.
2. Users need to run backward passes and perform one optimizer step for all the optimizers in the train_batch. …
> feat: support Pytorch flexible primitives [DET-3194, DET-3195, DET-3196, DET-3197, DET-3198]

- common/determined_common/experimental/checkpoint/_torch.py
- harness/determined/_experiment_config.py
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_lr_scheduler.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/utils.py
This reverts commit b860646dc887a4f01124d5862530b117382ccbdc.
N/A
N/A
N/A
> revert: support Pytorch multiple optimizers and LR schedulers

- common/determined_common/experimental/checkpoint/_torch.py
- harness/determined/_experiment_config.py
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_lr_scheduler.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/utils.py
In the new interface for this support, users need to initialize the
model, optimizers, and LR schedulers in the constructor of the trial
interface. They need to call the wrapper functions in the context object
to initialize these objects under distributed training settings.
They also need to initialize amp themselves.
Fixed a bug for https://github.com/determined-ai/determined/pull/707
Use the test suite.
N/A
> feat: support Pytorch multiple optimizers and LR schedulers

- master/Makefile
Because of how Make processes strings, the Segment keys were previously
being set to a string containing two quote characters rather than an
actual empty string.
> fix: don't set Segment key to quotes

- master/internal/api_experiment.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
- proto/src/determined/experiment/v1/searcher.proto
> feat: add preview search to new API

- examples/experimental/trial/flexible_primitives_mnist_pytorch/const.yaml
- examples/experimental/trial/flexible_primitives_mnist_pytorch/data.py
- examples/experimental/trial/flexible_primitives_mnist_pytorch/distributed.yaml
- examples/experimental/trial/flexible_primitives_mnist_pytorch/model_def.py
Add an example with multiple models and multiple optimizers with the new Pytorch primitives.
1. Manually train this model and check if it's successfully trained. Use TensorBoard to check on the generated images.
2. Have tested it with parallel training.
Please only review the second commit.
> docs: add example for Pytorch flexible primitives [DET-3202]

- cli/determined_cli/agent.py
- cli/determined_cli/checkpoint.py
- cli/determined_cli/cli.py
- cli/determined_cli/experiment.py
- cli/determined_cli/master.py
- cli/determined_cli/notebook.py
- cli/determined_cli/remote.py
- cli/determined_cli/shell.py
- cli/determined_cli/template.py
- cli/determined_cli/tensorboard.py
- cli/determined_cli/trial.py
- cli/determined_cli/user.py
- common/determined_common/api/__init__.py
- common/determined_common/api/authentication.py
- common/determined_common/api/experiment.py
- harness/determined/experimental/_native.py
This reverts commit 0c99a0cda9850543ee796c3e660c2c29f74c3c6a.
> revert: added cli logging to native.

- e2e_tests/tests/nightly/test_capability.py
- examples/experimental/trial/flexible_primitives_mnist_pytorch/const.yaml
- examples/experimental/trial/flexible_primitives_mnist_pytorch/distributed.yaml
- examples/experimental/trial/flexible_primitives_mnist_pytorch/model_def.py
Add nightly e2e test for pytorch flexible primitive example. Train only two steps.
N/A
N/A
> test: add nightly test for pytorch flexible primitive example [DET-3534]

- harness/determined/_trial_controller.py
- harness/determined/constants.py
- harness/determined/estimator/_estimator_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/ipc.py
- harness/determined/layers/_socket_manager.py
- harness/determined/pytorch/_pytorch_trial.py
Add an _allgather_metrics() method to EstimatorContext.  A followup-PR will either provide a useful API for calculating custom metrics that uses _allgather_metrics() or it will rename allgather_metrics() to be part of the (experimental) public API.
Part of this change involved replacing the ZMQServer and ZMQClient which are currently used as trial_controller.train_process_comm with ZMQBroadcastServer and ZMQBroadcastClient, since the ZMQServer and ZMQClient are not capable of allgather operations.  The existing behavior should not be affected at all by this change.
Manually ran python and estimator multi-machine dtrain experiments to verify the changes to those frameworks.
> feat: add allgather_metrics to EstimatorContext

- webui/tests/cypress/integration/01-setup.spec.ts
webui e2e-tests are getting blocked on the experiment cancelation step due to the experiment taking a while to pull a docker image. The pulling is taking longer than the 30 second cypress time limit on the response. The solution is to use the kill step instead.
Check for CI stability around webui e2e-tests. Specifically a reduction in test flakes for experiment cancelation, starting in `01-setup` test suite.
> ci: update webui e2e tests to kill experiment instead of cancel [DET-3543]

- docs/reference/api/pytorch.txt
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
As part of #remove-steps, we also need to remove the concept of steps from the `PytorchCallback`s API.
Currently, this is looking to be the only breaking change of #remove-steps. Everything else has been done by allowing new and old interfaces to coexist and deprecating the old ones. Open to suggestions on when/how to land this, or to leave the old interfaces intact and mark them as deprecated for at least a while.
> feat: remove steps from pytorch callbacks [DET-3252]

- harness/determined/estimator/_estimator_trial.py
- harness/determined/estimator/_util.py
- harness/determined/load/_load_trial_controller.py
It appears that using the PyTorch TensorBoard writer lead to TF events coming out in a "strange" state. 
Ran several experiments and observed that file naming changed from always having a file ending `1.0` to not having it, this file seemed to have been the cause of some of the issues. 
Going to test this out with a container that doesn't have TF.
> fix: use TF Tensorboard writer by default [DET-3353]

- cli/determined_cli/model.py
- common/determined_common/experimental/__init__.py
- common/determined_common/experimental/checkpoint/__init__.py
- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/determined.py
- common/determined_common/experimental/experiment.py
- common/determined_common/experimental/model.py
- common/determined_common/experimental/trial.py
- e2e_tests/tests/test_system.py
- master/internal/api_model.go
- master/static/srv/get_model_versions.sql
- proto/src/determined/api/v1/model.proto
Adds python and CLI methods for creating and querying model versions.
Added integration tests to cover new functionality.
> feat: model versions sdk and CLI [DET-3477] [DET-3480]

- webui/react/package-lock.json
> chore: fix low severity vulnerability from Lodash

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- e2e_tests/tests/config.py
- master/pkg/model/defaults.go
Upgrade the agent VM image to one built on top of a newer version of Ubuntu 16.04. This was motivated by a desire to mount a Lustre filesystem onto agent VMs, but the Lustre client requires a kernel version that is newer than what our base Ubuntu 16.04 image had.
The Docker contents did not change, but the change to the Environments repo changed the hash in the tag name, so we upgrade all references to the old hash to make the codebase consistent/easy to understand/easy to search.
This PR is a replacement to https://github.com/determined-ai/determined/pull/801, with the branch created from the main Determined repo so that we can manually trigger all tests.
> chore: upgrade agent VM image to newer kernel version

- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/SignIn.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/utils/data.test.ts
- webui/react/src/utils/data.ts
It's common to access a deeply nested property in an object but with multiple levels of optional properties. For example, one might need to access `window.obj.key1.key2` but both `key1` and `key2` are optional properties. `getOrElse` allows us to attempt to fetch the object property by full path with the option to specify a fallback value if nothing matches.
> refactor: add get-or-else support

- webui/react/src/components/ResourceChart.tsx
Disable and hide the figure options for resource chart.
> chore: remove figure options from plotly [DET-3572]

- cli/determined_cli/trial.py
- common/determined_common/api/experiment.py
- e2e_tests/tests/test_system.py
In order to make it more convenient to work with long trial logs, this
change makes it possible to request and view a given number of entries
from the start of a trial's log with the `--head` option.
There are other log-printing CLI commands that could conceivably have the same option added, but the request was for trial logs, and I imagine that that's by far the most important case anyway.
> feat: add `--head` option for printing trial logs [DET-3527]

- .circleci/config.yml
Enable multi node testing. Merge e2e GPU jobs in config.yml for circle CI.
Use the CI with the updated configuration to test if this works fine.
N/A
> ci: enable multi-node testing [DET-3444]

- cli/determined_cli/model.py
- common/determined_common/experimental/model.py
- e2e_tests/tests/test_system.py
Adds the register_version command and doc strings for autogenerated docs.
Integration tests cover changed code
> feat: model registry register_version CLI command [DET-3481]

- cli/determined_cli/cli.py
- cli/setup.py
Previously, the CLI used the standard library `ssl` module to store
unrecognized master certificates for future trusting, which only
supports extracting the leaf cert of the peer-provided chain [1]; it
therefore doesn't work well with internal CA setups, since Requests
needs but can't get the CA certificate. This shifts the logic to use
pyOpenSSL, which can extract the full chain and therefore satisfy
Requests's requests.
[1] https://bugs.python.org/issue18233
(The first case is what didn't work before; the others are just staying the same.)
Somewhat relevant: If you have a stored cert and _then_ attempt to connect to a server with a real CA-signed cert, the cert won't be recognized, since we override the normal CA bundle. But that isn't made worse by this PR, shouldn't be a common …
> fix: improve CLI's custom certificate handling [DET-3630]

- docs/how-to/distributed-training.txt
- docs/tutorials/data-access.txt
- harness/determined/_train_context.py
Add documentation around data access to the Distributed Training How-To Guide.
Briefly explain what ranks are and why data download directories should include the rank in their name. The motivation was that this is an important detail and was hidden in a subsection that distributed training users were unlikely to find.
- @shiyuann The ticket says to link to the examples, but I'm not sure what examples we are talking about. If you point me in the right direction, I will update this PR accordingly.
- The docs are clearer if you go through the How-To Guide, but the data access tutorial still doesn't highlight this info. Should we add a new section to the Data Access Tutorial that talks about DTrain?
> docs: add docs on data access for dtrain [DET-3506]

- common/determined_common/experimental/model.py
- docs/reference/api/experimental.txt
Adds generated api reference docs for the model registry.
Render and read the docs.
> docs: reference documentation for the model registry

- docs/reference/api/experimental.txt
This got added twice accidently, due to two concurrent PRs.
> docs: remove duplicate entry from API reference

- docs/reference/api/estimator.txt
- e2e_tests/tests/experiment/test_tf_estimator.py
- e2e_tests/tests/fixtures/estimator_dataset/distributed.yaml
- e2e_tests/tests/fixtures/estimator_dataset/model.py
- harness/determined/estimator/__init__.py
- harness/determined/estimator/_estimator_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/estimator/_reducer.py
- harness/tests/experiment/fixtures/estimator_linear_model.py
- harness/tests/experiment/tensorflow/test_estimator_trial.py
Introduce custom reducers for estimator trial.  From the docstring in the PR:
During distributed evaluation, many types of metrics calculated via ``tf.metrics`` or
``tf.keras.metrics`` cannot be aggregated properly from the per-slot final metrics
calculated by each separate Estimator replica. One example is ``tf.metrics.auc``, where
the ROC AUC calculated over predictions and labels from a full dataset cannot be derived
from a set of ROC AUC metrics evaluated over the shards of a dataset. However, with
``make_metric``, the ROC AUC could be calculated in distributed training by calling
``sklearn.metrics.roc_auc_score`` in a custom ``reducer`` function.
Lots of manual testing, in addition to adding a new unit test and a new parallel test.
> feat: add custom reducers to estimators [DET-3098]

- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/templates/master-deployment.yaml
- helm/charts/determined/templates/master-permissions.yaml
- helm/charts/determined/values.yaml
Added several missing configurations, made the k8 RP configurable, and added CPU and MEM request limits for the master.
Tested manually by deploying on a k8 cluster. Automated testing will be added as part of M4.
> feat: update helm chart for k8 RP [DET-3542]

- webui/react/src/components/LogViewer.tsx
Triggers when approximately within 50 pixels of the top of the scroll position.
> feat: update log viewer to load older logs when near the top [DET-3557]

- .circleci/config.yml
- cli/determined_cli/command.py
- cli/determined_cli/shell.py
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- e2e_tests/tests/config.py
- master/internal/command/summary.go
- master/pkg/model/defaults.go
- master/pkg/tasks/task.go
- master/static/srv/entrypoint.sh
- master/static/srv/sshd_config
Inject auxiliary passwd, shadow, and group files to augment the user
system inside the container.  This functionality depends on
libnss_determined being installed in the container.
This change also augments the command summary to include the
AgentUserGroup that each command is running with, and that information
is used by the CLI to choose the username when connecting to the sshd
server inside a shell container.
Finally, UsePAM was disabled in the sshd_config file, since the man page
explains that UsePAM is incompatible with running sshd as a non-root
user.  An alternate solution would be to run sshd as root but only
inject keys for the nonroot user, but that would have introduced the
following drawbacks:
- It might not have satisfied some security-sensitive organizations.
- It would not …
> fix: fix nonroot dtrain and nonroot shell [DET-3111]

- webui/tests/cypress/integration/02-navigation.spec.ts
follow up for https://github.com/determined-ai/determined/pull/878
we add this test to see if it runs into the same problem as with #878 
> test: add trial logs navigation test.

- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/checkpoint/_torch.py
- e2e_tests/tests/experiment/test_pytorch.py
Reverted a change to checkpoint export that was built to accommodate the flexible primitives API.  The checkpoint export API was heavily changed in that update, and we wanted more time to decide on if we want to move forward with that API.
Also reintroduced passing `**kwargs` into the `pytorch.load(..)` call when loading pytorch checkpoints.  This is most useful for the `map_location` argument, which was previously hard coded.
Tested manually with both new and old checkpoint formats.
> fix: restore previous checkpoint export functionality

- webui/react/src/services/decoder.ts
add support for parsing kubernetes log entries
```
045b68a5 [RUNNING] || 2020-07-20T15:35:38.548199278Z INFO: Running workload <RUN_STEP (100): (141,137,9)>
045b68a5 [RUNNING] || 2020-07-20T15:35:41.197537494Z INFO: Workload completed: <RUN_STEP (100): (141,137,9)> (duration 0:00:02.649047)
045b68a5 [RUNNING] || 2020-07-20T15:35:41.208223876Z INFO: Running workload <COMPUTE_VALIDATION_METRICS: (141,137,9)>
045b68a5 [RUNNING] || 2020-07-20T15:35:43.607370553Z INFO: Workload completed: <COMPUTE_VALIDATION_METRICS: (141,137,9)> (duration 0:00:02.398744)
045b68a5 [RUNNING] || 2020-07-20T15:35:43.620408964Z INFO: Running workload <CHECKPOINT_MODEL: (141,137,9)>
045b68a5 [RUNNING] || 2020-07-20T15:35:43.64517623Z INFO: Saved trial to checkpoint b5258099-0138-4ed7-9ff7-d01ee4b24ef0
045b68a5 …
```
> feat: add support for kubernetes trial log entries

- master/internal/agent/agent.go
- master/internal/core.go
- master/internal/kubernetes/informer.go
- master/internal/kubernetes/log.go
- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pods.go
- master/internal/kubernetes/volumes.go
- master/internal/scheduler/agent.go
- master/internal/scheduler/config.go
- master/internal/scheduler/container.go
- master/internal/scheduler/default_resource_provider.go
- master/internal/scheduler/default_resource_provider_test.go
- master/internal/scheduler/kubernetes_resource_provider.go
- master/internal/scheduler/task.go
- master/internal/sproto/default_resource_provider.go
- master/internal/sproto/kubernetes_resource_provider.go
- master/internal/sproto/resource_providers.go
- master/internal/trial.go
- master/pkg/agent/exit.go
- master/pkg/container/state.go
This PR support terminating tasks (killed by user, or by task handler). It also addresses a several corner cases including: 1) collision in pod names, 2) updating scheduler and task handler when an error occurs in the pod actor, 3) handle case where Kubernetes sometimes transitions pod statuses to pending while they are being deleted.
We are now reviewing #839 as part of this also. That included changes to track pod lifecycles and to processes logs. As part of this PR, I modified several message types that are part of the default RP as well, including `sproto.ContainerStateChanged` and `scheduler.TaskTerminated`.
<s>This PR is blocked by: #839 and #798. The last 5 commits are the new changes that make up this PR.</s>
Tested manually by spinning up a cluster. Automated testing will be …
> feat: support terminating tasks in k8 RP [DET-3418]

- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pods.go
- master/internal/kubernetes/volumes.go
We find all resources associated with the Determined label and delete them at start-up.
<s>This PR is blocker on #839 and #865. Only the last commit in this PR is part of this PR.</s>
Tested this manually by spinning up a k8 cluster.
> feat: clean up kubernetes resources on startup [DET-3421]

- docs/how-to/installation/aws.txt
- docs/how-to/installation/gcp.txt
- docs/how-to/installation/requirements.txt
- docs/reference/cluster-config.txt
Per suggestion from Angela Jiang.
> docs: add discussion of AWS and GCP quotas.

- master/internal/core_trial.go
- webui/react/src/components/LogViewer.stories.tsx
- webui/react/src/components/LogViewer.tsx
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/utils/browser.ts
This changes buffering of trial logs from backend to client (the browser) and should eliminate the server crashes we've seen when downloading large trial logs. Same trial logs could still crash the browser but not the server. (the browser has no official API for streaming to file system more info on the ticket)
We can probably achieve a better memory footprint maybe using something like http://asmjs.org/ or reading more into how JS engines internally allocate and handle memory for different calls but we should see if we want to invest more time here or not.
15643ms to buffer and download 3087007744 chars. total: ~3087007.744kB
client crashed at an attempt to buffer a 5GB Blob.
tested on chrome and firefox linux
we could look more into this and profile to see where we can get more wins. …
> feat: naive client-side trial logs download [DET-3521]

- CONTRIBUTING.md
I had to install `npm` to be able to build from source on a new machine. We also don't work with Python >= 3.8 right now.
> docs: tweak dev prerequisites

- master/internal/kubernetes/events.go
- master/internal/kubernetes/informer.go
- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pods.go
<s>This PR is blocker on #865 #873 #877 and #891. Only the last commit is part of this PR.</s>
As part of this PR, we add functionality to forward k8s event to the trial logs. This will improve users' observability into the state of their tasks.
Tested by running in a k8 cluster.
> feat: forward k8 events to task logs [DET-3549]

- master/pkg/tasks/copy.go
Change the determined whl's we copy to the harness from `*.whl` to `*$(VERSION)*.whl`.
This may be a naïve solution, but it seems just fine. The only thing I worry about is breaking some dev flow for the harness so that why I threw you on this, @aaron276h.
> chore: only copy current harness version to trial [DET-3681]

- webui/react/src/ioTypes.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
> fix: correct io-ts types

- webui/react/src/components/LogViewer.module.scss
- webui/react/src/components/LogViewer.tsx
There is a race condition between when new entries are fetched and when the scroll-to-latest button is clicked. What is considered the end or the bottom may differ due to timing. To address this, add a threshold of what is considered to be the "bottom" or the "end" so there is some flexibility so the tailing feature will continue to function even though the scroll-to-latest does not necessary hit the absolute end (threshold provided as the wiggle room).
> fix: fix scroll to latest entry [DET-3673]

- docs/how-to/installation/aws.txt
- docs/reference/cluster-config.txt
- docs/topic-guides/elastic-infra/dynamic-agents-aws.txt
- master/internal/provisioner/aws_config.go
We previously excluded G4s from the instance type whitelist; this commit
adds them to the whitelist and updates the documentation accordingly.
Note that the previous default agent AMI did not work with G4 instances.
The exact cause is unclear, but upgrading the Nvidia display driver from
410.104 to 450.51.05 appears to fix the problem (despite the fact that
Nvidia's docs claim that 410.104 supports T4 GPUs). The upshot is that
actually using G4 instances on AWS will require using an updated AMI.
**Testing**
I tested this by
* Launching a `g4dn.xlarge` using the current agent AMI
* Confirming that `nvidia-smi` did not work
* Upgrading the nvidia drivers on the instance
* Saving the instance state to a new AMI (`ami-07dda244ef15ff2eb`)
* Deploying a new Determined master with this PR
* …
> feat: Add support for G4 instances on AWS [DET-1771]

- .circleci/config.yml
- cli/tests/requirements.txt
This change manually installs `setuptools_scm` in CI before calling `pip install -r cli/tests/requirements.txt` to avoid a bug that occurs with packages that still rely on `setup_requires` in their `setup.py`.
This is the same issue described here: https://github.com/pypa/pip/issues/6133.
> chore: install setuptools_scm before pytest [DET-3709]

- master/go.mod
- master/internal/kubernetes/pod.go
This PR handles the case where we delete pods and k8s never send a `PodFailed` message to us, instead we only get a `PodPending` message. 
Tested this manually. Adding CI very soon!
> feat: handle missing PodFailed messages from k8

- agent/internal/agent.go
- master/internal/agent/agent.go
- master/internal/agent/agents.go
- master/internal/agent/proto.go
- master/internal/agent/slot.go
- master/internal/agent/slots.go
- master/internal/api_agents.go
- master/internal/command/api.go
- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pods.go
- master/internal/scheduler/default_resource_provider.go
- master/internal/scheduler/kubernetes_resource_provider.go
- master/internal/scheduler/resource_providers.go
- master/internal/sproto/resource_providers.go
- master/pkg/actor/api/api.go
Support task summaries and agents endpoints. As part of this PR we do not attempt to change the structure of endpoints to be more suitable for k8s, instead we fit the k8s RP to work with existing endpoints. This means there is no support for `agents/*` endpoints. 
To simplify integration with our actor system which routs api requests (for old api) by actor name, I added a forwarding mechanism which supports a preset actor name as the destination, instead of parsing the request path. 
<s>This PR is blocked on: #839, #865, #873, and #877. The last 3 commits is what makes up this PR. </s>
Tested this manually by spinning up a k8 cluster and doing `det agent list, det slot list, det task list`. Also verified that `/api/v1/agents` works via the Swagger UI.
> feat: support task and agent summaries for k8 RP [DET-3424, DET-3425]

- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pods.go
- master/internal/scheduler/kubernetes_resource_provider.go
This enables proxying for notebooks and Tensorboards. As part of this change we added support for parsing environment variables from strings to a map for the k8 RP. This was necessary to support Tensorboard. 
<s>This PR is blocked by: #839, #865, and #873. The last 3 commits are what make up this PR.</s>
Tested manually by spinning a k8 cluster.
> feat: support proxying for k8 [DET-3422]

- cli/tests/requirements.txt
- e2e_tests/tests/command/command.py
- e2e_tests/tests/conftest.py
- e2e_tests/tests/experiment/experiment.py
- e2e_tests/tests/experiment/test_native.py
- e2e_tests/tests/requirements.txt
- examples/tests/requirements.txt
- harness/determined/gpu.py
- harness/tests/conftest.py
- harness/tests/requirements.txt
- harness/tests/storage/test_s3.py
- harness/tests/storage/test_shared_fs.py
- harness/tests/test_gc_harness.py
- requirements.txt
pytest recently released major version 6.0. It introduces some
significant typing fixes. pytest 6.0 requires mypy==0.750, but is
actually developed against mypy==0.780.
This supports pytest 6.0 and explicitly requires pytest>=6.0.1 and
mypy==0.780.
CI should pass again.
> fix: fix make check

- cli/determined_cli/checkpoint.py
- cli/determined_cli/experiment.py
- cli/determined_cli/trial.py
- e2e_tests/tests/experiment/experiment.py
- master/go.mod
- master/internal/db/postgres.go
- master/internal/experiment_utils.go
- master/pkg/model/experiment.go
- master/static/migrations/20200729211811_extend-steps-table.down.sql
- master/static/migrations/20200729211811_extend-steps-table.up.sql
- master/static/srv/get_trial.sql
- master/static/srv/get_trial_metrics.sql
This change removes any references to the concept "step" in the CLI and replaces them with references to training workloads.
For `e2e_tests/tests/fixtures/single.yaml` with 300 batches:
```
(determined) ➜  no_op git:(remove-steps-demo) ✗ det e describe 4
Experiment:
Experiment ID | State     | Progress   | Start Time               | End Time                 | Description   | Archived   | Labels
-----------------+-----------+------------+--------------------------+--------------------------+---------------+------------+----------
4 | COMPLETED |            | 2020-07-30 13:56:52+0000 | 2020-07-30 13:56:57+0000 | noop_single   | False      |
Trials:
Trial ID |   Experiment ID | State     | Start Time               | End Time                 | H-Params …
```
> chore: remove steps from the CLI [DET-3625]

- harness/determined/gpu.py
Reproduced the breakage locally and confirmed that the change works correctly on gpu machines.
> fix: undo a mistaken edit from 'fix make check'

- cli/determined_cli/cli.py
- master/internal/api_experiment.go
- master/pkg/searcher/simulate.go
- proto/src/determined/experiment/v1/searcher.proto
This change updates the `det preview-search` functionality to work with the changes that removed steps from the UX of the system.
Once again, like #940, I put a very minimal amount of effort into fixing the CLI since it is throwaway code.
> feat: remove steps from preview-search [DET-3676]

- master/static/srv/get_checkpoints_for_experiment.sql
- master/static/srv/get_checkpoints_for_trial.sql
Add the `trial_id` field to get checkpoint queries.
> fix: include trial_id in get_checkpoints queries [DET-3732]

- webui/react/src/components/Table.tsx
- webui/react/src/pages/ExperimentList.table.tsx
Add column to Experiment list that uses a checkmark to indicate whether the Experiment is archived.
Tested manually.  
Tested sorting - when using descending order, `archived=True` is at the top.
I found a checkmark in Ant Design that I think looks good, but let me know if we want to go with Yes/No text for now.
> feat: add archived status column to Experiment list [DET-3540]

- master/internal/command/command.go
- master/internal/command/notebook_manager.go
- master/internal/command/tensorboard_manager.go
- master/static/srv/notebook-entrypoint.sh
Addresses the host mode networking issue where only a single notebook can start on an agent. This PR uses the same strategy as TensorBoards. We pick a random port per notebook within a range of ports. This is a mitigation. There is still a chance that 2 notebooks select the same port, although it is unlikely.
Manually verified that notebooks start on different ports.
> fix: use random port for notebooks [DET-3648]

- docs/faq.txt
- docs/reference/cluster-config.txt
- docs/reference/experiment-config.txt
- docs/reference/index.txt
- docs/topic-guides/checkpoints.txt
- docs/topic-guides/hp-tuning-det/hp-grid.txt
- docs/topic-guides/hp-tuning-det/index.txt
- docs/topic-guides/model-definitions/best-practices.txt
- docs/tutorials/quick-start.txt
Replace the original giant bulleted list with a collection of sections
and sub-sections. This should hopefully make it easier to find content
within this documentation page, to link to the documentation for
specific configuration variables, and to include more discussion about
particular configuration settings when appropriate.
Along the way, add a few examples and fix/rewrite some of the docs for
different variables.
> docs: reformat experiment config documentation.

- harness/determined/estimator/_estimator_trial.py
This is meant as a workaround for cases where TF ignores `gpu_options.visible_device_list`. 
Going to spin  up a cluster and take it for a spin.
> feat: support setting CUDA_VISIBLE_DEVICES for estimator_trial

- docs/tutorials/pytorch-mnist-tutorial.txt
- examples/experimental/trial/imagenet_nas_arch_pytorch/model_def.py
- examples/experimental/trial/mnist_pytorch_multi_output/model_def.py
- examples/official/native/native_mnist_pytorch/model_def.py
- examples/official/trial/cifar10_cnn_pytorch/model_def.py
- examples/official/trial/mnist_pytorch/model_def.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/tests/experiment/fixtures/pytorch_onevar_model.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
We do not need to have users call `reset_parameters`, except for very specialized models (where the user needs to call `reset_parameters` on their own regardless of our system).  It should therefore not be a part of our API, since it only clutters our API for 99% of users.
The reason we do not need to call it is that `reset_parameters()` (or some similarly-named equivalent... they're not all named the same) is called at the end of `__init__()` for every built-in `nn.Module` in PyTorch.
Found via `git grep -El 'def .*reset.*param'`:
Note that `_ConvNd.__init__()` is going to call the overridden
`_ConvBnNd.reset_parameters`, which is what the `hasttr(self, 'gamma')` hack is
going to protect against.
```python
class _ConvBnNd(nn.modules.conv._ConvNd):
def __init__(...): …
```
> chore: deprecate pytorch.reset_parameters [DET-3578]

- cli/determined_cli/model.py
- common/determined_common/experimental/model.py
- e2e_tests/tests/test_system.py
* "det model describe" failed for a model with no versions
* "det model describe --version k" ignored the "--version" argument
Manually ran the CLI before/after these changes.
> fix: fix bugs in "det model describe"

- cli/determined_cli/model.py
- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/model.py
- e2e_tests/tests/test_system.py
- master/internal/api_model.go
- proto/src/determined/api/v1/model.proto
Changes `version` to `model_version` in the REST API
Changes underscores to hyphens in the CLI
> fix: naming for model registry CLI commands and entities [DET-3767]

- master/internal/api_master.go
- master/internal/api_trials.go
- master/internal/grpc/validate.go
- master/pkg/logger/log_buffer.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/master.proto
a port of https://github.com/determined-ai/determined/pull/988
> feat: add master logs [DET-3680]

- master/internal/api_experiment.go
- master/internal/experiment.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
> feat: add experiment cancel and kill endpoints [DET-3581]

- e2e_tests/tests/nightly/test_capability.py
When we made the changes for remove steps, we did not fix tensorpack to be able to handle variable batches per workload - no matter what it is given it runs a full step. Because of this, the harness blows up when checking the length of batch metrics because tensorpack will in cases where the master decides to split a step, e.g. this test.
None, I saw this in parallel tests but missed it in nightly.
> chore: for tensorpack, max_length.batches must be a multiple of scheduling unit

- webui/react/src/pages/TrialLogs.tsx
Confirming the continuation of downloading trial logs will dismiss the modal instead of waiting for the download to complete first.
> fix: dismiss trial log download warning modal upon confirmation [DET-3779]

- master/internal/experiment.go
Currently, there is an assumption in the master that metrics be present in completed validations. This change makes this assumption explicit, rather than implicit, and changes what is now a panic to an error.
> chore: nil check validation metrics

- common/determined_common/experimental/determined.py
- master/internal/api_checkpoint.go
- master/internal/api_model.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/checkpoint.proto
- proto/src/determined/checkpoint/v1/checkpoint.proto
- proto/src/determined/experiment/v1/checkpoint.proto
- proto/src/determined/model/v1/model.proto
Singular get checkpoint endpoint. Accepts the uuid of the checkpoint and returns the entire checkpoint.
Manually tested the endpoint.
In the future we likely want checkpoint export methods to reference the new API endpoint.
> feat: get checkpoint endpoint [DET-3734]

- e2e_tests/tests/experiment/test_tutorials.py
- examples/tutorials/native-tf-keras/tf_keras_native_dtrain.py
The test before test_pytorch_parallel, tf_keras_native_dtrain, is failing causing it to fail. It's failing because it's looking for the wrong metric. This seems to have always be incorrect, but never been caught because the result wasn't properly checked.
```
Traceback (most recent call last): File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 215, in <module> main() File "/run/determined/pythonuserbase/lib/python3.6/site-packages/determined/exec/harness.py", line 211, in main build_and_run_training_pipeline(env) File …
```
>  chore: change search_metric to val_acc for tf_keras_native_dtrain 4bb2ab6 [DET-3794]

- agent/cmd/determined-agent/run.go
- agent/internal/agent.go
- agent/internal/options.go
This enhances the agent's configuration regarding use of TLS on the
master connection to better support a range of deployment scenarios:
- Verification can be turned on or off.
- A custom CA certificate chain can be specified.
- TLS can be toggled separately from TLS for the agent's own API.
This technically makes the agent config/CLI options
backward-incompatble; part of the previous `--tls` option is now
splitting into `--security-tls-enabled`. However, it is unlikely that
anyone was using that, since the system cannot currently be run fully
over TLS anyway.
The names for the CLI options are a bit long, but they conform to our usual pattern; I could remove a layer of nesting in the config structs and drop the `security-` from the options, but the current way matches the master.
This …
> feat: make agent's TLS verification level configurable [DET-3774]

- examples/tutorials/native-tf-keras/tf_keras_native.py
- examples/tutorials/native-tf-keras/tf_keras_native_dtrain.py
- examples/tutorials/native-tf-keras/tf_keras_native_hparam_search.py
In addition to downloading to non-unique places, we were downloading before submitting the experiment, which is wrong by itself.
This fixes an broken test.
Still passes tests.
> docs: apply our own best practices in tutorials [DET-3800]

- common/determined_common/experimental/checkpoint/__init__.py
- common/determined_common/experimental/checkpoint/_checkpoint.py
- common/determined_common/experimental/experiment.py
- e2e_tests/tests/test_system.py
- examples/official/trial/mnist_pytorch/const.yaml
- master/internal/api_experiment.go
- master/internal/api_model.go
- master/static/srv/get_checkpoints_for_experiment.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
- proto/src/determined/checkpoint/v1/checkpoint.proto
adds `/api/v1/experiments/id/checkpoints` which returns the checkpoints for an experiment.
Coverage via checkpoint export integration tests.
This will be accompanied by the same endpoint for trials to complete DET-3735
> feat: get checkpoints for experiment endpoint

- common/determined_common/experimental/trial.py
- master/internal/api_trials.go
- master/static/srv/get_checkpoints_for_trial.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/trial.proto
Adds `/api/v1/trials/id/checkpoints` which returns a list of checkpoints for the given trial.
Checkpoint export APIs use the new endpoint and therefore existing test cases provide coverage.
Depends on #1046
> feat: get checkpoints for trial endpoint [DET-3735]

- webui/react/src/components/Link.tsx
Fix the `Link` component to reroute using the internal router instead of triggering the loading of a new page.
> fix: trigger the correct click handler [DET-3817]

- e2e_tests/tests/test_users.py
Nonroot tests which previously could not expect exact matches on user or
group names are now able to expect exact matches, due to the
libnss_determined plugin in the container.
> test: make nonroot tests stricter

- .circleci/config.yml
> test: only send slack messages for master branch CI

- common/determined_common/storage/gcs.py
- common/determined_common/storage/hdfs.py
- common/determined_common/storage/s3.py
- common/determined_common/util.py
- harness/determined/tensorboard/gcs.py
- harness/determined/tensorboard/hdfs.py
- harness/determined/tensorboard/s3.py
- harness/determined/util.py
Lots of cloud storage APIs use the built-in random package RNG to do
automatic random backoffs, which affects the random state that we try to
preserve for ML reproducibility.
Take the heavy-handed solution, and just preserve the state for every
single StorageManager or TensorboardManager call that might affect the
RNG state.
Manually ran `test_gpu_restore` 20 times with GCS storage and 20 times with S3 storage; no failures.  Also manually hacked the `random` module to puke if it ever got called outside of a `preserve_random_state` context and ran with GCS + S3; no failures.
> fix: preserve rng state for all cloud access [DET-3810]

- webui/tests/cypress/support/commands.js
It seems like with cypress's whitelisting of the `auth` cookie, there is no guarantee that the cookie will be properly cleared under the testing environment. We currently have a url path check to confirm that the logout takes you to the sign in page, which should suffice. Simply removed the cookie check due to its flakiness.
Reference:
https://github.com/cypress-io/cypress/issues/5723
https://github.com/cypress-io/cypress/issues/5453
> fix: remove cookie check during logout because of flake [DET-3823]

- e2e_tests/tests/experiment/test_tf_estimator.py
test_dataset_restore tested functionality that we no longer have in the
system.  In reality, the test didn't even test that functionality when
it was written; it was a placeholder test for the right functionality
after a certain issue was addressed (DET-834, and arguably DET-836).
Because the test never really worked, nobody noticed when we removed the
dataset restoring functionality entirely.  But the test offers no real
coverage anymore.
None.
> chore: delete useless test

- e2e_tests/tests/fixtures/no_op/model_def.py
- e2e_tests/tests/test_system.py
- master/internal/trial_workload_sequencer.go
- master/internal/trial_workload_sequencer_test.go
This change fixes a bug in the trial workload sequencer were it is assumes that checkpoints won't fail. In the event of a failure checkpoint, a nil pointer is de-referenced  when trying to access checkpoint metrics that don't exist in a failure.
> fix: handle failed checkpoints correctly [DET-3853]

- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
#238  Description
Pagination is not shown when there is only one page worth of items or less (empty case as well).
> fix: hide table pagination when unnecessary [DET-3859]

- harness/determined/exec/tensorboard.py
The issue was related to us setting `AWS_REGION` to `None`.
Ran in us-east-1 and spun up multiple tensorboards.
> fix: support tensorboard in us-east-1 [DET-3842]

- master/internal/experiment.go
- master/internal/trial.go
- master/pkg/model/length.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/event_log.go
- master/pkg/searcher/event_log_test.go
- master/pkg/searcher/grid.go
- master/pkg/searcher/pbt.go
- master/pkg/searcher/random.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/searcher.go
- master/pkg/searcher/sha.go
- master/pkg/searcher/simulate.go
- master/pkg/searcher/tournament.go
This change alters trials to report units completed as a `float64` so that partial units can be reported correctly. Previously, if the searcher was configured in terms of epochs and anything less than an epoch was completed in a workload, the reported completed `model.Length` was rounded to the nearest epoch; this usually ends up being 1 (except in the case of unusually small epochs or unusually large scheduling units) and makes progress appear completely wrong.
The weird thing about "add a unit test that checks searcher progress with records, batches and epochs" is that when an experiment completed we destroy the progress, so it seems impossible to write without being _super_ flaky.
> fix: record progress in partial units [DET-3869]

- webui/react/config-overrides.js
- webui/react/src/components/CreateExperimentModal.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/types.ts
- webui/react/src/utils/types.ts
- add continue trial form
- migrate from max_steps to max_length
old experiment config:
after config upgrade:
> chore: migrate continue trial form and remove steps [DET-3780 DET-3854]

- cli/determined_cli/shell.py
- cli/determined_cli/tunnel.py
- common/determined_common/api/request.py
- e2e_tests/tests/command/test_shell.py
- e2e_tests/tests/test_users.py
- master/internal/command/shell_manager.go
- master/internal/core.go
- master/internal/proxy/proxy.go
- master/internal/proxy/tcp.go
Add a CONNECT handler to our Echo framework.  The new handler is part of
the old proxy, which now supports proxying raw TCP trafic as well as
HTTP and websocket traffic.  The tunneled traffic is plaintext
naturally, but it is TLS-encrypted between master and client if
connecting to the master over TLS, and it is also end-to-end
ssh-encrypted for all `det shell` traffic.
Introduce an executable determined_cli.tunnel module, which will tunnel
its stdin and stdout through an HTTP CONNECT proxy, exactly the way
`nc -X CONNECT -x` would work, but without introducing an external
dependency on netcat.
Fix `det shell` to add a ProxyCommand="..." option to the ssh invocation
so that ssh calls the determined_cli.tunnel tool to tunnel traffic
though the master.
This fix allows shells to work in …
> fix: proxy shell through master via HTTP CONNECT

- master/internal/trial_workload_sequencer.go
- master/internal/trial_workload_sequencer_test.go
This change fixes a bug where a very small adaptive searcher, in which the first rung is less than one batch, would end up requesting to run zero batches because we decided in to round down to the nearest batch when using records or epochs. We now round down usually, but round up if the searcher requested we run a quantity less than the trial's global batch size.
> fix: run atleast one batch per searcher op [DET-3877]

- harness/determined/_env_context.py
- harness/determined/_local_execution.py
- harness/determined/exec/harness.py
- harness/determined/layers/_socket_manager.py
- harness/tests/experiment/utils.py
- harness/tests/tensorboard/test_util.py
- harness/tests/test_horovod.py
- master/internal/core.go
- master/internal/scheduler/default_resource_provider.go
- master/internal/scheduler/kubernetes_resource_provider.go
- master/internal/scheduler/resource_providers_test.go
- master/internal/trial_test.go
- master/pkg/tasks/copy.go
- master/pkg/tasks/task.go
- master/pkg/tasks/task_spec.go
This change allows experiments to be run with all communication to the
master going over TLS.
Since the containers are spawned by the master itself, we don't need to
allow for verification to be skipped or have any separate manual
configuration; the master injects its own certificate into each
container spec, and the client code picks it up.
Technically, the separate "use TLS" and "master cert file" options in the harness are redundant, since currently they're only set at the same time. But making it that implicit feels like going a bit too far.
If you can come up with a better way to thread the cert from the master config down to the task specs, I'm all ears.
It would be nice to be able to place the cert in the container so that it's automatically picked up at a system level. I don't see …
> feat: allow the harness to connect to the master over TLS [DET-3775]

- cli/determined_cli/shell.py
BREKING CHANGE: Change the format of the ssh options arguments to
`det shell start` and `det shell open`.  Instead of calling:
det shell start --ssh-opt "-XY -o SomeOption='some string'"
which has multiple layers of quotes due to a two-step shell tokenizing,
now users should call:
det shell start -- -XY -o SomeOption="some string"
This change also allows us to clean up our internal implementation to
avoid relying on shell tokenization internally.
> feat: improve shell cli for optional args [DET-3883] [DET-3886]

- cli/determined_cli/tunnel.py
This change updates the tunneling helper script to allow proxying shell
connections to work when the master is listening on TLS. The main change
is a new HTTP connection class that applies TLS to the entire
connection; the standard library class makes the CONNECT request
unencrypted and only applies TLS to the proxied connection, which
doesn't make much sense for us.
To allow the copier thread to easily work with SSL sockets (which don't
have a useful fileno), normal sockets (which don't have read/write
methods), and stdin/stdout, there's also a class that wraps sockets to
provide read/write methods.
> fix: let shell proxying work with master TLS [DET-3882]

- master/internal/agent/agent.go
This PR adds logging to enable to track agent usage in an offline manner.
Log messages added:
```
determined-master  | INFO[2020-08-18T13:28:21Z] agent connected ip: 172.31.43.136 slots: 8    id=i-061172e664f7c82de system=master type=agent
determined-master  | INFO[2020-08-18T13:28:30Z] starting container id: 839d0f7d-c1c9-4124-8933-9210295f9864 slots: 1 task handler: /notebooks/f55c0380-ae30-4e9c-91d9-7a15a28545b2  id=i-061172e664f7c82de system=master type=agent
determined-master  | INFO[2020-08-18T13:28:45Z] starting container id: fd964d08-4206-4b20-aefa-ce7293872e9b slots: 1 task handler: /experiments/8/54f63b44-bf25-4a9f-9757-cd64c632fe48  id=i-061172e664f7c82de system=master type=agent
determined-master  | INFO[2020-08-18T13:29:21Z] stopped container id: …
```
> feat: add logging to agent to track usage [DET-3878]

- deploy/determined_deploy/aws/aws.py
- deploy/determined_deploy/aws/cli.py
det-deploy aws did not properly handle stack deletions. 
Manually tested creating and terminating stacks.
> fix: handle failed stack deletion

- docs/reference/cluster-config.txt
- master/internal/command/api.go
- master/internal/command/tensorboard_manager.go
- master/internal/config.go
- master/internal/core.go
- master/internal/proxy/proxy.go
- master/internal/scheduler/default_resource_provider.go
- master/internal/scheduler/kubernetes_resource_provider.go
Idle TensorBoard instances are spun down after a configurable amount of time (via master.yaml). Adds `LastRequestedTime` to the services registered in the proxy. The tensorboard manager calls itself on a tick. Every 5 seconds it checks for TensorBoard instances that haven't received traffic after the configured amount of time. These instances are killed.
Manually tested using local browser.
> feat: kill idle tensorboards [DET-3808]

- harness/determined/_experiment_config.py
- harness/determined/estimator/_estimator_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_context.py
Users have asked for the ability to perform dataset sharding themselves. Previously this was only supported via `data: dataflow_to_tf_dataset` in EstimatorTrial which was a hack.
> feat: make sharding configurable in wrap_dataset

- master/internal/experiment.go
- master/internal/trial.go
This change fixes a regression introduced within the development for 0.13.0. There was a decision made in #infra-ag to always checkpoint before searcher requested validations. In the event that we're running adaptive and that validation causes a promotion decision, we have to do this for consistency and reproducibility. Changing this order broke existing, implicit behavior in the trial actor. For example, if an asha trial is running and completes a validation that results in its promotion, on old versions of the master (<= 0.12.13) a preclose checkpoint workload would be issued. While the trial is performing this checkpoint workload, the searcher is able to synchronize the operations is wants the trial to do with the trial. On the current version of the master (0.13.0.dev0), since there …
> fix: add explicit searcher sync before close trial [DET-3889]

- docs/reference/api/keras.txt
- docs/reference/experiment-config.txt
- docs/tutorials/pytorch-mnist-tutorial.txt
- docs/tutorials/tf-mnist-tutorial.txt
- examples/official/trial/fashion_mnist_tf_keras/adaptive.yaml
- examples/official/trial/fashion_mnist_tf_keras/const.yaml
- examples/official/trial/fashion_mnist_tf_keras/distributed.yaml
- examples/official/trial/mnist_pytorch/distributed.yaml
- harness/determined/keras/_data.py
- harness/determined/keras/_tf_keras_context.py
- harness/determined/keras/_tf_keras_trial.py
* Clarify docs on epoch boundaries
* Fix epoch size in Fashion MNIST example
* Make wrapper requirements more clear
* Better linking to API reference.
> docs: various fixes for tf.keras docs.

- docs/release-notes/README.md
> chore: Add README for new proposed release note process.

- harness/determined/tensorboard/base.py
- harness/determined/tensorboard/gcs.py
- harness/determined/tensorboard/s3.py
- harness/determined/tensorboard/shared.py
The base tensorboard manager only identified tfevents files in the top level log directory. This change makes the search recursive to support subdirecties.
Manually tested by uploading tfevents containing images to a subdirectory.
> fix: recursively search log dir for tfevents [DET-3915]

- master/pkg/tasks/copy.go
The master certificate file must be readable even for a non-root task,
of course.
> fix: make master cert file world-readable in containers

- agent/internal/containers.go
If the master is listening over both TLS and non-TLS, it will send TLS
connection information to all containers, since it doesn't keep track of
whether each agent connected over TLS or not. But an agent that
connected over non-TLS would then create a task that tried to use TLS on
the non-TLS port, which would fail.
This updates the agent to avoid that by forcibly disabling TLS when the
agent itself didn't use it. It's a bit of a hack, but the mixed
TLS/non-TLS will soon be made impossible on the master side anyway.
> fix: better handle tasks with mixed TLS/non-TLS masters

- master/pkg/searcher/asha.go
- master/pkg/searcher/asha_test.go
Progress is calculated incorrectly for brackets with a single rung since metrics are never added to the top rung.  This is fixed by adding metrics to the top rung when validationCompleted is called.  Note that this issue was not exposed through our adaptive_asha experiments because aggressive and standard mode would rarely run a bracket with a single rung.  
I tested manually with the experiment config in https://determinedai.atlassian.net/browse/DET-3914 and also added an edge case test to asha_test.go.
> fix: asha searcher progress for brackets with one rung [DET-3914]

- agent/internal/agent.go
- master/pkg/actor/api/ws.go
Currently, the names of the websocket actors leads to uninformative logs. Improve naming to be consistent across agent/master and to be more descriptive.
Old:
```
determined-master  | INFO[2020-08-19T00:14:23-07:00] Creating actor       actorCreated=/agents/Armands-MBP.attlocal.net actorType="*agent.agent" logType=ActorEvents
determined-master  | INFO[2020-08-19T00:14:23-07:00] Creating actor       actorCreated=/agents/Armands-MBP.attlocal.net/37ca9e2f-12fb-4fec-8c11-fefea285b0f9 actorType="*api.websocketActor" logType=ActorEvents
determined-agent   | INFO[2020-08-19T00:14:23-07:00] Creating actor       actorCreated=/agent/socket actorType="*api.websocketActor" logType=ActorEvents
```
New:
```
determined-master  | INFO[2020-08-19T00:17:34-07:00] Creating actor …
```
> chore: rename websocket actors to be more descriptive

- master/internal/command/shell_manager.go
- master/static/srv/shell-entrypoint.sh
In k8s, the files we inject into the container are injected via
individual file-level bind mounts, which are effectively read-only in
docker.
As a result, shell-entrypoint.sh was unable to edit the authorized_keys
file in place, so it is now injected as authorized_keys_unmodified and
the modified version is written at runtime.
> fix: support shell with k8s

- master/internal/grpc/api.go
- master/internal/grpc/auth.go
We previously had an interceptor in place to ensure authentication for
unary gRPC endpoints, but it was missing for stream endpoints, allowing
stream endpoints to be accessed by anybody.
> fix: apply user authentication to stream endpoints [DET-3935]

- master/internal/api_experiment.go
- master/internal/db/postgres.go
This change changes `/api/v1/experiments/1/unarchive` and `/api/v1/experiments/1/archive` to not load the entire experiment configuration when trying to check if an experiment is valid to be archived or unarchived. Without this, experiments whose configurations have been around through breaking changes cannot be archived.
> fix: refrain from loading experiment configs where they aren't needed

- master/pkg/model/experiment_config_test.go
- master/pkg/model/hyperparameters_config.go
- master/pkg/model/hyperparameters_config_test.go
This change adds validation to the `hyperparameter` configuration section, to check if `global_batch_size` has been specified and if it is numeric.
Before remove steps, we didn't use the hyperparameters in the master at all. Now we use `global_batch_size`, so we should check if it exists first.
> fix: validate hyperparameter configs

- common/determined_common/experimental/model.py
- master/internal/api_model.go
- proto/scripts/swagger.py
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/model.proto
It is unclear why this changed, however patch requests weren't parsing the request body. The update mask was automatically filled in though. I suspect something in the grpc reverse proxy is to blame but wasn't able to root cause this issue. This PR offers the same functionality as before but uses the `body: "*"` request parsing.
Adding a better E2E test as a follow on.
> fix: patch request body parsing for model metadata [DET-3939]

- agent/internal/agent.go
- agent/internal/containers.go
- common/determined_common/api/request.py
- master/pkg/tasks/task.go
This passes the same file and environment variables that we use for the
harness to command containers (which includes shells and notebooks (and
TensorBoards, though those won't actually use this)) to allow our Python
code within them to correctly connect to a master using TLS, including
the case of a custom certificate.
Having to handle the cert specially inside the container in the client
code is somewhat annoying, but I don't know of a way to install it
generally when we don't necessarily have root in the container.
> feat: allow Python libraries in commands to use TLS for the master [DET-3899]

- .github/pull_request_template.md
- docs/release-notes/README.md
- Improve release note instruction.
- Update the PR template to remind developers to include release note in their PR.
N/A
Didn't use exclude pattern because we need to include the release note file in building for grammar and reference validation.
> docs: improve release note instruction

- docs/release-notes/1112-fix-keras-wrap.txt
- harness/determined/estimator/_estimator_context.py
- harness/determined/keras/_tf_keras_context.py
Previously, we return the wrapped model for both training and
model exporting. When training, the wrapped model is designed
to get the arguments of users' call on compile and fit. However,
when exporting checkpoints, users expect to get the original model.
So fix wrap_model to be no-op when not training.
Use the CI suite.
N/A
> fix: return the original tf.keras model when not training. [DET-3718]

- docs/faq.txt
- docs/release-notes/1114-ensure-proper-wrapping.txt
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
Users might not refer to the wrapped optimizer when creating an LR scheduler. We used to have checks in `wrap_lr_scheduler` but not in the backward compatibility code with the old API. This PR fixes that and adds a debugging FAQ to the Pytorch trial documentation for those kind of issues.
Use the CI test suite.
N/A
> fix: ensure properly wrapping in pytorch. [DET-3745]

- webui/react/src/components/CheckpointModal.tsx
- webui/react/src/fixtures/trialdetails-2994.json
- webui/react/src/ioTypes.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/task.ts
- webui/react/src/utils/types.ts
- tested with the offending trial detail response.
- revert d3384e2cfd9793bad602c032f1a0d62689b6562a
> fix: fix task openability check and a trial detail decoder mismatch [DET-3924 DET-3937]

- master/pkg/model/experiment_config.go
- master/pkg/model/experiment_config_test.go
This change adds validation to ensure records_per_epoch is supplied when a configuration is in terms of epochs.
> fix: validate records_per_epoch exists when epochs are used

- docs/release-notes/1140-fix-archive-pagination.txt
- webui/react/src/components/Table.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/utils/task.ts
There is a limit filter that is applied to experiment and task list tables. This is actually reserved for future filtering with the new list api endpoints, but they are prematurely being used. Removing the corresponding `slice(0, limit)` corrected the behavior. 
- Pagination only appears when there are at least 10 items.
- Once there are 10 items, pagination including a page size picker appears.
- Even when the page size is set to a number higher than the number of items (meaning all the entries can fit on one page), the pagination and the page size picker persists. This is to ensure that the page size picker can stick around to let the user chang the page size to something smaller. The pagination is directly tied to the page size picker, they are grouped as a single component so they can …
> fix: enable pagination size picker when entries are at least 10 count [DET-3931]

- master/internal/experiment.go
- master/internal/scheduler/fitting.go
- master/internal/scheduler/fitting_test.go
- master/internal/trial.go
This change allows the scheduler to fit multiple dtrain jobs to a single node. There was spike work done to ensure horovod can handle this.
Previously `findFits` was divided into `findSingleSlotFit` and `findMultiSlotFits`. This seems to be rooted in 1-slot tasks all being scheduled the same, where n-slot tasks were scheduled differently whether they were experiments or other tasks. I changed this to `findSingleAgentFit` and `findMultiAgentFits` because now all n-slot tasks are scheduled this same, where n fits on a single agent, and n-slot tasks, where n does not fit on a single agent, are only scheduled when they are experiments (as indicated by `SingleAgent: false`).
See [Release Note](../docs/release-notes/README.md) for details. (To be done as a part of the corresponding docs PR) …
> feat: change scheduler to allow multiple dtrain jobs per node [DET-3819]

- master/internal/trial.go
- master/pkg/tasks/task.go
- master/pkg/tasks/task_spec.go
This change updates the trial <-> scheduler relationship by adding a field `IsMultiAgent` to the task spec. This field is used to indicate when a container is started whether its default networking mode should be overriden. This distinction is because this should be the case for distributed training but not parallel.
With an experiment config for 2-slots per experiment (on mnist_pytorch):
Run 4 copies concurrently with a single 8-slot gpu:
Full utilization:
They all complete and converge:
Seems simple enough?
> feat: override trial network mode to host only when multi-agent [DET-3820]

- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/values.yaml
- master/internal/command/api.go
- master/internal/command/command.go
- master/internal/command/command_manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/core.go
- master/internal/core_experiment.go
- master/pkg/model/environment_config.go
- master/pkg/model/task_container_defaults.go
The default specified in the `master.yaml` can be overwritten on a per-task granularity. Docs for this 
change will be done as part of [DET-3905](https://determinedai.atlassian.net/browse/DET-3905).
Spun up a cluster and tried out different combinations of default configs.
> feat: support default gpu and cpu pod specs in master.yaml [DET-3942]

- cli/determined_cli/cli.py
- cli/determined_cli/command.py
- cli/determined_cli/experiment.py
- cli/determined_cli/template.py
- common/determined_common/__init__.py
- common/determined_common/api/experiment.py
- e2e_tests/tests/config.py
- e2e_tests/tests/experiment/experiment.py
- e2e_tests/tests/experiment/test_noop.py
- e2e_tests/tests/test_users.py
Inexplicably, sometimes ruamel.yaml is pacakged as ruamel_yaml instead.
> fix: support alternate ruamel packaging.

- docs/release-notes/1172-fix-dashboard-limit.txt
- webui/react/src/pages/Dashboard.tsx
**BUG FIX**
- Reapply the filtering for just the dashboard recent tasks. The limit filter was previously removed from the experiment and task list since they naturally get filtered through pagination. This affected the dashboard limit filtering, since it still relied on the filtering. 
> fix: apply filter limit to dashboard [DET-3973]

- master/internal/scheduler/default_resource_provider.go
- master/internal/scheduler/kubernetes_resource_provider.go
- master/internal/scheduler/resource_providers.go
As part of this PR added a scheduling tick to the k8 RP similar to the one we have in default RP.
Tested manually by spinning up a cluster and running adaptive experiments with and w/o MaxSlots set.
> feat: support MaxSlots in k8 RP [DET-3830]

- docs/release-notes/1176-fix-adaptive-asha-progress.txt
- master/pkg/searcher/asha.go
This change removes the code from asha calls to `trialExitedEarly`, since `trialClosed` is still called for early exit calls and this causes trials to get counted as completed twice.
> fix: don't double count failed trial completions [DET-3986]

- webui/react/.eslintrc.js
- webui/react/src/components/AuthToken.tsx
- webui/react/src/components/CreateExperimentModal.tsx
- webui/react/src/components/DeterminedAuth.tsx
- webui/react/src/components/LogViewer.tsx
- webui/react/src/components/ProgressBar.tsx
- webui/react/src/components/ResourceChart.stories.tsx
- webui/react/src/components/ResourceChart.tsx
- webui/react/src/components/Section.tsx
- webui/react/src/components/StateSelectFilter.tsx
- webui/react/src/components/TagList.tsx
- webui/react/src/components/TaskFilter.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/Cluster.tsx
- webui/react/src/pages/Dashboard.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentActions.tsx
- webui/react/src/pages/TaskList.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialActions.tsx
- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/themes.ts
Add the following rules:
- `object-curly-newline`
- `react/jsx-first-prop-new-line`
- `react/jsx-max-props-per-line`
The JSX rules will help us add fixable structuring to our JSX.
> style: add more React focused linting

- Makefile
- docs/Makefile
- docs/reference/api/estimator.txt
- docs/release-notes.txt
- docs/requirements.txt
We lacked a tool for formatting our reStructuredText files the way we
have for Python and Go; this adds configuration and Makefile targets for
using such a tool that I developed.
Several people recently expressed an interest in adding this sort of thing, so I finally got around to making this PR after having the pieces sitting around for a while.
Because of the rather experimental status of [`rstfmt`](https://github.com/dzhu/rstfmt), I'm not yet adding a corresponding `check` target; that way, we don't get blocked if something goes wrong with it. If it looks good for a while, I'll add that later.
(That also means I can leave the actual formatting changes out of this PR so that we can keep them separate from the config changes and not have to squash them together.)
> docs: configure `rstfmt` for formatting docs files [DET-3784]

- harness/determined/_env_context.py
- harness/determined/_local_execution.py
- harness/determined/_trial_controller.py
- harness/determined/constants.py
- harness/determined/exec/harness.py
- harness/determined/layers/_worker_process.py
- harness/tests/experiment/utils.py
- harness/tests/tensorboard/test_util.py
- harness/tests/test_horovod.py
- master/internal/kubernetes/spec.go
- master/internal/scheduler/fitting.go
- master/internal/trial.go
- master/pkg/tasks/ports.go
- master/pkg/tasks/task.go
- master/pkg/tasks/task_spec.go
This change adds the environment variable `DET_TRIAL_UNIQUE_PORT_OFFSET` to the harness. The master supplies this to the harness and it is guaranteed to be unique for each trial on an agent - for any trial, it will be equal to `min(deviceIds)` that the trial is assigned, so since different trials on the same agent will never share devices the value will be distinct for each trial. 
4 concurrent host-mode experiments 2-slot in host mode
they converge:
> feat: support multi-dtrain single-node in host mode [DET-3821]

- .circleci/config.yml
If parallelization is too high, some test runners fail due to not
actually having any tests to run.
> ci: reduce e2e-cpu parallelization

- master/pkg/model/experiment_config_test.go
Because the default random seed is determined by the time, once in a great while these tests will fail due to the experiment configs being created at different times.
One example is here: https://app.circleci.com/pipelines/github/determined-ai/determined/5069/workflows/5c3e9bf7-985b-49be-8e94-5562f53b4912/jobs/128772
> test: fix flake with experiment_config_test

- master/static/srv/shell-entrypoint.sh
The HOME variable was always set to / for non-root shells, when sshd should be setting it.
While we are at it, we might as well filter out several other environment variables which I think ought not to be passed in this way at all.
> fix: don't pass all environment variables through sshd

- master/internal/trial_workload_sequencer.go
This change changes how `sequencer.snapshotState()` is called when the trial workload sequencer completes a checkpoint. Previously, if the checkpoint was a searcher requested checkpoint (e.g. PBT), we did not snapshot the opIdx being incremented, so a failure between that checkpoint and the next searcher op being completed would result in us redoing the checkpoint.
> chore: update trial workload sequencer to ensure all state is snapshotted after a checkpoint

- webui/react/src/contexts/AppContexts.tsx
- webui/react/src/contexts/Users.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/types.ts
- webui/react/src/utils/task.ts
- webui/react/src/utils/types.ts
Currently in the React code there is both a User type and an Owner type that are very similar. This PR standardizes the naming convention by changing the types to User and DetailedUser
Tested as much as I could manually. I tried to hit all of the relevant endpoints and can't find anything broken.
One thing that is difficult to review: I renamed `User` to `DetailedUser` and `Owner` to `User` and I also converted some functions that did not need user details to use the less detailed type. This means that they were originally typed with `User`, they were then changed to `DetailedUser` as part of the renaming and then the were changed to use `User` (previously known as `Owner`) because they only needed the id/username. These examples don't show up in the diff at all. 
For example, this …
> chore: convert owner to user in react code [DET-3519]

- cli/determined_cli/render.py
Somehow I missed one earlier.
To verify this was the last one, I grep'd for `ruamel` and didn't see anything.  But... I swear that's what I did before as well.
> chore: remove a direct ruamel import

- docs/release-notes/1201-fix-loading-old-tensorboards.txt
- master/internal/command/tensorboard_manager.go
- master/internal/db/postgres.go
- master/pkg/searcher/event_log_test.go
This change changes the `newTensorboard` code path to only load the parts of the experiment configuration that it needs, so that old tensorboards can still be loaded.
Tested by running `det-deploy local cluster-up --det-version 0.12.13` and an experiment that writes to tensorboard, followed by upgrading to 0.13.1.dev, checking the version, and ensuring the tensorboard still runs.
This is really hacky, but there's not really a good non-hacky way that doesn't in some regards basically do the experiment configuration project partly. If anyone has a huge problem with this, I can make some new model structs with only the fields that this needs and write new queries to load them.
[DET-1234]: …
> fix: fix loading tensorboard from prior versions [DET-4008]

- docs/release-notes/1116-sys-exit.txt
- harness/determined/__init__.py
- harness/determined/_execution.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/exec/harness.py
- harness/determined/exec/worker_process.py
- harness/determined/experimental/_native.py
- harness/determined/gpu.py
- harness/determined/ipc.py
- harness/determined/load/_load_implementation.py
Catch SystemExit and error out.
N/A
N/A
> fix: catch SystemExit and error out [DET-2956]

- master/internal/kubernetes/events.go
- master/internal/kubernetes/pod.go
Previously, kubernetes pod events were difficult to interpret and essentially meaningless to data scientists. This change allows the events handler to intercept and modify certain events to be more human readable. The following events have been modified:
`x/y nodes are available: ...`   --> `Waiting for Resources. x GPUs available, y GPUs required.`
`pod triggered scale-up`        --> `Job requires additional resources, scaling up cluster.`
`Successfully assigned`.        --> `Pod resources allocated.`
`skip schedule deleting pod` --> `Deleting unscheduled pod.`
Manually tested by launching a kubernetes cluster and making sure that the logged pod events were properly replaced.
[DET-1234]: …
> feat: modify k8 events to be more understandable [DET-3172]

- docs/release-notes/1171-has-validation-filter.txt
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/pages/TrialDetails.tsx
After discussion with @vishnu2kmohan. Decided it's best to separate out the controls for `Has Checkpoint` and `Has Validation`. The select dropdown works to enable each filter independently or have the joint behavior to be an `OR` (opposed to the default and assumed `AND` behavior).
Update the `Has Checkpoint` filter on the trial details table to `Has Checkpoint Or Validation` filter. If the trial batches has a checkpoint or a validation, it will show up when the filter toggle is enabled.
Add the ability save filter states to user preferences. The `Has Checkpoint Or Validation` will get applied across all trial detail pages, while the `Metrics` filter save on a per unique experiment trial. If the user selects metrics X, Y and Z on trial 1 of experiment 1, when they visit trial 5 of …
> feat: has validation filter [DET-3962]

- cli/determined_cli/tensorboard.py
- docs/how-to/tensorboard.txt
- docs/reference/command-notebook-config.txt
- master/internal/command/tensorboard_manager.go
- tools/run-server.py
Allow a yaml file to be passed as an argument into the tensorboard start command, providing the option of running tensorboard in different container types. Additionally adds the `config` arg to print the config of a specified tensorboard.
Tested manually. Tensorboard uses a cpu-only container by default, so specify a config file that uses a different container type (e.g. a gpu container). Use `det tensorboard config tensorboard_id` to verify that the specified container is being used.
> feat: support config file for tensorboard [DET-3900]

- docs/release-notes/1213-set-default-session.txt
- harness/determined/estimator/_estimator_trial.py
By setting the default session before we import any user code,
if users call any TF code that detects GPUs, we prevent these
calls from causing issues when we pin processes to individual GPUs.
Inserted: 
```
from tensorflow.python.keras.backend import _get_available_gpus
gpus = _get_available_gpus()
```
in different parts of user code, and confirmed that w/o this fix we see same issues as before (N processes per GPU) and with this fix we see only one process per GPU and no other issues.
> fix: set default TF session in EstimatorTrial

- master/internal/kubernetes/request_queue.go
- master/internal/kubernetes/request_queue_test.go
- master/internal/kubernetes/request_workers.go
Previously, if a deletion was requested while a creation of that resource was still in progress, it was possible that we would try and execute the deletion before the creation.
Added unit tests and tested manually as well.
> fix: address corner case in k8s resourceQueue [DET-4053]

- e2e_tests/tests/experiment/experiment.py
- master/internal/trial.go
This PR fixes a deadlock in the trial actor. It happens when a trial is terminated gracefully and the trial containers are still starting. Before all the trial containers are started, the trial would not send the rendezvous information, which blocks trial containers sending back completed workload messages. This issue exists on both the default and k8s resource providers. In the default resource provider only when the instances are launched. However, on k8s, containers are started one by one. There might be a situation that some containers would never start up. This PR adds a timeout for all graceful trial terminating and directly handles as killing if not all containers are connected.
The solution is to check if all containers are ready when gracefully terminating it. If not, rather than …
> fix: fix a deadlock when gracefully terminate a trial [DET-3879]

- master/internal/api_experiment.go
Noticed this working on another endpoint.
> fix: support loading old exp confs from GET /api/v1/experiment

- master/internal/db/postgres.go
- master/internal/db/static_query_map.go
This change locks concurrent access to the queries map in `db.PgDB`. Technically two concurrent queries could come in, both see the value doesn't exist, and both populate it (the entire critical section isn't locked), but they would overwrite each other with the same value and the write lock stops the go runtime from barfing over concurrent map writes. I think being able to use `RLock` for the read portion is worth this, since we'll almost never have writes.
> chore: lock static query map [DET-3633]

- master/internal/api_experiment.go
- master/static/srv/proto_experiment_validation_history.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
- proto/src/determined/experiment/v1/experiment.proto
This adds the `/api/v1/experiments/id/validation-history` endpoint to describe the historical best validations of an experiment. It is done as a separate endpoint because expressing it as a combination of sorts and filters isn't realistic.
```
{
"validationHistory": [
{
"trialId": 1,
"endTime": "2020-09-02T13:27:55.607362Z",
...
"searcherMetric": 0.4304672100000001
},
{
"trialId": 1,
"endTime": "2020-09-02T13:27:56.729405Z",
"searcherMetric": 0.3874204890000001
}
]
}
```
We could say something like, sort by time and add a "best" filter, that does a pass through and continually takes better metrics, but that doesn't seem intuitive (I would think best meant something else, and it's not really a filter at that point, it's some kind of window agg).
Also the query is a little complicated - I …
> feat: add /api/v1/experiments/id/validation-history [DET-3729]

- master/static/srv/get_checkpoints_for_experiment.sql
- proto/src/determined/api/v1/experiment.proto
- proto/src/determined/checkpoint/v1/checkpoint.proto
This change add `SORT_BY_SEARCHER_METRIC` to `/api/v1/experiments/$ID/checkpoints` so we can retrieve the best checkpoints for an experiment.
```
{
"checkpoints": [
{
"uuid": "4474c16a-62b2-47b3-98f7-928f8d092562",
...
"searcherMetric": 0.3486784401000001
},
{
"uuid": "20b17a2c-eb7f-4ee4-968d-99139bcf9c1d",
...
"searcherMetric": 0.81
},
{
"uuid": "5a9e87da-af29-427e-9d8f-d336cabb18f0",
...
"searcherMetric": 0.9
}
],
"pagination": {
"offset": 0,
"limit": 0,
"startIndex": 0,
"endIndex": 10,
"total": 10
}
}
```
It's a tad unfortunate that with the framework that was built up for new api, a field must be in a small set of types at the root level to sort/filter on it.
In theory, we might be able add a block where we try to compare `pref.MessageKind` in `apiServer.sort` and do something like …
> feat: make /api/v1/experiment/id/checkpoints sortable by searcher metric [DET-4067]

- examples/experimental/trial/gaea_nas/eval/const.yaml
Change slots_per_trial in the const.yaml config to 1 so that CI tests do not fail.
> fix: gaea_nas const.yaml config for testing

- docs/release-notes/1242-prevent-dtrain-hangs.txt
- harness/determined/ipc.py
- harness/determined/layers/_worker_process.py
- harness/tests/test_ipc.py
Previously in rare corner we would fail to detect that a worker subprocess
had died leading to indefinite hangs. We now perform health checks for
all worker processes.
The only way I know how to reproduce this hang reliable in our system is by adding these lines into
`_init_session_config()` of `_estimator_trial`:
```
from tensorflow.python.keras.backend import _get_available_gpus, get_session
print(f"session {get_session}")
print(f"GPUS: {_get_available_gpus()}")
```
> fix: avoid d-train jobs from hanging [DET-3848]

- docs/release-notes/1261-fix-estimator-oom.txt
- e2e_tests/tests/experiment/test_tf_estimator.py
- e2e_tests/tests/fixtures/estimator_gpu_detection/const.yaml
- e2e_tests/tests/fixtures/estimator_gpu_detection/model_def.py
- harness/determined/estimator/_estimator_trial.py
Previously, if users placed code within their `model_fn` that detected GPU usage, 
this would cause problems when we pin processes to individual GPUs via
the Tensorflow session config. We now set the default Tensroflow session 
within the Estimator, prior to building the graph defined in the `model_fn`.
Tested manually and added a e2e test.
> fix: prevent GPU detection code from breaking EstimatorTrial [DET-3726]

- docs/release-notes/1264-connection-checks-for-dynamic-agents.txt
- master/internal/provisioner/provisioner.go
- master/internal/provisioner/provisioner_test.go
- master/internal/provisioner/scale_decider.go
- master/internal/provisioner/scale_decider_test.go
- master/internal/scheduler/filterable_view.go
- master/internal/scheduler/filterable_view_test.go
- master/internal/scheduler/view.go
We now compare the list of actively connected instances to the list of provisioned
instances, and remove instances that are failing to connect.
> feat: add connection checks into provisioner [DET-4081]

- master/Makefile
Increase the timeout tenfold to avoid flakes.
See an instance of the flake at:
https://app.circleci.com/pipelines/github/determined-ai/determined/5532/workflows/0ff070f9-e776-4798-bb17-e7e5c71fc856/jobs/143181
You can play with different settings on your machine by running `golangci-lint cache clean` and then `golangci-lint run -j 1 --timeout 1s` (or something) which should produce a failure.
> ci: increase golangci-lint timeout

- cli/determined_cli/shell.py
- harness/determined/horovod.py
- harness/determined/layers/_worker_process.py
- harness/tests/test_horovod.py
For `det shell`, be explicit that the python subprocess used for tunnelling ssh through the master is started with the same python interpreter as what the `det` command is using.
Also, locate instances in the harness which were using making similar calls and make them either use the same interpreter (for same-machine subprocesses) or `python3` for subprocesses started on other machines.
@davidhershey please confirm this fix works for you.  I reproduced the error by adding a link `python2` named as `python` on my PATH and confirmed the fix, but I'd feel better if you confirmed based on whatever environment you originally encountered the bug in.
> fix: use correct python in subprocesses [DET-4148]

- docs/reference/command-notebook-config.txt
- harness/determined/exec/tensorboard.py
- master/internal/command/tensorboard_manager.go
- master/internal/command/tensorboard_manager_test.go
- master/pkg/model/command_config.go
To address requests from the community, this change allows arbitrary arguments to be passed into tensorboard. It also provides the option of setting the `--purge_orphaned_data` flag, giving us more time to debug some tensorboard issues.
To set tensorboard arguments, users should use a tensorboard configuration file with arguments listed under the `entrypoint` field. For instance:
```
entrypoint: 
- "purge_orphaned_data=False"
- "window_title=Experiment 1"
```
Note: not all arguments are supported in determined tensorboard, such as `host`, `port`, and `path_prefix`. 
Added a unit tests for formatting arguments and manually tested tensorboard with optional arguments. `det tensorboard config` can be used to verify that settings have made it to the entrypoint.
See [Release …
> feat: allow tensorboard to accept arbitrary arguments

- docs/how-to/custom-env.txt
- docs/reference/cluster-config.txt
- docs/reference/helm-config.txt
- docs/release-notes/1274-configurable-default-task-images.txt
- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/values.yaml
- master/internal/api_experiment.go
- master/internal/command/command.go
- master/internal/command/command_manager.go
- master/internal/command/manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/config.go
- master/internal/core_experiment.go
- master/internal/core_searcher.go
- master/internal/trial_workload_sequencer_test.go
- master/pkg/model/defaults.go
- master/pkg/model/experiment_config.go
- master/pkg/model/experiment_config_test.go
- master/pkg/model/hyperparameters_config_test.go
- master/pkg/model/searcher_config_test.go
- master/pkg/model/task_container_defaults.go
It is not possible to configure the default task images, pull policy and registry credentials
via the `master.yaml`. Additionally made it configurable via the Helm chart as well.
> feat: support configuring default task images [DET-4079]

- master/internal/kubernetes/mock_client_test.go
- master/internal/kubernetes/request_queue_test.go
Brings back the unit test from before (which were reverted out due to flakiness). The issue in the prior version was the fake k8 client library that was being used. Instead we are now using our own implementation of pod and configMap interfaces. 
Ran locally a bunch of times.
> test: add unit tests for k8 requestQueue [DET-4027]

- docs/release-notes/1289-streaming-ednpoints-coroutine-leak
- master/internal/api_master.go
- master/internal/api_trials.go
the log stream handlers could get into a situation where the requester
has abandoned the request yet the handler still stays up and polls for
new entries indefinitely. This fixes that by checking the context.
> fix: fix a coroutine leak in streaming API handlers [DET-4088]

- webui/react/src/hooks/useRouteTracker.ts
`useRouteTracker`'s `useEffect` hook is called during each `location.pathname` change. Instead we want it called only when `listen` function changes (which is never during the lifecycle of the App).
> perf: reduce unnecessary useRouteTracker re-creation

- docs/release-notes/1299-fix-deselect-rows-after-table-batch-actions.txt
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
Deselect previously selected table rows upon a successful table batch action. Affected pages:
- Experiment List
- Task List
Run through each table batch action for both pages and make sure that all of the table rows are deselected upon completion.
> fix: deselect selected rows when table batch actions are done [DET-4128]

- master/internal/experiment.go
- master/internal/experiment_test.go
- master/internal/experiment_utils.go
- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/internal/trial_workload_sequencer_test.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/event_log.go
- master/pkg/searcher/event_log_test.go
- master/pkg/searcher/pbt.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/searcher.go
- master/pkg/searcher/sha.go
- master/pkg/searcher/simulate.go
- master/pkg/searcher/tournament.go
- master/pkg/searcher/util_test.go
- master/pkg/tasks/task_spec.go
- master/pkg/workload/completed_message.go
- master/pkg/workload/completed_message_test.go
- master/pkg/workload/workload.go
- master/pkg/workload/workload_test.go
After remove steps, the searcher is no longer concerned with
workloads or completed messages, just operations and metrics, so
this change moves those out of the searcher. There are future refactorings
to be done, and this makes them a lot less strange.
Used automatic refactoring tools for this, and unit tests/compiling should cover it.
Been meaning to do this since remove steps, and I finally broke down and got goland so it's 1-2 minutes not 30 miserable minutes.
> chore: move workload out of searcher

- webui/react/package-lock.json
- webui/react/package.json
- webui/react/src/components/ResourceChart.tsx
Changed the `ResourceChart` to use Plotly directly and removed React Plotly as a dependency
I'm not 100% certain if I need `plotInfo`, `renderPlot` and a `useEffect` hooks.
> chore: remove dependency on React Plotly [DET-3724]

- master/internal/trial.go
We check `allReady()` whenever the trial is not in `Active state`. Previously, 
in distributed  trials when one or more containers would disconnect, we would
then fail the `allReady()` check, causing us to terminate the trial as if we are
cancelling a trial that never fully connected.
Also removed a log message that was spamming the master logs.
> fix: don't unset allReady for trials [DET-4197]

- master/internal/core.go
- master/internal/provisioner/agent_setup.go
- master/internal/provisioner/agent_setup_test.go
- master/internal/provisioner/api.go
- master/internal/provisioner/aws.go
- master/internal/provisioner/aws_test.go
- master/internal/provisioner/gcp.go
- master/internal/provisioner/provisioner.go
- master/static/srv/agent_setup_script.sh.template
This adds logic to encode the master cert, when configured, into the
dynamic agents startup script, allowing agents and trials to connect
back to the master over TLS.
~~It feels a little odd to add the cert into the provisioner config, but I thought it was less awkward than passing it around as a separate argument in a bunch of places. I could be convinced otherwise, though.~~ Changed on request.
> feat: allow dynamic agents to use TLS to connect to the master [DET-3988]

- docs/how-to/installation/network-requirements.txt
- docs/reference/cluster-config.txt
- docs/release-notes/1320-one-port.txt
- master/cmd/determined-master/init.go
- master/cmd/determined-master/root.go
- master/cmd/determined-master/root_test.go
- master/go.mod
- master/go.sum
- master/internal/config.go
- master/internal/core.go
- master/internal/grpc/api.go
BREAKING CHANGE: The `http_port` and `https_port` options in the master
configuration have been replaced by the single `port` option. The
`security.http` option is no longer accepted; the master can no longer
be configured to listen over HTTP and HTTPS simultaneously.
Previously, the master could listen on up to three ports at the same
time: one each for HTTP, HTTPS, and gRPC. This streamlines everything to
always work through one port.
One part of that is disallowing the use of both TLS and non-TLS
connections at the same time. Another part is using a connection
multiplexing library to handle both HTTP and gRPC connections over the
same port.
(Conceivably, one could multiplex TLS and non-TLS connections too, but
we want to discourage that anyway for simplicity and security.)
This should …
> feat: allow the master to do everything over just one port [DET-3949]

- docs/how-to/installation/kubernetes.txt
- docs/reference/helm-config.txt
- docs/release-notes/1310-support-tls-configuring-in-helm.txt
- helm/charts/determined/Chart.yaml
- helm/charts/determined/templates/NOTES.txt
- helm/charts/determined/templates/_helpers.tpl
- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/templates/master-deployment.yaml
- helm/charts/determined/templates/master-service.yaml
- helm/charts/determined/values.yaml
Added support for configuring TLS to terminate inside a load-balancer or inside the Determined
master. 
Deployed both methods on a running k8 cluster and confirmed that TLS encryption worked 
(with certificates signed by LetsEncrypt).
> feat: support configuring TLS via Helm chart [DET-4030]

- master/internal/api_auth.go
This change replicates the old client side hash in the new api. This is mainly for backwards compatability; it would be remove entirely, but since the old passwords can't be migrated and it would be a painful migration to need to recreate all users, this just replicates it server side so we can remove it client side. This enables users up the new api to auth with it as expected, instead of needing to replicate the old client side hash on their passwords themselves, or being forced to use an sdk.
> chore: replicate old client side hash in new api [DET-4211]

- harness/determined/layers/_worker_process.py
Our worker-process-exit detection is too good... failing workers do not always have time to finish logging why they are failing.
Give them a few seconds to exit gracefully before forcefully terminating them.
> chore: allow dying workers to exit in peace

- common/determined_common/experimental/model.py
Due to a holdover from the old API, the model registry did not allow users to specify a model version.  Fixed the typo to restore functionality here.
Tested locally to validate the fix works.
> fix: update model registry to new api

- master/Makefile
- master/static/srv/entrypoint.sh
- master/static/srv/gc-checkpoints-entrypoint.sh
- master/static/srv/notebook-entrypoint.sh
- master/static/srv/shell-entrypoint.sh
- master/static/srv/tensorboard-entrypoint.sh
Both Go tests and Python package installations were printing out a bunch
of lines about successful things, which is noisy and unhelpful.
There are some other `pip install`s in various places (setting up in CI, the top-level `get-deps`, test Dockerfiles, some example startup hooks), but the output from those doesn't come up often in normal usage like it does for these things, so I'm inclined to let them be verbose.
> chore: make Go tests and Python installs quieter

- e2e_tests/tests/experiment/test_pytorch.py
Tested manually on a k8 cluster, checking tests that failed: https://app.circleci.com/pipelines/github/determined-ai/determined/6055/workflows/8f0e06a1-9ef8-4cca-b96b-335c67ea577a/jobs/158568
> test: fix broken k8 test

- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pod_test.go
Adds some unit tests for the kubernetes pod actor.
Depends on the k8s sidecar feature [DET-4026].
[DET-4026]: https://determinedai.atlassian.net/browse/DET-4026
> chore: unit tests for kubernetes pod actor [DET-4107]

- harness/determined/_data_layer/_data_layer.py
- harness/setup.py
This takes advantage of the new TLS option of yogadl to pass along the
received master TLS certificate, which removes the last known blocker to
running a cluster with the master serving entirely over TLS.
(Didn't test GCP, but the code paths are equivalent as far as the TLS configuration support is concerned.)
Blocked on https://github.com/determined-ai/yogadl/pull/26 (and a subsequent release and version bump).
> feat: allow yogadl to connect to the master over TLS

- master/internal/grpc/api.go
- proto/src/determined/api/v1/trial.proto
- proto/src/determined/log/v1/log.proto
- webui/react/src/services/utils.ts
Trial log streaming endpoint is now protected and [requires a token](https://github.com/determined-ai/determined/commit/6ad5d763e218df4aa1c687172136ce73c82bd467). Update WebUI to pass credentials over CORS under the DEV environment with `enable_cors` config enabled.
More specifically, the default fetch credentials is set to `same-origin`, but we need to change it to `include` for local dev because the ports do not match up (3000 vs 8080). On the API side, not only do we need to allow `Access-Control-Allow-Origin`, but we also need to enable `Access-Control-Allow-Credentials` to be set to `true` when fetch `credentials` is set to `include`.
[specifications around JS Native Fetch and `credentials` header setting](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#:~:text= …
> fix: send credentials for streaming endpoints in dev environment [DET-4240]

- docs/release-notes/1350-render-metrics-chart-with-same-same.txt
- webui/react/src/pages/TrialDetails/TrialChart.tsx
Metrics with the same name were conflicting in charts.
Issue fixed by grouping metrics with "<type>_<name>".
> fix: webui trial chart render metrics with same name [DET-4169]

- docs/release-notes/1351-webui-select-improvements.txt
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/StateSelectFilter.tsx
- webui/react/src/components/UserSelectFilter.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/styles/antd.scss
I spent a bit of time playing with [Ant Select](https://ant.design/components/select/) config and I think those small tweaks will improve webui UX in those cases:
1. MetricSelectFilter:
- made the input width smaller (no need for it to be larger since the text will always be "N selected"
- dropdownMatchSelectWidth=400 will make the dropdown width be 400 pixel, and in case labels are longer, they won't overflow the screen.
2. StateSelectFilter:
- dropdownMatchSelectWidth=150 will make the dropdown width be 150 pixel
3. UserSelectFilter:
- set a maxWidth=200 on the input element to prevent super long usernames to break the UI
- set a dropdownMatchSelectWidth=200 to avoid having a dropdown too small (and names partially unreadable when a short username is selected - like "all").
(example of …
> fix: webui tweak select for better layout [DET-4123]

- master/internal/trial.go
- master/internal/trial_test.go
Address an issue we previously had where if the harness socket connected to 
the master before the container is transitioned to `Running` we would drop
the socket connection. 
Updated unit tests.
> fix: don't accept stale socket connections [DET-4203]

- proto/src/determined/api/v1/api.proto
Parsing /experiments/labels when /experiments/{id} is also defined
seems to be unreliable. Regardless of the reason, this seems to be an
unsafe practice that we shouldn't rely on.
> chore: fix possible syntax error when parsing experiment labels request [DET-4265]

- master/internal/checkpoint_gc.go
- master/internal/command/command.go
- master/internal/scheduler/default_resource_provider_test.go
- master/internal/scheduler/fair_share.go
- master/internal/scheduler/fair_share_test.go
- master/internal/scheduler/fitting_methods_test.go
- master/internal/scheduler/scaling_test.go
- master/internal/scheduler/scheduler_test.go
- master/internal/scheduler/task.go
- master/internal/trial.go
Commands (TensorBoards, Notebooks), being interactive, would cause more obvious disruption to an end-user if preempted. 
Implementing this requires changes in 2 aspects of the scheduler. First simply not sending the ReleaseResources message to such tasks (and closely related: commands will also ignore this unless something changes CanTerminate to true, and nothing does right now). Second, the scheduler will also take this into account when allocating slots so that a group cannot lose a slot it needs for non-preemptible tasks, so the system cannot oversubscribe itself.
I've added unit tests that reproduced the original problem, including subtleties discovered during implementation. Some other unit tests needed to have CanTerminate added to their task definitions since it defaults to false, …
> fix: commands (TensorBoards, notebooks, etc.) should not be preempted [DET-4157]

- webui/react/src/pages/ExperimentDetails/ExperimentChart.tsx
Give the experiment chart the name of the metric so the legend doesn't use the generic name 'trace 0'.
> fix: experiment chart legend labelling line as 'trace 0'

- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
The provisioner default label_value for GCP is truncated to 30
characters. This was problematic for deprovisioning dynamic agents since
det-deploy looks up instances using the expected default label key /
value and failed to truncate in the same way. This truncation will be
relaxed in the future, but for now, det-deploy works around this by
explicitly setting label key/value in the cluster configuration.
> fix: det-deploy deprovisions GCP agents despite long master names [DET-4271]

- .circleci/config.yml
Context for this change can be found here: https://discuss.circleci.com/t/old-linux-machine-image-remote-docker-deprecation/37572. Especially the note about using remote docker without a version. The original PR included a switch from 16.04 images to 20.04 images, but that is more complicated: we have some hard-coded references to Python 3.6.10 that break when you make that switch, the 20.04 image is in beta anyway, and the 16.04 images aren't QUITE EOL'd - they last for 5 years (longer than I thought). I filed a JIRA to follow-up on that one.
> ci: update from deprecated remote docker versions and machine images [DET-4262]

- proto/scripts/swagger.py
- proto/swagger-patch.json
post-experiment supports creating a new experiment, forking an existing experiment, or continuing a trial.
- add swagger.json spec file merging support.
- add specs for post-experiment endpoint.
> chore: add post experiment endpoint docs to Swagger UI

- docs/release-notes/1404-fix-batch-experiment-cancel.txt
- webui/react/src/pages/ExperimentList.tsx
The correct target state for canceling an experiment is `StoppingCanceled` instead of `Canceled`.
> fix: use the correct target cancel state for canceling experiment [DET-4257]

- docs/release-notes/1409-default-certs.txt
- harness/determined/layers/_socket_manager.py
This obviates the need to supply a full certificate chain (going all the
way to a root certificate) when the master certificate is signed by a
well-known CA.
> fix: always load default system TLS certificates in the harness [DET-4293]

- agent/internal/containers.go
The removed code is no longer necessary now that the master can no
longer listen over both TLS and non-TLS simultaneously.
_n/a_ (the situation this code handled can't come up)
> chore: remove mixed mode TLS workaround from the agent

- proto/.gitignore
- proto/Makefile
- proto/patches/api.json
- proto/scripts/swagger.py
I had a few ideas for how to do this differently (in no particular order):
1. This PR symlinks from `proto/pkg` into the generated code tree.  I could imagine that instead of the symlink, you could instead copy some extra files (`go.mod` for instance) into the generated code tree and use `replace` commands in the `master/go.mod`, for instance.  This would be most similar to how a proper out-of-tree build would work I think.
1. Instead of the symlink step at the end, we could just mv each individual file after it is built into the `pkg` directory.  This would still require the callable functions I wrote for calculating inputs and outputs.
1. I think we could also accomplish something fairly similar in effect to this whole PR like so:
```make
build/build.stamp: $(all_proto_files)
touch $@ …
```
> chore: make `make -C proto build` idempotent [DET-4273]

- docs/release-notes/1397-no-fail-on-exp-restart.txt
- master/internal/db/postgres.go
Before, if the database can't read an experiment config on restart, it would cause the master to fail. Now, instead of failing, it will mark the experiment as failed and continue the restart.
Tested manually. 
- start an experiment on a AWS cluster running Determined 0.12.4
- pause the experiment, stop the master instance, and setup the latest version of Determined (with this fix)
- start master (should not fail with this fix) 
- previously paused experiments should now be errored
> fix: don't fail master if restoring non-terminal experiment from DB [DET-4074]

- webui/react/src/components/MetricChart.tsx
Opacity can be tweaked, is currently 75%.
Result is like this:
> fix: make webui chart legend transparent to show data behind [DET-4218]

- docs/release-notes/1400-preserve-colors-on-metrics-chart.txt
- webui/react/src/pages/ExperimentDetails/ExperimentChart.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
Notes:
- there's a linting fix on webui/react/src/pages/ExperimentDetails/ExperimentChart.tsx
- demo video uploaded on JIRA.
> fix: webui preserve colors on metrics chart [DET-4247]

- .circleci/config.yml
The google cloud release notes indicate that we need to upgrade:
cloud.google.com/kubernetes-engine/docs/release-notes#october_02_2020_r32
> ci: update gke version

- docs/reference/cluster-config.txt
- docs/release-notes/1417-default-boot-disk-image.txt
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp_config.go
The ``boot_disk_source_image`` field for GCP dynamic agents and `image_id` field for AWS dynamic agents are now optional. They default to the latest agent images.
1. Test bumpenv tool.
2. Test AWS and GCP dynamic agents.
> feat: make AWS and GCP agent image optional [DET-4201]

- docs/reference/helm-config.txt
- docs/release-notes/1412-db-helm-configs.txt
- docs/release-notes/1434-congure-storage-class.txt
- helm/charts/determined/templates/db-deployment.yaml
- helm/charts/determined/templates/db-persitent-volume-claim.yaml
- helm/charts/determined/values.yaml
This PR adds support for configuring the storageClass for the PVC deployed
as part of the Determined Helm Chart. Users need to set this when a default
storageClass is not configured.
Tested this on a k8s cluster.
> feat: support storageClass configuration in Helm Chart [DET-4357]

- docs/reference/cluster-config.txt
- docs/topic-guides/index.txt
- docs/topic-guides/tls.txt
This adds a new topic guide page gathering together information on TLS
configuration. This initial version just covers Determined-specific
things, but more background on TLS and certificate creation might be
useful later on.
We probably want more here on how to generate certificates eventually, but I'm punting on that for now to get the most important Determined-specific information down.
> docs: add docs for TLS usage and configuration [DET-4364]

- e2e_tests/tests/config.py
- e2e_tests/tests/experiment/test_pytorch.py
- e2e_tests/tests/experiment/test_tf_estimator.py
- e2e_tests/tests/experiment/test_tf_keras.py
- e2e_tests/tests/fixtures/templates/template.yaml
- e2e_tests/tests/test_system.py
- harness/determined/_trial_controller.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/pytorch/_pytorch_trial.py
Save money on CI by not testing features which are known to be buggy and
which have never really been properly supported.
Leaving the feature intact as AMLEs report it is occasionally useful and it
amounts to very few lines of code.
> chore: remove tests for native parallel

- harness/determined/_trial_controller.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/pytorch/_pytorch_trial.py
These calls have not been useful since `from_native()` took their place.
> chore: remove useless support_determined_native calls

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/cli.py
- deploy/determined_deploy/gcp/cli.py
- docs/how-to/installation/gcp.txt
Things like `det-deploy gcp` or `det-deploy aws` just print errors because the code assumes you have either an environment AND command or neither. Now requiring the command before going into the environment code. This prompts the user to try --help, and I've added help text for the local_state_path flags on GCP. I also wanted a --version flag while I was debugging this to see if I was actually on a release version, or a development version, etc...
I ran all combinations mentioned above.
> fix: show more help text and version info in det-deploy [DET-4373]

- docs/release-notes/1451-update-trial-id-for-new-trials.txt
- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/resource_managers.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/resourcemanagers/task.go
- master/internal/trial.go
Previously trial that did not have an id (so new trials) when requesting 
resources never updated their names. This meant that `det task list`
and `det slot list` would omit the trial id for these trials. This PR fixes
this by updating task names once trial id is set.
Tested locally and on a k8 cluster.
> fix: update task names for new trials [DET-4832]

- .circleci/config.yml
- Makefile
- docs/Makefile
- docs/examples.txt
- docs/how-to/ide-setup.txt
- docs/how-to/installation/gcp.txt
- docs/how-to/installation/kubernetes.txt
- docs/how-to/rest-apis.txt
- docs/index.txt
- docs/reference/api/pytorch.txt
- docs/reference/cluster-config.txt
- docs/reference/helm-config.txt
- docs/release-notes.txt
- docs/release-notes/1441-tensorboard-sources.txt
- docs/release-notes/1446-style-and-copy-fix.txt
- docs/release-notes/1451-update-trial-id-for-new-trials.txt
- docs/requirements.txt
- docs/topic-guides/custom-pod-specs.txt
- docs/topic-guides/tls.txt
- docs/tutorials/pytorch-mnist-tutorial.txt
- docs/tutorials/tf-mnist-tutorial.txt
We previously added a formatter for the reST files, but left out
enforcement of the formatting for stability's sake. But now it's been
long enough; let's make the checking automatic.
I went ahead and made a new CircleCI job, `lint-docs`, for this, since that feels proper. But I wouldn't mind tucking it into `lint-python`, which would be simpler (I think it would only require one line added to the config), especially if doing so, say, saved us any money.
> style: add enforcement of reST formatting

- docs/release-notes/1450-k8s-agents-endpoint.txt
- helm/charts/determined/Chart.yaml
- helm/charts/determined/templates/master-permissions.yaml
- master/internal/kubernetes/events.go
- master/internal/kubernetes/nodes.go
- master/internal/kubernetes/pods.go
Previously when we accessed the agents endpoint (WebUI, det slot list, det agent list)
while running on k8s, we would query the k8s API server for the current list of nodes
which was a blocking call. We now keep a running list of current nodes, so there is no
need to make blocking calls to the k8 API server while building the response for the 
agents endpoint.
Tested manually on a k8 cluster.
> fix: improve performance of agents endpoint for k8s [DET-4073]

- e2e_tests/tests/requirements.txt
Numpy 1.16.2 is the latest version where I could sidestep the following three errors
* ERROR: determined 0.13.6.dev0 has requirement numpy>=1.16.2, but you'll have numpy 1.16.1 which is incompatible.
* ERROR: tensorflow 1.15.4 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.
* RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
> fix: specify numpy version in requirements.txt

- docs/reference/cluster-config.txt
- docs/release-notes/1469-fix-fit-default.txt
- master/internal/resourcemanagers/resource_manager_config.go
Fix setting the default values for the `fit` field if the `scheduler` field exists in `master.yaml`.
Manual testing.
N/A
> fix: fix setting default for fit field in master.yaml

- harness/determined/exec/worker_process_wrapper.py
This change prepends rank_id to logs from our worker process launched by horovod. This is in line with what was provided by horovod previous, after logs returned to agent 0 by SSH.
This is pretty similar to what horovod would do on agent0 if the output from stdout/stderr were still getting back there (see https://github.com/horovod/horovod/blob/master/horovod/runner/common/util/safe_shell_exec.py#L198-L199 as pointed out be @aaron276h in the first place as to why this is missing). Because of this, I'm not too concerned about performance (since it was happened already and all on one machine).
I didn't do much in the way of error handling in the forwarding thread - any error is encounters would be a programming error, or something unhandleable and if there is an error, it _will_ show up in …
> fix: preserve rank_id in logs [DET-4413]

- harness/determined/exec/worker_process_wrapper.py
The change propagates the horovod worker process's retcode through the worker process wrapper that is responsible for redirecting its stdout/stderr and starting it so, to horovod, it is still as if it ran the worker process directly.
Noticed peeking at CI failures.
> chore: propagate horovod worker process retcode

- master/internal/api.go
from 
`{"error":{"code":13,"reason":"Internal","error":"reflect.Value.Slice: slice index out of bounds"}}`
to 
`{"error":{"code":3,"reason":"InvalidArgument","error":"offset out of bounds"}}`
> fix: fix out of order boundary check [DET-4422]

- docs/release-notes/1421-improve-metric-selector.txt
- webui/react/src/components/MetricSelectFilter.tsx
- webui/react/src/components/SelectFilter.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialChart.tsx
- webui/react/src/types.ts
- webui/react/src/utils/trial.ts
Improve the metric selector. 
Allow users to select all metrics. Allow users to select all metrics that match the filter. Allow users to deselect all metrics. Improve placeholders to be more informative about how many metrics are selected and how many metric are available in total.
User facing:
- Added ALL option to dropdown
- While filtering, have ALL option select all options that meet the filter. 
- Adjust the appearance of the ALL option when filtering (when no filter = `All`, when filter has filtered down to N results = `All N results`, when filter has only a single result = do not display ALL option)
- Add a clear icon (antd out-of-the-box) that deselects all options. Upgrade antd to access the `onClear` callback to enable this behavior.
- Changed the text in the dropdown when it is …
> feat: improved metric selector [DET-4122]

- .circleci/config.yml
Previously, the branch name cannot contain slash because it is used in the cluster id when deploying a cluster. Now fix it to replace a slash with two dashes.
Push the branch to the main repo and see if it passes the CI.
N/A
> ci: fix branch name cannot contain slash for ci [DET-4104]

- docs/how-to/installation/aws.txt
- docs/reference/cluster-config.txt
- docs/release-notes/1415-spot-instances.txt
- docs/topic-guides/elastic-infra/aws-spot.txt
- docs/topic-guides/elastic-infra/dynamic-agents-aws.txt
- docs/topic-guides/elastic-infra/index.txt
- docs/topic-guides/index.txt
- master/internal/provisioner/aws.go
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/aws_spot.go
Add documentation and release notes for spot instances. Also improve some parts of the spot implementation where writing documentation revealed gaps in the implementation. 
Rename the master.yaml field from spot_instance_enabled to spot to better match GCP's preemptible field. 
Add user-facing logging in cases where spot instances can't be created due to AWS capacity constraints or the user setting a spot_max_price that is too low. 
Remove confusing logging when cleaning up spot instances - the API is eventually consistent and we will repeatedly try to clean up spot instances until the API confirms that everything has been terminated. These operations should not produce user facing INFO logs because it leads to confusing output where the logs say the same instance has been terminated …
> docs: spot instances docs and fixes [DET-4338]

- deploy/determined_deploy/aws/aws.py
- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/secure.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/deployment_types/vpc.py
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/setup.py
- docs/how-to/installation/aws.txt
Make spot instances available via det-deploy
Manually test with simple configuration.
Tearing down agents is a little more complicated with spot instances. The spot API is eventually consistent so if we clean up all requests naively, there could be additional requests that exist, but just haven't become visible in the API. Requests usually show up after around 20-40 seconds (more or less), so 60 seconds seems like a safe amount of time.
This is part of the overall spot instance release so there are no specific release notes as part of this PR.
> feat: make spot instances available in det-deploy [DET-4339]

- docs/reference/helm-config.txt
- docs/release-notes/1522-helm-db-service-type.txt
- helm/charts/determined/templates/db-service.yaml
- helm/charts/determined/values.yaml
This came up as something that can be useful when @davetroiano was installing on a local 
cluster that did not have support for ClusterIP service types.
> feat: make DB service type configurable in Helm chart

- master/internal/trial.go
- master/pkg/tasks/task_spec.go
A bunch of code relating to the `TaskSpec` struct was left over from
when that type was serialized and sent to the old Python agent; that
code is now removed, since `TaskSpec` is no longer sent directly but
instead translated into a `container.Spec` within the master.
This also deletes the unused `KillContainer` and moves the message for
running a workload, which was stuck in among all the container start
messages, to a more appropriate place in the trial code.
I was originally imagining a somewhat larger refactor of the task/container spec translation stuff; some more might come later, but I do think, after looking at this code, that something like the current pattern more or less makes sense.
> refactor: clean up code for master-sent messages

- agent/Makefile
- docs/Makefile
- master/Makefile
- tools/scripts/gen-attributions.py
Use the right shebang line to play nice with Macs.
Don't write output files until the last moment to play nice with Make.
> chore: make gen-attributions.py play nicer

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/templates/simple.yaml
- docs/release-notes/1515-det-deploy-specify-subnet.txt
Allow det-deploy aws to specify subnet that agents should be launched in for simple deployment type. This gives users a solution in the case where the master picks a subnet in an availability zone that does not have agent instances of the specified type.
Tested manually with simple deployment type
When testing spot, I found that the cluster might be unable to launch GPU agents because the subnet did not support GPU instances and the only way to fix the issue is to SSH into the master and alter the config file.
> feat: allow det-deploy aws to specify subnet for simple deployment type

- master/internal/api/filters.go
- master/internal/api/logs.go
- master/internal/api/params.go
- master/internal/api_master.go
- master/internal/api_notebook.go
- master/internal/api_trials.go
- master/internal/command/events.go
- master/internal/db/postgres.go
- master/internal/db/postgres_filters.go
- master/internal/db/postgres_proto.go
- master/internal/db/postgres_trial_logs.go
- master/internal/grpc/validate.go
- master/pkg/actor/system.go
- master/pkg/logger/log_buffer.go
- master/pkg/model/experiment.go
- master/static/migrations/20200929105146_add-trial-log-fields-for-filtering.down.sql
- master/static/srv/stream_logs.sql
- proto/src/determined/api/v1/trial.proto
- proto/src/determined/log/v1/log.proto
This change adds filtering support to `/api/v1/trial/{trial_id}/logs`. It also unifies the trial and master logs streaming code paths and provides a small internal filter representation and a not-too-general way to convert it to SQL.
There were a lot of ways to do all this. For the most part, in the end, I settled back on the simpler way.
The only this in the PR I think now that is mildly controversial is the `api.ProcessLogs` is now an actor `LogStoreProcessor` or something. The idea here was mainly motivated by this opinion of mine: everything (especially things that are even remotely long-running, like streaming trial logs) should just be an actor. Now that some preliminary tracing support is going to land, it's even easier to get visibility into that plain-old goroutines, and the more …
> feat: support filtering in trial logs api [DET-4177]

- agent/cmd/determined-agent/run.go
- agent/internal/agent.go
- agent/internal/detect.go
- agent/internal/options.go
- docs/reference/cluster-config.txt
- docs/release-notes/1484-configurable-slot-type.txt
- master/internal/provisioner/agent_setup_test.go
- master/internal/provisioner/gcp_config.go
- master/static/srv/agent_setup_script.sh.template
Previously, we only support using autoconfiguring the slot type to be GPU and if there are no GPUs fall back to CPU. This applies to most use cases, including GPU-only cluster and testing infrastructure (typically users don't use purely CPU). However, we want to be able to support zero-slot resource pools for zero-slot tasks, such as Tensorboard, GC tasks, CPU-only notebooks, and etc,. And we don't want zero-slot resource pools to show any slots on the slot utilization.
Now, in order to support a zero-slot resource pool when we support multiple resource pools, we need to make slot type configurable for agents as opposed to always autoconfiguring the slot type. For dynamic agents, we always use GPUs as slot types so resource pools that use CPU agents will be considered to only run …
> feat: make slot type configurable. [DET-4308]

- docs/release-notes/1544-fix-cannot-find-resource-pool.txt
- master/internal/resourcemanagers/agent_resource_manager.go
FIx not being able to find a resource pool.
Use the CI test suite.
N/A
> fix: fix not being able to find resource pool [DET-4477]

- agent/cmd/determined-agent/run.go
- agent/go.sum
- agent/internal/agent.go
- agent/internal/container.go
- agent/internal/containers.go
- agent/internal/docker.go
- agent/internal/fluent.go
- agent/internal/options.go
- docs/how-to/installation/docker.txt
- e2e_tests/tests/experiment/experiment.py
- master/internal/config_test.go
- master/internal/core.go
- master/internal/db/postgres.go
- master/internal/provisioner/agent_setup.go
- master/internal/provisioner/agent_setup_test.go
- master/internal/provisioner/aws.go
- master/internal/provisioner/config.go
- master/internal/provisioner/config_test.go
- master/internal/provisioner/gcp.go
- master/internal/sproto/task_actor.go
- master/internal/trial.go
- master/pkg/container/spec.go
- master/pkg/model/experiment.go
- master/pkg/tasks/task.go
- master/static/srv/agent_setup_script.sh.template
- master/static/srv/get_logs.sql
- master/static/srv/get_logs_limit.sql
- master/static/srv/get_logs_offset_limit.sql
This PR moves trial logs to being sent through a Fluent Bit container running alongside each agent in the cluster. For the moment, doing so mostly just adds complexity, but the idea is to later add support for Elastic as a separate log backend, which will be made easier by the use of Fluent Bit.
The agent internally manages the lifecycle of the Fluent Bit container in order to keep administration simple and ensure that the daemon is started with the necessary configuration. The agent automatically configures Fluent Bit to connect back to the master and fill in the new fields being used for filtering. To simplify the required networking, the logs that the agent itself inserts are sent to the master rather than through Fluent Bit.
The master gains a new endpoint to accept POSTed trial logs, …
> feat: use Fluent Bit for trial logs [DET-4178]

- proto/Makefile
- tools/scripts/README.md
- tools/scripts/lock-api-state.sh
- tools/scripts/pre-release.sh
Added a script to update `buf` image on each release to ensure changes after this point are backwards compatible.
ran the script to make test 
- it fails if there are dirty files
- it creates a commit if there is an updated image
- moves on if there is no updated image to create commit of
1. ensure a clean git state
2. update the buf image
3. create a commit for updating buf image if necessary/changed
- once this is in we should update the release process doc to refer to this script
- suggestion on where we host this script? we have the devops-scripts repo
buf referring to https://docs.buf.build/
> build: add a pre-release script [DET-4414]

- e2e_tests/tests/experiment/test_metrics.py
- e2e_tests/tests/requirements.txt
- master/internal/api_experiment.go
- master/internal/db/postgres_experiments.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
These endpoints allow the web UI to populate menus for exploring metrics data interactively. They stream until the experiment completes to allow live updates of the UI as an experiment progresses.
Integration tests are included and passed. Also did some manual testing via curl to validate expectations.
This is intended specifically for a web UI feature - not actually sure if we consider this a "feat" or a "chorse".
> feat: add streaming endpoints with metric metadata for future UI work [DET-4439]

- e2e_tests/tests/experiment/test_metrics.py
- master/internal/api_experiment.go
- master/internal/db/postgres_experiments.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
This is closely related to https://github.com/determined-ai/determined/pull/1538. It's an additional API endpoint that's part of the same project and addresses some final feedback there.
> feat: add streaming endpoint for trial metrics at a specific point [DET-4440]

- docs/release-notes/1555-tf-keras-hang.txt
- harness/determined/_trial_controller.py
- harness/determined/keras/_tf_keras_trial.py
We have observed an issue where `hvd.allreduce()` may hang if different workers
call into it minutes apart. This can occur if workers in TFKerasTrial complete 
`model.evaluate()` at different speeds.
Added the following snippet into `compute_validation_metrics()` and confirmed that 
we no longer hang:
```
delays = {
0: 0,
1: 7,
2: 6,
3: 6,
14: 3,
15: 3,
20: 3,
13: 2,
22: 2,
23: 2,
21: 2,
5: 2,
12: 1,
7: 1,
6: 1,
8: 1,
4: 1,
10: 1,
18: 1,
}
my_delay = 0
if self.context.distributed.get_rank() in delays:
my_delay = delays[self.context.distributed.get_rank()]
my_delay *= 60
my_delay += random.randint(1,30)
import time
print(f"Worker {self.context.distributed.get_rank()} sleeping for {my_delay}.")
time.sleep(my_delay)
print(f"Worker {self.context.distributed.get_rank()} fininshed sleeping.") …
```
> fix: avoid hangs during validation for TFKeras [DET-4434]

- docs/release-notes/1572-k8s-watch.txt
- master/internal/kubernetes/events.go
- master/internal/kubernetes/informer.go
- master/internal/kubernetes/nodes.go
Handle errors where k8s sent unexpected types in response to `watch()` gracefully.
> fix: check for error when converting k8s watch objects

- docs/how-to/tensorboard.txt
- docs/reference/api/keras.txt
- docs/release-notes/1458-fix-keras-callbacks.txt
- examples/computer_vision/cifar10_tf_keras/model_def.py
- examples/computer_vision/iris_tf_keras/model_def.py
- examples/data_layer/data_layer_mnist_tf_keras/model_def.py
- harness/determined/keras/_tensorboard_callback.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/keras/callbacks.py
- harness/tests/experiment/fixtures/tf_keras_one_var_model.py
I broke the tensorboard callback when I stopped calling on_epoch_end with metrics, but this fixes it.
> fix: restore keras TensorBoard wrapper

- master/internal/core_checkpoints.go
- master/static/srv/get_checkpoint.sql
- master/static/srv/get_checkpoints_for_trial.sql
Fix a bug with the old API's checkpoint export endpoints arising from strict JSON de-serialization and an extra field in the source.
> chore: fix old checkpoint export apis [DET-4538]

- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/agent_resource_manager_test.go
- master/internal/resourcemanagers/deprecated_config.go
- master/internal/resourcemanagers/fitting_methods.go
- master/internal/resourcemanagers/resource_manager_config.go
- master/internal/resourcemanagers/resource_pool_config.go
- master/internal/resourcemanagers/scheduler.go
- master/internal/resourcemanagers/scheduler_config.go
- master/pkg/model/experiment_config.go
This PR adds the UX options for configuring the priority scheduler. For the 
`scheduler` (old way of configuring) we add `preemption` and `default_priority`
as top level configurations. For `resource_manager` (new way of configuring) we
make `scheduler` a nested configuration. This nested config can also be specified
for individual resource pools, allowing them overwrite the `scheduler` specified
in the `resource_manager`.  We also add an option to specify priority as part
of the `resources` field for individual experiments and tasks.
We are not adding documentation for any of this as these options are not yet 
supported in the product.
Tested manually by starting up the master with different configurations.
@shiyuann I am adding you to this since it touches a lot of the code you recently …
> feat: add configurations for priority scheduler [DET-4507, DET-4509]

- proto/src/determined/api/v1/api.proto
Adding this new "Internal" tag for APIs that are possibly subject to change in the future or are otherwise not (yet) intended for use by end-users.
> chore: Tag metrics streaming APIs as Internal due to their less-stable or less-supported status [DET-4546]

- master/internal/experiment.go
- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/group.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/resource_managers.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/resourcemanagers/resource_pool_test.go
- master/internal/sproto/task_actor.go
This PR supports propagating task configured priorities to the resource pools.
Tested manually & added unit test coverage.
<s>Note: Only the last two commits are related to this PR.</s>
> feat: propagate task priorities to resource pools [DET-4510]

- e2e_tests/tests/experiment/test_metrics.py
- master/internal/api_experiment.go
- master/internal/db/postgres_experiments.go
- master/internal/lttb/lttb.go
- master/internal/lttb/lttb_test.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
This is the last in a series of streaming endpoints being added for a UI to explore metrics, hyperparameters, and the relationships between them. It is very closely related to previous pull requests in style and design choices. See https://github.com/determined-ai/determined/pull/1562 for prior context.
> feat: implement API endpoint for sampling streams of metrics from the best trials [DET-4441]

- agent/cmd/determined-agent/run.go
- agent/internal/agent.go
- agent/internal/containers.go
- agent/internal/fluent.go
- agent/internal/options.go
- common/determined_common/__init__.py
- common/determined_common/api/request.py
- common/determined_common/requests.py
- docs/reference/cluster-config.txt
- docs/release-notes/1588-agent-hostname-override.txt
- docs/topic-guides/tls.txt
- harness/determined/_data_layer/_data_layer.py
- harness/determined/_env_context.py
- harness/determined/_execution.py
- harness/determined/exec/harness.py
- harness/determined/layers/_socket_manager.py
- harness/setup.py
- harness/tests/experiment/utils.py
- harness/tests/tensorboard/test_util.py
- harness/tests/test_horovod.py
- master/internal/provisioner/agent_setup.go
- master/internal/provisioner/agent_setup_test.go
- master/internal/provisioner/aws.go
- master/internal/provisioner/config.go
- master/internal/provisioner/gcp.go
- master/static/srv/agent_setup_script.sh.template
To handle cases where the address the agent is using to connect to the
master is not one of the valid addresses for the master certificate
(e.g., public vs. private addresses of a cloud instance), this adds the
ability to the various parts of the stack to option to expect a
different address in the certificate from the address that is actually
being used to connect.
> fix: allow clients to override the expected master cert address [DET-4547]

- docs/release-notes/1608-fix-trial-logs-viewer.txt
- master/internal/api_trials.go
Fix a bug where unique ID's are not returned for trial logs, which resulted in the webui not rendering them properly.
> chore: include offset in trial log IDs returned to webui [DET-4561]

- examples/nlp/albert_squad_pytorch/README.md
> fix: typo in ALBERT SQuAD example

- docs/reference/command-notebook-config.txt
- docs/release-notes/1620-command-shm-size.txt
- master/pkg/tasks/task.go
Allows users to specify `shmSize` in command configurations.
> feat: support per command shmSize settings [DET-4577]

- .circleci/config.yml
pytest was producing JUnit XML files in a slightly wrong format, causing
CircleCI to fail to find timing information for E2E tests and preventing
it from doing the automatic timing-based test splitting we wanted it to
do. This fixes the format so that the splitting works, reducing the time
for running E2E CPU tests from 20 minutes to 12, roughly. That doesn't
totally translate into a reduction in time for the overall E2E workflow,
since the affected job is no longer the longest one, but total time is
down by 5 or so minutes.
> test: fix CircleCI timing-based splitting for E2E tests

- master/internal/provisioner/gcp.go
- master/internal/provisioner/gcp_config.go
Unable to use A100 instances on Google, adding them to the whitelist. Also adding the ability specify a minimum CPU platform for the instance, as the default (Intel Broadwell) doesn't work when it's Intel Cascade Lake.
> chore: Adding NVIDIA Tesla A100 details for GCE [DET-4583]

- examples/hp_search_benchmarks/darts_cifar10_pytorch/README.md
- examples/hp_search_benchmarks/darts_cifar10_pytorch/adaptive.yaml
- examples/hp_search_benchmarks/darts_cifar10_pytorch/model_def.py
- examples/hp_search_benchmarks/darts_cifar10_pytorch/utils.py
The validation accuracy is quiet noisy and fluctuates a lot for this benchmark.  This negatively impacts the performance of hp search, which uses the latest validation accuracy to make early-stopping decisions.  Hence, we change the validation accuracy to return the best accuracy so far instead of latest so that the searcher has a higher quality signal for early-stopping.  
Verified with experiments that adaptive search does indeed find architectures with better final accuracy when using best accuracy so far as the searcher metric.
> fix: track best validation metric for darts_cnn hp search benchmark

- agent/internal/fluent.go
This change fixes the behavior of the lua filter run by fluent bit when it receives a nil log entry. In the event a log like `[rank=0] ` was received prior to this change, the rank parser would parse out rank as 0 and log as nil according to the regex `^\[rank=(?<rank_id>([0-9]+))\] (?<log>.*)`. This leads to the lua snippet in a later filter to try to concatenate `nil .. '\n'` which results in an error. It seems even though the filter errors, fluentbit considers the filter optional and attempts to ship the log without running it. Since the master deserializes batches of logs together and the lua filter converts rank id to an int, this caused the master to receive malformed JSON and throw out the entire batch. 
Took me a while to put this up because there was another, different fluent …
> chore: fix fluent lua filter

- docs/release-notes/1655-restart-with-failures.txt
- master/internal/experiment.go
Duplicates can arise in master restart when a trial has failed prior to the master restart. A bug was introduced in 0.13.0 during a refactor and the logic for dedup'ing events was removed. This adds the logic back in, where it makes sense in the current structure.
oops, this is a remove steps bug. I put the logic it back into the restore as opposed to the event log so the old events are at least there in the searcher events instead of just throwing them away (the old way just didn't add them to the uncommitted list that gets flushed).
> fix: don't replay duplicates in master restart [DET-4525, DET-4599]

- docs/release-notes/1629-fix-responsive-filters.txt
- webui/cypress/cypress-ci.json
- webui/cypress/cypress.json
- webui/react/src/components/Dropdown.tsx
- webui/react/src/components/ResponsiveFilters.module.scss
- webui/react/src/components/ResponsiveFilters.tsx
Responsive filters renders poorly when exactly at portrait table breakpoint of 768.
Update the filters to dynamically check for when the filters run out of space and starts wrapping. That is the point where the filters should collapse into a filters button + dropdown view.
One minor caveat is that with this approach, once the collapse occurs, it does not return back to the uncollapsed state when resizing the viewport to something large enough. Unless the user navigates away and back to the page or reloads the page.
Issue
Uncollapsed
Collapsed
Check responsive filters on:
> refactor: update filters to dynamically collapse when needed [DET-4584]

- master/internal/resourcemanagers/agent.go
- master/internal/resourcemanagers/fitting.go
- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/priority_test.go
- master/internal/resourcemanagers/scheduler_test.go
- master/pkg/container/container.go
- master/pkg/container/id.go
Adding priority scheduler with pre-emption. This scheduler is not yet configurable without master 
code changes as we are not yet ready to release it. 
The priority scheduler will never scheduler lower priority (non-zero slot) task while a higher priority 
task is pending. It is able to run with and w/o pre-emption. When pre-emption is enabled, lower 
priority tasks will be terminated in order to schedule higher priority tasks. By default pre-emption
is disabled. 
Tested manually and added basic unit test coverage. Extensive unit test coverage will be added as part
of [DET-4513](https://determinedai.atlassian.net/browse/DET-4513).
> feat: priority scheduler with preemption [DET-4512]

- examples/computer_vision/cifar10_pytorch/model_def.py
- examples/gan/gan_mnist_pytorch/model_def.py
- examples/hp_search_benchmarks/darts_cifar10_pytorch/model.py
- examples/hp_search_benchmarks/darts_cifar10_pytorch/utils.py
- examples/hp_search_benchmarks/darts_penntreebank_pytorch/data.py
- examples/hp_search_benchmarks/darts_penntreebank_pytorch/model_def.py
- examples/hp_search_benchmarks/darts_penntreebank_pytorch/randomNAS_files/model.py
- examples/hp_search_benchmarks/darts_penntreebank_pytorch/randomNAS_files/utils.py
- examples/meta_learning/protonet_omniglot_pytorch/model_def.py
- examples/nas/gaea_pytorch/eval/model.py
- examples/nas/gaea_pytorch/eval/utils.py
- examples/nas/gaea_pytorch/search/model_search.py
- examples/nas/gaea_pytorch/search/utils.py
- examples/tutorials/mnist_pytorch/layers.py
- harness/tests/experiment/fixtures/pytorch_xor_model.py
A bunch of these fail when run on Tesla A100's. It's possibly also caused by changes in new framework versions, but I suspect the different GPU sizes may be a factor here too. So to be safe, and to keep the examples especially running robustly (even if some of them wouldn't always need it in practice), I think it's wise to just always preface the view() calls with contiguous() calls.
> chore: Ensuring examples always call .contiguous() before .view() [DET-4613]

- common/determined_common/experimental/checkpoint/_torch.py
- harness/determined/pytorch/_pytorch_trial.py
Still working on a minimal reproduction of this, but it seems there's a possible bug involving the ByteBuffer class in Torch's C++ code. It calls .tell(), assuming the object passed in is an already opened file. We're supposed to be able to pass in a path and have it be opened, but that appears to be skipped in the case of some of our tests running against the latest PyTorch.
> chore: Work around possible bug when PyTorch opens checkpoint files [DET-4614]

- docs/release-notes/1665-fix-dots-in-config.txt
- master/cmd/determined-master/init.go
- master/cmd/determined-master/root.go
- master/cmd/determined-master/root_test.go
This change allow keys in map sections of the `master.yaml` to be specified with a `.` in them. This was previously not possible because, while we marshal the configuration successfully into a `map[string]interface{}`, when we merge this configuration into viper, viper loses its ability to disambiguate keys with `.`'s and nested objects because it uses `.` as the object delimiter by default (explained in more detail in comment in code).
Feels a bit a hack to make the problem just happen less, but `..` should be a much less common occurrence and the only real alternative is to pin to the viper commit where they let you ignore key delimiters in some cases but it ended up being a breaking change in viper, was reverted in favor of setting the key delimiter and that feels more a hack/risky. …
> fix: allow dots in map config keys [DET-4542]

- docs/reference/cluster-config.txt
Add a reference documentation for resource manager and resource pools.
N/A
N/A
> docs: add reference documentation for resource manager and resource pools [DET-4349]

- e2e_tests/tests/experiment/test_metrics.py
- master/internal/api_experiment.go
- master/internal/db/postgres_experiments.go
- proto/src/determined/api/v1/experiment.proto
Implementing a bunch of feedback that I got shortly after committing these calls. I'm wondering if our CI is going to flag this as incompatible, but anything disallowed by these changes was simply broken / wouldn't work / nonsensical before anyway. Furthermore, we tagged this API as "Internal" prior to release because a bigger change than this was being discussed (which we have decided against doing). These APIs are being implemented for a very specify use case, and as that use case progresses we might decide on other changes being necessary. The changes now are:
* Required parameters are now documented in the JSON schema
* Correct HTTP status code (400) are now returned for invalid input
* Correct HTTP status code (404) are now return for a non-existent experiment code
* The polling …
> chore: Improvements to metrics streaming endpoints [DET-4532]

- master/internal/agent/agents.go
- master/internal/api_agents.go
- master/internal/command/command.go
- master/internal/command/command_manager.go
- master/internal/command/manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/experiment.go
- master/internal/resourcemanagers/setup.go
- master/internal/sproto/globals.go
- master/internal/trial.go
- master/pkg/model/experiment_config.go
Allow experiment and commands to be configured with a `resources.resource_pool` field to be scheduled on the specified resource pool.
Will add an e2e test as a follow-up PR.
N/A
> feat: allow task requests to receive a resource pool field [DET-4342]

- docs/release-notes/1666-fix-db-pool-deadlock.txt
- master/internal/core.go
Limit the number of concurrent restores at any time within the system to maxConcurrentRestores.
This avoids an issue where the connection pool can be exhausted and the system deadlock. For
example if there are N connections in the pool and N experiments restoring, since a connection
is pinned per restore streaming events, if during any restore blocks for a connection before
completing, we are deadlocked.
There may be a better solution but this is pretty simple at least.
> fix: limit concurrent restores to avoid resource exhaustion [DET-4556]

- cli/determined_cli/cli.py
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/resourcemanagers/summaries.go
This PR improves observability into the priority scheduler by displaying task priority 
as part of the output of `det task list`. Additionally task summaries now include task
priorities so we will be able to display them via other mediums (e.g., WebUI) in the 
future.
This PR is blocked on #1634.
> feat: display task priorities in CLI [DET-4515, DET-4516]

- docs/release-notes/1678-fix-tpl.txt
- master/pkg/model/command_config.go
- master/pkg/model/experiment_config.go
Fix merging template for bind mounts.
Manually tested it.
N/A
> fix: template merging for bind mounts [DET-4630]

- master/internal/experiment.go
This change shrinks the searcher event buffer so that in the event of infrequent checkpoints and validations we don't end up with a large buffer (previously up to 1k entries) of large events sitting in memory for a long time.
In high scale situations, chances are steps are _very_ long and the metrics in them are also large. Because of this, it may be more performant to just flush events immediately instead of holding them in memory at all. I'm open to that.
> fix: flush searcher events more often [DET-4644]

- cli/determined_cli/tunnel.py
- master/internal/command/command.go
- master/internal/command/shell_manager.go
- master/internal/core.go
- master/internal/proxy/proxy.go
- master/internal/proxy/tcp.go
We were using HTTP CONNECT to proxy SSH connections to shells through
the master, but that isn't widely supported by HTTP proxies/load
balancers (in particular, AWS Elastic Load Balancing is documented not
to support it and GCP's load balancing was seen to fail; nginx, as
another example, doesn't support it without an external module).
Instead, we now proxy TCP connections over WebSockets, which have better
support and which we already use in such situations. There's a little
overhead, but it shouldn't be too much: WebSockets are capable of
transmitting binary data, so there's just a bit of extra framing around
the raw data.
Perhaps this should also be tested with the load balancer on GCP, since that was where we actually hit the issue, but it should be good if other WebSocket connections …
> fix: let shells work through an HTTP proxy/load balancer [DET-4469]

- master/internal/api/logs.go
- master/internal/api_trials.go
- master/internal/core.go
- master/internal/db/postgres.go
- master/internal/db/postgres_trial_logs.go
- master/internal/elastic/elastic.go
- master/internal/elastic/elastic_trial_logs.go
- master/internal/trial_logger.go
- master/static/srv/trial_status.sql
This PR adds an support for reading logs from elasticsearch when it is configured as the log backend for the cluster.
This supports the same API as trial logs, however in several cases this API is not well suited to elasticsearch. For example, the webui makes queries to the API like `/api/v1/trials/:trial_id/logs?limit=1000&offset=-1000&follow=true` that get converted to a postgres query with `LIMIT 1000 OFFSET count_this_trials_logs - 1000`. Postgres handles grabbing the last page of a large result set fine, however the equivalent query in elasticsearch potentially requires a large from+size that would exceed `index.max_result_window` or worse cause OOMs before it did. Because of this, I suggest we keep this API but move the webui to consuming logs by accessing for successive timestamp …
> feat: read logs from elasticsearch [DET-4621]

- .circleci/config.yml
Fix based on https://cryptography.io/en/latest/installation.html#building-cryptography-on-windows.
> ci: fix windows cli test

- examples/computer_vision/mmdetection_pytorch/README.md
This example does not currently work with Determined on Kubernetes due to the limit on the size of a ConfigMap.  This PR adds this disclaimer to the README in case users run into this issue.  
[DET-4524]
[DET-4524]: https://determinedai.atlassian.net/browse/DET-4524
> fix: add K8s disclaimer for mmdetection example [DET-4524]

- proto/scripts/swagger.py
before after diff on swagger.json
```
3639,3640c3639,3640
<         "experiment_id",
<         "start_time",
---
>         "experimentId",
>         "startTime",
3643c3643
<         "total_batches_processed"
---
>         "totalBatchesProcessed"
3801,3804c3801,3804
<         "start_time",
<         "experiment_id",
<         "trial_id",
<         "batch_number"
---
>         "startTime",
>         "experimentId",
>         "trialId",
>         "batchNumber"
3850c3850
<         "start_time",
---
>         "startTime",
4100,4101c4100,4101
<         "start_time",
<         "end_time",
---
>         "startTime",
>         "endTime",
4104c4104
<         "num_trials",
---
>         "numTrials",
4459,4461c4459,4461
<         "master_id",
<         "cluster_id",
<         "cluster_name"
---
> …
```
> chore: fix mismatched required api attribute names [DET-4648]

- docs/topic-guides/index.txt
- docs/topic-guides/system-concepts/resource-pool.txt
Add a topic guide for resource pools.
N/A
N/A
> docs: add topic guide for resource pools [DET-4348]

- webui/react/src/App.module.scss
- webui/react/src/App.test.tsx
- webui/react/src/App.tsx
- webui/react/src/components/Page.module.scss
- webui/react/src/styles/antd.scss
- webui/react/src/styles/index.scss
- webui/react/src/utils/browser.ts
Depending on different mobile browsers, the viewport height of 100 does not take the browser chrome into calculation. Meaning, when you view the mobile view the bottom of our page will be cut off instead of rendering all of the page to fit nicely in the visible content area.
Detailed explanation of the viewport issue on mobile:
https://css-tricks.com/the-trick-to-viewport-units-on-mobile/
Before:
After:
Test in iOS simulator, both iOS Safari and iOS Chrome.
Test in actual devices once deployed.
> style: correct mobile viewport [DET-4664]

- agent/internal/agent.go
- agent/internal/fluent.go
This change introduces logic to restart fluentbit on failures.
> chore: restart fluentbit on failures [DET-4665]

- common/determined_common/api/experiment.py
I hit this trying to use `--local --test` on a model that @katport wrote.
> fix: accept None-type hyperparameters with --local

- docs/reference/experiment-config.txt
- docs/release-notes/1719-fix-asha-max-concurrent-trials.txt
- docs/topic-guides/hp-tuning-det/hp-adaptive-asha.txt
- master/pkg/searcher/adaptive_asha.go
This change fix and bug and makes a shortcoming of the current `max_concurrent_trials` implementation  explicit in the documenation.
The long term fix is much more complicated and probably involves redesigning the searchers a bit.
> fix: fix asha max concurrent trials

- .circleci/config.yml
- CONTRIBUTING.md
- agent/go.mod
- master/go.mod
- proto/go.mod
Go 1.13 went out of support when 1.15 came out a few months ago, so
let's get everything bumped up.
> chore: update to Go 1.15

- docs/release-notes/1732-feat-more-flexible-local-gradient-agg.txt
- harness/determined/pytorch/_pytorch_context.py
hvd checks to make sure that backward calls before communicating is equal to backward passes per step.  we pass in the aggregation frequency, for backward passes per step, which is fine when backward is called once before an optimizer step.  however, in some train_batch calls, we need to do multiple backward passes before an optimizer step (this is pretty common in nas).  this pr supports this type of train step of which an example is shown below
```
def train_batch(
self, batch: TorchData, epoch_idx: int, batch_idx: int
) -> Dict[str, torch.Tensor]:
data, labels = batch
output = self.model(data)
loss1 = output['loss1']
loss2 = output['loss2']
self.context.backward(loss1)
self.context.backward(loss2)
self.context.step_optimizer(self.optimizer)
return {"loss1": loss1, "loss2": loss2}
``` …
> feat: support multiple backward call per train_batch in pytorch [DET-4667]

- docs/release-notes/1735-fix-command-priority.txt
- master/internal/command/command.go
Priority scheduler did not respect user set priorities in determined commands; this was due to priorities not being updated from their default set values. This fix allows determined commands to take on user defined priority levels.
Launch some commands with different priority levels and use det task list to check priorities are properly set.
> fix: command priority not respected [DET-4674]

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- e2e_tests/tests/config.py
- e2e_tests/tests/fixtures/tf_keras_grad_aggregation/grad_aggregation_test.py
- examples/gan/dcgan_tf_keras/const.yaml
- examples/gan/dcgan_tf_keras/distributed.yaml
- harness/determined/estimator/_estimator_context.py
- harness/determined/keras/_tf_keras_context.py
- harness/determined/keras/_tf_keras_trial.py
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp_config.go
- master/pkg/model/defaults.go
- tools/scripts/bumpenvs.yaml
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
Rebased onto horovod 0.21.0. The API of the horovod optimizer changed for Estimators + Keras.
We handle this in a backwards compatible way.
Ran full suite of tests: https://app.circleci.com/pipelines/github/determined-ai/determined/8336/workflows/ef7e0193-f8c7-49a0-99aa-6f89811f7e7c
> feat: rebase onto horovod 0.21.0 [DET-4668]

- .circleci/config.yml
The old version used an old Helm-related URL that is no longer correct,
leading to CI failures. The new version is the current latest version.
- [run Kubernetes CI tests](https://app.circleci.com/pipelines/github/determined-ai/determined?branch=helm-orb-upgrade) and see that they get past the installation step where they were failing before
> ci: upgrade version of CircleCI Helm orb

- docs/reference/helm-config.txt
- docs/release-notes/1737-elastic-kubernetes.txt
- helm/charts/determined/Chart.yaml
- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/values.yaml
This mostly involves passing a bunch of values through the config
template from the Helm values file into the final master config.
Documentation is also provided.
Should we also manage an Elasticsearch service ourselves at some point? That sounds like a whole other thing and I'm not really clear if that was supposed to be in scope.
> feat: enable configuring trial logs backend on Kubernetes

- .circleci/config.yml
Recently, nightly tests have been failing because only two files contain
`nightly`-marked tests and CircleCI's test splitting, due to how it
works on files without timing information, tends to put both of those
files in the same one of two parallel runs, causing the other one to
fail with no tests found.
This avoids that issue by explicitly limiting the splitting of E2E tests
to operate on only test files containing the requested mark (or all
files as before if no mark is provided, though that never actually
happens in our config).
There's potentially some fragility to this (e.g., I first included `@` in the `grep` and that missed some tests that pass the mark to another pytest helper instead of decorating a function directly), but I think it should be pretty fine; happy to hear opinions …
> ci: split CircleCI tests more carefully

- agent/internal/fluent_intg_test.go
- master/internal/elastic/elastic.go
This change fixes two race conditions with the agent integration tests. One involved us not waiting for the container to exit before checking the logs. The other involved logs showing up out of order and from different fluent flushes. This is fixed by awaiting the logging container exit and just waiting for all the logs and resorting them when checking if they were received.
> test: fix race condition in test-intg-agent

- docs/reference/api/pytorch.txt
- docs/release-notes/1647-feat-pytorch-custom-reducers.txt
- harness/determined/_trial_controller.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/pytorch/__init__.py
- harness/determined/pytorch/_experimental.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/pytorch/_reducer.py
- harness/tests/experiment/fixtures/pytorch_onevar_model.py
- harness/tests/experiment/pytorch/test_pytorch_trial.py
- harness/tests/experiment/utils.py
Allow users to write custom reducer logic for metrics in PyTorch via context.wrap_reducer().
No tests have been written yet.
Presently this change is going through internal dogfooding.
> feat: support custom reducers for PyTorch [DET-3695] [DET-4698]

- e2e_tests/tests/fixtures/metric_maker/metric_maker.py
- harness/determined/callback.py
- harness/determined/layers/_workload_manager.py
- harness/determined/tensorboard/metric_writers/callback.py
chore: hack tensorboard support to include custom metrics [DET-4697]
Our Tensorboard support is still based on the totally outdated Callback
class (BatchMetricWriter is the only remaining implementation of
Callback).
The bug was that PyTorch custom reducers for training metrics did not
show up in Tensorboard at all.  This is because they are only set in
avg_metrics, and the Callback interface never used to pass avg_metrics.
Since there is only one implementation of Callback, we can just change
pass batch_metrics and avg_metrics to allow BatchMetricWriter to detect
these custom reduced metrics.  It would be preferable to break the
Tensorboard logic out of the WorkloadManager, but this hack is easy
enough to land in time for the feature release of PyTorch custom
reducers. …
> chore: hack tensorboard support to include custom metrics [DET-4697]

- master/internal/kubernetes/spec.go
The Fluent Bit Kubernetes container config was largely copied from the
main container one, and so I accidentally included a duplicate request
for GPUs, meaning that trial pods could never be scheduled.
> fix: don't request GPUs for Fluent Bit container

- docs/release-notes/1772-fix-workload-durations.txt
- webui/react/src/services/decoder.ts
add the missing `endTime` property for metric based workloads (training and validation)
> fix: add endTime to metric workloads [DET-4743]

- docs/reference/cluster-config.txt
This came up in the oss-community slack a while back, had a note to fix it hanging around.
> docs: fix incorrect field name in docker registry creds docs

- .circleci/config.yml
We've occasionally seen CI failures due to what looks like an OOM kill
of the Go compiler during the GoReleaser packaging step. This bumps up
the memory available to that step from 4 GB to 6 GB [1], hopefully
preventing that failure from continuing to happen.
[1] https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes
Well, if the CI on this PR doesn't immediately fail, I'm pretty sure we're in no worse a state than we were before.
> ci: increase resource class for packaging steps

- .circleci/config.yml
The build itself is nearly a minute faster in development mode; that
doesn't translate 100% into overall expected time saved on per-PR CI,
but it should have a decent effect.
> ci: build React in development mode for E2E tests

- docs/topic-guides/yaml.txt
Edit out the distinction between maps and key-value pairs (which doesn't
seem to actually exist), add a section on scalars, and generally massage
the text to more precisely describe things.
> docs: edit YAML topic guide

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/secure.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/deployment_types/vpc.py
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/cli.py
- deploy/determined_deploy/gcp/terraform/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/main.tf
- deploy/determined_deploy/gcp/terraform/modules/compute/variables.tf
- deploy/determined_deploy/gcp/terraform/variables.tf
- e2e_tests/tests/config.py
I wanted this for CI, so we could easily test with non-default images (like when we're transitioning to new framework versions, etc.) Specifically wanting it for CUDA 11.
Spun up clusters on AWS and GCP and confirmed the images were set. Testing the default case now to make sure the defaults still get applied with no failures.
I believe this would fail if you specified one but not both. I'm thinking about either requiring both options or neither, or fixing it so that if you only set one in the YAML we just use the default for the other. (update: I changed it so if one is specified, the other is required).
> chore: Support changing default images in det-deploy on cloud [DET-4689]

- agent/internal/containers.go
- agent/internal/fluent.go
- master/internal/api/logs.go
- master/pkg/fluent/fluent.go
- tools/docker-compose.yaml
This change makes some tweaks to the fluent config to make it a little more reliable in the face of large log bursts and master or elastic backpressure.
(Old comment, retro below) This probably will matter more when we perf test elastic, but these are the things we're going to need to be tuning, probably. We probably should've been using `non-blocking` mode for the log driver all along, too, but using `non-blocking` without turning on the mmap buffers to the filesystem escape hatch means where we might've crashed the job before we would just lose logs --- with the escape hatch we should be able to recover unless we get too many logs for too long.
As remarked in https://determinedai.atlassian.net/browse/DET-4714, not running in non-blocking mode lead to very strange and unavoidable crashes …
> chore: tune Fluent Bit logging performance [DET-4714]

- master/internal/db/postgres_experiments.go
Caleb hit an issue working with the trial-sample endpoint, where if you supply a non-existent metric it breaks. Which isn't terribly surprising, except it breaks in the SQL scan phase because the JSON functions in the query just return empty columns. This is complicated because in the near future we also want to deal gracefully with sparse metrics (i.e. a metric is real but it isn't recorded every step) and maybe later things like nested metrics. One way or another we can't use the default SQL scanner anyway, so here I use my own and deal gracefully with missing values (and if you specify a metric that doesn't exist, you get no results - we can't 100% reliably distinguish between that and a sparse metric.
Ran through Caleb's initial test with both real and fake metrics, and reran the …
> chore: deal gracefully with missing values in trials-sample [DET-4771]

- master/internal/api_experiment.go
- master/internal/db/postgres.go
- master/internal/db/postgres_experiments.go
We originally discussed not support single-trial experiments in the sampling function that chooses the top-N trials. But it turns out it's still useful visualization (learning curve, etc.) to just pick the one trial and return its data.
The integer conversions here are because I was adding a function near other similar functions in postgres.go and saw we use int's internally all over the place for these IDs. So I'm just using int32 where it's needed for protobuf stuff.
Ran manually against a single-trial experiment.
> chore: update trials-sample endpoint to support a single trial experiments [DET-4688]

- docs/release-notes/deprecate-old-pytorch-api.txt
Deprecate the old Pytorch API.
N/A
N/A
> docs: deprecate old PyTorch API [DET-4772]

- deploy/determined_deploy/aws/aws.py
- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- docs/release-notes/1790-det-deploy-aws-list.txt
Support det-deploy aws list. It will list all the cloudFormation stacks that are managed by det-deploy aws. It is based on using the tags of cloudFormation stack. It uses constant tag pair `managed-by:determined` for identifying which stacks are spun up by det-deploy. It won't list the stacks that are spun up by previous versions of det-deploy.
Manually test it.
N/A
> feat: det-deploy aws list [DET-4607]

- e2e_tests/tests/experiment/test_noop.py
- e2e_tests/tests/fixtures/estimator_no_op/model_def.py
- e2e_tests/tests/fixtures/keras_no_op/model_def.py
This wasn't caught until recent CUDA 11 testing enabled a lot more tests on TF 2.x specifically. We weren't calling uniform(), we were returning the function itself. Actually calling it is somewhat pointless because estimators is a graph-mode-only framework and you just can't use the RNG this way easily. As before, we're doing a best-effort attempt to restore RNG state in TensorFlow, but it simply doesn't support this 100% anyway.
> chore: TF RNG in Estimators test would require a session [DET-4624]

- master/pkg/searcher/event_log.go
- master/pkg/searcher/searcher.go
This change updates the searcher code to only consider `workload.Errored` exits as errored. Previously all exits (true failures, user requested stops and soon invalid HPs) were counted as `earlyExits`. Since `earlyExits` are use to determine if an experiment has failed, this meant that if all trials of an experiment were requested to be stopped by the user, the experiment would be `ERRORED`. This is confusing, especially since the state of all the trials is `COMPLETED`.
> fix: requested stops shouldn't be treated as errored [DET-4725]

- master/internal/api_experiment.go
- master/internal/db/postgres.go
- master/internal/db/postgres_experiments.go
This reverts commit 1e2dc7872af8f0991232722f0ce6996c062e49de.
This is a clean revert. There were just conflicting discussions: we've decided that displaying the learning curve plot for single-trial experiments is wholly redundant with the trial view, so the web UI currently uses the error thrown by the backend to display a more helpful recommendation to the user.
> chore: Revert DET-4688, do not support single-trial experiments in trials-sample endpoint [DET-4840]

- e2e_tests/tests/experiment/test_metrics.py
- master/internal/api_experiment.go
- master/internal/config.go
- master/internal/core.go
- master/internal/db/postgres_experiments.go
- master/internal/experiment.go
- master/internal/hpimportance/hpimportance.go
- master/internal/hpimportance/manager.go
- master/internal/hpimportance/worker.go
- master/pkg/actor/context.go
- master/pkg/actor/pool/pool.go
- master/pkg/actor/ref.go
- master/pkg/model/experiment.go
- master/static/migrations/20201211160817_add-hpimportance-fields.down.sql
- master/static/migrations/20201211160817_add-hpimportance-fields.up.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
This is the initial infrastructure required for hyperparameter importance: automatically triggering computation after every 10% milestone in the experiment, or every 10 minutes, whichever is slower, doing so for training loss (if it exists) and the searcher metric, and a streaming API to retrieve the results.
It has been designed to allow the results to be computed with respect to arbitrary metrics on-demand, although that API does not exist today.
Added the same type of integration test I've been giving all of the streaming metrics APIs, and did some manual poking via curl.
One possible redesign to consider in the future is how we allocate workers for this. It's unlikely to be constantly working, but when it is working each task is computationally expensive (may be a couple of minutes on …
> chore: Endpoint and infrastructure for hyperparameter importance computation [DET-4464]

- common/determined_common/storage/gcs.py
We saw a [CI failure](https://app.circleci.com/pipelines/github/determined-ai/determined/8819/workflows/a6dd8e75-07fd-4300-8bb8-6b3b287c25fb/jobs/242223) recently due to an HTTP 504 (gateway timeout)
received while uploading to GCS; this adds a superclass of the
corresponding exception type to the list of types that will trigger
retrying uploads.
Otherwise, this is pretty unlikely to cause any material issues. At worst, it may cause a nonrecoverable failure to take a bit longer to surface.
> chore: retry for more errors when uploading to GCS

- agent/.golangci.yml
- master/.golangci.yml
- master/cmd/determined-master/init.go
- master/cmd/determined-master/main.go
- master/go.mod
- master/go.sum
- master/internal/api/params.go
- master/internal/api_experiment.go
- master/internal/command/command.go
- master/internal/provisioner/aws_spot_collections.go
- master/internal/provisioner/gcp.go
- master/internal/provisioner/gcp_config.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/resourcemanagers/resource_pool_config.go
- master/internal/sproto/globals.go
- master/pkg/actor/pool/pool.go
- master/pkg/archive/archive.go
This change enables the following golangci-lint linters:
- exportloopref: prevent the bug that was fixed by #1834
- gochecknoinits: reduce the side effects of imports
- godot: help comment formatting conform with standard Go conventions
The calls to `rand.Seed` and `petname.NonDeterministicMode` are
technically unnecessary, since `github.com/labstack/gommon` internally
seeds the global random `math/rand` generator on import and they all go
to the same place. But that should be treated as an implementation
detail and the multiple seeding is harmless, though pointless.
> chore: enable some more Go linters

- proto/src/determined/api/v1/trial.proto
- webui/react/src/components/LogViewer.module.scss
- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/ioTypes.ts
- webui/react/src/pages/TrialLogs.tsx
- webui/react/src/services/api.ts
- webui/react/src/services/apiConfig.ts
- webui/react/src/services/decoder.ts
- webui/react/src/services/types.ts
- webui/react/src/styles/icons.scss
- webui/react/src/types.ts
When there are a lot of trial logs happening with a short time of 1 second, the log viewer can potentially stop rendering older logs. The issue is that the requests are based on timestamps and with only resolution of whole seconds, the request for older trial logs remain the same, making it seem like the trial logs has terminated at that timestamp.
Update the trial log requests to use timestamps with milliseconds resolution.
> fix: increase trial log timestamp resolution to support milliseconds [DET-4861]

- docs/reference/api/pytorch.txt
- harness/determined/pytorch/_pytorch_context.py
Removed the ReduceLROnPlateau docs, which were out-of-date, and replaced them with a warning in `wrap_lr_scheduler`
I'm not sure if it is better to have more verbose documentation or to detect the common errors and document workarounds at the moment we detect them.  My sense is that our docs are too verbose so I went with the latter in this case.  I could be convinced otherwise though.
> chore: add custom error for torch's ReduceLROnPlateau

- master/internal/resourcemanagers/resource_manager_config.go
Fix bug where scheduler settings for a resource pool are filled in by default. Correct behavior should allows the scheduler config to be empty, which indicates that the resource pool should inherit the settings from the ResourceManager's settings.
This PR is a follow on to #1847, which missed one location where the scheduler is being configured with defaults where it should actually be left unconfigured. This PR fixes that mistake.
> fix: another place scheduler config for resource pool not being inherited

- agent/Makefile
- agent/go.sum
- master/Makefile
- master/go.sum
In order to keep everybody's dependencies in sync, avoid changing
people's local files after builds, and clean up old dependencies as soon
as possible, it is helpful to ensure that the committed versions of
`go.mod` and `go.sum` files are not changed by `go mod tidy`.
> ci: check that Go dependencies are tidied

- master/internal/grpc/api.go
For large experiments, some API endpoints can result in response bodies
larger than 4 MiB, which is the default maximum size that the gRPC-HTTP
proxy allows. This bumps the limit to 64 MiB to push the problem farther
away.
Pagination for our clients is on the way, which is the real solution.
> fix: allow larger gRPC response bodies

- common/determined_common/experimental/checkpoint/_torch.py
- docs/reference/api/pytorch.txt
- docs/release-notes.txt
- docs/release-notes/1784-remove-deprecated-pytorch-api.txt
- harness/determined/_experiment_config.py
- harness/determined/_trial_controller.py
- harness/determined/errors.py
- harness/determined/pytorch/__init__.py
- harness/determined/pytorch/_callback.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/util.py
BREAKING CHANGE: remove the deprecated Pytorch API.
N/A
N/A
> chore: remove the deprecated PyTorch API [DET-3262]

- schemas/Makefile
Checking schemas had assumed GNU version of the `find` command,
which assumes `.` as the starting point if none is provided. This
could cause build errors on Mac, whose built-in `find` utility
requires a starting point ("find: illegal option -- n").
> build: fix for `make check-schemas` on non-GNU build machines

- docs/release-notes/1803-improve-api-perf.txt
- master/internal/api_experiment.go
- master/internal/db/postgres.go
- master/static/srv/get_experiments.sql
Move filtering to the database when querying the experiments. Since the WebUI queries the experiments API every 5 seconds and the CPU usage is mostly spent on unmarshalling during querying when there are many users the master would undertake huge pressure on the CPU. This PR moves experiment filtering to the database so the database would return fewer experiments.
Manually tested it by using filtering in the WebUI.
This PR doesn't choose to move pagination to the database because the WebUI needs the number of all the filtered experiments to display the number of pages.
> perf: move experiment filtering to database [DET-4770]

- docs/release-notes/1877-fix-trial-hanging.txt
- master/internal/trial.go
It has been noticed that the trial doesn't deallocate resources when it fails at writing to the DB. The killing logic starts when failing at writing to the DB but then the trial waits for the container terminated message, which will never come. This PR fails the trial directly rather than handling restarting when the failure is caused by the DB.
N/A
N/A
> fix: trial hangs when it fails to write to the DB [DET-4905]

- harness/determined/ipc.py
- requirements.txt
This wasn't caught in the PR, but I was able to reproduce it locally after resetting my Conda environment.
`make -C harness check` passes now, whereas it doesn't in a clean Conda environment (with only the top-level requirements.txt installed) before.
> chore: fix type errors in IPC code

- .circleci/config.yml
- docs/how-to/installation/dynamic-agents-gcp.txt
- docs/how-to/installation/requirements.txt
- e2e_tests/tests/command/test_run.py
Adds some CI coverage for the CUDA 11 images that were recently published in connection with the upgrades to PyTorch and TensorFlow.
Ran the relevant tests here: https://app.circleci.com/pipelines/github/determined-ai/determined/9339/workflows/5afe5b24-3061-4508-88f1-f31037cf1c24.
A couple of things to note:
I consider it very hacky, but as a cost-effective way to maximize test coverage here, I'm setting a TF2 image as the TF1 default image, since the TF1 image is THE default, and is specified in many places. There's only 1 test that this causes a problem for (test_horovod_optimizer when tf2=false).
Also I'm having to use the "rapid" channel of GKE versions to use the A100 instances, and this means the version string may be a little fragile moving forward. It's always an easy fix at …
> feat: Documentation and CI of support for NVIDIA A100's and Google A2 instances

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
- deploy/determined_deploy/gcp/constants.py
- docs/release-notes/1851-framework-upgrades.txt
- e2e_tests/tests/config.py
- e2e_tests/tests/requirements.txt
- examples/gan/dcgan_tf_keras/const.yaml
- examples/gan/dcgan_tf_keras/distributed.yaml
- harness/setup.py
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp_config.go
- master/pkg/model/defaults.go
- tools/scripts/bumpenvs.yaml
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/experiment-details/set-a.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
Bumping to the recent TF 2.4.1 release to eliminate a requirement for AVX2.
GPU tests are running on an upstream branch.
> chore: Bump images and versions to Tensorflow 2.4.1

- docs/faq.txt
- docs/how-to/custom-env.txt
- docs/how-to/index.txt
- docs/how-to/model-debug.txt
- docs/reference/api/estimator.txt
- docs/reference/api/keras.txt
- docs/reference/api/pytorch.txt
- docs/release-notes/1895-model-debug-doc.txt
- docs/requirements.txt
- docs/topic-guides/model-definitions/best-practices.txt
- docs/topic-guides/model-definitions/trial-api.txt
It is looking like the observability project is going to solve what I was trying to solve in https://github.com/determined-ai/determined/pull/1625, only much better.  As a result, I'm pulling out just the debug documentation as a separate PR to land now.
> docs: add model debug doc

- docs/release-notes/1912-fix-trial-log-order.txt
- webui/react/src/components/LogViewerTimestamp.tsx
The trial log buffer is currently added in reverse order when the stream is in ascending order, causing logs within the same second to be in the reverse order.
- check that the log entry order is the same regardless of tailing behavior vs scroll to oldest behavior.
> fix: buffer the trial log in the correct order [DET-4931]

- deploy/determined_deploy/local/cli.py
- deploy/determined_deploy/local/cluster_utils.py
- docs/how-to/installation/deploy.txt
Add ability to specify which resource pool an agent should join in det-deploy local
> feat: support resource pools in det-deploy local agent-up [DET-4938]

- docs/faq.txt
- docs/how-to/installation/aws.txt
- docs/reference/cluster-config.txt
- docs/release-notes/1846-resource-pools.txt
- docs/topic-guides/index.txt
- docs/topic-guides/system-concepts/resource-pool.txt
Improve resource pool docs and add release notes for the resource pool feature.
> docs: clean up resource pool docs and add release notes

- docs/how-to/model-debug.txt
Fix typos in documentation on debugging models
> fix: typos in model debugging doc

- harness/determined/keras/_tf_keras_trial.py
Added docs that clarify the need for additional configuration when using TF 1.15 in eager mode with Determined.
> docs: clarification instructions for TF 1.15 eager mode

- docs/how-to/model-debug.txt
- Use the signup link for all links to the community Slack, since that
redirects to the actual workspace if the user is already signed
up (and perhaps the links will mostly be clicked by people who haven't
signed up anyway).
- Remove indentation that led to unnecessary blockquote elements.
- Make other miscellaneous copy edits.
> docs: edit model debug doc

- master/internal/agent/slot.go
- master/internal/agent/slots.go
- master/internal/resourcemanagers/agent.go
- master/internal/resourcemanagers/priority_test.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/sproto/agent_resource_manager.go
Previously, the agent resource pool relies on the container state change message to deallocate resources. This PR changes that to always deallocate resources when a task actor fails.
1. Start the cluster
2. Alter the table using the following SQL to fail the trial actor.
```sql
alter table trials drop column seed;
```
3. submit an adaptive experiment.
4. see if the resources get deallocated.
This PR doesn't fix that the experiment state should error out if a trial fails to write to the DB.
> fix: always deallocate resources if a task actor fail [DET-4973]

- docs/release-notes/1942-fix-pre-0-13-8-logs.txt
- master/internal/db/postgres_trial_logs.go
This change tweaks the query used to retrieve trial logs to select the timestamp from the old field `public.trial_logs.message` where it doesn't exist for old logs.
> fix: add backwards compatability for logs before 0.13.8

- master/internal/db/postgres_filters.go
- master/internal/db/postgres_trial_logs.go
This change makes the query to gather trial logs with timestamp filters backwards compatible with logs created before 0.13.8.
Bit of a hack, but it's necessary
> fix: make trial log timestamp filters backwards compatible 

- master/internal/checkpoint_gc.go
- master/internal/command/command.go
- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pod_test.go
- master/internal/kubernetes/spec.go
- master/internal/trial.go
- master/pkg/model/environment_config.go
- master/pkg/tasks/ports.go
- master/pkg/tasks/task.go
- master/pkg/tasks/task_spec.go
For a long time, we've had largely separate code paths with a bunch of
duplication to handle each of the three top-level task types (trials,
checkpoint GC, and commands). That started with the agent code and
transferred over into Kubernetes as well. This change unifies the code
paths to operate on a generic task spec type that has methods providing
the parameters that differ between tasks; everything only operates on
that type generically.
`TaskSpec`, rather than containing a pseudo-union (three pointers,
exactly one of which is expected to be non-nil), now holds one instance
of a new interface that is implemented by a concrete struct type for
each of the task types.
- run various tasks with both agents and Kubernetes and check that ports are forwarded, logs come through, etc.
It's not …
> refactor: reduce code duplication across task types

- common/determined_common/experimental/experiment.py
- e2e_tests/tests/test_system.py
- master/internal/db/postgres.go
- master/internal/db/postgres_experiments.go
- master/internal/db/postgres_proto.go
- master/internal/experiment_utils.go
- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/internal/trial_workload_sequencer_test.go
- master/pkg/model/experiment.go
- master/pkg/workload/workload.go
- master/pkg/workload/workload_test.go
- master/static/migrations/20210208000000_add-total-batch.down.sql
- master/static/migrations/20210208000000_add-total_batch.up.sql
- master/static/srv/get_checkpoint.sql
- master/static/srv/get_checkpoints_for_experiment.sql
- master/static/srv/get_checkpoints_for_trial.sql
- master/static/srv/get_model_version.sql
- master/static/srv/get_model_versions.sql
- master/static/srv/get_trial.sql
- master/static/srv/get_trial_metrics.sql
- master/static/srv/proto_get_trial_ids_for_experiment.sql
- master/static/srv/proto_get_trial_workloads.sql
- master/static/srv/proto_get_trials_plus.sql
- master/test/integration/api/api_trials_test.go
Replace the use of step id with the total batch in the DB. Any checkpoint, training metric, validation can be located with a trial id and a total batch number. They used to depend on the concept of steps. In order to hand over the control on checkpointing and validating to the user code, all the internal use of steps should be abandoned.
In the meantime, remove the constraint that all checkpoints and validations need to be associated with a step. We will change the restful APIs later to return the checkpoints and validations of all total_batches rather than just those of steps.
1. Use the CI for testing.
2. Manually test running experiments of constant hp params and adaptive hp search on 
training metrics, validations, checkpoints, and fault tolerance.
N/A
See [Release …
> refactor: replace step IDs with total batch in the DB

- deploy/determined_deploy/aws/cli.py
- deploy/determined_deploy/aws/constants.py
- deploy/determined_deploy/aws/deployment_types/secure.py
- deploy/determined_deploy/aws/deployment_types/simple.py
- deploy/determined_deploy/aws/deployment_types/vpc.py
- deploy/determined_deploy/aws/templates/efs.yaml
- deploy/determined_deploy/aws/templates/fsx.yaml
- deploy/determined_deploy/aws/templates/secure.yaml
- deploy/determined_deploy/aws/templates/simple.yaml
- deploy/determined_deploy/aws/templates/vpc.yaml
`det-deploy aws up` now supports two new options: `--retain-log-group`
and `--log-group-prefix`. The former sets the CloudWatch log group that
is created for the stack to not be deleted when the rest of the stack
is, which may be useful in some situations. The latter sets the prefix
that is applied to the stack name to generate the log group name
(default "determined", leading to the same behavior as before).
Because CloudFormation's templating is terrible, the implementation
looks a bit awkward. The `DeletionPolicy` field is required to be a
literal, so it is not possible to use an expression to set it
conditionally. Instead, we have to define two separate resources, one
retained and one not, each of which is created conditionally. As far as
I can tell, those conditions can't be written …
> feat: allow retaining CloudWatch log groups of det-deploy clusters

- .circleci/config.yml
- deploy/determined_deploy/aws/templates/simple.yaml
In order to avoid the (somehow) error-prone step of exporting CI logs
from CloudWatch to S3, we now set logs from CI-spawned det-deploy AWS
test clusters to be retained after the CloudFormation stacks are
deleted. Those log groups also now have a new "determined-ci" prefix to
separate them from other log groups, now that they're going to stick
around.
This also includes a fix for an issue in updating a stack after the
recent det-deploy change introducing log retention: the logical name of
a deleted log group is now set to the same as it was before, which
should avoid a conflict in CloudFormation.
> ci: set a CI-specific prefix for and retain CloudWatch log groups

- .circleci/config.yml
Due to an incorrect shell script, `--retain-log-group` was being set for
all AWS clusters, even when it shouldn't've been.
Watch the deploy on master!
> ci: fix retention of CloudWatch logs for deploy clusters

- CODEOWNERS
- master/internal/api/logs.go
- master/internal/api_auth.go
- master/internal/api_command.go
- master/internal/api_experiment.go
- master/internal/api_master.go
- master/internal/api_notebook.go
- master/internal/api_trials.go
- master/internal/api_user.go
- master/internal/core.go
- master/internal/grpcutil/api.go
- master/internal/grpcutil/auth.go
- master/internal/grpcutil/errors.go
- master/internal/grpcutil/logging.go
- master/internal/grpcutil/validate.go
As suggested by Bradley in a previous review, the pattern of periodically checking for a dead context and then returning nil allows us to gracefully terminate the loop when the client connection is closed. This was previously done after sleeping before beginning another iteration, but doing it right before actually sending the response drops the probability of a mess in the logs for no good reason about as low as we can get it.
Also refactoring more of this into it's own function, since it now appears 8 times in this file.
I don't like the name I chose for duplicate import: "grpcroot". Trying to think of a better alternative.
test_metrics.py has decent coverage of these functions.
> chore: check for closed connections before sending [DET-4829]

- master/internal/experiment.go
- master/internal/restore.go
- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/internal/trial_workload_sequencer_test.go
This commit changes how trial operations snapshotted in the experiment state are given to trials during a restore. Previous, the experiment would sent all these operations to trials after starting, now they are added to the trial before it is restored.
The only part really necessary for this fix is the bit that changes how we were calling `s.Workload()` in `t.reset()`. The other bits are because, the way restart was written, we were starting a trial in an invalid state (without its operations) which I realized later (now) is totally wrong.
> fix: restore trials with operations intact to avoid unintended behavior [DET-4994]

- docs/how-to/custom-env.txt
- docs/release-notes/1971-new-environment-images.txt
After reverting the change to use the new images by default in the last release, we have decided to continue defaulting to the old images, but document and offer the new ones for people to migrate to as they need new features, confirm their models perform well in the new versions, etc.
This requires a few updates to the docs, and also correcting some errors in the same sections.
> chore: update documentation for new images [DET-4998]

- master/internal/command/command.go
- master/internal/command/state.go
- master/internal/command/summary.go
- master/pkg/container/state.go
- proto/src/determined/api/v1/task.proto
- proto/src/determined/command/v1/command.proto
- proto/src/determined/notebook/v1/notebook.proto
- proto/src/determined/shell/v1/shell.proto
- proto/src/determined/task/v1/task.proto
- proto/src/determined/tensorboard/v1/tensorboard.proto
- update tasks api to return a top-level state
- share the logic with the old endpoint
> fix: add state to task endpoints [DET-4987]

- .circleci/config.yml
- agent/.goreleaser.yml
- docs/faq.txt
- docs/how-to/installation/kubernetes.txt
- helm/Makefile
- helm/charts/determined/Chart.yaml
- helm/charts/determined/templates/change-password.yaml
- helm/charts/determined/templates/master-deployment.yaml
- helm/charts/determined/values.yaml
- master/.goreleaser.yml
Push docker images to the NGC repo and also push the helm charts.
1. Build the helm charts for all the branches and all the PRs.
2. Push the release docker images to `nvcr.io/isv-ngc-partner/determined`.
3. Push the release and release candidates helm charts to `helm/ngc.nvidia.com/isv-ngc-partner/determined`.
1. manually run a test release candidate in the CI.
2. check if the NGC repo has the docker image.
3. check if the NGC helm repo has the charts.
4. install the helm chart from the NGC repo into a k8s cluster.
The steps are:
1. Create a k8s cluster and node pool.
2. Create a secret using [kubectl create secret](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/).
3. Modify the ``imageRegistry`` field to ``nvcr.io/isv-ngc-partner/determined`` in …
> ci: deploy NGC images as part of release [DET-4910]

- docs/release-notes/1979-k8s-cluster-page.txt
- master/internal/resourcemanagers/kubernetes_resource_manager.go
Change the "details" field in the Resource Pool GET API to be an empty struct instead of nil to be consistent with the non-kubernetes behavior. This fixes a bug where the Cluster page in the WebUI would crash because it expects that field to exist in the response.
Manually tested on a k8s cluster.
> fix: k8s resource pool API response should not have nil field [DET-4989]

- common/determined_common/api/authentication.py
- common/determined_common/api/request.py
- master/internal/api_auth.go
- master/internal/checkpoint_gc.go
- master/internal/command/command.go
- master/internal/command/command_manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/db/postgres_tasks.go
- master/internal/db/postgres_users.go
- master/internal/db/setup.go
- master/internal/grpcutil/auth.go
- master/internal/trial.go
- master/internal/user/service.go
- master/pkg/model/task_session.go
- master/pkg/tasks/task_spec.go
- master/static/migrations/20210211000000_add-task-session.down.sql
- master/static/migrations/20210211000000_add-task-session.up.sql
All the harness internal APIs will access the restful APIs with authentication. It uses a task token that is passed into the container. All task tokens' lifecycles are tied with the tasks' lifecycles.
Specifically, all the requests can have an HTTP header key-value pair with the key `Grpc-Metadata-x-task-token`. The gRPC server on the master will truncate the prefix `Grpc-` in the HTTP header and look it up in the task session list that exists in the database.
Use it only internally. So tested it manually by the following command:
```
det command run --config 'resources.slots=0' 'curl -H "Grpc-Metadata-x-task-token: Bearer $DET_TASK_TOKEN" GET "$DET_MASTER/api/v1/experiments"'
```
N/A
> chore: support task tokens in harness for authentication [DET-4897]

- proto/src/determined/api/v1/experiment.proto
Add limit 0, -1 and -2 behavior to generated rest-api docs for GET experiments.
> docs: add documentation regarding limit behavior for pagination

- .circleci/config.yml
cloud.google.com/kubernetes-engine/docs/release-notes#february_17_2021_2021-r6
> ci: bump gke version

- master/static/srv/get_experiments.sql
This change updates the GET experiments query to handle null jsonb (not just a NULL column) when filtering by labels. The labels column initially is returned as NULL if no labels key exists in the config jsonb. The expression works fine in this case, but if labels are added to an experiment and the removed it will get rewritten as null instead of removing the column which causes `jsonb_array_elements_text` to barf on the call with the arg `null` jsonb. This PR just checks for `null` jsonb and converts it to NULL.
spent like five minutes wondering why `null` wasn't getting coalesced before I realized it was a null jsonb object in a not null column lol.
> fix: fix query for GET experiments [DET-5039]

- common/determined_common/api/experiment.py
- common/determined_common/context.py
There are 2 deprecated warnings in determined-common:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc'
is deprecated since Python 3.3, and in 3.9 it will stop working
```
Solution: Need use `collections.abc.` instead of `collections.`
` make -C common test` without any deprecated warnings on `collections.abc`
> fix: fix deprecation warning on using ABCs from 'collections'

- master/internal/resourcemanagers/agent_resource_manager.go
In GCP, when the number of GPUs is zero, do not include the GPU type as part of the instance type string. This avoids confusing strings such as "n1-standard-4, 0xnvidia-tesla-k80".
Also adds a space between the number of GPUs and the type so that it is easier to read.
This PR seems too trivial to deserve release notes. LMK if you disagree.
> chore:  exclude useless GPU type in resource pool API [DET-5079]

- master/internal/resourcemanagers/kubernetes_resource_manager.go
Forking fails on k8s due to the "default" resource manager not existing. This changes the kubernetes resource manager to return "" instead of "default" as the default resource pools so that forked experiments can pass the resource pool check.
> fix: fix forking failure on k8s [DET-5087]

- docs/release-notes/2022-fix-parcoords-filters.txt
- webui/react/src/components/ParallelCoordinates.tsx
HP Parallel Coordinates filters that are previously removed come back during a re-render. Update the chart to detect filter removal and properly save the removal state.
> fix: detect parcoords filter removal properly

- master/internal/db/postgres.go
- master/internal/elastic/elastic.go
This updates the code that connects to PostgreSQL and Elasticsearch to print warning on connection failures. The occasional superfluous warning is worth the visibility into database connection hangs.
> chore: warn on failures to connect to persitent storage

- master/internal/api_master.go
- master/internal/core.go
- master/static/srv/allocation_raw.sql
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/master.proto
- proto/src/determined/master/v1/master.proto
The new endpoint groups up all steps, checkpoints, and validations to
give information about slot time used in a given time period.
The CSV endpoint needs to do something to deal with multiple labels. Right now it separates them with `|` and adds some escaping. Not sure if there's a standard thing to do here. Quoting?
> feat: add endpoint for raw resource allocation information [DET-5043]

- common/determined_common/schemas/expconf/_v0.py
- common/setup.py
Avoid image complications by using dummy values where petname would be
used.
This is ok since the values in question won't be user-facing until the
python SDK lands.
> chore: remove petname dependency

- docs/how-to/custom-env.txt
We never released an 0.8.0 version of the CUDA 11 image. Double-checked the new string is correct by grepping against some recently-run tests.
> docs: fix version of CUDA 11 image

- webui/react/src/components/ParallelCoordinates.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
Fix issue of categorical hp filtering was not working, so the trial table would remain empty whenever a filter is applied for categorical hps.
The core issue is that categorical hp values are converted to a numerical value to space them out nicely in the parallel coordinates. For example, [ 8, 16, 32 ] categorical values will be converted into [ 2, 4, 6 ] with a range of 1 through 7. 1, 3, 5, 7 are used as spacers to keep each categorical value visually separate. When the user applies a filter to this, the filter constraint comes back as something like [ 1.5, 2.5 ] for filtering on categorical value of 8. Simply need to translate it back to the category.
> fix: support trial filtering based on categorical hps [DET-5107]

- e2e_tests/tests/config.py
- e2e_tests/tests/nightly/test_distributed.py
- examples/computer_vision/deformabledetr_coco_pytorch/model_def.py
- examples/computer_vision/detr_coco_pytorch/model_def.py
Test for single gpu was broken due to a bug in the custom metric reducer that only affected single gpu eval.  Also changed batch size for distributed deformabledetr test to 2 instead of 1 to allow 1 datapoint per gpu.  
> fix: detr and deformabledetr e2e tests

- examples/computer_vision/deformabledetr_coco_pytorch/const_fake.yaml
- examples/computer_vision/deformabledetr_coco_pytorch/finetune.yaml
- examples/computer_vision/deformabledetr_coco_pytorch/model_def.py
- examples/computer_vision/detr_coco_pytorch/const_fake.yaml
- examples/computer_vision/detr_coco_pytorch/model_def.py
Fix e2e tests for detr and deformable_detr by modifying config to run just 1 validation workload instead of the 2 indicated by min_validation_period=100 batches and max_length:200 batches which was causing the time out.  
Also, removed an unused import and clarified a usage of deepcopy.
> fix: detr & deformable_detr e2e-test timeout

- examples/computer_vision/deformabledetr_coco_pytorch/data.py
- examples/computer_vision/detr_coco_pytorch/data.py
Reduces the dataset set when using the FakeBackend for DETR and Deformable DETR so that we will not timeout for e2e capabilities tests.  
> fix: e2e test for deformable detr with fake backend

- docs/release-notes/2061-asha-stopping.txt
- master/pkg/model/defaults.go
- master/pkg/model/searcher_config.go
- master/pkg/searcher/adaptive_asha.go
- master/pkg/searcher/adaptive_asha_test.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/asha_stopping.go
- master/pkg/searcher/asha_stopping_test.go
- master/pkg/searcher/search_method.go
- master/pkg/searcher/simulate.go
Add a stopping-based variant of adaptive search that does not require fault-tolerance for early-stopping.  This variant is based on  the implementation of ASHA in Ray Tune: https://docs.ray.io/en/master/tune/api_docs/schedulers.html#tune-scheduler-hyperband.  
> feat: add stopping-based variant of adaptive search [DET-3669]

- webui/react/src/components/LogViewer.module.scss
not an easy find, but noticed that the issue should be related to separators like quotation marks not properly breaked (see red rect here, the quotation should be there, not going to newline).
Found this https://github.com/w3c/csswg-drafts/issues/1171#issuecomment-494164252
That lead me to this https://developer.mozilla.org/en-US/docs/Web/CSS/line-break
> fix: force line-break to prevent overlapping in trial logs [DET-5121]

- docs/release-notes/2077-model-upload.txt
- harness/determined/_env_context.py
- harness/determined/_execution.py
- harness/determined/constants.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/exec/harness.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/util.py
- harness/tests/experiment/utils.py
- harness/tests/tensorboard/test_util.py
- harness/tests/test_horovod.py
- master/pkg/tasks/task.go
- master/pkg/tasks/task_spec.go
Before we always copied the working directory as model code.  Users
often saw apparent hangs waiting for checkpoint upload, which in fact
were caused by things like us silently trying to upload their entire
dataset to S3.
It might not be a good idea to upload auto-discovered model definitions
to checkpoint storage.  But rather than fundamentally alter the
assumptions of our checkpointing system, this PR just adds a clean copy
of the model which was submitted to the master into the training
container, and during managed training, that clean copy gets uploaded
rather than the /run/determined/workdir.
> fix: only upload model code as model code [DET-3865]

- docs/release-notes/2079-lr-scheduler-frequency.txt
- harness/determined/pytorch/_lightning/adapter.py
- harness/determined/pytorch/_lr_scheduler.py
- harness/determined/pytorch/_pytorch_trial.py
> feat: add frequency support for lr_scheduler [DET-5021]

- e2e_tests/tests/experiment/experiment.py
Download trial logs to artifacts directory for e2e tests.  This will make it easier to debug test failures that do not show up in master or agent logs.  
> ci: print trial logs for timed out e2e_test experiments

- docs/reference/experiment-config.txt
Document usage for stopping-based variant of `adaptive_asha`.
> docs: stopping-based variant of adaptive search

- .circleci/config.yml
- e2e_tests/tests/test_system.py
Adding automated tests of the coscheduler / gang scheduling feature.
This *is* the test plan! The test fails (times out) about 50% of the time when the coscheduler isn't enabled, but reliably passes when it is. This test also has the benefit of exercising the coscheduler more, since our other test clusters usually have auto-scaling, with which the coscheduler isn't supported.
I'm concerned this may be a little flaky because the coscheduler is known to sometimes have timeouts when an experiment requires the entire cluster, which is the case with this test. Since a multi-node job must consume 100% of the GPUs on a certain number of nodes, one alternative would be for the tests to use a 3-node-cluster and 2 (or more) 2-node tests. But let's see if that necessary before making that change. …
> chore: testing gang-scheduling [DET-5134]

- .circleci/config.yml
- e2e_tests/tests/test_system.py
This reverts commit 2c5beaadafc0b50d38de1ec481b263e95e47f208.
This failed a GKE run and needs investigation. It also failed the normal GPU tests because it's missing the TOTAL_SLOTS setting.
I'll fix the TOTAL_SLOTS problem on the GPU tests, and repush this to an upstream branch to troubleshoot the other failure. Reverting now to unblock tests.
> chore: Revert "Testing gang-scheduling [DET-5134]"

- docs/examples.txt
- docs/how-to/installation/deploy.txt
- docs/reference/cluster-config.txt
- docs/reference/command-notebook-config.txt
- docs/reference/experiment-config.txt
- docs/reference/index.txt
- docs/topic-guides/deployment/aws-spot.txt
- docs/topic-guides/system-concepts/resource-pool.txt
- master/pkg/model/experiment_config.go
Also fix a syntax error in the cluster config reference that resulted in
a bunch of list elements being rendered incorrectly.
> docs: improvements to spot instance and resource pool docs

- .circleci/config.yml
- e2e_tests/tests/test_system.py
- helm/charts/determined/templates/NOTES.txt
- helm/charts/determined/templates/master-config.yaml
- helm/charts/determined/templates/priority-classes.yaml
- helm/charts/determined/templates/scheduler-config.yaml
- helm/charts/determined/templates/scheduler-deployment.yaml
- helm/charts/determined/templates/scheduler-permissions.yaml
This is a second attempt at this patch. The last time the tests passed by coincidence (they succeed 50% of the time even without the fix they are validating). The root cause of this is that Helm seems to have some flawed indentation logic for the values overridden via the CLI, and coscheduler was specific with additional newlines and whitespace. If we change the order of the values, it's the GCS bucket that ends up being indented - though it seems to cause no problem. Simply trimming whitespace from the coscheduler value.
Verified on an upstream branch.
> ci: adding coscheduler to static k8s test clusters, and test

- docs/reference/experiment-config.txt
- master/pkg/model/defaults.go
- master/pkg/model/searcher_config.go
- master/pkg/searcher/asha.go
- master/pkg/searcher/grid.go
- master/pkg/searcher/grid_test.go
- master/pkg/searcher/random.go
- master/pkg/searcher/random_test.go
- master/pkg/searcher/util_test.go
This PR allows users to limit the maximum number of concurrent trials training at any given time for grid and random search.  While there is some overlap in capability with `max_slots`, `max_concurrent_trials` works for dynamic agents, which is not true for `max_slots`.  We expect to deprecate `max_slots` in a future release.   
Existing tests for searchers pass and verified that the `max_concurrent_trials` constraint is not violated.
> perf: support max_concurrent_trials for random and grid search [DET-3664]

- docs/reference/api/lightning_adapter.txt
- e2e_tests/.flake8
- e2e_tests/Makefile
- e2e_tests/tests/experiment/test_pytorch_lightning.py
- e2e_tests/tests/fixtures/pytorch_lightning_amp/apex_amp.yaml
- e2e_tests/tests/fixtures/pytorch_lightning_amp/apex_amp_model_def.py
- e2e_tests/tests/fixtures/pytorch_lightning_amp/auto_amp.yaml
- e2e_tests/tests/fixtures/pytorch_lightning_amp/auto_amp_model_def.py
- e2e_tests/tests/fixtures/pytorch_lightning_amp/data.py
- e2e_tests/tests/fixtures/pytorch_lightning_amp/mnist.py
- e2e_tests/tests/fixtures/pytorch_lightning_amp/model_def.py
- examples/computer_vision/mnist_pl/model_def.py
- harness/determined/pytorch/lightning/_adapter.py
- add parameters `precision`, `amp_level`, and `amp_backend` to LightningAdapter to allow user to set up automatic mixed precision using a similar API to trainer and without calling `auto_amp` or `configure_apex_amp`.
- set precision property
gpu e2e tests are added and passed here :
https://app.circleci.com/pipelines/github/determined-ai/determined?branch=ptl-amp
users can opt to avoid using the added parameters and set up AMP themselves using PyTorchTrial APIs
> feat: precision prop and amp support for lightning adapter [DET-5116]

- docs/release-notes/2144-fix-no-data-message-flash.txt
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
There is a split second where hp-viz shows `No data to plot` message when loading the data to populate the chart. The logic just needs a slight tweaking to avoid this.
> fix: avoid showing no-data message for a split second in hp-viz [DET-5099]

- docs/release-notes/2151-fix-no-hp-viz-crash.txt
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
When the experiment does not support hp-viz (single trial experiment or PBT experiment) there is an `useEffect` that causes an infinite loop of constantly updating the `filters` state.
> fix: avoid loop of effect in hp-viz when experiment is not supported [DET-5189]

- examples/gan/gan_mnist_pl/model_def.py
- harness/determined/pytorch/lightning/_adapter.py
- harness/tests/experiment/fixtures/lightning_adapter_onevar_model.py
> fix: fix an issue with wrapping lr_scheduler

- docs/release-notes/2165-fix-tooltip.txt
- webui/react/src/components/HumanReadableFloat.tsx
Fix the issue of showing `undefined` as prefix for human readable tooltips.
> fix: default tooltip prefix to be an empty string

- helm/charts/determined/templates/master-config.yaml
The telemetry setting defaults to true, so it can't use the same pattern
as things that default to false.
Closes: #2175
> fix: allow telemetry to be disabled under Helm [DET-5224]

- master/pkg/searcher/random.go
Fixing bug where we incorrectly incremented `CreatedTrials` for an invalid HP trial.
> fix: bug in random search leading to incorrect total trials

- docs/release-notes/2170-checkpoint-storage-defaults.txt
- harness/determined/deploy/local/cli.py
- harness/determined/deploy/local/cluster_utils.py
- harness/determined/deploy/local/storage.yaml
- harness/setup.py
- master/cmd/determined-master/init.go
- master/pkg/model/defaults.go
- Default storage location for checkpoint data in local clusters deployed via `det deploy local` has been changed to OS-specific user data dir (e.g. `$XDG_DATA_HOME/determined` or `~/.local/share/determined` on Linux, and `~/Library/Application Support/determined` on macOS). Previously, `/tmp` was used.
- This location can be changed using `--storage-host-path` command line flag of `det deploy local`.
- If users provide their own custom `master.yaml` via `--master-config-path`, `checkpoint_storage` configuration in yaml will continue to take precedence.
- Check that the old experiment data in /tmp is not lost after upgrade.
- Check the new default directory works ok, --storage-host-path, and --master-config-path.
[DET-1234]: …
> feat: local clusters to store checkpoint data in home [DET-5154]

- examples/computer_vision/mmdetection_pytorch/docker/Dockerfile
Fix mmdetection example by updating docker image to use torch 1.7 and cuda 10.2.
Tested example locally.
> fix: mmdetection docker image to work with torch 1.7

- webui/react/src/hooks/usePolling.ts
- webui/react/src/pages/ExperimentDetails/ExperimentOverview.tsx
While the experiment is active, the experiment detail page polls to keep the page updated with fresh data. When the experiment reaches a terminal state, the detail page stops polling. This can cause the rest of the page to be out of sync.
Solution is to allow the secondary polling to run one final time before it is terminated. A soft polling stoppage enables this behavior. The polling mechanism will mark the polling to be stopped but the timer for polling is allowed to still run its course to resolve the polling function one final time.
> refactor: improve experiment terminal state [DET-5202]

- e2e_tests/tests/experiment/test_metrics.py
- master/internal/config.go
- master/internal/hpimportance/hpimportance_test.go
The UI will now attempt to use this feature to sort metrics in a drop-down by their relative importance.
Tests are already written, but were disabled along with the feature. Will confirm they are run in pre-commits.
> chore: enable hyperparameter importance computation by default

- harness/determined/deploy/aws/cli.py
- harness/determined/deploy/aws/deployment_types/base.py
- harness/determined/deploy/aws/deployment_types/govcloud.py
- harness/determined/deploy/aws/deployment_types/secure.py
- harness/determined/deploy/aws/deployment_types/simple.py
- harness/determined/deploy/aws/deployment_types/vpc.py
- harness/determined/deploy/cli.py
- harness/determined/deploy/errors.py
- harness/determined/deploy/gcp/cli.py
- harness/determined/deploy/gcp/gcp.py
- harness/determined/deploy/gcp/terraform/outputs.tf
- harness/determined/deploy/healthcheck.py
- harness/determined/deploy/local/cluster_utils.py
- `det deploy {aws,gcp} up` will now poll the master after the deployment until it's up.
- "successful" deployment will take "longer", but as soon as command exists successfully, the cluster should be already good to go (as you don't need to wait extra few minutes for master to come up).
- this behavior can be skipped using `det deploy --no-wait-for-master`.
You can simulate a failing deployment by specifying a bad/unavailable container versions, e.g. doing `--det-version 0.15.0`.
> feat: health check master after cluster creation [DET-5183]

- e2e_tests/tests/experiment/test_metrics.py
This test timed out last night for what appears to be an unrelated failure. However in my investigation I noticed that we could be cutting it very close sometimes. Nightly tests run with a single GPU, so even though this is close to being a no-op model (10 batches on mnist_pytorch), it's 50 trials sequentially, dominated by the startup time of the harness. Just extending the timeout to prevent flakiness.
> chore: extend timeout on HP importance test

- .circleci/config.yml
- Since CircleCI aws cluster deployment with tls certificates waits for master to come up using its own different solution, disable the internal check in `det deploy`.
> fix: disable det deploy wait for aws cluster on circleci.

- harness/determined/pytorch/_pytorch_trial.py
- harness/setup.py
cloudpickle explicitly says not to use it for long-term storage and we know it has problems across Python versions (like 3.6/7->3.8). It was initially added in connection with MLFlow stuff and is not believed to be needed now (as opposed to standard pickle).
I already ran our GPU post-commit tests against this: https://app.circleci.com/pipelines/github/determined-ai/determined?branch=mackrory
I also ran the cifar10 model in Pytorch, then modified the Docker image to remove cloudpickle, patched the experiment to apply this change to harness, used the previous trial as the searcher.source_trial_id, and confirmed that training was able to pick up where it left off.
> chore: stop using cloudpickle to write PyTorch checkpoints [DET-5175]

- docs/release-notes/2226-fix-user-filter-crash.txt
- webui/react/src/pages/ExperimentList.tsx
- webui/react/src/pages/TaskList.tsx
Problem: WebUI crashes when user selects a rows in multi-selectable tables and then changing filters on the table.
Solution: Reset the selected rows when filter changes.
> fix: correct crash when changing filter on multi-selected rows [DET-5258]

- .circleci/config.yml
There is a known issue with the coscheduler that an experiment will sometimes hang when you repeatedly allocate 100% of the cluster's resources to a single experiment. This will be worked on, but in the mean time it's causing overall CI runs to fails about half the time on GKE, so the test is doing more harm than good.
Confirmed this didn't further break the GKE jobs here: https://app.circleci.com/pipelines/github/determined-ai/determined?branch=mackrory. The gang-scheduling test will gracefully skip itself when this TOTAL_SLOTS variable is not set (it already did that since it wasn't supposed to run on anything but static clusters).
> ci: stop using coscheduler for CI testing

- e2e_tests/tests/experiment/test_metrics.py
This test has been failing because it requires a 50-trial experiment. Even if you only do 1 MNIST batch, the startup-time of each trial is 20 seconds and on the single-GPU nightly cluster it exceeds the 10 minutes no-output timeout. It's not trivial to introduce a "debug" mode to run HP importance on smaller experiments, and we want to check the sanity of real results which isn't feasible with fewer trials.
Moving to the distributed test suite, we can get the 50-trial experiment done in about 4 minutes.
Pushed to an upstream branch where I had the "distributed" tests run on-demand. It's still running, but as of this writing test_hp_importance_api has already passed.
> ci: move test_hp_importance_api to distributed tests

- webui/react/src/components/ScatterPlot.tsx
Problem: Navigation (previous chart / next chart) for gallery modal view on HP Scatter Plots and HP Heatmap do not work on the very first load.
Technical issue: The problem is that the very initial size of the chart is 0 in width and height and the re-render ignores when the width and height of the resize event are 0. It's actually not 0 so change to dynamically getting the width and height to determine if the size of the chart is actually 0.
> fix: gallery modal [DET-5257]

- master/pkg/tasks/task_spec.go
This change updates the checkpoint GC task to use either the default `environment.image` or the defaults from task container defaults if they were defined.
This uses the task spec from the experiment, which is the task spec from master, which contains the master's task container defaults, not the task container defaults for the resource pool this got scheduled on. Maybe that is a shortcoming, but it probably will work fine.
> fix: force checkpoint GC to use the master's default environment [DET-5260]

- .circleci/config.yml
This change ups the circle ci timeout for for e2e test runs. If a test should timeout after a certain amount of time, developers should use `@pytest.mark.timeout` rather than relying on circle ci's default command timeout.
Circle doesn't seem to want to let me parameterize this, so this changes it for all e2e's.
> chore: up circle ci timeout for e2e tests

- .circleci/config.yml
LMDB 1.2 includes a new build-time dependency, only with Windows.  Add that dependency.
Tests should pass again
> ci: fix windows test with lmdb 1.2

- master/internal/hpimportance/manager.go
The error field may often include temporary and expected conditions, like not having > 50 trials when the experiment is 10% complete. We need to reset that when it completes.
Found and tested this while investigating a larger issue with HP importance.
> chore: reset error field on hp importance success

- docs/reference/cluster-config.txt
- docs/reference/command-notebook-config.txt
- docs/reference/experiment-config.txt
- docs/release-notes/2214-resource-pool-configs.txt
- master/cmd/determined-master/root_test.go
- master/internal/api_experiment.go
- master/internal/command/api.go
- master/internal/command/command.go
- master/internal/command/command_manager.go
- master/internal/command/manager.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
- master/internal/config_test.go
- master/internal/core.go
- master/internal/core_experiment.go
- master/internal/experiment.go
- master/internal/resourcemanagers/config.go
- master/internal/resourcemanagers/resource_pool_config.go
- master/internal/restore.go
- master/pkg/model/defaults.go
- master/pkg/model/environment_config.go
- master/pkg/model/experiment_config.go
- master/pkg/model/task_container_defaults.go
- master/pkg/tasks/task.go
- master/pkg/tasks/task_spec.go
Add new configuration options in the experiment config and master
config.
Experiment Config:
* Add resources.devices, a list of --device settings for docker run
(ignored by kubernetes resource manager).
* Add environment.add_capabilities, a list of --cap-add settings for
docker run (ignored by kubernetes resource manager).
* Add environment.drop_capabilities, a list of --cap-drop settings for
docker run (ignored by kubernetes resource manager).
Master Config:
* Add task_container_defaults.add_capabilities
* Add task_container_defaults.drop_capabilities
* Add task_container_defaults.devices
* Support a new task_container_defaults field each of the entries of
resource_pools.  The task_container_defaults applied to a
experiment/notebook/shell/command is matching resource_pool's …
> feat: per-resource-pool configs [DET-5173]

- harness/determined/common/schemas/expconf/_gen.py
- harness/determined/common/schemas/expconf/_v0.py
- master/pkg/schemas/defaults.go
- master/pkg/schemas/expconf/environment_config.go
- master/pkg/schemas/expconf/experiment_config.go
- master/pkg/schemas/expconf/experiment_config_test.go
- master/pkg/schemas/expconf/searcher_config.go
- master/pkg/schemas/expconf/test_types.go
- master/pkg/schemas/expconf/zgen_adaptive_asha_config_v0.go
- master/pkg/schemas/expconf/zgen_environment_config_v0.go
- master/pkg/schemas/expconf/zgen_environment_variables_map_v0.go
- master/pkg/schemas/expconf/zgen_experiment_config_v0.go
- master/pkg/schemas/expconf/zgen_native_config_v0.go
- master/pkg/schemas/expconf/zgen_resources_config_v0.go
- master/pkg/schemas/expconf/zgen_test_root_v0.go
- master/pkg/schemas/zgen_schemas.go
- schemas/expconf/v0/test-root.json
- schemas/gen.py
- schemas/test_cases/v0/test-structs.yaml
When I first designed the golang framework for expconf, I didn't actually realize that maps and arrays could be `nil`, so I was using redundant pointers to those objects.  This PR removes that.
Added relevant objects to the test structs and tests still pass.
The only part of this change that I think is a bit opaque is the hardcoded whitelist of type aliases in gen.py.  To help improve the discoverability of the whitelist, I wrote very clear error messages when the dev might need to add an element to it.
> chore: no pointers to maps or slices in expconf

- agent/cmd/determined-agent/run.go
- agent/internal/agent_test.go
- agent/internal/fluent.go
- agent/internal/options.go
- docs/release-notes/2251-fluent-config.txt
The `--fluent-port` option was present and affected log messages, but it
didn't actually change the port. That is fixed.
Also support changing the name of the Fluent Bit container (mostly for
testing purposes).
> feat: support configurable port and container name for Fluent Bit [DET-5272, DET-5273]

- docs/deploy/input.tf
Terraform 0.13 requires type string without quotes.
Terraform 0.13 requires type string without quotes.
Fixed this manually, but would be good to be in sync with future changes. 
> fix: Remove quotes for Terraform 0.13.

- master/pkg/agent/master_message.go
- master/pkg/container/address.go
This change updates how we determine the Addresses for a container to gracefully handle when Docker publishes ports for ipv4 and ipv6 (e.g. looks like `0.0.0.0:8080->8080/tcp, :::8080->8080/tcp`) by coalescing either to `agent-ip:host-port:...` and de-duplicating the Addresses returned to consumers when ipv4 and ipv6 are coalesced to the same address.
There are several ways to "fix" this - this feels the most correct. `Addresses()` still returns all addresses associated with the container in the event we need to rely on others in the future (and making this return exactly what rendezvous wants feels weird, it's in the wrong place) and it works when the container only has ipv6 bound too. The way we determine rendezvous ports - just assuming it's all the addresses associated with a …
> fix: gracefully handle Docker binding published ports to ipv4 and ipv6 [DET-5295]

- master/pkg/schemas/copy.go
- master/pkg/schemas/defaults.go
- master/pkg/schemas/merge.go
The object duplication was breaking down for types like:
type BindMountsConfigV0 map[string]BindMountV0
because it would create the `map[string]BindMountV0` and never 
convert it to a `BindMountsConfigV0`.
> chore: fix some minor bugs in expconf reflect code

- webui/react/src/components/UPlotChart.tsx
- webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx
This is just preventing renderings when chart data has no X values (that's where the main layout imperfection are happening).
If there are X values but no Y values, the chart will still be rendered, but chart layout is ok.
Cases like this, where possible, needs to be handled on a per-chart basis, because the issue of having no Y data can have 2 sources:
- no series or empty series
- series with data but hidden
A good example is the "GPU Hours by Label" chart in [the 2nd point of this page](http://localhost:3000/det/cluster/historical-usage?after=2021-01-01&before=2021-01-31&group-by=day) and the relative code fix in this MR.
Those 2 URLs will cause 2 different types of empty chart to be rendered:
[DET-1234]: …
> fix: improve rendering for uPlot chart with empty data [DET-5330]

- docs/release-notes/2277-fix-safari-trial-logs.txt
- webui/react/src/components/LogViewerTimestamp.tsx
- webui/react/src/components/Section.module.scss
- webui/react/src/components/Section.tsx
Trial logs does not render properly on `Safari 14.0.3` (`13.1.1` works fine)
The problem is due to `Safari 14.0.3` not respecting the CSS height of `100%`. `LogViewerTimestamp` attempts to dynamically fetch the height of the space available to set height of the visible log viewer, but on `Safari 14.0.3` it was returning `0` due to CSS issues.
The solution is to adjust the CSS to work on Safari (and the other browsers) so that the height can correctly and dynamically be fetched.
Fixed:
> fix: add support for dynamic section content via css [DET-5299]

- master/internal/core_experiment.go
This was emitted when creating new experiments. The cause is that
postExperiment() calls echo.Context#JSON(http.StatusCreated, ...), but it is
wrapped by api.Route(), which calls echo.Context#JSON() itself, with a different
status code. The second call is ignored but results in printing the ugly log
message.
To fix this, we can either
(a) change the HTTP status code for POST'ing an experiment to
be http.StatusOK, instead of http.StatusCreated, or
(b) change postExperiment() to not use api.Route(), or
(c) make api.Route() smart enough to support different HTTP response codes.
This commit takes option A, which results in a change to the REST API. However,
switching from status 201 to 200 is probably not a change that will upset many
API clients.
See [Release …
> fix: squelch "response already committed" master log message

- docs/release-notes/2287-non-numeric-numpy.txt
- harness/determined/pytorch/_data.py
Numerous users have run into mysterious error messages due to having
numpy arrays of python objects or strings.
It turns out numpy has support for string arrays that is useful to NLP
users, so there's not necessarily good reason to enforce that users use
python lists instead of numpy arrays for non-numeric data.
We can just handle it better.
The allowable dtypes for pytorch come from:
pytorch/torch/csrc/utils/tensor_numpy.cpp
The corresponding kinds are derived from:
numpy/numpy/core/numerictypes.py
> fix: only warn for non-numeric np.dtypes [DET-5288]

- master/internal/kubernetes/pod.go
- master/internal/kubernetes/pods.go
- master/internal/kubernetes/preemptions.go
In conjunction with the kubernetes coscheduler plugin, this change facilitates preemption in kubernetes by allowing experiments to be paused. Experiments are paused when their pods are tagged with the "determined-preemption" label. 
Tested manually on kubernetes with the coscheduler running alongside determined.
> feat: add support for preemption in Kubernetes [DET-5135]

- docs/release-notes/2271-fix-lr-scheduler.txt
- harness/determined/pytorch/_pytorch_trial.py
Fix a bug in how we step the `lr_scheduler` in pytorch when gradient aggregation frequency > 1.
Tested locally.
> fix: lr_scheduler step when using gradient_aggregation [DET-5289]

- docs/how-to/installation/kubernetes.txt
- docs/reference/helm-config.txt
- docs/topic-guides/deployment/determined-on-kubernetes.txt
- docs/topic-guides/system-concepts/scheduling.txt
> docs: add docs for preemption in kubernetes

- helm/charts/determined/templates/NOTES.txt
In connection with @eecsliu's recent changes - just a missed clause in the NOTES file.
Ran Helm locally
> chore: Helm notes should recognize preemption scheduler

- agent/internal/docker.go
- docs/how-to/installation/kubernetes.txt
- docs/reference/cluster-config.txt
- docs/topic-guides/cluster-configuration/tls.txt
- master/internal/api.go
- master/internal/api/stream.go
- master/internal/core.go
- master/internal/core_searcher.go
- master/internal/grpcutil/api.go
- master/internal/kubernetes/pods.go
- master/internal/kubernetes/request_queue.go
- master/internal/resourcemanagers/setup.go
- master/pkg/container/state.go
- master/pkg/searcher/search_method.go
Two main changes:
* Reduce gRPC log level from INFO to WARN. gRPC INFO log messages are
almost universally about cryptic implementation details, such as
pickfirstBalancer: HandleSubConnStateChange: 0xc0006a2010, {READY <nil>}
* Squelch a log message ("initializing endpoints for agents") that does
not seem useful.
Along the way, fix various typos and improve log message consistency.
> chore: improve master logging

- webui/react/src/components/CreateExperimentModal.module.scss
- webui/react/src/components/CreateExperimentModal.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.module.scss
- webui/react/src/pages/ExperimentDetails/ExperimentInfoBox.tsx
Introduce code splitting to break up expensive libraries. Focus primarily on the two largest libraries that are not immediately needed. The basic idea is to split up the overall bundle into multiple smaller sized packets, where most of them are not needed up front. Then when they are actually needed based on a user flow, they get dynamically loaded. The upfront cost is lowered so the initial time to paint on the web app load is much faster.
1. monaco-editor 41.9% of bundle size based on `npm run analyze` on built distribution.
2. plotly.js 15.0% of bundle size.
Before code splitting:
```
File sizes after gzip:
1.17 MB    build/static/js/2.f62b3a3f.chunk.js     <= breaking up this big boi
87.73 KB   build/static/js/main.926a7bd1.chunk.js
52.37 KB   build/static/css/2.31f03978.chunk.css …
```
> refactor: code split libraries [DET-5342]

- .circleci/config.yml
A100's have been unavailable most of the last week, they're expensive, and they're not strictly necessary to catch significant regressions in the CUDA 11 images (now that all our GKE clusters are on newer CUDA drivers). 
Basically this makes the CUDA 11 setup step almost identical to the vanilla GKE set up step except it applies the CUDA 11 images as the default, etc. The termination step is now identical so we just use a single definition now.
https://app.circleci.com/pipelines/github/determined-ai/determined?branch=cuda11
> ci: move CUDA 11 testing to more available GPUs

- harness/setup.py
Users are seeing messages about the wrong ruamel version being
installed.
I'm not sure which package is resulting in this old verison, but it
doesn't much matter; the reason we required 0.15.78 was due to our old
runtime image building system, where we had too much control over the
versions that got installed.  Now, we support ruamel.yaml as far back as
0.15.29.
> chore: loosen ruamel.yaml version

- master/internal/trial.go
This change updates the code that picks rendezvous ports out of the container addresses to only pick and deliver a single mapping to a container port even if multiple were given. For example, there was a user reported bug where the port bindings looked like the snippet below, even though each port was requested to be bound only a single time.
```
{'container_ip': '172.17.0.2', 'container_port': 1734, 'host_ip': '223.193.1.182', 'host_port': 49457}
{'container_ip': '172.17.0.2', 'container_port': 1734, 'host_ip': '223.193.1.182', 'host_port': 49454}
{'container_ip': '172.17.0.2', 'container_port': 1750, 'host_ip': '223.193.1.182', 'host_port': 49456}
{'container_ip': '172.17.0.2', 'container_port': 1750, 'host_ip': '223.193.1.182', 'host_port': 49453}
```
This is a weird one, I'm not …
> chore: only select a single host port per container rendezvous port

- webui/tests/bin/e2e-tests.py
`python bin/e2e-tests.py setup-test-cluster` fails complaining that the `config` argument is missing since it had been displaced by the logfile argument.
> fix: fix set up cluster cmd [DET-5399]

- e2e_tests/tests/command/test_run.py
Add printing of output in `_run_and_verify_exit_code_zero` to be able to see why `test_relative_bind_mount` flakes.
> chore: Add output printing to debug flaky test

- webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
Add an entry to the Trial Summary telling the user the current workload status
Tested manually while running experiment.
> feat: add workload status to trial infobox [DET-4289]

- .bumpversion.cfg
I tested using `bumpversion patch` and confirmed that `setup.py`s were properly bumped.
This line is redundant b/c a few lines above already bumps all `*/setup.py` files.
> chore: fix bumpversion config not properly bumping setup.py files

- docs/release-notes/2376-fix-gcp-terraform.txt
- harness/determined/deploy/gcp/gcp.py
Terraform 0.15 [doesn't support](https://www.terraform.io/docs/cli/commands/plan.html#passing-a-different-configuration-directory) passing the config directory as the last argument anymore; they suggest using -chdir instead, but that doesn't work in older terraform (e.g. 0.13). Since we explicitly specify the tfstate path anyway, change the subprocess `cwd` instead.
Also, remove `shell=True`. Now the users will be able to have directory names with spaces in them.
Tested with Terraform 0.13 and 0.15.
> fix: `det deploy gcp` support for terraform 0.15 [DET-5449]

- master/internal/agent/agent.go
This change updates the agent tracking code in the master to terminate when the websocket actor closes.
Prior to https://github.com/determined-ai/determined/pull/2351 it seems the agent actor in the master relied on the websocket actor propogating `actor.ChildFailed` up to it to detect exits and mark agents as terminated. #2351 changed this to swallow abnormal websocket closures.
This fix is still subpar, any _real_ agent abnormal websocket closures are now swallowed, not logged and essentially invisible (though _i've_ never seen one that matter, but that could be because of the noise). I think just a revert of #2351 may be more correct than this (and the _most_ correct thing is probably a heck of a lot of work).
[DET-1234]: …
> chore: close agents on websocket closures

- .circleci/config.yml
The old version (1.18.15-gke.1501) in favor of 1.18.17-gke.100, as
specified in release notes from May 12:
https://cloud.google.com/kubernetes-engine/docs/release-notes
> chore: update gke version

- docs/release-notes/2383-slots-per-agent.txt
- master/internal/provisioner/aws.go
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp.go
- master/internal/provisioner/gcp_config.go
- master/internal/provisioner/instance.go
- master/internal/provisioner/provisioner.go
- master/internal/provisioner/provisioner_test.go
- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- proto/src/determined/resourcepool/v1/resourcepool.proto
Add a SlotsPerAgent field in the resource pool API. This returns the slot number on each dynamic agent. If there is no dynamic agents configured, return -1.
- CI
- Manually check the resource pool field.
> feat: add SlotsPerAgent in resource pool API

- docs/reference/cluster-config.txt
- docs/release-notes/deprecate-old-master-config.txt
> docs: deprecate old master configuration fields

- harness/setup.py
websocket-client just released 1.0, which conflicts with docker-compose,
which breaks the determined install with older version of pip.
See https://app.circleci.com/pipelines/github/determined-ai/determined/12416/workflows/4d41102c-4e72-46e9-842f-6226121f2429/jobs/360714 for an example.
> chore: make pip happy again

- harness/determined/_train_context.py
- harness/determined/_trial_controller.py
- harness/determined/cli/experiment.py
- harness/determined/estimator/_estimator_context.py
- harness/determined/estimator/_estimator_trial.py
- harness/determined/estimator/_reducer.py
- harness/determined/experimental/_native.py
- harness/determined/ipc.py
- harness/determined/keras/_tf_keras_context.py
- harness/determined/keras/_tf_keras_trial.py
- harness/determined/load/__init__.py
- harness/determined/load/_load_implementation.py
- harness/determined/load/_load_trial_controller.py
- harness/determined/pytorch/_pytorch_context.py
- harness/determined/pytorch/_pytorch_trial.py
- harness/determined/pytorch/_reducer.py
This is part of a multi-step process to refactor the harness code in
favor of push architecture:
Goal:
*    Introduce Python WorkloadSequencer that uses Push Architecture.
That can't happen until:
*    The WorkloadManager is broken into simple function calls for
mutating workload responses.  These simple functions (one after each
of training, validation, and checkpointing) can be called right
before making calls to the push API, rather than after responding
with a workload.Response on a stream of workloads.
That can't happen until:
*    The StorageManager is no longer a part of the WorkloadManager.  The
StorageManager is the only part of the WorkloadManager that doesn't
fit neatly into the aforementioned three function calls, since
storage_mgr.store_path() is a contextmanager.  However, …
> chore: add zmq-based IPC to the DistributedContext [DET-5484]

- harness/determined/common/experimental/experiment.py
Add a 'tab' for continuation, otherwise Sphinx creates another parameter 
> docs: update parameter string

- master/internal/trial.go
- master/pkg/agent/master_message.go
This change alters how we derive container addresses. When docker changed to make ipv6 show up by default again it threw us for a loop. My hasty fix wasn't quite correct but also introduced with it a bug that also seemed to be docker port related. This lead me to hackily fix the bug of the bug fix rather than realize the root cause, since a revert of the original fix of bug caused the docker ipv6 change to not allow any containers to run. This change fixes both issues by always just returning a single container address when the container is bound to 0.0.0.0 or :: based on whether the proxy is ipv4 or ipv6.
> chore: only return the port binding appropriate for the proxy [DET-5495]

- harness/tests/experiment/pytorch/test_pytorch_data.py
`qsize()` raises on a NotImplementedError on Mac OS X. Disable these tests if the tests are running on Mac to reduce noise.
> chore: disable tests that will never pass on mac os x

- master/pkg/schemas/expconf/data_layer_config.go
- master/pkg/schemas/expconf/schema_test.go
- master/pkg/schemas/expconf/searcher_config.go
- master/pkg/schemas/expconf/storage_config.go
- master/pkg/schemas/merge.go
- schemas/test_cases/v0/merging.yaml
Previously, schemas.Merge() would happily merge a shared_fs checkpoint
storage and an s3 checkpoint storage into one, totally invalid,
frankenstorage.
The problem was also present on other union types.
New tests were added.
> fix: merge logic for union-type configs [DET-5486]

- harness/determined/deploy/gcp/terraform/main.tf
- harness/determined/deploy/gcp/terraform/modules/compute/main.tf
- harness/determined/deploy/gcp/terraform/outputs.tf
This updates a lingering reference to Ubuntu 16.04 (which has EOL'd and has been replaced by Ubuntu 20.04 elsewhere in our stack). It also eliminates warnings related to interpolation syntax that has been deprecated for quite a few Terraform versions now, and adds a source for the Google provider (idiomatic in more recent versions).
Put a cluster up and down, confirmed the OS version, and did some basic functionality tests (scaling up and down, running an experiment). Confirmed the warnings are gone. This was done on Terraform 0.13.5 - which is also a little bit behind. We don't document a required Terraform version, but this confirms we're not introducing any unreasonable requirement for the newness of the version.
> chore: update OS and other language in Terraform modules [DET-4276]

- harness/determined/common/schemas/expconf/_gen.py
- master/pkg/schemas/expconf/zgen_profiling_config_v0.go
- master/pkg/schemas/zgen_schemas.go
- schemas/expconf/v0/profiling.json
- schemas/test_cases/v0/experiment.yaml
- schemas/test_cases/v0/misc.yaml
Users should be able to set `profiling.enabled: true` in the experiment config and fall back to intelligent defaults on starting batch and duration of profiling. The current experiment config doesn't allow only `enabled: true` because it wants to validate that `begin_on_batch <= end_after_batch`. This PR changes the experiment config schema to allow one of both of the fields to be unset when `enabled: true`
This is fine because:
- if both are unset, the default behavior of starting at batch 0 and running for 5 minutes is good
- if start is unset but the end is set, it will default to 0 (previously this was handled by logic in the experiment config, but this PR moves that logic into the schema itself). Then the end doesn't matter because it should always be >= 0 (do we need to add a check …
> fix: make profiling schema more lenient [DET-5497]

- docs/how-to/installation/setup-gke-cluster.txt
There are some caveats on GKE that aren't very well documented that are required to get the latest NVIDIA docs:
* Keeping GPUs in a non-default node-pool (we already do this, since the master is in the default pool)
* A different DaemonSet for the driver installer
* Adding the cloud-platform scope
So we'll keep these in our documentation.
Follow the original procedure, and ensured I had problems with CUDA 11. Made the attached modifications manually and verified I got a CUDA 11-compatible version (https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-450-51-06/index.html).
> docs: update procedure for latest NVIDIA drivers on GKE

- master/internal/experiment.go
This bug is introduced in [here](https://github.com/determined-ai/determined/commit/afdb74955b5ec498095767b1d81d81756b6da510#diff-d92b0050d5549a1efe86c524037f8a2709d6ebf8ce2c63a777f63744bc8a0b00R103). When we filled in the resource pool value, we did that on a copied go struct. This is fixed by changing it to use a pointer.
Manually create one experiment and check the WebUI
> fix: resource pool not saved in the DB [DET-5485]

- docs/topic-guides/system-concepts/scheduling.txt
Updates the docs to reflect that the coscheduler has long waiting time if attempting to schedule jobs requiring the full cluster.
> docs: notify users of coscheduler behavior [DET-5150]

- harness/determined/cli/command.py
- harness/determined/cli/notebook.py
- master/internal/api_command.go
- master/internal/command/command.go
- master/pkg/model/command_config.go
- master/pkg/model/command_config_test.go
- master/pkg/model/compat.go
- master/pkg/model/defaults.go
- master/pkg/model/experiment_config.go
- master/pkg/model/experiment_config_test.go
The previewed notebook configuration goes down the same path populating the full configuration for the actual creation. However, some fields might be null and they are still populated. They should be removed in the previewed configuration.
Also, `resources.slots_per_trial` is an internal field since the experiment configuration and the command configuration shared the same resource configuration go struct. This PR also removes this field since now the experiment configuration goes down a new path that doesn't use the previous go struct.
I noticed there are tests that still use the old experiment configuration go struct but the production code does not use it. So the experiment workflow should just work.
- CI
- Manually run `det notebook start --preview`
See [Release …
> fix: omit internal fields in previewed notebook [DET-5523]

- master/internal/provisioner/aws.go
- master/internal/provisioner/aws_spot.go
- master/internal/provisioner/aws_spot_legacy.go
There is a bug where spot requests and spot instances in AWS do not include the resource pool as part of the tags. This leads to issues where one spot resource pool creates instances, but all of the spot resource pools think they are responsible for managing the instance. This causes spot instances to get shut down because some resource pools think they are idle. This PR ensures that we include the resource pool as one of the tags to prevent this contention. 
This PR also ensures that this change doesn't lead to orphaned spot instances by deleting all spot requests and instances that do not include the `determined-resource-pool` tag when the provisioner starts up.
> fix: prevent spot resource pool contention [DET-5349]

- master/internal/experiment.go
- master/internal/restore.go
- master/internal/trial.go
- master/internal/trial_workload_sequencer.go
- master/internal/trial_workload_sequencer_test.go
- master/pkg/schemas/copy.go
- master/pkg/schemas/copy_test.go
- master/pkg/schemas/expconf/experiment_config.go
Use a deep copy when passing an experiment config from one actor to
another.
> fix: prevent concurrent updates to a single expconf object [DET-5543]

- docs/release-notes/2453-fix-k8s-resource-manager.txt
- master/internal/kubernetes/pods.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/resource_managers.go
- master/internal/resourcemanagers/resource_managers_test.go
- master/internal/resourcemanagers/setup.go
- master/internal/sproto/kubernetes_resource_manager.go
Previously, when the k8s pods actor starts up, it sends a message to the k8s resource manager actor, which then creates a mock agent. Before the mock agent is created, no allocation requests should be handled in the k8s resource manager actor. However, there is no synchronization to ensure the k8s resource manager actor receives `SetPods` message first.
This PR moves creating the k8s pods actor into the `PreStart` of the k8s resource manager actor so the order is enforced.
CI
> fix: synchronize pods actor startup in k8s resource manager [DET-5536]

- master/internal/trial.go
This change just moves "starting a new run" to when resource are allocated from when we were terminated. It really should've happened in trial reset previously, but this change makes more semantic sense to me: a run isn't started until it is.. started?
> chore: move run increment to allocation not termination [DET-5559, DET-5450]

- master/internal/db/postgres.go
- master/internal/db/setup.go
better communicate that migrations are running.
sample startup logs
```
determined-master  | INFO[2021-05-27T13:19:24-07:00] Determined master 0.15.6.dev0 (built with go1.16.4) 
determined-master  | INFO[2021-05-27T13:19:24-07:00] connecting to database localhost:5432        
determined-master  | INFO[2021-05-27T13:19:24-07:00] running DB migrations from file:///home/hmd/projects/da/determined/tools/build/static/migrations; this might take a while... 
determined-master  | INFO[2021-05-27T13:19:24-07:00] found golang-migrate version 20210513134524  
determined-master  | INFO[2021-05-27T13:19:24-07:00] DB migrations completed                      
determined-master  | INFO[2021-05-27T13:19:24-07:00] deleting all snapshots for terminal state experiments 
determined-master  | …
```
> chore: report running of migrations

- harness/determined/tensorboard/base.py
- harness/determined/tensorboard/gcs.py
- harness/determined/tensorboard/hdfs.py
- harness/determined/tensorboard/s3.py
- harness/determined/tensorboard/shared.py
- harness/tests/tensorboard/test_base.py
I observed that as tfevent files build up, just selecting which files to
examine can actually be a bit of a bottleneck.  The current strategy
seems to have a minimum cost of about 1ms per 100 files (calling
stat() on 1500 event files takes my system 0.012s).  The previous
implementation kept a complex index of how large each file had been
before uploading it, which quadrupled the time for choosing files to
around 0.045 seconds.  The new strategy, which just chooses all modified
files since the last sync time, has basically no overhead over the cost
of stat'ing each file.
The only strategy I can think of that would be faster would be to hook
into inotify to have the operating system watch the list of files for
you.
> chore: improve performance of tfevent file filtering

- harness/determined/_swagger/client/api/profiler_api.py
- master/internal/api_trials.go
- master/test/integration/api/api_trials_test.go
- proto/src/determined/api/v1/trial.proto
- webui/react/src/pages/TrialDetails/Profiles/utils.ts
Add the `follow` param to the Profiling APIs to indicate whether the API should stream results until the trial is complete.
The available series changes are required for the ProfilingAgent to know whether profiling results have already been recorded for the trial so it can know to not add more profiling data.
I added the flag to both APIs because some tools don't have good support for streaming (e.g. Swagger) and it is really convenient to have non-streaming versions of the APIs.
> chore: add non-streaming APIs for trial profiler endpoints

- harness/tests/experiment/pytorch/test_pytorch_data.py
- harness/tests/fixtures/fake_subprocess_receiver.py
Fix test_ipc: the child process never exited.
Fix test_to_device_warnings: there is no longer any need for
multiprocessing.Queue().
> chore: fix some semi-broken unit tests

- master/internal/config.go
- master/internal/config_test.go
- master/pkg/schemas/expconf/storage_config.go
Since expconf, any S3 checkpoint storage configured in the master
which included the access key and access secret would be mangled while
generating a printable config, and experiments generated from that
master would no longer work.
Added a unit test to ensure that generating a printable config does not alter the original.
> fix: generating printable master config does not alter original

- e2e_tests/tests/experiment/test_noop.py
- e2e_tests/tests/fixtures/keras_no_op/model_def.py
This came up in @azhou-determined 's testing of making TensorFlow 2 the default. Turns out this test was only ever running against the default, and additional logic is required for it to run on the right version in the TF1/TF2 tests. And .uniform() may have changed since I last tested this.
This is covered by CI
> chore: fix TF version detection and RNG usage in test

- harness/determined/common/api/__init__.py
- harness/determined/common/api/profiler.py
- harness/determined/profiler.py
- master/internal/grpcutil/auth.go
- master/test/integration/api/api_trials_test.go
Disable profiling if profiling data already exists in the API. This avoids problems around multiple data points with the same batch index, timeseries graphs with large gaps, and confusing data caused by GPU warmup if the user didn't notice the restart.
Also change the POST API function to be passed in to the ProfilingAgent constructor instead of being hardcoded. Making all functions that communicate with the master API easy to overwrite will make it easier to write unit tests without a running master.
Additionally, fix missing task token authentication logic for streaming APIs and unify auth logic across unary and streaming APIs.
> chore: disable profiling after restart [DET-5424]

- webui/react/src/components/Page.tsx
- webui/react/src/components/PageHeader.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/TrialDetails.tsx
Include the experiment description in the WebUI breadcrumbs.
Removed the breadcrumbs from the Experiment Detail page.
Added the experiment description to the Trial Detail page breadcrumbs that is truncated when it exceeds ~40~ 30 characters.
Added a tooltip to the breadcrumb when the description is truncated.
I played with mobile a bit. This implementation doesn't look very good. 
Max length of 40 looks better than 30 on desktop IMO, but it really breaks the mobile view. The implementation looks better on mobile if we set the max description length of 15, but that isn't a good value for desktop. If the react code can differentiate between mobile and desktop, we could improve this, but I'm not sure how to do that/if that's a good practice.
However, there seems to be other problems with the …
> chore: add experiment name to breadcrumb on trial detail page [DET-5284]

- docs/reference/cluster-config.txt
- docs/reference/experiment-config.txt
- docs/release-notes/add-bind-mounts.txt
- master/internal/command/command.go
- master/pkg/model/defaults.go
- master/pkg/model/task_container_defaults.go
Add bind mounts to task container defaults to support cluster-level defaults.
Manually test it.
N/A
> feat: add bind mounts to task container defaults [DET-5362]

- docs/release-notes/backfill.txt
- docs/topic-guides/system-concepts/scheduling.txt
- master/internal/resourcemanagers/priority.go
- master/internal/resourcemanagers/priority_test.go
- master/internal/resourcemanagers/scheduler.go
Support back-filling in the priority scheduler. When there are no high-priority tasks to schedule or release, back-fill preemptible low-priority tasks. This behavior needs the preemption to be enabled.
- Add unit tests.
- Run the current test suite.
> feat: support back-filling in the priority scheduler [DET-5397]

- harness/setup.py
This was highlighted by dependabot. After looking into why it was pinned the way it was, the previous incompatibilities requiring a very specific range of some of these dependencies appear to no longer be an issue. As long as we're past certain minimum versions, things should work better.
> chore: update urllib3

- harness/determined/cli/cli.py
- harness/determined/cli/version.py
This fixes issues where e.g. `det master config | yq .` would fail if
the master version didn't match the cli version exactly, since the
warnings were printed to stdout rather than stderr.
> chore: minor edits to cli behaviors

- harness/determined/experimental/client.py
Expose symbols previously found in `det.experimental.determined`, `det.experimental.experiment`, etc, all inside of `det.experimental.client`.
Then introduce a `det.experimental.client.login()`, and `det.experimental.client.create_experiment()`, etc.
> feat: expose a default Determined in det.experimental.client

- webui/react/src/components/NotebookModal.tsx
The full notebook config was being parsed as yaml after every edit, leading to unwanted results such as deleting the number of slots and having null automatically filled in it's place. This fixes that problem by only parsing the config when launching a new notebook and treating it as text beforehand. This PR also adds word wrapping to the editor.
> fix: stop parsing notebook config on every edit [DET-5605]

- master/pkg/schemas/expconf/experiment_config.go
- master/pkg/schemas/expconf/experiment_config_test.go
- schemas/test_cases/v0/merging.yaml
Previously, forking an experiment with either devices or bind_mounts set
in the task_container_defaults at the master level would add duplicate
entries to the devices or bind_mounts (since the master injected them
into the original experiment, and injected them again after forking the
original experiment).
This does not dedup duplicates which already existed in the config,
since a schemas.Merge() operation should not actually fix an
already-broken user-provided config.  Instead, it should just never
break a user-provided config.
Added merge tests for these two objects.
> fix: dedup BindMounts and Devices on merge

- harness/determined/pytorch/_pytorch_trial.py
Previously, PyTorchTrial would issue warnings about
on_validation_step_start and on_validation_step_end anytime you provided
any PyTorchCallback, regardless of whether or not you used the
deprecated methods.
> fix: erroneous warning with PyTorchCallback

- docs/deploy/main.tf
With the release of Terraform 1.0.0, the old version constraint was no
longer satisfied by the latest Terraform image.
> chore: upgrade the version of Terraform used to deploy docs

- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/Header/TrialHeaderLeft.module.scss
- webui/react/src/pages/TrialDetails/Header/TrialHeaderLeft.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsHeader.tsx
> fix: update name and description in exp/trial headers [DET-5668][DET-5669]

- webui/react/src/components/PageHeaderFoldable.module.scss
- webui/react/src/components/PageHeaderFoldable.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
- webui/react/src/styles/global.scss
That's the 3rd button that will be visible in the header only when width of the page is > 1400px.
Note that with Caleb we decided to keep this simple and use css @media queries to position those buttons.
> fix: add download model to visible header buttons [DET-5670]

- .circleci/config.yml
#2572 cause the gke-parallel job to time out quite often. This PR switches the GKE version to the latest 1.18 instead, and it seems to be working better: https://app.circleci.com/pipelines/github/determined-ai/determined/13464/workflows/9d9db5e6-bfca-4b8e-93ce-592d0ab1a4c7
> fix: roll GKE in CircleCI back to 1.18 series.

- harness/determined/keras/_tf_keras_context.py
Previously, TFKerasTrial would automatically call wrap_optimizer()
on the optimizer argument to a user's `model.compile()` call, unless
that optimizer had already been wrapped with a context.wrap_optimizer()
explicitly by the user.
This was originally designed to allow subclassed keras.models.Model
classes with multiple optimizers in a way which was backwards-compatible
with models that worked before context.wrap_optimizer() was introduced.
However, there are actually 'meta' optimizers in tensorflow_addons which
don't really need to be wrapped by horovod at all, though typically the
meta optimizers wrap a "real" optimizer that does need to be wrapped by
horovod.
The original backwards compatible behavior was too overbearing; it
assumed that all optimizers needed to be wrapped by horovod. …
> fix: loosen check on context.wrap_optimizer()

- docs/release-notes/2596-fix-expose.txt
- master/internal/command/command.go
- master/internal/command/notebook_manager.go
- master/internal/command/shell_manager.go
- master/internal/command/tensorboard_manager.go
Tested manually.  Note that for the old code to fail, `docker inspect CONTAINER_ID | jq '.[].NetworkSettings'` should show the _wrong_ port last.  The ports seem to be sorted alphanumerically, and we typically pick ports in the 3000 range, so any port that starts with a 4 or higher is a good test port.
Example dockerfile:
```dockerfile
FROM docker.io/determinedai/environments:py-3.7-pytorch-1.7-lightning-1.2-tf-2.4-cpu-3a452bc
EXPOSE 8888
```
```bash
docker build . -t junk && det notebook start --config=environment.image=junk
```
> fix: support Docker images with EXPOSE in notebooks/shells/tensorboard [DET-5648]

- master/internal/sproto/globals.go
Currently, if user explicitly selects `kubernetes` pool in the notebook modal, the server errors out because of incorrect resource pool validation. This change fixes that issue.
> fix: error when explicitly selecting kubernetes pool for notebooks.

- model_hub/examples/huggingface/multiple-choice/README.md
- model_hub/examples/huggingface/text-classification/README.md
- model_hub/examples/huggingface/token-classification/README.md
> fix: transformers links in example READMEs

- .circleci/config.yml
- e2e_tests/tests/config.py
- examples/computer_vision/mmdetection_pytorch/docker/Dockerfile
- examples/computer_vision/unets_tf_keras/const.yaml
- examples/computer_vision/unets_tf_keras/distributed.yaml
- examples/gan/dcgan_tf_keras/const.yaml
- examples/gan/dcgan_tf_keras/distributed.yaml
- harness/determined/common/schemas/expconf/_v0.py
- harness/determined/deploy/aws/templates/efs.yaml
- harness/determined/deploy/aws/templates/fsx.yaml
- harness/determined/deploy/aws/templates/govcloud.yaml
- harness/determined/deploy/aws/templates/secure.yaml
- harness/determined/deploy/aws/templates/simple.yaml
- harness/determined/deploy/aws/templates/vpc.yaml
- harness/determined/deploy/gcp/constants.py
- helm/charts/determined/templates/master-config.yaml
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp_config.go
- master/pkg/model/defaults.go
- master/pkg/schemas/expconf/const.go
- master/pkg/schemas/expconf/legacy_test.go
- schemas/test_cases/v0/experiment.yaml
- tools/scripts/bumpenvs.yaml
- tools/scripts/refresh-ubuntu-amis.py
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/experiment-details/set-a.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
Updating images. Also, since Ubuntu images for GovCloud need to be added manually, the previous entries caused this run to fail because equivalents couldn't be looked up the same way. We now just gracefully log a warning, reminding the user that this needs to happen (as said in the README).
I'm running all the opt-in tests here: https://app.circleci.com/pipelines/github/determined-ai/determined/13602/workflows/d7bcc6c7-85ee-42c9-816a-3aa1e131f8a5
> chore: update environment images before release

- master/internal/api_experiment.go
- master/internal/db/postgres_experiments.go
- master/internal/db/postgres_filters.go
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
This change adds an API to query an experiment's best validation. That is pretty much it. This is necessary to implement the `checkpoint_policy: best` behavior in the confines of push architecture.
> feat: add API to query best searcher validation [DET-5212]

- master/internal/grpcutil/api.go
Without this, if a proxy is set using the `https_proxy` environment
variable, the gRPC gateway attempts to use it to connect back to the
master's own listener, which typically breaks things. A proxy should
never be used for such connections.
Thanks to Ryan for actually figuring out the issue before I got assigned to it.
> fix: make the gRPC gateway never use a proxy [DET-5689]

- master/internal/api/error.go
- master/internal/api_command.go
- master/internal/api_notebook.go
- master/internal/api_shell.go
- master/internal/api_tensorboard.go
- master/internal/resourcemanagers/agent_resource_manager.go
- master/internal/resourcemanagers/kubernetes_resource_manager.go
- master/internal/resourcemanagers/resource_managers_test.go
- master/internal/resourcemanagers/resource_pool.go
- master/internal/sproto/task.go
- webui/react/src/components/NotebookModal.tsx
- Return API error for "impossible" slot requests.
- Limit max number of slots in the UI.
Given a GCP, AWS, or Kube cluster with say 4 MaxSlotsPerPod or 4 gpu-nodes:
- In "Launch notebook" UI model, the number of slots for compute will be limited to the max possible number of slots (i.e. 4).
- "Bad" commands such as `det notebook start --config resources.slots=10`, `det shell start --config resources.slots=10` etc. should fail with a comprehensible error about an incorrect # of slots.
- "Good" commands such as `det shell start --config resources.slots=4` should succeed.
On-prem resource pools, e.g. `det deploy local` or local devclusters, will always allow all requests as the max slots are not known. As such, any request should continue working on these clusters.
See [Release …
> fix: prevent impossible slot requests for notebooks [DET-5690]

- harness/determined/__init__.py
- harness/determined/_rendezvous_info.py
- harness/determined/_train_context.py
- harness/determined/_trial_controller.py
- harness/determined/horovod.py
- harness/determined/ipc.py
- harness/determined/layers/_worker_process.py
- harness/tests/test_ipc.py
This PR introduce a series of small refactors to support push architecture.
* It fixes a rare hang in the ZMQBroadcastServer/Client.  The hang
has always been possible but seemingly was not often hit due to the
ordering of how we ran things.
* It introduces a node-local ZMQBroadcastServer/Client in the
DistributedContext.  This will be used in push architecture for things
like coordinating checkpoint downloads.
* It introduces Unix-socket-based ZMQ communication for the node-local
sever/client, which is slightly faster and less likely to be affected
by networking issues.
* It adds a test for the DistributedContext, for each of local/global
broadcast/gather/allgather functions.
Test added!
> chore: update ZMQ logic in DistributedContext

- master/internal/kubernetes/spec.go
The k8s coscheduler and priority scheduler implementations rely on a `minAvailable` metric that is calculated by dividing `slots` by `maxSlotsPerPod`. This is different from the implementation of CPU only training, and could cause issues if attempting to schedule them. By setting `minAvailable` to zero, we bypass the coscheduler and let the vanilla kubernetes scheduler schedule the pod. Gpu pod scheduling will remain unaffected.
> fix: prevents k8s priority scheduler from blocking cpu only training

- docs/how-to/installation/gcp.txt
- harness/determined/deploy/gcp/terraform/modules/compute/main.tf
- harness/determined/deploy/gcp/terraform/modules/service_account/main.tf
- master/internal/provisioner/gcp.go
- master/internal/provisioner/gcp_config.go
Mimicking `det deploy aws`, GCP clusters are now run with `docker run
--log-driver gcplogs` so that container logs are sent to GCP Cloud
Logging and viewable online. (Unconditionally for the master, and via a
new master config option for agents that has no effect in other
situations.)
> feat: make `det deploy gcp` clusters log to GCP Cloud Logging

- docs/reference/cluster-config.txt
- docs/release-notes/5432-local-bind-mount.txt
- harness/determined/deploy/local/cli.py
- harness/determined/deploy/local/cluster_utils.py
- harness/determined/deploy/local/docker-compose.yaml
- master/cmd/determined-master/init.go
- master/cmd/determined-master/root.go
Add support for automatically bind mounting the user's home directory onto task agents for `det deploy local` and a flag for disabling it.
Test by running: 
1. `det deploy local cluster-up`, open two files in the base directory and ensure any changes to one happen to the other.
2. `det deploy local cluster-up --no-auto-bind-mount` to ensure normal behavior.
> feat: support auto bind mount as part of det deploy local [DET-5432]

- CONTRIBUTING.md
- master/internal/resourcemanagers/kubernetes_resource_manager.go
WebUI uses `auxContainersPerAgent` to check if zero-slot tasks are allowed; Kubernetes does allow these, so its dummy resource pool should advertise itself as such.
Also, we now have `jq` as a requirement so I'm updating the `CONTRIBUTING` docs for good measure.
Deploy a kube cluster and try to launch a zero-slot notebook via "Launch Notebook" UI.
> fix: kube RPs should allow aux tasks [DET-5710]

- docs/release-notes/2644-pytorch-geometric.txt
- e2e_tests/tests/config.py
- e2e_tests/tests/nightly/test_capability.py
- examples/Makefile
- examples/graphs/proteins_pytorch_geometric/README.md
- examples/graphs/proteins_pytorch_geometric/const.yaml
- examples/graphs/proteins_pytorch_geometric/distributed.yaml
- examples/graphs/proteins_pytorch_geometric/model_def.py
- examples/graphs/proteins_pytorch_geometric/startup-hook.sh
- harness/determined/pytorch/_pytorch_trial.py
There was some interest in OSS slack on `pytorch_geometric` support; the problem is that this library uses custom class which exposes `.to` method (so we can move it to the device just fine), but its `__len__` doesn't represent the number of records in a batch, and we require that value.
Let's allow users to override the batch length calculation in using `PyTorchTrial#calculate_batch_length`.
This PR includes an example based on `pytorch_geometric`, which is also our first GCN (graph convolutional network) example. It should run to completion on a cluster both in `const` and `distributed` configurations. The standard trials which do not override this field should run normally as well.
> feat: improve support for `pytorch_geometric` and custom pytorch batches

- .circleci/config.yml
- e2e_tests/tests/config.py
- examples/computer_vision/mmdetection_pytorch/docker/Dockerfile
- examples/computer_vision/unets_tf_keras/const.yaml
- examples/computer_vision/unets_tf_keras/distributed.yaml
- examples/gan/dcgan_tf_keras/const.yaml
- examples/gan/dcgan_tf_keras/distributed.yaml
- harness/determined/common/schemas/expconf/_v0.py
- harness/determined/deploy/aws/templates/efs.yaml
- harness/determined/deploy/aws/templates/fsx.yaml
- harness/determined/deploy/aws/templates/secure.yaml
- harness/determined/deploy/aws/templates/simple.yaml
- harness/determined/deploy/aws/templates/vpc.yaml
- harness/determined/deploy/gcp/constants.py
- helm/charts/determined/templates/master-config.yaml
- master/internal/provisioner/aws_config.go
- master/internal/provisioner/gcp_config.go
- master/pkg/model/defaults.go
- master/pkg/schemas/expconf/const.go
- master/pkg/schemas/expconf/legacy_test.go
- schemas/test_cases/v0/experiment.yaml
- tools/scripts/bumpenvs.yaml
- webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
- webui/react/src/fixtures/responses/experiment-details/set-a.json
- webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
The combination of PyTorch 1.9 and the HOROVOD_GPU_ALLREDUCE=NCCL option (which means to use NCCL specifically for the All-Reduce algorithm only) has been resulting in extra processes on the GPUs and consequent memory errors. Configuring NCCL to be used for all operations appears to eliminate this problem and we probably should have been doing that anyway. Also, working around a recent regression in Pillow by just pinning to an older release (https://github.com/python-pillow/Pillow/issues/5571).
See also: https://github.com/determined-ai/environments/pull/110
https://app.circleci.com/pipelines/github/determined-ai/determined?branch=all_operations_nccl
At the time of this writing, one job is still running but the rest have passed.
> chore: update images for release

- webui/react/src/pages/SignIn.tsx
We know that loginRedirect is always set to internal react routes since it originates from a page in our SPA so we set signIn to always treat it as an internal route instead of trying to figure out whether it's an internal route or not.
Determining whether a string is a path to A) an internal react route vs B) an asset that hosted by react vs C ) a server route quickly and without making async requests is hard
multiple ways to address this: TBD (edited) 
- stop using string routes, use react route objects
- stop using relative paths where possible
- remove the need for routeAll
- if we use routeAll we explicitly tell it if we know it's an internal route which is an equivelant of just using routeToReactUrl
- something else? …
> fix: avoid passing loginRedirect to routeAll

- webui/react/src/pages/ExperimentDetails/ExperimentMultiTrialTabs.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
2 route improvements:
- The hp visualization routes for multi-trial experiments are getting redirected to a base route. For example, `/experiments/123/visualization/hp-parallel-coordinates` get redirected to `/experiments/123`. 
- Multi-trial and single-trial experiment pages reroute to a simpler route if the default tab is selected. Update the route to accurately reflect exactly what tab state the page is in. For example, currently if user is viewing Visualizations for the Multi-trial experiment page, it will change the route (if applicable) to `/experiments/123`. Instead we want `/experiments/123/visualization` for a couple of reasons: 1) we are starting to  sync up and preserve page state in the URL so they can be shareable. 2) avoid complex logic to maintain default routes (the …
> fix: preserve subroutes for experiment detail page

- e2e_tests/tests/nightly/test_capability.py
- examples/graphs/proteins_pytorch_geometric/README.md
- examples/graphs/proteins_pytorch_geometric/const.yaml
Seems like `proteins_pytorch_geometric` example sometimes has convergence issues which breaks nightlies. Remove it for the nightlies for now, pending an investigation. Also set batch_size to 20 to align with the original repo example.
> fix: remove proteins_pytorch_geometric from nightlies.

- docs/how-to/installation/kubernetes.txt
- helm/charts/determined/values.yaml
> docs: warn users not to use cpu training with a custom scheduler

- docs/release-notes/2708-reduce-single-trial-exp-page-loading.txt
- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
PROBLEM:
The single-trial component is initially created with an `undefined` trial Id until the first trial id is fetched by experiment page. Upon sending the newly fetched trial id to `ExperimentSingleTrialTabs` it doesn't immediately fetch trial detail as it's tied to a polling mechanism, hence waiting for one polling cycle to pass through before making the fetch.
SOLUTION:
Upon detecting a change of trial id in `ExperimentSingleTrialTabs`, immediately make the call to fetch trial detail.
> fix: immediately fetch single trial data when able to [DET-5758]

- docs/how-to/installation/kubernetes.txt
- helm/charts/determined/templates/db-deployment.yaml
- helm/charts/determined/templates/master-deployment.yaml
- helm/charts/determined/templates/priority-classes.yaml
- helm/charts/determined/values.yaml
- master/internal/kubernetes/spec.go
Kubernetes was preempting the master and DB instance because they had a priority of 0. This was occurring as part of the kubernetes preemption protocol, and not as a result of Determined itself. This fix adds a priority value to the master and db instances, as well as reintroduces content from the reverted pull #2631 (prevent CPU-only training from being blocked by the coscheduler).
Set up a CPU-only kubernetes cluster and submit a job. First, make sure that the master and DB instances don't die and restart after job submission. Then, make sure the job is able to be scheduled and starts running.
> fix: cpu only preemption [DET-5763]

- .bumpversion.cfg
- model_hub/Makefile
- model_hub/examples/huggingface/language-modeling/clm_config.yaml
- model_hub/examples/huggingface/language-modeling/mlm_config.yaml
- model_hub/examples/huggingface/language-modeling/plm_config.yaml
- model_hub/examples/huggingface/multiple-choice/swag_config.yaml
- model_hub/examples/huggingface/question-answering/squad.yaml
- model_hub/examples/huggingface/question-answering/squad_beam_search.yaml
- model_hub/examples/huggingface/question-answering/squad_v2.yaml
- model_hub/examples/huggingface/question-answering/squad_v2_beam_search.yaml
- model_hub/examples/huggingface/text-classification/glue_config.yaml
- model_hub/examples/huggingface/text-classification/xnli_config.yaml
- model_hub/examples/huggingface/token-classification/ner_config.yaml
* bumped base image for model-hub transformers to the latest default gpu image with torch 1.9
* modified experiment configs to use a separate cpu image so tensorboard will work
* bumped up versions of transformers and datasets
> chore: update model-hub transformers base image [DET-5701]

- docs/release-notes/2730-fix-too-many-streaming.txt
- webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
Thanks to @hamidzr's [investigative work](https://github.com/hamidzr/determined/commit/a277be0ebd2a8018a33009627bf9be99feb7e1da), it became clear that the abortion of streaming endpoints via the `AbortController` was not the issue. After further investigation, it is due to having too many open streaming endpoints. This is much more obvious in HP Visualization section.
PROBLEM:
Under HP Visualization, currently, as users navigate to each tab, each visualization tab mounts and creates new streaming connections. They start to add up quite a bit, very quickly.
SOLUTION:
Took a look at a couple of options. One option is to extract all the shared streaming endpoints and make those call at a higher order component (`ExperimentVisualization.ts`) so you don't make as many calls. The downside to …
> fix: destroy hp-viz tabs when navigating away [DET-5794]

- master/internal/api/stream.go
- master/internal/api_master.go
- master/internal/api_trials.go
This changes updates streaming code to make the trial logs fields and profiler labels endpoints close when the trial closes. It also shortens the trial stream termination delay because, let's be honest, 20s? That was a little ridiculous of me.
> fix: always terminate streams for terminated trials [DET-5790]

- docs/reference/api/lightning_adapter.txt
- docs/topic-guides/hp-constraints-det.txt
- docs/topic-guides/users.txt
A community user has recently highlighted a chunk of docs where an italic styling was used instead of monospace: https://determined-community.slack.com/archives/CV3MVAQJU/p1625534932056100
This change fixes it, along with a couple of other occurrences I've found with my rudimentary regexp.
N/A
> docs: fix some monospace treatment.

- webui/react/src/components/ContinueTrial.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
- webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
- webui/react/src/pages/TrialDetails.tsx
- webui/react/src/pages/TrialDetails/TrialDetailsHeader.tsx
This should take care of:
- On the Trial page of single-trial experiments, let's add an action to "Continue Trial" to the header
- On the Trial page of single-trial experiments, let's reorder the header buttons to be 1. TensorBoard 2. Download Model 3. Fork 4. Continue Trial
- On the Trial page of a multi-trial experiment, let's reorder the header buttons to be 1. TensorBoard 2. Continue Trial
> chore: Add back Continue Trial button to single-trial experiment page [DET-5749]

- harness/determined/_rendezvous_info.py
Take the text after the final `:` as the port, not the text after the
initial `:` as the port.
I ran the following code in a python interpreter to check my work:
```python
addr = "[::]:1234"
":".join(addr.split(":")[:-1])
int(addr.split(":")[-1])
```
> chore: fix rendezvous address port parsing

- master/internal/kubernetes/pods.go
- master/pkg/model/agent.go
The kubernetes GPU number displayed incorrect numbers, seemingly subtracting numbers from the total number of GPUs instead of just from the available number. This was due to kubernetes counting slots differently from IDs, where IDs looped for every pod. Patched by making the ID == slot count. 
Spin up a kubernetes cluster with autoscaling enabled (https://docs.determined.ai/latest/how-to/installation/setup-gke-cluster.html?highlight=gke). Make sure that the number of slots per node > 1. Start a few experiments and make sure that the number of available GPUs is correct on the dashboard. Also make sure that the number of allocated GPUs on the cluster page also looks correct. 
[DET-1234]: …
> fix: k8s available GPUs indicator [DET-5808]

- docs/release-notes/2753-model-dup.txt
- e2e_tests/tests/experiment/test_noop.py
- harness/determined/common/context.py
- harness/determined/exec/fetch_context.py
- master/internal/api_experiment.go
- master/pkg/tasks/task_trial.go
- master/static/srv/entrypoint.sh
- proto/src/determined/api/v1/api.proto
- proto/src/determined/api/v1/experiment.proto
- webui/react/src/services/api-ts-sdk/api.ts
This fixes the model definition duplication problem, which would cause
experiments with model definitions greater than roughly 64MB to never
start.
This also fixes the model-def-too-big-for-config-maps problem when
running on kubernetes.
Added an e2e test for a large upload, and I plan to run k8s tests to make sure this solution works on non-agents as well.
> fix: pull model definitions into containers [DET-5788]

- docs/release-notes/2761-fix-fork-stale-experiment.txt
- webui/react/src/components/ContinueTrial.tsx
- webui/react/src/pages/ExperimentDetails.tsx
- webui/react/src/pages/Reload.tsx
- webui/react/src/routes/index.ts
- webui/react/src/routes/routes.ts
- webui/react/src/routes/utils.ts
PROBLEM:
During a reroute that mounts to the same page component, the page component does not unmount. For example, when going from `/experiments/1` to `/experiments/2`, both of these pages mount to `ExperimentDetail` page component and so upon a successful fork, when rerouting to the newly forked experiment, the new page will show the stale data from the previous experiment until the new experiment data loads (if at all). 
SOLUTION:
Create a `/reload` route that takes a `path` query param that we can route to to force an unmount of the component. This essentially "refreshes" the page. This is the preferred approach over a `window.location` reload for a few reasons:
- we don't lose or mess with history we accumulate on our end
- using `window.location` in conjunction with our internal …
> fix: add reload route to allow remounting of same pages [DET-5818]

- docs/release-notes/2769-det-e-config.txt
- e2e_tests/tests/experiment/__init__.py
- e2e_tests/tests/experiment/test_noop.py
- harness/determined/cli/command.py
- harness/determined/cli/experiment.py
Add `--config` override to `det e create`, similar to `det notebook` or `det shell`. Now you can change experiment config in ad-hoc fashion, e.g. `det e create const.yaml . --config name=test-final-hack-9`
Also, remove a little bit of dead code in local mode that is irrelevant now that we've merged all python packages into one.
Added an e2e test.
> feat: add `--config` override to `det e create`. [DET-5786]

- CONTRIBUTING.md
> docs: add git-secrets docs [DET-5830]

- docs/topic-guides/system-concepts/scheduling.txt
- helm/charts/determined/templates/scheduler-config.yaml
- helm/charts/determined/templates/scheduler-deployment.yaml
This change updates the k8s scheduling documentation to describe the new priority scheduler with backfilling. It also updates the helm charts to default to the backfilling version of the preemption scheduler.
Launch determined on a k8s cluster based on this helm chart. Use `kubectl get pods -n kube-system` to make sure the `preemption-scheduler-...` pod is running and submit a job to check if it successfully schedules. 
> feat: change k8s preemption scheduler to backfilling scheduler [DET-5398]
