determined-ai/determined

master/internal/resourcemanagers/kubernetes/message.go
master/internal/resourcemanagers/kubernetes/pods.go
master/internal/resourcemanagers/kubernetes_resource_manager.go

Check that the pod exists before actually changing its label. 

fix: jq write k8s label

---

docs/sysadmin-basics/oidc.txt

[DET-6283](https://determinedai.atlassian.net/browse/DET-6283) - OpenID support in Determined EE
Docs only, no testing needed. 
The convention for enterprise-only features is that documentation should be committed to this repository. 

docs: describe oidc integration for enterprise

---

master/internal/command/command.go

Because notebooks, tensorboards, commands, and shells are not persisted, we'll prevent users from modifying them for now and instead ask them to terminate the instances if they wish to modify the priority.

fix: jq error changing ntbcs priority

---

docs/release-notes.txt
docs/release-notes/3122-docs-onboarding.txt
docs/release-notes/3282-rocm.txt
docs/release-notes/3304-fix-cpu-core-count.txt
docs/release-notes/3308-pull-logs.txt
docs/release-notes/3372-fix-jupyterlab-fullconfig-edit.txt
docs/release-notes/3377-rm36.txt
docs/release-notes/3407-deprecate-pbt.txt
docs/release-notes/3414-fix-jobname-not-updating.txt
docs/release-notes/3414-job-queue-adj-s1.txt
docs/release-notes/3453-fix-profiler-filtering.txt
docs/release-notes/socket-activation.txt
docs/sysadmin-basics/cluster-config.txt
docs/training-apis/index.txt

docs: add release notes for 0.17.6

---

webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelRegistry.tsx

Model Registry page has "key" prop warning in <ResponsiveTable> component. Same issue also on Model Details page.

chore: address "key" prop warnings

---

webui/react/src/pages/ExperimentList.tsx
webui/react/src/services/decoder.ts
webui/react/src/types.ts
webui/react/src/utils/task.ts
webui/tests/specs/03-cleanup.spec
webui/tests/tests/StepImplementation.ts

This adds the `Description`, `Searcher Type`, and `Forked From` columns to the experiment list table.

feat: add columns to experiment list table [DET-6400]

---

webui/tests/specs/02-authentication.spec
webui/tests/specs/03-cleanup.spec
webui/tests/tests/StepImplementation.ts

- add support for running auth test suite to run independently
- speed out sign out flow
`npx gauge run ./specs/02-authentication.spec`
circle ci insights for test-e2e-webui on jan 25
last 30 days 63% (down 33%)
last 7 days 69% (up 125%)

test: support running auth test suite to run independently

---

harness/determined/_data_layer/_data_layer.py

adds a metric for recording data layer usage. used for determining whether or not we should deprecate yogadl dependency

chore: add telemetry for data layer usage [DET-5338]

---

.circleci/config.yml

Drop `test-e2e-webui` from CircleCI tests. Don't drop the actual `webui/tests` directory and just remove it from automated CI tests for now. A separate body of work will do that, once we are 100% sure we don't need `webui/tests` and other related items.

ci: remove test-e2e-webui from circleci [DET-6607]

---

docs/concepts/scheduling.txt
docs/sysadmin-deploy-on-k8s/index.txt
docs/training-apis/experiment-config.txt

chore: add docs for specifying priority behavior in k8s

---

harness/determined/cli/job.py
master/internal/experiment.go
master/internal/job/job.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/resource_pool.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/trial.go

Support experiments switching resource pools.

feat: jq allow exp change RPs

---

webui/react/src/App.tsx

chore: fix spacing in ui update message

---

bindings/generate_bindings.py
harness/determined/common/api/bindings.py

chore: simplify generated code for optional param handling

---

master/internal/audit.go
master/internal/audit_test.go
master/internal/config/config.go
master/internal/context/context.go
master/internal/core.go

This change adds basic audit logging for master endpoints in the form of echo middleware. Implemented as designed in ticket, so I will defer a detailed explanation of the intended functionality to Jira.

feat: basic audit logging [DET-6370]

---

webui/react/src/hooks/useModal/useModalExperimentCreate.tsx

During experiment fork, when in advanced config editing mode, upon a key stroke that causes the formatting to error, after correcting the error, the error does not go away. This prevents the fork from happening.

fix: clear out the error if there are no errors upon each keystroke [DET-6614]

---

harness/determined/common/api/bindings.py

Generated code was not fully up-to-date.

fix: correct for out-of-order PR landing

---

webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/utils/error.ts
webui/react/src/utils/job.test.ts
webui/react/src/utils/job.ts

- moving jobs by position in the queue
- moving to another resource pool
- unit tests
- connect the UI from here to the server built on #3525 
- move jobs around using queue position option in the UI
I split part of this out to https://github.com/determined-ai/determined/pull/3482

feat: add further webui support for adjusting jobs

---

master/internal/hpimportance/manager.go

The suggestion to the user to install growforest is without a version, which fails unless you are in a directory with a `go.mod` that specifies it. This change pins the version manually so that the command would succeed in general.

fix: correct suggested command to install growforest

---

webui/react/src/components/ResponsiveTable.test.tsx

PROBLEM:
The flaky test occurs when the test randomly selects 2 or more of the same id to filter in the table.
[sample test flake](https://app.circleci.com/pipelines/github/determined-ai/determined/18699/workflows/dbc8bc3f-a29e-4fcd-bf23-b97393b91b8f/jobs/576849) notice the duplicate id selection (two ids of `rkkm5WAy`).
SOLUTION:
Add lines to ensure each id filter selection is a newly unique id from the given list.
Realistically, it shouldn't flake anymore, so a simple check of the recent CI that react unit test passes should suffice.

fix: ensure randomly picked search id is unique [DET-6626]

---

docs/release-notes/3387-master-config-cli.txt
e2e_tests/tests/cluster/test_agent_restart.py
harness/determined/cli/master.py

match the output format style of other det cli commands

chore: change the output format args for master config cli

---

webui/react/src/pages/Dashboard.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/TaskList.tsx

This is a continuation of [this PR](https://github.com/determined-ai/determined/pull/3481). The previous PR addresses the polling of `agents`. This PR focuses on applying the same work for the rest of the WebUI where applicable. The one call out area where this has NOT been applied is the `Task Logs` page, because there already is a PR to migrate that page over to a new pattern which will resolve it there.
PROBLEM
There are a few places through the WebUI where the polling is occurring without the blocking behavior, where the polling mechanism waits for the previous call to resolve before making another one. Here is an example of what the network calls look like:
SOLUTION:
To fix this, ensure the polling function being passed into the polling hook is an async function.
To test a particular …

chore: update polling functions to be async where applicable [DET-6601]

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

Just open this configuration up through helm.
input values.yaml
```
fluent:
image: fluent/fluent-bit:1.7
```
ouput logs
```
(determined) ➜  determined k logs -f determined-master-deployment-brad-5695b7c985-ptwdk
INFO[2022-01-28T20:18:18Z] master configuration: {"config_file":"","log":{"level":"info","color":true},"db":{"user":"postgres","password":"********","migrations":"file:///usr/share/determined/master/static/migrations","host":"determined-db-service-brad","port":"5432","name":"determined","ssl_mode":"disable","ssl_root_cert":""},"tensorboard_timeout":300,"security":{"default_task":{"id":0,"user_id":0,"user":"root","uid":0,"group":"root","gid":0},"tls":{"cert":"","key":""},"ssh":{"rsa_key_size":1024}},"checkpoint_storage":{"host_path":"/checkpoints","propagation":null,"save_experiment …
```

feat: configure k8s fluent image in the helm chart [DET-6380]

---

e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/experiment/test_launch.py
e2e_tests/tests/experiment/test_pytorch.py
harness/determined/exec/launch.py

fixes a bug where container exits with a failure code but experiment is marked as completed because launch layer is not capturing the sys.exit of the launch call.
- actual code change is in launch.py
- moved launch layer specific e2e tests into its own file
- added return code for run_failure_experiment to capture trial logs

fix: capture sys.exit code from launch

---

e2e_tests/tests/conftest.py

followup to https://github.com/determined-ai/determined/pull/3387
`ag det -C 10 | grep config -C 3 | ag -C 2 -- '(-o|--output|--json)' | less`
- run post merge tests

build: switch old -o json usage to --json

---

webui/react/src/components/Spinner.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx

fix: fix spinner placement for hp viz [DET-6631]

---

webui/react/src/components/LogViewer.tsx
webui/react/src/components/LogViewerCore.tsx

Two problems to address.
1. The tqdm logs uses a `\r` carriage return for progress bars because its an ANSI method of updating the previously printed line (and overwriting with a new string). Unfortunately we don't support the complex ANSI cursor movement behavior, especially via our streaming backend. So instead we treat them as new lines.
2. The flickering of the logs are caused by the log message being so large and tall that it exceeds the visible window range. The logic is broken for such large messages, causing the large log messages to disappear. Update the logic to address this.
NOTE: [this PR](https://github.com/determined-ai/determined/pull/3327) updates the task logs to use the new log viewer, will not have some of these visibility issues. Task logs is the last piece that will …

fix: correct tqdm log display and fix the flickering issue [DET-6470]

---

docs/release-notes.txt

docs: release-0.17.8 notes

---

master/internal/command/command.go
master/internal/core_experiment.go
master/internal/experiment.go
master/internal/job/job.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/resource_pool.go
master/internal/resourcemanagers/resource_pool_test.go

Change priority message to be an int instead of an int pointer.

chore: modify internal priority message

---

webui/react/src/components/NavigationSideBar.tsx

style: shift the dropdown to be visible in collapsed nav state

---

webui/react/bin/try-for-flakes.sh

Preserve the script that re-runs tests multiple times to attempt to trigger flaky test errors.

chore: preserve try-for-flake script for react unit tests from e2e

---

webui/react/src/components/Badge.tsx
webui/react/src/components/BadgeTag.stories.tsx
webui/react/src/components/BadgeTag.tsx
webui/react/src/components/MetricBadgeTag.stories.tsx
webui/react/src/components/MetricBadgeTag.test.tsx
webui/react/src/components/MetricBadgeTag.tsx
webui/react/src/constants/states.ts
webui/react/src/utils/job.ts

Storybook stories around `MetricBadgeTag`, `BadgeTag` and `Badge` are not able to build. There was a dependency structure with `jobStateToLabel` being in a separate file (instead of being in the same file as `stateToLabel` that caused the storybook builds to fail.

fix: resolve badge related stories

---

docs/examples.txt
examples/Makefile
examples/graphs/proteins_pytorch_geometric/README.md

Rebuilt the docs, tested that the new example appears and can be downloaded and extracted.

fix: add PyTorch Geometric example to the docs

---

webui/react/src/components/Message.test.tsx
webui/react/src/components/Message.tsx

Add test for `Message` component, verify that title, message, type matches.
`make test` inside of `webui/react`

chore: WebUI interaction test for Message component [DET-6425]

---

master/internal/api_job.go
master/internal/command/command.go
master/internal/experiment.go
master/internal/job/job.go
master/internal/job/job_test.go
master/internal/resourcemanagers/job.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/resource_pool.go
master/internal/resourcemanagers/resource_pool_test.go
master/internal/sproto/task.go

- switch priority lane if needed
- calculate new q position
- add guiding head and tail nodes
- avoid passing SetGroupPriority w/ null priorities
- note to self: what was their origin?
- reinitialize the q position when moving to another lane
- update how we initialize float64 from time.Time
- delegate sorting jobs to jobs actor
- 
notable missing pieces (future work)
- persistence
- rebalancing calculation
- k8
- unit tests
- through webui and cli: create jobs and move them around across priorities and resource pools
there are a good number of TODOs being added in the code but those are good candidates for tasks to be worked on in parallel.
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRk …

feat: put jobs behind or ahead of one another

---

webui/react/src/components/BadgeTag.test.tsx

test: interaction test for BadgeTag component [DET-6423]

---

harness/tests/experiment/test_local.py

fix: tests failing on pytest 7 [DET-6670] 

---

master/internal/db/postgres_experiments.go

This change updates the hpviz queries to withstand steps, validations and checkpoints that aren't necessarily aligned with each other.

chore: update hpviz to allow unaligned checkpoints [DET-4980]

---

master/internal/task/allocation.go

This change adds a new bool to the allocation actor to track when reservations have been started. `test_cancel_ten_experiment` was flaking occasionally, and it was caused by falsely equating `len(reservations) > 0` to "there are containers we should try to kill, and we should wait until we receive receipt of them being killed". This wasn't true when they are set at the top of `ResourcesAllocated` and we exited due to a DB failure, the experiment already being canceled, etc, before starting them. This caused allocations to hang waiting for `ContainerStopped` messages, which agents never send if you request a non-existent container to stop. This should make this happen less but still isn't perfect; in the event a container fails to launch this may still happen (since we would think we …

chore: unequate reservation existence and the fact they've been started

---

harness/tests/common/test_tls.py

https://determinedai.atlassian.net/browse/DET-6687
Occasionally https://example.com/ responds with 404. This causes `test_custom_tls_certs` to fail. Use https://google.com instead.

fix: use google.com instead of example.com as trusted domain

---

webui/react/src/pages/JobQueue/ManageJob.tsx

allow for a simpler change detection logic
by ensuring the fields are always present.
before: in fairshare when editing a job through manage job modal you'd get
fixes an unreleased bug
fixes #3581 

fix: use hidden prop to always include form items

---

docs/features/notebooks.txt

docs: notebook doc changes to conform to a style guide

---

master/internal/resourcemanagers/kubernetes_resource_manager.go

Return the actually slot used value for K8s
Create experiments with single/multiple slots, and verify slot used value increase accordingly

fix: update K8s slotsUsed value [DET-6704]

---

helm/charts/determined/templates/master-deployment.yaml

Tested manually. See Tim for secrets on pulling this image.

fix: update enterprise helm chart [DET-6668]

---

webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx

The Resource Pool details on the Manage Job modal weren't updating when you changed the selected pool. This fixes that.

fix: update Resource Pool details in Manage Job modal

---

master/static/srv/proto_get_trial_workloads.sql
master/static/srv/proto_get_trials_plus.sql

chore: update get trial queries to not require aligned metrics, checkpoints [DET-4980]

---

agent/internal/docker.go

It is possible for this Docker API call to fail with an error the body, but our code ignores the error and would always return container exited with 0, causing upstream consumers to mistake it for a user requested stop (real exit 0).
From reading https://github.com/moby/moby/blob/a5c757555091df6bd1e9c60c175d167dcdfde83c/container/state.go#L173-L236 i'm not super convinced we could ever see then but still trying to read code.

chore: handle possible errors from docker daemon call /containers/cID/wait

---

master/internal/sproto/globals.go

`GetCurrentRM` checks the existence of the `agents` or `pods` actors to decide whether to return `agentRM` or `k8sRM` actor, which means it really doesn't check _their_ existence. So calls cause extra nil derefs on things that "should never be nil". 
If I see logs from an RM crash, I always end up debugging this deref first because it spams the logs (with this, a panic would spam, but it would at least be a panic that says "no rm found", not a strange deref).
I think soon I will attempt to remove `GetCurrentRM` from the system.

chore: check existence of correct actor to find which RM is in use

---

webui/react/src/components/SelectFilter.stories.tsx
webui/react/src/components/SelectFilter.test.tsx

test: write SelectFilter tests [DET-6663]

---

webui/react/src/pages/TaskList.tsx
webui/react/src/services/apiConfig.ts

Limit each 4 task type endpoints from loading everything. Set a hard cap to something reasonable like 1000 per type.

chore: adding a limit to task endpoints by type

---

webui/react/src/components/ResourcePoolCard.module.scss

minor typo caused the background to disappear for "No Agents Connected" message on resource pool cards.
BEFORE
AFTER

style: fix the background color for `no agents connected` pool card [DET-6625]

---

.circleci/config.yml

ci: upgrade test-unit-react from medium to large resource class

---

webui/react/src/components/Section.test.tsx

Unit test for Section component
Navigate to `webui/react` and `make test`

chore: interactive test for Section [DET-6664]

---

master/internal/resourcemanagers/priority.go
master/internal/resourcemanagers/priority_test.go

fix: setting queue position doesn't trigger preemption

---

master/internal/job/job.go

- update jq API error message for single update requests.
- preserve errors as their original form.

chore: update jq error message for single-job updates

---

agent/internal/containers.go

As a convenience for users running older docker daemon versions, we should configure our client to negotiate an API version.

chore: at least try to auto-negotiate docker client version

---

docs/release-notes/3593-bps.txt
e2e_tests/tests/experiment/__init__.py
e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/experiment/test_pytorch.py
e2e_tests/tests/experiment/test_tf_keras.py
harness/determined/keras/_tf_keras_trial.py
harness/determined/keras/callbacks.py
harness/determined/pytorch/_pytorch_trial.py
harness/determined/util.py

For now, cumulative times are not recorded or shown.  Cumulative times
wouldn't be hard to add but they would introduce a variety of failure
cases where we could show something but we wouldn't know if it were
correct.

feat: log records/second and batches/second in trials [DPS-1]

---

harness/determined/common/api/bindings.py
master/internal/api_user.go
master/pkg/model/user.go
master/static/migrations/20220214125939_user_add_display_name.down.sql
master/static/migrations/20220214125939_user_add_display_name.up.sql
proto/src/determined/api/v1/api.proto
proto/src/determined/api/v1/user.proto
proto/src/determined/user/v1/user.proto
webui/react/src/contexts/Store.tsx
webui/react/src/services/api-ts-sdk/api.ts
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts
webui/react/src/types.ts

API endpoint that allows user fields to be edited. Currently only supports displayName.
Accessible in Swagger docs at `/docs/rest-api/#/Users/PatchUser`.
Send requests to `PATCH users/{username}` and verify that 

feat: create PATCH users endpoint 

---

agent/internal/docker.go

Reverts determined-ai/determined#3607
Will make another PR with this change which includes the debug flag required as I think it should be approved/denied in its full context.

chore: remove extra logging for credHelpers [DET-6710]

---

.circleci/config.yml
e2e_tests/tests/config.py
examples/computer_vision/unets_tf_keras/const.yaml
examples/computer_vision/unets_tf_keras/distributed.yaml
harness/determined/common/schemas/expconf/_v0.py
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml
harness/determined/deploy/aws/templates/vpc.yaml
harness/determined/deploy/gcp/constants.py
harness/tests/experiment/fixtures/ancient-checkpoints/0.17.6-estimator/metadata.json
harness/tests/experiment/fixtures/ancient-checkpoints/0.17.6-keras/metadata.json
harness/tests/experiment/fixtures/ancient-checkpoints/0.17.6-pytorch/metadata.json
helm/charts/determined/templates/master-config.yaml
master/internal/resourcemanagers/provisioner/aws_config.go
master/internal/resourcemanagers/provisioner/gcp_config.go
master/pkg/schemas/expconf/const.go
master/pkg/schemas/expconf/legacy_test.go
model_hub/Makefile
schemas/test_cases/v0/experiment.yaml
tools/scripts/bumpenvs.yaml
webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
webui/react/src/fixtures/responses/experiment-details/set-a.json
webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json

Minor upgrades only for security fixes.
https://app.circleci.com/pipelines/github/determined-ai/determined?branch=mackrory-minor-upgrades&filter=all
- [ N/A ] User-facing API changes need the "User-facing API Change" label.
- [ N/A ] Release notes should be added as a separate file under `docs/release-notes/`.
- [ N/A ] Licenses should be included for new code which was copied and/or modified from any external code.

chore: minor upgrades to ML frameworks

---

harness/determined/deploy/gcp/cli.py

Fixing a broken `det deploy gcp down` from last-minute refactorings in #3615
`det deploy gcp down` should be functional; also see #3615.

fix: regression in det deploy gcp down.

---

webui/react/src/hooks/useModal/useModal.tsx

fix: stop experiment modal closing unexpectedly [DET-6746]

---

webui/react/src/hooks/useModal/useModal.tsx
webui/react/src/hooks/useModal/useModalExperimentCreate.tsx

Changes the default minWidth in useModal to 300px.

fix: allow modal width to shrink on mobile [DET-6443]

---

master/internal/api_command.go
master/internal/api_notebook.go
master/internal/api_shell.go
master/internal/api_tensorboard.go
master/internal/db/postgres_tasks_intg_test.go
master/pkg/model/task.go
master/pkg/tasks/task_gc.go
master/pkg/tasks/task_trial.go

This change adds a small test to make sure that postgres enum's mappings in Golang code remain exhaustive.
We had a few bugs crop up around this, so this is a workaround until we use an orm or autogenerate db code or something.

chore: lint exhaustiveness of postgres enums

---

webui/react/src/components/SelectFilter.test.tsx

PROBLEM:
CircleCI is reporting errors for `SelectFilter.test.tsx`. This occurs locally too.
SOLUTION:
Add `await waitFor(() => { ... });` wrapper to ensure the tests are able to handle changes and re-rendering that occurs due to interactions.

fix: update select filter test to avoid console errors

---

webui/react/src/components/MultiSelect.test.tsx
webui/react/src/components/SelectFilter.test.tsx

Unit test for `MultiSelect` 
Navigate to `webui/react` and `make test`

chore: interaction test for multiselect [DET-6666]

---

master/pkg/model/task.go

Previously task log timestamps were aligned as a side effect of being
printed in seconds.  Now they have more precision but the omission of
trailing zeroes causes them to be misaligned and hard to read.  This
change that ensures trailing zeroes are printed.

chore: realign task log timestamps

---

webui/react/package.json

PROBLEM:
Storybook stories are currently included in the test coverages.
SOLUTION:
When generating test coverage, skip storybook stories (*.stories.tsx). [CRACO](https://github.com/gsoft-inc/craco) uses the `jest` config under `package.json` for coverage controls.

chore: remove storybook stories from test coverage

---

.circleci/config.yml

Only pin the GKE version with major/minor/patch versions (not build metadata) so CI version falls out of support less often.

chore: pin GKE less strictly

---

master/internal/db/postgres_tasks.go

`rank_id` was missing from the task logs query, which caused it to not be pretty printed into the logs.

fix: add rank_id to task logs

---

docs/conf.py

Update copyright in docs footer.

docs: update copyright

---

docs/training-debug/index.txt

docs: restructure training debugging doc

---

webui/react/src/components/LogViewer/LogViewerFilters.test.tsx
webui/react/src/components/LogViewer/LogViewerFilters.tsx
webui/react/src/components/SelectFilter.test.tsx
webui/react/src/setupTests.ts
webui/react/src/utils/string.test.ts
webui/react/src/utils/string.ts

Write interaction test for `LogViewerFilters.tsx`.
Something to note is that Ant Design v4 (v3 is not impacted) select dropdown has [an issue](https://github.com/ant-design/ant-design/issues/23009#issuecomment-929766415) where when opening a dropdown menu, the options list container has the style of "opacity: 0; event-pointer: none;" applied in the testing environment. The workaround was it either to use the lower level `fireEvent` from `react-testing-library` or pass a `skipPointerEventsCheck` value of true to `userEvent.click()`.

test: log filter test [DET-6787]

---

docs/release-notes.txt
docs/release-notes/3513-add-byol-example.txt
docs/release-notes/3593-bps.txt
docs/release-notes/3603-pytorch-lightning-upgrade.txt
docs/release-notes/3624-support-k8s-ssl.txt
docs/release-notes/unify-task-logs.txt

Add release notes for 0.17.10.

docs: add release notes for 0.17.10

---

docs/integrations/prometheus.txt

Fix broken link to Grafana JSON file.

docs: fix broken link

---

docs/sysadmin-deploy-on-prem/requirements.txt

Update Docker installation instructions for MacOS.

docs: update docker install for macos

---

master/internal/db/postgres_experiments_intg_test.go

In the spirit of reliability, this change adds tests to `get_experiments.sql` before I change it drastically, for the sake of performance.

test: add tests for get experiment

---

agent/internal/fluent_intg_test.go
master/internal/db/postgres_tasks.go
master/internal/elastic/elastic_task_logs.go
master/pkg/model/task.go

This code turned out kinda weird but got overlooked when I wrote it, so I rewrote it slightly to be more readable as I was poking around for bugs.
log before
```
[2022-02-28T09:17:57.238394Z] 0837289d || INFO:  validated: 34 records in 0.1703s (199.7 records/s), in 2 batches (11.75 batches/s)
```
log after (artifically added rank to this log, just to show removal of extra spaces.
```
[2022-03-08T15:25:26.838332Z] 0e30e7b4 [rank=0] || INFO: validated: 10000 records in 0.8873s (11270.0 records/s), in 157 batches (176.9 batches/s)
```

refactor: change oddly structured log code

---

e2e_tests/tests/test_logging.py

ci: temporarily stop test flakes

---

webui/react/src/components/LogViewer/LogViewerFilters.tsx
webui/react/src/components/MetricSelectFilter.tsx
webui/react/src/components/SelectFilter.module.scss

Taking this [previous work](https://github.com/determined-ai/determined/pull/3618/files) and apply it on all `SelectFilter`. The problem of the input filter not expanding all the way. Taking one step further on the previous work, the expanded input field would spill out of the container. Apply overflow appropriately so the text is contained behind the dropdown arrow.
BEFORE:
AFTER:
Test the select filter input expands the full dropdown container width instead of the previous 4px width. Some common places to look for:

fix: select filter input width [DET-6777]

---

docs/assets/styles/determined.css

Fixed CSS typo (no closing bracket) which caused correct font not to load.

docs: fix css typo

---

harness/determined/deploy/gcp/gcp.py
harness/determined/deploy/gcp/terraform/main.tf

fix: det deploy gcp bad resource name [DET-6838]
Also bumped terraform google provider version to allow for M1 support for gcp
[DET-6838]: https://determinedai.atlassian.net/browse/DET-6838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: det deploy gcp bad resource name

---

docs/integrations/prometheus.txt

chore: updates to prometheus docs

---

master/static/migrations/20220311095512_add_workspace_tables.down.sql
master/static/migrations/20220311095512_add_workspace_tables.up.sql

Based on the ERD doc, adds tables to the database to support workspaces and projects.
- `username` fields via `user_id` + JOIN
- `lastExperimentStartedAt`, `numExperiments`, and `numActiveExperiments` fields would come from query of experiments with matching `project_id`
- Notes table joined in on their `project_id` field (unless we want these to be JSON attached to the Project table)
- `checkpoint_id` cannot refer to `checkpoints` directly because it's a view, not a table.

feat: Add workspaces, projects, and related DB schema [DET-6815]

---

docs/interact/cli.txt
docs/release-notes.txt
docs/release-notes/3734-images.txt
docs/sysadmin-basics/upgrades.txt

Information on how to upgrade from pre-0.15.0 releases is no longer useful.
Also remove docs on how to deal with a relatively obscure distutils error; the
error is a property of distutils, anyway, and is not specific to Determined.

docs: remove some outdated information.

---

webui/react/src/pages/ExperimentDetails.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/TrialDetails/TrialChart.module.scss
webui/react/src/pages/TrialDetails/TrialChart.tsx
webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx
webui/react/src/pages/TrialDetails/TrialInfoBox.tsx

The skeletons we were using right after creating an experiment gave the impression that the page was waiting for data to load, when in fact the situation was that there isn't any data to show. The skeletons have been replaced with an empty state.
To test, fork an experiment in the webui. You should see a page similar to the "New state" screenshot below, not the "Old state".
Old state:
New state:

fix: replace loading skeleton with empty state [DET-6800]

---

docs/release-notes/README.md

Updated release notes creating process.

docs: update release note process

---

master/static/srv/check_idle.py

Previously, when jupyter took too long to start, check_idle.py would
inject a terrifying stacktrace into the notebook logs.
Tested manually by putting a `sleep 15` into `notebook-entrypoint.sh`.

fix: check_idle.py is quiet when jupyter takes a while to start up

---

harness/determined/common/api/bindings.py
master/internal/api_tasks.go
master/internal/task/all_gather.go
master/internal/task/allocation.go
master/internal/task/allocation_test.go
proto/src/determined/api/v1/api.proto
proto/src/determined/api/v1/trial.proto
webui/react/src/services/api-ts-sdk/api.ts

This change adds functionality to perform an all gather through the master. This is useful to do rendezvous without any shared_fs or other external coordination tools in a world where the RM cannot provide IP addrs.

refactor: add all gather for v2 rendezvous

---

e2e_tests/tests/cluster/test_logging.py
e2e_tests/tests/test_logging.py

Just going to turn this off until I have time to dig in, since it is very bothersome.

test: disable test_task_logs[command] flake

---

harness/determined/cli/job.py

Leftover cleanup from previous merge

chore: clean up code

---

proto/go.mod

forgot one
not really critical to bump this, but may as well

chore: bump proto to 1.18

---

master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/resource_pool.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/task/allocation_test.go
master/internal/task/errors.go
master/internal/task/rendezvous.go
master/internal/task/rendezvous_test.go
master/internal/task/resources_list.go
master/internal/trial.go

Make rendezvous optional and indicate whether it can be performed by the RM providing IP addrs through a feature flag.
Now, rather than assume every allocation will or won't do rendezvous based on a master side config, any tasks (trials/etc) can do rendezvous if the rm provides it.

refactor: feature flag out rm's providing IP addrs

---

agent/internal/container.go
master/internal/api_experiment.go
master/internal/checkpoint_gc.go
master/internal/command/command.go
master/internal/core_experiment.go
master/internal/experiment.go
master/internal/mocks/resources.go
master/internal/resourcemanagers/agent/agent.go
master/internal/resourcemanagers/kubernetes/message.go
master/internal/resourcemanagers/kubernetes/pod.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/resource_pool.go
master/internal/resourcemanagers/scheduler_test.go
master/internal/restore.go
master/internal/sproto/agent_resource_manager.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/task/allocation_test.go
master/internal/trial.go
master/internal/trial_test.go
master/pkg/actor/context.go
master/pkg/actor/ref.go
master/pkg/logger/util.go

This change tries to ensure it is easier to string compotents' logs together. The general strategy is each child component also logs it's parent, so you can join them like with FKs in postgres.
pros: @varlogtim can maybe easier grep the history of a task.
cons: really big logs
i'd love if we just do this and move to json structured logs one day and return those to the uis and let them solve the 'how to read this crap' problem. same for trial logs.

chore: better log metadata

---

master/internal/task/allocation.go
master/internal/task/rendezvous.go
master/internal/task/rendezvous_test.go

refactor: make rendezvous less actor-like

---

docs/features/job-queue.txt

Add documentation for the full job queue.

docs: job queue write feature

---

webui/react/package-lock.json
webui/react/package.json

Remove unused websocket dependencies.

chore: remove unused websockets

---

master/internal/resourcemanagers/agent_resource_manager.go
master/internal/resourcemanagers/resource_pool.go

A couple of things got left behind during the merge of `jq-write` branch. This PR fixes/cleans up two errors: the agent RM was returning "unexpected message" errors and deleting a job would result in excessive "no job id found" messages 

chore: fix up job queue issues after merge

---

webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
webui/react/src/pages/TrialDetails/TrialDetailsProfiles.tsx

A previous PR broke the Logs and Profiler tabs if they were visited while `trial === undefined`. This PR should fix that.
Create an experiment and immediately pause it. If visiting the Logs or Profiler tabs works (ie, isn't an entirely blank screen), this PR is successful.

fix: stop single trial tabs from breaking when trial is undefined

---

docs/sysadmin-basics/index.txt

Remove orphan line residue from :glob: cleanup.

docs: fix typo

---

webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/utils/job.ts

Make the UI aware of this unsupported action on k8.

chore: disable showing queue position related controls for k8 [DET-6917]

---

master/internal/resourcemanagers/kubernetes_resource_manager.go

fix: kubernetes job queue unexpected message

---

docs/concepts/index.txt

docs: fixes for concepts index page

---

agent/go.mod
agent/go.sum
master/go.mod
master/go.sum
master/internal/db/postgres.go
master/internal/db/postgres_cluster_intg_test.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_model_intg_test.go
master/internal/db/postgres_tasks_intg_test.go
master/internal/db/postgres_test_utils.go
master/internal/db/postgres_trial_intg_test.go
master/test/integration/api/main_test.go
master/test/testutils/fixtures.go

Reverts determined-ai/determined#3769

revert: add bun.DB singleton in master

---

harness/tests/requirements/requirements-harness.txt

Add torch as a dependency for harness requirements since installing DeepSpeed requires torch to be installed.  
We install torch under `extras-requires` in circleci unit tests so we don't encounter the issue in ci but running `make get-deps` locally will raise error.  

fix: add dependency for harness tests

---

docs/release-notes/3545-upgrade-mmdetection.txt
model_hub/docker/Dockerfile.mmdetection
model_hub/examples/mmdetection/panoptic_fpn.yaml
model_hub/model_hub/mmdetection/_data.py
model_hub/model_hub/mmdetection/_data_backends.py

Add support for coco panoptic segmentation dataset and associated mmdetection configs.  Includes following changes:
- upgrade mmcv and mmdet versions
- change file client substitution to include panoptic segmentation loader
- add config for panoptic fpn as an example
e2e mmdetection tests completed successfully.

chore: upgrade to support panoptic segmentation for coco [DET-6945]

---

agent/go.mod
agent/go.sum
master/go.mod
master/go.sum
master/internal/db/postgres.go

The protections around the singleton caused more harm than good, so they
are now removed.
This is a follow-up to #3769 and #3795.

chore: add bun.DB singleton in master (again)

---

harness/determined/ipc.py
harness/tests/test_ipc.py

* If a worker dies, we guarantee a nonzero exit.
We were sending SIGTERM to sshd containers, which were "gracefully"
exiting zero, causing non-chief containers with failed workers to act
like they didn't fail.
Now, we ensure that if a worker or child process dies, we always
always exit nonzero.
* Guarantee the last worker to exit is checked for a graceful exit.
There was a codepath where the exit status of the final worker to exit
on a node was being ignored.

fix: bugs in PIDServer

---

docs/release-notes/3347-job-queue-write.txt

docs: release notes for job queue

---

webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/pages/WorkspaceList.tsx
webui/react/src/routes/index.ts
webui/react/src/routes/routes.ts
webui/react/src/routes/utils.ts

This should be all the routes we need for Workspaces.
- Workspaces List
- Workspace Details
- Project Details
They're only accessible by typing in the URL at the moment.

feat: add workspace and project routes [DET-6822]

---

requirements.txt

- `black` is incompatible with the newest `click`: https://github.com/psf/black/issues/2964
- new `black` also needs new `typing-extensions`
- `tensorflow` has a hard requirement on old `typing-extensions`
Let's restrict `click` to an older version to unblock the CI, and remove this pin on the next CI `tensorflow` version upgrade.
CI passes.

ci: fix click/black conflict.

---

harness/determined/pytorch/_data.py

New args need to be accepted.
Still need to think through the implications of allowing new args with old versions of torch.

chore: update pytorch data loader args

---

examples/deepspeed/gpt_neox/gpt2_trial.py
examples/graphs/proteins_pytorch_geometric/model_def.py

Fix GPT-NeoX tests failing due to recent rebase on upstream that included API changes in the GPT-NeoX library.  
Improve pytorch geometric example to be more robust to data download failures by retrying a few times.
Tested experiments in GCP cluster.

fix: e2e tests for deepspeed and pytorch geometric

---

docs/training-apis/experiment-config.txt

We've had quite a few users ask about support for nested hps.  It was released awhile ago but documentation was sparse.  

docs: nested hps [DET-5819]

---

webui/react/src/components/RoutePagination.module.scss
webui/react/src/components/RoutePagination.test.tsx
webui/react/src/components/RoutePagination.tsx
webui/react/src/pages/TrialDetails.tsx
webui/react/src/services/decoder.ts
webui/react/src/types.ts

Allow users to navigate between trials for the same experiment with buttons/keys.

fix: use RoutePagination to navigate between trials

---

master/internal/api_experiment.go

This change fixes a race condition where the DB state of an experiment read as non-terminal but it was in process of closing, so `GET /api/v1/experiments/:id` would improperly return an error.

chore: handle job summary db <-> exp actor race condition

---

master/internal/task/allocation.go

Remove `Allocation.state` field in favor of `Allocation.model.State`.
I am contemplating inserting `Allocation` into database on `PreStart` (instead of when resources are allocated).

refactor: consolidate allocation state.

---

e2e_tests/tests/cluster/test_workspace_org.py
harness/determined/common/api/bindings.py
master/static/srv/get_experiment.sql
proto/src/determined/api/v1/api.proto
webui/react/src/services/api-ts-sdk/api.ts

- Change body of MoveProjectRequest and MoveExperimentRequest
- Bindings
- Small fix to get_experiment.sql now that this branch and master have added columns

fix: Update MoveProject + MoveExperiment

---

docs/sphinx-wrapper.py

~Our little sphinx-wrapper needs `set -o pipefail`, otherwise
sphinx-build can fail without our build step failing.~
Nope, debian dash doesn't have `set -o pipefail`

ci: fail building docs when sphinx-build fails

---

webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts
webui/react/src/types.ts

feat: implement workspace and project frontend APIs [DET-6823]

---

.circleci/config.yml
examples/deepspeed/gpt_neox/Dockerfile
examples/deepspeed/gpt_neox/hp_search.yaml
examples/deepspeed/gpt_neox/zero1_3d_parallel.yaml
examples/deepspeed/gpt_neox/zero1_pipeline_parallel.yaml
examples/deepspeed/gpt_neox/zero3_medium.yaml
harness/determined/launch/autodeepspeed.py

GPT-NeoX example broken on AWS due to NCCL socket settings.  
Fix:
- Add NCCL environment argument
- Make sure DET_MANUAL_INIT_DISTRIBUTED is propagated to non-chief nodes.
- Change CI deepspeed tests to multi-node to catch failures in the future.
Tested in my own cluster and will run CI test for deepspeed.

fix: gpt-neox example multinode on aws

---

harness/determined/common/experimental/checkpoint/_checkpoint.py

Micro-fix for
`det model list-versions` and
`det model describe`

fix: det model describe

---

examples/deepspeed/cifar10_moe/ds_config.json

Fix incorrect ds_config fields that snuck in when debugging.

fix: deepspeed cifar moe example ds_config

---

helm/charts/determined/Chart.yaml
helm/charts/determined/values.yaml
master/internal/resourcemanagers/job.go

It looks like in locking the API state for backwards compatibility, we merged some stray changes. This just cleans that up.

chore: cleanup stray changes

---

webui/react/src/hooks/useModal/useModalExperimentMove.module.scss
webui/react/src/hooks/useModal/useModalExperimentMove.tsx
webui/react/src/hooks/useModal/useModalProjectCreate.module.scss
webui/react/src/hooks/useModal/useModalProjectCreate.tsx
webui/react/src/hooks/useModal/useModalProjectMove.module.scss
webui/react/src/hooks/useModal/useModalProjectMove.tsx
webui/react/src/hooks/useModal/useModalWorkspaceCreate.module.scss
webui/react/src/hooks/useModal/useModalWorkspaceCreate.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/pages/WorkspaceList.tsx
webui/react/src/routes/utils.ts

Created modals for:
- createWorkspace
- createProject
- moveProject
- moveExperiment
This is merging into the Workspaces feature branch.

feat: workspaces create/move modals [DET-6826]

---

examples/deepspeed/gpt_neox/hp_search.yaml
examples/deepspeed/gpt_neox/zero1_3d_parallel.yaml
examples/deepspeed/gpt_neox/zero1_pipeline_parallel.yaml
examples/deepspeed/gpt_neox/zero3_medium.yaml

Change NCCL_SOCKET_IFNAME for GPT-NeoX example so that it will work on both AWS and GCP deployed clusters.

chore: use better NCCL SOCKET setting for gpt-neox

---

harness/determined/common/api/bindings.py
webui/react/src/services/api-ts-sdk/api.ts
webui/react/src/services/decoder.ts

Update the decoder to avoid errors. There could be additional UI changes necessary; the purpose of this update is, again, just to avoid ts compilation errors.

fix: update checkpoint decoder in react

---

master/test/integration/api/api_checkpoints_test.go

Updated tests (reflecting client api changes)

updated api integration tests

---

docs/concepts/scheduling.txt
docs/sysadmin-basics/cluster-config.txt
docs/sysadmin-deploy-on-k8s/helm-config.txt
docs/sysadmin-deploy-on-k8s/index.txt
docs/sysadmin-deploy-on-k8s/install-on-kubernetes.txt

docs: various fixes for master configuration and k8s docs

---

master/internal/command/command.go
master/internal/config/config.go
master/internal/experiment.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx

should we avoid reporting a name at api level for k8 resource pools? 

fix: match reported resource pool name for k8 across endpoints [DET-7006]

---

webui/react/src/components/RoutePagination.tsx

By default, the antd Pagination component shows a dropdown to set the page size if total > 50. Hide this for the RoutePagination use case.

fix: hide sizeChanger on RoutePagination

---

master/internal/command/command.go

Missed a spot when moving to `Asks` from `Tells`. When actor is not expecting a message, it returns an error and causes a crash. 

fix: RM crashes when setting cmd priority

---

docs/release-notes.txt

docs: Release notes for 0.17.14

---

harness/determined/common/experimental/experiment.py
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_model_intg_test.go
master/pkg/model/experiment.go
master/static/migrations/20220331152432_generic-checkpoints.tx.up.sql
master/test/integration/api/api_checkpoints_test.go

fix: fix integration tests

---

netlify.toml

we set the server_address through Netlify so we don't have to update it through git in the future.

chore: remove pr preview cluster address [DET-7040]

---

webui/react/src/hooks/useSettings.test.tsx
webui/react/src/hooks/useSettings.ts

PROBLEM:
current `updateSettings` hook references `settings` state which it mutates directly. This causes a circular state change because the `updateSettings` callback directly depends on the `settings` state directly. Also there is a side affect that results from the update.
SOLUTION:
remove `settings` as a dependency and use prev => {} call back format as an alternative to avoid circular loop.
also move side effect of route change out into an `useEffect`.

refactor: remove dependency of settings in the updateSettings call

---

docs/getting-started.txt

docs: fix install cli typo

---

e2e_tests/tests/fixtures/metric_maker/metric_maker.py
e2e_tests/tests/fixtures/no_op/model_def.py
harness/determined/common/storage/base.py
harness/determined/estimator/_estimator_trial.py
harness/tests/storage/test_storage_base.py
harness/tests/storage/util.py

This is more intuitive behavior for store_path, which will be exposed in
the Core API.

chore: make store_path auto-create the directory

---

harness/determined/exec/prep_container.py
master/internal/api_tasks.go
master/internal/sproto/task.go

Add support to do rendezvous through the master, using some information from slurm on slurm installations.

feat: add slurm rendezvous

---

webui/react/package.json

chore: update dep requirements for react

---

master/internal/api_experiment.go
master/internal/api_trials.go
master/pkg/protoutils/protoless/less.go

This change makes `get e lc --best` behave correctly, sorting nulls last and respecting searcher metric after.

fix: det e lc --best

---

docs/integrations/ecosystem-integration.txt
docs/sysadmin-deploy-on-prem/linux-packages.txt

docs: tweak docs for socket activation

---

webui/react/src/components/InteractiveTable.tsx
webui/react/src/pages/ExperimentList.tsx

fix: resolve crash on upgrade to InteractiveTable [DET-7036]
Basic:
`make live`
`git checkout 0.17.12`
add Trials to columns in column picker modal
`git checkout master`
behold the beauty of a web page crashing
`git checkout table-upgrade-crash-fix`
the page should not crash
explanation: `trials` column name changed to `numTrials` in `columns.settings`, app did a lookup on previous name derived from url/settings, came up blank and didn't even know it. 
this fix includes a check on the property, as well as a number of additional edge case safeguards.
try stress testing by (among others):
http://localhost:3000/det/experiments?columns=nopeNotAColumn&columns=nopeNeitherIsThis
http://localhost:3000/det/experiments?columns=nopeNotAColumn&columns=nopeNeitherIsThis&columns=name …

fix: crash on upgrade to InteractiveTable [DET-7036]

---

webui/react/src/components/InteractiveTable.module.scss
webui/react/src/components/InteractiveTable.tsx

chore: InteractiveTable scroll does not move pagination or other controls [DET-7037]
- add a bunch of columns
- scroll to the right
- verify that this doesn't happen
[DET-7037]: https://determinedai.atlassian.net/browse/DET-7037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: prevent InteractiveTable scroll from moving pagination or other controls [DET-7037]

---

webui/react/src/components/Spinner.test.tsx
webui/react/src/setupTests.ts

test: add interaction tests for spinner [DET-6665]
The interaction here is dependent upon antd style sheets that are not by default loaded into the test environment. Neither is it possible to import stylesheets in the standard way `import './styles.css'`. The solution as discussed [here](https://github.com/testing-library/jest-dom/issues/113#issuecomment-496971128) (stylesheets in jest-dom) is to manually append the desired style tags to the body of the document.
[DET-6665]: https://determinedai.atlassian.net/browse/DET-6665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

test: add interaction tests for spinner [DET-6665]

---

webui/react/src/hooks/useModal/useModalExperimentCreate.tsx
webui/react/src/pages/ExperimentDetails/ExperimentConfiguration.tsx

chore: mask registry creds in experiment config/fork [DET-7013]
- have an experiment
- click fork, add
```
registry_auth:
username: nameduser
password: wordpass
``` 
to the `environment` section of experiment config
- make fork
- go to configuration page of the new experiment
- `registry_auth` should not be there
- pause and continue experiment, expand continue experiment dialog
- `registry_auth` should not be there
- confirm continue, previous auth should be sent in request
- click fork again and expand experiment dialog
- `registry_auth` should not be there
- confirm fork, previous auth should be sent in request
- on new experiment, click fork again
- supply new `registry_auth`
- new auth should be sent in request …

chore: mask registry creds in webui [DET-7013]

---

harness/determined/cli/job.py

for consistency with other cli commands
~I also got a test update in here. maybe I should separate?~

chore: add a default target to det job

---

webui/react/src/components/NavigationTabbar.tsx

chore: add key attribute to avatar ActionCard action [DET-7015]
Adds a `key` attribute to the AvatarCard child within the ActionSheet actions list prop. The other actions within the list are rendered with keys that are equal to the actions `label` however the AvatarCard entry does not currently specify a `key` for the rendered component. Adding this `key` attribute fixes the `unique key` warning due to the currently missing key. 
Note:
This PR is a copy of the now closed PR https://github.com/determined-ai/determined/pull/3928, in order to adhere to the standard practice of using a forked repository. 
1. Pull branch
2. Run the webui
- `cd webui/react`
- `make live`
4.  Open the web browser console, and ensure there is no `unique key` warning.
See [Release …

chore: add key attribute to avatar ActionCard action [DET-7015]

---

docs/release-notes/checkpoint-gc-close.txt
harness/determined/cli/experiment.py
master/internal/checkpoint_gc.go

This change updates the checkpoint GC actor to properly exit when it is finished.

fix: checkpoint gc job should close

---

webui/react/src/components/NavigationTabbar.tsx

chore: add missing icons to mobile navbar [DET-7009]
use mobile, open navbar
all icons should be present
[DET-7009]: https://determinedai.atlassian.net/browse/DET-7009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add missing icons to mobile navbar [DET-7009]

---

docs/release-notes/3849-stale-job-state.txt
master/internal/api_experiment.go
master/internal/command/command.go
master/internal/experiment.go
master/internal/job/job.go
master/internal/resourcemanagers/fair_share.go
master/internal/resourcemanagers/job.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/priority.go
proto/src/determined/experiment/v1/experiment.proto

changes how we provide job summary for individual experiments from an opportunistic and incomprehensive "push when we have updates" to pull when asked.
DET-6918

chore: take out job summary caching [DET-6695]

---

master/internal/api_experiment.go
master/internal/job/job.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/resource_pool.go

This change adds a message for callers to request a resource manager to cleanup state on their end on delete requests.

chore: add message to cleanup external RM resources on delete, for slurm

---

webui/react/src/components/Logo.module.scss

fix: update HPE logo sizes

---

docs/prepare-environment/custom-env.txt

docs: update package versions, add ROCm, edit to style guide

---

.github/workflows/semantic.yml

Move to a new semantic pull request title check based on github actions.

ci: new semantic pull request check.

---

master/internal/resourcemanagers/agent_resource_manager.go
master/internal/resourcemanagers/resource_managers.go

Fix the new `job.DeleteJob` message to be properly forwarded through the agent RM.
Oops, thought I put this in the RM in the first place.

fix: forward job.DeleteJob through agentRM

---

harness/determined/common/_logging.py

Fix a change to task's python logging format that broke parsing log levels.
follow up https://determinedai.atlassian.net/browse/DET-7104

fix: task log level parsing

---

master/pkg/model/experiment.go
master/pkg/model/task.go
master/static/srv/get_task_logs_fields.sql
master/static/srv/notebook-entrypoint.sh
proto/src/determined/api/v1/task.proto
webui/react/src/services/api-ts-sdk/api.ts

This change configures Jupiter lab at launch to log in our standard format. It also fixes a mismatch between python's 'warning' log level, what we expect when regexing out the level with fluent and what the master was looking for in filters.

fix: notebook log level filtering [DET-7098]

---

.github/semantic.yml

ci: remove old semantic PR app config.

---

docs/tutorials/index.txt

docs: fix tutorial link swap

---

webui/react/src/components/LogViewer/LogViewer.test.tsx
webui/react/src/components/TrialLogPreview.tsx
webui/react/src/pages/TaskLogs.tsx
webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
webui/react/src/services/decoder.ts

Trial Logs currently have log message filtering applied. The standard timestamp is filtered out, and the kubernetes container id is filtered out as well. Apply the same logic to task log messages as well.
BEFORE (double timestamp):
AFTER:
UPDATED FORMAT:

chore: apply filtering to task logs

---

master/internal/sproto/resources.go
master/internal/trial.go

chore: add error type for non retryable errors

---

webui/react/src/components/DraggableListItem.module.scss
webui/react/src/components/DraggableListItem.tsx
webui/react/src/hooks/useModal/useModalCustomizeColumns.tsx

feat: add drog and drop functionality to experiment list column table [DET-7044]
Adds the ability to drag and drop rows in the "Customize Columns" label on the "Experiment List" page. 
1. Navigate to the "Experiment List" page and click the "Columns" button.
2. Under the "Visible" column it should be possible to drag and drop the column items.
- Drag columns around and then hit the "save" button, the column order on the experiments list table should match the new column order
- Drag columns around in the table on the experiment list page, and then repeat the above step and ensure the column order still matches the "visible" list.
- Enter  a search term and ensure the drag and drop functionality still works as expected. 
The `withDragAndDropProvider` was defined as a way to enable easier …

feat: add drag and drop functionality to experiment list column table [DET-7044]

---

master/internal/mocks/resources.go
master/internal/resourcemanagers/agent/agent.go
master/internal/resourcemanagers/kubernetes/pod.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/resource_pool.go
master/internal/resourcemanagers/scheduler_test.go
master/internal/sproto/resources.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/task/allocation_test.go

chore: handle errors from starting allocations [DET-5862]

---

e2e_tests/tests/experiment/test_profiling.py

I mistook which test we were talking about when I said 5m was OK.

ci: bump profiling test timeout back up

---

webui/react/src/pages/ModelRegistry.tsx

fix: avoid permanent filtered state in model registry [DET-6946]
- preferably have your own cluster to test the actual no model state (rather than deleting all the models on latest-master, I guess you can though). 
- go to `/det/models`
- if there are existing models delete them
- you should see the 'No Models Registered' Page
- add a new model, see it appear in the table
- apply a bunch of different kinds of filters. even when there are no models matching the filters, you should still have the option to clear the filters
Note:
if someone deletes all their models while in a filtered state, they will not get back to the  'No Models Registered' Page, it will just say "No data," like it does when there's none matching filters.
the filtering happens API side so there's no way to know that …

fix: avoid permanent filtered state in model registry [DET-6946]

---

webui/react/src/hooks/useModal/useModalCustomizeColumns.tsx

fix: experiment columns filter is still applied after closing [DET-6837]
- navigate to experiments page
- open columns modal
- type filter string
- columns are filtered and search highlight is applied
- close modal
- reopen modal
- verify that columns are not filtered and search highlight is not applied
[DET-6837]: https://determinedai.atlassian.net/browse/DET-6837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: experiment columns filter is still applied after closing [DET-6837]

---

master/internal/db/postgres_experiments.go
master/internal/db/postgres_proto.go

Since JSON can't represent infinity, we store infinite metric values as
the string `"Infinity"` or `"-Infinity"` in JSON in the database. Some
ways of taking those strings from PostgreSQL and converting them to
numbers work and preserve the infinite values, and some do not. The most
correct, and also most natural, way is to use `(map->>key)::float8`; the
similar `(map->key)::text::float8` adds quotes to string values and so
fails the last cast. (Also, we were using the `numeric` type before when
we did that, which does not support infinite values anyway.) Another
thing we were doing was running queries that returned jsonb values from
PostgreSQL back to Go and then attempting to do a standard
deserialization into a float64, which would fail on these string values;
we can take advantage of …

fix: handle infinite validation metric values in more cases

---

webui/react/src/services/decoder.ts

log parsing wasn't handling the rank ids in the log messages. Mapping specific to the [log generation code](https://github.com/determined-ai/determined/blob/master/master/pkg/model/task.go#L284-L321).

chore: handle rank id in log entries

---

docs/release-notes.txt
docs/release-notes/3758-deepspeed-dcgan.txt
docs/release-notes/3849-stale-job-state.txt
docs/release-notes/3914-user-path-params.txt
docs/release-notes/checkpoint-gc-close.txt

Add release notes for 0.17.15.

docs: add release notes for 0.17.15

---

master/internal/task/allocation.go
master/internal/trial.go

fix: guard trial and allocation correctness against RM misbehavior

---

.circleci/config.yml

similar to deploy-preview-cluster

build: give the latest-master deploy job a name

---

bindings/generate_bindings.py

```
ambiguous enum parameter: v1GetNotebooksRequestSortBy ['SORT_BY_UNSPECIFIED', 'SORT_BY_ID', 'SORT_BY_DESCRIPTION', 'SORT_BY_START_TIME']
ambiguous enum parameter: v1GetShellsRequestSortBy ['SORT_BY_UNSPECIFIED', 'SORT_BY_ID', 'SORT_BY_DESCRIPTION', 'SORT_BY_START_TIME']
ambiguous enum parameter: v1GetTensorboardsRequestSortBy ['SORT_BY_UNSPECIFIED', 'SORT_BY_ID', 'SORT_BY_DESCRIPTION', 'SORT_BY_START_TIME']
```

chore: warn about ambiguous enum definitions

---

docs/training-run/index.txt

Rebuild the documentation and review the affected page.
While the intended meaning was clear, this fixes a sentence fragment with complete grammar.

docs: fix grammar in training-run index

---

master/internal/core.go

fixing erroneous comment in [(#3971)](https://github.com/determined-ai/determined/pull/3971/files) which addressed [DET-6685]
[DET-6685]: https://determinedai.atlassian.net/browse/DET-6685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: fix documentation comment for /ws/data-layer

---

LICENSE

docs seem to have the correct year
`docs/conf.py: copyright = "2022...`

docs: update copyright date

---

webui/react/Makefile
webui/react/package-lock.json
webui/react/package.json

when installing dependencies we get this warning:
`npm WARN deprecated @types/moment-timezone@0.5.30: This is a stub types definition. moment-timezone provides its own type definitions, so you do not need this installed.`

chore: remove deprecated type provider for moment-timezone

---

webui/react/src/components/ActionSheet.tsx

Address small complaint in React about about a missing key. Not sure why exactly this is triggered in the multi-trial experiment Trials tab view...

fix: add key for cancel operation

---

e2e_tests/tests/cluster/test_logging.py
e2e_tests/tests/conftest.py

fix: change timeout in e2e_tests/tests/cluster/test_logging.py/test_trial_logs

fix: change timeout in e2e_tests/tests/cluster/test_logging.py/test_trial_logs

---

docs/features/job-queue.txt
docs/release-notes/3938-job-queue-k8s.txt
master/internal/job/job.go
master/internal/resourcemanagers/job.go
master/internal/resourcemanagers/kubernetes/message.go
master/internal/resourcemanagers/kubernetes/pod.go
master/internal/resourcemanagers/kubernetes/pods.go
master/internal/resourcemanagers/kubernetes_resource_manager.go
master/internal/resourcemanagers/resource_pool.go
master/internal/resourcemanagers/resource_pool_test.go
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/utils/job.ts

Adds previously available features of the job queue into Kubernetes. Most of the changes are similar to the changes made to the agent job queue.
Play with the job queue in kubernetes. Submit both single, distributed, and adaptive jobs and rearrange their priorities and positions.

feat: allow position modification in k8s [DET-6967] [DET-6968]

---

webui/react/src/components/NavigationTabbar.tsx

Doh found another one of these lol

fix: add another missing key fix

---

master/internal/checkpoint_gc.go
master/internal/command/command.go
master/internal/db/postgres_cluster_intg_test.go
master/internal/db/postgres_tasks_intg_test.go
master/internal/db/postgres_trial_intg_test.go
master/internal/task/preemption_test.go
master/internal/task/rendezvous_test.go
master/internal/trial.go
master/pkg/model/task.go

Remove redundant & useless constructor method.
I needed to check the new semantic pull request check so I made this PR.

refactor: remove `NewAllocationID`.

---

e2e_tests/tests/cluster/test_agent_disable.py

test: ensure that agent disabling doesn't count for experiment restarts [DET-5916]

---

.circleci/config.yml
webui/react/README.md

Add build result badge and test coverage badge to `webui/react/README.md`
Verify that badges exists.

ci: Add build/coverage badge for webui/react [DET-6767]

---

e2e_tests/tests/command/test_run.py
master/internal/core.go
master/internal/db/database.go
master/internal/db/postgres_helpers_intg_test.go
master/internal/db/postgres_tasks.go
master/internal/db/postgres_test_utils.go
master/internal/db/postgres_trial.go
master/internal/db/postgres_trial_intg_test.go
master/internal/mocks/db.go
master/internal/resourcemanagers/agent/agents.go
master/internal/resourcemanagers/agent/models.go
master/internal/resourcemanagers/resource_pool.go
master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go
master/internal/task/rendezvous.go
master/internal/task/rendezvous_test.go
master/internal/task/resources_list.go
master/internal/trial.go
master/internal/trial_test.go
master/pkg/cproto/container.go
master/pkg/model/test_utils.go
master/static/migrations/20220418191704_agent-resources.tx.down.sql
master/static/migrations/20220418191704_agent-resources.tx.up.sql
master/test/integration/api/api_trials_test.go

- task creation for trials and allocation creation now happen earlier, so the resource tables could FK on these objects.
- the data is unused for now, but will be needed for rolling upgrades and some EE work.
- since some of these are using Bun, switch allocation tests to use the real database.
N / A

chore: store allocation resources and agent RM containers in DB.

---

.circleci/config.yml

current upload method uses a hardcoded token - we should move to using a token provided by the env variable $CODECOV_TOKEN.

chore: move webui codecov upload to use env var instead of hardcoded token

---

webui/react/src/components/BreadcrumbBar.tsx
webui/react/src/components/Navigation.tsx
webui/react/src/pages/ProjectDetails/ProjectDetailsTabs.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/pages/WorkspaceList/WorkspaceActionDropdown.tsx

Merging into the Workspaces feature branch.
Speeds up loading pinned workspaces on the sidebar, plus small additional changes.

chore: speed up loading pinned workspaces

---

webui/react/src/services/apiConfig.ts

The `apiConfig.ts` is a common area for making a mistake because it required two api objects to be updated when there is a new api module to consume. The 2nd one is really easy to miss, so this update reduces it to one area to update.

refactor: simplify apiConfig to reduce redundancy

---

helm/charts/determined/templates/scheduler-deployment.yaml

Updates the k8s scheduler to the latest, which supports queue positions and reordering.

chore: update k8s scheduler to run latest image

---

e2e_tests/tests/experiment/test_pytorch_distributed.py
e2e_tests/tests/fixtures/mmdetection/distributed_fake_data.yaml
e2e_tests/tests/fixtures/pytorch_amp/apex_amp_distributed.yaml
e2e_tests/tests/fixtures/pytorch_amp/auto_amp_distributed.yaml
e2e_tests/tests/fixtures/pytorch_amp/manual_amp_distributed.yaml
e2e_tests/tests/fixtures/pytorch_identity/model_def.py
e2e_tests/tests/fixtures/pytorch_identity/torch_distributed.yaml
harness/determined/_core/_distributed.py
harness/determined/_trial_controller.py
harness/determined/exec/harness.py
harness/determined/exec/worker_process_wrapper.py
harness/determined/launch/torch_distributed.py
harness/determined/pytorch/README.md
harness/determined/pytorch/_pytorch_context.py
harness/determined/pytorch/_pytorch_trial.py
harness/tests/launch/test_deepspeed.py
harness/tests/launch/test_horovod.py
harness/tests/launch/test_torch_distributed.py
harness/tests/launch/test_util.py
model_hub/examples/mmdetection/fasterrcnn.yaml
model_hub/examples/mmdetection/hydra/configs/config.yaml
model_hub/examples/mmdetection/panoptic_fpn.yaml
model_hub/examples/mmdetection/yolov3.yaml
model_hub/model_hub/mmdetection/__init__.py
model_hub/model_hub/mmdetection/_callbacks.py
model_hub/model_hub/mmdetection/_trial.py
model_hub/model_hub/mmdetection/utils.py

launch layer + trial code changes needed for supporting torch native dtrain.
tests to follow.

feat: support for torch native dtrain

---

master/static/migrations/20220502180510_generic-checkpoints.tx.up.sql

fix: fix old checkpoints

---

webui/react/package-lock.json
webui/react/src/services/utils.ts

There is an issue of the `readStream` of not returning the buffer data upon a terminal state. When the promise has resolved, the data is not returned back. The logic was previously broken by me 🤦  Fortunately found this issue before a release!

fix: correct the return type for readStream

---

examples/computer_vision/detectron2_coco_pytorch/model_def.py
examples/computer_vision/efficientdet_pytorch/model_def.py
model_hub/examples/huggingface/language-modeling/clm_trial.py
model_hub/examples/huggingface/language-modeling/mlm_trial.py
model_hub/examples/huggingface/language-modeling/plm_trial.py
model_hub/examples/huggingface/question-answering/qa_beam_search_trial.py
model_hub/examples/huggingface/question-answering/qa_trial.py
model_hub/examples/huggingface/text-classification/glue_trial.py
model_hub/examples/huggingface/text-classification/xnli_trial.py
model_hub/examples/huggingface/token-classification/ner_trial.py

Fix breakages introduced by #4060.

chore: update deprecated reducer usage

---

docs/training-apis/api-core/checkpoints.txt
docs/training-apis/api-core/distributed.txt
docs/training-apis/api-core/getting-started.txt
docs/training-apis/api-core/hpsearch.txt
docs/training-apis/api-core/index.txt
docs/training-apis/api-core/metrics.txt
docs/training-apis/api-core/reference.txt
docs/training-apis/index.txt
examples/tutorials/core_api/0_start.py
examples/tutorials/core_api/0_start.yaml
examples/tutorials/core_api/1_metrics.py
examples/tutorials/core_api/2_checkpoints.py
examples/tutorials/core_api/3_hpsearch.py
examples/tutorials/core_api/4_distributed.py
harness/determined/core/_checkpoint.py
harness/determined/core/_context.py
harness/determined/core/_distributed.py
harness/determined/core/_preempt.py
harness/determined/core/_searcher.py
harness/determined/core/_train.py
harness/determined/pytorch/samplers.py

Co-authored-by: @gh-determined-ai 
https://determinedai.atlassian.net/browse/DET-6633

docs: add docs for the Core API

---

webui/react/src/pages/ExperimentList.tsx

User column missing from experiment list.
The `dataIndex: 'user'` needs to be there for the experiment user because the table `key` is set to a unique auto-gen type form api-ts-sdk.

fix: add user column back to experiment list

---

.circleci/config.yml

Adds codecov to python and consolidates coverage of go and webui portions.
Codecov doesn't behave well with python in circleci due to path resolution issues, so it's easier to pip install codecov instead of using the orb for python. 

chore: add and consolidate code coverage to codecov

---

webui/react/src/components/LearningCurveChart.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
webui/react/src/pages/TrialDetails/TrialChart.tsx

Metric values can now come through as `NaN`, `Infinity` and `-Infinity`. Our charts can't render these values, so typically the chart just renders a blank chart. For now, filter out these values for the purposes of charting, and will address handling them better in the near future.
Before:
After:

fix: filter out NaN, +/- Infinity metric values for charts for now.

---

webui/react/src/components/InteractiveTable.tsx
webui/react/src/pages/ExperimentList.tsx

fix: dont show archived in column picker [DET-7187]
crashing was addressed by [#4070](https://github.com/determined-ai/determined/pull/4070) but this includes some additional defensive coding to protect against that kind of thing in the future.
clear local storage
`git checkout 0.18.0-rc0` 
`make live`
navigate to experiments list. toggle archived. open column picker.
- archived shows up
move some columns around, click add all
- page crashes
clear local storage
`git checkout fix-column-picker`
do same, archived shouldn't show up, page shouldn't crash
[DET-7187]: https://determinedai.atlassian.net/browse/DET-7187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dont show archived in column picker [DET-7187]

---

webui/react/src/components/BreadcrumbBar.module.scss
webui/react/src/components/BreadcrumbBar.tsx
webui/react/src/components/Markdown.tsx
webui/react/src/components/NavigationSideBar.module.scss
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/NotesCard.tsx
webui/react/src/components/PageHeaderFoldable.module.scss
webui/react/src/components/PaginatedNotesCard.tsx
webui/react/src/components/SelectFilter.tsx
webui/react/src/components/TaskActionDropdown.tsx
webui/react/src/components/WorkspaceIcon.tsx
webui/react/src/hooks/useModal/Project/useModalProjectMove.tsx
webui/react/src/hooks/useModal/useModalExperimentMove.module.scss
webui/react/src/hooks/useModal/useModalExperimentMove.tsx
webui/react/src/pages/ExperimentDetails.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/ProjectDetails.module.scss
webui/react/src/pages/ProjectDetails.settings.ts
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/ProjectDetails/ProjectDetailsTabs.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/pages/WorkspaceDetails/ProjectActionDropdown.tsx
webui/react/src/pages/WorkspaceDetails/ProjectCard.module.scss
webui/react/src/pages/WorkspaceDetails/ProjectCard.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.tsx
webui/react/src/pages/WorkspaceList.settings.ts
webui/react/src/pages/WorkspaceList.tsx
webui/react/src/pages/WorkspaceList/WorkspaceActionDropdown.tsx
webui/react/src/pages/WorkspaceList/WorkspaceCard.module.scss

This is merging into the Workspaces feature branch.
Fixes a lot (but not all) of the bugs from the Workspaces bug bash.

fix: address workspaces bug bash reports

---

agent/cmd/determined-agent/run.go
agent/internal/agent_test.go
docs/release-notes/fix-k8s-logs.txt
docs/sysadmin-deploy-on-k8s/install-on-kubernetes.txt
docs/sysadmin-deploy-on-prem/docker.txt
e2e_tests/tests/cluster/test_logging.py
helm/charts/determined/values.yaml
master/internal/resourcemanagers/kubernetes/pod_test.go
master/pkg/etc/etc.go
master/pkg/tasks/const.go
master/pkg/tasks/task.go
master/static/srv/command-entrypoint.sh
master/static/srv/entrypoint.sh
master/static/srv/gc-checkpoints-entrypoint.sh
master/static/srv/notebook-entrypoint.sh
master/static/srv/shell-entrypoint.sh
master/static/srv/task-logging-setup.sh
master/static/srv/task-logging-teardown.sh
master/static/srv/task-signal-handling.sh
master/static/srv/tensorboard-entrypoint.sh

To prevent losing logs from very short commands in determined on kubernetes, all task container entrypoints are updated to wait on stdout and stderr process substitution filters before exiting. Additionally, the recommended fluentbit version is changed to 1.9.3, due to enhancements in SIGTERM handling. As a side effect from relying on so many shell features to fix this, we can no longer `exec` the container main process.

chore: wait for process substition log filters [DET-6712]

---

harness/determined/common/api/bindings.py
harness/determined/exec/prep_container.py
master/internal/api_tasks.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/static/srv/notebook-entrypoint.sh
master/static/srv/shell-entrypoint.sh
master/static/srv/tensorboard-entrypoint.sh
proto/src/determined/api/v1/api.proto
proto/src/determined/api/v1/trial.proto
webui/react/src/services/api-ts-sdk/api.ts

This change allows containers which would like proxies in slurm to advertise their proxy address to the master. When this address is advertised, the proxy is registered in the master and endpoints concerning proxies will list addresses for the container.
There are a million ways to write this code. I just went with the simplest I could find for now.

chore: slurm proxy support

---

docs/sysadmin-basics/cluster-config.txt
docs/sysadmin-deploy-on-aws/install-on-aws.txt
harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml
harness/determined/deploy/aws/templates/vpc.yaml
harness/determined/deploy/gcp/cli.py

* Pass `--fsx-id` option to CloudFormation.
* Simplify validation of `--scheduler-type` option.
* Make default value of `--max-agent-starting-period` consistent.
* Various grammar and docs cleanups.

chore: cleanup and fixes for "det deploy"

---

e2e_tests/tests/cluster/test_users.py
e2e_tests/tests/cluster/test_users_experiment_api.py
harness/determined/common/api/experiment.py

Don't reinitialize sessions in experimental experiment APIs using `determined` user.
Added a test.
Issue thread: https://determined-ai.slack.com/archives/C0124B04SGM/p1651698021338509
Test Script
```
import determined.common.api as determined_api
import determined.common.api.certs as certs
import pathlib
from determined.common import context
from determined.common import util
context_dir = '.'
context_path = pathlib.Path(context_dir)
model_context = context.Context.from_local(context_path)
dai_experiment_config = util.safe_load_yaml_with_exceptions(open('const.yaml'))
determined_master = 'http://localhost:8080'
requested_user = 'ilia'
password = 'oops'
certs.cli_cert = certs.default_load(
master_url=determined_master,
)
determined_api.authentication.cli_auth = …
```

fix: bindings sessions in experiment apis.

---

codecov.yml

Creates a simple codecov configuration file that enforces an 85% coverage metric on PRs.

chore: enable codecov enforcement

---

e2e_tests/tests/experiment/test_pytorch_distributed.py

fix: mark distributed tests as parallel

---

codecov.yml

Codecov is being annoying and it doesn't prevent people from squash-merging anyways, so we'll turn it to informational until we get a better and more informed opinion.

chore: change codecov to informational only

---

webui/react/src/components/ResourcePoolCardLight.tsx
webui/react/src/pages/Cluster/ClusterOverview.tsx
webui/react/src/pages/Cluster/utils.test.ts
webui/react/src/types.ts

on-premise deployments shouldn't rely on max agents for calculating or reporting total slots or agents.
- remove duplicate type definitions for ResourcePool type

chore: use reported slots available for on prem deployments

---

docs/getting-started.txt

docs: rework quickstart for ml developers

---

master/static/srv/entrypoint.sh
master/static/srv/tensorboard-entrypoint.sh

fix: add missing task log teardown for tb, trials

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/templates/scheduler-config.yaml
helm/charts/determined/templates/scheduler-deployment.yaml
helm/charts/determined/templates/scheduler-permissions.yaml

Previously for the preemption scheduler, we would piggyback off of the coscheduler resources and just rename the scheduler. This was causing some issues when interpreting if the job was actually preemptible or not because it would still be listed for the "coscheduler" instead of the "preemption" scheduler. This PR changes the resources to be explicitly "coscheduler" or "preemption".
Test feature:
1. Deploy k8s cluster
2. Submit a job
3. Go to the jobs task, click "Manage Job" for your job, and check if `Is Preemtible` == Yes
Test Upgrading:
1. Deploy k8s cluster using an old determined version
4. Use `helm upgrade` to upgrade it to the current one
5. Ensure it works smooth
[DET-1234]: …

chore: explicit naming of preemption and coscheduler resources [DET-7140]

---

e2e_tests/tests/fixtures/pytorch_amp/apex_amp_distributed.yaml
e2e_tests/tests/fixtures/pytorch_amp/auto_amp_distributed.yaml
e2e_tests/tests/fixtures/pytorch_amp/manual_amp_distributed.yaml

circleCI has eth interface devices, add to test configs

fix: NCCL interface in distributed tests

---

harness/determined/launch/horovod.py
harness/determined/launch/wrap_rank.py

this just affects logging, it seems.

chore: fix rank for horovod with mpi

---

codecov.yml

https://docs.codecov.com/docs/common-recipe-list#disable-pull-request-comments
I did not test this but I hope it'll work.

ci: turn off codecov bot PR comments

---

codecov.yml

A level of nesting may have been lost: https://docs.codecov.com/docs/common-recipe-list#set-non-blocking-status-checks

ci: make codecov information for sure now.

---

master/internal/prom/prom.go
master/internal/task/allocation.go
master/internal/trial.go

Updates to prometheus endpoint:
- add job ID to det-state mappings
- add experiment labels on experiment creation

chore: add job ID and experiment labels to prometheus endpoint mappings [DET-6964]

---

docs/release-notes/4132-web-fix-user-filter.txt
webui/react/src/services/apiConfig.test.ts
webui/react/src/services/apiConfig.ts

Fix the issue of handling older local storage user filter settings that are still using usernames instead of user ids. The usernames in the dashboard filters and other areas with stick user pickers cause `userIds=` to be sent to the API quick causes `400 Bad Request` response.

fix: user filter on dashboard [DET-7251]

---

.circleci/config.yml
docs/Makefile
examples/Makefile
helm/Makefile
model_hub/Makefile

Because docs/ depends on examples/, model_hub/, and helm/, and recursive
make is never quite correct, incremental builds will not be perfect.
But they should be correct enough for efficient local development.
Only clean builds are fully correct, which CI already does.
Tested for various types of incremental build scenarios.

build: make docs build incremental and idempotent

---

docs/Makefile
docs/live.py
docs/requirements.txt

The live.py local docs server supports autorebuilding whenever input
files change, and client-side autoreloading whenever a doc being viewed
is updated on disk.

chore: add a local docs server

---

.circleci/config.yml

Right now, `package-and-push-system-local` takes on average 8 minutes, and appears CPU bound. Want to validate this hypothesis by increasing the resource class and seeing if we get improvements in duration.

ci: Increase package-and-push-system-local resource class

---

.circleci/config.yml

PRs which are docs-only should not trigger the full CI.

ci: docs-only ci

---

webui/react/src/components/InteractiveTable.tsx

fix: adjust upscaling of column widths [DET-7220]
cursor tracking of column resize was disturbed by theme architecture.
there was an existing issue as well where the default widths led to there being slight amount of horizontal scroll that would slightly hide filters on the rightmost column if it had any.
this addressses both. 
the basic thing is: 
- if we upscale too much, we cause horizontal scroll
- if we upscale too little, we lose resize tracking (proportionally to how far off we are)
My sense is that causing unnecessary horizontal scroll is worse than a slight loss of resize tracking, so I am erring on the side of upscaling too little here.
tried to do it based on computed values before but it wasn't working. …

fix: adjust upscaling of column widths [DET-7220]

---

harness/determined/tensorboard/base.py
harness/determined/tensorboard/util.py
harness/tests/tensorboard/test_util.py

Instead of selectively uploading some types of tensorboard files (as specified by a list of extensions), upload all files.
Note: find_tb_files is so simple that it could have been removed. However, I am planning to extend util.py shortly to let the user specify the files they want to upload and possibly rename.
https://determinedai.atlassian.net/browse/DET-7139

feat: upload all tb files DET-7139

---

webui/react/README.md

doc: fix a broken file reference

---

codecov.yml

Apparently github annotations are not comments but a different thing. Turn them off as well.

ci: turn off github annotations.

---

master/static/srv/proto_get_trials_plus.sql

Without this join, the CTE materializes the entire table, which is insanely large in general.

perf: fixup query for latest training per trial [DET-7352]

---

docs/release-notes/delete-delete-failed-experiments.txt
master/pkg/model/experiment.go

This was actually just a typo on my part, I remembered always intended this once I looked at this.

chore: allow deleting delete failed [DET-7070]

---

webui/react/src/components/NavigationSideBar.module.scss
webui/react/src/components/NavigationSideBar.tsx

fix issue of not being able to click on experiments list page when viewing experiment detail page

fix: enable currently active side nav item [DET-7349]

---

.gitignore

Someone on the HPE side needed this helping with slurm work and it's basically no harm. Don't want it to end up just in EE.

chore: add .dccache to .gitignore

---

docs/sysadmin-basics/cluster-config.txt

docs: document database SSL options

---

docs/sysadmin-basics/cluster-config.txt

docs: update fluent-bit version.

---

agent/internal/container.go
agent/internal/containers.go
agent/internal/docker.go
master/internal/resourcemanagers/kubernetes/spec.go
master/pkg/cproto/spec.go
master/pkg/tasks/task.go
master/pkg/tasks/task_command.go
master/pkg/tasks/task_trial.go

`UseFluentLogging` is always true. Rip out all the related branching in the code.

refactor: rip out `UseFluentLogging`.

---

harness/determined/cli/agent.py
harness/determined/common/api/bindings.py
proto/src/determined/agent/v1/agent.proto
webui/react/src/services/api-ts-sdk/api.ts

We need this for slurm, since `/agents` is essentially broken for k8s and slurm due to the 'magic actor routing' not being magic enough.

chore: migrate det a list to new api and bindings

---

harness/determined/ipc.py
harness/determined/pytorch/_pytorch_trial.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/determined/pytorch/lightning/_adapter.py

`flake8-comprehensions` got a [new thing](https://github.com/adamchainz/flake8-comprehensions/pull/409) for unnecessary `map(lambda: `, and it [started to fail our ci](https://app.circleci.com/pipelines/github/determined-ai/determined/22506/workflows/88b86e3f-8a03-4f58-af50-54e4ac13ab33/jobs/716802). it's not wrong.
Also `pyzmq==23.0.0` has added proper support for types so a whole bunch of `type: ignores` is not unnecessary.
make python lint green again.

style: address new `flake8-comprehensions`, `pyzmq==23.0.0`.

---

webui/react/src/components/Logo.module.scss
webui/react/src/components/Logo.stories.tsx
webui/react/src/components/Logo.tsx
webui/react/src/components/NavigationSideBar.module.scss
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/PageMessage.tsx
webui/react/src/components/SelectFilter.module.scss
webui/react/src/components/TableFilterDropdown.module.scss
webui/react/src/components/TableFilterSearch.module.scss
webui/react/src/pages/ExperimentDetails/Header/ExperimentHeaderProgress.tsx
webui/react/src/pages/SignIn.tsx
webui/react/src/styles/antd.scss

PR to adjust and fix theme issues to follow up on the [theme architecture PR](https://github.com/determined-ai/determined/pull/4004).
List of tweaks:
- fix styles for multi-select filters
- update table column header filter and search box styles
- fix logos to support light/dark mode
- prevent experiment progress bar from flickering when it's not in an **active** state

style: minor theme fixes and style adjustments [DET-7349]

---

.circleci/config.yml

circleci caching is inconsistent.

ci: bust circleci cache

---

docs/release-notes/det-experiment-logs.txt
harness/determined/cli/experiment.py
harness/determined/cli/trial.py

Adds ```det e logs <EXP_ID>``` which gets the logs of the first trial of an experiment. Has the same flags as ```det trial logs```.
Single trial exp
```
det e create examples/gan/gan_mnist_pytorch/const.yaml examples/gan/gan_mnist_pytorch
det e logs 11
```
Create a experiment and get logs before it creates a trial
```
det e create examples/gan/gan_mnist_pytorch/const.yaml examples/gan/gan_mnist_pytorch
det e logs 12
```
HP search gets the first trial
```
det e create examples/tutorials/mnist_pytorch/adaptive.yaml examples/tutorials/mnist_pytorch/
det e logs 14
```
Various parameters
```
det experiment logs -f 14
det e logs --agent-id $HOSTNAME --tail 2 14 
det e logs --container-id 8a3a38323b0b --head 5 14 
det e logs --timestamp-after 2022-05-20T16:17:20.810813Z --timestamp-before …
```

feat: add det experiment logs <EXP_ID> [DET-7145]

---

master/static/srv/proto_get_trial_ids_for_experiment.sql

https://user-images.githubusercontent.com/28383080/169621191-58038f68-83f5-4317-9f6b-d75a15bf82ee.mov
https://user-images.githubusercontent.com/28383080/169621046-f576b485-9626-430c-867d-fa8672340d09.mov

fix: add restarts back to get_trial_ids for sorting

---

docs/sysadmin-basics/cluster-config.txt

docs: improve OpenTelemetry docs slightly

---

master/internal/user/service.go

For a while, the EE code has had some refactors in this code to expose
some functions for other packages, leading to occasional annoying
conflicts. Here we simply bring in those changes; this means there are
some functions that are unnecessarily exposed within the context of OSS
alone, which is mildly suboptimal but should be fine (and the changes
are otherwise normal-looking).

refactor: pull in user service code changes from EE

---

docs/training-apis/experiment-config.txt

chore: update entrypoint in expconf docs

---

master/internal/api_trials.go
master/internal/db/postgres_trial_intg_test.go
master/static/srv/proto_get_trials_plus.sql

This query plan once again got out of control as the steps table size changed drastically on our test cluster. Somehow this was caused by our use of `unnest` and Postgres not being able to select the selectivity of the trial_id index on everything when joining into the `searcher_info` CTE.
🤷 

perf: tweak proto_get_trials_plus plan

---

docs/release-notes/README.md

docs: update release note instructions with important admonition

---

master/internal/connsave/conn_save.go
master/internal/connsave/connsave.go

feat: save connection in context

---

agent/internal/agent.go
agent/internal/options.go

Waiting on master side changes, or can be pulled in with master side changes. 

feat: enable agent side mTLS connection to master

---

master/internal/resourcemanagers/resource_pool.go
master/internal/sproto/resources.go
master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go

I think I got a bit eager reacting to some review comments and renamed one thing too many.

chore: revert rename of `RestoreResourcesFailure -> ResourcesFailure`.

---

docs/release-notes/fix-rendezvous-timeout-message.txt
master/internal/task/all_gather.go
master/internal/task/rendezvous.go

chore: fix rendezvous timeout logic

---

harness/determined/cli/agent.py
master/internal/resourcemanagers/kubernetes/pods.go

Allow `det slots list` and the WebUI to accurately show how many slots are available after accounting for non-determined tasks.
Deploy a k8s cluster and, outside of determined, submit several pods that request GPUs. Check the WebUI and `det slot list` to make sure the cluster page, "Available GPUs", and the CLI all show accurate slot counts.

feat: k8s detect non-det tasks

---

webui/react/src/components/Page.tsx

PROBLEM:
`props.children` is getting overwritten at the OSS `Page` component by the `<Helmet>` code.
SOLUTION:
Extract the `Helmet` portion out of the `props.children` region.

fix: adjust page to preserve props.children

---

webui/react/.eslintignore

chore: add node_modules to eslintignore

---

docs/training-run/index.txt

docs: add enhanced launcher user guide

---

docs/release-notes/gcs-checkpoint-prefix.txt
docs/sysadmin-basics/cluster-config.txt
docs/sysadmin-deploy-on-k8s/helm-config.txt
docs/training-apis/experiment-config.txt
examples/tutorials/mnist_pytorch/const.yaml
harness/determined/common/schemas/expconf/_gen.py
harness/determined/common/storage/gcs.py
harness/determined/tensorboard/build.py
harness/determined/tensorboard/gcs.py
harness/tests/storage/test_gcs.py
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/internal/api_tensorboard.go
master/pkg/schemas/expconf/storage_config.go
master/pkg/schemas/expconf/zgen_gcs_config_v0.go
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/gcs.json
schemas/test_cases/v0/merging.yaml
schemas/test_cases/v0/misc.yaml

Adds support for master config and experiment config option of setting a gcs prefix.
Harness test along with
manual validation of creating an experiment/ master config / tensorboard with 
```
checkpoint_storage:
type: gcs
bucket: <TEST_BUCKET>
prefix: <TEST_PREFIX
```
Locally ensure that a bind mount set to a folder with GCS ```credentials.json``` along with the environment variable ```GOOGLE_APPLICATION_CREDENTIALS``` set to the container path of those credentials

feat: add google cloud storage (gcs) prefix support [DET-6883]

---

master/internal/job/job.go
master/internal/resourcemanagers/kubernetes/pod_test.go
master/internal/resourcemanagers/task_list.go

One of many small changes coming to make the diff more manageable.

chore: small cleanups for slurm

---

harness/tests/storage/test_gcs.py

Fix an upstream test failure in which I didn't have the credentials set for a gcs test.

fix: gcs storage upstream test failure

---

master/static/srv/proto_get_trials_plus.sql

it is what it is [DET-7471]
[DET-7471]: https://determinedai.atlassian.net/browse/DET-7471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: make trials table sort properly

---

CONTRIBUTING.md
webui/react/Makefile
webui/react/package.json

We don't support node 17 or higher yet due to our web package dependencies.

chore: update docs to accurate node support

---

webui/react/src/components/InteractiveTable.tsx
webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx

left one `any` for now, maybe try to get rid of it before merge.
not needed, only changed types

chore: reduce use of any in InteractiveTable

---

webui/react/src/components/LearningCurveChart.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx

allow users to narrow down trials by clicking their checkboxes in trials table below Learning Curve graph
find you a nice multi-trial experiment,e.g. 562
- click some checkboxes, only selected trials should show in the graph
- clear selection, all trials should show
- click some more checkboxes
- change metric, selection should be preserved
- change top trials to show only one
- that top trial should show regarless of whether it was selected
- go back to top trials = 100
- the previously selected trials should show
- go back to top trials =1 (without top trial being selected)
- click the checkbox for that single trial
- go back to top trials = 100
- just that single trial should show up
preferably also test with multi-trial experiment that is in progress??
See [Release …

feat: show only selected trials in learning curve

---

webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/NavigationTabbar.tsx
webui/react/src/hooks/useModal/useJupyterLabModal.stories.tsx
webui/react/src/hooks/useModal/useJupyterLabModal.test.tsx
webui/react/src/hooks/useModal/useJupyterLabModal.tsx
webui/react/src/hooks/useModal/useModalExperimentCreate.test.tsx
webui/react/src/hooks/useModal/useModalExperimentCreate.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/TrialDetails/TrialDetailsHeader.tsx
webui/react/src/storybook/shared/generateTestExperiments.ts

fix: enable Full Configuration in appropriate modals [DET-7495]
Currently the `Show Full Configuration` option for `useJupyterLabModal` and `useModalExperimentCreate` does not function correctly due to `useTheme` changes. This PR includes updates to how the modal is instantiated as well as adds an additional test cases which should help catch this bug in the future. 
1. Open the Launch JupyterLab modal.
2. Click `Show Full Config` 
3. The modal should function as expected.
4. Try to Fork an Experiment.
5. Ensure you can view the Full Configuration version of the modal. …

fix: enable Full Configuration in appropriate modals [DET-7495]

---

webui/react/Makefile

Node v16.17+ will fail. Update to handle up to v16.29.
Largest minor release seems to be `v10.24.x` so far. It's possibly but seems unlikely for node v16 to go beyond v16.29.

chore: widen node version detection to 16.29

---

agent/internal/agent.go
agent/internal/container.go
agent/internal/containers.go
docs/release-notes/agent-messaging-fault-tolerance.txt
e2e_tests/tests/command/test_run.py
master/internal/command/command.go
master/internal/resourcemanagers/agent/agent.go
master/internal/resourcemanagers/agent/agent_state.go
master/internal/resourcemanagers/kubernetes/pod.go
master/internal/sproto/resources.go
master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go
master/internal/task/resources_list.go
master/pkg/aproto/exit.go
master/pkg/model/task.go

This change ensures signals are never left without a response, except in the case they may be dropped on a websocket, and for this case retries are added.

chore: ensure container terminations aren't lost in the event of network failures [DET-7440, DET-7441]

---

e2e_tests/tests/experiment/test_launch.py

ci: fix log message grepped for by test_launch_layer_cifar

---

master/internal/command/command.go
master/internal/core_experiment.go
master/internal/experiment.go

There has been a mix of asks and tells in the actor, so the safe play is to check if the sender is expecting a response. This currently is done to the priority and weight messages, which are the job messages that have a chance of originating outside of the jobs actor.

chore: stamp out unexpected messages [DET-7492]

---

harness/setup.py

harness has azure-core and azure-storage-blob as dependencies.  The two packages are both a part of https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core and should have the same pinning to prevent version mismatch.  

fix: harness dependency clash fore azure

---

docs/release-notes/4304-fix-task-badge-limit.txt
webui/react/src/components/Badge.module.scss
webui/react/src/components/TaskCard.tsx

The limit should only be applied to task ids that come in the form of UUID and not experiment ids.
Example of experiment id of 10000 truncated to 1000.

fix: remove limit of length 4 for task id

---

.circleci/config.yml
e2e_tests/tests/cluster/test_master_restart.py

By popular demand.
The test hasn't been leaving agent in a good state so it needed some extra poking.

ci: use parallelism for `test-e2e-managed-devcluster`.

---

harness/setup.py

azure-core and azore-storage-blob have different version lineages.  changing version for azure-storage-blob to be the one corresponding to azure-core 1.23

fix: harness azure dependencies

---

docs/release-notes.txt
docs/release-notes/4257-which.txt
docs/release-notes/4286-passthru.txt
docs/release-notes/4288-version.txt
docs/release-notes/4304-fix-task-badge-limit.txt
docs/release-notes/agent-messaging-fault-tolerance.txt
docs/release-notes/checkpoint-prefix.txt
docs/release-notes/delete-delete-failed-experiments.txt
docs/release-notes/det-deploy-no-prompt-yes.txt
docs/release-notes/det-experiment-logs.txt
docs/release-notes/fix-agent-panic-command-env-var-configs-config.txt
docs/release-notes/fix-cant-cancel-agent-master-con.txt
docs/release-notes/fix-rendezvous-timeout-message.txt
docs/release-notes/fix-task-logs.txt
docs/release-notes/gcs-checkpoint-prefix.txt
docs/release-notes/helm-enable-prom.txt
docs/release-notes/incremental-resource-release.txt
docs/release-notes/secure-pprof-endpoints.txt
docs/release-notes/task-logs-improvement.txt

docs: add release notes for 0.18.2

---

.github/CODEOWNERS

Add an initial codeowners file
Make another PR later to the .github directory and ensure that PR is assigned to the team specified in the file
This is just an initial file which will get expanded over time.  Seems closest related to the ci category.  Maybe docs. :shrug: 

ci: codeowners

---

agent/.goreleaser.yml
master/.goreleaser.yml

Restrict access to the master.yaml and agent.yaml files to the user/owner only.

chore: Restrict access to master.yaml and agent.yaml to the user/owner only.

---

webui/react/src/components/ResourcePoolCard.module.scss
webui/react/src/components/ResourcePoolCard.tsx
webui/react/src/components/ResourcePoolCardLight.tsx
webui/react/src/components/ResourcePoolDetails.tsx
webui/react/src/hooks/useTheme.ts
webui/react/src/pages/ResourcepoolDetail.tsx

https://github.com/determined-ai/shared-web/pull/10
adjusted size:
old

chore: update cloud icons [DET-7160]

---

harness/determined/cli/command.py
master/internal/sproto/task.go
master/internal/task/allocation.go
webui/react/src/ioTypes.ts

Minor fix for the slurm resource manager.

chore: idempotent container running messages [DET-7555]

---

e2e_tests/tests/deploy/test_local.py

Tests repeatably enabling and disabling agents and adding and deleting existing agents.
Run locally (ensure you have docker images built locally) 
And verify works in this PR. 

feat: stress test for agent enable/disable and reconnect spam [DET-6733]

---

master/pkg/archive/archive.go
master/pkg/archive/archive_test.go

One of many small changes coming to make the diff more manageable.

chore: Merge Slurm-infrastructure support changes archive

---

master/internal/resourcemanagers/job.go

Merge in new access methods needed by Slurm RM.
Merge in new access methods needed by Slurm RM.

chore: Merge Slurm-infrastructure support changes job.go

---

master/static/srv/task-logging-setup.sh

One of many small changes coming to make the diff more manageable.

chore: Update task logging setup [FOUNDENG-81] (#290)

---

master/internal/experiment.go

With slurm there may be no checkpoints to gc and if so we end up with a error back from the checkpoint_gc.py script since no argument is provided to the --delete.
Manually tested with metric_maker on casablanca-login which hits this case, and verified we do invoke the cleanup if there are any checkpoints to be removed.

fix: Do not fail if no checkpoints to gc [FOUNDENG-83, DET-7548]

---

webui/react/src/components/LearningCurveChart.tsx
webui/react/src/components/UPlot/UPlotScatter.tsx
webui/react/src/components/UPlot/UPlotScatter/UPlotScatter.utils.ts
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/ExperimentVisualizationFilters.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx

Fixes an immediate issue with building webui on master branch.

fix: Import Scale from correct location

---

master/internal/trial.go

One of many small changes coming to make the diff more manageable.
Add Slurm-specific non-retryable error identification.

chore: Merge Slurm-infrastructure support changes trial

---

harness/determined/core/_context.py

Useful to find out why a hung trial is hung, when you forgot to run it
with debug=true.
- Run a long-running training
- docker exec into the container
- ps aux to find a determined.exec.harness process
- `kill -SIGUSR1 THEPID`
- check for a stacktrace in trial logs

feat: install a SIGUSR1 signal handler to print stacktraces

---

webui/react/src/utils/experiment.ts

The `Continue Trial` button shows up for single trial experiments when the experiment hasn't had the chance to actually start the 1 trial, so the `numTrials` end up being 0. This leads to a blank modal since there isn't any trial info available to continue off of.

fix: hide continue trial for experiments with 0 or more than 1 trial

---

webui/react/src/hooks/useModal/useModalExperimentCreate.tsx

PROBLEM:
For `Continue Trial`, the current form will submit and create an experiment even when the `max length` field is left empty (despite being required).

fix: default max length properly to undefined

---

webui/react/src/components/PageHeaderFoldable.module.scss
webui/react/src/components/PageHeaderFoldable.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceDelete.tsx
webui/react/src/hooks/useModal/useModalExperimentMove.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/ProjectDetails/ProjectDetailsTabs.module.scss
webui/react/src/pages/ProjectDetails/ProjectDetailsTabs.tsx
webui/react/src/pages/WorkspaceList.module.scss
webui/react/src/pages/WorkspaceList.tsx
webui/react/src/shared/components/PageHeader/PageHeader.tsx

- Adding empty state to workspaces list
- Don't have autocomplete on Delete Workspace modal
- Don't show Project picker in Move Experiment modal if Uncategorized is selected
- Fix Experiment Details overflow actions
- Dismiss Move Experiment notification on click
- Remove redundant Move Experiment confirmation

fix: various workspaces fixes

---

harness/determined/deploy/local/cluster_utils.py

fix: mac errors for det deploy local --agent-config-path

---

webui/react/src/pages/ProjectDetails.tsx

fix: only call move API for permissioned experiments

---

webui/react/src/components/NavigationSideBar.module.scss
webui/react/src/hooks/useModal/Project/useModalProjectCreate.tsx
webui/react/src/hooks/useModal/Project/useModalProjectEdit.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceCreate.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceEdit.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.tsx
webui/react/src/services/apiConfig.ts
webui/react/src/shared/utils/string.ts

This PR trims whitespace from workspace and project names, as well as re-expanding long pinned workspace names after the navbar is collapsed and re-expanded [DET-7390] [DET-7747].
[DET-7390]: https://determinedai.atlassian.net/browse/DET-7390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-7747]: https://determinedai.atlassian.net/browse/DET-7747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: trim workspace and project name whitespace [DET-7390] [DET-7747]

---

docs/concepts/index.txt
docs/sysadmin-basics/index.txt
docs/sysadmin-basics/workspaces.txt

docs: workspaces docs

---

webui/react/src/shared/.circleci/config.yml

pulling from the shared-web module into core
using subtree is not as straghtforward as we
want but pushing from core is closer to its
final shape so I move the changes to here.
original pr showing the ci change:
https://github.com/determined-ai/shared-web/pull/17

test: update ci job for testing shared-code

---

.circleci/config.yml

react unit tests are hitting the memory limit ceiling and that seems to be affecting the tester. 
https://app.circleci.com/pipelines/github/determined-ai/determined/23907/workflows/efa84a30-61bf-4454-993b-23ed9e9de25b/jobs/770678/resources
bumping the resources seems to help
https://determined-ai.slack.com/archives/CKQ3EV0G6/p1656609733904379

chore: bump the resources on react tests

---

e2e_tests/tests/cluster/test_agent_restart.py

The test has been flaky, it's plausible it's just the timeouts. Run shorter command for 20 seconds instead of 30, to speed up the test a bit in a best case, and increase the timeout to 40 seconds.

test: tweak `test_agent_reconnect_keep_experiment` test timeouts.

---

webui/react/src/components/InlineEditor.module.scss

chore: fix react fmt

---

webui/react/src/components/Metadata/EditableMetadata.test.tsx

UPDATE:
Ran this multiple times (about a dozen times on CircleCI) and did not encounter a failure during those runs.
PROBLEM:
There seems to be a timing issue where the dropdown option of `Delete Row` doesn't exist yet when `user.click()` is getting called. There is a slight animation of displaying the dropdown, so under high load, the animation could possibly be delayed.
SOLUTION:
Change the `getBy...` UI element finders to `findBy...` equivalent (which are basically combination of `waitFor` and `getBy...` that wait for element to exist).

test: fix editable metadata test flake [DET-7782]

---

docs/release-notes/task-container-env-defaults.txt
docs/sysadmin-basics/cluster-config.txt
master/internal/resourcemanagers/kubernetes/spec_test.go
master/pkg/model/defaults.go
master/pkg/model/experiment_config_test.go
master/pkg/model/task_container_defaults.go
master/pkg/model/task_container_defaults_test.go
master/pkg/schemas/expconf/environment_config.go

Environment variables are now in task_container_defaults.
Setup master config with task_container_defaults
```yaml
task_container_defaults:
- test_a=task_container_defaults
- test_b=task_container_defaults
- test_c=task_container_defaults
```
Then create a file named template.yaml
```yaml
environment:
- test_b=template
- test_c=template
```
Create the template
```
det tpl set tpl ../template.yaml
```
Run this command
```bash
det cmd run --template=test --config="environment.environment_variables=['test_c=expconf']" "printenv | grep test"
```
and verify the output is
```
[2022-07-06T16:30:29.240274Z] f8065628 || test_a=task_container_defaults
[2022-07-06T16:30:29.240279Z] f8065628 || test_b=template
[2022-07-06T16:30:29.240280Z] f8065628 || …
```

feat: environment_variables in task_container_defaults [DET-7638]

---

web
webui/react/Makefile
webui/react/src/shared/bin/test.py

- fix a tester error regarding an implicit submodule update from get-deps messing with the final code
- add cli arg to set repo-hash for the destination repo
- symlink /web to /webui/react (we like this route we can the webui/react to here later)
- add helpers for working with shared code

chore: add helpers for working with shared-code

---

CONTRIBUTING.md

This PR includes the suggestions put forward in https://github.com/determined-ai/determined/issues/4481 for improving the build experience.
It also includes steps for building Determined using Homebrew, which is portable across Linux distros and macOS.
The steps were tested on Ubuntu 22.04 and Rocky Linux 8.
See https://github.com/determined-ai/determined/issues/4481 for additional notes.
- [N/A] User-facing API changes need the "User-facing API Change" label.
- [N/A] Release notes should be added as a separate file under `docs/release-notes/`.
- [N/A] Licenses should be included for new code which was copied and/or modified from any external code.

docs: minor improvements and Homebrew build instructions

---

webui/react/src/shared/utils/datetime.test.ts

PROBLEM:
tests dealing with local time is failing because the local time conversion doesn't take Daylight Savings Time difference into account.
SOLUTION:
use native `dayjs.local()` to automatically handle DST

test: fix local time tests [DET-7449]

---

webui/react/Makefile
webui/react/src/shared/.circleci/config.yml
webui/react/src/shared/.github/pull_request_template.md
webui/react/src/shared/bin/test.py

fix push-shared target branch check
add changes introduced here https://github.com/determined-ai/shared-web/pull/20

test: set up shared web to test also with local strategy

---

docs/training-apis/experiment-config.txt
harness/determined/common/schemas/expconf/_gen.py
harness/determined/common/schemas/expconf/_v0.py
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/searcher-custom.json
schemas/expconf/v0/searcher.json
schemas/test_cases/v0/searchers.yaml

Add `name` as authorized value for searcher.

feat: new searcher name custom in experiment config

---

webui/react/src/shared/components/Avatar/Avatar.tsx
webui/react/src/shared/types.ts
webui/react/src/shared/utils/string.ts

- fix a bug with trimming displayName to initials
- props option to render the avatar az square
- option to disable the dynamic bg color feature
here to support https://github.com/determined-ai/saas/pull/212

feat: add square and noColor props to avatar component

---

webui/react/src/components/UPlot/UPlotChart.module.scss
webui/react/src/components/UPlot/UPlotChart.tsx

style: add uplot cursor styles for dark mode [DET-7505]

---

e2e_tests/tests/experiment/experiment.py

This should address failing `test_priortity_scheduler_noop_experiment` test.
N/A - Test fix.

test: `set_priority` should respect the master url.

---

master/internal/core.go

gzip compression shortens loading time for web assets, but newer versions of tensorboard don't support it. workaround is to only skip gzip compression for proxy paths.

fix: skip gzip only for proxy web assets [DET-7802]

---

webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.module.scss

- [DET-7180]
Verify that text color and background color is consistent in dark and light mode on `Hyperparameter` tab on `TrialDetails.tsx`.
Removed box shadow because @trentwatt told me to remove it.
cc: @alexjdetermined 
[DET-7180]: https://determinedai.atlassian.net/browse/DET-7180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: text color in Hyperparameters page

---

webui/react/src/components/UserAvatar.test.tsx
webui/react/src/components/UserAvatar.tsx
webui/react/src/shared/components/Avatar/Avatar.test.tsx

Replacement PR for [this](https://github.com/determined-ai/determined/pull/4516)
Update tests to remove test warnings such as...
```
PASS  src/shared/components/Avatar/Avatar.test.tsx (6.303 s)
● Console
console.error
Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 
at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:67:30)
at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:43:5)
at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1034:9)
at node_modules/react-dom/cjs/react-dom-test-utils.development.js:1073:13
```
[DET-1234]: …

test: update avatar tests to remove warnings

---

webui/react/src/components/Metadata/EditableMetadata.test.tsx

UPDATE: Going to try to resolve this again [one more time](https://github.com/determined-ai/determined/pull/4534) before resorting to skipping.
Disabling the 3rd EditableMetadata sub test for now due to flakyness still persist after an attempt to fix it. Disable for now until the flake is addressed.

test: disable flaky test for now

---

webui/react/src/pages/TaskList.settings.ts

[DET-7812]
Verify `short ID` and `Type` text won't overlap when changing the short ID width manually
[DET-7812]: https://determinedai.atlassian.net/browse/DET-7812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change `short ID` width

---

webui/react/src/hooks/useModal/Checkpoint/useModalCheckpoint.module.scss

[DET-7815]
Verify scroll bar is not on text in the Modal page
[DET-7815]: https://determinedai.atlassian.net/browse/DET-7815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: scroll bar overlap

---

web
webui/react/src/components/SlotAllocationBar.tsx

Current functionality
- hovering on the allocation bar shows all possible states
Desired updated functionality
- Legend only shows values represented currently in the allocation bar (i.e. if there are only “running” slots, then you would only see “running” instead of also seeing pending, warm, potential, etc

feat: update allocation bar legend logic [DET-7683]

---

webui/react/src/pages/ProjectDetails.tsx

[DET-7776]
1. Click `Uncategorized` tab in the side bar
1. Check the title on the tab
So far I just changed tab title because changing all file names and variables are too much.
[DET-7776]: https://determinedai.atlassian.net/browse/DET-7776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: rename window title

---

webui/react/src/components/InlineEditor.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelDetails/ModelHeader.tsx
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/WorkspaceDetails.tsx

[DET-7556]
- Check description placeholder is blank when the item is archived.
- Also check description placeholder is visible when the item is NOT archived.
You can find these placeholders in `Uncategorized` tab, experience in `Workspace` tab and so on...
I assumed when disable variable is passed to `InlineEditor` component, all placeholder should be blank.
Is it right? @trentwatt 
[DET-7556]: https://determinedai.atlassian.net/browse/DET-7556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide description placeholder when archived

---

docs/release-notes/fix-allocation-end-times-on-restore-failure.txt
master/internal/task/allocation.go
master/static/migrations/20220714191840_fixup-allocation-endtimes.tx.down.sql
master/static/migrations/20220714191840_fixup-allocation-endtimes.tx.up.sql

fix: correct allocation end times when it is set on restoration failure

---

webui/react/src/pages/ExperimentComparison/CompareVisualization.tsx

chore: remove activemetric duplication [DET-7737]
The `Visualization` component currently uses both `activeMetric` and `filter.metric` to control certain aspects of the component which can be both confusing and error prone. This update removes `activeMetric`  so all logic is now based on the `filters`
[DET-7737]: https://determinedai.atlassian.net/browse/DET-7737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove activemetric duplication [DET-7737]

---

e2e_tests/tests/cluster/test_priority_scheduler.py

fix: increase time to wait for command in priority scheduler
Fix in test.

fix: increase time to wait for command in priority scheduler test

---

docs/release-notes.txt
docs/release-notes/4493-model-def.txt
docs/release-notes/task-container-env-defaults.txt

docs: add release notes for 0.18.4

---

harness/determined/pytorch/deepspeed/_deepspeed_trial.py

Remove duplicated list_file calls for shared fs.  This can caused stale file handle issues for high slot trials.
Run e2e deepspeed tests.

perf: improve deepspeed checkpointing for sharedfs

---

.circleci/config.yml

Using a custom-built image that has all tooling and runtimes we install in our CI jobs to speed up workflows that run use `docker-image` instead of `machine-image`. The image is created from [this Dockerfile](https://github.com/determined-ai/determined-ci-images/blob/main/cimg-base/Dockerfile). Part of the plan is also migrating any jobs using `machine-image` runners to `docker-image` runners where possible to take advantage of the speed-up as well.
Will be running pipeline as part of pushing the branch as final check for the changes made.
The image defined in that separate repo will be redefined within the mono repo in a later commit, including the GHA workflow that builds and publishes it.
[DET-1234]: …

ci: switch to custom-built container image

---

.github/workflows/scan-docker-images.yml
.grype.yaml

Looking to migrate our CircleCI workflow that scans our docker images weekly against a locally-deployed anchor engine into a GHA workflow that uses another anchore tool: [Grype](https://github.com/anchore/grype#specifying-matches-to-ignore). Having read over the script we currently run, it seems like we can have the same functionality (including ignoring specific CVEs) using the grype action.
Doing some testing locally with `act`, but ultimately, I'll be trusting what the actual output of the job is when run from an actual runner. Before merging in this change, I'll be removing the `pull_request` trigger from the workflow definition.
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYx …

ci(scan-docker-images): migrate to gha

---

webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/TaskList.tsx

feat: remove reset column widths button [DET-7675]
The `Reset Widths` button has been removed.
1. Ensure the `Reset Widths` button has been removed from the Task List page. 
2.. Ensure the `Reset Widths` button has been removed from the Model Registry page. 
[DET-7675]: https://determinedai.atlassian.net/browse/DET-7675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove reset column widths button [DET-7675]

---

webui/react/src/components/ActionSheet.tsx
webui/react/src/components/Json.tsx
webui/react/src/components/PageMessage.tsx
webui/react/src/components/SlotAllocationBar.tsx
webui/react/src/components/UPlot/SyncableBounds.tsx
webui/react/src/components/UPlot/UPlotChart.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpoint.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpointRegister.tsx
webui/react/src/hooks/useModal/Columns/useModalColumnsCustomize.tsx
webui/react/src/hooks/useSettings.ts
webui/react/src/omnibar/tree-extension/utils.ts
webui/react/src/pages/Clusters/ClustersQueuedChart.tsx
webui/react/src/pages/ExperimentComparison.tsx
webui/react/src/pages/ExperimentComparison/CompareVisualization.tsx
webui/react/src/pages/InteractiveTask.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/ResourcepoolDetail.tsx
webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx
webui/react/src/routes/utils.ts
webui/react/src/services/decoder.test.ts
webui/react/src/services/utils.ts
webui/react/src/shared/configs/eslintrc.js
webui/react/src/shared/utils/storage.ts

Apply [keyword-spacing rule](https://eslint.org/docs/latest/rules/keyword-spacing).

chore: eslint keyword spacing

---

.github/CODEOWNERS

Add docs team to codeowners
N/A
Self-explanatory

chore: add docs to codeowners

---

webui/react/src/pages/WorkspaceDetails.tsx

[DET-7827]
- Check if there is no key warning in  project list in workspace tab
When I tried to a make duplicate name project, I got an error that says I can't make duplicate name. I believe name is a good candidate for key
[DET-7827]: https://determinedai.atlassian.net/browse/DET-7827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: missing `key` for rows

---

webui/react/src/components/InteractiveTable.module.scss

[DET-7840]
Check that there is no double scroll bars in all `InteractiveTable` when scrolling table
[DET-7077]: https://determinedai.atlassian.net/browse/DET-7077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-7840]: https://determinedai.atlassian.net/browse/DET-7840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: double scroll bar

---

.github/CODEOWNERS

Narrow down `agent/` to `agent/internal` as an attempt to cut down the number of `agent/go.mod` notifications I get from dependabot.

chore: tweak ilia's CODEOWNERS.

---

.circleci/config.yml

Currently, all long-running jobs are only manually triggerable. We still
want this to be the case, but because of a lack of integration between
GH status checks and CircleCI pipeline reporting, we can't specify what
subset of the `test-e2e` job is okay not to run.
As a workaround, we're moving those manually-runnable jobs into a
separate workflow that'll be initiated the same as the current
`test-e2e` workflow, but will be marked as entirely optional for status
checks on PRs to the monorepo. This allows us to not have to circumvent
branch protections for PRs that don't require running those manual jobs.
Make a PR and verify that both `test-e2e` and `test-e2e-longrunning` are correctly configured by CircleCI.
[DET-1234]: …

ci(test-e2e): move optional jobs into own workflow

---

.bumpversion.cfg
.github/workflows/test-cli.yml

Migrating test-cli CircleCI workflow into an independent GHA workflow as
part of general migration out of CircleCI. The steps are pretty much the
same with the following differences from the current CircleCI workflow:
- test-cli will now run all tests across both Windows and Ubuntu for
each Python version
- the test environment is entirely setup with just Python and pip -- no
conda installation of anything
Run workflow in both CircleCI and GHA with a PR and double-check output for differences.

ci(test-cli): migrate to gha workflow

---

harness/determined/common/api/bindings.py
master/internal/api_user.go
master/static/srv/get_users.sql
proto/src/determined/api/v1/user.proto
webui/react/src/services/api-ts-sdk/api.ts
webui/react/src/services/apiConfig.ts

Modify get users API: 
- add support for `sortBy`
- add support for `orderBy` (asc / desc)
- add support for `offset` and `limit`

feat: add sort and order to users api [DET-7828]

---

docs/sysadmin-basics/cluster-config.txt

docs: update description of telemetry reporting

---

.github/CODEOWNERS
.github/pull_request_template.md

until we figure out the saas git authorization
to run the test in ci we ask people this way to
run the test manually.

test: add checklist for testing shared changes

---

.github/workflows/lint-secrets.yml

Pretty much making a 1:1 translation of the lint-secrets job without any
functional changes. If after a few days of working with the new workflow
shows no issues or differences in operation to the current lint-secrets
workflow, then we can just delete the CircleCI workflow.
Make PR and check results of scan job.

ci(lint-secrets): migrate to gha workflow

---

.github/workflows/lint-react.yml

Just another 1:1 translation of a CircleCI workflow. If after a few days
of running side-by-side, there aren't any issues, we can delete the
current CircleCI workflow.
Make PR and check job outputs. If the job runs successfully, I'll also be re-running the workflow to see if the cache gets picked up for `node_modules`.

ci(lint-react): migrate to gha workflow

---

docs/index.rst

Fix landing page tile text overflow.

docs: shorten landing page tile descriptions

---

webui/react/src/pages/Clusters.tsx
webui/react/src/pages/ProjectDetails/ProjectDetailsTabs.module.scss
webui/react/src/pages/TrialDetails.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.module.scss
webui/react/src/shared/styles/antd.scss

Headers and tabs had unbalanced spacing. Minor tweaks to make them more consistent and move spacings to where appropriate.
BEFORE:
AFTER:

style: fix spacing for tabs and headers [DET-7823]

---

e2e_tests/tests/nightly/compute_stats.py

fix: flaky test caused by compare stats [DET-7838]

---

webui/react/src/pages/TrialDetails.tsx
webui/react/src/shared/types.ts

to track whether the associated api has been initialized or not
used for 
https://github.com/determined-ai/saas/pull/224/files?show-viewed-files=true&file-filters%5B%5D=

chore: add attr to track api state has been initialized

---

docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/7465-model-definition-file-cache.txt

docs: model definition file cache

---

.circleci/config.yml

Using CircleCI's Contexts for use in our jobs makes them inaccessible
for execution in fork PRs. We really just want the values used in the
`determined-ci` context (DET_SEGMENT_*_KEY) to be accessible for use but
not scraping by web scrapers, so I've added those "secrets" as
environment variables for the `determined` project and removed the use
of the context.
Make PR and let CI run.

ci(circleci): remove determined-ci context ref

---

.circleci/config.yml
webui/react/src/shared/bin/test.py

adds `intg-test` that checks out saas and tests saas web
test pr against this branch:
- [#4616 upstream branch with shared changes](https://github.com/determined-ai/determined/pull/4616): should fail because it breaks saas tests [yep](https://app.circleci.com/pipelines/github/determined-ai/determined/24792/workflows/5f6feea2-8fb0-4c25-99f4-22a89b7b286c/jobs/805118) ✅
- [#4617 fork branch with shared changes](https://github.com/determined-ai/determined/pull/4617): should fail due to lack of CI permissions-- requires PR from upstream branch [yep](https://app.circleci.com/pipelines/github/determined-ai/determined/24791/workflows/d47eb68e-1e00-493b-a6a9-69fc7a091339/jobs/805081) ✅
- [#4618 fork branch w/o shared changes](https://github.com/determined-ai/determined/pull/4618): should pass …

ci: test downstream

---

webui/react/src/App.tsx
webui/react/src/omnibar/Omnibar.tsx
webui/react/src/omnibar/tree-extension/index.ts
webui/react/src/omnibar/tree-extension/trees/actions.tsx
webui/react/src/omnibar/tree-extension/trees/dev.ts
webui/react/src/omnibar/tree-extension/trees/goto.ts

implement the missing closeBar feature. 
keep the previous command on close
improve omnibar action error handling
I've found myself wanting the omnibar to close after a successful command execution. 

chore: implement closeBar feature for omnibar

---

.github/workflows/lint-docs.yml

Recreating lint-docs jobs in GHA 1:1. Will delete CircleCI job after a
week or so of having both running simultaneously.
Make a PR and check workflow outputs.

ci(lint-docs): migrate to gha workflow

---

webui/react/src/components/Metadata/EditableMetadata.test.tsx
webui/react/src/components/Metadata/EditableRow.tsx

Fixes a flaky test. Latest version of test in this PR passed CI 4/4 times tested.

test: fix EditableMetadata test flake

---

webui/react/src/shared/hooks/useModal/useModal.tsx

chore: allow setting context type for useModal

---

master/internal/api_user.go
master/static/srv/set_user_display_name.sql
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/NavigationTabbar.tsx
webui/react/src/components/UserAvatar.test.tsx
webui/react/src/hooks/useFetch.ts
webui/react/src/pages/Settings.tsx
webui/react/src/pages/Settings/UserManagement.module.scss
webui/react/src/pages/Settings/UserManagement.settings.ts
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/routes/routes.ts
webui/react/src/routes/utils.ts
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts
webui/react/src/shared/types.ts
webui/react/src/types.ts

Access user management list view by `/det/settings/user-management?rbac=1`
Preview here: http://ec2-35-85-252-218.us-west-2.compute.amazonaws.com:8080/det/settings/user-management?rbac=1

feat: User management list view [DET-7796]

---

.circleci/config.yml

e2e-test is usually the longest running workflow. cut it from 35min to 8min.
the idea is that the skipped tests do not test changes introduced in /webui
more context: https://determined-ai.slack.com/archives/CT01QS70Q/p1653505930158909

build: skip det-deploy-local for webui only changes

---

master/internal/db/postgres.go

Adds a function that passes offsets, limits, and other options to bun, else falling back to defaults.

feat: support pagination in bun

---

harness/determined/common/api/bindings.py
master/pkg/model/experiment.go
master/pkg/searcher/asha.go
master/pkg/searcher/asha_stopping.go
master/pkg/searcher/custom_search.go
master/pkg/searcher/custom_search_test.go
master/pkg/searcher/search_method.go
master/pkg/searcher/searcher.go
master/pkg/searcher/tournament.go
master/pkg/searcher/util_test.go
proto/src/determined/experiment/v1/searcher.proto
webui/react/src/services/api-ts-sdk/api.ts

feat: custom unit tests, add/change a few other things [DET-7717]
No testing required. 
[DET-7717]: https://determinedai.atlassian.net/browse/DET-7717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: custom searcher unit tests, add/change minor things [DET-7717]

---

webui/react/src/components/Table.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelVersionDetails.tsx
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
webui/react/src/routes/routes.ts

[DET-7888] [DET-7848]
- Check if we can update name, node, metadata, and description. Even after refresh the page, the updated data should be there.  Also, we can route to the version page property
[DET-7888]: https://determinedai.atlassian.net/browse/DET-7888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-7848]: https://determinedai.atlassian.net/browse/DET-7848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: model deital bugs

---

webui/react/src/shared/styles/antd.scss

Had to [reopen PR](https://github.com/determined-ai/determined/pull/4629) because branch name was too long and prevented `test-e2e-longrunning`

style: fix disabled primary button style

---

webui/react/src/shared/components/AvatarCard/AvatarCard.module.scss

style: fix avatar card with long names

---

.circleci/config.yml
harness/determined/_trial_controller.py
harness/determined/cli/experiment.py
harness/determined/core/_distributed.py
harness/determined/horovod.py
harness/determined/pytorch/_experimental.py
harness/determined/pytorch/_pytorch_context.py
harness/determined/pytorch/_pytorch_trial.py
harness/tests/experiment/fixtures/pytorch_onevar_model.py
harness/tests/experiment/fixtures/pytorch_xor_model.py
harness/tests/experiment/keras/test_tf_keras_trial.py
harness/tests/experiment/pytorch/test_deepspeed_trial.py
harness/tests/experiment/pytorch/test_pytorch_context.py
harness/tests/experiment/pytorch/test_pytorch_trial.py
harness/tests/experiment/test_local.py
harness/tests/experiment/utils.py
harness/tests/test_imports.py

Improve/add automated tests of code in and related to `_pytorch_context.py` and `_pytorch_trial.py`, especially that which utilizes GPUs, Apex, and/or AMP; also especially with concern for expanding code coverage. [DET-7761] [DET-7763]
Automated tests should pass, of course.
Code coverage is expected to improve overall, albeit modestly. Some code has been removed or marked to be skipped in coverage reports.
There is much more work to be done on these parts of the code, but this particular PR is being closed because it has become stale.
[DET-7761]: …

chore: test improvement for _pytorch_context and _pytorch_trial [DET-7761] [DET-7763]

---

webui/react/src/components/ResponsiveTable.tsx
webui/react/src/hooks/useSettings.test.tsx
webui/react/src/hooks/useSettings.ts
webui/react/src/pages/JobQueue/JobQueue.tsx

UPDATE: There is a separate issue of the pagination happening on the backend but the filtering happening on the frontend. This will be addressed separately.
The table pagination buttons and page size picker on the resource pool job queue tabs do not work.
https://user-images.githubusercontent.com/220971/179803401-2d1721cb-0f93-4e2e-888c-8d21c8f07d8d.mov
Also related, the user settings hook is making calls to the use settings API but not currently handling errors.

fix: update resource pool job queues to paginate properly

---

webui/react/src/pages/Settings.tsx

Need to wait for user management to wrap up before exposing the settings tabs.

chore: temporarily hide user management

---

.github/workflows/lint-go.yml

Direct translation of the current CircleCI job into a GHA job. After
running both for a week, if the results don't differ, we can delete the
CircleCI job.
Make PR and check output of both CircleCI and GHA workflows.

ci(lint-go): migrate to gha workflow

---

.github/workflows/lint-bindings.yml

Replicating both the check-py-bindings and check-ts-bindings jobs from
the CircleCI workflow as a GHA workflow. While some repetition is
starting to become evident as there are now multiple workflows defining
similar dev environment configurations, it makes sense to start creating
reuse units (either reusable workflows or composite actions). That said,
this should be put off until all the lint workflows exist as GHA
workflows to ensure full coverage when refactoring.
Create PR and compare output of both CircleCI and GHA's `lint-{ts,py}-bindings` jobs.

ci(lint-bindings): migrate to gha workflow

---

webui/react/src/shared/utils/set.test.ts

Unit tests for the functions in `shared/utils/set`

test: utils/set unit tests [DET-7904]

---

codecov.yml
webui/react/README.md

Current webui/react codecov badge shows and links to the entire repo. Instead, restrict the coverage to webui/react only.
Easiest way to test this is to go each of the respective urls and make sure they resolve correctly.

chore: update codecov badge to reflect web only

---

e2e_tests/tests/experiment/test_custom_searcher.py
harness/determined/searcher/search_runner.py

RandomSearch implemented as CustomSearch method (according to [random.go](https://github.com/determined-ai/determined/blob/custom-searcher/master/pkg/searcher/random.go)). [DET-7884](https://determinedai.atlassian.net/browse/DET-7884)
This test should perform 5 trials (max_trials=5), 2 trials at a time (max_concurrent_trials=2).

test: RandomSearch implemented as CustomSearch [DET-7884]

---

master/internal/api_user.go
master/internal/db/postgres_users.go
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.test.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/pages/Settings.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

Add create user support in web UI. 
Fix routing [issue](https://determinedai.atlassian.net/browse/DET-7925) while hiding rbac implementation. 
Navigate to `/det/settings/user-management/rbac-enable` and click on `New User` button to create couple new users. 

feat: Create user UI [DET-7847]

---

webui/react/src/hooks/useModal/Model/useModalModelVersionDelete.tsx
webui/react/src/pages/ModelVersionDetails.tsx
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx

I found a minor bug in ModelVersionDeital.tsx which is about router issue.
`/det` is a env variable so removed it. However, I noticed the code is not used at all, so removed. 
Also, after deleting the version, it originally routes to the model list instead of model detail. I think it's unnatural so change it to model detail after deletion
Check if it would route to the model detail page after deleting the version

refactor: remove unused code in model version detail page

---

webui/react/Makefile
webui/react/src/shared/utils/Logger.test.ts

test: add unit tests for logger class [DET-7901]

---

webui/react/src/shared/components/Icon/Icon.stories.tsx
webui/react/src/shared/components/Icon/Icon.tsx
webui/react/src/shared/components/Icon/icon.test.tsx

[DET-7897]
- Check all test cases are valid and theres no missing test cases
- Pass CI test
- I couldn't test `title` due to the lack of element somehow. 
- Also, I wanted to test icon's content in pseudo-element, but so far no way to access it. Testing name of icon would be a bit useless test cases for now because of it.
[DET-7897]: https://determinedai.atlassian.net/browse/DET-7897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add test cases for `Icon.tsx`

---

harness/determined/common/api/bindings.py
master/internal/api_user.go
master/internal/user/authz_basic_impl.go
master/internal/user/authz_iface.go
master/internal/user/authz_unrestricted_impl.go
proto/src/determined/user/v1/user.proto
webui/react/src/services/api-ts-sdk/api.ts

Add patch user logic (activate/deactivate, admin, set agent user group) to grpc server. 
These APIs will be used by webUI user list page.

feat: migrate patch user logic to grpc server [DET-7909]

---

webui/react/src/shared/components/Image/Image.test.tsx
webui/react/src/shared/components/Image/Image.tsx

[DET-7898]
- Check if all test cases are meaningful, and not miss anything for test cases
[DET-7898]: https://determinedai.atlassian.net/browse/DET-7898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add test cases for `Image.tsx`

---

.bumpversion.cfg
.github/workflows/lint-python.yml

Replicating the current lint-python CircleCI job as a GHA workflow. One
difference is that the GHA one runs all check tasks simultaneously.
Part of this also involves updating the bumpversion config so that it
uses a glob for all GHA workflows instead of just the single test-cli
workflow file.
Make a PR and compare output of CircleCI and GHA workflows.

ci(lint-python): migrate to gha workflow

---

webui/react/src/shared/components/ActionDropdown/ActionDropdown.test.tsx

test: create interaction tests for action dropdown [DET-7895]
[DET-7859]: https://determinedai.atlassian.net/browse/DET-7859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-7895]: https://determinedai.atlassian.net/browse/DET-7895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: create interaction tests for action dropdown [DET-7895]

---

webui/react/src/shared/utils/string.test.ts

[DET-7944]
- Check if there's nothing missing for test cases
[DET-7944]: https://determinedai.atlassian.net/browse/DET-7944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add test cases for `string.ts`

---

webui/react/src/pages/Settings/SettingsAccount.tsx
webui/react/src/shared/components/Avatar/Avatar.module.scss
webui/react/src/shared/components/Avatar/Avatar.tsx

SaaS needs support for large avatar. Change Core large to extra-large instead and take the size as a prop.

chore: support enum sizes for avatar

---

webui/react/src/shared/components/ActionDropdown/ActionDropdown.test.tsx

Follow up for #4684
Check if these changes are valid

refactor: test cases for `ActionDropdown`

---

webui/react/src/shared/components/Page/Page.test.tsx

Interaction tests for `shared/components/Page/Page.tsx`

test: WebUI interaction test for page [DET-7894]

---

docs/cluster-setup-guide/deploy-cluster/index.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/overview.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/singularity.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst
docs/cluster-setup-guide/elasticsearch-logging-backend.rst
docs/reference/reference-deploy/config/master-config-reference.rst
docs/reference/reference-training/experiment-config-reference.rst

docs: port slurm deployment to oss docs

---

docs/reference/rest-api.rst
docs/training/model-management/model-registry-org.rst

docs: add rest api reference link and rewrite rest api doc

---

webui/react/src/ee/SamlAuth.test.ts
webui/react/src/ee/SamlAuth.ts

Add unit test coverage SAML Auth.

test: add samlauth tests [DET-7946]

---

harness/determined/common/api/bindings.py
proto/src/determined/api/v1/user.proto
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.test.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/services/api-ts-sdk/api.ts
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

Implement user actions (Edit, activate/deactivate) from user list page.
Navigate to `/det/settings/user-management/rbac-enabled` and edit users.

feat: WebUI edit user [DET-7846]

---

webui/react/src/shared/utils/service.ts

fix: mark all 4xx failures as auth failure

---

docs/assets/styles/determined.css
docs/index.rst

Update new doc tiles to use theme CSS variables.
BEFORE:
AFTER:

style: fix doc tile styling (dark mode support and responsive) [DET-7955]

---

.github/workflows/lint-go.yml
.github/workflows/lint-python.yml
.github/workflows/lint-react.yml
.github/workflows/test-cli.yml

test: update path conditionals for gh workflows

---

webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/TaskList.tsx

[DET-7307]
- Check if selected items will be cleared when clear filter in experiment table and task table
The Jira ticket says experiment table but I found the same behavior in task table so applied it as well
[DET-7307]: https://determinedai.atlassian.net/browse/DET-7307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: clear selected item when clear filters

---

webui/react/src/components/InteractiveTable.tsx
webui/react/src/pages/WorkspaceList.settings.ts
webui/react/src/pages/WorkspaceList.tsx

Fix workspace table view pagination. Bug details here: https://determinedai.atlassian.net/browse/DET-7927
Verify that interactive table pagination works as expected. (i.e. workspace list table, user list table)

fix: WebUI workspace pagination [DET-7927]

---

master/pkg/searcher/searcher.go

fix: shutdown operation [DET_7920]
No tests required.

fix: shutdown operation [DET-7920]

---

webui/react/src/components/InlineEditor.module.scss
webui/react/src/components/InlineEditor.stories.tsx
webui/react/src/components/InlineEditor.test.tsx
webui/react/src/components/InlineEditor.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/Settings/SettingsAccount.tsx
webui/react/src/shared/components/AvatarCard/AvatarCard.module.scss
webui/react/src/shared/components/AvatarCard/AvatarCard.test.tsx

- [DET-7914]
-  Cannot ignore keydown event until the IME is confirmed
- Description in uncategorized table has no limit but the one in experiment detail has 500 letters limit
- `isDarkOn` is deprecated in `InlineEditor` 
- Check if `InlineEditor` works as extected
- Check if description in uncategorized table has 500 letters limit
- Check if display name in settings has 32 letters limit
- Check if display name is ellipt when its too long
- Check if IME ignores keydown event until the IME is confirmed
[DET-7914]: https://determinedai.atlassian.net/browse/DET-7914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-1234]: …

fix: resolve issues around `InlineEditor` [DET-7914]

---

webui/react/src/shared/styles/antd.scss

[DET-7991]
- Check if text color is suitable in experiment detail and model detail page in both light and dark mode
[DET-7991]: https://determinedai.atlassian.net/browse/DET-7991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: breadcrumb text color

---

e2e_tests/tests/experiment/test_custom_searcher.py
harness/determined/common/schemas/expconf/_gen.py
harness/determined/common/schemas/expconf/_v0.py
master/pkg/schemas/expconf/searcher_config.go
master/pkg/schemas/expconf/zgen_custom_config_v0.go
master/pkg/schemas/zgen_schemas.go
master/pkg/searcher/custom_search_test.go
schemas/expconf/v0/searcher-custom.json

fix: Remove max length

---

webui/react/src/hooks/useModal/Model/useModalModelCreate.tsx
webui/react/src/hooks/useModal/Model/useModalModelDownload.tsx

style: fix modal padding [DET-7993]

---

webui/react/src/shared/utils/routes.test.ts

- fix typo of test
- All tests should pass

fix: hardcode pathname instead of using `paths`

---

webui/react/src/components/PageHeaderFoldable.module.scss
webui/react/src/components/PageHeaderFoldable.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss
webui/react/src/pages/TrialDetails/Header/TrialHeaderLeft.tsx

Fix two style issues:
1. Handle smaller mobile header sizes better
2. Fix trial state color (fix to show white instead of grey)
BEFORE:
AFTER:

style: fix mobile exp header [DET-7975]

---

webui/react/src/shared/utils/service.ts

moved from https://github.com/determined-ai/determined/pull/4736 since this should have been an upstream branch

fix: fix an issue with forbidden api actions causing logout

---

docs/release-notes/concurrent-grid.rst

Add a release note for 2c575fd9 (#4719).

docs: add release note for fix for searcher early termination bug

---

webui/react/src/components/Dropdown.stories.tsx
webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/Metadata/EditableRow.tsx
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/PageHeaderFoldable.tsx
webui/react/src/components/PaginatedNotesCard.tsx
webui/react/src/components/TableFilterDropdown.tsx
webui/react/src/components/TableFilterSearch.tsx
webui/react/src/components/TagList.tsx
webui/react/src/components/TaskActionDropdown.tsx
webui/react/src/components/TaskBar.tsx
webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
webui/react/src/pages/ModelDetails/ModelHeader.tsx
webui/react/src/pages/ModelDetails/ModelVersionActionDropdown.tsx
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/pages/WorkspaceDetails/ProjectActionDropdown.tsx
webui/react/src/pages/WorkspaceList/WorkspaceActionDropdown.tsx
webui/react/src/shared/components/ActionDropdown/ActionDropdown.tsx

[DET-7990]
- Check if all menus work as expected
[DET-7990]: https://determinedai.atlassian.net/browse/DET-7990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [Ant Design] replace old menu with new menu

---

helm/charts/determined/templates/change-password.yaml

On Openshift/OKD, the current working directory isn't necessarily
writable by the pod running the utility container.
Signed-off-by: Burt Holzman <burt@fnal.gov>

fix: Write change-password script in /tmp instead of CWD

---

.bumpversion.cfg
.github/workflows/lint-python.yml
.github/workflows/test-cli.yml

Instead of hard-coding version strings in workflows, read the VERSION file and set an env var for that.
Run the workflows?

ci: unversion workflows

---

.circleci/config.yml
e2e_tests/tests/cluster/test_logging.py
master/internal/api_shell.go

Shells erroneously required a non-empty "data" field to decide to generate keys.
It is totally unclear to me why only now this started breaking.. but uh.

ci: shells should generate keys, even with empty 'data' field

---

.github/CODEOWNERS

ci: remove trent from shared codeowners

---

webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx

Open HP Search and change `Units` to something different than it starts as. Click `Select Hyperparameters` and `Run Experiment`. HP Search should start without any errors.

fix: allow changing max_length units in HP Search

---

e2e_tests/tests/cluster/test_logging.py

I wanted GKE tests enabled for a large change I was making, but while they were out of commission, they rotted. I fixed them on another branch and forgot to revert flipping this test off on my main branch, oops.

ci: re-enable test fixed by earlier commit

---

docs/release-notes.rst
docs/release-notes/4458-hyperparameter-search.txt
docs/release-notes/4500-new-pytorchtrial-deepspeedtrial-callbacks.txt
docs/release-notes/4745-fix-sdk.txt

docs: add release notes for 0.19.1

---

bindings/Makefile

https://github.com/swagger-api/swagger-codegen/compare/v2.4.14...v2.4.27

chore: upgrade the generator from 2.4.14 to 2.4.27

---

webui/react/src/shared/components/AvatarCard/AvatarCard.tsx

for https://github.com/determined-ai/saas/pull/286

chore: expose Avatar props through AvatarCard

---

webui/react/src/services/utils.ts
webui/react/src/shared/utils/service.test.ts
webui/react/src/shared/utils/service.ts

added test for `utils/service` [DET-7903]
[DET-7903]: https://determinedai.atlassian.net/browse/DET-7903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add tests for utils/service

---

webui/react/src/shared/bin/test.py

[DET-7934]
@keita-determined  couldn't clone with the previous url without a PAT
[DET-7934]: https://determinedai.atlassian.net/browse/DET-7934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update saas git url

---

webui/react/src/hooks/useModal/Checkpoint/useModalCheckpointRegister.tsx

Go to the experiment details page with the network inspector open. There shouldn't be a call to `/api/v1/models?...` until and unless you open the Checkpoint modal and then the Register Checkpoint modal. Register Checkpoint modal should still work as expected.

refactor: reduce unneeded api calls [DET-7451]

---

e2e_tests/mypy.ini
model_hub/mypy.ini

mypy tests for model hub started failing when run with harness installed via `pip install -e harness` from the requirements.txt file.  installing in editable mode prevented mypy from finding determined stubs unless we modified mypy path to include the harness directory.  this will make sure `make check` tests will pass when developing locally and modifying `harness` code in editable mode. 
i haven't fixed the underlying issue which is we reinstall determined in editable mode into the python venv used for ci after installing determined from wheel.  there is also the issue of duplicated github actions tests and our standard circleci workflows.  
[DET-1234]: …

fix: lint-python ci failure

---

docs/release-notes/137-feat-slurm.txt

Add Slurm support release note to oss, as it hasn't shown up
ever in the release notes.

docs: Add release note for Slurm feature

---

webui/react/src/shared/utils/service.test.ts
webui/react/src/shared/utils/service.ts

fix: remove core external dependency from shared

---

webui/react/src/pages/ProjectDetails.tsx

fix: use correct experiment list offset when deleting an experiment [DET-7880]
Currently, the table `offset` is not correctly updated when an experiment is deleted. We want to re-calculate the correct offset if the current offset is greater than or equal to the total number of items in the table. 
1. Navigate to the experiments list and navigate to the last page of experiments.
2. Delete or Archive all the experiments on the last page. 
3. After deleting the last experiment on the last page, the table to automatically show the previously second to last page. 
[DET-7880]: https://determinedai.atlassian.net/browse/DET-7880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

fix: use correct experiment list offset when deleting an experiment [DET-7880]

---

webui/react/src/components/SlotAllocation.module.scss
webui/react/src/pages/ResourcepoolDetail.tsx

[DET-8052]
- Check if tab routes to the `Queued` and `Scheduled` tab when button in the resource pool header is clicked
[DET-8052]: https://determinedai.atlassian.net/browse/DET-8052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: tab routing issue in resource pool

---

master/pkg/model/user.go
webui/react/src/hooks/useModal/UserSettings/useModalCreateGroup.test.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateGroup.tsx
webui/react/src/hooks/useModal/UserSettings/useModalDeleteGroup.test.tsx
webui/react/src/hooks/useModal/UserSettings/useModalDeleteGroup.tsx
webui/react/src/pages/Settings/GroupManagement.module.scss
webui/react/src/pages/Settings/GroupManagement.settings.ts
webui/react/src/pages/Settings/GroupManagement.tsx
webui/react/src/pages/Settings/Settings.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

Implement group list page in Web UI. 
Navigate to `/det/settings/group-management/rbac-enabled`, create/edit/delete several groups.

feat: WebUI group list page [DET-7921, DET-7976]

---

webui/react/src/components/NavigationSideBar.tsx

Use jupyter icon instead of plus icon in navigation side bar when collapse.
Before:
After:

fix: use jupyter icon in navigation sidebar [DET-7097] 

---

webui/react/src/hooks/useModal/JupyterLab/useModalJupyterLab.tsx

[DET-8041]
- Check if JupyterLab modal won't pop up after launching Jupyter and moving to different page in nav bar such as Model Registry
[DET-8041]: https://determinedai.atlassian.net/browse/DET-8041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: jupyterLab modal poping issue

---

harness/determined/common/api/bindings.py
master/internal/job/job.go
proto/src/determined/api/v1/job.proto
webui/react/src/hooks/useSettings.ts
webui/react/src/pages/JobQueue/JobQueue.settings.ts
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/ResourcepoolDetail.tsx
webui/react/src/services/api-ts-sdk/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts

[DET-7841] [DET-7842]
- adds filtering by state on the API side for pagination
- updates webui to use those filters
- modifies `useSettings` to take a parameter that makes them only apply on certain routes
- uses that parameter to make sure settings for different job queue table to not affect the others
create a bunch of jobs at once by spamming `det e create`. this should result in a bunch of Queued jobs and a few active jobs.
- The jobs should all be displayed properly in their respective tabs
- the pagination in each tab should work correctly
- it should not be possible to mess anything up by navigating back and forth between tabs (except that the pagination will be reset)
see PR comments
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/READM …

fix: job queue pagination

---

webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/pages/WorkspaceList.tsx

On the Workspaces List page all workspaces should be shown in grid view, even if the table limit in list view is smaller than the total number. Same for the Projects List/Workspace Details page.

fix: grid view on Workspaces and Projects pages show all items [DET-8031]

---

webui/react/src/shared/styles/antd.scss

BEFORE:
AFTER:
- open 1-click HP search modal
- select a searcher type
- change one of the HP to `Log` type
- set min to `-3` and set max to `-5`
- verify that the input fields render ok both light and dark mode

style: update number input error style for dark mode [DET-8039]

---

harness/determined/deploy/aws/aws.py

I don't see a reason to explicitly stop the master instance on stack
updates: if UserData is being changed, the instance will be restarted
by cloudformation anyway.

fix: speed up `det deploy aws` stack updates.

---

webui/react/src/pages/ModelDetails/ModelHeader.tsx
webui/react/src/pages/ModelRegistry.tsx

[DET-8072]
- Check if admin have `delete` option in all model in Model Registry and Model Detail
- Check if user is not admin, the user can only delete model the user made
[DET-8072]: https://determinedai.atlassian.net/browse/DET-8072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide `Delete` button if user is not a creator or admin

---

webui/react/src/pages/JobQueue/JobQueue.settings.ts
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/ResourcepoolDetail.tsx
webui/react/src/routes/routes.ts

[DET-8069]
1. Go to Resource Pool Details/ Job Queue page
2. Change (any) column width
3. Width should not "reset" to previous state after a few seconds
4. Change width using handle between "Weight" and "Submitted" columns
5. Page shouldn't crash or throw error in console
[DET-8069]: https://determinedai.atlassian.net/browse/DET-8069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: correct job queue table bugs [DET-8069]

---

master/internal/experiment.go
master/pkg/searcher/custom_search_test.go
master/pkg/searcher/custom_searcher_events_queue.go

fix: remove under the given event id for correct resumption in client.

fix: remove under the given event id for correct resumption in client.

---

.github/workflows/publish-helm.yml

The quotes areout "true" were breaking the workflow.
The others are just not needed.
Run the workflow

ci: Remove unnecessary quotes [INFENG-1]

---

webui/react/src/hooks/useSettings.ts

- [DET-8051]
- 139 calls -> 8 calls in `Uncategorized` page on my local (94% reduction) (It depends on the page)
- Check if user setting api call is reduced, especially in `Uncategorized` page
- Check if user setting works as expected
[DET-8051]: https://determinedai.atlassian.net/browse/DET-8051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

perf: reduce user settings api call

---

e2e_tests/tests/experiment/test_custom_searcher.py

ASHA implemented as a Custom Searcher method (following asha.go).
Test should perform 16 trials in 3 rungs with the max length of 3000 batches (187, 750 and 3000) batches. All trials should be marked as completed, same as experiment.

test: asha as custom searcher method [DET-8013]

---

webui/react/src/pages/Settings/UserManagement.test.tsx
webui/react/src/pages/Settings/UserManagement.tsx

Add webUI test for user management.
Verify all tests passed. 

test: webui user management unit test [DET-7968]

---

.github/pull_request_template.md

Extremely tiny change adding a single checkbox to the PR template.
N/A
Jointly decided per internal process review meeting

docs: Add a checkbox to the PR template

---

.github/workflows/publish-helm.yml

Add missing token
Add missing line continuation character
Fix a ton of other errors :D
Been tested a fair amount from the branch.  It works. :)
Don't look at how many dumb mistakes I made.  I'm actually competent, I promise! :stuck_out_tongue: 

ci: fix helm repo [INFENG-1]

---

.circleci/config.yml

Fix failing `test-cli-win` and update a dated circleci orb for windows. 
Windows-specific hacks don't seem to be necessary any more.

ci: fix test-cli-win.

---

webui/react/src/shared/.circleci/config.yml

same as core
we run the same tests in the shared-web repo and react unit tests can be affected when they're resource constrained
please also checkout https://github.com/determined-ai/saas/pull/310

build: set shared web to use xlarge resource class

---

e2e_tests/tests/cluster/test_agent_restart.py
master/internal/db/postgres_tasks.go

We had a bug where, because allocations and trials are on different threads and the trial table rows are written lazily, trial run id and rows in the allocation table could get out of sync, which would cause us to attempt to rewrite allocation rows on restart that already existed. The change just makes the DB write a bit more lenient, for now.
This is a little non-ideal but much simpler than the alternative for now. In a follow up, I'm going to probably remove trial run ID altogether and make trial table saves not lazy.

fix: make allocation saves idempotent [DET-7953]

---

e2e_tests/tests/nightly/test_capability.py
e2e_tests/tests/nightly/test_distributed.py

We removed the non-model-hub mmdetection example but did not remove the associated e2e tests.  Removing them here so nightly tests won't fail.  

fix: remove non-model-hub mmdet tests

---

webui/react/src/pages/ModelRegistry.tsx

[DET-8084]
- Check if there is only 1 loading animation in Model Registry when fetching data
[DET-8084]: https://determinedai.atlassian.net/browse/DET-8084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove duplicate loading animation

---

webui/react/src/components/Table.module.scss
webui/react/src/components/Table.tsx

https://user-images.githubusercontent.com/109113616/185510971-36930232-21db-4437-9ecd-25943f0f17f8.mov
- Text shouldnt be out of screen when the name is too long

fix: fit long name in Model Register

---

master/internal/rm/resource_pool.go

fix: rps should correctly ignore job msgs not meant for them [DET-8214]

---

webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/shared/utils/error.ts
webui/react/src/utils/job.ts

issues: 
- move to top
- move job to position number N
cause: computing how to move a job to an arbitrary position requires the full list of jobs. previously this was fine as the ui was always working with full list of jobs but we started breaking down the jobs and didn't see this issue.
- TODO repro with release cluster
watch out for https://github.com/determined-ai/determined/pull/4756 . the changes here are set in a way that allow that pr to go through without having to build additional endpoints for now

fix: allow moving jobs to top without assuming the full job list [DET-8015]

---

docs/release-notes/set_gc_policy_fix.txt
e2e_tests/tests/cluster/test_checkpoints.py
harness/determined/cli/experiment.py
master/internal/core_experiment.go
master/internal/db/postgres_checkpoints.go
master/internal/db/postgres_checkpoints_intg_test.go
master/internal/db/postgres_helpers_intg_test.go
master/internal/db/postgres_trial.go

fix: set gc policy [DET-8018]
Tested in e2e and integration tests. 
[DET-8018]: https://determinedai.atlassian.net/browse/DET-8018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: set gc policy [DET-8018]

---

webui/react/src/shared/components/ActionDropdown/ActionDropdown.tsx

chore: preserve failed action's error msg

---

e2e_tests/tests/cluster/test_checkpoints.py

fix: remove subprocess unused import from e2e_tests/cluster/test_checkpoints.py

fix: remove subprocess import

---

harness/determined/pytorch/README.md
harness/determined/pytorch/_pytorch_trial.py

The code was written correctly the first time, but this information was nearly lost and we almost chose to break it.
This is a great time to add a comment.

chore: document reasons for scaler.update()

---

e2e_tests/tests/experiment/test_custom_searcher.py
harness/determined/searcher/core_search_runner.py
harness/determined/searcher/search_method.py
harness/determined/searcher/search_runner.py
master/internal/experiment.go
master/pkg/searcher/custom_search_test.go
master/pkg/searcher/custom_searcher_events_queue.go

Save operations and reorder posting and saving of operations and state to avoid having to replay events when restarting a crashed/stopped SearchRunner.
Note: because of the reordering we no longer have to keep the last processed event in the event queue on the master, and so I reverted that change (going back to `RemoveUpTo`).
We can consider this in scope for https://determinedai.atlassian.net/browse/DET-7826

feat: Save operations

---

.circleci/config.yml

we keep hitting our concurrency limit for running jobs on circleci
whats the point of ...-longrunning on non-upstream branchs? everything is already tested in the non-longruning workflow

build: avoid double testing through e2e-longrunning

---

master/pkg/aproto/defaults.go

When testing with TLS, we found the `tls.vhost` configuration for Fluent Bit HTTP outputs does not work as it did before, causing Fluent Bit to fail with TLS errors.
🤷 

fix: downgrade fluentbit to fix tls.vhost issues

---

webui/react/src/pages/TrialsComparison/Actions/useModalTagTrials.tsx
webui/react/src/pages/TrialsComparison/Actions/useTrialActions.tsx
webui/react/src/pages/TrialsComparison/Collections/useTrialCollections.tsx
webui/react/src/pages/TrialsComparison/Table/tagsRenderer.tsx
webui/react/src/pages/TrialsComparison/Trials/useFetchTrials.ts
webui/react/src/pages/TrialsComparison/TrialsComparison.tsx

resolve some staleness

---

docs/conf.py

Currently, the "TensorFlow Keras Fashion MNIST Tutorial" page gets automatically re-directed to the "PyTorch MNIST Tutorial" page, making the former tutorial inaccessible.  Delete the re-direct and restore user access to the TF tutorial.  
Go to the [Tutorials](https://docs.determined.ai/latest/tutorials/index.html) page, click on the "TensorFlow Keras Fashion MNIST Tutorial" and make sure it leads you to the correct tutorial.

docs: remove misleading redirect

---

harness/determined/cli/experiment.py

Since 0.17.12, det e describe has mangled the output of all workloads
from all contained trials together.
This was likely not noticed due to either:
- users not frequently using det e describe, or
- 90% of experiments are single-trials, so maybe those who do use
det e describe didn't happen to need it on a multi-trial experiment.

fix: det e describe with multiple trials

---

webui/react/src/pages/TrialsComparison/Collections/EditButton.tsx
webui/react/src/pages/TrialsComparison/Collections/useTrialCollections.tsx

[DET-8166]
- Check if edit modal appears by clicking and save the collection filter 
[DET-8166]: https://determinedai.atlassian.net/browse/DET-8166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: create edit button

---

webui/react/src/components/CheckpointModalTrigger.tsx
webui/react/src/components/TableBatch.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpoint.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.settings.ts
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.table.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/ExperimentMultiTrialTabs.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts
webui/react/src/types.ts

Adds a Checkpoint tab to Experiment Details page.
Check that checkpoints are listed correctly and that the checkpoint modal can be opened.

feat: experiment checkpoint list [DET-8201] [DET-8129]

---

master/internal/api_trials.go

The workloads API shimmed limit 0 to limit NULL, but `public.page_info` 
does not know how to handle NULL inputs. This changed shims it, 
instead, to the value for "give me everything".

chore: fix limit 0 for /api/v1/trials/:id/workloads

---

master/internal/api_experiment.go
master/internal/api_model.go
master/internal/api_tensorboard.go
master/internal/api_trials.go
master/internal/command/command.go
master/internal/command/command_manager.go
master/internal/command/notebook_manager.go
master/internal/command/shell_manager.go
master/internal/command/tensorboard_manager.go
master/internal/db/postgres_checkpoints.go
master/internal/job/job.go
master/internal/rm/fair_share.go
master/internal/rm/fitting_test.go
master/internal/rm/kubernetes/pod.go
master/internal/rm/kubernetes/pods.go
master/internal/rm/kubernetes/request_queue_test.go
master/internal/rm/kubernetes/spec.go
master/internal/rm/priority.go
master/internal/rm/provisioner/provisioner_test.go
master/internal/rm/provisioner/scale_decider.go
master/internal/rm/scheduler_test.go
master/internal/telemetry/reports.go

Set capacity in advance to avoid unnecessary memory allocation 
Check if the change is valid

perf: set memory cap to improve memory allocation

---

webui/react/src/pages/TrialsComparison/Collections/EditButton.tsx
webui/react/src/pages/TrialsComparison/Collections/useModalCreateCollection.tsx
webui/react/src/pages/TrialsComparison/Collections/useTrialCollections.tsx

[DET-8165]
- Check if filters are shown in modal.
- Check if modal validation works
[DET-8165]: https://determinedai.atlassian.net/browse/DET-8165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show filters in collection creation modal

---

webui/react/src/components/Table/InteractiveTable.tsx
webui/react/src/pages/TrialsComparison/Actions/useModalTagTrials.tsx
webui/react/src/pages/TrialsComparison/Collections/useTrialCollections.tsx
webui/react/src/pages/TrialsComparison/Table/tagsRenderer.tsx

[DET-8192]
- Check if all errors are handled 
I manually checked where error handlings are needed, so I probably miss some error handling. 
[DET-8192]: https://determinedai.atlassian.net/browse/DET-8192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add error message

---

webui/react/src/components/Badge.test.tsx
webui/react/src/components/Badge.tsx
webui/react/src/components/BadgeTag.test.tsx
webui/react/src/components/BadgeTag.tsx
webui/react/src/components/CheckpointModalTrigger.tsx
webui/react/src/components/Dropdown.tsx
webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/GalleryModal.tsx
webui/react/src/components/Grid.tsx
webui/react/src/components/Label.tsx
webui/react/src/components/Link.tsx
webui/react/src/components/LoadingWrapper.tsx
webui/react/src/components/OverviewStats.tsx
webui/react/src/components/PageMessage.tsx
webui/react/src/components/Section.tsx
webui/react/src/components/SelectFilter.tsx
webui/react/src/components/Skeleton/SkeletonSection.tsx
webui/react/src/components/TableBatch.tsx
webui/react/src/components/TaskActionDropdown.tsx
webui/react/src/components/TrialLogPreview.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpoint.test.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpoint.tsx
webui/react/src/pages/ModelDetails/ModelVersionActionDropdown.tsx
webui/react/src/pages/WorkspaceDetails/ProjectActionDropdown.tsx
webui/react/src/pages/WorkspaceList/WorkspaceActionDropdown.tsx
webui/react/src/shared/components/Spinner/Spinner.tsx

**This is a PR to prepare for React 18 upgrade**
In React18, `PropsWithChildren` will be removed. 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210
- Check if all test cases pass and all components work as expected

chore: replace `PropsWithChildren` with explicit children declaration 

---

proto/Makefile

Small QoL improvement to check errors in the loop and fail faster.
Successful builds should not be affected; failed builds should have shorter and more readable error output.
I won't be surprised there's some bash or makefile magic to achieve this more efficiently.

chore: proto build should fail on first error.

---

bindings/generate_bindings.py
harness/determined/common/api/bindings.py

Small missed detail in recent refactor.

chore: change import path in generated bindings

---

master/internal/api_workspace.go
master/static/srv/get_workspace_projects.sql
proto/src/determined/api/v1/workspace.proto
webui/react/src/pages/WorkspaceDetails/WorkspaceQuickSearch.tsx
webui/react/src/services/api-ts-sdk/api.ts

This is [the original concern](https://github.com/determined-ai/determined/pull/4837#discussion_r953189179).
When `id=0` is passed in `getWorkspaceProjects`, return all projects at once.
- Check if this PR doesn't break RBAC policy
- Check if `getWorkspaceProjects` works as expected when id = 0 and others

perf: improve `getWorkspaceProjects` api for Quick Search

---

webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/TrialsComparison/Table/TrialTable.tsx
webui/react/src/pages/TrialsComparison/Trials/useFetchTrials.ts
webui/react/src/pages/TrialsComparison/TrialsComparison.tsx
webui/react/src/shared/utils/data.ts

fix: correct metricName aggregation [DET-8163]

---

.github/workflows/link-artifacts.yml

Status events don't trigger workflow runs unless the workflow is defined
in the default branch for the repo. This means that testing this
workflow to iterate on it will require having the workflow merged in
before further iterations.
Get workflow merged in, check the workflow output after being merged, then open a follow-up PR to fix up anything.

ci(link-artifacts): add initial workflow attempt

---

webui/react/src/pages/TrialsComparison/Collections/EditButton.tsx
webui/react/src/pages/TrialsComparison/Collections/useTrialCollections.tsx

- Same width as create modal
- Able to edit collection name as well

chore: add input and same width for edit modal

---

.github/workflows/link-artifacts.yml

Another fix towards actually working.

ci(test-unit): fix debug line to print payload

---

.github/workflows/link-artifacts.yml

ci(test-unit): fix conditional check syntax

---

agent/internal/container.go
agent/internal/containers.go
agent/internal/docker.go

Should fix the race condition in https://determined-ai.slack.com/archives/C02PV33GSN5/p1661376182724349
N/A: no repro.

fix: race condition in agent `container` actor around missing `containerInfo`.

---

.github/workflows/link-artifacts.yml

ci(test-unit): limit runs to only test-e2e updates

---

harness/determined/common/api/bindings.py

Rebase error after landing #4902.

chore: fix rebase error

---

e2e_tests/tests/nightly/test_capability.py
e2e_tests/tests/nightly/test_distributed.py

Updating file names in nightly tests so it stops failing: https://app.circleci.com/pipelines/github/determined-ai/determined/26485/workflows/8caf6089-c94f-43e3-975e-0a84b24245b0/jobs/878154

test: update yaml file names

---

webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.test.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/pages/Settings/Settings.tsx
webui/react/src/pages/Settings/UserManagement.test.tsx
webui/react/src/pages/Settings/UserManagement.tsx

Can optionally select group when adding a user.
Navigates to `/det/settings/user-management/rbac-enabled`
Click `New User` and create several users with and without groups (create groups at group management tab if no groups available)
Navigates to group management tab and verify the result.

feat: Create user with group info [DET-8221]

---

webui/react/src/hooks/useSettings.ts

[DET-8290]
related: #4790
- Check if user settings is applied even in secret mode
My prev change caused this. I'm so dumb 🐛. But still there is a problem which api is called many times. Hopefully react-query will be installed here
[DET-8290]: https://determinedai.atlassian.net/browse/DET-8290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove prevUser constraint

---

webui/react/package-lock.json

npm audit fix
```
< 60 vulnerabilities (2 low, 5 moderate, 40 high, 13 critical)
---
> 51 vulnerabilities (2 low, 5 moderate, 33 high, 11 critical)
```
- walk through the ui to see if anything's out of place
```
7a8
> node_modules/antd-theme-generator/node_modules/har-validator/node_modules/ajv
36,51d36
< ansi-regex  3.0.0 || 4.0.0 - 4.1.0
< Severity: high
< Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
< Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
< fix available via `npm audit fix`
< node_modules/@webpack-contrib/schema-utils/node_modules/ansi-regex
< node_modules/webpack-dev-server/node_modules/cliui/node_modules/ansi-regex
< …
```

chore: address low hanging security updates

---

.github/workflows/link-artifacts.yml

ci(test-unit): flail productively

---

.github/workflows/link-artifacts.yml

ci(test-unit): accept only status events

---

harness/tests/experiment/fixtures/pytorch_onevar_model.py
harness/tests/experiment/pytorch/test_pytorch_trial.py
harness/tests/experiment/utils.py

Test checkpointing and restoring with a simple linear model in an Apex or PyTorch AMP context.
Run unit tests with GPU(s) and with `apex` installed.
Because these tests rely on GPU(s), they are **not currently being run by CircleCI**.

chore: test apex checkpointing [DET-7886]

---

master/internal/api_experiment.go
webui/react/src/utils/experiment.ts

Try to fork an archived experiment. It should be allowed.

fix: allow forking an archived experiment [DET-8277]

---

webui/react/src/components/PageNotFound.module.scss
webui/react/src/components/PageNotFound.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetails.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelVersionDetails.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/TrialDetails.tsx
webui/react/src/pages/WorkspaceDetails.tsx

Use a generic not found page. 
Figma link: https://www.figma.com/file/kqWThAhkfa4giVOwHzrAxA/RBAC-Web?node-id=40%3A14805
Navigates to non-exist assets (i.e. `/det/projects/9` when we only have less than 9 projects.  or similarly `/det/models/9`)
Should see a 404 not found page as shown in figma. 

feat: WebUI 404 not found page [DET-8226]

---

.circleci/config.yml

Moving deepspeed nightly tests from p3 to g4dn instances due to older instruction set on p3 that causes cpu offloading tests to fail.
CI results: https://app.circleci.com/pipelines/github/determined-ai/determined?branch=ds_test_config
Deepspeed tests for offloading works; GPT Neox test failed for unrelated reasons (see [here](https://determined-ai.slack.com/archives/CSG3W08JY/p1662060658901559)).
There are some flaky tests for test_unit and test_e2e.

ci: run deepspeed on g4dn instances

---

e2e_tests/tests/nightly/test_capability.py

Removing deepspeed test from p2 instance.

test: remove ds test from p2

---

.github/workflows/link-artifacts.yml

ci(test-unit): remove debug code

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml

Some people prefer to ask question on GitHub and they tend to use bug issue which isn't appropriate category, so I made a new one for question.
- Check if it looks well in issue page

chore: add question issue on GitHub

---

bindings/generate_bindings.py
harness/determined/common/api/bindings.py

chore: fix a typo in py generator

---

webui/react/src/shared/styles/index.scss
webui/react/src/shared/themes.ts

- [DET-8040]
- Check if scrollbar color matches the theme (system, light, dark) in all pages when hovering
[DET-8040]: https://determinedai.atlassian.net/browse/DET-8040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: adjust scrollbar color by theme

---

webui/react/src/components/Navigation.tsx
webui/react/src/contexts/Store.tsx
webui/react/src/hooks/useFetch.ts
webui/react/src/hooks/useSettings.ts

This should reduce the number of user settings API calls.
Open up the network inspector in Firefox and enter `setting` into the filter box. On an Experiment List page with 10 experiments, number of initial calls should be reduced from ~30 to ~10.

fix: reduce settings api calls [DET-8307]

---

webui/react/src/components/CheckpointModalTrigger.tsx
webui/react/src/components/InteractiveTable.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpoint.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpointDelete.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpointRegister.module.scss
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpointRegister.tsx
webui/react/src/hooks/useModal/Model/useModalModelCreate.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/shared/components/ActionDropdown/ActionDropdown.tsx
webui/react/src/shared/utils/string.test.ts
webui/react/src/shared/utils/string.ts
webui/react/src/types.ts
webui/react/src/utils/checkpoint.ts

Adds ability to batch Register or Delete checkpoints from Experiment Checkpoints table
Go to experiment checkpoints table, attempt to batch register and batch delete checkpoints.

feat: add batch register and deletion of checkpoints from experiment [DET-8130]

---

webui/react/src/shared/utils/service.ts

[DET-8297]
[DET-8297]: https://determinedai.atlassian.net/browse/DET-8297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: recursively unwrap caught exceptions for type checks

---

agent/internal/fluent.go
docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/fluent-k8s-uid
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/internal/rm/kubernetes/pod.go
master/internal/rm/kubernetes/spec.go
master/pkg/fluent/fluent.go

feat: allow specifying Fluent Bit container UID/GID on Kubernetes [DET-8012]

---

webui/react/src/components/InteractiveTable.module.scss
webui/react/src/components/InteractiveTable.tsx
webui/react/src/components/TagList.module.scss
webui/react/src/components/TagList.tsx
webui/react/src/components/TextEditorModal.module.scss
webui/react/src/components/TextEditorModal.tsx
webui/react/src/pages/ProjectDetails.tsx

- I talked to @alexjdetermined about pinned experiments, and have decided that all rows should have the same height to achieve pin feature. In order to do it, I made table row inline
- Its for #4925
https://user-images.githubusercontent.com/109113616/188760128-c725e48e-96df-4a57-a492-c4eeb8e41704.mov
- Check if all rows are inline in table and no issue with it in experiment table
- Check if experiment table view height and row height are fixed as well
- I replaced `InlineEditor` with `Editor modal` in experiment table to do inline.
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

feat: make table row inline

---

docs/index.rst

[DET-8327](https://determinedai.atlassian.net/browse/DET-8327)
The Administrator Guide tile appears twice on the doc index page:

fix: remove duplicate Admin Guide tile DET-8327

---

webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.module.scss
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx

fix: make hp search look good on mobile [DET-8321]

---

webui/react/src/pages/ProjectDetails.tsx

fix an issue where the loading state is taken away prematurely before the table data is updated when
switching projects

fix: remove early loading state resolution [DET-8320]

---

webui/react/src/contexts/Store.tsx

- bring more visibility into Store
- check and prevent detectable unnecessary ref changes
suggestion: review commit by commit
we seem to set a few things 2 to 3 times in a row. (app level rerender?)

chore: reduce and log effective store state changes

---

.circleci/config.yml

ci: gke version bump.

---

.circleci/devcluster/double.devcluster.yaml
e2e_tests/tests/cluster/test_groups.py
harness/determined/cli/__init__.py
harness/determined/cli/_util.py
harness/determined/cli/cli.py
harness/determined/cli/errors.py
harness/determined/cli/user_groups.py
harness/determined/common/api/bindings.py
master/internal/api_master.go
master/internal/config/authz_config.go
master/internal/config/config.go
proto/src/determined/api/v1/master.proto
webui/react/src/services/api-ts-sdk/api.ts

CLI implementation of user groups. 
e2e tests
Along with following ```det user-group -h``` and manually verifying the commands work as expected and that the help makes sense.
Needs #4620 to be merged.

feat: user group CLI and RBAC feature flag [DET-7889,DET-8210]

---

master/internal/grpcutil/auth.go

Motivation is the pattern we have now is we auth the request coming in and for RBAC we then call ```grpc.GetUser``` authing the user a second time. This makes it so for unary requests we just auth once. 
Existing e2e tests.
This does technically change the behavior if you send both an allocation token and a user token
before it would check the allocation token then the user token 
but now it will check the user token then the allocation token 
but either way both shouldn't be sent so don't think it matters.

perf: cache grpcutil.GetUser() result

---

harness/determined/common/schemas/expconf/_gen.py
harness/determined/common/schemas/expconf/_v0.py
master/pkg/model/compat.go
master/pkg/model/environment_config.go
master/pkg/model/task_container_defaults.go
master/pkg/schemas/expconf/environment_config.go
master/pkg/schemas/expconf/zgen_environment_config_v0.go
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/environment.json
schemas/test_cases/v0/defaults.yaml
schemas/test_cases/v0/experiment.yaml
schemas/test_cases/v0/gpu-cuda-migration.yaml

Add pbs configuration in the expconf similar to slurm configuration in the expconf for slurm job.
This will eventually allow additional control over PBS job submission.

chore: Add expconf environment.pbs

---

bindings/generate_bindings.py
e2e_tests/tests/cluster/test_logging.py
e2e_tests/tests/experiment/experiment.py
harness/determined/cli/experiment.py
harness/determined/cli/remote.py
harness/determined/cli/task.py
harness/determined/cli/trial.py
harness/determined/common/api/__init__.py
harness/determined/common/api/bindings.py
harness/determined/common/api/experiment.py
harness/determined/common/api/logs.py

Our logging has great CI already, so existing tests already provide sufficient coverage of refactored code.
After this, we will be able to add log following to the python sdk, which IMO is a big missing feature.
This change overlaps slightly with #4914.  It's unclear if that can land first since we have to track down some user behavior before landing it.

chore: add streaming to bindings and use it

---

docs/release-notes.rst
docs/release-notes/FE127-SlurmROCmSupport.txt
docs/release-notes/FE149-Podman4Support.txt
docs/release-notes/deepspeed-cpu-offloading.txt

docs: add release notes for 0.19.3

---

CONTRIBUTING.md

For EE currently you need at least 3.15 in protoc to use optionals. Figured make this before I forget. 

docs: protoc required version to 3.15 to support optionals

---

webui/react/src/pages/Settings/SettingsAccount.test.tsx

WebUI unit test for settings account

test: WebUI add test for settings account [DET-7967]

---

webui/react/src/components/DeterminedAuth.tsx
webui/react/src/components/Router.tsx
webui/react/src/components/ThemeToggle.tsx
webui/react/src/contexts/Store.tsx
webui/react/src/hooks/usePageVisibility.ts
webui/react/src/hooks/useTheme.ts
webui/react/src/pages/InteractiveTask.tsx
webui/react/src/pages/NoPermissions.tsx
webui/react/src/pages/SignIn.tsx
webui/react/src/pages/Wait.tsx
webui/react/src/shared/components/ActionDropdown/ActionDropdown.tsx
webui/react/src/shared/contexts/UIStore.ts

next step: add an option to fetch UI state without importing the whole store but leaving ui accessible from the main useStore.

chore: split out ui store part 1 [DET-8218]

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst

Update slurm-known-issues with a special case where experiments will fail on a CPU-only cluster.

chore: update slurm-known-issues

---

webui/react/src/shared/styles/icons.scss

The `shell` and `star` icon codes were switched in a recent font update. This updates our icon codes to fix them back. 
1. Open Webui and ensure the shell icon and star icons are rendered correctly. 

fix: update shell and star icons

---

webui/react/src/components/Table.module.scss
webui/react/src/components/Table.tsx
webui/react/src/pages/JobQueue/JobQueue.module.scss
webui/react/src/pages/JobQueue/JobQueue.settings.ts
webui/react/src/pages/JobQueue/JobQueue.table.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/WorkspaceList.tsx

Align table cells to make cells more readable
- Badges or icons shoul align center
- Numeric should align right
- String should be align left

fix: add alignment in tables

---

harness/determined/searcher/search_runner.py

This line of code `client._require_singleton(lambda: None)()` ensures that client singleton is initialized, and it needs to be invoked by CoreSearchRunner (already there) and LocalSearchRunner (added now).

fix: initialize client singleton for LocalSearchRunner

---

webui/react/src/shared/configs/.prettierrc.js

- related #5015
- First add shared config for Prettier
- Referred https://prettier.io/docs/en/configuration.html
- Check if Prettier rule is correct

chore: share `.prettierrc.js`

---

e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/experiment/test_custom_searcher.py
harness/determined/searcher/core_search_runner.py
master/internal/api_experiment.go

[Active state is now represented through a set of substates: Queued, Pulling, Starting and Running.](https://github.com/determined-ai/determined/pull/4420)
This PR addresses that change for Custom Searcher:
* master-side: when experiment is in Active state or any of the Active substates, master continues to get events from searcher event queue. if experiment is in any other state, master returns experiment_inactive event;
* client-side: changes only on pausing experiment when using CoreSearchRunner; added Active substates when checking if experiment is active.
Current tests should pass.
[DET-1234]: https://determinedai.atlassian.net/browse/DET-1234?atlOrigin=eyJpIjoiNWRkNTl …

fix: handle substates of ACTIVE

---

webui/react/src/contexts/Store.tsx
webui/react/src/hooks/useAuthCheck.ts
webui/react/src/utils/browser.test.ts
webui/react/src/utils/browser.ts

DET-8310
I was able to run a patched version of master through Samuel and verified that jupyterlab auth is in place. details in the ticket
~I think this should work as a proof of concept but I want to do it a bit differently with more time. 
the backend sets auth cookie when we login through other methods should it also handle this case or stop setting cookies altogether and leave it to the client~

fix: set auth cookie client side for external flows

---

harness/determined/pytorch/_pytorch_context.py
harness/determined/pytorch/_pytorch_trial.py
harness/tests/experiment/fixtures/pytorch_onevar_model.py
harness/tests/experiment/pytorch/test_pytorch_trial.py

chore: test PyTorch AMP with gradient aggregation [DET-6105]
Run unit tests with a GPU and with `apex` installed.
Because these tests rely on a GPU, they are **not currently being run by CircleCI**.

chore: test PyTorch AMP with gradient aggregation [DET-6105]

---

webui/react/src/components/ExperimentActionDropdown.tsx

[DET-8393]
- check if code handle undefined 
[DET-8393]: https://determinedai.atlassian.net/browse/DET-8393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: handle pin when its not defined

---

.github/workflows/scan-docker-images.yml

In splitting off report generation from image listing, the `checkout` step was not duplicated, which is required for the `upload-sarif` action to work. This commit adds that checkout back in.

ci(scan-docker-images): fix sarif upload job [INFENG-94]

---

.circleci/config.yml

The bum pyzmq build has been fixed upstream.

revert: work around a bum pyzmq build

---

webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/pages/Settings/Settings.tsx
webui/react/src/pages/Settings/UserManagement.tsx

https://determined-ai.slack.com/archives/CKQ3EV0G6/p1663706989991159?thread_ts=1663625872.693039&cid=CKQ3EV0G6

chore: auto fmt

---

determined-helm-chart_0.19.4-rc1.tgz
index.yaml

Unpublish accidental release 0.19.4-rc1
Wing it

Unpublish accidental release 0.19.4-rc1

---

e2e_tests/tests/experiment/experiment.py
harness/determined/exec/prep_container.py

Fix the exception raised when master is not reachable (Exception) -- APIHttpError only happens when call
completes without a successful status response could also be (SSLException, MasterNotFoundException).
This prevents the expected error message from being reported when the master is not reachable.
The initial prep_container was intended to fail reasonably quickly
to enable diagnostics of misconfiguration.   Recent changes
for re-using the common session (DET-8003) settings has caused the initial
communication to retry for more than 30 mins thus defeating the
original intent of prep_container.trial_prep and the error message
it provides.
This change lowers the session retry in prep_container (6 retries with 0.5 backoff -> 64 seconds) to enable the diagnostic message to be posted …

fix: Initial comm failure should provide explaination (FDN-217)

---

examples/computer_vision/efficientdet_pytorch/startup-hook.sh

test_efficientdet_coco_pytorch_const nightly test is failing
https://app.circleci.com/pipelines/github/determined-ai/determined/27433/workflows/db58b8cd-85bc-4b7c-8e62-4bb24a44d4a7/jobs/917416/tests
Dependency chain: `efficientdet-pytorch -> pycocotools>=2.0.2`
On September 16, pycocotools 2.0.5 got published on Pypi. Its `pip install` fails with `_mask.c: No such file or directory` without cython a `.pyx` file does not get compiled into `.c`. The previous version of pycocotools had `_mask.c` included in the distribution.
We have to either install cython or proactively install pycocotools 2.0.4. I chose to install pycocotools 2.0.4.
After approving `request-gpu-nightly` this test passed. Note: another parallel test failed due to a timeout but that is, of course, unrelated. …

fix: test_efficientdet_coco_pytorch_const failing

---

webui/react/src/hooks/useSettings.ts
webui/react/src/pages/ProjectDetails.tsx

Correcting a bug I introduced in useSettings
Go to Uncategorized Experiments page. You should be able to 
- toggle Show Archived switch. 
- switch pages
- sort the table by any sortable column
- add or remove columns using the Customize Columns modal (accessed through Columns button in top right)
- filter by tags, state, or user
All of these changes should persist on refresh.

fix: fix useSettings bug

---

harness/determined/pytorch/_callback.py
harness/determined/pytorch/_data.py
harness/determined/pytorch/_load.py
harness/determined/pytorch/_lr_scheduler.py
harness/determined/pytorch/_metric_utils.py
harness/determined/pytorch/_pytorch_context.py
harness/determined/pytorch/_pytorch_trial.py
harness/determined/pytorch/_reducer.py
harness/determined/pytorch/deepspeed/_deepspeed_context.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/determined/pytorch/lightning/_adapter.py
harness/determined/pytorch/samplers.py
harness/tests/experiment/pytorch/test_pytorch_context.py

chore: remove check from pytorch [MLG-182]
The module `determined.common.check` is do be replaced with case-by-case raising of exceptions (or assertions, in situations where being optimized out will not cause problems in production).
Unit/e2e tests as usual.
[MLG-182]: https://determinedai.atlassian.net/browse/MLG-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove check from pytorch [MLG-182]

---

webui/react/src/hooks/useSettings.ts

consolidates `useSettings` changes from #5011 and #5102 

fix: consolidate useSettings changes

---

webui/react/Makefile
webui/react/src/App.tsx

unrelated the bracket spacing was removed for `[]`  but not for `{}`  maybe we should have included that
lower verbosity level for prettier

chore: include running eslint fix in fmt target

---

.circleci/config.yml

we already skip a few jobs for docs only prs
we should be able extend this to web only prs as well
s sample what currently runs for web only prs (circleci) https://app.circleci.com/pipelines/github/determined-ai/determined/27697
skipped jobs for web only changes:
```
['package-and-push-system-local',
'check-py-bindings',
'test-debian-packaging',
'lint-go',
'build-go',
'test-unit-go',
'test-intg-master',
'test-intg-agent',
'go-coverage',
'lint-python',
'test-unit-harness-cpu',
'test-unit-harness-gpu',
'test-unit-harness-tf2',
'test-unit-storage',
'test-unit-model-hub',
'python-coverage',
'test-examples',
'test-e2e',
'test-e2e-aws',
'test-e2e-gke',
'test-e2e-gke-cuda-11',
'test-det-deploy',
'test-stress']
```
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/rel …

build: skip more jobs for web-only prs

---

webui/react/src/shared/utils/Logger.ts

after (timing info is shown as expected)
before

chore: reuse debugger instance for Logger

---

.github/workflows/labeler.yml
.github/workflows/link-artifacts.yml
.github/workflows/lint-bindings.yml
.github/workflows/lint-go.yml
.github/workflows/publish-helm.yml
.github/workflows/semantic.yml

Using the application instead of the generated token allows for a higher GH API quota and has the side effect of triggering further actions (mostly only relevant on the labeler or page commit actions).
Using the application instead of the generated token allows for a higher GH API quota and has the side effect of triggering further actions (mostly only relevant on the labeler or page commit actions).
Fingers crossed!

ci: Switch to token w/ higher quota [INFENG-100]

---

e2e_tests/tests/experiment/test_custom_searcher.py
e2e_tests/tests/fixtures/custom_searcher/core_api_custom_searcher.py
e2e_tests/tests/fixtures/custom_searcher/searchers.py
examples/custom_search_method/asha_search_method/core_search_runner/run_experiment.py
harness/determined/common/schemas/expconf/_gen.py
harness/determined/layers/_workload_sequencer.py
harness/determined/searcher/__init__.py
harness/determined/searcher/_core_search_runner.py
harness/determined/searcher/_search_method.py
harness/determined/searcher/_search_runner.py
harness/tests/search_methods.py
harness/tests/test_custom_searcher.py
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/searcher.json

This PR aggregates changes in response to Ryan's review comments. I will merge it without reviews.
Apply code layout rules
(https://github.com/rb-determined-ai/pedl/blob/9bd2168ec23fbba866194f3d7d3cfc243d267100/python_code_layout.md) Apply google style guide for imports
(https://google.github.io/styleguide/pyguide.html#22-imports) Remove debug printouts
Add docstrings

fix: address review comments

---

docs/quickstart-mdldev.rst
docs/tutorials/pytorch-mnist-tutorial.rst

Fix OSS user-reported errata:
- https://determined-community.slack.com/archives/CV37XVAGL/p1664247326984189
- https://determined-community.slack.com/archives/CV37XVAGL/p1664273607624219
N/A

docs: fix user-reported errata.

---

webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx

[DET-8490]
- Check if there's no error in the Jira ticket
[DET-8490]: https://determinedai.atlassian.net/browse/DET-8490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: null check

---

docs/Makefile
docs/_templates/page.html

- Bring back broken analytics tags to the docs.
- Also Makefile should respect changes in `*.html`.
Go to the docs page, open the network tab, see if there're requests to google analytics.

docs: bring back analytics.

---

examples/tutorials/core_api/2_checkpoints.py
harness/determined/common/schemas/_auto_init.py
harness/determined/estimator/_estimator_context.py
harness/determined/estimator/_estimator_trial.py
harness/determined/estimator/_reducer.py
harness/determined/keras/_enqueuer.py
harness/determined/pytorch/README.md

fix: doc typos

---

.circleci/config.yml

Of course, I forgot to remove the thing I said I was going to remove.

fix: remove temporary text

---

webui/react/src/components/BreadcrumbBar.tsx
webui/react/src/components/LogViewer/LogViewer.tsx
webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetails.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/ProjectDetails/ProjectDetailsTabs.tsx
webui/react/src/pages/TrialDetails/TrialChart.tsx
webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx

[DET-8026]
- Check if everything works well
- Check if there's no memory leak warnings around experiments list and experiment detail
- referred https://stackoverflow.com/a/65007703
[DET-8026]: https://determinedai.atlassian.net/browse/DET-8026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

perf: fix memory leak warnings

---

e2e_tests/tests/experiment/test_custom_searcher.py
examples/custom_search_method/asha_search_method/asha.py
examples/custom_search_method/asha_search_method/local_search_runner/run_experiment.py
examples/custom_search_method/asha_search_method/utils.py
harness/determined/searcher/_core_search_runner.py
harness/determined/searcher/_search_runner.py

This PR includes two fixes:
1. Fix for pausing/preempting: after experiment is paused; searcher never preempts, but show msg to the user.
2. Fixes for examples after https://github.com/determined-ai/determined/commit/deb6c31e3754db8aee4320f400040216a420a3b9

fix: pausing experiment and examples

---

webui/react/src/shared/themes.ts

In Dark mode, elevation effect looks a bit too much, so adjust the elevation
- Check if elevation looks good in dark mode

fix: adjust elevation for dark mode

---

harness/determined/tensorboard/gcs.py

See Jira for steps on how to patch google.storage to produce these errors.

fix: handle transient GCS errors in Tensorboard upload [DET-8491]

---

harness/determined/common/api/bindings.py
master/internal/rbac/api_rbac.go
master/internal/rbac/api_rbac_stub.go
master/internal/rbac/api_rbac_wrapper.go
proto/src/determined/api/v1/api.proto
proto/src/determined/api/v1/rbac.proto
webui/react/src/services/api-ts-sdk/api.ts

Proto stub for an endpoint to list groups and users assigned to a given workspace.
As long as master builds 

feat: groups and users to workspace proto

---

harness/determined/searcher/_search_runner.py

Report progress after each event that implies that the experiment _progressed_. The review is not necessary since this is addressing a comment on the feature PR; I will merge this after it builds successfully.
@rb-determined-ai noted that trial progress reporting is optional, and if the author of the experiment chooses not to call [report_progress](https://github.com/determined-ai/determined/blob/726fe804c84d8bb98ba09c50edb95d0fd7d8a5e8/harness/determined/core/_searcher.py#L65), the experiment will appear in the UI as 0% complete until the very end. The solution is to add a Progress operation to the operations returned for each event that signals a change in the completeness of an experiment. …

feat: report progress after every event that affects it

---

webui/react/src/hooks/useFeature.ts

We do not want the case that is being removed in this PR. We only want to enable `mock_workspace_members` if the query parameter is present. 

fix: remove workspace members view mock special casing

---

docs/training/hyperparameter/search-methods/hp-custom.rst
e2e_tests/tests/fixtures/custom_searcher/searchers.py
examples/custom_search_method/asha_search_method/asha.py
harness/determined/searcher/_search_method.py
harness/determined/searcher/_search_runner.py
harness/tests/search_methods.py

https://determinedai.atlassian.net/browse/MLG-51
Add train_length (that is already returned by master as part of ValidationCompleted event) to `on_validation_completed` event handler.

feat: pass train_length into on_validation_completed

---

webui/react/src/hooks/useTelemetry.ts

[WEB-455](https://determinedai.atlassian.net/browse/WEB-455) [WEB-457](https://determinedai.atlassian.net/browse/WEB-457)
- `git checkout master`
- `make live` against latest master. 
- http://localhost:3000/det/experiments/1193
- change tabs and refresh page, you should see "unknown error" popup
- checkout this branch
- do same
- you shouldnt see the popups.
there are two deeper causes:
- since the error was passed to `handleError` was specified as an object literal, the properties were ignored [here](https://github.com/determined-ai/determined/blob/master/webui/react/src/shared/utils/error.ts#L88-L100). that code should be changed to handle the case where object literals are passed in with those properties. 
- telemetry is failing to load. @keita-determined mentioned this might have to …

fix: dont show unknown error popups for elemetry

---

webui/react/README.md

- Update Readme to add new lint and format commands
- Check if contents are correct

chore: update readme for web

---

docs/training/hyperparameter/search-methods/hp-custom.rst

Garrett's comments:
> In the template, can we add from determined import searcher to show the user where this module is coming from? (edited) 
> In initial_operations it would be helpful to state that Create, ValidateAfter, etc are all accessed as in searcher.Create, searcher.ValidateAfter, etc. Not obvious what these classes are at the moment

fix: docs to reflect: from determined import searcher

---

examples/custom_search_method/asha_search_method/local_search_runner/README.md
examples/custom_search_method/asha_search_method/remote_search_runner/README.md

Fixed based on Garret's comment https://determined-ai.slack.com/archives/C03M8MBFK1N/p1664980222251119

fix: change core to remote in readme.md

---

harness/determined/pytorch/_pytorch_trial.py

this is a bug. if you call `on_validation_end` or `on_validation_step_end` while using non-horovod backend, the trial errors out. 

fix: check for horovod backend in PyTorchTrial

---

webui/react/src/hooks/usePermissions.ts

https://determinedai.atlassian.net/browse/WEB-514
Before: 
https://user-images.githubusercontent.com/28383080/194177895-bc8a971c-6f06-4b44-b407-9afe52c3f21c.mov
After:
https://user-images.githubusercontent.com/28383080/194178010-1a0d7962-64bf-4ed9-86df-978872d79a98.mov

fix: stop infinite rerender in move experiment modal

---

webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelRegistry.tsx

[WEB-444]
- Check if updating tags doesn't block table UI in model and model version page
- Followed the behavior of project list page 
[WEB-444]: https://determinedai.atlassian.net/browse/WEB-444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove unnecessary loading state in model & model version page

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx
webui/react/src/hooks/useSettings.ts
webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.settings.ts
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/ExperimentTrials.settings.ts
webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
webui/react/src/pages/ProjectDetails.settings.ts
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/ResourcepoolDetail.tsx
webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.settings.ts

All sorting and filters should work, the *first* time you click.
You should be able to paginate around freely.
Selecting checkboxes in e.g. ExperimentList, ExperimentTrials, ExperimentCheckpoints, should not trigger a loading state
resizing/reordering the columns should not trigger a loading state
https://determinedai.atlassian.net/browse/WEB-283
https://determinedai.atlassian.net/browse/WEB-467
https://determinedai.atlassian.net/browse/WEB-465
https://determinedai.atlassian.net/browse/WEB-490

fix: resolve table UI issues

---

webui/react/src/pages/TrialDetails/TrialDetailsOverview.settings.ts

fix: table ui follow up

---

webui/react/src/shared/components/Avatar/Avatar.module.scss

This reverts commit 21e29b8dbb8119baea9d53a800d34cd3b4e97177.
https://determined-ai.slack.com/archives/C03H5KZPU30/p1665091019418839

chore: revert "fix: use theme var in Avatar stylesheet [DET-8237] (#5109)"

---

.circleci/config.yml

https://determined-ai.slack.com/archives/C03JGLKTBEJ/p1664999065557479

ci: only run lint in package-and-push for release workflows.

---

harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/errors.py

fix: fix the error message for auto checkpoint download

---

webui/react/src/components/Router.tsx
webui/react/src/routes/index.tsx
webui/react/src/routes/routes.ts
webui/react/src/shared/types.ts

Previous: #5142
Followed [the instruction](https://github.com/remix-run/react-router/discussions/8753)
What I have done in this PR
- Replace `Switch` with `Routes`
```mermaid
gantt
title Update React-Router-Dom Plan
dateFormat  YYYY-MM-DD
section React-Router v6
Replace hooks                           :a1, 2022-09-28, 3d
Replace Root                             :crit, a2, after a1 , 5d
Wrap up React Router v6         :a3, after a2 , 5d
section React v18
Update to React v18      :b1,  2022-10-12, 5d
```
- Check if all routes work as expected (no blank pages)

chore: new react-router components

---

master/Makefile
master/internal/api_experiment_intg_test.go
master/internal/api_project_intg_test.go
master/internal/api_trials_intg_test.go
master/internal/api_user_intg_test.go
master/internal/api_workspace_intg_test.go
master/internal/cache/cache_intg_test.go
master/internal/core_checkpoint_intg_test.go
master/internal/core_experiment_intg_test.go
master/internal/core_trial_intg_test.go
master/internal/db/postgres_checkpoints_intg_test.go
master/internal/db/postgres_cluster_intg_test.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_helpers_intg_test.go
master/internal/db/postgres_model_intg_test.go
master/internal/db/postgres_tasks_intg_test.go
master/internal/db/postgres_test_utils.go
master/internal/db/postgres_trial_intg_test.go
master/internal/elastic/elastic_intg_testutils.go
master/internal/rm/agent_resource_manager_intg_test.go
master/internal/task/allocation_intg_test.go
master/internal/usergroup/group_intg_test.go
master/internal/webhooks/webhook_intg_test.go
master/pkg/model/test_utils.go
master/test/integration/api/api_checkpoints_test.go
master/test/integration/api/api_trials_test.go
master/test/integration/api/main_test.go
master/test/testutils/fixtures.go

Before ```make -c master check``` didn't have a build tag for our integration tests (agent does have this build tag already for linting). 
Integration test pass. 

test: enables linting for master integration tests

---

master/internal/api_task.go
master/internal/api_tasks.go
master/internal/api_tasks_intg_test.go
master/internal/api_trials.go
master/internal/api_user_intg_test.go
master/internal/db/postgres_experiments.go

Refactors tasks to call authz experiments. 
Integration test and existing end2end tests.

refactor: Authz tasks [DET-8367]

---

webui/react/src/pages/ExperimentDetails/ExperimentDetails.tsx

perf: remove unused getExpValHistory calls

---

docs/release-notes.rst
docs/release-notes/5123-tb-secrets.txt
docs/release-notes/reattach-deadlock.rst
docs/release-notes/workspace-agent-user-groups.txt

docs: add release notes for 0.19.5

---

webui/react/src/components/CheckpointModalTrigger.tsx

[Demo of the original bug](https://www.loom.com/share/72f5b4b689f04a76974154c6801ba920)
1. go to experiment
2. click on a checkpoint flag icon to bring up checkpoint modal
3. click "register checkpoint"
4. click "new model"
5. name the model and hit "create model"
Previous Result
Modal closes and success notification appears that the model was created. (NOTE: the checkpoint was not registered to that model)
Expected Result
After hitting "create model" the user should be returned to the "Register Checkpoint" modal with that new model pre-selected so they can fill out the version info and save the checkpoint.

fix: register checkpoint "new model" workflow [WEB-499]

---

webui/react/src/pages/TrialDetails.tsx

fix: trial workloads sort and filter

---

harness/determined/common/schemas/expconf/_gen.py
harness/determined/common/schemas/expconf/_v0.py
master/pkg/schemas/expconf/experiment_config.go
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/hpc-cluster-pbs.json
schemas/expconf/v0/hpc-cluster-slurm.json
schemas/test_cases/v0/experiment.yaml

Fixing the unit test involved defaulting the batch_args elements to null, which may have implications for dispatcher RM (null pointers). Perhaps there is a better way.

fix: decorate PBS & slurm options with ,omitempty

---

docs/reference/reference-interface/job-config-reference.rst
docs/reference/reference-training/experiment-config-reference.rst
master/pkg/model/command_config.go
master/pkg/tasks/task_command.go

Allow specification of PBS & Slurm options for DAI commands.
Manual testing to verify that the task spec was updated with any specified PBS & Slurm options.:
```
det cmd run --config-file=…
det cmd run --config=slurm.slots_per_node=99
det notebook start --config-file=…
det shell start --config-file=
det tensorboard start 97 --config-file=…
```

chore: PBS & Slurm options for commands

---

docs/training/apis-howto/api-core/checkpoints.rst
docs/training/apis-howto/api-core/distributed.rst
docs/training/apis-howto/api-core/getting-started.rst
docs/training/apis-howto/api-core/hpsearch.rst
docs/training/apis-howto/api-core/metrics.rst
docs/training/apis-howto/api-core/overview.rst
docs/training/apis-howto/api-pytorch-ug.rst
docs/training/apis-howto/overview.rst
docs/training/dtrain-introduction.rst
docs/training/hyperparameter/configure-hp-ranges.rst
docs/training/hyperparameter/handle-trial-errors.rst
docs/training/hyperparameter/hp-constraints-det.rst
docs/training/hyperparameter/instrument-model-code.rst
docs/training/hyperparameter/overview.rst
docs/training/hyperparameter/search-methods/hp-adaptive-asha.rst
docs/training/hyperparameter/search-methods/overview.rst
docs/training/load-model-data.rst
docs/training/setup-guide/custom-env.rst
harness/determined/launch/horovod.py
harness/determined/layers/_workload_sequencer.py
harness/determined/profiler.py
harness/determined/pytorch/_pytorch_trial.py
schemas/README.md

docs: fix fypos, grammar edits for clarification, etc.

docs: fix fypos, grammar edits for clarification, etc.

---

master/internal/db/postgres_snapshots_test.go

fix: lint for intg test

---

webui/react/src/shared/utils/data.test.ts
webui/react/src/shared/utils/data.ts
webui/react/src/utils/experiment.test.ts

Fix the following error due to updating react-router-dom verison
```
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'loginRedirect')
at data.ts:121:50
at Array.every (<anonymous>)
at k (data.ts:121:26)
at SignIn.tsx:75:29
at Fu (react-dom.production.min.js:262:359)
at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
at $o (react-dom.production.min.js:122:325)
at Au (react-dom.production.min.js:261:308)
at yu (react-dom.production.min.js:243:50)
at react-dom.production.min.js:123:115
sc @ react-dom.production.min.js:216
data.ts:121 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'loginRedirect')
at data.ts:121:50
at Array.every (<anonymous>)
at k (data.ts:121:26)
at SignIn.tsx:75:29
at Fu …
```

fix: fix getPath

---

.git-blame-ignore-revs
webui/react/src/pages/SignIn.tsx

prevent git-submodule to subtree migration commit from showing up in git blame history
- take out an unnecessary use of getPath

chore: add to git blame ignore

---

webui/react/src/pages/SignIn.tsx

remove an instance of unnecessary getPath usage
this has caused an issue that was really about an issue with getPath that's fixed separately

chore: remove unnecessary getPath usage

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/core_experiment.go
master/internal/core_experiment_intg_test.go
master/internal/project/authz_basic_impl.go

Create experiment had a esoteric so made
Integration test.
Previously, when submitting an experiment w/o project (i.e. into default project) while not having access to the default project, the error returned is `Failed to create experiment: unable to find parent workspace and project`.
This PR realigns with with a standard error received on submiting an experiment into project you don’t have access to: `Failed to create experiment: {"error":{"code":5,"reason":"NotFound","error":"project (3) not found"}}`
https://determined-ai.slack.com/archives/C03LE5Z8R46/p1665705596071129

chore: improve project not found error message in create experiment

---

harness/determined/cli/sso.py

Fixes [DET-8546](https://determinedai.atlassian.net/browse/DET-8546) - OIDC authentication from the CLI results in 400 Bad Request
In some cases the SSO URL was being escaped, leading to the equals in the querystring being double-escaped, which caused issues during the unescaping process.
This only affects enterprise functionality, so no testing required here. 

fix: remove =true from sso url querystring

---

webui/react/src/components/LogViewer/LogViewer.tsx
webui/react/src/components/LogViewer/LogViewerEntry.tsx
webui/react/src/components/Markdown.tsx

Go to Cluster Logs and Trial Logs pages and confirm the following work:
- Up and down arrow keys to move focus up and down list of logs
- Page up and page down to scroll up and down by page height
- Home and end to jump to the beginning and end of the logs

fix: keyboard scrolling in logs [WEB-463]

---

.github/pull_request_template.md

our automated tests should do this now.
the tests should be fixed now

chore: take out manual shared testing instructions

---

webui/react/src/components/Table/InteractiveTable.module.scss
webui/react/src/components/Table/Table.tsx
webui/react/src/components/TagList.module.scss
webui/react/src/components/TagList.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/ModelDetails.module.scss
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelRegistry.module.scss
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/OldProjectDetails.tsx
webui/react/src/pages/ProjectDetails.module.scss
webui/react/src/shared/styles/antd.scss

[WEB-82](https://determinedai.atlassian.net/browse/WEB-82)
Before:
https://user-images.githubusercontent.com/28383080/196826702-d2b1daba-2d59-4f40-a038-893a8d85686c.mov
After:
https://user-images.githubusercontent.com/28383080/196826565-2ef0bfde-2495-4cd5-92cc-bcd7ae562c61.mov
Add and remove tags and change and press enter to save the experiment descriptions. play around with resizing, etc. and try to break things.

fix: dont show scrollbars in table cells

---

harness/determined/cli/rbac.py

`det rbac describe-role ROLE` did not list global role assignments for users.
1. Assign user a role globally.
2. Describe that role, user should show up in the list.

fix: `det rbac describe-role` list global assignments for users.

---

master/internal/api/apiutils/utils.go
master/internal/db/database.go
master/internal/usergroup/api_groups.go

For [DET-8497], we need the DB to be able to signal invalid input and the API to pass it through. This will enable an EE PR that fixes [DET-8497].
I've also updated `MapAndFilterErrors` to be much more flexible and allow other packages to manage their own error filtering and mapping.
No behavior should change as a result of this PR.
[DET-8497]: https://determinedai.atlassian.net/browse/DET-8497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-8497]: https://determinedai.atlassian.net/browse/DET-8497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: API and DB error for invalid input

---

webui/react/src/pages/ExperimentDetails/ExperimentMultiTrialTabs.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/ModelVersionDetails.tsx
webui/react/src/pages/TrialDetails.tsx

https://determinedai.atlassian.net/browse/WEB-547
only show loading state when the underlying fetch call is first called, not every time it's polled.
could be nice to bake this loading state into `usePolling` itself so it returns a loading that is true time a new fn is called, and then false thereafter.
go do `dev.setServerAddress('https://gcloud.determined.ai')`
go do `http://localhost:3000/det/experiments/2026/trials/25249/overview`
go see
that loading flicker does not persist.

fix: dont show loading state when polling trial details

---

webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/OldProjectDetails.tsx
webui/react/src/types.ts
webui/react/src/utils/experiment.ts

https://determinedai.atlassian.net/browse/WEB-551
original experiment comparison page has been deleted in favor of the trials comparison page.
i removed the batch action that points to it from the feature flagged project details, but forgot to remove it from the non feature flagged project details.
result is that when a user click on compare, they are redirected to uncategorized. doh.

fix: remove compare action for experiments 

---

docs/live.py

- Switch directory to `site/html` to get rid of the unnecessary `html` prefix and better reflect "real" URLs.
- Print the live server URL because I won't remember it runs on port 1234 next week.

fix: tweak live docs server.

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/LogViewer/LogViewer.tsx

https://user-images.githubusercontent.com/109113616/197040193-397764b9-c46a-4493-ba1a-b03ffc0b5633.mov
- Check if layout looks good
- Check if data is correct after pressing `scroll to oldest` (up arrow button)

fix: layout of logview

---

e2e_tests/tests/experiment/test_custom_searcher.py

`test_pause_multi_trial_random_searcher_core_api` was reported to fail randomly, e.g., https://app.circleci.com/pipelines/github/determined-ai/determined/28988/workflows/0271c643-19b1-46a2-870c-3ce475c50c46/jobs/982770
The reason is waiting for QUEUED state after activating the experiment, which may change too quickly for the test to record it. Good news is that we don't really need to check for QUEUED. It is enough to check if the experiment is COMPLETED (since it also means that pausing/unpausing was successful).
Test should stop being flaky

test: fix flaky custom searcher test

---

master/internal/sproto/task.go

Reverts determined-ai/determined#5252

chore: Revert "fix: remove duplicate event message. (#5252)"

---

master/internal/api/apiutils/utils.go

`authz.PermissionDeniedError` is not hash-able, so we move the check above the others.

fix: move permission denied error to not encounter hash error

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/singularity.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst
docs/reference/reference-training/experiment-config-reference.rst

Provide additional info on using PodMan in rootless mode and the required configuration to make it work.  Add info in known issues to point to configuration requirements. Enhance information about using local image caches for both PodMan & Singularity.

docs: Add PodMan requirements and known issues [FOUNDENG-289]

---

master/static/migrations/20221025105442_fixup-incompatible-pbs-expconf.tx.down.sql
master/static/migrations/20221025105442_fixup-incompatible-pbs-expconf.tx.up.sql

fix: account for incompatible pbs-related expconf change

---

webui/react/src/components/DeterminedAuth.tsx

Loading animation was visible when username and password are empty
https://user-images.githubusercontent.com/109113616/197850400-81740077-9b28-4280-a002-727dd5c9dd0f.mov
https://user-images.githubusercontent.com/109113616/197850693-88da7d69-4e6a-48af-83fa-5e71f8e26b8e.mov
- Check if loading animation is not visible when username and password are empty
- Check if loading animation is visible when user hit the login button

fix: login loading animation

---

webui/react/src/components/LearningCurveChart.tsx
webui/react/src/components/UPlot/UPlotChart/tooltipsPlugin.ts

WEB-423
https://user-images.githubusercontent.com/109113616/197632771-3f2a1064-f657-4b55-ac95-6316e273fa9d.mov
https://user-images.githubusercontent.com/109113616/197632857-afd4d20d-5284-424c-8c80-154b25c3727b.mov
- Check if user can easily compare multiple trials
> Clicking while the node is highlighted should take users to that trial detail page.
This feature is already implemented

fix: improve chart interactivity

---

webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/hooks/useModal/UserSettings/useModalGroupRoles.tsx

Right now we’re filtering down to only roles that have isGlobal permissions in user and group management pages. 
All roles should be selectable on these pages un-scoped (this means scoped to all workspaces)
Change roles for user/group, verify that all roles (global/non-global) can be selected

feat: Non-global permissions assignable globally [WEB-539]

---

master/internal/sproto/resources.go
master/internal/sproto/task.go

Show Slurm/PBS job ID in experiment log.
Along with the HPC launcher and determined dispatcher change, this is what will look like:

chore: HPC job ID is logged in experiment log.

---

webui/react/Makefile

- Add stylelint format with `--fix` flag
- Check if `make fmt-css-stylelint:` and `make fmt-css` would format css code

chore: add style lint fix

---

harness/determined/common/api/bindings.py
master/internal/api_master.go
proto/src/determined/api/v1/master.proto
webui/react/src/services/api-ts-sdk/api.ts

Moving [this PR](https://github.com/determined-ai/determined-ee/pull/372/files) from EE to OSS.
- [ N/A ] Changes have been manually QA'd
- [ N/A ] User-facing API changes need the "User-facing API Change" label.
- [ N/A ] Release notes should be added as a separate file under `docs/release-notes/`.
- [ N/A ] Licenses should be included for new code which was copied and/or modified from any external code.

chore: add field for internal web UI use to identify product context

---

webui/react/src/shared/contexts/stores/UI.tsx

chore: replace `enum` with `object as const`

---

docs/tutorials/index.rst

Fixed a broken link in tutorial page
https://user-images.githubusercontent.com/109113616/198709889-5d7b5230-f40d-45fb-8018-7a1d97153981.mov
- Check if the link is correct and works as expected

docs: fix tutorial link

---

webui/react/src/components/NavigationSideBar.tsx
webui/react/src/hooks/useFeature.test.tsx
webui/react/src/hooks/useFeature.ts

feat: remove webhooks feature flag [WEB-560]
Enables Webhooks in Determined by removing the feature flag that is gating the behavior.
1. Log into Determined as an admin and ensure that the link in the navigation sidebar to the Webhooks listing page is visible.
2. Log into Determined as a non admin and ensure that the link in the navigation sidebar to the Webhooks listing page is not visible.
[WEB-560]: …

feat: remove webhooks feature flag [WEB-560]

---

docs/release-notes.rst

I missed an opportunity to update the release note before the release.

fix: shiyuan's change to custom searcher release note

---

docs/release-notes.rst

I missed an opportunity to update the release note before the release.

fix: Shiyuan's suggestion to release note

---

.github/workflows/check-rebaseable.yml

ci: add more credentials [INFENG-98]

---

.github/workflows/check-rebaseable.yml

Switch to checking out EE repo then fetching relevant OSS branch
It seems that the storing of credentials doesn't work as expected in actions/checkout, and this is probably better anyway.

ci: Switch checkout method [INFENG-98]

---

webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx

Change the permission check to the correct permission for role assignment edits. `UPDATE_ROLES` is a currently unused permission for creation/editing of the Roles themselves.

fix: allow workspace admins to change role assignments in webui.

---

webui/react/src/hooks/useModal/JupyterLab/useModalJupyterLab.tsx
webui/react/src/hooks/useModal/Model/useModalModelCreate.tsx
webui/react/src/hooks/useModal/Project/useModalProjectCreate.tsx
webui/react/src/hooks/useModal/Project/useModalProjectEdit.tsx
webui/react/src/hooks/useModal/Project/useModalProjectMove.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceCreate.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceEdit.tsx

WEB-227
- Check if modals can handle both button click and `Enter`  key to submit
- Workspace
- Create
- Edit
- Project
- Create
- Edit
- Model
- Create
I didn't enable `Enter` to submit in modals for deletion since `delete` is a unchangeable action.

fix: enter to submit

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml
.github/dependabot.yml
.github/labeler.yml
.github/workflows/labeler.yml
.github/workflows/link-artifacts.yml
.github/workflows/lint-bindings.yml
.github/workflows/lint-docs.yml
.github/workflows/lint-go.yml
.github/workflows/lint-migrations.yml
.github/workflows/lint-python.yml
.github/workflows/lint-react.yml
.github/workflows/lint-secrets.yml
.github/workflows/scan-docker-images.yml
.github/workflows/semantic.yml
.github/workflows/test-cli.yml
.pre-commit-config.yaml
.yamllint

Add yamllint check for .github/** only
Reformat just about all of the files to include yaml document begin headers, use wrapping blocks for text which is fine to wrap, add the special comment for the `on:` line in actions files (sigh), and reindent a couple of things which weren't "properly" indented.
The two golang actions which had an actual change (`on` variable value was quoted in lint-bindings and lint-go) will run as part of the PR.  The other change was reformatting some text in issue templates; will have to create new issues to make sure they still look the same afterwards (they *should*, assuming I understand yaml multiline values correctly).

ci: enable yamllint [INFENG-116]

---

docs/Makefile
docs/assets/styles/determined.css
docs/cluster-setup-guide/security/overview.rst
docs/cluster-setup-guide/security/rbac.rst
docs/conf.py
docs/introduction.rst
docs/live.py
docs/quickstart-mdldev.rst
docs/reference/reference-deploy/config/master-config-reference.rst
harness/determined/cli/user_groups.py

- RBAC docs.
- Do not do `text-transform: uppercase` for h4,h5,h6 because it looks odd a prevents `monospace` text in headings.
- Restyle help strings in `user-group` CLI to match the rest of the codebase.
- Automatically rebuild docs in `make live` on CSS changes.
It may be helpful to add screenshots once UI is final.

docs: RBAC v1.

---

.github/workflows/check-rebaseable.yml
.github/workflows/pre-commit.yml

Run pre-commit on pushes and commits, helping to catch errors which slip in when people don't run pre-commit themselves.
Verify that the action passes :)

ci: add pre-commit execution action

---

.circleci/config.yml

Confirm updated CI jobs pass fine for PR.

ci(remote-docker): pin version to 20.10.18 [INFENG-106]

---

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceAddMember.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceRemoveMember.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx

Minimal changes to add callback functions when adding/removing members for workspace
Navigate to workspace members page
Click on "Add Members" to add a member
Verify that the new member shows up at members table shortly
Select a member to remove
Verify that the removed member disappeared from members table shortly

fix: Workspaces member page refetch after update [WEB-621]

---

.circleci/config.yml

https://determined-ai.slack.com/archives/C03H5KZPU30/p1667241463073989
pause until there's active work to add new features on the other project.
This used to serve as a reminder for breaking changes to shared code and while
the other project is not actively being added to let's pause this check.

chore: pause shared-web ci checks

---

.circleci/config.yml

Let CircleCI run for PR and check if labels exist in billing history.

ci(test-e2e): add e2e test mark as cluster label [INFENG-5]

---

e2e_tests/tests/cluster/test_webhooks.py

We do not want to check the entirety of the defined test and expected payloads because it will cause test failures. The lines removed in the PR were supposed to be removed before but were not. 
This will fix some e2e tests that are currently failing. 
1. Ensure `cluster/test_webhooks` e2e test is not failing.
~- [] User-facing API changes need the "User-facing API Change" label.~

fix: update webhook payload check in e2e test

---

webui/react/src/types.ts

WEB-601
- Check if log filter is sorted by log severity level
- `All levels` is the one 

fix: sort by log severity level

---

webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx

Skip role fetch calls when rbac is not enabled
Related to [WEB-626](https://determinedai.atlassian.net/browse/WEB-626) and [WEB-627](https://determinedai.atlassian.net/browse/WEB-627)
Disable RBAC
Navigate to `/settings/user-management`
Inspect the page, there should not be any errors
Select one use to edit
Modal should not stay in loading state

fix: Skip role fetch when RBAC not enabled

---

webui/react/src/pages/WebhookList.tsx

Added error handling so that a user receives an error message when testing a webhook fails. 
fix: handle webhook testing errors [WEB-625]
1. Create a new webhook with a non functioning server address i.e http://localhost:3000
2. Test the webhook, you should see an error message with the event ID pop up.
[WEB-625]: https://determinedai.atlassian.net/browse/WEB-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: handle webhook testing errors [WEB-625]
