determined-ai/determined

master/pkg/model/environment_config.go
master/pkg/model/experiment_config_test.go

Remove some unused code Slurm options validation code (now occurs on the Determined-ee side of the house).
N/A

chore: remove unused slurm options validation

---

master/static/migrations/20221109145930_add-scim-users-to-group.tx.down.sql
master/static/migrations/20221109145930_add-scim-users-to-group.tx.up.sql

Need a second add users to group migration for the possibility of non-determined created users.

chore: migration for adding newly created scim users to usergroups

---

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceCreate.tsx

Follow up fixes for [WebUI expand workspace configuration [WEB-33] ](https://github.com/determined-ai/determined/pull/5396)
Also switch the form layout from horizontal to vertical per requested. 
Set up checkpoint storage configuration for workspace
Remove checkpoint storage configuration for workspace and save
Open the modal again and verify that checkpoint storage configuration no longer exists
[WEB-33]: https://determinedai.atlassian.net/browse/WEB-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: WebUI remove checkpoint storage config

---

webui/react/src/shared/components/CopyButton.tsx

WEB-630
- Check if copy button can copy text
- Check if its easy to copy button

fix: fix copy button

---

docs/release-notes/imds-v2.rst
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml
master/internal/rm/provisioner/aws.go

AWS deployments created through Determined will use IMDSV2. 
Run a cluster with ```det deploy aws```
```
det deploy aws up --cluster-id nblaskey-test-imds-v2 --keypair keypair --det-version 2cb9f7b7ebbfc5947faaa726dc81fdf732ec269b
```
Wait for url of cluster to be printed in cli and run any experiment with ```-m urlPrinted```
In aws console go to ```cloudwatch > metrics > All metrics```, enter in the search bar ```MetadataNoToken``` and the master instance ID (can find in cloud resources tab with "Logical ID" of "MasterInstance"). Verify on the graph there is 0 requests.
Cancel out master instance ID and use the agent instance ID found in master logs

feat: master and agent instances created with IMDSv2 support [DET-7987]

---

.circleci/config.yml
harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/govcloud.py
harness/determined/deploy/aws/deployment_types/secure.py
harness/determined/deploy/aws/deployment_types/simple.py
harness/determined/deploy/aws/deployment_types/vpc.py
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml
harness/determined/deploy/gcp/cli.py
harness/determined/deploy/gcp/constants.py

feat: Add webhooks_base_url to det deploy
This PR exists because I wanted to be able to set the `webhooks_base_url` in latest master. This implements the ability for `det deploy` to set the appropriate configuration option. 
If someone could tell me where exactly I should be placing 
`webhooks_base_url=http://latest-master.determined.ai:8080` for our latest master deploy job that would be super helpful. 
TBD
~- [ ] Release notes should be added as a separate file under `docs/release-notes/`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.~

feat: Add webhooks_base_url to det deploy

---

master/internal/core.go
webui/react/package-lock.json
webui/react/package.json
webui/react/public/index.html
webui/react/src/shared/configs/craco.config.js

In #5414 I added a content security policy meta tag. We had a discussion and I merged it, but it was still open to review, so I quickly reverted it in #5423. **This un-reverts and re-adds the content-security-policy from #5414 back in.**

chore: Restore content-security-policy PR

---

.circleci/config.yml

ci: bump resource class to avoid test-intg-master flakes 

---

webui/react/src/hooks/useModal/Project/useModalProjectEdit.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceCreate.tsx

This change fix the issue that when closing edit workspace/project modal, the input data is not updated.
Repro steps: 
Open the details of a project inside of a workspace
Remove the workspace name text (error message will appear that workspace needs a name) 
Click out of the modal (modal will close (and not save)) 
Open the details of the workspace again 
Name of the workspace displayed empty (and has no error message)
Select a workspace/project to edit, make some changes in the modal
Click cancel or close
Select "Edit" and open the modal again
Modal fields should sync with the actual data (before modification) 

fix: sync workspace/project modal data when cancel [WEB-607]

---

.circleci/config.yml
harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/govcloud.py
harness/determined/deploy/aws/deployment_types/secure.py
harness/determined/deploy/aws/deployment_types/simple.py
harness/determined/deploy/aws/deployment_types/vpc.py
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml
harness/determined/deploy/gcp/cli.py
harness/determined/deploy/gcp/constants.py

Reverts determined-ai/determined#5354
Reverting this body of work until more testing can be completed.

revert: Add webhooks_base_url to det deploy

---

webui/react/src/pages/ExperimentDetails/ExperimentMultiTrialTabs.tsx

feat: remove checkpoints from multi trial tabs [WEB-639]
~See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.~
[WEB-639]: https://determinedai.atlassian.net/browse/WEB-639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: remove checkpoints from multi trial tabs [WEB-639]

---

webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx

fix: editing projects in table [WEB-641] 
See [ticket](https://determinedai.atlassian.net/browse/WEB-641) for context. Currently it is impossible to edit project details when in the table view because the modal and action dropdown both disappear on every project fetch. This PR fixes the aforementioned issue. 
1. Go to a Workspace page and navigate to the list of projects and make sure you are in the table view. 
2. Click the action dropdown (three vertical dots on the right) and ensure that the dropdown menu stays visible indefinitely (should not disappear after several seconds). 
3.  Click the action dropdown (three vertical dots on the right) and then click "edit"  ensure that the modal stays visible indefinitely (should not disappear after several seconds). 
See [Release …

fix: editing projects in table [WEB-641]

---

harness/determined/common/schemas/expconf/_gen.py
master/pkg/schemas/expconf/experiment_config.go
master/pkg/schemas/expconf/zgen_slurm_config_v0.go
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/hpc-cluster-slurm.json

Add configuration to enable Determined EE support for slurm.gpu_type.

chore: Add expconf slurm.gpu_type [FOUNDENG-338]

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/CheckpointModalTrigger.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx

Bump typescript to enhance type
- Check if test cases pass

chore: bump `Typescript`

---

harness/determined/core/_context.py

fix: log not interpolating string

---

webui/react/src/pages/ProjectDetails/ProjectDetailsTabs.tsx

WEB-613
WEB-614
- Check if `+ new page` button on the top doesn't disappear after adding new notes
- Check if `show archived` button doesnt display while note tab is active

fix: note page button issues

---

webui/react/src/pages/OldProjectDetails.tsx
webui/react/src/pages/ProjectDetails.tsx

Fix the issue that when loading "Uncategorized" project, the message was "Loading project undefined details..."
Navigates to `/det/projects/1/experiments`
Verify that when loading, the message is "Loading..." 
Easier to view the message if throttle to "slow 3G"

fix: Project loading message [WEB-596]

---

tools/k8s/fetch-creds.sh

Since @dannysauer mentioned not liking the wall of echos.

style: remove wall of echos from shell script

---

webui/react/tsconfig.json

- Remove `skipLibCheck` for better type check
- Check if test and build pass
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README.md) for details.~

chore: remove `skipLibCheck`

---

master/static/srv/get_checkpoints_for_experiment.sql
master/static/srv/get_checkpoints_for_trial.sql

As caught by @trentwatt , `CAST` causes some nasty perf issues.
stopgap until #5100 lands

perf: remediate issues with cast + proto_checkpoints_view

---

master/static/srv/proto_get_trials_plus.sql

When a checkpoint is reported with `null` resources, it eventually becomes `'null'::jsonb` in PostgreSQL, and this query just couldn't handle that weirdness.
There probably is a more elegant solution like not allowing this in the first place, but then I need to migrate all the checkpoint tables, and I wasn't really up for that.

fix: handle 'null'::jsonb when aggegrating resource size in proto_get_trials_plus.sql [DET-8691]

---

webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss

WEB-448
- Check if text are not overlapped 
- 

fix: trial comparison modal style

---

.circleci/config.yml
.github/workflows/lint-docs.yml
.github/workflows/lint-python.yml

`lint-python` on github CI is borked because they've retired 3.7.11. Let's switch to 3.7.15.

ci: bump python 3.7.11 -> 3.7.15.

---

bindings/generate_bindings.py
harness/determined/cli/experiment.py
harness/determined/cli/rbac.py
harness/determined/common/api/bindings.py

we've been advertising to_json output on generated `Class` types as `Any` where we could use a stronger type
we change that here.
- address unmasked issues
- fix an index issue on an empty list of roles
TODO:
could we soft-intro
https://mypy.readthedocs.io/en/stable/command_line.html#disallow-dynamic-typing

chore: tighten to_json advertised type

---

webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx

WEB-670
- Check if metrics is selectable

fix: metrics selection

---

.circleci/config.yml

A bunch of nightlies have been failing due to shortage of k80. I believe we can omit TF tests for 2.5, 2.6, 2.7 to reclaim some capacity.
- Real users now want newer versions of TF, not these.
- Tests for 2.4 (our "legacy") and 2.8 (our "current") should cover functionality and compatibility well enough. These tests have never caught any issues past the initial release.
- IIRC all our EE TF users are already on TF 2.8+

ci: disable tensorflow 2.5-2.7 tests.

---

docs/reference/reference-deploy/config/master-config-reference.rst
docs/reference/reference-training/experiment-config-reference.rst
master/pkg/model/task_container_defaults.go

Update TaskContainerDefaultsConfig members Pbs & Slurm to SlurmConfigV0/PbsConfigV0 as likely was intended.
Also address some documentation issues:
• master configuration documentation fails to mention PBS under task_container_defaults.
• The link from master task container defaults to environment.slurm doesn't land accurately – you need to scroll down a page or two.

chore: container defaults for PBS/slurm

---

webui/react/src/components/BreadcrumbBar.tsx
webui/react/src/components/LogViewer/LogViewer.tsx
webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetails.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/OldProjectDetails.tsx
webui/react/src/pages/TrialDetails/TrialChart.tsx
webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx

Original PR: #5139
In React18, we don't need to do this  https://github.com/facebook/react/pull/22114
- Check if app works as expected
- Check if warning errors dont show up

chore: remove unnecessary cleanup

---

webui/react/src/components/ExperimentIcons/index.tsx

Make experiment status icon bolder as requested.
Before:
After:
Alex has already approved the new look via slack

fix: increase experiment status icon font weight

---

e2e_tests/tests/cluster/test_model_registry.py
e2e_tests/tests/test_sdk.py

Remove the check which doesn't quite work on brand new databases.

test: fix model registry test.

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/pages/TrialsComparison/Collections/useTrialCollections.module.scss
webui/react/src/shared/styles/antd.scss

chore: bump `Prettier` v2.8.0

---

docs/reference/reference-deploy/config/helm-config-reference.rst
docs/release-notes/tensorboard-timeout-helm.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

Helm chart was missing master config option ```tensorboard_timeout```
Deploy a k8s cluster with a low tensorboard timeout
```
helm install determined helm/charts/determined/ \
--values helm/charts/determined/values.yaml \
--set maxSlotsPerPod=1 \
--set detVersion=0.19.7 \
--set tensorboardTimeout=5
```
Create an experiment and wait for it to complete. Then create a tensorboard after it is finished. Verify the Tensorboard is terminated shortly after. 

chore: add tensorboardTimeout to Helm chart [DET-8716]

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/singularity.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst

PBS should be configured to provide CUDA_VISIBLE_DEVICES. Provide guidance on how to use more than 1 GPU when this is not provided.  Also add some clarifications to directory accessibility in the image caching setup page.

docs: Document PBS CUDA_VISIBLE_DEVICES requirement [FOUNDENG-359]

---

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceCreate.tsx

Create workspace as non-admin user throws an error
`Unable to save workspace.
only admin privileged users can set workspace agent user groups`
Log in as non-admin user
Create a workspace
Should not encounter any error

fix: Create workspace as non-admin

---

harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/govcloud.py
harness/determined/deploy/aws/deployment_types/secure.py
harness/determined/deploy/aws/deployment_types/simple.py
harness/determined/deploy/aws/deployment_types/vpc.py
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml

Allow `det-deploy aws up` to deploy enterprise versions.

feat: det deploy aws enterprise edition

---

.circleci/scripts/upload_test_results.py
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
bindings/generate_bindings.py
docs/conf.py
docs/sphinx-wrapper.py
docs/sphinx_ext_downloads.py
master/static/srv/check_idle.py
master/static/srv/check_ready_logs.py
master/static/srv/enrich_task_logs.py
pre-commit/web_lint_check.py
proto/scripts/swagger.py
pyproject.toml
requirements.txt
schemas/gen.py
schemas/lint.py
tools/scripts/gen-attributions.py
tools/scripts/refresh-ubuntu-amis.py
tools/scripts/update-bumpenvs-yaml.py
webui/react/src/shared/bin/test.py

check py files in new commits with black

chore: add pre-commit check for python

---

master/internal/api_user.go
master/internal/db/postgres_users.go
master/pkg/model/agent_user_group.go
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.test.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/hooks/usePermissions.ts
webui/react/src/pages/Settings/Settings.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts
webui/react/src/types.ts

Enable user agent group configuration when creating/updating user from WebUI.
Screen shot:
Log in as admin or a user with administrate user permission and navigates to `/settings/user-management`
Create a user without user agent group
Edit that user, add user agent group
Create another user with user agent group
Edit that user, remove user agent group

feat: WebUI support user agent group when creating user [WEB-638]

---

webui/react/src/components/ExperimentIcons/Queue.module.scss
webui/react/src/components/ExperimentIcons/Queue.tsx
webui/react/src/components/ExperimentIcons/Spinner.module.scss
webui/react/src/components/ExperimentIcons/Spinner.tsx
webui/react/src/components/ExperimentIcons/index.tsx
webui/react/src/components/PageHeaderFoldable.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/TrialDetails/Header/TrialHeaderLeft.module.scss
webui/react/src/pages/TrialDetails/Header/TrialHeaderLeft.tsx
webui/react/src/shared/themes.ts

WEB-681
Related PR: #5373
- Check if icons are visible in experiment and trial detail pages
- Check if buttons are actionable (pause, stop etc) if there are actionable buttons
- Check if non-actionable buttons show tooltip by hover
- Check if actionable buttons don't show tooltip by hover

feat: add icons in experiment and trial detail pages

---

webui/react/src/pages/WorkspaceList.tsx

fix: workspace list pagination [WEB-664]
Adds a listener to the `fetchWorkspaces` function in order to immediately trigger updates when table settings are changed. 
1. Navigate to the workspace list page. 
2. Change the table page number and ensure the table immediately and correctly updates.
3. Change the table "/ page"  number and ensure the table immediately and correctly updates.
[WEB-664]: …

fix: workspace list pagination [WEB-664]

---

.circleci/config.yml

- "cuda-11" flavor is obsolete because standard tests are cuda 11.
- only legacy tf 2.4 version tests are worth saving.
- increase `no_output_timeout` for AWS CF deletion because sometimes it takes more than 10 minutes. 
- take out requestable `deploy` job for a couple of reasons:
- it was broken for as long as I remember
- occasionally people request it because they want to request "all tests". however this deploy job will deploy an aws cluster which the user is supposed to manually cleanup. I doubt this was ever an intention.

ci: move useful weekly tests to master branch, remove the rest [DET-8725]

---

master/internal/command/command_manager.go
master/internal/command/notebook_manager.go
master/internal/command/shell_manager.go
master/internal/command/tensorboard_manager.go

Create multiple notebooks with different users
Query `/notebooks` to verify all notebooks can be returned
Query `/notebooks` with specific `users` to verify only notebooks associated with users are returned
Query `/notebooks` with specific `user_ids` to verify only notebooks associated with user ids are returned
Repeat the same process for `shells`, `commands`, `tensorboards`

fix: Tasks filter by user [WEB-675]

---

.determined_markdown.style
.github/pull_request_template.md
.mdlrc
.pre-commit-config.yaml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
docs/release-notes/README.md
harness/determined/pytorch/README.md
master/static/migrations/README.md
model_hub/README.md
schemas/README.md
tools/k8s/README.md
tools/scripts/README.md
webui/README.md
webui/react/README.md
webui/react/src/shared/README.md

Updates to precommit:
* verify some markdown files (ignore examples for now)
* update several markdown files to comply
* verify dependabot and workflow definitions
* version bump on yamllint
Some of the markdown fixes were re-wrapping.  One was also removing some unnecessarily colorful language. :facepalm: Mostly just bullet consistency, wrapping bare links, and similarly trivial stuff, though.
* Spot check the modified markdown files
* It'll be necessary to verify the PR template still works as expected after merge, but it should still be fine too.

ci: add markdownlint and json schema

---

webui/react/src/components/Navigation.tsx
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/NavigationTabbar.tsx
webui/react/src/contexts/Store.tsx
webui/react/src/hooks/useFetch.ts
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.test.tsx
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx
webui/react/src/pages/Cluster/ClusterOverallStats.test.tsx
webui/react/src/pages/Cluster/ClusterOverallStats.tsx
webui/react/src/pages/Clusters.tsx
webui/react/src/pages/Clusters/ClustersOverview.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetails.test.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/pages/ResourcepoolDetail.tsx
webui/react/src/stores/index.tsx
webui/react/src/stores/resourcePools.tsx

[WEB-587]
- Check if `resource pool` is loaded in 
- Cluster page
- Job Queue page
- Launch jupyter modal page
- Hyper Parameter modal
[WEB-587]: https://determinedai.atlassian.net/browse/WEB-587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: split `resource pool` from Store Context

---

tools/k8s/fetch-creds.sh

bashisms would break on Debian/Ubuntu/etc where /bin/sh is dash
I ran this locally and it worked.  I'd be shocked if it failed for other people (even when bash is "really" in `/usr/bin`, I've never seen a system without a symlink in `/bin`).

fix: use bash in bash script

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/overview.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/singularity.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst
docs/reference/reference-deploy/config/master-config-reference.rst
docs/reference/reference-training/experiment-config-reference.rst
docs/release-notes/FOUNDENG-329-enroot-support.rst

Add docs for Enroot support.
Experiment Configuration

docs: NVIDIA Enroot support [FOUNDENG-329]

---

webui/react/src/pages/Settings/GroupManagement.tsx

fix: group management edit and delete options [WEB-702]
The `Edit` and `Delete` options are currently incorrectly swapped.
1. Navigate to group management page. Click the action dropdown menu for any group . Ensure clicking the "edit" option prompts you to edit the group.
1. Navigate to group management page. Click the action dropdown menu for any group . Ensure clicking the "delete" option prompts you to delete the group.
~- [ ] Licenses should be included for new code which was copied and/or modified from any …

fix: group management edit and delete options [WEB-702]

---

master/internal/db/postgres.go

There's some sloppy error handling, that probably isn't actually causing any problems.
But it could cause problems, so it should be fixed.

chore: fix potential named statement leak

---

webui/react/src/contexts/Store.tsx

chore: remove unused setAgents `StoreAction` definition is no longer needed. 
After moving agents to their own store this action definitions is 

chore: remove unused setAgents store action

---

webui/react/src/App.tsx
webui/react/src/components/Navigation.tsx
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/NavigationTabbar.tsx
webui/react/src/components/Page.tsx
webui/react/src/components/PageMessage.tsx
webui/react/src/contexts/Store.tsx
webui/react/src/hooks/useAuthCheck.ts
webui/react/src/hooks/useFeature.ts
webui/react/src/hooks/useFetch.ts
webui/react/src/hooks/useTheme.ts
webui/react/src/pages/SignIn.tsx
webui/react/src/pages/SignOut.tsx
webui/react/src/stores/agents.tsx
webui/react/src/stores/determinedInfo.tsx
webui/react/src/stores/index.tsx

As part of breaking parts out of the central Store, this covers the Determined info.
Switch between OSS and EE, verify that login page has different theme. 

chore: Split determined info from Store [WEB-584]

---

master/internal/rw_coordinator_test.go

TestRWCoordinatorLayer had a few issues:
- When it flaked, it did not report its error.
- It had a hardcoded port, which could potentially interact poorly with other tests.
- It had a hardcoded wait, which was a waste of time and also a source of flakiness.
- It did not clean up its server before exiting.
The new version uses a random port and listens separately from serving in order to avoid the hardcoded wait and guarantee the server is ready.
Of course, the server is cleaned up before exiting.
[Example flake](https://app.circleci.com/pipelines/github/determined-ai/determined/30683/workflows/9f0f522a-7b18-4469-9fca-670095c55e15/jobs/1055025)

ci: fix TestRWCoordinatorLayer flake

---

webui/react/src/hooks/usePermissions.ts

Previously, we initialized some mock user permissions but those were removed in [5549](https://github.com/determined-ai/determined/pull/5549/files#diff-4645e1906ef18f3e2b028be247d65bf86da4d94684c98ea51160b298f352f2f9L96). 
Since those permissions were removed, the check against those non-existent permissions should also be removed. 
~- [] User-facing API changes need the "User-facing API Change" label.~

chore: remove check for deprecated user init permissions

---

master/internal/api_command.go
master/internal/core.go
master/internal/core_experiment.go
master/internal/restore.go
master/internal/rm/actorrm/actor_resource_manager.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/resource_manager_iface.go
master/pkg/model/command_config.go
master/pkg/model/task_container_defaults.go
master/pkg/model/task_container_defaults_test.go

Inherit PBS & Slurm defaults from task container defaults for launcher-provided pools.
- Fixes an existing problem where PBS & Slurm arguments were not being acted upon.
- Brings in task container defaults from launcher-provided pools.
- New RM-level API for resolving task container defaults.

chore: inherit PBS & Slurm defaults 

---

.pre-commit-config.yaml

I think markdownlint in general is a good idea, but adding a dep on Ruby is not ideal. :)
Comment the check out until a containerized (or python) solution is identified.
Run pre-commit and make sure config is still valid.

ci: comment out the Ruby-based markdownlint checks

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst

Fix a typo in environment_variable attribute.
Indicate that the ENROOT_RUNTIME_PATH only works with Slurm.

docs: Minor Enroot doc fixes

---

webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx

[WEB-714]
- Enable RBAC
- Go to project in workspace 
- Go to member tab
- Member tab should be visible without crush and all features in member tab work as expected
[WEB-714]: https://determinedai.atlassian.net/browse/WEB-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: workspace member

---

docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/hpc-launcher-resource-pools.rst

chore: docs for launcher-provided pools

---

.circleci/config.yml

https://determined-ai.slack.com/archives/C04C9JXB1C2/p1670960925258129

ci: temporarily disable test results upload.

---

webui/react/src/contexts/Store.tsx
webui/react/src/hooks/useFetch.ts
webui/react/src/hooks/useModal/UserSettings/useModalCreateGroup.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/pages/Settings/GroupManagement.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/stores/index.tsx
webui/react/src/stores/knowRoles.tsx

As part of breaking parts out of the central Store, this covers the knownRoles.
Enable rbac, navigate to user management page, select a user to edit, should be able to add/remove roles.
Navigate to group management page, select a user to edit, should be able to add/remove roles.

chore: split knownroles from store [WEB-589]

---

webui/react/src/pages/Settings/GroupManagement.tsx
webui/react/src/pages/Settings/UserManagement.tsx

Navigate to user management page, click on table header to sort, data should be sorted accordingly.
Change page size, verify the page size changed.

fix: Enable sort for user management table [WEB-715]

---

harness/determined/common/api/bindings.py
master/internal/api_project.go
master/internal/api_project_intg_test.go
master/pkg/model/project.go
proto/src/determined/api/v1/api.proto
proto/src/determined/api/v1/project.proto
webui/react/src/services/api-ts-sdk/api.ts

feat: create endpoint to return projects by activity [WEB-676]
Adds an endpoint to return all projects, sorted by `activity_time` that a user has accessed based on the `activity` table.
1. Use the swagger API to create an activity entry for a project and user.
2. Use the swagger API to make a get request to the new endpoint, only the project with an entry from (1) should be returned.
3. Use the swagger API to create another activity entry for a project and user.
4. Use the swagger API to make a get request to the new endpoint, the two projects should be returned now. The project from (3) should appear first in the list.
5. Use the swagger API to create another entry for the same project as (1)
6. Use the swagger API to make a get request to the new endpoint, the two projects should be …

feat: create endpoint to return projects by activity [WEB-676]

---

webui/react/src/components/NotesCard.module.scss
webui/react/src/components/NotesCard.tsx

https://determined-ai.slack.com/archives/CLCE8D998/p1671046591705379
https://user-images.githubusercontent.com/109113616/207699171-3e1a5717-bafa-44dd-8807-f8f31da11655.mov
- Check if note is visible and editable with/without text in all places that note is used

fix: note card height adjustment

---

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceCreate.tsx

Bug: if you open the “new workspace” modal (by clicking “+” next to “Workspaces” in the sidebar) the modal cannot be closed by any means (clicking “cancel”, clicking “X”, or clicking out of the modal).
This only happens at OSS.
Open the create workspace modal, click outside / close / cancel, should dismiss the modal.

fix: Cannot close workspace modal [WEB-717]

---

webui/react/src/hooks/useSettings.ts

[WEB-710]
[WEB-710]: https://determinedai.atlassian.net/browse/WEB-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: closing jupyterlab modal updates url [WEB-710]

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst

Add additional information about Slurm MaxNodes partition configuration, and add known Slurm issues section with guidance about diagnosing QUEUED jobs.
*Slurm Requirements*
*Knows Slurm Issue* 
Passed through grammarly.

docs: Add Slurm MaxNodes configuration info

---

master/internal/api_project.go
master/pkg/model/project.go

Follow up https://github.com/determined-ai/determined/pull/5582
Fix recently access project not filtered by user
Fix return value of "lastExperimentStartedAt" when not exist
Post activity to the same project with different user, then get recent accessed project, should not have duplicate projects in the return value.
Post activity of a project that does not have experiment, get recent accessed project, "lastExperimentStartedAt" should be null.

fix: Dashboard recent projects backend

---

webui/react/src/components/NavigationSideBar.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.test.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/pages/Admin/index.tsx
webui/react/src/pages/Settings/Settings.tsx
webui/react/src/routes/index.tsx
webui/react/src/routes/routes.ts
webui/react/src/routes/utils.ts

Add a new page for user management and group management.
Log in as admin, click avatar -> "Admin"
"Users" and "Groups" tabs should show up and work as expected.
Log in as non-admin, click avatar, "Admin" tab should not be visible.  

feat: Separate admin page [WEB-720]

---

agent/internal/containers/manager.go
agent/internal/containers/manager_api_test.go
agent/internal/containers/manager_test.go
agent/internal/containers/spec.go
agent/internal/detect/cpu.go
agent/internal/detect/detect.go
agent/internal/detect/nvidia.go
agent/internal/detect/rocm.go
agent/internal/detect/rocm_test.go

The primary goal of this change is refactoring the container manager away from the actor system. Secondary goals, repeating again, were clearer interfaces and more testing. As a tactical maneuver to help some of these goals, I removed the revalidate flow.
Blocked on #5385 
Order to review this set of PRs:
* [refactor: rewrite websocket lib without actors DET-8299](https://github.com/determined-ai/determined/pull/5382)
* [refactor: rewrite our docker lib without actors DET-8300](https://github.com/determined-ai/determined/pull/4943)
* [refactor: rewrite container lib without actors](https://github.com/determined-ai/determined/pull/5384)
* [refactor: rewrite fluent lib without actors](https://github.com/determined-ai/determined/pull/5385)
* [refactor: rewrite container manager lib without …

refactor: rewrite container manager lib without actors [DET-8626]

---

webui/react/src/hooks/useModal/UserSettings/useModalCreateGroup.tsx

[WEB-726]
- Enable `RBAC`
- Login with `admin` role
- Click on username bubble and hit settings
- Go to Group Management and click New Group 
- Click in the Group name input field in the modal 
- Confirm that NO autocomplete suggestions are shown 
Autocomplete gets triggered 
[WEB-726]: https://determinedai.atlassian.net/browse/WEB-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: disable autocomplete in user group

---

webui/react/src/pages/ModelDetails.module.scss
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelRegistry.module.scss
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/OldProjectDetails.tsx
webui/react/src/pages/ProjectDetails.module.scss
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.module.scss
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx

[WEB-608]
For **_description_** column in `Modal Register`, `Modal Detail`, `Uncategorized` , `Workspace`, `Project` tables
- Check if value is saved by clicking `Enter` or outside of input
- Check if `Tab` and `Shift + Tab` let you move to the next target
- Check if `Escape` button doesnt trigger anything <- it is the default HTML behavior
- Check if description is disabled and uneditable when its archived 
In the ticket, it says `escape to leave the input field`, but the ticket author and I agreed to have the default HTML behavior which doesn't do anything with `escape`.
[WEB-608]: https://determinedai.atlassian.net/browse/WEB-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

fix: replace `InlineEditor` with antd `Input` in table for description

---

webui/react/src/hooks/useModal/Experiment/useModalExperimentCreate.tsx

Fix continue/fork experiment modal not able to close.
At experiment page, click fork/continue trial, should be able to close the modal. 
After close, the modal should be able to be opened again.

fix: Close continue/fork experiment modal [WEB-699]

---

docs/training/apis-howto/overview.rst
schemas/test_cases/v0/experiment.yaml
tools/scripts/bumpenvs.yaml

chore: remove references to images with TensorFlow 2.5 and 2.6 from documentation and fixtures [MLG-217]

---

webui/react/src/hooks/useModal/Project/useModalProjectDelete.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceDelete.tsx
webui/react/src/pages/WorkspaceList/WorkspaceActionDropdown.tsx

WEB-748
- Check if the cursor doesnt jump if user starts inputting in the middle of text
- Check if modal can be deleted if, only if typed value matches the current workspace/project name exactly

fix: input fix for deletion modal

---

webui/react/src/pages/Settings/UserManagement.test.tsx

React unit test is failing in master branch due to the lack of context provider. 
- Check if all test cases become green ✳️

fix: failed test case by adding missing context provider

---

webui/react/src/components/Table/Table.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/JobQueue/JobQueue.table.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/OldProjectDetails.tsx
webui/react/src/pages/TaskList.tsx
webui/react/src/pages/TrialsComparison/Table/TrialTable.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx
webui/react/src/pages/WorkspaceList.tsx

Navigate to task/experiment list, open the console, should not be any error

fix: hook inside useMemo warning

---

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceRemoveMember.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx

[WEB-747]
- Enable RBAC
- Go to member tab in workspace page
- Add a member if there's no members
- Click 3 dots button to open the remove member modal
- Check the followings
- there's no errors in browser console
- User is able to close/cancel the modal
- User is able to remove the member
[WEB-747]: https://determinedai.atlassian.net/browse/WEB-747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove modal in workspace member

---

.circleci/config.yml
docs/interfaces/notebooks.rst
docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/notebook-timeout.rst
harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/base.py
harness/determined/deploy/aws/deployment_types/govcloud.py
harness/determined/deploy/aws/deployment_types/secure.py
harness/determined/deploy/aws/deployment_types/simple.py
harness/determined/deploy/aws/deployment_types/vpc.py
harness/determined/deploy/aws/injector/master.yaml.tmpl
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml
harness/tests/storage/util.py
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/internal/api_notebook.go
master/internal/config/config.go
master/internal/task/idle_timeout.go
master/internal/task/idle_timeout_test.go
master/pkg/model/experiment.go
master/pkg/model/task.go

- Add master config option for a global default notebook timeout setting.
- Support it in `det deploy aws` and enable it on latest-master.
- Refactor `det deploy aws` code a bit because I was tired of duplication.
- Refactor `IdleTimeoutWatcher` to have its config as embedded struct instead of field duplication.
- Deploy a cluster with this option and check an idle notebook terminates as expected (which is pretty convoluted depending on `notebook_idle_type`, to be fair).
- `latest-master` should have less stale notebooks from all the people who don't terminate them.

feat: master config option to enable notebook timeouts by default.

---

master/internal/api_auth.go
master/internal/command/events.go
master/internal/db/postgres_command.go

feat: secure proxy path for rbac ntsc

---

harness/determined/cli/__init__.py
harness/determined/cli/_util.py
harness/determined/cli/command.py
harness/determined/cli/notebook.py
harness/determined/cli/render.py
harness/determined/cli/workspace.py

feat: workspace cli controls for notebooks

---

webui/react/src/pages/WebhookList.tsx

`key` was missing 
- Check if there's no warnings in browser console in webhook page

fix: add missing key

---

harness/determined/core/_checkpoint.py

When pausing and unpausing experiments, metadata files between ranks would have different content.
Why: assume the following scenario:
1. Pause a running experiment. Metadata is merged and saved (locally) by rank=0: metadata = {steps: 10}
2. Unpause experiment. Assume no selector for download/restore_path is provided. All ranks get all the files,  including metadata = {steps: 10}.
2. Let the experiment run, assuming a checkpoint is saved every 10 batches.
3. on step=20, metadata from all ranks is merged and saved locally by rank=0: metadata = {steps: 20}. At this point rank=0 has a file metadata.json with {steps: 20} and all other ranks have {steps: 10}. 
4. On the next upload this will cause an error on files with different content.
Solution: merge and save metadata locally with …

fix: save merged metadata for sharded ckpts locally

---

docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/experiment-tag-propagation.rst

docs: documentation for job_project_source

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go

Closing [DET-8710]
No behavior should change
[DET-8710]: https://determinedai.atlassian.net/browse/DET-8710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: prepare for multiple k8s RPs

---

webui/react/package-lock.json
webui/react/package.json

- Downgrade Typescript since the current ESLint version doesn't support Typescript > v4.9
- Check if all test cases are green

chore: downgrade typescript from v4.9.3 to v4.8.4

---

master/internal/api_workspace.go
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceCreate.tsx
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceDelete.module.scss
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceDelete.tsx
webui/react/src/services/apiConfig.ts

[WEB-746]
- Go to workspace
- Check if Creating/Editing a workspace with an all whitespaced name like `    `  on webUI modal causes validation errors
- Check if Creating/Editing a workspace with an all whitespaced name though API causes errors
[WEB-746]: https://determinedai.atlassian.net/browse/WEB-746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: validate workspace name

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst

Singularity over PBS known issue.

docs: Add known issue

---

.circleci/config.yml

CircleCI is failing due to the lack of resources
- https://app.circleci.com/pipelines/github/determined-ai/determined/31492/workflows/419853a7-87b3-4250-bbd5-974cd57fe6ca/jobs/1089799/resources
- https://app.circleci.com/pipelines/github/determined-ai/determined/31504/workflows/ba0e0a83-ac69-427a-9760-782848cece05/jobs/1090366/resources
- https://app.circleci.com/pipelines/github/determined-ai/determined/31511/workflows/12dce8e0-14b3-4db6-988a-2fab657b35c2/jobs/1090749/resources
- Pass all test cases

chore: `xlarge` resource class for `package-and-push-system-dev`

---

master/internal/api_project.go
webui/react/src/hooks/useFeature.ts
webui/react/src/hooks/useModal/Workspace/useModalWorkspaceAddMember.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/pages/WorkspaceDetails/RoleRenderer.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx

chore: remove mock_workspace_members feature flag WEB-2
We want to deprecate the `f_mock_workspace_members=on` feature flag.
1. Visit a workspace details page.
2. Enable the rbac, mock_permissions_all, and mock_workspace_members feature flags for the page. `f_rbac=on&f_mock_permissions_all=on&f_mock_workspace_members=on`
3. Ensure that the `Members` tab does not show mock data, i.e:
ensure these mocked users and groups are not shown. 
4. Click the `Add Members` button, ensure that no mock roles are shown in the `Role` dropdown, the dropdown should not just show "Editor" and "Viewer".  For OSS the dropdown should be empty. 
See …

chore: remove mock_workspace_members feature flag [WEB-2]

---

webui/react/src/pages/Cluster/ClusterHistoricalUsage.tsx
webui/react/src/pages/Cluster/utils.ts
webui/react/src/stores/users.tsx

WEB-769
- Go to historical-usage page under cluster page
- Check if APIs are not called many times and charts are visible

fix: resolve infinite loop in historical-usage page

---

harness/determined/cli/version.py

Updated hint by referring to check port as well.
visual inspection of changes.

chore: updated master location hint

---

helm/charts/determined/templates/master-permissions.yaml

We were encountering an issue where k8s would not be able to update pod labels - this ended up not being necessary to solve the problem, but I think the patch pod permission should still be granted to the cluster.

fix: add k8s permissions to fix patch bug

---

harness/determined/cli/command.py

fix: a cli bug with serializing workspace id

---

docs/conf.py

updated copyright from 2022 to 2023

docs: update date in conf py file

---

webui/react/src/components/kit/Breadcrumb.tsx

Bug described in comments of WEB-772.
This PR re-exports the breadcrumb component from antd without wrapping it. The following code should work without error, using the ui kit Breadcrumb component:
```
<Breadcrumb>
<Breadcrumb.Item>Home</Breadcrumb.Item>
<Breadcrumb.Item>
<a href="">Application Center</a>
</Breadcrumb.Item>
<Breadcrumb.Item>
<a href="">Application List</a>
</Breadcrumb.Item>
<Breadcrumb.Item>An Application</Breadcrumb.Item>
</Breadcrumb>
```

chore: fix ui kit Breadcrumb children

---

webui/react/src/components/kit/Checkbox.tsx
webui/react/src/hooks/useModal/Experiment/useModalExperimentStop.tsx
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx

WEB-773
- Check if antd checkbox is replaced with UIkit checkbox, and there's no antd checkbox left in code
- Check if UIKit checkbox works as expected

chore: replace antd checkbox with UIKit checkbox

---

master/internal/api_tensorboard.go
master/internal/command/authz_basic_impl.go
master/internal/command/authz_iface.go
master/internal/mocks/nsc_authz_iface.go

chore: add authz to tb and update interface fn

---

.github/labeler.yml

Autolabel docs pull requests as documentation
YOLO!
(actually just wait for a PR affecting docs and verify that the label applies)

ci: autolabel docs pull requests

---

webui/react/src/components/BreadcrumbBar.tsx
webui/react/src/components/PageHeader/PageHeader.tsx
webui/react/src/components/kit/Breadcrumb.tsx
webui/react/src/pages/ModelDetails/ModelHeader.tsx
webui/react/src/pages/ModelVersionDetails.module.scss
webui/react/src/pages/ModelVersionDetails.tsx
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx

WEB-772
- Check if antd breadcrumb is replaced with UIkit breadcrumb, and there's no antd breadcrumb used in code
- Check if UIKit breadcrumb works as expected

chore: replace antd breadcrumb with UIKit breadcrumb

---

harness/determined/cli/notebook.py
harness/determined/cli/tensorboard.py
harness/determined/cli/workspace.py

add the `--workspace-name` arg to the tensorboard list and start commands.
Tested manually:
1) create a test workspace and a project inside the workspace
2) create an experiment inside the project
3) create a tensorboard based on the experiment inside the test workspace
4) list tensorboards by workspace and make sure it shows up when you specify the test workspace and not when you specify a different workspace (or uncategorized).

feat: add workspace filtering to tensorboard cli [DET-8812]

---

webui/react/src/hooks/useModal/Columns/useModalColumnsCustomize.tsx

- Go to a project (project A).
- Open Customize Columns modal, change the values from the default, and save.
- Go directly to the Uncategorized page (project B). Note that this bug only occurs if you travel directly between pages that both use the `useModalCustomizeColumns` hook.
- Open Customize Columns modal.
Before this PR, you would see the columns from project A displayed. After this fix, you should see the correct column names that are being applied to project B.

fix: useModalCustomizeColumns values not updating on page change [WEB-696]

---

master/internal/sproto/resources.go
master/internal/sproto/task.go

Moved display HPC Job ID message into dispatcher code only. 

chore: remove unused code

---

master/internal/api_command.go
master/internal/grpcutil/auth.go

Modify user session token set in task launch so that external sessions have the correct token set.
Open a jupyter notebook on an externally-managed cluster and try using the `det` CLI.
DET-8777

fix: modify user session token set for external session

---

e2e_tests/tests/cluster/abstract_cluster.py
e2e_tests/tests/cluster/managed_cluster.py
e2e_tests/tests/cluster/managed_cluster_k8s.py
e2e_tests/tests/cluster/test_master_restart.py
e2e_tests/tests/cluster/utils.py

chore: code refactoring to allow the addition of tests for new types of managed devclusters
This PR includes a subset of changes taken from PR #5584. 
The changes in this PR are as follows:
1. Move the _now_ts() method to utils.py and rename it to now_ts().
2. Reduce code redundancy by creating a new method set_master_port() (within utils.py) that reads the config from the given path and sets the master port.
3. Move the abstract class, `Cluster`, to a separate file `abstract_cluster.py`, and update the reference/imports in `managed_cluster.py`, `managed_cluster_k8s.py`, and `test_master_restart.py`.
Tested locally and as part of CircleCI workflow `test-e2e-managed-devcluster`. …

chore: code refactoring to allow addition of tests for new types of managed devclusters

---

docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/allow-heterogeneous-fits.rst
master/internal/config/scheduler_config.go
master/internal/rm/agentrm/fair_share.go
master/internal/rm/agentrm/fair_share_test.go
master/internal/rm/agentrm/fitting.go
master/internal/rm/agentrm/fitting_test.go
master/internal/rm/agentrm/priority.go
master/internal/rm/agentrm/priority_test.go
master/internal/rm/agentrm/provisioner/aws_spot.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/agentrm/round_robin.go
master/internal/rm/agentrm/round_robin_test.go
master/internal/rm/agentrm/scheduler_test.go
master/internal/telemetry/reports.go

Allow jobs to fit on to different size agents.

feat: allow heterogeneous fits [DET-8800]

---

master/internal/api_ntsc_intg_test.go
master/internal/api_tensorboard.go

chore: rbac tensorboard intg testing

---

webui/react/src/components/ProjectActionDropdown.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.module.scss
webui/react/src/pages/WorkspaceDetails/WorkspaceDetailsHeader.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.module.scss
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx

chore: Move "Add Members" and "New Project" buttons into tab content [WEB-813]
Moves the position of the Add Members and New Project buttons.
This is easiest tested against an rbac-enabled backend. 
1. Navigate to a workspace page in the UI.
2. Ensure on the `Projects` tab the `New Project` button appears to the right of the page near the other action buttons.
3. Ensure on the `Members` tab the `Add Members` button appears above the table. 
4. Ensure that the `Add Members` and `New Project` buttons only appear in accordance to (2) and (3). The buttons should only show in the tab content when the appropriate tab is selected. 
5. Ensure the `Add Members` functionality works by adding removing and adding members. 
6. Ensure `New Project` works by creating a new project. Please note: locally …

chore: Move "Add Members" and "New Project" buttons into tab content [WEB-813]

---

master/static/srv/get_workspace_projects.sql
webui/react/src/pages/WorkspaceDetails/WorkspaceQuickSearch.tsx

WEB-802
There is a feature to search workspaces and projects in Web UI. [`GetWorkspaceProjects`](https://github.com/determined-ai/determined/blob/990e62e958d8bf29ac2e58ffb49d2be62ab15a90/master/internal/api_workspace.go#L131) API is called to fetch data. However, it was critically slow to fetch data when there are many workspaces and projects, and returned dupe data.
- Before the fix, it takes around **5 min** to get projects associated with all workspaces
- After the fix, it only takes less than **1 sec**.
I replaced `subquery` with `JOIN` to speed up.
As a result 
|                            | Old Planning Time | New Planning Time | Speed Up Rate |
| --------------- | -------------------: | --------------------: | --------------:  |
| All workspaces | 0.820 ms                  | 7.629 …

fix: duplicate projects fix and query speed up

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst

Document Apptainer known issues.

docs: add Apptainer known issues

---

e2e_tests/tests/api_utils.py
e2e_tests/tests/cluster/test_agent_user_group.py
e2e_tests/tests/cluster/test_checkpoints.py
e2e_tests/tests/cluster/test_rbac.py
e2e_tests/tests/cluster/test_resource_manager.py
e2e_tests/tests/cluster/test_users.py
e2e_tests/tests/cluster/test_webhooks.py
e2e_tests/tests/cluster/test_workspace_org.py
e2e_tests/tests/experiment/__init__.py
e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/experiment/test_core.py
e2e_tests/tests/experiment/test_custom_searcher.py

test: merge two similar test user session utils

---

master/internal/trials/api_trials.go
master/internal/trials/authz_basic_impl.go
master/internal/trials/authz_iface.go

[WEB-489]
[WEB-489]: https://determinedai.atlassian.net/browse/WEB-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: AuthZ for trials comparison

---

.circleci/config.yml
master/internal/api_auth.go
master/internal/api_ntsc_intg_test.go
master/internal/api_tasks.go
master/internal/command/events.go
master/internal/db/postgres_command.go

https://app.circleci.com/pipelines/github/determined-ai/determined/32105/workflows/d737b2b2-8ede-40eb-a394-a4633165526f
- [enable the ci tests for `master` ](https://github.com/determined-ai/determined/pull/5777/commits/28309c7734f300a2e142b407e49ee8ef018660c8)change after the tests pass
TODO disable these before landing
following up on  a ci failure that popped up after #5754 . 
this potentially started hitting a new path that wasn't hit before:: restoring commands on a tls enabled cluster with reattach enabled. for the time being this should unblock the ci
the initial issue that popped up 
```
{
"error": {
"grpcCode": 2,
"httpCode": 500,
"message": "1 error occurred:\n\t* failed to fetch batch: sql: Scan error on column index 0, name \"generic_command_spec\": json: cannot unmarshal …
```

chore: avoid fetching full command spec for logs

---

webui/react/src/components/UPlot/UPlotChart.module.scss
webui/react/src/components/UPlot/UPlotChart.tsx
webui/react/src/components/kit/LineChart.tsx

[WEB-663]
Gives `<LineChart />` a download button. Functionality can then be added to the desired charts by migrating them to `<LineChart />`.
Below is a sample of what the download looks like on a multi-trial experiment.
https://user-images.githubusercontent.com/28383080/213429557-d9893c5c-2cc2-4114-a38f-92626a2f6889.mov
[WEB-663]: https://determinedai.atlassian.net/browse/WEB-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: export chart [WEB-663]

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/stores/index.tsx
webui/react/src/utils/observable.ts

[WEB-789]
Introduces micro-observables library.
uncomment this [stores/index.tsx](https://github.com/determined-ai/determined/compare/trentwatt/introduce-observables?expand=1#diff-98f4d3f957e6686a6acaaef7a4bebce1604c1b52a57c5673ed8f672fd2fa74fd) and verify that it compiles. 
[WEB-789]: https://determinedai.atlassian.net/browse/WEB-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: introduce observables

---

.github/CODEOWNERS

Updates `CODEOWNERS` for directories related to the backend team.

chore: Update CODEOWNERS for backend

---

harness/determined/common/storage/__init__.py
harness/determined/common/storage/azure.py
harness/determined/common/storage/base.py
harness/determined/common/storage/cloud.py
harness/determined/common/storage/gcs.py
harness/determined/common/storage/hdfs.py
harness/determined/common/storage/s3.py
harness/determined/common/storage/shared.py
harness/determined/core/_checkpoint.py
harness/tests/storage/test_s3.py
harness/tests/storage/test_shared_fs.py
harness/tests/storage/util.py

Adds selector to `checkpoint.upload()` that allows uploading only specific files/dirs in the ckpt_dir. Works for sharded and single upload. 

feat: checkpoint.upload with selector [MLG-238]

---

webui/react/src/hooks/useSettingsProvider.tsx
webui/react/src/pages/TaskLogs.tsx
webui/react/src/utils/metric.ts

`substr()` is deprecated, so replaced it with `substring()`
Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
- Check if all CI are green

chore: replace `substr()` with `substring()`

---

docs/release-notes/aws-checkpoint-download-fix.rst
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml

Ensure that cli deployed AWS clusters have access to checkpoint downloads.
- Deploy a determined aws cluster using this code change.
- Create a run which generates a checkpoint.
- Download the checkpoint through the server, ie: `det checkpoint download UUID --mode=master`
This PR addresses permissions in AWS Cloudformation templates.
DET-8762
[DET-8762]: https://determinedai.atlassian.net/browse/DET-8762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: AWS checkpoint download from master

---

agent/go.mod
agent/go.sum
docs/release-notes/gcs-checkpoint-downloads.rst
master/go.mod
master/go.sum
master/pkg/checkpoints/checkpoints.go
master/pkg/checkpoints/gcs/gcs_checkpoints.go

Add functionality for downloading Google Cloud Storage checkpoint downloads through master.
- Deploy a determined gcp cluster using this code change.
- Create a run which generates a checkpoint.
- Download the checkpoint through the server, ie: `det checkpoint download UUID --mode=master`
This PR adds capability for GCS downloads.
DET-8762
[DET-8762]: https://determinedai.atlassian.net/browse/DET-8762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: GCS Checkpoint Download from master

---

e2e_tests/tests/cluster/test_master_restart.py

Server restart tests are flaky. Increase the max timeout for terminations so tests will pass.

chore: Increase test timeout for server restart

---

e2e_tests/tests/cluster/test_model_registry.py
e2e_tests/tests/cluster/test_workspace_org.py

ported from ee
this version isn't being used directly here but we do use it in our other repo

chore: update test util for setting up test workspaces

---

harness/determined/cli/model.py
harness/determined/cli/workspace.py

chore: add -w to ntsc workspace cli arguments

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/Metadata/EditableRow.tsx
webui/react/src/components/ProjectActionDropdown.tsx
webui/react/src/components/TaskActionDropdown.tsx
webui/react/src/pages/ModelRegistry.module.scss
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/Settings/GroupManagement.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/pages/WebhookList.module.scss
webui/react/src/pages/WebhookList.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.module.scss
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx
webui/react/src/pages/WorkspaceList/WorkspaceActionDropdown.tsx
webui/react/src/shared/components/ActionDropdown/ActionDropdown.tsx

There are some warnings on browser consoles.
`ghost` and `type` cannot be used at the same time.
- Check if all buttons look good and works as expected
- Check if there's no warnings in any pages

chore: fix button warnings

---

.circleci/config.yml
agent/.goreleaser.yml
agent/get-deps.sh
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-prem/homebrew.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-prem/overview.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-prem/requirements.rst
docs/release-notes/brew.rst
helm/Makefile
master/.goreleaser.yml
master/Makefile
master/get-deps.sh
master/internal/config/config.go

Experimental homebrew formulas for `determined-master` and `determined-agent`.
To install the formulas locally, build everything and then use these incantations:
- in `master/`: `make package && cp dist/determined-master_0.19.11-dev0_darwin_amd64.tar.gz $(brew --cache dist/determined-master.rb) && brew reinstall dist/determined-master.rb`
- in `agent/`: `make package && cp dist/determined-agent_0.19.11-dev0_darwin_amd64.tar.gz $(brew --cache dist/determined-agent.rb) && brew reinstall dist/determined-agent.rb`
(probably swap amd64 -> arm64 on apple silicon)
Then, setup postgres (following the `caveats` from `determined-master` installation.
Then start the services:
```
brew services restart determined-master
brew services restart determined-agent
```
TBD:
See [Release …

feat: homebrew package.

---

e2e_tests/tests/cluster/test_workspace_org.py

fix: use renamed setup_workspaces

---

webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx
webui/react/src/stores/projects.tsx

Reimplement project store with observable.
All CI green.
Perform Move on experiment, verify everything works as expected.
Open network tab and verify that projects for the same workspace are not fetched more than once. 
Project store seems to be only used with `useModalExperimentMove`, which seems to defeat the purpose of having a store. Do we need to use project store in other places? 

chore: Reimplement project store with observable [WEB-795]

---

e2e_tests/tests/cluster/test_checkpoints.py
e2e_tests/tests/conftest.py

Add test for https://github.com/determined-ai/determined/pull/5663 and https://github.com/determined-ai/determined/pull/5619
Automated tests for checkpoint download through master

feat: e2e test for checkpoint download through master

---

agent/.goreleaser.yml
master/.goreleaser.yml

goreleaser changed the default bindir, and I did not notice it when updating goreleaser in #5642 
https://github.com/goreleaser/goreleaser/pull/2910
Install the debian packages and try running master & agent.

fix: rollback default bindir for new goreleaser.

---

master/internal/db/postgres.go

e2e tests were failing because of a bun error related to many to many relationships. This is caused by reinitialization of bun, during which it does not reinitialize the same models that it initialized originally.

fix: m2m test intg fail

---

.circleci/config.yml

https://determined-ai.slack.com/archives/C04C9JXB1C2/p1674673032674739
not sure how having added the py version into the keygeneration mix didn't result in
updated deps https://github.com/determined-ai/determined/blob/d2ba0837b0caa0a1c8927ae691694b95592dfea1/.circleci/config.yml#L362-L366

chore: up the ci cache buster version

---

requirements.txt

mypy complains about typing versions of pyzmq that don't provide type.

chore: pin pyzmq for mypy

---

webui/react/src/components/UPlot/UPlotChart.tsx

Before: going to scatter or heat maps on multi-trial experiment crashes the page
After: it doesn't

fix: dont update bounds for non-synced charts

---

.circleci/config.yml
model_hub/model_hub/mmdetection/_data.py
model_hub/model_hub/utils.py

chore: revert earlier py lint version bump

---

webui/react/src/components/NavigationSideBar.tsx
webui/react/src/hooks/useSettingsProvider.tsx

WEB-829
- Check workspace list in nav bar and page-wide spinners are centered

fix: spinner alignment

---

.github/workflows/doc-review.yml

Since the docs team only has one member, assign an alternate team for review on PRs in the docs directory opened by the docs team member
Open a PR and watch the magic go

ci: assign ml-group on doc pr by doc [INFENG-149]

---

.github/workflows/doc-review.yml

Use pull_request_target for doc review action because forks can't read repo secrets
Open a test PR and try again

ci: switch doc review target for forks [INFENG-149]

---

.github/workflows/doc-review.yml

Made my own fork of the action which actually supports pull_request_target.  Switch action to that fork, since upstream doesn't seem very well maintained. /shrug
Open yet another PR

ci: switch dock review to new fork [INFENG-149]

---

.circleci/config.yml
agent/.goreleaser.yml
agent/Makefile
docs/release-notes/multi-arch-and-arm64.rst
master/.goreleaser.yml
master/Makefile

Provide arm64 packages and multi-arch images.
Needs testing with a tagged release candidate.
The nvcr.io repository may have difficulty with multi-arch manifests.
This PR does not include any changes necessary for deploying arm64 clusters.
DET-8841

feat: Add multi-arch docker manifests and arm64 packages

---

master/internal/api_model.go

fix: add patch model permission check
e2e_tests.

fix: add patch model permission check

---

master/internal/api_user.go
webui/react/src/pages/Settings/SettingsAccount.tsx
webui/react/src/shared/utils/error.ts

After changing the user display name to a different display name, it is impossible for a user to rename their new display name to a previous display name (if previous display name is the same as username).
Navigate to settings page
Change display name
Change display name back
Test with admin/non-admin user
When test with admin user, set display name to 'admin', change to something else, then change back

fix: Changing display name [WEB-740]

---

master/internal/api_ntsc_intg_test.go
master/internal/api_tensorboard.go
master/internal/command/authz_basic_impl.go
master/internal/command/authz_iface.go
master/internal/mocks/nsc_authz_iface.go

The Terminate tensorboard function requires the same arguments as the other tensorboard functions to be effective.

chore: change terminate tensorboard implementation

---

e2e_tests/tests/cluster/test_oauth2_scim_client.py
e2e_tests/tests/cluster/test_rbac.py
e2e_tests/tests/cluster/test_users.py
e2e_tests/tests/cluster/test_users_experiment_api.py

chore: remove redundant test login

---

docs/cluster-setup-guide/basic.rst
docs/cluster-setup-guide/deploy-cluster/index.rst
docs/cluster-setup-guide/security/oauth.rst
docs/cluster-setup-guide/security/oidc.rst
docs/cluster-setup-guide/security/overview.rst
docs/cluster-setup-guide/security/rbac.rst
docs/cluster-setup-guide/security/saml.rst
docs/cluster-setup-guide/security/scim.rst
docs/cluster-setup-guide/security/tls.rst
docs/example-solutions/examples.rst
docs/index.rst
docs/interfaces/webui-if.rst
docs/model-hub-library/index.rst
docs/quickstart-mdldev.rst
docs/reference/reference-deploy/index.rst
docs/reference/reference-model-hub/index.rst
docs/reference/reference-training/index.rst
docs/training/apis-howto/api-core-ug.rst
docs/training/debug-models.rst
docs/training/dtrain-introduction.rst
docs/training/setup-guide/overview.rst
docs/training/submit-experiment.rst

This is the first attempt to bring consistency across the overview and index pages. For reference, visit the [Jira issue](https://determinedai.atlassian.net/jira/software/projects/DOCS/boards/41?selectedIssue=DOCS-19).

docs: more consistent descriptions

---

e2e_tests/tests/api_utils.py

fixes issues that some ee tests ran into https://app.circleci.com/pipelines/github/determined-ai/determined-ee/5066/workflows/c82ec4fa-fbf5-41d1-a2e7-c9b59d7b026c/jobs/174116
ee test run https://app.circleci.com/pipelines/github/determined-ai/determined-ee?branch=tmp-test-session-sideffect

chore: remove cert and auth sideeffects of calling determined_test_session

---

.circleci/config.yml

Fix an issue with make package workspace access on feature branches.

chore: fix CI make package issues

---

harness/setup.py

`harness/setup.py` previous had this comment: `# azure-core 1.23 requires typing-extensions 4.x which is incompatible with TF2.4`
Since we have upgraded our images to use Tensorflow 2.7 and 2.8, we do not need to restrict our dependencies for this reason.

chore: unpin version of azure-core and azure-storage-blob [MLG-16]

---

docs/reference/reference-deploy/config/master-config-reference.rst

Update the Slurm/PBS master configuration docs to better describe the current behavior WRT slot_type.
Docs build and tested locally.

docs: clarify usage of slot_type with HPC

---

webui/react/src/pages/WorkspaceDetails.tsx

[WEB-833]
- Change network throttle to `fast 3G`
- if there's no throttle, wouldn't see API cancelation cuz API is pretty fast, and no time to cancel
- Switching workspaces quickly
- Check if API calls are cancel.
https://user-images.githubusercontent.com/109113616/215866675-9f27048e-8f31-4bf2-bcbe-4f8051a36cc7.mov
https://user-images.githubusercontent.com/109113616/215866675-9f27048e-8f31-4bf2-bcbe-4f8051a36cc7.mov
[WEB-833]: https://determinedai.atlassian.net/browse/WEB-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cancel api calls after switching workspace

---

master/internal/api_tensorboard.go

Ensures proper permission checks for launching tensorboards.
Manually tested - 
Requires two workspaces, A and B, and your user to have edit access to B
1) create a test user with edit permissions to workspace A
2) Using your own user, create an experiment in a project in workspace B
3) Using the test user, launch a tensorboard for the experiment you launched, but spawn it in workspace A. The goal is to have your tensorboard launch in workspace A but reference an experiment in workspace B. **This should fail**

fix: task type not getting set properly during tb permission check

---

.github/dependabot.yml

Dependabot for docker is a bit trigger-happy to update us to ubuntu 23.04 which hasn't even been released yet: https://github.com/determined-ai/determined/pull/5888
Change the config to switch it into "security only" mode.

ci: security-only dependabot PRs for docker.

---

docs/cluster-setup-guide/security/rbac.rst
docs/reference/reference-deploy/config/master-config-reference.rst
master/internal/command/authz_basic_impl.go

docs: add rbac ntsc docs

---

master/internal/api_trials.go
webui/react/src/components/kit/LineChart.tsx
webui/react/src/hooks/useMetricNames.ts
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/TrialDetails.tsx
webui/react/src/pages/TrialDetails/F_TrialDetailsOverview.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts
webui/react/src/services/decoder.ts
webui/react/src/shared/utils/number.ts
webui/react/src/types.ts

Co-authored with Guangqing Tang.
Initial feature-flagged version of trial chart grid.
Does not handle streaming data well: causes an obtrusive flicker and a reset of the zoom. 
I broke the WIP to fix that out into a separate branch, and propose to merge this without that fix since it's behind a feature flag. Ticket is WEB-848.
#5853 addresses some UI issues currently present with the charts.
[WEB-653]
[WEB-660]
To turn on feature flag, append `?f_metrics_grid=on` to the url.
Involves backend changes, so netlify testing is not sufficient.
doing `det e create const.yaml .` from [test-metrics-grid.zip](https://github.com/determined-ai/determined/files/10538838/test-metrics-grid.zip) will generate data that demonstrates the pairing of training/validation metrics.
See [Release …

feat: trial metrics grid (feat @gt2345)

---

master/static/srv/task-signal-handling.sh

Recursion reports the following problem.  This defect is particularly about shell error in signal handling.
[2023-01-25 22:17:07] || INFO: [152214] root: Validating checkpoint storage ...
<info> [2023-01-25 22:17:10] || INFO: [152214] root: Uploading to GCS: determined/f778d383-3577-4220-915c-ec34a7fd7625
<error> [2023-01-25 22:17:15] || ERROR: [152214] root: Checkpoint storage validation failed: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
<none> [2023-01-25 22:17:15] || /run/determined/task-signal-handling.sh: line 39: trapped_signal: unbound variable
Apparently, recursion introduced a 'set -u' in their startup-hook.sh to trigger this.   That impacts the method invoked by the trap handler when a trap occurs apparently.
A reproducer:
``` …
```

fix: trapped_signal: unbound variable.

---

agent/internal/fluent_intg_test.go

Tries to solve this flake
https://app.circleci.com/pipelines/github/determined-ai/determined/32700/workflows/546e97d5-f9d7-4a1e-a524-b96887f94972/jobs/1142416
Agent intg passes.
Also adds a logging line for if we get the unexpected log flake again.

test: increase wait timeout for agent test-intg container exit [DET-8869]

---

examples/deepspeed/deepspeed_dcgan/cifar10_zero2.yaml
examples/deepspeed/deepspeed_dcgan/mnist.yaml
examples/deepspeed/deepspeed_dcgan/mnist_grad_accum.yaml

Previously, the Determined example in deepspeed/deepspeed_dcgan used DockerHub images built with TensorFlow 2.4. We now have those with TensorFlow 2.8. We are also anticipating the unpinning of our Azure requirement, which was necessary to be compatible with TensorFlow 2.4 (see [MLG-16](https://determinedai.atlassian.net/browse/MLG-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)).
[MLG-16]: https://determinedai.atlassian.net/browse/MLG-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update dockerhub image in deepspeed_dcgan configurations

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst

Explicitly list RHEL and Rocky Linux as supported, and broaden working to cover all compatible distros.

docs: Clarify minimum linux dependency for HPC Launcher

---

webui/react/src/components/NavigationSideBar.module.scss
webui/react/src/components/NavigationSideBar.tsx

WEB-840
Related: #5644
- if user have a permission to create workspaces, user can see the `+` button in nav bar  
- click the `+` button in nav bar
- check if user can create a workspace
@alexjdetermined agree to have this back.

feat: add `+` button back to create workspace

---

webui/react/src/hooks/usePermissions.ts
webui/react/src/pages/ModelRegistry.settings.ts
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

[WEB-803]
- If RBAC is NOT enabled
- Everyone can see model registry tab in workspace and global model registry
- If RBAC is enabled
- User who has `VIEWMODELREGISTRY` permission can see model registry tab in workspace and global model registry
- For Both (RBAC is enabled and disabled)
- Check if `useSettings` are independent
- Manually change the workspaceId col in db to check since we dont have workspace dropdown in model modal.
[WEB-803]: https://determinedai.atlassian.net/browse/WEB-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: model registry tab in workspace

---

.circleci/config.yml
webui/react/src/hooks/useModal/UserSettings/useModalPasswordChange.test.tsx

Update `test-unit-react` to report only `junit.xml` and extend timeout for `useModalPasswordChange.test.tsx`.
Update `test-e2e` and `test-intg-agent` to use XLarge resource class for CI.
DET-8887

chore: address some CI failure issues

---

harness/determined/exec/tensorboard.py
harness/determined/tensorboard/fetchers/azure.py
harness/determined/tensorboard/fetchers/base.py
harness/determined/tensorboard/fetchers/gcs.py
harness/determined/tensorboard/fetchers/s3.py
harness/determined/tensorboard/fetchers/shared.py

fix: Check tensorboard responsive before continue [MLG-195]
Prevent the Tensorboard instance from timing out on initial fetch by making sure the tensorboard instance is up before syncing, then signaling that the board is ready once at least one file has been downloaded.
Check in debug mode that the ready signal is indeed sent after the first file upload and only then.
Run a sync with extremely large amounts of tfevent files to prevent the bug in question.
Support reading the tfevent files concurrently
Follow-up Ticket: [MLG-295]
MLG-195
[MLG-195]: https://determinedai.atlassian.net/browse/MLG-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

fix: Check tensorboard responsive before continue [MLG-195]

---

webui/react/src/shared/components/Spinner/Spinner.tsx

Members tab for any workspace takes forever to load. The loading spinner doesn't terminate
Navigate to members tab for any workspace, spinner should disappear when loading finishes

fix: spinner not stoping [WEB-869]

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-prem/deploy.rst
harness/determined/deploy/local/cli.py

There's no reason for a normal user to ever use this option, we should not be suggesting it in the docs.

docs: hide `det deploy local ... --agents` option.

---

proto/pkg/commonv1/common.pb.go
proto/src/determined/common/v1/common.proto
webui/react/src/services/api-ts-sdk/api.ts

Removed unwanted comment in swagger in `/docs/rest-api/#/Experiments/GetExperiments`
- Check if the comment is fixed

chore: fix comment in swagger

---

e2e_tests/tests/cluster/test_rbac.py
e2e_tests/tests/utils.py
harness/determined/cli/__init__.py
master/internal/api_command.go
master/internal/api_ntsc_intg_test.go
master/internal/api_shell.go
master/internal/api_tensorboard.go
master/internal/command/authz_basic_impl.go
master/internal/command/authz_iface.go
master/internal/mocks/nsc_authz_iface.go

- pull in test utils
- trim the canTerminateTensorboard interface
- pull in ee changes to ntsc api for err mapping and filtering
DET-8888

chore: pull in test utils from ee

---

harness/determined/exec/tensorboard.py

Fix to longrunning e2e bug from [MLG-195]
https://app.circleci.com/pipelines/github/determined-ai/determined/32938/workflows/c2c4f9ef-ff1d-497f-a961-277768ffd50b/jobs/1153679
Deployed to AWS and ran pytest on that directly to vet the change
Waiting on https://app.circleci.com/pipelines/github/determined-ai/determined/33015 to confirm that regressions are fixed
Thanks @ioga for noticing the issue and explaining how to diagnose integrated tests on circleci
[MLG-195]: https://determinedai.atlassian.net/browse/MLG-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Give TensorBoard enough time to spin up for e2e tests

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst

In FOUNDENG-425, we added support to the launcher to import the proxy variables "http_proxy", "https_proxy", "ftp_proxy", "rsync_proxy", "gopher_proxy", "socks_proxy", "socks5_server", and "no_proxy" from "/etc/environment" and "/etc/sysconfig/proxy" (SLES) and export them in lowercase and uppercase to the container.
This is the user documentation describing this proxy support.
In "Install Determined on Slurm/PBS", we added bullet item #7.
In "Installation Requirements", we added the following "Proxy Configuration Requirements" section.

docs: FOUNDENG-439 Provide documentation for the proxy support we added to the launcher in FOUNDENG-425

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/overview.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst

Blocking Slurm defect was added in 22.05.5 so make the wording more specific.
===========
==========

docs: Update Slurm version restrictions

---

webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx

[WEB-865]
- Enable RBAC
- Login as Admin
- Go to to admin page
- Check if there's no infinite API calls in the browser console
- Check if user can create/edit user in admin page works
[WEB-865]: https://determinedai.atlassian.net/browse/WEB-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: resolve infinite API calls in Admin settings page

---

webui/react/src/pages/WorkspaceDetails.tsx

[WEB-868]
- Enable RBAC
- Login as admin
- Create a workspace only admin can see
- Logout and login as no-role user
- Go to the workspace
- Check if there's no `Request searchRolesAssignableToScope failed.` notification
I don't see the notification in local EE, but i see it on http://latest-ee-gke-master.determined.ai, so i explicitly make notification silent. 
[WEB-868]: https://determinedai.atlassian.net/browse/WEB-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: make notification silent

---

webui/react/src/components/SelectFilter.tsx
webui/react/src/pages/Cluster/ClusterHistoricalUsage.settings.ts
webui/react/src/stores/experiments.tsx

WEB-826
- Go to cluster page and move to `historical usage` tab
- Check if From, To, GroupBy are clickable
- Check if `SelectFilter` component behaves the same as before

fix: select in historical usage

---

webui/react/src/routes/utils.ts
webui/react/src/utils/error.ts

[WEB-872] [WEB-886]
- Find a place where user see many notifications
- For example, enable RBAC
- Create a notebook as Admin, and logout
- Login as a user without any permission
- Access the notebook url
- Check if only one notification shows up if its the same notification
- Check if it doesnt happen like the following video
https://user-images.githubusercontent.com/109113616/217392773-9875129c-7e0e-45b0-907b-e67be02a9263.mov
[WEB-872]: https://determinedai.atlassian.net/browse/WEB-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-886]: https://determinedai.atlassian.net/browse/WEB-886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

fix: prevent showing many notifications

---

.circleci/config.yml

RC builds are running out of memory.

ci: increase rc builder size to xlarge

---

e2e_tests/tests/nightly/test_convergence.py
examples/integrations/hf_trainer_api/det_callback.py

Fixes convergence tests and callback (one tab too many). Tested manually + running e2e tests.

fix: HF callback + test

---

.circleci/config.yml
agent/Makefile
master/Makefile

The Nvidia container registry is OCIv1 and the `docker manifest` tool requires a v2 registry, producing errors like `failed to configure transport: unsupported registry version`. For now we can just publish the amd64 images to nvcr.io and the multi-arch manifests to docker hub. In the future if we would like to support manifests on nvcr we would need to use something like `manifest-tool` instead (https://github.com/estesp/manifest-tool).
This also bumps `no_output_timeout` to 30m for `make release` commands, similar to `make package`.

chore: fix make release issues

---

webui/react/src/components/ThemeProvider.tsx

[WEB-887]
- Check if Tooltip color matches the theme color (system, light, dark)
- Check if other tooltips looks the same as before (system, light, dark)
[WEB-887]: https://determinedai.atlassian.net/browse/WEB-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: adjust tooltip background color

---

webui/react/src/hooks/useModal/Workspace/useModalWorkspaceAddMember.tsx

https://determinedai.atlassian.net/browse/WEB-858
Fixing filtering and also shortening the placeholder to address width issue (identified in https://determinedai.atlassian.net/browse/WEB-871)
From workspace page, view "Members" tab and open "Add Members" modal. Should be able to filter the users/groups by typing in the input field.

fix: AddMember modal filtering and placeholder

---

harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/common/storage/gcs.py
harness/tests/storage/test_gcs.py

Update python code for gcs when download mode is auto.
Use `det checkpoint download` to download checkpoints from a GCP (and AWS) cluster, where the flag `--mode=direct` should fail, but `--mode=auto` succeeds.

fix: det checkpoint auto download for gcs

---

agent/internal/fluent/fluent_api_test.go
agent/internal/fluent_intg_test.go

The Elasticsearch agent logging tests have been very sporadically flaking for a while. I tracked down one of the failures (the one in `fluent_api_test.go`) to Fluent Bit not receiving the last log line; I'm not sure why that's happening, but it might possibly be related to the last line being partial. I don't really know what's going on, and I suppose partial lines should work anyway, but it seems like enough of an edge case that I'm just making the last line partial, and also increasing the amount of logging in case this still fails in the future. The test also now gets a bounded number of tries, so that we can see output on failure instead of the test runner just getting killed.
The other test fails with the lines being out of order instead, which is even stranger, but I haven't …

test: tweak Elasticsearch logging tests

---

master/static/migrations/20230208142448_add-update-modified-time-user-table.tx.down.sql
master/static/migrations/20230208142448_add-update-modified-time-user-table.tx.up.sql

WEB-890
- Migrate db
- Login as admin on webui
- Go to admin page 
- Edit a user
- Check if `modified_at` is updated
- Check if sql is correct
My first time to add migration files. Am i doing correct?

fix: update modifled_at in users table

---

webui/react/src/components/UPlot/SyncProvider.tsx
webui/react/src/components/UPlot/UPlotChart/closestPointPlugin.module.scss
webui/react/src/components/UPlot/UPlotChart/closestPointPlugin.ts
webui/react/src/components/UPlot/UPlotChart/drawPointsPlugin.ts
webui/react/src/components/UPlot/UPlotChart/tooltipsPlugin.module.scss
webui/react/src/components/UPlot/UPlotChart/tooltipsPlugin2.ts
webui/react/src/components/UPlot/types.ts
webui/react/src/components/kit/LineChart.tsx
webui/react/src/hooks/useModal/Checkpoint/useCheckpointFlow.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpoint.tsx
webui/react/src/pages/DesignKit.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
webui/react/src/pages/TrialDetails/F_TrialDetailsOverview.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts
webui/react/src/shared/styles/index.scss

[WEB-657]
https://user-images.githubusercontent.com/28383080/216261186-e3b9006e-71f9-4d82-8be4-b30d7cfd391b.mov
`det e create const.yaml .` from [test-metrics-grid.zip](https://github.com/determined-ai/determined/files/10572701/test-metrics-grid.zip)
- it's weird that the original modal reappears underneath when you go to the next modal, but that is not unique to this PR. probably should be addressed as a part of modal revamp.
- previously we were using css styles to create a diamond shape. this worked because they were applied to a single `<div />` element that was overlaid on top of the canvas where the closest point was. we want to eventually show more/all checkpoints, and creating divs for each point does not make sense in that case, so i have used a custom canvas renderer for …

feat: interactive checkpoint markers on charts

---

harness/determined/cli/command.py

- consistent with other ntsc
- prevent workspace id being reported as N/A
- keep workspaceId in the json output
we swap the workspaceId fro workspaceName but the tensorboard table header was
still referencing workspaceId
reverted the first commit to see the second commit correctly results in reporting workspace id
@aciborowska reported:
> t det tensorboard list gives N/A in the workspaceId column.

fix: tensorboard cli should report workspace name

---

webui/react/src/stores/auth.ts

This fixes an issue where the logic redirecting the user to the default route happened on every refresh.
When visiting a page, refreshing the page should not redirect the user to the default route.
WEB-791 
WEB-901

fix: prevent login redirect happening constantly

---

master/Makefile

build: Correct typo on PHONY target designation

---

.circleci/config.yml

Already tested changes with a custom workflow in [this scrap PR]().
Making this PR to test changes across all the long running E2E tests.
PR for changes automating the configuration of the project used:
https://github.com/determined-ai/infra-eng-team/pull/30
INFENG-74

chore(circleci): switch over to dedicated GCP CI project [INFENG-74]

---

webui/react/src/pages/Settings/UserManagement.test.tsx

WEB-903
adding `jest.useRealTimers();` or other timer doesnt fix this flakiness cuz the test case itself doesnt work due to antd modal ([ref](https://stackoverflow.com/questions/68829540/react-testing-library-testing-ant-design-modal/68843345#68843345)), so just commented out the test case for now.
Adding timer seems work cuz we missed `await` before `waitFor` clause. It doesnt test properly without `await` (false positive). If running test with timer and await, the test case fails anyways. 
- Check if ci are all green

test: comment out flaky test case

---

master/static/migrations/20230208142448_add-update-modified-time-user-table.tx.down.sql

Forgot to add `DROP TRIGGER autoupdate_users_modified_at on users;` in down file. 
- Check the code and see if its good

chore: add `drop trigger` in migration down file

---

webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.tsx
webui/react/src/pages/ExperimentDetails/CodeViewer/IpynbRenderer.tsx

https://determinedai.atlassian.net/browse/WEB-893
Address 2 code viewer issues when viewing notebook files in the experiment code:
1. Correctly identify notebook files. Currently detecting anything that contains the string `.ipynb` to a notebook file, but ran into a case where it's part of the directory name.
2. Handle the case when rendering an invalid notebook file by rendering it as a text file.
Examples of properly handling files:

fix: gracefully handle rendering IPYNB notebook files in code viewer [WEB-893]

---

webui/react/src/hooks/useSettingsProvider.tsx

[WEB-867]
[conversation](https://determined-ai.slack.com/archives/C04FJLZHBEG/p1676058984563539)
- Check if spinner is centered after refreshing page 
[WEB-867]: https://determinedai.atlassian.net/browse/WEB-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix spinner regression

---

harness/determined/exec/prep_container.py

I accidentally broke slurm rendezvous when I started rendezvousing num_slots because of bad deserialization of `DET_SLOT_IDS`.

fix: correct slurm rendezvous

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.rst
docs/cluster-setup-guide/users.rst

Elaboration on usage of the root user  for
Slurm/PBS clusters
Looks like: 
and:

docs: root user usage for HPC

---

harness/determined/exec/tensorboard.py
harness/determined/tensorboard/fetchers/azure.py
harness/determined/tensorboard/fetchers/base.py
harness/determined/tensorboard/fetchers/gcs.py
harness/determined/tensorboard/fetchers/s3.py
harness/determined/tensorboard/fetchers/shared.py
harness/tests/storage/util.py

feat: Support concurrent fetching for TensorBoard metric files [MLG-295]
- Confirm that deploying locally, on AWS and on GCP that the TensorBoard fetchers run concurrently and successfully trigger readiness.
- Building on CircleCI and running the e2e tests 
- Watching https://app.circleci.com/pipelines/github/determined-ai/determined/33230
[MLG-295]: https://determinedai.atlassian.net/browse/MLG-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Support concurrent fetching for TensorBoard metric files [MLG-295]

---

webui/react/src/components/kit/LineChart.tsx

Currently an empty box will be shown if there are not enough charts in a particular row. This PR removes the empty box.
The chart feature switch `f_chart=on` should be on for the duration of the testing. 
1. Navigate to an experiment overview page that has less than `3` unique metrics collected. For example only "accuracy" and "loss". 
2.  Ensure that only one or two charts are shown  (depending on the number of metric) in a row no matter how far you zoom out. 
3.  Ensure that when you zoom in all the charts still show , they will be stacked vertically.
4. In an experiment with no metrics reported (errored/cancelled/paused being the easiest to test). Ensure that no empty charts are shown.
5. In an experiment with `3` or more metrics. Ensure all charts show when you zoom in or out. Also …

fix: remove empty box in chart grid [WEB-892]

---

master/static/srv/enrich_task_logs.py

Somehow this newline, is missing. The system assumes logs end with newlines and the comparable Fluentbit code adds it [here](https://github.com/determined-ai/determined/blob/449c194449ee86c96055bf2ce28c69e955aef81d/master/pkg/fluent/fluent.go#L173).

fix: add missing newline to slurm logs [DET-8943]

---

webui/react/src/components/DeterminedAuth.tsx
webui/react/src/pages/SignIn.module.scss
webui/react/src/pages/SignIn.tsx

WEB-897
- Check if button doesn't overflow even if text is long when SSO is enable
- When SSO is disabled, users don't see SSO section

fix: SSO name layout

---

agent/Makefile

build: Correct typo on PHONY target designation (agent)

---

harness/determined/common/api/analytics.py

[MLG-24]
Previously, if Segment.io analytics failed, it would hang an experiment potentially forever as it tries to reconnect. This makes sure that in the case that we can't connect to the analytics endpoint, that we timeout and allow the experiment to finish.
- Create an experiment with a `startup-hook.sh` that contains:
```shell
export DET_SEGMENT_MASTER_KEY="something"
echo '127.0.0.1 api.segment.io' >> /etc/hosts
```
This will force segment.io to not work. Without the changes in this PR, the experiment will hang on continuously trying to contact the `api.segment.io` endpoint and failing.
[MLG-24]: https://determinedai.atlassian.net/browse/MLG-24?atlOrigin=eyJpIjoiNWRkNT …

fix: Segment Analytics will no longer cause experiment to hang [MLG-24]

---

.pre-commit-config.yaml
harness/determined/cli/user.py
pre-commit/check.py

by default, precommit splits up and parallelize calls to the same hook but our check.py, and our underlying
make checks are not set up to utilize that.
modify local checks pre-commit so that
- it's passed all the changed files at once.
- we skip some unintentional pre-push checks

chore: limit check-all pre-push hook to serial run

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.rst

Fix example in doc. Get agent group name via $(id -gn).

docs: Fix DAI docs det user link-with-agent-user example

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/overview.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst
docs/reference/reference-deploy/config/master-config-reference.rst
docs/reference/reference-training/experiment-config-reference.rst

* Provide inline info about agent-specific scheduling options that do not apply to HPC Launcher configurations.
* Identify enroot-specific differences from docker (like for Singularity)
* Provide reference to custom resource pools as an option to deal with non-homogenous Slurm/PBS partitions.
==
Passed all wording changes through grammerly.com
==
==
==
==

docs: Improvements to HPC launcher docs

---

webui/react/src/hooks/useSettings.test.tsx
webui/react/src/hooks/useSettings.ts
webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.settings.ts
webui/react/src/pages/ExperimentDetails/ExperimentTrials.settings.ts
webui/react/src/pages/ExperimentList.settings.ts
webui/react/src/pages/JobQueue/JobQueue.settings.ts
webui/react/src/pages/Settings/GroupManagement.settings.ts
webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.settings.ts
webui/react/src/pages/TrialsComparison/Actions/useTrialActions.tsx
webui/react/src/pages/TrialsComparison/Collections/useTrialCollections.tsx
webui/react/src/pages/TrialsComparison/Table/settings.ts

Removed all `applicableRoutespace`
[WEB-827]
- Check if CI are all green
- Check if places where useSettings are used doesn't change the behavior as before
- Check if useSettings is working as expected
[WEB-827]: https://determinedai.atlassian.net/browse/WEB-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove `applicableRoutespace`

---

webui/react/src/components/kit/Form.tsx
webui/react/src/hooks/useModal/Checkpoint/useCheckpointFlow.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/Settings/GroupManagement.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/shared/configs/eslintrc.js
webui/react/src/stores/determinedInfo.tsx
webui/react/src/utils/error.ts

[WEB-927]
- Check if all fixes are proper
- Check if Ci are all green
- Check if there's no warning with `make fmt` in `webui/react` dir
- Check if all ESLint rules are `error`, and no `warn` or `warning`
[WEB-927]: https://determinedai.atlassian.net/browse/WEB-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: warning fixes in web

---

.circleci/config.yml

Use g4dn.xlarge for small AWS GPU instances and g4dn.metal for some tests running out of GPU memory.

chore: fix some gpu nightly errors

---

webui/react/Makefile

missing node version
related #6038
- Check if `make live` command works in node v18

chore: missing nodev18

---

webui/react/src/pages/SignIn.module.scss
webui/react/src/pages/SignIn.tsx

[slack link](https://determined-ai.slack.com/archives/CLCE8D998/p1677095505470959)
Centered logo in SSO button
- Check if SSO button logo is centered

fix: SSO layout

---

docs/release-notes/rbac-ntsc-mr.rst

docs: add rbac p2 release notes

---

.bumpversion.cfg
webui/react/vite.config.ts

Manually bump a missing webui version and update the bumpversion config to include the proper files.

chore: manual bump version

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst

Update section of Singularity over PBS known issues.

docs: update Singularity known issues.

---

agent/internal/agent.go

Hand the agent shutdown message. Technically this works right now because the panic shuts us down 🙃 

fix: handle agent shutdown msg

---

webui/react/vite.config.ts

vite version is behind, we should update before release finishes so that it can be bumped properly by bumpversion. 

chore: manually bump vite version

---

e2e_tests/tests/deploy/test_local.py

Test is flaky but hard to pin down, so add some prints for next time.

test: add logging to a flaky test

---

webui/react/src/pages/ModelRegistry.tsx
webui/react/src/services/types.ts

Currently we show all `models` for any `workspace` inside of the `workspace` specific `model registry` page because we have defined a deprecated `workspaceId` api parameter that we previously used to filter for the specific workspace. The deprecated api parameter has been removed and the API call updated. 
1. Navigate to a workspace and the `Model Registry` tab for the workspace. Confirm that you can only see models belonging to the current workspace .
2. Navigate to the `Model Registry` page. Ensure that you can see models for every workspace. 
3. Use the `Workspace` filter in the table and ensure that it correctly filters models.

fix: Unrelated models are shown in a workspace model registry tab

---

e2e_tests/tests/experiment/test_tasks_raw_csv.py
master/internal/core.go
webui/react/src/pages/Cluster/ClusterHistoricalUsage.tsx
webui/react/src/pages/Cluster/ClusterHistoricalUsageCsvModal.tsx
webui/react/src/services/api-ts-sdk/api.ts

Previously the Historic Allocations CSV output was solely at a workload-granularity; however, it produced many rows resulting in the CSV being difficult to read. For [DET-8537], a new endpoint was added to create a CSV at a task-granularity. As well, a select was added to the `ClusterHistoricalUsageCsvModal` where the user can select between workload/task level output.
e2e tests checking if the new task-level endpoint captures results from:
- No_Op Experiment
- Jupyter Notebook
- No_Op Experiment + Tensorboard
Validating that the endpoint returned successfully and that the CSV result returned an entry for each case
DET-8537
[DET-8537]: …

feat: Added task-based historical allocation endpoint [DET-8537]

---

webui/react/src/components/PageNotFound.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/WorkspaceDetails.tsx

WEB-939
`/det/workspaces/1/projects` goes to just an empty page instead of displaying not found page if user doesnt have a permission
[slack conversation](https://determined-ai.slack.com/archives/CKQ3EV0G6/p1677178729755389)
related: #5964 
workspace/project  means workspace page and project page
- Login as a admin
- If admin go to the exist workspace/project page, see a spinner and then workspace/project  contents shows up
- If admin go to the non-exist workspace/project  page, see `not found` page
- Logout and login as a user without permissions
- If the user go to the exist workspace/project  page, see `not found` page
- If the user go to the non-exist workspace/project  page, see `not found` page
- If a user go to the exist workspace/project  page, see a spinner and then workspace …

fix: show `not found` and `spinner` properly

---

examples/deepspeed/gpt_neox/Dockerfile
examples/deepspeed/gpt_neox/startup-hook.sh

Fix docker image and startup hook to work for non-privileged user
Tested locally and on the cloud.

fix: gpt-neox docker image and startup hook for non-privileged user [MLG-332]

---

master/static/srv/enrich_task_logs.py

Turns out some logs did have proper newlines after all, so rather than tracking down all those places and making them consistent, I've just added a newline conditionally.

fix: cleanup logging under slurm

---

webui/react/src/hooks/useModal/JupyterLab/useModalJupyterLab.tsx

Replace defaultValue with initialValue
https://ant.design/components/form#formitem
> You cannot set value for each form control via value or defaultValue prop, you should set default value with initialValues of Form. Note that initialValues cannot be updated by setState dynamically, you should use setFieldsValue in that situation.
- Check if Jupyter modal set initial value correctly

fix: replace defaultValue with initialValue

---

pre-commit/web_lint_check.py

i misunderstood `parser.add_argument`.  `parser.add_argument` cannot have `List[str]`
https://docs.python.org/3/library/argparse.html#type
- Check if pre-commit doesnt fail with `web_lint_check.py: error: argument file_paths: invalid typing.List[str] ` error 

fix: pre-commit web bug fix

---

docs/release-notes/custom-searcher-includes.rst
harness/determined/experimental/client.py
harness/determined/searcher/_remote_search_runner.py
harness/determined/searcher/_search_runner.py
harness/tests/test_custom_searcher.py

chore: allow includes in custom searcher experiment [MLG-338]
When creating a custom searcher from `determined/harness/searcher` like so:
```python
includes = ["dsat"]
search_runner = searcher.RemoteSearchRunner(search_method, context=core_context)
search_runner.run(submitted_config_dict, model_dir=args.model_dir, includes=includes)
```
One can include extra directories for the experiment to mount like the standard `client.create_experiment` function.
[MLG-338]: https://determinedai.atlassian.net/browse/MLG-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: allow includes in custom searcher experiment [MLG-338]

---

.circleci/config.yml
examples/tutorials/mnist_pytorch/startup-hook.sh

Attempt to fix test-e2e-gke-parallel by using T4 for compute instead of K80. A similar change fixed test-e2e-parallel on AWS.
After we bumped the environment references in determined to 0.19.12 (e.g., `determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.8-gpu-0.19.12`) `test_pytorch.py::test_pytorch_parallel` starting failing in `test-e2e-gpu-parallel` and `test-e2e-gke-parallel` workflows. The error in `test-e2e-gpu-parallel` (running on AWS) has been fixed by updating the instance type. This change updates the instance type used by `test-e2e-gke-parallel` in a similar fashion.

fix: test-e2e-gke-parallel use t4

---

.circleci/config.yml

We got an incorrect file downloaded one time [1], so retry this download, like in 2906257f (#5996).
[1] https://app.circleci.com/pipelines/github/determined-ai/determined/34074/workflows/e48681f8-8b75-4349-82eb-06e922d8bfcb/jobs/1202610
Eh, should be good.

ci: retry protoc download

---

master/internal/db/postgres_experiments.go

`JOIN` clause does not effectively do anything in `TrainingMetricsSeries` and `ValidationMetricsSeries` queries, but it makes the query plan worse.
Metrics still look the same.

perf: tweak metrics series query.

---

master/static/srv/enrich_task_logs.py

Depends on an EE PR to fill in `DET_CONTAINER_ID`.

chore: add more metadata to slurm logs

---

master/internal/rm/kubernetesrm/pods.go

Fix for GKE's automatically added quota (which doesn't limit CPU or GPU).

fix: tolerate additional non-CPU, non-GPU quotas in k8s

---

webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss

Follow up of #6117
Texts are overlapped due to header column background color if there are lots of trials to compare
This PR is to add background color for header column
- Open trial comparison with  lots of trials  in multi experiment  detail page
- Check if texts are not overlapped

fix: add bgColor in trial comparison table

---

webui/react/src/hooks/useModal/Checkpoint/useCheckpointFlow.tsx
webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
webui/react/src/pages/TrialDetails/TrialInfoBox.tsx

[WEB-965]
- Go to `/det/experiments/{exp_id}/overview`
- Check if there's no warnings in browser console
[WEB-965]: https://determinedai.atlassian.net/browse/WEB-965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: browser console warnings

---

webui/react/src/components/DynamicTabs.tsx
webui/react/src/components/kit/Pivot.tsx
webui/react/src/pages/DesignKit.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx

WEB-823
- Go to Pivot section in UIKit page
- Check if the first pivot name is `Primary Pivot` instead of Default Pivot and the second pivot name is `Secondary Pivot` instead of `Card Pivot`
- Check if all Pivots work
WEB-823

chore: UIKit Pivot renaming

---

webui/react/src/pages/JobQueue/ManageJob.tsx

fix: correct manage job view

---

e2e_tests/tests/nightly/test_capability.py
examples/computer_vision/detectron2_coco_pytorch/.detignore
examples/computer_vision/detectron2_coco_pytorch/Dockerfile
examples/computer_vision/detectron2_coco_pytorch/Makefile
examples/computer_vision/detectron2_coco_pytorch/README.md
examples/computer_vision/detectron2_coco_pytorch/const.yaml
examples/computer_vision/detectron2_coco_pytorch/const_fake.yaml
examples/computer_vision/detectron2_coco_pytorch/distributed.yaml
examples/computer_vision/detectron2_coco_pytorch/model_def.py

The `nightly` test `test_capability.py::test_detectron2_coco_pytorch_const` was marked to be skipped during the attempt to upgrade default Determined images to use PyTorch 1.12 (see [this PR](https://github.com/determined-ai/determined/pull/5985)).
We have created new images with the latest version of Detectron2, v0.6, updated the experiment configurations accordingly, and made minimal compatibility changes to the experiment code.
`test-e2e-gpu-nightly` will be approved and is expected to be successful.
The previous custom image used in the Detectron2 example (found [here](https://hub.docker.com/r/katport/detectron2)) was built with Detectron2 v0.1.2. 
The new image is built with v0.6, the latest version, which was released in October 2021. The image and example were manually QA'd by the …

chore: update detectron2 example to use v0.6 and reenable nightly test [MLG-301]

---

webui/react/src/components/ProjectCard.module.scss
webui/react/src/components/ProjectCard.tsx

WEB-949
Display icon for workspace below project name on ProjectCards on the dashboard.
On dashboard:
On workspace details page:

feat: display workspace icon in ProjectCard

---

e2e_tests/tests/experiment/test_tasks_raw_csv.py
master/internal/core.go

Improved performance of historical allocation task endpoint by removing training & validation time columns. Modified corresponding e2e test to not check training & validation times. Simplified computation of imagepulling, removing implicit assumption that an allocation begins once the previous allocation ends and using the `start_time` present in `task_stats` 
e2e_tests/tests/experiment/test_tasks_raw_csv.py
Local performance testing was performed using 50k and 100k duplicated task entries in `tasks`, `trials`, `allocations`, `task_stats`, `raw_steps`, `raw_validations`. Local test show a response time of 1 minute for 100k tasks, in original code 55k tasks took 30 minutes complete. …

perf: Historical allocation task endpoint, removed training/validation times

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst

Updated the documentation with the new Slurm task epilog script that better handles Slurm cancelation of podman jobs.
We've had the updated Slurm task epilog script on the znode cluster for about 3 weeks now and have not encountered the issue where the nodes go into the "drained" state due to the podman container not being terminated properly.

fix: FOUNDENG-438 Podman tests from the gate are breaking znodes again

---

webui/react/src/components/kit/Toggle.tsx
webui/react/src/pages/DesignKit.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx
webui/react/src/pages/WorkspaceList.tsx

[WEB-841](https://determinedai.atlassian.net/browse/WEB-841?atlOrigin=eyJpIjoiYTYzMjIxYTVkMjUyNGM5Mzg0NWI2ZTU1MzIzNzMyZGUiLCJwIjoiaiJ9)
Adds Toggle component to UI Kit. Also removes `suffixLabel` prop, since this wasn't used in our app.
[WEB-841]: https://determinedai.atlassian.net/browse/WEB-841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add Toggle component to UI Kit [WEB-841]

---

master/static/srv/enrich_task_logs.py

We were submitting `rank_id` as `rank` and the API was silently not accepting it.
oops.

fix: post rank_id correctly for fluent-less logging [DET-8999]

---

webui/react/src/components/Router.tsx

https://determinedai.atlassian.net/browse/WEB-948
Router should not attempt to render the requested page (or the login page) until after auth check is complete.
If auth check is pending, display a spinner instead of the login page or the requested page.
While logged out
While logged in

fix: render spinner while auth check pending

---

docs/cluster-setup-guide/deploy-cluster/index.rst

Bring content updates over from the beta site.
Add setup options for on prem and k8s as discussed with stakeholders.

docs: Content updates

---

harness/determined/cli/user.py

By popular demand
`det user list` includes user id column.

feat: display user id in `det user list`.

---

webui/react/src/components/kit/Select.tsx
webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx

WEB-1004
- Open Move Experiment modal, and check if width of select component is full width

fix: selection width in `move experiment` modal

---

e2e_tests/tests/experiment/test_tasks_raw_csv.py
master/internal/core.go

Modified `/resources/allocation/tasks-raw` endpoint such that the provided timestamps are used in an interval overlap rather than checking if the timestamps are contained in that range. And adjusted `test_tensorboard_experiment_capture` to ensure the experiment completes prior to starting the Tensorboard.
This resolves `test_task_raw_csv:test_experiment_capture` & `test_task_raw_csv:test_tensorboard_experiment_capture` where to the resulting response was empty due to the task falling outside of the end timestamp.
e2etesting: `e2etests/tests/experiment/test_tasks_raw_csv`

fix: flaky test_tasks_raw_csv & corrected timestamp handling for historical task allocation

---

harness/determined/deploy/gcp/cli.py
harness/determined/deploy/gcp/terraform/main.tf
harness/determined/deploy/gcp/terraform/modules/compute/main.tf
harness/determined/deploy/gcp/terraform/modules/compute/variables.tf
harness/determined/deploy/gcp/terraform/modules/database/main.tf
harness/determined/deploy/gcp/terraform/modules/database/variables.tf
harness/determined/deploy/gcp/terraform/modules/filestore/main.tf
harness/determined/deploy/gcp/terraform/modules/filestore/variables.tf
harness/determined/deploy/gcp/terraform/modules/gcs/main.tf
harness/determined/deploy/gcp/terraform/modules/gcs/variables.tf
harness/determined/deploy/gcp/terraform/modules/network/main.tf
harness/determined/deploy/gcp/terraform/modules/network/variables.tf
harness/determined/deploy/gcp/terraform/variables.tf

This feature allows Determined users to apply a key-value pair called a "label" to the master GCP instance created by a command such as the following:
`det deploy gcp up --cluster-id labeltest --project-id determined-ai --add-label foo=bar --add-label key=value`
This is analogous to the existing feature in deploying Determined to a AWS:
`det deploy aws up ... --add-tag foo=bar --add-tag key=value`
Note that what GCP and AWS call "labels" and "tags" are essentially the same thing: key-value pairs that can be used to filter lists of instances (and can be understood as meaningful by users). Also note that GCP instances have "tags", but these are qualitatively different.
Manually run `det deploy gcp up ... --add-label foo=bar --add-label key=value` and note the label in the Google Cloud …

feat: add labels to GCP instances created with det deploy gcp [MLG-170]

---

ds_autotuning_prototype/README.md
ds_autotuning_prototype/examples/cifar10_example/script.py
ds_autotuning_prototype/examples/ffn_example/autotune_config.yaml

Small fixes to readme, configs, and model code.

fix: readme fix, config edit, and make cifar10 work off grenoble

---

webui/react/src/hooks/useModal/Experiment/useModalExperimentCreate.tsx

This fixes an issue where the experiment fork/continue trial modals would not open again after the user closed the modal via the close button. This is because we overloaded the modal's close handler to toggle switching to the config view. This method is replaced by simply overriding the onClick prop on the cancel button.
WEB-963

fix: Close expiriment fork/ continue trial modal properly

---

webui/react/src/hooks/useModal/Experiment/useModalExperimentCreate.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx

Issue: When user enters a max length (whether it’s epoch, batches, etc - based on the user specified length), the newly created trial ignores it
Navigate to a experiment/trial page, click on "Continue Trial"
Enter "Max batches"
Proceed with network tab open to verify the "Max batches" took effect, it should reflect at `config.searcher.max_length. batches`
This PR deprecates the usage of `useRef<FormInstance>` with `Form.useForm()`
WEB-1007

fix: Continue Trial flow does not take the new `max_length`

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.module.scss
webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx

[WEB-1008]
- Check if experiment move modal is reopen-able
- Check if single/multiple  experiments  are movable
- Replaced `List` with `UIKIt Select` for standardized design 
[WEB-1008]: https://determinedai.atlassian.net/browse/WEB-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: exp move modal

---

master/internal/api_project.go

[WEB-1013]
Added missing `p.archived` in query and removed subquery
- Check if `GetProjectsByUserActivity` api returns the same result as before
- Check if `Archive` /`Unarchive` button works on project card on dashboard page
[WEB-1013]: https://determinedai.atlassian.net/browse/WEB-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add `archived` param and simplify query

---

master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/pod_test.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/request_queue.go
master/internal/rm/kubernetesrm/spec.go
master/pkg/set/set.go

Switch from `map[T]bool` to a more proper set type in some places (just in the Kubernetes RM for now as a start, since I've been working there lately).

refactor: use generic Go set type in more places

---

e2e_tests/tests/experiment/test_allocation_csv.py
master/internal/core.go
webui/react/src/pages/Cluster/ClusterHistoricalUsageCsvModal.tsx

The historical resource allocation tasks endpoint was capturing entries regarding tasks that had not been active in multiple years; additionally the aggregating at the `task` level incorrectly inflates the historical resource allocation times, due to task start & end times containing time where the task had not been scheduled, but was not yet done.
This modifies the endpoint to instead aggregate historical resource allocation data at the `allocation` level instead. This will more accurately reflect expected timing, as well as use a more reliable `end_time` field.
e2e test: `tests/experiments/test_allocation_csv.py`

fix: aggregate historical allocation task endpoint at allocations instead of tasks

---

master/internal/sproto/task.go
master/internal/task/allocation.go

The assigned event is sent correctly for the agent rm, but (confusingly) when the 'resources' are allocated in slurm/k8s, it is just a handle to submit a slurm job/k8s pod, so the CLI can print "something something assigned to an agent" when the task has only been dropped onto the underlying RM's queue. This moves the message (to where allocation start time is set, for the same reason) so it is less confusing.

chore: move assigned event to correct location [DET-9012]

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/install-on-kubernetes.rst
docs/cluster-setup-guide/security/rbac.rst
docs/reference/reference-deploy/config/helm-config-reference.rst

Added some docs on how to set up multi RP in K8s and clarified some RBAC docs

docs: clarified rbac and k8s docs

---

webui/react/src/components/Link.tsx
webui/react/src/components/ProjectCard.tsx
webui/react/src/components/kit/Card.tsx

[WEB-1014]
- Removed `rawLink` as well as fixing issues
- Current bug video https://www.loom.com/share/738007378054438991ddfbfaa5a6150e
- Check if user should be able to click the Card to navigate to another part of the app without an app refresh
- Check if opening a modal from the Card’s action menu dropdown and then clicking should not be registered as a Card-level click
[WEB-1014]: https://determinedai.atlassian.net/browse/WEB-1014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: project card issue

---

bindings/generate_bindings_ts.py
webui/react/src/services/api-ts-sdk/api.ts

This fixes an issue where the typescript api bindings would not properly pass on undefined values for non array or datetime values.
the getWorkspaceProjects endpoint should work in the webui
No Ticket

fix: flip undefined check logic for url params in ts bindings

---

docs/cluster-setup-guide/security/rbac.rst

docs: add rbac progress

---

docs/release-notes/fix-det-user-change-password.rst
e2e_tests/tests/cluster/test_users.py
harness/determined/cli/user.py
harness/determined/common/experimental/determined.py
harness/determined/experimental/client.py

`det user change-password` for changing your own password was broken because of auth.
run `det user change-password` to change your own password.

fix: `det user change-password` for user's own passwords.

---

webui/react/src/shared/configs/eslintrc.js

`make check` passes with the modifications included in this PR (can remove before merging)

chore: remove type/interface member ordering rule from eslint

---

master/internal/user/postgres_users.go

[WEB-1024] <- 2 ^ 10
- Check if user can login with username with capital text
- For example, username `Person` and `person` are distinguished
[WEB-1024]: https://determinedai.atlassian.net/browse/WEB-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: username case sensitive issue

---

master/pkg/actor/prom.go
master/pkg/actor/ref.go
master/pkg/actor/trace.go
tools/devcluster.yaml

Add actor system prometheus metrics.
Wish I had thought of how easy this is ages ago.

feat: collect timing data for actor system internals

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.test.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx

feat: show HPs for Custom Searcher trials on experiment table [MLG-343]
Before:
After:
Run a custom searcher
```shell
cd examples/custom_search_method/asha_search_method
det experiment create remote_search_runner/searcher.yaml .
```
Before this change, the hyperparameters wouldn't display in the experiment table. Now they will.
[MLG-343]: https://determinedai.atlassian.net/browse/MLG-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: show unique HPs for Custom Searcher trials on experiment table [MLG-343]

---

webui/react/src/hooks/useModal/UserSettings/useModalCreateGroup.tsx
webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/services/decoder.ts
webui/react/src/types.ts

Update "Add/Edit User/Group" modal "Role" picker to be "global role"
Assign user to a group with roles, verify that roles associated with user do not show up at edit user modal.
Assign user to a workspace with some role, verify that roles associated with workspace do not show up at edit user modal.
Assign group to a workspace with some role, verify that roles associated with workspace do not show up at edit group modal.
WEB-1010

feat: hide non-global roles on user/group modal

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst

A new bullet item under "Additional Known issues" section:

docs: add HPC Launcher job exit code known issue

---

examples/tutorials/core_api_pytorch_mnist/model_def_metrics.py

requirements: https://github.com/determined-ai/determined/pull/6114

docs: update script for new core api user guide

---

webui/react/src/index.tsx
webui/react/src/router.tsx

Import index.scss where `<App/>` is - issues appear on production build without this.
slack: https://determined-ai.slack.com/archives/CKQ3EV0G6/p1678895401235979
Test this on prod build
Check select dropdowns on `/det/design`
Check buttons on the experiment overview, and text and icon should be aligned well

fix: CSS inside router

---

.circleci/config.yml
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-aws/aws-spot.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-aws/install-on-aws.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-gcp/install-gcp.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/setup-eks-cluster.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/setup-gke-cluster.rst
docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/t4-gpu-default.rst
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml
harness/determined/deploy/gcp/constants.py
harness/determined/deploy/gcp/terraform/variables.tf
harness/determined/deploy/gke/constants.py
master/internal/config/provconfig/aws_config.go
master/internal/config/provconfig/gcp_config.go
master/packaging/master.yaml

Moves from K80 to T4 GPUs for better performance/cost and support.

chore: move from K80 to T4 GPU type defaults

---

agent/go.mod
agent/go.sum
master/go.mod
master/go.sum
master/internal/db/postgres_checkpoints.go
master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/pod_test.go
master/pkg/model/task_container_defaults.go
master/pkg/model/task_container_defaults_test.go
master/pkg/set/set.go

Add a merge func for task container defaults to be used by a later commit in EE.

chore: add merge func for task container defaults [DET-9106]

---

webui/react/src/pages/Cluster/ClusterOverallStats.tsx

Bug screenshot:
Go to cluster page and make sure that the above (screenshotted) bug doesn't appear. This is easiest to test by changing your window size and making sure that the CUDE, ROCM, and/or CPU Slot cards change size in step with all of the other small cards.

fix: correct cluster slots card size [WEB-1028]

---

webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/stores/users.tsx

Fetches list of users whenever a user is added or edited. Ticket calls for handling deletion as well, but I don't see a way to delete users on web.
- Log into an RBAC cluster as admin.
- Navigate to User Management page in Admin Settings
- Create a new user using the "Add user" button/modal
- Newly created user should appear in table without refreshing

fix: update User Management table on new user [WEB-1011]

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/overview.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst

- Clarify the set of Slurm versions not supported now that SchedMD has corrected
- Correct a typo in the preemption docs

docs: Slurm details updates [FOUNDENG-512]

---

webui/react/src/utils/observable.ts

Just missing an unsubscribe upon the unmounting of the observable hook.

chore: minor cleanup in useValueMemoizedObservable

---

harness/determined/core/_checkpoint.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py

Since `CheckpointContext` now supports sharding, the workloads loop in `DeepSpeedTrialController` does not need to collect data spread across nodes.
Run some Deepspeed examples and note that checkpoints are being created as expected (same files of approximately the same sizes as before these changes). This includes the saving and loading of checkpoints when experiments are paused and unpaused.
The following examples and configurations thereof ran without errors and without new warnings:
- `cifar10_cpu_offloading`
- `zero_3_cpu_offload.yaml`
- `cifar10_moe`
- `zero_stages.yaml` with ZeRO stage 3
- `gpt_neox`
- `19M.yml`
- `global_num_gpus/pp_size/mp_size = 1` 
- `global_num_gpus/pp_size/mp_size = 2`
Dynamic agent instances were of type `g4dn.4xlarge` or `g4dn.12xlarge`.
The above …

chore: take advantage of CheckpointContext handling sharded data [MLG-13]

---

harness/tests/cli/test_experiment.py
harness/tests/common/api_server.py

* Made the functionality of the flaky test more explicit
* Split up previous non-flaky test into two tests
* New "succeeding" wait test tests that "wait" waits until the experiment is completed.

test: Small refactor of CLI experiment tests

---

master/internal/task/allocation.go

fix: handle results of polling updates in allocation actor

---

webui/react/src/components/ActionSheet.tsx
webui/react/src/components/kit/IconicButton.tsx
webui/react/src/components/kit/LogViewer/LogViewer.tsx
webui/react/src/pages/DesignKit.tsx

Fix all browser warnings including UIKit page 
- Check if there's no warnings in browser console, and validly fixed warnings

fix: browser warnings

---

harness/determined/common/storage/shared.py
harness/tests/storage/test_shared_fs.py
harness/tests/storage/util.py

chore: do not error on shared_fs delete for nonexistent paths [MLG-378]

---

webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx

Fix the problem of a permanent spinner showing on the model version header section.
WEB-1065

fix: remove perpetual spinner

---

webui/react/src/hooks/useModal/Model/useModalModelVersionEdit.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelDetails/ModelHeader.tsx
webui/react/src/pages/ModelVersionDetails.tsx
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx

[WEB-1016]
- Data will be reflected immediately after editting name and/or description
- Description is now in modal to edit
- Check if data is reflected immediately after editting name and/or description
- Check if description in edit modal works in model and model version page
[WEB-1016]: https://hpe-aiatscale.atlassian.net/browse/WEB-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: reflect data immediately in model page and model version page

---

webui/react/src/hooks/useModal/UserSettings/useModalPasswordChange.tsx

[WEB-1066]
- Create a new user
- Login as the new user
- Change the password from settings page
- Check if user can change password correctly with empty password
- Login with a new password
- Try to change it again 
- Check if user can change password correctly again with non-empty password
[WEB-1066]: https://hpe-aiatscale.atlassian.net/browse/WEB-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: login validation

---

webui/react/src/hooks/useModal/UserSettings/useModalCreateUser.tsx
webui/react/src/pages/Settings/UserManagement.tsx

Resetting some web files which somehow weren't aligned with latest master. 

reset webui to latest master

---

master/internal/core.go

Static assets have moved to a new `/det/assets` location and are no longer served as gzip as a result. Update gzip static paths to match the new location to serve static assets as compressed gzip files.
BEFORE:
AFTER:
WEB-1032

fix: update webui static gzip path regex

---

master/internal/api_master.go

```
hbp ➜ determined git:(master) det dev curl /api/v1/resources/allocation/raw
{
"error": {
"code": 13,
"reason": "Internal",
"error": "no start time provided"
}
}
hbp ➜ determined git:(master) gco -
Switched to branch 'allocs-status-code'
Your branch is up to date with 'origin/allocs-status-code'.
hbp ➜ determined git:(allocs-status-code) det dev curl /api/v1/resources/allocation/raw
{
"error": {
"code": 3,
"reason": "InvalidArgument",
"error": "no start time provided"
}
}
hbp ➜ determined git:(allocs-status-code)
```
DET-9147

fix: fix err status code for ResourceAllocationRaw

---

.circleci/config.yml

bump gke to version 1.23.
CI works.

ci: bump gke version to 1.23

---

webui/react/src/pages/TrialDetails/F_TrialDetailsOverview.tsx

1. Go to a Trial Details page
2. Add `?f_chart=on` to the end of the URL (make sure there aren't any other query params)
3. You should see the new chart experience with the Trials Workloads table below it

feat: show TrialWorkloads table when f_chart is on [WEB-1025]

---

master/internal/db/postgres_experiments.go

Straight up bug, we are missing the STOPPING_KILLED enum when grabbing non-terminal experiments to recover. This causes STOPPED_KILLED experiments to 'hang' because we never transition them to CANCELED.

fix: correctly handle stopping_killed experiments on restart

---

harness/determined/exec/prep_container.py

Easy and cheap way to trace hardware errors after they have occurred.

feat: log gpu information in task logs [MLG-234] [DET-5274]

---

e2e_tests/tests/test_sdk.py
harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/common/experimental/trial.py
harness/determined/experimental/client.py

- checkpoint.delete()
- method to get multiple checkpoints from a trial

feat: checkpoint delete in python SDK [MLG-377]

---

harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py
harness/determined/pytorch/deepspeed/dsat/_run_dsat.py
harness/determined/pytorch/deepspeed/dsat/_utils.py

linting fixes

---

master/internal/rm/agentrm/agent_slot.go

fix: fix disable slot unexpected msg [DET-9155]

---

examples/integrations/hf_trainer_api/image_classification.py

Fixing a bug in examples/integrations/hf_trainer_api.py
main() function was not defined properly.
Run the example locally

fix: tb_callback not found

---

docs/reference/reference-deploy/config/master-config-reference.rst

Properly document task_container_defaults inheritance for global, partition_overrides, and resource_pools.
Provide an example of partition_overrides.
Document case insensitivity of partition_overrides.
- Verified with grammarly.com
---
---
---
DET-9120

docs: Improve task_container_defaults docs [DET-9120]

---

webui/react/src/stores/users.tsx

This PR fixes two bugs in the user store. As a reminder you should never call `.get()` on an observable outside of an _action_ or if you're absolutely sure you only need the value of the observable at one point in time.
While signed in as admin
- Repeatedly refresh /det/settings/account. You should never see a Large U as the user avatar.
- Repeatedly refresh /det/admin/user-management?sortDesc=false&sortKey=SORT_BY_NAME&tableLimit=100. You should never see Missing / no visible table
N/A

fix: Fix user store

---

docs/interfaces/proxy-ports.rst
docs/release-notes.rst

docs: fix release note

---

webui/react/src/components/ProjectCard.module.scss
webui/react/src/components/ProjectCard.tsx

[WEB-1044]
- Check if project name font size is `13px`
- Check if workspace icon's width and heights are `20px`
- Check if layout doesnt get messy with various project name length
[WEB-1044]: https://determinedai.atlassian.net/browse/WEB-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: font and layout fix in project card

---

harness/determined/pytorch/_pytorch_trial.py

fix: skip op assert in test mode

---

harness/determined/deploy/gcp/constants.py
harness/determined/deploy/gcp/terraform/variables.tf

Fixes an issue with `det deploy gcp up` defaults requesting too many GPUs for GCP.
DET-9163

chore: reduce GPU count for GCP deployments

---

master/internal/db/postgres_tasks.go

Slurm code was checking this, instead. Figure it makes enough sense to do this.

fix: close open allocations terminates, too

---

master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go

fix: remove extra markResourcesStarted call

---

e2e_tests/tests/cluster/test_agent_disable.py
master/internal/rm/agentrm/agent_slot.go

fix the shared utility that patches slot state which used to ignore the input and always noOp-ed.
DET-9173
added a test. see it fail https://app.circleci.com/pipelines/github/determined-ai/determined/35576/workflows/53407cd9-15bb-4702-a745-224da65f8320/jobs/1270058 . add the fix

fix: fix patchSlotState

---

webui/react/src/pages/ModelVersionDetails.tsx

[WEB-1094]
- Go to note tab in  model version
- Edit note and save it
- Check if no page refresh is triggered 
[WEB-1094]: https://hpe-aiatscale.atlassian.net/browse/WEB-1094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: avoid unnecessary refresh in model version node

---

webui/react/src/components/kit/Select.tsx
webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx
webui/react/src/hooks/useModal/Model/useModalModelMove.tsx
webui/react/src/pages/DesignKit.tsx

[WEB-1082]
- Check if filter in `move experiment` modal works
- release party bug
[WEB-1082]: https://hpe-aiatscale.atlassian.net/browse/WEB-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: workspace modal filter

---

webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx

style: fix button arrangement

---

master/internal/task/allocation.go
master/pkg/model/task_container_defaults.go
master/pkg/model/task_container_defaults_test.go

`MergeIntoExpConfig` already made the decision (and it is documented) to append `sbatch_args` so change this logic append lists.

chore: tweak task_container_defaults.sbatch_args merging logic

---

master/internal/experiment.go

fix: log and skip invalid request(trial) id, don't kill experiment
N/A

fix: log and skip invalid request(trial) id, don't kill experiment

---

master/pkg/actor/context.go
master/pkg/actor/system.go

Backport actor wildcard support to OSS. Actors can register with a wildcard address (eg `sproto.AgentsAddr.Child("*")`) rather than registering children individually.
Also backports a convenience function, `RespondCheckError`, to help reduce actor response code complexity.

chore: backport wildcard actor lookup

---

webui/react/src/components/NavigationSideBar.module.scss
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/pages/DesignKit.module.scss
webui/react/src/pages/DesignKit.tsx
webui/react/src/shared/components/Page/Page.tsx

[WEB-1053]
>A document must not have more than one [main](https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element) element that does not have the [hidden](https://html.spec.whatwg.org/multipage/interaction.html#attr-hidden) attribute specified.
https://html.spec.whatwg.org/multipage/grouping-content.html#the-main-element
- Check if there is only 1 `<main>` tag in each HTML document
- Check if there's no design change
[WEB-1053]: https://hpe-aiatscale.atlassian.net/browse/WEB-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: replace unnecessary main tags

---

webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelVersionDetails.tsx

[WEB-1114]
similar to #6070
- Check if not found page is shown if model or model version doesn't exist
- Check if model or model version page is shown if model or model version exists
[WEB-1114]: https://hpe-aiatscale.atlassian.net/browse/WEB-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: gently handle `not found page` in model and model version pages

---

docs/release-notes/remove-det-deploy.rst
harness/determined/deploy/__main__.py
harness/determined/deploy/cli.py
harness/setup.py

Long overdue, resurfaced after a backlog deep dive session.
`det deploy` still works, `det-deploy` is gone.

chore: remove deprecated `det-deploy` executable [DET-5171]

---

webui/react/src/components/InfoBox.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx

chore: implement experiment details header section using InfoBox [WEB-1064]

---

docs/interfaces/proxy-ports.rst
examples/features/ports_flask/README.md
examples/features/ports_flask/hello-client.py
examples/features/ports_flask/hello-client.yaml
examples/features/ports_flask/hello-server.py
examples/features/ports_flask/hello-server.yaml
examples/features/ports_flask/startup-hook.sh

- fix an incorrect command in the docs.
- add another example for generic proxy configs, inspired by an OSS use case.
Try the example.

docs: add a simpler proxy configs example, fix typo in proxy ports guide.

---

docs/training/apis-howto/api-pytorch-ug.rst
harness/determined/pytorch/_pytorch_context.py

docs: add docs for torch profiler support [MLG-179]

---

webui/react/src/components/ModelCreateModal.tsx

Follow up of #6378
I found a bug that metadata is not correctly stored when model is newly created.  I also added type fix. 
- Check if metadata is stored correctly when model is cerated

fix: set default value for create model modal

---

.circleci/config.yml

Previous attempt: https://github.com/determined-ai/determined/pull/6393
We want a smaller range and to only specify a range for the subnets.
Successful run:
https://app.circleci.com/pipelines/github/determined-ai/determined/35929/workflows/2b87faff-2c4e-41ee-a10c-894fe62f0786/jobs/1287163
CI is green. Shouldn't need manual testing.

chore: allocate less address space in e2e gke cluster tests [DET-9231]

---

webui/react/src/pages/ProjectDetails.tsx

fix: dont hardcode explist flag to true

---

.github/workflows/check-rebaseable.yml

Inform users in the github action when the rebaseability check fails and the information necessary to figure out what to do about it
https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1295450385/GitHub+Check+Rebaseable+Test
Should not need manual testing. This is github action specific

chore: show error message that links to git rebaseability page

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst

Update to describe certain limitations in the HPC cluster environment.

docs: slot command limitations for HPC clusters

---

master/internal/config/config.go
master/internal/config/provconfig/config.go
master/internal/config/resource_pool_config.go
master/internal/rm/agentrm/agent_resource_manager.go

Startup scripts are often used to setup various auth (e.g. docker credentials), and thus may contain secrets. Let's blur them out like we do for passwords, telemetry keys and other secrets.
- Deploy MLDE cluster using docker credentials `det deploy ... --docker-user ... --docker-password ...`
- Make sure these credentials are not visible in master config or cluster -> resource pool card -> config.

feat: treat instance startup script as a secret [DET-9214]

---

Makefile
examples/tests/requirements.txt

* Unpin pandas. Pin caused test failures. Prior pinned version (1.0.3)
no longer works with tip numpy.
* Unpin torchvision. Pin was unnecessary.
* Remove torch requirement. This requirements.txt is meant only as
*additional* requirements after determined has been installed. torch
already exists in determined's requirements.txt. I've verified that
the current version pinned there (1.9.0) also works here.
[MLG-359]
In a clean python environment:
1. `pip install -r requirements.txt`
2. `pip install -r examples/tests/requirements.txt`
3. `make -C examples test`
[MLG-359]: https://hpe-aiatscale.atlassian.net/browse/MLG-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …

test: examples test requirements.txt maintenance.

---

master/internal/api_experiment.go
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts
webui/react/src/types.ts

Use `/api/v1/experiments-search` API for experiment list table.
Navigate to any project details page, open network tab to verify that we are using the new `/api/v1/experiments-search` API with correct project ID.
Scroll page and verify offset for API request changes.
WEB-1001

chore: Use experiment-search API for new experiment list table

---

e2e_tests/tests/cluster/test_checkpoints.py
e2e_tests/tests/cluster/test_logging.py
e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/fixtures/no_op/model_def.py
harness/determined/common/api/logs.py
master/internal/api_trials.go
master/internal/db/postgres_trial_logs.go
master/internal/elastic/elastic_task_logs.go
master/internal/elastic/elastic_trial_logs.go
master/pkg/model/experiment.go
master/pkg/model/task.go
master/pkg/protoutils/protoconverter/converter.go

Removed:
- Deprecated message field from TrialLog
- `Resolve` function used to resolve that message field
- Message field in TrialLogsResponse
Ran existing testing suite
DET-8983

refactor: removed message field from TrialLog [DET-8983]

---

docs/reference/reference-deploy/config/master-config-reference.rst

docs: fix `public_ip` misinformation [DET-7014]

---

e2e_tests/tests/cluster/test_checkpoints.py
e2e_tests/tests/cluster/test_logging.py
e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/fixtures/no_op/model_def.py
harness/determined/common/api/logs.py
master/internal/api_trials.go
master/internal/db/postgres_trial_logs.go
master/internal/elastic/elastic_task_logs.go
master/internal/elastic/elastic_trial_logs.go
master/pkg/model/experiment.go
master/pkg/model/task.go
master/pkg/protoutils/protoconverter/converter.go

Reverts determined-ai/determined#6253
Reason: UI still uses message field

revert: return message field from TrialLog [DET-8983]

---

harness/determined/common/experimental/experiment.py

validation metrics in a checkpoint is nullable. don't puke.

fix: do not error on nullable validation metrics [MLG-403]

---

.gitignore
go.work
proto/Makefile

Creates a `go.work` file which enumerates any subdirectories containing a `go.mod` file. This allows editors and go tooling (eg the go language server) to operate correctly from the top level directory, and removes the need to open subdirectories as individual projects. This update also modifies `proto` swag output to only emit json, as the generated but unused `docs.go` emits linting errors.

chore: add go workspace for dev use

---

master/internal/task/allocation.go

Determined on HPC clusters used an alternate path for rendezvous, but our preemption logic already checked if rendezvous on the traditional path was ready to determine if something should be gracefully preempted or killed, causing HPC jobs to always get killed.
`det e pause` doesn't involve slurm in the termination at all, as it should work
```
[2023-04-04T20:16:20.520675Z] [cont=0] || INFO: [3734213] root: Validating checkpoint storage ...
[2023-04-04T20:16:20.531478Z] [cont=0] || INFO: [3734213] root: Launching: ['python3', '-m', 'determined.launch.horovod', '--autohorovod', '--trial', 'model_def:MNistTrial']
[2023-04-04T20:16:31.758060Z]          || INFO: gracefully terminating allocation's remaining resources (reason: user requested pause)
[2023-04-04T20:16:33.649788Z] [cont=0] || …
```

fix: do not skip graceful preemption for tasks using alternate rendezvous path [DET-9258]

---

webui/react/src/pages/ExperimentDetails/ExperimentDetails.tsx

Experiment detail page blank for experiments not found
Navigate to single trial and multi trials experiment details page to verify everything load as expected.
Change URL to an experiment not exist (or no permission), there should be a 404 page instead of blank page.
WEB-1077

fix: Show page not found on experiment details [WEB-1077]

---

harness/determined/searcher/_search_runner.py

https://determined-ai.slack.com/archives/C04645NHSP6/p1680098952436249

populate the custom searcher logs with the correct event

---

.circleci/scripts/get_output_from_stack.py

```
output_value = list(filter(lambda d: d["OutputKey"] == output_key, stack.outputs))[0][
TypeError: 'NoneType' object is not iterable
```

fix: account for missing aws stack outputs [DET-9255]

---

e2e_tests/tests/cluster/test_checkpoints.py
e2e_tests/tests/cluster/test_resource_manager.py
e2e_tests/tests/command/test_run.py
e2e_tests/tests/command/test_tensorboard.py
e2e_tests/tests/conftest.py
e2e_tests/tests/deploy/test_local.py
e2e_tests/tests/experiment/test_custom_searcher.py
e2e_tests/tests/experiment/test_profiling.py
e2e_tests/tests/template/test_template.py
harness/determined/cli/job.py
harness/determined/deploy/aws/gen_vcpu_mapping.py
harness/determined/deploy/aws/preflight.py
harness/determined/deploy/local/cli.py
harness/determined/deploy/local/cluster_utils.py
harness/determined/deploy/local/docker-compose.yaml
harness/setup.py
harness/tests/experiment/fixtures/pytorch_onevar_model.py
tools/scripts/bumpenvs.py
tools/scripts/refresh-ubuntu-amis.py
tools/scripts/update-bumpenvs-yaml.py

Reverts determined-ai/determined#6386

Revert "chore: remove docker-compose from det deploy local [MLG-37]"

---

harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py

fix: search state accounting

---

docs/release-notes/fix-zero-slot-limits.rst
e2e_tests/tests/command/test_run.py
master/internal/rm/kubernetesrm/spec.go

https://determined-community.slack.com/archives/CV3MTNZ6U/p1680628926074179
Run zero slot trial or command with requests or limits override in the pod spec.

fix: podspec requests/limits for zero slot workloads [DET-9257] 

---

CONTRIBUTING.md

chore: tweak Go, Python versions in dev setup instructions

---

master/internal/api_experiment.go
master/internal/api_model.go

[WEB-1117]
https://user-images.githubusercontent.com/109113616/229638211-7d4d2955-f56b-4070-a5cc-d4ec474bc004.mov
- Go to the pages where tags(labels) are used (experiment detail, model detail page, model version page)
- Create the same name labels
- Check if no duplicate labels are saved
[WEB-1117]: https://hpe-aiatscale.atlassian.net/browse/WEB-1117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: avoid duplicate labels

---

harness/determined/pytorch/deepspeed/dsat/_defaults.py
harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py
harness/determined/pytorch/deepspeed/dsat/_run_dsat.py
harness/determined/pytorch/deepspeed/dsat/autotune.py

This PR adds a super simple searcher for testing purposes, `SimpleBatchSearch`, which does a model profiling info run and then just submits follow on Trials with (per gpu) batch sizes ranging from 2 to `tuner_num_trials`, as set in the config. There is no logic to the search.
A `--tuner-type/-t` flag was also set to the `dsat.autotuning` which allows you to switch between searchers.  The default is `-t random`; use `-t simple` to run the `SimpleBatchSearch` test searcher instead.

feat: add simple linear batch test searcher

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/custom-pod-specs.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/overview.rst

docs: modified docs for clarity and k8s pod security

---

examples/tutorials/core_api_pytorch_mnist/distributed.yaml
examples/tutorials/core_api_pytorch_mnist/model_def_adaptive.py
examples/tutorials/core_api_pytorch_mnist/model_def_checkpoints.py
examples/tutorials/core_api_pytorch_mnist/model_def_distributed.py
examples/tutorials/core_api_pytorch_mnist/model_def_metrics.py

Both types of continuations tested and ready for review

feat: add Core API pytorch mnist tutorial update

---

e2e_tests/tests/cluster/test_proxy.py
examples/features/ports/startup-hook.sh

We install `pynvml` in our environment images. Apparently, now it's more kosher to use `nvidia-ml-py`. Generally, the two are the same, but `gpustat` package (dependency of `ray`) does some low-level hacky stuff which requires `nvidia-ml-py`.
This has caused the ray dashboard to break.
Also tweak the polling a bit for the ease of debugging if it happens again.
Need follow-up work to replace pynvml with nvidia-ml-py in the images.

test: fix ray tests [DET-9267]

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-aws/install-on-aws.rst
docs/reference/reference-deploy/config/master-config-reference.rst

Remove leftover K80 mentions, correct the aws quota facts.

docs: remove leftover K80 mentions.

---

webui/react/src/components/kit/LogViewer/LogViewerSelect.tsx
webui/react/src/hooks/useSettings.ts

Fix issue of log viewer filters not working.
Fix issue of log viewer filter reset not working.
Fix issue of log viewer reset button not showing when search text exists.
Looks like the culprit was a `useState` wrapping around an observable. Changes were referencing the state object, which doesn't change when the contents of the observable changes. The `memoized` state was updated to remain an observable and using `useObservable` directly (without `useState`) to point to the state directly so changes are detected properly.
WEB-1129
WEB-1134

fix: update settings observables to detect changes

---

harness/determined/pytorch/deepspeed/dsat/__init__.py
harness/determined/pytorch/deepspeed/dsat/_defaults.py
harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py

Refactored various elements. The `DSATModelProfileInfoTrial` class which tracks the model profiling info run is now a super class of `DSATTrial`, the `DSATTrialTracker` also handles the config processing, and various other cleanups throughout. 

fix: searcher refactor

---

.circleci/config.yml
model_hub/model_hub/mmdetection/_data.py
model_hub/model_hub/utils.py

[MLG-359]
This PR consists of two changes:
1. A couple patches in `model_hub` that set typing such that mypy==0.910 passes under Python 3.8. This likely means `make check` will fail on these files under Python 3.7.
2. A change to the docker image used in CircleCI making CI checks run using Python 3.8 instead of 3.7.
Release will progress in the following steps:
1. A new cimg-base will be built from https://github.com/determined-ai/determined-ci-images/pull/9. It will be pushed to dockerhub with the tag 'py38'.
2. This build will run its CI tests using `determinedai/cimg-base:py38'
3. Assuming pre-commit tests are green, this PR will be merged.
4. If post-commit tests are green, a `cimg-base` with the tag `latest` will be built from the determined-ai/determined-ci-images PR …

build: Updates Python used in CircleCI to 3.8.16

---

e2e_tests/tests/cluster/test_master_restart.py

We assert for a message in logs but there is no guarantee the log will have been written by the time we ask.
CI passes a bunch
Could be something else but this seems like a possibility and an overall improvement.

test: fix race checking for trial logs in missing_docker_container [DET-8933]

---

.circleci/config.yml

Now that `determinedai/cimg-base:latest` has 3.8.16, we can revert the change to config.yaml to again pull latest.
This is step 5 in (and a continuation of) #6391.
[MLG-359]
CircleCI tests are green that should be green (this change affects the Docker image many CircleCI tests use)
[MLG-359]: https://hpe-aiatscale.atlassian.net/browse/MLG-359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: Some CircleCI tests begin with a python 3.8.16

---

docs/_templates/article-header-buttons.html
docs/_templates/toggle-primary-sidebar.html

On docs site: "Release Notes", "Set Up", and "Reference" links in the header should work
WEB-1148

docs: fix links

---

.github/workflows/pre-commit.yml
.github/workflows/publish-helm.yml
.github/workflows/scan-docker-images.yml

In a few cases, we had actions using a full version string or master branch.
For the actions/checkout actions, the mix was confusing dependabot, which failed to update For yq, the action is released frequently enough that using v4 makes more sense than master
Run CI. :)

ci: github actions consistently use major version

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/overview.rst

for readability
origin: PR #6471

docs: minor edit pod security

---

.circleci/config.yml

CI is failing due to codecov removing their pip package. their migration guide suggests installing their uploader binary.

fix: install codecov uploader in CI

---

e2e_tests/tests/cluster/test_logging.py

Add a better exception to get raised when logging test times out.

chore: better error messages for logging test [DET-9280]

---

e2e_tests/tests/cluster/test_rbac.py

Fix a lint issue in e2e test code reported by the recent flake8-comprehensions release

chore: fix a lint issue in e2e test code

---

tools/scripts/replicate-metrics.py

chore: address mypy lint warnings [DET-9334]

---

.circleci/config.yml

Saw a failure on this [1], so throw a retry on there.
[1] https://circleci.com/gh/determined-ai/determined-ee/242727

ci: retry Go download even more

---

e2e_tests/tests/cluster/test_rbac.py

chore: simplify logic and improve naming in an RBAC test

---

harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py

Deleted old code which accidentally overwrite a property and added a attr to the init, where it should have been all along.

fix: minor cleanup

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/ExperimentMoveModal.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.module.scss
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
webui/react/src/pages/F_ExpList/glide-table/contextMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/useGlasbey.ts
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts
webui/react/src/types.ts

Note: The bulk delete api is currently a no-op on the backend, that functionality will be implemented separately.
- Edit button becomes visible when rows are selected and vanishes when they aren't
- Count on Edit button reflects number of rows selected (including "All") if all are selected
- Bulk actions trigger correctly when specific experiments are selected and when all experiments in the list are selected 

feat: add bulk actions to glide table [WEB-981]

---

.circleci/config.yml

We are using Python 3.8 pretty much everywhere else (exceptions are that we have `mypy` configured for 3.7, we test the harness CLI against Python 3.7 among later versions, and we are still building images with Tensorflow 1 and Python 3.7).
We will be supporting TensorFlow 2.12 soon, which requires Python 3.8.

chore: bump default python version to 3.8 in CircleCI

---

docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/launch-error.rst

chore: update launch_error docs and add release notes

---

harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py
harness/determined/pytorch/deepspeed/dsat/autotune.py

Rather than forcing subclasses to overwrite a single `get_new_searcher_ops_list` method which needs to cover all cases,
split this into two methods: `get_trials_after_validation_completed` and `get_trials_after_early_exit`.  These methods also just return iterables of `DSATTrial` instnaces, rather than operations, which seemed conceptually cleaner and simplifies things a little technically.

feat: deepspeed autotune trial based methods

---

master/Makefile

these seem closer to test dependencies and slow down `master build`

build: take mockery out of master build path

---

harness/MANIFEST.in

previously docker-compose.yaml 

chore: remove yaml from manifest

---

docs/interfaces/webui-if.rst
docs/tutorials/pytorch-mnist-tutorial.rst

Make the WebUI page more user friendly and improve algolia and google search crawler results by adding headings and links to more information and ways to work with the WebUI.

docs: Improve the WebUI page

---

.circleci/config.yml
.github/dependabot.yml
webui/react/Makefile

A couple of changes necessary for the master->main default branch rename
YOLO!  This may well fail CI because the branch hasn't been moved yet. :)
This should probably be rebased into -EE fairly soon after merging and the corresponding branch rename as well.

ci: master main rename

---

master/internal/api_trials_intg_test.go

Fixes this error
```
internal/api.go:1: : # github.com/determined-ai/determined/master/internal [github.com/determined-ai/determined/master/internal.test]
internal/api_trials_intg_test.go:449:3: unknown field XAxis in struct literal of type apiv1.CompareTrialsRequest
internal/api_trials_intg_test.go:449:24: undefined: apiv1.XAxis_X_AXIS_BATCH (typecheck)
```
introduced by 2 concurrent changes:
https://github.com/determined-ai/determined/pull/6566
https://github.com/determined-ai/determined/pull/6578

fix: update test to reflect change in CompareTrialsRequest

---

.circleci/config.yml
e2e_tests/pytest.ini
e2e_tests/tests/conftest.py
e2e_tests/tests/deploy/test_local.py
e2e_tests/tests/model_hub/test_mmdetection.py

ci: quarantine some flaky tests

---

.circleci/config.yml

Moving the quarantined test suite out of the general test workflow so that it doesn't block PR merging.
Check CI after pushing.

ci(circleci): split-off quarantined e2e tests

---

webui/react/src/pages/F_ExpList/glide-table/columns.ts

The `Searcher Metric Values` column being short in width makes the table look like it's being cut off on the right, but the column just needs widening.
BEFORE:
AFTER:
WEB-1174

fix: widen the Searcher Metric Values column [WEB-1174]

---

ds_autotuning_prototype/trial_classes/ffn_example/startup-hook.sh
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py

Fixed a minor typo which caused DS AT to break for Trial classes. 
Also fixed a typo where I sent the `Shutdown` class instead of a `Shtudown()` instance

fix: minor bug broke Trial class DS AT

---

master/internal/db/postgres_trial.go
master/internal/db/postgres_trial_intg_test.go

fix an internal bug that lead to unnecessary recomputation of total_batches for trials
added a test

perf: remove unnecessary full trial.total_batches recomputes

---

harness/determined/pytorch/_pytorch_trial.py
harness/tests/experiment/pytorch/test_pytorch_trial.py

fix: fix validation before logic

---

harness/determined/cli/project.py
harness/determined/cli/workspace.py

the key names had gone out of date after a batch rename
of enums in py bindings in the following commit:
588306fa195ab614c7077c6c0c7e38172564c8a9
run 
- det workspace ls
- det workspace list-projects Uncategorized
- det project ls Uncategorized
visual inspection of 
```
ag '\.v1[^ ]*\['
and 
ag 'bindings\.[^ ]*\['
```

chore: fix mismatching enum keys

---

webui/react/src/App.tsx
webui/react/src/components/BatchActionConfirmModal.test.tsx
webui/react/src/components/BatchActionConfirmModal.tsx
webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/TaskActionDropdown.tsx
webui/react/src/components/TaskBar.tsx
webui/react/src/components/TaskList.tsx
webui/react/src/components/kit/Confirmation.test.tsx
webui/react/src/components/kit/Confirmation.tsx
webui/react/src/components/kit/Modal.tsx
webui/react/src/components/kit/useConfirm.test.tsx
webui/react/src/components/kit/useConfirm.tsx
webui/react/src/omnibar/tree-extension/trees/actions.tsx
webui/react/src/pages/DesignKit.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
webui/react/src/pages/InteractiveTask.test.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
webui/react/src/shared/components/ActionDropdown/ActionDropdown.test.tsx
webui/react/src/shared/components/ActionDropdown/ActionDropdown.tsx
webui/react/src/utils/dialogApi.ts

- Add Batch Action Confirmation Modal and apply the updated `useModal` pattern.
- Add tests for Batch Action Confirmation Modal.
- Abstract Confirmation Modal to the UI Kit and replace the antd/dialogApi `modal.confirm` with the abstracted confirmation modal.
- Add tests for Confirmation Modal.
- Add `Confirmation Modal` to the Design Kit.
NOTE: 2nd round for this work. 1st round can be found [here](https://github.com/determined-ai/determined/pull/6559)
WEB-1132
WEB-1133

refactor: remove dialogApi modal dependency [WEB-1132, WEB-1133]

---

.gitignore
agent/cmd/determined-agent/run.go
agent/internal/agent.go
agent/internal/container/container.go
agent/internal/container/container_runtime.go
agent/internal/containers/manager.go
agent/internal/options/options.go
agent/pkg/docker/docker.go
agent/pkg/docker/docker_api_test.go
agent/pkg/docker/events.go
agent/pkg/singularity/singularity.go
agent/pkg/singularity/singularity_api_test.go
master/determined.code-workspace
master/internal/rm/kubernetesrm/pod_test.go
master/pkg/archive/archive.go
master/pkg/etc/etc.go
master/pkg/tasks/const.go
master/pkg/tasks/task.go
master/pkg/tasks/task_gc.go
master/static/srv/enrich_task_logs.py
master/static/srv/singularity-entrypoint-wrapper.sh
master/static/srv/sshd_config
master/static/srv/task-logging-setup.sh

feat: singularity support

---

webui/react/src/stores/cluster.tsx

This fixes an issue where the cluster store would poll without waiting for the previous request to return. We fix this by decoupling the standalone request functions (one of which is used in a modal) from the overall polling logic.
Check network activity on page -- there should only be one agents request in flight at a time.

fix: fix cluster store polling

---

examples/computer_vision/cifar10_tf_keras/cifar_model.py
examples/computer_vision/iris_tf_keras/model_def.py
examples/computer_vision/unets_tf_keras/model_def.py
examples/decision_trees/gbt_titanic_estimator/model_def.py
examples/gan/dcgan_tf_keras/model_def.py
examples/gan/pix2pix_tf_keras/pix2pix/discriminator.py
examples/gan/pix2pix_tf_keras/pix2pix/generator.py
examples/tests/test_official.py
examples/tutorials/fashion_mnist_tf_keras/model_def.py

We should avoid putting `#TODO`s in our example code. Examples should be complete and correct, given whatever state the `determined` code is in. Put another way, examples should show how Determined is awesome, not how it's busted or janky.
Create a Jira issue or GitHub ticket when there's something missing in Determined or if an example can be improved!

fix: remove TODOs from examples

---

CONTRIBUTING.md

update the contributor's guide with a link to documentation guide

docs: update contributors guide

---

harness/determined/searcher/_search_runner.py
harness/tests/custom_search_mocks.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

chore: MLG-369: Some initial tests for DS AT

---

.circleci/config.yml
e2e_tests/tests/deploy/test_local.py
harness/determined/deploy/local/cluster_utils.py

det deploy local tests are flaky. I think it's due to docker aliases not being assigned to the network on time. The fix is to set hostname and network when creating the container. This branch was run on CI for 15 times without failure. 
test run on circleci 100 times prior to changes: https://app.circleci.com/pipelines/github/determined-ai/determined/37381/workflows/fb163d12-9e26-452a-9152-f933bd565bd7/jobs/1357200
failed 2/100
with these changes: https://app.circleci.com/pipelines/github/determined-ai/determined/37280/workflows/26e2f512-91a6-47e2-932e-1449527ca5b2/jobs/1352326
failed 0/100 times

chore: fix det deploy local tests

---

webui/react/src/utils/error.ts

This fixes an issue where using the web app with an invalid token would result in a redirect loop when the public url was unset.
no testing required

fix: Fix invalid token logout loop

---

harness/determined/pytorch/deepspeed/dsat/_defaults.py
harness/determined/pytorch/deepspeed/dsat/_run_dsat.py
harness/determined/pytorch/deepspeed/dsat/_utils.py

This PR does two things:
* Populates the search runner's config with various cli args so that the user can see what settings were used
* Fixes an errant `-p` argument to the `_run_dsat.py` that should have been removed in a previous pr.

feat: visualize cli args

---

.circleci/config.yml

CircleCI requires private context to run `test-e2e-react` , and that causes CI failure from forked branches. In order to avoid it, added filter
related: #6562
- Check if `test-e2e-react` is skipped on forked branches

chore: filter out forked branches for `test-e2e-react`

---

webui/react/src/components/ActionSheet.tsx
webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/Link.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/columns.ts
webui/react/src/pages/F_ExpList/glide-table/contextMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/linkCell.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/routes/utils.ts
webui/react/src/shared/utils/routes.ts

Add options `Open Link in New Tab` and `Open Link in New Window` to experiment table link cell context menu.
Before:
After:
WEB-1168

feat: add `Open Link in New Tab` and `Open Link in New Window` options to experiment table link cells[WEB-1168]

---

webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/stores/users.tsx

The current user list page is using the return user list as the total count. Update to use the total available user count from the API pagination info instead.
WEB-1187

fix: update user management table to use the correct total from pagination info [WEB-1187]

---

harness/determined/tensorboard/base.py

`Waiting for Tensorboard files to finish uploading` logging message is the last before shutdown. When something is wrong in shutdown, it makes it [confusing](https://hpe-aiatscale.slack.com/archives/C04C9JXB1C2/p1682962118013919?thread_ts=1682961986.088279&cid=C04C9JXB1C2) whether tensorboard is to blame. Let's add a completion message.
N/A

feat: logging message for tb upload completion.

---

harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py
harness/determined/searcher/_search_method.py
harness/determined/searcher/_search_runner.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

[MLG-464]
Tests and integrates the changes from [MLG-468] that allowed custom searchers to issue Shutdown operations that support a "failure" state.
[MLG-464]: https://hpe-aiatscale.atlassian.net/browse/MLG-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MLG-468]: https://hpe-aiatscale.atlassian.net/browse/MLG-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Allow DS AT Experiments to fail when module_profile_info fails

---

.circleci/config.yml

Inject DEFAULT_PT_GPU_IMAGE value  as a parameter so that it
is updated by bumpversion, and can be referenced by --ee testing.
Will be referenced in -ee config.yml

chore: Add circleci param for default-pt-gpu-image

---

ds_autotuning_prototype/core_api/ffn_example_ds_launcher/single.yaml
ds_autotuning_prototype/core_api/ffn_example_ds_launcher/startup-hook.sh
ds_autotuning_prototype/core_api/ffn_example_torch_launcher/single.yaml
ds_autotuning_prototype/core_api/ffn_example_torch_launcher/startup-hook.sh
ds_autotuning_prototype/core_api/no_op_test/single.yaml
ds_autotuning_prototype/core_api/torchvison_models/single.yaml
ds_autotuning_prototype/core_api/torchvison_models/startup-hook.sh
ds_autotuning_prototype/native_dsat_tests/torchvision_models_example/autotune_config.yaml
ds_autotuning_prototype/native_dsat_tests/torchvision_models_example/startup-hook.sh
ds_autotuning_prototype/startup-hook.sh
ds_autotuning_prototype/trial_classes/torchvison_models/single.yaml
ds_autotuning_prototype/trial_classes/torchvison_models/startup-hook.sh
examples/deepspeed/cifar10_cpu_offloading/zero_3_cpu_offload.yaml
examples/deepspeed/cifar10_cpu_offloading/zero_no_offload.yaml
examples/deepspeed/cifar10_moe/moe.yaml
examples/deepspeed/cifar10_moe/zero_stages.yaml
examples/deepspeed/deepspeed_dcgan/cifar10_zero2.yaml
examples/deepspeed/deepspeed_dcgan/mnist.yaml
examples/deepspeed/deepspeed_dcgan/mnist_grad_accum.yaml
examples/deepspeed/pipeline_parallelism/distributed.yaml
examples/integrations/hf_trainer_api/deepspeed.yaml

Now that we have successfully built the `deepspeed==0.8.3` environment images, actually use them.
I confirmed all deepspeed examples that already worked continue to work with the new version.
Some of the environments images had `tf-2.8` in it, and this doesn't seem to have any particular impact on our examples.

chore: update deepspeed to 0.8.3 [MLG-399]

---

docs/release-notes/summary_metrics.rst

Locally forgot to commit feedback given.

docs: summary metric release note reword

---

ds_autotuning_prototype/README.md
ds_autotuning_prototype/core_api/ffn_example_ds_launcher/deepspeed.yaml
ds_autotuning_prototype/core_api/ffn_example_ds_launcher/script.py
ds_autotuning_prototype/core_api/ffn_example_torch_launcher/deepspeed.yaml
ds_autotuning_prototype/core_api/ffn_example_torch_launcher/script.py
ds_autotuning_prototype/core_api/no_op_test/deepspeed.yaml
ds_autotuning_prototype/core_api/no_op_test/script.py
ds_autotuning_prototype/core_api/torchvison_models/deepspeed.yaml
ds_autotuning_prototype/core_api/torchvison_models/script.py
ds_autotuning_prototype/hf_trainer_api/README.md
ds_autotuning_prototype/hf_trainer_api/det_callback.py
ds_autotuning_prototype/hf_trainer_api/image_classification/image_classification.py
ds_autotuning_prototype/hf_trainer_api/language-modeling/run_clm.py
ds_autotuning_prototype/trial_classes/torchvison_models/model_def.py
harness/determined/pytorch/deepspeed/__init__.py
harness/determined/pytorch/deepspeed/_deepspeed_context.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/determined/pytorch/deepspeed/dsat/__init__.py
harness/determined/pytorch/dsat/__init__.py
harness/determined/pytorch/dsat/__main__.py
harness/determined/pytorch/dsat/_defaults.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_run_dsat.py
harness/determined/pytorch/dsat/_utils.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py
harness/tests/experiment/pytorch/test_deepspeed_trial.py

[MLG-499]
This allows users to add the `with dsat.dsat_reporting_context(core_context, op):` line into their code that can use deepspeed autotuning while still being able to run as a no-op outside of that context.
Establishes the `determined.pytorch.dsat` module as the public interface to support deepspeed autotune, most notably for the functions `dsat_reporting_context` and `get_ds_config_from_hparams`
[MLG-499]: https://hpe-aiatscale.atlassian.net/browse/MLG-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: refactor dsat module to be independent of deepspeed imports [MLG-499]

---

.flake8
.pre-commit-config.yaml
harness/.flake8
harness/determined/cli/template.py
requirements.txt

we have 9 different copies of flake8 configs. do we want the same style choices everywhere?
./cli
./common
./deploy
./e2e_tests
./examples/tests
./harness
./model_hub
./schemas
./tools

chore: add flake8 pre-commit check for harness

---

master/internal/rm/agentrm/provisioner/provisioner_test.go

modify mocking and add unit test for provisioning failure.

chore: add unit testing for provisioning failure

---

docs/release-notes/deprecate-tf1.rst

chore: deprecate tf1.

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/k8s-dev-guide.rst

Update kubernetes custom master deployment docs. They haven't been updated since we switched to using devcluster.

docs: k8s deployment docs [DET-9449]

---

bindings/generate_bindings_ts.py
webui/react/src/services/api-ts-sdk/api.ts

The `timestampBefore` and `timestampAfter` parameters were getting double encoded, causing the pagination log requests to return with `400 Bad Request`
Update the grpc generated API to have the `convert` function to simply cast the string/boolean into string as opposed to encoding them.
WEB-1212

fix: correct log pagination behavior [WEB-1212]

---

webui/react/src/pages/F_ExpList/glide-table/columns.ts

Shrink the widths of the new experiment list table columns to maximize the amount of visible data.
BEFORE:
AFTER:
WEB-1195

style: update new experiment list column widths [WEB-1195]

---

.circleci/config.yml
.github/workflows/link-docs-preview.yml
docs/Makefile
docs/deploy/.gitignore
docs/deploy/promote.py
docs/deploy/upload.py
docs/requirements.txt

This PR sets up both:
- local tooling to publish docsite previews based off a current build
- automatic docsite generation for PRs that make docs changes
Local scripts tested manually during development.
CircleCI changes tested by making a PR.
GHA changes require merging before being able to iterate on it. I'd do this locally, but given it depends on having a PR opened in the first place to interact with...
INFENG-184

chore(docs): setup docsite previews [INFENG-184]

---

master/static/srv/get_model_versions.sql

Fix some performance issues with the get_model_versions query by copying
queries from the underlying views and using them directly.
[DET-9457]
[DET-9457]: https://hpe-aiatscale.atlassian.net/browse/DET-9457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

perf: speed up model versions query

---

examples/deepspeed/deepspeed_autotuning/core_api/ffn_example_ds_launcher/deepspeed.yaml
examples/deepspeed/deepspeed_autotuning/core_api/ffn_example_torch_launcher/deepspeed.yaml
examples/deepspeed/deepspeed_autotuning/core_api/no_op_test/script.py
examples/deepspeed/deepspeed_autotuning/core_api/torchvison_models/deepspeed.yaml
examples/deepspeed/deepspeed_autotuning/trial_classes/torchvison_models/deepspeed.yaml
examples/deepspeed/deepspeed_autotuning/trial_classes/torchvison_models/model_def.py
harness/determined/pytorch/dsat/__main__.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_utils.py

Adds a `--run-full-experiment` (open to better names!) flag which will generate a follow-on experiment according to the original config, but with the updated `zero_optimization` params found by DS AT.
Also updates the `should_be_failure` condition to also fail every trial after the model profiling info run fails.

add follow on exp option

---

webui/react/src/components/WorkspaceMemberAddModal.tsx
webui/react/src/pages/ResourcepoolDetail.tsx

[WEB-1207]: Spinner layout
[WEB-1209]: Typo
For Typo
- Create a workspace, and check if success message doesnt contain typo
For Spinner
- go to Cluster > Resource pool card > Stats page
- Hit cmd-R to reload the page
- Check if spinner is in the middle (`Fast 3G` might help to see the spinner)
[WEB-1207]: https://hpe-aiatscale.atlassian.net/browse/WEB-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1209]: https://hpe-aiatscale.atlassian.net/browse/WEB-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: spinner layout and typo in workspace success message

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

When the size of experiment list is changed, `data[row]` can be `undefined` due to the size is changed.
https://user-images.githubusercontent.com/109113616/236358180-33f811f6-667c-4e54-821f-b40a647c8f73.mov
- Check if table doesnt break even if the size of experiment list is changed

fix: cell out of bounds

---

CONTRIBUTING.md

we removed support for it with
7c12bd2545e4e98018fa37f5326f377ff58583b2
https://github.com/determined-ai/determined/blob/3c744a0032a986779897f34d2516dada8f440e59/.circleci/config.yml#L2232

doc: update min py version for dev

---

harness/determined/pytorch/dsat/__main__.py
harness/determined/pytorch/dsat/_defaults.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_utils.py
harness/tests/experiment/fixtures/deepspeed_autotune/example_experiment/deepspeed.yaml
harness/tests/experiment/fixtures/deepspeed_autotune/example_experiment/ds_config.json
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Basically just me learning how to write tests.  Please sanity check.  Did a little refactoring, removed the repeated usage of the final submitted metrics in the `MockMaster`, and added a `DSATTrial` test class.

feat: minor test updates

---

tools/scripts/lock-published-urls.sh

Release party automation script for #6715.
Paired with dev-scripts #25.

ci: add automation script for redirects

---

examples/deepspeed/deepspeed_autotuning/hf_trainer_api/image_classification/image_classification.py
examples/deepspeed/deepspeed_autotuning/hf_trainer_api/language_modeling/run_clm.py
harness/determined/integrations/huggingface/__init__.py
harness/determined/integrations/huggingface/hf_callback.py

feat: use lock with json overwrite for hf

---

harness/determined/pytorch/dsat/_dsat_search_method.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

`DSATTrialTracker` tests, plus some refactoring.

feat: basic trial tracker tests

---

harness/determined/integrations/huggingface/hf_callback.py

Should fix the single-trial hf errors

fix: hf overwrite bug

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

Update glide table to support auto column adjustment. Big thank you to @trentwatt for figuring a lot of this out.
The [current state of the glide table](https://github.com/glideapps/glide-data-grid/blob/f1d23fe54ea95e92639d4857a51ff57d1555df98/packages/core/src/data-editor/use-column-sizer.ts#L18-L28) for some reason hard codes auto column resize for custom cells to be 150px wide. There is an [open issue](https://github.com/glideapps/glide-data-grid/issues/697) reported there to allow for custom cells to define their own measure callback function to handle auto column resize.
WEB-1193

feat: enable double click auto column adjust [WEB-1193]

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/utils.ts

fix: add border after last frozen column in glide [WEB-1194]

---

master/internal/rm/agentrm/provisioner/provisioner_test.go

chore: fix tests and add new one

---

harness/determined/core/_checkpoint.py

metadata must include a 'steps_completed' key in the current implementation.

docs: added docstring in _checkpoint.py

---

.circleci/config.yml

chore(circleci): limit doc preview generation to upstream branches

---

examples/deepspeed/deepspeed_autotuning/hf_trainer_api/README.md
harness/determined/pytorch/dsat/_defaults.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_run_dsat.py
harness/tests/experiment/fixtures/deepspeed_autotune/example_experiment/deepspeed.yaml
harness/tests/experiment/fixtures/deepspeed_autotune/example_experiment/ds_config.json
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Adds tests for the random search method, plus bug fixes and refactorings.

feat: add search method tests

---

master/internal/api_notebook.go

chore: replace missing arg panic with an api error

---

harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

quick fix for the unit tests

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/singularity.rst

Fixes a small typo error in the singularity docs.

fix: typo in singularity docs

---

.circleci/config.yml
harness/Makefile
harness/tests/experiment/fixtures/estimator_xor_model.py
harness/tests/experiment/fixtures/tf_keras_xor_model.py
harness/tests/experiment/integrations/test_deepspeed_trial.py
harness/tests/experiment/keras/test_keras_data.py
harness/tests/experiment/tf_utils.py
harness/tests/experiment/utils.py

Enable deepspeed unit tests now that we have a GPU runner for them.
Check that tests pass in CI
MLG-514

ci: Enable deepspeed unit tests

---

harness/determined/pytorch/dsat/_dsat_search_method.py

Write the best found config to the search runner checkpoint, so that the user can recover it, if needed.

feat: write best ds config json to checkpoint

---

master/internal/config/authz_config.go

backported from EE.
(cherry picked from commit 649a31fcf69d693a0c6ce73d4030d762b501ad9d)

chore: backport workspace creation role assignment config

---

e2e_tests/tests/experiment/experiment.py
harness/determined/pytorch/dsat/__main__.py
harness/determined/pytorch/dsat/_defaults.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_run_dsat.py
harness/determined/pytorch/dsat/_utils.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Refactors the argparsing so that different search methods have their own, independent name spaces. E.g., there are some common global args, but then specific search methods have flags special to them and only those search methods should inherit those args.  In anticipation of adding some new search methods very soon.
Also refactors `should_shutdown` to be owned by the search method and not by the trial tracker, which was always weird.
Lastly, renamed `SimpleDSATSearchMethod` to `_TestDSATSearchMethod`, since that's really what it is.

refactor argparse into subparsers

---

harness/determined/cli/notebook.py
harness/determined/common/api/request.py

The JupyterLab session generated by the CLI has a slightly different URL from a session generated from the WebUI. The side effect is that the CLI session is not killable by the WebUI. Update the backend to generate the same URL to fix this.
WEB-1238

chore: update jupyter-lab URL to be consistent with CLI generated URL [WEB-1238]

---

harness/determined/pytorch/dsat/_defaults.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_utils.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Adds a very simple binary search. 
Randomly generates as many configurations as can be concurrently runs binary search on all of them. Either a binary search completes before `max_trials` is hit, in which case a new conig is generated and BS is started over again for that config, or the search is interrupted when `max_trials` is hit.

feat: add binary search

---

.github/workflows/link-docs-preview.yml

chore(gha): fix invalid syntax for docsite linker

---

.circleci/config.yml

Sometimes aws is slow and we start seeing a ton of CI failures.

ci: increase `det deploy aws up` wait time to 20m.

---

docs/interfaces/cli-ug.rst

Since v0.15.0, the CLI has been packaged with the rest of the determined Python library. This updates the CLI users guide to reflect that.

docs: Update language about upgrading/uninstalling CLI

---

webui/react/src/pages/TrialDetails/TrialDetailsProfiles.tsx

Fix typo
it should be `/docs/reference/training/experiment-config-reference.html#profiling`
follow up: #6799
- Check if the url is correct

fix: doc url fix

---

harness/determined/integrations/huggingface/hf_callback.py
harness/tests/experiment/fixtures/deepspeed_autotune/hf_integration_experiment/ds_config.json
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

I only had the lock on the writing, but it should be on the reading of the config, as well.
Also adds tests.

fix: move lock to fix hf overwrites

---

master/internal/rm/agentrm/resource_pool.go
master/internal/task/allocation.go
master/internal/trial.go

chore: provisioning retry error prop

---

master/internal/rm/agentrm/provisioner/provisioner.go
master/internal/rm/agentrm/resource_pool.go

chore: prop err from CurrentSlotCount()

---

docs/release-notes/command-config-cli-bind-mounts.rst
harness/determined/cli/command.py

chore(CLI): set command config binds from --config

---

harness/determined/pytorch/dsat/_dsat_search_method.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Just fixes small requests we spoke about previously.

fix: small fixes

---

harness/determined/pytorch/dsat/_run_dsat.py

fix: proper placement of start/end profile step

---

harness/determined/pytorch/dsat/_dsat_search_method.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Adds another test and fixes some small bugs, plus a little cleanup.

feat: more random search tests

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/ParallelCoordinates.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx

The official [hermes-parallel-coordinates](https://github.com/hkang1/hermes) library now supports initializing a chart with filters. We can swap out our forked version with the official version. Thanks, @mapmeld, for [creating the fork](https://github.com/determined-ai/determined/pull/5243) to hold us over!

chore: update hermes [WEB-1186]

---

harness/determined/deploy/aws/aws.py

Sometimes, CloudFormation is slow and a job gets killed by CircleCI while waiting for the cluster to come up because there's no output for a long time.
There was evidence that the slowness is actually due to an AWS bug and that the stack might _never_ come up in those cases, but at least this way we can find out for sure. And I suppose it's a little bit nicer for actual users as well.
This adds the output to stack deletion too, for symmetry and the user experience reason, though I don't remember having any hangs there.
It would not be too hard technically to hack the Boto3 waiter to print periodic messages without the need for a separate thread, but it didn't look possible with only the _documented_ interfaces, so threading it is.

chore: print messages while `det deploy aws (up|down)` waits

---

harness/determined/pytorch/__init__.py
harness/determined/pytorch/_pytorch_trial.py
harness/tests/experiment/pytorch/test_pytorch_trial.py

chore: do not set trial state on PyTorchTrial until load

---

master/internal/populate_metrics.go

after
```
hbp ➜ determined git:(speed-up-metric-gen) hyperfine --runs 3 './master/build/determined-master populate 1000 --config-file /tmp/devcluster/master.conf'
Benchmark 1: ./master/build/determined-master populate 1000 --config-file /tmp/devcluster/master.conf
Time (mean ± σ):      8.757 s ±  0.051 s    [User: 0.760 s, System: 1.293 s]
Range (min … max):    8.707 s …  8.810 s    3 runs
Time: 0h:00m:26s
```
before
```
hbp ➜ determined git:(speed-up-metric-gen) gco main; make -C master build > /dev/null
hbp ➜ determined git:(main) hyperfine --runs 3 './master/build/determined-master populate 1000 --config-file /tmp/devcluster/master.conf'
Benchmark 1: ./master/build/determined-master populate 1000 --config-file /tmp/devcluster/master.conf
Time (mean ± σ):     13.548 s ±  0.156 s …
```

perf: speed up synthetic metric generation

---

.devcontainer/devcontainer.json

Fix the devcontainer node version and add ssh and gitconfig bindings.

chore: devcontainer node version and bindings

---

harness/determined/deploy/gcp/terraform/modules/compute/main.tf

This increases the `det deploy gcp` server instance to have a 200gb disk, to match the aws deployment disk size.

chore: increase det deploy gcp server size to 200gb

---

master/internal/db/postgres_trial.go
master/static/migrations/20230504000000_recompute-trials-total-batches.tx.down.sql
master/static/migrations/20230504000000_recompute-trials-total-batches.tx.up.sql

- Fix a missing where clause
- Add a migration. I've set the migration date to be newer than the 0.22.0 migration, but older than 0.23.0. So
- We don't need to rename 0.23.0 migrations
- But we'd need to run this migration manually for `latest-` servers.
- Deploy 0.22.0 cluster
- Run a few trials
- Run a trial which causes a rollback
- See that the total_batches is messed up
- Upgrade to 0.22.1
- The total batches should become ok
- Run trials & trials with rollbacks to confirm

fix: total batches update on rollbacks.

---

.github/workflows/link-docs-preview.yml

chore(gha): add debug info to help iterate on link preview workflow

---

harness/determined/integrations/huggingface/hf_callback.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_run_dsat.py

Follow up from: https://github.com/determined-ai/determined/pull/6846

updates according to comments for mypy changes

---

harness/determined/pytorch/dsat/__init__.py
harness/determined/pytorch/dsat/_defaults.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_run_dsat.py
harness/determined/pytorch/dsat/_utils.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

feat: asha

---

.circleci/config.yml

ci(circle): add react node cache key suffix

---

.circleci/config.yml

ci(circle): skip jobs if only .github files were changed

---

.github/workflows/link-docs-preview.yml

ci(gha/link-docs-preview): use md5sum for branch hashing

---

.github/workflows/link-docs-preview.yml

ci(gha/link-docs-preview): fix url base for preview links [INFENG-193]

---

.github/workflows/link-docs-preview.yml

ci(gha/link-docs-preview): fix variable name in output

---

webui/react/src/components/kit/NoteCards.tsx

Replace `New Page` with `New Note` in project notes.
Navigate to project details -> note tab.
Button that creates new page of notes is named "New Note"

chore: Replace `New Page` with `New Note` in NoteCards

---

docs/release-notes.rst
docs/release-notes/deprecate-fluent-logging.rst

docs: Add release notes for 0.22.1

---

harness/determined/pytorch/dsat/__init__.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/pytorch/dsat/_run_dsat.py
harness/determined/searcher/__init__.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Use the python module for `searcher` directly rather than importing the individual elements

use the python module for `searcher` directly

---

webui/react/src/components/Table/InteractiveTable.tsx

The gap is due to the pinned rows placed as a pre-calculated position based on the height of the row of being `60px` tall. The row height has since been adjusted to `48px`.
The best approach would be to dynamically read in the row height and using that par of the calculation, but it's not trivial to do and since we are moving to `glide-table` framework, decided just a simple number adjustment would be best for now.
BEFORE:
https://github.com/determined-ai/determined/assets/220971/40d97792-db52-4683-9c71-933e17cfc3c2
AFTER:
https://github.com/determined-ai/determined/assets/220971/03ca5647-3be6-498a-9aee-42e3a6b893e0
WEB-1260

fix: adjust pinned position calculation [WEB-1260]

---

harness/determined/pytorch/dsat/_dsat_search_method.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Avoids the possibility of scheduling the same trial twice. Could probably be handled better, but it's a start.

fix: no trial twice

---

harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/searcher/_search_runner.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

It passes the e2e tests again!

Fixing tests and flake8 issues

---

examples/tests/test_official.py

fix: remove improper test_official.py tests

---

webui/react/src/hooks/useModal/Checkpoint/useModalCheckpoint.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/shared/configs/eslintrc.js
webui/react/src/utils/loadable.ts
webui/react/src/utils/wait.ts

This turns on the typescript-eslint rule that ensures the type of the expression in a switch statement is `never` after all case statements. There were three places where we didn't fully cover all cases, which are fixed here. In addition, we also disable the `no-fallthrough` rule, because it can sometimes cause a false positive where the fallthrough is unreachable -- it also overlaps in purpose with the `noFallthroughCasesInSwitch` typescript config option.
checkpoint modal and job queue modal functionality should be unchanged.

chore: enable exhaustiveness checks in switch statements

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/Table/InteractiveTable.tsx
webui/react/src/components/TaskList.tsx
webui/react/src/hooks/useSettings.ts
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelRegistry.tsx
webui/react/src/pages/Settings/GroupManagement.settings.ts
webui/react/src/pages/Settings/GroupManagement.tsx
webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/pages/TrialDetails/Profiles/Charts/SystemMetricChartFilters.tsx
webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.settings.ts
webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.tsx
webui/react/src/pages/TrialsComparison/Table/TrialTable.tsx
webui/react/src/pages/WebhookList.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx
webui/react/src/pages/WorkspaceList.tsx

It's not clear if the current `updateSettings` is intended to support partial settings, so explicitly making it so. Seen some PRs using it as partial updates.
UPDATE: There was a typing that allowed partial settings updates but the code was not intentionally supporting it. Now explicitly supporting partial settings updates and correcting the types throughout the codebase.

refactor: explicitly support partial settings and compare changes in full settings (as opposed to comparing settings to updates)

---

webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.module.scss

Before
After
- Check if icon is aligned center

fix: icon position

---

webui/react/src/App.tsx
webui/react/src/stores/polling.ts

Web store polling is too frequent, reduce the polling to something more realistic.
UPDATE: removed project because we are not polling that currently since it has a dependency on a workspace selection by the user.
Users: 1 min
DeterminedInfo: 10 min
Workspaces: 1 min
Permissions: 30 seconds
All other stores: 10 seconds
WEB-1245

chore: update polling intervals for stores [WEB-1245]

---

e2e_tests/tests/cluster/test_agent.py
master/internal/rm/agentrm/agents.go
master/internal/rm/kubernetesrm/pods.go

Modified `/agents` endpoint in [master/internal/rm/agentrm/agents.go](https://github.com/determined-ai/determined/compare/main...corban-beaird:determined:remove-agents-endpoint?expand=1#diff-cebe384fcfdfc1db8d1227536e81b43f879d9ba3bab59c716b165b15357d74b6), so that it only accepts requests from websockets. And removed the `/agents` endpoint from [master/internal/rm/kubernetesrm/pods.go](https://github.com/determined-ai/determined/compare/main...corban-beaird:determined:remove-agents-endpoint?expand=1#diff-484ca0962b47a22acd9c33be68bfb161a513e5c3b1ac6d3d660d2cfb0eb78f47)
Spin up a local devcluster and confirm that agents connect successfully
Spin up a [GKE cluster](https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1339359245/Runbook+Developing+Determined+with+Kubernetes) …

refactor: remove /agents endpoint [DET-9479]

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/FilterForm/components/FilterFormStore.ts
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/setupTests.ts

`crypto.randomUUID` is only available in `HTTPS`  https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
Use `uuid` instead
related: #6502
- Check if new condition/group can be added in `HTTP`

fix: replace `crypto.randomUUID` with `uuid`

---

webui/react/src/pages/Settings/UserManagement.tsx
webui/react/src/stores/users.tsx

PROBLEM:
There are a couple:
- The user store is polling and upon each poll everything that references the user list observable gets re-rendered due to the user list being a new array of users.
- The user sorting has not be working in conjunction with the API. The user store is already fetching everything, so trying fetch user list pages is coming into conflict with user store's ability to return just page data.
SOLUTION:
- Only update the user list when the user data has changed.
- The user store is already polling for the whole store, so removing the unused pagination.
- Perform sorting and filtering locally.
WEB-1273
WEB-1261
WEB-1203

fix: avoid having user edit modal reset to original state every 5~10 seconds [WEB-1273, WEB-1261, WEB-1203]

---

master/.golangci.yml
master/cmd/determined-gotmpl/main.go
master/cmd/determined-master/root.go
master/internal/core.go
master/internal/core_searcher.go
master/internal/db/postgres_test_utils.go
master/internal/elastic/elastic_task_logs.go
master/internal/experiment.go
master/internal/rm/kubernetesrm/pods.go
master/internal/user/service.go
master/internal/webhooks/shipper.go
master/pkg/archive/archive.go
master/pkg/etc/etc.go
master/pkg/model/logging_config.go
master/pkg/schemas/expconf/schema_test.go
master/pkg/tasks/copy.go

staticcheck is a weird linter because "The author of staticcheck doesn't support or approve the use of staticcheck as a library inside golangci-lint."
but it does catch some stuff, e.g. ioutil deprection, and unused `queue` property when configured.

refactor: make staticcheck linter use correct go version.

---

master/internal/populate_metrics.go

(cherry picked from commit 480bedc1832d91b4e3e85306aefbe161bdeb69c5)
results in longer trials with the same number of total rows

chore: vary generated training and validation metric counts

---

docs/model-dev-guide/apis-howto/deepspeed/deepspeed.rst
docs/model-dev-guide/hyperparameter/search-methods/hp-custom.rst
docs/reference/searcher/custom-searcher-reference.rst
docs/reference/training/api-deepspeed-reference.rst
harness/determined/searcher/_search_method.py

Add a bunch of docstrings and examples to clarify how one should build Custom Searchers

chore: update the custom searcher docs [MLG-447]

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

[WEB-1246]
- set url pram `page=1000` in the new exp table, and check if it doesn't cause out of bounds error
[WEB-1246]: https://hpe-aiatscale.atlassian.net/browse/WEB-1246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: out of bounds when page is bigger than actual

---

.pre-commit-config.yaml
e2e_tests/.flake8

chore: enable flake8 pre-commit check on e2e_tests

---

harness/determined/pytorch/dsat/_utils.py

Concurrency issues with how we were locking our files for the HuggingFace config. Currently running a continuous stream of experiments to confirm this doesn't happen anymore

bug: fix sporadic JSON issues with HuggingFace examples [MLG-576]

---

docs/reference/deploy/config/master-config-reference.rst
docs/setup-cluster/deploy-cluster/slurm/hpc-launching-architecture.rst
docs/setup-cluster/deploy-cluster/slurm/hpc-security-considerations.rst
docs/setup-cluster/deploy-cluster/slurm/install-on-slurm.rst
docs/setup-cluster/deploy-cluster/slurm/overview.rst

docs: Add HPC Launcher Security Considerations [FOUNDENG-617]

---

tools/scripts/gql.py
tools/scripts/track-pr

This was in the first version but then accidentally got neglected in the switch from a shell script to a Python one.

ci: skip non-fix/feat PRs in release automation

---

docs/model-dev-guide/model-management/checkpoints.rst

This method was removed in 0.21.0
The removed section is addressed by another section in the same doc https://docs.determined.ai/latest/model-dev-guide/model-management/checkpoints.html#pytorch-checkpoints

docs: remove an obsolete section about `Checkpoint.load_from_path`.

---

docs/interfaces/proxy-ports.rst

The docs had an incorrect command.

docs: fix a typo in the proxy ports guide.

---

webui/react/src/hooks/useResize.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.module.scss
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.module.scss
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/columns.ts
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/loadingCell.tsx
webui/react/src/pages/F_ExpList/glide-table/exceptions.tsx
webui/react/src/pages/F_ExpList/glide-table/utils.ts
webui/react/src/pages/ProjectDetails.module.scss

- Update table style to design specs.
- update border colors to use design approved theme color
- update cell background color to use design approved theme color
- update header background color to use design approved theme color
- update selected background color to use design approved theme color
- adjust link cells to show white instead of active blue color to reduce table focus noise
- fix loading state to stretch properly into available space
- Use system theme colors instead of hard-coded colors.
- Auto adjust height of the table in new experiment list page.
BEFORE:
AFTER:
WEB-1227
WEB-1281

style: update glide table styles to design specs [WEB-1227, WEB-1281]

---

docs/release-notes.rst
docs/release-notes/command-config-cli-bind-mounts.rst
docs/release-notes/deprecate-template-set.rst
docs/release-notes/dont-accept-epoch-bad-values.rst
docs/release-notes/fix-det-e-list-cli.rst
docs/release-notes/launcher_329.rst
docs/release-notes/remove-legacy-apis.rst

docs: Add release notes for 0.22.2

---

docs/model-dev-guide/apis-howto/deepspeed/autotuning.rst
docs/model-dev-guide/apis-howto/deepspeed/overview.rst

add link to the dsat user guide

---

master/internal/core.go

Added `gpu_hours` to the CSV exported by the `/allocation/allocations-csv` endpoint.  
The reported time only considers the GPU hours that occurred during the time interval specified as input to the endpoint. 
As well as properly handling `end_time` == `NULL`.
Run an experiment, command, Tensorboard, and a Jupyter notebook and ensure that all times reported match expected times. 
Additionally, I inserted dummy rows into the `allocations` table with `start_time` and `end_time` values for each of the following cases:
* `start_time` = NULL, `end_time` != NULL  (and vice versa) 
* `start_time` >= `end_time`
* `start_time` < beginning of time interval (but still in range b/c of `end_time`)
* `end_time` > end of time interval (but still in range b/c of `start_time`)
See [Release …

feat: added `gpu_hours` to historical allocation CSV [DET-9506]

---

harness/determined/pytorch/dsat/_dsat_search_method.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Cleans up some of the ASHA internals (there was a small bug regarding what trials get promoted) and adds various new tests.

feat: more tests and asha cleanup

---

docs/example-solutions/examples.rst
docs/model-dev-guide/apis-howto/deepspeed/overview.rst
docs/release-notes/deepspeed-autotune.rst
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

fix the doc builds, add a release-note

---

examples/deepspeed_autotune/torchvision/README.md
examples/hf_trainer_api/README.md

Can certainly be better. Feel free to edit further, if you want.

fix: readme cleanup

---

docs/model-dev-guide/apis-howto/deepspeed/autotuning.rst
harness/determined/pytorch/dsat/_defaults.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Tweaks some defaults and changes some small behaviors both for performance and to avoid possible bad edge cases.

feat: update defaults and small tweaks

---

docs/reference/python-sdk.rst
docs/release-notes.rst
docs/training/model-management/checkpoints.rst
e2e_tests/tests/experiment/test_core.py
e2e_tests/tests/fixtures/no_op/model_def.py
e2e_tests/tests/test_sdk.py
harness/determined/__init__.py
harness/determined/_execution.py
harness/determined/_trial.py
harness/determined/_trial_controller.py
harness/determined/cli/experiment.py
harness/determined/common/experimental/__init__.py
harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/common/experimental/determined.py
harness/determined/common/experimental/experiment.py
harness/determined/common/experimental/trial.py
harness/determined/estimator/_estimator_trial.py
harness/determined/experimental/__init__.py
harness/determined/experimental/_native.py
harness/determined/experimental/client.py
harness/determined/keras/_tf_keras_trial.py
harness/determined/load.py
harness/determined/pytorch/_pytorch_trial.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/tests/cli/test_experiment.py
harness/tests/experiment/utils.py

- rename Trial to LegacyTrial
- rename TrialReference and ExperimentReference to Trial and Experiment

chore: rename Trial to LegacyTrial and TrialReference/ExperimentReference to Trial/Experiment in SDK [MLG-547]

---

harness/tests/experiment/keras/test_keras_data.py

On a mac, the tests where `multiprocessing=True` run slow:
```
use_multiprocessing=False: 72 passed ... in 2.22s
use_multiprocessing=True: 72 passed ... in 144.54s
```
Since there's not likely to be much interaction between this parameter and the others, this patch eliminates 71 of the
`use_multiprocessing=True` test cases. `coverage` shows no decrease in code coverage.
MLG-578

test: Removes several multiprocessing executions of test_enqueuer.

---

master/static/migrations/20230525143842_add-rp-workspace-bindings.tx.down.sql
master/static/migrations/20230525143842_add-rp-workspace-bindings.tx.up.sql

feat: rp-workspace db migration

feat: rp-workspace db migration [DET-9517]

---

master/internal/db/postgres_trial.go
proto/pkg/trialv1/trial.pb.go
proto/src/determined/trial/v1/trial.proto

just as our PR number has a nice symmetry, this change brings a similar balance to our code.
this was left indented to avoid more merge conflicts.

chore: simplify metrics handler syntax

---

harness/determined/core/_context.py

signal handlers can only be registered on the main thread. we do this to debug hung workers, but this should not always throw an exception if running outside a main thread.

chore: install sigusr1 on main thread only [MLG-585]

---

webui/react/src/components/kit/Breadcrumb.tsx

There are warnings from breadcrumb component
- Check if there's no warnings from breadcrumb component in a page breadcrumb is used

fix: breadcrumb warnings

---

examples/deepspeed/cifar10_cpu_offloading/zero_3_cpu_offload.yaml
examples/deepspeed/cifar10_cpu_offloading/zero_no_offload.yaml
examples/deepspeed/cifar10_moe/moe.yaml
examples/deepspeed/cifar10_moe/zero_stages.yaml
examples/deepspeed/deepspeed_dcgan/cifar10_zero2.yaml
examples/deepspeed/deepspeed_dcgan/mnist.yaml
examples/deepspeed/deepspeed_dcgan/mnist_grad_accum.yaml
examples/deepspeed_autotune/torchvision/core_api/deepspeed.yaml
examples/deepspeed_autotune/torchvision/deepspeed_trial/deepspeed.yaml
examples/hf_trainer_api/hf_image_classification/deepspeed.yaml
examples/hf_trainer_api/hf_language_modeling/deepspeed.yaml
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/determined/pytorch/dsat/_dsat_search_method.py
harness/determined/searcher/_search_runner.py

Fixes TODOs missed by me neglecting to search for them outside of `/dsat` and responds to various comments on environment issues.

fix: comment and environment cleanup

---

webui/react/src/pages/DesignKit.module.scss
webui/react/src/pages/DesignKit.tsx

[WEB-1280], [WEB-1259]
https://github.com/determined-ai/determined/assets/109113616/af70e034-730d-4a64-9af8-bd31a1803e55
https://github.com/determined-ai/determined/assets/109113616/8ee5240c-36fc-46aa-841b-f86e9d57074f
- Check if nav bar is sticky
- Check if anchor tag works after refreshing page
- Check if there's no visual diff change
[WEB-1280]: https://hpe-aiatscale.atlassian.net/browse/WEB-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1259]: https://hpe-aiatscale.atlassian.net/browse/WEB-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: sticky nav bar in UIKit page

---

e2e_tests/tests/experiment/test_allocation_csv.py

Fixed `test_tensorboard_experiment_capture` not capturing Tensorboard task. 
Test had been excluding task due to recorded `end_time` being less than a second before task actually terminated, pushed `end_time` out by 1 minute into the future to ensure that task was captured was correctly.
- Confirm `tests/experiment/test_allocation_csv.py::test_tensorboard_experiment_capture` does not fail due to `end_time` coming before `Tensorboard` task terminates 
DET-9542

chore: adjust end_time threshold for allocation tensorboard test [DET-9542]

---

.circleci/config.yml
harness/determined/cli/render.py
harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/simple.py
harness/determined/deploy/aws/injector/master.yaml.tmpl
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml

Let's try using normal RDS rather than aurora.

ci: `det deploy aws` flavor for a normal RDS postgres.

---

webui/react/src/components/kit/CodeEditor.tsx

Fix the issue of the selected active box in the file directory not lining up with the directory item content.
BEFORE:
AFTER:
WEB-285

style: remove unnecessary wrapper around directory tree [WEB-285]

---

master/internal/db/postgres_experiments.go

'det w delete <workspace-name>' was erroring out when workspace had one or more projects with no experiments with :
> Failed to delete workspace: failed to gather trial IDs for experiment: querying for trial IDs of experiments []: ERROR: syntax error at or near ")" (SQLSTATE 42601)
DeleteProject was trying to delete experiments that didn't exist. Added an if statement to check the number of experiments within that project before trying to delete them.
1. Open CLI
2. Create a workspace using "det w create <workspace-name>"
3. Create a project under that workspace using "det p create <workspace-name> <project-name>"
4. Try deleting the workspace using "det w delete <workspace-name>". It should delete successfully without throwing the above error.
See [Release …

fix: fixing error that 'det w delete <workspace-name>' throws when no exps under proj [DET-9492]

---

webui/react/src/pages/WorkspaceList.tsx

Reset "tableOffset" on change of "Whose" filter
On Workspace List page:
DET-9551

fix: WorkspaceList tableOffset bug

---

master/internal/api_resourcepool.go
master/internal/db/postgres_rp_workspace_bindings.go

Fill out bind endpoint and db function. RBAC already in place

feat: add bind endpoint

---

docs/assets/styles/determined.css

Increases the size of the Algolia search modal by introducing one new css variable and styling update.
1. Visit the "docs" page `/docs` and click inside the search box. 
2. Ensure the the search box does not exceed `1000px` 
3. Type inside the modal search box, ensure the height does not exceed `800px` 
WEB-1158

chore: Increase size of Algolia search modal [WEB-1158]

---

master/internal/api_resourcepool_intg_test.go
master/internal/api_workspace_intg_test.go
master/internal/db/postgres_rp_workspace_bindings_intg_test.go

chore: add testing function stubs

---

master/static/migrations/20230531154906_backfill_tasks.tx.down.sql
master/static/migrations/20230531154906_backfill_tasks.tx.up.sql

Eventually it would be nice to get rid of the `raw_checkpoints` table and other 'old' checkpoints view, and migrate them all to `checkpoints_v2`. The current view setup causes many query headaches. One thing standing in the way of this is that `checkpoints_v2` links tasks to checkpoints, where `raw_checkpoints` linked trials to checkpoints. Prior to some Determined release, there was no task table so some trials do not have task rows. This change backfills them.
Next PR in set: `insert into checkpoints_v2 select ... from raw_checkpoints`

chore: backfill tasks tables to always have entries for trials

---

master/internal/api_resourcepool.go
master/internal/db/postgres_rp_workspace_bindings.go
master/internal/mocks/workspace_authz_iface.go
master/internal/workspace/authz_basic_impl.go
master/internal/workspace/authz_iface.go

feat: overwrrite bindings endpoint [DET-9548]
intg-test 
[DET-9548]: https://hpe-aiatscale.atlassian.net/browse/DET-9548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: overwrrite bindings endpoint [DET-9548]

---

master/internal/api_project.go

When a recently viewed project moves out of scope for a user, they are currently given repeated permission denied errors when they attempt to view their recent projects. 
Rather than giving returning a permission denied error, the offending projects is ommited from the `viewableProjects`
- Create a user (Editor) with editor access in one workspace (Workspace A), and another workspace the user has no role in (Workspace B)
- Create a project in Workspace A, view it as the user. 
- Move project as an admin user to Workspace B
- Ensure that the project is not shown in Editor's recently viewed projects on `/det/dashboard` and that no permission denied errors are displayed …

fix: omit projects outside of users permissions [DET-9557]

---

master/internal/core.go
master/internal/proxy/proxy.go
master/internal/proxy/proxy_intg_test.go
master/internal/task/allocation.go
master/internal/task/idle_timeout.go

Remove the proxy service actor.
DET-9509
DET-9486

chore: actor refactor proxy

---

harness/determined/cli/cli.py

* Promotes `die` to a module-level function (2.6.4 in the style guide, and also DRYes out the code by making it more generally available).  Closing around the ArgParser to use its `exit` was unnecessary.
* f-strings a couple strings.

chore: clean up message handling in main

---

master/internal/experiment/authz_iface.go
master/internal/experiment/bulk_action.go

some actions on experiments resulted in a sql query error due to a missing workspace_id in the select query.
these are exposed via singular and batch endpoints.
```
ERROR: column \"workspace_id\" does not exist (SQLSTATE 42703)
```
- visually check references to `FilterExperimentsQuery`
- run `det e delete|(un)archive` on an experiment with a user that has workspace-scoped permissions sample are commands in the ticket
more context: https://hpe-aiatscale.slack.com/archives/C02PV33GSN5/p1680887120975499?thread_ts=1680883528.380939&cid=C02PV33GSN5
DET-9559

fix: add missing workspace_id column to FilterExperimentsQuery calls

---

master/internal/rm/kubernetesrm/log.go
master/internal/rm/kubernetesrm/mock_client_test.go
master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/pod_test.go

[DET-9510]
Remove KubernetesRM pod log actor.
[DET-9510]: https://hpe-aiatscale.atlassian.net/browse/DET-9510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: actor refactor pod log

---

webui/react/src/stores/cluster.tsx

Avoid situation where we have overlapping nodes and we over count them in kubernetes in the cluster info page.
Luckily we already handle this case for slurm but we just need to support the k8s resource pool type.
Manual -- launch k8s cluster with one node and two resource pools like this in ```values.yaml```
```
resourcePools:
- pool_name: default
- pool_name: test
```
In the cluster page ```CUDA Slots Allocated``` should show ```0 / 1``` instead of ```0 / 2```

chore: treat k8s like slurm in cluster info page

---

webui/react/src/hooks/useMetricNames.ts
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
webui/react/src/pages/F_ExpList/CompareMetrics.tsx
webui/react/src/pages/F_ExpList/ComparisonView.tsx
webui/react/src/pages/TrialDetails/F_TrialDetailsOverview.tsx
webui/react/src/pages/TrialDetails/MultiTrialDetailsHyperparameters.tsx
webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

Shows all metrics in experiment comparison view. 
Navigate to new experiment list
Select couple rows then click compare
Metrics should be displayed at the `Metrics` tab
WEB-990

feat: Add Chart grid to experiment comparison view [WEB-990]

---

harness/determined/common/experimental/model.py

This fixes `Model.get_versions` to read paginated results from master
should master choose to return its results in multiple pages. It also
explicitly sets its requested limit to `None`, where this was previously
just a default.  `get_versions` is plenty performant even without
paginating.
Test that `det m list-versions` still works.

chore: Fix pagination in get_versions.

---

webui/react/src/pages/F_ExpList/CompareMetrics.tsx

`ChartGrid` component missing a prop after #7052
- Check if no missing prop error with `?f_explist_v2=on` flag

fix: missing prop in `ChartGrid` component

---

webui/react/src/pages/F_ExpList/CompareMetrics.tsx

fix: handleError is required in ChartGrid

---

harness/tests/common/api_server.py
harness/tests/determined/common/experimental/test_experiment.py

Goal here is to see how simply we can rewrite tests for CLI's wait in the SDK.
* New test module for SDK's experiment
- contains single test for raising errors when waiting for a PAUSED experiment (this behavior was previously untested)
* Adds kwargs to `api_server.sample_get_experiment` allowing for overrides

test: new SDK test wait for experiments that are "PAUSED"

---

master/internal/api_experiment.go
master/internal/api_trials.go
master/internal/db/postgres_trial.go
master/internal/db/postgres_trial_intg_test.go
master/internal/db/postgres_trial_metrics.go
master/internal/trials/postgres_trials.go
master/pkg/model/experiment.go
master/pkg/model/metrics.go
master/static/migrations/20230605133832_set-default-metric-type.tx.down.sql
master/static/migrations/20230605133832_set-default-metric-type.tx.up.sql
master/static/migrations/20230605134555_set-custom-type-constraint.tx.down.sql
master/static/migrations/20230605134555_set-custom-type-constraint.tx.up.sql
master/static/srv/calculate-full-trial-summary-metrics.sql

- add one summary metric entry per custom metric type to trial's summary metrics
- default all custom_types on underlying `raw_validations` and `raw_steps`
- lean into `model.MetricType` and update its usage.
- add db constraints for custom_type val in training and validation partitions.
- the distinction between json path for summary metrics vs persisting individual metrics. https://hpe-aiatscale.slack.com/archives/C02PV33GSN5/p1685483925637699
- we don't need a migration
- avoid further exposing and relying on internal partitioning scheme and PartitionType (going away soon hopefully)
DET-9507

feat: add summary metric support for generic metrics

---

webui/react/src/pages/F_ExpList/glide-table/TableActionBar.module.scss
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
webui/react/src/pages/F_ExpList/glide-table/utils.ts

[WEB-1309], [WEB-1198]
- Check if experiment count is visible in the new exp table
- Check if `start time` unit abbreviation is correct (`mo` instead of `months` etc)
[WEB-1309]: https://hpe-aiatscale.atlassian.net/browse/WEB-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1198]: https://hpe-aiatscale.atlassian.net/browse/WEB-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show experiment count and change `start time` unit

---

master/internal/db/postgres_test_utils.go

fix: fix int

---

webui/react/src/components/SplitPane.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

Only static columns (checkboxes and names) should be shown when the comparison view is open on the new experiment list page.

fix: hide non-static columns when comparison view open

---

docs/assets/styles/determined.css

[WEB-1303]
https://github.com/determined-ai/determined/assets/109113616/cd367e43-87fe-4988-b9c8-b50c34b256fb
- Check if scroll chaining doesnt happen in side bar in doc
[WEB-1303]: https://hpe-aiatscale.atlassian.net/browse/WEB-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: scroll chaining in doc sidebar

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/utils.ts

Add support for displaying header sort icons (ascending - up arrow / descending - down arrow)
Add support for header ellipsis - show ellipsis when header text needs to truncate to fit in a given column width.
Dark Mode
Light Mode
WEB-1219

feat: show column sort [WEB-1219]

---

master/internal/api_resourcepool_intg_test.go
master/internal/db/postgres_rp_workspace_bindings_intg_test.go

so the tests only trigger on intg tests.

fix: add intg test flag on top of intg test files

---

agent/internal/agent.go
agent/pkg/singularity/singularity.go
master/pkg/cproto/spec.go
master/pkg/tasks/task.go

Make the declared slot type available to the container runtime. Then, have the singularity module make use of '--rocm' if appropriate.

chore: add slot type to container client config

---

master/internal/api_agents.go
master/internal/api_job.go
master/internal/authz/obfuscate.go
master/internal/cluster/authz_basic_impl.go
master/internal/cluster/authz_iface.go

Added RBAC code to obstrufcate container and agent information being shared over agent endpoints. 
- Confirming that `/det/clusters` page correctly shows agent information
- Agents & Containers successfully connect & launch when experiments are created
- Confirming that the following endpoints return unobstrufcate in OSS:
*  `"/api/v1/agents"`
* `"/api/v1/agents/{agent_id}"`
* `"/api/v1/agents/{agent_id}/slots"`
* `"/api/v1/agents/{agent_id}/slots/{slot_id}"`
[DET-9211]
[DET-9211]: https://hpe-aiatscale.atlassian.net/browse/DET-9211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: added rbac for agent endpoints [DET-9211]

---

webui/react/src/components/CreateUserModal.tsx

[WEB-1176],  [WEB-1204]
- Enable RBAC
- Go to `Admin page`
- Refresh page and check if kebab buttons do not move 
[WEB-1176]: https://hpe-aiatscale.atlassian.net/browse/WEB-1176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1204]: https://hpe-aiatscale.atlassian.net/browse/WEB-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: unexpected icon movement in admin page

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

The logic for updating experiments for the infinite scroll and the table vary slightly. The page for infinite scroll starts with a `0` and for paginated view it starts with `1`.
- Update `paged` view to use a 0-based index as well.
- Simplify `setExperiments` routine to be easier to read and understand.
- Reset page offset upon table mode toggle.
Infinite Scroll
Paginated View

fix: correct infinite scrolling behavior

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/utils.ts

This PR updates the table cells on the new experiment list to use the surface color which is the correct color for surfaces and other text-bearing containers per https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1155694597/Theme+Architecture
Visually confirm that the experiment listing looks good in both light and dark mode and that hover and selected states are visually distinct.
- [x Changes have been manually QA'd
No ticket

fix: Use correct theme colors for new table

---

master/internal/experiment.go
master/internal/job/job.go

work around DET-9563
follow repro steps [here](https://hpe-aiatscale.atlassian.net/browse/DET-9564) and tack on a `det j`
DET-9568

chore: assume missing experiment project as deleted experiment

---

agent/cmd/determined-agent/run.go
agent/internal/agent.go
agent/internal/options/options.go
agent/pkg/podman/podman.go
agent/pkg/singularity/singularity.go
docs/reference/deploy/config/agent-config-reference.rst
master/static/srv/singularity-entrypoint-wrapper.sh

Add a debug flag to the agent options and use it to conditionally enable 'set -x' in the container entry point wrapper script.
From command line:
```
srun -N1 /mnt/lustre/foundation_engineering/gaisford/determined-agent --master-host=casablanca-login  --master-port=8086 --resource-pool=default --container-runtime=singularity --slot-type=cpu --debug=true/false
```
From config file:
```
cat > agent.yaml
debug: true
srun -N1 /mnt/lustre/foundation_engineering/gaisford/determined-agent --master-host=casablanca-login  --master-port=8086 --resource-pool=default --container-runtime=singularity --slot-type=cpu --config-file=/home/gaisford/agent.yaml
```
Repeat with --container-runtime=podman. …

chore: conditional debugging output

---

webui/react/src/components/FilterForm/components/FilterForm.tsx

bug fix from #7122
`shared` folder is removed in #7112, so changed proper import path
- Check if theres no error after `make live`

fix: spinner import error

---

webui/react/src/components/FilterForm/components/FilterForm.tsx

Fix from #7132
- Check if path is correct

chore: change import path

---

harness/tests/determined/common/experimental/test_model.py
harness/tests/fixtures/api_responses.py

Also adds capability within api_responses to paginate an arbitrary mocked response.
[MLG-586]
[MLG-586]: https://hpe-aiatscale.atlassian.net/browse/MLG-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: New test -- Model.get_versions reads paginated responses.

---

webui/react/src/components/FilterForm/TableFilter.tsx
webui/react/src/components/FilterForm/components/FilterFormStore.test.ts
webui/react/src/components/FilterForm/components/FilterFormStore.ts

[WEB-1340]
- Check if **valid** filter count is visible while filter popover is open/closed
Hopefully it doesnt affect performance
[WEB-1340]: https://hpe-aiatscale.atlassian.net/browse/WEB-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show filter count while filter is open

---

master/internal/api_trials.go

Shocked this went missed for so long.

fix(api): complete trial to task log request mapping

---

docs/architecture/introduction.rst
docs/model-dev-guide/prepare-container/custom-env.rst
docs/reference/training/experiment-config-reference.rst
docs/setup-cluster/deploy-cluster/k8s/custom-pod-specs.rst

Fix typos and other errors in the Intro to Determined.

docs: Fix typos in Intro to Determined

---

docs/release-notes/username-cant-make-same-user.rst

minor edits for readability as discussed in slack

docs: Make minor edits to username release note

---

harness/determined/exec/gc_checkpoints.py
harness/determined/exec/launch.py
harness/determined/util.py

We already mask secrets in Trial logs, but we missed the secrets in checkpoint gc logs.

fix: mask checkpoint storage secrets in gc logs

---

webui/react/src/hooks/useFeature.ts

Feature flags should have a default state of either on or off.
In the config passing `-<feature name>` should turn off the feature switch.
In the url passing `?f_<feature name>=off` should turn off the feature switch.
Switches passed via the URL can override the config.
Turn on/off default value of a feature switch at `webui/react/src/hooks/useFeature.ts` -> `FeatureDefault` and verify from web UI.
Edit the master config file to turn on/off a feature switch and it should overwrite the default state.
In url turn on/off a feature switch and it should overwrite the config setting. 
WEb-1027

feat: feature switch can be turned off

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

fix: remember experiment list sorts

---

webui/react/src/components/kit/LineChart.module.scss
webui/react/src/components/kit/LineChart.tsx
webui/react/src/pages/F_ExpList/CompareMetrics.tsx

Change the comparison view for metrics to use `MetricBadgeTag` component as chart title.  
Before:
After:
WEB-1369

fix: use `MetricBadgeTag` for chart grid title

---

webui/react/src/pages/F_ExpList/glide-table/menu.tsx

[WEB-1364]
- Check if menu does not overlap with comparison view
[WEB-1364]: https://hpe-aiatscale.atlassian.net/browse/WEB-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: menu overlapping

---

proto/pkg/apiv1/experiment.pb.go
proto/src/determined/api/v1/experiment.proto
webui/react/src/services/api-ts-sdk/api.ts

clarify that this contains all the metrics and can be migrated to and not just "generic" ones.

chore: fix a metric name comment.

---

master/internal/api_trials.go
master/internal/db/postgres_trial_metrics.go
master/pkg/model/metrics.go
master/static/migrations/20230615134125_sanitize-generic-metric-types.tx.up.sql

we haven't release this yet but maybe add a migration to drop/rename these?
DET-9585

chore: sanitize metrictype [DET-9585]

---

webui/react/src/components/MetricSelect.tsx
webui/react/src/components/SplitPane.module.scss
webui/react/src/components/kit/internal/types.ts
webui/react/src/hooks/useMetricNames.ts
webui/react/src/ioTypes.ts
webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
webui/react/src/pages/F_ExpList/ComparisonView.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.module.scss
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/services/decoder.ts
webui/react/src/types.ts

This involved a fair bit of refactoring and cleaning up old code, but if you spot anything I missed that would be an easy fix let me know.

feat: trials comparison table in experiment comparison [WEB-993]

---

harness/determined/cli/_util.py
harness/determined/common/api/__init__.py
harness/determined/common/api/_util.py
harness/determined/common/experimental/determined.py
harness/determined/common/experimental/experiment.py
harness/tests/determined/common/experimental/test_determined.py
harness/tests/determined/common/experimental/test_experiment.py
harness/tests/fixtures/api_responses.py

Default to aggressive retries in Python SDK.
- GET Methods in the Python SDK should retry 5 times if a 504 error is encountered.
- POST methods do not default retry. 

chore: default retry in sdk

---

webui/react/src/components/NavigationSideBar.tsx
webui/react/src/pages/Settings/UserSettings.settings.ts
webui/react/src/utils/shortcut.ts

Create keyboard shortcut `ctrl/cmd + U` to toggle sidebar collapse
Press `ctrl + U` or `cmd + U` should toggle sidebar collapse.
Tooltip to the collapse button in the sidebar have the current keyboard shortcut as content.
WEB-1351

feat: Create keyboard shortcut to toggle sidebar collapse

---

agent/internal/container/container.go
agent/pkg/singularity/singularity.go
master/pkg/cproto/spec.go
master/pkg/tasks/task.go

and Apptainer.
Specifying credentials in the experiment configuration file:
```
environment:
registry_auth:
username: ...
password: ...
```
Registry_auth is optional.
Valid credentials are accepted.
Invalid credentials are rejected.

chore: support registry auth with Singularity

---

.pre-commit-config.yaml
pre-commit/run-go-fmt-import.sh
pre-commit/run-go-gofumpt.sh
pre-commit/run-golangci-lint.sh

adapted from https://github.com/Bahjat/pre-commit-golang
run it on all files using `pre-commit run ID --all-files
let gha do the same

chore: add go pre-commit checks

---

.circleci/config.yml

Moving harness unit tests to use custom GPU runners.
PR meant to be either fine enough to merge right in, or act as a point of reference for how harness tests should use the custom runners.
Run CI and iterate through any errors that come up.
INFENG-192

ci(circleci): use custom GPU runners for harness GPU unit tests [INFENG-192]

---

tools/scripts/licenses/codemirror-lang-markdown
tools/scripts/licenses/codemirror-lang-python
tools/scripts/licenses/codemirror-legacy-modes
tools/scripts/licenses/hermes-parallel-coordinates
tools/scripts/licenses/uiw-react-codemirror
tools/scripts/licenses/uuidjs

- Some libraries are removed or added, so update the library licenses
- Check if all web licenses are updated

chore: update license for web packages

---

docs/release-notes.rst
docs/release-notes/deprecate-ptl-adapter.rst
docs/release-notes/rbac-not-found-errs.rst
docs/release-notes/username-cant-make-same-user.rst

docs: add release notes for 0.23.1

---

master/internal/api_user_intg_test.go
master/internal/checkpoint_gc.go
master/internal/command/command.go
master/internal/experiment.go
master/internal/restore.go
master/internal/rm/kubernetesrm/pod_test.go
master/internal/rm/kubernetesrm/pods.go
master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go
master/internal/trial.go
master/internal/trial_test.go
master/pkg/tasks/task.go
master/pkg/tasks/task_command.go
master/pkg/tasks/task_trial.go

BuildTaskSpec is an awkward ask up (not down) the actor hierarchy that is frequently in the way and has caused deadlocks. This change removes it.
DET-9591

chore(actors): remove BuildTaskSpec message

---

docs/README.md

related: https://github.com/determined-ai/determined/pull/7081/files

docs: Update readme with version switcher info

---

docs/release-notes/gcp_cluster_management.rst
harness/determined/deploy/gcp/cli.py
harness/determined/deploy/gcp/gcp.py

As proposed by @ioga  in [this](https://hpe.sharepoint.com/:w:/t/detai/EcpKiIe0ZIpOjIEw8om3zo4BoKwkSYjhd2bQPJDvwJhayQ?e=dwLXLh) doc, added the following features:
- New list function 'det deploy gcp list --project-id <project_id>' that lists all clusters under the default gcs bucket in that project. User can also list clusters in a particular gcs bucket by using this command 'det deploy gcp list --project-id <project_id> --tf-state-gcs-bucket-name <gcs_bucket_name>'
- New delete subcommand 'det deploy gcp down --cluster-id <cluster_id> --project-id <project_id>' that deletes a particular cluster from the project.
- det deploy gcp up now uses a default gcs bucket '$PROJECT-ID-determined-deploy' to store tf state unless a local tf state file is present or a different gcs bucket is specified …

feat: new list fuction, new delete subcommand and made gcs bucket default

---

docs/Makefile
docs/conf.py
docs/requirements.txt

Prevent CI from failing on `upload-docs-search-index`. We are not using `sphinx_design` at the moment anyway.
Not necessary for release party
CI Builds docs on `upload-docs-search-index` (step is only run on master)

fix: Make sure that docs can build properly again [DET-9607]

---

tools/scripts/gql.py
tools/scripts/track-pr

ci: copy PR bodies into release party tracking issues

---

webui/react/package-lock.json
webui/react/package.json

[WEB-1383]
Hyperparameter value `global_batch_size` is `64` in exp 2773
datapoint on `global_batch_size` is incorrectly on `95` 
All datapoints including `global_batch_size` are correctly visualized
- Check if parallel coordinate displays data correctly in single/multi experiments in the new exp table
[WEB-1383]: https://hpe-aiatscale.atlassian.net/browse/WEB-1383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update `hermes-parallel-coordinates`

---

master/internal/api_experiment.go
master/internal/api_job.go
master/internal/command/command.go
master/internal/core.go
master/internal/experiment.go
master/internal/job/job.go
master/internal/sproto/globals.go
master/internal/sproto/jobs.go

Part 1 of job refactor. Redefine job actor as global and use system for actor context.

chore: refactor job as global

---

master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/pod_test.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/request_queue.go
master/internal/rm/kubernetesrm/request_queue_test.go
master/internal/rm/kubernetesrm/request_workers.go
master/internal/rm/kubernetesrm/spec.go

chore: request queue refactor

---

master/internal/config/config.go
master/internal/core.go
master/pkg/tasks/copy.go
master/pkg/tasks/task.go

On master restart, having TLS enabled causes task recovery to fail due to a problematic DB scan, leading to tasks still running on an agent without knowledge from the master. This PR changes the data that gets saved so that marshaling and unmarshaling don't break

fix: TLS enabled leads to zombie tasksd

---

.circleci/config.yml

ci(circle/test-unit): split off gpu unit tests

---

master/pkg/syncx/queue/queue.go
master/pkg/syncx/queue/queue_test.go

Add a generic queue as a drop-in replacement for an actor inboxes when
removing the actor system. This is useful to avoid side affects where switching
to a channel would introduce new back-pressure mechanisms. In some cases,
it is difficult to vet such back-pressure for unintended side effects. In other cases,
it is impossible to add without a larger change than is wise in a single change.

chore: add generic queue for drop-in actor inbox replacement

---

master/internal/api_trials.go
master/internal/api_trials_intg_test.go
master/pkg/model/metrics.go
master/pkg/model/metrics_test.go

DET-9608
```
hbp ➜ master git:(trialsample-test) gotestsum ./internal --count 1000 --run TestMultiTrialSample
✓  internal (2m12.193s)
DONE 1000 tests in 133.869s
```
the main fix is[ this commit](https://github.com/determined-ai/determined/pull/7191/commits/ed99a2447863f554ce9b3cc63d9b03a2de61567e) 

test: sort metrics by type in multiTrialSample

---

harness/determined/cli/workspace.py
master/internal/api_workspace.go

create a template in a workspace, then delete the workspace it should not fail and the template should be deleted

fix: delete workspace templates when deleting workspace

---

e2e_tests/pytest.ini
e2e_tests/tests/api_utils.py
e2e_tests/tests/cluster/managed_cluster.py
e2e_tests/tests/cluster/managed_cluster_k8s.py
e2e_tests/tests/cluster/test_agent_disable.py
e2e_tests/tests/cluster/test_groups.py
e2e_tests/tests/cluster/test_master_restart.py
e2e_tests/tests/cluster/test_oauth2_scim_client.py
e2e_tests/tests/cluster/test_rbac.py
e2e_tests/tests/cluster/test_users.py
e2e_tests/tests/cluster/test_users_experiment_api.py
e2e_tests/tests/cluster/test_workspace_org.py
e2e_tests/tests/cluster/utils.py
e2e_tests/tests/conftest.py
e2e_tests/tests/deploy/test_local.py
e2e_tests/tests/experiment/test_port_registry.py
e2e_tests/tests/utils.py
master/internal/config/authz_config.go

Reverts determined-ai/determined#7100

fix: revert #7100 (master returns rbacEnabled = false...)

---

master/internal/api_tasks.go
master/internal/api_trials.go
master/internal/core.go
master/internal/rm/actorrm/actor_resource_manager.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/agentrm/fair_share.go
master/internal/rm/agentrm/mock_test.go
master/internal/rm/agentrm/priority.go
master/internal/rm/agentrm/priority_test.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/agentrm/round_robin.go
master/internal/rm/agentrm/scaling.go
master/internal/rm/agentrm/scheduler_test.go
master/internal/rm/allocationmap/allocation_map.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/resource_manager_iface.go
master/internal/rm/tasklist/task_list.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go

chore(actors): remove allocation ref from rm tasklist

---

examples/hf_trainer_api/hf_image_classification/adaptive.yaml
examples/hf_trainer_api/hf_image_classification/const.yaml
examples/hf_trainer_api/hf_image_classification/const_epochs.yaml
examples/hf_trainer_api/hf_image_classification/deepspeed.yaml
examples/hf_trainer_api/hf_image_classification/distributed.yaml
examples/hf_trainer_api/hf_image_classification/image_classification.py
examples/hf_trainer_api/hf_language_modeling/adaptive.yaml
examples/hf_trainer_api/hf_language_modeling/const.yaml
examples/hf_trainer_api/hf_language_modeling/const_epochs.yaml
examples/hf_trainer_api/hf_language_modeling/deepspeed.yaml
examples/hf_trainer_api/hf_language_modeling/distributed.yaml
examples/hf_trainer_api/hf_language_modeling/run_clm.py

This small pr adds the ability to easily specify the `--trust_remote_code` option via the entrypoint in our `hf_trainer_ap` examples, e.g. as in [the line here](https://github.com/determined-ai/determined/blob/8d120e8ac2db019f0ab1c83a608a6f665f495a1b/examples/hf_trainer_api/hf_image_classification/adaptive.yaml#L49).  This flag is needed when running some models from huggingface, such as MosaicML's [mpt models](https://huggingface.co/mosaicml/mpt-7b) or the [falcon models](https://huggingface.co/tiiuae/falcon-40b-instruct) (though both require additional, more complex changes to run).
Verify the existing `hf_trainer_ai` examples still run.

feat: add trust_remote_code to hf_trainer_api examples

---

webui/react/src/components/FilterForm/components/type.ts

[WEB-1381]
- Check if data is filterable by `grid` and `custom` searcher types
- docs: https://docs.determined.ai/latest/model-dev-guide/hyperparameter/search-methods/overview.html
[WEB-1381]: https://hpe-aiatscale.atlassian.net/browse/WEB-1381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add missing searcher types

---

webui/react/src/components/kit/CodeEditor/CodeEditor.module.scss
webui/react/src/components/kit/internal/monokai.css

[WEB-1396]
- Check if long text does not overflow
[WEB-1396]: https://hpe-aiatscale.atlassian.net/browse/WEB-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: text overflow in code view

---

master/internal/api_resourcepool.go
master/internal/db/postgres_rp_workspace_bindings.go
master/internal/db/postgres_rp_workspace_bindings_intg_test.go
master/static/migrations/20230626140104_add-rp-workspace-bindings-constraint.tx.down.sql
master/static/migrations/20230626140104_add-rp-workspace-bindings-constraint.tx.up.sql

chore: fill in missing intg tests [DET-9520]

---

master/internal/api_workspace.go
master/internal/db/postgres_rp_workspace_bindings.go
master/internal/db/postgres_rp_workspace_bindings_intg_test.go
master/internal/mocks/workspace_authz_iface.go
master/internal/workspace/authz_basic_impl.go
master/internal/workspace/authz_iface.go

feat: List RPs Avaiable to Workspace [DET-9531]

---

docs/release-notes/gcp_cluster_management.rst

Spell out acronyms for better usability

Docs: Spell out acronyms in a release note

---

webui/react/src/pages/WorkspaceDetails/WorkspaceQuickSearch.tsx

[WEB-1403]
- Check if quick search modal displays a number of experiments of its project right after the project name
- Show # of all experiments instead of non-archived experiments
[WEB-1403]: https://hpe-aiatscale.atlassian.net/browse/WEB-1403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add num of experiments in quick search modal

---

harness/tests/determined/common/experimental/test_checkpoint.py

Now that `checkpoint.Checkpoint.download` calls
`checkpoint.Checkpoint.reload`, `download` has another path to request data off master that must be handled. This handles it my mocking `reload`.

test: Add another mock to checkpoint tests

---

webui/react/src/pages/Settings/GroupManagement.tsx

In Group Management, pagination changes do not update rows.
In Group Management page, change pages and ensure that groups listed change appropriately.
WEB-1411

fix: refetch groups on settings change

---

webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx

Bug reproduction steps:
- Open compare view, go to Details
- Select an experiment that failed then two that succeeded
- You should see three selected experiments but two trials in the details tab
- Unselect one of the successful ones
- Application crashes
The reason this happens is because `TrialsComparisonTable` takes both `experiment` and `trials` through props, and they are suppose to be related to each other, but when we updating `experiment`, there can be a short period of time when `trials` stays in old state, and causes discrepancy. 
Follow bug reproduction steps and application should not crash, data should adjust accordingly
WEB-1410

fix: experiment list comparison view 

---

webui/react/src/ioTypes.ts

Fix that new experiment list table not rendering on GKE. 
Summary metrics min/max/sum can be `Infinity`, `-Infinity` and `NaN`, and trying to decode it to number causes error.

fix: summary metrics decode

---

webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx

[WEB-1414]
- Go to an experiment detail page and open hyperparameter search modal
- Check if there's no issue to run experiments for hp search with different search type (`adaptive_asha`, `grid`, `randpm`)
[WEB-1414]: https://hpe-aiatscale.atlassian.net/browse/WEB-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hp seach launch issue

---

harness/determined/deploy/gcp/cli.py
harness/determined/deploy/gcp/gcp.py

Add validate credential to the list clusters function to make sure the credentials are valid.
Check if `det deploy gcp list --project-id <project_id>` is listing clusters without throwing any errors  

fix: adding credential check to gcp list clusters function

---

harness/tests/requirements/requirements-harness.txt

Pydantic V2 protects namespaces in a way that doesn't work with a handful of our existing tests. Upgrading from 1.10.x to 2 resulted in errors like:
```
NameError: Field "model_persistence_threshold" has conflict with protected namespace "model_"
```
This pins pydantic to prevent it upgrading to V2.

test: Pin Pydantic

---

webui/react/src/hooks/usePermissions.common.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts
webui/react/src/stores/cluster.tsx
webui/react/src/stores/workspaces.tsx
webui/react/src/types.ts

This PR implements the web side of the following 5 API endpoints:
-  Bulk bind workspace to RP (POST /api/v1/resource-pools/{resourcePoolName}/workspace-bindings) 
-  Bulk unbind workspace to RP (DELETE /api/v1/resource-pools/{resourcePoolName}/workspace-bindings) 
-  Overwrite RP/workspace bindings (PUT /api/v1/resource-pools/{resourcePoolName}/workspace-bindings) 
-  List workspaces bound to RP (GET /api/v1/resource-pools/{resourcePoolName}/workspace-bindings) 
-  List RPs available to the workspace (GET /api/v1/workspaces/{workspaceId}/available-resource-pools) 

feat: implement web resource pool binding api [WEB-1402]

---

webui/react/src/components/kit/InputShortcut.module.scss
webui/react/src/components/kit/InputShortcut.tsx
webui/react/src/pages/DesignKit.tsx
webui/react/src/pages/Settings/UserSettings.settings.ts
webui/react/src/utils/shortcut.ts

Add keyboard shortcut input to UI Kit.
Navigate to `/design#InputShortcut` section and enter/clear any keys
- Not sure if we want to use the icon or just characters in input field.
- While focusing on input, all other shortcuts would be skipped.  
WEB-1362

feat: Add keyboard shortcut input to UI Kit [WEB-1362]

---

webui/react/src/components/ManageGroupsModal.tsx
webui/react/src/pages/Settings/GroupManagement.tsx
webui/react/src/pages/Settings/UserManagement.tsx

Do not limit groups loaded in ManageGroupsModal
Fix bug with removing user from group via ManageGroupsModal
On User Management page,
- Open "Manage Groups" modal for a user
- Should be able to see more than 10 groups listed in the dropdown
- Should be able to add user to more than 10 groups and see them all selected
- Should be able to remove a user from a group
Using max `limit` value of 500 for now. May eventually want the ability to provide a limit of 0, or to add some sort of incremental loading to this dropdown.
Noticed bug with removing user from group while testing, technically a separate bug but including in this PR.
Previous PR #7263 actually addressed a different issue with pagination on the GroupManagement page, not actually the issue being reported in WEB-1411.
See [Release …

fix: ManageGroupsModal on UserManagement page

---

docs/reference/training/experiment-config-reference.rst
docs/setup-cluster/deploy-cluster/slurm/slurm-known-issues.rst
docs/setup-cluster/deploy-cluster/slurm/slurm-requirements.rst

* Add slurm configuration requirements for scheduling multiple jobs per node, and enforcing resource isolation.
* Enhance the Slurm ``PENDING`` now that we surface the slurm reason in experiment log.
* Improve the distributed jobs guidance to use slots_per_node.

docs: Provide additional Slurm configuration guidance [FE-88]

---

master/internal/rm/agentrm/provisioner/gcp.go
master/internal/rm/agentrm/provisioner/gcp_operation_tracker.go

Remove use of actors for the GCP operation tracker. 
DET-9625

chore: GCP operation tracker refactor

---

master/internal/core.go
master/internal/db/setup.go

On startup, check the `rp_workspace_bindings` table and see if there are any resource pools that don't exist anymore in the config. If they don't exist, mark the `valid` column of those bindings as `false`.

feat: resource pool invalidation on startup [DET-9533]

---

docs/requirements.txt
examples/tests/requirements.txt

Pin pillow to version < 10 due to breaking changes with pytorch.

chore: update pillow version for test requirements

---

webui/react/src/components/ResourcePoolCard.module.scss
webui/react/src/components/ResourcePoolCard.tsx
webui/react/src/hooks/useFeature.ts

[WEB-1398]
- Check if this should only show up in the resource pool cards if rbac is on and only appears if there are bindings
- Check if flag works (`f_rp_binding=on` in url)
[WEB-1398]: https://hpe-aiatscale.atlassian.net/browse/WEB-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: list resource pool binding

---

e2e_tests/tests/requirements.txt

Pin pydantic in e2e tests to account for breaking change in upstream dependency.
e2e_cpu passes.

test: pin pydantic in e2e_tests

---

harness/determined/cli/checkpoint.py
harness/determined/cli/model.py
harness/determined/cli/trial.py

currently the model CLI disregards user argument, it is being ignored by the model client.
- create a model with `det -u admin model create <Model_Name>` 
- ensure that the model is created with `model.username` = admin

fix: set user in model CLI client [DET-9612]

---

webui/react/src/pages/Settings/UserSettings.settings.ts

Make sure that Cmd + Shift + U toggles the sidebar's collapsed state

fix: navbarCollapsed shortcut key

---

pre-commit/run-golangci-lint.sh

Fix a small failure with the golangci-lint pre-commit where grep returns false on no match.

chore: fix golangci-lint pre-commit

---

webui/react/design/index.tsx

Fixes the UI Kit page.
Tested locally
No Ticket

fix: Fix type mismatch on design page

---

.circleci/config.yml

python-coverage is failing when invoked as part of `test-unit-gpu`. Temporarily disabling it until we figure out why `coverage report` finds no data.
It should be re-enabled as part of https://hpe-aiatscale.atlassian.net/browse/DET-9618 fix.

chore: temporarily disable python-coverage on test-gpu

---

docs/release-notes.rst

Correct release date for `0.23.2`.

docs: correct release date for 0.23.2

---

webui/react/src/components/Json.tsx
webui/react/src/components/ResourcePoolCard.tsx
webui/react/src/hooks/useSettingsProvider.tsx
webui/react/src/stores/userSettings.tsx
webui/react/src/types.ts
webui/react/src/utils/data.ts

This adds a new `Json` type to the codebase and uses it in the `Json` component and the user settings store. The additional typing also uncovered two bugs in the user settings store which I have fixed.
Check that the code type-checks.
No Ticket

chore: Add proper Json type to the code

---

master/internal/rm/kubernetesrm/pod.go

Fix an issue with testing where we may get a container log message before receiving a resource started message.

chore: fix flaky TestReceiveContainerLog

---

examples/features/ports/startup-hook.sh

Resolve test-e2e-cpu test_experiment_proxy_ray failures.

chore: fix ray proxy pydantic testing issue

---

webui/react/design/index.tsx
webui/react/tsconfig.json

This ensures the design kit landing page is included in typechecking.
WEB-1420

fix: ensure design kit landing page is typechecked

---

docs/_templates/sidebar-version.html
docs/conf.py

Fix docs version switcher does not properly show up at `https://docs.determined.ai/latest/`

docs: fix version switcher

---

docs/release-notes/removed_config_endpoint.rst
e2e_tests/tests/cluster/managed_cluster.py
harness/determined/cli/master.py
master/internal/core.go
master/internal/user/service.go
master/internal/user/service_test.go

Removed echo-backed `/config` endpoint, and replaced references to point at the grpc-gateway endpoint `api/v1/master/config`. This will help ensure that the work done resolve admin<>ClusterAdmin inconsistencies is applied to all points of access to the master config.
- Ensure that `/config` no longer works (regardless of user role/permissions)
- Ensure that `det master config` only returns results for admin users in OSS
DET-9580

chore: removed echo-backed /config and updated cli [DET-9580]

---

webui/react/src/components/ResourcePoolBindings.module.scss
webui/react/src/components/ResourcePoolBindings.tsx
webui/react/src/pages/ResourcepoolDetail.tsx

[WEB-1399]
related PRs: #7300, #7286
- Check if binding tab is visible when RBAC and `rp_binding` flag is on
- Check if table is updated after managing bindings (data doesnt persist since backend work is not done)
- Check if table data is sortable by workspace name
- Check if clicking workspace name jumps to workspace detail page
[WEB-1399]: https://hpe-aiatscale.atlassian.net/browse/WEB-1399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: create bindings tab in resource pool detail page

---

master/internal/api_resourcepool.go
master/internal/config/resource_config.go

feat: protect cluster default resource pools from being bound [DET-9627]

---

master/internal/api_experiment.go
master/internal/db/postgres_test_utils.go
master/internal/db/postgres_trial_intg_test.go
master/internal/populate_metrics.go
master/internal/trial.go
master/pkg/model/experiment.go
master/test/integration/api/api_checkpoints_test.go
master/test/integration/api/api_trials_test.go

Remove an unused property which serves no purpose.
N/A

refactor: remove unused `Trial.JobID` property.

---

harness/determined/common/api/_util.py
harness/determined/common/experimental/determined.py
harness/determined/common/experimental/experiment.py
harness/determined/common/experimental/model.py
harness/determined/experimental/client.py
harness/tests/determined/common/experimental/test_experiment.py

fixing a bad rebase that caused this PR (already previously merged at 651729192ac20b998c5db89e940243de434496ce) to get lost somehow.

chore: fix bad merge rebase

---

master/internal/api_master.go

Corrected order of error check for master config; ensures that if the permission check errors out, that error is reported rather than the a potentially faulty permission error.

chore: correct order of err check for master config

---

.github/workflows/check-rebaseable.yml

Per INFENG-178, update check-rebaseable action to first try rebasing main, then skip the rebaseable check if that fails.
Hopefully this just works, but we need to get into a situation where main isn't cleanly rebasing first. :shrug:   It also  runs as a pull_request_target workflow, so the only way to fully test it is to get it into main.  Hooray for GitHub Actions!

ci: try rebasing main before checking PR (INFENG-178)

---

docs/_templates/analytics.html

Add HPE specific analytics script for compliance to DOCS.
WEB-1295

docs: add HPE marketing analytics code [WEB-1295]
