webui/react/src/components/kit/LineChart.tsx
webui/react/src/pages/TrialDetails/Profiles/Charts/SystemMetricChart.tsx
webui/react/src/pages/TrialDetails/Profiles/Charts/ThroughputMetricChart.tsx
webui/react/src/pages/TrialDetails/Profiles/Charts/TimingMetricChart.tsx
webui/react/src/pages/TrialDetails/Profiles/utils.ts
webui/react/src/utils/chart.ts

Chart time axis improvements:
- Moves `getTimeTickValues` from `pages/TrialDetails/Profiles/utils` to `utils/chart`
- Fixes a bug we discussed.
- On experiments less than 12 hours, use `getTimeTickValues` for axis ticks. See http://localhost:3000/det/experiments/1622/overview?f_chart=on for a 1-minute experiment
- On experiments longer than 12 hours, use uPlot's default axis ticks. See http://localhost:3000/det/experiments/1621/overview?f_chart=on for a 20-hour experiment
- On the linked experiments, with `f_chart=on`, verify that you can change linear/log scale
- On the linked experiments, set x-axis to Time
- Open to feedback on these and shorter/longer experiments

feat: Display better x-axis ticks on charts with time axis [WEB-849]

---

master/internal/db/migrations.go

In integration tests, multiple processes can attempt to run migrations against the same database at once, which can lead to errors because PostgreSQL's `CREATE TABLE IF NOT EXISTS` is not great with concurrency (it allows for a time-of-check/time-of-use failure).
The specific errors we were seeing were conflicts in the pg_type table, so the code now locks that table for the duration of the migration transaction.
More information:
https://www.postgresql.org/message-id/CA+TgmoZAdYVtwBfp1FL2sMZbiHCWT4UPrzRLNnX1Nb30Ku3-gg@mail.gmail.com https://stackoverflow.com/questions/29900845

test: add locking around migration [DET-8957]

---

webui/react/src/pages/TrialDetails/F_TrialDetailsOverview.tsx

While working on another PR, I noticed on http://latest-master.determined.ai:8080/det/experiments/1789/overview?f_chart=on the right chart is showing the tooltip for the checkpoint point (batch 1,000,000), but not the 'Best Checkpoint' notice text
The issue was `xVals = Array.from(xValSet).sort()` was sorting 1,000,000 alphabetically; using `.sort((a, b) => a - b)` fixes
While debugging this, I considered if `maxDatapoints` could hide a checkpoint when its batch x-value was not returned in the downsampled points. I changed `findIndex` to attach the checkpoint to the first x `>= checkpoint.totalBatches`. The final batch is kept by downscaling, so we don't need to worry about checkpoints at the end of an experiment.
Visit `http://localhost:3000/det/experiments/1789/overview?f_chart=on` , …

fix: Checkpoint helper for points > 1000 and points > maxDatapoints

---

master/internal/db/migrations.go

Taking a table lock sometimes runs into permissions issues; advisory locking should avoid that.
Also, I realized the locking should probably be after the deferred transaction close instead of before.

fix: replace migration table lock with advisory lock

---

webui/react/.npmrc
webui/react/Makefile

This removes the `check-requirements` make target in the react folder and replaces it with npm's native version check against the engines property. This should make managing the node version slightly easier because there's one less place to check.
If running a version of node that's not supported in the package.json engines property, `npm install` should fail.
No ticket

build: check npm version on install

---

pre-commit/web_lint_check.py

This updates the web linters to automatically apply fixes when doing a
pre-commit check. This should ideally streamline the commit process to
reduce the amount of times the user needs to run prettier and eslint
before committing.
When committing code, if the code contains issues that a linter can fix automatically, those fixes should be applied ~while also preventing the commit from going through~.
things to check:
* prettier: try adding a statement to a ts file without a semicolon
* eslint: try disabling a test in a ts file by replacing the `it` call with `xit`
* stylelint: try adding a blank line in between two style declaration blocks
[WEB-928]
[WEB-928]: …

build: Apply webui lint fixes in precommit

---

webui/react/src/hooks/useModal/Model/useModalModelMove.tsx

When moving a model, we already filtered the dropdown of destinations by canMoveModel,
but the bug notes we include the model's current workspace.
- As admin, go to `/det/models` and select a model to view details.
- Note the parent workspace in the left of the breadcrumb menu (in the screenshot, "Demo")
- In the top right of model details, click the three dots menu and select Move
- For the destination workspace name, try to find the model's parent workspace. It will not be there

fix: Dont suggest moving model into its current workspace [WEB-941]

---

e2e_tests/tests/deploy/test_local.py

Previously, the database was being retained between tests, sometimes causing tests to fail when extra agents appeared due to agent reattach. The tests should generally be independent anyway, so reset the database (by default, with an option to disable) each time the cluster or master comes up.

ci: delete database at beginning of det deploy tests [DET-8937]

---

.circleci/config.yml

We keep hitting GKE GPU quotas; this will probably help with that.
Wait and see. (We already do this same thing elsewhere (for deploys), so it should be fine.)

ci: make GKE test jobs run serially

---

helm/charts/determined/templates/master-permissions.yaml
master/internal/rm/kubernetesrm/pods.go

Fix the cluster info page by also matching `limits.nvidia.com/gpu` so slots are counted correctly. Also gave master permission to list quotas in the helm chart and improved the error handling around the k8s API call for quotas.
The cluster info page should accurately report the number of GPU slots when a k8s limit quota is in place.

fix: GPU counting for k8s cluster info page

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/install-on-slurm.rst
docs/reference/reference-deploy/config/master-config-reference.rst

- Generalize journalctl command example --since option to work on Unbutu.
- Clarify user_name/group_name account requirements.
Ran through grammerly.com
and

docs: Launcher doc improvements

---

.circleci/config.yml
agent/internal/container/container.go
master/pkg/syncx/errgroupx/errgroupx.go
master/pkg/syncx/errgroupx/errgroupx_test.go

A race could potentially occur between returning ```launchgroup.Cancel()``` and returning ```ErrKilledBeforeRun``` or an error from the other thread from the context getting canceled. This could cause the test to fail with asserting a different error message.
Instead of canceling the context we just return an error and fix the wrapper around ```errgroup``` that wasn't canceling upon error return properly. 
Looped ```test-intg``` here
https://app.circleci.com/pipelines/github/determined-ai/determined/34115
I'm not 100% sure about this race causing the test flake here since the timing seems super precise and unlikely.
https://app.circleci.com/pipelines/github/determined-ai/determined/33810/workflows/d62e8f42-41b6-41b7-a02d-43c682625e37/jobs/1191309
See [Release …

chore: race could cause run container to return a different error than expected [DET-8870]

---

docs/conf.py
docs/requirements.txt

We would like to support markdown-format documentation.  There are still some kinks to be worked out with converting rst to myst files, but this is a start.

docs: add myst_parser extension

---

e2e_tests/tests/requirements.txt
examples/tests/requirements.txt

Installing the requirement `tensorflow-macos=2.8.0` pulls protobuf as a downstream dependency. Version 4.21 of the Python protobuf package had a breaking change that makes it incompatible with tensorflow-2.8.0 (see https://github.com/tensorflow/tensorflow/issues/56077). Later patches to Tensorflow limit the version of protobuf to 3.20. We've got a work item to update the tensorflow we include, but until then this change gives the ceiling on tensorflow's protobuf dependency that its later versions enforce.
I've run `make test` and `make check` in a fresh virtualenv.
This is a stop-gap solution for [MLG-336] until we update tensorflow.
MLG-336
[MLG-336]: …

build: [MLG-336] Limit the version of protobuf

---

master/internal/checkpoint_gc.go

Checkpoint GC is the odd one out and doesn't call the RM to resolve which RP is should run on. Other RPs handle this ok (they must, I suppose), but DispatcherRM ends up making a poor choice to run on the GPU pool. This is because it uses pool to determined slot type, but when pool isn't filled it, it defaults to CUDA.
There is some inconsistency between RMs here that needs to get resolved. I ticketed it.

fix: checkpoint gc should set resource pool

---

.circleci/config.yml

In order to prevent quota failures from showing up as CI failures, this makes node pool creation failure send a Slack notification and mark the job as successful.
I couldn't figure out how to use the Slack orb while distinguishing this particular situation from the general failure case, so I just slapped in a direct request to the already-configured Slack webhook for sending messages to #ci-bots.
`circleci-agent step halt` marks the job as successful, which is why we want a notification at all. For some reason, CircleCI fails to provide an equivalent for marking the job as canceled or some other state besides success/failure; we could make a call to the CircleCI API to cancel the current job, but that would rely on having a CircleCI token available, which we're trying to get away from.

ci: send Slack notification on GKE node pool creation failure

---

webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.settings.ts
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/ExperimentTrials.settings.ts
webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.settings.ts
webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.tsx
webui/react/src/pages/TrialsComparison/Table/settings.ts
webui/react/src/pages/TrialsComparison/TrialsComparison.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.settings.ts
webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.settings.ts
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx

The bug report is that ExperimentCheckpoints table is empty in some cases; I see this happening when `offset` comes from useSettings and we try to load a non-existent "page 2" of checkpoints.  The storagePath on tables should be experiment-specific.
I looked up other potential issues with tables and storagePath.
- This is NOT an issue for tables which are global (currently tasks, webhooks, user and group admin)
- This is an issue for workspace-specific tables (WorkspaceMembers, WorkspaceProjects)
- This is an issue for experiment-specific tables (ExperimentCheckpoints, ExperimentTrials)
- This is an issue for one trial-specific table (TrialDetailsHyperparameters)
- I don't know about TrialsComparison but I did make it dependent on projectId string
Repeating the issue: visit …

fix: Additional tables get experiment- / workspace-specific storagePath [WEB-962]

---

docs/release-notes/pt-images.rst

Adding release notes for Pytorch-only images

chore: add release notes

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
webui/react/src/pages/TrialDetails/TrialRangeHyperparameters.tsx

[MLG-343] [MLG-296]
We want to change the webui in the case of Custom Searchers. The Experiment graph tabs other than "Learning Curves" are not helpful, as we won't have an experiment config to anchor it.
Same goes for the hyperparameters displayed on each trial. Since we can't assume that we will have an experiment config, we are opting to simply show the hyperparameters from the trial as constants.
Without this change, custom searchers will display this for an individual Trial:
And the Experiment Page Visualization tabs other than "Learning Curves" are blank:
**With the change:**
The "Learning Curves" tab is the only one shown:
And the individual Trials show their hyperparameters:
All other types of searchers are unchanged.
**How to Test**
- Run a custom searcher before and after to see …

feat: show trial hyperparameters for custom searchers [MLG-343]

---

webui/react/src/pages/TrialDetails/TrialDetailsHyperparameters.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx

For release party: TrialDetailsHyperparameters throws a JavaScript error until there is 1+ trial available
I believe this is caused by #6128 where we use [trial.id] in useMemo, while other parts of the page are more protected (`trial?.hyperparameters`)
This is less of an issue for experiment or workspace tabs because the object is already present. For safety I did change WorkspaceProjects to use `id`
Visit an experiment with 0 trials and click on the Hyperparameters tab

fix: useMemo does not depend on trial having been loaded

---

webui/react/src/components/PageHeaderFoldable.module.scss

This fixes an issue where, when using a `PageHeaderFoldable` component, options that appear in the header always appear in the overflow menu.
buttons in the page header should not have duplicate options in the overflow menu visible at the same time
[WEB-961]
[WEB-961]: https://determinedai.atlassian.net/browse/WEB-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide Foldable menu options when button is visible

---

master/internal/sproto/resources.go

The problem is the ending: at this line of the message
[2023-03-01T16:51:47.462154Z]          || ERROR: Command (formally-key-stallion) was terminated: allocation failed: resources failed with non-zero exit code:
After the fix, it will read like this without ending ':'
[2023-03-09T15:48:16.856735Z]          || ERROR: Command (vastly-caring-gnat) was terminated: allocation failed: resources failed with non-zero exit code

fix: don't print ':' when err msg is empty

---

Makefile

This removes the `get-deps-bindings` target from the top level makefile because it's no longer in use
`make get-deps` should work
No ticket

fix: remove get-deps-bindings target from top level makefile

---

master/internal/rm/kubernetesrm/pods.go

Fixes an issue where quotas with both CPU and GPU limits were counted twice and therefore skipped (since we currently only support one quota for now).
Create and apply a quota (e.g. `kubectl apply -f quota.yml --namespace=default`) that includes both CPU and GPU limits such as this:
```yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
kind: ResourceQuota
metadata:
name: default-quota
spec:
hard:
cpu: "7"
memory: 1Gi
pods: "10"
nvidia.com/gpu: "9"
```
The cluster info page should reflect the correct number of slots (e.g. 9 in the above example).

fix: support mixed CPU/GPU k8s quotas

---

master/internal/task/idle_timeout.go

[DET-8720](https://determinedai.atlassian.net/browse/DET-8720)
To reproduce the error & verify changes:
- In devcluster.yaml under the master config, set tensorboard_timeout: 5
- Run an experiment & wait for it to complete.
- In the shell, run `det tensorboard start $experimentID`.
- Once terminated/failed, run `det tensorboard` to get a list of tensorboard processes & their IDs.
- Run `det tensorboard logs $tensorboardID` to view logs.
At the bottom of the logs, you should _not_ see (blank reason):
`[2022-11-29T20:27:42.533867Z]          || INFO: forcibly killing allocation's remaining resources (reason: )`
`[2022-11-29T20:27:48.138135Z] 1de345dc || INFO: resources were killed: resources failed with non-zero exit code:  (exit code 1)`
`[2022-11-29T20:27:48.142166Z]          || INFO: …

fix: add an exit reason to tensorboard allocation signal

---

harness/determined/deploy/aws/aws.py

In `update_stack`, the list `tags` is missing the key-value pair `constants.defaults.STACK_TAG_*` ("managed-by=determined" at the time of this writing). The consequences of this is that any stack that has been updated will not appear in the output from `det deploy aws list`.
This was manually tested by running `det deploy aws up --cluster-id drh-zwei ...`, which had been updated like this before and did not appear in the output of `det deploy aws list`. It does now.
Thanks to @azhou-determined for help finding this bug!
TODO: create an automated test that checks for consistency between a new stack and an updated stack?? This could be prohibitively expensive.

fix: default tag in AWS stack updates

---

webui/react/src/hooks/useModal/Experiment/useModalExperimentMove.tsx

The actual request is not failing, the error being thrown is [`Required parameter id was null or undefined when calling getWorkspace`](https://github.com/determined-ai/determined/blob/e6813e10a3f0195be4d9e52afbe3cbda935c4fb2/webui/react/src/services/api-ts-sdk/api.ts#L26200), but is suppressed by `processApiError`. 
The reason that we are able to call `getWorkspaceProjects` with undefined id, even though the types say it is defined, is basically because antd `useForm` lies about the types. If you say
```
const form = useForm<{workspaceId: number}>()
const workspaceId = Form.useWatch('workspaceId', form);
```
then `workspaceId` officially will have the type `number` but can be `undefined` if the corresponding form value is empty.
In the spirit of keeping the scope small for a release …

fix: stop "Request getWorkspaceProjects failed." notifications

---

webui/react/src/components/kit/LogViewer/LogViewerSelect.tsx

regression from moving `SelectFilter` to kit, looks like this got lost in the mix
verify that trial details logs level select filter shows up properly with no level selected (also with level selected)

fix: log level filter width

---

docs/interfaces/commands-and-shells.rst

minor edits including typo fixes in preparation for larger updates
mainly:
Installed the CLI using the pip utility:
changed to:
Install the CLI using the pip utility:

docs: minor edits to commands and shells

---

master/go.mod
master/internal/db/postgres.go
master/internal/user/external_users.go
master/internal/user/postgres_users.go

This is a small refactor to allow changes to UserByExternalToken to not cause rebase conflicts between forks. Moving UserByExternalToken to its own file and just putting a no-op placeholder, because it's never used in the main fork. And allowing existing DB queries to be run through a singleton instance, similar to what we do with Bun.

chore: preparing to integrate UserByExternalToken with SCIM support

---

agent/internal/container/container.go
agent/internal/container/container_api_test.go

Completing work in [TODO Comment](https://github.com/determined-ai/determined/blob/master/agent/internal/container/container.go#L221):
- When:
- Container has started
- But it hasn't started running
- And the container is killed using a SIGKILL
- Then:
- The docker container will not correctly due to the context being cancelled
So, instead of using the context that was used to spin up the docker container, the parent context is instead used.
Added new integration test `agent/internal/container/container_api_test.go` to create a container, kill it upon the creation of the underlying docker container, and confirm the container is properly removed.
DET-8988

fix: ensures docker container is cleaned up if a container is killed after start, but before run [DET-8988]

---

docs/_templates/analytics.html
docs/_templates/page.html

Previously, we copy/pasted page.html from the furo theme, then made modifications throughout it.
Now, we extend page.html and (nearly) all of our modifications fit inside blocks specifically exposed to us.
As a result, we are no longer so tightly bound to the furo version.
Before this change, the diff between our `page.html` and furo's `page.html` were as follows:
```diff
--- /home/rb/code/source/furo/src/furo/theme/furo/page.html	2023-03-14 15:57:45.562008862 -0600
+++ _templates/page.html	2023-03-14 16:33:28.527841043 -0600
@@ -1,12 +1,30 @@
{% extends "base.html" %}
+{% block extrahead %}
+
+<script>
+    window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
+
+    ga('create', 'UA-110089850-1', 'auto');
+    ga('set', 'transport', 'beacon');
+    ga('send', …
```

docs: use theme templates better

---

webui/react/src/components/LearningCurveChart.tsx
webui/react/src/components/UPlot/UPlotChart.tsx
webui/react/src/components/kit/LineChart.tsx

Saw this while debugging other code. The focus / highlight series on DesignKit was getting erased as new data was added.
The best way to support this isn't the `chartRef.current.setSeries` from our current uPlotChart helper library, but setting alpha value directly.  The only other place using this feature is the soon-to-be-removed LearningCurve chart. I changed the setting there and removed it from uPlotChart.
- Visit `/det/design` and scroll to second chart
- Purple line remains "focused" while new data is being added

fix: Chart focus maintained as series changes

---

webui/react/src/components/kit/Nameplate.module.scss
webui/react/src/components/kit/Nameplate.tsx

Needs to maintain width when sidebar is collapsed
Collapse sidebar and make sure Avatar in top-left is at full width
WEB-1048

fix: Nameplate icon width bug

---

docs/release-notes/remove-pt-callbacks.rst
harness/determined/pytorch/_callback.py
harness/determined/pytorch/_pytorch_trial.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py

remove deprecated on_validation_step_begin/end callbacks.
This should go out in the next breaking change release, which will be 0.21.0 for Trainer API.

chore: remove deprecated validation callbacks [MLG-21]

---

.circleci/config.yml
e2e_tests/tests/api_utils.py

`certs.default_load` is called by the auth-related helpers, but not by `configure_token_store` sometimes used in e2e tests.
`using_k8s` fixture uses `configure_token_store`.
when a handful of tests that use `using_k8s` became the first in the test split, it broke.
`test-e2e-gpu-single` works.
`circleci tests split --split-by=timings` is a source of non-determinism.

test: initialize certs properly in an auth utility [DET-9104]

---

master/internal/db/postgres_experiments.go
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/ExperimentVisualizationFilters.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx

LearningCurve typically is based on its searcher metric from the validation metrics. This causes a delay if validation hasn't happened and filled metric names yet.
Solution: similar to our single-trial charts, if our preferred metric is not available yet, show the 0th metric.
- Visit a previous multi-trial experiment and it should show validation metric.
- Create a test experiment with no validation metrics, or in `src/hooks/useMetricNames.ts`, simulate by commenting out
```typescript
(event.validationMetrics || [])
.filter((metric) => !xAxisMetrics.includes(metric))
.forEach((metric) => (validationMetricsMap[metric] = true));
```
- With validation metrics removed, a multi-trial experiment will show one of its training metrics.
- Fork a multi-trial experiment and it will start out blank. …

fix: Load multi-trial learning curve with only training metrics [WEB-1026]

---

model_hub/model_hub/mmdetection/_callbacks.py

flake8-comprehensions==3.11.0 just dropped and it found a simplification for us to make.
It is straightforward to validate that this change is a noop:
```python
optimizers = ['a', 'b', 'c', 'd', 'e']
old = {i: opt for i, opt in enumerate(optimizers)}
new = dict(enumerate(optimizers))
assert old == new
```

chore: update code for new flake8 upgrade

---

master/internal/task/allocation.go

`time.Now().UTC()` internally calls `t.stripMono()` which makes this check susceptible to clock resets.
- [???] reproducing this is very hard

fix: allocation rekill shouldn't use time.UTC in fine time checks [DET-9149]

---

examples/deepspeed/gpt_neox/det_utils.py
examples/deepspeed/gpt_neox/gpt2_trial.py
harness/determined/pytorch/_pytorch_context.py
harness/determined/pytorch/deepspeed/_deepspeed_context.py

When we added more imports of SummaryWriter, we forgot to include the workaround for the distutils bug affecting torch >=1.9 <1.11.

fix: expand torch + distutils workaround [DET-9158] 

---

master/internal/task/idle_timeout_test.go

With a tick of just one millisecond, scheduling could apparently vary enough that even attempting to wait multiples of the tick could still fail in practice. Increasing the tick by enough should cover that variance while allowing us to simplify the logic.

test: attempt to make TestIdleTimeoutWatcher more reliable

---

webui/react/src/pages/WorkspaceList/WorkspaceCard.tsx

[WEB-1084]
https://user-images.githubusercontent.com/109113616/227063638-f50ba3ec-9e32-4824-959a-8760ffcb5765.mov
- Go to workspaces
- Click on “Edit” from a workspace card’s dropdown
- Check if clicking outside the modal to dismiss the modal and clicking on the modal doesn't cause page transition
[WEB-1084]: https://hpe-aiatscale.atlassian.net/browse/WEB-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: workspace card issue

---

webui/react/src/utils/README.md

This adds some basic non-jsdoc documentation for Loadables. Some members of the team find JSDoc hard to read so I wrote a more conversational document on usage of Loadables.
N/A
N/A

docs: Add usage examples for Loadable

---

webui/react/src/components/kit/LogViewer/LogViewerSelect.tsx
webui/react/src/shared/prototypes.ts

NOTE: If we decide to send back an empty string for agent ID filter option, the WebUI will automatically show a `No Agent ID` as an option also.
PROBLEM:
Problem, we hide the agents filter today when there is 1 or less option. Because we don't show agent ID info in the logs, it's hard to discern what agent the task logs are coming from.
SOLUTION:
Update log viewer filters to show agents filter if there is at least one entry. @trentwatt did all the heavy lifting for this.
ADDITIONAL FIX:
Fix the sortAll logic to handle 0 or 1 element.
WEB-1083

feat: show log viewer agent filter options even when there is one option

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx

This resolves an issue where this validation-only experiment ( https://gcloud.determined.ai/det/experiments/2301/visualization/learning-curve ) has trials but no chart or loading message.
- I discovered that this page shows `<Spinner tip="Fetching metrics..." />` but it is not visible for unclear reasons?
- With the new changes, if there is no activeMetric, and searcherMetric is not available, we will graph the 0th metric
With devcluster to run this code locally,
- command + space = open the omnibar
- Enter `dev serverAddress https://gcloud.determined.ai` to change backends
- Log in as admin using password for that server
- Visit `localhost:3000/det/experiments/2301` and confirm a learning curve chart now appears
See [Release Note](https://github.com/determined-ai/determined/blob/master/do …

fix: Learning curve on validation-only experiment

---

webui/react/src/pages/Settings/UserManagement.tsx

Makes the users table more like ExperimentList in indicating when a name filter is applied. Uses isFiltered and a button which calls an existing filter reset.
There is no filter like this on the Groups filter.
- As admin, visit the Users page. There is no filter applied, all users are shown, the 🔍 on the name column is grey
- Click the 🔍 and enter in a name to filter users by name.
- The users list is limited. The 🔍 is now blue, and a button "Clear Filters (1)" appears at top right of the table.
- Refreshing the page keeps filter settings, and blue 🔍 and Clear Filters button.
- Clicking Clear Filter returns to all users view
- Refreshing the page keeps all-users view

fix: Indicate and clear user search filter [WEB-1074]

---

webui/react/src/pages/WorkspaceDetails/WorkspaceMembers.tsx

Code based on #6309 - when we filter the workspace members by username, we should:
- highlight the 🔍 icon in blue
- reset tableOffset setting to 0 (to avoid being on page 2 and not showing a unique username)
- show a "Clear Filters (1)" button to remove name search
In EE (where workspaces have a Members tab):
- filter the workspace members by username
- confirm visibility of blue 🔍 on column, and Clear Filters button
- click Clear Filters button to remove the filters

fix: Indicate and clear workspace member search filter [WEB-1088]

---

docs/Makefile
docs/README.md
docs/_templates/page.html
docs/assets/scripts/docsearch.sbt.js
docs/assets/styles/docsearch.sbt.css
docs/conf.py
docs/deploy/start_algolia_crawl.sh

Versioned algolia searches, relative algolia searches, and hiding the sphinx search bar are all working.
When the default search bar is hidden, the spacing is a bit off, but that's pretty minor.

docs: add algolia search [MLG-367]

---

webui/react/src/components/UPlot/SyncProvider.tsx

In ChartGrids with different maximum X values, the final point is not hover-able. Discovered that `dataBounds` was not updated (always undefined when we show up here) ~, so we can just use `unzoomedBounds`~
I've been using 2125 from latest-master
Set `f_chart=on`
Test streaming in of data from a running experiment, then refresh to test on a completed experiment.
In LineChart, after `yValues[serieIndex][xVal] = Number.isFinite(pt[1]) ? pt[1] : null;` , you can make validation series add a second point at different x-values after the training data.
```typescript
if (serieIndex % 2) {
const xVal2 = Math.round(pt[0] * (1 + Math.random()));
xSet.add(xVal2);
yValues[serieIndex][xVal2] = pt[1] * 1.2;
}
```
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-not …

fix: dataBounds was never updated, use unzoomedBounds for chartgrid sync [WEB-1039]

---

master/pkg/tasks/task_gc.go

CheckpointGC's TaskSpec has a ResourceConfigV0 that is not properly instantiated, so its use caused panics in Slurm code.

fix: GC task spec's ResourcesConfig should be valid

---

webui/react/src/shared/utils/data.ts

App theme not applied due to `checkDeepEquality` uses `isEqual` to detect state changes, and `isEqual` sorts on object keys, which isn't quite correct for nested objects. 
https://github.com/determined-ai/determined/blob/0d4281e1632da8de98049a91352c7537d9b6d678/webui/react/src/shared/utils/store.ts#L16
Verify that app style can properly load.
Before:
After:
Changes in this PR only reverts what's been done in https://github.com/determined-ai/determined/pull/6202 to `isEqual` function.
I also attempted to replace our current `isEqual` with the `isEqual` from lodash, but according to the test cases, we want 
`{ abc: 123 }, { abc: 123, ghi: undefined }` equal 
`Symbol('coin'), Symbol('coin')` equal
`new Set([[1]]), new Set([[1]])` not equal
These test cases do not align with lodash's …

fix: isEqual utility function

---

tools/scripts/refresh-ubuntu-amis.py

update-ubuntu-amis.py is not finding AMIs due to changes made to the table we were querying.
This PR changes the query endpoints we use and how these new endpoints are parsed.
run `refresh-ubuntu-amis.py --bumpenvs-yaml ...`
run `refresh-ubuntu-amis.py --packer-json ...`
MLG-368

fix: update ubuntu ami tables

---

e2e_tests/tests/cluster/test_workspace_org.py
master/internal/api_workspace.go

Previously, when a workspace with a duplicate name was attempted to be created, the result was an internal server error.
Now, when a workspace with a duplicate name is created (either through a Post or a Patch) the result is:
- gRPC code 6 (AlreadyExists)
- HTML 409 Conflict
Added checks in `e2e_tests/tests/cluster/test_workspace_org.py`:`test_workspace_org`
DET-8808

fix: handle duplicate workspace name DB errors [DET-8808]

---

harness/determined/deploy/gcp/cli.py
harness/determined/deploy/gcp/terraform/modules/compute/main.tf
harness/determined/deploy/gcp/terraform/outputs.tf
harness/determined/deploy/gcp/terraform/variables.tf
master/internal/config/provconfig/gcp_config.go
master/internal/config/provconfig/gcp_config_test.go
master/packaging/master.yaml

These changes make user-defined labels on GCP deployments, specified as in `det deploy gcp up ... --add-label foo=bar`, be propogated to dynamic agents. [MLG-365]
This does not happen already because, while other components of a Determined GCP deployment are handled by Terraform run in subprocesses created by the `harness`, dynamic agents are created by API calls in `determined-master`.
1. Add an extra volume to the determined-master Docker container command in the metadata_startup_script of the master instance: `-v /path/to/determined-master:/usr/bin/determined-master`. This change should not be committed!
2. Create a deployment with the modification from step 1, including at least one user-defined label like `--add-label foo=bar`. The master health check is _expected to fail_ (because …

feat: propogate gcp cluster labels to dynamic agents [MLG-365]

---

master/internal/trial.go
master/pkg/tasks/task_trial.go

All trials within an experiment share their default task spec, so writing to a map on it causes concurrent map writes. Fix this by moving writes to after the trial creates its shallow copy.
@jerryharrow / @erikwilson , I presume you saw this with HP search? That would mostly confirm deny my theory.

fix: set unique port reqs on trial's shallow copied task spec

---

harness/determined/cli/agent.py

This is another attempt at getting 'slot list' going for dispatcher -- presently it prints an error.
The code responsible for producing the output of 'det agent' & 'det slot' is agents.py.
'det slot' was failing in fetching the agents, so I made it more like 'det agent' which does not suffer from this defect.
We don't actually know at present in the dispatcher RM which slots are in use; we only track total and in-use GPU counts, and simply return the correct number of occupied slots in the agents response. Nor do we track the slot location of specific allocations (that's left to the WLM), so we currently can't work back to display the task name. I put in a helper to identify the slot container ID as 'cluster', in which case we do not print a task name.
We don't presently discover the …

fix: get 'slot list' going for dispatcher

---

master/pkg/syncx/mapx/mapx.go
master/pkg/syncx/mapx/mapx_test.go

Slurm code has a ton of sync.Maps and/or map[K]V with a mutex beside it called `mapNameMutex`. Both kinda suck, and this is easy enough to add.
eh. open to some oss lib, too, but I didn't see anything. or a better name.

chore: replacement for sync.Map and/or maps beside mutexes with long names

---

webui/react/src/__mocks__/router.tsx
webui/react/src/ee/SamlAuth.ts
webui/react/src/index.tsx
webui/react/src/pages/InteractiveTask.test.tsx
webui/react/src/router.tsx
webui/react/src/shared/utils/routes.test.ts
webui/react/src/shared/utils/routes.ts
webui/react/src/utils/error.ts

Some cleanup ahead of WEB-1043 where we need the ability to display the designkit without the server running -- this removes the circular dependency where the router is dependent on itself. Instead, we wrap the router in an object that's instantiated in the index file. The mock is also updated for testing purposes.
No ticket

chore: Fix router/app circular dependency

---

harness/determined/deploy/gcp/cli.py
harness/determined/deploy/gcp/constants.py
harness/determined/deploy/gcp/terraform/main.tf
harness/determined/deploy/gcp/terraform/modules/compute/main.tf
harness/determined/deploy/gcp/terraform/modules/compute/variables.tf
harness/determined/deploy/gcp/terraform/variables.tf
master/internal/config/provconfig/gcp_config.go
master/internal/config/provconfig/gcp_config_test.go

These changes allow users to specify the [boot disk size and type](https://cloud.google.com/compute/docs/disks) for dynamic agents. [MLG-224]
The parameters are written to a configuration file in the `metadata_startup_script`; this configuration file is used by the provisioner in `determined-master`.
1. Add an extra volume to the determined-master Docker container command in the metadata_startup_script of the master instance: `-v /path/to/determined-master:/usr/bin/determined-master`. This change should not be committed!
2. Create a deployment with the modification from step 1, including specifications like `--disk-size 159 --disk-type pd-balanced` (the default values are `200` and `pd-standard`). The master health check is _expected to fail_ (because the Docker container can’t find the …

feat: specify disk size and type for dynamic agents in gcp deployment [MLG-224]

---

docs/release-notes/checkpoint-size-speedup-speedup.rst
master/internal/db/postgres_checkpoints.go
master/internal/db/postgres_checkpoints_intg_test.go

Usage of checkpoints view caused postgres to do a bunch of unnecessary joins. Going to both checkpoint tables improves this.
Existing integration tests.

fix: checkpoint insertion slow performance on big databases [DET-9219]

---

docs/reference/reference-deploy/config/master-config-reference.rst
docs/release-notes/launcher-jvm-args.rst

- Add master config reference doc for resource_manager.launcher_jvm_args
- Add release note
- Validated text via grammerly.com

docs: Add resource_manager.launcher_jvm_args [DET-9230]

---

.circleci/config.yml

[DET-9231]
Our e2e tests were using the default CIDR for pods as defined by GKE, which was as large as /14 in some cases. We are now specifying this to /16 to prevent intermittent test issues.
CI is green. Shouldn't need manual testing.
[DET-9231]: https://hpe-aiatscale.atlassian.net/browse/DET-9231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: allocate less address space in e2e gke cluster tests [DET-9231]

---

.circleci/config.yml

Reverts determined-ai/determined#6393
Perhaps a much smaller space like /20 would be better? Reverting for now

Revert "chore: allocate less address space in e2e gke cluster tests [DET-9231]"

---

.circleci/config.yml

Deploying the latest-master cluster sometimes fails when two commits land too close together; the queue job keeps the actual executions from overlapping, but it seems that CloudFormation will still sometimes fail, with no error logging that I can find other than the failed command, if two deploys happen in sufficiently quick succession. So throw a retry on there, as is our wont.
Stack deletion can also fail; I have no idea why that is, but throw a retry on there too.

ci: retry deploying AWS clusters [DET-9232]

---

master/internal/api_agents.go
master/internal/rm/actorrm/actor_resource_manager.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/resource_manager_iface.go
master/internal/rm/rmerrors/errors.go

It is not the case that we will allow a determined admin to enable or disable slots in the cluster -- that would be up to the manager of the cluster. So lets print a better error message.
With guidance from Bradley this PR introduces new RM interfaces for slot management. The implementation for kubernetes is 'not supported', while for agents we get the same behavior as before. Once this change is in place we will add a dispatcher implementation (also 'not supported'), and this will be documented as a known limitation.
Here's what this would look like on a HPC cluster when all the parts are in place. First the old message:
_Failed to enable slot on agent: {"error":{"code":5,"reason":"NotFound","error":"actor /agents/node010/slots/2 could not be found"}}_
And the new message:
_Failed to …

fix: slot enable/disable for HPC cluster

---

harness/determined/cli/checkpoint.py
harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/errors.py

- Only allow downloading completed checkpoints
- Print a nicer error message for the others
- downloading good checkpoints should work ok.
- downloading deleted checkpoints should print a nice error.

fix: allow `det checkpoint download` for completed checkpoints only [DET-3786]

---

.circleci/devcluster/double.devcluster.yaml
docs/release-notes/fix-default-pool-task-container-defaults.rst
e2e_tests/tests/cluster/test_resource_pools.py
master/internal/api_command.go
master/internal/core_experiment.go
master/internal/restore.go

- Specify some config in `task_container_defaults` for the default pool
- Submit a task to the default pool in a default way, that is, don't specify it in the config explicitly.
- Pool config still should be applied.

fix: respect default pool task container defaults [DET-9241]

---

harness/tests/launch/test_launch.py

`true` and `false` don't always exist in `/bin` in every POSIX-compliant system. This patch removes this assumption at the cost of assuming that the commands are either built into the shell or somewhere in the PATH environment variable.
`pytest harness/tests/launch/test_launch.py`

test: Make `test_launch` more portable.

---

docs/reference/reference-deploy/config/helm-config-reference.rst
helm/charts/determined/templates/db-deployment.yaml
helm/charts/determined/templates/master-deployment.yaml
helm/charts/determined/values.yaml

#6431 
Deploying onth k8s with this helm chart. (HPE Ezmeral Runtime 5.6)
User-facing change types:
- feat: new user-facing feature

feat: Add quota limits for helm

---

examples/Makefile

There was a bug causing examples to not rebuild when they should have,
which was causing issues for engineers unaware of the bug.
Specifically, when new files appeared in glob patterns, but which were
created before the build.stamp (which can happen if you
build-then-rebase), then you could run `make -C examples build` and it
would insist there was no work to do.  The same issue would happen if a
file was deleted, no rebasing required.
Build bugs are always much worse for anyone not intimately familiar with
the build system, and as we grow this is getting more obvious.
The new logic is a bit faster for clean builds (1.5s to 1.1s for me) and
a bit slower on noop builds (0.05s to 0.11s).
Additionally, the new logic makes a couple of strategic sacrifices:
- The per-example incremental …

build: fix examples makefile

---

e2e_tests/tests/deploy/test_local.py

In service of diagnosing a flaky test, this makes the tests check that `det deploy` exited successfully and adds a log dump in the failure case for that test.

ci: check `det-deploy` exit status in `test_local.py`

---

.circleci/config.yml

These commands fail sometimes; enabling debug mode will show us a stack trace that is otherwise hidden.

ci: enable debug mode for `det deploy aws` commands

---

master/go.mod
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/pods_test.go

Takes care of DET-9122.
Cluster info page should accurately reflect your cluster setup by taking taints and tolerations into account. If a cluster has no taints, every node should belong to every resource pool.

feat: k8s cluster info using taints/tolerations

---

docs/release-notes/6460-hdfs.txt
harness/determined/common/storage/hdfs.py

It has not been tested in years, and AFAIK no customer or user has successfully used it since we went open-source.

chore: deprecate HDFS storage support

---

ds_autotuning_prototype/core_api/ffn_example_torch_launcher/search_runner_config.yaml
ds_autotuning_prototype/core_api/torchvison_models/zero_search_config.yaml
harness/determined/pytorch/deepspeed/dsat/_dsat_search_method.py
harness/determined/pytorch/deepspeed/dsat/_utils.py

Previously I merged user-supplied zero optimizations with the defaults, but it is cleaner to not do that.

fix: do not merge user zero search config with defaults

---

docs/architecture/introduction.rst
docs/cluster-setup-guide/basic.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/overview.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-k8s/setup-eks-cluster.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst
docs/cluster-setup-guide/historical-cluster-usage-data.rst
docs/cluster-setup-guide/security/rbac.rst
docs/interfaces/cli-ug.rst
docs/interfaces/commands-and-shells.rst
docs/interfaces/index.rst
docs/interfaces/notebooks.rst
docs/reference/cli-reference.rst
docs/reference/reference-interface/job-config-reference.rst
docs/reference/reference-training/experiment-config-reference.rst
docs/training/dtrain-introduction.rst
docs/tutorials/pytorch-porting-tutorial.rst

- If a link is used as if referring to a location (e.g., "see <link> for more"), then it may implicitly use the target's title as the link text. However, if the text of the link is intended to form a natural part of the surrounding sentence, then the text should be specified explicitly to ensure that the sentence continues to make sense even if the title is changed.
- We don't need to capitalize "command" or "shell", or "notebook" as a general concept (though "Jupyter Notebook" is the name of a particular product). But note the B in "TensorBoard"!
- The hyphenated "command-line interface" lines up better with our current usage (and my preference).

docs: do some copy editing

---

docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-known-issues.rst
docs/cluster-setup-guide/deploy-cluster/sysadmin-deploy-on-slurm/slurm-requirements.rst

PBS Workload Manager relies on the value `resources_available.accel_type` to identify the GPU type. This value is used to populate the `Accelerator` field on the Resource Pool Configuration page. If the value of `resources_available.accel_type` is not set on a node. The Resource Pool Configuration page will include a value `unconfigured` in the Accelerator field. To fix this problem, HPC system admins can set the value for `resources_available.accel_type`. This PR describes this issue as part of the `slurm-known-issues` section and also provides instructions on how to fix the issue.
These instructions were manually tested on the casablanca-login2 machine.
Before
After
Please refer the image below for the newly added sub-section.
See [Release …

docs: add a known issue and its fix for PBS - Display valid value for Accelerator field in the Resource Pool Configuration

---

master/internal/api_user_intg_test.go
master/internal/config/config.go
master/internal/config/config_test.go
master/internal/config/provconfig/config.go
master/internal/config/resource_pool_config.go
master/internal/core.go
master/internal/rm/agentrm/agent_resource_manager.go

Another take on #6387 
`*ResourceConfig` pointer embedding was a landmine which made the value method `func (c Config) Printable` mutate the underlying config.
- Deploy MLDE cluster using docker credentials `det deploy ... --docker-user ... --docker-password ...`
- Make sure these credentials are not visible in master config or cluster -> resource pool card -> config.
- Make sure the jobs still run.

feat: treat instance startup script as a secret #2 [DET-9214]

---

docs/index.rst
docs/tutorials/index.rst

change title of tutorials page back to tutorials
(change from "Try" to "Tutorials")

docs: Edit Page Title

---

docs/release-notes/fix-default-pool-task-container-defaults.rst
docs/release-notes/fix-zero-slot-limits.rst

Release note edits for k8s fixes.

docs: release note edits.

---

.circleci/config.yml

We are seeing some failures caused by rate limits, hence we are bumping
the max number of retries with exponential backoff, which also reduces the 
request rate.
N/A

ci: more retries for `det deploy` [DET-9256]

---

docs/release-notes/tasks-404-fix.rst
master/internal/api_tasks.go
master/internal/api_trials_intg_test.go
master/internal/core_task.go
master/internal/experiment.go
master/pkg/model/task.go

Task list was asking the rm for task information twice causing a race for the task to not be found on the second ask.
Existing tests + EE test run here
https://github.com/determined-ai/determined-ee/pull/798

fix: task list race caused incorrect 404s to be returned [DET-9293]

---

master/internal/experiment/bulk_action.go

`FilterExperimentsQuery` expects `workspace_id` column, but it was not present.
1. Setup RBAC permissions so a user only has an editor role on a particular workspace, not globally.
2. Try to kill/activate/move/delete experiments in this workspace.
- This is a hot fix but we need automated tests for this.

fix: exp actions with workspace-specific user perm [DET-9300]

---

harness/determined/common/storage/cloud.py
harness/determined/common/storage/shared.py
harness/determined/core/_distributed.py
harness/determined/deploy/gcp/gcp.py
harness/determined/estimator/_estimator_trial.py
harness/determined/tensorboard/shared.py
harness/determined/util.py

Apparently NFS can cause rmtree to fail, so we avoid calling it directly, and instead call it in a new rmtree_nfs_safe wrapper function.
I'm not going to lie, I don't have any experience with NFS, but I'm not entirely convinced that `rmtree` should fail on a healthy NFS.  It seems like there'd be a lot more evidence of it in google searches, and I'd kind of expect `shtuil` to have some sort of workaround for it by now.
Also, there's the matter of the filelocks that aren't getting cleaned up that also make me suspect this CI filesystem isn't fully healthy.
EE tests at https://github.com/determined-ai/determined-ee/pull/802.

fix: wrap shutil.rmtree in a loop [DET-9127]

---

.circleci/config.yml

We've seen a few transient failures (timeouts and 500s) while publishing to Docker Hub (e.g., [1]), so throw a retry on there.
[1] https://circleci.com/gh/determined-ai/determined/1313744

ci: retry Docker Hub publish steps

---

master/internal/rm/agentrm/resource_pool.go

Nil pointer dereference crashes resource pool when running on a system without provisioner. 

fix: nil pointer when running locally

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/contextMenu.tsx

Replaces #6475 for a working Netlify preview.
Right-clicking on the Glide table opens an antd Menu similar to our current experiment list context menu. These options are actions for the current user to apply to the selected experiment (e.g. Archive, Move)
Notes:
- Pin / Unpin is not supported in Glide, and current implementation has useSettings, so it's not used here
- The menu stays visible until the action is completed (for example Archive will send a request to the server, then update the experiment list).
- Now sharing code with ExperimentActionDropdown
Visit a project with a few experiments with the Glide table flag on (for latest-master backend, I used `/det/projects/107/experiments?f_explist_v2=on`)
- ""Right clicking"" on a table cell shows context menu at clicked location
- …

feat: Right-click for context menu in Glide table [WEB-977]

---

master/pkg/model/task_container_defaults.go
master/pkg/model/task_container_defaults_test.go

Expconf slurm|pbs.sbatch_args replaced task_container_defaults sbatch_args. Need to append instead.
Add unit test cases for Slurm/Pbs Config and inheritance.
Validated with [Slurm inheritance slumcluster.sh config on casablanca](https://github.com/determined-ai/determined-ee/pull/762).
Submitted Configuraiton
Runtime Configuration

fix: Append instead of replace sbatch args [DET-9263]

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/linkCell.tsx

We discussed an issue with the custom links-cell opening onMouseUp even if that's not where we clicked.
On investigation, glide remembers `lastMouseDown` to detect these traveling/dragged clicks and avoids calling `onCellClicked` for them. But then it continues on to call any custom renderers' `onClick` 👿  https://github.com/glideapps/glide-data-grid/blob/main/packages/core/src/data-editor/data-editor.tsx#L2012
So my suggestion is instead of links-cell calling `useNavigate`, we use `onCellClicked`. The way I got this cell's type and links is the same as the renderer. We basically re-render the cell. If there's a better way to get the link let's find it.
With flag `?f_explist_v2=on`
- Left-click a row normally to select and un-select the row
- Left-click a link normally to travel to its …

fix: use onCellClicked instead of links-cell [WEB-1141]

---

docs/release-notes/exp-trial-task-logs-json.rst
harness/determined/cli/experiment.py
harness/determined/cli/remote.py
harness/determined/cli/task.py
harness/determined/cli/trial.py
harness/determined/common/api/__init__.py
harness/determined/common/api/logs.py

Other trial & experiment CLI commands (ex. `det trial describe`) already have a `--json` flag, so this is just a matter of extending that functionality to the `det e logs <experiment-id> --json`, `det t logs <trial-id> --json`, and `det task logs <task-id> --json`.
In doing so, I also refactored the printing functions inside logs.py to combine `pprint_task_logs` + `pprint_trial_logs` -> `pprint_logs` by moving the final print statement to original handlers for `det e|task|trial logs`. Additionally, the `--json` CLI argument (and other output formatting arguments) in `experiment.py, task.py, trial.py, task.py` were imported from `_util.py`.
Simply run `det e logs <experiment-id> --json`, `det t logs <trial-id> --json`, `det task logs <task-id> --json` and confirm the output is of the …

chore: add --json to det e|task|trial logs [DET-8982]

---

docs/reference/reference-deploy/config/agent-config-reference.rst

Add structure to agent config ref, replacing bulleted lists with heading levels, to enable better search results. Edit content to enable readability and better search results.

docs: Add structure to agent configuration ref

---

master/internal/api_trials_intg_test.go
master/internal/trials/postgres_trials.go

- Metrics sampling broke for trials which report "epochs" because floats couldn't be deserialized into ints: https://determined-community.slack.com/archives/C04PZL88HDL/p1681744867345819
- also change setseed usage so the samples are reproducible.
- add tests for both issues.
Run any experiment which reports metrics, e.g. https://github.com/determined-ai/determined/blob/master/examples/tutorials/core_api_pytorch_mnist/model_def_metrics.py#L73

fix: metrics sampling for metrics with epochs.

---

docs/reference/reference-training/experiment-config-reference.rst

Experiment Configuration Reference page: Add structure to enable algolia search index to find field names on the page.

docs: enable algolia search by adding structure

---

webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.test.tsx
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetails.test.tsx

When go directly to experiment details page (without going to clusters page first), Hyperparameter Search modal does not close properly.
This issue is caused by `resourcePools` not available in this component so I added a poll to fetch `resourcePools`. 
cc @hkang1 to verify this is the proper way to do it. 
Go to experiment details page, open Hyperparameter Search modal, you should be able to close it. 
WEB-1149

fix: close modal properly

---

docs/assets/scripts/docsearch.sbt.js

Previously, searches from the root index.html emitted absolute paths on
accident, rather than relative ones.  Now we handle that case properly.
This was a regression from only yesterday.
Also, previously, emitted URLs were relative.  Algolia was caching
the relative URLs in the historical entiries of the search modal, and
they were not working when clicked from other locations.  Now we convert
relative URLs to absolute URLs based on window.location so that Algolia
caches values that are usable from anywhere.

docs: fix searchbar result paths

---

master/go.mod
master/internal/core.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/pods_test.go
master/internal/rm/setup.go

Update to #6425 (which was reverted), but includes the global task container defaults' tolerations while deciding whether a node belongs to a resource pool. This fixes [an issue](https://app.circleci.com/pipelines/github/determined-ai/determined/36281/workflows/18c95a74-1bae-4617-a2a4-f44d98f4072f/jobs/1304145) detected by our end to end tests. Takes care of DET-9122.
Same as #6425.
DET-9122

feat: k8s cluster info using taints/tolerations incl. global ones

---

master/internal/api_command.go
master/internal/experiment.go

fixes launch error so that it has the expected behavior of not returning an error for kubernetes or slurm.

fix: launch error has no effect for k8s and slurm

---

master/internal/db/postgres_trial.go

The SQL statement for trial update is missing a `where trial.id = $1` to ensure the proper trial entries get updated.
DET-9369

fix: update searcher_metric_values properly [DET-9369]

---

docs/reference/reference-deploy/config/master-config-reference.rst

Add structure to master config ref, add heading levels, to enable better search results

docs: Add structure to master config ref

---

webui/react/src/components/WorkspaceMemberAddModal.tsx

The new standard modal for Add Member [to a workspace] recently changed the `groupName` prop to `name`. This was hiding groups when searching for users+groups by name inside the Add Member modal.
In an EE / RBAC environment
Open a workspace other than Uncategorized
Go to the Members tab, and click the "Add Member" button at right
In the "User or Group" section, type the start of user or group names and confirm the name filter is focusing on them

fix: Workspace member modal includes users and groups

---

.circleci/config.yml
e2e_tests/tests/deploy/test_local.py

Bit of a heavy hammer, but the issue with these tests appears to not be specific to any particular test: after some specific tests in `test-det-deploy-local` were quarantined, other tests that were left behind started failing in the same way. And now `test-stress` seems to be showing the same thing as well.
@azhou-determined is working on the underlying issue, so ideally we'll be able to unquarantine these entirely soon..

ci: fully quarantine `test-det-deploy-local` and `test-stress`

---

master/internal/rm/kubernetesrm/pods.go

Fixing an e2e test (test-e2e-gke-k8s-reattach) failure.
Same as #6518.

fix: include global TaskContainerDefaults when no resource pool

---

.circleci/config.yml
docs/Makefile
docs/conf.py
docs/deploy/scrape.py

Scrape + upload Aloglia records of the "dev" version on every commit that lands on main.  The dev index is used by source builds of the docs. This implies that old source build won't have a functional search bar, but that seems fine.
Scrape + upload Alogila records for the official version on every commit that is either tagged as a release or a release candidate.  There's no point in keeping extra release-candidate search indices.

ci: auto-scrape algolia records

---

harness/determined/cli/experiment.py
harness/determined/common/api/profiler.py
harness/determined/common/api/request.py
harness/determined/common/context.py
harness/determined/common/storage/hdfs.py
harness/determined/ipc.py
harness/determined/tensorboard/hdfs.py
harness/setup.py
harness/tests/test_imports.py
master/static/srv/check_ready_logs.py
master/static/srv/enrich_task_logs.py

loading harness takes around 0.75s on my machine. there's quite a few imports that can be lazily-imported to reduce load time.
**Before**
```
Program: determined.cli.cli
0.753 <module>  harness/determined/__init__.py:1
└─ 0.725 <module>  harness/determined/core/__init__.py:1
├─ 0.674 <module>  harness/determined/core/_checkpoint.py:1
│  └─ 0.673 <module>  harness/determined/tensorboard/__init__.py:1
│     └─ 0.660 <module>  harness/determined/tensorboard/metric_writers/__init__.py:1
│        └─ 0.659 <module>  harness/determined/tensorboard/metric_writers/callback.py:1
│           └─ 0.658 <module>  harness/determined/util.py:1
│              └─ 0.655 <module>  harness/determined/common/__init__.py:1
│                 ├─ 0.378 <module>  harness/determined/common/api/__init__.py:1
│ …
```

chore: lazy load imports to speed up load time [MLG-455]

---

.circleci/config.yml

Accidentally had the doc-scraping in a release workflow, but wanted it somewhere where it would run much more often.

ci: actually auto-scrape algolia records

---

e2e_tests/tests/cluster/test_users_experiment_api.py

Fix test flake that occurred here
https://app.circleci.com/pipelines/github/determined-ai/determined/37363/workflows/df112a8d-6f8f-41c6-89e9-db0e31d05826/jobs/1355952
e2e_cpu passes
My running assumption is the reason why it has been passing was a race between spawning the process and master deactivating determined.
If it instead it was an error that happened when deactivating the user or a legitimate bug in deactivating users added two asserts to catch that.

test: fix test_experiment_api_determined_disabled flake

---

.circleci/config.yml

With a prefix of `mmdetection-quarantine`, an S3 bucket in the stack would try to have a name longer than the maximum of 63 characters, so stack creation would always fail.
The original `mmdetection` doesn't need to be shortened to work, of course, but I figure both of them ought to be the same.

ci: reduce overly long CloudFormation stack name

---

harness/determined/tensorboard/base.py
harness/determined/tensorboard/shared.py

Although a distributed experiment would successfully run to completion, there were warning messages that said "directory does not exist".
For example, I ran the following experiment.
```
(base) rcorujo@C02FJ0T8MD6Q cifar10_pytorch % pwd
/Users/rcorujo/IdeaProjects/FOUNDENG-527_wckey/determined-ee/examples/computer_vision/cifar10_pytorch
(base) rcorujo@C02FJ0T8MD6Q cifar10_pytorch % cat rig_distributed.yaml
#debug: true
name: cifar10_pytorch_distributed
hyperparameters:
learning_rate: 1.0e-4
learning_rate_decay: 1.0e-6
layer1_dropout: 0.25
layer2_dropout: 0.25
layer3_dropout: 0.5
global_batch_size: 512 # Per-GPU batch size of 32
resources:
slots_per_trial: 8
records_per_epoch: 50000
max_restarts: 0
searcher:
name: single
metric: validation_error
max_length:
epochs: 2
entrypoint: …
```

fix: Investigate "directory does not exist" tensorboard warning messages [DET-9166]

---

master/internal/rm/kubernetesrm/pods.go

@stoksc and I talked it through and decided that `summarize` itself was an expensive operation, and users wouldn't be bothered by it being only a few seconds out of date. Further, it could be a problem if some API operations were cached and not others, since that could lead to inconsistency. So we just cached the result of the `summarize` operation for now until we can come up with a longer-term fix for the k8s API rate limiting.
Tests like those described in [this Slack thread](https://determined-ai.slack.com/archives/C0147SMJQQY/p1682016860926639) should be faster.

fix: cache k8s summarize for performance

---

webui/react/src/components/Metadata/EditableMetadata.tsx
webui/react/src/components/Metadata/EditableRow.tsx
webui/react/src/services/types.ts
webui/react/src/types.ts

Models and ModelVersions have editable Metadata which can accept JSON values. This causes an error on the Model Details page.
This PR makes JSON metadata visible when viewing and editing.
JSON rows are disabled from editing, because saving in the text editor would convert the value to a string.
We don't have a design or component to create and edit indefinitely nested JSON so we can't as quickly fix creating and editing JSON metadata
Use `/det/models/397` with latest-master as an example model; otherwise to prepare a model in the database you can `SET metadata = '{ "sample": "data" }'::json WHERE id = ?`
On the model details page:
- JSON row appears string-ified
- During edit, form is disabled to protect JSON value, and is string-ified for display
- Editing another row's metadata, then …

fix: Metadata card can view and preserve JSON values [WEB-1183]

---

master/internal/api_trials_intg_test.go
master/internal/db/postgres_experiments.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/pods_test.go

The reason for separate `UPDATE` added in https://github.com/determined-ai/determined/pull/5294/files#r1036537936 got lost to the bun-ification.
Also there're formatting changes because someone did not run `make fmt`. Same as https://github.com/determined-ai/determined/pull/6650/files.

refactor: simplify config handling in `AddExperiment`.

---

e2e_tests/tests/experiment/test_core.py

Just a spot refactor of something I happened across.
Another version that would be closer to the original would be
```python
for hp in exp_hyperparameters:
assert any(c.column == "hp." + hp for c in columns.columns)
for mc in exp_metrics:
assert any(c.column == mc for c in columns.columns)
```
but I figured what I have in the PR is the clearest overall.

refactor: clean up a bit of logic in `test_core.py`

---

master/internal/trials/postgres_trials.go

On a decision tree demo, we have unusual metric names which are not handled well by our metrics API. Traced error to how these are queried from the JSONB column in the DB.  The new code will use `bun.Ident`
`cd examples/decision_trees`
`det e create gbt_titanic_estimator/const.yaml gbt_titanic_estimator`
When the experiment completes, look for a chart with a point from validation metrics

fix: metricName escaping using bun.Ident

---

harness/determined/cli/sso.py

SaaS has had a few users report issues with `det auth login` printing the wrong URL. I've validated that the URL that is printed is correct; I suspect the issue here is that users are killing the CLI process before visiting the link, which closes the `localhost` port and gives a connection refused error when visiting the printed link. I've added a print statement warning about this.
DET-9117

chore: add warning to det auth login flow

---

docs/Makefile

This is my bug, but non-docs-writers or docs-writers who use a persistent build directory likely didn't notice.

ci: fix bug in docs makefile

---

docs/release-notes/legacy-optimizers.rst

**Breaking Changes**
-  Experiment: Optimizer has to be an instance of tensorflow.keras.optimizers.legacy.Optimizer starting from Keras 2.11
-  Experiments now use images with TensorFlow 2.11 by default. TensorFlow users who are not
explicitly configuring their training image(s) will need to adapt their model code to
reflect these changes. Users will likely need to use Keras optimizers located in
``tensorflow.keras.optimizers.legacy``. Depending on the sophistication of users' model
code, there may be other breaking changes. Determined is not responsible for these
breakages. See the `TensorFlow release notes
<https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0>`_ for more details.
-  PyTorch users and users who specify custom images should not be affected.
This note is somewhat …

chore: release note on breaking TF changes to Keras optimizers

---

docs/index.rst

Help users find the experiment configuration reference by adding the link to the top level left side navigation

docs: Help users find exp conf ref

---

docs/release-notes/summary_metrics.rst

Document summary metrics migration.

docs: summary metric migration downtime

---

harness/determined/pytorch/_pytorch_trial.py

Dataloaders are created before state is loaded. The state variable at this moment is invalid, and `state.batches_trained` is not a proper value for the skip argument of `get_data_loader` . 
This should be changed to use the same value that the `training_enumerator` sees.
No Ticket

fix: dataloader skip on resume

---

master/internal/checkpoint_gc.go
master/pkg/tasks/task_gc.go

These code changes allow the "sbatch_args" and "pbsbatch_args" defined in the resource pool or partition overrides section of the "master.yaml" to be consumed and passed to the Workload Manager (i.e., "Slurm" or "PBS") for GC tasks.
See "Test Plan" for "determined-ee" in pull request https://github.com/determined-ai/determined-ee/pull/827

fix: GC jobs do not inherit sbatch_args from custom resource_pool [DET-9363]

---

master/internal/api_experiment.go
master/internal/api_project.go
master/internal/db/database.go
master/internal/db/postgres_experiments.go
master/internal/db/postgres_snapshots.go
master/internal/db/postgres_snapshots_test.go
master/internal/experiment.go
master/internal/mocks/db.go

The goal is to allow concurrent deletion of multiple experiments.
- divides experiments into groups of 10 (might be better to max this out at 10 rather than batching?)
- retrieving trials, tasks for the batch and deletions use a Bun transaction and can apply to multiple experiments
- `deleteExperiments` and snapshot code need context for Bun; use `context.Background()` since this runs async and the web ctx gets cancelled
- GetAgentUserGroup / GC of checkpoints remains in a loop; if this were made concurrent we might be able to send a map of AgentUserGroups and experiment IDs to make the right queries? 
Comes after #6568
Delete test experiments using the CLI; they go through the same process
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README …

fix: Delete multiple experiments with new call [WEB-1135]

---

webui/react/src/components/Markdown.tsx
webui/react/src/components/Navigation.module.scss
webui/react/src/components/kit/LogViewer/LogViewer.tsx
webui/react/src/components/kit/Pivot.module.scss
webui/react/src/pages/ExperimentDetails/CodeViewer/CodeViewer.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/exceptions.tsx

This PR duplicates the https://github.com/determined-ai/determined/pull/6699, which get merged then accidentally removed.  
-  New experiment list page should have only 1 scroll bar.
- Trials page should have only 1 scroll bar.
Navigate to `/det/projects/{pro_id}/experiments?f_explist_v2=on`
Verify that there is only one scroll bar vertically 
Before:
After:
Navigate to `/det/experiments/{exp_id}/trials`
Verify that there is only one scroll bar vertically 
Before:
After:
Since this PR changes UI kit style of Pivot, verify that any related pages look reasonable.
When we zoom in a lot to like 175%, there won't be multiple scroll bar, but the navigation sidebar may not be as functional.
Before:
After:
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-note …

fix: Remove redundant scroll bar for new experiment list

---

e2e_tests/tests/experiment/__init__.py
e2e_tests/tests/experiment/test_custom_searcher.py

Failing tests should always be debuggable from the failed test logs, but that doesn't work if the failed test logs don't contain what happened inside training.
[example of unhelpful failure](https://app.circleci.com/pipelines/github/determined-ai/determined/38009/workflows/ec106894-d444-4c64-8bea-90fdde83ab90/jobs/1390142)

ci: make custom searcher dump failed trial logs

---

webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx
webui/react/src/pages/Clusters/ClustersQueuedChart.tsx

Fixes an issue where the cluster stats 7 day chart was not appearing for a single point. Displays chart with one point and x-axis range of Jan 1 - Dec 31 of same year (I can modify this to be +/- 30 days)
Note: the previous code intentionally avoided making a chart in this case, so confirm if we do want this chart
On Cluster, select a resource pool card, then the Stats tab

fix: Cluster stats chart displays with single day result [WEB-1206]

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/core_experiment.go
master/internal/core_experiment_intg_test.go
master/internal/experiment/authz_basic_impl.go
master/internal/experiment/authz_iface.go
master/internal/mocks/authz_experiment_iface.go

This is a longer-term fix for the EE update begun in https://github.com/determined-ai/determined-ee/pull/832
We will determine `canCreateExperiment` permission from the context project, not the experiment (the experiment might not be created, or might be moving into a new project and workspace).  The experiment parameter is no longer needed.
There should be no effect in OSS
- Create an experiment from the CLI
- Move an experiment between projects from the CLI or WebUI
I looked into an unrelated WebUI issue where the current project is an option in MoveExperimentModal. This modal can sometimes be used with multiple experiments. Even when a single experiment / `sourceProjectId` is provided, it's the default value of the destination project dropdown.  So filtering out this project only …

fix: Remove canCreateExperiment experiment param [WEB-1205]

---

e2e_tests/tests/cluster/test_rbac.py

In https://github.com/determined-ai/determined-ee/pull/809 we fixed RBAC logic to make sure users inherit permissions from their groups
This adds an RBAC-only e2e_test where user doesn't have access to a workspace until added to a group
The project / list-experiments code is based on another PR fix
Needs to be tested in EE.
If you're using devcluster, enable RBAC
In e2e_tests, run `pytest tests/cluster/test_rbac.py::test_group_access`

chore: test RBAC transfers permission from group to users [WEB-1172]

---

.circleci/config.yml
.pre-commit-config.yaml
webui/react/.gitignore
webui/react/Makefile
webui/react/package-lock.json
webui/react/package.json
webui/react/scripts/designkit-screenshot.mjs
webui/react/scripts/make-github-comment.mjs
webui/react/scripts/make-screenshot-diff.mjs

This adds a visual diff test to designkit. We generate screenshots of each section of the designkit on the branch in question using playwright and then again on the main branch. We then use playwright's built in image comparison facilities to generate a diff between the screenshots. If differences are found, both screenshots and the diff are output to a flat html file that displays the results and CI will report in github.
CI Only -- no testing required
we're using `undici` for our node fetch needs because it's the source of the [experimental fetch library that landed in node 18](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental), so when we upgrade, we should be able to just remove the import and library and everything will be the same.
See [Release …

test: Add visual diff test to designkit

---

webui/react/src/pages/TrialDetails/TrialChart.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

Metrics which were precisely 0 were being treated like other falsey values, not being shown on the chart
These changes affect the current trial metrics chart, and the future one
Ilia shared a python file where one metric (x2) alternates between 0 and 1, and the other (x3) logs 0.01 and 1.01
For testing I ran the experiment here: http://latest-main.determined.ai:8080/det/experiments/2747/overview
We should see a zig-zag line alternating between 0 and 1 for the metrics: x2 and x3
This should fix the current trial metric chart and the next-gen chart enabled with `f_chart=on`

fix: allow 0 metrics on old and new charts [WEB-1216]

---

webui/react/src/components/TrialLogPreview.module.scss

When the Ant Tabs component height + overflow behavior changed (which removes an extra scrollbar), it affected the TrialLogPreview (the ticker at the bottom of the TrialDetails page which shows the latest logs)
To fix without a regression, this uses `position: fixed` and sets width to the original containing element. This is calculated as 100% - Sidebar width, -32px for Page element padding, -32px for the gap between Sidebar and Page. This needs +1px to cover the border
Other `position: sticky` elements are at the top of the pages and work OK.
Original behavior
- Fork a recent experiment and note logs appearing at the bottom of the page / viewport
- Wait for the metric chart to appear
- Scroll up and down the page to confirm that the TrialLogPreview stays at the bottom of the browser …

fix: Use position: fixed to replace sticky TrialLogPreview

---

.circleci/config.yml
harness/MANIFEST.in
harness/Makefile
harness/setup.py
model_hub/MANIFEST.in
model_hub/Makefile
model_hub/setup.py
requirements.txt

First, use find_namespace_packages instead of find_packages because it
includes directories containing only data files (non-python files) as
"packages".  We were seeing deprecation warnings during `make build`
with recent versions of setuptools for not doing that.  Although it
seems odd, that is what setuptools maintainers recommend [1].
Second, use an `include` pattern to find packages, rather than `exclude`
patterns.  The exclude pattern list was needlessly long and we only ship
one package so include makes more sense.
Third, include `py.typed` in MANIFEST.in.  MANIFEST.in is what controls
what goes into source distributions, and there's no reason py.typed
shouldn't be included.
Fourth, eliminate the package_data from our setup() call.  Having
include_package_data=True is sufficient to …

chore: cleanup our setup.py

---

master/internal/api_experiment.go

Related comment: 
Currently, the resulting query from the expertiment filter in some cases is joined with other queries using an `OR` operator, which causes incorrect queries. The update here ensures that the resulting experiment filter query is always joined with the rest of the query with an `AND` operator i.e 
```
(project_id = 3) AND // non-filter sql
(((((SELECT COUNT(*) FROM trials t WHERE e.id = t.experiment_id) = 0))) OR ((true)) AND (e.archived = false)) // filter sql
```
1. Using the `search-experiments` API supply a `project id` argument and `filter` argument that contains `OR` conjunctions between the  `condition groups`, choose filter options that will always return true. An example from the UI: 
Resulting filter expression:
``` …
```

fix: add correct experiment filter grouping

---

master/internal/api_notebook.go
master/internal/api_tasks.go

Cherrypicking some changes back into OSS from EE https://github.com/determined-ai/determined-ee/pull/836.
Make sure CircleCI tests pass, but also manually verify endpoints `POST /api/v1/NSCs` (through `CanCreateNSC()`, launching notebooks/shells/commands/tensorboards) and `GET /api/v1/experiments/:exp_id, GET /tasks, GET /api/v1/NSCs/:nsc_id`.
- [ X] Changes have been manually QA'd
- [ X] User-facing API changes need the "User-facing API Change" label.
- [ X] Release notes should be added as a separate file under `docs/release-notes/`.
- [X ] Licenses should be included for new code which was copied and/or modified from any external code.
DET-9468

chore: porting EE PermissionDenied changes back to OSS [DET-9468]

---

examples/deepspeed/deepspeed_autotuning/hf_trainer_api/language_modeling/run_clm.py

An old `import` was still in one script.

fix: single hf examples again

---

.circleci/config.yml

* Renames `scrape-docs` to `upload-docs-search-index`. The former name obscures the stage's purpose. The latter name describes its effect.
* Moves the tagged execution to the release workflow. The old execution (both branch and tag) was at the end of `test-e2e`. This worked fine for the branch filter, but didn't ever execute on the tag filter because it had a dependency that wasn't also tag filtered. This change keeps official release activity in the release workflow while still maintaining the indexing/uploading to Algolia of the `determined-dev` index.
Check that `upload-docs-search-index` has run in CircleCI and that a corresponding index has been uploaded to Algolia after a release has been cut. https://hpe-aiatscale.atlassian.net/wiki/spaces/DOC/pages/1328414765/Algolia+search has …

ci: Schedule search indexing with release workflow

---

harness/determined/cli/sso.py

feat: Turn off echo'ing of the localhost URL as it contains a secure token.
fix: there was a printf bug.
1. `det auth login`, fudge the localhost URL, and make sure the error message correctly shows the example URL.
2. `det auth login` -> make sure that you can login.

feat: mask token det auth login [MLG-540]

---

examples/tutorials/core_api_pytorch_mnist/model_def_distributed.py
harness/determined/core/_checkpoint.py

fix: Core api pytorch mnist update2
added filelock in model_def_distributed.py to avoid downloading files from multiple ranks to fix corrupted file error which occurs on some machines

fix: Core api pytorch mnist update2

---

.circleci/config.yml

CI run: https://app.circleci.com/pipelines/github/determined-ai/determined/38681/workflows/3b7e2c2a-2285-4d44-ae8a-ff0126c876cb.

ci: bump GKE Kubernetes version

---

master/internal/api_trials_intg_test.go
master/internal/trials/postgres_trials.go

Previously these endpoints would error with a non numeric metric reported. Now these will return the values without error.
Integration test.
There is a webui aspect to this that will need to be done to update the ui to handle cases of these previously always numeric values that may now be non numeric. 
Release note I think is okay to add on the web aspect? 

chore: support non numeric metrics in CompareTrials, SummarizeTrials, and TrialsSample [DET-9384]

---

docs/release-notes/fix-det-e-list-cli.rst
harness/determined/cli/experiment.py

'det e list -a' was showing only non-archived experiments and 'det e list' was showing both archived and non-archived experiments Fixed it by changing the 'archived' argument of the API call under the GetExperiments CLI function

fix: 'det e list' and 'det e list -a' behavior was switched DET-9480

---

webui/react/src/pages/Dashboard.tsx

As requested in ticket, instead of "/" the Dashboard page should show a link with workspace name for a recent task
Frontend uses store for workspace names because these are not included in the task info. If workspace names haven't loaded yet, you would momentarily see the workspace ID instead of the name
On `/det/dashboard` these recent rows should appear with a link.  If you use the latest-main db then it will have the tasks as recent examples

fix: Dashboard shows workspace name and link for tasks [WEB-1136]

---

master/internal/api_trials_intg_test.go

Merged two PRs that conflicted with this test. The earlier PR merged made reporting "epoch" and error so the test errored earlier than expected. This is the correct behavior we want.
Integration tests pass

test: fix TestNonNumericEpochMetric test

---

.circleci/config.yml

In #6602, `build` was added as a dependency and set to install in some other places, but not for the publishing jobs.
Hope for the best, merge this, and push a tag.

ci: install `build` when publishing Python packages

---

docs/setup-cluster/deploy-cluster/index.rst
docs/setup-cluster/deploy-cluster/on-prem/overview.rst
docs/setup-cluster/deploy-cluster/on-prem/wsl.rst

This PR add documentation for installing and running Determined AI on WSL using both the deb/rpm packages and Docker containers.
Sections of the deb/rpm and Docker install pages were adapted with WSL-specifics learned when drafting both [this blog post](https://boxofcables.dev/running-determined-ai-on-wsl-2/) and [this project](https://github.com/sirredbeard/determined-wsl).
The test plan for these changes include:
Configuring a new Windows VM with WSL2 and following the steps for both procedures to verify they work as stated.
- [NA] User-facing API changes need the "User-facing API Change" label.
- [NA] Release notes should be added as a separate file under `docs/release-notes/`. …

docs: Add documentation for installing and running Determined AI on WSL

---

master/pkg/syncx/orderedmapx/orderedmapx.go
master/pkg/syncx/orderedmapx/orderedmapx_test.go

Add a thread safe ordered map, in which the elements can be retrieved in the order in which they were added, to implement the queuing functionality needed for pull request https://github.com/determined-ai/determined-ee/pull/849
See testing section for pull request https://github.com/determined-ai/determined-ee/pull/849

chore: Add ordered map (orderedmapx) to allow for queuing of job cancelations [DET-9465]

---

master/internal/trial.go
master/pkg/model/experiment.go

NewTrial was hardcoded to state:ActiveState even if the trial.state
was PAUSED, so depending upon timing new trials may show as Active/Queued
when the experiment is actually paused.  Pass the initial state to
NewTrial such that it can be persisted in the DB matching the actual
state in memory.
Verified manually by pausing/resuming no_op adaptive.   No longer able to see newly created trials queued after pause.

fix: trials created by paused experiments should be paused [DET-9493]

---

docs/reference/deploy/config/master-config-reference.rst

Master configuration reference: indent content under 4th level headings making it easier for a reader to distinguish between 3rd and 4th level content.

docs: Indent content under 4th level headings

---

.github/workflows/track-prs-for-release.yml
tools/scripts/add-pr-to-release-project.sh

As a first step toward exploring a new release process, this creates a GitHub action that adds each merged fix/feat PR to an organization-level GitHub project for tracking during the release party.
The PRs are not added directly to the project; instead, new issues linking to them are created in a separate repo. It would be possible and a bit simpler to add them directly, but I felt that it was preferable to have a separate place specifically for release-related discussion that was not appending onto the already closed PRs.
Did a bunch of iteration on a private test repo. There's some chance that something will go wrong on the transfer to this one, but I think I've done the best I can do. And it's not like anything terrible will happen if something is off.

ci: track merged PRs in a GitHub project

---

webui/react/src/components/kit/CodeEditor/CodeEditor.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentCodeViewer.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentCodeViewer.tsx

Two fixes for code editor release:
- Make the container around the experiment code viewer fit the window height
- Removed `white-space: nowrap` CSS rule so file names wrap, instead of overlapping code editor
Checkpoint file names with latest-main data, `/det/experiments/2744/code`

fix: Full height on code editor [WEB-1258]

---

webui/react/src/pages/WorkspaceList.tsx

Fix an issue on WorkspaceList table view, where a full-width context menu appeared on left-click.
When I tried to open WorkspaceActionDropdown menu from the three-dots menu, it opened up a full-width context menu which covers up the dropdown.  In the screenshot you can see one menu covers up the other
On `/det/workspaces`, switch to Table view.
- Right-click on blank/inactive spaces of row opens context menu --- this menu is correct width
- Left-click on blank spaces of row **does not** open context menu
- Left-click on three dots menu opens one correct-width dropdown

fix: patch WorkspaceList full-width context menu [WEB-1275]

---

harness/determined/deploy/aws/templates/simple.yaml

Per AWS support:
>Both of the DB Clusters are pausing due to Auto pause being enabled. [1] The Cluster will be resumed if there are any new connections made to the database. 
>Due to this pause the resource is not entering CREATE_COMPLETE status in CFN. The internal team has suggested to not enable Auto pause when creating through CFN, or to increase the autopause idle time to a sufficiently large value (max is 24 hours) or make some connections to the cluster as soon as the DB cluster is created, in order to allow the resource to enter CREATE_COMPLETE properly.
Let's try increasing the AutoPause time.

fix: bump AWS CFN `SecondsUntilAutoPause` to see if it helps with timeouts.

---

harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml

Amazon has silently upgraded all of our clusters from 10 to 11 because Aurora PostgreSQL 10 is EOL: https://aws.amazon.com/blogs/database/upgrade-amazon-aurora-postgresql-and-amazon-rds-for-postgresql-version-10/
We don't have to specify `DBClusterParameterGroupName` parameter which nails us down to postgresql 10. Let amazon do its defaults.

fix: make AWS CF template postgres version-agnostic.

---

harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple.yaml

Bumping up the timeout in #6921 did not work. Let's turn off autopause completely. Also standardize the scaling configuration between the various templates.

fix: turn off AutoPause for AWS RDS Aurora.

---

.circleci/config.yml

Some of these have been killed while running lately, which generally means it's time to bump the resource class.

ci: increase resource classes for some tests

---

docs/release-notes/feat-GetExperiments.rst
e2e_tests/tests/experiment/test_api.py
e2e_tests/tests/experiment/test_custom_searcher.py
master/internal/api_experiment.go

Added a condition that filters sql results when parent workspace or project is archived and wrote a test to verify

feat: Hide experiments from archived projects in `GetExperiments` DET-9381

---

webui/react/src/components/JupyterLabModal.tsx

JupyterLab modal will keep workspace selection when switching between simple-form and full-config modes
Flexible workspace form and validation
- On `/det/dashboard`, in the top right, click the 'Launch JupyterLab' button
- The "Launch" button in the bottom right of the form is greyed out. Hovering has tooltip "Address validation errors..."
- A dropdown allows you to select a workspace on this form. The form's "Launch" button now turns blue
- Hover over the workspace input and click the small x to clear. The "Launch" button is greyed out again
Retaining workspace between modes
- Select a workspace again
- Click "Show Full Config"
- The same workspace is selected above the config text input. The "Launch" button in the bottom right is blue / enabled
- Clear the workspace. The "Launch" button …

fix: Workspace selection on JupyterLab modal [DET-9503]

---

docs/setup-cluster/deploy-cluster/aws/install-on-aws.rst
docs/setup-cluster/deploy-cluster/gcp/install-gcp.rst
docs/setup-cluster/deploy-cluster/k8s/install-on-kubernetes.rst
docs/setup-cluster/deploy-cluster/on-prem/docker.rst
docs/setup-cluster/deploy-cluster/on-prem/homebrew.rst
docs/setup-cluster/deploy-cluster/on-prem/linux-packages.rst
docs/setup-cluster/deploy-cluster/on-prem/wsl.rst

The on-prem set-up guides are not consistent with the new WSL set-up guide. The on-prem set-up guides do not clearly describe their purpose. Some of the instructions are unclear, wordy, full of jargon, and difficult to read.
The solution is to edit the on-prem set-up guides to make them more consistent, by reusing the same language and content where possible, and applying consistent formatting and headings where feasible.

docs: Apply consistency to setup guides

---

master/internal/task/allocation.go

Check `a.restored` status and print different task logs accordingly -- this is a cosmetic fix on top of https://github.com/determined-ai/determined/pull/6771
Attempt restoring an experiment & checking that the error message matches.
DET-9515

chore: check if a.restored to send task log [DET-9515]

---

harness/tests/experiment/integrations/test_pytorch_lightning.py
harness/tests/experiment/pytorch/test_pytorch_trial.py
harness/tests/experiment/test_local.py

The default directory for saving tensorboard files is the current user directory. Due to this, tests leave tensorboard artifacts after being run.
This PR passes a tensorboard directory to the PyTorchTrial unit tests so that tensorboard files are created in the pytest temp directory, which is cleaned up after tests are run.
Run unit tests in `harness/tests/experiment` and confirm that `runs` directory is NOT created.
MLG-507

fix: Test runs dirs

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

Fixes bug with scrolling to new pages in the Glide table component. We discussed the issue and selection comes from this code which was intended for `selectAll` mode
Visit `/det/projects/1/experiments?f_explist_v2=on&page=1` and scroll up and down the table to trigger loading rows for the infinite scroll. The checkbox header should not indicate anything was auto-selected

fix: only select new pages during selectAll mode [WEB-1283]

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/contextMenu.tsx

Improve the table experiment loading experience. Currently the new experiment list will render up to the data it has instead of the full total. For example, if the user loads page 3 upfront and each page is roughly 50 entries, then the API will return entries 100 ~ 150. And assuming there are a total of 500 entries, the UI will pad the rows so there are 150 entries and render the data for entries 100 ~ 150 since they are loaded. However for new rows that span beyond 150 ~ 500, it will hit a "wall" on the scroll and wait for new API fetches to occur before the newer entries are returned followed by rendering the next set of entries (150 ~ 200).
Instead, change it so upon knowing that there are 500 entries, create all 500 rows of data and fill in the rows with actual data when they are …

perf: render full experiment list [WEB-1234]

---

harness/determined/pytorch/dsat/_utils.py
harness/tests/experiment/pytorch/test_deepspeed_autotuning.py

Protects against errors in the case where the user wants to include an `overwrite_deepspeed_args` field in their `hyperparameter` dictionary for a HF integration trial while simultaneously keeping batch-size values in the DS json config as `"auto"` and configuring the batch size through HF CLI args instead.
Without this fix, our `get_hf_args_with_overwrites` function was propagating `"auto"` to the CLI entrypoint and creating flags like `--per_device_train_batch_size "auto"` which is illegal in HF.

fix: no auto in hf cli

---

agent/internal/agent.go
agent/pkg/cruntimes/crutils.go
agent/pkg/podman/podman.go
agent/pkg/singularity/singularity.go

Use a per-user + per agentID /tmp folder to enable multiple users of determined-agent on HPC systems without conflicts.
Drop the pull on singularity since the command is intended to output a file (and it was broken for running local images).
```
% tools/slurmcluster.sh -A casablanca
%det cmd run --config environment.image=/mnt/lustre/foundation_engineering/images2/determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.11-gpu-6eceaca  hostname
...
[2023-05-25T15:54:52.992647Z] e7b9f31b || casablanca-login
[2023-05-25T15:54:53.791233Z] e7b9f31b || INFO: resources exited successfully with a zero exit code
[2023-05-25T15:54:53.854017Z]          || INFO: Command (terminally-premium-cockatoo) was terminated: allocation stopped early after resources exited successfully with a zero exit code
``` …

fix: parameterize agent tmp by agent id [DET-9111]

---

master/internal/rm/agentrm/resource_pool.go
master/internal/rm/kubernetesrm/resource_pool.go

The kubernetes `/api/v1/resource-pools` endpoint showed that the `slotsUsed` value would monotonically increase, thus showing the number of slots used since the beginning of master start as opposed to the number of slots currently used. This is because on task termination, the handler does not get passed as part of the message, leading to nothing being deleted from the RP tasklist. This field is also missing from the agent resource pool message.

fix: k8s tasklist forever growing

---

master/internal/db/postgres_trial.go
master/internal/db/postgres_trial_intg_test.go

Makes summary metrics full recompute take the table as a parameter for help with generic metrics.
Existing integration tests.

refactor: full trial summary metrics recompute take metric type as param

---

master/internal/api_checkpoint.go
master/internal/api_checkpoint_intg_test.go
master/internal/api_experiment_intg_test.go
master/internal/core_checkpoint.go
master/internal/core_checkpoint_intg_test.go
master/internal/db/postgres_test_utils.go

fix: add canDoActionOnCheckpointThroughModel to core_checkpoint 
Do the following with EE version

fix: add canDoActionOnCheckpointThroughModel to core_checkpoint 

---

webui/react/src/components/ModelMoveModal.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetails.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelVersionDetails.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/TaskLogs.tsx
webui/react/src/pages/TrialDetails.tsx

The new standardized breadcrumbs in PageHeader are helpful, but are inconsistent in preventing users from reaching `/det/workspaces/1` (the workspace details page for Uncategorized/Uncategorized)
This updates instances of `paths.workspaceDetails(w.id)` for the Uncategorized workspace to instead go to `paths.projectDetails(1)`
Check breadcrumbs in Uncategorized workspace
- Experiment details page has "Uncategorized Experiments / ExperimentName" linking to `/det/projects/1/experiments`
- In a multi-trial experiment, the trial page (accessible from Trials tab) has "Uncategorized Experiments / ExperimentName / Trial ID" linking to /det/projects/1/experiments`, /det/experiments/ID`, and `/det/trials/trialID`
Find a model in `/det/models` which belongs to the Uncategorized workspace and has 1+ …

fix: In new breadcrumbs, uncategorized links to /projects/1 [WEB-1319]

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/exceptions.tsx

When changing filters, we show a Loading component in place of the GlideTable. Currently this replaces all table headers and rows with grey bars.
OLD VERSION
This PR removes the Loading component, and makes use of the GlideTable's loading-cell for NotLoaded content.
NEW VERSION
UI test
- go to the Uncategorized project and add `?f_explist_v2=on`
- apply a filter to the table (for example Name Contains ex). the animation quickly appears and goes away, but should keep column headers / names visible
- remove the filter. During animation, headers / column names remain visible
- Add a filter with no results (for example Name Contains rrrrrrrrrr). You see a no results page
If you want to see the loading state for longer time, in `pages/F_ExpList/F_ExperimentList`, comment out …

feat: When modifying glide table filters, keep columns visible [WEB-1232]

---

master/internal/sproto/task.go
master/internal/task/allocation.go

DET-9466 - https://hpe-aiatscale.atlassian.net/browse/DET-9466
In https://github.com/determined-ai/determined-ee/pull/822  Bradley requested that we pass in the allocationID to the “releasedResources()” function in “dispatcher_resource_manager.go”, rather than get it inside the function from “m.reqList.Allocation()”.

chore: Pass in the allocation ID to releasedResources()

---

master/internal/rm/kubernetesrm/resource_pool.go

This was previously fixed for experiments, but tasks followed a different path when releasing slots. This covers the other case.
Run a GKE or local kubernetes cluster and submit a short sleep command. Go to `<cluster address>/api/v1/resource-pools` and look at the `slots available` field. Make sure it increments when the job is submitted and decrements when the job completes.
Also try terminating the command early, making sure the count decrements too.

fix: k8s slots count growing for commands [DET-9550]

---

docs/release-notes/rbac-not-found-errs.rst

Release note for https://github.com/determined-ai/determined/pull/6937
DET-9035

chore: added release note for DET-9035

---

agent/pkg/singularity/singularity.go

Cater for read-only bind mounts.
To the experiment definition add:
```
bind_mounts:
- host_path: /home/users/gaisford/determined-agent_0.22.1-dev0_linux_amd64
container_path: /whatever
- host_path: /home/users/gaisford/determined-agent_0.21.3-dev0_linux_amd64
container_path: /whatever2
read_only: true
```
In the experiment log, observe the following:
```
[2023-06-05 18:15:50]
[13ac25ed] singularity run \ 	--writable-tmpfs \
--pwd /run/determined/workdir \ 	--env-file /tmp/determined-gaisford-node002/1151093388-13ac25ed-52a6-4a57-ac91-809a1ddbe18a/envfile \
--bind /tmp/determined-gaisford-node002/1151093388-13ac25ed-52a6-4a57-ac91-809a1ddbe18a/archives/etc/ssh/ssh_config:/etc/ssh/ssh_config \
--bind /tmp/determined-gaisford-node002/1151093388-13ac25ed-52a6-4a57-ac91-809a1ddbe18a/archives/op …
```

chore: bind mount options for singularity

---

webui/react/src/components/kit/Button.module.scss
webui/react/src/components/kit/Button.tsx
webui/react/src/components/kit/Dropdown.tsx
webui/react/src/pages/DesignKit.tsx

Styling for buttons was dependent on usage of Antd icons. Adding classes to support using both Antd icons and our `Icon` component in the `Button`'s `icon` prop.
No release testing required. Regression testing on Buttons. Design Kit page should show examples with Antd icons and font icons
WEB-1226

fix: Button with icon styling

---

webui/react/src/pages/ExperimentDetails/ExperimentCodeViewer.module.scss

On the experiment code view, needed to shorten the code editor component by a few pixels for:
- bottom of code editor to be above last log banner
- find tool (Ctrl F) visible above last log banner
On an experiment, where the last log banner is visible on the bottom of the page, click the Code tab.
Select a code file (most Python files) longer than the window can fit
Confirm the bottom of the code window is just above the last log banner
Select the code editor and type: Ctrl F. The find appears inside the code editor component

fix: Bottom of code editor, find tool both visible [WEB-1318]

---

webui/react/src/components/kit/Breadcrumb.tsx

This PR removes an extra margin on the page breadcrumb. The page header already has padding applied so this margin is unnecessary. The `page` argument for `Columns` is intended for when Columns is being used as page layout.
N/A
No ticket

fix: Breadcrumb should not have extra margin

---

agent/pkg/singularity/singularity.go

Forward any capabilities configuration from the experiment to the singularity command line.
To the experiment configuration, add this:
```
environment:
add_capabilities:
- add_one
- add_two
drop_capabilities:
- drop_one
- drop_two
```
In the experiment log, observe:
```
2023-06-06 17:22:11]
[659bd6a1] singularity run \ 	--writable-tmpfs \
--pwd /run/determined/workdir \
--env-file /tmp/determined-gaisford-node002/1346786491-659bd6a1-2232-4568-809c-d545ffe26372/envfile \
--bind /tmp/determined-gaisford-node002/1346786491-659bd6a1-2232-4568-809c-d545ffe26372/archives/etc/ssh/ssh_config:/etc/ssh/ssh_config \
--bind /tmp/determined-gaisford-node002/1346786491-659bd6a1-2232-4568-809c-d545ffe26372/archives/opt/determined:/opt/determined \
--bind …
```

chore: capabilities options for singularity

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

Memo-ize loading state introduced in #7010 and with new behavior in #7026 
Prevents multiple re-renders by creating `[]` or `[NotLoaded]` only once
Comment: we typically use a name like `loadableExperiments` to represent `Loadable<Experiment[]>` type, with `Loadable` as the outer wrapper, so it would not fit a `Loadable<Experiment>[]` type.  I went with `experimentsIfLoaded` for the name of memo-ized variable.
Visit `/projects/107/experiments?f_explist_v2=on` or similar glide table page to see rows and column names load successfully.
Use console.log or React DevTools - Profiler to check for excessive re-renders

fix: Prevent re-renders on glide table

---

harness/determined/cli/proxy.py

The Grenoble cluster ("o184i054.gre.smktg.hpecorp.net") is configured to use a proxy server.
```
corujor@o184i054:/cstor/corujor/determined-ee$ env | grep -i proxy
no_proxy=localhost,127.0.0.1,16.16.184.54,172.23.184.54,172.22.184.54,.hpecorp.net
ftp_proxy=http://web-proxy.bbn.hpecorp.net:8088
https_proxy=http://web-proxy.bbn.hpecorp.net:8088
NO_PROXY=localhost,127.0.0.1,16.16.184.54,172.23.184.54,172.22.184.54,.hpecorp.net
FTP_PROXY=http://web-proxy.bbn.hpecorp.net:8088
HTTPS_PROXY=http://web-proxy.bbn.hpecorp.net:8088
HTTP_PROXY=http://web-proxy.bbn.hpecorp.net:8088
http_proxy=http://web-proxy.bbn.hpecorp.net:8088
```
When we run the "det shell start" command on the Grenoble cluster, we get the following error:
```
corujor@o184i054:/cstor/corujor/determined-ee$ det shell start
error …
```

fix: det shell start fails on grenoble with 0.21.2 (reading HTTP_PROXY, but ignoring NO_PROXY) [DET-9364]

---

webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx

Fixes an issue introduced in #6737 which was displaying the historical usage compute chart in single-point form (x axis forming calendar year)
New version accurately displays single and multi-day on this chart
- View `/det/clusters/historical-usage`; chart x-axis should match a few days of data
- Single-point mode selected when there is only one point in total. To demo this, I replaced the section in `src/pages/Cluster/ClusterHistoricalUsage` with
```
<Section bodyBorder loading={!chartSeries} title="Compute Hours Allocated">
{chartSeries && (
<ClusterHistoricalUsageChart
groupBy={chartSeries.groupedBy}
hoursByLabel={{total: [chartSeries.hoursTotal.total[0]] }}
time={[chartSeries.time[0]]}
/>
)}
</Section>
``` 
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs …

fix: Chart regression in detecting single point cluster chart

---

master/internal/api_project.go
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/MultiSortMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/columns.ts

Changes the default columns on the new experiment table
Includes a server-side change to add searcherMetric and searcherMetricValue to possible columns.
Visit `/det/projects/1/experiments?f_explist_v2=on` or another project with Glide Table visible.
Click the Columns button, and on the bottom right of the menu click "Reset" to see the new default settings.
- active columns should be: name, start time, user, description, tags, state, duration, searcher type
- click the header for Tags. There is a "Filter by this column" menu option, but no "Sort" option
Open the columns menu again
- Columns menu has **searcher metric and searcher metric value at the end**
- Column order in the menu is id, forked, start time, user, description, tags, state, duration, resource pool, searcher type, progress, …

feat: New default glide table columns [WEB-1197]

---

e2e_tests/tests/cluster/test_workspace_org.py
master/internal/api_experiment.go

we need to kill active experiments before deleting the workspace as currently that behavior is undefined.
(cherry picked from commit 8089a553c9c0abd5571543c831b956bef0a8781e)
tested in ee https://github.com/determined-ai/determined-ee/pull/880

tests: kill exps before workspace deletion

---

docs/setup-cluster/deploy-cluster/slurm/singularity.rst
docs/setup-cluster/deploy-cluster/slurm/slurm-requirements.rst

Add user docs for manage-enroot-cache

docs: Provide user docs for manage-enroot-cache

---

docs/release-notes/rbac-not-found-errs.rst

Rewriting the release note and fixing a spelling error.

docs: Fix a typo in a release note

---

master/internal/config/provconfig/gcp_config.go

[MLG-425]
`pd-standard` on it's own isn't a valid default for gcp disks. Make sure it is the full string.
Should not  need testing for release party. This default can only be used if you remove the disk specification in the terraform `metadata_startup_script`, which isn't a valid use case. But this is nice to have.
[MLG-425]: https://hpe-aiatscale.atlassian.net/browse/MLG-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: ensure golang gcp defaults for disk are valid [MLG-425]

---

bindings/generate_bindings_py.py
harness/determined/cli/experiment.py
harness/determined/common/api/bindings.py

these are used in tests and logs and are more helpful if they're a bit more verbose.
I added some custom logic to skip longers pieces of text that probably contribute less to this goal
```
v1GetExperimentsResponse(experiments=[..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., …
```

chore: make printed bindings more readable

---

webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

Add `sorts` to user settings, to save sorts on new Experiment List.
On new experiment list (`f_explist_v2=on`)

fix: persist Experiment List sorts

---

docs/release-notes/username-cant-make-same-user.rst
master/internal/api_user_intg_test.go
master/internal/db/postgres_users.go
master/internal/user/postgres_users.go
master/internal/user/service_intg_test.go
master/static/migrations/20230612120719_rename-new-username-fix.tx.down.sql
master/static/migrations/20230612120719_rename-new-username-fix.tx.up.sql

Bug where we couldn't create a user with the same name as a previously renamed user.
```
det -u admin user create testoriginal
det -u admin user rename testoriginal testnew
det -u admin user create testoriginal # should not fail
```

fix: allow creating a user with original username of a renamed user

---

webui/react/src/components/FilterForm/components/FilterForm.tsx
webui/react/src/components/FilterForm/components/FilterFormStore.test.ts
webui/react/src/components/FilterForm/components/FilterFormStore.ts
webui/react/src/components/kit/LineChart.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

When loading an experiment which ended or errored early (`dataPoints` is undefined), the LineChart xAxis code should work around it
When we load a filter from settings, the page fires `fetchExperiments` when `isLoadingSettings` changes, and shortly after for `filtersString` change. The unfiltered request can take longer and overwrite the filtered request.
We want to wait for `formStore.init()` so we can access the `filtersString` observable. I'm proposing to fix this with an `isLoaded` observable inside `formStore`.
Doing `make live` for latest-main experiments to replicate locally
**Bug 1**
- On `/det/projects/1/experiments?f_explist_v2=on`, filter experiment name contains "lightning".  You should see 7 experiments, some are complete and some are errored.
- Open the Compare view
- Slowly …

fix: Glide Table comparison view no data error; loading saved filters issue

---

tools/scripts/track-pr

When a PR with the appropriate label is merged during a release (or a previously merged PR has the label added), the release branch should now automatically be updated with the cherry-picked version if possible. If there is a conflict, the PR will be added to the conflict column in the current release project for manual handling.

ci: handle cherry-picking PRs for release

---

docs/setup-cluster/security/tls.rst

Adding a new TLS certificate setup guide based on the sharepoint document MLDE Let's Encrypt Certs Setup Guide
jira: DOCSTW-206
note: the publishing script replaces "Determined" with the appropriate MLDE phrase
e.g., it uses (r"Determined", c) to match the word "Determined" and replaces it with the value of c ("HPE Machine Learning Development Environment").

docs: Add TLS Certs Setup Guide

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx

We discussed an issue where http://latest-main.determined.ai:8080/det/experiments/2072/visualization/learning-curve is not displaying a LearningCurve chart.
Though we believed this was related to no validation metrics, the fix is related to displaying multi-trial tabs when `filters.batch === 0` - the original statement is intended to delay rendering while `filters.batch === undefined` , but was triggering on any false-y values.
While connected to the latest-main DB, test experiment 2072.  Or use another experiment with no validation metrics.
Training loss should appear on a LearningCurve chart.

fix: Display chart if filters.batch is a number

---

tools/scripts/track-pr

Previously, checking for fix/feat PRs happened before the label check, which is not what we want -- specifically labeled PRs of any type should be handled on merge.

ci: cherry-pick all appropriately labeled PRs, regardless of type

---

webui/react/src/services/apiConfig.ts

Due to incorrect argument positioning in the call to `compareTrials` we are currently sending a `customType` argument as `SCALE_LINEAR` this bug causes the backend to not return any metrics since the customType is bogus.
This PR fixed the positional arguments. 
Current Behavior:
**Trial Overview**
**Compare Metrics tab**
Fixed Behavior:
**Trial Overview**
**Compare Metrics tab**
1. In the new experiment list `compare` view `metric` tab ensure that any experiment that has metrics has viewable chart data. At least a single chart should not show "No data to plot."
2. Ensure that the `Trial Overview` chart for trials that have metrics, show the metric values and not just "No Data to plot." …

fix: correct scale positional argument in compareTrials API call [WEB-1386]

---

docs/reference/deploy/config/master-config-reference.rst

DOCSTW/board/DOCSTW-209
otel-enabled and otel-endpoint should be otel_enabled and otel_endpoint

docs: Minor edits to master config reference

---

webui/react/src/components/kit/Drawer.module.scss
webui/react/src/components/kit/Drawer.tsx
webui/react/src/pages/DesignKit.tsx

Adds a customized Antd.Drawer, a full-height sidebar / overlay which scrolls into the window from the left or right.
This is a new component, so it does not replace existing components on the site.
- On `/det/design`, open the left and right Drawer components
- Confirm Drawer can close by clicking 'x' button
- Left Drawer scrollable content scrolls the body content, not the header
- Right Drawer content has checkboxes and text area; this content is preserved if you close and re-open the Drawer
- Confirm Drawer **does not close** if clicking on or outside the Drawer
- Antd animation is 0.3 seconds and does not need customization

feat: Drawer component added to UI Kit [WEB-1349]

---

webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

This updates the glide table with the ability to pin colums.
We only store the number of pinned columns to make the logic around moving columns while also allowing pinned columns to be rearranged. We would otherwise need to keep both the pinned column list and the unpinned column lists in sync.
WEB-1124

feat: allow column pinning for glide table

---

master/internal/rm/kubernetesrm/spec.go

We currently are not checking if tls is enabled when setting `DET_MASTER` in a Kubernetes agent. This results in protocol errors running experiments if tls is enabled. This change sets the `DET_MASTER` protocol to https if tls is enabled and http otherwise. 
- Create a Kubernetes cluster with TLS enabled
- Validate that you can run experiments 
- Create a Kubernetes cluster with TLS disabled
- Validate that you can run experiments

fix: set protocol scheme in kubernetes resource manager

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

**updated to fix two small issues with Glide Table**
1. When compare view is on, we check window width to keep some part of the compare panel visible
2. If the experiment glide table does not fill with rows, avoid showing row lines below:
Comment: the name column line is still there because `getRowThemeOverride` does not pass a column value, and `verticalBorder` does not pass a row value.
Use the `f_explist_v2=on` flag to view a project with just a few experiments: example `/det/projects/49/experiments?f_explist_v2=on`
**Table rows**
- Confirm the last data row has a bottom border
- Confirm rows below the last row do not have distinct markings
**Compare view**
- Click the "Compare" button to see table and compare panel side by side.
- Move the divider left and right; the divider cannot be …

fix: Don't draw rows after end of data; compare panel width [WEB-1339] [WEB-1365]

---

helm/charts/determined/Chart.yaml
helm/charts/determined/scripts/k8s-password-change.py
helm/charts/determined/templates/change-password.yaml
helm/charts/determined/templates/db-deployment.yaml
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/templates/scheduler-deployment.yaml
helm/charts/determined/values.yaml

This change is related to helm charts only.
The change results from the experience made during the installation of MLDE in the ISP's K8s environment. The HPE MSC (HPE My Software Center) images registry for licensed image download was used.
Removed: the static image references that were left inside the templates and created for each image a "default" var in values.yaml, added logger level and color (t/f) variables in master.yaml config.
Git branch: helm-static-imgs-ref

chore: Helm file removed static imgs refs, added log config

---

webui/react/src/components/kit/Dropdown.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/MultiSortMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/menu.tsx
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx

This updates the select all functionality in the glide table by allowing automatic selection of the top 5, 10, 25, and 50 rows of the table. When a selection is active, clicking the select all column resets the selection. 
With the glide table active:
* click the select all button
* The selection menu should appear
* When clicking on an item in the menu, the appropriate number of rows should be selected
* clicking on the select all button with an active selection clears the selection.
WEB-1188

feat: add selection menu to glide table

---

master/internal/proxy/tcp.go

Associated pull request in the ```determined-ee``` repo is https://github.com/determined-ai/determined-ee/pull/904.  Together, they address [FE-52](https://hpe-aiatscale.atlassian.net/browse/FE-52).
These code changes are relevant only when running ```tools/slurmcluster.sh``` or ```make slurmcluster``` (found in the ```determined-ee``` repo), which starts the Determined master locally on your laptop or test machine.   The Determined master that runs locally on your laptop or test machine runs experiments/shells/notebooks/etc on the HPC cluster (i.e., ```Slurm```) via the ```launcher```.
The issue being addressed here is that the ```det shell start``` command doesn't work when run locally from your laptop or test machine and ```DET_MASTER=localhost:8081```.
This is because the master tries …

fix: Modify the Determined master dialer to honor the proxy environment variables [FE-69]

---

webui/react/src/components/SplitPane.tsx
webui/react/src/hooks/useScrollbarWidth.ts
webui/react/src/pages/F_ExpList/ComparisonView.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.module.scss
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/columns.ts

This is a tricky situation, I'm open to suggestions both on the behavior I chose and how I implemented it. The issue was that on the new experiment list if:
- you had extra columns pinned (beyond just checkboxes and name)
- you opened the comparison pane
- you resized the comparison pane so that it covered the pinned experiments
- and you closed the comparison pane
Then the columns would overlap on the table.
The behavior I implemented to fix this is that when you resize the comparison pane, the difference between the old width and the new width is taken. If the table pane grew, then that difference is added onto the last pinned column. (This is the same behavior as previously) If the table pane shrunk, the last pinned column shrinks until it has exhausted that difference or it reaches a …

fix: pinned column resizing in compare view [WEB-1395]

---

webui/react/src/components/FilterForm/components/FilterField.tsx
webui/react/src/components/FilterForm/components/FilterFormStore.ts
webui/react/src/components/kit/InputNumber.tsx
webui/react/src/components/kit/Select.tsx

This adds a shortcut to the filter field where the user can press the enter key while the value field is focused in order to add a new field below it.
in the glide table's filter menu, pressing the enter button with any value column focused should insert a new form field below the currently focused field.
Default enter behavior on select and datepicker is overridden by intercepting the keyDown event.
WEB-1255

feat: add glide table filter field add shortcut

---

master/internal/proxy/proxy_intg_test.go

To flesh out the testing suite for proxy, add a test for the function `NewProxyHandler` which returns the echo handler function used for proxying HTTP-like traffic to services running in the cluster.
The intg test `TestNewProxyHandler` in `proxy_intg_test.go` should pass.
DET-9555

chore: add NewProxyHandler test to proxy_intg_test [DET-9555]

---

harness/determined/common/api/request.py
harness/tests/common/test_api.py

fix an issue with make_url that ignored paths given in through master_addres
allow for paths passed in as part of master url to `make_url` util

chore: account for paths passed in for DET_MASTER

---

harness/determined/cli/shell.py
harness/setup.py

`os.chmod` does not work as intended on Windows. This PR replaces the `os.chmod` operation if a Windows System is detected.
Run `det shell start` on a windows machine, making sure that the key file is created in a Public tempdir, such as `C://Users/Public` 
It's probably easiest to hardcode the `retention_dir` inside of `determined.cli.shell._prepare_key()` , run `setup.py`, and then try to create a shell via `python -m determined.cli shell start`
Windows inherits permissions from the current directory. If that directory is public, the file becomes public, causing this issue. `os.chmod` does not fix that. We are adding a new dependency for Windows systems.
See: https://github.com/determined-ai/determined/issues/6433
See [Release Note](https://github.com/determined-ai/determined/blob/master …

fix: Windows file permissions

---

master/internal/api_workspace.go

`GetWorkspaceProjects` API's sorting doesnt work due to ambiguous reference
[WEB-1378]
- Check if all sorts work in a project page and API
- Check if sorting is applied as soon as it's selected
[WEB-1378]: https://hpe-aiatscale.atlassian.net/browse/WEB-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: sort of  `GetWorkspaceProjects` API

---

master/internal/experiment_filter.go
webui/react/src/components/FilterForm/components/FilterField.tsx

This fixes an issue where the user filter in the new experiment list would sometimes fail to find matching experiments for users with display names set. This is because the webui would send the username, but the api was expecting the display name or username if set. To fix this, we update the frontend and backend to use the user id instead.
1. With the new experiment list active, filter by a user that has a display name
2. experiments from that user should show up.
WEB-1409

fix: use user id for new explist user filter

---

tools/scripts/track-pr

If a PR is coming from EE, then the basic codepath operates on EE automatically and the modified one that cherry-picks OSS PRs onto the EE branch should be skipped.

ci: handle cherry-picking EE PRs into release branch

---

webui/react/src/hooks/useSettings.ts
webui/react/src/hooks/useSettingsProvider.tsx

**The observed bug**: gcloud server, or localhost with gcloud backend, consistently do not read from querySettings. Latest-main and running locally cannot replicate.
**Our explanation**: on servers where querySettings code runs first, the query and stored settings merge successfully.
When querySettings happens later, the code to apply changes `stateOb.update((s) => s.set(config.storagePath, stateSettings))` is not triggering the update to settings expected by `settings = useMemo(() => ... [state])`  (due to s, state, and stateSettings being Immutable.Map objects)
**The fix**: `stateOb.update((s) => { ... }` should be based on `useSettings` code
**Clearing settings**:
- The `useEffect` for querySettings is run multiple times, so if navigation is checked before page-specific settings, …

fix: Race condition loading parsed query settings into all settings [WEB-1376]

---

webui/react/src/components/kit/LogViewer/LogViewerSelect.tsx
webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx

Replaces #7264 which modified log filters UI
This alternative uses its own AbortController ref to cancel the previous log requests. There are also changes to the reliability of the filters onChange call (so it won't trigger when we first load the page and cancelling the initial load of logs)
We lose access to the LogViewer component's `config.canceler` which closes the stream when navigating away, so I add an abort to the same `useEffect` cleanup callback used to close the `trialLogsFields` streaming request.
If you want to use gcloud experiment 2498, open omnibar and `dev serverAddress set https://gcloud.determined.ai`
Or find an experiment which lots of log filter options
- On the logs page, select multiple options in one or more dropdowns. Logs update as you make selections in a …

fix: LogViewer request handling to avoid filter mismatch [WEB-1412]

---

webui/react/src/pages/F_ExpList/CompareMetrics.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

Currently, the metric charts in the `Compare` tab may flash no data to plot because the current check only ensures that the data is at least partially loaded. However, some metric charts might not have an updated data `series` causing the UI to show the `no data to plot` message. 
This PR includes an update to `useTrialMetrics` to return whether or not each individual metric contains data. The `Compare` metrics tab now uses that information to ensure that each metric's chart has been fully updated.  
1. Open the `Compare` tab in the new experiments list. 
2. Select experiments that do not all contain the same metrics. For example, select an experiment that has only `validation loss` then select another experiment that has `validation accuracy`. Ensure that that as the new charts for the …

fix: no data to plot is shown sometimes incorrectly [WEB-1413]

---

docs/setup-cluster/workspaces.rst

per feedback: The “default landing page” is the dashboard page, not the uncategorized experiments list.

docs: Make correction on workspaces page

---

webui/react/src/pages/Settings/UserSettings.settings.ts

Omnibar's Ctrl Space hotkey should use the formatted name for the key ("Space")
Thanks Emily for pointing to recent changes. Looks like one PR around omnibar and one PR which gives a name to the Space key (rather than showing a blank space in UI) led to this falling through.
On the dashboard or other page, use Ctrl Space to launch the omnibar hover
For Mac users: this is "control" and not "command" key

fix: Link omnibar shortcut to new Space convention [WEB-1418]

---

harness/determined/launch/deepspeed.py
harness/tests/launch/test_deepspeed.py

Migrate our deepspeed launching strategy from only including specific known-important variables to only excluding known-dangerous variables.
This is what horovodrun has always done.
Also this works nicer in our system where users expect environment variables set in their expconf to be visible to their training code.
It is also a better choice for our system because unlike a user-owned machine, there won't likely be very many environment variables that aren't related to training, since we run inside of containers.

feat: launch.deepspeed passes (almost) all envvars

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

In the new Glide Table, we had a context menu appear when left-clicking on a column header.
This also allows right-click , without the default browser context menu from appearing.
On `/det/projects/1/experiments?f_explist_v2=on`
Left click on a column header to view context menu
Left click on other columns' headers to confirm the menu options match the column type
Select a sort option from the menu, confirm it sorts table
Right click on a column header to view context menu
Right click on other columns' headers to confirm the menu options match the column type
Select a sort option from this menu, confirm it sorts table

fix: Table header context menu enabled [WEB-1382]

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
pre-commit/run-golangci-lint.sh

typecheck complains if it's given a single file and not the package in some cases
It's now closer to the golangci-lint that make check runs with the difference being that here we check the parent package(s) of changes files and not the root packages. As I'm not sure if golangci-lint will be fast in all scenarios for everyone let's try to keep its scope smaller if we can

chore: golangci check the package instead

---

webui/react/src/App.tsx
webui/react/src/hooks/useSettings.test.tsx
webui/react/src/hooks/useSettings.ts
webui/react/src/hooks/useSettingsProvider.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/SignOut.tsx
webui/react/src/stores/userSettings.tsx

This PR adds a new store that provides a more idiomatic way of reading and writing user settings. It temporarily shares state with the old `useSettings` hook until that is replaced with this. Main features:
- Reduced complexity (no checking equality before writing, handling query params, etc)
- Improved serialization (settings can be anything)
- Impossible to accidentally access settings while they're still loading
- Check if all settings data is fetched when page is loaded
- Check if there no infinite settings calls in network tab
- Check if settings POST call is invoked when user changes the settings and check DB
- ex: changing filters in the new exp table, close filter popup, refresh page, check if filters persist
- Check if there's no console error in console tab (should be debug …

chore: Add new UserSettings store [WEB-1353]

---

e2e_tests/tests/cluster/test_groups.py
e2e_tests/tests/command/test_run.py
harness/determined/cli/__init__.py
harness/determined/cli/_util.py
harness/determined/cli/command.py
harness/determined/cli/experiment.py
harness/determined/cli/project.py
harness/determined/cli/user_groups.py
harness/determined/cli/workspace.py
harness/determined/common/api/errors.py
harness/determined/common/api/request.py
master/internal/api/error.go
master/internal/core_checkpoint_intg_test.go

For all cases where a Python error overrides the golang RBAC 'not found' error, we wish to output a consistent error message to users -- reminding them to check their permissions _if_ RBAC is enabled.
To test this change, check out branch [9606-test-python-err](https://github.com/determined-ai/determined-ee/tree/9606-test-python-err) from EE (which has the right commit cherry-picked) & spin up your own RBAC-enabled EE cluster. Then, for each of the cases changed, follow a similar workflow:
- in the admin role, create 'X' object that a second user should not have access to.
- From the second user's perspective try to `det describe` or somehow interact with 'X' object
- Confirm that the error given is of form: `<workspace/project/etc> <id> not found, please check your permissions.`
See …

fix: harmonize python & golang GET NotFound errs [DET-9606]

---

harness/determined/common/experimental/checkpoint/_checkpoint.py

When copying checkpoint files coming from shared-fs storage, we now no longer error when the destination checkpoint directory already exists. Instead, when metadata.json doesn't already exist in the destination, we'll write/overwrite files from the checkpoint into the destination. This new behavior mirrors what we already do when the checkpoint is stored in S3.
One way or another, find a checkpoint that has `checkpoint_storage.type: shared_fs`. Then try downloading the checkpoint to a local path that does or does not already exist.
Helpful snippets follow.
In the experiment config YAML:
```yaml
checkpoint_storage:
type: shared_fs
host_path: /path/to/master/checkpoints
```
Download:
```shell
det t download --latest -o <path> <trial-id>
```
or
```python
from determined.experimental import …
```

fix: Download to existing directory from shared_fs source [MLG-672]

---

e2e_tests/tests/cluster/managed_cluster.py
harness/determined/cli/master.py

With recent updates the CLI & api for master config, the new output json encloses everything in with a `config` key, causes tests that pull the config following the previous structure to fail. 
Instead, this corrects the output coming from the CLI to behave as previously without the additional `config` nesting.
- Run e2e tests

chore: corrected CLI to not nest master config under `config`

---

tools/scripts/gql.py
tools/scripts/track-pr

We've gotten the feedback that it would be nice to know what PRs have been cherry-picked but are not yet available to test. Cherry-picked PRs are now moved to a new unreleased status; adding tracking issues is delayed until `track-pr release-unreleased-prs` is run (which happens when an RC is cut). The PRs are then moved to a new released status instead of being deleted. The process doesn't touch them after that, but after a few releases I've found myself wanting to see what fixes have been merged as part of the project view.

ci: track unreleased cherry-picked PRs during release

---

tools/scripts/track-pr

Ignore case, include anything with a Conventional Commits type that starts with `feat` or `fix` (not just those exactly), exclude other types more broadly (not only things consisting of solely lowercase letters).

ci: tweak PR title matching in release tracking

---

harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/common/experimental/model.py
harness/tests/determined/common/experimental/test_checkpoint.py
harness/tests/determined/common/experimental/test_model.py

Local objects contain copies of data that exists also in the remote master. These copies can get out of sync.
This change addresses methods that change local objects' data and post (or patch) a request to master to update the remote copies, too.
Before this change errors over the API would still change local versions. With this change, we now treat APIErrors as total failures, and no longer update local copies.
This PR also adds tests for exactly this behavior in all the "update" methods in the SDK.
[MLG-587]
To manually test what the new unit tests do:
1. create a Model, ModelVersion, or Checkpoint.
2. Then make sure your client can't connect to master.
3. Call one of the modified methods (like model.add_metadata).
4. Observe that no change has been made to the local copy (for example …

fix: SDK methods don't update local on failure

---

webui/react/src/components/FilterForm/components/FilterField.tsx

Bug in Glide Table FilterForm - if you have a valid date field, and then clear the date input with its [x] button, it continues to send the null date as a string ("df"). This zombie filter causes a 500 error.
After applying this change:
- Above-left of the glide table, click the Filter button
- Set the start date filter to be after July 30th (or other future date)
- 0 experiments match filter; button label is "Filter (1)"
- Hover over date input and click the small x to clear it
- Experiments are shown again; button label is "Filter" again

fix: Cleared date field removed from filters [WEB-1408]

---

e2e_tests/tests/cluster/test_groups.py
e2e_tests/tests/cluster/test_rbac.py
harness/determined/cli/user_groups.py

Undoing instance of `not_found_errs` in the python user_groups code to resolve testing discrepancy in EE & standardize not-found-errs coverage in the same modules across golang & python.
Relates to https://github.com/determined-ai/determined/pull/6937, https://github.com/determined-ai/determined/pull/7252.
Test in EE against branch 9606-test-python-err, but also make sure CI checks pass here.
https://app.circleci.com/pipelines/github/determined-ai/determined-ee?branch=9606-test-python-err
DET-9606

fix: reverting not-found-errs change to python user-groups

---

webui/react/src/stores/userSettings.tsx

Fixes an issue with how user settings store constructs objects.
Visit the new experiment listing page and confirm that the settings load correctly first try.
No Ticket

fix: Fix issue in user settings store

---

webui/react/src/pages/Settings/GroupManagement.tsx

Refreshing `GroupManagement` page should load columns as expected
WEB-1438

fix: use DEFAULT_COLUMNS in GroupManagement table

---

tools/scripts/track-pr

- When a PR was labeled with the cherry-pick marker only after merging, it was never added as an open item, and so there was nothing to mark as unreleased and then released later on.
- When a PR ran into a conflict during cherry-picking, it was added as a conflicting item, whereas that should be assuming that the PR already exists as an item and only changing its status instead.

ci: fix some bugs in tracking of cherry-picked PRs

---

webui/react/src/pages/TrialDetails/TrialChart.tsx
webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx

When user forks or creates a new experiment and then proceeds to view the experiment detail page, after it comes off of the queue and proceeds to run, the page will render `Unable to fetch experiment` error message.
After diagnosing, the effect is that there are a bunch of `time-series` calls that gets called by `TrialChart` followed by a uncaught error thrown. It turns out when the loadable is returned as `NotLoaded` an empty `[]` is provided as a default `MetricNames` value. The problem lied in the fact that the empty default `[]` value is created as a new reference each time.
1. Wrap the api call in a `try/catch` block to prevent uncaught error.
2. Create a memoized `[]` empty metric names list as a default.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs …

fix: new exp detail crash [WEB-1444]

---

webui/react/src/components/ActionSheet.tsx
webui/react/src/components/FilterForm/TableFilter.tsx
webui/react/src/components/FilterForm/components/FilterField.tsx
webui/react/src/components/FilterForm/components/FilterGroup.tsx
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/RadioGroup.tsx
webui/react/src/components/ResourcePoolCard.tsx
webui/react/src/components/Table/TableFilterDropdown.tsx
webui/react/src/components/kit/Empty.tsx
webui/react/src/components/kit/Icon.test.tsx
webui/react/src/components/kit/Icon.tsx
webui/react/src/components/kit/InputShortcut.tsx
webui/react/src/components/kit/Modal.tsx
webui/react/src/components/kit/internal/Spinner/Spinner.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/MultiSortMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
webui/react/src/pages/TrialDetails/Header/TrialHeaderLeft.tsx
webui/react/src/pages/TrialDetails/TrialDetailsHeader.tsx

This PR allows Icons to be labeled as decorative and thus hidden from screen readers. I went through and marked all the decorative icons I could find and corrected a few aria-labels that were incorrect.
1. Go to the new experiment list and select an experiment
2. Via console tools confirm that the icon on the edit button has no aria label.
WEB-1379

chore: Clean up redundant aria-labels, correct wrong aria-labels [WEB-1379]

---

harness/determined/core/_context.py

The condition in the code was inverted. 
I've hit this while trying to use ray tune in the detached mode, because it spawns the "trials" outside of the main thread. 
The SIGUSR1 handler has been broken [since 0.23.0](https://github.com/determined-ai/determined/commit/cb52a196f4dbab64a1a020a13e4c971fb067f278).
- Try using SIGUSR1 for debugging.
- Once detached mode lands, this will be exercised by ray tune examples.

fix: install sigusr1 on main thread only.

---

harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/common/experimental/model.py

Earlier design: reload eagerly, whenever we're already making a call to master anyway.
Current design: reload only when the user calls for it (or in Experiment.wait).

chore: reload only when explicit

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/hooks/useSettings.test.tsx
webui/react/src/hooks/useSettings.ts
webui/react/src/utils/observable.ts

This PR fixes an issue that occurs when useSettings is active while settings it controls are being updated directly via the user settings store. This is tricky because `useSettings` guards all updates with `isEqual` which means it needs access to the _directly_ previous version of the state to work, opening the possibility for race conditions. I managed to rewrite it over to make all writes via the user settings store using some hacky nonsense.
1. Test changing the old and new versions of the experiment listing page, toggling features and adjusting columns.
2. Refresh and confirm the changed settings persist
No ticket

fix: userSettings store should function correctly when useSettings is active

---

webui/react/src/components/kit/LineChart.tsx
webui/react/src/pages/F_ExpList/CompareMetrics.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

Addresses an issue where the ChartGrid component was not loading new rows as the user scrolls through.
I think the old height logic here was used in old examples where we had small charts, or non-Loadable data.
Visit `/det/projects/1/experiments?f_explist_v2=on`
Open the Compare view
Select multiple types of experiments (mnist, cifar, fashion), adding multiple metrics charts to the ComparisonView
Scroll down the metrics chart on the ComparisonView - count 6 or more charts
There should be no additional space to scroll down past the last metric

fix: All metrics viewable in the glide table compare tab [WEB-1372] [WEB-1394]

---

webui/react/src/hooks/useSettings.ts

This PR fixes an issue where useSettings would incorrectly override settings under a race condition.
1. Go to the new experiment listing
2. Pin a column, observe it pins in the rightmost spot
3. Unpin any column but the last one, observe it unpins successfully
WEB-1462

fix: Correctly sequence updates in useSettings bridge code [WEB-1462]

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

This fixes an issue where the selection in the new experiment list experience is preserved when navigating between pages.
With the experiment list v2 flag enabled
WEB-1371

fix: clear table selection when changing pages

---

harness/determined/cli/command.py

This code had a bug where keys starting with`[, {` would be parsed as yaml, the we would call `.startswith` on the yaml and explode. Fix it by not calling string methods on any types.
I tested this when I landed it, I am unsure how this broke since then. Error stack:
```
(det) ➜  harness git:(trial_one_to_many_tasks) ✗ det shell start --config 'bind_mounts=[{host_path: "/tmp", container_path: "/tmp"}]'
bind_mounts [{host_path: "/tmp", container_path: "/tmp"}] <class 'str'> True
Traceback (most recent call last):
File "/Users/bradleylaney/Code/determined/harness/determined/cli/cli.py", line 288, in main
parsed_args.func(parsed_args)
File "/Users/bradleylaney/Code/determined/harness/determined/common/api/authentication.py", line 475, in f
return func(namespace)
File …
```

fix(cli): compound keys in --config opts for commands

---

master/internal/audit.go

Make it more helpful for user debugging.

feat: master audit logging should log failed requests at `Info` level.

---

harness/determined/cli/agent.py

Fix calls to old agents API.
I think this was missed here: d2b43de57d69be20a13654bb8e2e0b9963e77f6e
- Ensure `det agent disable --all` works and doesn't throw an error like it did before.
- Maybe ensure that the autocompleter works? (I couldn't get this to work and I assume this is something I need to setup in order for this to work)
MLG-724

fix: update get agents call for agent disable all [MLG-724]

---

docs/_templates/search-field.html
docs/requirements.txt

This updates the docs to fix the accessibility issues highlighted in the levelaccess tool.
- The sidebar toggles as well as the labels controlling the expansion and collapse of the table of contents have been given screenreader labels
- the inputs controlling the sidebar visibility have been updated to indicate that they control the primary/secondary sidebars as well as a pointer to a descriptive label
In order to do this properly, we fork the pydata-sphinx-theme python package and make the changes there. The changes to the package can be seen in https://github.com/determined-ai/pydata-sphinx-theme/pull/1 -- once approved, we can change the branch this PR is pointing to to main.
Docs site should not have any 10 severity accessibility issues in levelaccess.
See [Release …

docs: update aria labelling for sidebar toggles and toctree groups

---

webui/react/src/components/JupyterLabModal.tsx
webui/react/src/stores/cluster.tsx

Update resource pool picker under create JupyterLab session modal to be alphabetically sorted.
Update resource pool picker to allow name search.
WEB-1138

feat: sort resource pools by name when creating new jupyterlab sessions [WEB-1138]

---

tools/scripts/track-pr

To find the maximum dot-separated version, a simple string comparison is incorrect; instead we parse and compare the version tuples.

ci: fix latest release branch selection

---

docs/_templates/toggle-primary-sidebar.html
docs/assets/styles/determined.css
docs/conf.py

We want to show the sidebar and the search on the home page (i.e., we do not want to suppress it). We want to use the gray color palette rather than the multi-color (secondary brand colors) palette.
(Note: this reverses some of the changes that were made via PR #7169. )

docs: Reset home page tiles and sidebar

---

docs/release-notes/new-experiment-list.rst
webui/react/src/hooks/useFeature.ts

This PR launches the new experiment list for the general userbase by changing the default state of the feature switch to "on". Individual users can choose to disable the feature by turning the feature switch off.
1. Load the app
2. Go to Uncategorized and confirm it is the new experience
3. Append ?f_explist_v2=off to the url
4. Confirm you see the old experience
No Ticket

chore: explist_v2 feature switch should default to on

---

docs/index.rst

Rephrase the home page title to let users know this is the product documentation and what they can expect to find. This is more in line with other documentation sites.

docs: rephrase the home page title

---

webui/react/src/components/UserSettings.tsx

This uses the friendly names in the features config for the user settings labels
- open the settings sidebar
- the feature flags should be labeled with the friendly names, not the flags themselves.
no ticket

fix: use friendly names for user settings

---

tools/scripts/track-pr

Previously, we were not correctly setting the status of tracked PRs in release projects; a PR in a project has an item ID indicating its presence in the project that is distinct from the ID of the PR itself. This may have something to do with some PRs that were observed ending up in entirely unexpected places, though the old code should have just done nothing rather than moving things to wrong places, so I'm still not sure what was going on there.

ci: correctly change item status in release tracking

---

.circleci/config.yml

Fix `install_python.sh` script. Conda no longer supports `requests<2.27.0`, but the particular version of conda that we were using is force installing `requests==2.25.1`. Bump `conda` version to latest stable.
`test_ing` must be green.

ci: Conda bump

---

e2e_tests/tests/cluster/test_rbac.py

RBAC test failures that occurred when we switched these tests from running on OSS permission model to RBAC model.
Tests pass here https://github.com/determined-ai/determined-ee/pull/969/files

test: fix rbac test failures

---

e2e_tests/tests/nightly/test_capability.py

This example is currently broken, and we are deliberating whether it's useful and worth fixing.

test: skip `test_efficientdet_coco_pytorch_const`.

---

master/static/migrations/migration-move-to-top.sh

DET-9643
rename one of the migrations to be ahead of the current time in your machine then run move-to-top
```
.rw-r--r--   193 hmd  10 Jul 13:28  20240612120719_rename-new-username-fix.tx.down.sql
.rw-r--r--   106 hmd  10 Jul 13:28  20240612120719_rename-new-username-fix.tx.up.sql
.rw-r--r--   132 hmd  10 Jul 13:28  20230613164813_add-rp-workspace-bindings.tx.down.sql
.rw-r--r--   338 hmd  10 Jul 13:28  20230613164813_add-rp-workspace-bindings.tx.up.sql
.rw-r--r--   211 hmd  10 Jul 13:28  20230614134612_fix-gen-metric-unique-constraint.tx.down.sql
.rw-r--r--  2.3k hmd  10 Jul 13:28  20230614134612_fix-gen-metric-unique-constraint.tx.up.sql
.rw-r--r--     0 hmd  10 Jul 13:28  20230615134125_sanitize-generic-metric-types.tx.down.sql
.rw-r--r--   102 hmd  10 Jul 13:28 …
```

set up the migration script to validate the new migration num

---

master/internal/config/resource_config.go

Default aux pools were allowed to be bound because the function that returns default pools wasn't properly returning the aux pool name. 

fix: typo that allows binding default aux pool

---

harness/setup.py
harness/tests/requirements/requirements-harness.txt

responses==0.23.2 means urllib3>=2, and most of our dependencies are 
not ready for urllib3 version 2.

ci: avoid latest responses==0.23.2

---

master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go

Typo lead pods to run as wrong user.
Unit test + will test manually on a cluster set up with groups after merged.

fix: k8s determined-container gets wrong RunAsUser

---

master/internal/api_trials_intg_test.go
master/internal/trials/postgres_trials.go

Fixes an issue where `bun.Ident`, which we used to allow metrics names with /, was writing metric names such as `val.loss` into SQL as `AS "val"."loss"`
Example experiment with API error: http://latest-main.determined.ai:8080/det/experiments/3246/overview
The fix renames the metric for the query (i.e. `val·loss`) for the query, and restores the original name in the JSON response
In an experiment such as `examples/tutorials/mnist_pytorch`, rename `validation_loss` in `const.yaml` and `model_def.py` to `val.loss`
Run the experiment and observe you can plot `val.loss` with valid API responses
Update: verify that included unit test covers the issue of metric names with a "." , "/" , or other special characters
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/rele …

fix: Metrics with dot in name appear correctly in trial view [DET-9691]

---

.github/workflows/track-prs-for-release.yml

These are all potentially modifying the release branch, so we want them to not run simultaneously. The groups could probably be made more fine-grained, but the jobs are fast enough that keeping it simple should be fine.

ci: put all GHA jobs for release tracking in a concurrency group

---

master/internal/api_resourcepool.go
master/internal/api_workspace.go

in HPC clusters, some resource pools will be created without an explicit configuration in the master config. Previously, the rp-workspace mapping feature assumed that the config had all resource pools defined, which led to errors on the cluster page. 
This is a temporary patch - a permanent fix would require a bigger refactor, which will be done next sprint.

fix: rp-workspace mapping RP not found [WEB-1508]

---

harness/determined/pytorch/_data.py
harness/tests/requirements/requirements-harness.txt
tools/scripts/update-bumpenvs-yaml.py

A few changes preceding the advent of `pytorch==2.0.1` images:
1. A versioning conditional on our PyTorch DataLoader
2. Deprecated `attrdict` replaced with `attrdict3` in harness. This is necessary for `python>=3.9`. Either library is fine for `python==3.8`.
I've also thrown in a small update to `update-bumpenvs-yaml.py` to remove checking for `tf1` images following an update to our environments repo.
All PyTorch and DeepSpeed related tests should pass in CI.
Upgrading our task environment to `pytorch==2.0.1` is not as impossible as it seems, but we will have to take a look at `apex.amp` and our old, version pinned examples, as those are the key blockers of this from an OSS standpoint. …

feat: Pytorch2 necessary changes

---

master/static/srv/command-entrypoint.sh

**Note:** Some e2e tests, such as `tests/command/test_run.py::test_image_pull_after_remove` use an image (e.g., `environment.image=archlinux:base-20211010.0.36274`) that does not contain Python.  Therefore, in order to prevent the test from failing, I've changed `command-entrypoint.sh` to not exit if Python is not installed.
Anoop reported that when running a command from the MAC laptop with the Determined devcluster (i.e., `tools/slurmcluster.sh`) pointing to the `grenoble` cluster, tunneling wasn't working when the proxy port was configured.
To reproduce the issue observed by Anoop, perform the following steps:
1. On your MAC laptop, start the dev launcher and point it to the `grenoble` cluster.
```
(base) rcorujo@C02FJ0T8MD6Q hpc-ard-capsules-core % ./loadDevLauncher.sh -d …
```

fix: det tunnel should work with proxy port exposed [FE-121]

---

harness/determined/cli/cli.py

we used to print at least two newline characters at the end of every exception handled by the CLI that called the `die` handler. Here we remove one of those.
call a cli command that errors out
```
det e describe a2341
```
```
parser.exit(exit_code, colored(message + "\n", "red"))
```
was changed to print as part of some good refactoring and I think we unintentionally introduced double `\n` 

chore: remove double newline in cli error messages

---

webui/react/src/pages/F_ExpList/glide-table/columns.ts
webui/react/src/pages/TrialDetails/TrialInfoBox.tsx
webui/react/src/services/decoder.ts
webui/react/src/types.ts

follow up of #7481
#7481 change caused the issue https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1690570722216369
Values on `Checkpoints` column in the old view is not visible . This PR is the fix
This change is required since the following column picker in the old experiment table uses `dataIndex`
https://github.com/determined-ai/determined/blob/5ef7d30356c0a24051bcbf60f46e15c288e2716b/webui/react/src/pages/ExperimentList.tsx#L663
- Check if values on `Checkpoints` are all visible in both new/old experiment table
_Only changed frontend data schema since backend change might cause some other bugs. When we ditch the old experiment table, we can revert this change._

fix: rename checkpoints

---

master/internal/task/allocation.go
master/static/srv/entrypoint.sh

https://github.com/determined-ai/determined/pull/7492 broke `det command run` (and possibly other tasks) that didn't specify a proxy port in the config file.
```
(determined) (base) rcorujo@C02FJ0T8MD6Q determined-ee % PYTHONPATH=/Users/rcorujo/IdeaProjects/JUNK/determined-ee/harness det --master=localhost:8081 command run echo hello 
Launched command (id: 121e2f03-43d5-4f41-b538-eca806ab82ff).
[2023-08-01T15:00:08.851187Z]          || INFO: Scheduling Command (certainly-allowing-sole) (id: 121e2f03-43d5-4f41-b538-eca806ab82ff)
[2023-08-01T15:00:11.245390Z]          || INFO: HPC Job ID: 311
[2023-08-01T15:00:11.245454Z]          || INFO: Command (certainly-allowing-sole) was assigned to an agent
[2023-08-01T15:00:25.186271Z] [cont=0] || WARNING: [2315368] root: falling back to naive proxy …
```

fix: custom proxies do not work for trials in slurm [DET-9718]

---

harness/determined/exec/pid_server.py
harness/determined/ipc.py
harness/determined/launch/deepspeed.py
harness/determined/launch/horovod.py
harness/determined/util.py
master/static/srv/task-logging-setup.sh
master/static/srv/task-logging-teardown.sh

On Slurm job failures we do not reliably get the full logs
posted to the master from non-chief ranks.   When processing task-logging-teardown.sh
on error paths we commonly hit the 30sec timeout and therefore
end up with the entrypoint returning which which results in
termination of all processing with SIGKILL.
When errors occur pid-server will terminate the top-level
children launched via SIGTERM, however, this only terminates the
top-level children when there are actually multiple layers with
various process groups under the sshd.  When
only the top-level children are killed others still are holding
stdout/stderr active and therefore the log processing does not shut
down cleanly leading to potential message loss.
This change adds --signal-children support to the pid_server such that …

fix: Improve HPC error shutdown to improve logging [FE-44]

---

tools/scripts/track-pr

Due to delays in running GitHub Actions, a PR that is labeled for release cherry-picking immediately before or after being merged can go through the cherry-pick code path twice. (The on-label action sees a merged PR and the on-merge action sees a labeled one, so they both think they have to perform the cherry-pick.) The second cherry-pick then fails because Git sees that the commit would be empty and complains.
This change updates that code to check if a cherry-pick failure was due to a would-be-empty commit and skips the cherry-pick in that case.
Ideally, we would fix the concurrency issue at the GitHub level, but that sounds like more of a hassle. At an intermediate level of ideality, we would tell `git cherry-pick` to automatically skip the cherry-pick when it would be empty, but that …

ci: handle duplicate cherry-picks of a PR to release branch

---

webui/react/src/stores/userSettings.test.tsx
webui/react/src/stores/userSettings.tsx
webui/react/src/types.ts

This adds a new update function to the userSettings store which allows updating the settings at a storageKey given an updater function, similar to `setState((oldState) => newState)`
Unit tests should pass
During testing, I found that the types for `set` and `update` did not work for the test interface, so those are updated as well.
no ticket

chore: Add new `update` function to userSettings store

---

.github/CODEOWNERS

Setup codeowners for ml-sys areas:
- harness except for autogen
- expconf
- python bindings generator
- select e2e_tests (e.g. `experiment` (core UX tests) or `command` (mostly CLI tests), but not `cluster`)
As a next step, we'll need to:
- check if we like the assignment process: https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#about-auto-assignment
- TBD: enable branch protection
- iterate: if other high-traffic or auto-generated files will surface up, remove them.

ci: setup CODEOWNERS for ml-sys team.

---

webui/react/src/components/CreateGroupModal.tsx

In RBAC mode, the admin can add and remove users from groups.
The ticket is to keep deactivated users from being newly added to groups.
Current code uses the `disabled` attribute; this means a deactivated user cannot be added or removed from groups.
I tried filtering out deactivated users from the component, but then the antd.Select component shows an inactive user as their number id ("44").
As admin of an EE / RBAC server, on `/det/admin/group-management`
Click "New Group" and click under the Users label. You should see a list of many users which you can add to the group
For an existing group with users, click the row's three-dot menu and Edit to see users who can be added or removed from the group
On the users management page, create a test user and deactivate that account.
In the "New …

fix: Groups modal does not include inactive users [WEB-1256]

---

master/internal/api_experiment.go
master/internal/api_project.go
master/internal/experiment_filter.go
webui/react/src/ioTypes.ts

This replaces the sum and count metric columns for training metrics with a `mean` column that returns the arithmetic mean of the training metrics. The Columns API and experiment search api are updated with support for the new column. the runtime type of the metric config is updated a little to ensure the new format checks but also to fix issues with non-pointer values.
with the new experiment list flag turned on, visit an experiment listing page.
Note that the validation metrics are currently untouched because the column api and sort and filter automatically choose between max and min based on the experiment config.
WEB-1480

feat: Replace sum and count training metrics with mean in new experiment list

---

harness/determined/cli/experiment.py
harness/determined/cli/trial.py

Test cases:
- Run `det e logs [expid] --level INFO`
- Run `det t logs [trialid] --level INFO`
.... and make sure they work.

fix: log level filter broken on det t/e logs [MLG-798]

---

webui/react/src/components/UserSettings.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts

Changes how we use `experimentListGlobalSettingsConfig` so default values will fill in for partial settings on the exp. list.
Removes repeated console.error on pages such as http://latest-main.determined.ai:8080/det/projects/1/experiments
when the settings includes:
```javascript
"f_project-details-global": {
"expListView": "scroll"
},
```

fix: Accomodate partial experiment list settings

---

master/internal/rm/kubernetesrm/mock_client_test.go

In DET-9675, we attempt to remove mock_client_test.go & replace the mock interfaces found there with generated mocks. Due to the complexity of the tests, it’s not possible to make this replacement without severely complicating the code. To remedy this, write a comment in mock_client_test.go detailing this.
N/A
DET-9731
DET-9675

chore: summarize state of mock_client_test.go [DET-9731]

---

docs/conf.py
docs/requirements.txt

It was necessary to remove an ancient botocore dependency workaround.

docs: add sphinx-tabs extension

---

docs/release-notes.rst

Didn't get a chance to comment on notes for the last two releases before they went in (OOO for one, had an interview while the other was up). Also threw in some edits to older notes that I noticed.
While I know I am quite an outlier in terms of having opinions about this kind of editing, I would really like, and I think it is reasonable to ask, for more people besides me to at least take a cursory look over docs text to fix up basic formatting issues like single (instead of double) backticks and clearly weird capitalization.

docs: edit some release notes

---

master/internal/experiment_filter.go

Currently we cannot filter by checkpoint size in the new experiment list. Error received is `ERROR: column reference "checkpoint_size" is ambiguous`
This clarifies to use the `experiments.checkpoint_size` column
This doesn't fix awkwardness of API (for example to say > 10 MB, we write checkpointSize > 1000000 )
- Visit project page for Uncategorized. Filter by checkpointSize
- After server-side fix, no error emerges.
- Applying a minimum checkpointSize limits how many experiments are returned 

fix: Filter experiments by checkpoint size [WEB-1539]

---

docs/architecture/introduction.rst

Added Profiling to this table: https://docs.determined.ai/latest/architecture/introduction.html#benefits
Looks like this:

docs: Added Profiling to the Benefits table in the intro

---

webui/react/src/hooks/useFeature.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts

This updates the default for the `explist_v2` feature switch to on. Additionally I changed the storage paths for the settings since they shouldn't have a `f_` prefix.
1. Clear settings for your user
2. Test that the feature is on by default
3. Test that adding a new column works and persists after refresh
4. Test that changing row height works and persists after refresh
5. Test that row height is reflected in the settings drawer
No Ticket

chore: Make explist_v2 generally available

---

agent/internal/agent.go
agent/internal/options/options.go
agent/pkg/singularity/singularity.go

having installed Nvidia container CLI and updated the Singularity version on the aizn cluster, some divergence in behavior is evident in the Nvidia support offered by Singularity & Apptainer; slightly different run command qualifiers are required to get the desired result.
The approach adopted here is to allow `--container-runtime=apptainer` on the agent command line, and use this to construct the generated singularity commands appropriately.
Alternatives considered: have the singularity agent run the command `singularity --version` and parse the results; feasible of course, but more complex that the solution given here.
Additionally, I added a check to reject invalid values for the container runtime type.
Running the agent in a resource allocation: …

chore: migrate to singularity --nvccli

---

webui/react/src/components/UPlot/UPlotChart/closestPointPlugin.ts
webui/react/src/components/UPlot/UPlotChart/drawPointsPlugin.ts
webui/react/src/hooks/useFeature.ts
webui/react/src/pages/DesignKit.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/TrialDetails.tsx
webui/react/src/pages/TrialDetails/TrialDetailsMetrics.tsx

Trials will have a "Metrics" tab which shows the new charts / `ChartGrid` view.
Uses `isLoaded` from `useTrialMetrics` to reduce time that view shows "No data to plot"
Turning this on everywhere means we can also remove the charts feature flag
Visuals:
In experiments which ended with 0 trials, this will show the NeverTrials message which we also show in Overview and Hyperparameter tabs
If you use the latest-main backend:
- A single-trial experiment: `/det/experiments/1651/overview`
- Clicking the best checkpoint in the chart opens up the checkpoint modal
- Many metrics: `/det/experiments/2146/metrics`
- Trial of a multi-trial experiment: `/det/experiments/1757/trials/6322/metrics`
- An experiment which errored without any trials: `/det/experiments/1363/metrics`
- Successful experiment …

feat: Move new charts into always-on Metrics tab [WEB-1522] [WEB-1523]

---

.circleci/config.yml
docs/release-notes/pytorch2.rst
e2e_tests/tests/config.py
e2e_tests/tests/nightly/test_distributed.py
harness/Makefile
tools/scripts/bumpenvs.yaml
tools/scripts/update-bumpenvs-yaml.py

Putting our pytorch single-gpu and cpu tests on the shiny new `pytorch==2.0.1` images. Also throwing one nightly test in for good measure.
`test-unit-harness-pytorch2-cpu`
`test-unit-harness-pytorch2-gpu`
Hopefully we will not need this in the future when we upgrade our default task environments. We'll treat these as separate for now, until we have a better way to verify that they work with every integration we support.
MLG-510

ci:  Add pytorch2 tests

---

harness/determined/pytorch/_pytorch_context.py
harness/determined/pytorch/_pytorch_trial.py
harness/determined/pytorch/_trainer.py
harness/determined/pytorch/deepspeed/_deepspeed_context.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/tests/experiment/pytorch/test_pytorch_trial.py

Added new unit tests
**Case 1: When logging is disabled**
Added line `self.context.set_enable_tensorboard_logging(False)` to the init function of the trial class in this [example](https://github.com/determined-ai/determined/tree/main/examples/deepspeed/cifar10_cpu_offloading).
Verified that:
(1) From the UI, tensorboard would not finish loading as there is no tensorboard data
(2) Also verified that the underlying s3 storage has no tensorboard file for this trial (experiment id is 906 and we see that no folder exist for it)
Case 2: When logging is enabled (default behavior)
Using the [example](https://github.com/determined-ai/determined/tree/main/examples/deepspeed/cifar10_cpu_offloading) as is:
Verified that:
(1) From the UI, we can open tensorboard with metrics
(2) Also verified that the …

feat: Enable disabling Tensorboard logging [MLG-22]

---

tools/scripts/track-pr

Undoing an accidental local development change that came in as part of #7502.

ci: fix remote name in PR tracking script

---

agent/cmd/determined-agent/run.go
agent/internal/options/options.go
agent/pkg/singularity/singularity.go
docs/reference/deploy/config/agent-config-reference.rst

add singularity image cache capability.
Start the agent with a reference to an image cache:
`srun -N1 --gpus-per-node=4 /mnt/lustre/foundation_engineering/gaisford/determined-agent --master-host=casablanca-login  --master-port=8086 --resource-pool=default --container-runtime=apptainer --image-root=.launcher/images
`
If the requested image is in the cache then it is used on the generated singularity command line:
```
TRAC[2023-08-09T08:51:36-05:00] Requested image: determinedai/environments:cuda-11.3-pytorch-1.12-tf-2.8-gpu-9d07809  component=singularity
TRAC[2023-08-09T08:51:36-05:00] singularity run \
--writable-tmpfs \
--pwd /run/determined/workdir \
--env-file /tmp/determined-gaisford-node002/2625739182-9da62980-a155-4eb7-a511-eb49f6bfdc1f/envfile \
--bind …
```

chore: add agent --image-root

---

docs/assets/styles/determined.css

When clicking on a link to a specific section, the new page loads at the top and then scrolls down to the section. This can get annoying because it sometimes doesn't start scrolling for half a second, and then you have to wait for it scroll too.
So this PR turns off that behavior. 
Example: This link should load immediately at "Slurm Options": https://determined-ai-docs.s3.us-west-2.amazonaws.com/previews/6a8c454897b93e6f53e0f3508fabcdd6/reference/training/experiment-config-reference.html#slurm-options

docs: Add css to turn off scrolling when clicking on section links

---

webui/react/src/components/kit/LineChart.tsx
webui/react/src/components/kit/internal/UPlot/UPlotChart/tooltipsPlugin.ts

Turns on the `closeOnMouseExit` option on chart tooltip. This is especially helpful for single-point charts where the tooltip never closed.
Using latest-main backend,
- Go to `/det/projects/1/experiments` , with the new glide table
- Filter name to include `trees`, this includes experiments which end by reporting a validation metric one time
- Select one of the tree experiments
- Confirm there is a single validation metric point
- Confirm tooltip appears when mouse enters, and disappears when mouse exits the chart

fix: Single-point tooltip closes when mouse exits chart [WEB-1541]

---

webui/react/src/hooks/useMetricNames.ts

To cherry-pick into release? https://github.com/determined-ai/release-party-issues/issues/464
On experiments such as http://latest-main.determined.ai:8080/det/experiments/2118/trials/9397/metrics which failed without generating metrics, the Metrics and Hyperparameters tab show a loading spinner instead of a No Data message.
`useTrialMetrics` is returning `isLoaded: false` due to `metricNamesLoaded` returning false
After review, the issue is that we require `V1ExpMetricNamesResponse` to have new metric names before calling `setMetrics(Loaded( ... ))`. This experiment failed before generating any metrics.
This branch changes our setup for `V1ExpMetricNamesResponse` to update `NotLoaded` to `Loaded([])`.
- Using latest-main as a backend, `/det/experiments/2118/trials/9397/metrics` should …

fix: Handle metric names finish loading, but still empty

---

tools/scripts/track-pr

The pattern for finding release branches didn't take into account the `-ee` suffix used for EE branches.
We could just remove the `$` and it would probably be fine, but in this case I feel that the extra complexity is worth the precision.

ci: fix release branch selection when cherry-picking EE PRs

---

webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx

Moves options menu to left group of buttons in glide table view
On experiment list, Options button:
- is in new location
- has tooltip on hover
- can change row height setting

feat: OptionsMenu moved to left group [WEB-1519]

---

webui/react/src/components/kit/LineChart.tsx
webui/react/src/components/kit/internal/UPlot/SyncProvider.tsx

This contains two ChartGrid fixes:
1. When a ChartGrid contains two series with different x-min-max ranges, the scale should expand to cover both ranges
2. ChartGrid charts represent a NotLoaded series as spinner.  Once the series are all Loaded, if none contain points, then the chart should not be shown in the grid.
Visual of Problem 1: chart appears blank, x-axis range too small
Visual of Problem 2: chartgrid with 'no data' messages
Details:
- bounds were previously combined into the `unzoomedBounds` with some adjustments to prevent NaN/undefined values during loading, this should function the same
- if there is only one point on the chart, the dataMin and dataMax are the same. We set the bounds to [0, max], unless the point is negative, in this case the range is [min, 0]
**Scale fix** …

feat: Don't show charts where all series are Loaded(no data) [WEB-1524]

---

webui/react/src/pages/JobQueue/JobQueue.tsx

When there are > 10 jobs in a JobQueue tab (Active, Queued), there are buttons for changing page # and items per page, but these do not trigger a new API call.  We do not have polling in place either. So the only way to change results are UI dropdowns which call `fetchAll`, or refreshing the page.
Proposed fix: `useEffect` calls `fetchAll` after changing page offset or limit.
Run on CLI to create >20 jobs: `for i in {1..22}; do det -u admin shell start -d --config resources.slots=0; done`
- When refreshing, you should see 2 or 3 pages of jobs are available
- Clicking page [2] should change the contents of the table

fix: trigger jobs fetchAll on pagination changes [WEB-1546]

---

webui/react/src/components/MetricBadgeTag.test.tsx
webui/react/src/components/MetricBadgeTag.tsx
webui/react/src/components/MetricSelect.tsx
webui/react/src/components/kit/LineChart.tsx
webui/react/src/hooks/useMetricNames.ts
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
webui/react/src/pages/F_ExpList/CompareParallelCoordinates.settings.ts
webui/react/src/pages/F_ExpList/CompareParallelCoordinates.tsx
webui/react/src/pages/TrialDetails/MultiTrialDetailsHyperparameters.settings.ts
webui/react/src/pages/TrialDetails/MultiTrialDetailsHyperparameters.tsx
webui/react/src/pages/TrialDetails/TrialChart.tsx
webui/react/src/pages/TrialDetails/TrialDetailsMetrics.tsx
webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/services/types.ts
webui/react/src/types.ts
webui/react/src/utils/metric.test.ts
webui/react/src/utils/metric.ts
webui/react/src/utils/workload.test.ts
webui/react/src/utils/workload.ts

With the introduction of generic metric `types` (or `groups` going forward), metrics type/group is no longer restricted to just `Validation` and `Training`. It can be any user specified string value. Here are some examples to demonstrate how the metrics will change from the Web POV.
Results without custom metric groups from `/api/v1/experiments/metrics-stream/metric-names`:
```
{
"result": {
"searcherMetrics": [ "validation_error" ],
"trainingMetrics": [ "loss", "train_accuracy", "train_error" ],
"validationMetrics": [ "validation_accuracy", "validation_error" ],
"metricNames": [
{ "group": "training", "name": "loss" },
{ "group": "training", "name": "train_accuracy" },
{ "group": "training", "name": "train_error" },
{ "group": "validation", "name": "validation_accuracy" },
{ "group": …
```

feat: custom metric groups (formally known as types) [WEB-1469]

---

webui/react/src/components/ResourcePoolCard.module.scss
webui/react/src/components/ResourcePoolCard.tsx
webui/react/src/pages/Clusters/ClustersOverview.tsx

This PR replaces the action menu on resource pool cards with a tooltip for default resource pools. The message to the user informs them that a default resource pool's bindings cannot be changed. 
1. Navigate to the Cluster overview page as an admin.
2. With the `Resource Pool Binding` feature flag off, ensure that no action menu nor tooltip is shown for the resource pool cards under "Resource Pool". 
3. Ensure that the descriptive label i.e "Default Compute" is shown for the default resource pools.
4. With the `Resource Pool Binding` feature flag on, ensure that for the default resource pools an action item menu (3 dots) is not shown. Ensure that the text "Default" is shown with a tooltip message that is visible when hovering over the "Default" text. 
5. Navigate to the Cluster overview …

chore: Show Tooltip instead of actions for Default Resource Pools [WEB-1554]

---

.github/workflows/track-prs-for-release.yml
tools/scripts/track-pr

For visibility's sake, this includes the URL for viewing the GitHub Actions logs in the Slack notification for a cherry-pick conflict.

ci: indicate GHA run URL when reporting a cherry-pick conflict

---

webui/react/src/components/ProjectActionDropdown.tsx
webui/react/src/components/ProjectCard.tsx
webui/react/src/components/ProjectMoveModal.tsx

Deleting an empty project takes time to be reflected on the WorkspaceDetails page.
On review, `ProjectDeleteModal` calls `onClose` if the modal is exited or `onDelete` if the modal is submitted; and our use of `ProjectActionDropdown` assumed both would execute and use (`onComplete`) to trigger updating project list.
The logic might be due to a delay if the project contains experiments. Web UI currently shows the Delete option only for empty projects, so it's a non-issue.
- Create a project. In the WorkspaceDetails cards view, delete the project and see it quickly disappear
- Create a project. In the WorkspaceDetails list/table view, delete the project and see it quickly disappear
- Move a project to another workspace. The project should quickly disappear from this workspace view
See …

fix: Project delete/move triggers update of workspace projects list [WEB-1497] [WEB-1377]

---

master/internal/api_workspace.go
master/internal/mocks/workspace_authz_iface.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/workspace/authz_basic_impl.go
master/internal/workspace/authz_iface.go

There was an issue where a workspace viewer had permissions to edit workspace default pools and submit experiments to them, even if they were bound to another workspace. This change tightens the security around editing the workspace and experiment submission by:
- making the resolve resource pool function check for accessible resource pools even for default workspace pools
- adding a workspace RBAC authorization function that only allows cluster admins to be able to modify the default pool
- add logic so that a pool that is inaccessible to the workspace cannot be used as its default pool 

fix: default pools editable and submittable

---

docs/interfaces/tensorboard.rst
docs/setup-cluster/workspaces-rpools.rst

Update the instructions to let users know they cannot bind a **default** resource pool to a workspace.

docs: Update resource pool to workspace mapping

---

docs/model-dev-guide/apis-howto/api-pytorch-ug.rst
docs/model-dev-guide/submit-experiment.rst

Edit the PyTorch Trial docs to add a pointer to the pytorch distributed launcher information.
Jira ticket [TECHWR-79]. 
Test that the solution solves the problem of having a user encounter the PyTorch Trial docs without any information about the predefined PyTorch Distributed Launcher.
[TECHWR-79]: https://hpe-aiatscale.atlassian.net/browse/TECHWR-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Point to pytorch distributed launcher

---

docs/architecture/introduction.rst
docs/index.rst
docs/integrations/ecosystem/ecosystem-integration.rst
docs/integrations/pachyderm/pachyderm.rst

Problem domain: Determined users cannot find the Pachyderm documentation when visiting the Determined docs.
Solution: Introduce users to the concept of using pachyderm alongside determined, ensuring users can find "pachyderm" when using the Algolia search by and can access the Pachyderm documentation.

docs: Introduce users to pachyderm w det

---

requirements.txt

Unpinning `click` package version as both our versions of `tensorflow` and `black` have been updated, which addresses the core reason for the version pin.
ci passes linting tests
MLG-445

chore: unpin click version

---

master/internal/api_workspace.go
master/internal/mocks/workspace_authz_iface.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/workspace/authz_basic_impl.go
master/internal/workspace/authz_iface.go

Pulls the same changes as #7647 but applies to main instead of release branch. The main difference between the this PR and 7647 is the `req.Workspace.DefaultComputeResourcePool` and `req.Workspace.DefaultAuxResourcePool` fields, which are new and of type *string instead of string. The logic has been changed slightly to account for the nil case. 
This PR included multiple fixes, but most have been tested in the previous release party. The only part that requires testing is setting default resource pools for a workspace.
Using a privileged user (clusterAdmin or workspaceAdmin permissions), verify that you can set a default compute and aux pool for a workspace using both the CLI and WebUI. 
CLI command: `det w edit <name> --default-compute-pool <name> --default-aux-pool <name>`. 
WebUI: …

fix: default pools editable and submittable (#7647)

---

master/internal/core.go
master/internal/db/postgres_rp_workspace_bindings.go

Prevents a cluster from starting up if the specified default resource pools have bindings to workspaces.
Start a cluster, create a workspace, and bind one of your resource pools to the workspace. Go into the config and set:
```
...
resource_manager:
...
default_compute_resource_pool: <name of the bound pool>
...
```
Attempt to start the cluster up again and see that it fails. Repeat the same with `default_aux_resource_pool`.
Try this with a different resource pool (and with no default resource pools specified) and make sure it succeeds.

feat: check if default resource pools are bound

---

docs/conf.py

Due to a rather unfortunate interaction between `sphinx-tabs` and the internals of Sphinx itself, simply including the former as an extension causes `pydata-sphinx-theme`'s version dropdown to break. This change deactivates the code that causes that to happen, at the cost of unnecessarily including the tabs-related CSS and JS files even on pages that don't need them.
The issue is that `sphinx-tabs` replaces one of Sphinx's internal data structures with a copy of itself in a callback [1] (well, two, but only one is relevant here). This seems like it probably ought to be fine, but Sphinx's HTML builder depends on two different places referencing the same object, which the copy breaks.
Inside Sphinx, `StandaloneHTMLBuilder` creates a `globalcontext` member variable, a `dict` whose value for …

docs: work around bug causing version dropdown to fail

---

master/cmd/determined-master/root.go

This fixes a crash when 'task_container_defaults' isn't fully specified in config.
Run these changes in a test branch & spin up a devcluster _with_ `task_container_defaults` & `cpuSpec` defined, with _only_ `task_container_defaults` defined, and without `task_container_defaults`.
FE-176

fix: add type check to pod spec merge

---

master/internal/api_workspace.go

Previous updates to workspace update had inadvertently left a double update when setting default resource pools. As a result, the db update was failing due to "multiple assignments to same column". This fixes it.
Use the webui (workspaces -> select a workspace -> resource pools -> set as a default) and make sure it succeeds. Or use the cli: `det w edit <workspace name> --default-compute-pool <pool name> --default-aux-pool <pool name>`. 

fix: patch workspace has duplicate update statements

---

webui/react/src/components/ExperimentCreateModal.tsx

Keeps Continue Trial modal's state, by reducing changes from a `useEffect` based on experiment / trial update.
Confirmed @hkang1 's comment about polling during incomplete experiment was resetting the modal
Go to `/det/experiments/3698/overview` to see a paused experiment which continues polling
Click "Continue Trial" and select "Show Full Config" to open the custom YAML modal
Enter custom text into the custom YAML textbox (such as making another version for image / cpu, doesn't need to be accurate)
Confirm after 20-30 seconds that the modal and its textbox are unchanged
Click Continue Trial and confirm the new experiment has your custom config

fix: Continue Trial modal does not reset mode [WEB-1566]

---

master/internal/api_resourcepool.go

There was previously no distinction between RPs with no bindings, and RPs that a user did not have access to, as both would appear to have no bindings. As of this PR, if a user does not have access to a workspace that is bound to a resource pool, we should be able to detect it and return a not found error.
using two workspaces (A and B), bind A to a resource pool. create a user with edit access to B, and use the CLI command `det rp bindings list-workspaces <resource pool name>`. You should get an error that the resource pool "does not exist or is not available to view".

fix: users can see inaccessible RPs

---

master/pkg/syncx/mapx/mapx_test.go

fix: add unit test cases for `mapx` methods `Values()` and `Clear()`
Added unit test `TestMapx` to test all methods of `mapx`.
Test results for `FuzzMap` test before the fix in #7698 
```
jagadeesh.madagundi@C02FJ10GMD6Q mapx % go test -fuzz FuzzMap --parallel 64 .     
fuzz: elapsed: 0s, gathering baseline coverage: 0/6 completed
failure while testing seed corpus entry: FuzzMap/2fa92b628ed3b99b
fuzz: elapsed: 0s, gathering baseline coverage: 2/6 completed
--- FAIL: FuzzMap (0.20s)
fuzzing process hung or terminated unexpectedly: exit status 2
FAIL
exit status 1
FAIL    github.com/determined-ai/determined/master/pkg/syncx/mapx       0.452s
jagadeesh.madagundi@C02FJ10GMD6Q mapx % go test -fuzz FuzzMap --parallel 64 .
fuzz: elapsed: 0s, gathering baseline coverage: 0/6 completed
failure …
```

fix: add unit test cases for mapx methods Values and Clear

---

master/pkg/syncx/mapx/mapx_test.go

Code cleanup for the `mapx` unit test.
Addressing outstanding comments on #7699 
The unit test ran successfully
FE-23

fix: code cleanup for mapx unit test

---

webui/react/src/components/kit/LineChart.tsx
webui/react/src/components/kit/internal/UPlot/SyncProvider.tsx
webui/react/src/components/kit/internal/UPlot/UPlotChart.tsx

Fixes an issue with ChartGrid component - after #7609 the x-axis min and max accumulate across charts
This x-axis sync needs to reset when we switch the x-axis domain (such as batches -> time), to avoid expanding min-max across incompatible units
Can toggle between batches and time x-axis on an experiment metrics tab (`/det/experiments/1651/metrics`) 
Can toggle between batches and time on an experiment list comparison sidebar (`/det/projects/107/experiments?compare=true`)
Neither builds up a huge x-axis bounds from

fix: Reset chart min/max when changing XAxisDomain

---

harness/determined/cli/job.py
harness/determined/common/util.py

When displaying the list of jobs, DeterminedAI CLI splits the provided job submission timestamp on a dot(`.`). This works fine for DeterminedAI-provided timestamps which are of the format `2022-12-31T23:59:59.999999Z`. But, this code crashes when the timestamp is in another format like in the case of external jobs the timestamp format is `2022-12-31T23:59:59Z`. In either case, we only need the first 19 characters to create the timestamp. So, updated the code to use only the first 19 characters.
Tested manually using EE repo.
```
jagadeesh.madagundi@C02FJ10GMD6Q cifar10_pytorch % det job list
-----+--------------------------------------+-----------------+-----------------------------+----------+---------------------------+---------------------------+-----------------+------------
0 | …
```

chore: update determined cli to handle timestamp format for external jobs

---

webui/react/src/components/kit/internal/UPlot/SyncProvider.tsx

Discovered in testing #7719 - 
In a chart grid component,  you can zoom into a chart by clicking and dragging left or right
When we switch the x-axis such as Batches -> [Unix] Time, the units are incompatible. Any custom zoom should be reset
In an experiment metrics tab such as `/det/experiments/1651/metrics`, 
- Zoom into one chart by clicking and dragging left or right
- All charts should sync to the new x-min-max bounds
- Change X Axis between batches -> time
- Chart zoom should reset to the bounds in time units

fix: Changing x axis type should reset any current custom zoom

---

README.md

Adds links to user guides to the Documentation section of the GitHub Readme.
View it here: https://github.com/determined-ai/determined/tree/KevinMusgrave/readme3#documentation

docs: Add user guides to the Documentation section

---

docs/release-notes/trial-logs-failing.rst
master/internal/api_trials_intg_test.go
master/internal/experiment.go

Fixes `experimentIDFromTrialTaskID` to account for the `backfilled` taskIDs.
Integration test
manual get trial logs for trial ID 2020 on gcloud with ```det t logs 2020````

fix: backfilled tasks weren't seen as trial tasks

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/pods.go

When a k8's NodeInformer fails to list nodes on initialization due to a permission error, instead of panic'ing the expected behavior is to allow the failure and log a warning that the the node informer failed due to a permission error. 
- Change the following snippit from `helm/charts/determined/templates/master-permissions.yaml`:
Current:
```
- apiGroups: [""]
resources: ["nodes", "events"]
verbs: ["list", "watch"]
```
Change to:
```
- apiGroups: [""]
resources: ["events"]
verbs: ["list", "watch"]
```
- Spin up a GKE environment (using the [Runbook](https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1339359245/Runbook+Developing+Determined+with+Kubernetes))
- determined may not properly be installed in the cluster since the permissions will fail, if so you'll need to clone …

fix: allow NodeInformer to fail with permission error [DET-9772]

---

e2e_tests/tests/cluster/test_agent_disable.py
e2e_tests/tests/cluster/test_agent_restart.py
e2e_tests/tests/cluster/test_master_restart.py
e2e_tests/tests/cluster/test_priority_scheduler.py
e2e_tests/tests/cluster/utils.py
e2e_tests/tests/command/__init__.py
e2e_tests/tests/command/command.py

chore: add a new assertion method to check command exit status and report any errors
One of the e2e slurm tests, part of determined-ee nightly tests, is failing on and off. The current test setup does provide any info on such failures (please refer [here](https://app.circleci.com/pipelines/github/determined-ai/determined-ee/9014/workflows/b1b11f41-e452-446e-aece-6e26124754b8/jobs/405428)). Added a new method that evaluates the command info and asserts if the command was successful. In case of a failure, it will print the command logs to help the developers debug the issue further. 
```
e2e_tests % pytest tests/cluster/test_master_restart.py -k test_master_restart_cmd
============================================================================= test session starts …
```

chore: add a new assertion method to check command exit status and report any errors

---

master/internal/api_experiment.go
webui/react/src/hooks/useMetricNames.ts
webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

TrialOverview and TrialMetrics stream metric names until the experiments/trials on the page have all terminated.
On the server we check for new metric names every 30 seconds unless requested, and this delays when we can start showing values for the first metrics
After discussion of this ticket, we'd like the metric names endpoint to query faster (every 5 seconds).
Locally fork an experiment from `/det/projects/107/experiments`, or use the const.yaml in WEB-1576 to make your own quick-running experiment
The first metric names should appear in the dropdown, and on the chart, before the experiment finishes running

fix: Faster polling for first experiment metrics [WEB-1576]

---

webui/react/src/components/UPlot/SyncProvider.tsx
webui/react/src/components/kit/internal/UPlot/SyncProvider.tsx
webui/react/src/pages/DesignKit.tsx

For charts with a single x-value, we typically set the x-axis to include the point and 0. This is breaking on charts where all points are at x=0
In this case, we should set the x-axis to be xmin=0, xmax=1. The chart datapoint will then be rendered:
Visit `/det/experiments/4194/overview` and confirm a visible and hoverable point in the top left
Visit `/det/experiments/4194/metrics` and confirm a visible hoverable point on the left edge of both charts
Visit another completed experiment and confirm chart bounds look normal on Overview and Metrics tabs 

fix: Handle chart x-axis with all points at x=0 [WEB-1622]

---

master/internal/api_experiment.go

`getExperiment` helper is not selecting the `unmanaged` boolean field, so it's always false.
1. submit a detached mode experiment
2. Check `GetExperiment` response payload for it
3. `unmanaged` should be true.

fix: include `unmanaged` field in `GetExperiment`.

---

webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx
webui/react/src/pages/Clusters/ClustersQueuedChart.tsx

On the `Avg Queued Time` charts (under each resource pool) when there is only a single data point, the date range is incorrect. Fix the date range to render a proper chart.
BEFORE:
AFTER:
The hard part is going to replicate the state of the resource pool stats to ensure there is only one data point... This can be mocked but not easy to do...
WEB-1621

fix: correct date range for avg queued time charts [WEB-1621]

---

webui/react/src/components/kit/CodeEditor/CodeEditor.module.scss

[WEB-1612], [WEB-1431], [DET-9683]
https://github.com/determined-ai/determined/assets/109113616/735f9036-d1cd-48f8-9e1c-663e1c1a07d4
https://github.com/determined-ai/determined/assets/109113616/716053be-efb1-49f5-8977-2f57fed97ae6
- Check if width in code editor is consistent during scrolling and after switching files
- tips: find a file with long lines (ideally at least 110 lines)
- Check if mobile view behavior is the same as before this PR
[WEB-1612]: https://hpe-aiatscale.atlassian.net/browse/WEB-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1431]: https://hpe-aiatscale.atlassian.net/browse/WEB-1431?atlOrigin=eyJp …

fix: glitchy width in code editor

---

.circleci/config.yml

The `nightly` tests workflow currently runs on the `main` branch using the CircleCI `triggers:` mechanism in `.circleci/config.yml`.
```
nightly:
triggers:
- schedule:
cron: "0 5 * * *"
filters:
branches:
only:
- main
```
However, this does not allow the developer to run the `nightly` tests workflow on demand at the gate, in case they wish to see how their code changes impact the nightly tests.
The changes being made in this pull request allow the `nightly` tests workflow to continue to run on the `main` branch once per night, according to a schedule that the CircleCI administrator sets up (see https://circleci.com/docs/set-a-nightly-scheduled-pipeline/).  It also allows the developer to request that the `nightly` tests workflow be run on demand at the gate if the developer adds the …

chore: Create/document a mechanism to run the nightly tests on a PR [FE-146]

---

agent/internal/agent.go
master/internal/rm/agentrm/agent.go

On the Determined Enterprise Edition, when the dev cluster is started with `tools/slurmcluster.sh`, an SSH tunnel is created between the local host and the HPC cluster. Due to the way the reverse tunnel is created, all the nodes will report a loopback address of `[::1]`. This will cause distributed experiments to fail. To work around this, use the newly added agent's `hostname` parameter, which will be the node name that the agent is running on, as the IP address. As long as the cluster has been configured to resolve the node names to their respective IP addresses via `/etc/hosts`, DNS, or some other mechanism, this will work.
Note that if the master and the agent are both running locally on the same machine, the agent will also report an address of `[::1]`.  In this case, where the …

fix: Get distributed jobs working with devcluster [FE-181]

---

.circleci/config.yml
e2e_tests/pytest.ini
e2e_tests/tests/conftest.py
e2e_tests/tests/nightly/test_convergence.py
e2e_tests/tests/nightly/test_distributed.py

Per [this Slack thread](https://hpe-aiatscale.slack.com/archives/C04C9JXB1C2/p1692209150919889?thread_ts=1692208341.014209&cid=C04C9JXB1C2), I did some digging into what's flaky using the CI Dashboard and [the CircleCI Insights tool](https://app.circleci.com/insights/github/determined-ai/determined/workflows/nightly/tests?branch=main&reporting-window=last-7-days) to find what's seeming flakiest.
This is based on @wes-turner's #7520, which quarantined two flaky nightly tests. There's some more work and/or thought that needs to go into coming up with the proper approach for quarantining those (especially `test_cifar10_tf_keras_accuracy`), so in the meantime I hope this helps the nightlies be more useful.
This should be a CI-only change.

ci: quarantine some flaky nightlies

---

tools/k8s/devcluster.yaml

The custom stage for the coscheduler is still a useful example, but now it's been demoted to comment status.

chore: tools/k8s doesn't use coscheduler

---

master/internal/api_project.go
webui/react/src/components/FilterForm/components/FilterField.tsx

We've seen this issue on gcloud - likely there are metric names which we consider to be different, but when turned into the React key attribute are the same string, or clash with our use of .min/.max/.last
With this index fix, the keys in the dropdown options are unique
**Updated with backend fix**
On https://gcloud.determined.ai/api/v1/projects/1/columns we return `training.accurarcy.last` three times, with Unspecified, Number, and Text types.
We should return one Unspecified column, and skip repeats of the column name 
Use the omnibar to set the backend to https://gcloud.determined.ai
On `/det/projects/1/experiments`, click "Filter" at top-left of the table
Open up the field Name dropdown, and you should see ID, Name, State
Use the mouse to grab the dropdown scroll cursor and rapidly go …

fix: Avoid dropdown repeating in ExpList fields dropdown [WEB-1598]

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization/LearningCurve.tsx

We recently added support for metric groups other than the original training and validation types (see: #7727)
LearningCurve is defaulting to "unknown" group, because we didn't update its tooltip. We should send `metricType: ''` so it's not replaced, and not rendering an empty/blank group name.
Visit a multi-trial experiment, and hover over points
Confirm "unknown." does not appear in multitrial chart tooltip

fix: Learning curve will send falsey metricType

---

webui/react/src/stores/userSettings.test.tsx
webui/react/src/stores/userSettings.tsx

This PR does two things:
1. splits out the overload case for partial updates from the `userSettings.set` case into its own function called `setPartial`. This reduces the magic a bit and makes each piece easier to reason about.
2. Adds a special-case to `setPartial` for the type `T & Partial<U>`.
The second case _could_ be generalized to work on any intersections of object types but the typing was _a lot_ and I didn't really want to get into it.
1. Check that the tests pass
2. Check that the user settings drawer works properly
No Ticket

chore: Split out partial updates into setPartial

---

docs/release-notes/dupeCheckpoints.rst
master/internal/api_checkpoint_intg_test.go
master/static/migrations/20230908100300_fix-dupe-checkpoints.tx.down.sql
master/static/migrations/20230908100300_fix-dupe-checkpoints.tx.up.sql

Bug in checkpoints view's where clause.
We left join on raw_steps and raw_validations but messed up the WHERE clause.
We start with
```
WHERE s.archived IS NULL OR (s.archived = false AND v.archived IS NULL) OR v.archived = false
```
Assume s.archived IS NULL and v.archived IS NULL is false they almost always will be
```
WHERE false OR (s.archived = false AND FALSE) OR v.archived = false 
```
```
WHERE false OR false OR v.archived = false
```
We are left with, which with a checkpoint on an steps_completed that had a training step archived, would give us the dupe checkpoints. 
```
WHERE v.archived = false 
```
covered by integration test.

fix: dupe checkpoints

---

docs/release-notes/metrics-overwrites.rst
master/go.mod
master/internal/db/postgres_trial_intg_test.go
master/internal/db/postgres_trial_metrics.go

Allow reporting metrics at the same step with duplicate keys as long as the duplicate keys have the same value, e.g.
```
{'step': 1718, 'valid_loss_epoch': 0.592993438243866, 'epoch': 0}
{'step': 1718, 'train_loss_epoch': 0.9345674514770508, 'epoch': 0}
```
Automated tests have been added.
To test manually, implement a core API script which reports metrics in this fashion, e.g.
```
epoch = i // 10
core_v2.train.report_training_metrics(steps_completed=i, metrics={"loss": random.random(), "epoch": epoch})
core_v2.train.report_training_metrics(steps_completed=i, metrics={"loss2": random.random(), "epoch": epoch})
```

feat: allow metrics with duplicate keys and the same value [MLG-890].

---

helm/charts/determined/scripts/k8s-password-change.py
helm/charts/determined/templates/change-password.yaml
helm/charts/determined/templates/db-deployment.yaml
helm/charts/determined/templates/master-deployment.yaml
helm/charts/determined/templates/priority-classes.yaml
helm/charts/determined/values.yaml

Changes regarding: Helm chart
* Management of cluster wide object **non-namespeced** objects creation scheduler priority creation can be disable permitting to deploy two masters on the same K8s cluster without errors
* External Ca Cert injection using initcontainer - Installer could create a secret with the certificate 
e.g., `kubectl create secret generic ext-ca-cert --from-file="ca.crt" -n mlde`
and point it inside the `values.yaml` to insert into the Master container in the certificate dir
* K8s change passwords script 
* not working in Node port mode when Cluster IP is specified
* escape password parameter added `| quote` (missed by mistake I guess)
* PostgreSQL port setup now works

feat: helm ca.cert injection, cluster-wide non-namespaced res creation flag, password change and minor-fix

---

harness/determined/cli/agent.py

`det agent [enable|disable]` error message was incorrectly suggesting we have `--agent-id` option which is not true.
fixes #7831 
Running `det agent disable` displays a sensible error.

fix: error message for `det agent [enable|disable]`.

---

examples/features/torch_batch_process_embeddings/bert_embedding_generation.py

This fixes one of the e2e_test examples that didn't get updated properly with the https://github.com/determined-ai/determined/pull/7592 PR.
CI passes

fix: fix how we are calling the bert embedding example

---

webui/react/src/components/ModelActionDropdown.tsx
webui/react/src/components/ModelRegistry.tsx

We allow users to edit rows of the ModelRegistry table, similar to ExperimentList.  When we refresh model data through polling, it overwrites an edit in progress.
ExperimentList does not have this issue because it uses ExperimentActionDropdown. I've transferred that logic here for a new ModelActionDropdown component.
This also fixes an issue where state was updated every time, because existing model tags were sorted differently in the API response and in the rendered state.
- On `/det/models`, start editing the description field. Pause and wait several seconds. The description should not be changed back to the original or empty value
- Add a model tag
- Right-click a row and Archive the model; soon it should appear Archived (i.e. editing disabled)
See [Release …

fix: Make models list editing work via ModelActionDropdown [WEB-1603]

---

harness/determined/cli/dev.py

when piped into another program
when using det dev bindings the cli will try to match user query to a specific call via a single interactive prompt. We should disable this and error out if the call is being piped to another program
no testing is needed (internal dev tool).

chore: disable interactive matching for dev bindings

---

e2e_tests/tests/command/__init__.py
e2e_tests/tests/command/command.py
e2e_tests/tests/command/test_run.py

This will enable running the command run tests for HPC slurm/pbs jobs.
Once this is merged, will add @pytest.mark.e2e_slurm and @pytest.mark.e2e_pbs tags to determined-ee. See https://github.com/determined-ai/determined-ee/pull/1044

test: enable command run tests for hpc

---

webui/react/src/components/ProjectActionDropdown.tsx
webui/react/src/components/ProjectCard.tsx
webui/react/src/components/ProjectDeleteModal.tsx
webui/react/src/components/ProjectEditModal.tsx
webui/react/src/components/ProjectMoveModal.tsx
webui/react/src/pages/Dashboard.tsx
webui/react/src/pages/ProjectDetails.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx

Addresses feedback from release party a few weeks ago: https://github.com/orgs/determined-ai/projects/18/views/1?pane=issue&itemId=36080269
Old version: we would pass `fetchProjects` to the project action menu so after move/delete succeeded, we would trigger a refresh of the page data
New version: remove uncertainty from the `onClose` and `onComplete` functions with specific options for `onEdit`, `onMove`, and `onDelete`. On a Project's ProjectDetails page we continue using the `fetchProject` callback (or redirect if we are deleting this project). On a WorkspaceProjects list, this adds an `onProjectRemove` and `onProjectEdit` callbacks to quickly update the UI.
Extra change: I hid these project action menus on the dashboard. Will ask design about this
- On `/det/` (dashboard) hover over …

fix: Project move/delete updates UI state [WEB-1668]

---

master/internal/user/postgres_users.go

Fix a bug where when only agent user groups are updated for a User, it empty updates all other fields.
Pass all e2e tests, and make sure
```
// With fixes
det -u admin user link-with-agent-user admin --agent-uid 1 --agent-user 1 --agent-gid 1 --agent-group 1
User Id | Username  | Admin  | Active  | Remote  | Agent Uid  | Agent Gid  | Agent User  | Agent Group 
-----------+------------+---------+----------+----------+-------------+-------------+--------------+--------------- 
1 | admin     | True   | True    | False   | N/A        | N/A        | N/A         | N/A 
2 | determined | False  | True    | False   | N/A        | N/A        | N/A         | N/A
// No fixes
det -u admin user link-with-agent-user admin --agent-uid 1 --agent-user 1 --agent-gid 1 --agent-group 1
User Id | Username  | …
```

fix: redefine user columns updated in postgres_users toUpdate

---

webui/react/src/components/Metadata/EditableMetadata.tsx
webui/react/src/components/Metadata/MetadataCard.tsx

Support metadata editor, allowing the value to be fully cleared, and recovering rows when cancelled
- On `/det/models`, select a model
- In the Metadata section at the end of the page, click the pencil icon to open the editor
- Add one key and value, then click Save. Metadata now is available
- Click the pencil icon, and use the menu to remove that row. Click Save and the Metadata is now empty. Refresh the page to confirm Metadata was removed.
- Click the pencil icon, add one key, and save. Click the pencil again, remove that row, then click Cancel. The metadata should still be present.

fix: Metadata deleting last row, cancelling delete [WEB-1655]

---

docs/release-notes/agent-uid-workspaces.rst
e2e_tests/tests/cluster/test_agent_user_group.py
master/internal/api_checkpoint.go
master/internal/api_command.go
master/internal/api_experiment.go
master/internal/api_workspace_intg_test.go
master/internal/experiment.go
master/internal/user/postgres_agentusergroup.go
master/internal/workspace/postgres_workspace.go

NTSC didn't inherit workspace's agent user group just since we added NTSC to workspace after we added this feature.
e2e test + intg 
manual
```
det -u admin workspace create testg --agent-user 2000 --agent-uid 2001 --agent-group 1000 --agent-gid 1001
```
```
det cmd run -w testg "id"
```
You should get
```
[2023-09-14T19:54:14.504445Z] f4f90219 || uid=2001(2000) gid=1001(1000) groups=1001(1000)
```

fix: NTSC use workspace's agent group info [DET-9843]

---

webui/react/src/components/kit/Input.tsx
webui/react/src/components/kit/InputNumber.tsx
webui/react/src/components/kit/Select.tsx
webui/react/src/components/kit/Tags.tsx
webui/react/src/hooks/useInputEscape.ts
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx
webui/react/src/hooks/useModalEscape.ts

This PR introduces the ability for inputs to correctly handle "Escape" button presses and clicks to ensure that the inputs themselves lose focus, instead of having the entire modal close. 
Example showing text, number, and dropdown inputs losing focus and then the modal closing. 
https://github.com/determined-ai/determined/assets/103522725/54683ec0-c9d8-4ba8-87c0-053b53e15d79
**Note:** The functionality handles all inputs in the UI Kit, however there are some input instances throughout the UI, such as some `Select` inputs that do not currently use UI Kit components. The plan is to ensure that there is a follow-up ticket to ensure all inputs use the `UI Kit` components
1. Navigate to the Workspaces list page.
2. Click on the `New Workspace` button.
3. Click outside the modal, the modal …

feat: Input should capture the Esc button and Clicks while focused [WEB-1251]

---

master/pkg/model/environment_config.go

When the user runs det command run and specifies a specific image to use for a particular device type (i.e., cpu, cuda, rocm), the other device types from TaskContainerDefaults are lost.
For example, if the user runs:
```
det command run --config "environment.image.cuda=anoophpe/app-qa:6.0" echo hello
```
Then the `cpu` and `rocm` images from TaskContainerDefaults are lost when the image in user-specified configuration is merged with the images from the TaskContainerDefaults.
When the same command above is run with 0 slots specified, as shown below, it will fail with the error `unable to launch job: No image is configured for slot_type: cpu`.
```
det command run --config "resources.slots=0" --config "environment.image.cuda=anoophpe/app-qa:6.0" echo "hello"
```
This is because the …

fix: api_command.go does not merge map values when overrides TaskContainerDefaults [FE-114]

---

docs/architecture/introduction.rst

The description of fair-share scheduling is too hard to read. Rewrite it so that users can better understand the meaning and how to modify its behavior.
The description of fair-share scheduling is difficult to comprehend.

docs: Clarify weighted fair-share scheduling policy

---

docs/release-notes/describe-model.rst
harness/determined/cli/model.py

`model_by_name` was calling `GET /models?name=xyz` but `name=xyz` uses `ILIKE '%xyz%'` under the hood, so if you had two models, say `xyz` and `xyz2`, `det model describe` would explode upon finding two models.
There is a separate debate about whether `GET /models?name=xyz` should be calling `ILIKE '%...%'`. I don't believe it should, really, but I figured we can debate that separate of this bug fix.
report: https://hpe-aiatscale.slack.com/archives/CSG3W08JY/p1695042418994789

fix(cli): det model describe should call GET /model not GET /models

---

docs/_templates/toggle-primary-sidebar.html

Dev guide is too hard to scroll down to. This is an interim solution while we work on a collapsible sidenav.

docs: Add another top nav link

---

bindings/generate_bindings_py.py
bindings/generate_bindings_ts.py

feat: Allow passing in swagger json as an argument
This is to support external openapi 2.0 json files for generating python and ts clients.

feat: Allow passing in swagger json as an argument

---

webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx

Avoids an issue where if someone reloads a single-trial experiment page on the Logs tab, the Antd Tabs component will "slide" to display this last tab. If this occurs while the page loads, it assumes the tab section has 0 width and hides other tabs to the left (note three dots selection menu at right). This is only fixed when someone clicks a tab and triggers re-rendering:
The proposed solution is two pieces of CSS to overwrite Antd:
- `transform: translate(0)` to avoid sliding the tabs left
- `box-shadow: none` to avoid applying a semitransparent shadow to the left edge, indicating tabs hidden to the left
We don't hide the three-dots menu since it's unobtrusive and useful on narrow screens
Visit a single-trial experiment such as `/det/experiments/1651/logs`
Refresh until you can see a …

fix: avoid hiding tabs in single trial experiment [WEB-1651]

---

docs/interfaces/notebooks.rst
docs/setup-cluster/deploy-cluster/on-prem/deploy.rst

`--auto-bind-mount` support has been removed from det deploy local. (See: [release notes])(https://docs.determined.ai/latest/release-notes.html#version-0-17-0
).
This is a draft PR to analyze references to `--auto-bind-mount` in the documentation and remove or replace such references.
#2932 
- [Jupyter Notebooks](https://docs.determined.ai/latest/interfaces/notebooks.html#save-and-restore-notebook-state)
- [Install Determined using `det deploy`](https://docs.determined.ai/latest/setup-cluster/deploy-cluster/on-prem/deploy.html#install-using-deploy)

Remove references to --auto-bind-mount

---

master/internal/rm/actorrm/actor_resource_manager.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/kubernetesrm/resource_pool.go

We saw a NPE when the a scheduler group was removed before one of its allocations, since there is periodically code that wants the group for an allocation. Allocations should never outlive groups in the scheduler; the messages are sent in the right order but because the group message goes through from group actor->RP and the allocation message goes from allocation->RM->RP, if the RM is backed up the removals can happen out of order.
Since groups already wait on allocation exits, the fix just makes sure allocations wait for RMs to confirm receipt of the ResourcesReleased message before exiting.
Corresponding dispatcher RM PR required. Better NPE handling in the scheduler coming after that. Also could use a PR to handle if the RP crashes and never sends the ResourcesReleased ack, so …

fix(allocation): allocation lifetimes should contain resource lifetimes

---

master/internal/api_checkpoint.go
master/internal/api_command.go
master/internal/api_experiment.go
master/internal/experiment.go
master/internal/user/external_users.go
master/internal/user/postgres_agentusergroup.go
master/internal/user/postgres_users.go
master/pkg/model/agent_user_group.go

Related to  https://github.com/determined-ai/determined/pull/7769, this bunifies & tidies up `master/internal/user/postgres_agentusergroup.go` and moves the methods in `master/internal/user/external_users.go` to `postgres_users.go`
Create a user & experiment & test getting its agent user group.
Add tests postgres_agentusergroup.go as part of https://github.com/determined-ai/determined/pull/7875
For EE: circle CI checks (https://app.circleci.com/pipelines/github/determined-ai/determined-ee?branch=postgres-agent-user-groups), test branch (https://github.com/determined-ai/determined-ee/tree/postgres-agent-user-groups)
DET-9841

chore: bunify & tidy up internal/user

---

docs/_static/version-switcher/versions.json

The longterm-fix is still ticked, but hasn't happened yet.

docs: quick fix for version dropdown

---

webui/react/src/components/UserSettings.test.tsx
webui/react/src/components/UserSettings.tsx
webui/react/src/stores/userSettings.tsx
webui/react/src/stores/users.tsx

This mitigates an issue that appeaers on installations that have rbac enabled. When updating settings, it's sometimes possible that a race condition happens between the update request and the polled settings request. becaue we optimistically update the local state, this can cause the app to appear like it's not accepting the changes, only for it to eventually settle after the next polling call.
We fix this issue by adding a grace period to the beginning of the polling method. we keep track of all in-flight update calls and wait for up to 500ms for those to complete before making the `getUserSetting` call. If there are no updates in flight, the poll continues without waiting.
workspace filters should be preserved on servers with rbac enabled.
See [Release …

fix: mitigate user settings race conditions

---

master/internal/api_experiment.go

The API is returning -1x the searcher metric values when config has `smaller_is_better: False`
This line was introduced in #7518 for sorting 'better' or 'worse' values of the metric, but we handle sorting in other parts of code
With the original code, sort experiments by searcher metric value. Find a negative value
With the updated code, typically there will be no more negative values

fix: return searcher_metric_value as-is [WEB-1707]

---

docs/reference/deploy/config/master-config-reference.rst
docs/release-notes/max-slots-per-pod-per-rp.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/internal/config/config.go
master/internal/config/config_test.go
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go
master/pkg/model/task_container_defaults.go

Put ```max_slots_per_pod``` into ```task_container_defaults```. Also mirror ```task_container_defaults``` config with rp config. 
Unit test config stuff
Run a cluster with 2 GPUs on a single node.
Throw this in Helm values.
```
resourcePools:
- pool_name: default
task_container_defaults:
kubernetes:
max_slots_per_pod: 2
- pool_name: second
```
run with global ```maxSlotsPerPod = 1``` (just by setting the helm value)
Spot check helm is set right
```
det -u admin master config | grep max_slots
max_slots_per_pod: 1
max_slots_per_pod: 2
max_slots_per_pod: 1
```
Run
```
det e create examples/tutorials/mnist_pytorch/const.yaml examples/tutorials/mnist_pytorch/ --config="resources.slots_per_trial=2" --config="resources.resource_pool=default" -f
```
```kubectl get pods``` should show one pod
Run …

chore: max_slots_per_pod can be per resource pool [DET-9771]

---

harness/determined/layers/_workload_sequencer.py
harness/determined/pytorch/_pytorch_trial.py
harness/tests/experiment/pytorch/test_pytorch_trial.py

In an upcoming feature https://github.com/determined-ai/determined/pull/7764, we have the ability to change experiment config then try rerunning an experiment.
The import aspect for this is we can resume from a checkpoint with a steps_completed larger or equal to our searcher's max length. Current trial code does not handle this case well. Pytorch trial trains for another max length, and other trials seem to error.
Pytorch trial changes covered by unit test
I don't see an obvious way to test `_workload_sequencer` changes. I manually tested using the in progress single experiment continue on running `fashion_mnist_tf_keras_const` and running where steps_completed would be equal to searcher's max length. You might be able to do this with some db surgery and pause and activating the …

chore: handle case where steps completed is more than max length

---

master/Makefile

`mockery` output during `make check` is way too verbose. We don't need a bunch of info-level noise.
Instead, now looks like this:
This should cause no behavior changes

chore: less verbose mockery output

---

e2e_tests/tests/command/test_shell.py

We are getting spurious failures of this test and it provide no info when it fails.  On failure it also hangs until the shell times out since the shell is still executing and therefore
doesn't close the stream we are reading.   Add an exit to force
an EOF so the test fails quickly on failure.
On failure the error will now include the stdout read to help with triage:
```
>               pytest.fail(f"Did not find expected input {det.__version__} in shell stdout." + lines + "\n")
shell (id: 02060eba-4de3-4739-8257-f9d7a4e5cfef) is ready.                      OUTPUT:
E               OUTPUT:jerryharrow@jerryharrow-dev-box:~$ COLUMNS=80 det --version
E               OUTPUT:det 0.25.2-dev0
E               OUTPUT:jerryharrow@jerryharrow-dev-box:~$ exit
E               OUTPUT:logout
E …
```

chore: Improve failure diagnostics in shell test [FE-216]

---

webui/react/src/components/kit/LogViewer/LogViewer.tsx
webui/react/src/components/kit/internal/useGetCharMeasureInContainer.ts
webui/react/src/components/kit/internal/useResize.ts

Bug is that on low-to-mid width windows, TaskLogs puts unnecessary vertical space between log messages.
Both TaskLogs and TrialLogs use the LogViewer component, but TaskLogs inserts more lines because `useGetCharMeasureInContainer` estimates width-per-character to be 50% wider. After some tests, this could be a timing issue because we measure the width of a one-character div while loading the page, then delete the div.
~My proposal is to keep the div, with `visibility: hidden`, and have it as a dependency to the width. This gets called more times, and catches the correct width-per-character.~
New version uses the `visibility: hidden` div and deletes it after, but in connection with a resize event handler.
- With latest-main backend, visit …

fix: Change measure of text lines in log containers [WEB-1664]

---

docs/integrations/prometheus/prometheus.rst

adds documentation of how to authenticate prometheus for use with determined.
goes with: https://github.com/determined-ai/works-with-determined/pull/24

docs: document prometheus auth

---

docs/integrations/pachyderm/pachyderm.rst
docs/setup-cluster/deploy-cluster/k8s/custom-pod-specs.rst

Update custom pod specs page to include the new capability (0.23.4):
Kubernetes: Users may now populate all `securityContext` fields within the pod spec of the `determined-container` container except for `RunAsUser` and `RunAsGroup`. For those fields, use `det user link-with-agent-user` instead.

docs: Update custom pod specs page

---

docs/release-notes/master-logs.rst
master/internal/core.go
master/internal/grpcutil/api.go

We would log API panics to stdout/stderr of master but not ```det master logs```.
Edit GetExperiments to add a ```panic("test")```, run ```det e``` and then in ```det master logs``` we should see the panic stack trace.

chore: put grpc panics and other logs into 'master logs'

---

webui/react/src/pages/Dashboard.tsx

Small change - only on the Dashboard, remove this action menu from ProjectCards, using `hideActionMenu` prop introduced in #7870
After dashboard has fully loaded, the three dots menu does not appear when hovering over a ProjectCard

fix: Hide action menu on dashboard project cards [WEB-1667]

---

webui/react/src/components/kit/CodeEditor.tsx

This fixes an issue where files more than one folder deep were not viewable in the experiment code view. The code to find which file node in the file list is active assumed that the node keys would only contain the last path segment (i.e: a file at `foo/bar/baz` would have a key of `baz`) or fully match the selected file path. For files 1 folder deep, the search would match the folder, then fully match the file, but because deeper files needed to match more of the partial path, it would fail.
This is fixed by instead matching the current path with all previously matched segments with the node key. Because the only consumer of CodeEditor that this effects is ExperimentCodeViewer, this should be fine.
- submit an experiment with files that are more than one level deep
- in the code viewer, …

fix: show deep files in experiment code viewer

---

.circleci/config.yml

In ef59afa4b2fc, a pre-splitting selection step was added to work around an unfortunate behavior of CircleCI's splitting tool when passed a file with no tests to be run. The code was later amended to try to handle slightly more complex marks, and a whole other thing was done on top of that in EE, but really we should just use pytest itself to print out exactly the right set of files without reimplementing any of its logic.
This change also adds code to defend against something going wrong and causing no files to be selected, which would cause all tests to be run in every split. (That's what happened in EE that led to this change getting done.)

ci: more precisely select files for splitting in E2E tests

---

harness/determined/pytorch/_pytorch_trial.py
harness/tests/experiment/pytorch/test_pytorch_trial.py

fix a bug where searcher progress was not being reported according to reporting_period/scheduling_unit
submit a pytorch experiment, verify that searcher progress is reported per scheduling_unit in the expconf. in the web UI, the progress bar should update incrementally as training progresses.

fix: report searcher progress according to reporting period [MLG-988] 

---

master/internal/api_user.go

This fixes an issue where adding a sort parameter in the `GetUsers` endpoint would result in the endpoint throwing a 500 error. This is because the order expression was invalid due to how bun escapes the input to `Order`. We instead clean up the logic by always ordering by the sort column and only adding the id sort if the other sort didn't add it already.
hitting `/api/v1/users` with sort parameters should work.
No ticket

fix: fix sorting in GetUsers endpoint

---

docs/release-notes/shell-open-bugfix.rst
e2e_tests/tests/command/test_shell.py
harness/determined/cli/notebook.py
harness/determined/cli/shell.py
harness/determined/cli/tensorboard.py
master/internal/rm/resource_manager_iface.go

"det notebook|shell|tensorboard open" doesn't error when task not ready and instead waits for the task to be ready.
For notebooks / tensorboards we let the UI be the "waiting" page. For shells we wait in the CLI.
Open a queued notebook / tensorboard with
```
det notebook|tensorboard open ID
```
and you should get taken to the ui with a queued tag.
Open a killed notebook / tensorboard / shell with and you should get
```
det notebook|tensorboard|shell open ID
Notebook / tensorboard / task has ended 
```
Opening a queued shell should wait in CLI
```
det shell start --detach
det shell open
```
Notebooks and tensorboards technically do this but the proxy code handles this in a way that is more user friendly than erroring if it is not ready.
See [Release …

feat: "det notebook|shell|tensorboard open" doesn't error when task not ready

---

harness/determined/core/_checkpoint.py
harness/tests/storage/util.py

Using a new image on the Houston server I noticed that uploading sharded checkpoints fails due to random ordering of files during conflict resolution. In a nutshell, each rank was able to process files in different order and md5 hashes would not match, leading to an error (no wonder). 
It's clear to me that it is a bug in the code, however, I don't understand why the same code is failing consistently with the new image and works equally consistently with either the current det image or one of the older example images. My guess is Pytorch 3.10? Also, I could not reproduce this failure on AWS (with any of the images).
Test on Houston server.
Use `hf_trainer_api\hf_language_modeling` with  `deepspeed.yaml` config and with the following images:
* open `deepspeed.py` and change …

fix: sort files for conflict resolution in sharded checkpoints

---

master/pkg/model/user.go
master/pkg/model/user_test.go

Fix a nil ptr exception for users who haven't logged in.
Unit test
plus rbac test passes here
https://app.circleci.com/pipelines/github/determined-ai/determined-ee/9485/workflows/5e9154ff-a75e-48d2-8479-94762e6b9eae

fix: nil ptr for Proto() on users who haven't logged in

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpHeatMaps.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.module.scss
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.tsx

Avoid truncating hyperparameter names on the scatter plot tabs (scatter plot and heat map)
This is an older ticket and Heat Map titles have not been truncated since #3474
For Scatter Plot tab, I doubled the length of a metric name before it is truncated
On both tabs, we want to avoid long titles going over the edge of the chart without wrapping, so I added `word-break: break-all`
Titles appear correctly on `/det/experiments/1757/visualization/hp-scatter-plots`
You can also use web inspector to increase length of a parameter in the title, leads to a line break

fix: Longer titles on HParam scatter plots [WEB-373]

---

harness/determined/cli/workspace.py

PR #7584 relied on argparse defaults to populate parameters. This worked for all the parameters but `offset`, where the default was `None`, and index math was done assuming it was 0.

fix: list-projects failed when no offset was passed

---

e2e_tests/tests/cluster/test_job_queue.py
e2e_tests/tests/command/test_shell.py

Fixes test flake 
https://app.circleci.com/pipelines/github/determined-ai/determined/45745/workflows/2915ba9a-92bf-413d-b774-7b2940b3dfb1/jobs/1894469/parallel-runs/3
test_job_queue_adjust_weight was letting an experiment run after the test was completed causing shells take longer to start up.
CI passes

test: fix shell open test flake

---

webui/react/src/components/kit/NoteCards.tsx
webui/react/src/pages/ProjectNotes.tsx

Ticket is from a long time ago, but worth fixing
In the Project Notes section, we should disable UI for adding/deleting notes when the user has only Viewer permission. I had thought to use `canModifyProjects` but this affected OSS users on others' projects, so I chose `canCreateExperiment`
Disabling the project should hide the [+ New Note] button
The state is the same as archiving a project, so you can mimic this by temporarily archiving a project and browsing notes. Archiving should remove options to add and delete notes.

fix: Note UI respects project permissions [WEB-637]

---

docs/release-notes/k8s-affininty-bug-fix.rst
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go

We broke custom affinities with  https://github.com/determined-ai/determined/pull/7779
We append the don't schedule onto disabled nodes affinity on this
```
// A node selector represents the union of the results of one or more label queries
// over a set of nodes; that is, it represents the OR of the selectors represented
// by the node selector terms.
type NodeSelector struct {
//Required. A list of node selector terms. The terms are ORed.
NodeSelectorTerms []NodeSelectorTerm `json:"nodeSelectorTerms" protobuf:"bytes,1,rep,name=nodeSelectorTerms"`
}
```
This will have broken peoples affinity since it will ORed against the agent being enabled or not which will mostly be true. Fix is to append it a layer down in the requirement arrays here
```
// A null or empty node selector term matches …
```

fix: k8s custom pod spec affinity would get ignored

---

harness/determined/deploy/aws/templates/govcloud.yaml

Agent AMIs got out of sync and haven't been updated for a year in the template.
Raised in https://github.com/determined-ai/determined/issues/7977#issuecomment-1732526543
N/A

fix: govcloud agent AMIs are out of sync with bumpenvs [MLG-986]

---

harness/determined/common/experimental/workspace.py
harness/tests/determined/common/experimental/test_workspace.py

BREAKING CHANGE: calls to `workspace.Workspace.list_pools` return objects rather than strings.
ResourcePool objects are dumb because they're not backed by a table like other resources. The only attribute a ResourcePool can have is its name.
Nevertheless, `list_pools` should return actual, typed ResourcePool objects rather than their names for conformity with the rest of the SDK.
The following now returns ResourcePool objects rather than strings:
```python
client.login(<details>)
ws = client.get_workspace(<workspace>)
ws.list_pools()
```

fix: Return ResourcePools rather than names

---

master/internal/core.go
master/internal/db/database.go
master/internal/db/postgres_cluster.go
master/internal/db/postgres_cluster_intg_test.go
master/internal/mocks/db.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/pkg/config/telemetry.go

https://hpe-aiatscale.atlassian.net/browse/SAAS-1374
Allow for passing of `clusterID` in master config. 
If a cluster already has a `clusterID` it is ignored.

chore: allow passing clusterID in master config

---

master/internal/user/postgres_users.go

Implementing the suggested follow-up from #7665 -  when an agent user group is modified, it should update `users.modified_at`.
A query is added to `addAgentUserGroup`, where User.Update will affect it. The other relevant area of the code, `removeAgentUserGroup`, is called only where it is immediately followed by `addAgentUserGroup`.
As an admin user, go to `/det/admin/user-management`
To the right of a user row, click the three-dots menu and select Configure Agent
Give the user agent and group a unique name for testing, and submit
The `modified_at` column value the user should update within a few seconds

feat: updating agent user group affects users.modified_at [WEB-1594]

---

webui/react/src/components/ExperimentCreateModal.tsx

Patches the Fork Experiment / Continue Trial modal, so changes to the full config YAML are POSTed to the server, and not resending the original config
This bug may have come about in #7688 and #7849
- Fork an experiment, editing the full config YAML to change the description. Verify this in the created experiment
- Fork an experiment, editing `resources.slots_per_trial` in the YAML

fix: pass final forked config to server for new experiment

---

harness/determined/core/_train.py

We've got a [user complaint](https://github.com/determined-ai/determined/issues/7966) that core api report_training_metrics are no longer printed in the trial logs.
These were removed in https://github.com/determined-ai/determined/pull/7407. let's bring them back.
Also simplify `DummyTrainContext` because it inherits from `TrainContext`. 
Run any trial and ensure it has `determined.core: report_training_metrics(` log lines.

fix: bring back logging for `core.train.report_*` calls.

---

master/cmd/determined-master/root.go
master/internal/core.go
master/test/testutils/fixtures.go

chore(tests): fix data races in grpclog init during integrations

---

master/Makefile
master/internal/db/postgres_rp_workspace_bindings.go
master/internal/db/postgres_trial_intg_test.go

There is a race in the Bun library, already tracked by https://github.com/uptrace/bun/issues/810. This works around it so we can turn the race detector on.
Is a test fix.

chore(tests): workaround data races in uptrace/bun

---

harness/determined/common/api/_util.py

Fix an issue where terminated shells would give a verbose error message like
```
shell (id: fcace6b5-5ea4-4cd3-a390-1a12500a600f) is ready.
disconnecting websocket
Exception in thread Thread-2:
Traceback (most recent call last):
File "/Users/garrett/miniforge3/envs/det/lib/python3.9/threading.py", line 980, in _bootstrap_inner
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
To reconnect, run: det shell open fcace6b5-5ea4-4cd3-a390-1a12500a600f
```
Start and kill a shell then try to open it
We should expect the message to be this
```
det shell open $ID
CLI version 0.26.1-dev0 is less than master version 0.26.1-rc0. Consider upgrading the CLI.
Waiting stopped: task has been terminated.                                      
task has been …
```

fix: shell open gives unfriendly message on terminated

---

proto/pkg/apiv1/api.pb.go
proto/pkg/apiv1/api.pb.gw.go
proto/src/determined/api/v1/api.proto

Calls to `PATCH /api/v1/users/assignments`, added in #7971 , are failing because it was defined in the proto after `/api/v1/users/{user_id}`
Explains error on latest-main: `type mismatch, parameter: user_id, error: strconv.ParseInt: parsing \"assignments\": invalid syntax`
URL is not conflicted by any other definitions in api.proto

fix: order of API paths in proto for AssignMultipleGroups

---

webui/react/src/components/ExperimentCreateModal.tsx

As discussed during release party, editing experiment YAML config during forking gets overwritten by the Name field
This change makes that field, and the YAML name field, unified and applied to the new experiment.
- Find a simple experiment and select the Fork button. Rename the experiment while forking it. Name passes to new experiment
- Open the experiment fork modal, and rename the experiment in Simple Mode. Change to Advanced Mode and confirm that the YAML name field was changed by your renaming. Give the experiment a new name, then toggle back to Simple Mode to see the change is copied over to the form
- Return to Advanced Mode and set the name again. Complete forking the experiment, and confirm name passes to new experiment.
See [Release …

fix: Experiment name settable in fork config

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/templates/master-deployment.yaml

We want data, especially credentials, in master-config.yaml in the helm chart to be encrypted. We can do this by changing it from a ConfigMap to a Secret
Manual Testing with local k8s cluster
DET-9850

chore: change master config to k8s secret

---

webui/react/src/components/kit/Select.tsx

This adds a prop for selects which attaches the menu dropdown inline for cases where the select is in a context that scrolls independent of the body (for example, in larger modals)
no testing needed
[WEB-1670]
[WEB-1670]: https://hpe-aiatscale.atlassian.net/browse/WEB-1670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: allow attaching select dropdown to select container

---

webui/react/src/pages/F_ExpList/CompareMetrics.tsx

On the ExperimentList, when comparing metrics between experiments, the metrics are being labeled "unknown.ExperimentName"
We send `metricType: undefined` but this gets replaced by 'unknown' in the code: `s.metricType ?? 'unknown'`
Instead we should send an empty string.
Related to: #7727 #7809 
On `/det/projects/107/experiments`, check multiple experiments and open the Compare tab

fix: Metric type is blank in comparison chart

---

master/static/migrations/20231006105547_update-modified-at-for-certain-columns-on-users-table.tx.up.sql

fix for https://github.com/determined-ai/release-party-issues/issues/786#issuecomment-1749503941
When `last_auth_at` is updated, trigger should ignore the change
- Check if `modified_at` column is updated only when one or more of `password_hash`, `admin`, `active`, `display_name`, `remote` column(s) are changed. 

fix: ignore `last_auth_at` to update `modified_at` on users table

---

webui/react/src/components/kit/internal/UPlot/SyncProvider.tsx

This is based on a community-reported issue.
When we have a mix of experiments with some shared continuous metrics, and some single-point metrics at a much higher batch number,
This gives us a visible issue where the x-axis does not expand to contain the single-point metrics. The x-axis range is being reset between charts between `"batches"` and `undefined`.
The proposed change avoids ever setting `this.axis` to undefined, or `resetAxis` to true based on an undefined value.
With latest-main as the backend (i.e. `make live`)
- On `/det/projects/1/experiments`, open the compare view and select experiment "wryyyyy" (id = 3763)
- Confirm chart x-axis has up to 200,000 batches; scroll up and down to see single-point and multi-point charts
- Select another experiment (I'm using id=4423, a …

fix: Single point chart avoids issue with axis ranges

---

docs/redirects.py

There was a bug in rename_into where when renaming a directory called a/b into a directory c/, we would redirect to c/a/b instead of c/b.

docs: redirects.py moves subdirectories properly

---

harness/determined/common/experimental/trial.py

This renaming makes `logs` more consistent with the emerging `get_*` / `list_*` / `iter_*` standard.

chore: Deprecate Trial.logs in favor of Trial.iter_logs

---

harness/determined/cli/proxy.py
harness/determined/cli/shell.py
harness/determined/cli/tunnel.py

fix: DET_CERT_MASTER_FILE=noverify det shell open

---

master/internal/api_resourcepool.go

`/resource-pools` response can be arbitrarily ordered, so the same list of resource pools can trigger unnecessary re-render. 
An alternative way to fix this issue is to order resource pool response in the front end. 
- Go to a multi-trial experiment result page, checkpoints tab. Example: [Determined](https://gcloud.determined.ai/det/experiments/2676/trials) 
- Try to register a checkpoint
- Wait like 5-20 seconds, modal will stay there until manually closed.
WEB-1752

fix: Return resource pools with a fixed order to avoid unnecessary re-rendering 

---

e2e_tests/tests/cluster/test_ship_logs.py
master/internal/rm/kubernetesrm/spec.go
master/pkg/tasks/task.go
master/static/srv/ship_logs.py

Line endings were being dropped whenever the rank or level regexes matched.  Fix includes a regression test.
Also k8s (and slurm, though that fix is on the EE side) was not using ship_logs.py at all, as apparently the only place ToDockerSpec was being used is in the agent resource manager.

fix: hotfixes for ship_logs.py

---

agent/.goreleaser.yml

FE-224. Allow the default /etc/determined/agent.yaml read access.
The released default agent.yaml file does not allow non-root user read access. determined-agent command failed to start:
-rw-------   1 root    root      592 Sep 11 18:49 agent.yaml
```
determined-agent --master-host=localhost --master-port=8080 --container-runtime  singularity
FATA[2023-09-21T14:34:45Z] fatal error running Determined agent          error="error reading configuration file: open /etc/determined/agent.yaml: permission denied"
```

chore: make agent.yaml readable by default

---

docs/reference/deploy/config/agent-config-reference.rst
docs/reference/deploy/config/master-config-reference.rst
docs/setup-cluster/deploy-cluster/k8s/install-on-kubernetes.rst
docs/setup-cluster/deploy-cluster/on-prem/options/docker.rst
docs/setup-cluster/deploy-cluster/on-prem/options/wsl.rst
docs/setup-cluster/security/tls.rst

Remove references to fluent bit as log shipper.
Fluent bit is no longer used for log shipping:
https://docs.determined.ai/latest/release-notes.html#version-0-25-1

docs: Remove ref to fluent bit

---

e2e_tests/tests/cluster/test_ship_logs.py
harness/determined/exec/prep_container.py
master/static/srv/ship_logs.py

A while ago, the first HTTP call we made to the master was in prep_container.py.  There, we emitted a special, super-detailed message to help users with broken container settings or proxy settings or certificate settings to help sysadmins debug their clusters.
That message now belongs in ship_logs.py.  Also, we do a special round-trip to the master just to check that connection, before we even start a child process.

fix: move couldn't-connect-to-master message into ship_logs.py

---

docs/reference/python-sdk.rst
harness/determined/common/experimental/determined.py
harness/determined/common/experimental/metrics.py
harness/determined/common/experimental/trial.py

This PR:
* removes generated documentation for deprecated TrainingMetrics and ValidationMetrics objects and methods
* adds generated documentation for their replacement TrialMetrics
* better documents the attributes within TrialMetrics
* adds deprecation warnings for methods docstrings claim are deprecated
[MLG-1030]
Check [SDK docs on main](http://latest-main.determined.ai:8080/docs/reference/python-sdk.html). There should be a description of TrialMetrics and its attributes and no description of ValidationMetrics or TrainingMetrics. It should include `stream_trials_metrics` from `client` and `Trial.stream_metrics`, and should not include either `stream_trials_training_metrics` or `stream_trials_validation_metrics` from `client` and should not include `Trial.stream_validation_metrics` or …

chore: update metrics documentation

---

.circleci/config.yml
webui/react/package.json

As suggested, put `PLAYWRIGHT_BROWSERS_PATH=0` in the CI config YAML instead of in package.json
Tests run successfully
<!---
Use this section of your description to add context to the PR. Could be for
particularly tricky bits of code that could use extra scrutiny, historical
context 

fix: Move setting of playwright browsers path

---

docs/reference/python-sdk.rst

rstfmt complained that a line break had too many "="s. This shortens it into compliance.

docs: fix python-sdk reference syntax

---

.circleci/config.yml
e2e_tests/tests/experiment/test_tf_keras.py

Open PR for anything I overlooked with Examples Pruning. So far:
1. `test-e2e-gke-parallel-tfonly` is being removed since it's failing due to having no tests to run.
CI is green.

chore: Post pruning hotfixes

---

webui/react/src/App.tsx

Fix the issue that the theme selection is not persistent. 
As soon as the page refreshes or reloads, it defaults to system settings.
This is because `SettingsProvider` and `UIProvider` were not properly wrapped.
Change system mode to light, then at the WebUI, switch the mode to Dark, refresh page, the theme should persist.
Change system mode to dark, then at the WebUI, switch the mode to Light, refresh page, the theme should persist.
Start server with RBAC, at the login page, HPE logo should be visible.
WEB-1756

fix: Theme dropped after page refreshing

---

master/internal/db/postgres_experiments.go
master/internal/db/postgres_experiments_intg_test.go
master/static/migrations/20231011104015_add-exp-trials-on-del-casc.tx.down.sql
master/static/migrations/20231011104015_add-exp-trials-on-del-casc.tx.up.sql

add `ON DELETE CASCADE` constraint to tables involved in experiment deletion.
Now, experiment deletion can be accomplished with one database call since the delete cascade will clean up child tables that contain the IDs of removed experiments or trials spawned from such experiments. 
The delete cascade was added to the following tables:
- trials (trials)
- checkpoints (checkpoints_v2)
- training metrics (raw_steps)
- validation metrics (raw_validations)
- experiment snapshots (experiment_snapshots)
addresses the following JIRA ticket: [DET-9463]
Up migration:
- performed integration testing on `DeleteExperiments()` function by creating 4 experiments each containing trials, checkpoints, and metrics. Removed experiments from the database and checked that corresponding rows for all dependent …

refactor: add delete cascade to tables affected by experiment deletion

---

e2e_tests/tests/experiment/test_core.py

We reinstated one of the pruned examples (`tutorials/core_api`)
This example had some e2e_tests. Reinstating those to make sure this example stays tested.
CI Passes
Check out the new examples repo! https://github.com/determined-ai/determined-examples
Well, maybe after its first ever PR hits....

chore: reinstate core_api example e2e tests

---

docs/release-notes/core-v2-tensorboard.rst
e2e_tests/tests/experiment/test_core.py
e2e_tests/tests/fixtures/core_api/pytorch_profiler_sync.py
e2e_tests/tests/fixtures/core_api/pytorch_profiler_sync.yaml
harness/determined/core/_context.py
harness/determined/exec/gc_checkpoints.py
harness/determined/exec/tensorboard.py
harness/determined/experimental/core_v2/_core_context_v2.py
harness/determined/tensorboard/base.py
harness/determined/tensorboard/build.py

- When tensorboard manager is in auto mode, automatically do the sync on closure. This should sync files written after the last metrics payload, e.g. native pytorch profiler traces.
- Core API v2 did not properly write tensorboard files while in managed mode.
- Run a managed core api experiment which uses pytorch profiling *for the entire duration of the experiment*, and make sure the trace is saved and can be accessed in the tensorboard. See tests for an example.
- Run Core API v2 experiment in a managed mode (i.e. as an experiment), and make sure tensorboard captures the metrics.

fix: tensorboard sync for profiler data, Core API v2 managed mode [MLG-1063]

---

docs/reference/training/experiment-config-reference.rst
docs/tutorials/pytorch-mnist-tutorial.rst

Since PyTorchTrainer (0.21.0), `PyTorchTrial` no longer requires `records_per_epoch` when specifying training lengths in epochs. This PR updates the user-facing docs to reflect this.

docs: update experiment config reference for records_per_epoch in PyTorchTrial [MLG-557]

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/resource_pool.go

Change pods.go from an actor to a plain Go struct with locks and make all calls synchronous. The change is simple; most of the work is in making sure this causes no bugs like deadlocks or race conditions, and no performance issues due to lock contention.
DET-9901

chore(actors): refactor pods.go without actors [DET-9901]

---

webui/react/src/pages/TrialDetails/Profiles/Charts/SystemMetricChart.tsx
webui/react/src/pages/TrialDetails/Profiles/utils.ts

In trial's Profiler tab, charts with Bytes values should be run through our `humanReadableBytes` function, so we see "1.0 GB" instead of "1.00 e+10" Bytes
A separate time axis issue is connected to a backend / query issue we saw in July
Open an experiment with profiler tab (I use `/det/experiments/1788/profiler`). Scroll down to the System Metrics chart.
Use the dropdown to select each metric. If the axis is "Bytes" or "bytes/s", the human-readable number is displayed:
Axis labels such as "Gigabytes" or "gigabit/s" are not modified.

fix: Display byte axis values using humanReadableBytes [DET-9906]

---

harness/determined/cli/workspace.py

We've recently have an issue where an EE test fails at `det w describe {workspace_name}`. The root issue is that it calls other CLI functions (`list_workspace_projects`) with its original `args`. This throws an error when `list_workspace_projects` tries to access its own args, `args.offset` and `args.limit` 
The fix catches the error and uses default values.
Run `det w list --offset 10 --limit 1` - it returns one workspace
Run `det w describe WorkspaceName`
Run `det -m latest-main.determined.ai:8080 w list` - it returns all workspaces (it is not limited)

fix: CLI uses default if pagination not included in args [DET-9908]

---

docs/_extensions/sort_by_weight.py
docs/conf.py

Added custom extension that enables contributors to add a `:weight:` field to an article and have the articles in a directory be sorted from lowest to highest number. 

docs: sort articles by weight custom extension

---

master/static/migrations/20231019155909_new-trigger-by-username.tx.down.sql
master/static/migrations/20231019155909_new-trigger-by-username.tx.up.sql

Responding to the error `ERROR:  control reached end of trigger procedure without RETURN` when creating new users in UI and in e2e testing (oddly, this is an issue when running e2e tests locally but not on CI)
This modifies the `users.modified_at` database trigger from #8091 and #8093 to run on INSERTs and UPDATEs
As admin, visit `/det/admin/user-management`
Sort by Modified Time so you see the most recent users
Create a new user. They should appear as the first row with "Just Now" in the Modified Time column
Update an older user with a new display name or other detail. This should move up to the first row with "Just Now" in the modified column

fix: Trigger function updates new user modified_at without error

---

webui/react/src/stores/userSettings.tsx

This fixes a class of issues that occur when migrating a component from the `useSettings` hook to directly reading from/writing to the settings store. Previously, the settings store would update the underlying state map after each polling request. This causes issues for consumers that have object values in their settings, because those objects would then be replaced with identical objects after the settings poll finished. When passing the object value into a hook dependency, the consumer then updates along with the settings, even though the values don't change. This can cause issues when the hook is responsible for things like loading data, because it can cause extra calls and block user interaction.
We fix this by doing a deep equality check on the settings after merging with the polling …

fix: prevent extra updates when observing settings store

---

webui/react/src/pages/Admin/GroupManagement.tsx
webui/react/src/pages/Admin/RemoveUserFromGroupModal.tsx

[WEB-1739]
In Groups tab
Check if menu item label from “Edit” to “Edit Group”
Check if menu item label from “Delete” to “Delete Group”
Check if menu item color for “Delete Group” to destructive action red
Check if group level column header copy from “Users” to “Members”
Check if using nameplate layout table to be one “User” column that matches the nameplate style formatting of the user column in the “Users” tab table. with alpha sort
Add confirmation alert for “Remove user from group”
> (Optional if easy) Add “Expand/collapse All Groups” + to column header
cannot find easy solution 
[WEB-1739]: https://hpe-aiatscale.atlassian.net/browse/WEB-1739?atlOrigin=eyJpIjoiNWRkNTljNz …

feat: update group table

---

harness/determined/common/experimental/project.py
harness/tests/determined/common/experimental/test_project.py

Project notes have name and contents. There is no uniqueness constraint on name within a project. This gives an awkward interface for removing a note by its name.
Previously, we had logic that optionally took a "contents", so a user could narrow down _which_ note to delete when multiple notes had the name as the note to be removed. But this interface is complicated, and what's the likelihood that a user will event want it. Even more, we hadn't implemented all the if/then casing right with "contents", and this method had a bug as implemented.
This fixes the bug by removing the feature.
Test `remove_note` functionality for when multiple notes of the same name exist. These notes can be added in the web UI or with `Project.add_note`. Ex:
```python …
```

fix: remove 'contents' parameter from remove_notes

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/question.yml
CONTRIBUTING.md
README.md
docs/_templates/article-header-buttons.html
docs/manage/troubleshooting.rst
docs/model-dev-guide/api-guides/apis-howto/deepspeed/advanced.rst
docs/model-dev-guide/debug-models.rst

Fixing broken Slack links in various parts of the repo.

docs: Fix broken Slack links

---

docs/release-notes/deprecate-apex.rst
harness/determined/pytorch/_pytorch_context.py

Notice of deprecation for `apex`.

chore: deprecate `apex` support.

---

harness/determined/cli/dev.py
harness/determined/cli/errors.py
harness/determined/cli/experiment.py
harness/determined/deploy/aws/cli.py

`CliError.e_stack` is not used. whenever `DET_DEBUG=1` is set, the original exception traceback will be printed anyway thanks to python capturing the original exception automatically.

refactor: `CliError` does not need `e_stack` property.

---

master/internal/api_auth.go
master/internal/core.go

- add a middleware that supports optional redirects on auth failures for given routes
- use it to set up this behavior for proxied servers
somewhat similar to what we do with det proxies for tasks https://github.com/determined-ai/determined/blob/63b381a7552ac5bcf54bbe7eb9989c69d65f4ae5/master/internal/api_auth.go#L119-L129
no changes are expected when the internal proxied_servers config is not used. 
when a proxied server (aka a sidecar) is used the unauthenticated requests to those paths are expected to be redirected to the signin ui

chore: support redirect on auth failure for echo routes

---

harness/setup.py

There was a breaking change in the ruamel.yaml API, which has the unfortunate effect on our cli of causing commands like `det e config` to emit absolutely no error message, just exit 1 silently.
The fix is too big to squeeze into the release so we will use a pin until the real fix is ready.

fix: pin ruamel.yaml<0.18.0

---

master/internal/api_experiment_intg_test.go
master/internal/api_project_intg_test.go
master/internal/api_tasks.go
master/internal/api_tasks_intg_test.go
master/internal/api_user_intg_test.go
master/internal/api_workspace_intg_test.go

Get tasks had a regression making it not respect RBAC.
Run a task on an RBAC cluster, then on a user with no permission check they can't see any in ```det task ls````

fix: GetTasks doesn't respect rbac [DET-9914]

---

webui/react/src/components/CheckpointModal.tsx
webui/react/src/utils/checkpoint.ts

When an experiment checkpoint was previously deleted, we should disable the "Register Checkpoint" option. We previously partly disabled "Delete Checkpoint"
On `/det/experiments/2727/checkpoints` (or another experiment with a mix of completed and deleted checkpoints):
- On the table of checkpoints, on the right is a three-dots menu. Completed checkpoints have "Register" and "Delete" options; Deleted checkpoints have both options disabled
- Click a flag of a completed checkpoint. The link to Delete and modal-finish button (Register Checkpoint) are enabled
- Click a flag of a deleted checkpoint. The link to Delete is missing and Register Checkpoint is disabled

fix: Dont suggest register / delete a deleted checkpoint [WEB-1736]

---

webui/react/src/ee/SamlAuth.test.ts
webui/react/src/ee/SamlAuth.ts

Previously in #5962 we added `?r=0.123` to our Login page URL to make a clean login page
This was related to some earlier PRs on login and LocalStorage such as #5911
We believe the issue in 3rd-party logins is that `r=0.123` is encoded by our state-preservation code and passed to `relayState`. This PR removes the `r=` parameter and may remove `relayState` entirely if there are no other URL variables.  We include an example of this in the test.
PR testing whether this introduces problems: changes are tested and do not introduce problems
Testing for team with OIDC log in , to see if it fixes their bugs:
- successful SAML log in
- successful OIDC log in
- as admin, create a new non-admin user with no workspaces or permissions
- when logged out, a page such as `/det/workspaces` redirects to …

fix: prevent passing login r= param to relayState

---

harness/determined/launch/deepspeed.py

The deepspeed tests all failed when I ran the `e2e_tests` on `sawmill` to test a ROCM image.  The `sawmill` cluster has a `bard` partition with ROCM GPUs, although there is no `gres` configured for Slurm.
```
tests/nightly/test_distributed.py::test_deepspeed_moe FAILED             [ 90%]
tests/nightly/test_distributed.py::test_deepspeed_zero FAILED            [ 93%]
tests/nightly/test_distributed.py::test_deepspeed_dcgan FAILED           [ 96%]
tests/nightly/test_distributed.py::test_deepspeed_cpu_offloading FAILED  [100%]
```
The root cause of the failure is that, by default, `IFS` is set to a space, a tab, and a newline character, so it is written to the `/determined_local_fs/procs/0/run/determined/workdir/.deepspeed_env` file as:
```
IFS='
'
```
The `.deepspeed_env` file is later …

fix: deepspeed e2e_tests fail when environment variable contains a newline character [FE-256]

---

docs/.redirects/redirects.json
docs/redirects.py

`make docs publish` requires that all previously-published URLs have a redirect, even if that redirect is to something like `_index.html`.  This PR makes sure that this condition will be checked in `redirects.py check` and consequently `make docs check` to catch this error before `redirects.py publish` is attempted.
Also add some redirects for some dropped previously-published urls.
1. Navigate to `determined/docs`
2. Run `python redirects.py check`. There should be no errors.
3. Delete a file, such as `docs/integrations/prometheus/_index.rst`
4. Run `python redirects.py check`. There should be errors for broken redirects AND errors for dropped published urls. 
MLG-1100

docs: check for dropped urls in PRs

---

docs/reference/deploy/master-config-reference.rst
docs/reference/training/experiment-config-reference.rst

- Link to the `bind_mount` docs from exp config had "resource.devices" text for some reason.
- Some internal `bind_mounts` fields were marked as required while in fact they are optional and have a default.
N/A
Sometimes I read the docs.

docs: fix inaccuracies in `bind_mounts` docs.

---

e2e_tests/tests/cluster/test_logging.py
e2e_tests/tests/experiment/experiment.py

We run some CLI list and describe commands after every single experiment, as a "to sanity check that basic CLI commands don't raise errors".  That has made e2e test logs unreadable since the day it was added.  For now, we can keep the tests, but don't dump stdout and stderr into the test logs.  Some day, we should figure out what codepaths are being tested passively, and write proper tests for them.
Also, the test_task_logs has been failing intermittently with a timeout but no error message for weeks.  Instead of using pytest.mark.timeout(), which can't be caught, implement our own timeout logic, and only dump stdout and stderr if the cli crashes.

ci: wart removal

---

docs/index.rst

docs: Fix a 404 error
reported by external user
the link from the landing page to "how it works" produces a 404 error
this is a result of the info architecture changes and the fact that we don't have a test for raw html on our index pages (i.e., if we move/rename files, nothing tells us the index page is broken)
we won't need these tests once we transition away from raw html (i.e., we recently implemented a new css with a custom sphinx extension that allows us to use .. container:: homepage (along with :glob: patterns) see [TECHWR337](https://hpe-aiatscale.atlassian.net/jira/software/projects/TECHWR/boards/41/backlog?selectedIssue=TECHWR-337))

docs: Fix a 404 error

---

master/internal/command/command.go
master/internal/command/command_job_service.go
master/internal/experiment.go
master/internal/experiment_job_service.go
master/internal/job/jobservice/jobservice.go
master/internal/sproto/jobs.go

Restores job queue set resource pool behavior.
DET-9923

chore: restore set resource pool using job service

---

harness/determined/cli/model.py
harness/determined/cli/trial.py

The following dependencies were migrated
model:
* Model.get_models -> list_models
* Model.get_versions -> list_versions
trial:
* Trial.select_checkpoint -> list_checkpoints
For Trial.select_checkpoint, argument validation that was in select_checkpoint has been copied into the function in the CLI that called it (trial::download), validating passed flags as flags rather than parameters in the parent.
The changed CLI methods are:
```
det trial download
det model list
det model list-versions
```
Please try them each out, maybe playing with their flags. No deprecation warning should ever be printed.

fix: migrate CLI from deprecated SDK methods

---

harness/determined/pytorch/dsat/_utils.py

Oops, we forgot to set the "make it work" switch to the "on" position.
For a valid yaml string:
s = "image: {gpu: image:tag}"
This innocent looking code does not work:
yaml.YAML(typ="safe").load(s)
But this code does work:
yaml.YAML(typ="safe", pure=True).load(s)
Setting pure=True cause ruamel.yaml to skip the C implementation, which is apparently not entirely correct.  Why not?  Who knows.
This was exposed by the recent conversion of some
`yaml.dump(config)` calls to `util.yaml_safe_dump(config)` in the e2e experiment utils.

fix: dsat with all yaml formats [MLG-1156]

---

harness/determined/pytorch/_pytorch_trial.py
harness/tests/experiment/pytorch/test_pytorch_trial.py
harness/tests/experiment/pytorch_utils.py

previous change to enable training lengths longer than searcher length introduced bug where test_mode flag will train for max_length instead of just one batch.
run a script using pytorch trainer API (example for mnist):
```
import determined as det
import yaml
import logging
from model_def import MNistTrial
def main():
with open("const.yaml", "r") as file:
exp_conf = yaml.safe_load(file)
hparams = exp_conf["hyperparameters"]
with det.pytorch.init(hparams=hparams, exp_conf=exp_conf) as train_context:
trial = MNistTrial(train_context)
trainer = det.pytorch.Trainer(trial, train_context)
trainer.fit(
max_length=det.pytorch.Epoch(1),
test_mode=True
)
if __name__ == "__main__":
logging.basicConfig(level=logging.INFO, format=det.LOG_FORMAT)
main()
```
verify in stdout that the code trains for 1 …

fix: only train for one batch in PyTorch Trainer test mode

---

helm/charts/determined/values.yaml

- It probably went out of sync due to a concurrent helm chart refactoring and a bumpenvs upgrade.
- Also trim trailing spaces which have appeared in this file.

fix: use proper default cpu env image in the helm chart.

---

.circleci/config.yml

By default, jobs run only on branches, so nothing was happening on tags without this.

ci: update wrapper config to run on tags

---

webui/react/src/stores/userSettings.test.tsx
webui/react/src/stores/userSettings.tsx

this fixes an issue where components that used the settings store would rerender on poll even if the polling function returned identical data. This is slightly different from #8212 -- there, the entire settings object was recreated, causing anything that relied on objects within the settings to refresh. This fixes the issue where each render returned the same object reference in a new Loadable.
covered in unit testing, no manual testing required
WEB-1787

fix: prevent settings store from triggering rerenders on poll

---

master/internal/api_command.go
master/internal/grpcutil/api.go
master/internal/user/service.go

This PR fixes a bug in authentication so that the `det_jwt` cookie will only get set in the Authorization header if external sessions authentication is enabled
On login screen, set cookie `det_jwt=test` and ensure that login still succeeds with default credentials.
MLG-1165

fix: check externalConfig is enabled before setting det_jwt as auth header

---

webui/react/.eslintrc.js
webui/react/src/components/Table/Table.tsx
webui/react/src/hooks/useAsync.ts
webui/react/src/hooks/useLoadable.ts
webui/react/src/pages/Admin/UserManagement.module.scss
webui/react/src/pages/Admin/UserManagement.settings.ts
webui/react/src/pages/Admin/UserManagement.test.tsx
webui/react/src/pages/Admin/UserManagement.tsx
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

This updates the user management table to have more and clearer filter functionality. The name filter is extracted out from the header menu into a search bar above the table, and role and status filters are added as well. There's a refactor of the user management table as well -- we've removed the dependency on `useSettings`, instead reading/writing directly from tue user store. In addition, we no longer read the user data from the user store, instead doing filtering and sorting on the backend.
As there are other places where we have this pattern (read-only remote data is requested only when dependent values change), we introduce a new `useLoadable` hook which handles holding the internal state, throwing out stale updates, and setting up cancelers while also allowing us to use the …

feat: new user management filters

---

harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/deployment_types/base.py

Pre-patch, --dry-run:
1. validates flags
2. checks quotas (unless otherwise suppressed)
3. prints a CF template
This patch removes the 3rd step.
It was easy to confuse the template printed by --dry-run with the parameters that would be actually used when deploying a cluster (https://github.com/determined-ai/determined/issues/7978 for one such bug report).
It's tempting to remove the --dry-run flag entirely. This patch takes the stance that it's helpful to have an option that at least validates flags without doing something that's hard to undo, and so even a restricted --dry-run still has some use.
Run a `det deploy aws up` with `--dry-run` passed.

chore: deployment's --dry-run option doesn't print template

---

webui/react/src/pages/TrialDetails/TrialDetailsMetrics.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

We discussed how the trial's Metrics tab group-by-name feature is coloring lines the same unless the group is specifically named "Validation"
The PR uses training=blue/validation=orange colors, but otherwise uses glasbeyColor
Review charts and tooltip key where there are training/validation metrics with the same name. On gcloud this is `/det/experiments/2736/metrics`
;;; on latest-main use `/det/experiments/4951/metrics`
Review charts and tooltip key where there are metrics from other named groups. On gcloud this is `/det/experiments/2713/trials/40852/metrics`
;;; on latest-main use `/det/experiments/4754/metrics`

fix: Metric group charts have more than one color

---

webui/react/src/components/ProjectCard.module.scss
webui/react/src/components/ProjectCard.tsx
webui/react/src/components/TimeAgo.module.scss
webui/react/src/components/TimeAgo.test.tsx
webui/react/src/components/TimeAgo.tsx

this cleans up the `TimeAgo` css. previously, `TimeAgo` rendered as a div with width set to fit-content in #5419. This was to fix the div stretching to fill its container as a block-level element. Now, the text renders as a span, so the width of the container fits its content naturally. While in there, we remove the classname prop, which was only used in one place in the codebase.
* when viewing a model, hover over the value for the "updated" field. The tooltip should appear in the center of the text.
* when viewing an unarchived project, the "last submitted experiment" field in the lower right corner should not collide with the experiment count field in the lower left corner …

chore: remove fit-content from `TimeAgoc`

---

harness/tests/determined/common/experimental/test_trial.py

example failure [here](https://app.circleci.com/pipelines/github/determined-ai/determined-ee/9996/workflows/0001517d-c2db-40f2-bdcd-a4e174e556c1/jobs/476604), in the EE repo where the 0.23.3 edition of responses wasn't cached for some reason.

ci: mypy fix for responses>=0.24.0

---

harness/determined/deploy/gcp/cli.py

Both `--preemptible` and `--preemption-enabled` cast values with the built-in `bool`, which casts to True any possible value but "0". Even "false" and "False". This is almost certainly not what users expect.
Using `string_to_bool`, "0" is still supported. But now all the strings that should evaluate to False do, too.
ROI on testing this might not be high, but:
Deploy a cluster to GCP with `det deploy gcp up` with different values for `--preemptible` and `--preemption-enabled`.

fix: properly interpret flag values

---

master/internal/trial.go

`handleAllocationExit` has an unspoken invariant that it must further the state of the trial somehow, either by closing it or trying to continue it. This change fixes bugs where this wasn't upheld and make it clearer in the function comment.
edit the code so that one of the modified paths always returns an error and make sure the trial ends up errored, not hung.

fix(experiments): transient errors shouldn't leave trial hung

---

webui/react/src/pages/Admin/GroupManagement.tsx
webui/react/src/pages/Admin/index.tsx

On Safari, the group admin page wasn't showing group names
We researched and found Safari/WebKit uses `width: intrinsic` instead of `fit-content`
After discussion on Slack about this ticket and #8309 , best option is 100% width
We also added parentheses around the number of groups or users
On `/det/admin/user-management`,
With EE backend, group name column appears on Safari without issues
Users and Groups tabs appear with a number in parentheses. (If groups is undefined, the Group parentheses and number do not appear)

fix: Set group name and number columns to handle Safari [DET-9948] [DET-9949]

---

harness/determined/launch/deepspeed.py

The DeepSpeed runner users `readlines` to read the environment variable file and expects an equals sign on each line.  We prevent newlines from being in written environment variables, since this would break that format.  But carriage returns are also considered line  breaks by `readlines` in the default `open` mode and so also break the format (causing the runner to crash) -- so this PR omits them too.
DeepSpeed CI
- [] Changes have been manually QA'd
MLG-1206

fix: prevent carriage return in env from crashing deepspeed launcher

---

docs/release-notes/remote-was-able-to-login.rst
e2e_tests/tests/cluster/test_users.py
master/internal/api_auth.go
master/internal/api_user.go
master/internal/api_user_intg_test.go
master/internal/user/service.go

Users with patched remote values were able to login. This was a bug.
```
det -u admin user create testuser
det -u admin user edit testuser --remote true 
```
Should not be able to login in the webui with testuser
There is a somewhat of a case this PR doesn't hit which is pre this upgrade
if you start with a remote user then patch it to not remote, this user won't be able to login until you change their password. I don't think there is an easy migration path unless we assume all non remote invalid passwords can be set to blank which feels risky.

fix: patched remote users were able to login with password

---

docs/reference/training/experiment-config-reference.rst
harness/tests/test_horovod.py
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/optimizations.json
schemas/test_cases/v0/experiment.yaml

Performance Improvement. Our default Horovod `tensor_fusion_cycle_time` was set to a legacy value of 5ms. 1ms is the new `horovod` default value, so let's match that. 
No Testing Required.
MLG-1117

chore: Update Horovod Cycle Time

---

webui/react/src/constants/states.ts

A remaining state button which says "Scheduled" is replaced with "Running". This affects the Tasks page.
Run a notebook in `/det/tasks`
Cycle through stages including light blue button with "Running" on it
`git grep Scheduled` shows no other labels with "Scheduled"

chore: Job/task displays Running instead of Scheduled [WEB-1615]

---

e2e_tests/tests/cluster/test_checkpoints.py
e2e_tests/tests/cluster/test_priority_scheduler.py
e2e_tests/tests/experiment/test_core.py

Checkpoint GC was taking 15 minutes each time due to a few bugs.
First bug we waited 5x2 minutes for both experiments to finish checkpoint gc after they ran. They didn't run a checkpoint gc since they reported 10 checkpoints and had a 10 checkpoint save amount.
Second bug is we were giving the wrong checkpoint uuids causing only one checkpoint gc to run.
Third bug is running wait_for_checkpoint gc after each other. They should be combined.
CI passes/

test: fix slow delete_checkpoint test

---

webui/react/src/pages/Cluster/ClusterHistoricalUsage.tsx
webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx

After we update the xRange / zoom interactions ( https://github.com/determined-ai/hew/pull/27 ) the LineChart component will be ready to replace the charts on Cluster Historical Usage
On `/det/clusters/historical-usage`
- chart cursors are synced between charts
- click and drag on a chart; zoom is synced between charts
- click the chart legend to show and hide lines on an individual chart
Date range:
- select earlier and later start dates; the chart should update
- select earlier and later end dates; the chart should update
- toggle back and forth between month and day charts; the x-range should change
- on the monthly view, select a month in 2021 or earlier; the x-range should include the set dates even when we have no data in this year
See [Release …

feat: Cluster historical usage charts move to UI Kit LineChart [WEB-1786] [WEB-1764]

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

This adds a header menu item to the experiment list table that hides the column from view. If the column is pinned, the column is unpinned when hidden.
* when visiting the experiment list table, click on a column header. The "hide column" menu item should appear in the header menu.
* after clicking on the "hide column" menu item, the column should not show up in the table
* after clicking on the "hide column" menu item when the column is pinned, the column should not show up in the table, and the number of pinned columns should decrease
WEB-1781

feat: add hide column header menu item to explist

---

e2e_tests/tests/fixtures/mnist_pytorch/profiling.py

fix `test_streaming_observability_metrics_apis` in CI broken from #8292 

chore: fix profiler test in CI

---

master/pkg/model/task.go
master/pkg/model/task_test.go

Our ```allocation.Proto()``` will cause a nil pr exception on in progress tasks since it assumes endTime is not nil.
Update the ```Proto()``` method to match the nilability of the Go struct.
No one uses this endpoint yet so this won't cause many issues.
Unit test

chore: fix nil ptr on allocation.Proto()

---

harness/determined/cli/agent.py
harness/determined/cli/task.py
master/internal/api_tasks.go
master/internal/api_tasks_intg_test.go
master/internal/authz/obfuscate.go

RBAC enabled users with no viewer permissions can now run `det slot list` and `det task list` to see task allocations with all sensitive allocation information obscured. 
`det slot list` now uses the new grpc endpoint to access API tasks during the `GetTasks` request.
To test the CLI display on `det slot list` and `det task list`: 
- Spin up a determined cluster in EE with RBAC enabled. 
- Run `det user login admin` and `det rbac my-permissions` to ensure that `admin` has all necessary permissions to view and create Notebooks, Tensorboards, Shells, and Commands.
- Run `det shell start` 
- Run `exit` to exit out of the determined shell if it opens up in your terminal
- Run `det slot list` and `det task list` to ensure that you can see shell allocation and all of its details while logged in …

fix: NTSC task and slot viewing obscured for RBAC users with no Viewer Permissions

---

.circleci/real_config.yml

Our Go cache was suboptimal not saving build deps or even master go modules.
CI passes and second run build-go speed increases.
Looks like cache hit went from 4 minute go build to 2 minute go build

ci: cache go modules deps and build cache

---

harness/determined/cli/agent.py
harness/determined/cli/task.py
master/internal/api_tasks.go
master/internal/api_tasks_intg_test.go
master/internal/authz/obfuscate.go

Reverts determined-ai/determined#8311

chore: revert task obfuscation lint failures

---

webui/react/src/components/ProjectCard.tsx
webui/react/src/pages/WorkspaceList/WorkspaceCard.tsx

We sometimes display Workspaces and Projects in a grid / cards view
This created a UI issue when https://github.com/determined-ai/hew/pull/34 added a wrapper  - `<div><AntdModal>...</AntdModal></div>` - these divs got counted as elements of the grid in a way that AntdModals were not.
This PR moves the modal context holder inside of the Card.
We moved modals outside the Card in PRs such as #6185 because the **left**-click on a Modal was propagating out to click the card and follow its link. The new wrapper div can call `e.stopPropagation` on both left and right click events.
- `/det/workspaces` cards appear in an uninterrupted grid
- editing a workspace name works correctly (does not click through to navigate to the workspace)
- `/det/workspaces/105/projects` appear in a grid
See [Release …

fix: Move modal context holders inside of Workspace/Project cards

---

e2e_tests/tests/command/test_shell.py
harness/determined/common/api/authentication.py
harness/tests/cli/test_auth.py

Fix -u flag for JupyterLab instances and Determined instantiated shell sessions. Now, when a user who is not logged in runs a `det user` command in a shell on a remote host, they will be prompted for a login password for the passed in user. Upon entering the correct password, the command will be executed for the user passed in with -u flag argument.
Run e2e tests (specifically covered in `command/test_shell.py`). 
1. `cd .../determined/e2e_tests/tests`
2. `pytest -k "test_user_flag_shell"`
DET-9475

fix: user flag to prompt for password during unauthenticated user requests

---

.circleci/real_config.yml
docs/model-dev-guide/api-guides/apis-howto/_index.rst
docs/model-dev-guide/prepare-container/custom-env.rst
docs/reference/deploy/helm-config-reference.rst
docs/reference/deploy/master-config-reference.rst
docs/reference/job-config-reference.rst
docs/reference/training/experiment-config-reference.rst
docs/release-notes/python-39-bump.rst
docs/setup-cluster/deploy-cluster/slurm/singularity.rst
docs/setup-cluster/gcp/install-gcp.rst
docs/setup-cluster/slurm/singularity.rst
docs/setup-cluster/slurm/slurm-requirements.rst
e2e_tests/tests/config.py
harness/tests/experiment/fixtures/ancient-checkpoints/0.17.6-keras/metadata.json
harness/tests/experiment/fixtures/ancient-checkpoints/0.17.6-pytorch/metadata.json
harness/tests/fixtures/checkpoint.json
helm/charts/determined/values.yaml
master/pkg/schemas/expconf/const.go
master/pkg/schemas/expconf/legacy_test.go
model_hub/Makefile
schemas/test_cases/v0/experiment.yaml
tools/scripts/bumpenvs.yaml
webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
webui/react/src/fixtures/responses/experiment-details/set-a.json
webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json
webui/react/src/pages/ExperimentDetails/ExperimentDetails.test.mock.ts

Bumpenvs for 0.26.4. Includes all changes in environments since 0.24.0.
CI passes

chore: Bumpenvs 0.26.4

---

webui/react/.eslintrc.js
webui/react/src/components/FilterForm/components/FilterField.tsx

Adding eslint rule described in https://eslint.org/blog/2022/07/interesting-bugs-caught-by-no-constant-binary-expression/
Errors code with the operator `A ?? B` where A is a constant non-null type and B is never returned
The one line flagged here is `c.column === value?.toString() ?? ''` ; it appears to be operator precedence issue which I've solved with parentheses: `(value?.toString() ?? '')`
Site builds, tests pass

chore: Add eslint rule for ?? expressions [WEB-1804]

---

webui/react/src/components/ResourcePoolCard.tsx

Fixes an issue where `ResourcePoolCard`s were spaced incorrectly due to modal.
As in #8378 , we can now move the modal placeholder inside of the `Card` component 
- Fixes spacing on `/det/clusters`
- Did a search of where we use `Card` and `Card.Group`. For example `/det/workspaces/563/pools` is working.
- On an instance with more resource pools, hovering over the card shows the expected dropdown and modal (to simulate this on local devcluster, in pages/Cluster/ClusterOverview I made `actionMenu` always return a populated array)

fix: Place modal inside of ResourcePoolCard

---

docs/manage/users.rst
docs/setup-cluster/checklists/_index.rst

As an Admin who is setting up Determined for my organization, I want to understand Determined's strategy for supporting non-root containers, how to set up the non-root user, how to test that jobs still run when the privileges are configured, and any other important information.
Enhancements to #8203

docs: Update non root container instructions

---

master/internal/db/postgres_rp_workspace_bindings_intg_test.go

Fix flake from here https://app.circleci.com/pipelines/github/determined-ai/determined/48124/workflows/5525d0df-5d6d-4031-a4a5-2966321a8a74/jobs/2064456
See this flake doesn't happen in the future

test: fix TestAddAndRemoveBindings flake

---

harness/determined/experimental/client.py

When we added `list_models` to `Determined`, we forgot to add it to `client`. Meant that users got `Determined.get_models` deprecation notices (via `client.get_models`) that they couldn't do anything about.
MLG-1301
This PR adds `client.list_models`. Here's an easy way to call it:
```python
from determined.experiment import client
client.login(<login>)
client.list_models()
```

feat: client gets list_models, too.

---

webui/react/src/components/GalleryModal.tsx
webui/react/src/components/ResourcePoolDetails.tsx
webui/react/src/components/TaskList.tsx
webui/react/src/components/TextEditorModal.tsx
webui/react/src/hooks/useModal/useModal.tsx
webui/react/src/pages/Cluster/ClusterHistoricalUsageCsvModal.tsx
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx
webui/react/src/pages/WorkspaceDetails/WorkspaceQuickSearch.tsx

Applies system/light/dark theme to hyperparameter, notebook, or any old-style modal still inside `src/hooks/useModal`
Switch to dark mode.
In a single-trial experiment, open the Hyperparameter tab, then click the Hyperparameter Search button
The background should be solid, and the title font-family should come from a CSS variable

fix: Wrap older modals in theme class [WEB-1824]

---

e2e_tests/tests/conftest.py

There is a fixture which runs the following command:
det cmd --config resources.slots=1 "'sleep 30'"
It has never worked because it is missing the `run` subcommand.
Why fix a broken fixture when tests are fine without it?

ci: delete broken fixture

---

webui/react/src/pages/F_ExpList/glide-table/tooltip.tsx

The `Tooltip` used in our `useTableTooltip` method is currently imported from Antd and not Hew. This update implements the Hew tooltip. 
1. Navigate to the experiment comparison table on the uncategorized page or any workspace project.
2. Ensure the `State` and `User` columns are enabled. You can enable them by clicking the "Columns" button on top of the table.
3. With the theme in light mode, hover over the user icon and then the state icon, ensure that both tooltips that show have a solid background. 
5. With the theme in dark mode, hover over the user icon and then the state icon, ensure that both tooltips that show have a solid background. 
WEB-1827

fix: Experiment List Tooltip is Transparent [WEB-1827]

---

docs/_static/version-switcher/versions.json

We automated this process from this release (0.26.4) going forward but forgot to do it for last release.
This will never be a problem again.
None

chore: add version dropdown url for previous release

---

harness/tests/determined/common/experimental/test_trial.py

I can't see why mypy is complaining, but I can make it ignore it.
I prefer to ignore a false positive rather than pin a day-old version of a library, to minimize dev disruptions.

ci: fix linting with responses==0.24.1

---

master/internal/rm/kubernetesrm/pods.go

K8s autoscaling nodes (on GKE) get marked with the `DeletionCandidateOfClusterAutoscaler` taint when there aren't any jobs scheduled on it. This does not prevent jobs from being scheduled on the node, but the additional taint makes it so that our resource pool toleration no longer matches. As a result, the node does not appear to be part of any resource pool. this fixes the issue by making the `DeletionCandidateOfClusterAutoscaler` tolerated automatically by all resource pools.
**Prerequisites: gcloud CLI and gcloud access, kubectl installed, and determined installed.**
Start a GKE cluster with the following commands (copy pastable unless you want/need to change names or node locations):
1. `gcloud container clusters create k8s-autoscaling-rp-test --region us-west1 --node-locations …

fix: k8s autoscaling nodes not counted towards RP

---

harness/determined/common/experimental/experiment.py
harness/determined/common/experimental/trial.py

calling `list_checkpoints` without sort and order parameters is supposed to default to the experiment's searcher config, but instead falls through to sorting by ID on the backend.
Ensure that calling `list_checkpoints` without any arguments returns a list of checkpoints sorted by the experiment's searcher metric and smaller_is_better
```
client = experimental.Determined(master=DET_MASTER, user="determined", password="")
ckpts = client.get_experiment(1).list_checkpoints()
print(ckpts)
```

fix: SDK list_checkpoints not defaulting to searcher metric sort

---

webui/react/src/stores/cluster.tsx

In areas where we display {slotsUsed} / {slotsAvailable}; the number available comes from `maxPoolSlotCapacity`.
The function should be accurate and consistent between OSS and EE
This change will overwrite the EE-only line:
`if (pool.slotsAvailable && pool.slotsAvailable > 0) return pool.slotsAvailable; // The case for HPC Slurm & PBS clusters`
This should have no effect on local devcluster.
Builds successfully
Completing discussion with backend team about whether this calculation is the best way to represent Slurm and PBS

chore: use ResourcePool info for consistent capacity calculation [WEB-1796]

---

master/internal/command/command.go
master/internal/command/command_service.go

In KillNTSC, if `Signal` returns a not found error, continue & don't  return an error. This fixes a potential race condition where the db says a command isn't completed yet the allocation has already exited.
Pass CircleCI

chore: add error check to KillNTSC

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/api_project.go
master/internal/api_user_intg_test.go

DeleteExperiments was misinterpreting the response from a function it called, resulting in non-sense behavior. I improved the API of the function and fixed the calling code. I also fixed some cases where we were erroneously logging errors on success cases.
DET-9978

fix(api): handle delete experiment failures correctly

---

webui/react/src/components/TaskBar.tsx
webui/react/src/pages/InteractiveTask.test.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts

Interactive task used to not have access to the workspace id, so the permission check for killing task is always false for non-admin.
Log in as a user with workspace admin role
Create a notebook in that workspace
Notebook can be killed from `/det/tasks` page, as well as on `/det/interactive` page
WEB-1268

fix: Kill task permission on interactive page

---

harness/pytest.ini

Avoid a wall of warnings every single run.

ci: register unit pytest marks

---

master/internal/db/postgres_experiments_intg_test.go
master/static/migrations/20231122090045_generic-metrics-on-del-casc.tx.down.sql
master/static/migrations/20231122090045_generic-metrics-on-del-casc.tx.up.sql

Fixed experiment deletion by adding delete cascade to `generic_metrics` table.  When trials are deleted due to delete cascade from experiments, generic metrics will in turn be deleted given their corresponding trial.
No manual testing needed.
DET-9981

fix: add delete cascade to generic metrics

---

master/internal/api_command.go
master/internal/api_experiment.go
master/internal/api_notebook.go
master/internal/api_shell.go
master/internal/api_tensorboard.go
master/internal/config/config.go
master/internal/config/config_test.go
master/internal/config/oidc_config.go
master/internal/user/postgres_users.go
master/internal/user/postgres_users_intg_test.go
master/pkg/model/user.go
master/pkg/tasks/task_trial.go

Added PACHD_ADDRESS to the task environment variables as a part of pachyderm user provisioning.
1. Create a Kubernetes cluster using the determined-ee repo.
2. Checkout branch saloni-gupta-pachyderm-intg.
3. Add your pachyderm address to the `./devcluster.yaml`:
```
integrations:
pachyderm:
address: "foo"
```
4. Start the devcluster
5. Login using your OIDC credentials.
6. Open a jupyter notebook.
7.  Run the command `!env` in the notebook.
8. Verify that the PACHD_ADDRESS environment variable is the same as the one you put in the `./devcluster.yaml` file.

feat: adding PACHD_ADDRESS and DEX_TOKEN to task env [DET-9875]

---

webui/react/src/ioTypes.ts
webui/react/src/pages/F_ExpList/glide-table/OptionsMenu.tsx
webui/react/src/stores/experiments.tsx
webui/react/src/stores/users.tsx
webui/react/src/types.ts
webui/react/src/utils/valueof.ts

This migrates the detaileduser and experimentitem types to io-ts. This is because these types are in use as codecs for the immutableobservables in the user and experiment stores respectively. To prevent the codec type from drifting away from the concrete type, we instead derive everything from the codec type. A small knock-on effect is that the helper `ValueOf` type and codec have been moved to a separate module to prevent circular imports.
no testing required -- typescript checks should continue to pass.
WEB-1833

chore: migrate detaileduser and experimentitem types to io-ts

---

master/internal/api_command.go
master/internal/api_experiment.go

Fix failing test here
https://app.circleci.com/pipelines/github/determined-ai/determined/48552/workflows/75ec094f-166f-4d8a-a9ca-7898a9ce660a/jobs/2094830
Caused by a regression in this PR
https://github.com/determined-ai/determined/pull/8473/files
e2e tests cover this

fix: failing custom searcher due to ExtraEnvVars being overwritten

---

master/internal/rm/agentrm/agent.go
master/internal/rm/agentrm/agent_state.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/sproto/resources.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go
master/internal/task/allocation_service_test.go

We had a few bugs, but the main one was that on receipt of a `ResourcesRestoreFailure` allocations
would not exit but just chill waiting on a `ResourcesReleased` event that would never come (RMs have never
sent this). The other issue was the RM was relying on allocations to cleanup their resources but if restore failed
they wouldn't be around to do this, so now we send an extra SIGKILL from the RM just in case.
I don't think these fixes are 100% optimal, I think there is some architectural change that solve all these and
similar issues, but I haven't dreamed up the best approach yet. 
I also fixed up some logging and type names to make debugging and readability better. 
Covered by automated testing. (I'm going to add more in a follow up)
Ended up needing to attach delve to a live …

fix(rm): tasks shouldn't hang on restore failures

---

master/internal/api_experiment_intg_test.go
master/internal/experiment/bulk_action.go

Fix an error where bulk delete can fail when using a filter with a message like:
`
[bun]  13:29:26.577   SELECT                  632µs  SELECT "e"."id", CASE e.state::text WHEN 'STARTING' THEN 15 WHEN 'DELETE_FAILED' THEN 11 WHEN 'QUEUED' THEN 13 WHEN 'ACTIVE' THEN 1 WHEN 'PAUSED' THEN 2 WHEN 'STOPPING_ERROR' THEN 5 WHEN 'COMPLETED' THEN 6 WHEN 'ERROR' THEN 8 WHEN 'DELETING' THEN 10 WHEN 'RUNNING' THEN 16 WHEN 'UNSPECIFIED' THEN 0 WHEN 'STOPPING_COMPLETED' THEN 3 WHEN 'STOPPING_CANCELED' THEN 4 WHEN 'CANCELED' THEN 7 WHEN 'DELETED' THEN 9 WHEN 'PULLING' THEN 14 WHEN 'STOPPING_KILLED' THEN 12 END AS state, COUNT(model_versions.id) AS versions FROM experiments as e JOIN projects p ON e.project_id = p.id LEFT JOIN checkpoints_view c ON c.experiment_id = e.id LEFT JOIN model_versions ON …

fix: use explicit e.state in bulk experiment delete query

---

docs/release-notes/8488-tqdm.rst
harness/determined/launch/wrap_rank.py
harness/tests/launch/test_wrap_rank.py
master/static/srv/ship_logs.py

This has already been fixed in ship_logs.py, but since ship_logs.py isn't allowed to to have any non-stdlib dependencies (including determined) and since determined can't depend on ship_logs.py (which is only available on-cluster), the right answer is copy/paste.

fix: tqdm logs within wrap_rank [MLG-1236]

---

master/internal/usergroup/group_intg_test.go
master/internal/usergroup/postgres_groups.go

For better code organization, adding this function to the usergroup module instead of EE oidc module. This method is used in EE oidc/service.go (and maybe saml/service.go).
added an intg test
Should I unexport all the Tx functions now that `UpdateUserGroupMembership` is in the same module -- or leave as is?

chore: add UpdateUsergroupMembership

---

.circleci/real_config.yml

Our Go cache started to be ineffective between these two commits
https://app.circleci.com/pipelines/github/determined-ai/determined/48447/workflows/287c3493-1e86-4c47-830f-4fcc82cce5fd/jobs/2087184
https://app.circleci.com/pipelines/github/determined-ai/determined/48449/workflows/bfb1205b-bbeb-4994-8a86-bf6a18891c2b/jobs/2087365
I'm not entirely sure what is going on here but it is causing an extra 2 minutes to be added to CI.
We don't actually need to run ```get-deps``` for building our Go so try not doing that and see if it helps. 
Cache miss https://app.circleci.com/pipelines/github/determined-ai/determined/48539/workflows/b7d2bc77-6056-4e11-929c-fe39764a122c/jobs/2093810
Cache hit https://app.circleci.com/pipelines/github/determined-ai/determined/48539/workflows/77a6b5cd-2811-47d0-849f …

ci: fix Go build cache by not making it run get-deps

---

.circleci/real_config.yml
harness/tests/determined/common/storage/test_s3.py

Fixes moto linting issue that will happen when our Python cache is busted.
Adds a day expiry to the cache so that these issues will appear on main sooner.
No testing needed

ci: add date to python cache, fix moto linting issue

---

harness/determined/cli/trial.py
harness/determined/common/experimental/trial.py

`Trial.list_checkpoints` never passed the `states` parameter, resulting in a return of STATE_DELETED checkpoints under some conditions. This is not an issue with the SDK, but rather a confusing output due to the CLI args. Updating the error message to dispel confusion.
1. Find or make a trial with multiple checkpoints 
2. Get the UUID of the “best checkpoint”: det trial describe <trial_id> --json
3. Delete the checkpoint: det checkpoint delete <uuid>
4. Download the “best checkpoint”: det trial download <trial_id> --best
Expected behavior:  Another checkpoint is downloaded
MLG-1163

fix: Update Trial Download Error Message

---

webui/react/src/components/HelpModal.tsx
webui/react/src/omnibar/Omnibar.tsx
webui/react/src/omnibar/tree-extension/trees/actions.tsx
webui/react/src/omnibar/tree-extension/trees/index.ts

Replaces Omnibar response to `help` (opening an Antd Modal) with a Hew / UI Kit modal.
In #8432 I was unable to fix dark mode theming on this Antd Modal; it is also resolved here
Put UI into Dark Mode
Ctrl/Control Space to open up the Omnibar
Type `help` and press enter
Confirm the new modal contains lists of shortcuts and commands:

fix: Overwrite omnibar antd modal with Hew standard modal [WEB-1830]

---

master/internal/command/command.go
master/internal/command/command_job_service.go
master/internal/experiment.go
master/internal/experiment_job_service.go
master/internal/job/jobservice/jobservice.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/agentrm/agent_resource_manager_intg_test.go
master/internal/rm/agentrm/resource_pool_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/sproto/jobs.go
master/internal/sproto/task.go
master/internal/task/allocation.go

Removed `for` loops from the following methods for K8s and determined (agent) resource managers: 
- `MoveJob`
- `Release`
- `SetAllocationName`
- `SetGroupMaxSlots`
- `SetGroupPriority`
- `SetGroupWeight`
In all of the above referenced files, added `ResourcePool` field to API request literals if it wasn't previously there.
Now, the functions listed above make a direct call to the resource pool provided in the API request.
DET-9920

refactor: replace resource pool looping with direct call

---

master/internal/usergroup/group_intg_test.go

Solve https://app.circleci.com/pipelines/github/determined-ai/determined/48642/workflows/c2da444e-9db2-476f-b44b-e23ddd6809f1/jobs/2100987 flake -- switched to `require.ElementsMatch(...)`
Pass circleCI

chore: add ElementsMatch to usergroup test

---

webui/react/src/components/DeleteModelModal.tsx
webui/react/src/pages/ModelDetails/ModelHeader.tsx

Bug: deleting a model from a Workspace's Model Registry tab redirects us to the wrong place (general `/det/models` page)
Solution: a redirect is only needed if the user is requesting delete from the Model Details page, where I will pass a `listPath` prop. Actions on the model registry tables will no longer trigger a redirect.
Note: we don't use the store in models, so the registry takes a few seconds to update
Alternatives: I considered always passing a workspace to the delete modal, and redirecting by default. The issue was that ModelActionDropdown is wrapped by InteractiveTable/ContextMenu and cannot pass new props
- Create two models within a workspace
- Click into one model's details page. Delete the model from this page, and you will be redirected back to the workspace's registry tab …

fix: Model delete redirect only needed if inside the model [WEB-1867]

---

docs/integrations/ide/vscode.rst
harness/determined/cli/__init__.py
harness/determined/cli/_util.py
harness/determined/cli/experiment.py
harness/determined/cli/notebook.py
harness/determined/cli/shell.py
harness/determined/cli/tensorboard.py

Windows Users are having issues with VSCode remote-ssh integration. This is due to Windows defaulting to CMD with OpenSSH instead of using WSL bash and the proper ssh tool for the job. Adding warning to CLI and also changing `det shell show_ssh_command` to `det shell show-ssh-command`
Start a remote shell.
1. Be a Windows user
2. `det shell show-ssh-command` should show a VSCode-specific warning in WSL shell.
1. Be any user
2. `det shell show_ssh_command` should show a deprecation warning.
This should address https://github.com/determined-ai/determined/issues/7726
MLG-871

chore: Rename show_ssh_command in CLI and add message for VSCode WSL Users

---

docs/reference/python-sdk.rst

Help evangelize the python sdk by updating the documentation. Specifically, by describing a specific version of the [det-python-sdk-demo](https://github.com/determined-ai/determined-examples/tree/e499000d92a0a973d1f40a419934f393957a3296/blog/python_sdk_demo) example and applying the latest standards.

Mention det python sdk demo

---

docs/setup-cluster/_index.rst

Users want to be able to find the HPE MLDES Managed Service trial so that they can sign up. Users want to be able to find the HPE MLDES Managed Service documentation so that they can find out more.

docs: Add a link to mldes trial

---

docs/release-notes.rst
docs/release-notes/8488-tqdm.rst
docs/release-notes/fix-log-policies-match-itself.rst
docs/release-notes/oidc-pachyderm-env-vars.rst
docs/release-notes/oidc-sync-groups.rst

docs: add release notes for 0.26.5

---

docs/manage/workspaces.rst

Remove the extra toctree from the `workspaces` file that was referencing the `workspaces-rpools` page. We don't need this anymore because we are catching them all at the `_index` page level.
remove
```
.. toctree::
:maxdepth: 1
:hidden:
Binding Resource Pools to Workspaces <workspaces-rpools>
```
in favor of
```
.. toctree::
:glob:
:hidden:
./*
./*/_index
```

docs: Fix workspaces projects left nav

---

.circleci/real_config.yml

Circleci test split could not find the timing data because it was not saved and reported by us for `test-e2e-gke` flow. Fix this.
- circleci starts doing split-by-timing for GKE tests
- circleci `tests` tab is property populated for GKE tests

test: store test results for `test-e2e-gke`.

---

master/internal/api_checkpoint_intg_test.go
master/internal/api_trials.go
master/internal/api_trials_intg_test.go
master/internal/core_checkpoint_intg_test.go
master/internal/db/postgres_checkpoints_intg_test.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_model_intg_test.go
master/internal/db/postgres_trial.go
master/internal/db/postgres_trial_intg_test.go
master/internal/run/postgres_run_intg_test.go
master/pkg/model/experiment.go
master/static/migrations/20231204141901_run-checkpoints.tx.down.sql
master/static/migrations/20231204141901_run-checkpoints.tx.up.sql
master/test/integration/api/api_checkpoints_test.go
master/test/olddata/pre_run_trials.go

Adds a one run to many checkpoint relationship table. Didn't just add a field so in the future if we want to make the relationship many to many we can just drop the unique constraint on the relationship table.
should be covered by integration tests

chore: run to checkpoint migration

---

webui/react/src/components/Metadata/EditableMetadata.tsx
webui/react/src/components/Metadata/MetadataCard.module.scss
webui/react/src/components/Metadata/MetadataCard.tsx

Replaces antd.Card and Typography in the MetadataCard component, affecting ModelDetails (objective of ticket) and ModelVersionDetails.
View a Model from the registry, such as `/det/models/71`
Before any metadata:
Editing:
With values:
The difference in font sizes for keys and values exists in the current version.
The MetadataCard appears inside a tab panel at ModelVersionDetails, so I've added `elevationOverride` to its Surface prevent it from looking different on that page.

chore: Model metadata sections move to Surface [WEB-1813]

---

harness/determined/deploy/aws/cli.py

- truncate full hashes given to lore-version to the standard 7chars long
- add help docs and disclaimers to the cli
deployed successfully while giving a full valid lore hash
https://hpe-aiatscale.atlassian.net/browse/MLG-1453
https://hpe-aiatscale.atlassian.net/browse/MLG-1416

chore: add lore help and experimental disclaimer

---

master/Makefile
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go
master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/pods.go

Implement `GetSlot`, `GetSlots`, and `GetAgent` for Kubernetes resource manager API.
No manual testing needed.
DET-9919, DET-9921

chore: implement GetSlot, GetSlots, and GetAgent for K8s rm

---

docs/release-notes/remove-dry-run-det-deploy-aws.rst
harness/determined/deploy/aws/cli.py

Original ticket was brought up by user attempting to set `--no-shut-down-agents-on-connection-loss` and not seeing `--dry-run` option populated. AFAICT, `--no-shut-down-agents-on-connection-loss` is correctly populated in the AWS templates and functions as expected. 
Per slack discussions, we are removing `--dry-run` because it currently has no effect and AWS CloudFormation doesn't surface a way to "preview" deploy before deploying. 

chore: remove --dry-run option from det deploy aws [MLG-983]

---

e2e_tests/tests/cluster/test_users.py
e2e_tests/tests/command/test_shell.py
harness/determined/common/api/authentication.py
harness/tests/cli/test_auth.py
harness/tests/cli/test_user.py
harness/tests/cli/util.py
harness/tests/requirements/requirements-cli.txt

The unit test replaces two e2e tests, and then provides even more test
coverage beyond those.
The intention of this test is more "clearly document the current
behavior" rather than "enforce the current behavior forever".
There are decisions we've made, especially regarding the default login
credentials, that feel suspect to me.  I hope this test is useful for
highlighting the effects of changing any of those decisions, so we can
make those changes in an educated way.  I do not intend for this test
to force us to keep the exact implementation we have forever.

ci: unit-test login scenarios

---

docs/release-notes/fix-master-download.rst
master/internal/core_checkpoint_intg_test.go
master/pkg/checkpoints/s3/s3checkpoints.go

Bug in how we called the s3 API meaning we couldn't download from ```us-east-1```
Integration test should cover it, manual though
manual
run ```mnist_pytorch_const``` with config
```
name: mnist_pytorch_const
hyperparameters:
learning_rate: 1.0
n_filters1: 32
n_filters2: 64
dropout1: 0.25
dropout2: 0.5
searcher:
name: single
metric: validation_loss
max_length:
epochs: 1
smaller_is_better: true
entrypoint: python3 train.py
checkpoint_storage:
type: s3
bucket: storage-unit-tests-us-east-1
prefix: master/checkpoint-download
access_key: EDIT
secret_key: EDIT
```
direct download a checkpoint through ```det checkpoint download $CHECKPOINT_ID --mode master``` $CHECKPOINT_ID you can get from ```det e lc $expID```
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/relea …

fix: master cannot download s3 from us-east-1 

---

e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/fixtures/no_op/empty_model_dir.yaml
e2e_tests/tests/test_sdk.py
harness/determined/cli/experiment.py
harness/determined/common/experimental/determined.py
harness/determined/exec/prep_container.py
harness/determined/experimental/client.py
master/pkg/model/experiment.go

Triage to allow for `model_dir` to be set to none when creating experiments. 
- Removes the check on the model definition.
- Updates the CLI & SDK to allow for these types of experiment submissions
- Adds testing for this use case
- Attempt to create a new experiment through the SDK with `model_dir=None`
- `e2e_tests/tests/test_sdk.py:test_completed_experiment_and_checkpoint_apis` now also checks if an experiment can be create without a model definition (given that entrypoint is already in the container)
This resolves the immediate issue, but a more thought through implementation for checking for this specific case besides allowing any submission to be made without a `model_dir` or model definition specified would be ideal.
See [Release …

fix: allow for `model_dir` to be None when submitting experiments

---

examples/computer_vision/iris_tf_keras/distributed.yaml

Using GPU slot 16 would lead to error where sequence length < num_slots. ([link](https://gcloud.determined.ai/det/experiments/2856/overview))
Thus, change the number back to 2 as before.
In `determined/examples/computer_vision/iris_tf_keras`
`det e create distributed.yaml . --project 56`
https://gcloud.determined.ai/det/experiments/2858/logs
Completed successfully

fix: Change slot number back to 2 in Keras example

---

master/static/migrations/20231208132223_drop-raw-checkpoints.tx.up.sql

Remove `raw_checkpoints` table.
In case customers who upgraded determined still had checkpoints in this table, all elements from `raw_checkpoints` were copied into `checkpoints_v2` [here](https://github.com/determined-ai/determined/pull/7325). We left `raw_checkpoints` around to avoid a tricky down migration, but this PR removes the table without a down migration since we no longer insert checkpoints into `raw_checkpoints`, and instead use `checkpoints_v2`.
Manual test required:
- Store some checkpoints in `checkpoints_v2` as follows:
- Start up a local cluster with the `devcluster` command so that all migrations run except for `20231208132223`. To ignore migration `20231208132223`:
- Either run a down migration using `determined-master -m <master instance> migrate down <older migration …

chore: drop raw_checkpoints table

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/App.module.scss
webui/react/src/components/ExperimentMoveModal.tsx
webui/react/src/components/ModelRegistry.tsx
webui/react/src/components/OverviewStats.module.scss
webui/react/src/components/OverviewStats.tsx
webui/react/src/components/ProjectCard.module.scss
webui/react/src/components/ProjectCard.tsx
webui/react/src/components/ProjectMoveModal.tsx
webui/react/src/components/Table/Table.tsx
webui/react/src/components/UserSettings.tsx
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpTrialTable.tsx
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/WorkspaceList/WorkspaceCard.module.scss
webui/react/src/pages/WorkspaceList/WorkspaceCard.tsx

Bug: If `antd.Typography` element text overflows into a tooltip, we are not seeing the theme's background/font, similar to issues which we saw with other tooltips and modals.
This PR comes from scanning for all imports of Typography. If it comes from antd and the file uses the `ellipsis` prop, then we replace it with `<Title truncate={ tooltip: true }>` or `Label` or `Body` from hew.Typography.
- Created XS size for titles
Fixes this bug with hovering long names on `/det/workspaces`:
Code replacement is sound across changes.
Affected components:
- ProjectCard and WorkspaceCard
- Stats on top of Clusters view (continues to have font-size override)
- Comparing experiments -> Details tab, experiment name headers
- Long experiment descriptions in Experiment Details Header
- Text cells in a …

fix: antd.Typography with expansion tooltips moved to hew [WEB-1862]

---

webui/react/src/App.tsx
webui/react/src/hooks/useTheme.settings.ts
webui/react/src/stores/userSettings.tsx

This fixes an issue where the user management table appeared to refresh constantly. the user management page is set up to refresh the table when its underlying persisted settings refresh, which can happen inadvertently when multiple clients are using the same user account. The theme setting was set up to always update the settings table to the local value on conflict, which causes a conflict when one client changes the theme. To fix this, we:
1) ensure that the user settings store does not trigger refreshes when setting to an identical value. note that we aren't able to use the deep or immutable observable wrappers introduced in #8405 because the value is an immutable collection wrapped in a plain object -- immutable collections are stateful, so a simple deep check wouldn't work, and …

fix: prevent theme settings conflict in multi-client/window scenario

---

harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/base.py
harness/determined/deploy/aws/deployment_types/vpc.py
harness/determined/deploy/aws/injector/master.yaml.tmpl
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/lore.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml

Change user-facing parts of the det deploy that references lore to genai.
Internal references clean up will be a separate task (lower pri).
`det deploy aws up --cluster-id swy-lore-test4   --region us-west-2 --keypair szewai-determined-aws --compute-agent-instance-type g4dn.12xlarge --max-dynamic-agents 10 --det-v 115f685a4cd4025118a198751a81b5e0105c5f68  --max-idle-agent-period 60m   --deployment-type genai --genai-version a45d508`

chore: Change CLI and constants

---

model_hub/docker/Dockerfile.transformers
model_hub/model_hub/huggingface/_config_parser.py
model_hub/model_hub/huggingface/_trial.py
model_hub/model_hub/mmdetection/_trial.py
model_hub/model_hub/utils.py
model_hub/mypy.ini
model_hub/setup.py
model_hub/tests/test_hf.py
model_hub/tests/test_mmdetection.py

`attrdict` is broken since Python 3.9.  Possible replacements do not meet our dependency requirements. This PR implements our own `AttrDict` as a utility class.
Replaces https://github.com/determined-ai/determined/pull/8541
Unit tests pass. Also try any `mmdetection` and `hugginface` example.
- [C] Changes have been manually QA'd
MLG-1442

chore: Remove attrdict from model hub

---

docs/reference/model-hub/mmdetection-api.rst

Fix broken link to `readme` that was moved as part of examples pruning.

docs: Fix mmdetection readme link

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go

Update for experiment hyper-parameter search to remove extra quotes.
Automated.
DET-9799

fix: update experiment hp search param quoting

---

harness/determined/cli/workspace.py

Old:
`det workspace describe <workspace>` (when executed with out `--json`) used to first print a table of information about the passed workspace and then would print another table listing all the projects that belong to the workspace.
New:
`det workspace describe <workspace>` *only* describes the passed workspace
Justification:
`det workspace list-projects <workspace>` is already a thing. If a user wants to list workspaces they can run that command. The old behavior was awkward to implement because it needed to assume parameters to list-projects that would normally be passed as flags to `det workspace list-projects`.
[MLG-1113]
Describe a workspace:
```
det workspace describe <workspace>
``` …

chore: cli describe workspaces no longer also lists projects

---

docs/integrations/ide/vscode.rst
harness/determined/cli/shell.py

`os.uname()` doesn't work on Windows. Use platform to identify a Linux system before warning WSL users. Also add a line in docs for Windows users.
Test that `show-ssh-command` doesn't error on Windows and still shows a warning on WSL.
Linked issue here https://github.com/determined-ai/determined/issues/8621
MLG-1503

fix: os.uname() not found on windows

---

examples/computer_vision/iris_tf_keras/const.yaml

The current `const.yaml` configuration fails due to a too-large global batch size.  This PR reduces the global batch size.
Run `det e create const.yaml .` from within the `examples/computer_vision/iris_tf_keras` dir and verify that the trial runs without failing. 
Original error message pre-fix:
```
[2024-01-03 18:48:56]
[ac93e99e] Traceback (most recent call last): <none> [2024-01-03 18:48:56]
[ac93e99e]   File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main <none> [2024-01-03 18:48:56]
[ac93e99e]     return _run_code(code, main_globals, None, <none> [2024-01-03 18:48:56]
[ac93e99e]   File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code <none> [2024-01-03 18:48:56]
[ac93e99e]     exec(code, run_globals) <none> [2024-01-03 18:48:56]
[ac93e99e]   File …
```

fix: reduce tfkeras iris const batch size

---

harness/determined/cli/_util.py
harness/determined/common/api/_util.py

extend timeout of NTSC CLI commands. 5 min is too short since tasks can be in a queued/starting state before they are considered ready.

chore: extend CLI NTSC timeout [MLG-870]

---

docs/reference/deploy/master-config-reference.rst

Add an admonition.
Reason: By default `authenticationClaim` is set to email. However, a user can be provisioned by setting the authenticationClaim in the config to something that may not be unique such as name, preferred_username, given_name etc, causing conflicts.

docs: Add oidc note about uniqueness

---

webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/pages/ResourcePool/ResourcepoolDetail.tsx
webui/react/src/pages/ResourcePool/Topology.tsx
webui/react/src/types.ts

Reported in a few places - we have polling on JobQueue but not ResourcepoolDetail, so you might see disagreement between the tab and the number of Active or Queued tasks:
**Updated fix:** this moves the polling of `getJobQStats` from JobQueue to ResourcepoolDetail.  This still requests stats from all resource pools, so that we can get that info in JobQueue's ManageJobModalComponent. JobQueue is not used anywhere else.
**Update 2:** this also fixes an issue where agents with only some slots used were rendered incorrectly in Topology
- Go to `/det/resourcepool/compute-pool/queued` and see 0 queued tasks
- In another tab or window, launch two Jupyter Notebooks
- As the notebooks get ready, they will appear in Queued and the total will update
- As a notebook becomes Active, it will disappear …

fix: Changes on jobs table trigger cluster stats [WEB-1914]

---

webui/react/src/pages/TrialDetails/TrialDetailsMetrics.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

On the experiment Metrics tab, we put metrics with similar names on the same plot. Ideally training loss and validation loss would be plotted together.
In the example, loss and val_loss were plotted together but both coded in the training metric group.
~Under this change, the metric group coloring will look for prefixes, and "val_" will override the metric being in training metric group.~
**Update: Removes blue/orange coloring for training/validation special groups, instead using glasbey colors; this avoids issues with multiple series being resolved to the same chart + training group**
Experiment `/det/experiments/5518/metrics` displays validation_loss and loss on the same chart
Update `/det/experiments/5522/metrics` shows multiple lines in one chart
See [Release …

fix: Trial metric chart series always have unique colors

---

webui/react/src/pages/Admin/UserManagement.tsx

Description of the bug: in latest-main there are two Inactive users
When viewing 10 users / page on latest-main , sorting by Active one direction (Active first) shows only Active users; sorting the other way (Inactive first) shows the two Inactive users but at the bottom of the table
The fix is changing the direction of `booleanSorter` for this column
After the fix, when viewing 10 users / page with latest-main backend
- sorting by Active first shows only Active users [last page shows Inactive users at the bottom of the table]
- sorting by Inactive first shows two Inactive users at the top of the table

fix: Sort order in users.active column [DET-10048]

---

harness/determined/deploy/aws/templates/simple-rds.yaml

Previously implemented template changes apparently cause a validation error when the newly added `DBSnapshot` parameter isn't present. The new parameter was intended to be optional with the empty string value indicating no argument was passed, and this change makes it so that when the parameter is the empty string, it'll continue as expected.
Run E2E tests for this branch before merging to make sure things actually pass before getting to `main`.

fix(cli/deploy/simple-rds): set template default snapshot

---

.circleci/real_config.yml
codecov.yml

This PR provisions Go coverage metrics through Codecov and imposes a (currently non-blocking) per-PR (`codecov/patch/backend`) and overall backend (`codecov/project/backend`) coverage ratchet.
`codecov/project`,` codecov/patch`, `codecov/project/backend`, and `codecov/patch/backend` coverage checks and metrics are visibly available in Github status checks after all CI checks have completed and passed, and the "Details" page links to Codecov UI containing the dashboard for respective coverage metrics.
DET-10037, DET-10038, DET-10039

chore: add Go coverage ratchet to unit and integration tests

---

master/internal/api_auth.go
master/internal/api_tasks.go
master/internal/command/postgres_command.go
master/internal/command/postgres_command_intg_test

Move postgres_command.go from the db module to command, following best code practices.
Pass attached intg test.
DET-10003

chore: move postgres_command.go to command module

---

docs/setup-cluster/aws/install-on-aws.rst
docs/tools/notebooks.rst
docs/tutorials/_index.rst

Reorder the tutorials so the most important is at the top. Fix issues noted in the docs channel. Clarify that data is not deleted when modifying a deployment. Let users know to set work_dir each time they launch JupyterLab in AWS and how to easily save JupyterLab progress.

docs: Reorder the tutorials for visibility

---

webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx
webui/react/src/pages/WorkspaceList.tsx

Avoid showing the No Workspaces / No Projects messages until finished loading a response from API
Both of these pages use the Spinner component to show loading, so we don't need to show the message unless we finish loading and receive 0 results
When you load Determined and then click Workspaces in the nav bar, it shows the loading spinner without the No Workspaces message
Workspace without projects shows No Projects message `/det/workspaces/535/projects`

fix: Check if loading before saying no workspaces / projects [WEB-1904]

---

webui/react/src/components/TaskActionDropdown.tsx

This was an issue on the Tasks table, where using the dropdown to View Logs, then clicking the browser back button, disables most table actions.  In addition to the reported issue, I could not click the row checkbox or open the right-click context menu.
I can only replicate on latest-main + Firefox;  not with `devserver` or `make live` hosting. So I am unable to test this completely.
My theories are:
- we should call `onComplete?.()` when completing the menu action / before navigating
- it may help to replace the Link element with `useNavigate`
On the tasks page, clicking the three-dots menu opens a dropdown.
Clicking "View Logs" opens the logs for that task 

fix: replace View Logs link with useNavigate [WEB-1893]

---

master/internal/core_experiment.go
master/internal/db/postgres_experiments.go
master/pkg/model/experiment.go
master/static/migrations/20200401000000_initial.tx.up.sql
master/static/migrations/20240105121220_drop-exp-columns-git-model-packages.tx.down.sql
master/static/migrations/20240105121220_drop-exp-columns-git-model-packages.tx.up.sql
webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json

Delete unused fields from the experiment table.
Pass existing db intg tests.
To manually test, spin up a devcluster & check that the db (psql -h localhost -p 5432 -U postgres -d postgres) does not have "git_*" or "model_packages" columns in the experiment table
DET-10034

chore: delete unused experiment fields

---

webui/react/src/constants/states.ts

The term "Scheduled" is meaningful for the Jobs/Tasks page and will be restored
Active/running tasks are labeled as "Scheduled" on `/det/tasks`

fix: Revert "chore: Job/task displays Running instead of Scheduled"

---

harness/determined/cli/experiment.py
harness/determined/common/declarative_argparse.py
harness/determined/common/util.py
harness/determined/pytorch/_pytorch_context.py
harness/determined/pytorch/deepspeed/_deepspeed_context.py
harness/determined/tensorboard/metric_writers/pytorch.py

distutils is removed in python 3.12.  We shouldn't really be using it anyway, but rather than do a breaking change to switch to the behavior I want us to have, here's a quick fix that unbreaks us, and I made a ticket to do the breaking change at some point in the future.
Note that to manifest the failure, you'll need to uninstall setuptools from your python environment (which provides its own distutils package starting in python 3.12).

fix: stop using distutils (for python 3.12) [MLG-1519]

---

master/internal/api/error.go
master/internal/api_user.go
master/internal/api_user_intg_test.go
master/internal/user/postgres_users.go
master/internal/user/postgres_users_intg_test.go
master/internal/user/service.go
master/internal/user/service_intg_test.go

Fix an error message, to match previous Determined version.
Return db.ErrDuplicateRecord if attempting to add a user to the DB that returns db.CodeUniqueViolation.
See attached intg test.
DET-10051

chore: reinstate original DuplicateError to postgres_users.go

---

helm/charts/determined/templates/master-service.yaml

Changes regarding: Helm chart - `master-service.yaml ` template file
On OPENSHIFT clusters, if the parameter` .Values.openshiftRoute.enabled` is set to true, to request the creation of the **Route HAProxy**, the related master service must have type **ClusterIP**; this because using the the **Haproxy** route the IP traffic goes though the **Load Balancer** (LB) already present in the **Haproxy** itself, hence nor the **LoadBalancer** neither the **NodePort** are needed.
Previously the chart created a master service that depends on the param. `useNodePortForMaster`, so it creartes **NodePort** or **LoadBalancer** (as in this case) that is not needed.
Template `master-service.yaml` change practically works this way: if an route openshift is requested the service type will be ClusterIP …

fix: Helm master-service clusterip mngt. openshift

---

docs/deploy/scrape.py

Algolia search index is uploaded, then renamed after uploading. We never explicitly wait for the upload to finish before renaming the object on the cloud, causing a potential race condition. This PR adds a wait step.
Check algolia for number of index records. Should match what was uploaded.
MLG-1513

fix: wait on algolia search upload

---

webui/react/src/components/ExperimentIcons.tsx

This fixes an issue where experiments that were stopping for one reason or another showed as stopped.
submit an experiment
on the experiment's detail page, cancel the experiment
the experiment state should show up as stopping before updating to stopped.
WEB-1913

fix: break out stopping... states from stopped states in webui

---

webui/react/src/pages/Dashboard.tsx

Fix the issue that the buttons on the dashboard page are out of place during page load. 
Before: 
After:
This PR only remove the out of place button, and should follow up with utilizing multiple spinners [WEB-1898](https://hpe-aiatscale.atlassian.net/browse/WEB-1898)
WEB-1902
[WEB-1898]: https://hpe-aiatscale.atlassian.net/browse/WEB-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Remove out of place spinner at dashboard page

---

webui/react/src/pages/F_ExpList/glide-table/columns.ts
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/textCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/index.tsx

Copy `drawTextWithEllipsis` logic from the Glide Table column headers to other cells.
Includes text and number type columns (this doesn't affect number format or sorting)
Did not include min width text columns: Archived (single emoji), and Progress (values "0%" to "100%")
On `/det/projects/1/experiments`, shrink the width of a text column such as "start time", name, or description:
- The value should be truncated with "..." and the right edge should line up with the header truncation
- Right-click the cell and select "Copy Value". You copy the untruncated value of the cell
Include a universally numeric metric such as `training.loss.min` in the table. Sort 0->9 and 9->0 to confirm it is being sorted numerically (2, 10, 300) and not alphabetic ("10", "2", "300")
When width is shortened:
- …

feat: Truncate and pad cell values in glide table [WEB-1778]

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpScatterPlots.module.scss

Currently the `HPScatterPlots` shows a vertical scrollbar when only one row of plots exist which is unnecessary. The height for the scatter plots is set to `350px` however the min height for the containers is set `200px` causing the vertical scroll bar to show. This is a simple fix to update the container height.
1. Visit the HP Scatter plot tab for a completed multi-trial experiment with several Hyperparameters.
2. Select HPs so that only one row of plots show, change your screen size and ensure that a vertical scrollbar is only shown within the scatter plot grid container when there is more than one row of scatter plots. 
https://github.com/determined-ai/determined/assets/103522725/9461b9e7-63f8-41b7-b411-92701fa797ed
See [Release …

fix: HP ScatterPlots show unnecessary scrollbar

---

docs/release-notes/jupyter-root.rst
master/static/srv/notebook-entrypoint.sh

Set the root of the jupyter notebook file browser to `/`, and the default starting location to the `work_dir`.
Pros:
* full file tree becomes visible
* default starting directory in the file browser, launched notebooks or terminals stays the same (`work_dir`), unless you navigate away in the browser
* you can always return back using the home icon, so it’s really hard to get lost
* if you navigate somewhere you don’t have write permissions, creating new notebook will return a “permission denied” error. there’s no new permissions obtained by the user (as they could always reach whatever location outside the `work_dir` using the terminal).
Background: https://hpe-aiatscale.slack.com/archives/C02T7L0593K/p1704929788275849
- Launch a notebook with or without `work_dir` config setting. Check …

feat: set jupyter notebook file browser root to `/`.

---

harness/determined/ipc.py

When the time between zmq allgathers was greater than the tcp timeout
configured for the machine, zmq allgathers would hang.
Solves #8222, using @igor0's suggestion.
(If you are in the release party, I recommend you mark this as "won't fix" since the fix has basically already been verified by the oss user who suggested, and it's unclear what conditions are required to reproduce it).

fix: add zmq heartbeat in DistributedContext [MLG-1133]

---

e2e_tests/tests/cluster/test_exp_continue.py
master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go

Check for HP search being "done" was bugged due to converting across different proto enums. 
Improve this check.
Also move these tests from e2e_tests to integration. This is relevant to overall CI time.
intg tests

chore: improve error message for continuing a completed hp search [DET-10041]

---

e2e_tests/tests/nightly/compute_stats.py

Make compute_stats have a min tolerance of 3 seconds so shorter tests won't flake using it.
See if ee tests flake less.

test: make compute_stats have a min tolerance of 3 seconds

---

harness/determined/common/context.py
harness/determined/common/detignore.py
harness/determined/common/v1file_utils.py
harness/determined/util.py
harness/tests/filetree.py
harness/tests/test_imports.py
harness/tests/test_util.py

When trial APIs in `--local` mode are making checkpoints, they should respect `.detignore` similar to the usual context directory creation.
- Added a unit test.
- Per original OSS complaint, make a directory with some root-only files which are ignored by detignore, and then try a `--local` run.
For example, 
- `det e create ... --local -test`— initial state, works ok
- `touch root.txt`
- `sudo chown root root.txt`
- `sudo chmod 400 root.txt`
- `det e create ... --local -test` — will fail because of a permission error
- `echo root.txt >> .detignore`
- `det e create ... --local -test` — now works ok

fix: Trial APIs `--local` should respect `.detignore`. [MLG-1352]

---

docs/requirements.txt

A bug in the pydata-sphinx-theme caused the version switcher to not properly avoid 404 errors when switching between versions, if the current doc url did not exist in the target version.
pydata-sphinx-theme has a fix in 0.14.0, but we cannot upgrade due to sphinx-book-theme.  So I backported the relevant fix.  This commit pulls the backported fix into the determined docs build system.
I copied the modified javascript to https://docs.determined.ai/latest so you can make sure this works (there's not really another way to test it).

fix: docs version switcher [MLG-1524]

---

docs/reference/python-sdk.rst
harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/common/experimental/experiment.py
harness/determined/common/experimental/model.py
harness/determined/common/experimental/trial.py
harness/determined/common/experimental/user.py
harness/determined/experimental/client.py

I’ve been asked why did the docstring for the `Experiment` class https://docs.determined.ai/latest/reference/python-sdk.html#determined.experimental.client.Experiment
has `determined.experimental.client.get_experiment()` in it, but it’s not a hyperlink.
I went in and added `:func:`, `:attr:`, and `:meth:` annotations for it and a few classes nearby.
Also added docs autogen for a bunch of missing methods in `determined.experimental.client`, and missing `User` and `ResourcePool` class references.
Are things which look like methods and functions in the docs actually getting rendered as hyperlinks?
If you find more broken or nonexisting links which are not in this PR, please make your own PR to fix them.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-no …

docs: fix a few hyperlinks in the Python SDK reference.

---

docs/setup-cluster/on-prem/options/linux-packages.rst

This PR updates references to Red Hat Enterprise Linux and CentOS to the generic Enterprise Linux and expands the definition to RHEL and RHEL-compatible distributions, including AlmaLinux, Rocky Linux, Oracle Linux, and others.
It also removes references to Scientific Linux, which is discontinued.
These steps have been manually tested on AlmaLinux 9 and Ubuntu 22.04 LTS.

docs: Update references to RHEL and CentOS to Enterprise Linux

---

.circleci/real_config.yml
webui/react/Makefile

fix react e2e test failure https://app.circleci.com/pipelines/github/determined-ai/determined/49978/workflows/c3146d0f-01a7-4efa-8c3e-4206f537ca74/jobs/2191778
```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/webkit-1944/pw_run.sh
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║ …
```

fix: playwright fix

---

webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
webui/react/src/pages/F_ExpList/ComparisonView.tsx

Addresses an Antd / UI Kit  ticket, plus a bug ticket, around the `TrialsComparisonModal`
- Replaces `antd.Tag` with `Row` containing `Label` and close icon button
- Updates `colSpan` to cover multiple experiments or multiple trialIds (+1 to include original column)
As used in multi-trial experiment trials table:
-
As used in the experiments Glide Table:
Open a multi-trial experiment such as `/det/experiments/1290/trials`. Check to select multiple trial rows. In the action menu, select Compare trials to open the modal
Open a project such as `/det/projects/1/experiments`. Check multiple successful / completed experiments which can be compared.
Open the Compare section using the button at top right of the table.
In the Compare section, click the Details tab to see the table as used here
See …

chore: TrialsComparisonModal style fixes [WEB-1919] [WEB-1909]

---

master/internal/api_experiment.go
master/internal/experiment.go
master/internal/trial.go
master/pkg/tasks/task.go
master/pkg/tasks/task_test.go

taskSpec.ExtraEnvVars was not initialized in the case of remote users which was causing a panic whenever the user tried to create an experiment
Log in as a remote user and check if you can create an experiment

fix: fix CreateExperiment for Remote Users

---

webui/react/src/components/ProjectCard.module.scss
webui/react/src/components/ProjectCard.tsx
webui/react/src/pages/WorkspaceList/WorkspaceCard.module.scss
webui/react/src/pages/WorkspaceList/WorkspaceCard.tsx

Uses a standard Hew.Badge to mark archived workspaces and projects. The CSS variable `--theme-status-inactive` must be replaced with an HSL color; both light and dark themes use the same color.
- On `/det/workspaces`, turn on Show Archived, and find or test appearance of an archived workspace
- On a workspace with multiple projects, turn on Show Archived, and find or test appearance of an archived workspace

chore: Replace custom archived note with Hew badge [WEB-1886]

---

docs/setup-cluster/on-prem/options/wsl.rst

This overhaul of the WSL leverages `det deploy` instead of manually installing Postgres and Determined containers and dramatically simplifies the process.
These steps have been manually tested on AlmaLinux 9 and Ubuntu 22.04 LTS.

docs: Overhaul WSL deployment instructions

---

docs/tutorials/quickstart-mdldev.rst

This PR updates the list of supported Linux distros, adds WSL as a platform, and adds Arm and PowerPC architectures to the Quickstart for Model Developers
These updates to the documentation do not require testing or reference changes/documentation that have already been tested, such as #8658

docs: Update Linux distros, add WSL, and archs to Quickstart

---

webui/react/src/pages/WorkspaceDetails.tsx

this fixes an issue where the user store would cease polling when leaving the workspace details page. we start polling the user store at 10s (up from 60s) when getting to the workspace details page. by default, the `startPolling` function returns a cleanup function that stops polling altogether on unmount, so the user store would stop polling when the user leaves the workspace details page. this fixes that by instead polling at the original amount on unmount.
- as an admin, open two windows.
- in one window, visit a workspace with projects available, in the other, visit the users page
- in the users window, edit one of the project owners of the workspace and wait about 10 seconds
- you should see the changes reflected in the workspace window
- in the workspace window, navigate to the …

fix: restore original user store poll on leaving workspace details

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/HyperparameterSearchModal.tsx
webui/react/src/components/OverviewStats.tsx

Uses an updated hew to fix a reported issue with the chart: https://github.com/determined-ai/hew/pull/99
Also fixes an issue where a Label with `rows: 1` is putting an error in the JS Console
Builds successfully, Typography change is valid

fix: Update hew for chart fix, avoid error from Typography.Label

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/App.tsx

In order to remove antd, we want to replace `antd/dist/reset.css` with something of the similar functionality. 
Dependencies tried: 
normalize.css - Does not have the style needed
sanitize.css - Works [link](https://www.npmjs.com/package/sanitize.css?activeTab=readme)
modern-normalize - Works [link](https://www.npmjs.com/package/modern-normalize?activeTab=readme) 
modern-normalize is chose over sanitize.css due to it's more actively maintained and also has smaller size.
Navigate through pages on different browsers (chrome, safari, firefox) and check that styles are expected. 
WEB-1921

chore: Replace antd reset.css with modern-normalize

---

webui/react/src/components/ExperimentIcons.tsx

[WEB-1941]
We were missing JupyterLab states, so added them for experiment icons
- Run web UI locally
- `dev.setServerAddress('https://gcloud.determined.ai')`
- login in as admin
- navigate to dashboard
- Verify that the dashboard works with `Terminated` state
[WEB-1941]: https://hpe-aiatscale.atlassian.net/browse/WEB-1941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: support `CommandState` for experiment icon

---

webui/react/src/components/FilterForm/TableFilter.tsx
webui/react/src/components/FilterForm/components/FilterGroup.tsx

This fixes the dropdown in WEB-1938.
I saw an unrelated bug in FilterForm, where tooltips from the table below appear over the form elements. We can (mostly) avoid this with `e.stopPropagation` in `onMouseMove`.
In the experiment filters, click "Add condition group", then in that row, click the "+" to see these two options. Confirm you can add conditions to filter experiments.

fix: use Hew dropdown on FilterGroup [WEB-1938]

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

In the user auth project, we only added the helm edits to EE -- this PR ports them back to OSS to standardize the oidc/saml helm config.
tldr; haran noticed that the helm changes were in EE only, but should be in OSS, plus all the user auth provisioning features hadn't been properly included there.

chore: update oss/ee oidc & saml helm config

---

docs/manage/users-remote.rst
docs/reference/deploy/master-config-reference.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

change groupsClaimName -> groupsAttributeName, and displayNameCLaimName -> displayNameAttributeName in OIDC. This standardizes the fields with OIDC
This will break EE -- so there needs to be an extra PR to be landed shortly after this is merged (& ee is rebased) that changes the relevant variable names in the OIDC ID Token Claims struct.

chore: standardize oidc/saml group & display attribute names in helm config

---

.circleci/real_config.yml
codecov.yml

Currently, Codecov coverage reports do not precisely match the coverage reports generated by Go Codecov coverage tends to be lower than Go coverage output due to Codecov's defaults to ignore LOC that are not directly within the body of a function as well as marking certain LOC as partially covered or uncovered for branches that evaluate to `false`.
This PR overwrites those defaults to bring Codecov reports inline with Go coverage reports by 
- Counting all LOC in a file (as the Go cover tool does) when calculating coverage metrics and generating reports.
- Changing lines marked by Codecov as `partial` to `hit` (so that Codecov coverage percentages are calculated to mark the code in such lines as "covered")
This PR also lowers the per-PR coverage target by 5% for Go code in the event that …

chore: codecov reports to match go coverage reports

---

docs/setup-cluster/on-prem/options/docker.rst

master moved to main; update URL to match
Update a github path we missed in the branch rename
Click the link.  Does it work?  Yes.

chore: update github path in docker docs

---

docs/setup-cluster/slurm/slurm-requirements.rst

[FE-269](https://hpe-aiatscale.atlassian.net/browse/FE-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
DeterminedAI cannot function properly on an HPC cluster with PBS if the ngpus resource is not configured properly. Add instructions to the PBS Requirements section explaining how to configure the ngpus resource.
[FE-269](https://hpe-aiatscale.atlassian.net/browse/FE-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[FE-269]: https://hpe-aiatscale.atlassian.net/browse/FE-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

docs: [FE-269] Add documentation detailing configuration steps to set the values for ngpus.

---

docs/setup-cluster/slurm/slurm-known-issues.rst
docs/setup-cluster/slurm/slurm-requirements.rst

Add a new PBS known issue "Cluster tab does not display GPU information" including a link to the PBS requirements section.
This is a follow up for the PR #8714 
Tested manually
FE-270

docs: [FE-270] add PBS known issue - Cluster tab does not display GPU information

---

master/pkg/checkpoints/local/local_checkpoints.go

Fixes an issue with local checkpoint download where file contents are relative to the root.
e2e tests
This bug fix is for unreleased code in PR https://github.com/determined-ai/determined/pull/8684.

fix: local checkpoint download path fix

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/App.tsx
webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/columns.ts
webui/react/src/pages/F_ExpList/glide-table/contextMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/checkboxCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/experimentStateCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/linkCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/loadingCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/progressCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/sparklineCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/tagsCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/textCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/userAvatarCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/index.tsx
webui/react/src/pages/F_ExpList/glide-table/menu.tsx
webui/react/src/pages/F_ExpList/glide-table/tooltip.tsx
webui/react/src/pages/F_ExpList/glide-table/utils.ts

After conversation with glide-table-grid maintainer, our changes are resolved as of the recent v6 release.
Updated locations of types in modules
Ongoing issue: the checkbox is rendered in purple for a moment before it switches to the select color
- Successful web build
- Interactive table loads correctly
- Checkmarks work correctly (test on small project such as /det/projects/31/experiments )

chore: Move from internal glide-table-grid to v6.0.0 [WEB-1945]

---

webui/react/src/ee/SamlAuth.test.ts
webui/react/src/ee/SamlAuth.ts
webui/react/src/pages/SignOut.tsx

Currently in MLDE we accept a `redirect` parameter when visiting the sign in page, after signing in the user will be auto-redirected to that page. However, today it is not possible to preserve a `redirect` from the `logout` page. This actually makes it impossible to sign a user out from an `outside url` and then redirect them back to the `outside url`.
1. Visit the logout url with a `?redirect=<some url>`
2. Ensure you are redirected to the sign in page with the `?redirect=<some url>` preserved.
3. After signing in, ensure that you are redirected to `<some url>`
The ultimate issue is that isAuthenticated (https://github.com/determined-ai/determined/blob/main/webui/react/src/pages/SignIn.tsx#L39) can never be set to false after logging in if a user is not on MLDE. You can test this on a …

feat: Preserve 'redirect' query during logout [GAS-489]

---

master/internal/core.go

[WEB-1870]
The response data from (almost?) all determined AI API endpoints were not compressed at all, so that caused long response time with `Fast 3G network` (look at `Content download` time). 
Especially,  `experiments-search` API usually returns big data, so this PR improve the page loading time around **10x**.
---
---
- Check if API data are compressed
- Check if there's `Content-Encoding: gzip` in response header
- Check if `js/css/html` files are still compressed
[WEB-1870]: https://hpe-aiatscale.atlassian.net/browse/WEB-1870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: compress data from API for the page load performance improvement
