webui/react/src/components/NavigationSideBar.module.scss
webui/react/src/components/kit/Nameplate.module.scss
webui/react/src/components/kit/Nameplate.tsx

[WEB-1415]
- Check if a long text doesnt overflow in places where `Nameplate` component is used
- top of nav bar, select in add member modal, user select in group management modal
- For the select component, when text overflows, text should have ellipsis
- Check if it works fine with/without display name (only username)
[WEB-1415]: https://hpe-aiatscale.atlassian.net/browse/WEB-1415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: handle long values

---

.circleci/config.yml

Previously split these off while figuring out how we could deal with them not being immediately runnable by fork PRs.
Bringing them back in so they're required again for our PRs as they were before.

ci(circle/test-unit): regroup gpu unit tests

---

harness/determined/cli/render.py

chore: use det custom json encoder in print_json

---

e2e_tests/tests/command/test_notebook.py
harness/determined/cli/dev.py
harness/determined/common/api/__init__.py
harness/determined/common/api/_util.py
harness/determined/common/api/request.py
harness/tests/common/test_api.py
master/internal/core.go

the original `make_url` utility used to handle some unexpected `path` arguments passed
where the update version did not and this was letting some misusage of `make_url` to work which updating
the utility revealed.
- provide and log more info when requests fail to match an api handler
- revert default make_url to the old implementation where it was forgiving of bad path parameters in some cases.
- add a test for accessing notebooks through proxy
- explicitly reject paths parameters set as absolute 
to avoid having to audit every usage of make_url and requests throughout the system we put back the original implementation and provide the new make_url as a new option to gradually adopt. …

chore: update make_url utility with fallback

---

master/internal/db/postgres_trial.go
master/internal/db/postgres_trial_intg_test.go
master/internal/db/postgres_trial_metrics.go
master/internal/db/postgres_trial_metrics_test.go

chore: clean up comments in trial and metric code

---

webui/react/src/hooks/useMetricNames.ts
webui/react/src/pages/TrialDetails/TrialChart.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts
webui/react/src/services/types.ts

Fixes an issue where we would show `no data` on the experiment overview page even though the UI was already showing metrics that had been received on the chart.
While debugging this error I found another bug on the experiment overview page reported here: https://hpe-aiatscale.atlassian.net/browse/WEB-1444
1. Fork or create an experiment.
2. Once the experiment is running view the experiment overview page. Ensure that once a single metric has been reported the chart never shows "No data to plot" afterwards.
WEB-1393

fix: Metrics reporting no data

---

webui/react/src/components/FilterForm/TableFilter.tsx

[WEB-1425]
- Check if a condition is added if filter is empty in a new experience table
Found [useSettings bug](https://hpe-aiatscale.slack.com/archives/CKQ3EV0G6/p1689117218241409). useSettings doesn't return the stored settings data at first somehow. Even if the data for filter is fetched, it is not loaded immediately, but it is not related to this PR.
[WEB-1425]: https://hpe-aiatscale.atlassian.net/browse/WEB-1425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add condition by default in filter

---

requirements.txt

[INFENG-210]
[INFENG-210]: https://hpe-aiatscale.atlassian.net/browse/INFENG-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: bump up flake8 to 3.9.2

---

master/internal/api_project.go

With rbac enabled,
Go to the new experiment list table with non-global permission, `/columns` API should return with no error.
WEB-1448

fix: permission filtering on columns API

---

examples/hf_trainer_api/hf_image_classification/deepspeed.yaml
examples/hf_trainer_api/hf_language_modeling/deepspeed.yaml

Adds `--fp16` flags to the entrypoints of our HuggingFace Trainer examples when using DeepSpeed, in order to use the more-efficient mixed-precision training.
`cd` into both examples under `/examples/hf_trainer_api/` and verify that the experiments will run without erroring via `det e create deepspeed.yaml .`. If a CUDA out-of-memory error is hit, try reducing the `--per_device_train_batch_size 8` value in the `entrypoint`.

fix: add fp16 flags to hf ds examples

---

.circleci/config.yml

Updates GKE cluster version per https://cloud.google.com/kubernetes-engine/docs/release-notes#2023-r15_version_updates
1.25.8 is no longer available as of July 07, 2023
CI Manages to create GKE cluster with correct version

ci: Fix GKE cluster version used for CircleCI

---

harness/determined/common/experimental/trial.py
harness/tests/determined/common/experimental/test_determined.py

Trial now has a `state` that is populated when constructed `_from_bindings` or when explicitly `reload`ed.
[MLG-668]
With
```python
from determined.common.experimental import trial
```
Create a Trial via `client.get_experiment(<exp_id>).get_trials` or via `trial.Trial`. If the latter, call `reload`. Observe that `state` is set.
[MLG-668]: https://hpe-aiatscale.atlassian.net/browse/MLG-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Expose trial state to Trial

---

harness/determined/common/experimental/workspace.py
harness/tests/determined/common/experimental/test_workspace.py
harness/tests/fixtures/api_responses.py
harness/tests/fixtures/workspace.json

New class for workspaces within the SDK.
Create them from IDs! Create them from names! Create all the workspaces!
Mostly just a stub class at this point.
Create a Workspace in the SDK with the constructor `determined.common.experimental.workspace.Workspace`. Call `reload` on it. There isn't much functionality in workspaces yet and not much to see, but if you figure out how to change the workspace's name then reloading will populate that to the client.
Also, maybe test constructing the Workspace via names that do/don't exist. Can master have two different workspaces with the same name (I don't think it can)? What would happen?

chore: Workspace as an object in the SDK.

---

docs/_templates/page.html
docs/_templates/search-field.html
docs/conf.py
docs/index.rst

UPDATE: Getting the Web section ID is still in progress. Will land this for now but there is a dedicated field for it when we get it.
Apply missing metadata tags.
- Metadata tag for "Description" is missing, please add it. 
- Metadata tag for "Design version" is missing, please add it. 
- Metadata tag for "IE compatibility" is missing, please add it. 
- Metadata tag for "Keywords" is missing, please add it. 
- Metadata tag for "Lifecycle" is missing, please add it. 
- Metadata tag for "Robots" is missing, please add it. 
- Metadata tag for "Segment" is missing, please add it. 
- Metadata tag for "Target country" is missing, please add it. 
- Metadata tag for "Web section ID" is missing, please add it. [Blocked]
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs …

docs: hpe docs compliance for section 5 [WEB-1292]

---

docs/release-notes/6735-add-tls-to-notebooks.rst

chore: add release notes for notebook tls

---

webui/react/src/pages/F_ExpList/CompareMetrics.tsx
webui/react/src/pages/F_ExpList/CompareParallelCoordinates.tsx
webui/react/src/pages/F_ExpList/ComparisonView.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

The `ComparisonView` has been updated to no longer unmount components when tabs change. Additionally the `useTrialMetrics` hook has been moved into the `ComparisonView` to avoid making duplicate API calls. 
1. Navigate to the `Compare` view and then the `HyperParameters` tab without an experiments selected.
2. Select a few experiments that do have metrics in the left selection pane. Ensure the parallel coordinates chart renders correctly. 
3. Switch the the `Metrics` tab, confirm that the metric data has already loaded. The charts should already be showing data, no charts should be in the loading state. 
4. Select and de-select a few experiments, ensure that the metrics charts render correctly. /
5. Switch to the `Hyperparameters` tab. Confirm the parallel coordinates chart is already …

chore: change compare tab refresh behavior [WEB-1434]

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/App.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/columns.ts
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/checkboxCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/experimentStateCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/linkCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/loadingCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/progressCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/sparklineCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/tagsCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/userAvatarCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/index.tsx
webui/react/src/pages/F_ExpList/glide-table/menu.tsx
webui/react/src/pages/F_ExpList/glide-table/tooltip.tsx
webui/react/src/pages/F_ExpList/glide-table/utils.ts

Not technically a "fix" as it was just simply not supported by the original `glide-grid-table` library. The library simply chose to skip the ability to measure the cell size when it's a custom defined cell type. This PR achieves the expected behavior by doing the following:
1. fork the `glide-grid-table` into [our own](https://github.com/determined-ai/glide-data-grid) and making the changes (until `glide-grid-table` decides to accept our PR of resolving this)
2. publish the fork on [npmjs.com](https://www.npmjs.com/package/@glideapps/glide-data-grid?activeTab=code)
3. update our custom cells to provide a `measure` function to provide dynamically calculated widths for the cell
- navigate to experiment list view `?f_explist_v2=on` query param if still applicable
- add a variety of different …

fix: custom column resize [WEB-1341]

---

docs/release-notes.rst
docs/release-notes/6735-add-tls-to-notebooks.rst
docs/release-notes/7278-remove-log-option.rst
docs/release-notes/removed_config_endpoint.rst

docs: add release notes for 0.23.3

---

master/internal/api_resourcepool.go
master/internal/workspace/postgres_workspace.go

Add support for workspace names as a parameter to some endpoints. 
Create a bunch of workspaces as admin user. Open the swagger API and try to bind, unbind, and overwrite rp<>workspace bindings with both workspace IDs and workspace names.

fix: workspace mapping workspace names handlers

---

docs/setup-cluster/security/rbac.rst

docs: remove RBAC limitations section

---

webui/react/src/components/ResourcePoolCard.tsx

Moved from fork branch PR #7396 

fix: label default compute and default aux pools differently (FE-108)

---

master/internal/authz/obfuscate.go

In addition to current obfuscated information in Agent summaries, this PR obfuscates slot id's in agent summaries for users who do not have access to sensitive agent information.
- Confirm that when a non-ClusterAdmin user access /api/v1/agents the slot id's are replaced with randomized UUIDs in the response.

feat: obfuscates slot id in agent summary for non-admins

---

webui/react/src/pages/TrialDetails/useTrialMetrics.ts

[WEB-1336]
- Check if there's no `maximum update` warnings after unselect all boxes (select multiple boxes in advance)
- Initial rendering is already less than 15 times in `F_ExperimentList.tsx` before the PR, so fixed `maximum update` warnings  since it causes additional rending
[WEB-1336]: https://hpe-aiatscale.atlassian.net/browse/WEB-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: perf improvement in `useTrialMetrics`

---

harness/determined/cli/user.py

try to change user's password and give mismatching inputs. check the exit code to != 0

chore: fail with non-zero exit code when password change fails

---

docs/interfaces/tensorboard.rst

[MLG-333] Add documentation to explain how to pass in optional tensorboard arguments.
`make live` in docs folder
Verified that changes showed up as expected
MLG-333
[MLG-333]: https://hpe-aiatscale.atlassian.net/browse/MLG-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add documentation about passing in optional tensorboard arguments [MLG-333]

---

docs/release-notes/9355-allow-security-context
master/internal/rm/kubernetesrm/spec.go
master/pkg/model/environment_config.go

feat: allow-pachyderm-notebook-extension [DET-9355]

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/utils.ts

Distinguish hover state for selected rows.
BEFORE:
AFTER:
WEB-1385

style: apply hover color for selected table rows [WEB-1385]

---

webui/react/src/components/kit/Icon.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx

Use different icons for compare view on or off.
Navigate to new experiment list. 
Toggle `Compare`, icon should show the status of on or off. 
WEB-1427

feat: Compare icon reflects status

---

docs/interfaces/tensorboard.rst
examples/features/torch_batch_process_embeddings/bert_embedding_generation.py

- Change Chroma client used to PersistentClient to enable persisting vector database to a directory (the original code was the older version of the API).
- As persisting can take a long time, changing dataset size such that the example finishes in a shorter amount of time.
coverage run -m pytest -vv --capture=tee-sys --disable-warnings --master-host="<HOST_ADDR>" --master-port="8080" --durations=0 tests/nightly/test_distributed.py::test_torch_batch_process_generate_embedding

feat: minor edit to torch batch process embedding example

---

docs/index.rst

Update docs Web Section ID in the metadata section to our new value: `R12299`

chore: update docs hpe compliance web section id

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/ColumnPickerMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
webui/react/src/pages/F_ExpList/glide-table/columns.ts

Make it easier for users to pin/unpin columns when the compare view is active. 
Navigate to new experiment list. 
Pin/Unpin columns should work as expected. 
Open compare view, column picker should only check pinned (visible) columns.
With compare view open, check/uncheck columns should pin/unpin columns. 
https://github.com/determined-ai/determined/assets/40620519/080ce957-709d-47f3-ac96-d3e40124ac8a
`Show/hide all` and `reset` are hidden for now when compare view is open to minimize confusion.
WEB-1424

feat: Pin column when compare panel open

---

master/internal/rm/kubernetesrm/spec.go

A previous merged [PR](https://github.com/determined-ai/determined/pull/7395) caused a CI issue. I forgot to do a nil check. Here's the fix.

chore: podspec-capability-bugfix

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization/ExperimentVisualizationFilters.tsx

[WEB-1439]
- Check if width is wide enough when `1` is selected 
[WEB-1439]: https://hpe-aiatscale.atlassian.net/browse/WEB-1439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: wider width for `top trials` select

---

harness/determined/common/experimental/determined.py
harness/determined/common/experimental/experiment.py
harness/tests/determined/common/experimental/test_determined.py
harness/tests/fixtures/api_responses.py
harness/tests/fixtures/experiments.json

Adds method to get multiple experiments to the top-level SDK client.
ensure that `list_experiments` correctly filters and returns experiments according to specified parameters. 
```
client.list_experiments(
sort_by: Optional[experiment.ExperimentSortBy] = None,
order_by: Optional[experiment.ExperimentOrderBy] = None,
experiment_ids: Optional[List[int]] = None,
labels: Optional[List[str]] = None,
users: Optional[List[str]] = None,
states: Optional[List[experiment.ExperimentState]] = None,
name: Optional[str] = None,
project_id: Optional[int] = None,
limit: Optional[int] = None,
)
```
calling `client.list_experiments()` with no parameters should return all experiments on the determined master.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/READM …

feat: add list_experiments to Python SDK [MLG-670]

---

harness/determined/cli/resource_pool.py
master/internal/core_experiment.go
master/internal/experiment.go
master/internal/workspace/postgres_workspace.go

Dogfooding revealed a few problems that can be easily fixed. these include:
- experiments not using the proper workspaceID
- webUI not binding workspaces to resource pools
- CLI for rp bindings should not list pools by default

fix: rp-workspace mapping dogfooding fixes

---

master/internal/api_resourcepool.go
master/internal/db/postgres_rp_workspace_bindings.go
master/internal/rm/authz_basic_impl.go
master/internal/rm/authz_iface.go
master/internal/workspace/postgres_workspace.go

Refactors several areas for ease of use:
- `FilterResourcePools` has been changed to accept a list of workspaceIDs that the user has access to. This makes it easier to implement the underlying function
- `AllWorkspaces` has been added to return all the workspaces currently in the workspaces table. This is called inside `GetResourcePools` to fulfill the above change `FilterResourcePools` function.
- `GetUnboundRPs` has been refactored to take in a string instead of resource pools so that it can be used inside `FilterResourcePools`.

chore: rp<>workspace mapping refactor rm authz interface

---

webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx
webui/react/src/pages/Clusters/ClustersQueuedChart.tsx

Experiment queued time can sometime be very long, long values should display properly.
Before:
After:

fix: chart axis long label 

---

e2e_tests/pytest.ini
e2e_tests/tests/cluster/test_groups.py
e2e_tests/tests/cluster/test_rbac.py
e2e_tests/tests/conftest.py

Moved several tests that test permissions-related features from `e2e_cpu` to `e2e_cpu_rbac`. We don't care about these tests' success in OSS, so let's not run them there.
We've previously relied on querying the backing master to see if RBAC is enabled, but that gate has proven brittle. It's also more complicated than is strictly necessary.
I've changed the mark but have not removed them from OSS so as to avoid rebasing headaches.
[MLG-454]
[MLG-454]: https://hpe-aiatscale.atlassian.net/browse/MLG-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: mark RBAC-related tests 'e2e_cpu_rbac'

---

master/static/migrations/20230718141429_migrate-checkpointv1.tx.up.sql

Avoid needing users to install the uuid extension.
Ran manually.

chore: avoid postgres uuid extension

---

webui/react/src/hooks/useFeature.ts

chore: Turn new experiment listing off by default

---

docs/setup-cluster/workspaces-rpools.rst

Add the proper CLI commands and clarifying statements.

docs: update CLI for rp workspace mapping

---

harness/determined/deploy/aws/injector/master.yaml.tmpl
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml

This branch started as me trying to test my failing e2e-cpu-distributed tests on main to see if they were working, but then I realized they were newly broken on main, too. 
the multiple injectors in det deploy aws are.. kinda nuts

ci(aws): fix RDS connections

---

webui/react/src/pages/ExperimentList.settings.ts
webui/react/src/pages/ExperimentList.tsx

related: #7373
- Check if `checkCount` to `checkpoints` in old exp table's column pickup modal
- Check if useSettings for `checkpoints` works as expected 

fix: rename `checkCount` to `checkpoints`

---

docs/model-dev-guide/batch-processing/batch-process-api-ug.rst

Add a link to an example to the user guide.

docs: Add torch batch process example

---

webui/react/src/components/ResourcePoolCard.tsx
webui/react/src/hooks/usePermissions.ts
webui/react/src/pages/ResourcepoolDetail.tsx

The `UPDATEMASTERCONFIG` permission is currently being overloaded to limit resource bool binding management to cluster admins. This pr makes that limitation apply to the web as well.

fix: only let cluster admins manage resource pool bindings [WEB-1476]

---

webui/react/src/components/SplitPane.tsx

Fix the issue compare panel was no longer draggable.
Turns out that `useMobile` initially returns `true` then `false` on desktop, so the `ref` was not correctly assigned.
Navigate to experiment list, open compare panel, should be able to drag and resize compare panel. 
WEB-1487

fix: compare panel resize

---

webui/react/src/components/kit/internal/UPlot/UPlotChart/tooltipsPlugin.ts

Chart tooltip overflow due to the calculated position can be smaller than 0.
Before:
After:
WEB-1486

fix: chart tooltip overflow

---

master/internal/api_resourcepool.go
master/internal/api_workspace.go
webui/react/src/hooks/useFeature.ts

Address 3 issues that come up with rp workspace mapping:
- workspaces get unbound if trying to bind via the webUI
- default resource pools don't get set when editing workspaces from the CLI
- rp workspace binding is not turned on by default

fix: rp workspace mapping not working

---

webui/react/src/components/kit/LineChart.module.scss
webui/react/src/components/kit/LineChart.tsx
webui/react/src/pages/F_ExpList/CompareMetrics.tsx

Reduce spacing between Charts (each Chart now has 6px spacing on all four sides)
Expand Charts element to fill full height of the page
Before:
After:
On Experiment List page, select experiments and view Metrics tab in Compare view. Make sure the spacing 1) below each card and 2) below all cards matches the "After" screenshot above. Verify that scrolling charts below the available space still works.
Make sure ChartGrid on DesignKit page also still looks and functions correctly.
WEB-1483

fix: ChartGrid styling

---

webui/react/src/hooks/useMetricNames.ts
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
webui/react/src/pages/F_ExpList/CompareParallelCoordinates.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts

[WEB-1479], [WEB-1482]
- if no trials exist for all of the selected experiments, show a consistent empty state of `No data to display`
- Check if showing `No data to display` in experiments with multi trials when state is `Error`
[WEB-1479]: https://hpe-aiatscale.atlassian.net/browse/WEB-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1482]: https://hpe-aiatscale.atlassian.net/browse/WEB-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: stop showing invalid loading

---

docs/setup-cluster/workspaces-rpools.rst

docs: add limitations to rp bindings docs

---

docs/setup-cluster/deploy-cluster/slurm/slurm-known-issues.rst
docs/setup-cluster/deploy-cluster/slurm/slurm-requirements.rst

It was recently discovered that the PBS configuration option `job_history_enable` must be set to `True` in order for the HPC launcher to detect job status correctly. The appropriate changes have already been made to the Launcher codebase, so the docs are now being updated to reflect the newfound requirement.
CircleCI testing pipeline will provide sufficient coverage.
FE-120

docs: FE-120: Add `job_history_enable = True` to PBS installation requirements

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/pages/F_ExpList/ComparisonView.tsx

[WEB-1502]
- Check if the new exp page doesn't crash
-  after selecting some experiments
- Select Hyperparameters page and create a range
- Select Details page or Metrics page
- Unselect one experiment
- No `unexpected application error` shown
[WEB-1502]: https://hpe-aiatscale.atlassian.net/browse/WEB-1502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: avoid crashing the new exp page

---

docs/release-notes/7561-rp-workspace-mapping.rst

docs: rp workspace mapping release notes

---

master/internal/experiment_filter.go

[WEB-1509]
- Check if `Searcher Metric` filter returns the right data correctly in the new experiments filter
[WEB-1509]: https://hpe-aiatscale.atlassian.net/browse/WEB-1509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: support `searcherMetric` in experiment filter

---

webui/react/src/pages/F_ExpList/glide-table/TableActionBar.module.scss
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx

No selection
Partial selection
All selection
WEB-1510

style: update experiment selection label [WEB-1510]

---

webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
webui/react/src/types.ts

style: update copy and add dividers to exp list table action dropdown [WEB-1490]

---

webui/react/package-lock.json

Resolving complaints from `npm install` audit warnings

chore: update vite and other security issue packages

---

harness/determined/common/experimental/experiment.py
harness/tests/determined/common/experimental/test_experiment.py

Adds attributes (name, description, archived, notes, progress) to SDK's Experiment and a subset of setters.
- create an experiment, and fetch it in python SDK:
```
exp = client.get_experiment(1)
```
- verify that `exp.[name, description, archived, progress, notes]` are present (if set) on experiment
- verify that `set_[name, description, notes]` sets the corresponding property on exp.[name, description, notes]`

feat: add experiment attributes to SDK Experiment [MLG-738]

---

harness/determined/pytorch/_data.py

Rollback torch 1.7 support change https://github.com/determined-ai/determined/pull/7515/commits/43e36bfe2a12621052d149c9558473e008d96ba9
because supporting torch 1.7 is cheap https://github.com/determined-ai/determined/pull/7515#discussion_r1279935915

chore: rollback torch 1.7 support removal.

---

webui/react/src/components/FilterForm/components/FilterField.module.scss
webui/react/src/components/FilterForm/components/FilterForm.module.scss

https://hpe-aiatscale.slack.com/archives/CKQ3EV0G6/p1690902343156009
- Check if horizontal scrollbar is not visible on desktop (Safari, Firefox, Chrome)
- Check if filter is horizontally scrollable on mobile
- Check if filter is vertically scrollable on desktop and mobile

fix: filter scrollbar adjustment

---

webui/react/src/components/ResourcePoolBindings.tsx
webui/react/src/components/ResourcePoolCard.tsx
webui/react/src/components/kit/Card.tsx
webui/react/src/pages/ResourcepoolDetail.tsx

This PR disables the option bring up the Manage Bindings modal for default resource pools, as well as removing the requirement for RBAC to be enabled to use the feature.
Ensure that Manage Bindings button/menu option is disabled for default resource pool.

fix: disable Manage Bindings option for default pools [WEB-1521]

---

master/internal/core_experiment.go

During experiment submission, we were using the project ID defined in the request, which is not always set. This fixes the behavior by using a function that properly resolves the project/workspace in the config OR in from the request.

fix: use proper experiment project resolution

---

master/internal/api_resourcepool.go
master/internal/config/resource_config.go

default pools doesn't work in slurm because they don't always use configs. This refactors the code to use the resource manager resource pool functions and modularizes parts of the api handlers.

fix: fix default pools and refactor

---

agent/pkg/singularity/singularity.go

Rollback usage of --nvccli while we work on the aizn test environment.

chore: temporarily rollback agent usage of --nvccli 

---

webui/react/src/components/ResourcePoolBindingModal.tsx

chore: add copy to manage bindings modal

---

docs/setup-cluster/deploy-cluster/gcp/install-gcp.rst

Docs have drifted out of sync with the code.

docs: correct some `det deploy gcp` docs facts.

---

docs/architecture/introduction.rst
docs/model-dev-guide/dtrain/config-templates.rst

docs: apply minor tweaks

---

master/internal/api_checkpoint.go
master/internal/api_experiment.go
master/internal/checkpoint_gc.go
master/internal/checkpoint_gc_test.go
master/internal/db/postgres_test_utils.go
master/internal/experiment.go
master/pkg/actor/actors/nothing.go

Refactor checkpoint GC away from actors. It is just a function now!
So sick.

chore(actors): refactor checkpoint GC without actors

---

webui/react/package-lock.json
webui/react/package.json

Fixes an issue where pressing and holding a column header in the Glide Table would cause the table to scroll up or down. 
For information on how we are handling the package versioning four our glide table fork you may read [Dependency Forks](https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1368162327/Dependency+Forks#Publishing-Packages)
https://github.com/determined-ai/determined/assets/103522725/0b7506e1-50f6-415d-a0d8-cbbcadf72eab
1. On the experiment list page scroll to the middle of the Glide Table. You cannot already be at the top of the table to test this functionality since the table needs space to scroll up. 
2. Click and hold a column header, ensure that the table does not scroll up. 
3. Click and hold a column header and move the mouse around the page, the table …

fix: scrolling when dragging column headers in Glide Table

---

proto/pkg/jobv1/job.pb.go
proto/src/determined/job/v1/job.proto
webui/react/src/services/api-ts-sdk/api.ts

fix: correct name for external jobs.
Minor changes that was missed in the previous PR #7070 
NA
[FE-23](https://hpe-aiatscale.atlassian.net/browse/FE-23)
DET-9007
[FE-23]: https://hpe-aiatscale.atlassian.net/browse/FE-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: correct name for external jobs

---

master/internal/db/postgres_rp_workspace_bindings.go

The overwrite endpoint previously assumed that bindings would be overwritten with other ones, and that bulk deletion would occur via the remove bindings endpoint. The length check was unnecessary to begin with and prevents empty lists from being considered valid inputs. Removing the length check now allows the overwrite endpoint to treat an empty list as a bulk deletion.

fix: rp binding fix overwrite [WEB-1529]

---

webui/react/src/components/NavigationTabbar.tsx

[WEB-1500]
- Check if `Cluster logs` is not in the list on mobile view
[WEB-1500]: https://hpe-aiatscale.atlassian.net/browse/WEB-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide `cluster logs` in mobile view

---

.github/CODEOWNERS

This adds the web team as codeowner for the /webui directory.
N/A
No Ticket

chore: Add web as codeowner for /webui

---

webui/react/src/ioTypes.ts
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
webui/react/src/types.ts

Now that generic metrics landed on the backend, update frontend to handle them.
WEB-1538

chore: update type to handle generic summary metric types [WEB-1538]

---

master/internal/api_agents.go
master/internal/mocks/rm.go
master/internal/rm/actorrm/actor_resource_manager.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/resource_manager_iface.go

This change is require to refactor the resource managers to non-actors, since otherwise we need a mock actor in front of the new impl to receive these requests.
DET-9729

chore(rm): refactor cluster management APIs into RM

---

docs/release-notes/README.md

Add formatting pointers to the Release Notes "readme" file.

docs: Edit the release notes readme

---

harness/determined/common/api/errors.py

Previously, the body of an APIException was parsed as a JSON object and a message string was parsed from the result to be the exception's message. Currently, though:
the only key present in an APIException's body is error (not message)
the error value is a JSON-encoded dict, not a string.
This change now pulls out the "error" when possible and encodes the result in a formatted string that becomes the exception's message.
[MLG-454]
Perform some operations that result in an `APIException`. One such means, documented in [MLG-454], in to create an experiment with a bag experiment config. But `APIException`s are generally pretty common -- most "you did something wrong" errors that aren't 404s. Try, for example, "unarchiving" an experiment that isn't archived. Let your imagination run wild.
See …

chore: Parse and format APIExceptions

---

harness/tests/requirements/requirements-harness.txt

Responses has been patched with v0.23.3 to move its urllib3 lower bound back to "1.25.10", meaning newer versions are safe again to use.
[Unit tests](https://app.circleci.com/pipelines/github/determined-ai/determined/42861/workflows/4ca58431-b575-49af-9339-e7c938bdda9d) succeed with responses==0.23.3.

test: unpinning responses

---

webui/react/src/components/PageHeaderFoldable.module.scss
webui/react/src/components/kit/Button.module.scss
webui/react/src/components/kit/Button.tsx
webui/react/src/pages/DesignKit.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx

Spacing between icon and text in some buttons is too small. 
Before:
After: 
On new Experiment List page and DesignKit page, make sure all buttons have spacing between icon and text.
WEB-1472
WEB-1511

fix: Button icon spacing

---

docs/release-notes/README.md

These were suggested on #7572 but seem to have been accidentally reverted before merge.

docs: edit release notes readme

---

docs/architecture/introduction.rst

docs: fix lint for docs/architecture/introduction.rst

---

harness/determined/pytorch/_trainer.py

docs: update doc string related to adding enable_tensorboard_logging flag

---

webui/react/src/components/ExperimentMoveModal.tsx

[WEB-1267]
- Create a new project
- (Without refreshing pages) Go to an experiment and open move modal
- The newly created project should be in the project list for move destination
[WEB-1267]: https://hpe-aiatscale.atlassian.net/browse/WEB-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fetch the latest projects

---

master/internal/db/postgres_experiments.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_test_utils.go

Checkpoint garbage collection was incorrectly deleting all the checkpoints except the checkpoint from the latest trial. It was fixed by changing the sql query that determines the checkpoints to be deleted.
Create a few experiments with different configurations for garbage collection, and make sure the checkpoints saved are consistent with those configurations.
DET-9702

fix: fix checkpoint gc which was incorrectly deleting checkpoints [DET-9702]

---

master/internal/checkpoint_gc.go

Since the `checkpoint_gc` actor doesn't exist, this actor doesn't get created. This causes RMs to crash, since they always expect a group actor to exist.
I thought `ok == false` was only returned when the actor already existed, my b. Though, this is an example of a terrible API imo -- multiple failure cases coalesced into a single bool return with no error context.

fix(actors): create valid fake group actor for checkpoint GC, don't leak it

---

docs/release-notes/remove_ptladapter.rst

make a release note more consistent with the style guide

docs: improve a release note

---

master/internal/mocks/allocationmocks/allocation_service.go
master/internal/task/allocation_service.go
master/internal/task/allocation_service_iface.go
master/internal/trial.go

Introduction of the AllocationService changed ownership of an allocation from the
task that started it to the service. This causes issues because if the trial ends before
the allocation, the group may be unregistered by the experiment and cause RMs to
panic when trying to find the group associated with an RM scheduling.
This was pretty hard to find, you need to panic in trial.go, have experiment exit before the
allocation, and have something get scheduled before the allocation exits.

fix(actors): trial lifetime must contain allocation lifetime, still

---

webui/react/src/components/ColumnsCustomizeModal.test.tsx
webui/react/src/components/Transfer.tsx

fix: avoid converting workspace name to sentence casing [WEB-1548]

---

webui/react/src/components/FilterForm/TableFilter.tsx

Minor fix for spacing between words in Filter button
Filter and Sort buttons should have equal spacing between words

fix: filter button text

---

.github/workflows/lint-secrets.yml

* The say command is (finally) no longer required. :) https://github.com/awslabs/git-secrets/pull/221/files
* Use a variable to represent tempdir (DRY)
* Only check out one revision of secrets tool, not all
* Switch to checking out current main/master, since upstream doesn't consistently tag releases
See if this job works on this PR. :)

ci: remove "say" workaround and update version

---

docs/requirements.txt

The new version supports the recently added tabs extension.

docs: bump rstfmt version

---

webui/react/src/hooks/useSettings.ts
webui/react/src/stores/userSettings.tsx

ISSUE: the payload for the API call to clear out the user settings in the database is incorrectly set up.
WEB-1559

fix: properly clear out the settings from the database [WEB-1559]

---

webui/react/src/components/ResourcePoolBindingModal.tsx
webui/react/src/components/Transfer.tsx
webui/react/src/stores/workspaces.tsx
webui/react/src/utils/sort.ts

- Alphabetically sort the workspaces with the exception of `Uncategorized` workspace to be pinned at the top.
- Update search placeholder to be "Search workspaces"
BEFORE:
AFTER:
WEB-1552
WEB-1553

fix: alphabetical binding workspaces and search copy change [WEB-1552, WEB-1553]

---

webui/react/src/services/decoder.ts

Detecting and parsing metric values as a float (from a string) is a temporary measure that is no longer needed, now that the values are expected to come through as numbers.
WEB-1564

chore: remove unused parseFloat for decoding string metric values [WEB-1564]

---

webui/react/src/components/FilterForm/components/FilterField.tsx
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/ExperimentVisualizationFilters.tsx
webui/react/src/pages/F_ExpList/glide-table/MultiSortMenu.tsx

- [WEB-1440]
- [Slack](https://hpe-aiatscale.slack.com/archives/CKQ3EV0G6/p1691609405528689)
- Check if select component width is wide enough to see the text
[WEB-1440]: https://hpe-aiatscale.atlassian.net/browse/WEB-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: select component width

---

webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx

avoid creating new metric columns for metric groups we won't have metrics for through the workloads api
select metrics from non-legacy metric groups and these shouldn't lead to new columns in the workloads table
unsuported columns don't get added:

chore: avoid creating new table columns for non-legacy metrics

---

master/internal/api_workspace.go

I had a sudden realization that the comment was not very accurate. This amends the statement with different wording to make it better.

chore: update error message to be more accurate

---

docs/articles/viewing-epoch-based-metrics.rst

fix for the 0.24.0 release
the second code snippet has been fixed and is correct with this PR

docs: fix epoch metrics article

---

webui/react/src/utils/metric.ts

[WEB-1571]
- Check if application does not die even though `validation` or `training` property is not in object, or object is `undefined`
- Usually these properties are missing in queued/error experiments
[WEB-1571]: https://hpe-aiatscale.atlassian.net/browse/WEB-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: optional chaining in `extractMetricValue`

---

master/internal/db/postgres_experiments.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_test_utils.go

Replaced old test with table driven tests with more coverage than before that test all 8 configurations of GC collection settings and fixed a previous change that prevented checkpoints from being GCed if they didn't have validation metrics.
Made sure that the previous tests and the new tests were passing at the same time.

fix: allow checkpoints to be GCed without validation metrics and add tests

---

docs/integrations/pachyderm/pachyderm.rst

Fix formatting on pachyderm page

docs: Fix formatting

---

webui/react/src/pages/Admin/UserManagement.tsx

This fixes an issue in client-side user search. The search should be case-insensitive and allow matches in both username or display name.
On `/det/admin/user-management`, filter usernames by an uppercase letter or a lowercase letter.
- The results should be the same
- Username and display name should be included

fix: Case-insensitive client-side username search [DET-9770]

---

docs/release-notes.rst
docs/release-notes/list-user-remote.rst
docs/release-notes/pytorch2.rst
docs/release-notes/remove_ptladapter.rst

docs: add release notes for 0.24.0

---

webui/react/src/pages/Admin/UserManagement.tsx

this fixes an issue where entering some non-alphanumeric characters in the user management user filter would cause unintended behavior. For example, filtering on '.' would cause all users to be shown, and entering a unclosed bracket or paren would cause the ui to crash. We instead escape all possible special characters so they're matched literally.
regex character behavior:
1) on the user management page, filter the users by `.`
2) only users with `.` in their username or display name should show
only valid regexes shown:
1) on the user management page, filter the users by `[`
2) the ui should not crash.

fix: allow special characters in user manangement filter

---

webui/react/src/components/kit/Drawer.tsx

Allow mask/overlay click to dismiss the drawer.
WEB-1572

chore: enable mask closable by default for drawers

---

README.md

Incorporates suggestions by @tara-det-ai 
View the readme here: https://github.com/determined-ai/determined/tree/KevinMusgrave/readme2

docs: Improve writing of the github readme

---

docs/release-notes.rst

Apply formatting and remove old file that was somehow emptied instead of deleted.
n/a

docs: fix new release notes

---

harness/determined/common/experimental/experiment.py
harness/tests/determined/common/experimental/test_experiment.py

Adds functionality to download code archive to local machine for Python SDK experiments.
Create an experiment. Then, with a Python SDK experiment resource:
`exp = client.get_experiment(id=1)`
`filepath = exp.download_code()`
`filepath = exp.download_code("~/tmp")`

feat: add download code method for Python SDK experiment [MLG-838]

---

master/pkg/syncx/mapx/mapx.go

Fixing outstanding errors in the previous PR #7669
TBD
[FE-23](https://hpe-aiatscale.atlassian.net/browse/FE-23)
[FE-23]: https://hpe-aiatscale.atlassian.net/browse/FE-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: correct outstanding error in mapx

---

webui/react/src/utils/jupyter.ts

[WEB-1563]
- Check if error message is the error message itself in a wprkspace with RBAC
[WEB-1563]: https://hpe-aiatscale.atlassian.net/browse/WEB-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: error message in jupyter

---

master/internal/api_resourcepool_intg_test.go

I must have missed this during rebase - tests are now flaky because the order of the workspace IDs is not guaranteed. The correct implementation is already applied from lines 311 to 315, so we just need to remove this one.
Intg tests pass, and monitor to make sure they aren't flaky.

fix: rp bindings intg test failure

---

harness/determined/deploy/gcp/preflight.py
master/internal/config/provconfig/gcp_config.go

GCP came out with new instance types, and users would like to try them out:
https://determined-community.slack.com/archives/CV3MTNZ6U/p1692722455479129
Note: in my testing, these clusters could not get provisioned due to "insufficient capacity".
- deploy g2-standard, e.g. `det deploy gcp up --cluster-id ilia-test-l4 --project-id dai-dev-55 --max-dynamic-agents 1 --compute-agent-instance-type g2-standard-4 --gpu-num 1 --gpu-type nvidia-tesla-l4 --det-version ba05ee3bff375590601b600295ec5c6a8b9e04a4 --no-filestore`
- deploy a2-ultragpu

feat: `det deploy gcp` support for a2-ultragpu and g2-standard.

---

docs/release-notes/tpl-list-fix.rst
master/static/srv/get_templates.sql

resulted in api logic not knowing which workspace the template belonged in.
DET-9778
create a template in a workspace and list templates through the cli and make sure the workspace name comes up correctly

fix: add missing workspace_id from get_templates

---

webui/react/src/components/kit/LineChart.tsx
webui/react/src/pages/F_ExpList/CompareParallelCoordinates.tsx
webui/react/src/utils/metric.ts

PROBLEM: Compare View charts showing up as `No data to plot` empty view when there actually is data to show.
UPDATE:
The issue was that in LineChart and ParallelCoordinates were were still using an outdated encoded key of `${metricType}|${metricName}`. We're currently just straight encoding the `Metric` object into a string. One additional fix of sorting the `Metric` object keys while encoding with `JSON.stringify`.
WEB-1596

fix: render Compare View properly

---

.circleci/config.yml

Add release branch name pattern to nightly trigger.

chore: Add nightly tests to release branches

---

harness/determined/deploy/gcp/preflight.py
master/internal/config/provconfig/gcp_config.go

A100-80GB GPUs have a different code.
Follow up to #7702 
`det deploy gcp up --cluster-id i80 --project-id dai-dev-55 --region us-central1 --zone us-central1-a --max-dynamic-agents 1 --compute-agent-instance-type a2-ultragpu-1g --gpu-num 1 --gpu-type nvidia-a100-80gb --det-version 0bfae9409ebe83f770a6e2c1bd1eda8491262499 --no-filestore`

fix: correct GPU name for A100-80GB.

---

harness/determined/common/experimental/determined.py

The CLI likes to construct its own sessions. Maybe someday we'll switch those patterns, but for today this addition makes it easy to migrate to use SDK tools from the CLI's existing sessions.
Create a session any way you like. Some possibilities:
```python
from determined.common import api
sess1 = api.Session(<master>, <user>, <auth>, <cert>, <retry>)
client.login(<master>, <user>, <password>, <cert>)
sess2 = client._get_singleton_session()
```
Create a new Determined object with it:
```python
det = client.Determined._from_session(sess1)
```
Call some `Determined` methods:
```python
det.get_models()
```

chore: New constructor for Determined objects using existing session.

---

harness/determined/cli/job.py
harness/determined/common/util.py

fix: fix failing e2e_cpu tests
All CI tests are running successfully now.
https://app.circleci.com/pipelines/github/determined-ai/determined/43940
FE-23

fix: fix failing e2e_cpu tests

---

harness/determined/common/api/request.py

fix(cli): not found errors should retain useful context

---

harness/determined/experimental/_native.py

we’re catching the wrong import error to decide whether or not the experiment is a PyTorchTrial, which a) leads to going down a wrong codepath and b) obscures the actual error, which is not having tensorboard installed on local virtual environments.
fix for --local --test is to only catch the appropriate import error and set enable_tensorboard_logging to false, since that’s probably what’s expected for a one-batch training test anyway.

fix: --local --test mode catches wrong import exception [MLG-860]

---

webui/react/src/components/ConfigureAgentModal.tsx

`0` is a valid entry for both `User Agent ID` and `Group Agent ID`
BEFORE:
AFTER:
WEB-1606

fix: allow zeroes for user agent id and group agent id

---

webui/react/src/components/MetricBadgeTag.tsx
webui/react/src/components/kit/LineChart.tsx
webui/react/src/pages/TrialDetails/useTrialMetrics.ts
webui/react/src/utils/metric.test.ts
webui/react/src/utils/metric.ts

PROBLEM: The `useTrialMetrics` hook that returns the trial metrics for the `Metrics` tab under experiment/trial detail is not organized by the metric group but just purely by metric name.
FIX: Account for metric group during data re-org for chart props.
BEFORE:
AFTER:
WEB-1604

fix: properly display group metrics in metrics tab charts [WEB-1604]

---

webui/react/src/services/apiConfig.ts

Fix parameter mismatch blocking react build in current code version
`npm run build`  completes successfully, other tests pass

fix: React build issue

---

e2e_tests/tests/cluster/test_proxy.py
e2e_tests/tests/experiment/test_unmanaged.py
e2e_tests/tests/requirements.txt
examples/features/ports/ray_job.py
examples/features/ports/ray_launcher.py
harness/determined/cli/proxy.py

- For proxy tunnel listener, set `SO_REUSEADDR` / `allow_reuse_address = True` to allow the tunnels to be quickly killed & restarted without locking up the port.
- This should fix proxy & ray test failures when running them in quick succession.
- Without `SO_REUSEADDR`, the socket is busy for some time after the process is killed; we don't have a security problem here so the new process should be able to reuse the address.
- Different port hack for `test_experiment_proxy_ray_publish` is no longer necessary
- Ray `Dataset` APIs have changed since 2.5, resulting in the test ray job actually not working correctly
- Ray tune now effectively requires `pyarrow` dependency
- use `ray start --disable-usage-stats` for faster noninteractive startup
`test-e2e-cpu` tests `test_proxy.py` tests and …

fix: proxy tunnel server should use `SO_REUSEADDR`.

---

harness/determined/common/experimental/__init__.py
harness/determined/common/experimental/experiment.py
harness/determined/common/experimental/trial.py
harness/determined/experimental/__init__.py

Deprecate instead of remove old classnames `TrialReference` and `ExperimentReference` as to not cause a breaking change.
```
from determined import Determined, experimental
client = Determined(master="localhost", user="username", password="******")
trial_ref = experimental.TrialReference(trial_id=1, session=client._session)
trial_ref.logs()
exp_ref = experimental.ExperimentReference(experiment_id=1, session=client._session)
exp_ref.list_trials()
```

chore: deprecate Trial/Experiment *_Reference classnames in Python SDK [MLG-858]

---

webui/react/src/components/ResourcePoolCard.module.scss
webui/react/src/components/ResourcePoolCard.tsx

- Make `workspace` label plural when applicable
- Move `Default` label to the left with the resource pool name
BEFORE:
AFTER:

fix: resource pool card workspace tweaks

---

webui/react/src/components/ResourcePoolCard.module.scss
webui/react/src/components/ResourcePoolCard.tsx
webui/react/src/pages/Clusters/ClustersOverview.tsx
webui/react/src/pages/WorkspaceDetails/ResourcePoolsBound.tsx

Also includes some CSS simplifications of the ResourcePoolCard that should result in no visual change. Blocked by (and some overlap with) #7732 

fix: not all resource pools should be labeled "default" [WEB-1600]

---

master/internal/api_resourcepool_intg_test.go
master/internal/db/postgres_rp_workspace_bindings.go
master/internal/db/postgres_rp_workspace_bindings_intg_test.go

RBAC issue described [here](https://github.com/orgs/determined-ai/projects/18/views/1?pane=issue&itemId=36579905). The messages are not consistent, potentially leaking information. This fixes the issues by making the messages more consistent and accurate. Only the view RBAC permissions is important to be consistent as the other RP binding commands are only available to cluster admins.
try `det rp bindings list-workspaces` on a RP that exists, but you don't have access to. Then try on an RP that doesn't exist. The error message should be the same.

fix: make rbac messages consistent

---

webui/react/src/components/kit/LineChart.tsx
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx
webui/react/src/pages/F_ExpList/CompareParallelCoordinates.tsx

In the Compare panel on the Experiment List page, each of the three tabs ("Metrics", "Hyperparameters", "Details") have different empty state messages. Use the same message for all of them ("No data available.")
Select experiments for comparison that do not have trial data. Make sure all three tabs display the "No data available." message.
WEB-1512

chore: use Message for no data in ComparisonView

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/ExperimentMoveModal.tsx
webui/react/src/components/FilterForm/TableFilter.tsx
webui/react/src/components/UserSettings.tsx
webui/react/src/pages/ExperimentList.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/ColumnPickerMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/MultiSortMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/OptionsMenu.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
webui/react/src/pages/F_ExpList/glide-table/contextMenu.tsx

Problems to solve:
- State setters/dispatchers are passed around instead of event handlers. Some side effects include unexpected re-rendering, memory leaks due to state changing dispatchers still being in use when component responsible for creating it unmounts, and other less predictable issues.
- BUG FIX: Table row selections are not preserved between table pages when in paginated mode.
- (not in scope) table is currently hard coded to handle experiments specifically.
Additional tests
WEB-1471
WEB-1561

refactor: make glide-table conform to standard event handler pattern and fix paginated row selection bug [WEB-1471, WEB-1561]

---

Makefile

in root dir, `make go-version-check` fails after the #7657
- Check if `make go-version-check` works 
- Check if `devcluster` runs without errros

build: fix `go-version-check` command

---

master/internal/rm/agentrm/resource_pool.go
master/internal/rm/kubernetesrm/informer.go
master/internal/rm/kubernetesrm/mock_client_test.go
master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/pod_test.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/request_queue.go
master/internal/rm/kubernetesrm/request_queue_test.go
master/internal/rm/kubernetesrm/request_workers.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/task/allocation.go

Refactor pod to be a plain Go struct driven by the pods actor from external signals, informer events, and resource request events. 
Need to swing back around and carefully remove the `time.Sleep` for tests. Figured I'd save that for another day.

chore(actors): refactor pod.go

---

docs/release-notes.rst
docs/release-notes/remove_estimatortrial.rst
docs/release-notes/tpl-list-fix.rst
docs/release-notes/trial-logs-failing.rst

docs: add release notes for 0.25.0

---

.flake8

ignore import restrictions on pre-commit.

chore: ignore flake8 import restrictions pre-commit check

---

master/pkg/archive/archive.go
master/pkg/constants/log_levels.go
master/pkg/model/task.go
master/pkg/tasklog/log_levels.go

Constants in the model package cannot be referenced in pkg/archive as it would create a disallowed import cycle.
Remedy: pull out the log level definitions to a seperate package that can be used by both model & archive.
Keeping the definitions in the model package in place for now as it lowers the changed line count.

chore: rearrange log level constants

---

master/internal/task/allocation.go

As discussed with Bradley, since the message was not very useful to the customer, and did not apply in the HPC environment anyway, it has been removed from the experiment log and now appears in the master log at DEBUG level:
`master: DEBU[2023-09-01T13:34:47-04:00] Ignoring request to daemonize resources.      experiment-id=62 job-id=28e90f2c-cb72-4eda-a358-d96972725a47 task-id=62.5efda4d6-2781-4d3a-9a4f-7199673cea6a task-type=TRIAL trial-id=62 trial-run-id=1`

chore: suppress the daemonize message on HPC jobs

---

agent/packaging/entrypoint.sh
master/static/srv/enrich_task_logs.py

Fixes failures in CircleCI that result in logs not being shipped back to master as a result of silent TLS errors. 
This handles configuring the TLS cert for the `api.post()` call in `enrich_task_logs.py`; as well as, prints log shipping exception to `stderr` on the task container in the event that someone is listening.
- Confirm: tests/cluster/test_logging.py passes
- Run: `det cmd run echo 'hello'` and confirm that 'hello' appears in the task log
DET-9803

fix: handles custom TLS certs in enrich_task_logs.py [DET-9803]

---

master/internal/rm/agentrm/resource_pool.go

I'm also open to deleting this line.

chore: reduce master log noise

---

docs/_static/version-switcher/versions.json

The long-term fix has a [ticket](https://hpe-aiatscale.atlassian.net/browse/MLG-888).

docs: quick fix for version dropdown

---

master/internal/api_experiment.go
master/internal/api_trials.go
master/internal/experiment.go
master/internal/restore.go
master/internal/restore_test.go
master/internal/task/allocation_service.go
master/internal/trial.go
master/internal/trial_intg_test.go
master/pkg/actor/actors/test_actor.go
master/test/testutils/fixtures.go

This reverts commit 216729287700acbdeeb4eb35109f803723b532d3 due to issues with restoring trials in the latest-main cluster.

chore: revert trial actor refactor

---

docs/setup-cluster/deploy-cluster/slurm/install-on-slurm.rst
docs/setup-cluster/deploy-cluster/slurm/overview.rst
docs/setup-cluster/deploy-cluster/slurm/slurm-known-issues.rst
docs/setup-cluster/deploy-cluster/slurm/upgrade-on-hpc.rst

Explicitly document the procedure for performing an HPC upgrade, and provide information about how to verify launcher packages, and the expected result.
Bump launcher version so the package verification messages match.
...

docs: Add sections on HPC upgrade and package verificaiton

---

docs/reference/training/experiment-config-reference.rst
docs/setup-cluster/deploy-cluster/slurm/upgrade-on-hpc.rst

docs: HPC launcher doc tweaks, add image scheme docker-archive://

---

master/internal/task/allocation.go

fix: lower severity of allocation log changed when debugging

---

agent/cmd/determined-agent/run.go
agent/cmd/determined-agent/run_test.go
docs/release-notes/agentVisibleGPUs.rst

We discussed earlier making use of the agent --visible-gpus option to control the slots exposed to determined, but placing this responsibility on the customer could lead to accidents. Instead, let's import any visible GPU information from the environment as the default value for --visible-gpus.
Tested manually on:
- casablanca-login2 (PBS).
- casablanca-login, aizn, o184i054 (Slurm).
Other manual testing:

chore: agent device discovery too greedy

---

webui/react/src/pages/Admin/GroupManagement.tsx

Change copy to avoid confusion about removing user from a user group. Message currently suggests that the user is getting deleted instead.

chore: minor copy change

---

webui/react/src/components/kit/LineChart.tsx
webui/react/src/components/kit/LogViewer/LogViewer.tsx
webui/react/src/components/kit/internal/Markdown.tsx
webui/react/src/components/kit/internal/UPlot/UPlotChart.tsx
webui/react/src/components/kit/internal/useGetCharMeasureInContainer.ts
webui/react/src/components/kit/internal/useResize.ts
webui/react/src/pages/TaskLogs.test.tsx

The current state of the `useResize` hook does not properly return the size of the provided `HTMLElement` ref. The issue is that with the provided `RefObject<HTMLElement>`, changes to the reference is not detected by the `useResize` hook.
Update the hook to consume a `RefCallback` instead. See the [lower part of this section as a reference](https://legacy.reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node).
WEB-1656

fix: correct useResize hook to return proper element sizes [WEB-1656]

---

webui/react/src/pages/SignIn.module.scss

https://hpe-aiatscale.slack.com/archives/CKQ3EV0G6/p1694019620154909
Follow up of #6053
- Check if text in SSO buttons should be white like other buttons
- Always white in any themes

fix: SSO button text color

---

harness/determined/cli/dev.py

- avoid changing stderr
- avoid printing non-utf8 output to stdout
DET-9798

chore: support binary output via dev curl.

---

.github/workflows/check-rebaseable.yml

Add a newline to the printf.  Sigh.
Merge this and see if it works, because that's how awesome the github actions workflow is for pull_request_target. :shrug:

ci: add a newline to the output for pre-check

---

.github/workflows/check-rebaseable.yml

Internally, github actions runs bash as `bash -e`, which exits on the first failing command.  This doesn't work so well when I want to save the return code from a failing command.  So, adding a `set +e` should undo that, allowing the printf to actually capture the return code.
Merge into main and hope it works, because github actions is annoying to test like that.

ci: fix check-rebaseable syntax [ci skip]

---

webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx

Logs are not updated after switching to another tab, because we abort when unmount, but never reassign a new canceler when switching back.  
Run an experiment, while logs are printing, go to another tab in browser. 
Go back, the logs should keep printing. 
WEB-1654

fix: log viewer not updating

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go

Don't think this could happen right now but found through this tool and is worth a fix
https://hpe-aiatscale.slack.com/archives/C058AC320M9/p1694190773367269?thread_ts=1694119417.684979&cid=C058AC320M9
No testing needed for this.

chore: nil exception on GetResourcePoolsRequest error

---

webui/react/src/pages/F_ExpList/glide-table/columns.ts

Frontend manipulate `progress` value, so it leads to the confusion. This PR is a fix to display `progress` value as it is.
- Check if `progress` value in the new exp table is the value as it is as percentage
After talking with @gt2345, we've decided to display value as it is
[Slack conv](https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1694195891906299)

fix: display `progress` value as it is

---

.circleci/config.yml

Moving e2e tests to nightly schedule only in order to help with CirclCI credit usage limit.
Look at subsequent PRs to ensure they don't run the e2e tests.
This is only a temporary change due to a CircleCI contract issue.  We'll move it back after the contract is updated.  The branch requirements will also be changed in order to not require these tests for the duration of the temporary change.

ci: temporarily move e2e to only nightly [skip ci]

---

webui/react/src/hooks/usePermissions.ts

Enable RP bindings management for users with role of `WorkspaceAdmin`
DET-9825

fix: enable RP bindings management for workspace admins [DET-9825]

---

master/internal/api_experiment.go
master/internal/api_trials.go
master/internal/experiment.go
master/internal/restore.go
master/internal/restore_test.go
master/internal/task/allocation_service.go
master/internal/trial.go
master/internal/trial_intg_test.go
master/pkg/actor/actors/test_actor.go
master/pkg/searcher/searcher.go
master/test/testutils/fixtures.go

A 2nd attempt at trial actor refactoring. This PR addresses an issue with large numbers of restored trials where we would always attempt to save and record the searcher trial creation even if it was not needed. By checking if the searcher has already recorded the trial creation we can avoid expensive json serialization that slows down server start for extremely large experiment restarts.
Passes automated tests and works well with latest main deployment were issue was first discovered.
DET-9734

chore: trial actor refactor

---

docs/release-notes.rst

docs: add release notes for 0.25.1

---

docs/tutorials/index.rst
docs/tutorials/pytorch-mnist-local-qs.rst
docs/tutorials/pytorch-mnist-tutorial.rst

With changes to our Examples, we'll be removing some of our references including some of our tutorials. We'll need to help users understand the meaning of some of our terms including "Trial API" when visiting the tutorials index page.

docs: Clarify meaning of trial api

---

webui/react/src/components/JupyterLabModal.tsx
webui/react/src/components/kit/Modal.tsx

[WEB-1647]
- Check if `Read about JupyterLab settings` link should work in Jupyter config modal
[WEB-1647]: https://hpe-aiatscale.atlassian.net/browse/WEB-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: doc url in jupyter config modal

---

docs/setup-cluster/deploy-cluster/slurm/singularity.rst

New option for manage-enroot-cache: --nocreate
Screenshot of the revised user docs showing added seconds paragraph:

chore: update user docs

---

e2e_tests/tests/nightly/test_distributed.py

The `dsat` nightly distributed tests had incorrect `@pytest.mark.deepspeed` marks, in addition to `@pytest.mark.distributed` marks. They should only have the latter marks.  This PR removes the `@pytest.mark.deepspeed` marks.
Verify on CircleCI that the modified `dsat` tests are only run in one workflow: nightly `test-e2e-gpu-distributed`

test: remove deepspeed marks from dsat tests

---

webui/react/src/hooks/useSettings.ts

Since we separate out `set` and `setPartial` in `userSettings`, we should use `setPartial` when setting is partial.
Navigate to experiment list, change table settings by pin/unpin, move... table should behave as expected. 
WEB-1665

fix: use setPartial in experiment list setting

---

master/internal/config/resource_manager_config.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/rmerrors/errors.go

Reverts determined-ai/determined#7696

Revert "feat: add config option to omit default resource pools"

---

.circleci/config.yml
webui/react/.gitignore
webui/react/Makefile

This fixes the test results being missing from the webui unit tests. the full coverage report overwrote the junit artifact, causing the upload to fail.
Test results for react unit tests should be displayed in CircleCI
[WEB-1233]
[WEB-1233]: https://hpe-aiatscale.atlassian.net/browse/WEB-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: fix webui test results upload [WEB-1233]

---

.github/workflows/build-perf-image-perf-test.yml
performance/.dockerignore
performance/Dockerfile

feat: containerize performance tests [INFENG-222]

---

e2e_tests/tests/nightly/test_convergence.py

`test_cifar10_tf_keras_accuracy` has been flaky for a long time. https://hpe-aiatscale.atlassian.net/browse/MLG-884 exists as a ticket to decide what to do with it longer term. This moves the test to quarantine at least for now.

test: quarantine nightly cifar10-keras convergence test

---

webui/react/src/components/BatchActionConfirmModal.tsx
webui/react/src/components/ExperimentTensorBoardModal.tsx
webui/react/src/components/PageHeaderFoldable.tsx
webui/react/src/constant.ts
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx
webui/react/src/pages/TrialDetails/TrialDetailsHeader.tsx
webui/react/src/utils/experiment.ts

[WEB-1631]
- Hide `Profiler` tab
- Disable actions of unmanaged experiment/trial 
- Hyperparameter Search button in `Hyperparameter` tab
- Fork 
- Continue Trial 
- View in Tensorboard
- Experiment List 
- Pause 
- Kill 
- Cancel 
- Resume 
- View in Tensorboard 
- For Tensorboard bulk action
- Show Modal if unmanaged experiments are included
[WEB-1631]: https://hpe-aiatscale.atlassian.net/browse/WEB-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: disable actions of unmanaged experiments/trials

---

master/internal/config/resource_manager_config.go

#7885 had unused code in Go file
- Check if all CI pass and go build doesnt error out

fix: remove unused import in go file

---

.github/ISSUE_TEMPLATE/question.yml

chore: prompt for docs in github question template

---

agent/.golangci.yml
master/.golangci.yml

Increase max line length to 120.
No testing needed

chore: increase Go's max line length to 120

---

.github/CODEOWNERS

web team is assigned whenever auto-generated files are updated. This PR is to ignore these files to reduce noise.
- Check if change is correct

chore: no code owners for auto-generated files

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/message.go
master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/pod_test.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/resource_pool.go

This reverts commit c1a0cf46578fbfbf051c5d6f6e1d63b279059210.

revert: "chore(actors): remove pkg/actors usage from pods.go (#7658) [DET-9652]

---

webui/react/src/pages/TrialDetails/useTrialMetrics.ts

Fix a bug that skip epoch 0 when rendering metrics line chart.
Run an experiment with metrics in both batches and epoch (such as the following example as an unmanaged workload)
Navigate to metrics tab on experiment details page.
Switch between x-axis, and line chart would be different for different x-axis.
Also note that for epoch x-axis, epoch 0 is visible. 
```
#!/usr/bin/env python3
import random
from determined.experimental import core_v2
def main():
core_v2.init(
defaults=core_v2.DefaultConfig(
name="epoch-zero-test",
),
)
for i in range(100):
print(f"training loss: {random.random()}")
epoch = int(i * i / 100)
core_v2.train.report_training_metrics(steps_completed=i, metrics={"loss": random.random(), "epoch": epoch})
if (i + 1) % 10 == 0:
print(f"validation loss: {random.random()}") …
```

fix: Display data point when epoch is 0

---

webui/react/src/components/BatchActionConfirmModal.tsx
webui/react/src/components/ConfigureAgentModal.tsx
webui/react/src/components/CreateGroupModal.tsx
webui/react/src/components/CreateUserModal.tsx
webui/react/src/components/ExperimentCreateModal.tsx
webui/react/src/components/ExperimentEditModal.tsx
webui/react/src/components/ExperimentMoveModal.tsx
webui/react/src/components/JupyterLabModal.tsx
webui/react/src/components/ManageGroupsModal.tsx
webui/react/src/components/ModelCreateModal.tsx
webui/react/src/components/ModelEditModal.tsx
webui/react/src/components/ModelMoveModal.tsx
webui/react/src/components/ModelVersionEditModal.tsx
webui/react/src/components/PasswordChangeModal.tsx
webui/react/src/components/ProjectCreateModal.tsx
webui/react/src/components/ProjectDeleteModal.tsx
webui/react/src/components/ProjectEditModal.tsx
webui/react/src/components/TextEditorModal.tsx
webui/react/src/components/WebhookCreateModal.tsx
webui/react/src/components/WorkspaceCreateModal.tsx
webui/react/src/components/WorkspaceDeleteModal.tsx
webui/react/src/components/WorkspaceMemberAddModal.tsx
webui/react/src/components/kit/Form.tsx
webui/react/src/components/kit/Modal.tsx
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx

Giving the Form component an ID and passing it into the Modal through the `form` field of the `submit` prop links the two components together. This means that if the user's focus is in an input element of the form, pressing the Enter button should attempt to submit the form and close the modal.
This PR does not cover modals not using the Modal component from the UI Kit, such as `useModalHyperparameterSearch`.
The following should apply to all modals affected by the PR, but can be easily demonstrated with the CreateWorkspaceModal.

feat: submit forms in modals by pressing enter [WEB-1130]

---

webui/react/src/components/TaskList.module.scss

[WEB-1202]
- Check if tensoboards should be aligned with `Show Source` button
[WEB-1202]: https://hpe-aiatscale.atlassian.net/browse/WEB-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: align items in task list

---

e2e_tests/tests/requirements.txt

We use ray tune, and it now requires a different installation flavor.
tests which use ray are working.

test: fix e2e_tests ray dependency.

---

.github/CODEOWNERS

Update docs codeowners entry to reflect the current docs team preference
Look at header over the file in the PR and see if it says "this codeowners file is valid"
I wasn't positive if the `/**/` matches "no directories" or not.  I think it does, but adding a second line isn't exactly expensive. :shrug: 
INFENG-225

chore: update docs ownership per discussion [INFENG-225]

---

harness/determined/common/experimental/determined.py
harness/determined/experimental/client.py

Workspaces have already existed in the SDK for internal use. This exposes them to the public API.
For whatever names make sense to test for:
```python
client.get_workspace(<name>)
```

feat: Add workspaces to the SDK client

---

webui/react/.eslintrc.js
webui/react/.unimportedrc.json
webui/react/design/index.tsx
webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/ActionSheet.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
webui/react/src/pages/JobQueue/JobQueue.tsx
webui/react/vite.config.mts

Re-adds the work from #7767, this time without breaking builds (fingers crossed).
Unimported files should be printed to console by running npm run unimported. This PR does not remove the dead code, just report it.
Current results:
```
summary               unimported v1.29.2 (node)
────────────────────────────────────────────────────────
entry file 1        : src/index.tsx
entry file 2        : design/index.tsx
unresolved imports  : 0
unused dependencies : 1
unimported files    : 16
─────┬──────────────────────────────────────────────────
│ 1 unused dependencies
─────┼──────────────────────────────────────────────────
1 │ smoothscroll-polyfill
─────┴──────────────────────────────────────────────────
─────┬──────────────────────────────────────────────────
│ 16 unimported files …
```

chore: track dead code [WEB-258]

---

webui/react/src/components/PageNotFound.module.scss

[WEB-1652]
- Check if button text is aligned center
[WEB-1652]: https://hpe-aiatscale.atlassian.net/browse/WEB-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: button in 404 page

---

docs/assets/styles/determined.css

- Rafactor tile css in docs
- No visual changes

refactor: css for tile in docs

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx

[WEB-1679]
- Check if selection will be 0 after action
[WEB-1679]: https://hpe-aiatscale.atlassian.net/browse/WEB-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: clear selection after action

---

master/internal/rm/tasklist/job.go

Update the priority schedule not to explode on invalid inputs but to ignore them instead.
This is a bit "feels bad" because I love "failing fast", but when it results in a small bug taking down a cluster, compromises must be made. @erikwilson has some changes in flight for groups. As part of that we should have "DeleteJob" or whatever fires the "GroupActorStopped" logic get an error if it tries to remove a job/group with active allocations.

fix(scheduler): tolerate missing groups in priority scheduling

---

master/internal/db/postgres_trial.go
master/static/migrations/20230817155037_fix-summary-nulls.tx.down.sql
master/static/migrations/20230817155037_fix-summary-nulls.tx.up.sql

see https://github.com/determined-ai/determined/pull/7946/commits/3c4373a68b65cac2e2d35a0275d1b6721c3ba064

 fix: use summary metric's migration caused nulls 

---

master/internal/experiment.go
master/pkg/model/experiment.go

On crash, experiments were attempting to write PAUSED or ACTIVE experiments to "". The change just transitions those to the ERROR state instead. 
Found from looking at a customer's logs.

fix(experiments): prevent invalid experiment transitions on crash

---

harness/tests/determined/common/experimental/test_workspace.py

When a not-found error in the Workspace constructor was changed from a ValueError to an api.errors.NotFoundException, this test was not updated.

test: fix a broken test

---

agent/pkg/singularity/singularity.go

Determined agent failed if setting the env var without "=value", for example:
test_run.py test_environment_variables_command 
"--config",
"environment.environment_variables='THISISTRUE=true','WONTCAUSEPANIC'",
`[2023-09-18T23:45:53.152130Z] 057dd599 || INFO: FATAL:   while setting environment: while processing /tmp/determined-launcher-znode50/685115867-057dd599-ab5f-4065-ba7a-d904edab98d8/envfile: while evaluating environment script: could not execute "WONTCAUSEPANIC": execution is disabled`
After the fix test_environment_variables_command passing.

fix: singularity agent env variable

---

master/internal/rm/kubernetesrm/informer.go

Reduce warnings about k8s nil events by checking in the informer for nil event objects, log at trace level, and continuing on to the next event.
Warnings like `[WARNING]: error converting event of type watch.Event to *k8sV1.Node: {Type: Object:<nil>} pod-name="default"` do not appear in log output.

chore: log k8s nil event objects at trace level and ignore

---

performance/.gitignore
performance/Makefile
performance/README.md

Changes tested locally. Future work will test the configuration code in CI runners.

chore(performance): create initial Makefile [INFENG-223]

---

master/static/migrations/20230920130838_add-update-modified-at-in-user-table-by-insert.tx.down.sql
master/static/migrations/20230920130838_add-update-modified-at-in-user-table-by-insert.tx.up.sql

Fix of https://github.com/determined-ai/release-party-issues/issues/643#issuecomment-1728200978
- Check if newly created user's `modified_at` is `now` instead of `Dec 31, -0745`

fix: update `modified_at` by insert in user table

---

harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/base.py
harness/determined/deploy/aws/templates/simple-rds.yaml

Adds the ability to specify a database instance class and initial storage size for a `simple-rds` deployment when using `det deploy aws`.
1. Run `det deploy aws up --deployment-type simple-rds --db-size <size> --db-class <class> ...` and ensure the chosen instance size and classes were used in the resulting cluster. 
INFENG-227

feat: Add instance flavor and size arguments for det deploy aws [INFENG-227]

---

master/internal/rm/agentrm/agent_resource_manager.go

Fix Agent Resource Manager crashing when Resource pool returns nil actor message and nil actor error
Launch a cluster, make a resource pool crash (eg. panic on receipt of a message you can trigger), and then make sure the entire RM does not crash as a result of one of these calls.

fix: handle nil actor message and nil actor errors in agent RM

---

master/internal/db/postgres_tasks.go

fix: Update Tasks Stats Causes Deadlock [DET-9853]

---

master/internal/user/postgres_users_intg_test.go

Add tests for `postgres_users.go` and `postgres_agentusergroups.go`
Pass the test included.
DET-9840

chore: add tests for postgres_users.go

---

webui/react/src/pages/ModelDetails.tsx
webui/react/src/pages/ModelDetails/ModelVersionActionDropdown.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/types.ts

- Go to a Model Details page containing multiple versions
- Start editing the description field of one of the model versions in the table. 
- Pause and wait several seconds without completing edit/clicking away. 
- The description should not be changed back to the original or empty value

fix: data fetch shouldn't interrupt editing model version description [WEB-1703]

---

webui/react/src/components/Markdown.module.scss
webui/react/src/components/kit/internal/Markdown.module.scss

This hasn't been an issue in practice because the CSS for `ant-tabs` was overriding it, but this applies our default font-family to markdown text anyway in case we use the component in a different context.

style: align default markdown font-family to theme [WEB-617]

---

webui/react/src/components/ResourcePoolBindings.tsx

Fix an issue that when refresh, table content disappear. 
With rbac enabled, navigate to cluster -> select a resource pool -> bindings tab
If there is no bindings, create some bindings first
Refresh at this page, table content should persist
WEB-1569

fix: Add fetch to resource pool bindings

---

docs/architecture/introduction.rst

Follow-up to #7913: The slots allocation should be proportional for single-trial case. I may have been confused when commenting on it in the context of a dtrain and provided a bad example for the point I was trying to make.
cc @ighodgao 

docs: fair-share scheduling policy [skip ci]

---

harness/determined/cli/model.py
harness/determined/cli/render.py
harness/determined/cli/workspace.py
harness/determined/common/experimental/__init__.py
harness/determined/common/experimental/model.py
harness/determined/common/experimental/project.py
harness/determined/experimental/__init__.py

BREAKING CHANGE: This moves Model.to_json out of the public API. It was weird there in the first place, not designed for outside use, and probably never used.
Some SDK resources have `to_json` methods that emulate bindings. This moves them out of the SDK into CLI render utilities.
These methods were built for the CLI, only support the CLI, and so should live in the CLI.
The CLI is the only place these methods were called, so try exercising those commands:
```shell
det model list --json
det model create <name> --json
det model describe <name> --json
det  w list-projects <name> --json --sort-by name --limit 1 --offset 0
```
etc.

chore: move SDK to_json methods out of the SDK

---

harness/determined/experimental/client.py

First step in standardizing our docstrings per the Google style guide. Mostly, this was just formatting. But in some cases, existing docstrings were incomplete or misleading. They have been fixed.

chore: Better, conforming docstrings in SDK client.

---

.circleci/config.yml
.github/workflows/performance-tests.yml
performance/Dockerfile
performance/Makefile
performance/src/utils/k6-summary.js

ci(performance): create initial gha workflow [INFENG-224]

---

harness/determined/common/experimental/determined.py
harness/determined/experimental/client.py

New method for the client:
* list_workspaces()
```python
client.login(<details>)
client.list_workspaces()
```

feat: SDK can list workspaces.

---

master/internal/core.go
master/internal/telemetry/logger.go
master/internal/telemetry/reports.go
master/internal/telemetry/singleton.go
master/internal/telemetry/telemetry.go
master/internal/telemetry/telemetry_test.go

Is a test.
Part 1 of turning on `--race` for units and integrations.

chore(tests): fix data races in telemetry tests

---

.circleci/config.yml

Two-liner fix. Once `master` branch became `main`, images for modelhub-mmdetection suffixed with `-dev0` stopped being published.
See https://hub.docker.com/r/determinedai/model-hub-mmdetection/tags?page=1&name=dev0
Confirm that https://hub.docker.com/r/determinedai/model-hub-mmdetection/tags?page=1&name=dev0 shows recently published tags. Before this fix the latest tag was `0.23.1-dev0`.

fix: fasterrcnn image not found [MLG-516]

---

docs/release-notes/detached-checkpoint-cloud.rst
e2e_tests/tests/experiment/test_unmanaged.py
e2e_tests/tests/fixtures/unmanaged/error_termination.py
harness/determined/core/_heartbeat.py
harness/determined/core/_log_shipper.py
harness/determined/experimental/core_v2/_core_v2.py
harness/determined/tensorboard/base.py
harness/determined/tensorboard/build.py

- Better thread cleanup on detached mode process shutdown for log sender and tensorboard threads.
- Support s3 & gcs for tensorboard storage.
- Moved the "error" test from examples into test fixtures.
- Set explicit names for the background threads we spawn to simplify debugging a bit.
Automated testing added.
Manual testing: setup a detached mode code which
1. has `checkpoint_storage=` parameter set
2. throws an exception mid-way
The code should exit on exception, rather than be stuck waiting for background threads to finish.

fix: detached mode tensorboard storage support [MLG-872]

---

.circleci/config.yml
e2e_tests/pytest.ini
e2e_tests/tests/nightly/test_distributed.py

The stable diffusion example tests were never actually run, due to my misunderstandings of our test infra.  Previously, the `nightly/test_distributed.py::test_textual_inversion_stable_diffusion_finetune` and `nightly/test_distributed.py::test_textual_inversion_stable_diffusion_generate` tests were simply skipped because the env var which was supposed to hold a required huggingface authorization token was missing.
This PR is intended to make these tests actually run (and hopefully pass).  Also, if the relevant env vars are not found, this PR makes the test error out, rather than just skipping.
Verify that the nightly distributed tests have been running in CircleCI.

test: stable diffusion example tests [MLG-903]

---

master/internal/api_experiment_intg_test.go
master/internal/api_trials_intg_test.go

chore(tests): fix data races in streaming API intg tests

---

.github/CODEOWNERS

Gives backend cluster, command and template ownership of e2e tests.
No testing needed.

ci: backend owns e2e_tests folders cluster, command, and template

---

master/go.mod
master/internal/webhooks/shipper_test.go

chore(tests): fix data races in webhooks intg tests

---

master/internal/rm/kubernetesrm/pods.go

Includes a pod name for informer log messages, and changes the Warning output of unknown pods to Debug.
None, logging only.

chore: cleanup pod informer logging

---

harness/determined/deploy/aws/aws.py

- `describe_stacks` call must be paginated. we have more than one page of stacks now so it has become an issue.
- prior to #6207, "managed-by" tag has been wiped out on updates. this means a number of old stacks which have been updated were not listed. let's check the "deployment-type" tag as well: it's unlikely we'll collide with other applications, and listing "wrong" stacks seems less costly than forgetting a stack.
`det deploy aws list` should list all stacks, not just the first 100 of them.

fix: `det deploy aws list` results were incomplete.

---

webui/react/src/pages/F_ExpList/glide-table/TableActionBar.tsx

At the experiment list table, show `loading experiments` instead of `0 experiment` when loading. 
Navigate to experiment list table.
When experiments are loading, there is the `loading experiments` message  instead of `0 experiment`.
Select some experiments then refresh, there is the `loading experiments` message  instead of `x of 0 experiment selected`.
WEB-1601

fix: Show experiment loading state

---

webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/types.ts

Workspace members list should not show deactivated users.
With rbac enabled, find a workspace with members.
Deactivate one or some of the members.
Deactivated members should no longer show up at the workspace members tab.
WEB-1109

feat: Hide deactivated user in ws members list

---

master/internal/user/service.go
master/internal/user/service_test.go

The enable/disable slots echo-endpoints had already been removed and replaced by their grpc-gateway counterparts (`api/v1/agents/.*/slots/.*`).
This PR cleans up remaining references to `agents/.*/slots/.*`. 
These endpoints were also the last endpoints referenced in `adminAuthPointsList`, so it was no longer necessary to be checking in `service.go:ProcessAuthentication` for if an endpoint was adminOnly. Admin only authentication is handled in the relevant authz implementations, with `ProcessAuthentication` being redundant.
- Current e2e test (`test_disable_and_enable_slots` confirms expected functionality)
DET-9583

refactor: removed reference removed agents/.*/slots/.* endpoint [DET-9583]

---

webui/react/src/pages/TrialDetails/useTrialMetrics.ts

When trial id not changed, we should not reset loading state. 
Run an experiment with multiple metrics (at least 3).
Navigate to trial details page then metrics tab.
While the experiment is running, scroll to the bottom of the metrics tab.
Stay there for at least 30 seconds, the page should not auto refresh then reset scroll position to the top.
WEB-1661

fix: Trial metric unnecessarily reset loading state

---

master/internal/task/allocation.go
master/internal/task/allocation_service.go
master/pkg/model/task.go
master/pkg/model/task_test.go

Refactor allocation exit logic to use less defers, unify allocation cleanup/terminated logic
and swap to closers from trying to remember everything in cleanup
Run a few jobs that exit in various ways (kill during run, kill during image pull, crash, complete) and make sure they end in an expected state.

chore: cleanup allocation exit logic

---

webui/react/src/pages/WorkspaceDetails.tsx

We no longer want to allow deactivated users to be added to a `Workspace` similar to how we do not allow deactivated users to be added to a `Group`.  Additionally, there was a lengthy discussion with product concerning how and where this functionality should be implemented, due to the fact that the ticket initially mentioned implementing this on the backend. 
Ultimately, it was decided that this only needed to be a UI update. As of now, we only need to ensure deactivated users cannot be added to a workspace via the UI. 
1. Log in to an `RBAC` enabled cluster as a user with User Administration and Role Assignment permissions.  
2. Navigate to the User management page, this can be accessed by clicking your username in the top left corner of the page and then clicking "Admin"
3. Ensure that …

feat: Dont allow users to add deactivated users to a workspace [WEB-1100]

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/ExperimentEditModal.test.tsx
webui/react/src/components/ExperimentEditModal.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/contextMenu.tsx

Add an "Edit" option to the right-click context menu for experiments on the Experiment List, which opens the "Edit Experiment" modal.
On Experiment List:
1. User right clicks on an experiment
2. Clicks “edit' option
3. Modal appears with all editable fields (Name, Description)
4. User can save or cancel
5. On save success, close modal and show notification “Experiment updated successfully”
6. Errors/validation should happen inline via form fields on hitting save. 
WEB-1308

feat: Edit experiment from list

---

master/static/migrations/20231006193809_trigger-by-username--on-users-table.tx.up.sql

follow up of #8091
I forgot to add `username` in `autoupdate_users_modified_at` trigger
- Check if `autoupdate_users_modified_at` is triggered by `username` change

fix: trigger `autoupdate_users_modified_at` by `username` change

---

master/internal/stream/trials.go
master/pkg/stream/declarative.go

Fixes two issues:
1) Add order by to TrialCollectStartupMsgs, otherwise we may encounter extraneous deletion and addition messages 
2) Add a case where if the keysetbuilder has not been used, return an empty string instead of "0"

fix: streaming updates bug fixes

---

webui/react/src/pages/WorkspaceDetails.tsx

Update the list of users and groups in the WorkspaceMemberAddModal without requiring a page refresh.
Note: this can only be tested on an RBAC cluster
1. Log into cluster as an admin.
2. Open two tabs of the cluster webui.
3. In tab A, go to a Workspace Details page, click on the Members tab, and click the Add Member button to bring up the WorkspaceMemberAddModal.
4. In tab B, click on your username in the top left corner and select the Admin option.
5. Choose a random username that does not exist on the cluster. Confirm that it doesn't appear when entered into the User or Group select in the modal in tab A.
6. In tab B, click the Add User button, fill in the username you came up with in the previous step, and click Save.
7. In tab A, **without refreshing the page** try to search for the …

fix: update WorkspaceMemberAddModal when new user or group is created [WEB-1111]

---

docs/Makefile

Command to run the sphinx-build wrapper not been printed to screen since this Makefile was imported into the determined repo. Back then, the build was less complicated, but I don't really understand the motivation for silencing the echoing of this particular command. Certainly seems better now to print it.

build: print sphinx-build command on make build

---

.circleci/config.yml

Adds the `hugging-face` context to `test-e2e-gpu-distributed-nightly` under `test-e2e-longrunning` so that [the stable diffusion tests](https://github.com/determined-ai/determined/blob/b9bd8c9e3729b8c1e5e870afc068a0c1ae2c400a/e2e_tests/tests/nightly/test_distributed.py#L277-L354) can read relevant env vars.
Verify that the `test-e2e-gpu-distributed-nightly` tests completed successfully in the `test-e2e-longrunning` workflow.

chore: add hf context to all dist e2e [DET-9893]

---

.github/workflows/doc-review.yml

Undo #7982, while also assigning docs virtual team to the relevant PRs
Roll the dice.  This is a pull_request_target action, so it only works when it's in main.  So GitHub basically doesn't want me to test it.
CC: @tara-det-ai nd @rb-determined-ai because they cared about #7982 too

ci: dannys/reenable docs autoassign

---

docs/interfaces/notebooks.rst
docs/reference/deploy/config/master-config-reference.rst

docs: Apply style guide edits

---

master/internal/stream/socketlike.go
master/internal/stream/supervisor.go
master/internal/stream/system.go
master/internal/stream/trials.go
master/pkg/stream/stream.go

Refactor streaming updates code to remove early conversions into `*websocket.PreparedMessage`. This allows for easier testing by enabling consumers to be more flexible and allowing us to define our own functions for preparing messages.

chore: streaming updates refactor [DET-9795]

---

master/internal/config/config.go
master/internal/core.go

add an internal option to the master config to allow proxying requests to another
internal process listening on the same node.
this should not be used in production deployments of Determined as is.

chore: add option to proxy requests to internal service

---

master/internal/stream/system_intg_test.go
master/test/migrationutils/utils.go
master/test/olddata/pre_remove_steps.go
master/test/streamdata/stream_data.go
master/test/streamdata/stream_trials.sql

add intg tests for startup functionality. These tests are very likely going to be refactored in a future intg test PR, but these will help make sure we don't break things in the future.
This PR depends on #8101 

chore: streaming updates startup testing

---

master/internal/api_checkpoint.go
master/internal/api_experiment.go
master/internal/checkpoint_gc.go
master/internal/checkpoint_gc_test.go
master/internal/command/command.go
master/internal/experiment.go
master/internal/mocks/allocationmocks/allocation_service.go
master/internal/mocks/resources.go
master/internal/rm/agentrm/mock_test.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/agentrm/resources.go
master/internal/rm/agentrm/scheduler_test.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go
master/internal/task/allocation_service.go
master/internal/task/allocation_service_iface.go
master/internal/task/allocation_service_test.go
master/internal/trial.go

Removes actor system from task resource start and kill methods.

chore: task resources actor refactor

---

master/internal/api_experiment.go
master/internal/experiment.go
master/internal/restore.go
master/internal/trial.go
master/internal/trial_intg_test.go

Removes actor system from trials.

chore: final trial actor refactor

---

harness/determined/common/experimental/experiment.py
harness/tests/determined/common/experimental/test_experiment.py

change list_trials to take in max_results instead of page limit
ensure that list_trials with max_results returns specified number of trials
```
exp = client.get_experiment(10)
exp.list_trials(max_results=2)
```

feat: use max_results in SDK's list_trials

---

docs/.redirects/redirects.json
docs/setup-cluster/deploy-cluster/slurm/singularity.rst

https://hpe-aiatscale.atlassian.net/browse/FE-259
This creates a duplicate of the following:
/setup-cluster/slurm/singularity.html
This should be considered a temporary solution.

docs: Restore path to singularity file

---

harness/determined/common/experimental/experiment.py
harness/tests/determined/common/experimental/test_experiment.py

Reverts determined-ai/determined#8173

Revert "feat: use max_results in SDK's list_trials"

---

docs/.redirects/redirects.json

Some links were broken and block release. :| 
navigate to docs
`python redirects.py check` and `python redirects.py publish` should both work.

docs: fix redirects

---

docs/reference/python-sdk.rst
docs/release-notes/python-sdk.rst
harness/determined/experimental/client.py

Adds release notes for Python SDK feature branch.

chore: add release notes for Python SDK

---

webui/react/src/components/kit/Icon/Icon.module.scss

Go to the Icons section of the Design Kit in Safari and make sure all of the icons appear as expected

fix: icons should appear in safari

---

docs/model-dev-guide/debug-models.rst
harness/determined/_trial_context.py

`PyTorchTrialContext.from_config()` was removed with Trainer API (0.21.0). This updates the docs to no longer refer to this method.

docs: remove references to PyTorchTrialContext.from_config() [MLG-832]

---

docs/assets/styles/determined.css

docs: toctree tile css

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/resource_pool.go

This change makes k8s resource pools plain Go structs with locks and all calls to RPs are synchronous. Since actors handle messages synchronously anyway, the only difference is that caller may actually way on the locks in situations where previously a `ctx.Tell` would've fired and forgot. Calls to the RP are typically short, so much so that any lock contention should be minimal. Calls to the RM in k8s that saturate the UI (and could adversely affect UX if they slow down) already gather their data from caches.
DET-9657

chore(actors): refactor k8s' resource_pool.go without actors [DET-9657]

---

master/cmd/stream-gen/main.go
master/go.mod
master/go.sum
master/internal/core.go
master/internal/db/migrations.go
master/internal/db/postgres.go
master/internal/stream/socketlike.go
master/internal/stream/system.go
master/internal/stream/system_intg_test.go
master/internal/stream/trials.go
master/pkg/model/task.go
master/pkg/stream/stream.go
master/test/migrationutils/utils.go
master/test/streamdata/stream_data.go

Adds style changes to stuff I missed from my previous PR.
no testing required

chore: linting fixes for stream updates

---

docs/manage/security/_index.rst
docs/manage/users.rst
docs/reference/deploy/agent-config-reference.rst
docs/setup-cluster/_index.rst
docs/setup-cluster/checklists/_index.rst
docs/setup-cluster/checklists/infiniband.rst
docs/setup-cluster/k8s/helm-commands.rst

Apply clarifying edits and corrections after reviewing with SME.
Reference: #8203

docs: Edit setup checklist

---

master/pkg/stream/stream_test.go

Unit tests for streaming updates code in `master/pkg`
No testing required, so long as it passes CI 

chore: initial unit tests for pkg/stream

---

.circleci/config.yml

nightlies fail to deploy because AWS does not allow bucket names to be more than 63 characters. 
this is a quickfix that just shortens the problematic name, we should settle on an actual strategy ([JIRA](https://hpe-aiatscale.atlassian.net/browse/MLG-1126))

chore: shorten job name to unblock nightlies [MLG-1031]

---

webui/react/src/pages/Admin/index.tsx

Update users and groups tab to reflect count.
Screenshot
With rbac enabled, navigate to admin page
User tab and group tab should have a number that reflects the count of user and group.
Maybe group should be wrapped around in a store, so use case like this would no longer require an extra API call. 

feat: Update users and groups tab to reflect count

---

master/static/srv/update_aggregated_queued_time.sql

[DET-9912]
[DET-9912]: https://hpe-aiatscale.atlassian.net/browse/DET-9912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: inaccurate task queue time [DET-9912]

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/ActionSheet.tsx
webui/react/src/components/NavigationSideBar.module.scss
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/NavigationTabbar.module.scss
webui/react/src/components/NavigationTabbar.tsx
webui/react/src/pages/DesignKit.tsx

- Check that NavigationSidebar looks ~the same as before (a few pixels difference is acceptable) and links and collapsing/expanding work as expected.
- Check that Nameplate looks as expected in Design Kit 

refactor: use Nameplate component in NavigationSidebar [WEB-1057]

---

webui/react/src/components/CreateGroupModal.test.tsx
webui/react/src/components/CreateGroupModal.tsx
webui/react/src/pages/Admin/GroupManagement.tsx

While logged into a RBAC cluster with an account having Cluster Admin privileges:
1. Click on your username/icon in the top left corner and select "Admin"
2. Go to Groups tab
3. Open another browser tab at same URL
4. In tab A, click the "New Group" button to open up the "Create Group" modal
5. In tab B, click the three-dot overflow menu on the right side of one of the table rows and select "Edit" to open the "Edit Group" modal
6. Both modals should contain two inputs: a required Group Name input field and an optional "Select Global Roles" multiselect field
7. The only differences between the modals should be the text in the title and primary button
8. Submit both modals after selecting at least one role and confirm that groups were created/edited successfully.
See [Release …

feat: unify new/edit group modals [WEB-1741]

---

.circleci/real_config.yml

Always run the CI "Setup venv" step for caching.

chore: ci should always setup python venv for caching

---

webui/react/src/components/TaskBar.tsx

https://hpe-aiatscale.slack.com/archives/CKQ3EV0G6/p1698358870393289
- Create a new task or open a existing task
- Check if Chevron icon should be visible in task bar

fix: icon size in TaskBar

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/setup.go

Exactly what is says.
Fairly easy one, turns out.
DET-9658

chore(actors): refactor k8s rm without actors [DET-9658]

---

webui/react/src/components/AddMemberModal.tsx
webui/react/src/components/AddUsersToGroupModal.tsx
webui/react/src/pages/Admin/GroupManagement.tsx

[WEB-1742]
- Create new “Add Members to Group” modal should be based on the “Add Members to Workspace” modal
- Title: `Add Members to {groupName}`
- Input (Multi-select combobox):
- Label: `Find and Select Users`
- Placeholder: `Add Users`
- List: 
- Only show users that are not in this group. 
- Shouldn't return deactivated users
- List of relevant users based on input, nameplate style list items.
- Validation: Disable button until the `Find and Select Users` input has a selection
- Buttons:
- `Cancel`
- `Add to Group`
- Group detail should be updated after adding group members
- Add new “Add Members” action to the row action overflow menu (3 dot) in the Groups table that launches this modal.
- Remove “Users” from Edit Group and New Group modals
See [Release …

feat: update add members to group

---

master/internal/core.go
master/internal/resource_allocation.go

Exactly what is says.
Definitely the easiest one.
DET-9662

chore(actors): remove actors from resource aggregation [DET-9662]

---

webui/react/src/components/ConfigureAgentModal.tsx
webui/react/src/pages/Admin/UserManagement.tsx

"Configure Agent" copy in the user management UI is nonsense. Update it to "Link with Agent UID/GID" to make it reflect what it actually does and match the CLI.
Check that the new copy does not blow up the dropdown menu or the modal.
The new copy is blessed by @hkumar92 

fix: update copy for Agent UID/GID modal in the user mgmt UI.

---

webui/react/package-lock.json
webui/react/package.json

Before this PR trying to use `scripts/proxy.js` resulted in the following error:
```
> ./scripts/proxy.js <cluster URL>
node:internal/modules/cjs/loader:1051
throw err;
^
Error: Cannot find module 'request'
Require stack:
- /Users/emilybonar/src/determined/webui/react/scripts/proxy.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
at Module._load (node:internal/modules/cjs/loader:901:27)
at Module.require (node:internal/modules/cjs/loader:1115:19)
at require (node:internal/modules/helpers:130:18)
at Object.<anonymous> (/Users/emilybonar/src/determined/webui/react/scripts/proxy.js:6:17)
at Module._compile (node:internal/modules/cjs/loader:1241:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
at Module.load …
```

chore: install `request` as dev dep to fix proxy.js

---

docs/model-dev-guide/api-guides/apis-howto/deepspeed/deepspeed.rst
harness/determined/pytorch/deepspeed/_deepspeed_context.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py

Support profiling for DeepSpeed trials. DeepSpeed supports PyTorch Profiler, which we already provide an API for in PyTorch trials. Implementation for DeepSpeed is the same.
This PR is in a draft status because I am still testing this.
Submit a Deepspeed trial. In the trial's init, configure the profiler:
```
class MyTrial(DeepSpeedTrial):
def __init__(self, context: DeepSpeedTrialContext) -> None:
self.context = context
...
self.context.set_profiler(
activities=[
torch.profiler.ProfilerActivity.CPU,
torch.profiler.ProfilerActivity.CUDA,
],
schedule=torch.profiler.schedule(
wait=1,
warmup=1,
active=2
),
)
```
In the Web UI, open Tensorboard. There should be a "Pytorch Profiler" tab with profiling metrics.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/relea …

feat: support PyTorch Profiler in DeepSpeed trials [MLG-1095]

---

webui/react/src/components/DeterminedAuth.tsx

[WEB-1767]
- Check if `invalid credentials` message appears with wrong username or password
- Check if `user is not active` message appears with deactivated user  
- When the user is deactivated and credential is wrong, `invalid credentials` message should appear
[WEB-1767]: https://hpe-aiatscale.atlassian.net/browse/WEB-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: login error message

---

webui/react/src/components/FilterForm/components/FilterFormStore.test.ts
webui/react/src/components/FilterForm/components/FilterFormStore.ts
webui/react/src/components/FilterForm/components/type.ts

this refactors the FilterFormStore change methods to return new objects and arrays when changed instead of directly mutating the objects. traversal is centralized to a single function which takes an updater function, which the other updater functions call.
* visit the experiment list page for a project
* open the 'filter' menu in the action bar
* if there's already filters in the menu, click reset filter. The filter menu should contain an empty experiment condition.
* filter the experiment list by id by adding a condition "where id = 1". The experiment list should contain one experiment with the id of 1, if it exists.
* update the existing condition to "where trial count < 2". The experiment list should contain all single-trial experiments.
* Add a new condition, either by clicking the "+ …

chore: refactor filterformstore

---

docs/model-dev-guide/api-guides/apis-howto/api-core-ug.rst
docs/model-dev-guide/api-guides/apis-howto/api-keras-ug.rst

fix: fix docs linting

---

.bumpversion.cfg

fix: update bumpversion cfg for new CircleCI config

---

e2e_tests/tests/cluster/test_exp_continue.py
e2e_tests/tests/fixtures/no_op/grid-short.yaml
e2e_tests/tests/fixtures/no_op/random-short.yaml
master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/experiment.go

Added a new CLI command `det e continue-hp-search <exp-id>`  which allows the user to continue a failed/interrupted HP search experiment. Although this command is mainly for random search and grid search experiments, it also supports single experiments.
- added e2e tests that should cover almost everything
- can be tested by creating a grid search or random search experiment, stopping the experiment midway or killing some trials and then using the CLI command to continue it. It should continue to completion without any errors.
- if the command is used on a completed experiment, it should show an error.
DET-9752

feat: added a new cli command to recover hp search experiments [DET-9752]

---

webui/react/src/components/CreateGroupModal.tsx

[WEB-1789]
- Enable RBAC and go to Group tab in Admin Settings page
- Check if group without roles should be created without error messsage
[WEB-1789]: https://hpe-aiatscale.atlassian.net/browse/WEB-1789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: undefined handling in `CreateGroupModal`

---

master/internal/stream/system_intg_test.go
master/test/streamdata/stream_data.go

contains a fix for a broken intg test (`KeepAlive` boolean should have been the other way around, so renamed to `EarlyTerminate`) and improves the testing model so that users don't provide arguments to fixed fields in the function.
Run intg test and make sure they pass.

chore: fix intg test and improve testing model

---

master/internal/command/command_job_service.go
master/internal/experiment_job_service.go
master/internal/job/jobservice/jobservice.go

Fix an issue where job service would panic due to the workspace not existing.
This fix is for unreleased code.
DET-9940

chore: fix job service panic when workspace does not exist

---

webui/react/src/pages/Admin/GroupManagement.tsx

[WEB-1792]
- Check if width in group table is appropriate
- action buttons show be minimal size and content width should be wide enough
[WEB-1792]: https://hpe-aiatscale.atlassian.net/browse/WEB-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: adjust width size in group table

---

webui/react/src/components/ExperimentCreateModal.tsx
webui/react/src/services/types.ts

Bug: When creating forked experiment with edited workspace and/or project, the new experiment is still created at the parent experiment's project. This happens because we pass the "ProjectId" from the parent experiment to the backend, and this overwrites whatever project we put in the config. 
- Fork/Continue an experiment without changing project information, the new experiment should be in the same project as the parent experiment.
- Fork/Continue an experiment changing only the project (not workspace), the new experiment should be in the new project.
- Fork/Continue an experiment changing both the project and workspace, the new experiment should be in the new project.
- Fork/Continue an experiment changing both the project and workspace, but the information is invalid, the action would …

fix: Project info not persist when forking experiment

---

webui/react/src/components/CheckpointModal.tsx
webui/react/src/types.ts

this allows experiments with directory checkpoint storage to parse.
* submit an experiment with directory checkpoint storage set up in the config
* searches including the experiment should show up successfully in the frontend
No ticket

fix: allow experiments with directory checkpoint storage to parse

---

.circleci/real_config.yml
e2e_tests/pytest.ini
e2e_tests/tests/cluster/test_logging.py
e2e_tests/tests/conftest.py

test_task_logs has been failing more and more often in recent days. Moving it to quarantine until we can figure out / fix the problem.

test: quarantine GPU execution of test_task_logs

---

master/internal/rm/agentrm/agent.go
master/internal/rm/agentrm/agent_state.go

Doing this in tons of small PRs, if at all possible.
No testing required, covered by e2es.

chore(actors): remove ctx usage in agent_state.go

---

master/internal/api_experiment.go
master/internal/api_trials.go
master/internal/api_user_intg_test.go
master/internal/experiment.go
master/internal/experiment/bulk_action.go
master/internal/experiment/experiment_iface.go
master/internal/experiment_job_service.go
master/internal/restore.go
master/internal/restore_test.go
master/internal/trial.go
master/internal/trial_intg_test.go

Removes actors from experiments.
DET-9661

chore: experiment actor refactor

---

docs/model-dev-guide/api-guides/apis-howto/api-pytorch-ug.rst
docs/reference/deploy/helm-config-reference.rst
docs/release-notes.rst
docs/release-notes/cli-user-edit.rst
docs/setup-cluster/aws/dynamic-agents-aws.rst
docs/setup-cluster/on-prem/options/deploy.rst
docs/setup-cluster/slurm/slurm-known-issues.rst

fix typo in user edit release note
n/a

docs: fix typo in user edit release note

---

master/pkg/stream/stream.go
master/pkg/stream/stream_test.go

fixes a bug where json marshaling doesn't marshal with the proper keys. Issue was caused by the MarshalJson() function not being called due to it being a pointer receiver. 
This PR also includes a fix for an err msg typo

fix: json marshaling bug

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

[WEB-1783]
- Check if there is a pin icon for `Pin` / `Unpin` item in column header menu
[WEB-1783]: https://hpe-aiatscale.atlassian.net/browse/WEB-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add pin icon in dropdown

---

examples/features/unmanaged/ray/ray_hp_search.py

I suppose ray is also very opinionated on how they want their modules to be imported.

test: fix `ray.air.session` import.

---

docs/reference/deploy/helm-config-reference.rst
docs/reference/deploy/master-config-reference.rst
docs/reference/training/experiment-config-reference.rst
docs/release-notes/log-policies.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/pkg/model/task_container_defaults.go
master/pkg/model/task_container_defaults_test.go

Adds docs for log policies PR.

docs: log policies

---

docs/insert-version-url.py

Fix some out of order imports failing tests on main.
Is a test fix.

docs: fix linting failure

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/linkCell.tsx
webui/react/src/pages/F_ExpList/glide-table/custom-renderers/cells/tagsCell.tsx

Show a placeholder '-' for null values in data cells.
At the experiment list table, null values are denoted by '-' placeholder.
Sort and filter should work as expected. 
WEB-1779

feat: Show "-" for null values in data cells 

---

harness/determined/cli/experiment.py
harness/determined/common/experimental/experiment.py

SDK Experiment objects can now `delete_tensorboard_files`. This (recursively) removes the directory
```
<tb-root>/tensorboard/experiment/<exp-id>
```
on master.
See #8227 for details. Then delete the tensorboard files with the SDK:
```python
client.login(<info>)
exp = client.get_experiment(<exp>)
exp.delete_tensorboard_files()
```

feat: delete TB files from the SDK

---

.circleci/real_config.yml

e2e_gpu_quarantine is failing on main because one of the splits has no tests, but there is only one test to run so we don't need splits at all. I could fix the shell to not panic if we run a useless split, but I think it should still, honestly. That's a lot of wasted resources.
Is a test.

fix(tests): lower e2e_gpu_quarantine parallelism

---

harness/determined/experimental/client.py

`list_experiments` was missing from `experimental.client` due to an oversight. 

chore: add list_experiments to experimental.client

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

fix: Cell can be undefined in experiment list table

---

master/internal/experiment.go

Missed `err == nil` condition in a `handleContinueExperiment` function in a previous ticket. Fixed it by adding the if condition.

fix: fixed bug in error handling in experiment.go

---

harness/determined/deploy/aws/injector/master.yaml.tmpl
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/lore.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml

Deployment failed under `--scheduler-type=priority` due to a broken reference in the template. This fixes that.
[DET-9941]
[DET-9941]: https://hpe-aiatscale.atlassian.net/browse/DET-9941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: aws deployment can deploy priority scheduler

---

e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/nightly/test_distributed.py
harness/determined/pytorch/dsat/__main__.py

This PR shortens up the `dsat` ([deepspeed autotune](https://docs.determined.ai/latest/model-dev-guide/api-guides/apis-howto/deepspeed/autotuning.html)) e2e tests by having them run only an 4-trial search, rather than the default 64 trials (as controlled by the `--max-trials` flag).
Inspect the Circle CI test logs and verify that the tests do not come close to hitting the 30 min timeout limit.

chore: short dsat e2e tests

---

webui/react/src/components/FilterForm/components/FilterForm.tsx
webui/react/src/components/FilterForm/components/FilterFormStore.ts
webui/react/src/components/FilterForm/components/type.ts
webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx
webui/react/src/pages/F_ExpList/glide-table/MultiSortMenu.tsx

- Create a new conditional column header menu item that appears when one or more filter for the column is applied.
- Show number of applied filters as a count for the column. 
- Clicking the button will clear all filters effecting the column and reload the table. 
- Update the menu label for “Filter by this column” to be “Add filter”
- Update the “reset filters” button copy in the filters menu from “Reset” to “Clear filters”
At the experiment list table, create multiple filters on multiple columns, with or without group, you should be able to clear all filters of one column from that column header.
Previous functionality of clicking close icon to clear one single filter should work as expected.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/RE …

feat: clear filter from experiment table header

---

harness/determined/deploy/aws/templates/lore.yaml

service now only works for versions after [pull/331](https://github.com/determined-ai/lore/pull/331)
https://hpe-aiatscale.slack.com/archives/C05R8V26SF4/p1699472261355759?thread_ts=1699301113.664059&cid=C05R8V26SF4
maybe we could open a port range instead of a single one to support older hashes too

chore: update the lore service port

---

.circleci/real_config.yml

chore: temporarily disable CI upload job

---

master/internal/api_tasks.go

- Adds `canGetAllocation()`, which is called in `GetAllocation()`
- Changes `CanGetExperiment()` to `CanGetExperimentArtifacts()` in `canEditAllocation()`
- Confirm that a user with any role (Viewer, Editor, ClusterAdmin, WorkspaceAdmin, WorkspaceCreator) can view allocations associated with a workspace they have access to
- Confirm that a user without a role cannot view an allocation in any workspace
DET-9922

fix: added permission check on GetAllocation (DET-9922)

---

webui/react/src/pages/Cluster/ClusterOverallStats.tsx

Before: 
After:
Log in to OSS or someone with `canAdministrateUsers` permission on EE
Check the clusters page after creating some tasks
Stats cards with 0 should not show up
WEB-1616

fix: Hide cluster stats when 0

---

harness/determined/cli/master.py

temporary fix to allow `--json` to be passed into `det master config`. 
https://hpe-aiatscale.atlassian.net/browse/MLG-1280 has been filed for a long-term fix.
run `det master config --json` and verify successful output.

fix: allow --json in det master config CLI command

---

harness/determined/deploy/aws/templates/lore.yaml

chore: fail deployment if launching part of the service fails

---

master/internal/usergroup/group_intg_test.go
master/internal/usergroup/postgres_groups.go

Making this change for another EE PR where we want to run this method as a Bun transaction.
Pass circleCI tests

chore: converting SearchGroupsWithoutPersonalGroups into tx

---

harness/determined/common/experimental/determined.py
harness/determined/common/experimental/workspace.py
harness/determined/experimental/client.py

* Create a Workspace from client / Determined
* Delete a Workspace from client / Determined
* Create a Project from Workspace
* Delete a Project from Workspace
```python
client.login(<login>)
work = client.create_workspace(<name>)
proj = work.create_project(<name>)
work.delete_project(<name>)
client.delete_workspace(<name>)
```
while verifying that the projects / workspaces were created/deleted.

feat: add workspace/project creation/deletion

---

webui/react/src/components/CreateGroupModal.tsx
webui/react/src/components/CreateUserModal.tsx
webui/react/src/components/JupyterLabModal.tsx
webui/react/src/components/ManageGroupsModal.tsx
webui/react/src/components/ProjectMoveModal.tsx
webui/react/src/components/Table/TableBatch.tsx
webui/react/src/components/Table/TableBulkActions.tsx
webui/react/src/components/WebhookCreateModal.tsx
webui/react/src/hooks/useModal/Checkpoint/useModalCheckpointRegister.tsx
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.test.tsx
webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx
webui/react/src/pages/Cluster/ClusterHistoricalUsageCsvModal.tsx
webui/react/src/pages/JobQueue/ManageJob.tsx
webui/react/src/pages/WorkspaceDetails/RoleRenderer.module.scss
webui/react/src/pages/WorkspaceDetails/RoleRenderer.tsx

[WEB-1820]
- Check if there's no place antd select component is used
- Check if all replaced select components has solid background
- Check if all replaced select components work as expected
[WEB-1820]: https://hpe-aiatscale.atlassian.net/browse/WEB-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: replace antd select with hew select

---

webui/react/src/components/FilterForm/components/FilterFormStore.ts

this updates a comment in the filterformstore to more accurately describe the function of a variable.
comment only -- no testing required
no ticket

chore: filterformstore comment re: change tracking

---

e2e_tests/tests/cluster/test_model_registry_rbac.py

Fixes regression in a test here [https://github.com/determined-ai/determined-ee/commit/af995bac832416b051807eace4bff36470d6eaf8#diff-a9b7f55f9139ab19c01a[…]72aba40dbbe7ffe21002fR354](https://github.com/determined-ai/determined-ee/commit/af995bac832416b051807eace4bff36470d6eaf8#diff-a9b7f55f9139ab19c01af178349c7bbde6e3c84666872aba40dbbe7ffe21002fR354)
EE passes here https://app.circleci.com/pipelines/github/determined-ai/determined-ee/10129/workflows/e317463f-c75d-4d6b-93d3-e4ce85edc1d6/jobs/486806

test: fix model registry rbac wrong user regression

---

docs/manage/upgrade.rst
docs/setup-cluster/on-prem/options/linux-packages.rst
docs/setup-cluster/slurm/_index.rst

Purpose: https://hpe-aiatscale.atlassian.net/jira/software/projects/ENGDOCMLDX/boards/57?selectedIssue=ENGDOCMLDX-7
The upgrade instructions should cover specific upgrade instructions when installing from linux packages (the RPM command option is -U (upgrade) instead of (-i) install) plus once the upgrade is complete the determined-master.service needs to be reloaded and restarted:
sudo systemctl daemon-reload
sudo restart determined-master.service
Without this reload and restart, the state is out of sync and launched jobs may fail.     
Might be useful to indicate that running jobs should not be interrupted by this process.

docs: Update upgrade instructions

---

webui/react/src/pages/Cluster/ClusterOverallStats.tsx
webui/react/src/utils/cluster.ts

Calculate cluster overall stats card the same as slots allocation bar [here](https://github.com/determined-ai/determined/blob/292c75d6035de2cd57c79e9d30ba8d6ba2d42006/webui/react/src/components/ResourcePoolCard.tsx#L234)
Launch something on k8s cluster, and look at the cluster page.
The resource pool overall stats card should be consistent with the allocation bar. 
WEB-1822

fix: Calculate allocation bar stats same as overview [WEB-1822]

---

.circleci/real_config.yml

Actually cache Determined's Python install and Python versions for e2e tests.
Cache miss
https://app.circleci.com/pipelines/github/determined-ai/determined/48166/workflows/ccbb0309-0d8d-4c12-8251-d9a7eb57ce80
Cache hit
https://app.circleci.com/pipelines/github/determined-ai/determined/48168/workflows/f462107a-d70a-4956-acc0-ea41d9a290fc

ci: cache install Python

---

.circleci/real_config.yml

- Store .npm artifact since we dont save npm logs currently and we've spent hard time to know the reason why some ci such as [this one](https://app.circleci.com/pipelines/github/determined-ai/determined/47782/workflows/29dbe79c-3bc1-423e-bb5a-c041931654d0/jobs/2039843/steps) failed.

ci: store npm log artifacts

---

webui/react/src/pages/F_ExpList/glide-table/GlideTable.tsx

ref: https://github.com/determined-ai/release-party-issues/issues/1014#issuecomment-1813205887
minor regression from #8342
Same work as #8324
- Check if there is a pin icon for Pin / Unpin item in column header menu

fix: add back pin icon in experiment list header

---

.circleci/real_config.yml
.devcontainer/devcontainer.json
.github/workflows/lint-react.yml
CONTRIBUTING.md

Resolve an issue with npm install failing with an error like "Exit handler never called!"
Automated testing

chore: bump CI node version to 20.9.0

---

master/internal/command/command_service.go

Log, instead of returning, an error in RestoreAllCommands. This will match pre-actor refactor behavior.
N/A

chore: log RestoreAllCommands error

---

master/internal/usergroup/postgres_groups.go

For use in a user auth EE ticket, export `AddGroupTx`.
N/A
DET-9937
DET-9876

chore: convert & export AddGroupTx

---

docs/setup-cluster/k8s/install-on-kubernetes.rst

per [discussion](https://hpe-internal.slack.com/archives/C02D5U8ERU5/p1700600218056439?thread_ts=1700596700.607509&cid=C02D5U8ERU5), we formally support 1.25

Update k8s install info

---

master/internal/experiment.go

Always update the experiment search state when a trial reports early exit.
This resolves some corner case issues where the experiment searcher state is not correctly updated when there are database issues restoring trials.

chore: update trial complete or early exit to always notify searcher

---

.circleci/real_config.yml
harness/determined/deploy/aws/deployment_types/base.py
harness/determined/deploy/aws/deployment_types/simple.py

Cloudformation logs are removed when we bring CI clusters down, this option will retain them so logs can be examined when tests fail.

chore: preserve CI logs when bringing an AWS cluster down

---

master/internal/api_tasks.go
master/internal/core.go
master/internal/core_checkpoint.go
master/internal/db/postgres_experiments.go
master/internal/rm/agentrm/provisioner/aws/aws.go
master/internal/trial.go

Various logging fixes.
Tested manually extensively, needs no release party testing.

chore: cleanup some spurious cluster logs

---

docs/insert-version-url.py

Correct script name in docstring, inline small function, change function docstring to comment (since it describes only a particular variable within the function, not the entire function).

chore: clean up version dropdown update script

---

webui/react/__mocks__/hew/Tooltip.tsx
webui/react/package-lock.json
webui/react/package.json

This updates Hew to version 6.12

chore: Update Hew Version to 0.6.12

---

harness/determined/cli/dev.py

add an alias to `det dev bindings`

chore: add aliases to det dev commads

---

.circleci/real_config.yml
e2e_tests/pytest.ini
e2e_tests/tests/cluster/test_logging.py
e2e_tests/tests/conftest.py

This reverts commit 50535f113012ffb437f0f23a7343b8db0f070695.

chore: Revert "test: quarantine GPU execution of test_task_logs (#8261)"

---

harness/determined/common/experimental/experiment.py
harness/determined/experimental/client.py
harness/tests/determined/common/experimental/test_experiment.py

* Experiment.state used to be loaded directly from bindings, and so had a bindings.experimentV1State type. This casts it to the SDK's ExperimentState.
Bonus:
* TrialState is now publicly exposed in `client`.
[MLG-1347]
Get an experiment and look at the state. Compare with members of `client.ExperimentState`.
```python
exp = client.get_experiment(<exp_id>)
```
[MLG-1347]: https://hpe-aiatscale.atlassian.net/browse/MLG-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Experiment state now is an ExperimentState

---

webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
webui/react/src/pages/TrialDetails/TrialDetailsHeader.tsx

[WEB-1858]
- Check if trail detail header does not have `Hyperparameter Search` option for unmanaged multi trial experiments
- Check if `Hyperparameter Search` option should not be visible in in trial menu option in trial tab of multi trial experiments
[WEB-1858]: https://hpe-aiatscale.atlassian.net/browse/WEB-1858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: hide hyperparameter search for unmanaged multi tiral experiments

---

webui/react/src/constants/states.ts
webui/react/src/pages/ExperimentDetails/ExperimentDetails.test.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts
webui/react/src/types.ts
webui/react/src/utils/experiment.ts

Using new enhancements to `det e continue`, add a conditional action button to non-detached, multi-trial experiments with valid searcher type (`grid, random`) that appears on incomplete (`cancel, error`) terminal experiments.
This functionality will allow users to reactivate a multi-trial experiment without allowing for any configuration changes.
The permission for Retry is the same as the permission for `Fork`
Create/Locate a valid experiment for retry:
- multi-trial
- Errored or cancelled
- Searcher type grid or random
`Retry` button should show up before `Fork` on the top right
Click on `Retry` then confirm
The experiment should be resumed to `Queued` state
WEB-1859

feat: Enable multi-trial "retry" for errored/cancelled exp

---

webui/react/Makefile

there is no submodule anymore
git submodule status

chore: take out submodule update cmd

---

.circleci/real_config.yml
.circleci/scripts/upload_test_results.py

chore: re-enable CI metrics upload

---

master/internal/rm/agentrm/agent_state.go
master/internal/rm/agentrm/agents.go
master/internal/rm/agentrm/resource_pool.go

In the actor system, agents registered themselves with pools and pools fetched agent states
by asking those that had registered with them. After the refactor, pools just call the agent service
directly, so they need to pass a filter otherwise they end up with all the agents.
Launch a bunch of experiments, make sure agent counts look right.
Honestly, completely shocked this didn't completely break e2es. Kinda make sense since the
schedulers haven't changed much since RPs were heterogeneous but still.
DET-9997

fix(agentrm): resource pools must filter agents.list() by name

---

webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx

[WEB-1866]
- Check if project list gets updated after archive / unarchive projects
[WEB-1866]: https://hpe-aiatscale.atlassian.net/browse/WEB-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fetch projects after archive/unarchive

---

harness/determined/common/experimental/trial.py

experimentId is there in the bindings response; sometimes it's useful. Adding it into the object via `_hydrate`..
[MLG-1414]
Create a trial object any way you like (other than directly via the constructor). Examine trial ID.
```python
client.login(<info>)
tr = client.get_trial(<trial_id>)
trs = client.get_experiment(<exp_id>).list_trials()
...
```
[MLG-1414]: https://hpe-aiatscale.atlassian.net/browse/MLG-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add experiment id to SDK Trial objects

---

master/internal/stream/system_intg_test.go
master/internal/stream/test_util.go
master/test/streamdata/stream_data.go

Instead of using the msg structs for integration testing, we will instead use string representations to allow for easier test creation and improved reusability of existing test structure.
- Run automated streaming tests
DET-9996

refactor: use string representations for complex structs and subtests 

---

harness/determined/deploy/aws/injector/master.yaml.tmpl
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/lore.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml

Add addition redirect for /genai, keeping /lore around for backward compatibility. Context is that the formal name of the product will be Generative AI Studio, so we need to update references from lore -> genai
Change `master.yaml.tmpl` and run  `python -m determined.deploy.aws.master_config_inject`
Outstanding clean up after Lore side changes land: https://hpe-aiatscale.atlassian.net/browse/MLG-1431
In both cases, I also checked that det UI is working normally.
`det deploy aws up --cluster-id swy-lore-test3   --region us-west-2 --keypair szewai-determined-aws --compute-agent-instance-type g4dn.12xlarge --max-dynamic-agents 10 --det-v e8cd4cf4d41b16327b2ea23096e9e240c9e4efcb  --max-idle-agent-period 60m   --deployment-type lore --lore-version 9d97be28`
`det deploy aws up --cluster-id …

feat: add lore redirect

---

webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/utils/experiment.ts

Using new enhancements to `det e continue`, add a conditional action button to non-detached, multi-trial experiments with valid searcher type (`grid, random`) that appears on completed experiments with errored trials.
Create/Locate a valid experiment for retry:
- multi-trial
- completed with at least 1 errored trial
- Searcher type grid or random
`Retry` button should show up before `Fork` on the top right
Click on `Retry` then confirm
The experiment should be resumed to `Queued` state
For single trial experiments, and completed experiments with no errored trial, the Retry button should not show up.
WEB-1860

feat: Retry for multi-trial experiments with errored trials

---

.github/workflows/performance-tests.yml

Intermediate PR that focuses on just implementing CI changes that'll allow testing custom DB snapshot usage in the CLI.

ci(performance): use latest versions for CLI and deployment

---

master/internal/db/postgres_command.go
master/internal/db/postgres_command_intg_test.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_test_utils.go

Increase test coverage with some db tests.
tests

test: add more Go db tests

---

webui/react/src/hooks/useModal/HyperparameterSearch/useModalHyperparameterSearch.tsx
webui/react/src/stores/cluster.tsx

ISSUE:
On K8 clusters, for a hyperparameter search, the `slots per trial` of 0 is a valid entry.
FIX:
Allow the value `0` for `slots per trial`.
repeat the following for both non k8 cluster and a gke cluster.

fix: allow slots per trial to be 0 [WEB-1871]

---

.circleci/real_config.yml
go.mod
master/cmd/cover-regex/cover_regex.go

Adds a Go command used in CI that looks at coverage reports and outputs if any function calls need to be required.
This will help us require and enforce coverage on all database queries. 
This can start with ```Bun``` and eventually move towards other things that we think should be required to be tested.
Looks reasonable
https://app.circleci.com/pipelines/github/determined-ai/determined/48709/workflows/5f97bac7-c81e-417f-a9cd-806617fa9f06/jobs/2105800
I'm sure there might be an issue or two but as we iterate and fix issues we should gain confidence to make it fail CI.
https://circleci.com/api/v1.1/project/github/determined-ai/determined/2105800/output/114/0?file=true&allocation-id=6568ca3413d3c30e791531a2-0-build%2FABCDEFGH
See [Release …

ci: add Go coverage regex match so we can require some functions to be tested

---

master/internal/api_experiment.go

fix(api): delete experiment error handling corrections

---

performance/Makefile

Use `DET_MASTER` instead of `DET_URL` so it's pulled from env vars, and default to localhost.

test: make `DET_MASTER` configurable in the perf test `Makefile`.

---

docs/integrations/notification/_index.rst

Improve the webhooks documentation particularly around the new webhook tasklog feature. Apply documentation standards.

docs: Improve webhooks tasklog

---

webui/react/src/pages/F_ExpList/glide-table/exceptions.tsx

fix: correct docs link in empty project [WEB-1879]

---

master/internal/db/postgres_experiments.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_test_utils.go

Adds more tests to ```internal/postgres_experiment.go```.
Test passes.

test: add more tests to db/postgres_experiments.go

---

.circleci/real_config.yml
e2e_tests/pytest.ini
e2e_tests/tests/conftest.py
e2e_tests/tests/model_hub/test_mmdetection.py

- Mess with circleci test selection to allow for files with `pytest.mark.skip`ped tests.
- Get rid of broken mmdetection quarantine
- Skip all failing tests
- File https://hpe-aiatscale.atlassian.net/browse/MLG-1439
N/A

test: skip all failing `mmdetection` tests.

---

master/internal/stream/metrics.go
master/internal/stream/system.go
master/internal/stream/test_util.go
master/pkg/stream/stream.go
master/static/migrations/20231116155837_add-metrics-trigger.tx.down.sql
master/static/migrations/20231116155837_add-metrics-trigger.tx.up.sql
master/stream.py

Makes metrics append-only, and resolves deadlock issue on pq.Listener timeouts 
- Run existing integration tests 

fix: makes metrics append-only & resolves deadlock on listener timeouts

---

master/internal/stream/authz_basic_impl.go
master/internal/stream/authz_iface.go
master/internal/stream/checkpoints.go
master/internal/stream/system.go
master/internal/stream/system_intg_test.go
master/internal/stream/test_util.go
master/static/migrations/20231126215150_add-checkpoints-trigger.tx.down.sql
master/static/migrations/20231126215150_add-checkpoints-trigger.tx.up.sql
master/stream.py
master/test/streamdata/stream_data.go
master/test/streamdata/stream_trials.sql

First pass at streaming updates on checkpoints. Missing down migration and tests, but code compiles. 

feat: streaming updates checkpoints

---

docs/setup-cluster/_index.rst

Reverts determined-ai/determined#8561

Revert "docs: Add a link to mldes trial"

---

docs/manage/users-remote.rst

docs to support feature updates via #1153

docs: Update oidc group claim name notes

---

harness/determined/deploy/aws/cli.py

chore: include cluster name in stack deletion confirmation

---

docs/release-notes.rst

I had to re-release 0.26.5 due to technical snafus and forgot to add a release note for the new version.

chore: release notes for 0.26.6

---

.circleci/real_config.yml
webui/react/Makefile

[WEB-1276]
- Check if CI passes
- Check if `make build` does not install playwright browser binary
[WEB-1276]: https://hpe-aiatscale.atlassian.net/browse/WEB-1276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

build: avoid installing playwright by `make build`

---

master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/task/allocation_service.go
master/internal/task/allocation_service_iface.go
master/internal/task/allocation_service_test.go
master/pkg/syncx/queue/queue.go
master/pkg/syncx/queue/queue_test.go

We had a bug where a user tried to pause an experiment but it unexpectedly was killed. The root
cause was that we don't persist the ready bit, so it is lost on a master crash, and the ready bit is what
we check to decide if we should bother with graceful termination at all.
Wrote a failing test, fixed it; needs no manual testing.
I doodled for a bit but ended up coming back to a minimal fix. The first commit is exactly what I needed
to effectively test this and the second is the fix, if you would like to review that way. Last commit is a bit of cleanup.
At this point, rendezvous is still not entirely persisted. If a master crash happens while we are mid-rendezvous, it
will still result in weird failures. I'm going to try a more comprehensive fix in a follow up, but I think that fix will …

fix(tasks): persist rendezvous readiness

---

master/internal/stream/authz_basic_impl.go
master/internal/stream/authz_iface.go
master/internal/stream/projects.go
master/internal/stream/system.go
master/internal/stream/system_intg_test.go
master/internal/stream/test_util.go
master/static/migrations/20231211011129_add-projects-trigger.tx.down.sql
master/static/migrations/20231211011129_add-projects-trigger.tx.up.sql
master/stream.py
master/test/streamdata/stream_data.go

Adds the project streaming entity and basic intg tests for projects.
Run the intg tests and make sure they pass.

feat: add projects streaming entity

---

docs/release-notes/checkpoint-fs-server-download.rst
e2e_tests/tests/cluster/test_checkpoints.py
harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/deploy/local/cluster_utils.py
master/internal/api_tensorboard.go
master/pkg/checkpoints/checkpoints.go
master/pkg/checkpoints/gcs/gcs_checkpoints.go
master/pkg/checkpoints/local/local_checkpoints.go
master/pkg/checkpoints/s3/s3checkpoints.go
master/pkg/schemas/expconf/storage_config.go

Adds local checkpoint storage download through server.
Automated tests updated.
DET-9589

feat: add local checkpoint storage download through server

---

e2e_tests/tests/model_hub/test_mmdetection.py

mmdetection tests are busted and have no support whatsoever.

test: skip more `mmdetection` tests [DET-10036]

---

master/internal/user/external_users.go
master/internal/user/postgres_users.go

Porting relevant changes to `ByExternalToken` to OSS, as part of the EE ticket to bunify postgres scim.
N/A

chore: update byExternalToken signature

---

bindings/generate_bindings_py.py
harness/determined/common/api/bindings.py
harness/determined/common/experimental/experiment.py
harness/tests/determined/common/experimental/test_experiment.py

URL-encode path parameters that are strings in bindings. 

chore: encode path parameters in generated bindings [MLG-781]

---

webui/react/package-lock.json
webui/react/package.json

This update provides a fix for WEB-1892
WEB-1892

chore: Upgrade hew to 0.6.19

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

Add indication for loading before loading for the first time. The table was previous blank because we passed 0 as `rows` when initialization. 
At the experiment list table, using break point or running on slower internet, verify that the table should have loading indicators before the data is loaded for the first time.
WEB-1883

fix: Show experiment loading state before first loading

---

docs/release-notes.rst
docs/release-notes/fix-master-download.rst
docs/release-notes/list-active-users.rst
docs/release-notes/remove-dry-run-det-deploy-aws.rst

docs: add release notes for 0.26.7

---

webui/react/src/components/Metadata/EditableMetadata.tsx
webui/react/src/components/Metadata/MetadataCard.module.scss
webui/react/src/components/Metadata/MetadataCard.tsx
webui/react/src/pages/ModelVersionDetails.module.scss
webui/react/src/pages/ModelVersionDetails.tsx

Updates ModelVersionDetails page to use `<Surface>`, `<Section title="">` instead of antd.Card
View a model with multiple versions; check the version details page for any unexpected changes from the current model version page

chore: Model Version pages to Hew UI [WEB-1814]

---

master/internal/sproto/task.go

chore: fix a typo in RRI

---

webui/react/package-lock.json
webui/react/package.json

Updates hew to 0.6.20
which contains a fix for: https://hpe-aiatscale.slack.com/archives/CKQ3EV0G6/p1704208658527359

chore: update hew to 0.6.20

---

docs/release-notes/allow-empty-model-definitions.rst

Adds release note documenting breaking change due to https://github.com/determined-ai/determined/pull/8422
- Does not require testing, only adds release note

chore: adds release note for breaking CLI experiment creation change

---

README.md

Minor change to the github readme: add links to the examples folder and the examples repo.

docs: Mention examples in the git readme

---

docs/manage/security/scim.rst
docs/manage/users-remote.rst
docs/reference/deploy/master-config-reference.rst

Merge these changes with #[1139 ee](https://github.com/determined-ai/determined-ee/pull/1139) so that when the change is released, the docs are updated at the same time. Then Close this PR.
Document the `scim` `display_name` attribute to support the code change in 1139 ee
https://github.com/determined-ai/determined-ee/pull/1139

docs: Document scim display name attribute

---

webui/react/package-lock.json
webui/react/package.json

Update hew to 0.6.21, which contains a fix for WEB-1907

chore: Update hew to 0.6.21

---

harness/determined/exec/tensorboard.py

print a message to TB logs to indicate it's waiting for metrics. Actual fix depends on DET-10001

chore: print TB status message to logs [MLG-1119]

---

.github/workflows/performance-tests.yml
docs/release-notes/db-snapshot-flag.rst
harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/simple.py
harness/determined/deploy/aws/templates/simple-rds.yaml

Adds a `--db-snapshot` flag to provide a DB snapshot to initialize the RDS instance with for the Simple RDS deployment type.
Local testing of added template logic done -- the username/password parameters are mutually exclusive with the snapshot parameter.
This change is made not to fill a user request but to enable the performance testing suites to boot instances pre-configured with the data necessary to run tests instead of having to manually load the data after boot.
INFENG-269

feat(cli/deploy): add db snapshot flag for simple-rds [INFENG-269]

---

e2e_tests/tests/experiment/test_tf_keras.py

Make tf keras tests happy: set the validation size to the true dataset size (rather than the batch size like before)
N/A

test: fix `test_tf_keras_parallel`.

---

master/pkg/stream/stream_test.go

These tests ensure that broadcast does not send messages that do not fit the filter provided. This covers cases that intg tests cannot guarantee due to concurrency.
Make sure these unit tests pass.

chore: broadcast unit tests

---

master/internal/stream/system_intg_test.go
master/internal/stream/test_util.go
master/test/streamdata/stream_data.go

No manual testing needed - ensure these tests pass

chore: add fall in and fall out tests

---

webui/react/src/components/Table/ResponsiveTable.tsx
webui/react/src/components/Table/TableFilterDropdown.module.scss
webui/react/src/components/Table/TableFilterDropdown.tsx

For some reason the `TableFilterDropdown` components lost their styling. These components open in a portal outside of the application root components, and were not being wrapped in the `themeClass` therefore they did not have the correct styling applied. 
This fixes the theming issue by adding the `themeClass` the the dropdowns.
1. Visit pages with Tables in the application, for example the Tasks or Model Registry page. 
2. Click the filters on the table and ensure that styling is correctly applied to the dropdown component. 
WEB-1952

fix: Add theme to TableFilterDropdown [WEB-1952]

---

harness/determined/cli/notebook.py
harness/determined/cli/remote.py
harness/determined/cli/shell.py

This PR takes out `fmt: off` comments to reformat the files with the standard automated way.

style: reformat `det (n|t|s|c)` arguments code.

---

master/internal/stream/projects.go

Forgot to push my last commit before merging projects. 

chore: update comments

---

harness/determined/cli/experiment.py

- `activate` is a rather confusing counterpart to `pause`. add `unpause` alias, and also mention "pause" in the help message.
- https://hpe-aiatscale.slack.com/archives/CSG3W08JY/p1701980883539129?thread_ts=1701979814.635459&cid=CSG3W08JY

feat: add `det e unpause` alias.

---

docs/release-notes.rst
docs/release-notes/allow-empty-model-definitions.rst
docs/release-notes/checkpoint-fs-server-download.rst

docs: add release notes for 0.27.0

---

harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/deployment_types/vpc.py
harness/determined/deploy/healthcheck.py

https://hpe-aiatscale.atlassian.net/browse/MLG-1464
test deploying valid and invalid hashes
```
import sys
from determined.common import api
from determined.common.api import certs
from determined.deploy import healthcheck
addr = sys.argv[1]
cert = certs.Cert(noverify=True)
healthcheck.wait_for_genai_url(addr, timeout=5, cert=cert)
```
sample output
```
Waiting for GenAI instance to be available................................................................................................................................
Determined cluster has been deployed, but GenAI health check has failed.
For details, SSH to master instance and check /var/log/cloud-init-output.log.
```

feat: add health check for genai deployments

---

webui/react/src/pages/F_ExpList/glide-table/ColumnPickerMenu.module.scss
webui/react/src/pages/F_ExpList/glide-table/ColumnPickerMenu.tsx

If column picker has large number of rows (120+), when closing, there is a noticeable jitter as showed in the screenshots
https://github.com/determined-ai/determined/assets/40620519/b60b4cdb-0349-4eca-a2a6-35e778f81ab1
This issue can be fixed with introducing react-window `FixedSizeList` for optimization. 
This also includes a horizontal scroll bar to show the overflow name of columns.
Before: 
After:
At the experiment list page, click on the `Columns` button
Switch the tab to the one with over 120 columns (could be `Metrics` or `Hyperparameters`)
Click outside of the column picker, the column picker should close without any jitter.
Select/unselect columns, everything should work as expected. …

fix: use FixedSizeList for column picker

---

helm/charts/determined/Chart.yaml

Update path to eliminate a redirect.
Relates to #8675 
click the link and see if it loads?

chore: update helm image path to use main branch

---

docs/setup-cluster/k8s/setup-eks-cluster.rst

In "Set up and manage an AWS Kubernetes (EKS) Cluster", fix broken link to eksctl installation page.

docs: Fix broken ext link

---

docs/setup-cluster/on-prem/requirements.rst

This PR updates the installation instructions for Docker, including:
- Updating references from CentOS 7, which goes EOL later this year, to generic "Enterprise Linux" to include AlmaLinux, Rocky Linux, and RHEL
- Update `yum` commands to more performant `dnf` in enterprise Linux instructions
- Update `apt-get` commands to more performant `apt` in Ubuntu
- Updated Docker and NCR install steps from Docker and NVIDIA Docs
- Adding a section about installation on WSL
These steps have been manually tested on Ubuntu 22.04 and AlmaLinux 8.

docs: Update Docker Installation Instructions

---

docs/setup-cluster/on-prem/options/wsl.rst
docs/setup-cluster/on-prem/requirements.rst
docs/tutorials/quickstart-mdldev.rst

Updating a couple recent docs additions to pass linter.

[docs] Update docs to pass linter

---

docs/setup-cluster/on-prem/options/wsl.rst
docs/setup-cluster/on-prem/requirements.rst
docs/tutorials/quickstart-mdldev.rst

Reverts determined-ai/determined#8703

Revert "docs: Update docs to pass linter"

---

docs/setup-cluster/on-prem/options/wsl.rst
docs/setup-cluster/on-prem/requirements.rst
docs/tutorials/quickstart-mdldev.rst

Updating docs to pass docs linter

docs: Update docs to pass linter

---

docs/reference/training/api-det-reference.rst
docs/reference/training/api-pytorch-reference.rst

api-det-reference.rst and api-pytorch-reference.rst had each other's tags.
Look at the links on https://docs.determined.ai/latest/reference/training/_index.html

docs: fix references on children of "training reference" root

---

webui/react/package-lock.json
webui/react/package.json

Upgrade to Vite 5.0.11
Hew PR: https://github.com/determined-ai/hew/pull/97
Project builds and pages works as expected. 
WEB-1875

chore: Upgrade to vite 5

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/setupTests.ts

[WEB-1877]
Migration guild: https://vitest.dev/guide/migration.html#migrating-from-vitest-0-34-6
- Check if all react test cases pass
- Check if web app is runnable and buildable
[WEB-1877]: https://hpe-aiatscale.atlassian.net/browse/WEB-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: upgrade `vitest@1.2.1`

---

master/internal/db/postgres_checkpoints_intg_test.go
master/internal/db/postgres_trial.go
master/internal/rm/agentrm/agent.go

Wanted to cover this to make sure it was working as expected after a bug report near it.
Is a test.

test: cover db.GroupCheckpointUUIDsByExperimentID

---

docs/release-notes.rst
docs/release-notes/db-snapshot-flag.rst
docs/release-notes/jupyter-root.rst
docs/release-notes/master-mount.rst

docs: add release notes for 0.27.1

---

master/.golangci.yml
master/internal/api_user.go
master/internal/user/postgres_users.go
master/internal/user/postgres_users_intg_test.go
master/pkg/model/user.go
master/pkg/model/user_test.go

Still need tests on the service, I'll do in a follow up.
Found a bug while doing this, wow.
DET-10061

chore: add more tests for internal/users/postgres_users.go

---

webui/react/src/pages/F_ExpList/glide-table/exceptions.tsx

[WEB-1951]
- Check if the new URL is `/get-started/webui-qs.html` in the empty experiment list
note: as of 01/25/2024, the doc link is not publicly available yet. 
[WEB-1951]: https://hpe-aiatscale.atlassian.net/browse/WEB-1951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: the new quick start guide link

---

docs/_static/version-switcher/versions.json

Revert 0.27.0 dropdown insert. Add version 0.26.6 to dropdown.
No Testing Required
No Ticket

docs: Fix dropdown url

---

.circleci/real_config.yml

We got some timeouts on some of these, so slap on a retry.

ci: retry git fetch for early stopping checks

---

harness/determined/deploy/healthcheck.py

chore: clean up extra prints

---

docs/release-notes/gcs-429.rst
harness/determined/common/storage/gcs.py
harness/determined/tensorboard/gcs.py

GCS client for checkpoints and tensorboards should retry on 429.
By popular demand https://determined-community.slack.com/archives/CV3MTNZ6U/p1706724799473879
N/A

feat: GCS client should retry on `TooManyRequests`.

---

webui/react/src/components/HyperparameterSearchModal.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCodeViewer.test.tsx
webui/react/src/pages/F_ExpList/CompareParallelCoordinates.tsx
webui/react/src/pages/F_ExpList/glide-table/columns.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/types.ts
webui/react/src/utils/experiment.ts

[WEB-1952]
- Check if all pages and actions that were related to `experiment.config` should work as before
- Check if the deprecated config is not used anywhere in web
- Parallel Coord comparison view doesnt display chart even before this PR. It is a known bug.
[WEB-1952]: https://hpe-aiatscale.atlassian.net/browse/WEB-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: replace experiment config

---

docs/reference/deploy/master-config-reference.rst
docs/release-notes.rst

Reverts determined-ai/determined#8777
reason: adding breaking changes to 0.27.2 release notes

Revert "docs: Update oidc and saml docs"

---

docs/release-notes.rst

A few separate changes:
* A couple EE features/improvements didn't make the EE release notes. This adds them.
* A couple EE features/improvements were added tothe wrong version in the EE release notes. This moves them to the one they were actually released as a part of.
* Moves EE-only release notes to OSS and tags them (*Enterprise edition only*).
- starting with 0.26.5
* Tags EE-only release notes that were already in OSS with an explicit (*Enterprise edition only*).
- starting with 0.26.5

docs: adds/corrects EE changes, merges to OSS

---

docs/setup-cluster/on-prem/_index.rst

Adds mention of .RPM files alongside .DEB files to https://docs.determined.ai/latest/setup-cluster/on-prem/_index.html
Tested, formatted, and built locally.

docs: Add mention of RPMs to on-prem _index.rst

---

docs/release-notes.rst

Old version of a note was accidentally left in.

docs: remove duplicated note

---

docs/setup-cluster/on-prem/requirements.rst

https://github.com/determined-ai/determined/issues/8826

Fix broken ref

---

webui/react/package-lock.json
webui/react/package.json

Fixes bugs on Metrics tab of Experiment Details page (WEB-1957 and WEB-1975)
WEB-1957:
Find an experiment with two metrics charted. Open the metrics tab, then open another tab, and return to the metrics tab. Should not see unnecessary scrollbars.
WEB-1975:
Find an experiment with three metrics (more than one row) charted. Open the metrics tab and verify that all labels are on the same surface as the chart.
WEB-1957 and WEB-1975

fix: update hew with bugfixes

---

master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/agentrm/agent_resource_manager_intg_test.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/resource_manager_iface.go
master/internal/sproto/task.go

Remove dead code from the RM interface.
Don't break any existing tests.
This will have to have an EE-only counterpart, to be landed after this commit is rebased into the EE repo.
RM-17

chore: remove GetAllocationSummary from RM interface

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/ColumnsCustomizeModal.test.tsx
webui/react/src/components/DraggableListItem.tsx
webui/react/src/components/Transfer.module.scss
webui/react/src/components/Transfer.tsx

[WEB-1958]
- Check if transfer component is virtualized and work as expected in `binding tab in resource pool (RBAC required)` and `column button in the old experiment table`
- should be able to add/remove items by clicking items or `add/remove all` in the bottom
- should be able to search items by text and text should be highlighted
- should be able to drag & drop items to reorder columns in `visible` form
[WEB-1958]: https://hpe-aiatscale.atlassian.net/browse/WEB-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: replace `react-window` with `react-virtuoso` in transfer component

---

docs/release-notes.rst
docs/release-notes/8803-ship-logs-hanging.rst
docs/release-notes/gcs-429.rst
docs/release-notes/identify-task.rst

docs: add release notes for 0.28.1

---

.circleci/real_config.yml

e2e CPU tests had maxSlotsPerPodnumber set as number of gpus-per-machine, which works for GPU machines but not CPUs. After my recent changes in this [PR](https://github.com/determined-ai/determined/pull/8833) which validates the number of slots needed for each task in k8, a few tests that were using CPU broke. Fixed it by creating a new parameter called max-slots-per-pod which is equal to gpus-per-machine in GPU machines and, size of machine/ slot-resource-requests-cpu in CPU machines.
Make sure all test pass, especially test-e2e-longrunning

fix: e2e CPU tests have wrong maxSlotsPerPod number

---

e2e_tests/tests/cluster/test_workspace_org.py
e2e_tests/tests/test_sdk.py
harness/determined/common/api/authentication.py
harness/determined/common/api/errors.py

* Added some documentation for error types
* Changed some `e2e_tests` to look specifically for the error they're expecting (`NotFoundException` rather than its parent `APIException`)

chore: document internal api errors

---

.circleci/real_config.yml
docs/.gitignore
docs/Makefile
docs/conf.py
docs/setup-cluster/on-prem/options/wsl.rst

Add `make check-links` to docs. Add to CI as well.
1. `cd docs`
2. `make check-links`
3. check `docs/check-links/output.txt`
4. Wow there are a lot of broken links!
MLG-1516

docs: add link checker utility

---

docs/index.rst
docs/model-dev-guide/api-guides/batch-process-api-ug.rst
docs/model-dev-guide/dtrain/reproducibility.rst
docs/model-dev-guide/hyperparameter/search-methods/hp-adaptive-asha.rst

- Add link to LLM blog post per request of Community team
- Fix some missed formatting
- Rewrite a section

docs: Add llm blog link to home page

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/CreateGroupModal.tsx
webui/react/src/pages/Admin/GroupManagement.tsx

[WEB-1990]
- Check if there's no and `api/v1/groups/<group-id>` and `api/v1/roles/search/by-group/<group-id>` call in the initial group page load
- Check if adding/editting group works as expected in RBAC (`New Group` to add a group. `Edit Group` dropdown to edit group)
- no regression
[WEB-1990]: https://hpe-aiatscale.atlassian.net/browse/WEB-1990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: unnecessary group related api calls during the initial group page loading

---

.circleci/real_config.yml

This doesn't actually have any effect since this isn't a new cluster, but it saves writing a bunch of junk to make that arg getting passed to det deploy condition.

fix: add context for --initial-user-password

---

webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.module.scss
webui/react/src/pages/ExperimentDetails/TrialsComparisonModal.tsx

[WEB-1994]
see screenshot in the ticket
- Check if long text doesnt overflow in trail comparison view
- Check if all values (string, number, boolean) display correctly
- Check if tooltip is shown by hover when text is truncated
- Check if sticky cells (Metrics and Hyperparameter dropdowns) works when scroll horizontally
[WEB-1994]: https://hpe-aiatscale.atlassian.net/browse/WEB-1994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: trial comparison text overflow bug fix

---

.circleci/real_config.yml
e2e_tests/pytest.ini
e2e_tests/tests/conftest.py
e2e_tests/tests/deploy/test_local.py

* removes stress tests entirely per https://hpe-aiatscale.slack.com/archives/C04C9JXB1C2/p1708971178943249?thread_ts=1708956608.840949&cid=C04C9JXB1C2
* moves `det_deploy_local` out of quarantine and back to regular `test-e2e`. Here, it's currently run only on `main` because of the dependency on `package-and-push-system-local`. This job is only run on `main` because it's slow.
* adds a `det_deploy_local` to `e2e-tests-longrunning` to be run anytime a person requests it.

test: unquarantine deploy-local tests

---

e2e_tests/tests/deploy/test_local.py

These skipped tests try to get the scheduler type, and getting the scheduler type is currently broken in our test suite.
This PR is to get tests green again. The tests themselves will be fixed in an upcoming PR.

test: skip tests that need to get scheduler type

---

.circleci/real_config.yml
e2e_tests/tests/experiment/test_custom_searcher.py

Fix failing nightlies after
https://github.com/determined-ai/determined/commit/76ec233d75ed91467494e7a4114940040c5d1757
Two failures, first
https://app.circleci.com/pipelines/github/determined-ai/determined/51605/workflows/94a91e92-fbc6-4db1-8aac-f81fe49d29ea/jobs/2296970
is because of 
```
=================================================================================================================================== ERRORS ====================================================================================================================================
_________________________________________________________________________________________________________________ ERROR at setup of test_run_asha_batches_exp ______________________________________________________________________________ …
```

ci: fix failing nightlies after auth PR

---

harness/determined/deploy/aws/templates/lore.yaml

(cherry picked from commit e75c518e33c55f7ba72d2ca5f2069616ff614354)
https://hpe-aiatscale.atlassian.net/browse/GAS-621

chore: bump up ebs size to 400gb for genai deployments

---

docs/index.rst

We'll have to remove the link to the external blog post for now until there are some checks in place on that blog post site to redirect URLs.

tc: Remove broken link

---

harness/determined/cli/dev.py

We have a few URLs which include curly brackes, specifically the filter field on `SearchExperiments`. Curly brackets have a [globbing](https://everything.curl.dev/cmdline/globbing) behavior which we don't need. 
To make these URLs work with `det dev curl`, we need to turn off curl's globbing feature.
Do a curl on a URL which includes a brace, e.g. 
```
det dev curl '/api/v1/experiments-search?projectId=133&offset=0&limit=200&sort=id=desc&filter={"filterGroup"{"children"[],"conjunction":"and","kind":"group"},"showArchived":false}'
```

fix: `det dev curl` support for URLs with curly brackets.

---

.circleci/real_config.yml

https://hpe-aiatscale.slack.com/archives/C04C9JXB1C2/p1709565408754739

chore: bump ci setup_remote_docker version

---

.circleci/real_config.yml

Buster is old; bookworm current.
Patch suggested by https://github.com/determined-ai/determined/pull/7329#discussion_r1511498433.

test: CLI workflows in CI use new Python images

---

webui/react/src/hooks/useMetricNames.ts
webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx
webui/react/src/pages/TrialDetails/MultiTrialDetailsHyperparameters.tsx
webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx

[ET-45]
[Slack](https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1709311079011079)
- Check if the chart is rendered when page has at least 1 [V] accuracy data point to plot [example experiment detail in GKE](http://gke.determined.ai/det/experiments/756/trials/2980/overview)
- Check if the chart is rendered after coming back from `Metrics` tab several times
- Looks like this only happens in GKE
[ET-45]: https://hpe-aiatscale.atlassian.net/browse/ET-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: `no data plot` in chart with data

---

docs/Makefile

make sure `attributions.rst` exists before `publish-check`.
cd docs
make clean
make publish-check

docs: fix pre_publish check

---

master/internal/config/config_test.go

chore: [RM-68] improve readability for unit test
the original version had repeated strings for config parsing; with a bit of refactoring, we can reuse the same base config and make it easier to see what's changed for each test case (as suggested by @carolinaecalderon). 
Ensure unit tests pass. 
RM-68
[RM-68]: https://hpe-aiatscale.atlassian.net/browse/RM-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [RM-68] improve readability for unit test

---

.circleci/real_config.yml

And the quarantine workflow along with. We've decided as a company that [future flaky tests will be skipped](https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1306132589/CI+triage+runbook#%5BDeprecated---Skip-tests-instead!%5D-CI-Quarantine-Suite) rather than quarantined until they're fixed.
Last test run as part of the quarantine suite is being removed as part of #8862, and is not needed even before that PR lands.

test: remove last quarantined test

---

.circleci/devcluster/multi-k8s.devcluster.yaml
.circleci/real_config.yml
e2e_tests/pytest.ini
e2e_tests/tests/cluster/test_multi_k8s.py
e2e_tests/tests/cluster/utils.py
e2e_tests/tests/conftest.py
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/pods.go

Add tests for multirm.
Test passes
There aren't many tests yet but that is mostly because the design so far is pretty straight forward.
Probably will want to add proxy tests when we do proxying

test: add e2e_tests for multirm k8s [RM-11]

---

webui/react/src/components/ExperimentContinueModal.tsx
webui/react/src/components/ExperimentCreateModal.tsx

[ET-32] [ET-58]
- Check if error text doesnt break UI layout in continue trial modal when error occurs
- Check if page doesnt crash when yaml config is empty in the full config page
[ET-32]: https://hpe-aiatscale.atlassian.net/browse/ET-32?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-58]: https://hpe-aiatscale.atlassian.net/browse/ET-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove error text in continue trial modal

---

.circleci/real_config.yml

Use major version prefix when specifying GKE version to avoid e2e failures upon removal of minor versions.
CI Passes e2e GKE tests

chore: change GKE version

---

.circleci/real_config.yml

[INFENG-505]
* Originally I was just gonna change a message on a job step
* refactored some similar steps to eliminate some reused code
* We also found a new way to detect if a dir has changes using `git diff --quiet "$MERGE_BASE" HEAD -- "<< parameters.dir >>"`
* removed all references to `skip-if-not-shared` since it was unused
Mock some PRs with changes in `docs`, `webui`, and `.github` to make sure `halt` is working properly. When checking the diff on the PRs, please be aware that this line was temporarily changed.
```bash
MERGE_BASE="$(git merge-base upstream/main HEAD)"
```
```bash
MERGE_BASE="$(git merge-base upstream/jcom/INFENG-505/clarify-circleci-skip-title-messages HEAD)"
```
https://github.com/determined-ai/determined/pull/9008/files …

ci: DRY skip logic and clarity on step name

---

master/internal/api_auth.go
master/internal/api_user_intg_test.go
master/internal/grpcutil/auth.go

We have multiple middlewares that cover authentication. The master proxy we use for GAS does not engage the one that
checks for allocation tokens.
added integ tests
the logic checking for allocation tokens should probably sit somewhere as a global middleware that encompasses user.ProcessAuth and allocations 🤔 
https://github.com/determined-ai/determined/blob/6ffb2f64513619ffe8fbab23529b1d71e931e6ef/master/internal/grpcutil/api.go#L69
blocks https://hpe-aiatscale.atlassian.net/browse/GAS-507?filter=-1

chore: add grpc based auth fallback to proxied requests

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/templates/master-deployment.yaml

This reverts commit 6fec24d66d5efd706409b4ef877bec7edc389fa1.
Broke GKE tests. Revert for now while we figure out the issue.

chore: revert helm for multirm kubeconfig_path

---

master/internal/api_experiment_intg_test.go
master/internal/experiment/bulk_action.go

[ET-96]
- Check if move experiment API works in any cases
- e.g: 
- with `filters` field
- with RBAC
- with `excludedExperimentIds` field
- with single/multiple experiments
- etc...
[ET-96]: https://hpe-aiatscale.atlassian.net/browse/ET-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: move experiment SQL error

---

docs/manage/security/rbac.rst

replaces https://github.com/determined-ai/determined/pull/9046

docs: Describe editorrestricted

---

webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/TrialDetails.tsx
webui/react/src/pages/TrialDetails/Profiles/utils.ts
webui/react/src/pages/TrialDetails/TrialDetailsProfiles.tsx

chore: remove profiling not enabled check in web UI

---

docs/release-notes.rst

Applies to 0.29.1 release notes.
This was a review-only PR that was not meant to be merged and so it was closed. The release notes were updated manually in the AWS S3 bucket.
The reason for the one-off update was because the release notes regarding "EditorRestricted" role were missed during the 0.29.1 release process.

docs: Update release notes

---

docs/reference/deploy/helm-config-reference.rst
docs/reference/deploy/master-config-reference.rst
helm/charts/determined/values.yaml

Add helm docs + ```values.yaml``` changes for multirm
no testing needed

docs: helm doc changes for multirm [RM-37]

---

agent/.goreleaser.yml
agent/Dockerfile
docs/conf.py
harness/setup.py
master/.goreleaser.yml
master/Dockerfile
model_hub/setup.py

Update old e-mail address.
- [NA] User-facing API changes need the "User-facing API Change" label.
- [NA] Release notes should be added as a separate file under `docs/release-notes/`.
- [NA] Licenses should be included for new code which was copied and/or modified from any external code.

chore: update old e-mail address

---

tools/devcluster.yaml

added change in master config to devcluster.yaml
run devcluster locally and make sure there are no errors

chore: add change in master config to devcluster.yaml

---

webui/react/src/components/JupyterLabModal.tsx

Preselect workspace when launching notebooks  
Open `Launch JupyterLab` at Home by clicking the button or using shortcut
The workspace field is preselected and mutable
Switch between simple and full config, workspace field is persistent
[Ticket](https://hpe-aiatscale.atlassian.net/browse/DFR-486)

feat: Pre-select ws when launching notebook

---

webui/react/src/e2e/models/BaseComponent.ts
webui/react/src/e2e/models/components/AddUsersToGroupsModal.ts
webui/react/src/e2e/models/components/ChangeUserStatusModal.ts
webui/react/src/e2e/models/components/CreateUserModal.ts
webui/react/src/e2e/models/components/DeterminedAuth.ts
webui/react/src/e2e/models/components/Navigation.ts
webui/react/src/e2e/models/components/SetUserRolesModal.ts
webui/react/src/e2e/models/components/SkeletonSection.ts
webui/react/src/e2e/models/components/Table/InteractiveTable.ts
webui/react/src/e2e/models/components/Table/SkeletonTable.ts
webui/react/src/e2e/models/hew/Dropdown.ts
webui/react/src/e2e/models/hew/Modal.ts
webui/react/src/e2e/models/hew/Pivot.ts
webui/react/src/e2e/models/hew/Toast.ts
webui/react/src/e2e/models/pages/Admin/UserManagement.ts
webui/react/src/e2e/models/utils/error.ts

refactor defaultSelector as an instance property. Some logic needed to get reworked, including the `NamedComponentWithAttatchment` interface used in our new constructors.
[INFENG-455]
[INFENG-455]: https://hpe-aiatscale.atlassian.net/browse/INFENG-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Jcom/infeng 455/default selector instance prop

---

docs/setup-cluster/_index.rst
docs/setup-cluster/mldes/_index.rst

Per [this ticket](https://hpe-aiatscale.atlassian.net/browse/SAAS-1877) advertise MLDES in Determined OSS documentation and give instructions on deploying a Determined (MLDE) cluster via MLDES. Also links to MLDES prod and documentation.
SAAS-1877

docs: add instructions on deploying determined via HPE MLDES [SAAS-1877]

---

master/static/migrations/20240313113450_add-models-trigger.tx.down.sql

Small sql change to fix our down migrations.
CI passes.

fix: down migrations

---

master/internal/rm/multirm/multirm.go

RM-151
Change log level to trace for multirm messages
Spin up your own test cluster to check -- follow instructions in tools/k8s/README
[RM-151]: https://hpe-aiatscale.atlassian.net/browse/RM-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: change multirm log messages to trace level [RM-151]

---

docs/reference/deploy/helm-config-reference.rst
docs/reference/deploy/master-config-reference.rst
docs/release-notes/multirm-for-k8s.rst

to cherry pick for release
revert #9050 #9122

docs: revert-multiRM-mc-doc

---

docs/reference/deploy/master-config-reference.rst
docs/release-notes/logging-retention.rst

Docs had the wrong command `det master cleanup-logs`. Changed it to `det task cleanup-logs`

fix: fix docs for log retention

---

helm/charts/determined/values.yaml

No ticket for this.
Fix helm style for master tls config
CI passes.

chore: style fix for helm tls

---

docs/index.rst
docs/reference/deploy/agent-config-reference.rst
docs/reference/experiment-config-reference.rst

Debug enables debugging on the fly. Users should be able to find out about this agent configuration option when visiting the experiment configuration reference page.

docs: Copy debug to exp config

---

harness/.flake8
harness/determined/tensorboard/fetchers/__init__.py
model_hub/model_hub/huggingface/_utils.py
model_hub/model_hub/mmdetection/_data_backends.py
requirements.txt

[MD-16]
Add a rule to ban relative imports in harness.
Also fix a few untidy imports.
CI lint passes.

chore: add flake8 relative-import rule

---

.circleci/real_config.yml
webui/react/index.html
webui/react/vite-plugin-branding.ts
webui/react/vite-plugin-csp.ts
webui/react/vite.config.mts

We have to set the description in index.html to be `Determined` for open source deployments and `MLDE` for EE deployments. This change uses an environment variable (set during the release build process) to determine whether or not to set the description to MLDE or not. 
Anyone building the webui locally may end up with the determined description, but anyone using EE images should receive the `MLDE` description.
manually tested:
use devcluster and go to the determined login screen. Inspecting the source (inspect -> sources -> look for `det` or `login` or `index`) , we should see that the description for the homepage is `Determined Deep Learning Training Platform`. 
Quit out of devcluster and go to `webui/react`. Run `export DET_BUILD_EE=true` in your terminal and run `make clean && make …

feat: overwrite determined description if EE

---

docs/reference/experiment-config-reference.rst
harness/determined/cli/experiment.py
harness/determined/cli/trial.py
proto/pkg/apiv1/experiment.pb.go
proto/pkg/apiv1/trial.pb.go
proto/src/determined/api/v1/experiment.proto
proto/src/determined/api/v1/trial.proto
webui/react/src/services/api-ts-sdk/api.ts

fix: fix docs and wording

---

docs/release-notes/det-deploy-ee.rst
e2e_tests/tests/deploy/test_local.py
harness/determined/deploy/local/cli.py
harness/determined/deploy/local/cluster_utils.py

as part of EE unforking, this makes `det deploy local` configurable to use enterprise edition or not. The `--enterprise-edition` flag determines whether we pull from the open source docker or the enterprise docker.

feat: make enterprise edition configurable in det deploy local

---

helm/charts/determined/values.yaml

No ticket for this.
The tiniest nit.
Tested locally, needs no testing.

chore: style fix for helm initialUserPassword

---

docs/reference/python-sdk/example-workflows.rst
docs/setup-cluster/k8s/setup-aks-cluster.rst
docs/setup-cluster/k8s/setup-eks-cluster.rst

1. Add a frequently asked ckpt download question with the hopes it'll jiggle algolia: https://hpe-aiatscale.slack.com/archives/CSG3W08JY/p1713390837024639
2. Put deprecation labels on stale AKS & EKS docs. https://hpe-aiatscale.slack.com/archives/CRYLQP7MW/p1713382332853349

docs: FAQ for python SDK ckpt download, k8s deprecation labels.

---

master/internal/plugin/oidc/service_intg_test.go
master/internal/plugin/saml/service_intg_test.go

Skips flakey tests that came from the ee rebase.
test-go passes

test: skip flakey user provision tests

---

.circleci/real_config.yml

Latest main is being deployed as enterprise edition because the underlying code that it uses is hard coded as `--enterprise-edition`. To fix this, we make enterprise edition conditional.

ci: pass ee into args to prevent latest main deploying as ee

---

.circleci/real_config.yml
docs/setup-cluster/k8s/setup-eks-cluster.rst

check docs link doesn' run at pr level
make -C docs check-links
some of the slurm link checks fail on ci. maybe a rate limit? the timeout is already at 20s

docs: fix another instance of broken docs link

---

e2e_tests/tests/api_utils.py
e2e_tests/tests/streaming/test_client.py
master/internal/core.go
master/internal/stream/util.go

[MD-371]
Put streaming updates behind a feature flag to unblock users with AWS Aurora v1 database.
CI tests pass.
[MD-317]: https://hpe-aiatscale.atlassian.net/browse/MD-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MD-371]: https://hpe-aiatscale.atlassian.net/browse/MD-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add streaming updates feature flag [MD-371]

---

LICENSE

chore: update the license date

---

docs/reference/deploy/helm-config-reference.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

chore: add log retention to help charts

---

webui/react/src/e2e/models/BasePage.ts
webui/react/src/e2e/models/README.md
webui/react/src/e2e/models/components/NavigationSideBar.ts
webui/react/src/e2e/models/components/WorkspaceCreateModal.ts
webui/react/src/e2e/models/hew/Card.ts
webui/react/src/e2e/models/hew/Toast.ts
webui/react/src/e2e/models/pages/Admin/UserManagement.ts
webui/react/src/e2e/models/pages/ProjectDetails.ts
webui/react/src/e2e/models/pages/SignIn.ts
webui/react/src/e2e/models/pages/Workspaces.ts

INFENG-638
Typescript doesn't need all of the type annotations we are using. Removing redundant annotations can save us some time if we ever decide to change type. For example, if sidebarItem() changes return type then this automatically also changes it's return type `readonly modelRegistry = this.sidebarItem('Model Registry');` where as this is still and error `readonly modelRegistry: BaseComponent = this.sidebarItem('Model Registry');`. Since the variable changing type will cause compile errors where it is used, and that is where the functional impact would happen, this compile error during assignment doesn't provide additional value. It's just potential future work, so I'm removing it now.
CI passes
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release- …

test: react e2e use type inference for newed components

---

.circleci/real_config.yml

[INFENG-651]
check the jira ticket. I just wanted to change the job names from appearing as `test-e2e-react-1` and `-2`
As long as circle ci compiles, we're good. if a requirement is wrong, [it'll tell you](https://app.circleci.com/pipelines/gh/determined-ai/determined?branch=jcom%2FINFENG-651%2Fdescriptive-circle-ci-job-names).
[INFENG-651]: https://hpe-aiatscale.atlassian.net/browse/INFENG-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: ee and oss job names [INFENG-651]

---

docs/get-started/_index.rst
docs/release-notes.rst
docs/release-notes/allow-and-require-user-passwords.rst
docs/release-notes/det-deploy-ee.rst
docs/release-notes/enable-prometheus-default-true.rst
docs/release-notes/long-metrics.rst

Reverts determined-ai/determined#9246

Revert "docs: Update observability release note"

---

docs/get-started/_index.rst

The quickstart should be visible in the get started home page.

docs: Add qs to getstarted

---

helm/charts/determined/values.yaml

fix: undo default log retention in values.yaml

---

.circleci/real_config.yml

INFENG-598
Circle-CI's support team did a review of our CI pipeline and gave us some feedback on cutting cost. It turns out test-e2e-cpu is ~%27 of determined overall spend. Since large executors cost 20% of xlarge, sizing down to large and adding a few more runners should result in non-trivial cost savings with minimal impact to developers. There were a few other jobs that also were a pretty large part of spend that I sized down as well. 
I ran the pipeline multiple times and ensured non of the jobs I tweaked failed with the new executor sizes.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

test: resize test executors that aren't fully used [infeng-598]

---

webui/react/src/components/JupyterLabModal.tsx
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/hooks/useFeature.ts
webui/react/src/pages/Templates/TemplatesPage.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/routes/index.tsx
webui/react/src/routes/routes.ts
webui/react/src/routes/utils.ts

[MD-377]
Link to ERD: https://hpe.sharepoint.com/:w:/r/teams/detai/Shared%20Documents/Engineering/Web/ERDs/Web%20implantation%20for%20Templates.docx?d=w21a4382ed90742f59d597425c0899c22&csf=1&web=1&e=aZflWe
This PR adds feature flag for managing templates, and when feature is enabled, templates configuration page is accessible through navigation bar, workspace details and Jupyter model.
Note that configuration page itself is empty for now.
Switch "Manage templates" on in user settings.
The navigation side bar should have a Template menu.
Navigate to workspace details page, there should be a tab for templates.
At Launch Jupyter Notebook model, there should be a "manage templates" link.  …

feat: Add templates feature flag and entry points

---

master/internal/stream/publisher.go

Streaming Updates got an runtime error.
```
[31mERRO[0m[2024-04-15T21:26:42Z] listener on (postgres://postgres:postgres@genai-erikew-database-reti2f2oj40v.cluster-csrkoc1nkoog.us-west-2.rds.amazonaws.com:5432/determined?application_name=determined-master&sslmode=verify-ca&sslrootcert=/etc/determined/db_ssl_root_cert.pem) reported problem: EOF
2024-04-15T14:26:42.467-07:00	panic: runtime error: invalid memory address or nil pointer dereference
2024-04-15T14:26:42.467-07:00	[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x24fd007]
2024-04-15T14:26:42.467-07:00	goroutine 118 [running]:
2024-04-15T14:26:42.468-07:00	github.com/determined-ai/determined/master/internal/stream.publishLoop[...]({0x37452d8, 0xc0004aa640}, {0xc0008b8000, 0xc000749498?}, {0x30f8680?, 0x13}, …
```

fix: notification nil pointer dereference

---

webui/react/src/e2e/tests/userManagement.spec.ts

[INFENG-455]
one line change with an accompanying comment. the test can be slow with 5 logins
[INFENG-455]: https://hpe-aiatscale.atlassian.net/browse/INFENG-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: increase the timeout on a new users test [INFENG-455]

---

docs/integrations/observability/_index.rst
tools/observability/grafana-prom-values.yaml
tools/observability/resource-utilization-dash.json

[RM-130]
Adds a Resource Utilization dashboard using DCGM metrics and `kube_pod_labels` from prometheus data source.
No test needed.
[RM-130]: https://hpe-aiatscale.atlassian.net/browse/RM-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: add resource utilization dashboard [RM-130] 

---

webui/react/playwright.config.ts
webui/react/src/e2e/fixtures/auth.fixture.ts
webui/react/src/e2e/fixtures/user.fixture.ts
webui/react/src/e2e/models/pages/Admin/UserManagement.ts
webui/react/src/e2e/tests/auth.spec.ts
webui/react/src/e2e/tests/userManagement.spec.ts

[INFENG-663]
check the jira ticket for all broken tests covered by this change
[INFENG-663]: https://hpe-aiatscale.atlassian.net/browse/INFENG-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: some react tests are flaky [INFENG-663]

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/e2e/tests/auth.spec.ts

[ET-243]
change default timeout for toast notifications and take the "deflake" out of the testcase now that the notifications last longer
There's a test in auth.spec that supports this change a little. I'd recommend running that test.
**manual test steps:**
* npm i
* try to sign in with bad creds
* wait 8 seconds for the toast to disappear
[ET-243]: https://hpe-aiatscale.atlassian.net/browse/ET-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: timeout change and package dedupe [ET-243]

---

docs/reference/deploy/master-config-reference.rst

docs: fix master config doc typo

---

webui/react/src/hooks/usePermissions.ts
webui/react/src/pages/Templates/TemplateCreateModal.tsx
webui/react/src/pages/Templates/TemplatesPage.tsx
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts

[MD-381]
Add create template modal to WebUI.
Create template function can be accessed from:
- Navigation sidebar -> Template page
- Workspace details -> Template tab
With `Templates` feature flag on
Navigate to Templates page from sidebar
Click `New Template` button to open a modal for creating templates.
All fields are required, if one of the fields is missing, the form cannot be submitted.
Note backend may reject if config field is only a valid yaml but not a valid task configuration. 
Once submitted successfully, a notification should pop up. 
Repeat the same testing steps at workspace details page, template tab
Only difference is the workspace field should be pre-selected and disabled. 
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/README …

feat: Create template through WebUI

---

.github/dependabot.yml

This commit I think was a mistake from the ee repo merge.
This is undoing that change with 
```
git checkout 283daab2d8eed70dae568ac7ac80db60e25be9e0~1 -- dependabot.yml
```
see if we get dependabot prs after this

ci: revert ee rebase changes to dependabot.yaml

---

proto/Makefile

fix: proto build shouldn't run if source files are unchanged

---

helm/charts/determined/Chart.yaml

No ticket
Fix an overlooked "master->main" in the Chart.yaml
There's no testing for an edited comment in the chart body, which explains the [ci skip].

docs: Update Chart.yaml [ci skip]

---

.circleci/real_config.yml

https://app.circleci.com/pipelines/github/determined-ai/determined/55152/workflows/e5f1c0c8-1717-47ca-a993-6a8d9d3ee279/jobs/2534702/steps is occasionally fail, so store npm log to debug
- ci pass
- npm log should be store in `test-e2e-react-ee` ci job

ci: store npm log

---

tools/observability/api-dash.json
tools/observability/resource-utilization-dash.json

[RM-133]
High level updates:
- organize visualizations into groups, telling a cohesive story; include API Monitoring Dashboard for a cohesive feel
- include headline visualizations, to give users a notion of status at a glance
- separate GPU requests and utilization; include current and over time visualizations
- include pods by namespace
- include summary of running tasks
None needed.
Updated API Monitoring:
(the rest of the dashboard is the same)
Updated Resource Utilization:
[RM-133]: …

docs: Dashboard Improvements after dogfooding

---

master/static/migrations/20240503155534_drop-experiments_best_validation_history.tx.down.sql
master/static/migrations/20240503155534_drop-experiments_best_validation_history.tx.up.sql

This function is unused.
CI passes

chore: drop unused postgres function experiments_best_validation_history

---

docs/model-dev-guide/prepare-container/custom-env.rst
docs/setup-cluster/deploy-cluster/slurm/singularity.rst
docs/setup-cluster/slurm/singularity.rst

Reverts determined-ai/determined#9312

Revert "docs: Reformat tables with image names"

---

webui/react/src/e2e/tests/userManagement.spec.ts

test: skip a flaky test [ET-233, ET-178]

---

docs/setup-cluster/k8s/install-on-kubernetes.rst

Recommend users to use helm repo instead of downloading our custom tarball.
N/A

docs: update "install on k8s" guide to use helm repo instead of tarball.

---

codecov.yml

[INFENG-689]
codecov update. i fixed "yes" and "no" to yaml booleans as well
[INFENG-689]: https://hpe-aiatscale.atlassian.net/browse/INFENG-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update codecov to ignore e2e react [INFENG-689]

---

docs/reference/deploy/helm-config-reference.rst
docs/release-notes/helm-requires-initial-password.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

Reverts determined-ai/determined#9274 due to remaining open questions about the desirability of the behavior.

fix: Revert "feat: helm requires bootstrap password (DET-10196)"

---

docs/release-notes.rst

Update release notes date from May 3 -> May 8

chore: update release notes date

---

docs/release-notes.rst
docs/release-notes/pod-label-bugfix.rst

docs: add release notes for 0.32.1

---

docs/release-notes/helm-requires-initial-password.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

[DET-10196]
BREAKING CHANGE: `helm install` requires setting a bootstrap password for the admin and determined users via the initialUserPassword entry.
This is not required, or meaningful, when modifying existing deployments (i.e. `helm upgrade`)
Manually checked cases:
- Running `helm install` with default settings
- fails with message `Error: INSTALLATION FAILED: execution error at (determined/templates/master-deployment.yaml:22:28): An initial password for admin and determined users is required!`.
- Running `helm install` with a password set.
- normal successful deployment
- Running `helm upgrade` with the password removed again
- normal upgrade, shows `REVISION: 2` among other details
The majority of e2e test suites start with a `helm install` so the happy path is pretty thoroughly …

feat: helm requires bootstrap password [DET-10196]

---

docs/model-dev-guide/api-guides/apis-howto/deepspeed/deepspeed.rst

Adding a section about FSDP to DeepSpeed Usage Guide.
Avoid broken external links by providing only a top level hyperlink.

docs: Add FSDP to deepspeed

---

docs/release-notes/feature-clean-up.rst

[RM-249]
None needed.
[RM-249]: https://hpe-aiatscale.atlassian.net/browse/RM-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: deprecation notice for agentrm features

---

docs/release-notes/k8s-slots-jumping.rst

docs: Update release note

---

docs/manage/security/rbac.rst

Docs Issue 254
https://github.com/determined-ai/determined/blob/main/docs/release-notes/webui-create-user-with-password.rst

docs: Describe pwd requirements WebUI

---

docs/assets/styles/determined.css
docs/tools/_index.rst
docs/tools/genai/_index.rst

Provide a navigation path from Determined to GenAI docs. Minor update to css.

docs: Add nav to genai docs

---

.circleci/real_config.yml

Reenables building and pushing oss dev images on a per-commit basis (instead of just per master commit) . 

chore: push oss images per commit

---

webui/react/src/e2e/tests/userManagement.spec.ts

[INFENG-694]
I should've kept this flaky fix in. I was hoping maybe the flake has left with the new devcluster stuff, and I was refactoring at the time anyway.
https://output.circle-artifacts.com/output/job/d1b9d965-1f01-4938-9e21-e4d4da7a0a4b/artifacts/0/webui/react/src/e2e/playwright-report/index.html#?testId=46710bd7f7f3d0299264-de618de281ac4f8610f3
[INFENG-694]: https://hpe-aiatscale.atlassian.net/browse/INFENG-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: put flaky fix back in [INFENG-694]

---

docs/reference/deploy/helm-config-reference.rst

Update docs with more info about required field.
#9359 

docs: Add more info helm install password

---

docs/release-notes/webui-manage-templates.rst
webui/react/src/hooks/useFeature.ts

[MD-407]
Default manage templates feature flag to true.
[Link](https://hpe.sharepoint.com/:w:/r/teams/detai/Shared%20Documents/Engineering/Web/ERDs/Web%20implantation%20for%20Templates.docx?d=w21a4382ed90742f59d597425c0899c22&csf=1&web=1&e=trAYN6) to ERD
CRUD templates should work as expected
[MD-407]: https://hpe-aiatscale.atlassian.net/browse/MD-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Release WebUI templates with notes

---

model_hub/tests/requirements.txt

setuptools 70 is no longer compatible with older versions of torch/mmcv. pinning it for now.

pin setuptools in model hub tests

---

.circleci/real_config.yml

various fixes

---

harness/determined/core/_checkpoint.py
harness/tests/core/test_checkpoint.py

fix a bug where core.checkpoint doesn't notify master on checkpoint deletes. 
modify the example in `examples/tutorials/core_api/2_checkpoints.py`, add the following lines (after L65)
```diff
checkpoint_metadata = {"steps_completed": steps_completed}
with core_context.checkpoint.store_path(checkpoint_metadata) as (path, uuid):
save_state(x, steps_completed, trial_id, path)
+           if core_context.distributed.rank == 0:
+               core_context.checkpoint.delete(uuid)
+               print(f"deleted ckpt {uuid}")
```
change the expconf (`2_checkpoints.yaml`)  to store all checkpoints:
```diff
+ checkpoint_policy: all
```
submit experiment, verify in web UI that all checkpoints for this exp are shown as deleted.
See [Release …

fix: notify master for core checkpoint deletes [MD-325]

---

docs/conf.py
docs/setup-cluster/slurm/slurm-known-issues.rst

Fix broken nvidia docs anchor link that was causing the failure here 
https://app.circleci.com/pipelines/github/determined-ai/determined/56214/workflows/95c194ec-c163-4a2d-abc3-ef8ce7650c3b/jobs/2617218

docs: update broken nvidia anchor link

---

e2e_tests/tests/cluster/test_proxy.py
e2e_tests/tests/fixtures/ports-proxy/config.yaml
e2e_tests/tests/fixtures/ports-proxy/start.py

chore: add a no-dependency multi-port multi-trial test exp

---

master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/kubernetesrm/resource_pool_intg_test.go

RM-265
Exactly as the title says..

chore: set group max slots test

---

tools/observability/README.md

docs: fix observability README docs link

---

.circleci/devcluster/multi-k8s.devcluster.yaml
master/internal/config/resource_config_test.go
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/gateway_service.go
master/internal/rm/kubernetesrm/gateway_service_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/request_queue_test.go
master/internal/rm/kubernetesrm/spec_test.go
master/pkg/check/check_numbers.go
master/pkg/check/check_string.go
master/pkg/check/check_test.go
master/pkg/check/validate.go

https://hpe-aiatscale.atlassian.net/browse/RM-267
https://hpe-aiatscale.atlassian.net/browse/RM-288
going off of the conversation here https://hpe-aiatscale.slack.com/archives/C06K1CD0DMW/p1716864615405799?thread_ts=1716338052.746629&cid=C06K1CD0DMW

feat: make gw port range configurable; add validation

---

docs/reference/deploy/common-config-options.rst

Clarifies telemetry collected and how it is used.
Passes `make fmt` and `make check`.
- [NA] User-facing API changes need the "User-facing API Change" label.
- [NA] Release notes should be added as a separate file under `docs/release-notes/`.
- [NA] Licenses should be included for new code which was copied and/or modified from any external code.

docs: clarify data collected by telemetry

---

.circleci/real_config.yml

stop CI from publishing build artifacts in the ee workflows.
Go to any workflow on circleCI and click into the `package-and-push-system-dev-ee` workflow. If on release, you can also check out `package-and-push-system-rc-ee` or `package-and-push-system-release-ee`. 
Look at the `Artifacts` tab in the workflow. There should be nothing there.

chore: no longer store ee artifacts in circleCI

---

.circleci/devcluster/double.devcluster.yaml
e2e_tests/tests/cluster/test_proxy.py
e2e_tests/tests/fixtures/ports-proxy/config.yaml
e2e_tests/tests/fixtures/ports-proxy/start.py
master/internal/rm/kubernetesrm/pod.go
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go

https://hpe-aiatscale.atlassian.net/browse/RM-275

chore: limit deploying gw resources to rank0 pods

---

docs/release-notes/deprecate-ppc64.rst

[RM-294](https://hpe-aiatscale.atlassian.net/browse/RM-294)
Correcting the release note for the deprecation [PR](https://github.com/determined-ai/determined/pull/9467)
[RM-294]: https://hpe-aiatscale.atlassian.net/browse/RM-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: correct release note for deprecating PPC64/POWER builds

---

e2e_tests/tests/cluster/test_proxy.py
e2e_tests/tests/fixtures/ports-proxy/config.yaml
e2e_tests/tests/fixtures/ports-proxy/start.py

brings in tests from https://github.com/determined-ai/determined/commit/c367f51a1270032bc5aa6814bfb44e627a3ec688

test: cherry pick port registry tests

---

docs/tutorials/quickstart-mdldev.rst

[RM-294](https://hpe-aiatscale.atlassian.net/browse/RM-294)
Removing the residual PowerPC/PPC64 reference from determined docs.
[PR](https://github.com/determined-ai/determined/pull/9467) to remove PowerPC
[RM-294]: https://hpe-aiatscale.atlassian.net/browse/RM-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: remove all references to PowerPC/PPC64

---

package-lock.json
package.json

[TESTENG-4]
update playwright version
[TESTENG-4]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: update playwright [TESTENG-4]

---

docs/integrations/observability/_index.rst
docs/integrations/prometheus/_index.rst

tc: Test format

---

e2e_tests/tests/cluster/test_proxy.py

- split up tests and use parameterization better.
- lower the max conc trials for two_slot tests

test: split multi node and single node

---

.circleci/real_config.yml

infeng-501
This uploads some of the remaining un-instrumented tests to datadog by uploading previously created junit reports.
Tested that results are now uploading for unit tests in datadog
https://app.datadoghq.com/ci/test-runs?saved-view-id=2750853

test: upload unit and intg tests to datadog[infeng-501]

---

master/.mockery.yaml

fix: mockery new fmt

---

webui/react/playwright.config.ts
webui/react/src/e2e/README.md
webui/react/src/e2e/fixtures/api.auth.fixture.ts
webui/react/src/e2e/fixtures/api.user.fixture.ts
webui/react/src/e2e/fixtures/global-fixtures.ts
webui/react/src/e2e/models/BaseComponent.ts
webui/react/src/e2e/models/ant/Dropdown.ts
webui/react/src/e2e/models/ant/Popover.ts
webui/react/src/e2e/models/components/FilterForm/components/FilterGroup.ts
webui/react/src/e2e/models/hew/DataGrid.ts
webui/react/src/e2e/tests/experimentList.spec.ts
webui/react/src/e2e/tests/userManagement.spec.ts
webui/react/src/e2e/utils/naming.ts

[TESTENG-3]
no serial for me
[TESTENG-4]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TESTENG-3]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: preparing a homework assignment [TESTENG-3]

---

.github/pull_request_template.md

INFENG-710
* INFENG-710 #in-review #comment Add reminder checkbox for new feature PM signoff
* Also rearrange boxes and update verb tense & punctuation on all boxes for consistency
I know this isn't really "CI" but that seemed the closest conventional tag. :shrug: 
Open a PR after merging and visually inspect?

ci: add new feature signoff checkbox [INFENG-710] [skip-ci]

---

.circleci/real_config.yml
docs/setup-cluster/k8s/controller-reviews.rst

hashicorp just updated their doc link structure. and wso2 link doesn't allow our crawler.

docs: address two link check failures

---

docs/requirements.txt

chore: fix boto3 requirement syntax

---

webui/react/playwright.config.ts
webui/react/src/e2e/tests/experimentList.spec.ts
webui/react/src/e2e/tests/projectsWorkspaces.spec.ts
webui/react/src/e2e/tests/userManagement.spec.ts

[TESTENG-12]
just revising the timeout config and slow markers since the framework is stable now. i removed the global timeout since circle CI technically already has one and it was hard to maintain
[TESTENG-12]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: playwright timeout config [TESTENG-12]

---

webui/react/src/e2e/fixtures/auth.fixture.ts
webui/react/src/e2e/fixtures/global-fixtures.ts
webui/react/src/e2e/models/common/base/BasePage.ts
webui/react/src/e2e/models/pages/Admin/UserManagement.ts
webui/react/src/e2e/models/pages/ProjectDetails.ts
webui/react/src/e2e/models/pages/SignIn.ts
webui/react/src/e2e/models/pages/WorkspaceList.ts
webui/react/src/e2e/tests/auth.spec.ts
webui/react/src/e2e/tests/navigation.spec.ts
webui/react/src/e2e/tests/projectsWorkspaces.spec.ts

[TESTENG-48]
moving determined logic outside of basepage
[TESTENG-48]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: page title appendix in global fixture config [TESTENG-48]

---

master/static/migrations/20240617155550_add-allocation-workspace-table.tx.up.sql

Corrects recent migration to ensure that workspace_id can be set to null in the event that allocation workspace information was unable to be retrieve due to experiment deletions.
- Ensure migration is successful when allocation's are missing workspace information for historic deletions

fix: correct workspace_id column type on allocation_workspace_info 

---

.circleci/real_config.yml

Removes the Shared Cluster workflow from the real config while the flake on this test workflow is being resolved. 
- Ensure that CI doesn't include a shared cluster workflow

chore: remove shared cluster test for circle ci

---

.circleci/real_config.yml
e2e_tests/tests/environment/test_nvidia_driver.py

`test-e2e-gke-single-gpu` won't be running Nvidia drivers version matching test since gke agent node doesn't have fabric manager.
CI passes.

fix: nvidia drivers version matching test failed in test-e2e-gke-single-gpu

---

webui/react/src/pages/WorkspaceDetails.tsx

This reverts commit 7e3f27b455b5f9da11ebc764b7c50f3c01a1f109.
The commit is accidentally pushed into main branch
Ci pass

chore: Revert "remove circular dependence + correctly derive values"

---

e2e_tests/tests/model_hub/test_mmdetection.py

None
Skip a test that is failing in `mmdet`. We are currently reevaluating the value of `model_hub`.
CI is green

chore: disable mmdet test

---

master/internal/api_project.go

ET-313
Adding the number of runs in a project for the "recently viewed projects" part of the dashboard
Go to the dashboard and look at the `/activity` call in the Network Tab. Check to see if numRuns is returning the correct amount of runs.

fix: add numRuns to GetProjectsByUserActivity

---

webui/react/src/components/CompareHyperparameters.test.mock.tsx
webui/react/src/components/CompareHyperparameters.test.tsx
webui/react/src/components/CompareHyperparameters.tsx
webui/react/src/components/CompareParallelCoordinates.tsx
webui/react/src/components/ComparisonView.test.mock.tsx
webui/react/src/components/ComparisonView.tsx
webui/react/src/hooks/useMetrics.ts
webui/react/src/pages/ExperimentDetails/ExperimentVisualization/HpParallelCoordinates.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx
webui/react/src/types.ts
webui/react/src/utils/data.ts
webui/react/src/utils/tests/generateTestData.ts

[ET-261]
Go to the Glide experiment list, select an experiment, open comparison view, and switch to the Hyperparameters tab to view the Parallel Coordinates plot. From there, select and unselect various experiments with different hyperparameters and metrics. At no point should the selected metric change unless you unselect the only experiment that has it. At no point should all of the lines on the chart disappear.
[ET-261]: https://hpe-aiatscale.atlassian.net/browse/ET-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

fix: comparison view parallel coordinates chart shouldn't break when selecting rows [ET-261]

---

docs/reference/deploy/_index.rst
docs/setup-cluster/checklists/k8s-versions.rst

Request: Document the Kubernetes versions we officially support.
Need to include the following:
- We support non end-of-lifed Kubernetes versions
- We support OpenShift versions with the "full support" window

docs: Describe supported k8s versions

---

docs/manage/users-remote.rst

Update remote user management docs to include the new parameter.
Engineering: #9613

docs: Update remote users auto redirect

---

webui/react/src/e2e/models/README.md
webui/react/src/e2e/tests/experimentList.spec.ts

test: chore: fix some typos

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx

[ET-630]
`// eslint-disable-next-line react-hooks/exhaustive-deps` added in #7150 for some reason, but i believe its not needed anymore.
- Change the sort from column and sort option in the new experiment table and flat run
- Check if the sort settings are preserved after refreshing the page and make sure no regressions
[ET-630]: https://hpe-aiatscale.atlassian.net/browse/ET-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update sort settings

---

master/internal/rm/kubernetesrm/job.go
master/internal/sproto/resources.go
master/internal/task/allocation.go

RM-240
no longer needed, as a result of the actor refactor
Pass exisiting circleCI tests

chore: remove ContainerState from ResourcesStateChanged

---

e2e_tests/tests/nightly/test_pytorch2.py
examples/hf_trainer_api/hf_language_modeling/distributed.yaml
harness/.flake8
harness/Makefile

we now validate training length and one of our examples has values that don't match, which is failing nightly test.

chore: fix e2e test Hf trainer searcher lengths

---

harness/determined/cli/workspace.py

DET-10435
Clarify the help message for `det w create --namespace <NAMESPACE>` and `det w bindings set <WORKSPACE> --namespace <NAMESPACE>`. 
Change shorthand `list` from `l` to `ls` for `det w bindings list`.
CI passes.

chore: slot caps small CLI clarity and consistency changes

---

webui/react/src/components/JupyterLabModal.tsx

[DET-10433]
We may save deleted templates to user settings when creating notebook, so we should check if the template is still valid before setting it as initial value. 
Select a template and create a notebook.
Delete that template.
Open the launching notebook modal again, the deleted template should no longer be selected. 
[DET-10433]: https://hpe-aiatscale.atlassian.net/browse/DET-10433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: use existed templates when launching notebook

---

.circleci/devcluster/single-k8s.devcluster.yaml
.circleci/real_config.yml
e2e_tests/pytest.ini
e2e_tests/tests/cluster/test_workspace_org.py
e2e_tests/tests/conftest.py
harness/determined/cli/workspace.py

DET-10424
Modify existing tests that previously leverage the shared cluster for testing to use a minikube single rm devcluster config to ensure that slot caps can be properly tested while the shared cluster timeout failures are being resolved seperately.
- Ensure that `test-e2e-single-k8s` passes successfully

chore: add single rm k8s testing for workspace slot caps [DET-10424]

---

webui/react/src/e2e/models/pages/ProjectDetails.ts
webui/react/src/e2e/tests/experimentList.spec.ts

test: move wait statement to shared code

---

docs/release-notes/deprecate-containerRuntime.rst
docs/setup-cluster/k8s/_index.rst
docs/setup-cluster/k8s/resource-caps.rst

#9180
[preview docs](https://determined-ai-docs.s3.us-west-2.amazonaws.com/previews/c51c93d1bda68cea8c8944dc5bdfae87/setup-cluster/k8s/resource-caps.html)

docs: Describe workspace slot level caps

---

webui/react/src/pages/FlatRuns/FlatRuns.tsx

[ET-642]
Show the correct empty page in the flat run table when filters are applied
- enable flat run table
- go to project with some runs
- check if `No results matching your filters` message shows up when there's no match with some filters
- <img width="905" alt="image" src="https://github.com/user-attachments/assets/84a4aa40-8504-4bb4-90ec-cdfe96e141f8">
- check if `No Searches` message show up if the project does not have any runs and no filters are applied
- <img width="905" alt="image" src="https://github.com/user-attachments/assets/8c24e0d0-7203-4ae7-ae6a-7728675109d0">
[ET-642]: https://hpe-aiatscale.atlassian.net/browse/ET-642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …

fix: show the correct empty page in flat run table when filters are applied

---

master/internal/api_workspace.go
master/internal/db/database.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/multirm/multirm_intg_test.go
master/internal/workspace/postgres_workspace.go

No ticket for this.
Style and wrapup fixes with some cleaner error handling and added transaction commit
CI passes

chore: style and wrapup fixes

---

master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go

DET-10436
Added tests for CreateNamespace and DeleteNamespace. Ended up splitting CreateNamespace into a helper function because testing syncNamespaces proved to be very tedious due to mocking - and eventually reached a roadblock where I wasn't able to mock Event.Watch()
CI passes

chore: add tests for CreateNamespace and DeleteNamespace in jobs.go

---

webui/react/src/e2e/models/components/ExperimentActionDropdown.ts
webui/react/src/e2e/tests/experimentList.spec.ts
webui/react/src/e2e/utils/detCLI.ts

test: create Pause experiment action test [ET-644]

---

docs/release-notes/basic-lineage.rst

-  WebUI: View Pachyderm data lineage
The backend has already been updated in a prior release. To use this feature the user must already have configured the Pachyderm data integration via their MLDE config file(s). This feature is just to let users click on a link from the MLDE trial view page to the Pachyderm repo for the Pachyderm data. The user can also click this link when viewing checkpoints derviced from the Pachyderm data.

docs: basic lineage release notes

---

webui/react/src/e2e/tests/experimentList.spec.ts

test: skip flaky test until after release

---

docs/setup-cluster/k8s/resource-caps.rst

https://github.com/determined-ai/determined/pull/9687/files#r1690263010

docs: Fix workspace cli doc

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx

ET-606
Fixing bug where we would show "Fetching Metrics..." for canceled experiments that had no metrics
1. Start a new experiment that can spawn metrics (eg `det e create examples/tutorials/core_api/3_hpsearch.yaml examples/tutorials/core_api/ `)
2. Cancel it before it starts
3. Go to the Visualization tab and see that it shows "No data to plot"

fix: Endless fetching for cancelled experiment without metrics

---

webui/react/src/e2e/tests/userManagement.spec.ts

Skip failing automated test Deactivate and reactivate user

chore: skip failing Deactivate and reactivate user test

---

master/internal/api_experiment.go

chore: fix exp delete log msg

---

docs/release-notes/compare-selected-experiments.rst

chore: add release note for ComparisonView bugfix

---

webui/react/src/components/ProjectCard.tsx
webui/react/src/e2e/models/common/ant/Switch.ts
webui/react/src/e2e/models/common/hew/Label.ts
webui/react/src/e2e/models/common/hew/Toggle.ts
webui/react/src/e2e/models/components/ProjectCard.ts
webui/react/src/e2e/models/components/WorkspaceCreateModal.ts
webui/react/src/e2e/models/pages/ProjectDetails.ts
webui/react/src/e2e/models/pages/WorkspaceDetails.ts
webui/react/src/e2e/models/pages/WorkspaceDetails/WorkspaceProjects.ts
webui/react/src/e2e/models/pages/WorkspaceList.ts
webui/react/src/e2e/tests/projectsWorkspaces.spec.ts
webui/react/src/pages/WorkspaceList.tsx
webui/react/src/pages/WorkspaceList/WorkspaceCard.tsx

[TESTENG-60]
adds a majority of workspace tests and some test hooks
[TESTENG-60]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: workspace and project tests [TESTENG-60]

---

webui/react/src/pages/JobQueue/ManageJob.tsx

refactor: change 'close' to 'save' on button in ManageJob modal [DET-10446]

---

webui/react/src/components/Searches/Searches.settings.ts
webui/react/src/components/Searches/Searches.tsx

fix: debounce searches column width settings #9700

---

webui/react/src/e2e/tests/userManagement.spec.ts

Fix for this test was merged (https://github.com/determined-ai/determined/pull/9735) so undoing the skip

chore: undo test skip after fix was merged

---

docs/requirements.txt

MD-468
This fixes two issues:
1. `make all` was not working. We need a higher Sphinx version.
2. If I ignore the build doc error. I have have to downgrade numpy from 2.0.1 to 1.23.5 for running code that depends on tensorflow successfully. It seems like any code that relies on tensorflow would be impacted.
The steps to reproduce the issues are included in the ticket description.

chore: pin numpy version and upgrade sphinx [MD-468]

---

webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.settings.ts
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/TrialCheckpoints.tsx
webui/react/src/pages/TrialDetails.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts

[ET-658]
Adds a `Checkpoints` tab to the view at experiments/x/trials/y/overview , using the trial checkpoints API.
1. Created and ran a single run with checkpoints
2. With flat runs view enabled, navigated to the run overview page
3. Observed Checkpoints tab in the expected location; clicked it
4. Saw checkpoint summary table
[ET-658]: https://hpe-aiatscale.atlassian.net/browse/ET-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: checkpoint view for flat runs [ET-658]

---

docs/setup-cluster/on-prem/_index.rst

N/A
This fixes a CI failure on main, first seen [here](https://app.circleci.com/pipelines/github/determined-ai/determined/58945/workflows/c1725fec-15f9-4eda-ae69-b8f451c190d4/jobs/2826773).
The freedesktop dot org website has changed its certificates and no longer signs for an unprefixed domain. Adding in the WWW to get https://www.freedesktop.org/wiki/Software/systemd/ obtains a valid certificate, however this page indicates that it too is obsolete and has been replaced by a new dedicated systemd page.
N/A

docs: fix insecure link to systemd docs

---

master/internal/api_runs_intg_test.go
master/internal/experiment_filter.go

ET-675
Fixing the contains & notContains operators for hyperparameter and metadata filters in the Run Table
Select a hyperparameter or metadata filter with 'contains' & 'notContains' operator (text values) on the runs table and filter 

fix: fix contains filter for hyperparameters and metadata

---

webui/react/README.md

chore: readme should include codecov

---

webui/react/README.md

chore: fix readme typo

---

webui/react/src/omnibar/tree-extension/index.test.tsx
webui/react/src/omnibar/tree-extension/index.ts

[ET-203]
Adding tests to the tree-extension portion of the omnibar to boost code coverage.
[ET-202]: https://hpe-aiatscale.atlassian.net/browse/ET-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-203]: https://hpe-aiatscale.atlassian.net/browse/ET-203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: omnibar tree-extension tests [ET-203]

---

webui/react/src/pages/FlatRuns/columns.ts

https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1722886900665269
[ET-680]
fixed the link of `forked` column in the flat run table
- Check if the link in the `forked` column in the flat run table navigate to the correct page
[CM-418]: https://hpe-aiatscale.atlassian.net/browse/CM-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-680]: https://hpe-aiatscale.atlassian.net/browse/ET-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …

fix: forked from link

---

.circleci/real_config.yml

Fix a bug introduced in #9792 .
Does slurmcluster CI work okay?

ci: fix scripting for `make slurmcluster` job

---

webui/react/src/components/NavigationSideBar.module.scss

[ET-633]
On short screens (such as landscape-oriented mobile devices) the navigation sidebar was not scrollable and so only the items at the top of the list were visible. This ticket makes the sidebar scrollable.
[ET-633]: https://hpe-aiatscale.atlassian.net/browse/ET-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: make navigation sidebar scrollable [ET-633]

---

webui/react/src/components/FilterForm/TableFilter.tsx
webui/react/src/components/FilterForm/components/FilterField.tsx
webui/react/src/components/FilterForm/components/FilterForm.tsx
webui/react/src/components/FilterForm/components/FilterGroup.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

[ET-227]
Display values for metadata columns in Runs view filter menu
https://github.com/user-attachments/assets/eff8e64b-f587-4e92-9782-55c31c740202
- Add string type metadata
- Check if user should be able to filter by string type metadata in the run table
- Check if non string type metadata columns are not visible in filter
- Check if use InputSelect from hew so that there is both 
- Autocomplete from suggestions list and 
- Saving text in input even if it doesn’t exactly match one of the suggestions
- Check if only `conditions is, is not, and contains` conditions are allowed for the string type metadata columns
[ET-227]: …

feat: support filter by metadata with string type

---

master/internal/api_experiment.go
master/internal/experiment/bulk_action.go
master/internal/experiment/bulk_action_intg_test.go
master/internal/experiment/bulk_action_test.go

[ET-138]
[ET-139]
[ET-140]
Adds unit tests to cover `ActivateExperiments`, `CancelExperiments`, `KillExperiments`, `PauseExperiments`, and the underlying `getExperimentsEditableByUser` logic which is mostly orthogonal to the "do this operation on every eligible experiment" piece.
No new behaviors have been added; this is an extremely light refactor for testability and the rest of it is for test coverage only.
[ET-138]: https://hpe-aiatscale.atlassian.net/browse/ET-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-139]: https://hpe-aiatscale.atlassian.net/browse/ET-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …

test: add go unit tests for experiment bulk actions [ET-138]

---

docs/integrations/data-transformers/pachyderm.rst
docs/tutorials/pachyderm-cat-dog.rst

Clarify that the link lets them go to their pachyerm repo.
Related: #9813 

Clarify basic data lineage to mldm

---

docs/release-notes/updated-user-roles-slot-caps.rst

Added release notes for PR [9822](https://github.com/determined-ai/determined/pull/9822)

chore: add release notes for PR 9822

---

webui/react/src/components/FilterForm/TableFilter.tsx
webui/react/src/components/FilterForm/components/FilterForm.tsx
webui/react/src/components/Searches/Searches.tsx
webui/react/src/components/TableActionBar.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx

[ET-740]
Check the title of the filter view with flat runs toggled off/on.
[ET-740]: https://hpe-aiatscale.atlassian.net/browse/ET-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change filter form to say "Show runs" in flat runs view [ET-740]

---

master/internal/api_agents.go
master/internal/api_job.go
master/internal/job/jobservice/jobservice.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go

[CM-456]
This will not remain in production; the goal is to include it in the release party candidate to get better information on a performance issue and then revert it before cutting the final build.
[CM-456]: https://hpe-aiatscale.atlassian.net/browse/CM-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add tracing info to some backend APIs

---

docs/manage/security/tls.rst
harness/determined/keras/_tf_keras_trial.py

Fix broken tensorflow & certbot links to ensure that `make -C docs check-links` passes as expected
- N/A

fix: update broken tensorflow & certbot links

---

master/internal/api_agents.go
master/internal/api_job.go
master/internal/job/jobservice/jobservice.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go

Reverts determined-ai/determined#9841

Revert "chore: add tracing info to some backend APIs"

---

webui/react/src/e2e/README.md
webui/react/src/e2e/tests/experimentList.spec.ts

ET-674
This adds a test to the e2e test suite that tests the bulk experiment kill flow.
e2e tests should continue to pass, no other testing required.

ci: add e2e bulk kill test

---

helm/charts/determined/templates/master-config.yaml

[CM-515]
Fix syntax in master-config.yaml.
[CM-515]: https://hpe-aiatscale.atlassian.net/browse/CM-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: fix master-config syntax

---

e2e_tests/tests/cluster/test_webhooks.py

Delete workspaces after webhook test
e2e_test pass

test: Delete workspace after webhook test

---

webui/react/src/e2e/tests/projectsWorkspaces.spec.ts

Fixes issue with View Toggle test on Workspace List unnecessarily expecting a specific workspace.
No additional release party testing required. Automated tests should pass.

fix: flaky workspace test

---

codecov.yml

No ticket for this.
Our code coverage has increased to about 43.5%! 🎉
We can afford to bump our coverage target to 45% with a 3% threshold, so project coverage can be between 42% to 48% for passing CI.
CI passes.

chore: bump coverage target

---

webui/react/src/e2e/tests/experimentList.spec.ts

[ET-753]
[ET-753]: https://hpe-aiatscale.atlassian.net/browse/ET-753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: experiment list show archived filter [ET-753]

---

webui/react/src/e2e/fixtures/api.workspace.fixture.ts

[TESTENG-95]
throw token into debug error message if unauthenticated
[TESTENG-95]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: debug auth [TESTENG-95]

---

master/internal/api_config_policies.go
master/internal/api_config_policies_intg_test.go
master/internal/configpolicy/postgres_task_config_policy.go
master/internal/configpolicy/postgres_task_config_policy_intg_test.go
master/pkg/model/task_config_policy.go

CM-487
- added GET API endpoint for config policies
- refactored structs for TaskConfigPolicies and combined into one
- refactored CRUD functions to work for both workload types
- refactored tests to work with the new changes
- added automated tests

feat: add Config Policies GET API and modify CRUD functions to accept both Workload types

---

tools/slurm/scripts/slurmcluster.sh

The `make slurmcluster` step in CI has two fairly common failure modes:
- The `gcloud compute scp` command to fetch the launcher token fails [saying the remote file does not exist](https://app.circleci.com/pipelines/github/determined-ai/determined/59943/workflows/a719335a-9783-4988-94c1-48316a227613/jobs/2894155).  That feels like it might be some sort of startup problem rather than the file only existing in some VMs.
- The `gcloud compute ssh` command to start launcher.service sometimes [fails complaining about a timeout](https://app.circleci.com/pipelines/github/determined-ai/determined/60237/workflows/a2bc119e-bacd-4d54-a6ea-b14c2bc5e0fe/jobs/2916385).  Additional retries may solve this.
I'm hoping to fix the flakes by introducing a small retry loop around these commands. …

ci: deflake make slurmcluster, hopefully

---

master/internal/core.go
webui/react/src/App.tsx
webui/react/src/routes/index.tsx

[ET-783]
Initial page load speed is slow in any pages, especially the flat run table page. In order to fix this issue, applied 2 techniques. 
1. Code splitting
2. Compress CSS, JS files (surprisingly these files weren't compressed)
Backend is http://latest-main.determined.ai:8080/
Tested web page is http://localhost:8080/det/projects/1/runs
- Check if JS/CSS files are compressed (gzip)
- Check if web files are splitting
- Check if all pages are accessible like before (no regressions)
[ET-783]: https://hpe-aiatscale.atlassian.net/browse/ET-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: …

perf: improve the initial page load speed

---

webui/react/src/pages/FlatRuns/FlatRuns.tsx

https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1727117556339019
- incorrect `dataPath` for hyperparameters, so table showed empty data(`-`) unintentionally
- Check if hyperparameter values are correctly shown  in both flat run and experiment table

fix: correct `dataPath` for hyperparameters

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/ConfigPolicies.test.tsx
webui/react/src/components/ConfigPolicies.tsx
webui/react/src/hooks/usePermissions.ts
webui/react/src/pages/WorkspaceDetails.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

CM-478
Adds "Config Policies" tab to WorkspaceDetails page, with editor for config policies YAML.
Error:
Confirmation modal:
Success toast:
No permissions:
Empty: 
Only in EE:
- Non-admin should not see `Apply` button
- Admin should be able to `Apply` (with valid YAML syntax that modifies what's fetched)

feat: workspace task config policies UI [CM-478]

---

webui/react/src/e2e/tests/userManagement.spec.ts

test: increase Reactivate test step timeout

---

docs/release-notes.rst

docs: Update release notes date

---

webui/react/src/components/CompareHyperparameters.test.mock.tsx
webui/react/src/components/ComparisonView.test.mock.tsx
webui/react/src/components/ExperimentContinueModal.module.scss
webui/react/src/components/ExperimentContinueModal.tsx
webui/react/src/components/ExperimentCreateModal.tsx
webui/react/src/components/HyperparameterSearchModal.tsx
webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
webui/react/src/fixtures/responses/experiment-details/set-a.json
webui/react/src/pages/Dashboard.test.tsx
webui/react/src/pages/ExperimentDetails/ExperimentDetails.test.mock.ts
webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/TrialDetails/TrialInfoBox.test.tsx
webui/react/src/types.ts
webui/react/src/utils/experiment.test.ts
webui/react/src/utils/experiment.ts
webui/react/src/utils/tests/generateTestData.ts

[MD-527]
Part of searcher context removal project.
Remove `max_length` for searchers in WebUI
Continue/Fork/HPSearch work as expected with the right backend.
Tests passed.
[MD-527]: https://hpe-aiatscale.atlassian.net/browse/MD-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove max_length from WebUI

---

webui/react/src/e2e/fixtures/user.fixture.ts
webui/react/src/e2e/tests/userManagement.spec.ts
webui/react/src/e2e/utils/users.ts

CM-468
Makes changes to User Management tests. No major changes to test steps, mostly refactoring. Notable changes include:
- Shares one test user between all single-user tests.
- No longer keeps track of user state when not necessary.
- Uses `TestUser` type instead of `V1PostUserRequest` to simplify code.
Should not require additional release party testing. Automated tests should pass.

test: User Management test updates [CM-468]

---

webui/react/src/components/TaskActionDropdown.tsx
webui/react/src/components/TaskList.tsx
webui/react/src/e2e/models/components/TaskList.ts
webui/react/src/e2e/tests/workspaceTasks.spec.ts
webui/react/src/types.ts

[MD-460]
Allow user to copy task ID from task table action.
At the task list page, click on the triple dots to expand the action.
Click on copy task ID, and verify that the task ID has been copied to clipboard.
[MD-460]: https://hpe-aiatscale.atlassian.net/browse/MD-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add copy task id to task list

---

docs/release-notes/config-policies.rst

[CM-574]
Release note for task config policies project.
[CM-574]: https://hpe-aiatscale.atlassian.net/browse/CM-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: task config policies release note

---

docs/model-dev-guide/api-guides/apis-howto/api-pytorch-ug.rst
examples/tutorials/mnist_pytorch/adaptive.yaml
examples/tutorials/mnist_pytorch/train.py
harness/determined/pytorch/_pytorch_trial.py
harness/determined/pytorch/_trainer.py

duplicate of https://github.com/determined-ai/determined/pull/10065 but merging this b/c messy rebase

chore: refactor max length out of pytorch trials

---

e2e_tests/tests/experiment/test_pending_hpc.py

This test contains a 60 second sleep() to ensure a log line has time to get injected, then asserts that the log line is found.
Then it tries to kill the first experiment with a comment about speeding up the test.  Except the underlying test is usually done in 50 seconds, not 60.  And the log line usually appears in 10ish seconds, not 60.
So instead, wait until the log line appears, then kill the first experiment, then wait for a RUNNING state on the second experiment, then end the test.

ci: shorten test_pending_hpc.py

---

helm/charts/determined/templates/db-volume-snapshot-class.yaml

chore: conditionally create VolumeSnapshotClass

---

docs/reference/experiment-config-reference.rst
docs/tutorials/_index.rst
docs/tutorials/log-management.rst

Two new features: improved log search and log signal

docs: Update log policies

---

examples/deepspeed/dcgan/mnist.yaml
examples/deepspeed/dcgan/trainer.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/determined/pytorch/deepspeed/_trainer.py

refactors ops/max length out of deepspeed trial

chore: refactor max_length out of deepspeed trial

---

e2e_tests/tests/nightly/test_distributed.py
examples/diffusion/textual_inversion_stable_diffusion/detsd/pipeline.py
examples/diffusion/textual_inversion_stable_diffusion/generate_grid.yaml

fix diffusion example that was lost along the way to searcher context removal.
weirdly enough, this test was not failing [before](https://app.circleci.com/pipelines/github/determined-ai/determined/62232/workflows/09db8e85-9833-4d90-8c83-fe56869fa150/jobs/3059227/artifacts) but is [now](https://app.circleci.com/pipelines/github/determined-ai/determined/62423/workflows/4493aacc-3a28-4292-b029-d0b683fe73e1/jobs/3074291/artifacts) despite the code not having changed. 
as @rb-determined-ai discovered, the missing MAX_LENGTH by itself wasn't enough to cause the test to fail, because the trial increments step before the error and loads from checkpoint on restart. in the trial that was failing, a previous data download step had failed, causing the test assertion to be invalid.
See [Release …

fix: fix diffusion example [DET-10470]

---

harness/determined/keras/_callback.py
harness/tests/experiment/keras/test_callback.py

What happened was an unfortunate combination of fancy context managers and early exits, where I was unwittingly deleting checkpoints before keras could load them, but only in the case of checkpoints from different trial IDs.  I had tested pause/continue, which didn't have the bug.
The new code is structurally incapable of the same bug, and has a regression test anyway.

fix: keras continue from cloud checkpoint

---

docs/release-notes/gen-ai-warning.rst

add release note calling out incompatibility for GenAI studio

chore: genai release note

---

docs/release-notes/unsupport-aurora-postgres-reminder.rst
harness/determined/deploy/aws/aws.py

Release notes and error log in harness should link to my gist rather than Ryan's.

fix: use new migration gist

---

docs/release-notes/security-note.rst

Update dependencies release notes.

docs: update dependencies

---

e2e_tests/tests/requirements.txt

aiohttp-cors 0.8.0 breaks ray 2.10.0 (the latest version python 3.8 supports)

chore: pin aiohttp-cors

---

docs/release-notes.rst
docs/release-notes/security-note.rst

docs: add release notes for 0.38.1
