master/internal/rm/agentrm/agent_state.go
master/internal/rm/agentrm/agent_state_intg_test.go
master/internal/rm/agentrm/agent_state_test.go

I removed the RP arg to retrieving agent states since restore is enabled by default for every resource pool now (plus, it was wrong, since I don't think it accounted for implicit default pools).
DET-10060

chore: add tests for agent_state.go queries

---

webui/react/src/components/RegisterCheckpointModal.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx

We will attempt to register all of the checkpoints on a page for certain views. This PR will use only the selected checkpoints.
Launch an experiment like `det e create ./examples/tutorials/core_api/2_checkpoints.yaml ./examples/tutorials/core_api/`.
On the experiment checkpoint page click on the three dots icon (far right) to register. Make sure experiment registers successfully and that you can change the "Version Name".
Next select multiple checkpoints and perform a bulk action register for two checkpoints.
Then verify the checkpoints are correctly registered in the model registry page.
WEB-1948

fix: use selected checkpoints when registering

---

docs/release-notes/master-mount.rst
helm/charts/determined/templates/master-deployment.yaml
helm/charts/determined/values.yaml

Adds a `mountToMaster` value under `checkpointStorage`. Set to `false` by default means no change to current behavior.
If it's set to `true` and the type is `shared_fs` it will add that hostpath mount to the master as well. This allows for `checkpoint.download()` to work with `shared_fs` on Kubernetes on version `0.27.0` and up.
tested with both true/false set on both shared_fs and other checkpoint storage. Works as expected- only creates volume mount when true and shared_fs.
- [ N/A] Licenses should be included for new code which was copied and/or modified from any external code.
No Ticket

feat: helm option to mount shared_fs checkpoints to master

---

webui/react/src/pages/ModelDetails.tsx

[WEB-1326]
- Check if pagination works in model detail page
[WEB-1326]: https://hpe-aiatscale.atlassian.net/browse/WEB-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: pagination fix in model detail page

---

webui/react/src/components/ManageNodesModal.module.scss
webui/react/src/components/ManageNodesModal.tsx
webui/react/src/pages/ResourcePool/ResourcepoolDetail.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/decoder.ts
webui/react/src/types.ts

When admin views a cluster resource pool, they'll see a dropdown in the breadcrumbs section:
If there are no active agents, there is a Message
If there are available agents, they appear as a set of toggle switches reflecting enabled/disabled state.
The "Apply Changes" button becomes enabled once changes are made.
When there are 10+ toggles, there is a text filter:
**The original ticket suggests a dropdown to allow jobs to finish or 'gracefully terminate', but no such option is available in the current EnableAgent Go code**
I've included `const defaultNodes` and `nodes = defaultNodes` as comments; uncommenting these makes two agents visible. When you click Apply Changes, you will see an API call and error (because these are not real agent IDs).
See [Release …

feat: Add a modal to enable/disable Agents [WEB-1718]

---

tools/devcluster.yaml

Existing setup leaves users exposed to stale bindings build. Let's have the harness and webui build keybindings rebuild the proto bindings as well.
https://hpe-aiatscale.slack.com/archives/C04TUNDGKMF/p1706040175088669

chore: `make devcluster` to rebuild bindings before harness and webui.

---

harness/determined/deploy/aws/deployment_types/vpc.py
harness/determined/deploy/aws/templates/lore.yaml

This uses the new genai docker repo rather than the older repo we were using before.
Deploy a determined cluster on AWS. Example: 
```
det deploy aws up \
--deployment-type genai \
--genai-version latest \
--det-v 0.27.0 \
--aux-agent-instance-type m5.large \
--compute-agent-instance-type g4dn.xlarge
```
With your own cluster-id and keypair. 
SSH into the master and confirm the docker image is from `determinedai/genai:latest` rather than `determinedai/environments-dev:lore-backend-image-latest`

fix: use the new genai docker repo

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

This change was initially made in determined-ai/determined-ee@df500801e44a
PR: determined-ai/determined-ee#1121
CC: @carolinaecalderon 
I did add documentation in the values file, which was originally missing in EE.  Not sure why this parameter is capitalized, since it probably shouldn't be, but cleaning up the helm chart to make it consistent is not within the scope of this PR.
N/A - this'll totally just work (since it's been fine in EE for a while).  So confident, I'm skipping CI.
I did run
```
helm template --set maxSlotsPerPod=2 ./helm/charts/determined/
```
and validated that there are no parse issues.  And then...
```
sauer@host$ helm template --set maxSlotsPerPod=2 --set oidc.GroupsClaimName=hello --set oidc.enabled=true --set enterpriseEdition=true --set oidc.provider=xxx --set …
```

chore: bring in missing EE helm chart change [ci skip]

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/F_ExpList/glide-table/contextMenu.tsx

The bug: Options in the right-click context menu sometimes close the menu but do not execute the action (archive/unarchive, open edit modal, etc.)
A few days after the bug report, we upgraded to glide-table v6. The bug is still present.
The easiest way to repeat the bug is to right-click the top row, and then click an option which is overlayed over the table header, or outside the glide table.
The issue was `useOutsideClickHandler` - from https://github.com/determined-ai/determined/pull/6532 - we use it to close the ContextMenu by clicking somewhere outside. We keep this handler but make it trigger in fewer cases.
I fixed an unrelated bug with the "Experiment updated successfully" message. `notification.success` (pictured) is replaced by more standard `openToast`.
It is easier to test …

fix: Experiment table, right-click context menu [WEB-1942]

---

webui/react/src/components/CheckpointModalTrigger.test.tsx
webui/react/src/components/CheckpointModalTrigger.tsx
webui/react/src/hooks/useFetchModels.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/pages/ExperimentDetails/ExperimentTrials.tsx
webui/react/src/pages/TrialDetails/TrialDetailsWorkloads.tsx

[WEB-1950]
- Check if model fetch api is only called once in init phase
- Check if checkpoint `delete` and `register` still works
[WEB-1950]: https://hpe-aiatscale.atlassian.net/browse/WEB-1950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: cease many model fetch api calls in checkpoint tab

---

docs/reference/training/experiment-config-reference.rst
docs/release-notes/command-capacity.rst
e2e_tests/tests/cluster/test_resource_manager.py
e2e_tests/tests/command/test_run.py
master/internal/core_experiment.go
master/internal/rm/agentrm/resource_managers_test.go
master/internal/rm/agentrm/resource_pool.go
master/internal/trial.go
master/pkg/model/command_config.go
master/pkg/model/compat.go
master/pkg/model/experiment_config.go
master/pkg/schemas/expconf/experiment_config.go
master/pkg/schemas/expconf/zgen_resources_config_v0.go
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/resources.json
schemas/test_cases/v0/defaults.yaml
schemas/test_cases/v0/experiment.yaml

- Add an expconf flag to allow forcing command-like scheduling for experiments (https://hpe-aiatscale.slack.com/archives/C04TUNDGKMF/p1706031288718059)
- Fix command capacity checks on static pools (https://hpe-aiatscale.slack.com/archives/C02PV33GSN5/p1706067629265619)
- Added an autotest to ensure flagged experiments don't get distributed across multiple nodes in `e2e_cpu_2a`.
- Scrapped/reworked some older tests which don't make sense any more.
currently not supported by slurm due to https://github.com/determined-ai/determined-ee/blob/64ae6c75eb1d5072cb60b1572f394219c0210f57/master/pkg/tasks/dispatcher_task.go#L568

feat: expconf flag to force scheduling on a single node/container/pod

---

docs/reference/deploy/helm-config-reference.rst

Update helm chart configuration reference to support #8741 as described in the 0.27.1 release notes.
Specifically, update the documentation, adding the `mountToServer` value under checkpointStorage. Describe `false` (default) and `true` (when storage type is `shared_fs`, the shared directory will be mounted on the server, allowing `checkpoint.download()` to work with `shared_fs`.

Update helm chart config ref

---

master/internal/proxy/proxy.go

https://hpe-aiatscale.slack.com/archives/C02PV33GSN5/p1706202417603839
Run a notebook and make sure we don't see a lot of connections with
```
netstat -W | awk '{print $5}' | cut -d':' -f1 | sort | uniq -c
```

fix: add default transport to proxy connection

---

docs/get-started/example-solutions/_index.rst
docs/model-dev-guide/api-guides/apis-howto/deepspeed/autotuning.rst
docs/model-hub-library/_index.rst
docs/model-hub-library/transformers/_index.rst
docs/reference/model-hub/_index.rst
docs/release-notes.rst

At huggingface.co the name of the organization is Hugging Face (two words, both capitalized). When referencing the name of the organization use Hugging Face rather than Huggingface or huggingface. This rule does not apply to names of libraries or functions.
Fixes instances where Hugging Face Transformer was misspelled as Trainsformer.

docs: Fix minor issues

---

webui/react/src/components/FilterForm/components/FilterField.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

In the experiment filter UI, switching from a text filter (Name contains "profile") to a numeric filter (metric = _), calls `updateFieldValue(field.id, null);`.
~Update: the issue is `isValid` filters fields for the API calls and for saving in `updateSettings`, so temporary invalid states such as `value == null` won't be stored, and can get overwritten by previous values. The best option is to separate `asJsonString` and `asSettingsString` in the new approach.~
2nd Update: now treating this as a race condition, where anything which updates the form field operators and values, is wrapped in an `Observable.batch`
Set a text query (Name contains "val"); experiments are filtered
Change column name to another text column (Searcher Metric); text value is still used for filter
Change column name …

fix: Filter value resets when switching column types [WEB-1949]

---

harness/tests/requirements/requirements-harness.txt

Resolve some issues with recently released python modules by pinning to older versions.

fix: python requirements for pytest and moto

---

.circleci/real_config.yml
requirements.txt

Model_hub tests require building tokenizers, that are pinned to an older version and require a now old version of the rust compiler. Remove the requirement for local development; the CI imports the requirement independently. 
Confirm all CI tests complete successfully.
Context: https://hpe-aiatscale.slack.com/archives/CSG3W08JY/p1706227736615449?thread_ts=1691690041.149519&cid=CSG3W08JY

test: do not import model_hub test requirements

---

webui/react/src/components/ProjectMoveModal.tsx

A ticket about workspaces in the ProjectMoveModal dropdown
- appearing in alphabetic order (currently ✔️ )
- search / autocomplete (currently ❌ )
Sets searchable text of workspaces using `label={workspace.name}`
The filter might have broken when we updated Typography. `ExperimentMoveModal` is already working
Open a workspace other than default (such as `/det/workspaces/1486/projects`)
Click the three dots menu to select "Move..."
In the modal, test text autocomplete is case-insensitive

fix: Text filter on ProjectMoveModal [WEB-1495]

---

CONTRIBUTING.md

Webui requires node 20.* to compile. The docs listed multiple version of python; updating it so be consistent.
Run `make all` with the specified dependency versions.

docs: update dependency version in contributing readme

---

docs/reference/deploy/master-config-reference.rst
docs/release-notes.rst

Update reference docs to be more consistent. Update the name of the option, `oidc.groups_claim_name` to `oidc.groups_attribute_name` in the 0.26.5 release notes so that users know which option to look for in master config file.
Purpose: There were changes to the enterprise only edition features (security and authentication) as described in the enterprise only edition of the release notes for 0.27.1.

docs: Update oidc and saml docs

---

.circleci/real_config.yml

Update GKE version to comply with latest release for e2e tests.
CI passes on main.

chore: update gke version to comply with latest release for e2e tests

---

master/internal/db/postgres_tasks.go
master/internal/db/postgres_tasks_intg_test.go
master/internal/db/postgres_test_utils.go
master/pkg/model/task.go
master/pkg/model/task_session.go

Add integration tests for all exported functions in `db/postgres_tasks.go`, and initialize the db in TestMain.
Add bun descriptions to the AllocationSession & TaskLog models, so that the ID key is auto-incremented with each addition.
See attached test.
Truncated the start time in `RequireMockAllocation` to match what the db stores.
Remove `CheckTaskExists ` from `postgres_tasks.go`, as it's used nowhere.
Writing the tests first, then bun-ifying db/postgres_tasks.go in https://github.com/determined-ai/determined/pull/8764
DET-10124

test: add intg tests for tasks module

---

webui/react/package-lock.json
webui/react/package.json

this fixes an issue where, when switching between document cards, the prompt asking th euser if they're sure and warning against data loss appears with no buttons and the wrong text
* visit the notes section of a project
* add a new note
* edit the content of the note
* add another new note
* switch to the new note you just created
* a modal should appear with proper fonts and options
WEB-1961

fix: update hew to a version without broken documentcard prompts

---

master/internal/api_checkpoint_intg_test.go
master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/api_tasks_intg_test.go
master/internal/api_trials_intg_test.go
master/internal/checkpoint_gc.go
master/internal/command/command.go
master/internal/core.go
master/internal/db/database.go
master/internal/db/postgres.go
master/internal/db/postgres_cluster_intg_test.go
master/internal/db/postgres_tasks.go
master/internal/db/postgres_tasks_intg_test.go
master/internal/db/postgres_test_utils.go
master/internal/db/postgres_trial.go
master/internal/db/postgres_trial_intg_test.go
master/internal/db/setup.go
master/internal/populate_metrics.go
master/internal/rm/agentrm/agent.go
master/internal/rm/agentrm/agent_state_test.go
master/internal/task/allocation.go
master/internal/task/allocation_service_test.go
master/internal/telemetry/reports.go
master/internal/telemetry/telemetry_test.go
master/internal/trial.go
master/test/integration/api/api_checkpoints_test.go
master/test/integration/api/api_trials_test.go

Bunify methods in `db/postgres_tasks.go`, and add a context.Context parameter to those functions. 
For functions that call methods from `postgres_tasks.go`, define `ctx := context.Background()` if it's not already passed in as a parameter. For functions that passed in the db as a parameter, but no longer need it because the relevant method is bun-ified, remove the db parameter. (_in other words, streamline the substitutions_).
Remove unused functions in `postgres_test_utils.go, postgres.go`.
For the method `completeTrialsTask`, originally in `postgres_tasks.go`, remove the function wrapper, and insert it directly into the `postgres_trials.go`  method where it's only used once.
`errors.Errorf(...) --> fmt.Errorf(...)` for all methods bun-ified, or majorly refactored.
Unmocked the db in …

chore: bunify db/postgres_tasks.go 

---

master/internal/rm/kubernetesrm/informer.go

When k8s retrywatcher fails, it causes us to receive infinite nil events and pins the CPU to 100%. Since a retrywatcher failure likely means something bad happened, we'll panic when the issue comes up. 
Manually tested - as long as the cluster is able to work normally without crashing, this fix works. The bug that this fixes happens infrequently and we'll land a test PR after this one.

fix: retry watcher failure causes infinite loop

---

master/internal/api_master_intg_test.go
master/static/srv/get_aggregated_allocation.sql

Improve resource aggregation daily performance.
Integration test should cover it.

perf: improve resource agg performance

---

master/internal/api_workspace_intg_test.go
master/static/srv/get_workspace.sql
master/static/srv/get_workspaces.sql

Improve performance of ```get_workspaces.sql```. 
The anon db revealed the query is taking way longer than it should.
This PR essentially undoes the optimization added in https://github.com/determined-ai/determined/pull/5929

perf: improve get_workspaces query

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go

Use ```bestTrialID``` to improve the performance of get experiments.
We already do this for search experiments.
integration test should cover it

perf: improve GetExperiments showTrialData performance

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/core_checkpoint_intg_test.go
master/internal/core_experiment.go
master/internal/db/database.go
master/internal/db/postgres_experiments.go
master/internal/db/postgres_test_utils.go
master/internal/db/postgres_trial_intg_test.go
master/internal/experiment.go
master/internal/populate_metrics.go
master/internal/restore.go
master/pkg/model/experiment.go
master/pkg/model/test_utils.go
master/test/integration/api/api_checkpoints_test.go
master/test/integration/api/api_trials_test.go

We often load model def for experiments when we really shouldn't. This change makes it a lot harder to load the model def if you don't mean to.
Existing tests pass

perf: avoid loading model def in experiment model

---

.circleci/real_config.yml

Fix alerts always happening instead of just happening on failure.
After this lands see if I get pinged.

ci: make perf tests only alert on failure

---

webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx

this fixes an issue where resetting the filter settings on trials with logs that take a long time to respond (over 500 ms) can cause the catch up log request to get cancelled. To fix, we skip aborting the request when handling filter changes if the filter is being updated to an empty object. This is because the request was already reset when the filter was reset. We also ensure that old requests don't stick around by merging the outer abort controller with the one that the stream config gives us.
- on a trial logs page, use devtools to throttle the network to GPRS levels
- apply a filter and wait for the logs to appear.
- click reset filters
- the full logs should appear …

fix: improve trial log request cancelling

---

master/static/migrations/20240202140521_proto-checkpoint-view-missing-index.tx.down.sql
master/static/migrations/20240202140521_proto-checkpoint-view-missing-index.tx.up.sql
master/static/srv/get_model_version.sql
master/static/srv/get_model_versions.sql
master/static/srv/insert_model_version.sql
master/static/srv/update_model_version.sql

```proto_checkpoint_view``` was casting ```checkpoints_v2.uuid``` to a text meaning we couldn't use the index on ```checkpoints_v2.uuid``` so model queries were full scanning checkpoints.
```TestCheckpointReturned``` should have this covered well

perf: update proto_checkpoint_view to use index

---

docs/release-notes/oidc-changed-vars.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

Add EE helm chart changes to OSS

chore: add ee helm chart changes to oss

---

master/internal/api_auth.go
master/internal/api_user_intg_test.go

to proxied services instead of redirecting those to login  page
https://hpe-aiatscale.atlassian.net/browse/GAS-568?filter=-2
```
after:
hbp ➜ lore git:(main) ✗ curl -H "Accept: application/json" -L http://localhost:8080/genai/favicas -v
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /genai/favicas HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.4.0
> Accept: application/json
>
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json; charset=UTF-8
< Vary: Origin
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 1; mode=block
< Date: Fri, 02 Feb 2024 23:48:17 GMT
< Content-Length: 27
<
{"message":"Unauthorized"}
* Connection #0 to host localhost left intact
before:
hbp ➜ lore git:(main) ✗ curl -H "Accept: application/json" …
```

chore: respond with 401 for programmatic requests.

---

master/internal/api_trials.go
master/internal/db/database.go
master/internal/db/postgres_trial.go
master/internal/db/postgres_trial_intg_test.go
master/internal/trial.go
master/pkg/model/experiment.go

Condenses trial update functions into one function that updates the specified fields for a given trial.
CI passes.
DET-9993

refactor: condense trial update functions

---

master/internal/rm/kubernetesrm/informer_intg_test.go

#8786 was a release fix that addressed the issue of uncaught retryWatcher failures. This PR adds a test to make sure that the code behaves as expected when the channel the informer reads from is closed.
No manual testing required. Run the test and make sure it succeeds. 

chore: add testing for k8s informer panic

---

docs/release-notes/identify-task.rst
master/internal/command/postgres_command.go
master/internal/command/postgres_command_intg_test.go

Remove extra quotes around TaskType from IdentifyTask -- fix the corresponding intg test to match this.
These changes will affect api_auth.go in the following code block:
```
if spec.TaskType == model.TaskTypeTensorboard {
err = command.AuthZProvider.Get().CanGetTensorboard(...)
} else {
err = command.AuthZProvider.Get().CanGetNSC(...)
}
```
The 'if' block would never be true before, but now it can be.
Run intg tests.
We could test this feature's effect in api_auth.go by duplicating the processProxyAuthentication, but I believe TestIdentifyTask suffices when we replace the equality check with `model.TaskTypeABC` exactly. What's important is that the equality check is triggered with the right TaskType (tensorboard), and the postgres intg test also ensures that.
See [Release …

fix: remove extra quotes around IdentifyTask

---

docs/release-notes/8803-ship-logs-hanging.rst
e2e_tests/tests/cluster/test_ship_logs.py
master/static/srv/ship_logs.py

Previously, after the main subprocess exited or was killed, the log shipper would wait without limit for the stdout and stderr readers to finish reading, under the assumption that after the main subprocess died they would be quickly drained.
However, if the main subprocess spun off other, non-terminating child processes, there would remain writers to the stdout and stderr, and this assumption caused a hang.
I named this the "Orphaned Grandchild Problem", and it is concerning because it can cause severe problems for users making fairly innocent mistakes.  It didn't appear earlier because most training scripts that we influence practice structured concurrency.
This fix includes a regression test.

fix: remove possible hang from ship_logs.py [MLG-1565]

---

webui/react/src/components/CreateUserModal.test.tsx
webui/react/src/components/CreateUserModal.tsx
webui/react/src/pages/Admin/UserManagement.tsx

[WEB-1965]
- Check if no initial user role api calls in `user` tab in user management table with RBAC enabled (see [WEB-1965] for more details)
- Check if user information is correct in edit user modal and works as expected
- Check if user can be newly created in create user modal
[WEB-1965]: https://hpe-aiatscale.atlassian.net/browse/WEB-1965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: mitigate many unnecessary api calls in user management table

---

master/internal/api_workspace.go
master/internal/api_workspace_intg_test.go
master/internal/core_checkpoint_intg_test.go
master/internal/db/postgres_checkpoints_intg_test.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_model_intg_test.go
master/internal/db/postgres_test_utils.go
master/pkg/model/model.go

Details in [DET-9982]. Previously, if a user tried to delete a workspace with models (archived or not), they were met with an SQL error. Most of the workspace contents were deleted and the workspace was left in state "Deleting". 
With this change, we first check if a workspace has models on a delete request. If it does, a human-readable error message is returned and the workspace state is unchanged. Nothing in the workspace is deleted.
Added integration tests to confirm functionality. Also tested locally using CLI. 
DET-9982
[DET-9982]: https://hpe-aiatscale.atlassian.net/browse/DET-9982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

fix: check for models before deleting workspace

---

bindings/generate_bindings_ts.py
webui/react/src/ioTypes.ts
webui/react/src/pages/JobQueue/JobQueue.table.tsx
webui/react/src/pages/TaskLogs.tsx
webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
webui/react/src/services/api-ts-sdk/api.ts
webui/react/src/services/decoder.ts

Context: https://hpe-aiatscale.slack.com/archives/C02PV33GSN5/p1706886505065759
TLDR: When web fetches logs from the API we we converting the timestamp from the database to and from a JavaScript Date object. Dates only support millisecond precision, so all significant digits in the microsecond range were truncated. Due to the way we request logs, this led to ~500 microseconds worth of entries not being reported on the web LogViewer. By allowing the timestamp to be passed without a conversion step, this problem should be avoided.
- Go to any trial logs page
- Download the full logs though the Download Logs modal
- Open the Network tab of your browser's inspector
- Scroll up in the LogViewer until you see a GET request to `/api/v1/trials/{trial_id}/logs?limit=100&...`
- Copy the response to …

fix: stop truncating log timestamps to avoid missing logs [WEB-1791]

---

.circleci/real_config.yml
helm/charts/determined/templates/genai/genai-deployment.yaml
helm/charts/determined/templates/genai/genai-persistent-volume-claim.yaml
helm/charts/determined/templates/genai/genai-resource-pool-metadata.yaml
helm/charts/determined/templates/genai/genai-service-account.yaml
helm/charts/determined/templates/genai/genai-service.yaml
helm/charts/determined/templates/master-config.yaml

Older versions of go template do not support short-circuiting with `and`. Our method of trying to safely check for versions wasn't being called correctly. More info: https://stackoverflow.com/questions/55464747/combining-two-if-conditions-into-one

fix: handle helm templating in older go template versions

---

docs/setup-cluster/slurm/slurm-requirements.rst

Update Slurm installation requirements, removing reference to the following distribution: Red Hat® Enterprise Linux (RHEL) or CentOS 7.9

docs: Update slurm install

---

master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/resource_manager_iface.go
master/internal/sproto/task.go

The `SetAllocationMethod` in the ResourceManager interface is not used anywhere, just defined. 
Remove all definitions to this method -- best practice for tech debt, only keep code that we use in the codebase.
N/a, just don't break existing intg or e2e tests.
DET-10149

chore: remove unused SetAllocationName

---

master/internal/rm/agentrm/agent_state.go
master/internal/rm/agentrm/agent_state_test.go

clearAgent state was broken. Add a test and fix it.
intg test

chore: agent state wasn't getting deleted and logged error

---

master/internal/db/postgres_experiments.go
master/internal/db/postgres_experiments_intg_test.go

Was getting some errors in logs related to being unable to update the trial view.
Fix these errors and add a test
Integration test

chore: fix error on terminating experiments on restart

---

master/static/srv/generic-task-entrypoint.sh

Add support for startup hooks in generic task entrypoint, and add `pythonuserbase` to make `pip install`s work.

feat: generic tasks: support startup hooks

---

e2e_tests/tests/cluster/test_master_restart.py
e2e_tests/tests/task/__init__.py
e2e_tests/tests/task/task.py
e2e_tests/tests/task/test_generic_tasks.py
master/internal/api_generic_tasks.go
master/internal/command/command_service.go
master/internal/core.go
master/internal/db/postgres_tasks.go
master/internal/spec_util.go

Restoring Generic Tasks after master restarts
1. Create a Task 
`det task create e2e_tests/tests/fixtures/generic_task/test_config.yaml --context e2e_tests/tests/fixtures/generic_task`
2. Restart master before task completes
3. Wait for task to complete and verify task completion via logs & DB task status
`det task logs <task-id>`
DET-10100

feat: Generic task restore

---

agent/internal/core.go
docs/release-notes/log-level-config.rst
tools/devcluster.yaml

Agent log level can now be set via agent config.
- Change the value of `log.level` (and `log.color`) in the `agent` stage of `.../determined/tools/devcluster.yaml`:
```
- agent:
...
config_file:
log:
level: <input_level>
color: <input_color>    
```
- Run `make devcluster` and verify that the output of `agent configuration` in the build logs includes `"log":{"level":<input_level>, "color":<input_color>}`. 
DET-8884

chore: configure agent log level through config file

---

e2e_tests/tests/cluster/test_job_queue.py
e2e_tests/tests/cluster/test_master_restart.py
e2e_tests/tests/task/task.py
e2e_tests/tests/task/test_generic_tasks.py

Fixing generic task tests that cause the job queue test to fail
e2e tests should pass, specifically `test_job_queue.py` & `test_generic_tasks.py`

fix: job queue test failures

---

webui/react/src/components/WorkspaceDeleteModal.tsx

https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1707939243269789
- Create a workspace with at least one registered model
- Delete the workpspace and check if the toast shows error message from backend API

fix: show error message from backend API for workspace deletion

---

codecov.yml

Backend code coverage has increased to about 43%, so increasing the target to 42% (with the same 3% threshold).
CI passes.

chore: update backend coverage target

---

master/internal/db/postgres_jobs_intg_test.go

Add integration test coverage for postgres_jobs.go - [DET-10133]. 
Run integration tests locally, and via CI. Ensure they pass.
DET-10133
[DET-10133]: https://hpe-aiatscale.atlassian.net/browse/DET-10133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: cover postgres_jobs.go

---

.circleci/real_config.yml
master/static/migrations/20240213090511_testsleep.tx.up.sql

Fixes two issues with performance tests.
1. The feature branch was accidentally using the main database because of a bug.
2. Sometimes the feature branch would fail and not run the db cleanup command.
Run a migration on a perf feature branch and check main database isn't updated

ci: fix performance feature branch using wrong db

---

master/internal/core_checkpoint_intg_test.go
master/pkg/checkpoints/checkpoints.go
master/pkg/checkpoints/s3/s3checkpoints.go

Instead of hardcoding the AWS URL whenever attempting to retrieve a bucket's region, instead leverage the endpoint URL when specified, ensuring that when MinIO is used for checkpoint storage the correct endpoint is used.
- Launch a MinIO server locally
- Create a bucket & an access key 
- Configure devcluster.yaml to use MinIO for checkpoint storage
- Confirm that checkpoints are able to successfully be stored & retrieved via master
Automated testing around the use of MinIO as an S3 checkpoint storage option should be put in place.

fix: correctly source bucket region when using minio

---

webui/react/package-lock.json
webui/react/package.json

This uses the npm build for hew. previously, we used the github build, which required us to grab hew's dependencies and build on install. this should improve build times as the package is built ahead of time.
no testing needed -- build should succeed
`hew` was already a preexisting package in npm, so this is published under the `@hpe.com` scope. Because of that, the package is aliased back to `hew` to make the pr smaller. we can look at switching to `@hpe.com/hew` later.
no ticket

chore: use npm build for hew

---

.circleci/real_config.yml

Our queue orb had a breaking change and we had the version as volatile.
https://github.com/eddiewebb/circleci-queue/blame/main/src/%40orb.yml
Just downgrade for the time being, we can think about upgrading later.
CI passes

ci: fix broken ci due to queue version change

---

master/pkg/schemas/extensions/checks.go
master/pkg/schemas/extensions/compare_properties.go
master/pkg/schemas/extensions/disallow_properties.go
master/pkg/schemas/extensions/eventually.go
master/pkg/schemas/extensions/eventually_required.go
master/pkg/schemas/extensions/optional_ref.go
master/pkg/schemas/extensions/union.go
master/pkg/schemas/zgen_schemas.go
schemas/README.md
schemas/expconf/v0/environment.json
schemas/test_cases/v0/environment.yaml

This turns out to be my regression from Jan 2021 when expconf first landed.
Also, we might as well resurrect the detailed explanations that used to be in extensions.py, and which were still cited by the go files, even though the python code was deleted a long time ago.

fix: allow experiments to configure k8s sidecars

---

master/internal/api_user_intg_test.go
master/internal/core_experiment.go
master/internal/experiment.go
master/internal/restore.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/resource_manager_iface.go
master/internal/spec_util.go
master/internal/spec_util_intg_test.go
master/internal/sproto/agent_resource_manager.go
master/internal/sproto/task.go
master/internal/trial.go

The system can launch multi-container notebooks but accesses only a single container’s instance from the Web UI (as expected). There is no validation on slot requests in config when launching notebooks in CLI or Web UI. Fixed it using ValidateCommandResources instead of ValidateResources in the codebase. Also removed the ValidateResources function.
1. Set max_slots_per_pod in devcluster.yaml as a small number like 1 or 2. 
2. Start a notebook using the CLI, with resources.slot as higher than the max slots per pod. Eg. max_slots_per_pod = 2 and CLI command: `det notebook start --config resources.slots=4`
3. The CLI should show this error:
> Failed to start a new notebook: failed to prepare launch params: validating resources: request unfulfillable, please try requesting less slots
See …

fix: stop allowing multi-container allocations to launch in single agent config[DET-9911]

---

e2e_tests/tests/api_utils.py
harness/determined/cli/_util.py
harness/determined/common/api/__init__.py
harness/determined/common/api/_session.py
harness/determined/common/api/_util.py
harness/determined/common/api/authentication.py
harness/determined/common/experimental/determined.py

Pre-patch, a `Session` that was constructed without a `max_retries` had its `_max_retries` assigned to `None`. If you wanted to use the default retry, you had to explicitly pass it a `Retry` constructed from `api.default_retry`.
If we're claiming that `api.default_retry` is a default, then it should actually be default when constructing Sessions. It's a reasonable default to use, so let's do it.
It's still possible to create a Session with a `_max_retries = None`, now you just have to do that explicitly (`None` is not the default).
In summary:
* Remove `default_retry` from `api.default_retry`, because why does anyone need it
* Make a single default `urllib3` `Retry` object to be used as the default for Sessions where the retry isn't specified
* Give `*Session` constructors the default …

chore: api's default retry now session's default retry

---

e2e_tests/tests/cluster/test_rbac.py

Two commands were missing the "det" in `det rbac ...`

ci: fix e2e tests in ee

---

e2e_tests/tests/api_utils.py

create_test_user was returning a nonsense username in some cases.

ci: more e2e test fixes

---

master/internal/db/database.go
master/internal/db/postgres_experiments.go

chore: delete unused functions [RM-41]
`CheckExperimentExists` and `CheckTrialExists` are not used in the codebase. Rather than bunifying them, we can delete them; they can be added back in if we ever need them
[RM-41]
[RM-41]: https://hpe-aiatscale.atlassian.net/browse/RM-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RM-41]: https://hpe-aiatscale.atlassian.net/browse/RM-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RM-41]: https://hpe-aiatscale.atlassian.net/browse/RM-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: delete unused functions [RM-41]

---

master/internal/checkpoints/postgres_checkpoints_intg_test.go
master/internal/db/postgres_experiments_intg_test.go
master/static/migrations/20240222102938_add-trigger-for-checkpoint-delete.tx.down.sql
master/static/migrations/20240222102938_add-trigger-for-checkpoint-delete.tx.up.sql

Adds a trigger that avoids deleting checkpoints from the database if they aren't marked as `DELETED`, indicating their deletion from storage.
CI passes.
DET-10027

chore: add trigger to abort checkpoint deletion

---

e2e_tests/tests/cluster/test_master_restart.py
e2e_tests/tests/fixtures/no_op/short-default-ckpt.yaml

Fix flake https://app.circleci.com/pipelines/github/determined-ai/determined/51619/workflows/5358e0ec-7fc1-4893-b1d3-5422a43be44a/jobs/2298153
The basic premise of the flake was that the experiment tensorboard uploads would wait on gcs 429 errors making the experiment take longer than 60 seconds
https://circleci.com/api/v1.1/project/github/determined-ai/determined/2293269/output/145/0?file=true&allocation-id=65dcd1db5c29034450ab1342-0-build%2FABCDEFGH
My understanding of why this is happening recently is we changed how retrying works in 
https://github.com/determined-ai/determined/pull/8780
here we would just skip tensorboard uploads that failed due to 429s, but now we retry it and block on it
The fix is just to run a shorter experiment since this isn't what we are testing for this test. …

test: fix tensorboard reattach k8s flake [RM-39]

---

.circleci/real_config.yml
Makefile
docs/setup-cluster/k8s/k8s-dev-guide.rst
go.mod
master/get-deps.sh

Upgrades Go from 1.21 to 1.22.
CI passes

chore: upgrade Go from 1.21 -> 1.22

---

master/internal/rm/kubernetesrm/spec.go

Simply prints out the podspec before the task is run. The message occurs at the start of the task and doesn't interfere with the task logs.
Manually verify: run a task in kubernetes and check that the logs include a string of the podspec.

feat: log podspec [DET-9861]

---

e2e_tests/tests/cluster/test_workspace_org.py

We should not check twice that the REST API 404ed on a missing workspace. Trust our exception type.

test: remove redundant (and brittle) assertion

---

.circleci/real_config.yml
e2e_tests/tests/requirements.txt

INFRAENG-363 is exploring test metrics for Determined-AI. We have a running trial for data dog right now. 
Test results flow to DataDog for this branch - Pass
Followed setup instruction but set ddtrace in the requirements rather than doing an ad-hoc pip install. 
https://app.datadoghq.com/ci/setup/test?framework=pytest&language=python
INFRAENG-363

test:  upload test results to datadog

---

e2e_tests/tests/experiment/test_metrics.py

Fix test flake seen on main
https://app.circleci.com/pipelines/github/determined-ai/determined/51614/workflows/903b01d9-94ec-4bff-99d0-7b91ab67ba68/jobs/2297652
e2e_cpu passes

chore: fix mp.pool test_streaming_metrics_api

---

master/internal/stream/DESIGN.md
master/internal/stream/projects.go
master/internal/stream/publisher.go
master/internal/stream/supervisor.go

- add DESIGN doc back into code
- fix some typos in comments
- rely on defer in the context cancelation function
- eliminate unnecessary/unhelpful wrapper function
- use time.Ticker instead of time.After

chore: minor tweaks as modev takes over streaming updates

---

master/internal/rm/kubernetesrm/pod_test.go

Fix failing test on main
https://app.circleci.com/pipelines/github/determined-ai/determined/51712/workflows/bdcbdfb7-e33a-4526-98d1-a261538687bd/jobs/2304253
Caused by
https://github.com/determined-ai/determined/pull/8899
Intg passes

test: fix failing Go TestResourceCreationFailed test

---

harness/determined/common/api/authentication.py
harness/tests/common/api/test_authentication.py

Since we are now stricter about what is a valid master_url (rejecting some silly things like usernames or fragments that make no sense in the url), we must take special care when reading auth.json written by old versions of our code.
Without this fix, users who mistakenly logged in in the past with
DET_USER=http://user@mymaster
would have a broken CLI because the shim code would puke every time it tried to upgrade auth.json from v1 to v2.

fix: canonicalize master urls shim code

---

master/internal/rm/kubernetesrm/pod_test.go
master/internal/rm/kubernetesrm/spec.go

Reverts https://github.com/determined-ai/determined/pull/8899 due to a security issue.

chore: revert pod spec and test changes

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/api_project.go
master/internal/api_workspace.go
master/internal/core_experiment.go
master/internal/db/database.go
master/internal/db/postgres_experiments.go
master/internal/db/postgres_experiments_intg_test.go
master/internal/db/postgres_test_utils.go
master/internal/project/postgres_project.go
master/internal/project/postgres_project_intg_test.go
master/internal/webhooks/postgres_webhook.go
master/internal/workspace/postgres_workspace.go

[RM-48] chore: cover and bunify project functions in postgres_experiments.go
ensure all unit/integration tests pass; there should be no change in behavior
`ProjectExperiments` is called when deleting a workspace. Create a workspace, add a project, and an experiment. Then, delete it. It completes without error.
Repeat above with deleting a project from a workspace.
RM-48
[RM-48]: https://hpe-aiatscale.atlassian.net/browse/RM-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: cover and bunify project functions in postgres_experiments.go

---

docs/release-notes/8851-force-default-passwords.rst

Adds release note for #8851 force default user passwords for all det deploy and CI clusters

tc: Add release note 8851

---

harness/determined/cli/sso.py

In EE, the CLI returns an error when listing auth providers but auth is not being used. This is because we are always expecting a list, but we receive null in this case, hence the error `'NoneType' has no len()`. This fix updates the CLI to catch null values and not fail the length check.
Run a devcluster on EE with the `oidc` config field populated with something like:
```
oidc:
authentication_claim: email
auto_provision_users: false
client_id: ''
client_secret: ''
enabled: false
idp_recipient_url: ''
idp_sso_url: ''
provider: ''
scim_authentication_attribute: userName
```
Run the cli command `det auth list-providers` - the CLI should return `No SSO providers found.`

fix: cli fails when listing providers [DET-10127]

---

go.mod

on macOS/darwin, go doesn't run after updating to `1.22`. 
```
go: downloading go1.22 (darwin/amd64)
go: download go1.22 for darwin/amd64: toolchain not available
```
per [this github issue](https://github.com/golang/go/issues/65568), changing to `1.22.0` fixes the issue.

chore: change go 1.22 to 1.22.0 in go.mod

---

harness/determined/deploy/gcp/cli.py

For some reason `down` calls `dry_run`, which checks quotas. The output of dry_run isn't relevant to a delete, and we don't need to check quotas when destroying a cluster.
Tested when written, don't worry about it for release party. 
What I did: `det deploy gcp down` while a GCP project is at capacity. It should work.

fix: det deploy gcp down shouldn't check quotas

---

harness/determined/constants.py

`HOROVOD_GLOO_RENDEZVOUS_PORT` is unused.
#2771 was the PR that removed its only use. Once, it was [passed directly to horovod](https://github.com/rb-determined-ai/determined/blob/b531bda5e8e31c1c20e2fa4602d9929b97d67194/harness/determined/layers/_worker_process.py#L177-L182).

chore: remove unused constant

---

.circleci/real_config.yml

https://circleci.com/developer/images?imageType=machine

build: bump cpu image to latest ubuntu 2004

---

harness/determined/deploy/gcp/terraform/modules/compute/main.tf

I moved this as a style thing last minute before landing this change and missed that we `>>` into the master.yml.context in a way that breaks this. Also the yaml indentation ended up wrong. 
oops

fix: malformed config with gcp up with --initial-user-password

---

.circleci/real_config.yml
CONTRIBUTING.md
docs/model-dev-guide/api-guides/apis-howto/_index.rst
docs/tools/cli/cli-ug.rst
e2e_tests/mypy.ini
e2e_tests/tests/command/test_run.py
e2e_tests/tests/config.py
e2e_tests/tests/model_hub/test_mmdetection.py
harness/determined/cli/dev.py
harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/mypy.ini
model_hub/mypy.ini
schemas/mypy.ini
tools/mypy.ini
tools/scripts/bumpenvs.yaml

Python 3.7 is EOL.
* Some docs that referred to 3.7 now refer to 3.8
* Training API "how to" doc no longer mentions any 3.7 docker images
* `CONTRIBUTING.md` no longer says to upgrade pip when installing determined
* `CONTRIBUTING.md` has revised text about Python requirements
* mypy tests against 3.8.
* Features new to 3.8 can be used without suppressing type checking or conditional imports. These changes have been made.
* No longer run `test-cli` in CircleCI against Python 3.7.
* There are no wheels for TF1 using Python 3.8. Removing 3.7 support means TF1 cannot be used. In previous commits, we removed support of TF1. We also clean up those references here. In particular:
- `e2e_tests/tests/command/test_run:test_k8_init_containers` and …

chore: remove support for Python 3.7; prefer 3.8

---

e2e_tests/tests/api_utils.py
e2e_tests/tests/deploy/test_local.py
e2e_tests/tests/experiment/experiment.py
e2e_tests/tests/nightly/compute_stats.py

Fixes `test-det-deploy-local` tests that were broken by a change in caching strategy in #8872.
Changes to test_local.py:
* changed interface to functions bringing up and down resources to be both more general and more explicit
* resources in the tests themselves are brought up and down using a context manager. This ensures they clean up after themselves even when they fail.
* deleted a couple functions that had been needed for the previously-deleted `test-stress`.
Changes to api_utils.py:
* `is_hpc` operates directly on a passed session.
Changes to experiment.py & compute-stats.py
* The session for a run experiment is passed to `api_utils.is_hpc` so that this function can query the now-live master to determine whether that master is running an HPC scheduler. Previous calls to `is_hpc` …

test: refactor usage within test_local

---

e2e_tests/tests/streaming/test_client.py

Add e2e test for streaming updates python client
e2e tests pass
[MD-282](https://hpe-aiatscale.atlassian.net/browse/MD-282)
[MD-282]: https://hpe-aiatscale.atlassian.net/browse/MD-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Add e2e test for streaming updates python client

---

master/internal/rm/multirm/multirm.go
master/internal/rm/multirm/multirm_intg_test.go

require error.Contains for multiRM unit test that returns a list of resource managers. This way, we'll avoid failing the test if the list is a different order.
Pass test

chore: fix multirm unit test flake

---

agent/Makefile
master/Makefile

Set ```CGO_ENABLED=0``` when building Determined so we don't need to depend on GLIBC.
https://hpe-aiatscale.slack.com/archives/C058AC320M9/p1709568451569729
Full e2e suite passes

chore: set CGO_ENABLED=0

---

master/internal/rm/agentrm/agent.go
master/internal/rm/agentrm/agent_test.go

AgentState is only set on the agent master-side whenever it is "started", which is when we've made it through all the initialization messages. But an agent can crash while it is starting, and then this access into AgentState causes a NPE, which probably ends up being a convincing red herring when debugging.
I'll follow up to add tests in a bit.
Yep.
RM-53

fix: don't access agentState when it may be nil

---

.circleci/scripts/wait_for_perf_migration_upload_results.py

We broke some Determined code we are using. This updates this to use the new session stuff.
Perf test passes

ci: update performance test script for breaking Determined change

---

.circleci/devcluster/double-reattach.devcluster.yaml
docs/release-notes/reattach-stopping.rst
e2e_tests/tests/cluster/test_master_restart.py
master/internal/config/config.go
master/internal/db/postgres_experiments.go
master/internal/experiment.go
master/internal/restore.go
master/internal/task/allocation_service.go
master/internal/task/allocation_service_test.go
master/internal/task/preemptible/preemptible.go
master/internal/trial.go

Make restore logic restore STOPPING states instead of just updating the states in the db and ignore running resources.
Covered by e2e tests

fix: stopping states are not handled in restore properly [RM-69]

---

master/internal/config/resource_config.go
master/internal/config/resource_config_test.go

Require unique resource pool names in config.
unit tests

chore: multirm unique resource pool config changes [RM-74]

---

master/internal/config/config.go
master/internal/config/config_test.go
master/internal/experiment_job_service.go

Fix `ReadPreemptionStatus` bug where if resource pool name was passed in; if nil, it causes a nil pointer dereference.
Pass `TestMultiRMPreemptionAndPriority` (see. new test case) and included e2e tests.
RM-77

fix: nil deref in ReadPreemptionStatus

---

webui/react/src/hooks/useAuthCheck.ts

There is bug in GenAI currently where a user gets stuck in an infinite redirect loop, this fixes the issue. 
You can see the bug in action below:
https://github.com/determined-ai/determined/assets/103522725/7375fff4-bdc6-4c78-a6f0-5717080cf21f
The ultimate cause of the bug is that if you look at the logic in the sign in page we:
1. Check if the user `isAuthenticated"
2. Check if there is a redirect, if there is we redirect the user. 
However the issue is that in (1) the `isAuthenticated` can be set to true without the user actually being a valid and authenticated user. This causes an infinite login bug in GenAI since we use the `MLDE` login page for authentication also. The reason that this is not an issue in MLDE is because after sign-in:
1. The user is redirected to the `dashboard` page …

fix: Check auth validity before setting isAuthenticated

---

CONTRIBUTING.md

From #2892 , `make -C tools run` is no longer a supported command. Users should run `devcluster [-c CONFIG_PATH]` or `make devcluster` instead.
N/A

chore: amend contributing doc to point to correct make rule

---

master/internal/core.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/agentrm/resource_managers_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go

Remove panics from resource manager initialization and replace them with error messages so that it is easier to trace back and handle errors.
CI passes.
DET-9975

chore: remove panics from rm initialization

---

master/internal/api_command.go
master/internal/api_experiment.go
master/internal/api_generic_tasks.go
master/internal/api_job.go
master/internal/api_resourcepool.go
master/internal/api_resourcepool_intg_test.go
master/internal/api_user_intg_test.go
master/internal/checkpoint_gc.go
master/internal/checkpoint_gc_test.go
master/internal/core_experiment.go
master/internal/experiment.go
master/internal/job/jobservice/jobservice.go
master/internal/restore.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/multirm/multirm.go
master/internal/rm/multirm/multirm_intg_test.go
master/internal/rm/resource_manager_iface.go
master/internal/spec_util.go
master/internal/spec_util_intg_test.go
master/internal/sproto/jobs.go

Introduce a new type `ResourcePoolName` string, that replaces resource pool name string input/output in RM methods & provides more description where used.
Pass existing tests
I couldn't substitute ResourcePoolName type into sproto messages because of an import cycle  -- ideally, as we move away from using sproto messages and simply passing in the variables, we can use ResourcePoolName wherever we pass in a string resource pool name.
DET-76

chore: add type ResourcePoolName string

---

.circleci/real_config.yml
docs/release-notes/ngc-images.rst
docs/setup-cluster/deploy-cluster/slurm/singularity.rst
docs/setup-cluster/slurm/singularity.rst
docs/setup-cluster/slurm/slurm-requirements.rst
e2e_tests/tests/config.py
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/lore.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml
harness/determined/deploy/gcp/constants.py
harness/tests/experiment/fixtures/ancient-checkpoints/0.17.6-keras/metadata.json
harness/tests/experiment/fixtures/ancient-checkpoints/0.17.6-pytorch/metadata.json
harness/tests/fixtures/checkpoint.json
helm/charts/determined/values.yaml
master/internal/config/provconfig/aws_config.go
master/internal/config/provconfig/gcp_config.go
master/pkg/schemas/expconf/const.go
model_hub/Makefile
schemas/test_cases/v0/experiment.yaml
tools/scripts/bumpenvs.yaml
tools/scripts/update-bumpenvs-yaml.py
webui/react/src/fixtures/responses/experiment-details/non-scalar-metrics-4078.json
webui/react/src/fixtures/responses/experiment-details/set-a.json
webui/react/src/fixtures/responses/trial-details/old-trial-config-noop-adaptive.json

Bumpenvs for NGC+ Images (and tf2.8 removal)
https://github.com/determined-ai/environments/pull/235
CI doesn't fail
MD-270

chore: Bumpenvs for NGC+ images

---

e2e_tests/tests/cluster/test_rbac.py
harness/determined/cli/rbac.py

When a user is assigned to roles that have overlapping permissions, `det rbac my-permissions` lists each permission within a given scope as many times as the number of roles assigned to the user within that scope containing that permission. 
This leads to a lot of duplicate permissions being listed within a given scope when a user runs `det rbac my-permissions`. We fix that here!
It's also worth noting that this change does not affect the result of running `det rbac my-permissions --json`.
CI passes.
DET-10172

fix: remove duplicate permissions in rbac CLI output

---

docs/setup-cluster/gcp/_index.rst

Community request: clarify that the instructions for Deploying on GCP are not used to spin up a cluster via GKE.

docs: Update Deploy on GCP

---

examples/tutorials/core_api/0_start.yaml
master/.golangci.yml
master/internal/elastic/elastic.go
master/internal/rm/kubernetesrm/mock_client_test.go
master/internal/webhooks/api_webhook.go
master/internal/webhooks/shipper.go

Ban use of `http.Transport` and `http.Client` in the codebase. Instead, use `cleanhttp` library.
Pass existing tests.
RM-85

chore: ban http.Transport & http.Client; add cleanhttp

---

.circleci/real_config.yml

INFRAENG-487
Circle-ci lets us re-run failed tests individually if we use the circle ci runner instead of splitting and running separately. 
https://circleci.com/docs/rerun-failed-tests/
This makes it faster and cheaper to re-run failures on circle-ci since individual tests can be re-run instead of whole jobs.
pipeline passed and all the E2E tests took the same amount of time. Spot checking most of them, they all ran the same number of tests as main.
https://app.circleci.com/pipelines/github/determined-ai/determined/52143/workflows/311b97d9-4e74-4c18-90c2-f03abd7f3cf6/jobs/2331410
We'll have to be careful of long-running nightly e2e. I'm running a sample to insure they work. https://app.circleci.com/pipelines/github/determined-ai/determined/52143/workflows/2e6ceb8a-4d72-4ae3-9f3c-73e85358f …

ci: Djanicek/infraeng 487/circle test runner

---

webui/react/src/components/ResourcePoolCard.tsx

Display resource manager names (only if there are multiple) for K8s resource pool cards.
For a cluster of K8s, configure multiple resource managers, the resource pool cards should display the resource manager names. 

feat: Add multi RM name to K8s

---

webui/react/src/components/ProjectDeleteModal.tsx

[Slack Thread](https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1710436294375949)
containing special regex characters in project name causes page crash
- Rename project with that includes special characters for regex such as `?`, `+` etc
- Check if project list page loads without page crash
- Check if `Delete project` modal works and project can be removed

fix: escape regex in `ProjectDeleteModal`

---

webui/react/vite.config.mts

This PR updates the code reports generated by the frontend unit tests to only report code in the src folder, and omits vendor code and generated code from the reports. This is so the codecoverage report will be more accurate to what we actually care about.
no testing needed

chore: limit code coverage report to files in src; omit generated files

---

docs/manage/security/rbac.rst
docs/release-notes/editor-restricted-role.rst

Add release note for the EditorRestricted role and add more info to RBAC docs to clearly distinguish `Editor` from `EditorRestricted`.
CI passes.
DET-10173

docs: add EditorRestricted role release note

---

.circleci/real_config.yml

Instead of installing determined from PyPI with pip, test-perf now pulls its determined from GitHub. This is to make it possible to coordinate changes between the python files that run as a part of the test and the libraries within determined that those files call.

ci: test-perf uses determined version from github

---

docs/reference/deploy/master-config-reference.rst
docs/release-notes/multirm-for-k8s.rst

Update configuration docs & add a release note for multirm.
N/A
RM-78

docs: add documentation for multirm

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/templates/master-deployment.yaml

See https://github.com/determined-ai/determined/pull/9015

chore: helm for multirm kubeconfig_path

---

webui/react/playwright.config.ts
webui/react/src/e2e/README.md
webui/react/vite.config.mts

Quick config changes primarily to make running locally easier.
some of the specific changes that may need justification:
- Using a proxy for `npm run preview` eliminates the need for the CORS workaround and uses the right http server.
- retries is down to one in CI. If it doesn't pass after one retry, in my experience, the second retry is normally a waste of time.
- edge now works locally but needs an install on CI. Since edge is just chromium under the hood I turned that off for now.
ran locally with readme instructions and in pipeline
infeng-448

test: playwright config and browser usability

---

.circleci/real_config.yml
docs/deploy/Makefile
docs/deploy/cdn.tf
docs/deploy/main.tf
docs/deploy/s3.tf

Add the owner and gh_team tags the new tagging policy requires Also add the long_running tag to the long-running instances
See what happens in CI; react accordingly.
The terraform image used for doc publishing is switched from light to latest because the light tag is no longer maintained as of over a year ago.
https://github.com/hashicorp/terraform/issues/33139
I've already imported, planned, and reapplied the updated Terraform files.  So this should just work cleanly without needing to recreate objects, etc.
Supersedes #8969

ci: tag CI-deployed resources

---

master/internal/api_master_intg_test.go
master/internal/rm/agentrm/agent_test.go
master/internal/storage/service_intg_test.go
master/internal/telemetry/telemetry_test.go

The definition of `db.ResolveTestPostgres()` is in a file marked with `// +build integration` and therefore files that reference it fail to compile when that file is ignored (e.g. when running `make test`).
The agent test does not directly access the DB, but it ends up spinning up some goroutine somewhere that attempts to use an uninitialized `Bun()` and panics (presumably, because there's no DB available to satisfy the initialization of The One Bun in time). When it's run as part of `make test-intg` instead, it passes.
These tests would always run with integration tests anyway, all this changes is that they're ignored if you're only running "unit tests" or some select subset of tests that need to ignore these files in order to compile correctly.
Automated tests still pass
See [Release …

chore: mark db-dependent tests as needing to run in integration

---

master/internal/rm/agentrm/agent.go
master/internal/rm/agentrm/agent_model.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/agentrm/agent_state.go
master/internal/rm/agentrm/agent_state_test.go
master/internal/rm/agentrm/agents.go
master/internal/rm/agentrm/fair_share.go
master/internal/rm/agentrm/fitting.go
master/internal/rm/agentrm/fitting_test.go
master/internal/rm/agentrm/priority.go
master/internal/rm/agentrm/priority_test.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/agentrm/resource_pool_test.go
master/internal/rm/agentrm/resources.go
master/internal/rm/agentrm/round_robin.go
master/internal/rm/agentrm/scheduler_test.go
master/internal/rm/agentrm/summaries.go

[DET-9976]
Removes the `agentID` type in favor of using `aproto.ID` throughout package agentrm.
N/A
A little surprising that there's a net gain of SLOC, but it's because of all the new `import...aproto` lines.
Also, this refactor touches a ton of untested code, but I promise it's purely a static change >.<
[DET-9976]: https://hpe-aiatscale.atlassian.net/browse/DET-9976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: remove agentID type from agentrm

---

e2e_tests/tests/cluster/test_model_registry.py
harness/determined/cli/model.py

[DET-9632]
Essentially identical to a convenience CLI command that was part of a PR #7175 last year as it was useful for testing at the time. It spun off into a separate ticket due to being out of scope, but it's probably still convenient to (re)include.
https://github.com/determined-ai/determined/commit/8b0ec750a4c2dec1156d33feb97c4b7765788e42#diff-27dd013a7937c3e0392be1d4090837fec1f0fb87ef0037cac6516e447360ee40R138
modified e2e test which exercises the new command should pass
[DET-9632]: https://hpe-aiatscale.atlassian.net/browse/DET-9632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add command det model delete

---

docs/manage/security/rbac.rst

fix: docs lint

---

webui/react/src/components/JupyterLabModal.test.tsx
webui/react/src/components/JupyterLabModal.tsx
webui/react/src/stores/workspaces.tsx

Filter resource pools by selected workspace when creating notebook.
With and without rbac enabled, open the modal for creating Jupyter notebook.
Before selecting the workspace, the resource pool dropdown is disabled.
After selecting the workspace, verify that the resource pool dropdown only contains resource pools that are bound to that workspace (including shared resource pools)
[MD-284](https://hpe-aiatscale.atlassian.net/browse/MD-284)
[MD-284]: https://hpe-aiatscale.atlassian.net/browse/MD-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Use filtered resource pools when creating notebook

---

webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

Looks like `searchExperiments` was not being called because of this conditional: 
`if (isLoadingSettings  ||  Loadable.isNotLoaded(loadableFormset)) return;`. 
Occurred on any project details page without experiments, but also *did not* occur when first visiting a page that did have experiments and loaded correctly, then navigating to a page without experiments.
Seems to be addressed by making sure `formStore.init()` is always called, even without data from existing `filterset`.
1. Visit the project details page for a project with no experiments.
2. Refresh the page.
3. Make sure the page displays the "No Experiments" message instead of a loading state.

fix: loading experiments without filterset

---

harness/determined/deploy/aws/injector/master.yaml.tmpl
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/lore.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml

A follow-up PR to: https://github.com/determined-ai/determined/pull/8492
Removing the outdated /lore redirect (replaced by /gen redirect in the previous pr). It was kept around as GenAI CI wasn't caught up.
(1) Tested that the cluster can be launched with the change
(2) tested that the master.yaml indeed contains the update (only /genai redirect is seen)
(3) tested that /genai redirect still works

chore: Remove /lore redirect from deployment template

---

webui/react/src/components/NavigationSideBar.tsx
webui/react/src/components/ThemeToggle.tsx
webui/react/src/components/UserSettings.tsx

Changing some surface level text to raise clarity on the sidebar dropdown
[INFENG-547]
[INFENG-547]: https://hpe-aiatscale.atlassian.net/browse/INFENG-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: webui nav sidebar dropdown text changes

---

harness/determined/pytorch/_pytorch_trial.py

Pytorch Datasets (`torch.utils.data.Dataset`) aren't guaranteed to have a `__len__` implemented (Datasets can be either "map-style" or "iterable-style". When map-style, they must implement a `__len__`, and when iterable-style they _may_). The `__len__` on a Pytorch DataLoader may pass the call through to its Dataset.
A `det.pytorch.PyTorchTrial` is typically constructed from a `det.pytorch.DataLoader`. `det.pytorch.DataLoader` cannot, itself, front an iterable-style Pytorch Dataset. It is, however, possible to construct a `det.pytorch.PyTorchTrial` with an unwrapped `torch.utils.data.Dataset` if `context.experimental.disable_dataset_reproducibility_checks()` is called in the `PyTorchTrial`'s `__init__`.
Before this patch, during a `PyTorchTrialContext.run` we called `len` on the trial's …

fix: remove calls to Pytorch Dataset len

---

harness/determined/common/experimental/determined.py
harness/determined/experimental/client.py

Follow up for https://github.com/determined-ai/determined/pull/8927
Since parent id is mostly used internally, and can be confusing for end user when exposed, we decide to remove it from SDK function `create_experiment`

fix: remove parent_id from create_experiment

---

master/internal/api_logretention_intg_test.go

Test-go was failing on main because of TestScheduleRetention. Split it into 3 parts to avoid timing out

fix: fix TestScheduleRetention

---

master/internal/api_agents.go

(cherry picked from commit 370ef81d2eecf8971a49d6a77c4c84b4cd2c51e9)
safety net just in case one of the RM's doesn't include the summaries
https://github.com/determined-ai/determined-ee/pull/1227

chore: agent level check if slotstats are computed at rm level

---

master/internal/rm/multirm/multirm.go

Change the multirm logs from info level to debug level
Start a new experiment, on a multiRM cluster & define it to run on a resource pool 'XYZ' (or whatever other name). Then, after starting the experiment, check that your logs contain
`DEBU[2024-04-01T13:28:57-04:00] RM defined as <the-rm-name-where-the-pool-lives>, <the-pool-name>              component=resource-router`
If you test with a pool/pool name that doesn't exist, then you should see the default RM and pool name being used, with the message at the debug level.
If you test with a blank pool name (so _don't_ define a resource pool in your experiment yaml), you should see "RM undefined, routing to default resource manager" at the debug level.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-no …

chore: change log level for multirm messages [RM-125]

---

.circleci/scripts/wait_for_perf_migration_upload_results.py

Two problems combined into one:
1. the session that `_wait_for_master` used had the system's default retry policy (which takes about 15 seconds before it gives up)
2. `_wait_for_master` reported every 60 iterations through its loop (which itself was limited by the number of iterations) rather than every 60 seconds. This meant that it only actually reported once every 16 minutes.
CircleCI had been killing workflows that didn't print text after 10 minutes. So when migrations took more than 10 minutes, the whole test would fail.
This PR fixes both of problems (1) and (2).

ci: more printing about state of master

---

.github/CODEOWNERS

* Comment had stated that `harness/determined/deploy` was unknowned (though it actually had been owned by MD). Made it owned by RM
* Comment had stated that `harness/determined/cli` was unknowned. Removed the comment.

chore: CODEOWNERS deploy owned by RM not MD

---

webui/react/src/pages/ExperimentDetails/ExperimentVisualization.tsx

https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1711644073872369
- Check if loading indicator is not visible in queued state in single and multi trials experiments
- Check if no regressions with other states such as running, stop etc

fix: stop showing loading indicator in `queued` state

---

tools/scripts/gen-attributions.py

license is a builtin constant (added by the `site` module). Let's not shadow it.
No change in anything user-facing. No release testing necessary.

fix: no more shadowing "license"

---

master/internal/core.go
master/internal/rm/multirm/multirm.go
master/internal/rm/multirm/multirm_intg_test.go

Fix index bug in GetJobQueueStatsRequest by executing the proper RM call on the correct RMs belonging to the list of resource pools given.
Also, add `os.Run()` to the multirm test file -- so now the tests run! Change the mock RM return values from mock.Anything to the relevant complex type.
Without the changes to the GetJobQueueStatsRequest, its test should fail the `empty_request` case as follows:
```
--- FAIL: TestGetJobQueueStatsRequest (0.00s)
--- FAIL: TestGetJobQueueStatsRequest/empty_request (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
```
With these changes, all should pass! …

fix: job queue panic for multirm [RM-123]

---

docs/reference/deploy/master-config-reference.rst
docs/release-notes/multirm-for-k8s.rst

Add multiRM docs, and mention that notebook/proxied workload support is coming, but not available yet.
At the moment, this PR is compared against https://github.com/determined-ai/determined/pull/9053, just because we're going to merge the PR that reverts the docs first

docs: update multiRM docs

---

tools/scripts/gen-attributions.py

1. A couple missed instances of `license` were missed. Now they're `lic`.
2. `type` was used. Didn't want to change the interface, so this just got a `noqa`.

chore: unshadow more builtins

---

master/internal/rm/multirm/multirm.go

Accidentally overwrote this in [ RM-123, 
](https://github.com/determined-ai/determined/pull/9079), but the log should be at debug level.
N/A

chore: change RM log message back to Debug level

---

.github/workflows/semantic.yml

INFENG-600
Removed the validation on single commits. It was a legacy feature anyway.
https://github.com/amannn/action-semantic-pull-request?tab=readme-ov-file#legacy-configuration-for-validating-single-commits
The config is on pull_request_target, so we can't test this change until it hits main.

ci: INFENG-600 remove single commit legacy validation

---

helm/charts/determined/templates/genai/genai-deployment.yaml

When using genai on k8s clusters that use different namespaces for their resources pools, the existing services could not be resolved without specifying the k8s namespace that it was created in.
Should not need manual testing from release party.

fix: make sure that the genai helm chart services work across namespaces

---

docs/release-notes/tag-to-dynamic-agents.rst
docs/setup-cluster/aws/install-on-aws.rst
harness/determined/deploy/aws/deployment_types/base.py
harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/lore.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml

```det deploy aws``` will apply the ```add_tags``` to dynamic agents.
Launch a cluster
```
det deploy aws up --cluster-id clusteridtest --keypair testkeypair \
--deployment-type simple \
--det-version f78b9aa68e3428a75be043de16e75dc863bc0229 \
--add-tag owner=nickblaskey \
--add-tag gh_team=rm_team
```
run an job so a dynamic agent is launched, then check that it is filled in

feat: det deploy aws adds tags to dynamic agents [RM-140]

---

.circleci/real_config.yml

Create nightly cleanup job that removes all namespaces (and therefore all k8s objects within them) from the CircleCI GKE cluster and deletes all buckets created by CI jobs used for testing with that cluster.
Successful run with resources to delete: https://app.circleci.com/pipelines/github/determined-ai/determined/52752/workflows/ef46cdef-ca8d-4345-a1e7-49e15d7473aa/jobs/2370042
Successful run with no resources to delete: https://app.circleci.com/pipelines/github/determined-ai/determined/52764/workflows/0a6c0b3f-8e4b-427e-ba92-d6f7b5e930a6/jobs/2370726
CI passes.
DET-10117

chore: add nightly gke cluster cleanup job

---

master/internal/rm/agentrm/agent_resource_manager_intg_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go
master/internal/rm/multirm/multirm_intg_test.go

Match RM behavior for GetJobQueueStats in the kubernetes implementation of the interface to the agent implementation. Add a clause to filter _in_ resource pools in the included stats.
See new tests for the agentRM & k8sRM -- without my changes to the code these tests would pass only for agent RM & fail in k8s.
RM-136

fix: match GetJobQueueStats behavior in k8s RM to agent RM [RM-136]

---

.circleci/real_config.yml
helm/charts/determined/values.yaml

Fix for e2e gke tests and don't run shared cluster e2e test during nightly (or it'll interfere with the cleanup job)
CI passes.

fix: helm value for gke tests

---

.github/CODEOWNERS

https://github.com/orgs/determined-ai/teams/test/members
add this team to codeowners

chore: add test to CODEOWNERS [INFENG-605]

---

.github/pull_request_template.md

INFENG-600
Rewrote some of the PR template; I'm very open to suggestions.

chore: update github PR template [INFENG-600]

---

docs/reference/python-sdk/example-workflows.rst

- Add docs on how to replicate `det e create -f` with the python sdk (https://hpe-aiatscale.atlassian.net/browse/MD-255?focusedCommentId=29068)
- Reformat the SDK examples page to have normal sections instead of tabs, as now we have a few of them
N/A

docs: add a python sdk example for log following.

---

docs/release-notes/experiment-deadlock.rst
master/.golangci.yml
master/internal/api_project_intg_test.go
master/internal/experiment_job_service.go
master/internal/experiment_job_service_test.go

RM-152
Unlock the internal experiment mutex in ResourcePool()
I added a unit test that checks that the function returns smoothly. Without my change, the test would timeout anyway/fail.
[RM-152]: https://hpe-aiatscale.atlassian.net/browse/RM-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: unlock mutex for experiment ResourcePool() [RM-152]

---

master/internal/api_logretention_intg_test.go

This test has been quite flaky and times out quite often. Steps taken to increase reliability:
- Reduced the time incremented by fake clock in each test
- Moved time to just after midnight instead of midnight on the dot to avoid syncronization issues
- Reduced the default log retention days.
Ran each test locally a 100 times. The average time of each tests are:
- TestScheduleRetentionNoConfig: 0.71s
- TestScheduleRetention100Days: 1.79s
- TestScheduleRetentionNeverExpire: 5.07s

fix: reduce time and increase reliability of tests

---

harness/determined/deploy/gcp/cli.py

det deploy gcp down should not fail because of det-version missing
RM-153

fix: det gcp down doesn't have a det_version argument

---

webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts

-  Reset user settings in settings drawer
-  select few experiments and open compare view
-  click around for a few seconds and make sure you're able to interact with table UI

fix: prevent table breaking on null columnWidths [ET-161]

---

tools/devcluster.yaml
tools/k8s/devcluster.yaml

docker volumes are more resilient to user system configuration. users should be less likely to run into os level issues with this approach

chore: set the default data vol to be a docker volume instead of a mount

---

harness/setup.py

Updates determined pip package metadata in PyPi.
* adds content of README.md
* updates e-mail address
* updates Python to version 3.8+
[DET-10187]
Unsure how to test without deploying a new version. 
[DET-10187]: https://hpe-aiatscale.atlassian.net/browse/DET-10187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update PyPi metadata

---

docs/_shared/basic-installation.txt
docs/_shared/password-note.txt
docs/_shared/password-steps-helm.txt
docs/_shared/password-steps-webui.txt
docs/get-started/webui-qs.rst
docs/manage/security/rbac.rst
docs/manage/security/scim.rst
docs/manage/users.rst
docs/model-dev-guide/api-guides/apis-howto/api-core-ug.rst
docs/setup-cluster/checklists/_index.rst
docs/setup-cluster/k8s/install-on-kubernetes.rst
docs/setup-cluster/on-prem/options/wsl.rst
docs/tutorials/pachyderm-cat-dog.rst
docs/tutorials/quickstart-mdldev.rst

Replaces #9101 because it is partly out of scope. Intended to be merged with #9113

docs: Describe pwds default accounts

---

helm/charts/determined/values.yaml

Reverts helm values doc change for multirm.

docs: revert helm values change for multirm

---

webui/react/vite.config.mts

`npm run test` in `webui/react` caused these error because e2e tests were not ignored in Vitest.
- Test CI should pass without the above errors

test: ignore e2e test cases in vitest

---

e2e_tests/tests/cluster/test_logging.py

intentional failures https://app.circleci.com/pipelines/github/determined-ai/determined/53837/workflows/64c6bb5a-d27e-44ec-9846-58f58754474e

test: fix logging test typehint syntax error

---

webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

ET-161
this is an alternate fix for a bug where updating the compare width would cause the experiment list settings to be in an invalid state. It seems like the issue was due to settings widths not containing pinned columns, so we try to update the column widths along with the columns when they update.
* Reset user settings
* visit an experiment list page
* open compare mode
* click and drag the divider
* the pinned columns in the left panel should shrink and grow with the divider position

fix: ensure all columns have widths

---

e2e_tests/tests/cluster/test_users.py
harness/determined/cli/user.py
harness/determined/common/api/errors.py
harness/tests/cli/test_user.py

When a user attempts to log in with an incorrect username and/or password, CLI display a misleading error message:
```
Failed to log in user: Unauthenticated: Please use 'det user login <username>' for password login, or for Enterprise users logging in with an SSO provider, use 'det auth login --provider=<provider>'.
```
```
det user logout
```
Login with incorrect password and/or username
```
det user login
```
Expect "Failed to log in user: Invalid username/password combination. Please try again." as the output.
MD-277

fix: cli gives misleading error message when logging in with a bad password [MD-277]

---

tools/k8s/README.md
tools/k8s/multicluster.yaml

RM-164
Add a devcluster file to run Determined across multiple Kubernetes clusters locally.
Needs no testing.

chore: add a devcluster.yaml for using multiple k8s clusters

---

harness/determined/keras/_load.py
harness/determined/keras/_tf_keras_trial.py

MD-358
Update the import paths of some modules in tensorflow and Keras.
Create three experiments and see if they complete successfully:
1. `example/computer_vision/iris_tf_keras/const.yaml`: Use <place_holder_tensorflow_image> in the experiment config. 
2. `example/computer_vision/iris_tf_keras/const.yaml`: Use <place_holder_tensorflow-hpc_image> in the experiment config. 
3. `example/computer_vision/iris_tf_keras/const.yaml`: Use the default experiment config.

fix: keras import errors in new versions

---

.circleci/real_config.yml

PR #9126 removing the awscli installation was not well tested and doesn't work in production. This adds it back, but explicitly adds it to the user path so that the pip doesn't complain about installation into a system-managed python path.
[MD-349]
[MD-349]: https://hpe-aiatscale.atlassian.net/browse/MD-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: publish-docs installs awscli into user space

---

.circleci/real_config.yml
docs/reference/deploy/helm-config-reference.rst
e2e_tests/tests/api_utils.py
e2e_tests/tests/cluster/test_logging.py
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

https://hpe-aiatscale.atlassian.net/browse/RM-105
adds an option for setting master level startup hook to TCD to our helm chart
I'll rebase after the target branch is merged into main
> Base automatically changed from hz-global-startup to main [now](https://github.com/determined-ai/determined/pull/9135#event-12413608013)
nice
deploy locally to `kind` and run a command with master tcd startup set

feat: add helm master level config template for tcd startup hooks

---

webui/react/src/components/JupyterLabModal.tsx

[MD-360]
Follow up of #9109
- Check if launch button is enabled when all required fields are filled
- Check if launch button is disabled when one or more required fields are missing
[MD-360]: https://hpe-aiatscale.atlassian.net/browse/MD-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fix disable button condition in launch jupyter notebook modal

---

docs/Makefile
docs/deploy/.gitignore
docs/deploy/Makefile
docs/deploy/README.md
docs/deploy/backend_EE.conf
docs/deploy/backend_OSS.conf
docs/deploy/cdn.tf
docs/deploy/input.tf
docs/deploy/main.tf
docs/deploy/s3.tf
docs/deploy/vars_EE.yaml
docs/deploy/vars_OSS.yaml

Make the code for both doc deploy mechanisms the same with some variables to configure instead of directly editing the terraform.  Add convenience method for publish-oss and publish-ee, but setting the DET_VARIANT env var before calling publish (or publish-ee or publish-oss) will override the default, which is currently OSS.
Note that, if EE continues to exist separately, one should probably change the docs/deploy/Makefile's `DET_VARIANT` variable default to EE in order to maintain complete backwards compatibility.
Tested locally with `make plan` to verify everything aligns on both versions.  Real test will be in the next release, but it should be fine. :D
[DET-123]: …

ci: merge EE and OSS doc deploy together [INFENG-625]

---

docs/setup-cluster/k8s/install-on-kubernetes.rst

Take out the max k8s version because that restriction is meaningless and only causes user confusion https://determined-community.slack.com/archives/CV3MTNZ6U/p1713214201626689

docs: remove max supported k8s version.

---

webui/react/src/components/ModelRegistry.tsx

[MD-362](https://hpe-aiatscale.atlassian.net/browse/MD-362)
When filters change for model registry table, reset table offset to avoid API error. 
When model registry table is over 1 page, navigate to page 2+, apply filters to table (name, tags, workspace...), and the table should auto reset to the first page.
[MD-362]: https://hpe-aiatscale.atlassian.net/browse/MD-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Reset table offset when filtering for models

---

tools/k8s/multicluster.yaml

chore: make the data_dir consistent to other advertised devc configs

---

docs/deploy/_index.rst

To bypass the local build error "this file is not part of any TOC tree" even though "README.md" files are part of conf.py "exclude_patterns"
This adds the README.md to an orphaned index page
(README created as part of #9162 ) 

docs: Add readme to toc

---

harness/determined/ipc.py

None
Fix linting issue with `mypy`. zmq.Context is generic and needs a type. Adding the default type as referenced in [zmq docs](https://pyzmq.readthedocs.io/en/latest/api/zmq.html)
lint-python passes

chore: add typing annotations for zmq

---

examples/tutorials/mnist_pytorch/const.yaml

When this searcher is run for a single epoch it doesn't get a chance to report progress before the entire experiment is complete. This means that the progress bar in the web jumps from 0 to 100 in a step change.
The step-change makes it look like something is broken. This eliminates that (by switching the searcher to step on batches) and demonstrates that the progress bar is working.
[MLG-1522]
[MLG-1522]: https://hpe-aiatscale.atlassian.net/browse/MLG-1522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …

fix: single-searcher MNIST example runs for multiple epochs

---

master/internal/rm/kubernetesrm/pods.go

RM-148
If a pod has a "determined system", "determined preemption" OR "determined" label, don't count it as a "nonDet" pod. This fixes a bug where the db/master pods were counted twice as det pods & nonDet pods, and the master logs gave a `too many pods mapping to node` warning. 
Spin up your own small CPU cluster (or use mine -- slack me for the IP), and check that there are `# of slots - 2 ` slots left in the "default RM". This means that the db & master pod are being counted just once (correct). If there are fewer slots available than expected, or no slots free, this means the pods are being double counted.
Additionally, try spinning up your own experiment and make sure you don't get the "too many pods" warning in your master logs.
See [Release …

fix: count determined-system pods as det pods [RM-148]

---

master/internal/api_checkpoint.go
master/internal/checkpoints/postgres_checkpoints.go
master/internal/checkpoints/postgres_checkpoints_intg_test.go
webui/react/src/components/CheckpointModal.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts

ET-169
This fixes an issue where errors from the delete checkpoints endpoint were not reported in the ui. We fix that and also improve the error messaging such that the user knows which model version the checkpoint is registered to.
* visit the model versions page and select a model, then a version.
* on the resulting page, click the trial breadcrumb in the model checkpoint card
* find the checkpoint in the trial checkpoint table
* click the flag icon to show the checkpoint info for the checkpoint
* click the "request checkpoint deletion" button, then click "request delete" on the resulting modal
* An error message should pop up saying which model and version the checkpoint is registered to.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-notes/READM …

fix: report errors from deletecheckpoints endpoint + improve feedback

---

helm/charts/determined/templates/_helpers.tpl
helm/charts/determined/templates/genai/genai-deployment.yaml

[GAS-675]
When using `.Values.useNodePortForMaster=false` with a `tlsSecret` for the master node, determined creates a service LoadBalancer that is only accessible by explicitly using "https". This makes sure the right scheme is conveyed to the genai backend.
Should not need to be validated in release party. The GenAI team is validating it separately.
[GAS-675]: https://hpe-aiatscale.atlassian.net/browse/GAS-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: pass correct master scheme to genai

---

webui/react/src/components/CheckpointModal.tsx
webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx

ET-169
Server errors are silenced by default in production -- this pr undoes that for the server errors coming from deletecheckpoints.
same as #9178 

fix: louden server errors coming from deleteCheckpoints

---

harness/determined/cli/dev.py

add a flag to skip this behavior
(this is a purely internal feature as it's nested under dev and "hidden" from users)
I find myself wanting this as I try out and test out changes otherwise I can never get the name right on the first try

chore: auto pick the only matching name on partial hits

---

e2e_tests/tests/experiment/test_unmanaged.py
e2e_tests/tests/fixtures/unmanaged/error_termination.py
harness/determined/core/_heartbeat.py
harness/determined/core/_log_shipper.py

in `_LogShipper` and `_Heartbeat`, atexit handlers never get called, since `_core_v2` registers an `atexit` on start, and on interpreter exit the latter atexit gets triggered and calls `close()` on `_LogShipper` and `_Heartbeat` which deregisters the handlers.
run a detached mode experiment that throws an error:
```
import random
import tempfile
from determined.experimental import core_v2
def main():
checkpoint_storage = tempfile.mkdtemp()
core_v2.init(
defaults=core_v2.DefaultConfig(
name="unmanaged-1-error",
),
checkpoint_storage=checkpoint_storage,
)
for i in range(100):
core_v2.train.report_training_metrics(steps_completed=i, metrics={"loss": random.random()})
if i == 15:
raise ValueError("oops")
if (i + 1) % 10 == 0:
core_v2.train.report_validation_metrics(
steps_completed=i, …
```

fix: better exception handling in detached mode

---

docs/model-dev-guide/api-guides/apis-howto/api-pytorch-ug.rst

docs: add profiling section for trainer API UG [MD-373]

---

webui/react/src/App.tsx
webui/react/src/components/ProjectActionDropdown.tsx
webui/react/src/components/ProjectCard.tsx
webui/react/src/components/ProjectEditModal.tsx
webui/react/src/hooks/useFeature.ts
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx
webui/react/src/stores/projects.tsx
webui/react/src/stores/stream.ts

[MD-369](https://hpe-aiatscale.atlassian.net/browse/MD-369)
Sometime the backend may not support streaming updates, so we can create a flag at WebUI to disable and enable streaming updates.
When streaming updates flag is false, we skip connecting to web socket during start up, and at the project list page, we manually update the store when patchProject happens.
With streaming_updates flag on and off, navigate to project list page.
Create/edit/delete project should work as expected.
[MD-369]: https://hpe-aiatscale.atlassian.net/browse/MD-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: …

feat: Use feature flag for streaming updates

---

.circleci/real_config.yml

In several recent releases, the final `publish-docs` has failed to complete, since it has no way of being tested beforehand. This adds a version of the job that runs on RCs and does most of the same things but stops short of the actual publish.
Ideally, we would have an even more complete dry run that did an actual publish to some sort of staging environment, but that would be rather more involved to set up and I believe this much of a dry run would already have caught the recent failures.

ci: do dry runs of `publish-docs` for RCs

---

e2e_tests/tests/api_utils.py

a skip logic running on slurm tests would fail due to resource_pools being explicitly set to null
failure report https://hpe-aiatscale.slack.com/archives/C04C9JXB1C2/p1713371230944499
add the ci label and check slurm tests run and pass https://app.circleci.com/pipelines/github/determined-ai/determined?branch=hz-config-check

test: fix a test util issue with master config schema assumptions

---

e2e_tests/tests/cluster/test_rbac_ntsc.py

Fix failing test after this
https://github.com/determined-ai/determined/pull/9140
Notebooks, tensorboards, shells and commands should return 404 trying to launch a workspace you don't have access to.
test passes

test: can't launch NSC test assert 404 instead of 403

---

.circleci/real_config.yml

Det deploy local test didn't have the proper dependencies linked, so the test is failing (on main). This just adds `package-and-push-system-local` as required, since `test-det-deploy-local` consumes the images generated there
Make sure `test-det-deploy-local` succeeds on CI

ci: fix test-det-deploy-local

---

master/internal/core.go

RM-166
Check for EE license when trying to start up Determined with multiple resource managers defined.
Follow instructions at tools/k8s/multicluster.yaml, without a valid license, and confirm that the cluster crashes upon start-up. Then, with a valid license, try starting up the cluster again & confirm that it starts up successfully.

chore: make multi-RM an EE-only feature [RM-166]

---

docs/setup-cluster/k8s/setup-eks-cluster.rst

use a permalink through a release
compared with https://github.com/NVIDIA/k8s-device-plugin/blob/v0.14.5/nvidia-device-plugin.yml
```
colordiff ~/dl/nvidia-device-plugin.yml /tmp/15
41c41
<       - image: nvcr.io/nvidia/k8s-device-plugin:v0.14.5
---
>       - image: nvcr.io/nvidia/k8s-device-plugin:v0.15.
```

docs: fix nvidia device plugin link for EKS

---

docs/reference/deploy/helm-config-reference.rst
docs/reference/deploy/master-config-reference.rst
docs/release-notes/multirm-for-k8s.rst
docs/setup-cluster/k8s/_index.rst
docs/setup-cluster/k8s/setup-multiple-resource-managers.rst
helm/charts/determined/values.yaml

##Description
Feature: Multiple Resource Managers for Kubernetes.
Docs: Add/Update the following:
- /reference/deploy/helm-config-reference
- /reference/deploy/master-config-reference
- /release-notes/multirm-for-k8s
- setup-cluster/k8s/setup-multiple-resource-managers
https://github.com/determined-ai/determined/pull/9050
https://github.com/determined-ai/determined/pull/9122
https://github.com/determined-ai/determined/pull/9119
- Tentative title "Configure Multiple Resource Managers"
- Draft docs page for describing how to work with and manage multiple resource managers for kubernetes installations. 
- Target audience: admin. 
- Target release date: Not tied to a release.
For starters, we need to add examples mentioned here in #9016: …

docs: Describe multi rm k8s

---

.circleci/real_config.yml
master/.goreleaser_sharedcluster.yml
master/Makefile

This PR removes the changes made to the GKE shared cluster testing that allowed it to run successfully in the EE repo.
CI Passes.

fix: shared cluster test to work in OSS again

---

.circleci/devcluster/react.devcluster.yaml
.circleci/real_config.yml
webui/react/src/e2e/models/pages/Admin/UserManagement.ts
webui/react/src/e2e/models/pages/ProjectDetails.ts
webui/react/src/e2e/models/pages/SignIn.ts
webui/react/src/e2e/models/pages/Workspaces.ts
webui/react/src/e2e/tests/auth.spec.ts
webui/react/src/e2e/tests/navigation.spec.ts
webui/react/src/e2e/tests/projectsWorkspaces.spec.ts

infeng-449
use devcluster for react tests rather than a shared backend. THis should alleviate a lot of repeatability issues at the cost of speed, but I think the trade-off has shown that it's worth it. 
This overrides ENV variables setup by circle-ci. (lines 1701-1705) Once this merges, I can change the variables in circle and I'll create a -new PR to remove the override from this config. I think that lets this merge with 0 downtime. If I change the ENV vars it will have a mismatch before or after this merges briefly.
Fast-follow items that I'll work on next once tests are passing again: https://hpe-aiatscale.atlassian.net/browse/INFENG-636
Ran CI
[DET-123]: …

test: use devcluster for react tests [INFENG-449]

---

.circleci/real_config.yml
webui/react/package-lock.json
webui/react/package.json

[ET-42]
hew update to get chart scroll fix
- Select several experiments in the new experiment table to see at least 5 charts in comparison view
- and scroll up and down without any glitch (see the video in the ticket)
[ET-42]: https://hpe-aiatscale.atlassian.net/browse/ET-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hew update for chart scroll bug

---

docs/reference/deploy/helm-config-reference.rst
docs/reference/deploy/master-config-reference.rst
docs/release-notes/enable-prometheus-default-true.rst
master/internal/config/config.go
master/test/testutils/fixtures.go
tools/devcluster.yaml

Default ```observability.enable_prometheus``` to true for convenience. There was no reason it should have been defaulted to false since the performance is negligible.   
Run a devcluster with no prometheus config and see that 
```det dev curl /debug/prom/metrics``` returns metrics
Run a devcluster with 
```
observability:
enable_prometheus: false
```
```det dev curl /debug/prom/metrics``` returns not found

chore: default observability.enable_prometheus to true

---

webui/react/src/stores/userSettings.tsx

[ET-187]
[ET-191]
- debounce userSettings POST API call
- Check if POST `users/setting` are not called many times during the new experiment table column width resize
- detail: [ET-187]
- Check if page loading is not blocked by POST `users/setting` in `Fast 3G` network
- detail: [ET-191]
- Check if theres no regression around userSettings
[ET-187]: https://hpe-aiatscale.atlassian.net/browse/ET-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-191]: https://hpe-aiatscale.atlassian.net/browse/ET-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-187]: …

fix: debounce `userSettings` update

---

.circleci/real_config.yml
webui/react/playwright.config.ts
webui/react/src/e2e/fixtures/dev.fixture.ts
webui/react/src/e2e/models/BasePage.ts
webui/react/src/e2e/models/pages/Admin/UserManagement.ts
webui/react/src/e2e/models/pages/ProjectDetails.ts
webui/react/src/e2e/models/pages/SignIn.ts
webui/react/src/e2e/models/pages/Workspaces.ts
webui/react/src/e2e/tests/auth.spec.ts
webui/react/src/e2e/tests/navigation.spec.ts
webui/react/src/e2e/tests/projectsWorkspaces.spec.ts

INFENG-636
There were a few follow-ups from the effort to run UI tests with a devcluster backend that we put off in order to get the pipeline passing again. This is that follow up to make the sign in page test more accurate around the error messages, as well as to make sure the test can detect EE vs. OSS version and validate that the branding is correct depending on which version we are using.
Tests should pass CI.

test: ee and oss have separate handling

---

master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/pkg/model/task_container_defaults.go

[DET-10245]
Task container defaults weren't being merged properly between cluster level and resource pool level. Instead, cluster level TCDs were being completely overwritten. This changes the logic so that it is actually merging. 
Test on both kubernetes and agents if possible.
In this example, we'll demonstrate setting environment variables and log policies.
Start by setting a task container default at the cluster level, such as:
```
resource_manager:
...
task_container_defaults:
- testCluster=testCluster
log_policies:
- action:
type: exclude_node
pattern: ECC Error_Cluster_TCD
...
```
Additionally, set the TCD at the resource pool level:
```
resource_manager:
...
resource_pools:
- pool_name: default
task_container_defaults:
- testRP=testRP …
```

fix: properly merge resource configs

---

.circleci/real_config.yml

The EE python publish job uses different credentials to publish to fury.io which are in the determined-ee context
Make an RC and see what happens!

ci: add determined-ee context to python ee publish

---

tools/scripts/track-pr

Also correct a bug caused by operator precedence.

feat: don't attempt to deal with EE when cherry-picking PRs for release

---

helm/charts/determined/templates/genai/genai-deployment.yaml
helm/charts/determined/templates/genai/genai-initialize-shared-fs-permissions.yaml

[GAS-690]
When using agent GIDs on a cluster, both the genai backend and the controller experiments must run with that agent GID as it's primary group, or the setgid flag on the shared drive will be ignored. This is because root's default group is "root", so it uses this group instead of the intended top level directories group of "determined". This prevents the data from being shared properly.
Should not need to be validated in release party.
I did test this by building a full cluster on GKE, creating an unprivileged user, running the shared filesystem group script on the shared_fs, and running through the process of making a dataset and running generation on it …

fix: allow genai deployments with agent GIDs set to share data properly

---

docs/release-notes/long-metrics.rst
master/internal/api_trials_intg_test.go
master/internal/core.go
master/internal/trials/postgres_trials.go

[MD-285]
TIL postgres has a 63 character limit on the column names. We use metric names as columns in this code, and so long metrics were trimmed to 63 characters, and not returned by the API as a result.
We had a test which tested full ascii metric names, but it only checked if the API errors out, not whether it returns useful values.
- Add a map to do an internal conversion between raw metric name and a column name.
- Updated the auto tests to check for this.
Run an experiment with a metric name longer that 63 characters, and make sure it's present in the experiment table compare views.
[MD-285]: https://hpe-aiatscale.atlassian.net/browse/MD-285?atlOrigin=eyJpIjoiNWRkNTlj …

fix: support for metric names over 63 characters long [MD-285]

---

webui/react/package-lock.json
webui/react/package.json

[ET-118]
select component in log viewer bug
- Check if the select component height doesnt change after selecting item in log viewer (see the ticket for more details)
[ET-118]: https://hpe-aiatscale.atlassian.net/browse/ET-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hew update for select bug in log viewer

---

webui/react/src/pages/Cluster/ClusterHistoricalUsageFilters.tsx

[DET-10249]
`value` prop was directly modified in calendar onChange handler. That caused unintentional state change. 
- Go to historical usage page `/clusters/historical-usage`
- Set the `from` range too far (more than a year) with group by `day` and `months`
- Check if `start date cannot be after end date` error is not shown and correctly call `/api/v1/resources/allocation/aggregated` API
[DET-10249]: https://hpe-aiatscale.atlassian.net/browse/DET-10249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

fix: historical-usage date calculation bug

---

helm/charts/determined/templates/_helpers.tpl
helm/charts/determined/templates/genai/genai-deployment.yaml
helm/charts/determined/templates/master-deployment.yaml

[GAS-908]
Enables genai to connect to the determined db over TLS when this is enabled in the cluster.
Reference Thread: https://github.com/determined-ai/determined/pull/3624
Does not need to be validated in release party. The genai team is validating it separately.
[GAS-908]: https://hpe-aiatscale.atlassian.net/browse/GAS-908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: enable genai to connect to db over TLS

---

webui/react/src/components/ManageGroupsModal.tsx

DET-10246
Validation was keeping us from removing all groups from a user in the Web UI. This fixes that.
1. Turn on RBAC or use a cluster with RBAC enabled
2. Create a user
3. Add the user to one group (can be a new group if you'd like)
4. While logged in as an admin in the Web UI, navigate to the Admin Settings page (`/admin/user-management`)
5. Use the kebab menu next to your new user and select "Manage Groups"
6. Remove all groups from the list of groups to which the user should belong
7. The app should let you click "Save," removing the user from all groups
8. Verify the user isn't in the group in the CLI by using `det user-group describe GroupName` (substituting the real group name you chose into the command)
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJp …

fix: users can be removed from all groups in Web UI

---

.circleci/real_config.yml

Fix failing podman tests
https://app.circleci.com/pipelines/github/determined-ai/determined/54910/workflows/19816278-7088-4c7e-910e-5a6c50699a96/jobs/2515396
Don't build proto again. We probably shouldn't be building proto more than once per CI. We also likely don't even need to build ```proto``` at all.  My best guess of what is going on is somehow the ```store_artifacts``` is interacting weirdly with us building proto again so try making sure we always run after build proto is done. 
Tests pass on main after landing

ci: try to fix podman tests by building proto once

---

.circleci/real_config.yml
webui/react/src/e2e/fixtures/user.fixture.ts
webui/react/src/e2e/tests/userManagement.spec.ts

INFENG-666
increase react runner size to large since we are maxing out CPU on the current runner.
Ran and passed CI

test: increase runner size for react e2e

---

.circleci/real_config.yml
helm/Makefile

Publishing helm charts to NGC is useless. Publishing to `https://helm.determined.ai` is done elsewhere.
https://hpe-aiatscale.slack.com/archives/C03JGLKTBEJ/p1714429971196879
https://hpe-aiatscale.slack.com/archives/C7E6HPZ5F/p1714432108065479
This is changing CI jobs for release which we have no way to test or dry-run. Please review carefully.

chore: stop publishing helm charts to NGC.

---

docs/release-notes/non-det-tasks-k8s-fix.rst
e2e_tests/tests/cluster/test_master_restart.py
master/internal/rm/kubernetesrm/pods.go
master/internal/rm/kubernetesrm/pods_test.go

Fix an issue where we only looked at the default namespace for getting pods.
Also cache get agents which probably should have been done anyway but getting all namespaces makes this even more important.
unit test + manual
Make a non default named namespace that determined master has access to 
```
apiVersion: v1
kind: Pod
metadata:
name: sleep-pod
spec:
containers:
- name: sleep
image: busybox
command: ["sleep", "100"]
resources:
requests:
cpu: "2000m" # Or request gpus if this is on a gpu cluster
```
Then apply the file with ```kubectl -n namespace -f file.yaml```
```det slot ls``` should show
```
Agent ID   | Resource Pool   |   Slot ID | Enabled   | Draining   | Allocation ID   | Task Name                      | Type   | Device …
```

fix: show non det pods in other namespaces than 'default' [RM-141]

---

.circleci/real_config.yml

Fix failing podman tests not fixed by https://github.com/determined-ai/determined/pull/9267
Avoid building and packaging the agent again, just use the one built in ```build-go```
test passes on main after

ci: try to fix slurm podman tests by not building agent binary

---

master/internal/api_runs.go
master/internal/api_runs_intg_test.go

ET-245
Runs that are part of an archived experiment should be considered archived
Integration tests should pass

fix: Hide runs in archived experiments

---

.circleci/real_config.yml

Quick solution so that slurm tests aren't run by default every push. We ideally do not want to run HPC tests on every commit to decrease spend and runtime, so for now we will ask users to enter circleCI and manually approve of requests to run these tests. A future improvement is to automatically decide which tests to run based on the modified files
Check CircleCI and make sure that under `test-e2e`, the slurm and hpc tests are not running and are awaiting approval

ci: gate hpc by request

---

webui/react/src/e2e/tests/userManagement.spec.ts

[INFENG-663]
honestly we should warn about unawaited promises
fixing [this](https://output.circle-artifacts.com/output/job/75b109b5-2690-4809-a672-a15cc5f6f0e6/artifacts/0/webui/react/src/e2e/playwright-report/trace/index.html?trace=https://output.circle-artifacts.com/output/job/75b109b5-2690-4809-a672-a15cc5f6f0e6/artifacts/0/webui/react/src/e2e/playwright-report/data/97f8a7cb7f56c3ebbeec08989f9f07dbab42c390.zip)
[INFENG-663]: https://hpe-aiatscale.atlassian.net/browse/INFENG-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

test: flaky user test fix [INFENG-663]

---

webui/react/.eslintrc.js
webui/react/src/e2e/fixtures/auth.fixture.ts
webui/react/src/e2e/models/hew/DataGrid.ts
webui/react/src/e2e/tests/projectsWorkspaces.spec.ts

[INFENG-668]
show linting errors on floating promises
Here's [an example](https://app.circleci.com/pipelines/github/determined-ai/determined/55037/workflows/3a8e35d1-7d2e-46a0-b9c7-9e49e6c92e41/jobs/2525620?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary&invite=true#step-113-297_153) of a successful lint
[INFENG-668]: https://hpe-aiatscale.atlassian.net/browse/INFENG-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: e2e no floating promises [INFENG-668]

---

docs/release-notes/k8s-slots-jumping.rst
master/internal/authz/obfuscate.go
master/internal/authz/obfuscate_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go
master/internal/rm/kubernetesrm/pods.go
master/pkg/model/agent.go
master/pkg/model/agent_test.go

Fix issues where slots were being returned out of order. There are two fixes in this PR
1. Make k8s use slot IDs that will return sorted. For more than 10 gpus on an agent the response would be out of order
2. The issue in the ticket, rbac would jumble the order. 
Unit tests cover this pretty well
Manual 
Run a devcluster with
```
security:
authz:
type: rbac
```
and agent
```
artificial_slots: 8
```
run a experiment, create a user with no access ```det -u admin user create test```
check agents ```det -u test dev curl /api/v1/agents``` and see that the contaner is on the same slot id every refresh
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIj …

fix: slots being filled returned out of order on k8s [RM-42]

---

master/internal/core.go
master/internal/rm/dispatcherrm/dispatcher_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go
master/internal/rm/kubernetesrm/pods.go

Add master logs for failed health checks.
Run devcluster, delete cluster_id table and look to see it is logged

chore: log health check failures in master logs

---

webui/react/src/hooks/useTypedParams.test.tsx

https://hpe-aiatscale.slack.com/archives/C04C9JXB1C2/p1714588016489469
- CI should pass
- `src/hooks/useTypedParams.test.tsx > useTypedParams > does not touch params that are not in the codec` test case should be skipped

test: skip a `useTypedParams` test case due to flakiness

---

.circleci/real_config.yml

After EE merge the Slack alerts ended up being configured to go to #ci-bots-ee which is archived and did not work.

ci: circleci slack alerts should go to #ci-bots

---

harness/determined/common/api/bindings.py
master/internal/templates/api.go
master/internal/templates/api_intg_test.go
proto/pkg/apiv1/api.pb.go
proto/src/determined/api/v1/api.proto
webui/react/src/services/api-ts-sdk/api.ts

[MD-379]
In order to support move templates between workspaces, update `PutTemplate` to take workspace id. 
Change workspace id for a template through `/api/v1/templates/{templateName}` endpoint. 
Using invalid workspace id should not go through. 
[MD-379]: https://hpe-aiatscale.atlassian.net/browse/MD-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Update workspace for templates server side

---

.circleci/real_config.yml

infeng-672
the change in `INFENG-598: Ensure tests are sufficiently parallel or scale down resource classes` caused issues for test-ee2-cpu (probably) and needs to be reverted.
ci passes

test: revert runner size test-e2e-cpu

---

harness/determined/deploy/aws/templates/lore.yaml

efs-utils needs cargo to be installed. This updates the genai master build to support it according to the docs here: https://github.com/aws/efs-utils
They recommend:
```
$ sudo apt-get update
$ sudo apt-get -y install git binutils rustc cargo pkg-config libssl-dev
$ git clone https://github.com/aws/efs-utils
$ cd efs-utils
$ ./build-deb.sh
$ sudo apt-get -y install ./build/amazon-efs-utils*deb
```
Does not need to be tested in release party

chore: update efs-utils install for v2.0

---

harness/determined/tensorboard/base.py
harness/determined/tensorboard/metric_writers/callback.py
harness/determined/tensorboard/metric_writers/pytorch.py
harness/tests/tensorboard/test_base.py
harness/tests/tensorboard/test_metric_writers.py

Fixes two separate issues
1. Metrics being overwritten by the TensorBoard metric writer. In some cases we reset a file handle then immediately write another event destined for the same file handle, which overwrites the file. To accurately batch writes to once per second, we need to track two timestamps, one before the write, and one after.
2. Tensorboard sync to cloud storage happening more than once per second will hit cloud storage quotas, so throttle them to at most once per second. Though this issue has been surfaced for GCS, this fix would effectively throttle uploads for all tensorboard managers since I don't see a good reason why we'd need to sync that often. …

fix: tensorboard metric overwrites and sync throttle [MD-328] [MD-291]

---

e2e_tests/tests/cluster/managed_cluster.py
e2e_tests/tests/cluster/test_rbac.py
e2e_tests/tests/experiment/experiment.py

To help better identify e2e test flakes, add some logging statements to expose information about the particular failure event. Additionally, this changes the comment to `create_workspaces_with_users` to add more clarity for its usage.

chore: improve messaging for e2e tests

---

.circleci/config.yml
.circleci/real_config.yml

[INFENG-676]
a new workflow for manual e2e
[the manual run](https://app.circleci.com/pipelines/github/determined-ai/determined/55160/workflows/72c3324c-c141-4165-805a-5ce92d2f7790/jobs/2534936?invite=true#step-146-69_31)
[when triggered from webhook](https://app.circleci.com/pipelines/github/determined-ai/determined/55159/workflows/d871e611-c582-42da-bd0c-bee008803c1b/jobs/2535001?invite=true#step-146-45_32
)
[INFENG-676]: https://hpe-aiatscale.atlassian.net/browse/INFENG-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

ci: run e2e-react manually [INFENG-676]

---

.circleci/real_config.yml

test-e2e workflows will already have them. test-e2e-longrunning is pure duplication on main. 
See if main is still running these after this lands

ci: don't run test-e2e-longrunning tests on main

---

webui/react/src/components/FilterForm/TableFilter.tsx
webui/react/src/components/TableActionBar.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/FlatRuns/FlatRuns.settings.ts
webui/react/src/pages/FlatRuns/FlatRuns.tsx

[ET-111]
Add filter feature in Flat Run table (Run table is under feature flag)
- Enable feature flag of Flat Runs View
- Go to flat run table
- Check if 
- filter button is visible and usable on top of the run table
- filter is saved after applying valid filters, so filtered table is preserved even after refreshing the page
- filter should be able to be applied from table header
- filter should be able to be cleared from table header
(filter behavior should be the same as the experiment table we have now (its not feature flagged))
[ET-111]: https://hpe-aiatscale.atlassian.net/browse/ET-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

feat: support filter in flat run table

---

harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/base.py
harness/determined/deploy/aws/templates/lore.yaml
helm/charts/determined/templates/_helpers.tpl
helm/charts/determined/templates/genai/genai-deployment.yaml

[GAS-14]
Allows us to pass a mount path for the shared_fs drive in genai. This makes it possible to use shared_fs for checkpoints and for datasets without necessarily using the same disk.
No need to test in release party. The GenAI team is testing separately.
[GAS-14]: https://hpe-aiatscale.atlassian.net/browse/GAS-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: support for configuring the shared_fs mount path in genai

---

webui/react/src/components/TableActionBar.tsx

https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1715014499179449?thread_ts=1715008712.981189&cid=CLCE8D998
API requests for batch actions should only contain experiment ids for selected experiments where the action is valid.
- On Experiments List, select two experiments which would not have the same action valid (for example, one completed experiment and one paused experiment).
- Select the bulk action (for example, resume), and confirm in the modal that appears.
- Should see a toast that confirms successful action on one experiment, not two. Can also confirm by looking at payload sent in action's API request, which should only contain the one valid experiment ID. …

fix: filter batch action experiments

---

webui/react/src/e2e/tests/navigation.spec.ts

[INFENG-683]
refactor to use sidebar pagemodels
[INFENG-683]: https://hpe-aiatscale.atlassian.net/browse/INFENG-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: refactor nav spec to use sidebar pagemodels [INFENG-683]

---

webui/react/.gitignore
webui/react/src/e2e/fixtures/api.auth.fixture.ts
webui/react/src/e2e/fixtures/dev.fixture.ts
webui/react/src/e2e/fixtures/global-fixtures.ts
webui/react/src/e2e/tests/experimentList.spec.ts
webui/react/src/e2e/tests/navigation.spec.ts
webui/react/src/e2e/tests/projectsWorkspaces.spec.ts

infeng-671
Previously for all our tests we logged in by navigating to the UI and logging in. It will be faster and have less code to just auto-login through the API and apply the cookie to the browser.
More stuff coming in user management with the next ticket, but this is a self-contained start.
ran manually and CI should pass.

test: log in with the api rather than through the UI for most react tests

---

.circleci/real_config.yml

We added the override in the RC section but forgot to add that in the release version. Whoops.
Same code works for RCs, so fingers crossed that it also works properly on the next release. :grimacing: 

ci: add missing var overide in ee release [skip ci]

---

webui/react/src/e2e/fixtures/dev.fixture.ts

INFENG-692
there’s some potential flake with dev.setServerAddress. It runs synchronously, but fires an async logout request in the background, so the test might continue on before the logout occurs.
This will wait after reload for the network to be quiet for 500ms after the reload which should mean we have finished logout, and can login for the test.
ci passes

test: wait for background logout

---

.circleci/real_config.yml

chore: remove step for authenticated master session check to use standard script
No ticket.
`test-e2e-gke-shared-cluster` adds a step that waits for the master connection using an authenticated determined session, verifying that valid authenticated requests during the test runs are expected to succeed. 
Remove this step to use the standard script that tests the master connection with an unauth session, as this achieves the main goal of the step, which is to ensure that the master is accessible prior to running test cases.
CI passes.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

chore: remove step for authenticated master session check to use standard script

---

.circleci/real_config.yml

why now? a pip version change? 
tests pass

chore: add missing setuptools to win cli tests

---

docs/reference/deploy/helm-config-reference.rst
docs/release-notes/helm-requires-initial-password.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

[DET-10196]
BREAKING CHANGE: Helm now **requires** setting a bootstrap password for the admin and determined users via the `initialUserPassword` entry.
This is a fairly simple and straightforward change, and most of our existing documentation around this entry already indicates that it's required.
Attempting to run a helm deployment without adding an `initialUserPassword` entry should fail.
[DET-10196]: https://hpe-aiatscale.atlassian.net/browse/DET-10196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

feat: helm requires bootstrap password (DET-10196)

---

codecov.yml
webui/react/package.json
webui/react/vite.config.mts

[INFENG-689]
removes e2e from vite codecov config
e2e not showing up [here](https://app.circleci.com/pipelines/github/determined-ai/determined/55414/workflows/7c4ac9d4-59a8-4307-b047-72873df17d26/jobs/2554123/artifacts)
[INFENG-689]: https://hpe-aiatscale.atlassian.net/browse/INFENG-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update codecov to ignore e2e react [INFENG-689]

---

.circleci/real_config.yml

it often run into transient network issues. a simple retry over the whole process works as low lift solution that we can evaluate over time
https://hpe-aiatscale.atlassian.net/browse/RM-259
tests pass
https://app.circleci.com/jobs/github/determined-ai/determined/2548113 

chore: add retries to check-doc-links ci job

---

docs/model-dev-guide/prepare-container/custom-env.rst
docs/setup-cluster/deploy-cluster/slurm/singularity.rst
docs/setup-cluster/slurm/singularity.rst

- switch from grid to list
- list is more tolerant of content changes
- help prevent having to perform manual intervention when running bumpenvs process
**Singularity**
The duplicated page `deploy-cluster/slurm/singularity.rst` is meant to be a copy of `slurm/singularity.rst`, and so the default docker image table has been updated in both to match `slurm/singularity.rst`.
There are duplicates of the `singularity.rst` page because moving the page from `deploy-cluster/slurm/singularity.rst` to `slurm/singularity.rst` breaks the bumpenvs process noted in #8180 .

docs: Reformat grid tables

---

docs/release-notes/pod-label-bugfix.rst
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go

[RM-278]
[RM-278]: https://hpe-aiatscale.atlassian.net/browse/RM-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove pod labels with potentially incompatible names

---

webui/react/src/components/ColumnPickerMenu.tsx

I saw a hardcoded value used in two different places. Here's the location where it's already being defined and used.
https://github.com/determined-ai/determined/blob/main/webui/react/src/pages/F_ExpList/F_ExperimentList.tsx#L1073-L1077
Make sure the column picker looks the same as before

refactor: columnpicker remove hard coded value

---

harness/determined/common/storage/boto3_credential_manager.py

`det checkpoint download` for s3 backends was failing to some attribute error due to bad imports refactoring.
Run `det checkpoint download <ckpt uuid>` against a checkpoint on s3.
Bug to add an autotest: https://hpe-aiatscale.atlassian.net/browse/MD-408

fix: det ckpt download from s3.

---

.circleci/config.yml
.circleci/real_config.yml
master/internal/rm/kubernetesrm/resource_pool_intg_test.go

RM-201
Add tests to resource_pool.go for exported functions on `kubernetesResourcePool`. These tests run on a minikube cluster that circleCI spins up before running all master intg tests.
See attached test.

chore: add intg tests to resource_pool.go

---

webui/react/src/components/OptionsMenu.module.scss
webui/react/src/components/OptionsMenu.settings.ts
webui/react/src/components/OptionsMenu.tsx
webui/react/src/components/Searches/Searches.tsx
webui/react/src/components/TableActionBar.tsx
webui/react/src/components/UserSettings.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx

[ET-229]
Add table settings menu, and removed dead code (infinite scroll is removed permanently)
- Enable Flat Run table
- Check if `row height` changes by changing option settings and the settings should persist
[ET-229]: https://hpe-aiatscale.atlassian.net/browse/ET-229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add options in flat run

---

.circleci/real_config.yml
docs/model-dev-guide/prepare-container/custom-env.rst
docs/setup-cluster/deploy-cluster/slurm/singularity.rst
docs/setup-cluster/slurm/singularity.rst

https://hpe-aiatscale.atlassian.net/browse/DET-10292
https://hpe-aiatscale.slack.com/archives/C04C9JXB1C2/p1715354349333909
take out branch protections to let the tests run slurm tets should not fail with image not found
https://app.circleci.com/pipelines/github/determined-ai/determined/55541/workflows/baba4a8f-bd5c-4fd4-9b9e-d99fc065b5c4/jobs/2563937 test ran and passed I'll put back in the branch protection.

docs: revert a doc format change to reenable slurm tests

---

.circleci/real_config.yml

[DET-10196]
Fixes CircleCI issues introduced by #9359 .
N/A
[DET-10196]: https://hpe-aiatscale.atlassian.net/browse/DET-10196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: fix circleci gke tests with helm password [DET-10196]

---

e2e_tests/tests/command/command.py
harness/determined/cli/command.py
harness/determined/cli/notebook.py
harness/determined/cli/render.py
harness/determined/cli/shell.py
harness/determined/cli/tensorboard.py

https://hpe-aiatscale.atlassian.net/browse/RM-263
https://hpe-aiatscale.atlassian.net/issues/MD-412?filter=10316
also remove a duplicate get for shells

chore: report ntsc names via cli when launched

---

e2e_tests/tests/fixtures/no_op/grid-long-run.yaml
e2e_tests/tests/run/test_api.py

DET-10294
Fix the flakiness of the kill run test by creating a new fixture that generates 4 runs with a deterministic hyperparameter and filter on that hyperparameter in the test. Addtionally we want to ensure that the experiment runs for long enough for the trials to be killed
e2e test should pass after multiple runs
4 runs with a distinct "unique_id" hyperparameter of 1, 2, 3 & 4

test: Remove flakiness of KillRun test

---

master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go

[RM-279]
Kubernetes restricts pod label values: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set 
Pods labels on Determined resources should conform to Kubernetes standards, or the workload will not be scheduled. If Determined resource names used in pod labels don't conform to standards, the name is updated.
1. Create a workspace or user containing spaces. Include as many random/special characters as you'd like!
2. Start a workload as that user or in that workspace.
3. Confirm the workload is scheduled and runs/works.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …

feat: add pod labels with proper validation

---

master/internal/rm/multirm/multirm.go
master/internal/rm/multirm/multirm_intg_test.go

DET-10289
Currently, `getRM` only returns the name of the desired resource manager, rather than the resource manager itself. Rename this to `getRMName` so that getRM can be implemented to retrieve the desired resource manager, as its function name suggests.
Ref [here](https://github.com/determined-ai/determined/pull/9226/files#r1585220300), where we use `getRM` to return the resource manager needed to provision resources within its corresponding cluster.
CI passes.

refactor: rename multiRM to more intuitive name

---

docs/integrations/observability/_index.rst

Add note on transformation of labels, in the case of workspace, username, or other pod labels containing special characters.

docs: final observability edits

---

harness/determined/common/experimental/checkpoint/_checkpoint.py
harness/determined/common/experimental/experiment.py
harness/determined/common/experimental/trial.py

We want to expose pachyderm configs from the expconf for pachyderm integrations in the python SDK. These are basically just convenience methods for getting a specific field out of the experiment config. Pachyderm configs were added to the expconf in #8933 and take the following structure:
```
integrations:
pachyderm: 
pachd:
host: localhost
port: 80
proxy:
scheme: http
host: localhost
port: 80
dataset:
branch: br
commit: commit-hash
project: proj
repo: repo-name
token: tkn
```
these are expected to be populated mostly manually by users today
- Submit an experiment that a) has the `integrations: pachyderm` config defined in the expconf, and b) creates at least 1 checkpoint.
For example, using the Core API script at `examples/tutorials/core_api/2_checkpoints.py`, with the following expconf: …

feat: SDK methods to fetch pachyderm configs [MD-406]

---

.circleci/real_config.yml
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/kubernetesrm/resource_pool_intg_test.go

RM-201
Add intg tests for resource_pool.go
Leave a couple things as TODO for Bradley's refactor PR.
See attached test.

chore: add resource_pools intg test

---

master/internal/db/migrations.go
master/internal/db/postgres.go
master/static/views_and_triggers/README.md
master/static/views_and_triggers/down.sql
master/static/views_and_triggers/up/checkpoints.sql
master/static/views_and_triggers/up/metrics.sql
master/static/views_and_triggers/up/model.sql
master/static/views_and_triggers/up/project.sql
master/static/views_and_triggers/up/users.sql
master/static/views_and_triggers/up/util.sql

Instead of making ```views_and_triggers``` use a separate schema just require people to manually drop them.
Using a separate schema requires us to set the search path requiring extra permissions. Avoid needing more database permissions with this change.
intg passes

chore: don't use a seperate schema for views_and_triggers

---

tools/k8s/launch-minikube-with-gateway.sh

chore: gateway startup without pwdless sudo

---

examples/features/unmanaged/2.yaml

Add an exp config file for unmanaged example #2 for "checkpoints". It is trivial, but I had a support conversation about it. Let's add to avoid that conversation in the future.
N/A

docs: add exp config for unmanaged example #2.

---

master/internal/core_experiment.go

[MD-385]
For unmanaged experiments, the slots per trial should be 0 since we are not spending any resource for it. 
Create a master without any agent connection, run unmanaged experiments and the experiments complete successfully even though there is no computing resource available 
[MD-385]: https://hpe-aiatscale.atlassian.net/browse/MD-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Skip resource checking for unmanaged exp

---

helm/charts/determined/templates/master-config.yaml

[DET-10293]
BREAKING CHANGE: helm: initial user passwords must satisfy some basic complexity requirements:
-  Passwords must be at least 8 characters long.
-  Passwords must contain at least one upper-case letter.
-  Passwords must contain at least one lower-case letter.
-  Passwords must contain at least one number.
Most likely not needed, this is mostly static helm templating.
[DET-10293]: https://hpe-aiatscale.atlassian.net/browse/DET-10293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …

feat: helm install checks password complexity [DET-10293]

---

docs/reference/deploy/master-config-reference.rst
docs/release-notes/feature-clean-up.rst
master/cmd/determined-master/root.go
master/cmd/determined-master/root_test.go
master/internal/config/scheduler_config.go

[RM-254]
For agent resource managers, use the priority scheduler by default.
Start a new instance of Determined, e.g. by running devcluster, with no configuration. On the cluster overview page, the resource pool description should say Scheduler Type Priority.
[RM-254]: https://hpe-aiatscale.atlassian.net/browse/RM-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update default scheduler to priority for agentrm

---

tools/scripts/retag-bumpenvs-yaml.py
tools/scripts/update-docker-tags.sh

None
A few updates to release party helper scripts for updating our docker image tags.
cut rcs and cut releases in release party. requires dockerhub credentials.

chore: Update docker retag scripts

---

.circleci/devcluster/custom-agent-version.devcluster.yaml
.circleci/devcluster/double-priority.devcluster.yaml
.circleci/devcluster/double-reattach.devcluster.yaml
.circleci/devcluster/double.devcluster.yaml
.circleci/devcluster/elastic.devcluster.yaml
.circleci/devcluster/multi-k8s.devcluster.yaml
.circleci/devcluster/oauth.devcluster.yaml
.circleci/devcluster/perftest.devcluster.yaml
.circleci/devcluster/port-registry.devcluster.yaml
.circleci/devcluster/postgres-with-ssl.devcluster.yaml
.circleci/devcluster/priority.devcluster.yaml
.circleci/devcluster/rbac-model-registry.yaml
.circleci/devcluster/react.devcluster.yaml
.circleci/devcluster/saml.devcluster.yaml
.circleci/devcluster/single-rbac.devcluster.yaml
.circleci/real_config.yml
docs/release-notes/cli-requires-initial-password.rst
e2e_tests/tests/cluster/test_users.py
e2e_tests/tests/experiment/test_custom_searcher.py
e2e_tests/tests/experiment/test_unmanaged.py
harness/determined/deploy/local/cli.py
harness/determined/deploy/local/cluster_utils.py
harness/determined/searcher/_search_runner.py
master/internal/core.go

[DET-10197]
BREAKING CHANGE: on new deployments, `master` will log an error and abort startup if no `initialUserPassword` is found in config.
To allow users to continue leaning on other reasonable default settings with something like `det deploy local cluster-up`, an `--initial-user-password` flag is provided in the CLI.
Unlike helm, these commands tend to be fairly fast and transparent -- they only try to start master once, and if it errors out, they dump the logs, so the error message details are pretty visible and easy to fix.
Scenarios I've manually tested:
- Launch a new cluster with `det deploy local cluster-up` not providing a password (fails to start)
- Launch a new cluster with `det deploy local cluster-up --initial-user-password='TestPassword1'` (works)
- Launch the local …

feat: require initial passwords on new cluster-up [DET-10197]

---

.github/CODEOWNERS

None
Adding RM as the owning team for slurm tooling

chore: Add slurm codeowners

---

docs/model-dev-guide/dtrain/config-templates.rst

Describe how users can now create and manage configuration templates via the WebUI (in addition to CLI).
See: #9383 
Release: 0.33.x

docs: Describe config templates WebUI

---

webui/react/src/components/JupyterLabModal.tsx
webui/react/src/components/ProjectCard.tsx
webui/react/src/e2e/fixtures/api.auth.fixture.ts
webui/react/src/e2e/models/ant/Tabs.ts
webui/react/src/e2e/models/components/ProjcetActionDropdown.ts
webui/react/src/e2e/models/components/ProjectCreateModal.ts
webui/react/src/e2e/models/components/ProjectDeleteModal.ts
webui/react/src/e2e/models/components/ProjectsPage.ts
webui/react/src/e2e/models/components/ResourcePoolsPage.ts
webui/react/src/e2e/models/components/TasksPage.ts
webui/react/src/e2e/models/components/WorkspaceDetails.ts
webui/react/src/e2e/models/components/WorkspacesList.ts
webui/react/src/e2e/models/hew/Card.ts
webui/react/src/e2e/models/pages/Workspaces.ts
webui/react/src/e2e/tests/projectsWorkspaces.spec.ts
webui/react/src/e2e/utils/detCLI.ts
webui/react/src/pages/WorkspaceDetails/WorkspaceProjects.tsx
webui/react/src/stores/cluster.tsx

##
INFENG-456
This adds react E2E tests and page object models for project creation and deletion. This does not complete the the full test we are automating, but it is a self contained test with usable page objects so I'm going to merge it to prevent conflicts later.
CI passes OSS and EE

test: project create and delete react e2e [INFENG-456]

---

master/cmd/determined-master/migrate.go
master/cmd/determined-master/populate_metrics.go
master/internal/core.go
master/internal/core_intg_test.go
master/internal/db/database.go
master/internal/db/migrations.go
master/internal/db/postgres_test_utils.go
master/internal/db/setup.go
master/test/testutils/fixtures.go

[DET-10312]
Since creating the admin user without a password is a migration step, we need to check for invalid configuration (missing initial password) before the migration is run, but wait to apply the configuration until after the migration is run. This therefore splits the previous admin password configuration into two separate steps.
Due to the way this straddles the usual place Bun would be initialized, I didn't Bun-ify anything as part of this, and did a little bit of redundant config parsing to avoid doing anything that could call `initTheOneBun()` twice.
This attempts to solve an issue that was found testing #9314 .
[DET-10312]: …

fix: master checks db newness before migrating [DET-10312]

---

.circleci/real_config.yml

When cluster creation fails halfway, `pkill determined-mast` will exit with 1. CircleCI runs these inline script with `set -e`, so that failure causes `make unslurmcluster` to no run, leaving stray TF resources behind.
Is a test.

test: ensure make unslurmcluster always runs in CI

---

.circleci/real_config.yml
tools/slurmcluster.sh

This code clones dev-scripts to get slurmcluster. Unfortunately there are two things named slurmcluster and it doesn't need the one (the gcp slurm tests run `make -C tools/slurm slurmcluster` which lives entirely within the repo).
Needs no tests.

chore: remove confusing slurm-related code

---

docs/release-notes/cli-requires-initial-password.rst
master/internal/core.go
master/internal/core_intg_test.go

[DET-10197]
Effectively removes service-side checking for blank passwords on default user accounts, by putting it behind a feature switch.
`det deploy local` commands etc. don't stall for up to 10 minutes
[DET-10197]: https://hpe-aiatscale.atlassian.net/browse/DET-10197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add feature gate for checking for blank admin/determined password [DET-10197]

---

e2e_tests/tests/cluster/test_job_queue.py

[RM-315]
e2e scheduler tests use the default scheduler. Update tests to use the priority scheduler since it is now default.
None needed.
[RM-315]: https://hpe-aiatscale.atlassian.net/browse/RM-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: use priority scheduler in e2e tests

---

harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/templates/lore.yaml

We were not setting the default for the shared_fs mount dir correctly in `det deploy aws --deployment-type genai`

fix: set the defaults for shared_fs mount in genai correctly

---

webui/react/src/components/NavigationTabbar.tsx

ET-194
Adds "Admin Settings" to mobile navigation menu (if user has admin permissions)
Also renames "Settings" option to "User Settings"
- Open app in mobile mode.
- Click three-dot menu on lower right.
- User with admin permissions should see "Admin Settings" option which leads to Admin Settings page
- User without admin permissions should not see that option

fix: add Admin Settings to NavigationTabbar (ET-194)

---

master/.golangci.yml

We've had the stdlib `errors` package disallowed [since at least April of 2020](https://github.com/determined-ai/determined/blame/main/master/.golangci.yml#L48). More recently, we decided to stop using `github.com/pkg/errors`, which is a good thing IMO. But we need the stdlib `errors` for stuff like `errors.Is`, so this removes it from the list of disallowed packages.
None, it's a linting/CI change.

chore: remove stdlib errors package from lint blocklist

---

webui/react/src/globalStorage.ts
webui/react/src/pages/SignIn.tsx

[DET-10192]
SSO login was not redirecting to the page that users were desiring. This PR has the webui temporarily store the target URL when a login is attempted.
When SSO login occurs, the path is null; we can take advantage of this by only using the stored target URL when the path is null. 
Following the steps first with normal username/password login, then with Okta login:
- Login and verify that you are redirected to either the dashboard (RBAC not enabled) or workspaces (RBAC enabled). 
- log out
- go to a page such as `/det/tasks` or `/det/clusters` and make sure you are redirected to the login page
- Log in and verify that you are redirected to the page you are trying to reach (the two aforementioned are tasks or clusters, respectively). 
- log back out 
- log back in and verify that …

fix: redirect on sso login

---

harness/determined/deploy/aws/cli.py

Normal det deploys were broken with this default set. It didn't seem necessary in the original PR, but we had to unset this again to not pollute other deploys.
This caused the parameter to leak into normal aws deploys which isn't valid

fix: dont utilize the default efs mount on normal aws deploys

---

docs/manage/historical-cluster-usage-data.rst

https://github.com/orgs/determined-ai/projects/53/views/1?pane=issue&itemId=64794275
Add a note to the  Historical Cluster Usage Data page to let users know that if using the export to csv functionality, the gpu_hours for a given allocation only reflects the number of gpu hours the allocation used during the export time window even if it started and/or ended outside the export time window.

docs: Add historical cluster usage warning

---

webui/react/.gitignore
webui/react/playwright.config.ts
webui/react/src/e2e/fixtures/api.auth.fixture.ts
webui/react/src/e2e/fixtures/api.user.fixture.ts
webui/react/src/e2e/fixtures/global-fixtures.ts
webui/react/src/e2e/fixtures/user.fixture.ts
webui/react/src/e2e/models/ant/Dropdown.ts
webui/react/src/e2e/models/ant/Select.ts
webui/react/src/e2e/tests/userManagement.spec.ts
webui/react/src/e2e/utils/users.ts

https://hpe-aiatscale.atlassian.net/browse/INFENG-673
The playwright test previously created users through the UI. Now they will create and teardown user setup through the API since it is faster and more reliable. There is still a test doing user setup/teardown through the UI so that tests still cover that workflow.
I also spent some time smoothing out flakes. That wound up involving a lot of retries around the 10s refresh for tables but I've gotten bulk actions un-skipped and passing 3+ times in a row in the pipeline which is a good sign.
CI passes several times in a row
[INFENG-673]: https://hpe-aiatscale.atlassian.net/browse/INFENG-673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …

test: create test users through the API [INFENG-673]

---

.circleci/real_config.yml

the new AMIs build a newer version of `amazon-efs-utils` which breaks an efs-utils test that relied on the mount name containing "efs". change it to just grep for nfs4, assuming there's not another non-efs nfs4 mounted

fix: fix efs-utils test for new images [MD-417]

---

docs/release-notes/pods-to-jobs.rst
docs/setup-cluster/k8s/_index.rst
docs/setup-cluster/k8s/custom-pod-specs.rst
docs/setup-cluster/k8s/helm-commands.rst

RM-258
Include release note & updates to Kubernetes docs for the pods to jobs project.
N/A

 docs: release notes & updates for Kubernetes pods to jobs

---

.bumpversion.cfg

INFENG-724
This changeset removes some unnecessary glob patterns from `.bumpversion.cfg`. The files/directories referenced no longer exist. They examples were first moved to another directory in #8140, and then deleted entirely in #8153.
Look through `model_hub/` and note there is no `examples/` subdirectory, nor is there any Makefile or other automation that subsequently creates it. Additionally, see the two PRs referenced above, and note that the files themselves were moved and deleted.

chore: INFENG-724: Remove model_hub examples from .bumpversion.cfg

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/kubernetesrm/resource_pool_intg_test.go

What it says on the tin.
..but I also renamed `Schedule` to `Admit` because it's not scheduling, just deciding to admit tasks to Kubernetes to be scheduled (and from that, `reschedule` is now `tryAdmitPendingTasks`). My test had a call to schedule followed by an assertion that the job queue's state said we were queued. The name couldn't stand any longer lol.
Has automated testing.

fix: job queue's allocated slots should be correct after restarts

---

webui/react/src/components/InterstitialModalComponent.tsx
webui/react/src/components/RunFilterInterstitialModalComponent.test.tsx
webui/react/src/components/RunFilterInterstitialModalComponent.tsx
webui/react/src/components/RunMoveWarningModalComponent.test.tsx
webui/react/src/components/RunMoveWarningModalComponent.tsx
webui/react/src/hooks/useTypedParams.test.tsx
webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
webui/react/src/setupTests.ts
webui/react/src/utils/mergeAbortControllers.test.ts
webui/react/src/utils/mergeAbortControllers.ts

[ET-94]
this adds an interstitial component for run bulk actions. when opened, it runs a search given the current selection and filters and determines whether or not the selection contains any runs that are part of a search, returning the results to the opener. as a side effect, we pull out the `mergeAbortControllers` helper from `trialDetailsLogs` while also adding test coverage to that helper.
Component is not currently user-facing. Unit tests should comprehensively check functionality.
[ET-94]: https://hpe-aiatscale.atlassian.net/browse/ET-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: …

chore: run bulk action interstitial component

---

agent/.goreleaser.yml
agent/.goreleaser_ee.yml
agent/Makefile
docs/release-notes/deprecate-ppc64
docs/release-notes/deprecate-ppc64.rst
master/.goreleaser.yml
master/.goreleaser_ee.yml
master/Makefile

[[RM-294](https://hpe-aiatscale.atlassian.net/browse/RM-294)]
Deprecate PPC64/POWER builds. Note: This is not just AgentRM specific, but will be deprecated for all RMs 
Potential Impact: Built for a single OSS [~3 years ago](https://determined-community.slack.com/archives/CV37XVAGL/p1617206888020800), haven’t heard of customers using it since. Users can’t use Determined on PPC64 architecture anymore 
Packages with our code do not support power pc. Ok to remove in Q3 / 0.33.1.
Current AgentRM deprecation document linked [here](https://hpe.sharepoint.com/:w:/r/teams/detai/_layouts/15/Doc.aspx?sourcedoc=%7BD5D9B85A-7371-42C5-AAF6-4DAD09D2EF98%7D&file=Pruning%20Under-utilized%20AgentRM%20Features%20(Needs%20Feedback%20for%20Commitment%20of%20Work).docx&action=default&mobileredirect=true).
No …

chore: deprecate PPC64/POWER builds

---

webui/react/src/components/NavigationTabbar.tsx
webui/react/src/components/UserSettings.tsx
webui/react/src/hooks/useFeature.ts

Nav Bar
Tab Bar
Removed `genai` from Experimentals list of features.
[GAS-1016](https://hpe-aiatscale.atlassian.net/browse/GAS-1016)
Removes the user control of turning on/off genai from the Experimental list of features under user settings. The `noUserControl` flag makes the feature purely controlled by the backend `featureSwitches`, where if it is included in there, then it is enabled.
- Check that the `GenAI` feature does NOT show up on the `Experimentals` list of features under user settings.
- Check that url query param `f_genai=true` does not turn GenAI on in an MLDE cluster that does not have genai enabled.
- Check that if the cluster has `genai` returned by the `/master` endpoint (featureSwitches) then it appears in the sidebar.
- Also check that if the cluster does NOT have …

feat: remove genai from experimental feature list and enable via `/master` feature switches [GAS-1016]

---

docs/release-notes/job-state.rst
master/internal/rm/kubernetesrm/job.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/jobs_test.go

[RM-166]
Kubernetes job status on the Cluster Page will correctly reflect the state of workloads. Once all Kubernetes pods are scheduled on nodes, the job state will be reflected as "scheduled" rather than "queued".
None needed.
[RM-166]: https://hpe-aiatscale.atlassian.net/browse/RM-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: job state shows as scheduled when resources are allocated

---

master/.mockery.yaml
master/Makefile

[RM-277](https://hpe-aiatscale.atlassian.net/browse/RM-277)
We are transitioning to using a single mockery configuration file to streamline our mock generation process. Currently, we have 18 individual mockery commands, which are time-consuming. By consolidating these into a single configuration file, we can significantly reduce execution time and improve efficiency.
`make -C master clean`  to delete local mocks
`make -C master check` to generate mocks (also sometimes `make -C master mocks` )
`make -C master test-intg` to make sure mocks are generated right 
ran with `devcluster -c ./.circleci/devcluster/elastic-base.devcluster.yaml`
and confirmed if the devcluster ran fine - `curl -X GET "http://localhost:9200/_cluster/health?pretty"`
See [Release …

chore: switch to mockery config file

---

harness/determined/exec/prep_container.py
master/internal/rm/kubernetesrm/gateway_service.go
master/internal/rm/kubernetesrm/gateway_service_test.go
master/internal/rm/kubernetesrm/gateway_spec.go
master/internal/rm/kubernetesrm/job.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/request_queue.go
master/internal/rm/kubernetesrm/request_workers.go
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go
master/internal/task/allocation.go

Reattach gateways

---

webui/react/src/e2e/README.md
webui/react/src/e2e/tests/experimentList.spec.ts

[TESTENG-4]
no changes, just leaving some hints for whoever continues testing [here](https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1323270145/Experiment+List#Row-Actions)
[TESTENG-4]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: preparing a homework assignment [TESTENG-4]

---

master/internal/rm/kubernetesrm/resource_pool.go

we recently changed k8 submissions from pods to jobs, but this resource summary object doesn't reflect a job containing multiple pods

fix: use num pods in k8 job summary

---

master/internal/api_project.go
master/internal/api_runs.go
master/internal/api_runs_intg_test.go
master/internal/experiment_filter.go

ET-295
Adding missing columns for GetColumns, filter & sort for Run Table
Including new test that checks is all default columns returned have valid sort and filter paths (except tags)
Sort & filter on all columns(except tags) in the Run Table and verify results

fix: run columns mismatching sort/filter columns for run table

---

webui/react/src/components/Searches/Searches.tsx
webui/react/src/pages/FlatRuns/FlatRuns.settings.ts
webui/react/src/pages/FlatRuns/FlatRuns.tsx
webui/react/src/pages/FlatRuns/columns.ts
webui/react/src/pages/SearchDetails.tsx

ET-297
Addresses feedback from Searches View acceptance meeting and other issues
- Change filter criteria from "numTrials > 1" to "searcherType != single"
- Rename "Trials" tab to "Runs"
- On Search Runs, remove "Searcher Type", "Searcher Metric", and "Searcher Metric Value" from default columns
- Make sure Search Runs for a project and the Project Runs view have separate settings (for visible columns, filters, etc)
- Fix bug with back button from Search Runs
- This was an issue in `FlatRuns` related to the handling of the `page` param. Changing pagination in `FlatRuns` to match how its handled in `F_ExperimentList` to avoid this issue
- Make sure Project -> Searches tab only shows experiments with "single" Searcher Type. Can show experiments with only 1 trial. 
- Click the id for a …

fix: Searches view fixes (ET-297)

---

master/internal/api_project_intg_test.go

This reduces the number of requests being made by the `TestConcurrentProjectKeyGenerationAttempts` test to ensure we do not exceed the number of possible project keys given the project name, which was resulting in this test flaking.
- Ensure `TestConcurrentProjectKeyGenerationAttempts` passes

fix: ensure number of project keys possible for testing is not exceeded

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/kubernetesrm/resource_pool_intg_test.go

Error out earlier for Kubernetes clusters when slots requested are not a multiple of `max_slots_per_pod`
On a kubernetes cluster with `max_slots_per_pod` configured as > 1, submit an experiment with `slots_per_trial` as a non-multiple of `max_slots_per_pod` (i.e. `slots_per_trial=2`, `max_slots_per_pod=3`). experiment should error out upon creation. 

chore: check non-multiples of slots per pod for kubernetes rm [MD-403]

---

master/internal/api_trials.go

Remove debug logs that were accidentally committed in a previous PR

chore: remove debug logs that were accidentally committed

---

.circleci/real_config.yml
.circleci/scripts/collect_logs.py

https://hpe-aiatscale.atlassian.net/browse/RM-237
collect and save tasks (currently just first trial of an experiment's) logs as ci artifacts for e2e tests.
adds about 4s to each job.
a quick log size estimate as is: looks like each run the total of all the logs collected today is <10MB
we have about 1300 test-e2e workflow runs each 30 days that adds up to about 13GB of storage use that should auto clear as the artifacts age out
samples: https://app.circleci.com/pipelines/github/determined-ai/determined/56392/workflows/04457f70-98f8-407c-835f-e5bca81a481b/jobs/2630701/artifacts
sample with task logs https://app.circleci.com/pipelines/github/determined-ai/determined/56396/workflows/24e85025-e118-4dd6-b095-301aa6e15dee/jobs/2631032/artifacts …

test: collect det task logs as artifacts for ci jobs

---

.circleci/real_config.yml
e2e_tests/tests/deploy/test_local.py
tools/slurm/scripts/slurmcluster.yaml

Addressing CircleCI test failures on Slurm clusters, Debian package install, and e2e "local" and perf tests.
CI tests pass

ci: fix some failing long-running tests related to password requirements

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go

Going forward, the kubernetes resource manager `name` config is being deprecated and changed to `cluster_name`. This change will change the field used for initialization jobService and resourcePool  from `Name` to `ClusterName` to be consistent with this change.

chore: change cluster name in jobService and resourcePool initialization

---

e2e_tests/tests/cluster/test_proxy.py
master/internal/rm/kubernetesrm/job.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go

chore: remove need for explicit singluar podPort tracking

---

master/internal/rm/kubernetesrm/job.go
master/internal/rm/kubernetesrm/resource_pool_intg_test.go

RM-323
Fixes an issue where we didn't wait for all pod states to make a call about the state of a job.
Has an automated test.

fix: partially scheduled k8s jobs should display as queued

---

docs/model-dev-guide/dtrain/dtrain-introduction.rst
docs/model-dev-guide/hyperparameter/search-methods/_index.rst
docs/release-notes.rst
docs/setup-cluster/slurm/slurm-known-issues.rst
docs/tutorials/pachyderm-cat-dog.rst

docs: Fix broken links

---

master/static/srv/update_aggregated_allocation.sql

DET-10311
Historical allocations weren't showing up sometimes because the data was not present. This can occur when we attempt to calculate the historical allocation for the same date again, violating a constraint and failing the whole transaction. This leads to us repeatedly failing to calculate historical allocation and the data remaining empty. To fix this, we add a clause so that nothing happens when a conflict happens.
No manual testing required.
Testing this is difficult to reproduce, but if you would like to verify, one way is (on your own devcluster) go to `master/internal/db/postgres_cluster.go` line 99 and add `lastDatePtr=nil`. This forces there to be a key conflict. If devcluster runs successfully, then the PR works.
See [Release …

fix: historical allocations not appearing

---

harness/determined/cli/user.py
harness/determined/common/api/authentication.py
webui/react/src/components/DeterminedAuth.tsx
webui/react/src/types.ts
webui/react/src/utils/user.ts

[DET-10216]
CLI: when supplying a password for `det user login` or for another command that fails login and prompts for a password, a warning is displayed if the provided password fails the complexity check.
WebUI: after successfully logging in, if the password is weak, a warning toast notification is displayed.
Automated testing for these cases is uniquely challenging since end-to-end flows that could result in users with weak passwords have been removed -- and if we could find any, we should patch them out rather than exploit them to generate tests for this.
CLI:
- launch a cluster that has a weak/blank password for a user (may need to start with an older version of determined to allow this)
- authenticate as that user with `det user login`, observe warning message.
- delete or mess up …

feat: warn users to change their passwords [DET-10216]

---

docs/model-dev-guide/api-guides/apis-howto/_index.rst
docs/model-dev-guide/prepare-container/_index.rst
docs/model-dev-guide/prepare-container/custom-env.rst
docs/model-dev-guide/prepare-container/tensorflow-support.rst

per customer request
startup-hook.sh does not apply to det cmd. It applies to experiments, notebooks, shells, and TensorBoards, but not commands.

docs: Clarify startuphook

---

webui/react/src/App.module.scss
webui/react/src/components/Page.module.scss

DET-10330
Remove gap at the bottom of webUI pages.
Changed from imageA to imageB (both displayed below).
imageA
imageB
CI passes.

fix: webui page height

---

e2e_tests/tests/cluster/managed_cluster_k8s.py
e2e_tests/tests/cluster/test_agent_disable.py
e2e_tests/tests/cluster/utils.py

Fix flakey test https://app.circleci.com/pipelines/github/determined-ai/determined/57030/workflows/987af866-5aed-4ff1-825d-1c7dcff5deee/jobs/2681147
Images got a lot larger after framework split so increase timeout.
ci passes

test: increase timeouts for running experiments on k8s after env split

---

master/internal/run/runs.go
master/internal/run/runs_test.go

ET-306
When submitting metadata with nested structs (maps/lists) that contain no elements, this would previously cause a 500 response. Instead, this changes that behavior to now treat these instances as leaf nodes for indexing with nil values & stores the metadata as expected.
- Automated test `runs_test.go:TestFlattenMetadataEmptyNestedStructs`

chore: handle empty nested structs in run metadata as nil leaf nodes

---

examples/hf_trainer_api/hf_image_classification/adaptive.yaml
examples/hf_trainer_api/hf_image_classification/const.yaml
examples/hf_trainer_api/hf_image_classification/const_epochs.yaml
examples/hf_trainer_api/hf_image_classification/deepspeed.yaml
examples/hf_trainer_api/hf_image_classification/distributed.yaml
examples/hf_trainer_api/hf_image_classification/image_classification.py
examples/hf_trainer_api/hf_language_modeling/adaptive.yaml
examples/hf_trainer_api/hf_language_modeling/const.yaml
examples/hf_trainer_api/hf_language_modeling/const_epochs.yaml
examples/hf_trainer_api/hf_language_modeling/deepspeed.yaml
examples/hf_trainer_api/hf_language_modeling/distributed.yaml
examples/hf_trainer_api/hf_language_modeling/run_clm.py

[](https://hpe-aiatscale.atlassian.net/browse/MD-439)
Huggingface made a breaking change to their `datasets` repo. Running code locally now requires `trust_remote_code=True` in any API call that does a `load` operation. See https://github.com/huggingface/datasets/releases/tag/2.20.0
This PR adds this flag and sets it to true in our TrainerAPI examples.
CI passes, specifically:
`test-e2e-gpu-distributed` and `test-e2e-gpu-nightly`

fix: Huggingface Trust Remote Repo

---

webui/react/src/e2e/models/BaseComponent.ts
webui/react/src/e2e/models/BasePage.ts
webui/react/src/e2e/tests/experimentList.spec.ts

[testeng-1]
code is base component is commented. the test case in experiment list is updated with it
I doublechecked every case I could think of in the debugger. Luckily, the test scenario has all the use cases I can think of.
Here's what I do when I create an nth element:
* update locator of nth element (clone of original element)
* any properties in nth which have a parent that refer to original get a clone. update the clone parent to the clone and recurse
* any properties in newChild which have a parent that refer to original child get a clone. update the clone parent to newChild clone and recurse
All these things should be working:
```ts
secondRow = row.nth(1)
secondRow.pwlocator
secondRow.A.pwlocator
secondRow.componentWithParentAsA.pwlocator
secondRow.A.directChildOfA.pwlocator …
```

test: det framework supports "nth" component [testeng-1]

---

master/static/srv/notebook-entrypoint.sh

pre-commit lint check fix

---

webui/react/src/components/TaskActionDropdown.tsx
webui/react/src/components/TaskConnectModal.module.scss
webui/react/src/components/TaskConnectModal.tsx
webui/react/src/components/TaskList.tsx
webui/react/src/types.ts

Adds a modal that displays connect options for active shell and notebook tasks.
1. start a shell or notebook task. 
2. verify that there is a "Connect" option in the task dropdown
3. Connect should open a modal that contains:
- remote server address for jupyter notebook
- `det shell open ID` command for shells
4. verify that clipboard functionality works

feat: add connect modal for notebook and shell tasks [MD-404]

---

docs/release-notes/deploy-local-auto-password.rst
e2e_tests/tests/deploy/test_local.py
harness/determined/deploy/local/cluster_utils.py

[DET-10197]
BREAKING CHANGE: if an initial user password is not specified, the `det deploy local` command generates one automatically; if that random password is recognized as the correct one for `determined`, it is printed so users can log in with it and change their password. Otherwise, it is assumed that this is a relaunch of a cluster with an existing database.
The proposal for this change was first described here: https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1716571996243779?thread_ts=1716404697.160779&cid=CLCE8D998
`det deploy aws` and `det deploy gcp` can rely on Terraform state to determine whether a database (or database image) already contains passwords, and prompt interactively if not, and `helm` can run some simple checks during templating. However, `det deploy local` …

feat: det deploy local generates a password for you [DET-10197]

---

webui/react/src/components/DeterminedAuth.tsx

[DET-10216]
Think I accidentally resolved a rebase conflict incorrectly when I merged #9519 . This restores a missing `if` statement so the toast doesn't just display every single time.
Noticed and fixed during acceptance review with @hkumar92 
Same as #9519 
[DET-10216]: https://hpe-aiatscale.atlassian.net/browse/DET-10216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: hide warning for weak password unless it actually applies [DET-10216]

---

docs/_shared/basic-installation.txt
docs/_shared/note-pip-install-determined.txt
docs/model-dev-guide/api-guides/apis-howto/api-core-ug.rst
docs/setup-cluster/_index.rst
docs/setup-cluster/on-prem/options/wsl.rst
docs/tutorials/pachyderm-cat-dog.rst
docs/tutorials/quickstart-mdldev.rst

Docs for https://github.com/determined-ai/determined/pull/9518/files
* Test that the [quick installation](https://docs.determined.ai/latest/get-started/basic.html#step-2-install-determined) steps are reproducible
* Test that messages display as expected and that docs steps match the experience
* Test all local install and password-related messages in the _shared docs directory to see that they match the user experience

docs: Describe local password sec

---

master/internal/api_project.go
master/internal/api_project_intg_test.go
master/internal/project/postgres_project.go

ET-305
Adds validation on project keys when making PatchProject requests. 
- Automated test pass (`TestPatchProjectWithInvalidProjectKey`)

fix: add validation to patching project key (ET-305)

---

master/internal/project/postgres_project.go

ET-301
This adds missing columns to the workspace model query.
* `getProject` payload should have `workspaceName` and `createdAt` present and correct.
* when viewing a project, the workspace breadcrumb should be present.

fix: add missing columns to workspace response [ET-301]

---

webui/react/src/pages/ProjectDetails.tsx

ET-310
With Flat Runs feature flag on, make "Runs", "Searches", "Notes" tabs visible on the Uncategorized page.
With Flat Runs feature flag on, on Uncategorized page:
- "Runs" tab appears with runs for uncategorized project
- "Searches" tab appears with searches for uncategorized project
-  "Notes" tabs appears, can add/edit/delete notes for uncategorized project

feat: add tabs to Uncategorized page (ET-310)

---

master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go
master/internal/rm/kubernetesrm/resource_pool_intg_test.go
master/internal/rm/resource_manager_iface.go

[RM-350]
The Kubernetes resource manager caches the response to a `GetAgents` request. Return a deep copy of the cached response to prevent unintentionally modifying the cached response.
[RM-350]: https://hpe-aiatscale.atlassian.net/browse/RM-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: do not modify cached GetAgentsResponse

---

e2e_tests/tests/experiment/test_allocation_csv.py
master/internal/command/command.go
master/internal/command/command_intg_test.go
master/internal/core.go
master/internal/task/postgres_allocations.go
master/internal/task/postgres_allocations_intg_test.go
master/internal/trial.go
master/internal/trial_intg_test.go
master/pkg/model/task.go
master/pkg/model/workspace.go
master/static/migrations/20240617155550_add-allocation-workspace-table.tx.up.sql

DET-10378
Creates `allocation_workspace_information` table, responsible for persisting workspace id/name & experiment id for historic allocation reports. Adds new entries on successful creation of allocation for trials & NTSC tasks.
Backfills table using existing process used to retrieve workspace & experiment information for the historic allocation CSV endpoints.
Modifies logic for historic allocation report to leverage  `allocation_workspace_information` instead of resolving based on current state. 
Modifies existing e2e test to confirm workspace name is consistent when experiments are moved & deleted. 
- e2e test passes
[DET-123]: …

fix: persist workspace id/name & experiment id for historic allocations [DET-10378]

---

docs/release-notes/idle.rst
master/static/srv/check_idle.py

MD-447
Notebooks were not terminated due to idleness because the master would parse the payload as having `idle: false` regardless of what the `check_idle.py` was trying to report. 
I suspect at some point in refactoring the `Sessions` and related code, this `PUT` switched from json payload to body, and master just could not parse out the boolean out of it.
1. Start a notebook with `det notebook start --config idle_timeout=5m`
2. wait for notebook to open.
3. close the notebook. don't do anything in it, especially do not launch kernels! or, if you do, use a different `notebook_idle_type` value.
4.  wait for 5m
5. notebook should get terminated
[DET-123]: …

fix: wrong notebook idleness payload [MD-447]

---

webui/react/src/components/FilterForm/components/ConjunctionContainer.test.tsx

[ET-201]
Add `ConjunctionContainer` test cases
- CI passes
- coverage should be more than 80% (ConjunctionContainer component)
[ET-201]: https://hpe-aiatscale.atlassian.net/browse/ET-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: add `ConjunctionContainer` test cases

---

.circleci/real_config.yml

N/A - circleci fix
Adds a missing security property to yaml for a slurm agent test
N/A

test: add missing initial_user_password value to circleci config

---

webui/react/src/pages/WorkspaceDetails.tsx

Projects (under workspaces) modals get closed randomly when in list view and RBAC enabled. This change band-aids the problem by making sure the problematic code doesn't get called unless it has to.
1. Open devcluster with this version + RBAC enabled.
2. Create two workspaces (A and B), and inside workspace A create a project (A1).
3. Navigate to workspace A and show a list view of projects
4. In the list view, click on the project actions for A1 and select the move action
5. Before selecting the destination workspace, wait 5-10 seconds. Make sure the modal does not disappear in this time period.
6. Select the destination workspace and continue. The workspace should be moved properly.
7. Next, navigate to the workspace B and show a list view of the projects. You should see A1 there.
8. …

fix: edit/move modals for projects in workspaces unexpectedly closes [DET-10388]

---

agent/internal/containers/manager.go
master/.golangci.yml
master/internal/api/api_test.go
master/internal/api_checkpoint.go
master/internal/api_experiment.go
master/internal/checkpoint_gc.go
master/internal/db/postgres_tasks_intg_test.go
master/internal/db/postgres_trial_profiler_metrics.go
master/internal/experiment.go
master/internal/rbac/rbac_intg_test.go
master/internal/rm/agentrm/agent_state_test.go
master/internal/rm/agentrm/agents.go
master/internal/rm/agentrm/provisioner/aws/aws.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/multirm/multirm.go
master/internal/rm/multirm/multirm_intg_test.go
master/internal/rm/rmevents/rmevents_test.go
master/internal/task/tasklogger/logger_test.go
master/pkg/model/agent_user_group.go
master/pkg/schemas/expconf/schema_test.go
master/pkg/searcher/grid_test.go
master/pkg/searcher/util_test.go

Go 1.22 had a language change which fixed a common foot gun in Golang. https://go.dev/blog/loopvar-preview
Update our linters to allow you to write code like this 
```
for _, exp := range experiments {
go func() {
doSomething(exp)
}()
}
```
CI passes

chore: change linters to handle Go 1.22 loopvar change [RM-353]

---

e2e_tests/tests/run/test_api.py

Fix flake in Pause/Resume test

fix: Pause/Resume run test flake

---

docs/setup-cluster/checklists/_index.rst
docs/setup-cluster/checklists/postgresql-setup-guide.rst
docs/setup-cluster/checklists/postgresql.rst

replaces: #9586
audience: admin
purpose: users often miss important information including the recommended configuration for max_connections and other settings for bigger deployments
since this links from the "advanced installation" guide it is appropriate to move the content to its own page

docs: Improve postgreSQL setup

---

webui/react/playwright.config.ts
webui/react/src/e2e/README.md
webui/react/src/e2e/fixtures/api.auth.fixture.ts
webui/react/src/e2e/fixtures/auth.fixture.ts
webui/react/src/e2e/fixtures/dev.fixture.ts
webui/react/src/e2e/fixtures/global-fixtures.ts
webui/react/src/e2e/tests/auth.spec.ts
webui/react/src/e2e/tests/experimentList.spec.ts
webui/react/src/e2e/utils/detCLI.ts
webui/react/src/e2e/utils/envVars.ts

[TESTENG-49]
autouse dev setserveradress
move env var config to a file
rename env vars, check the readme
[TESTENG-49]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: env variable config and automatic setServerAddress [TESTENG-49]

---

e2e_tests/tests/experiment/test_metrics.py
harness/determined/common/api/_rbac.py

`flake8-comprehensions` was updated from 3.14.0 to 3.15.0 over the weekend. Some of the code couldn't pass lint check.
CI passes.

fix: lint issue from flake8-comprehensions 3.15.0

---

master/.golangci.yml

Switch to a allow list approach on Go linters rather than the deny list approach we took.
Linters list made with ```golangci-lint linters```
CI passes, make sure linters still work by checking bad code gets caught 

chore: stop enabling all in Go linters [RM-346]

---

webui/react/src/components/ProjectCard.test.tsx
webui/react/src/components/ProjectCard.tsx
webui/react/src/types.ts

ET-314
ProjectCard should display runs count instead of experiments count when Flat Runs feature flag is on.
With Flat Runs feature flag on 
- ProjectCards on dashboard should display number of runs, and the tooltip should say "runs" on hover
- Same on Workspace Details pages
With Flat Runs feature flag on, they should still show experiments.

fix: display runs count in ProjectCard (ET-314)

---

.bumpversion.cfg
webui/react/vite.config.mts

build: INFENG-739: remove hardcoded version from Vite config
INFENG-739
* Replace the process.env.VERSION variable explicitly defined in vite.config.mts with either the actual VERSION environment variable, if it's set, or the most recent git tag, followed by an optional commit counter and partial unique SHA hash. This shells out to git, and also accounts for the rare but possible case that the config is being used from outside of a git repository. In that situation, the version string is useless anyway, so we return "unknown" from the shell.
* During the release, we will set VERSION ourselves based on the tag, so we don't have to go over the top trying to parse it out here. The local version doesn't matter too much, either, as it's only referenced during development, and, as far as I can …

build: INFENG-739: remove hardcoded version from Vite config

---

docs/model-dev-guide/api-guides/apis-howto/deepspeed/deepspeed.rst

Replaces #9521 
This change adds a link to the new FSDP / Core API example in the examples repo.

docs: Add link to FSDP example

---

harness/setup.py

https://hpe-aiatscale.atlassian.net/browse/MD-415
Python `requests` library update broke the `docker` python library. `docker` has since fixed the issue. See: https://github.com/docker/docker-py/pull/3257
CI passes

fix: docker version bump to unpin requests

---

.circleci/real_config.yml

also ensures the steps run when the tests fail
make the tests fail to see the logs get collected https://github.com/determined-ai/determined/pull/9537/commits/469c6d68893a8abab28cc1301b460b1f0a5be01a

test: collect det job ci logs only in case of failure

---

webui/react/src/pages/FlatRuns/FlatRuns.tsx

[ET-605]
In Runs view, with comparison mode on, Columns selection should reflect pinned columns (the only visible columns in comparison mode). This makes it consistent with the current behavior on the Experiments view.
- open Runs table
- open Column menu, see all visible columns are checked
- open Compare view
- open Column menu, see only pinned columns are checked
- check a column, it should get pinned
- uncheck a column, it should be unpinned
- close Compare view
- unchecked column should still be visible, just not pinned
- open Column menu, all visible columns should be checked
[ET-605]: https://hpe-aiatscale.atlassian.net/browse/ET-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …

fix: column picker should effect pinned columns in compare view [ET-605]

---

webui/react/src/e2e/models/README.md

[INFENG-767](https://hpe-aiatscale.atlassian.net/browse/INFENG-767)
appreciation for glouie
[INFENG-767]: https://hpe-aiatscale.atlassian.net/browse/INFENG-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: chore: add gratitude to test page model readme [INFENG-767]

---

webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/types.ts
webui/react/src/utils/experiment.ts

[MD-437]
Allow user to continue multi-trial experiments if applicable. 
Multi-trial experiments that are able to continue must satisfy the following criteria:
- The searcher type is random or grid
- The state is cancelled or errored  
Navigate the the experiment details page of a multi trial experiment, if the experiment is not able to continue, then the `Continue Trial` button should not be available.
Find a multi-trial experiment with `Continue Trial` button, clicking on the button will continue the experiment.
https://github.com/determined-ai/determined/assets/40620519/d17325ed-96f1-4170-a9df-c090cc5669a2
[MD-437]: …

feat: continue trial from WebUI for multi-trial experiment

---

webui/react/src/components/RunActionDropdown.test.tsx
webui/react/src/components/RunActionDropdown.tsx
webui/react/src/pages/FlatRuns/FlatRunActionButton.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/types.ts
webui/react/src/utils/flatRun.test.ts
webui/react/src/utils/flatRun.ts

[ET-293]
Support pause/unpause in flat run table
> In context menu, if you run is part of a search it should be disabled. In bulk actions dropdown, we send request unmodified, and we need to interpret error where trial is part of a multi trial and raise it as part of a toast.
from [ET-293]
- Pause/Unpause should work in the context menu and bulk action
[ET-293]: https://hpe-aiatscale.atlassian.net/browse/ET-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: pause unpause UX

---

harness/determined/common/api/bindings.py
master/internal/api_project.go
master/internal/api_project_intg_test.go
proto/pkg/apiv1/api.pb.go
proto/pkg/apiv1/api.pb.gw.go
proto/pkg/apiv1/project.pb.go
proto/src/determined/api/v1/api.proto
proto/src/determined/api/v1/project.proto
webui/react/src/services/api-ts-sdk/api.ts

ET-226
Add getMetadataValues endpoints which fetches all unique metadata values for a given key in a given project. This only applies to metadata values that are string typed.

feat: add getMetadataValues for projects

---

harness/determined/cli/render.py
harness/determined/cli/user.py
harness/determined/common/api/authentication.py

we'd probably want a shared path for all cli warnings. we have deprecation warnings and probably other warning classes as well
or maybe use https://docs.python.org/3/library/exceptions.html#UserWarning ? 
`det u logout; det e ls > /dev/null`

chore: set cli pwd warning go to stderr

---

harness/determined/cli/workspace.py
helm/charts/determined/templates/master-permissions.yaml
master/internal/api_workspace.go

DET-10385, DET-10386
This PR fixes the following issues:
- API requests for single RM only work when the cluster name is specified in the request
- Autocreate panic is not handled when attempted with OSS
- Some lint issues after feature branch rebase with main
- Autocreating namespace fails given workspace whose name doesn't match the accepted namespace regex pattern.
Spin up a single RM kubernetes EE cluster to execute the test plan.
To test API requests for single RM, run the following commands and make sure that they work:
- `det w create ws1 --auto-create-namespace`
- `det w create ws2 && det w bindings set ws2 --namespace default`
- `det w create ws3 --namespace default`
- `det w create ws4 && det w bindings set ws4 --auto-create-namespace`
To test auto-create panic handled …

fix: API requests with single RM and recover from panic during unauthorized autocreate

---

webui/react/src/components/HyperparameterSearchModal.module.scss

[ET-308]
https://github.com/determined-ai/determined/assets/109113616/a98f37a3-a9e0-40fd-92df-7c3dced26eaf
- open hyperaparatmeter search in experiment detail page
- Check if the vavlue table does not overflow when the page is narrow and in mobile view
[ET-308]: https://hpe-aiatscale.atlassian.net/browse/ET-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: overflow in hyperparameter modal

---

webui/react/src/components/WorkspaceCreateModal.tsx

The resource quota input field is now visible even if the auto-create namespace toggle is off, but it is greyed out. Also added a min of 0 to the resource quota counter
- Verify that the resource quota input field is visible and greyed out when autocreate toggle is off and editable when autocreate toggle is on.
- Verify that the counter for resource quota does not go below 0

feat:  allow resource quota input field to be visible at all times

---

e2e_tests/tests/deploy/etc/agent.yaml

[RM-373]
Remove `label` from agent config used in ci tests. `label` was deprecated in 0.20.0 and removed in https://github.com/determined-ai/determined/pull/9609.
ci tests pass
[RM-373]: https://hpe-aiatscale.atlassian.net/browse/RM-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: remove deprecated label from agent config

---

.circleci/real_config.yml
.circleci/scripts/job_level_alerts.py

https://hpe-aiatscale.atlassian.net/browse/RM-372
adding a condition to skip over workflows that have elapsed their timeout instead of reporting them as active.
make sure send alerts does not:
send-alert job:
1. takes too long 5hrs in these cases
2. does not fail if another ci job takes long
this job has been staying active for 5hours
https://app.circleci.com/pipelines/github/determined-ai/determined/57843/workflows/1a75f6bf-77b2-45e5-8155-9f2f5dcc96c4/jobs/2742238
testing the timeout https://app.circleci.com/pipelines/github/determined-ai/determined/58023/workflows/53afd482-abd0-403a-9346-0de85400e533/jobs/2756232
context https://hpe-aiatscale.slack.com/archives/C04C9JXB1C2/p1720448458815989 …

chore: send alerts can wait forever and fail for broken workflows

---

docs/manage/historical-cluster-usage-data.rst
docs/reference/experiment-config-reference.rst
docs/release-notes/relabel-allocation-csv.rst
master/internal/core.go

Waiting on acceptance or response to https://hpe-aiatscale.atlassian.net/browse/DET-10408?focusedCommentId=32936
[DET-10408]
Renames the `gpu_hours` column in the allocation report CSV to `slot_hours` as this is a more accurate description. Adds a `resource_pool` column to help users identify what slot type(s) these slot-hours apply to.
Run any number of experiments >0 on a cluster that has at least one slot configured.
On cluster historical usage tab, make sure the end date is current, and click Download CSV.
Choose to group by Allocations and download the CSV
Observe `slot_hours` and `resource_pool` columns are present in the download
[DET-10408]: …

fix: allocation csv: gpu_hours -> slot_hours, add resource_pool [DET-10408]

---

webui/react/src/components/HyperparameterSearchModal.module.scss
webui/react/src/components/HyperparameterSearchModal.tsx

[MD-402]
Allow user to add or remove hyperparameters when creating experiment through HP search
Navigate to `Hyperparameters` tab of an experiment, click on the `Hyperparameters Search` button
When selecting hyperparameters, add and remove hyperparameters
Click on the `Run Experiment` button to create a experiment
Verify that the new experiment is using the updated hyperparameters 
https://github.com/determined-ai/determined/assets/40620519/a7e9d907-cd27-4a57-8932-78874eaefbae
[MD-402]: https://hpe-aiatscale.atlassian.net/browse/MD-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: …

feat: Add/remove HPs when creating experiment through HP search

---

helm/charts/determined/templates/genai/genai-deployment.yaml

[GAS-1112] (part of [GAS-1111])
Populate image pull secrets on k8s deployments correctly. Passing it in the environment variables allows the genai backend to create experiments with the secret bound.
Does not need to be tested in release party.
[GAS-1111]: https://hpe-aiatscale.atlassian.net/browse/GAS-1111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GAS-1112]: https://hpe-aiatscale.atlassian.net/browse/GAS-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

feat: support image pull secrets in genai

---

harness/determined/deploy/aws/templates/efs.yaml
harness/determined/deploy/aws/templates/fsx.yaml
harness/determined/deploy/aws/templates/govcloud.yaml
harness/determined/deploy/aws/templates/lore.yaml
harness/determined/deploy/aws/templates/secure.yaml
harness/determined/deploy/aws/templates/simple-rds.yaml
harness/determined/deploy/aws/templates/simple.yaml

If you investigate the Cloudformation stacks on AWS, the `DockerPass` field is in plain text. This hides it by doing the same thing we are doing for `DBPassword`
Not needed to be tested in release party.

chore: hide the docker password in cloudformation stacks

---

harness/determined/cli/resources.py

feat: Add resources allocation-csv to det cli [DFR-519]
[DFR-519]
Add feature to det cli to allow query of resources allocation-csv endpoint.
run `det res all 2024-07-12T00:00:00 2030-01-01T00:00:00` and see that you get output.
- [Y] Changes have been manually QA'd
- [N] New features have been approved by the corresponding PM
- [N/A] User-facing API changes have the "User-facing API Change" label
- [N] Release notes have been added as a separate file under `docs/release-notes/`
- [N/A] Licenses have been included for new code which was copied and/or modified from any external code
[DFR-519]: https://hpe-aiatscale.atlassian.net/browse/DFR-519?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

feat: Add resources allocation-csv to det cli [DFR-519]

---

docs/release-notes/historic-usage-chart-timezones.rst
webui/react/src/pages/Cluster/ClusterHistoricalUsage.settings.ts
webui/react/src/pages/Cluster/ClusterHistoricalUsage.tsx
webui/react/src/pages/Cluster/ClusterHistoricalUsageChart.tsx
webui/react/src/pages/Cluster/ClusterHistoricalUsageCsvModalComponent.tsx
webui/react/src/pages/Cluster/ClusterHistoricalUsageFilters.tsx

DET-10407
An escalation was reported that the data being presented in the historic usage charts was excluding expected start & end dates of the provided range. This adjusts the terminology in the frontend & query parameters to be reflective of this inclusion. 
Additionally, this PR adjust the `Date.parse()` call for the X axis on the Historic Usage Charts to ensure that the comparison between times is done based on the local timezone, so that when the information is rendered in the Line Chart all communicated information is visible.
- Navigate to the `Cluster` tab
- Ensure that the selected dates are included in the charts:
- Examples:
- Monthly, From: '2024-01', To: '2024-02', should include data points for '2024-01-01' & '2024-02-01'
- Daily, From: '2024-01-01', To" '2024-02-01', should …

fix: ensure historic usage charts assume the correct timezone (DET-10407)

---

harness/determined/common/storage/base.py
harness/determined/common/storage/cloud.py
harness/determined/common/storage/shared.py
harness/determined/core/_checkpoint.py
harness/tests/core/test_checkpoint.py

make sharded checkpoint uploads with `store_path` check for file conflicts across workers before upload.

fix: upload non-conflicting files for sharded checkpointing [MD-298]

---

master/internal/api_notebook.go
master/internal/command/command_intg_test.go
master/internal/command/command_service.go
master/internal/db/postgres_notebook_sessions.go
master/internal/user/postgres_users.go
master/internal/user/service.go
master/pkg/model/notebook_session.go
master/pkg/tasks/task_command.go
master/static/migrations/20240709125620_notebook-sessions-by-user.tx.up.sql

[MD-453]
SaaS / managed deployments do not persist user sessions into the user_sessions table which prevents notebook tokens from being generated. Instead of hacking around different codepaths for managed vs unmanaged deployments, this fix changes notebook sessions to associate with users instead of user sessions, since we always persist users.
Also removes some unnecessary fields.
Make sure notebooks can start successfully. On the task list page and task dropdown, clicking "Connect" should open a modal that displays a URL with a token. 
[MD-453]: https://hpe-aiatscale.atlassian.net/browse/MD-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

fix: user IDs instead of user session IDs for notebook sessions [MD-453]

---

.circleci/real_config.yml

[RM-311](https://hpe-aiatscale.atlassian.net/browse/RM-311)
Missed removing one agent nightly test.
Main PR with description- https://github.com/determined-ai/determined/pull/9516
No test plan needed
[RM-311]: https://hpe-aiatscale.atlassian.net/browse/RM-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove singularity agent znode nightly test

---

docs/setup-cluster/k8s/internal-task-gateway.rst

docs: expand det abbreviation in docs

---

docs/model-hub-library/_index.rst

docs: Model hub library docs

---

docs/model-hub-library/_index.rst
docs/release-notes/model-hub-deprecation.rst
model_hub/model_hub/huggingface/_trial.py
model_hub/model_hub/mmdetection/_trial.py

https://hpe-aiatscale.atlassian.net/browse/MD-32
#9666 
Officially deprecate Model Hub with removal planned in the next release.
None

chore: Deprecate model hub

---

webui/react/src/components/LoadableCount.module.scss
webui/react/src/components/LoadableCount.test.tsx
webui/react/src/components/LoadableCount.tsx
webui/react/src/components/TableActionBar.module.scss
webui/react/src/components/TableActionBar.tsx
webui/react/src/e2e/models/components/TableActionBar.ts
webui/react/src/e2e/tests/experimentList.spec.ts
webui/react/src/pages/FlatRuns/FlatRuns.settings.ts
webui/react/src/pages/FlatRuns/FlatRuns.tsx

Add the selection label to the flat runs table.
Also includes fix for bug with "Select all" action
- Enable the Flat runs feature
- go to a runs table
- there should be a label with the total number of runs
- make a selection
- the label should be updated accordingly 
[ET-252]: https://hpe-aiatscale.atlassian.net/browse/ET-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ET-309]: https://hpe-aiatscale.atlassian.net/browse/ET-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

feat: Add selection label to FlatRuns page (ET-309)

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go

DET-10326
Validate if default namespace provided in the master config for a K8 RM, exists at master start up

chore: validate default namespace for kubernetes RM

---

harness/determined/transformers/_hf_callback.py

raise an exception to exit training if searcher units do not match units passed into HF trainer. 
in `examples/hf_trainer_api/hf_language_modeling/const.yaml` change searcher.max_length.batches to 101, submit the experiment and make sure it errors out

chore: raise exception in HF trainer for mismatched train units [MD-456]

---

docs/setup-cluster/k8s/setup-multiple-resource-managers.rst
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/job.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/resource_pool_intg_test.go
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go

Add a ```determined_master_scheme``` to help this case
https://hpe-aiatscale.slack.com/archives/C06K1CD0DMW/p1721244178479199?thread_ts=1721243514.575999&cid=C06K1CD0DMW
The idea is defaulting based off the TLS config is not right in the multirm case because the within cluster likely won't use TLS while the external cluster might connect to master through a gateway.

chore: add `determined_master_scheme` for K8s multirm

---

webui/react/src/components/FilterForm/components/FilterFormStore.test.ts
webui/react/src/components/FilterForm/components/FilterFormStore.ts

[ET-600]
#9509 removed the default columnName.
the filter form UI has been broken, so fixed it. Used `id` because thats the common column among the new experiment table, flat run table, search table. 
- open the filter form and clear it and see the default value is set
[ET-600]: https://hpe-aiatscale.atlassian.net/browse/ET-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: default value in filter form

---

master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
webui/react/src/components/WorkspaceCreateModal.tsx

… validation
DET-10418
DET-10432
Fixed the error toasts from the KubernetesRM endpoint that appear for non-cluster admins and fixed the failing build when a default namespace isn't supplied in the additional RM config and default to the default ns
1. Open devcluster.yaml in tools/k8s. Comment out the default_namespace field under resource_manager.
2. spin up a minikube devcluster using.
3. Make sure that master builds without an error.
4. login with non-admin account.
5. Go to workspaces page and make sure there aren't getKubernetesResourceManager errors showing up.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

fix: fixed getKubernetesResourceManager error in webui and default ns validation

---

e2e_tests/tests/cluster/test_master_restart.py
master/internal/trial.go
master/internal/trial_intg_test.go

RM-368
When a cluster restarts, it restarts running trials. For large experiments with several trials (like a hyperparameter experiment), some of these restored trails end up in STOPPING_COMPLETED indefinitely versus COMPLETED state. Fix this bug.
I was able to reproduce this on AWS by killing the agent service, stopping the master service, and then restarting them both. WIth my fix, the experiments naturally resolved themselves.
See new e2e test. No additional testing needed.

fix: resolve indefinitely queued (STOPPING_COMPLETED) trials

---

docs/reference/experiment-config-reference.rst

How to access user data
Problem: it isn't clear what the interface is to access the values from inside the model code. 
Users can call their own arbitrary user_data from the Experiment Configuration file. This would be things like data sources and containers or even credentials (which are obscurable). To do this, the user uses `data` (not `metadata.data`) in the Experiment configuration yaml file. Which is documented [here](https://docs.determined.ai/latest/reference/experiment-config-reference.html#data). However, it is not clear how Determined accesses the values of this user data from inside the model code.
Solution:
Help users understand that the way to access the data:
https://docs.determined.ai/latest/reference/experiment-config-reference.html#data ... 
is here …

docs: Link to cluster info

---

master/internal/api_workspace.go

Auto-created namespaces were not being recorded as autocreated in the db when the user inputted them manually. Fixed the issue.
1. spin up a k8 cluster on minikube with EE.
2. Try to create a workspace with the autocreate toggle on.
3. Open the edit workspace modal and copy the name of the auto created namespace.
4. turn the toggle off for the autocreate ns and input default as the ns and save.
5. open the edit workspace modal and paste the autocreated ns name and save.
6. open the edit workspace modal and verify that the autocreated toggle is on.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

fix: add autocreate as true to db when user inputs autocreated ns manually

---

webui/react/src/components/OverviewStats.tsx
webui/react/src/pages/TrialDetails/TrialInfoBox.test.tsx
webui/react/src/pages/TrialDetails/TrialInfoBox.tsx

[ET-638]
Blue color link instead of white link for `Data Input` card to let users know its clickable
- `Data Input` card should have blue link in the experiment detail page
- `Data Input` instead of `Data input`
[ET-638]: https://hpe-aiatscale.atlassian.net/browse/ET-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: highlight `Data Input` link

---

webui/react/src/components/MultiSortMenu.tsx
webui/react/src/e2e/models/components/MultiSortMenu.ts
webui/react/src/e2e/tests/experimentList.spec.ts

[INFENG-766]
This is the example I gave during my dev presentation. It's good to have this on main because we'll be closer to running correctly against shared environments.
[INFENG-766]: https://hpe-aiatscale.atlassian.net/browse/INFENG-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: experiment list sort [INFENG-766]

---

.bumpversion.cfg
.devcontainer/server.sh
.github/workflows/lint-python.yml
Makefile
agent/Makefile
docs/Makefile
docs/conf.py
docs/deploy/Makefile
docs/deploy/scrape.py
docs/deploy/upload.py
harness/Makefile
harness/pyproject.toml
harness/setup.py
helm/Makefile
master/Makefile
model_hub/Makefile
model_hub/pyproject.toml
model_hub/setup.py
requirements.txt
version.sh

INFENG-744
* Remove dependency on static `VERSION` file and replace it with a bash
script, version.sh, that either fetches the version from git tags,
usually used for local builds, or returns an existing environment
variable, mainly used in CI.
* The script uses a few different git tools to find the most recent
previous tag for a given commit, a combination of git-describe,
git-tag, and git-merge-base. Additional implementation details are
available in the comments in that file. The resulting version, though,
is `<prev-tag>+<HEAD-short-SHA>`. This ensures that certain Python
dependency constraints are able to be satisfied when building
Determined locally. Otherwise, if `VERSION` is already set, as will be
the case in CI, the script simply returns that instead.
* Replace existing `cat`s of …

build: INFENG-744: remove VERSION file

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go

ET-86
Experiments/Searches in "deleting" state appear in tables. This causes confusing behaviour where a deleted experiment gets removed then re-appers in the table until it gets deleted.
With Flat Run Flag On:
1. Go to Searches tab in run table
2. Select one or multiple searches
3. Delete them and confirm that the search is removed
With Flat Run Flag Off:
1. Go to Experiments table
2. Select one or multiple experiments
3. Delete them and confirm that the experiment is removed

fix: Remove experiments immediately after deleting by filtering out deleting experiments

---

CONTRIBUTING.md
docs/setup-cluster/checklists/postgresql.rst
docs/setup-cluster/on-prem/options/docker.rst
docs/setup-cluster/on-prem/options/linux-packages.rst

Update docs to use postgreql 14 instead of 10. Also explicitly state that any version later than 10 is supported.
N/A

docs: use postgres 14 in code snippets.

---

master/internal/api_workspace.go

No ticket. 
single RM resource quota no cluster name error
CI passes

fix: single RM resource quota no cluster name error

---

harness/determined/cli/workspace.py

No ticket
CLI set resource quota during workspace create with non-auto-created namespace
CI passes

fix: CLI set resource quota during workspace create with non-auto-created namespace

---

e2e_tests/tests/cluster/test_workspace_org.py
harness/determined/cli/workspace.py
master/internal/api_workspace.go

DET-10423
DET-10425
Add additional test cases for auto-creating namespaces & setting resource quotas when creating a workspace in a cluster using multi/single K8s resource managers.
- N/A (ensure these tests pass)

chore: add auto-create namespace & set resource quota test cases for workspace_namespace bindings

---

master/internal/api_workspace.go
master/internal/api_workspace_intg_test.go
master/internal/db/postgres_rbac_intg_test.go
master/internal/workspace/authz_basic_impl.go

DET-10421
Unit tests for set resource quota permissions as ClusterAdmin for RBAC and as Deterimed Admin for OSS.
CI Passes.

chore: unit tests for set resource quota perms

---

master/internal/api_workspace.go

fix: set rq errors

---

.circleci/real_config.yml
e2e_tests/tests/cluster/test_workspace_org.py

No ticket.
~End-to-end tests in the long-running workflow use clusters from an isolated GCP project that doesn't have vast visibility, making them difficult to use for multiRM / multi-cluster testing. The shared cluster(s), having better visibility and long-standing setups, are more usable for multiRM testing. Filter out multiRM tests from long-running tests and run any necessary multiRM  end-to-end GKE tests in the shared cluster workflow.~
While the shared cluster workflow is removed from CI, remove the`e2e_gpu` mark from the workspace-namespace binding e2e tests as we use a different mark, `test_e2e_single_k8s`, for the singleRM tests.
CI passes (particularly, long-running workflow passes) …

chore: longrunning tests to ignore multiRM marked e2e tests

---

tools/slurm/scripts/slurmcluster.sh

chore: makeslurm option reference to workload manager

---

e2e_tests/tests/cluster/test_workspace_org.py

Remove workspace-namespace binding tests from AWS test runs.
CI passes.

fix: remove mark from aws tests

---

e2e_tests/tests/cluster/test_proxy.py
e2e_tests/tests/cluster/test_resource_manager.py
master/internal/core_experiment.go
master/pkg/model/experiment_config.go

MD-454
`Slots` is not a valid key in the experiment config. It's required in `ResourcesConfigV0` for [compatibility with older resource config](https://github.com/determined-ai/determined/blob/main/master/pkg/model/compat.go#L28-L46). 
I also reviewed other fields in [interactive job configuration](https://docs.determined.ai/latest/reference/job-config-reference.html#command-notebook-configuration)(NTSC). `Slots` is the only field that in the interactive job configuration and shares the same struct with experiment, but it is not valid for use in the experiment config.
CI passes.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …

fix: disallow slots in exp config [MD-454]

---

docs/release-notes/wksp-slot-caps-webui.rst

chore: add release notes for workspace slot caps

---

docs/release-notes/run-centric-ux.rst
webui/react/src/components/ProjectCard.test.tsx
webui/react/src/e2e/fixtures/global-fixtures.ts
webui/react/src/hooks/useFeature.ts
webui/react/src/pages/ExperimentDetails/ExperimentDetails.test.tsx

ET-636
This defaults the flat runs view to on while also adding release notes
* clear your settings
* go to the uncategorized project page
* you should see the flat runs view

chore: default flat runs to on

---

webui/react/src/components/CompareMetrics.tsx
webui/react/src/components/ComparisonView.test.mock.tsx
webui/react/src/components/ComparisonView.test.tsx
webui/react/src/components/ComparisonView.tsx
webui/react/src/components/RunFilterInterstitialModalComponent.tsx
webui/react/src/components/Searches/Searches.settings.ts
webui/react/src/components/Searches/Searches.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.settings.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/FlatRuns/FlatRuns.settings.ts
webui/react/src/pages/FlatRuns/FlatRuns.tsx
webui/react/src/types.ts
webui/react/src/utils/experiment.ts
webui/react/src/utils/flatRun.ts

ET-189
Even if selected experiments/runs are not loaded on the current page, the Compare panel should still fetch data for them.
On Experiments List page (with "New Experiment List" feature flag on):
- Select an experiment
- Open the "Compare" view
- Change the page
- Should display "Metrics", "Hyperparameters", and "Details" tabs with appropriate content
- Should NOT display "No items selected." message
On Runs List page (with "Flat Runs View" feature flag on):
- Select a run
- Open the "Compare" view
- Change the page
- Should display "Metrics", "Hyperparameters", and "Details" tabs with appropriate content
- Should NOT display "No items selected." message
[DET-123]: …

fix: show selections in ComparisonView on any page (ET-189)

---

webui/react/src/pages/Cluster/ClusterHistoricalUsageCsvModalComponent.tsx

DET-10442
Due to a recent refactor, after & after timestamps were converted into from & to. This is fine for displaying the historic usage charts, which was the intended behavior; however, this was also applied to the logic for the historic allocation CSV request, which this PR returns to the original state. 
- Ensure that historic allocation CSV download (both Group By: Workloads & Allocations) successfully starts a download for the provided time range in the webUI

fix: use before/after search params for historic allocation CSV download endpoint [DET-10442]

---

webui/react/src/e2e/fixtures/api.project.fixture.ts
webui/react/src/e2e/fixtures/api.user.fixture.ts
webui/react/src/e2e/fixtures/api.workspace.fixture.ts
webui/react/src/e2e/fixtures/global-fixtures.ts
webui/react/src/e2e/models/pages/ProjectDetails.ts
webui/react/src/e2e/tests/experimentList.spec.ts
webui/react/src/e2e/tests/userManagement.spec.ts

[TESTENG-46](https://hpe-aiatscale.atlassian.net/browse/TESTENG-46)
adds support for workspace and project created by api as a test fixture
[TESTENG-46]: https://hpe-aiatscale.atlassian.net/browse/TESTENG-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: workspace and project api [TESTENG-46]

---

harness/determined/cli/resources.py

First time using the `det resources` CLI and I think the help text could be improved. One quick thing to squeeze in before release is a new command that gets abbreviated as "all", which I think could be confusing as it's not like an option to return all allocations, which is kinda how it reads.
Going to install and manually verify
- [ NOT YET! ] Changes have been manually QA'd
- [ Y ] New features have been approved by the corresponding PM
- [ N ] User-facing API changes have the "User-facing API Change" label
- [ N/A ] Release notes have been added as a separate file under `docs/release-notes/`
- [ N/A ] Licenses have been included for new code which was copied and/or …

chore: lengthen abbreviation to avoid ambiguity

---

webui/react/src/components/Searches/Searches.settings.ts
webui/react/src/components/Searches/Searches.tsx

ET-641
This debounces the column width settings for the searches pages.
1. Open your browsers devtools and navigate to the network tab.
2. navigate the page to a project search list.
3. change the sort order either by using the column header menu or the dropdown menu. Note that there should be one POST request to settings per change.
4. change the width of any column. Only one POST request should be made when the column width is done moving.

fix: debounce searches column width settings

---

webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/SearchDetails.tsx

ET-647
This loads trial data for single run searches in the search view. this prevents issues with the continue trial where the trial information was missing in the experiment config.
when visiting the search page of a single-run search, both options on the "Continue Run" menu button should open a modal.

fix: load trial data for single run searches in search view

---

webui/react/src/pages/JobQueue/ManageJob.tsx

DET-10446
Modify text in the ManageJob confirmation to say 'save' instead of 'close' in order to clarify the effect of pressing that button.
- Ensure that the ManageJob modal shows 'Save' instead of 'Close'

refactor: change 'close' to 'save' on button in ManageJob modal [DET-10446]

---

webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.tsx
webui/react/src/pages/SearchDetails.tsx

fix: load trial data for single run searches in search view #9742

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/internal/config/oidc_config.go
master/internal/config/saml_config.go
master/internal/plugin/saml/service.go

Reverts determined-ai/determined#9690
I think this branch caused ci failures that were masked by other failures. Reverting to investigate.

Revert "chore: add configurable posix claims fields to master config [RM-398]"

---

webui/react/src/services/decoder.ts

ET-655
This fixes an issue where the searcher metric wasn't decoded from the experiment api payload.
on the searches table, add the "searcher metric" column to the view. It should be populated.

fix: extract searcher metric from experiment payload

---

webui/react/src/e2e/tests/experimentList.spec.ts

Instead of creating a new experiment mid-test (which may have been interrupting other tests), use previously created experiment.

test: use previously created experiment for pause test

---

webui/react/src/pages/TrialDetails.tsx

[ET-657]
On a single run search the Code tab should be visible.
[ET-657]: https://hpe-aiatscale.atlassian.net/browse/ET-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add code tab to run page [ET-657] 

---

helm/charts/determined/values.yaml
webui/react/src/components/WorkspaceCreateModal.tsx

- Add "Cluster Name" title as shown below
-  change helm chart `additional_resource_managers[i].name` to `additional_resource_managers[i].cluster_name`
Before (No title)
After (with title)
CI Passes.

chore: add Cluster Name title and change helm value

---

tools/k8s/.gitignore
tools/k8s/contour.yaml
tools/k8s/launch-minikube-with-gateway.sh
tools/k8s/remote_connect.md
tools/k8s/remote_connect.py

https://hpe-aiatscale.atlassian.net/browse/RM-239
This document describes the remote dev tooling for connecting devcluster to a kubernetes
cluster running in the cloud.
Overview of how this works:
- set up reverse proxy
- port collision
- err handling
- clean up
- ensure there is a Gateway running the target cluster
- launch if necessary
- grab its configuration
- updated the given devcluster config based on the collected and launched services
- run devcluster

chore: add a utility for connecting devcluster to remote k8s clusters

---

webui/react/src/e2e/tests/experimentList.spec.ts

N/A
Skips a test that has a nearly 30% fail rate. Will revisit ASAP to try to make this test more stable and un-skip it once more.

test: skip flaky test

---

webui/react/src/components/ColumnPickerMenu.module.scss
webui/react/src/components/ColumnPickerMenu.test.mock.tsx
webui/react/src/components/ColumnPickerMenu.test.tsx
webui/react/src/components/ColumnPickerMenu.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx

[ET-222]
[ET-223]
Show metadata in the run table.
have not excluded the array type columns yet. will implement it after #9759 is merged, but its not a blocker to merge this PR.
- Go to run table
- Click `Columns` button and see `Metadata` tab. user should be able to add metadata columns and filter and sort by metadata (metadata with array type are not supported for filtering and sorting, PR will come after #9759 to exclude the array type metadata in filter and sort)
[ET-222]: https://hpe-aiatscale.atlassian.net/browse/ET-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: …

feat: show metadata in run table

---

helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml

Added clusterName to master-config.yaml and fixed how defaultNamespace is called in it.

fix: fixed helm chart values and master-config.yaml

---

helm/charts/determined/values.yaml

Avoid nil pointer dereference error during helm install/upgrade by passing in empty `resource_manager.defaultNamespace` and `resource_manager.clusterName` 
helm install and helm upgrade using this `values.yaml`

fix: uncomment helm values

---

webui/react/src/components/HyperparameterSearchModal.tsx

[MD-472]
Sometime the API can take a while to finish, adding a loading indicator to the HP search modal so the page does not seem freeze.
When creating an experiment using HP search, after submission, the button would become loading. 
[MD-472]: https://hpe-aiatscale.atlassian.net/browse/MD-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add loading indicator when creating HP search

---

.circleci/real_config.yml
tools/slurm/scripts/slurmcluster.sh
tools/slurm/terraform/main.tf
tools/slurm/terraform/scripts/generate-tfvars.sh
tools/slurm/terraform/variables.tf

CM-405
1. Add a flag for `make slurmcluster` pipeline to set labels on the VM it creates and its disk
2. Use them in the CI
Also I've discovered that `make slurmcluster` job will stay pending when a background task to create a cluster failed, so I've fixed that. The job should now fail right away if that happens.
Also I went to war with trailing whitespace in the circle config.
Do the VMs spawned by CI have that label?
Test run: https://app.circleci.com/pipelines/github/determined-ai/determined/59112/workflows/bd2dfd65-498c-46be-a01f-908aefa48a05/jobs/2836426
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

ci: label `make slurmcluster` instances for cloud spend [CM-405]

---

webui/react/src/components/FilterForm/components/type.ts
webui/react/src/components/RunFilterInterstitialModalComponent.test.tsx
webui/react/src/components/RunFilterInterstitialModalComponent.tsx
webui/react/src/utils/filterFormSet.ts
webui/react/src/utils/flatRun.ts

ET-679
This fixes an issue where single search runs were being filtered out of
the comparison view in runs view. We were erroneously applying a filter
to the search results.
* in the search runs view, open the comparison view and switch to the details tab
* filter the search results such that only runs of single searches are in the view
* add rows to the selection
* trials selected should appear in the details tab as the user updates the selection

fix: don't filter single runs in the comparison view

---

docs/release-notes/editor-project-restricted.rst
master/internal/db/postgres_rbac_intg_test.go
master/static/migrations/20240801095202_add-editor-project-restricted-role.tx.up.sql

DET-10428
Adds pre-canned Editor Project Restricted role, which has the same permissions as an Editor without the ability to create or update projects. 
- Ensure that CI passes

feat: add editor project restricted role and testing [DET-10428]

---

master/internal/api_project.go
webui/react/src/components/ProjectMoveModal.tsx

ET-626
Display message for matching name error when moving projects
Create two projects with the same name in separate workspaces. Move one project to the workspace of the other and confirm that the error message is `Project with name '{project_name}' already exists in target workspace`

fix: return proper error message when moving a project with a matching names

---

docs/reference/deploy/master-config-reference.rst
docs/setup-cluster/k8s/resource-caps.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go

stop supporting resource_manager.namespace and use release namespace as default instead of "default" in helm deployements.
no testing required

chore: change the comment for defaultNamespace in values.yaml

---

webui/react/src/components/CompareHyperparameters.test.mock.tsx
webui/react/src/components/CompareMetrics.tsx
webui/react/src/components/ComparisonView.test.mock.tsx
webui/react/src/components/ComparisonView.tsx
webui/react/src/hooks/useMetricNames.ts
webui/react/src/hooks/useMetrics.ts

ET-677
This fixes an issue where the page could appear slower than it should on load due to too much blocking traffic. We make three requests to build the comparison view for runs, searches and experiments:
1) request to get search/run information of selected runs/search ids
2) request to get metric names from selected runs/searches
3) request to get timeseries data given selected run ids and metric names.
we were attempting to make these requests simultaneously when the each request is dependent on information in the previous request. We also used `usePrevious` hooks as dependencies of `useCallback` hooks, which meant that we would erroneously update the callback reference when the previous value update was picked up on subsequent renders.
this pr fixes these issues by not rendering the …

fix: prevent multiple calls to time-series on compare view select

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/pages/FlatRuns/FlatRuns.tsx

[ET-654]
excluding ARRAY type columns from filter and sort
If you wanna add metadata, look at [this comment ](https://github.com/determined-ai/determined/pull/9808#issuecomment-2278391220)
- Make a metadata with array type
- Check if the metadata cannot be filtered or sorted
- Check if Array type column shows data as array like `[1, 2, 3, [2, 4]]`
[ET-654]: https://hpe-aiatscale.atlassian.net/browse/ET-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: exclude `Array` type columns

---

docs/release-notes/experiments-failed-status.rst
e2e_tests/tests/cluster/test_experiment_delete.py
e2e_tests/tests/cluster/test_master_restart.py
e2e_tests/tests/experiment/test_core.py
master/internal/experiment.go

RM-70
If a searcher completes but the experiment fails in shutdown, the experiment should end in failure. Thus, if an experiment is cancelled, a trial failure should trump the CANCELLED state = the experiment should be marked as FAILED.
See new e2e test, and edited e2e tests. No manual testing needed.

fix: don't ignore failed exps

---

.circleci/real_config.yml

INFENG-812
This changeset fixes a CircleCI bug that results in building release-flavored Docker images for things like `model_hub` even during non-release builds. Specifically, update `package-and-push-system-dev` and `package-and-push-system-dev-ee` CircleCI jobs to build dev Docker images correctly by fixing a bash if statement to check for if we're running the job from the "main" branch or a branch prefixed with "release-". The previous behavior would match on any git branch regardless, because of the position of the glob characters.
This behavior doesn't seem to cause problems now because the production path builds images with the version specified in `VERSION`, which is something like `0.36.0-dev0`, so it shouldn't clobber anything existing, but I believe this will build and push the …

build: INFENG-812: fix model_hub Docker tag

---

docs/model-dev-guide/api-guides/apis-howto/api-core-ug-basic.rst
docs/model-dev-guide/api-guides/apis-howto/api-core-ug.rst
docs/model-dev-guide/api-guides/apis-howto/api-pytorch-ug.rst
docs/model-dev-guide/model-management/_index.rst
docs/model-dev-guide/model-management/checkpoints.rst
docs/reference/python-sdk/python-sdk.rst

as discussed in eng-det-halp
https://hpe-aiatscale.slack.com/archives/CSG3W08JY/p1723492042530919
docs ticket #634
update this page
https://docs.determined.ai/latest/model-dev-guide/model-management/checkpoints.html#using-the-checkpoint-class
problem domain:
users are unsure what `get_checkpoint` returns. 
this doc implies that you can only really just download the checkpoint with the Checkpoint class. Perhaps it would be a good idea to add "getting a list of files in the checkpoint" as an example?
i.e.,
it is not at all clear that `Checkpoint.resources` is a map of `filename` to `size` in the checkpoint.
use case:
a user already has the checkpoint directory path and just wants to list files. …

docs: Getting a list of files in a checkpoint

---

docs/get-started/architecture/introduction.rst
docs/reference/deploy/helm-config-reference.rst
docs/release-notes/deprecate-k8s-preemption-scheduler.rst
helm/charts/determined/templates/NOTES.txt
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/templates/scheduler-config.yaml
helm/charts/determined/templates/scheduler-deployment.yaml
helm/charts/determined/templates/scheduler-permissions.yaml
helm/charts/determined/values.yaml
master/internal/config/config.go
master/internal/config/config_test.go
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/spec.go

CM-385
Deprecate the Kubernetes priority with preemption scheduler. Remove references to the helm chart & invalidate master configuration input `defaultScheduler: preemption`. Set the `preemption` value for all kubernetes resource managers to false (since now no scheduler has preemption enabled).
No testing needed, but manual testing shows that defining `defaultScheduler: preemption` in the yaml chart will be overwritten by a blank default value to the master configuration. Also, trying to define `defaultScheduler: preemption` in a devcluster yaml's master configuration won't be recognized as valid.

chore: deprecate kubernetes priority w/ preemption scheduler

---

docs/requirements.txt
e2e_tests/tests/requirements.txt
harness/tests/requirements/requirements-harness.txt

https://hpe-aiatscale.slack.com/archives/CSG3W08JY/p1723649552010439
> As new Intel Mac’s are no longer produced and with time fewer will remain in use, we will be stopping testing and eventually building macOS x86_64 binaries after the release 2.2.0 is complete (mid January 2024). We will not be producing macOS x86_64 binaries for Release 2.3.0.
Support for PyTorch on Intel Mac deprecated. The highest version it can go is 2.2.2.
Solution: Set up PyTorch 2.2.2 specifically for Intel MAC while keeping other environments using 2.3.0.
CI passes.
`make all` and `make -C harness check` don't have error on an Intel MAC.
[DET-123]: …

chore: fix torch version to 2.2.2 for intel mac

---

docs/reference/deploy/helm-config-reference.rst
docs/reference/deploy/master-config-reference.rst
docs/release-notes/rocm-k8s-gpu.rst
master/internal/config/resource_config_test.go
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/jobs_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go

Adds initial experimental support for amd gpus on k8s.
Unit tests cover this change
Also manually verified on amd hardware. Automated e2e tests were deemed not in scope due to hardware availability issues
blocked on https://github.com/determined-ai/environments/pull/275. We just need the environment images to land in the same release as this. Some additional docs will be added in the environments pr detailing what our rocm environment does and does not support. 

chore: initial k8s rocm support [CM-367]

---

docs/integrations/data-transformers/pachyderm.rst
docs/tutorials/pachyderm-cat-dog.rst

Describe how to configure the experiment config yaml file to view the basic data lineage (pach repo).
Include option to set variables dynamically.
Ensure the cat dog tutorial is updated.

docs: Describe basic lineage steps

---

webui/react/src/pages/ExperimentDetails/ExperimentCheckpoints.tsx

[ET-277]
With the flat runs flag off, go to the Checkpoints tab of a single trial experiment. There must be at least one checkpoint in the table for testing purposes.
- click the overflow icon at the far right of a table row to pull up the action menu for that checkpoint
- wait, do not click anything for ~10 seconds
- the action menu should still be visible
- test both the register and delete checkpoint actions to confirm that they still work as expected
[ET-277]: https://hpe-aiatscale.atlassian.net/browse/ET-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: …

fix: checkpoint table action menu shouldn't vanish on polling [ET-277]

---

webui/react/src/hooks/useTypedParams.test.tsx

ET-260
this unskips a test that was marked flaky. It would throw errors because the neighboring test wasn't waiting for each test to finish running, causing issues with the test code.
react unit tests should continue to pass.

chore: unskip flaky test

---

webui/react/src/components/Metadata.test.tsx
webui/react/src/components/Metadata.tsx
webui/react/src/pages/TrialDetails/TrialDetailsOverview.tsx

- Hide `Metadata` section if there's no data to show
- Check if metadata section appears if metadata exits
- Check if metadata section is hidden if no metadata exits

fix: hide metadata section if there's no metadata

---

webui/react/src/components/CreateGroupModal.tsx
webui/react/src/components/CreateUserModal.tsx
webui/react/src/components/DeleteGroupModal.tsx
webui/react/src/pages/Admin/Admin.test.tsx
webui/react/src/pages/Admin/GroupManagement.test.tsx
webui/react/src/pages/Admin/GroupManagement.tsx
webui/react/src/pages/Admin/UserManagement.test.tsx
webui/react/src/pages/Admin/UserManagement.tsx
webui/react/src/pages/Admin/index.tsx

CM-436
Addresses issues that occur when creating users and deleting/creating groups. 
- Count for groups and users should stay up-to-date
- Deleting a group should not cause pagination settings to display incorrect empty state for previous page
In EE/With RBAC:
- Create a user. Count of users should increase without refresh.
- Create a group. Count of groups should increase without refresh.
- If creating a group increases the group count enough to add another page, clicking that page number should display the newly created group as expected.
- If deleting a group decreases the group count enough to remove a page, the page should decrement automatically and display expected results (not an empty state for that page)
See [Release Note](https://github.com/determined-ai/determined/blob/master/ …

fix: Group and User management (CM-436)

---

docs/model-dev-guide/api-guides/apis-howto/deepspeed/autotuning.rst
docs/model-dev-guide/hyperparameter/search-methods/hp-custom.rst
docs/reference/custom-searcher-reference.rst
docs/reference/experiment-config-reference.rst
docs/release-notes/deprecate-custom-searchers.rst
e2e_tests/tests/fixtures/custom_searcher/searchers.py
harness/determined/searcher/_remote_search_runner.py
harness/determined/searcher/_search_method.py
harness/determined/searcher/_search_runner.py

Deprecate all custom searchers and methods. 

chore: deprecate Custom Searcher [MD-504]

---

docs/tools/webui-if.rst

fix docs tickets including
https://github.com/orgs/determined-ai/projects/53/views/1?pane=issue&itemId=73898381

docs: Minor docs enhancements

---

docs/rebrand-docs.py

Docutils removed `rawsource` in V2.0, which was being used in our rebranding script breaking the release party process.
- Ensure that the rebranding script does not fail on `rawsource` attribute missing
- Ensure that the rebranded docs in the EE cluster are rebranded properly. 

fix: replace rawsource attribute with node directly, due to removal of rawsource in Docutil 2.0

---

webui/react/src/pages/ExperimentDetails/ExperimentDetails.tsx
webui/react/src/pages/ExperimentDetails/ExperimentSingleTrialTabs.module.scss

ET-628
This fixes an issue where loading a single trial experiment page tab near the end of the tab list would hide the tab on mobile. We disabled the scrolling behavior of the tab list because on certain occasions it could scroll offpage. on removing that fix, i'm unable to reproduce the initial issue on firefox, chrome or safari.
- ensure run centric ux is off
- visit a single trial experiment
- click the logs tab
- use the developer tools responsive view to ensure the viewport is less than 480px
- refresh the page
- the tab should be scrolled into view.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

fix: experiment single trial tabs don't scroll on load

---

docs/manage/security/rbac.rst

New to determined: customers can now add an "editor-like" role that doesn't allow creating or updating of projects
Feature: #9796 

docs: Document rbac editorprojectrestricted role

---

webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.module.scss
webui/react/src/pages/ModelVersionDetails/ModelVersionHeader.tsx

[ET-384]
Go to a Model Version page, shrink your viewport to ~mobile width, and confirm that the buttons (including overflow button) are present.
[ET-384]: https://hpe-aiatscale.atlassian.net/browse/ET-384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: model version name overflow on mobile [ET-384]

---

master/internal/api_experiment.go

https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1724182588030219
Remove duplicate ids to improve API performance.
In a certain environment that has relatively lots of run data (50k~), `v1/experiments/metrics-stream/metric-names` takes some time. For example, `https://gcloud.determined.ai/api/v1/experiments/metrics-stream/metric-names?ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=1&ids=2&ids=3&ids=4&ids=5` takes 6s. It would take longer if there are more run data or more `ids` query parameters.
This PR is to improve the API response speed performance by removing the duplicate `ids`.
After this fix, the above API call takes around 1s, so 6 times faster than before. We can do some more improvement around the API, but this is the first step. …

perf: remove duplicate ids in `ExpMetricNames` api

---

docs/reference/deploy/master-config-reference.rst
master/internal/config/config_test.go
master/internal/config/ui_config.go
master/internal/core.go

we had a custom logic for doing fallback for variations of the logo that we needed from the user. here we simplify that and leave it to the user to decide to use duplicate vartions if desired.
- updated unit tests
- test with an empty `logo_path` as well as one with some missing logo variation

fix: fix fallback logic for partially provided custom logos

---

webui/react/src/components/ColumnPickerMenu.test.tsx
webui/react/src/components/ColumnPickerMenu.tsx
webui/react/src/components/TableActionBar.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx

ET-278
this fixes an issue where the pinned column state wasn't restored when resetting columns.
* visit a new table page (either runs, searches, or the new experiment list)
* ensure no columns are pinned
* open the columns menu and click the reset button
* the default columns should have the correct pinned state (id, state and start time should be pinned)

fix: reset pinned column state when resetting columns

---

.circleci/devcluster/double-reattach.devcluster.yaml
master/cmd/determined-master/root.go
master/cmd/determined-master/root_test.go
master/internal/api_generic_tasks.go
master/internal/config/config.go
master/internal/config/config_test.go
master/internal/rm/agentrm/fair_share.go
master/internal/rm/agentrm/mock_test.go
master/internal/rm/agentrm/priority.go
master/internal/rm/agentrm/scheduler_test.go
master/internal/rm/kubernetesrm/resource_pool.go
master/internal/rm/kubernetesrm/resource_pool_intg_test.go
master/internal/sproto/task.go
master/internal/task/allocation.go
master/internal/task/allocation_intg_test.go
master/internal/task/allocation_service_test.go
master/internal/task/preemptible/preemptible.go
master/internal/task/preemptible/preemptible_test.go
master/internal/task/preemptible/service.go
master/internal/trial.go
master/internal/trial_intg_test.go
master/pkg/model/generic_task_config.go
master/pkg/model/task_container_defaults.go
master/pkg/model/task_container_defaults_test.go
master/pkg/schemas/expconf/experiment_config.go
master/pkg/schemas/expconf/zgen_experiment_config_v0.go
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/experiment.json
schemas/test_cases/v0/experiment.yaml

Adds a configuration option in experiment config (`task_container_defaults`) that specifies how long to wait after preemption before the task is killed. 
Previously, this configuration already existed in the master config, so it has been moved. 
```python3
import logging
import time
import determined as det
from determined import core
def main(core_context):
for batch in range(100):
time.sleep(10)
steps_completed = batch + 1
if steps_completed % 5 == 0:
core_context.train.report_training_metrics(
steps_completed=steps_completed, metrics={"x": batch}
)
if steps_completed % 10 == 0:
core_context.train.report_validation_metrics(
steps_completed=steps_completed, metrics={"x": batch}
)
if __name__ == "__main__":
logging.basicConfig(level=logging.DEBUG, format=det.LOG_FORMAT)
with core.init() …
```

feat: configurable preemption timeout [MD-500]

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/pages/ExperimentDetails/ExperimentCodeViewer.tsx

ET-741
This fixes an issue where a parse error occurs when the user selects an ipynb file in the experiment code viewer. The file content updates as an effect of the selected file path changing. Because the effect happens after render, the editor is briefly rendered with the wrong content. To fix this, the file content is now keyed with the path. when the path doesn't match, we assume the content hasn't loaded yet.
Further error handling fixes should be introduced in this pr upstream in hew.
* visit an experiment page of an experiment that contains an ipynb file in the files, or, with the flat_runs feature flag on, visit a run containing the same
* click the code tab
* select an non-ipynb file
* select an ipynb file
* no error should appear in the toast or in the console.
See [Release …

fix: prevent loading issues with ipynb files

---

.github/workflows/backport.yaml

CM-446
See https://hpe-aiatscale.atlassian.net/wiki/x/CgBLZQ for more details.
Suppose a developer wants to backport a fix `XYZ` into release branch `release-A`. On the pull request for `XYZ`, add labels `backport release-A`. Then, after the PR is merged, the github action will trigger :
(1) creating a new backport PR from main into the release branch (in this case `release-A`)
(2) automatically merging the backport PR
Manual testing  done on https://github.com/carolinaecalderon/github-backport

chore: add backport github action

---

webui/react/src/components/WorkspaceCreateModal.tsx

Error Toast saying "failed to get listNamespace Bindings" pops up when you log in as a Workspace Creator, and try to edit the workspace. Fixed that by adding user permission checks to API request 
- spin up a minikube cluster, and login with different roles such as Cluster Admin, Workspace Admin, editor, Workspace Creator and perform different workspace and namespace bindings actions and make sure no errors come up.

fix: fix error toast popping up in Workpace Creator view

---

harness/determined/common/api/__init__.py
harness/determined/common/api/_session.py
harness/determined/common/api/authentication.py
harness/determined/core/_context.py
harness/determined/exec/gc_checkpoints.py
harness/determined/exec/launch.py
harness/determined/exec/prep_container.py
harness/determined/experimental/core_v2/_core_context_v2.py
harness/determined/launch/deepspeed.py
harness/determined/launch/horovod.py
harness/tests/cli/test_auth.py
harness/tests/launch/test_deepspeed.py
harness/tests/launch/test_horovod.py
harness/tests/launch/test_launch.py
harness/tests/launch/test_torch_distributed.py
harness/tests/launch/test_util.py
master/static/srv/check_idle.py
master/static/srv/check_ready_logs.py

use task session tokens instead of user session tokens in the `CoreContext` and other internal tasks, since some experiments are long running and will expire within the 7 day user token deadline.
- Make sure a normal experiment (mnist_pytorch for example) runs successfully
- submit a script that checks the tokens being used in sessions:
```python3
import logging
import os
import determined as det
from determined import core
if __name__ == "__main__":
logging.basicConfig(level=logging.DEBUG, format=det.LOG_FORMAT)
with core.init() as core_context:
core_session_token = core_context.train._session.token
session_token_env = os.environ["DET_SESSION_TOKEN"]
user_token_env = os.environ["DET_USER_TOKEN"]
print(f"Token on `core.Context`: {core_context.train._session.token}")
print(f"Task token …
```

fix: use task sessions in Core API [MD-509]

---

examples/features/torch_batch_process_embeddings/requirements.txt

See https://github.com/chroma-core/chroma/issues/2687. There are mixed reports of this working in 0.5.3 and some other recent versions - but I think this has been broken for us roughly since 0.5.4 came out.
Going to request the e2e-gpu-distributed tests to make sure this worked. Update: aaaand they did.
- [ N/A ] Changes have been manually QA'd
- [ N/A ] New features have been approved by the corresponding PM
- [ N/A ] User-facing API changes have the "User-facing API Change" label
- [ N/A ] Release notes have been added as a separate file under `docs/release-notes/`
- [ N/A ] Licenses have been included for new code which was copied and/or modified from any external code

ci: pin chromadb version to avoid incompatibility

---

webui/react/src/components/DeterminedAuth.test.tsx
webui/react/src/components/DeterminedAuth.tsx

CM-432
Add unit testing to `DeterminedAuth` to test:
- Successful login with strong password (no weak password warning toast)
- Successful login with weak password (with weak password warning toast)
No additional testing required, unit test should pass.

test: successful login with weak or strong password

---

master/internal/run/runs.go
master/internal/run/runs_test.go

ET-744
When an object metadata is inside an array, the object elements are now displayable.
Add metadata to a run that has a list of objects (i.e `"a": [{"b": 3}, {"c":2}]`) then, on the run table select and confirm that the elements are viewable.

fix: allow for objects inside array metadata to be typed properly

---

e2e_tests/tests/cluster/test_webhooks.py
master/internal/api_experiment.go
master/internal/api_task.go
master/internal/api_tasks.go
master/internal/api_trials.go
master/internal/core_task.go
master/internal/db/postgres_test_utils.go
master/internal/experiment/authz_rbac.go
master/internal/webhooks/postgres_webhook.go
master/internal/webhooks/postgres_webhook_intg_test.go
master/internal/webhooks/shipper_test.go
master/internal/webhooks/singleton.go
master/pkg/schemas/expconf/integrations.go
master/pkg/schemas/zgen_schemas.go
schemas/expconf/v0/integrations.json
schemas/expconf/v0/webhooks.json

[MD-479]
Part of workload alerting project.
ERD link: https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1666809868/Workload+Alerting+ERD
Expand the experiment config -> integrations -> webhooks
```
integrations:
webhooks:
webhook_name:
- test-webhook
```
Below is a table for which group of experiments can trigger which mode of webhooks.
workspace \ mode     |                             Specific                         |                       Workspace
| :------------------- | :-------------------------------------: | :------------------------------------: |
workspace defined    |  match workspace && match config      |      all experiments within workspace
workspace null           |                      match config                       |                     all …

feat: Logic of different modes for webhook

---

docs/manage/users-remote.rst
docs/reference/deploy/master-config-reference.rst
docs/release-notes/auto-populate-posix.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/internal/config/oidc_config.go
master/internal/config/saml_config.go
master/internal/plugin/oidc/service.go
master/internal/plugin/oidc/service_intg_test.go
master/internal/plugin/saml/service.go
master/internal/plugin/saml/service_intg_test.go
master/internal/user/postgres_agentusergroup.go

[CM-399]
When the a determined master is configured to expected the POSIX claims in SSO login & they are provided in the claim, then we will populate the relevant fields for the user:
AgentUID   null.Int    `db:"agent_uid" json:"agent_uid"`
AgentGID   null.Int    `db:"agent_gid" json:"agent_gid"`
AgentUser  null.String `db:"agent_user" json:"agent_user"`
AgentGroup null.String `db:"agent_group" json:"agent_group"`
Also re-adds new fields to master configuration (original done here https://github.com/determined-ai/determined/pull/9690/files). The original PR was reverted because of CI errors. 
Test using an Okta application.
Recommended application: `carolina-oidc-test`, https://dev-2564556-admin.okta.com/admin/app/oidc_client/instance/0oacxxzecx7a9l5O85d7/#tab-general 
- add your user to …

feat: Auto-Populate POSIX Information on sign in using SSO [CM-399]

---

master/internal/api_runs.go
master/internal/api_runs_intg_test.go

ET-748
Add sorting for arbitrary metadata
Go to run table and select a metadata column and sort

fix: sorting by arbitrary metadata

---

webui/react/src/components/Searches/Searches.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx

ET-650
This fixes an issue where it's possible for the user to navigate outside of the list bounds in the new experiment view, the searches view, and the runs view. When doing so, the user sees a blank page, which can be confusing. In the case that the user tries to load pages beyond the result set, we now reset the pagination back to the first page of results.
* on any project, open the runs page.
* navigate to the last page
* in the address bar, edit the page query parameter such that it's higher than the existing number
* press enter
* you should be redirected to the first page of results.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNW …

fix: prevent out of bounds navigation on new list views

---

examples/tutorials/mnist_pytorch/train.py

ruamel changed their APIs and previous method call no longer exists.
run MNIST locally: go to `examples/tutorials/mnist_pytorch` and run `python3 train.py`, make sure it runs and exits successfully.

fix: use new ruamel yaml APIs

---

webui/react/src/components/HyperparameterSearchModal.tsx

[ET-119]
Disable “Run Experiment” button when clicked once and still running `submitExperiment`
- Check if “Run Experiment” button is disabled and loading in hyperparameter search modal when clicked once and still running `submitExperiment`, so user cannot submit the same hyperparameter search multiple times.
[ET-119]: https://hpe-aiatscale.atlassian.net/browse/ET-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: prevent `hyperparameter search modal` submitting the same request multiple times

---

webui/react/package-lock.json
webui/react/package.json
webui/react/src/components/RunActionDropdown.tsx
webui/react/src/pages/FlatRuns/columns.ts

[ET-80]
Related PR: https://github.com/determined-ai/hew/pull/135
Empty entries in the run table should contain a dash
- If the cell value is empty (null value), show the dash `-` in the run table
[ET-80]: https://hpe-aiatscale.atlassian.net/browse/ET-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show `-` for empty data in run table

---

webui/react/src/components/ModelRegistry.settings.ts
webui/react/src/components/ModelRegistry.tsx
webui/react/src/components/Table/InteractiveTable.tsx

[ET-640]
Resets the user setting of `tableOffset` on page load. I investigated more elegant ways to solve this, such as removing tableOffset from the settings config and only storing it in the URL params, but InteractiveTable and useSettings are tightly coupled enough that it would take a not-insignificant refactor to do so.
- Go to Model Registry page
- Use the Pagination component to change the table page number
- Navigate away from Model Registry page
- Navigate back to Model Registry page
- Confirm that the table is on its first page, not the one you navigated to in the second step
[ET-640]: https://hpe-aiatscale.atlassian.net/browse/ET-640?atlOrigin=eyJpIjoiNWRkNTljNzY …

fix: reset Model Registry page number on pageload [ET-640]

---

harness/determined/transformers/_hf_callback.py

https://hpe-aiatscale.atlassian.net/browse/MD-511
`TRAIN = "train_progress"` appears to be a confusing variable name for a value that is intended as a placeholder. This caused an issue in the behavior of `on_log()`. This PR renames `TRAIN` to `DEFAULT` and `TRAIN_PROGRESS` to `TRAIN`
Run an example with huggingface callback and make sure metrics are being recorded properly.

fix: Hf callback metric naming

---

master/internal/db/postgres_cluster.go
master/internal/db/postgres_cluster_intg_test.go
master/static/srv/update_aggregated_allocation.sql

CM-440
Our Historical Usage page fetches allocations by date in UTC time specifically, and we store allocations without a timezone, which converts the input time to UTC before storing the timestamp without the timezone internally. 
However, fetching timestamps with no timezone and then casting to `timestamptz` (with a timezone) only adds a timezone to the stored time stamp, doing no internal conversion from UTC to the corresponding time in the user's set timezone. (so `('2024-10-02 01:30'::timestamp)::timestamptz = 2024-10-02 01:30 <user_set_timezone>`, which isn't what we want.
With the changes in this PR, we keep consistent with how allocations are stored and continue to handle them in the `resource_aggregates` table without casting to a `timestamptz`.  …

fix: inconsistent timezone handling in daily allocation aggregation

---

master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/jobs_test.go

[CM-461]
Older version of Kubernetes don't have the expected label (`batch.kubernetes.io/job-name`), instead they use `job-name`.
https://kubernetes.io/docs/reference/labels-annotations-taints/#job-name
This PR adds a fallback to handle backwards compatibility in the event that version of k8s being used does not support the latest job label key.
- CI Passes
[CM-461]: https://hpe-aiatscale.atlassian.net/browse/CM-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add backwards compatibility for Pods to Jobs for k8s <v1.27 [CM-461]

---

master/internal/experiment/bulk_action_intg_test.go
master/internal/experiment/bulk_action_test.go

[ET-138]
As requested [here](https://github.com/determined-ai/determined/pull/9658/files/a0af8b0e292098cda3bd459e299a7530428b9d6a#r1681208318), puts some additional coverage on the filtering tests and enables some additional controls to improve on coverage further.
One observation out of this is that the filter logic appears to always return empty results if the project ID (outside the filters) is left zero-valued and the filter project ID must either be zero or match the other project ID. As I recall, we were questioning this design in our audit of the API for the run-centric story; I think we have a slightly clearer answer, thanks to this. I definitely think this behavior is quirky, and I lean toward thinking we probably shouldn't have `ProjectID` in the filters if `ProjectID` is …

test: cover project id filtering on bulk actions [ET-138]

---

master/internal/db/postgres_cluster_intg_test.go
master/static/srv/update_aggregated_queued_time.sql

CM-440
This is an extension of [#9988](https://github.com/determined-ai/determined/pull/9888).
The testing of `UpdateResourceAllocationAggregation` didn't account for the `update_aggregated_queued_time` script, which truncates a timestamp with a timezone to an arbitrary date when updating the `resource_aggregates`table.  
We fix this here by interpreting the timestamp in UTC time before passing it in as a date since the Historical Usage page and CSV downloads that fetch and display allocation information aggregate for a given day using UTC time.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

fix: timezone handling error in queued allocation time update

---

harness/determined/common/api/bindings.py
master/internal/api_config_policies.go
master/internal/configpolicy/task_config_policy.go
master/internal/configpolicy/utils.go
master/internal/configpolicy/utils_test.go
proto/pkg/apiv1/config_policies.pb.go
proto/src/determined/api/v1/config_policies.proto
webui/react/src/services/api-ts-sdk/api.ts

[CM-502]
Introduce unmarshal functions to process user input for task config policies.
Covered by unit tests.
[CM-502]: https://hpe-aiatscale.atlassian.net/browse/CM-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add unmarshal functions for task config policies

---

Makefile

Removing some lingering references to a directory we recently removed.
Just some missed references from the recently work to remove `model_hub`.
I ran `make clean` to sanity check for syntax problems, etc. Wasn't caught by CI originally because CI doesn't call `make all`.
- [N/A] Changes have been manually QA'd
- [N/A] New features have been approved by the corresponding PM
- [N/A] User-facing API changes have the "User-facing API Change" label
- [N/A] Release notes have been added as a separate file under `docs/release-notes/`
- [N/A] Licenses have been included for new code which was copied and/or modified from any external code

chore: removing model_hub references from Makefile

---

.circleci/config.yml
.circleci/real_config.yml
Makefile
agent/.goreleaser_dryrun.yml
agent/Makefile
harness/Makefile
helm/.goreleaser_dryrun.yml
helm/Makefile
master/.goreleaser_dryrun.yml
master/Makefile
master/pkg/tasks/copy.go
model_hub/Makefile
version.sh

INFENG-809
INFENG-831
The following changeset does a few different things, and I apologize for its size, but it was easier to wrap it all together. Broadly speaking, this introduces a new CircleCI `release-dryrun` workflow to test the release process, as well as some important tweaks to the `version.sh` script that fix a critical bug in how we tag Docker images.
I've introduced a new CircleCI workflow called `release-dryrun`. The goal was to test all of the recent release process changes with a separate workflow that didn't risk publishing public artifacts that would either conflict with existing versions or otherwise pollute package indexes. This has also been a separate Determined feature request for a little bit now anyway.
There were several ways to do this, but I opted for separating …

build: INFENG-809: Update CircleCI tag logic and add release dryrun workflow

---

docs/model-dev-guide/api-guides/apis-howto/_index.rst
docs/model-dev-guide/create-experiment.rst
docs/model-dev-guide/prepare-container/set-environment-images.rst
docs/reference/deploy/agent-config-reference.rst
docs/setup-cluster/_index.rst
docs/setup-cluster/k8s/helm-commands.rst
docs/setup-cluster/k8s/k8s-dev-guide.rst
docs/setup-cluster/rocm-support.rst
docs/setup-cluster/slurm/slurm-known-issues.rst

Update docs to latest ROCm support as mentioned in 0.36.0 release notes and prior release notes. Make content more readable and less duplicative. Organize the content under proper sections and pages.
https://hpe-aiatscale.atlassian.net/browse/DOCSMLDX-35
docs preview: https://determined-ai-docs.s3.us-west-2.amazonaws.com/previews/d97560c619e6d0ca2965fcbf25127c11/setup-cluster/rocm-support.html

docs: Update ROCM support

---

master/internal/api_trials.go
master/internal/api_trials_intg_test.go

CM-518
GetTrialRemainingLogRetentionDays was not taking global log retention days into account while calculating remaining days. Fixed it by adding a check and an automated test for this scenario.
Added automated test.
For manual testing:
1. Add a global log retention policy to master config:
```
retention_policy:
log_retention_days: 90
schedule: 0 3 * * *
```
3. Start devcluster.
4. Create an experiment and do not specify the log retention days.
5. After a trial under the experiment is completed, the remaining log retention days on the Logs tabs of the trial overview shows accurate value (89 days)
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJp …

fix: GetTrialRemainingLogRetentionDays should take global log retention days into account [CM-518]

---

harness/determined/transformers/_hf_callback.py

Once the training is completed, we shouldn't see this exception. It It prevents things like model evaluation from happening.
CI passes.

fix: huggingface callback raise process preempted exception

---

e2e_tests/tests/cluster/test_webhooks.py

`metrics_sigma` is no longer a field in single-medium-train-step.yaml. So the test need to be updated.
CI Passes.

chore: update test log pattern webhook cache

---

master/internal/configpolicy/utils_test.go

Looking at the tests, I noticed that it was checking contents if noErr was false and we want to verify contents if noErr is true (i.e., there are no errors and the contents were unpacked correctly).

chore: fix config policy unmarshal tests

---

harness/determined/pytorch/_pytorch_trial.py

we check for validation loaders on non-chief workers when we don't define them on non-chief workers.
modify `examples/mnist_pytorch/train.py` to override `evaluate_full_dataset` instead of `evaluate_batch`. submit a distributed training job and make sure it runs successfully.

fix: move validation dataloader check in PyTorchTrial [MD-515]

---

examples/hf_trainer_api/hf_image_classification/image_classification.py

The datasets.load_metric() call has been replaced by evaluate.load().

fix: update huggingface example

---

master/internal/rm/kubernetesrm/resource_pool_intg_test.go

The latest versions of k8s have a new Job condition called
JobFailureTarget which is a signal to the jobs controller to kill off
the pods of the job.
Our jobUpdatedCallback() function waits for the JobFailure condition,
which now comes after the pod is fully terminated, which takes a lot
longer.
Probably we need to make sure our k8s logic is still valid, and deal
with the additional time it takes a job to reach JobFailed, if it
affects anything other than this test.
Until then, let's unblock CI for the whole team by just increasing the
test time for TestExternalPodDelete and TestNodeWorkflows.

ci: increase timeout for k8s intg tests

---

docs/reference/deploy/master-config-reference.rst
docs/reference/experiment-config-reference.rst
docs/release-notes/fix-master-log-retention-days.rst
master/internal/core.go
master/internal/logretention/logretention.go

CM-519
Fix a bug where the master's task spec container defaults Log Retention Policy wasn't set from the master config or applied to new/past experiments. 
Previously, the master task spec log retention policy remained null, so running `det task cleanup-logs` would not delete any logs, even if the config had that specified. Instead, to affect the task logs with that CLI command, you had to apply a per-experiment retention policy.
Add some documentation to clarify that if master is upgraded/restarted with a new retention policy this will override an experiment's value.
Manually test (until I can figure out how to configure an e2e master tests with a log retention policy).
Spin up your own, regular devcluster. 
1 . Launch an experiment with a log retention policy specified in its yaml -- …

fix: update LogRetentionDays from master config when master starts/upgrades

---

.github/CODEOWNERS

CM and RM team have merged, so this reassigns code to the merged CM team. Backend still needs to be broken up into CM, ET, etc.
No testing necessary

chore: reassign RM code to CM in CODEOWNERS

---

docs/release-notes/unspecified-slots.rst
master/internal/rm/agentrm/mock_test.go
master/internal/rm/agentrm/resource_pool.go
master/internal/rm/agentrm/resource_pool_test.go
master/internal/rm/agentrm/scheduler_test.go
master/internal/rm/agentrm/summaries.go
tools/devcluster.yaml
webui/react/src/components/SlotAllocationBar.tsx
webui/react/src/utils/cluster.test.ts
webui/react/src/utils/cluster.ts

CM-503
For agent based deployments, if agents of different slot types are assigned to the same resource pool, change the "Compute Slots Allocated" label to "Unspecified Slots Allocated" label to clarify the mixed statusfor the user. 
Additionally, add an error log message in zero slot or multi-slot-type cases. 
Finally, if a resource pool's slot type is of type `TYPE_UNSPECIFIED`, do not filter out any agents from the slot progress bar count.
See new label for slots allocated for pools with multi-slot-type agents (pool1) or zero-slot agents (pool2)
See unit tests in agent, confirming that the slot type assigned in the resource summary is "zero" or "unspecified" for zero or multiple slot type agents. See screenshots of the changes in the webui in the test cluster
For release party, I …

fix: do not filter slots for mixed-slot-type pools

---

master/internal/logretention/logretention.go

CM-528
Change log level of log retention policy logs to "Info" level, not "trace".
```
INFO[2024-09-16T10:36:29-06:00] deleting expired task logs                    component=log-retention default-retention-days=-1
INFO[2024-09-16T10:36:29-06:00] deleted expired task logs                     component=log-retention err="<nil>" rows=123
```
N/A.
Spin up on your own test cluster to verify, set master config values for log retention policy/days. Then, clean up with `det task cleanup-logs`. You should see these log levels in the Info level.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

chore: change log level for log retention policies

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/question.yml
CONTRIBUTING.md
README.md
docs/_templates/article-header-buttons.html

Replace the tracking Slack links with static links, because the tracking links keep expiring after a certain amount of time or number of clicks, and therefore don't work.

docs: Replace slack links

---

webui/react/package-lock.json
webui/react/package.json

ET-751
This updates the hew package, which has been updated to reduce the number of available code editor languages to just javascript, yaml, json and markdown. this should shrink the package size by 2MB unpacked, 500KB packed.
React build size should be smaller. otherwise no testing is required

chore: remove unused languages from code editor

---

e2e_tests/tests/experiment/test_allocation_csv.py

test_cmd_capture was flaking around maybe 1% of the time.
I can't tell if the failure was that timestamp_before is non-inclusive or if was just a rounding error somewhere, but adding only a couple seconds to the boundaries seems to be enough to avoid flakes.
I fixed the other tests in the file too.  One test had been patched already... but not the others.
[Example flake](https://app.circleci.com/pipelines/github/determined-ai/determined/60247/workflows/e16e5152-71e8-437f-aa7f-0c71783901a4/jobs/2917136).

ci: fix flaky test_allocation_csv tests

---

master/internal/api_config_policies.go
master/internal/api_config_policies_intg_test.go
master/internal/configpolicy/postgres_task_config_policy.go

Added GET global config policies API endpoint
Added automated test

feat: add GET global config policies API

---

master/.mockery.yaml
master/internal/api_config_policies.go
master/internal/api_config_policies_intg_test.go
master/internal/cluster/authz_basic_impl.go
master/internal/cluster/authz_iface.go
master/internal/cluster/authz_permissive.go
master/internal/configpolicy/authz_basic_impl.go
master/internal/configpolicy/authz_iface.go
master/internal/configpolicy/authz_permissive.go
master/internal/configpolicy/authz_rbac.go
master/internal/db/postgres_rbac_intg_test.go
master/internal/workspace/authz_basic_impl.go
master/internal/workspace/authz_iface.go
master/internal/workspace/authz_permissive.go
master/internal/workspace/authz_rbac.go
master/static/migrations/20240917113855_modify-tcp-rbac-perms.tx.up.sql

[CM-530]
- Remove "modify globaly config policies" permission from `WorkspaceAdmin` role
- Classify global config policy permissions as `global_only`
- Add RBAC tests for config policies and refactor existing tests
- Move config policies RBAC work into the `configpolicy` package and add configpolicy-specific logging
[CM-530]: https://hpe-aiatscale.atlassian.net/browse/CM-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: refactor and test RBAC config policies work [CM-530]

---

docs/integrations/_index.rst
docs/integrations/notification/_index.rst
docs/integrations/notification/slack.rst
docs/integrations/notification/workload-alerting.rst
docs/integrations/notification/zapier.rst

Document the experimental feature: Webhooks improvement: see also #9944 
Include the use cases: https://hpe-aiatscale.atlassian.net/browse/MD-458
Support workload alerting, different webhook modes, e.g., #9865
Improve the "integrations" section.
Docs Preview
https://determined-ai-docs.s3.us-west-2.amazonaws.com/previews/360dc8f29a2910aba1e59c63cbe54db3/integrations/notification/workload-alerting.html

docs: Add workload alerting

---

e2e_tests/tests/task/test_generic_tasks.py

test is flaky, race between task going from PAUSING -> PAUSED and test check. so retry a few times.

fix: fix flaky generic task pause test

---

docs/setup-cluster/slurm/_index.rst
docs/setup-cluster/slurm/hpc-environment-requirements.rst
docs/setup-cluster/slurm/install-on-slurm.rst
docs/setup-cluster/slurm/slurm-known-issues.rst
docs/setup-cluster/slurm/slurm-requirements.rst
docs/setup-cluster/slurm/upgrade-on-hpc.rst

Docs Preview
* A customer would start here: [Deploy on Slurm PBS](https://determined-ai-docs.s3.us-west-2.amazonaws.com/previews/9b1dde2811e0cc09edc84c9c1fedded0/setup-cluster/slurm/_index.html)
* Then they would visit the [requirements](https://determined-ai-docs.s3.us-west-2.amazonaws.com/previews/9b1dde2811e0cc09edc84c9c1fedded0/setup-cluster/slurm/slurm-requirements.html)
* including [HPC Environment Requirements](https://determined-ai-docs.s3.us-west-2.amazonaws.com/previews/9b1dde2811e0cc09edc84c9c1fedded0/setup-cluster/slurm/hpc-environment-requirements.html)
Problem Domain
When there is no root access, the customer admin must complete specific steps prior to the Determined installation. These steps were not documented in our docs.
Purpose of this PR:
Update slurm pbs setup and …

docs: Add hpc installation guide

---

master/internal/rm/agentrm/summaries.go

Just fix the log to only print when there a multiple slot types assigned to one pool, ignore in the zero case. This avoids cases where pools _don't_ have any agents assigned and the logs are spammed with this error message.
N/A

chore: do not log error for resource pools with zero agents

---

webui/react/src/components/ExperimentActionDropdown.tsx
webui/react/src/components/Searches/columns.ts
webui/react/src/pages/FlatRuns/columns.ts
webui/react/src/utils/table.test.ts
webui/react/src/utils/table.ts

[ET-749]
Make sure Flat Runs feature flag is on. Go into any project with a significant number of experiments (Uncategorized is a good default choice). Perform the following steps on both the Runs and Searches tabs.
- Turn on all columns using column picker
- Check that in every cell where no data is available, there is a `-` present
[ET-749]: https://hpe-aiatscale.atlassian.net/browse/ET-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: show `-` for empty data in searches table [ET-749]

---

docs/reference/deploy/helm-config-reference.rst
docs/release-notes/helm-db-snapshot.rst
helm/charts/determined/templates/db-deployment.yaml
helm/charts/determined/templates/db-persistent-volume-claim.yaml
helm/charts/determined/templates/db-volume-snapshot-class.yaml
helm/charts/determined/templates/db-volume-snapshot.yaml
helm/charts/determined/values.yaml

CM-448
See notes: https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1748041758/Guide+Release+Party+Database+Backups
TLDR; add Helm values such that you can easily snapshot/backup OR restore a database's persistent volume.
Manual testing or N/A

feat: add database snapshot functionality to Helm chart

---

docs/release-notes/9966-fix-grid.rst
master/pkg/searcher/grid.go
master/pkg/searcher/grid_test.go

Previously, when a hyperparameter contained an emtpy "nested" hyperparameter:
hyperparameters:
empty: {}
It was lost during grid sampling, and was never passed to the trial. This is because the nested hyperparameter isn't considered its own axis for the grid search, and is only implicitly populated by being on the path of some inner hyperparameter axis.  However, when there is no inner hyperparameter axis, we need to detect that and emit a one-point axis that preserves the empty nested hyperparameter.
Another possible solution would be to convert the empty nested hyperparameter as a const hyperparameter with an empty map for a value when unmarshaling the hyperparameters yaml object.  I think no user code would be affected by which solution is used, since user code will see the same …

fix: grid hp samping ignored empty nests

---

e2e_tests/tests/cluster/test_priority_scheduler.py
e2e_tests/tests/cluster/utils.py

The default arg meant a 30(!)-second sleep.
One innocent-looking test was sitting and doing nothing for a full 90 seconds simply by omitting the default arg three times.
This is a good example of why default args are bad; this default saved somebody typing `, 0` and the cost was a test took 90 extra seconds, probably without the author even realizing it.  Better to be clear and explicit, especially with internal APIs (where compatibility and breaking changes are never a concern).

ci: remove default arg from utils.run_command()

---

webui/react/src/e2e/tests/userManagement.spec.ts

Potential fix for flaky "Deactivate and Reactive" test. 
Not reproducing failures locally, doesn't seem like this would need to be handled differently for CI. Attempting to add some assertions that are used in the similar "Bad Credentials" test, which is not flaky on CI, to see if that addresses the issue.

fix: Deactivate User test flake

---

webui/react/src/pages/Cluster.module.scss

Makes sure Cluster page, Master Logs displays logs component at full-page height.
Before:
After:

fix: Cluster page height

---

harness/determined/transformers/_hf_callback.py

With the previous [fix](https://github.com/determined-ai/determined/pull/9913/files), the training continues after getting a preemption signal. This is the actual fix.
CI passes.

fix: fix hf on_save raise exception

---

webui/react/src/e2e/tests/userManagement.spec.ts

Potential fix for flaky 'Deactivate and Reactivate' test.
Not reproducing failures locally, doesn't seem like this would need to be handled differently for CI. Trying out adding a validation step used in a similar test that's missing here, even though I'm not sure why that would lead to sign out timing out. 

fix: Reactivate User test flake

---

webui/react/src/pages/FlatRuns/columns.ts
webui/react/src/utils/table.test.ts
webui/react/src/utils/table.ts

[ET-804]
Resolves a dependency on work from ET-749 (not in release).
N/A
[ET-804]: https://hpe-aiatscale.atlassian.net/browse/ET-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: bring in handleEmptyCell from #9963

---

webui/react/playwright.config.ts
webui/react/src/e2e/models/common/hew/DataGrid.ts

ET-678
This attempts to deflake the datagrid action pause tests by increasing the rightclick timeout. I'm skeptical that this will deflake because the error message on timeout says that it's performing the click action, meaning it's already located the element and it's visible and clickable. 
In addition, we reduce the worker count by one to prevent further timeout issues stemming from the machine throttling.
No manual testing needed -- ci should be green.

ci: increase datagrid rightclick timeout/ reduce worker count

---

master/internal/api_config_policies.go
master/internal/api_config_policies_intg_test.go
master/internal/configpolicy/utils.go
master/internal/configpolicy/utils_test.go

[CM-486], [CM-492]
Implement PUT APIs for task config policies.
[CM-486]: https://hpe-aiatscale.atlassian.net/browse/CM-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CM-492]: https://hpe-aiatscale.atlassian.net/browse/CM-492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: implement PUT APIs for task config policies

---

docs/deploy/upload.py

I noticed that the `docs/deploy/upload.py` uses `time.time_ns()` on line [148](https://github.com/determined-ai/determined/blob/bc3b2a6cdbe45ad41d98507f1ea50b8bcf016d68/docs/deploy/upload.py#L148C21-L148C35) which requires an import, otherwise we are getting an exception. This PR imports this missing module.

fix: import missing time module

---

webui/react/src/hooks/useSettings.ts

[MD-521]
Reset settings is not working properly for settings without `skipUrlEncoding`.
This happens because when reseting, we didn't reset the url query, so after refresh, we read from url query and set those settings again.
Navigate to trial logs page, apply some filter, then reset filters.
Before this change, the reset button would show up again. With this change, the settings would be actually reset.
Similar behavior happens at the model registry page too.
[MD-521]: https://hpe-aiatscale.atlassian.net/browse/MD-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: …

fix: reset settings not working properly due to url encoding

---

master/internal/api_project.go
master/internal/api_runs.go
webui/react/src/pages/FlatRuns/FlatRuns.tsx
webui/react/src/pages/FlatRuns/columns.ts

ET-304
This adds the archived column to the columns api. It also updates the flat runs view to handle showing the archived state of runs and ensures the archived definition matches the show archived behavior.
When viewing the column list for the new experiment list, the searches view, and the runs view, the user should see the "archived" column in the general tab.

fix: display archived column for runs and searches

---

webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx
webui/react/src/services/apiConfig.ts

[ET-694]
Switches clients over to the correct paths after reclassifying endpoints as internal in #9933 
N/A
[ET-694]: https://hpe-aiatscale.atlassian.net/browse/ET-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: run centric api deprecated bindings (ET-694)

---

master/static/srv/generic-task-entrypoint.sh
master/static/srv/task-setup.sh

When a task's uid setting is nonzero but username is still "root", we will accidentally set the HOME directory to /root.
This happens because we start the container based on the UID, then we look up the username (uid->username lookup) and we find that we are called "root", then we do a username->HOME lookup to arrive at /root.

fix: use UID not username to set HOME dir

---

webui/react/src/e2e/tests/experimentList.spec.ts

ET-754
This adds a pagination test to the e2e experiment list test suite. We check page url parameter after interacting with the pagination element. Because the table rows are virtualized, we cannot directly check the row count based on what is in the html dom.
React-e2e tests should pass

test: add e2e experiment list pagination test

---

master/internal/api_command.go
master/internal/configpolicy/task_config_policy.go
master/internal/configpolicy/task_config_policy_intg_test.go

[CM-551]
Need to check both `resources.max_slots` and `resources.slots` when checking if a NTSC workload requests is within constraints.
Covered by automated tests.
[CM-551]: https://hpe-aiatscale.atlassian.net/browse/CM-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: check task config policies against slots and max_slots

---

webui/react/src/components/ConfigPolicies.tsx
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

CM-521
Add secondary tabs for "Experiments" and "Tasks" to "Config Policies" tab on Workspace Details page. Also made changes to 
* call delete endpoint when saving an empty document 
* Not display JSON brackets when loading with empty config policies object
* display CodeEditor in read-only mode when user does not have permissions to modify
Only in EE:
"Config Policies" tab on Workspace Details page should display secondary tabs for "Experiments" and "Tasks"
Non-admin should not see Apply button, and should see CodeEditor in read-only mode.
Admin should be able to Apply (with valid YAML syntax that modifies what's fetched).
Should be able to remove all YAML and Apply without error. …

feat: Config Policies UI, Workspaces Experiments [CM-521]

---

master/internal/webhooks/postgres_webhook.go

CM-527
There is a write under a read lock, causing the master to crash in integration tests with `fatal error: concurrent map writes`.
Change is a test fix.

fix: correct expToWebhookConfig cache locking

---

master/internal/user/postgres_users.go

[DET-10404](https://hpe-aiatscale.atlassian.net/browse/DET-10404)
[DET-10404]: https://hpe-aiatscale.atlassian.net/browse/DET-10404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Revoke Access Tokens when a User is Deactivated

---

master/internal/api_command.go
master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/api_logretention_intg_test.go
master/internal/configpolicy/task_config_policy.go
master/internal/configpolicy/task_config_policy_intg_test.go

[CM-491]
Check if experiment config passes any constraints defined in task config policies.
Covered by unit tests.
[CM-491]: https://hpe-aiatscale.atlassian.net/browse/CM-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: check experiment constraints

---

webui/react/src/components/ModelCreateModal.tsx
webui/react/src/components/ModelMoveModal.tsx
webui/react/src/components/ModelRegistry.tsx
webui/react/src/e2e/models/components/AddUsersToGroupsModal.ts
webui/react/src/e2e/models/components/ChangeUserStatusModal.ts
webui/react/src/e2e/models/components/CreateUserModal.ts
webui/react/src/e2e/models/components/ModelCreateModal.ts
webui/react/src/e2e/models/components/ModelRegistry.ts
webui/react/src/e2e/models/components/SetUserRolesModal.ts
webui/react/src/e2e/models/components/WorkspaceCreateModal.ts
webui/react/src/e2e/models/components/WorkspaceDeleteModal.ts
webui/react/src/e2e/tests/workspaceModelRegistry.spec.ts

CM-538
Adds automated e2e tests for "Workspace Models" section of Workspaces/Projects release party test plan
https://hpe-aiatscale.atlassian.net/wiki/spaces/ENGINEERIN/pages/1321238531/Workspaces+Projects
No additional testing required, automated tests should pass.

test: Workspace Models tests [CM-538]

---

webui/react/src/e2e/tests/projects.spec.ts
webui/react/src/e2e/tests/workspaceTasks.spec.ts

CM-554
Potential fixes for flaky tests
Workspace Tasks › JupyterLab
Project List › Filter
No additional release party testing required. Automated tests should pass.

fix: Workspace Projects and Tasks test flakes [CM-554]

---

e2e_tests/tests/cluster/test_agent_disable.py
e2e_tests/tests/cluster/utils.py

Before, it wasn't using the session to fetch logs.

chore: wait_for_task_state shows logs on failure

---

webui/react/src/components/ConfigPolicies.test.tsx
webui/react/src/components/ConfigPolicies.tsx
webui/react/src/components/NavigationSideBar.tsx
webui/react/src/hooks/usePermissions.ts
webui/react/src/pages/ConfigPoliciesPage.tsx
webui/react/src/routes/index.tsx
webui/react/src/routes/routes.ts
webui/react/src/routes/utils.ts
webui/react/src/services/api.ts
webui/react/src/services/apiConfig.ts
webui/react/src/services/types.ts

CM-522, CM-521
Adds page for Global Config Policies UI
Only in EE:
Should display "Config Policies" as option in Navigation Sidebar.
"Config Policies" Page should display secondary tabs for "Experiments" and "Tasks"
Non-admin should not see Apply button, and should see CodeEditor in read-only mode.
Admin should be able to Apply (with valid YAML syntax that modifies what's fetched).
Should be able to remove all YAML and Apply without error.

feat: Global Config Policies UI [CM-522]

---

master/internal/api_experiment.go
master/internal/configpolicy/postgres_task_config_policy.go
master/internal/configpolicy/postgres_task_config_policy_intg_test.go
master/internal/configpolicy/task_config_policy.go
master/internal/configpolicy/task_config_policy_intg_test.go
master/internal/core_experiment.go

[CM-494]
Implement experiment invariant config silent override when adding or updating an experiment.
[CM-494]: https://hpe-aiatscale.atlassian.net/browse/CM-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: exp invariant config silent override during add or update

---

docs/setup-cluster/checklists/postgresql.rst
docs/setup-cluster/on-prem/options/linux-packages.rst

Since pg15, you need to explicitly grant access on public schema.
I remember some people hit the same issue in older postgres versions as well when using external/custom postgres installations with special permissions.
https://determined-community.slack.com/archives/CV3MTNZ6U/p1728583301953569?thread_ts=1728510027.402639&cid=CV3MTNZ6U
N/A

docs: revise postgres permission setup instructions.

---

e2e_tests/tests/cluster/test_agent_disable.py

It turns out that k8s is just really slow sometimes.
Here's the logs from a flaky run.  Notice:
- It takes 6m38s to pull the image
- The init container takes about 20s
- There's still 3 seconds between when the container starts and when we see logs out of it
- Based on the 30 second timeout, we are capturing these logs about 10 seconds after the `sleep 180` has started, and there's nothing in the logs that suggests the pod is dead or anything
So yeah, k8s is just slow sometimes I guess.
```
tests/cluster/test_agent_disable.py::test_disable_agent_zero_slots starting at 2024-10-10 14:29:12
== begin task logs ==
[2024-10-10T14:29:14.845359Z]          || INFO: Scheduling Command (formally-humorous-moray) (id: a75c28dc-c993-4a85-8641-9b1a1effeb7a.1)
[2024-10-10T14:29:15.000000Z] a75c28dc || …
```

ci: deflake test_disable_agent_zero_slots

---

master/internal/command/command.go
master/internal/command/command_intg_test.go

CM-562
Add a constraint check to a stray priority change API.
TBD.

chore: check config policies on 'det notebook set priority'

---

master/internal/api_experiment.go

No ticket.
Stray change from [#10019](https://github.com/determined-ai/determined/pull/10019). 
CI passes

chore: change error code back

---

master/internal/experiment.go
master/internal/experiment_job_service.go

CM-564
Pushing this check down a level makes sure it applies for `PATCH /api/v1/experiments/:id` calls, too.
TBD.

fix: apply config policy constraints to PATCH /experiments/:id

---

master/internal/configpolicy/task_config_policy_intg_test.go

[CM-571]
fix slices and maps merge test. Change slice equality check method
CI passes.
[CM-571]: https://hpe-aiatscale.atlassian.net/browse/CM-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: fix slices and maps merge test

---

master/internal/api_config_policies_intg_test.go
master/internal/configpolicy/task_config_policy.go
master/internal/configpolicy/utils.go
master/internal/configpolicy/utils_test.go

[CM-569]
Experiment config slots to comply with constraint max slots. 
CI Passes.
[CM-569]: https://hpe-aiatscale.atlassian.net/browse/CM-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: experiment config slots to comply with constraint max slots

---

e2e_tests/tests/cluster/test_config_policies.py
e2e_tests/tests/fixtures/config_policies/ntscvalid.yaml
master/internal/api_config_policies_intg_test.go
master/internal/configpolicy/utils.go

[CM-559]
Returns an error if admins set invariant config for NTSC. Also fixes some nil pointer issues and refines error message when there's a conflict between global and workspace config policies.
[CM-559]: https://hpe-aiatscale.atlassian.net/browse/CM-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: ntsc config not supported

---

docs/setup-cluster/slurm/singularity.rst
docs/tools/cli/commands-and-shells.rst

eng-det-oncall-support 3 Oct 2024
The issue described revolves around where the user is trying to run a Determined AI shell with Singularity/Apptainer to perform interactive inference tasks. How Singularity/Apptainer handles home directories and file bindings, differs from how Docker containers might handle similar configurations. The files are actually copied to directories including  /run/determined/workdir (which is where we should point users), but because of the automatic home directory binding, the user is placed in their home directory upon shell launch, which might be confusing. 
Outside of /run/determined/workdir the users should not use anything in /run/determined.

Docs: describe data files apptainer

---

master/internal/configpolicy/task_config_policy.go

CM-572
Fix a call to `cfg.Resources().Priority()` on an experiment config without `schemas.WithDefaults`. I didn't call with defaults because the config is intentionally incomplete (we need to know what the user set, without any defaulting).
Manually tested.

fix: nil deref in usage of incomplete experiment config policies

---

master/internal/api_experiment.go
master/internal/experiment.go

CM-540
Unfortunately we can't be clever about skipping checkpoint GC since there still may be tensorboard files.
Tested manually and left a comment so this change isn't undone.

fix: run checkpoint GC more aggressively to ensure tensorboards are GC'd

---

docs/manage/security/rbac.rst
docs/release-notes/rbac-new-tokenCreator-role.rst
master/static/migrations/20241010175001_add-access-token-rbac-permissions.tx.up.sql

chore: create `TokenCreator` role with permissions to VIEW / CREATE / REVOKE own access tokens

---

master/internal/api_trials.go
master/internal/rm/agentrm/agent_resource_manager.go
master/internal/rm/dispatcherrm/dispatcher_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/multirm/multirm.go
master/internal/rm/multirm/multirm_intg_test.go
master/internal/rm/resource_manager_iface.go

The `ExternalPreemptionPending` method always essentially called `allocation.Signal`, but through 2/3 pointless other calls/message passes. This just cuts out a few middlemen.
I did it now because it stood in the way of a test @rb-determined-ai was trying to remove.
This is code removal, needs no testing. It even swaps to tested code instead!

chore: remove redundant rm.ExternalPreemptionPending interface

---

.circleci/real_config.yml

INFENG-922
This changeset fixes a tag/label value in the CircleCI config; `gh_team: machine-user` should be `gh_team: machine-users` (plural). This fixes some inconsistencies in cost tracking.
Probably unnecessary, although getting the `test-e2e-hpc-gcp` job to run would guarantee that the correct label is being applied. But unless label application isn't working at all, this only updates the value that's already being set.

chore: INFENG-922: use correct gh_team tag for infrastructure

---

master/internal/api_tensorboard.go

I think this was just missed in: https://github.com/determined-ai/determined/pull/8700
- Fix nil map.
- Launch a Tensorboard on a unified install.

fix: Tensorboard broken on unified install [CM-578]

---

docs/reference/training/_index.rst
docs/reference/training/api-transformers-reference.rst
harness/determined/transformers/_hf_callback.py

The det.transformers.DetCallback chose to only work on-cluster, and
derived much of its behavior by directly inspecting ClusterInfo.
It also enforced that the user provided a transformers-style training
length which matched the searcher max_length.
And it didn't bother respecting min_validation_period or
min_checkpoint_period, or really any other training loop detail found in
the experiment config.
The end result is that with absolutely no API changes, we can actually
move to the searcher-context-removal paradigm with almost no breakages
whatsoever.
The only case that would break is if the user was _relying_ on the
asha searcher to tell the huggingface Trainer when to checkpoint.  Our
system is overall not supporting that behavior anymore, so if that
breaks it is unavoidable.

chore: remove searcher context from DetCallback

---

harness/determined/cli/token.py

In the event that `expiration_days` isn't provided, this corrects the missed declaration of the `expiration_in_hours` variable.
- `det token create` successfully creates a token

fix: correct token creation CLI to ensure it works with default expiry

---

master/internal/api_config_policies.go
master/internal/configpolicy/postgres_task_config_policy.go
master/internal/configpolicy/utils.go
master/internal/configpolicy/utils_test.go

[CM-575]
Return error if workspace invariant config violates global constraints
CI passes (automated testing)
[CM-575]: https://hpe-aiatscale.atlassian.net/browse/CM-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: return error if workspace config violates global constraints

---

.circleci/config.yml
version.sh

INFENG-926
This fixes a bug in version.sh that would cause an invalid local version string to be output under certain circumstances; specifically, if a tag were made on a commit that was not on the current branch (i.e. reachable with git-describe). This took a code path in version.sh that did not properly remove any existing tag +metadata with grep, leading to version strings like 0.751.0+dryrun+27a014b44. Note the extra plus sign (+). This causes downstream tools, like helm, to fail.
Now, we remove any existing version metadata from the final for all code paths.
This also changes all instances of `\d` character classes to `[0-9]`. This fixes a cross-platform issue where BSD grep's `-E` includes `\d` classes, while GNU grep's `-E` does not. This means the script worked fine on macOS, but …

build: INFENG-926: Fix version.sh version string output

---

webui/react/src/pages/TrialDetails/LogViewer.tsx
webui/react/src/pages/TrialDetails/TrialDetailsLogs.module.scss
webui/react/src/pages/TrialDetails/TrialDetailsLogs.tsx

[MD-529]
Address comments from log search bug bash. 
- Search pane and log pane have the same font size.
- Search and click the last line of log, the log viewer window should be able to scroll to that location.
- Holding the backspace to erase search text should work as expected.
- Select a log that's right after a very long log (experiment config), when closing the search pane, the selected log should still be positioned at the top. (This only happens for the first time when user close the search pane).
- When regex is not enabled, the search should be case-insensitive.
- Search for something and change filters such as agent id or container id, both search pane and log pane should update accordingly.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release-n …

fix: Log searche feedbacks

---

docs/manage/security/_index.rst
docs/manage/security/access-tokens.rst
docs/manage/security/auto-posix.rst
docs/manage/security/rbac.rst
docs/manage/users-remote.rst

replaces #10108 (materially the same)
Describe two new features: 
- Allow auto POSIX linking if agent_uid, agent_gid, agent_user or agent_group are provided in the OIDC or SAML claims
- Allow users to create long lived tokens that they can use for authentication
Related
- https://hpe-aiatscale.atlassian.net/browse/DET-10383 
Checklist

docs: Describe sso improvements

---

webui/react/src/pages/ExperimentDetails/ExperimentDetailsHeader.tsx
webui/react/src/pages/TrialDetails/Header/TrialHeaderLeft.tsx

ET-837
This updates the experiment header and the trial header to have correct copy when `f_flat_runs` is on.
with f_flat_runs on, visit a trial page
* the experiment header should have the experiment id as `search id_number`
* the trial header should have the trial id as `run id_number`

fix: update copy in experiment and trial headers

---

docs/setup-cluster/k8s/setup-multiple-resource-managers.rst

Fix a bad link markup.
Look at multi-rm docs page.

docs: fix internal link in multi-rm docs page.

---

master/internal/configpolicy/task_config_policy.go
master/internal/configpolicy/task_config_policy_intg_test.go
master/internal/core_experiment.go

[CM-584]
Admins can set global and workspace invariant experiment config policies containing config fields that are "incomplete" (they fail our [completeness validator](https://github.com/determined-ai/determined/blob/main/master/pkg/schemas/schema.go#L42) ).
However, users can also submit such incomplete configs when launching experiments, and these configs get populated with pre-defined [defaults](https://github.com/determined-ai/determined/blob/main/master/pkg/schemas/zgen_schemas.go).
Populate the final config with defaults after merging with the workspace and global invariant config (so that invariant config fields are also populated with defaults after overriding/merging is complete).
CI passes (automated testing)
See [Release …

chore: populate final merged config with defaults when merging invariant configs

---

master/static/migrations/20241023165301_system-metrics-on-del-casc.tx.up.sql

[MD-530]
Fix an issue preventing deleting experiment with profiling enabled.
Create an experiment with profiling, one example is to change `determined/examples/tutorials/mnist_pytorch/train.py` to add `profiling_enabled`:
```
trainer.fit(max_length=max_length, latest_checkpoint=latest_checkpoint, profiling_enabled=True)
```
Verify that "Profiler" tab for that experiment in the Web UI exists with value.
Delete the experiment, the experiment should eventually disappear with no error. 
[MD-530]: https://hpe-aiatscale.atlassian.net/browse/MD-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DET-123]: …

fix: Add on delete cascade to system_metrics

---

master/internal/api_config_policies.go
master/internal/api_config_policies_intg_test.go

CM-556
Some of the APIs return a status, e.g. status.Errorf(codes.InvalidArgument, errMessage) and some return a simple error, e.g. fmt.Errorf("error parsing config policies: %w", err). Review the task config policy APIs and ensure we are returning a status code in exported/able functions.
N/A -- make sure e2e tests pass

chore: standardize status api errors for task config policies

---

docs/reference/deploy/helm-config-reference.rst

[CM-582]
Clarify version overrides (`detVersion` in `values.yaml` overrides appVersion in `Chart.yaml` and `--version` in `helm install` and `helm upgrade` commands) during helm installs in our [helm configuration reference docs](https://docs.determined.ai/latest/reference/deploy/helm-config-reference.html)
[CM-582]: https://hpe-aiatscale.atlassian.net/browse/CM-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: clarify version overrides during helm installs

---

docs/manage/config-policies.rst
docs/reference/cli-reference.rst
harness/determined/cli/config_policies.py

CM-480
- Add config policies to CLI reference docs
- give `det config-policies` shorthand name `det cp`
- clarify in the config-policies help messages that policies are applied globally when `--workspace-name` flag is unspecified 

chore: add config policies to CLI reference docs

---

docs/reference/experiment-config-reference.rst

restore experiment configuration file content
original #10098

docs: log policies restore exp config

---

docs/setup-cluster/aws/aws-spot.rst
docs/setup-cluster/aws/install-on-aws.rst
docs/setup-cluster/checklists/postgresql.rst
docs/setup-cluster/on-prem/options/docker.rst
docs/setup-cluster/on-prem/options/linux-packages.rst
docs/setup-cluster/slurm/hpc-environment-requirements.rst

Update instances of "postgresql <14", add note about Aurora v1

docs: Update postgres aurora info

---

master/internal/configpolicy/task_config_policy_intg_test.go

The `reproducibility.experiment_seed` field of the `expconf.ReproducibilityConfig` is automatically populated with `time.Now().Unix()` in the [WithDefaults](https://github.com/determined-ai/determined/blob/main/master/pkg/schemas/expconf/experiment_config.go#L365) pseudointerface implementation. Sometimes, this time is identical for the expected and actual final structs, but other times it's not.
Explicity set this field so that it isn't auto-defaulted to the new current timestamp.
CI passes.

chore: fix merge exp flake

---

master/internal/api_token.go

[DET-10469](https://hpe-aiatscale.atlassian.net/browse/DET-10469)
Reducing the scope of SSO improvement project to EE Only.
`det token create` should work on ee but not oss.
[DET-10469]: https://hpe-aiatscale.atlassian.net/browse/DET-10469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: SSO improvement feature requires Enterprise Edition.

---

docs/release-notes/unsupport-aurora-postgres-reminder.rst

We didn't yet have a release note about the EOL for Aurora v1 and Postgres <14 so I created one.
Related: #10116

docs: Add aurora postgres release note

---

master/internal/api_user_intg_test.go

Add test for filtering user by Role id.
Migration of this [PR](https://github.com/determined-ai/determined-ee/pull/1062)
CI pass.

test: Add test for filtering user by Role Id

---

harness/determined/keras/_tf_keras_trial.py

All of our other training loops now emit this, and asha searches depend on it.

chore: add batches and epochs to TFKerasTrial metrics

---

.circleci/real_config.yml

404
Bump the version we use for Go builds to 1.22.8. I made a note to follow up with a PR that gets the latest Go release for a given minor version instead of pinning to a patch version next week when I have time.
Basically covered by all tests.

chore: bump Go version used by CI builds to 1.22.8

---

examples/deepspeed/dcgan/README.md
examples/deepspeed/dcgan/data.py
examples/deepspeed/dcgan/ds_config.json
examples/deepspeed/dcgan/gan_model.py
examples/deepspeed/dcgan/mnist.yaml
examples/deepspeed/dcgan/model.py
examples/deepspeed/dcgan/trainer.py
examples/deepspeed/gpt_neox/det_utils.py
harness/determined/exec/harness.py
harness/determined/pytorch/__init__.py
harness/determined/pytorch/_pytorch_trial.py
harness/determined/pytorch/_trainer_utils.py
harness/determined/pytorch/deepspeed/__init__.py
harness/determined/pytorch/deepspeed/_deepspeed_context.py
harness/determined/pytorch/deepspeed/_deepspeed_trial.py
harness/determined/pytorch/deepspeed/_trainer.py
harness/tests/experiment/fixtures/deepspeed_linear_model.py
harness/tests/experiment/integrations/test_deepspeed_trial.py

https://hpe-aiatscale.atlassian.net/browse/MD-501
Add Deepspeed Trainer API
Refactor some pytorch training classes
Reinstate DCGANTrial as an example of DeepSpeed Trainer
1. Try DCGAN trainer example. Instructions are in the `README` included with `tests/deepspeed/dcgan`. After it's done, continue the run for 100 more batches.
2. Run GPT NEOX example. After it's done, continue the run for 100 more batches.
3. Deepspeed unit tests pass.

feat: Deepspeed Trainer

---

.circleci/devcluster/multi-k8s.devcluster.yaml
.circleci/devcluster/single-k8s.devcluster.yaml
docs/release-notes/add-host-port-scheme-to-helm.rst
docs/setup-cluster/k8s/setup-multiple-resource-managers.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/cmd/determined-master/root.go
master/cmd/determined-master/root_test.go
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/job.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go
tools/k8s/devcluster.yaml
tools/k8s/multicluster.yaml
tools/k8s/remote_connect.py

DFR-530 / DFR-529
When `determined_master_ip` is unsettable via Helm and defaults to the service IP, life with proxies is hard. This change renames `determined_master_ip` to `determined_master_host` everywhere with some backwards compatibility, defaults `determined_master_host` to `<det_namespace>.<det_service_name>.svc.cluster.local`, and makes all of this overridable in Helm.

chore: determined_master_host and friends helm support, better defaults

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/configpolicy/postgres_task_config_policy.go
master/internal/configpolicy/postgres_task_config_policy_intg_test.go
master/internal/configpolicy/utils.go
master/internal/configpolicy/utils_test.go
master/internal/experiment.go

[CM-583]
add checkpoint and max slots config policy enforcements in PATCH experiment
CI passes.
[CM-583]: https://hpe-aiatscale.atlassian.net/browse/CM-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add checkpoint and max slots config policy enforcements in PATCH experiment

---

e2e_tests/tests/experiment/test_core.py

previously test expected one checkpoint per trial in experiment. with new asha trials may have more than one checkpoint. so we compare all.

fix asha e2e test

---

.circleci/real_config.yml

INFENG-938
Restore previous version tag format, which places a hyphen '-' between the patch revision part and the remainder of the version string. So, for example, instead of a string like v0.38.0rc3, we will look for v0.38.0-rc3. The former is not SemVer-compliant, whereas the latteris.
This fixes an issue where Helm breaks when using release candidate versions, because it expects the string to be SemVer-compliant. Setuptools, by contrast, can munge the hyphenated version into a more canonical PEP 440-compliant format, so we prefer the new SemVer-compliant format instead.
Using your favorite regex tool of choice, verify that the new regular expressions match new rc version strings, like `v0.38.0-rc3`.
See [Release Note](https://github.com/determined-ai/determined/blob/master/docs/release- …

build: INFENG-938: Tweak version string format

---

.circleci/real_config.yml
helm/Makefile

INFENG-937
This changeset adds a Helm makefile target and CircleCI job to publish release candidate Determined Helm charts. This is necessary to deploy release candidates onto the new GKE cluster.
Previously, bumpversion would increment the rc version of the Helm chart, then commit this to the release branch (along with other similar version bumps). `rph` would then use this in-tree version of the Helm chart to upgrade the Helm release on the (old/existing) release party GKE cluster. Because we aren't managing versions on disk anymore, though, we need to install the Helm chart from somewhere else, which means we have to publish it somewhere in the first place for ArgoCD to find. This is more consistent anyway; we already publish Python package release candidates, for example.
We already …

build: INFENG-937: Publish Helm chart release candidates

---

.circleci/real_config.yml

INFENG-940
Reverse the polarity of the CircleCI `make-component` job so it obeys the `dryrun` boolean variable properly, otherwise it will work the opposite way.
Obverse the if statement and make sure it's correct.

build: INFENG-940: Fix logic error in CircleCI config make-component job

---

agent/Makefile
helm/Makefile
master/Makefile

INFENG-938
Add an optional `v` in the grep regular expression that computes previous version tags in GoReleaser Makefile targets for master, agent, and helm. This ensures continuity between the previous tag format, which used bare version strings, and the new tag format, all of which begin with a literal `v`. Otherwise, when trying to derive a previous tag that begins with a `v`, the grep would fail.
Note that things would still otherwise work fine for the next release, because previous tags would still satisfy the format. Subsequent releases, however, would be incorrect, because the tag would begin with a `v` and thus not match. `GORELEASER_PREVIOUS_TAG` is used for determining which release notes to include, and having it set incorrectly would cause problems for the GitHub release. …

build: INFENG-938: Update version format in Makefiles

---

.circleci/real_config.yml

INFENG-942
The release job is skipping the React build step because there are two jobs that attempt to skip the entire job if no changes are detected in specific directories. Previously, bumpversion made it so that, by dint of updating various files, the job would not be skipped. Now that we aren't using it, though, certain downstream jobs are failing because React wasn't built.
To fix this, I've added a "force" variable to the build-react job, to allow conditionally bypassing the checks if indicated by the caller. This preserves existing behavior, to avoid potentially other unintended consequences of beginning to build React everywhere, but also to avoid running up CircleCI compute bills, as this much extra build time would probably have a material effect on spending.
Given that it's a …

build: INFENG-942: Conditionally bypass build-react job checks

---

.circleci/devcluster/multi-k8s.devcluster.yaml
.circleci/devcluster/single-k8s.devcluster.yaml
docs/release-notes/add-host-port-scheme-to-helm.rst
docs/setup-cluster/k8s/setup-multiple-resource-managers.rst
helm/charts/determined/templates/master-config.yaml
helm/charts/determined/values.yaml
master/cmd/determined-master/root.go
master/cmd/determined-master/root_test.go
master/internal/config/resource_manager_config.go
master/internal/rm/kubernetesrm/job.go
master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/spec.go
master/internal/rm/kubernetesrm/spec_test.go
tools/k8s/devcluster.yaml
tools/k8s/multicluster.yaml
tools/k8s/remote_connect.py

…rt, better defaults" (#10134)"
This reverts commit 782f7a09fcd4699a00d87c74c838a1a01af3fdd7.
DFR-529/530
When `determined_master_ip` is unsettable via Helm and defaults to the service IP, life with proxies is hard. This change renames `determined_master_ip` to `determined_master_host` everywhere with some backwards compatibility, defaults `determined_master_host` to `<det_namespace>.<det_service_name>.svc.cluster.local`, and makes all of this overridable in Helm.
Reverted this, re-landing, had an embarrassing typo that broke everything.
Has automated tests, that's why I knew to revert.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTlj …

feat: determined_master_host and friends helm support, better defaults

---

helm/.goreleaser.yml
helm/.goreleaser_ee.yml

INFENG-943
Set `prerelease: auto` in both Helm GoReleaser configs. GoReleaser will make intelligent decisions based on the tag and avoid setting release candidate Helm chart releases as "latest".
I'm not sure how this plays with the [make_latest](https://goreleaser.com/customization/release/?h=make_latest#github) option, which also exists and is set to `true` by default, but marking a release as a pre-release (in GitHub) also turns off the "latest" flag, so I guess we'll see.
We'll have to do it live.

build: INFENG-943: GoReleaser configure prerelease

---

webui/react/src/components/MultiSortMenu.tsx
webui/react/src/e2e/tests/experimentList.spec.ts

ET-828
this updates the experiment list e2e multi sort test:
1) the test could flake if the table was comparing numeric values lower than 10 with numeric values larger than 10.
2) the test helper now handles both the setup and scenario steps, allowing for more levels of sorting.
the multi sort menu is also updated to output the values of the direction selector to the dom to allow selections during the e2e tests that don't need to be aware of the column copy.
react e2e tests should pass. will run back-to-back test suites on circleci to validate non-flakiness.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

test: make explist e2e sort test more reliable

---

master/internal/api_model.go

[ET-842]
More accurate error message for model names
- Make sure when user create a model with an identical name, the error message should be `avoid names equal to other models (case-sensitive)` instead of  `case-insensitive`
[ET-842]: https://hpe-aiatscale.atlassian.net/browse/ET-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: error message fix for duplicate model name

---

docs/manage/config-policies.rst

docs: checkpoint storage note for config policies

---

examples/computer_vision/iris_tf_keras/adaptive.yaml

keras's metrics.categorical_accuracy is `categorical_accuracy`, not `val_categorical_accuracy`

fix: fix iris example to use reported metric name

---

harness/determined/deploy/aws/aws.py
harness/determined/deploy/aws/cli.py
harness/determined/deploy/aws/constants.py
harness/determined/deploy/aws/deployment_types/simple.py

[CM-415]
**BREAKING CHANGE**
DRAFT PR, this still needs to have the logic wired through to detect the case where:
- det deploy aws up is called w/o specifying the deployment type
- & that deployment type does not match the label on the stack being upgraded
- -> then, we need to give them a link to the one pager & tell them to explicitly specify the deployment type (ideally as `simple-rds`)
1. Create a Simple cluster using `det deploy aws` **ON AN OLDER VERSION OF DETERMINED**
2. Add some data to the cluster, like some users and experiments (you'll look for this stuff later, so make it memorable)
3. Check out the release candidate then use det deploy to upgrade to the new version. This should fail and print a link to [the migration …

chore: change det deploy aws's default deployment type to simple-rds

---

.circleci/real_config.yml

We removed `--deployment-type=simple` because Aurora V1 is going away, so these deployments need to move to RDS. My idea is to rename these deployments so CFN will be happy then manually run the migration guide to restore DB state on the new clusters. Alternatively, we can just lose the state but that kinda sucks.
N / A

fix: swap latest main and preview clusters to RDS

---

master/internal/api_experiment.go
master/internal/api_experiment_intg_test.go
master/internal/configpolicy/postgres_task_config_policy.go
master/internal/configpolicy/postgres_task_config_policy_intg_test.go
master/internal/configpolicy/utils.go
master/internal/configpolicy/utils_test.go
master/internal/experiment.go

CM-590
This PR fixes a couple of issues:
- `det e set max-slots` to comply with invariant config and constraints
- `det e set gc-policy` to comply with invariant configs

fix: set max slots and checkpoint gc policy should comply with config policies

---

webui/react/src/components/Searches/Searches.tsx
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx

ET-843
This fixes an issue where the archived columns were available to filter on even though boolean columns aren't valid for searches. when used in a search, the search would fail with a 500 error.
when viewing the searches or experiments for a project, the user should not be able to see or select the "archived" column in the filter menu.

fix: ban archive columns in filter for experiment/search search

---

harness/determined/experimental/client.py

client.login() controls a singleton, and throws an error if you try to login twice.
But if you wanted to logout() and log back in again, that seems like it should be allowed.
An OSS user hit this issue with a script that was meant to run for weeks, where multiple logout() and login() calls avoided dealing with the TTL of our sessions.
- call `client.login()`
- call `client.logout()`
- call `client.login()` again; it should not puke

fix: client.logout() re-enables client.login()

---

.github/workflows/backport.yaml

In the auto-backport ticket, ignore `test-e2e-longrunning` tests so the PR will auto-merge
I tested manually on my own forked repo

chore: ignore test_e2e_longrunning tests when merging auto-backports

---

docs/release-notes/pytorch-tensorboard-plugin.rst

Pytorch Profiler TensorBoard Plugin is not compatible with our latest environment image, because it has been [deprecated](https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html#use-tensorboard-to-view-results-and-analyze-model-performance) by PyTorch. Add it to the known issue.

docs: known issue of tb_plugin

---

docs/model-dev-guide/api-guides/apis-howto/api-core-ug.rst
docs/model-dev-guide/create-experiment.rst
docs/model-dev-guide/debug-models.rst
examples/computer_vision/iris_tf_keras/train.py
examples/deepspeed/dcgan/data.py
examples/deepspeed/dcgan/model.py
examples/diffusion/textual_inversion_stable_diffusion/detsd/trainer.py
examples/tutorials/core_api_pytorch_mnist/adaptive.yaml
examples/tutorials/core_api_pytorch_mnist/distributed.yaml
examples/tutorials/core_api_pytorch_mnist/model_def_adaptive.py

The model debugging guide was completely out-of-date, and needed a near-total rewrite.
Additionally, the Core API user guide had additional details that needed updating, which I missed in my first pass.
Also, there were issues with two examples:
- the iris example was not configured to train long enough to actually converge, which looks bad for an example
- The core_api_mnist_pytorch example had a couple show-stopper bugs, so not all of its stages ran at all.
Finally, several examples touched in the searcher-context-removal project needed `make fmt` applied to them.

docs: update docs for non-Trial-centric world

---

webui/react/src/types.ts
webui/react/src/utils/experiment.ts

fix: include max_length in continue expconf

---

docs/model-dev-guide/api-guides/apis-howto/deepspeed/deepspeed.rst
docs/model-dev-guide/api-guides/apis-howto/deepspeed/pytorch2deepspeed.rst
docs/reference/deploy/helm-config-reference.rst
docs/reference/experiment-config-reference.rst
docs/reference/training/api-deepspeed-reference.rst
docs/reference/training/api-pytorch-reference.rst
docs/release-notes/searcher-context-removal.rst
examples/deepspeed/dcgan/README.md
examples/deepspeed/dcgan/model.py
harness/determined/pytorch/_trainer_utils.py
harness/determined/pytorch/deepspeed/_deepspeed_context.py
harness/determined/pytorch/deepspeed/_trainer.py
master/pkg/searcher/searcher.go

a few docs updates from searcher context removal.

docs: docs changes for searcher context removal

---

performance/daist/daist/rest_api/tasks.py

Deprecating searcher context eliminated this API, so we can just take it out of performance tests.
We should see the failure rate go back to 0 in performance tests.

ci: take removed API out of performance tests

---

webui/react/src/components/HyperparameterSearchModal.tsx
webui/react/src/stores/cluster.tsx

Addressing the bug described here: https://hpe-aiatscale.slack.com/archives/CLCE8D998/p1730317938890049
Avoids erroneously dividing by Infinity and returning "0%" as the value for `clusterStatus`. 
(Should be 26+0/40+0 = 26/40 instead of 26+0/40+Infinity = 0).
Also will make `SlotAllocationBar` show "0/0" instead of "0/Infinity".
Could cause divide-by-zero errors anywhere a number is divided by the result of `maxPoolSlotCapacity`, but it looks like we're guarding against those anyway and it seems like a preferable error compared to this one.
[DET-123]: https://hpe-aiatscale.atlassian.net/browse/DET-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

fix: maxPoolSlotCapacity bug

---

webui/react/src/components/LoadableCount.test.tsx
webui/react/src/components/LoadableCount.tsx
webui/react/src/components/Searches/Searches.tsx
webui/react/src/components/TableActionBar.tsx
webui/react/src/e2e/models/components/TableActionBar.ts
webui/react/src/e2e/tests/experimentList.spec.ts
webui/react/src/pages/F_ExpList/F_ExperimentList.tsx
webui/react/src/pages/FlatRuns/FlatRuns.tsx

ET-844
this changes the select all logic. previously the select all prompt would appear when selecting more than the page limit's worth of objects across the result set. if the selected count equaled the total rows in the result set, the clear selection prompt would appear. now, the select all prompt appears when the selection includes all visible rows in the result set, but the selection is not the entire result set. if the selection otherwise exceeds the page limit, we show the clear selection prompt.
this fixes the select all prompt appearing when selecting single rows across pages, as well as the select all prompt not appearing when selecting all rows on the last page of results that does not hit the page limit. there was also an issue where, for searches and experiments, the select …

fix: cover select all edge cases

---

master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/jobs_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go

change burst and qps
print
list jobs performance improvement
updates from brad

fix: perf issue with too many API reqs when listing pods in all ns

---

.gitattributes

I think I shouldn't have disabled merge on these. https://github.com/determined-ai/redacted/pull/262#issue-2566638197
>have you seen your PRs getting blocked by: "merge conflict on openapi31.json" files? with the flag we have in git attributes and how it's a single line we've disabled git from automatically attempting to merge these files this changes that
> reduce git merge conflicts by remove the -merge flag and saving the oapi spec as multiline text file.
https://git-scm.com/docs/gitattributes

chore: enable merge flag for generated bindings

---

e2e_tests/tests/cluster/test_master_restart.py
master/internal/trial.go
master/internal/trial_intg_test.go

This PR causes issues where experiments that run a searcher then expect to save a checkpoint are thwarted by the master simply stopping the experiment before that happens.

fix: revert: fix: resolve indefinitely queued (STOPPING_COMPLETED) trials

---

master/internal/api_token.go
master/internal/license/license.go

chore: fix license check

---

master/internal/rm/kubernetesrm/jobs.go
master/internal/rm/kubernetesrm/jobs_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go

Cherry picked the k8s performance fix into 
Manually test k8s flows in release party

fix: port k8s perf fix

---

master/internal/rm/kubernetesrm/jobs_test.go
master/internal/rm/kubernetesrm/kubernetes_resource_manager_intg_test.go

Some tests weren't passing but I didn't wanna block cutting the RC or manual testing. This should fix the k8s tests that weren't passing.
None; automated test changes only

fix: make some k8s tests pass

---

harness/Makefile

No longer needed
Will just re-run the build

chore: eliminate use of fury repo

---

.circleci/real_config.yml

DT-5
CI failed because the build was attempted on the master branch of the Apex repo. For reliability, it needs to be built on the latest release instead.

ci: fix apex installation [DT-5]

---

.circleci/real_config.yml

Remove the CI jobs that deploy/update clusters:
* latest-main cluster
* Netlify preview cluster

ci: remove deploying latest main and preview clusters

---

.circleci/real_config.yml

Remove deploying/updating latest GKE cluster in CI.

ci: remove deploying latest gke cluster

---

docs/conf.py
docs/reference/deploy/helm-config-reference.rst
docs/reference/deploy/master-config-reference.rst
docs/reference/experiment-config-reference.rst
docs/setup-cluster/mldes/_index.rst

Add an obsolete notice to the `deploying via MLDE managed service` page.
Add the links in `deploying via MLDE managed service` to the linkcheck ignore list.
Update Google Cloud links.
CI passes.

docs: add warning to the obsolete docs and update links

---

helm/.goreleaser.yml
helm/.goreleaser_dryrun.yml
helm/.goreleaser_ee.yml
helm/.goreleaser_ee_dryrun.yml
helm/.goreleaser_rc.yml
helm/Makefile

* Fix [CI job](https://app.circleci.com/pipelines/github/determined-ai/determined/63448/workflows/80c41a1b-507c-43ac-868f-26e396ec4f7d/jobs/3149726) `publish-helm-gh-rc`.
* Label release candidate as `draft` instead of `pre-release`. RC is not intended for user to use. Repo viewer will not be able to see it when it is labeled as `draft`. Taking one step back , why do we publish rc with helm chart as an asset? There is [a Github action](https://github.com/determined-ai/determined/blob/1284914424830afcb551f69f1c95ff92f71735ee/.github/workflows/publish-helm.yml) called `publish helm chart` publishes it to the helm repo at helm.determined.ai. So ArgoCD can find it and upgrade the release party cluster. For more context, check out: https://github.com/determined-ai/determined/pull/10141
* Run …

ci: fix incorrect field key in the goreleaser and rc label

---

.github/workflows/publish-helm.yml

We had labeled release candidates (RCs) as pre-releases, which cluttered the repo's release page. It's not easy to find the final version. To address this, RCs are labeled as drafts. This commit allows the Github Action `publish-helm` trigger by RC and upload RC helm chart to the helm repo.
Relevent Github webhook event doc: https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=created#release

ci: allow release candidate triggers helm chart upload
